### ISSUE TITLE
getting error message

### ISSUE THREAD

**Issue by mgbtcfv** [zcash/zcash#1006]
I am getting the following message while trying to download form git:

Updating testnet3 symlinks to regtest parameters.
Verifying parameter file integrity via sha256sum...
regtest/z4-proving.key: FAILED
testnet3/z4-proving.key: FAILED
regtest/z4-verification.key: OK
testnet3/z4-verification.key: OK
shasum: WARNING: 2 computed checksums did NOT match
mg-XPS-13-9343% 

Does anyone know what this means?

**Comment by ebfull** [comment]
Weird.

```
rm ~/.zcash-params/regtest/z4-proving.key
rm ~/.zcash-params/testnet3/z4-proving.key
```

and try ``./zcutil/fetch-params.sh`` again.

**Comment by mgbtcfv** [comment]
Thank you! That worked!

On Wed, Jun 8, 2016 at 5:04 PM, ebfull <notifications@github.com> wrote:

> Weird.
>
> rm ~/.zcash-params/regtest/z4-proving.key
> rm ~/.zcash-params/testnet3/z4-proving.key
>
> and try ./zcutil/fetch-params.sh again.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/zcash/zcash/issues/1006#issuecomment-224743890>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AMkeCdKBrY1_SvtKEQnU9RUQRKWKlTZ6ks5qJzxfgaJpZM4IxXsq>
> .
>



-- 
Michael Gucci, MD
