### ISSUE TITLE
Require coinbase value to be protected.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#101]
**Rationale**

If all coinbase values (which encode the non-transaction subsidy/reward for mining) are required to go through a Mint, then all value in Zerocash is born with privacy and someone along the line of transfers must explicitly opt-in to revealing some balance as public.

By contrast, by keeping coinbase transactions and Zerocash mechanisms completely decoupled, someone must opt-in to a Mint sometime after a miner receives a public reward.

The systemic difference between these two may be large and notable. If privacy is opt-in, and a social precendent arises that only bad people hide their holdings, then the anonymity set may dwindle to nothing, and without a concerted bootstrap effort it cannot recover. If, OTOH, all mined currency (as well as premine reward and any other monetary base source) is private-by-default, then the anonymity set is large and grows *by default*.

**Implementation Trade-offs**

As a practical difference, requiring a miner to compute Mints may be inconvenient to the miner or receipients interacting with a miner.  Keep in mind that depending on how this ticket's rule is enforced, there are different trade-offs.

**A First-Pass Implementation - Require CoinBase TxIn to also be a Mint**

A first-pass implementation based off of the current design would be to modify the definition of ``CTransaction::IsCoinBase()`` to add an additional constraint. The current constraint is that the transaction contains only a single ``CTxIn`` with a null ``prevout``. Adding the constraint that this single ``CTxIn`` must also include the special-case ``scriptSig`` which represents a Mint would enforce the rule.  This would also require the verification of ``Mint`` to have two cases to distinguish Minting value coming from a normal TxOut or "ex nihilo" as a coinbase mining reward.

This implementation requires a miner to perform a Mint for inclusion in every block! I believe the Mint can be computed prior to computing a block header and a set of transactions to mine, so it would not add a computational step between a miner discovering a new best chain head and beginning to mine on that chain head, so long as the miner had a pre-computed Mint lying around.

**Related Tickets**

There's another potential design approach on the tip of my brain, but it depends on potential changes to Mint/Pour protocol integration (see #94).  The rough summary is: if Mint's are represented as TxOuts, rather than TxIns (which *might* be nicer in terms of accounting code) then many basecoin TxIns can be combined out to a single Mint, and now if there's some more complicated restriction rule for this ticket, a miner can delay Minting until they actually want to transfer funds, and even in that case they can batch together a dozen or so block reward coinbases...

Like it's cousin #82, this "restrictive feature" idea is intended to promote systemic privacy. Unlike #82, this is much less restrictive and users still have the full choice to use any "base" transaction features.  The only difference is that someone, at some point, had to explicitly opt-in to remove their privacy.

**Comment by ebfull** [comment]
I would really like to see this goal achieved, but I expect miners will sit on coins they mine for a while anyway.

**Comment by daira** [comment]
Note that we probably need the Founder's Reward to be sent to a multisig (therefore transparent) address, per https://github.com/zcash/zcash/issues/125#issuecomment-194815560 and subsequent comments. This doesn't prevent us requiring the reward to the miner from being protected, but it does complicate things.

**Comment by zookozcash** [comment]
I just don't think this is important. If you pick an arbitrary publicly-visible Zcash balance and trace backwards to see what globally-transparent-txns it came from, you can do that until you hit a private-payment, in which case that's the end of that line of tracing (unless you can bridge the gap with outside-the-blockchain information, or because you have a view-key that lets you see that private-payment).

I figure most such traces will hit a private-payment before they hit a genesis block. But, if a few of them do go all the way to a genesis block, does that matter? Would balances that have globally-transparent traces going all the way back to a genesis block be more valuable? I don't know. I don't want to invest precious engineering effort in this issue when I don't understand how important it would be.

**Comment by daira** [comment]
We decided at the engineering meeting to include in 1.0 the variant of this in which coinbases can only be spent to the v<sup>old</sup><sub>pub</sub> of a Pour. The variant that requires mining rewards to be immediately Poured in the same transaction was rejected due to the complexities @ebfull described in https://github.com/zcash/zcash/commit/5a00f33c381b9ea81aedcc92ba34f735207fd8d5#commitcomment-15254012 , especially the consequences for undo implementation.

**Comment by nathan-at-least** [comment]
In [a comment above](https://github.com/zcash/zcash/issues/101#issuecomment-196537128) @zookozcash said:

> But, if a few of them do go all the way to a genesis block, does that matter?

My intuition is that the "few" will be drastically different between the two systems. @daira stated it nicely in a slack discussion: there may be a "bootstrapping problem". If no one else has Poured yet, it provides no privacy.

This one is important to me, and I want to provide some rationales for its inclusion for posterity. These aren't too hard or precise, but true to my intuition:

* Bootstrapping problem (as above).
* Network Effect: 2*X protected coins provide more than 2 times the privacy/value of X protected coins.
* If the initial spend of every coin must be protected, _then a specific motivation, rationale, or UX_ must exist to explicitly reveal protected coins _at some point_ in its history. By contrast, if every coin begins life transparently, then I expect _an absence of motivation, rationale, or knowledge_ to perpetuate transparent (non-fungible) coins around the system. 
* I imagine the ratio of protected to total "active coins" [*] to be a very important metric. If only 10% of coins are protected, then graph analysis has access to 90% of current coins. If 10% of xfers are confidential transfers (aka Pours) then 90% of the edges are available to graph analysis.

On the last point, if only 10% of the supply is protected, and I'm developing ecosystem tools or infrastructure, should I bother "directly supporting" protected transfers? Why do the extra work to only gain 10/9 as large of a potential market? By contrast, if 90% of the supply is protected, by "direction supporting" protected transfers, I'm gaining 10/1 of a potential market by adding that support. ("Direct support" might mean private deposits/withdrawals with a service, private spends in a shopping cart app, etc...")

[*] I say "active coins" here instead of "monetary base" to distinguish the fact that the simpler-to-implement approach to this ticket leaves unmoved coinbase rewards in a transparent state. This is an important distinction, but I believe all of my intuitive arguments above apply to both cases of fulfilling this ticket.

**Comment by daira** [comment]
This is not yet specified in the protocol spec.

**Comment by ebfull** [comment]
This presents a problem for our policies on testing; a lot of our RPC tests assume we can just spend things from the coinbase. I believe disabling this and the slow start mining in regtest mode, and adding unit tests to ensure it behaves properly in mainnet, is the best approach.

**Comment by nathan-at-least** [comment]
I'm inclined to agree with @ebfull. The only thing is that we need to be clear, explicit, and consistent about this policy. Does that mean we continue to tweak regtest mode to be more and more different from production, just to support rpc tests? At what point does that make regtest mode and rpctests a waste of time and complexity? I haven't figured out a good answer to this yet.

**Comment by ebfull** [comment]
> Does that mean we continue to tweak regtest mode to be more and more different from production, just to support rpc tests?

We'll have to do it for things like this, but I agree; eventually we need to rid of regtest entirely.

**Comment by nathan-at-least** [comment]
I believe the engineering meeting topic is about how to test this.
