### ISSUE TITLE
users can't find the FAQ

### ISSUE THREAD

**Issue by zookozcash** [zcash/zcash#1012]
https://zcashcommunity.slack.com/archives/zcash/p1465747357000030

**Comment by zookozcash** [comment]
https://github.com/zcash/zcash/wiki/FAQ

**Comment by bitcartel** [comment]
Some of the nicest looking documentation I've seen is hosted at ReadTheDocs (RTD).  They pull .rst and .md documentation from a repo and build/format it.  Github officially supports RTD as a service so you can live-edit docs from the Github web-site with automatic updates to the RTD site.

Example:
https://docs.readthedocs.io/en/latest/getting_started.html
Corresponding .rst file:
https://github.com/rtfd/readthedocs.org/blob/master/docs/getting_started.rst

RTD also offers a search function - which the Github wiki does not.

Related to issue #1011.

**Comment by str4d** [comment]
The FAQ is now [on the main website](https://z.cash/support/faq.html), linked directly from the homepage. If users can't find it there, I doubt there is anything more we can do.
