### ISSUE TITLE
do timestamps from 2 hours in the future need to be accepted?

### ISSUE THREAD

**Issue by jl777** [zcash/zcash#1015]
The current code allows blocks with future dated timestamps to be accepted up to 2 hours.
with the blocktime reduced 4x, it seems at least to reduce it to 30 minutes, but maybe even to 10 minutes would be a good idea.

we all know we cant assume that blocktimestamps are monotonically increasing, but still it does make things a bit strange when at any time the blocktime stamp can go backwards 2 hours

**Comment by defuse** [comment]
Related: #998.

**Comment by daira** [comment]
This affects the security of difficulty adjustment (and vice-versa: if a block isn't found for more than the maximum timestamp increment, e.g. due to a failure in difficulty adjustment, then the network can stall permanently).

**Comment by jl777** [comment]
Are you sure?

   // Check timestamp
  In bool CheckBlockHeader(const CBlockHeader& block, CValidationState& state, bool fCheckPOW)

  if (block.GetBlockTime() > GetAdjustedTime() + 2 * 60 * 60)
        return state.Invalid(error("CheckBlockHeader(): block timestamp too far in the future"),
                             REJECT_INVALID, "time-too-new");

The check appears to be for the new block relative to the current time on the node that receives the block, clock drift and not a max time for next block to be found, is the way I read it.

However, my C++ is not my best language, so maybe I am wrong

**Comment by str4d** [comment]
@jl777 is correct; it limits block times to two hours ahead of the current understanding of time, not the latest block time.

**Comment by nathan-at-least** [comment]
There are two issues impacted by this limit:

Can this issue affect difficulty adjustment? We believe our difficulty adjustment scheme isn't compromised if we don't adjust this (absolute) time.

Does this mean our block timestamps won't behave well as "timestamps should"? We don't intend to support this case, and don't promote relying on the block timestamps as a time authority.

So we plan to not adjust this limit (in absolute terms).
