### ISSUE TITLE
Use the depends system to literally `rm` the parts of libsnark we don't use

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#1020]
Sean had this great idea on slack. If we use the depends system to delete the parts of libsnark we don't use, then we assure ourselves and security auditors that the code we're excluding from audits is actually unused.

Could we literally just add some `rm` commands that do this?

**Comment by ebfull** [comment]
I'd want to do it via the patch files because then it's easier for auditors to apply to a local copy of libsnark.

**Comment by defuse** [comment]
This is probably harder than I expect: We'll have to patch up the Makefile and stuff like that.

**Comment by zookozcash** [comment]
+1

**Comment by nathan-at-least** [comment]
This depends on our decision in #820.

**Comment by nathan-at-least** [comment]
We've decided to go with the strategy in #820, so this is no longer necessary. In our fork we'll remove unused code.

**Comment by daira** [comment]
I think the fact that we decided on the in-tree strategy wasn't recorded on #820. Let's make sure we record decisions like this on all relevant tickets.
