### ISSUE TITLE
z5 Release

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#1022]
Nathan says: Try to get one engineer who hasn't done a release to pair on this.

**Comment by str4d** [comment]
So we don't forget: the Zcash version number needs to be changed in `configure.ac` as well as `src/clientversion.h`.

**Comment by ebfull** [comment]
We should add that step in the release notes.

**Comment by str4d** [comment]
Closed by #1031

**Comment by str4d** [comment]
Wait, we haven't actually done anything with that merge yet >_>

**Comment by daira** [comment]
Remember that the release publicity needs to call out the port changes as something that might be incompatible with people's current firewall configurations etc.

**Comment by mgbtcfv** [comment]
Daira,
How do I update the miner to z5? Could you please post instructions on the forum? Do I need to uninstall the previous version?

**Comment by ebfull** [comment]
Check out the new branch with git:

```
git fetch origin
git checkout zc.v0.11.2.z5
```

Build:

```
./zcutil/fetch-params.sh
./zcutil/build.sh -j8
```

Delete old testnet data:

```
rm -rf ~/.zcash/testnet3/
```

**Comment by daira** [comment]
Should this be closed?
