### ISSUE TITLE
Design a currency symbol for adoption by exchanges.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#103]
-and license appropriately.

Related: [Bitcoin Symbol wiki page](https://en.bitcoin.it/wiki/Bitcoin_symbol), #99, #104

**Comment by daira** [comment]
We're using ZEC.

**Comment by daira** [comment]
We should justify the decision to use ZEC instead of XZC in more detail, since it was [raised on the forums](https://forum.z.cash/t/symbol-for-zcash/418).

**Comment by bitcartel** [comment]
I belive one must apply for a code like XZC to be accepted as part of ISO 4217, so nobody can really "claim" it as theirs, although being first to use it would be beneficial as part of any application.

Note that ZEC does not clash with any ISO Alpha 2-letter code for a country, whereas both BTC and ETH do:
https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
https://en.wikipedia.org/wiki/ISO_4217

**Comment by bitcartel** [comment]
We are using ZEC.

**Comment by nathan-at-least** [comment]
Moved to our website issue tracking, since we need a FAQ entry.

**Comment by ravibhojwani** [comment]
Where’s the z Unicode tho

**Comment by ravibhojwani** [comment]
@daira your awesome.. I’ll send it .., just please keep the garden tidy .. I can’t lose that screen

**Comment by ravibhojwani** [comment]
https://github.com/zcash/zcash/issues/104#issuecomment-75612482  Don’t change it please

**Comment by ravibhojwani** [comment]
https://github.com/zcash/zcash/issues/104#issuecomment-75612482  Please please don’t
