### ISSUE TITLE
Multi-threaded mining via command-line option -genproclimit duplicates work by using the same nonce values

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#1033]
The zcash-cli option -genproclimit spawns multiple mining threads, but each one will use the same sequence of nonce and extraNonce values, thus duplicating work.

Currently, each thread starts with its own extraNonce at 0 (on the first run it is increased to 1) and this value is incremented on each new attempt to find a solution after a nonce has been exhausted.

Ideally there should be a generator for nonce and extranonce values (for any block being mined on a given prevblockhash) which all threads consume from to ensure work is unique.

To verify this, modify logging statement:

```
diff --git a/src/miner.cpp b/src/miner.cpp
index 2f9caf0..8d83a32 100644
--- a/src/miner.cpp
+++ b/src/miner.cpp
@@ -512,8 +512,8 @@ void static BitcoinMiner(CWallet *pwallet)
                                                       pblock->nNonce.size());
 
                     // (x_1, x_2, ...) = A(I, V, n, k)
-                    LogPrint("pow", "Running Equihash solver with nNonce = %s\n",
-                             pblock->nNonce.ToString());
+                    LogPrint("pow", "Running Equihash solver with nExtraNonce = %d and nNonce = %s\n",
+                             nExtraNonce, pblock->nNonce.ToString());
                     std::set<std::vector<unsigned int>> solns;
                     EhOptimisedSolve(n, k, curr_state, solns);
                     LogPrint("pow", "Solutions: %d\n", solns.size());

```

Launch zcashd:

`./src/zcashd -daemon -genproclimit=3 -debug=pow
`

And examine debug.log with:

`grep nExtraNonce debug.log
`

Output will look like this:
```
2016-06-18 22:25:41 Running Equihash solver with nExtraNonce = 1 and nNonce = 0000000000000000000000000000000000000000000000000000000000000000
2016-06-18 22:25:41 Running Equihash solver with nExtraNonce = 1 and nNonce = 0000000000000000000000000000000000000000000000000000000000000000
2016-06-18 22:25:41 Running Equihash solver with nExtraNonce = 1 and nNonce = 0000000000000000000000000000000000000000000000000000000000000000
```

**Comment by str4d** [comment]
Known issue, I will be fixing this while I rework the miner for multithreading.

**Comment by ebfull** [comment]
Thanks for making a ticket for this!

**Comment by MostAwesomeDude** [comment]
If you're only starting up the threads once, an old trick is to make each thread advance by $NUMTHREADS each time, rather than by one; four threads might yield 0, 4, 8, ...; 1, 5, 9, ...; and so forth. And then you don't need any cross-thread synchronization.

**Comment by jl777** [comment]
multithreaded mining appears to have more than inefficiency bugs. With 8 threads and several hours, no blocks. then with 1 thread, found a block within minutes. compared to a system that had 2x speed on zcbenchmark, my 8 threads got one third the ZEC after 3+ days vs 2 days on the faster system, so it is very non-linear and skewed toward the fastest system.

hopefully this will be fixed when a working multithreaded miner is working
