### ISSUE TITLE
WalletModelTransaction::newPossibleKeyChange() (walletmodeltransaction.cpp)

### ISSUE THREAD

**Issue by textbrowser** [zcash/zcash#1035]
The method allocates keyChange without verifying if keyChange is already reserved.

**Comment by ebfull** [comment]
I recommend opening a ticket in upstream Bitcoin about this. It happens to be in the Qt wallet, which we will not be supporting in our public release.

**Comment by daira** [comment]
This is in the QT wallet code which has been removed.
