### ISSUE TITLE
improvements to hosting and publishing of CI data

### ISSUE THREAD

**Issue by zookozcash** [zcash/zcash#1043]
* stop using a subdomain of LeastAuthority.com
* make sure ci.z.cash doesn't exist if it doesn't point to our server
* make the coverage reports be easily findable and browsable by the public (i.e. linked from buildbot web pages, or linked from [The Roadmap](https://github.com/zcash/zcash/milestones), or linked from our web pages, or github-hosted docs, etc.

see also https://github.com/zcash/zcash/issues/892

**Comment by ebfull** [comment]
ci.z.cash has been removed, for now.

**Comment by nathan-at-least** [comment]
@ebfull Why is this on the agenda? Can we just assign this to the devops team?

**Comment by nathan-at-least** [comment]
We'll assign this to our new devops hire when they're ready.

**Comment by ageis** [comment]
http://ci.z.cash/ is live. I'd like to redirect requests for `ci.leastauthority.com` to the new domain via DNS CNAME, but I don't have access to that.

**Comment by nathan-at-least** [comment]
ping @ageis: Are all the tasks here complete? If so, could you close this. If not, could you open new tickets in the infra repo and then close this?
