### ISSUE TITLE
Mining uses only 1 thread despite higher nMinerThreads

### ISSUE THREAD

**Issue by solardiz** [zcash/zcash#1054]
Despite patching of chainparams.cpp line 303 to set nMinerThreads to higher than the previous default of 1, I am only getting 1 zcash-miner thread from `zcashd -gen` (only 100% usage on one CPU core, and confirmed via `info threads` in gdb that there's just one thread of this type). Perhaps I simply haven't found the right line to patch? I did make sure this line I patched is actually reached, though.

**Comment by str4d** [comment]
`nMinerThreads` is used to configure the default number of mining threads (1 in regtest, `boost::thread::hardware_concurrency()` otherwise). But that only comes into play when `-genproclimit=-1`, and by default `-genproclimit=1`.

**Comment by str4d** [comment]
(IOW, it's easier to use `zcashd -gen -genproclimit=N` to configure the number of mining threads.)

**Comment by solardiz** [comment]
Thanks. `zcashd -gen -genproclimit=32` works, 3200% CPU usage, VIRT varies from 14 GB to 24 GB (this suggests there's plenty of overhead on (de)allocations, which we'll need to avoid), RES from 4 GB to 13 GB (I am watching in `top`). Findings lots of stale blocks (and no non-stale ones).

I'll close this issue, although probably some documentation is needed so that others know how to configure this.
