### ISSUE TITLE
Need to include mining in a user's guide

### ISSUE THREAD

**Issue by solardiz** [zcash/zcash#1056]
We have https://github.com/zcash/zcash/wiki/Public-Alpha-Guide but it does not say anything about mining - even if deliberate, perhaps it should at least state so and explain why.

**Comment by str4d** [comment]
"How to mine" was mentioned in the ["Why Equihash?" blog post](https://z.cash/blog/why-equihash.html), and there are also various comments [on the forum](https://forum.z.cash/). But I agree it is useful to restate it in a more visible location.

**Comment by zookozcash** [comment]
Hey Jay, I'll bet this one would be a good one for you at this stage. Have you run a Zcash miner yet?

**Comment by zawy12** [comment]
Being inexperienced in all of this, here's what I needed to know that was missing:

1) zcash.conf needs:  gen=1 and genproclimit=4 (for 4 threads)
2) Begin mining with zcashd -daemon 
3) Have to run as root to get decent speed.  Use "sudo" on Unbuntu.
4) Benchmark test is for 1 thread, not a real miner, and time is for 2 ("solves"?)
5) str4d has a standalone miner that does a more complete test.
6) Use "ps aux H" to see the thread use of CPU and RAM
7) Is "kill" the only way to stop it?

**Comment by solardiz** [comment]
On Wed, Jul 20, 2016 at 02:12:25PM -0700, zawy12 wrote:
> 1) zcash.conf needs:  gen=1 and genproclimit=4 (for 4 threads)

Alternatively, specify "-gen -genproclimit=4" on zcashd command-line.

> 3) Have to run as root to get decent speed.  Use "sudo" on Unbuntu.

Why?  This shouldn't be needed.  What speed difference are you seeing,
and how do you explain it?  Do you, for example, see any difference in
huge pages usage when you run as user vs. root (see /proc/meminfo)?

**Comment by zawy12** [comment]
I ran it many times without the sudo and it gave only 1% to 3% for both CPU and RAM (ps aux H).   Just now I tried to go back and run it again, and it gives an error:

> Error opening block database.
>Do you want to rebuild the block database now?

 I try to answer "Y", "y", or "yes" to the question and it does weird stuff.  But I can still run it as root.

**Comment by solardiz** [comment]
On Wed, Jul 20, 2016 at 03:17:51PM -0700, zawy12 wrote:
> I ran it many times without the sudo and it gave only 1% to 3% for both CPU and RAM (ps aux H).   Just now I tried to go back and run it again, and it gives an error:
> 
> > Error opening block database.
> >Do you want to rebuild the block database now?
> 
>  I try to answer "Y", "y", or "yes" to the question and it does weird stuff.  But I can still run it as root.  

Once you've ever used sudo, you probably have files owned by root in your tree. You need to recursively chown it back to the user, or start over - and never use sudo again (or if you must, for testing/benchmarking, do this on a copy of the tree). It should work as non-root, really.

**Comment by ioptio** [comment]
Mining docs here: https://zcash.readthedocs.io/en/latest/rtd_pages/zcash_mining_guide.html
