### ISSUE TITLE
move the unit tests to a new virtual machine apart from the performance benchmarks

### ISSUE THREAD

**Issue by zookozcash** [zcash/zcash#1068]
Taylor will rent a new server.

Jay will make a new builder in the buildmaster config for unit tests separate from performance tests. Sean will show Jay how to get started on that.

Then we'll have the unit tests builder use the buildslave on the new server.

**Comment by nathan-at-least** [comment]
BTW- one of the non-obvious (to me) goals is to keep the performance tests on the same machine for historical accuracy.

**Comment by ebfull** [comment]
Woohoo! @arcalinea and I did this in https://github.com/Electric-Coin-Company/bbotzc/pull/21.
