### ISSUE TITLE
Mining to a wallet/address out of the box?

### ISSUE THREAD

**Issue by yaapelsinko** [zcash/zcash#1069]
For me and (I believe) other miners, one of the first concerns is the possibility of deploying multiple mining instances and securing the coins mined, somehow automagically.

There is a forum thread no one ever answered: https://forum.z.cash/t/is-it-possible-to-specify-a-specific-fixed-coinbase-address-for-mining-in-zcashd/652

So, is it possible (with current versions, like z5 or upcoming z6), to mine coins and automatically send them to an address, instantly making them independent of the machine they were mined by?
Will it be implemented for release?
Is/will it be dummy-friendly?

**Comment by aniemerg** [comment]
If you don't mind get your hands dirty, their is an explanation of how this can be done in the [Guide to Mining on Amazon EC2](https://github.com/Austin-Williams/zcash-guides/wiki/Guide-to-Mining-Zcash-on-Amazon-EC2#option-3-mine-to-the-same-address-every-time)

**Comment by yaapelsinko** [comment]
As far as I understand, all the options in the guide are talking that I have my wallet dat, and the address pool my instance mine to is bound to the wallet.dat. And I have to do some magic cloning the wallet dat between all the instances, backing it up and so on...

What I'm talking about is the following. For example, I have a personal wallet/address. I setting up N mining instances, and if it is necessary, all of them have their own wallets, addresses, keys, whatever. As they mine, they send all coins mined to my wallet automatically, effectively emptying they working wallets. And I don't ever need to look into any instance as long as it's working.

Or any other approach to make a mining instance stateless, so that one just have to start it with the command "zcashd -MinePlsToMyAddress TheAddressAbracadabra". 

Will it be possible? Or is it already?

**Comment by daira** [comment]
I see no reason why it wouldn't be possible. I don't know whether it will be implemented before the 1.0 launch.

**Comment by nathan-at-least** [comment]
We won't be adding features before 1.0.0 launch. I'll see if we can implement it in the subsequent release.

**Comment by str4d** [comment]
We added a `-mineraddress` option to `zcashd` in 1.0.6.
