### ISSUE TITLE
Fix the libsnark point compression DoS vector and contribute it to upstream

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#1073]
The algorithm libsnark uses for taking square roots loops forever if the input isn't a perfect square (or whatever). This is a DoS vector if an attacker can provide compressed points, and should be fixed regardless of whether we expose the attack surface in Zcash, since other users of libsnark might get bit by it.

**Comment by defuse** [comment]
@daira posted this paper on square roots to slack: http://stanford.edu/~jbooher/expos/sqr_qnr.pdf

**Comment by wkarshat** [comment]
New location of the Booher square roots paper https://www.math.arizona.edu/~jeremybooher/expos/sqr_qnr.pdf

**Comment by daira** [comment]
The upstream ticket is https://github.com/scipr-lab/libsnark/issues/41 . I don't know whether we want to close this one, since zcashd will no longer use libsnark after #4060.

**Comment by Eirik0** [comment]
We are not intending to fix this because we plan to remove libsnark.
