### ISSUE TITLE
Fix the SIGHASH_SINGLE bug

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#1078]
If you try to do `SIGHASH_SINGLE` in an input for which there is no corresponding (same-index) output, then `SignatureHash` returns `1`. It is a known bug that at least some places (e.g. `CheckSig`) don't check for this error code, and so the bug is baked into Bitcoin's consensus rules. *Our new code* (JoinSplits) is checking for the error code when we call SignatureHash, which is inconsistent with those parts of Bitcoin. Fortunately, there are no bugs introduced by that since we always use `SIGHASH_ALL` for JoinSplits (so restricting the signature type was a good call!).

Should we fix the bug? There are only 2 calls (excluding ones in tests) that would need to have an error check added, but by fixing it we risk breaking Bitcoin tools which expect the bug to be present.

Here's the relevant code from `SignatureHash`:

```
uint256 SignatureHash(const CScript& scriptCode, const CTransaction& txTo, unsigned int nIn, int nHashType)
{
    static const uint256 one(uint256S("0000000000000000000000000000000000000000000000000000000000000001"));
    if (nIn >= txTo.vin.size() && nIn != NOT_AN_INPUT) {
        //  nIn out of range
        return one;
    }

    // Check for invalid use of SIGHASH_SINGLE
    if ((nHashType & 0x1f) == SIGHASH_SINGLE) {
        if (nIn >= txTo.vout.size()) {
            //  nOut out of range
            return one;
        }
    }
...
```

**Comment by defuse** [comment]
PR #1079.

**Comment by jl777** [comment]
it is a tough call. however, sighash_single has very limited usage and I dont think there are many tools that use it. As long as the tx version number isnt a low value (same as standard bitcoin ones), we can hope they will eventually fix this bug via new txversion to indicate sighash_single bug is fixed.

even if not, I would assess the chance of conflicts from this as minimal and it is probably a good idea to fix as any usage if sighash single is likely to be a custom usage

**Comment by nathan-at-least** [comment]
BTW, here's a 2014 post by Peter Todd that explores some implications of this consensus-warping bug: https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2014-November/006878.html
