### ISSUE TITLE
Are Mint/Pour TxIns unsigned by base address keys?

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#108]
If a base transaction is signed by "base keys" (associated with base/Bitcoin-style addresses), then implementations must be careful to avoid introducing linkability between transactions.

From my current understanding, I don't think they need to be signed, since (base) signatures are embedded in TxIns as part of the ``scriptSig``, but both Mint and Pour are special case ``scriptSig`` instances with no base signatures.

ping @imichaelmiers

**Comment by ebfull** [comment]
I don't understand this ticket, can we consider closing it?

**Comment by daira** [comment]
See #529.
