### ISSUE TITLE
zcash-cli getinfo should show the zcash release number

### ISSUE THREAD

**Issue by daira** [zcash/zcash#1081]

**Comment by str4d** [comment]
Reposting from Slack:

> I tried to do this at the time, but it would have meant redefining the meaning of that constant (how it is parsed) which would completely break compatibility with anything that uses that API (as in, things using that bit of the API wouldn't even be able to figure out the base non-Zcash version). So if we want to change things, we either accept that compatibility break in the name of simplicity, or add a separate Zcash version field that splits the version information (not great) but keeps compatibility. But maybe I'm worrying about compatibility there too much.

> The other issue IIRC was about having enough space in the 32-bit field for Zcash numbering. The current format of that field is to allow 100 numbers per level, with four levels upstream, which only leaves 42 possible variants for our .z# per upstream version.

@zookozcash comments:

> I think our business partners who are going to adding Zcash support don't mind having to change a constant in order to use the API. In fact, they'd probably prefer that to detect accidentally connecting to the wrong rpc endpoint.

**Comment by daira** [comment]
This ticket is about the output of ``zcash-cli getinfo``. It doesn't specify how that information is obtained from the RPC interface; it could be a separate JSON field or even a new RPC call. Note that accidentally connecting to a Zcash RPC endpoint with a Bitcoin RPC client is hardly an issue, because it's a different port and such clients are likely to hard code the Bitcoin RPC port number.

**Comment by daira** [comment]
On the other hand, I think we may be overemphasising the importance of the Bitcoin version that we forked from. Originally we were planning to rebase fairly frequently onto upstream, but I'm not sure that's actually practical given the extent of our changes now; I think we are more likely to cherry-pick upstream changes that are useful for Zcash. In that case, the link with a Bitcoin version is likely to become increasingly tenuous.

**Comment by nathan-at-least** [comment]
Small feature changes, especially those requested by users, are going into 1.0.1 by default. Also, when we update version number schema, will it address the need of this ticket?

**Comment by daira** [comment]
This might have been incidentally fixed; assigning myself to check.

**Comment by daira** [comment]
``zcash-cli getinfo`` shows only ``"version": 1001550``, which I know means 10.0.15 but there is no reason why a non-developer would know that. On the other hand ``zcash-cli getnetworkinfo`` also shows ``"subversion": "/MagicBean:1.0.15/"``.

**Comment by str4d** [comment]
This issue is stale; at the time our version system was completely different. We do correctly represent the Zcash version in the `version` field now.

@daira's comment above is about a separate usability issue, which I do not see as an issue. If users are trying to figure out the version from the CLI, we have `zcashd -version` or `zcash-cli -version`. If they are trying to figure out from somewhere else, then whatever is in between the user and `zcashd` (like a GUI wallet) should be parsing and displaying the version information itself.
