### ISSUE TITLE
Out-of-memory while running tests should be reported properly

### ISSUE THREAD

**Issue by daira** [zcash/zcash#1083]
They should be reported as ERRORs, not FAILs, and with a reasonable error message. See #1065 for the current behaviour.

**Comment by zookozcash** [comment]
Related: https://github.com/zcash/zcash/issues/1498

**Comment by str4d** [comment]
Not going to address this: Sprout proofs post-Sapling take less memory to create, and we haven't see these kinds of issues in CI for a long time.
