### ISSUE TITLE
Error 'libbitcoinconsensus_la-eccryptoverify.lo' is not a valid libtool object

### ISSUE THREAD

**Issue by pahakalle** [zcash/zcash#1087]
at the make install part of building i get an error saying "libtool:   error: 'libbitcoinconsensus_la-eccryptoverify.lo' is not a valid libtool object
"

**Comment by ebfull** [comment]
That's odd! What does your build environment look like? (what version of g++, and so on.)

**Comment by pahakalle** [comment]
sorry i somehow fixed it. and i was running it on kali linux but my computer froze and it somehow caused that but after deleting and reinstalling the files it fixed it for me 😄
