### ISSUE TITLE
Error when compiling on Ubuntu 14.04

### ISSUE THREAD

**Issue by ferni** [zcash/zcash#1091]
I followed this guide: https://github.com/zcash/zcash/wiki/Public-Alpha-Guide

Namely:

git clone https://github.com/zcash/zcash.git
cd zcash/
git checkout zc.v0.11.2.z6
./zcutil/fetch-params.sh

./zcutil/build.sh -j4

This is the last part of the output:

libtool: link: /home/fer/prog/zcash/depends/x86_64-unknown-linux-gnu/native/bin/ccache g++ -m64 -std=c++11 -pipe -O2 -Wno-deprecated-declarations -Wno-placement-new -Wno-terminate -Werror -Og -g -Wstack-protector -fstack-protector-all -fPIE -pthread -Wl,-z -Wl,relro -Wl,-z -Wl,now -pie -o bitcoin-tx bitcoin_tx-bitcoin-tx.o -fopenmp  -L/home/fer/prog/zcash/depends/x86_64-unknown-linux-gnu/lib univalue/libbitcoin_univalue.a libbitcoin_common.a libbitcoin_util.a secp256k1/.libs/libsecp256k1.a libzcash.a crypto/libbitcoin_crypto.a -lsnark /home/fer/prog/zcash/depends/x86_64-unknown-linux-gnu/lib/libgmpxx.a /home/fer/prog/zcash/depends/x86_64-unknown-linux-gnu/lib/libgmp.a /home/fer/prog/zcash/depends/x86_64-unknown-linux-gnu/lib/libsodium.a -lboost_system-mt -lboost_filesystem-mt -lboost_program_options-mt -lboost_thread-mt -lboost_chrono-mt -ldl -lcrypto -lanl -fopenmp -pthread
/bin/bash ../libtool  --tag=CXX   --mode=link /home/fer/prog/zcash/depends/x86_64-unknown-linux-gnu/native/bin/ccache g++ -m64  -std=c++11 -pipe -O2 -Wno-deprecated-declarations -Wno-placement-new -Wno-terminate -Werror -Og -g  -Wstack-protector -fstack-protector-all -fPIE -pthread  -L/home/fer/prog/zcash/depends/x86_64-unknown-linux-gnu/lib   -Wl,-z,relro -Wl,-z,now -pie -o zerocash/tests/utilTest zerocash/tests/utilTest.o -L/home/fer/prog/zcash/depends/x86_64-unknown-linux-gnu/lib -lboost_system-mt -lboost_filesystem-mt -lboost_program_options-mt -lboost_thread-mt -lboost_chrono-mt libzcash.a libbitcoin_util.a crypto/libbitcoin_crypto.a -lsnark -lgmp -lgmpxx -lboost_system-mt -lcrypto -lsodium -fopenmp -lcrypto -lanl 
libzcash.a(libzcash_a-JoinSplit.o): In function `libzcash::uint64_to_bool_vector(unsigned long)':
/home/fer/prog/zcash/src/./zcash/circuit/utils.tcc:45: undefined reference to`libzerocash::convertBytesVectorToVector(std::vector<unsigned char, std::allocator<unsigned char> > const&, std::vector<bool, std::allocator<bool> >&)'
libzcash.a(libzcash_a-JoinSplit.o): In function `libzcash::JSInput::JSInput()':
/home/fer/prog/zcash/src/zcash/JoinSplit.cpp:345: undefined reference to`libzcash::IncrementalMerkleTree<29ul, libzcash::SHA256Compress>::append(libzcash::SHA256Compress)'
libzcash.a(libzcash_a-JoinSplit.o): In function `std::vector<bool, std::allocator<bool> > libzcash::to_bool_vector<uint256>(uint256)':
/home/fer/prog/zcash/src/./zcash/circuit/utils.tcc:26: undefined reference to`libzerocash::convertBytesVectorToVector(std::vector<unsigned char, std::allocator<unsigned char> > const&, std::vector<bool, std::allocator<bool> >&)'
libzcash.a(libzcash_a-JoinSplit.o): In function `std::vector<bool, std::allocator<bool> > libzcash::to_bool_vector<uint252>(uint252)':
/home/fer/prog/zcash/src/./zcash/circuit/utils.tcc:26: undefined reference to`libzerocash::convertBytesVectorToVector(std::vector<unsigned char, std::allocator<unsigned char> > const&, std::vector<bool, std::allocator<bool> >&)'
libzcash.a(libzcash_a-JoinSplit.o): In function `libzcash::merkle_tree_gadget<libsnark::Fp_model<4l, libsnark::alt_bn128_modulus_r> >::generate_r1cs_witness(libzcash::MerklePath const&)':
/home/fer/prog/zcash/src/./zcash/circuit/merkle.tcc:53: undefined reference to`libzerocash::convertVectorToInt(std::vector<bool, std::allocator<bool> > const&)'
libzcash.a(libzcash_a-JoinSplit.o): In function `libzcash::IncrementalWitness<29ul, libzcash::SHA256Compress>::path() const':
/home/fer/prog/zcash/src/zcash/IncrementalMerkleTree.hpp:107: undefined reference to`libzcash::IncrementalWitness<29ul, libzcash::SHA256Compress>::partial_path() const'
/home/fer/prog/zcash/src/zcash/IncrementalMerkleTree.hpp:107: undefined reference to `libzcash::IncrementalMerkleTree<29ul, libzcash::SHA256Compress>::path(std::deque<libzcash::SHA256Compress, std::allocator<libzcash::SHA256Compress> >) const'
libtool: link: /home/fer/prog/zcash/depends/x86_64-unknown-linux-gnu/native/bin/ccache g++ -m64 -std=c++11 -pipe -O2 -Wno-deprecated-declarations -Wno-placement-new -Wno-terminate -Werror -Og -g -Wstack-protector -fstack-protector-all -fPIE -pthread -Wl,-z -Wl,relro -Wl,-z -Wl,now -pie -o zerocash/tests/utilTest zerocash/tests/utilTest.o -fopenmp  -L/home/fer/prog/zcash/depends/x86_64-unknown-linux-gnu/lib -lboost_filesystem-mt -lboost_program_options-mt -lboost_thread-mt -lboost_chrono-mt libzcash.a libbitcoin_util.a crypto/libbitcoin_crypto.a -lsnark /home/fer/prog/zcash/depends/x86_64-unknown-linux-gnu/lib/libgmpxx.a /home/fer/prog/zcash/depends/x86_64-unknown-linux-gnu/lib/libgmp.a -lboost_system-mt /home/fer/prog/zcash/depends/x86_64-unknown-linux-gnu/lib/libsodium.a -lcrypto -lanl -fopenmp -pthread
collect2: error: ld returned 1 exit status
make[2]: *** [zcash/GenerateParams] Error 1
make[2]: *** Waiting for unfinished jobs....
zerocash/tests/utilTest.o: In function`testConvertVectorToInt::test_method()':
/home/fer/prog/zcash/src/zerocash/tests/utilTest.cpp:12: undefined reference to `libzerocash::convertVectorToInt(std::vector<bool, std::allocator<bool> > const&)'
/home/fer/prog/zcash/src/zerocash/tests/utilTest.cpp:13: undefined reference to`libzerocash::convertVectorToInt(std::vector<bool, std::allocator<bool> > const&)'
/home/fer/prog/zcash/src/zerocash/tests/utilTest.cpp:14: undefined reference to `libzerocash::convertVectorToInt(std::vector<bool, std::allocator<bool> > const&)'
/home/fer/prog/zcash/src/zerocash/tests/utilTest.cpp:15: undefined reference to`libzerocash::convertVectorToInt(std::vector<bool, std::allocator<bool> > const&)'
/home/fer/prog/zcash/src/zerocash/tests/utilTest.cpp:16: undefined reference to `libzerocash::convertVectorToInt(std::vector<bool, std::allocator<bool> > const&)'
zerocash/tests/utilTest.o:/home/fer/prog/zcash/src/zerocash/tests/utilTest.cpp:17: more undefined references to`libzerocash::convertVectorToInt(std::vector<bool, std::allocator<bool> > const&)' follow
zerocash/tests/utilTest.o: In function `testConvertBytesVectorToVector::test_method()':
/home/fer/prog/zcash/src/zerocash/tests/utilTest.cpp:49: undefined reference to`libzerocash::convertBytesVectorToVector(std::vector<unsigned char, std::allocator<unsigned char> > const&, std::vector<bool, std::allocator<bool> >&)'
collect2: error: ld returned 1 exit status
make[2]: **\* [zerocash/tests/utilTest] Error 1
bitcoin_tx-bitcoin-tx.o: In function `CBitcoinAddress':
/home/fer/prog/zcash/src/base58.h:137: undefined reference to`CBase58Data::CBase58Data()'
/home/fer/prog/zcash/src/base58.h:137: undefined reference to `CBase58Data::SetString(std::string const&)'
bitcoin_tx-bitcoin-tx.o: In function`MutateTxAddOutAddr':
/home/fer/prog/zcash/src/bitcoin-tx.cpp:222: undefined reference to `CBitcoinAddress::IsValid() const'
/home/fer/prog/zcash/src/bitcoin-tx.cpp:226: undefined reference to`CBitcoinAddress::Get() const'
bitcoin_tx-bitcoin-tx.o: In function `AppInitRawTx':
/home/fer/prog/zcash/src/bitcoin-tx.cpp:37: undefined reference to`SelectParamsFromCommandLine()'
bitcoin_tx-bitcoin-tx.o: In function `MutateTxSign':
/home/fer/prog/zcash/src/bitcoin-tx.cpp:340: undefined reference to`vtable for CCoinsView'
/home/fer/prog/zcash/src/bitcoin-tx.cpp:341: undefined reference to `CCoinsViewCache::CCoinsViewCache(CCoinsView*)'
bitcoin_tx-bitcoin-tx.o: In function`CBitcoinSecret':
/home/fer/prog/zcash/src/base58.h:158: undefined reference to `CBase58Data::CBase58Data()'
bitcoin_tx-bitcoin-tx.o: In function`MutateTxSign':
/home/fer/prog/zcash/src/bitcoin-tx.cpp:354: undefined reference to `CBitcoinSecret::SetString(std::string const&)'
/home/fer/prog/zcash/src/bitcoin-tx.cpp:358: undefined reference to`CBitcoinSecret::GetKey()'
/home/fer/prog/zcash/src/bitcoin-tx.cpp:386: undefined reference to `CCoinsViewCache::ModifyCoins(uint256 const&)'
/home/fer/prog/zcash/src/bitcoin-tx.cpp:396: undefined reference to`CCoinsModifier::~CCoinsModifier()'
/home/fer/prog/zcash/src/bitcoin-tx.cpp:418: undefined reference to `CCoinsViewCache::AccessCoins(uint256 const&) const'
/home/fer/prog/zcash/src/bitcoin-tx.cpp:341: undefined reference to`CCoinsViewCache::~CCoinsViewCache()'
bitcoin_tx-bitcoin-tx.o: In function `~CCoinsView':
/home/fer/prog/zcash/src/coins.h:377: undefined reference to`vtable for CCoinsView'
bitcoin_tx-bitcoin-tx.o: In function `MutateTxSign':
/home/fer/prog/zcash/src/bitcoin-tx.cpp:396: undefined reference to`CCoinsModifier::~CCoinsModifier()'
/home/fer/prog/zcash/src/bitcoin-tx.cpp:341: undefined reference to `CCoinsViewCache::~CCoinsViewCache()'
bitcoin_tx-bitcoin-tx.o: In function`~CCoinsView':
/home/fer/prog/zcash/src/coins.h:377: undefined reference to `vtable for CCoinsView'
bitcoin_tx-bitcoin-tx.o: In function`LockedPageManager::CreateInstance()':
/home/fer/prog/zcash/src/./support/pagelocker.h:152: undefined reference to `LockedPageManager::LockedPageManager()'
/home/fer/prog/zcash/src/./support/pagelocker.h:153: undefined reference to`LockedPageManager::_instance'
bitcoin_tx-bitcoin-tx.o: In function `call_once<void (*&)()>':
/home/fer/prog/zcash/depends/x86_64-unknown-linux-gnu/include/boost/thread/pthread/once_atomic.hpp:123: undefined reference to`LockedPageManager::init_flag'
/home/fer/prog/zcash/depends/x86_64-unknown-linux-gnu/include/boost/thread/pthread/once_atomic.hpp:138: undefined reference to `LockedPageManager::init_flag'
/home/fer/prog/zcash/depends/x86_64-unknown-linux-gnu/include/boost/thread/pthread/once_atomic.hpp:134: undefined reference to`LockedPageManager::init_flag'
bitcoin_tx-bitcoin-tx.o: In function `LockedPageManager::Instance()':
/home/fer/prog/zcash/src/./support/pagelocker.h:139: undefined reference to`LockedPageManager::_instance'
bitcoin_tx-bitcoin-tx.o: In function `LockedPageManagerBase<MemoryPageLocker>::UnlockRange(void*, unsigned long)':
/home/fer/prog/zcash/src/./support/pagelocker.h:82: undefined reference to`MemoryPageLocker::Unlock(void const_, unsigned long)'
libbitcoin_common.a(libbitcoin_common_a-core_write.o): In function `CBitcoinAddress':
/home/fer/prog/zcash/src/base58.h:136: undefined reference to`CBase58Data::CBase58Data()'
/home/fer/prog/zcash/src/base58.h:136: undefined reference to `CBitcoinAddress::Set(boost::variant<CNoDestination<CKeyID, CScriptID> > const&)'
libbitcoin_common.a(libbitcoin_common_a-core_write.o): In function`ScriptPubKeyToUniv(CScript const&, UniValue&, bool)':
/home/fer/prog/zcash/src/core_write.cpp:85: undefined reference to `CBase58Data::ToString() const'
libbitcoin_common.a(libbitcoin_common_a-key.o): In function`CKey::Check(unsigned char const_)':
/home/fer/prog/zcash/src/key.cpp:20: undefined reference to `eccrypto::Check(unsigned char const*)'
libbitcoin_common.a(libbitcoin_common_a-key.o): In function`ECC_InitSanityCheck()':
/home/fer/prog/zcash/src/key.cpp:187: undefined reference to `CECKey::SanityCheck()'
libbitcoin_common.a(libbitcoin_common_a-key.o): In function`CKey::Derive(CKey&, uint256&, unsigned int, uint256 const&) const':
/home/fer/prog/zcash/src/key.cpp:122: undefined reference to `BIP32Hash(uint256 const&, unsigned int, unsigned char, unsigned char const*, unsigned char*)'
/home/fer/prog/zcash/src/key.cpp:125: undefined reference to`BIP32Hash(uint256 const&, unsigned int, unsigned char, unsigned char const_, unsigned char_)'
libbitcoin_common.a(libbitcoin_common_a-key.o): In function `call_once<void (*&)()>':
/home/fer/prog/zcash/depends/x86_64-unknown-linux-gnu/include/boost/thread/pthread/once_atomic.hpp:123: undefined reference to`LockedPageManager::init_flag'
/home/fer/prog/zcash/depends/x86_64-unknown-linux-gnu/include/boost/thread/pthread/once_atomic.hpp:138: undefined reference to `LockedPageManager::init_flag'
/home/fer/prog/zcash/depends/x86_64-unknown-linux-gnu/include/boost/thread/pthread/once_atomic.hpp:134: undefined reference to`LockedPageManager::init_flag'
libbitcoin_common.a(libbitcoin_common_a-key.o): In function `LockedPageManager::Instance()':
/home/fer/prog/zcash/src/./support/pagelocker.h:139: undefined reference to`LockedPageManager::_instance'
libbitcoin_common.a(libbitcoin_common_a-key.o): In function `LockedPageManagerBase<MemoryPageLocker>::LockRange(void*, unsigned long)':
/home/fer/prog/zcash/src/./support/pagelocker.h:56: undefined reference to`MemoryPageLocker::Lock(void const_, unsigned long)'
libbitcoin_common.a(libbitcoin_common_a-key.o): In function `call_once<void (_&)()>':
/home/fer/prog/zcash/depends/x86_64-unknown-linux-gnu/include/boost/thread/pthread/once_atomic.hpp:123: undefined reference to `LockedPageManager::init_flag'
/home/fer/prog/zcash/depends/x86_64-unknown-linux-gnu/include/boost/thread/pthread/once_atomic.hpp:138: undefined reference to`LockedPageManager::init_flag'
/home/fer/prog/zcash/depends/x86_64-unknown-linux-gnu/include/boost/thread/pthread/once_atomic.hpp:134: undefined reference to `LockedPageManager::init_flag'
libbitcoin_common.a(libbitcoin_common_a-key.o): In function`LockedPageManager::Instance()':
/home/fer/prog/zcash/src/./support/pagelocker.h:139: undefined reference to `LockedPageManager::_instance'
libbitcoin_common.a(libbitcoin_common_a-key.o): In function`LockedPageManagerBase<MemoryPageLocker>::LockRange(void_, unsigned long)':
/home/fer/prog/zcash/src/./support/pagelocker.h:56: undefined reference to `MemoryPageLocker::Lock(void const_, unsigned long)'
libbitcoin_common.a(libbitcoin_common_a-key.o): In function `call_once<void (*&)()>':
/home/fer/prog/zcash/depends/x86_64-unknown-linux-gnu/include/boost/thread/pthread/once_atomic.hpp:123: undefined reference to`LockedPageManager::init_flag'
/home/fer/prog/zcash/depends/x86_64-unknown-linux-gnu/include/boost/thread/pthread/once_atomic.hpp:138: undefined reference to `LockedPageManager::init_flag'
/home/fer/prog/zcash/depends/x86_64-unknown-linux-gnu/include/boost/thread/pthread/once_atomic.hpp:134: undefined reference to`LockedPageManager::init_flag'
libbitcoin_common.a(libbitcoin_common_a-key.o): In function `LockedPageManager::Instance()':
/home/fer/prog/zcash/src/./support/pagelocker.h:139: undefined reference to`LockedPageManager::_instance'
libbitcoin_common.a(libbitcoin_common_a-key.o): In function `LockedPageManagerBase<MemoryPageLocker>::LockRange(void*, unsigned long)':
/home/fer/prog/zcash/src/./support/pagelocker.h:56: undefined reference to`MemoryPageLocker::Lock(void const_, unsigned long)'
libbitcoin_common.a(libbitcoin_common_a-key.o): In function `call_once<void (_&)()>':
/home/fer/prog/zcash/depends/x86_64-unknown-linux-gnu/include/boost/thread/pthread/once_atomic.hpp:123: undefined reference to `LockedPageManager::init_flag'
/home/fer/prog/zcash/depends/x86_64-unknown-linux-gnu/include/boost/thread/pthread/once_atomic.hpp:138: undefined reference to`LockedPageManager::init_flag'
/home/fer/prog/zcash/depends/x86_64-unknown-linux-gnu/include/boost/thread/pthread/once_atomic.hpp:134: undefined reference to `LockedPageManager::init_flag'
libbitcoin_common.a(libbitcoin_common_a-key.o): In function`LockedPageManager::Instance()':
/home/fer/prog/zcash/src/./support/pagelocker.h:139: undefined reference to `LockedPageManager::_instance'
libbitcoin_common.a(libbitcoin_common_a-key.o): In function`LockedPageManagerBase<MemoryPageLocker>::UnlockRange(void_, unsigned long)':
/home/fer/prog/zcash/src/./support/pagelocker.h:82: undefined reference to `MemoryPageLocker::Unlock(void const_, unsigned long)'
libbitcoin_common.a(libbitcoin_common_a-key.o): In function `call_once<void (*&)()>':
/home/fer/prog/zcash/depends/x86_64-unknown-linux-gnu/include/boost/thread/pthread/once_atomic.hpp:123: undefined reference to`LockedPageManager::init_flag'
/home/fer/prog/zcash/depends/x86_64-unknown-linux-gnu/include/boost/thread/pthread/once_atomic.hpp:138: undefined reference to `LockedPageManager::init_flag'
/home/fer/prog/zcash/depends/x86_64-unknown-linux-gnu/include/boost/thread/pthread/once_atomic.hpp:134: undefined reference to`LockedPageManager::init_flag'
libbitcoin_common.a(libbitcoin_common_a-key.o): In function `LockedPageManager::Instance()':
/home/fer/prog/zcash/src/./support/pagelocker.h:139: undefined reference to`LockedPageManager::_instance'
libbitcoin_common.a(libbitcoin_common_a-key.o): In function `LockedPageManagerBase<MemoryPageLocker>::UnlockRange(void*, unsigned long)':
/home/fer/prog/zcash/src/./support/pagelocker.h:82: undefined reference to`MemoryPageLocker::Unlock(void const_, unsigned long)'
libbitcoin_common.a(libbitcoin_common_a-key.o): In function `call_once<void (_&)()>':
/home/fer/prog/zcash/depends/x86_64-unknown-linux-gnu/include/boost/thread/pthread/once_atomic.hpp:123: undefined reference to `LockedPageManager::init_flag'
/home/fer/prog/zcash/depends/x86_64-unknown-linux-gnu/include/boost/thread/pthread/once_atomic.hpp:138: undefined reference to`LockedPageManager::init_flag'
libbitcoin_common.a(libbitcoin_common_a-key.o): In function `LockedPageManager::Instance()':
/home/fer/prog/zcash/depends/x86_64-unknown-linux-gnu/include/boost/thread/pthread/once_atomic.hpp:134: undefined reference to`LockedPageManager::init_flag'
libbitcoin_common.a(libbitcoin_common_a-key.o): In function `LockedPageManager::Instance()':
/home/fer/prog/zcash/src/./support/pagelocker.h:139: undefined reference to`LockedPageManager::_instance'
libbitcoin_common.a(libbitcoin_common_a-key.o): In function `LockedPageManagerBase<MemoryPageLocker>::UnlockRange(void*, unsigned long)':
/home/fer/prog/zcash/src/./support/pagelocker.h:82: undefined reference to`MemoryPageLocker::Unlock(void const_, unsigned long)'
libbitcoin_common.a(libbitcoin_common_a-pubkey.o): In function `CPubKey::Verify(uint256 const&, std::vector<unsigned char, std::allocator<unsigned char> > const&) const':
/home/fer/prog/zcash/src/pubkey.cpp:14: undefined reference to`CECKey::CECKey()'
/home/fer/prog/zcash/src/pubkey.cpp:15: undefined reference to `CECKey::SetPubKey(unsigned char const_, unsigned long)'
/home/fer/prog/zcash/src/pubkey.cpp:17: undefined reference to `CECKey::Verify(uint256 const&, std::vector<unsigned char, std::allocator<unsigned char> > const&)'
/home/fer/prog/zcash/src/pubkey.cpp:19: undefined reference to`CECKey::~CECKey()'
/home/fer/prog/zcash/src/pubkey.cpp:19: undefined reference to `CECKey::~CECKey()'
libbitcoin_common.a(libbitcoin_common_a-pubkey.o): In function`CPubKey::RecoverCompact(uint256 const&, std::vector<unsigned char, std::allocator<unsigned char> > const&)':
/home/fer/prog/zcash/src/pubkey.cpp:27: undefined reference to `CECKey::CECKey()'
/home/fer/prog/zcash/src/pubkey.cpp:28: undefined reference to`CECKey::Recover(uint256 const&, unsigned char const_, int)'
/home/fer/prog/zcash/src/pubkey.cpp:31: undefined reference to `CECKey::GetPubKey(std::vector<unsigned char, std::allocator<unsigned char> >&, bool)'
/home/fer/prog/zcash/src/pubkey.cpp:33: undefined reference to`CECKey::~CECKey()'
/home/fer/prog/zcash/src/pubkey.cpp:33: undefined reference to `CECKey::~CECKey()'
libbitcoin_common.a(libbitcoin_common_a-pubkey.o): In function`CPubKey::IsFullyValid() const':
/home/fer/prog/zcash/src/pubkey.cpp:39: undefined reference to `CECKey::CECKey()'
/home/fer/prog/zcash/src/pubkey.cpp:40: undefined reference to`CECKey::SetPubKey(unsigned char const_, unsigned long)'
/home/fer/prog/zcash/src/pubkey.cpp:42: undefined reference to `CECKey::~CECKey()'
/home/fer/prog/zcash/src/pubkey.cpp:42: undefined reference to`CECKey::~CECKey()'
libbitcoin_common.a(libbitcoin_common_a-pubkey.o): In function `CPubKey::Decompress()':
/home/fer/prog/zcash/src/pubkey.cpp:48: undefined reference to`CECKey::CECKey()'
/home/fer/prog/zcash/src/pubkey.cpp:49: undefined reference to `CECKey::SetPubKey(unsigned char const*, unsigned long)'
/home/fer/prog/zcash/src/pubkey.cpp:52: undefined reference to`CECKey::GetPubKey(std::vector<unsigned char, std::allocator<unsigned char> >&, bool)'
/home/fer/prog/zcash/src/pubkey.cpp:54: undefined reference to `CECKey::~CECKey()'
/home/fer/prog/zcash/src/pubkey.cpp:54: undefined reference to`CECKey::~CECKey()'
libbitcoin_common.a(libbitcoin_common_a-pubkey.o): In function `CPubKey::Derive(CPubKey&, uint256&, unsigned int, uint256 const&) const':
/home/fer/prog/zcash/src/pubkey.cpp:62: undefined reference to`BIP32Hash(uint256 const&, unsigned int, unsigned char, unsigned char const_, unsigned char_)'
/home/fer/prog/zcash/src/pubkey.cpp:64: undefined reference to `CECKey::CECKey()'
/home/fer/prog/zcash/src/pubkey.cpp:65: undefined reference to`CECKey::SetPubKey(unsigned char const_, unsigned long)'
/home/fer/prog/zcash/src/pubkey.cpp:66: undefined reference to `CECKey::TweakPublic(unsigned char const_)'
/home/fer/prog/zcash/src/pubkey.cpp:68: undefined reference to `CECKey::GetPubKey(std::vector<unsigned char, std::allocator<unsigned char> >&, bool)'
/home/fer/prog/zcash/src/pubkey.cpp:70: undefined reference to`CECKey::~CECKey()'
/home/fer/prog/zcash/src/pubkey.cpp:70: undefined reference to `CECKey::~CECKey()'
libbitcoin_common.a(libbitcoin_common_a-interpreter.o): In function`IsLowDERSignature':
/home/fer/prog/zcash/src/script/interpreter.cpp:174: undefined reference to `eccrypto::CheckSignatureElement(unsigned char const*, int, bool)'
libzcash.a(libzcash_a-JoinSplit.o): In function`libzcash::uint64_to_bool_vector(unsigned long)':
/home/fer/prog/zcash/src/./zcash/circuit/utils.tcc:45: undefined reference to `libzerocash::convertBytesVectorToVector(std::vector<unsigned char, std::allocator<unsigned char> > const&, std::vector<bool, std::allocator<bool> >&)'
libzcash.a(libzcash_a-JoinSplit.o): In function`libzcash::JSInput::JSInput()':
/home/fer/prog/zcash/src/zcash/JoinSplit.cpp:345: undefined reference to `libzcash::IncrementalMerkleTree<29ul, libzcash::SHA256Compress>::append(libzcash::SHA256Compress)'
libzcash.a(libzcash_a-JoinSplit.o): In function`std::vector<bool, std::allocator<bool> > libzcash::to_bool_vector<uint256>(uint256)':
/home/fer/prog/zcash/src/./zcash/circuit/utils.tcc:26: undefined reference to `libzerocash::convertBytesVectorToVector(std::vector<unsigned char, std::allocator<unsigned char> > const&, std::vector<bool, std::allocator<bool> >&)'
libzcash.a(libzcash_a-JoinSplit.o): In function`std::vector<bool, std::allocator<bool> > libzcash::to_bool_vector<uint252>(uint252)':
/home/fer/prog/zcash/src/./zcash/circuit/utils.tcc:26: undefined reference to `libzerocash::convertBytesVectorToVector(std::vector<unsigned char, std::allocator<unsigned char> > const&, std::vector<bool, std::allocator<bool> >&)'
libzcash.a(libzcash_a-JoinSplit.o): In function`libzcash::merkle_tree_gadget<libsnark::Fp_model<4l, libsnark::alt_bn128_modulus_r> >::generate_r1cs_witness(libzcash::MerklePath const&)':
/home/fer/prog/zcash/src/./zcash/circuit/merkle.tcc:53: undefined reference to `libzerocash::convertVectorToInt(std::vector<bool, std::allocator<bool> > const&)'
libzcash.a(libzcash_a-JoinSplit.o): In function`libzcash::IncrementalWitness<29ul, libzcash::SHA256Compress>::path() const':
/home/fer/prog/zcash/src/zcash/IncrementalMerkleTree.hpp:107: undefined reference to `libzcash::IncrementalWitness<29ul, libzcash::SHA256Compress>::partial_path() const'
/home/fer/prog/zcash/src/zcash/IncrementalMerkleTree.hpp:107: undefined reference to`libzcash::IncrementalMerkleTree<29ul, libzcash::SHA256Compress>::path(std::deque<libzcash::SHA256Compress, std::allocator<libzcash::SHA256Compress> >) const'
collect2: error: ld returned 1 exit status
make[2]: **\* [bitcoin-tx] Error 1
make[2]: Leaving directory `/home/fer/prog/zcash/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/home/fer/prog/zcash/src'
make: **\* [all-recursive] Error 1
fer@fer-pc-ubuntu:~/prog/zcash$

**Comment by s2925534** [comment]
Have you been able to fix this issue as its happening to me as well?

**Comment by daira** [comment]
Can you try again with a recent version of Zcash, please?

**Comment by ioptio** [comment]
Closing this since it was before launch, many things have changed. Make a new ticket if there is a related issue.
