### ISSUE TITLE
Finish the list of consensus changes for security auditors

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#1092]
The security auditors need the [list of consensus changes](https://github.com/zcash/zcash/wiki/Security-Auditor-Quick-Start#list-of-consensus-changes) to be finished before the audit can begin. It would also be nice if those bullet points linked to relevant code (in the security-review-frozen version).

**Comment by defuse** [comment]
@nathan-at-least: Check out this ticket for prioritization, it has to happen before the audit starts.

**Comment by bitcartel** [comment]
Added change to txids to the wiki page.

**Comment by daira** [comment]
Moved to https://github.com/zcash/zips/issues/58
