### ISSUE TITLE
Document that zcrawreceive does not check the spent serials map to ensure the note isn't spent

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#1095]
`zcrawreceive`is the raw interface for checking that you still have some value stored in a note. Therefore, it should check if the note given to it has already been spent. I can't find these checks, so I think they aren't there.

**Comment by nathan-at-least** [comment]
Note: #1096 should be in the same PR since they are both now documentation updates about the same topic.

**Comment by nathan-at-least** [comment]
We've decided *not* to add this documentation, so I've marked this "wontfix". There is *already* a deprecation warning in the live help output for the ``zcraw*`` commands, and we intend to have them removed by the Beta.
