### ISSUE TITLE
Document that zcrawreceive doesn't check correctness of note commitments

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#1096]
The current Zcash protocol spec says that decryption of a note by a recipient includes checking that the note commitment in the transaction was computed correctly. Our software doesn't do this, it just checks that the re-computed note commitment exists in the commitment set (which is similar, but not the same thing).

The zero-knowledge proof proves that the commitment was computed correctly, so why is it necessary for receivers do do this extra check?

If it is necessary, then is the way we re-compute the commitment and find *any* note commitment on the blockchain that matches it vulnerable to some attack?

**Comment by defuse** [comment]
The extra check is in the original paper, too: 1.(e) on page 19 is the same condition as Figure 4, Receive.3.b.ii.bullet-point-one.

**Comment by ebfull** [comment]
Our RPC is stateless, so we do not scan the blockchain for transactions where we are the recipients. If we did, we would perform that check. (We would *have* to, because the ciphertexts could have the wrong trapdoors.) Right now we're receiving the ciphertexts out of band, along with what we need to decrypt them, but we aren't told which transaction it appears in, so we cannot perform that check at all.

None of this arrangement of the RPC, including the format of the "buckets" printed by zcrawpour, appears in the protocol specification, and hopefully it will all be removed pending a design for the (stateful) payment API.

**Comment by defuse** [comment]
@ebfull: Doesn't the current zcrawreceive try to find the commitment in the commitment set built up from the blockchain?

**Comment by defuse** [comment]
(Note to self.) The check is necessary because the ciphertext is encrypted using an ephemeral key, so anyone could have made it, and the circuit *does not check* its contents. The check is to verify the correctness of those v rho and r, not to verify the correctness of the commitment in the blockchain (which *is* checked by the circuit).

**Comment by defuse** [comment]
Here's a better illustration of the potential problems. There are two things you might want to do:

1. Given your viewing key, find all the notes you own and determine how much money you have.
2. Given your viewing key and a set of notes (sent out of band), determine which of them you actually own and the total amount of money you have.

The intended purpose of `zcrawreceive` as far as I know is to help with (2). But you can't solve (2) using `zcrawreceive` when you have more than one note. 

Trivial counterexample: Both notes are the same, and `zcrawreceive` will tell you they're both valid and have value, so you add their values together and think you have twice as much money as you do.

More complicated counterexample: Mallory deliberately sends two different encryptions of the same v, rho, and r to Alice so that they look like different notes to her, and she can't tell she really only owns one note using `zcrawreceive`.

In short, `zcrawreceive` API doesn't provide enough functionality. It needs to take a list of notes and (at least) ensure all of their commitments are distinct.

**Comment by defuse** [comment]
We can address this usable security problem as part of the payment API milestone. 

It's a usable security problem because the `zcrawreceive` API lends itself to being used in an insecure algorithm: pass all of your note ciphertexts to it in series and add up the valid ones' values.

**Comment by defuse** [comment]
Evidence it's a problem: @str4d's wallet scripts do exactly that: https://github.com/zcash/zcash/pull/772/files#diff-c890e56a845c16a5caeb75ac74cc7c6bR26

**Comment by str4d** [comment]
Yes. I totally did that to exemplify this issue. Yup.

**Comment by nathan-at-least** [comment]
Note: We plan to deprecate all of the current ``zcraw*`` interface calls in the z9 release (in favor of the upcoming RPC interface) and we will remove it as part of the z10 Beta release so that new Beta users will not get confused.

**Comment by bitcartel** [comment]
Related: #1137 has been merged, to inform users that zcraw* are being deprecated very soon.

**Comment by nathan-at-least** [comment]
We've decided not to add this documentation, so I've marked this "wontfix". There is already a deprecation warning in the live help output for the zcraw* commands, and we intend to have them removed by the Beta.
