### ISSUE TITLE
Include semantic purpose in the protocol / variable names.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#110]
An example is [``hashZerocoinMerkleRoot``](https://github.com/Electric-Coin-Company/zerocashd/blob/get_being_strange-0.9.4-1/src/core.h#L458), which describes the data structure, but not its purpose. We suspect this tree stores coin commitments, so a name like ``zerocashCommitmentsMerkleRoot`` would clarify that.

Note: Upstream bitcoin has the same naming problem with ``hashMerkleRoot``. As we include more and more Merkle trees, this naming scheme becomes more and more ambiguous.

(Side note: If we had a specific type for representing Merkle tree roots, then the field name could be simplified even further to ``zerocashCommitments`` since the type would be called ``MerkleTreeRoot`` or something similar.)

**Comment by daira** [comment]
We completely rewrote the code since this ticket was filed, and I don't think we have any systematic problem with naming that justifies keeping the ticket open.
