### ISSUE TITLE
z7 release

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#1100]

**Comment by ebfull** [comment]
Public alpha guide needs to be updated with the new RPC language.

**Comment by daira** [comment]
Done in https://github.com/zcash/zcash/wiki/Public-Alpha-Guide-z7 (this can just replace https://github.com/zcash/zcash/wiki/Public-Alpha-Guide when we're ready).

**Comment by ebfull** [comment]
Thanks!
