### ISSUE TITLE
Rename CZC{SpendingKey,PaymentAddress} to CBase58{SpendingKey,PaymentAddress}

### ISSUE THREAD

**Issue by daira** [zcash/zcash#1102]
These derive from `CBase58Data` and specifically represent Base58 encodings, so I think the latter names would be clearer.

**Comment by str4d** [comment]
I'm happy to make a PR for this, but given that we already have `class CBitcoinAddress : public CBase58Data` and `class CBitcoinSecret : public CBase58Data`, I'm +0 on the idea. Personally I'd either rename `CZC{}` to `CZcash{}`, or rename `CBitcoin{}` to `CBase58Transparent{}` in addition to this change.

**Comment by rex4539** [comment]
If you decide which approach to follow, I can make the PR.

**Comment by daira** [comment]
All of the `CZC*` classes appear to have been removed in #3242, so this issue can be closed.
