### ISSUE TITLE
Shut down the zcash-dev mailing list

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#1108]
From the public slack:

@daira: "The zcash-dev mailing list is almost dead (it had only had a single substantive thread, and blog post announcements, since April). This is a problem because it's another forum to keep track of, that doesn't justify the cost of keeping track of it
5:03 I propose that we close it and use github tickets for anything that would otherwise have been posted to zcash-dev"

@zooko: "Yes, let's shut down the zcash-dev mailing list and direct people to https://github.com/zcash and https://forum.z.cash."

**Comment by zookozcash** [comment]
Please preserve the publicly-visible archives.

**Comment by defuse** [comment]
Let's put the archives on `z.cash` so that we don't need the `zca.sh` domain for anything anymore.

**Comment by defuse** [comment]
I unassigned myself since we have the awesome @ageis to help with this. :-)

**Comment by ageis** [comment]
GNU mailman has been uninstalled and [lists.z.cash](https://lists.z.cash) / lists.zca.sh simply serves the zcash-dev archives.
