### ISSUE TITLE
Disambiguate the ``Zcash Core codebase`` label between code/implementation-specific issues and protocol issues.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#111]
There used to be a label named ``zerocashd``. I was conflating codebase / implementation issues from protocol issues, so:

* I renamed ``zerocashd`` → ``zerocashd codebase``, and
* I added ``consensus protocol`` (disambiguated from things like rpc protocol or network protocol unrelated to consensus).

Now we need to [revisit all the ``zerocashd codebase`` tickets](https://github.com/Electric-Coin-Company/zerocashd/labels/zerocashd%20codebase) and see if they're actually relevant to ``consensus protocol`` and/or the ``zerocashd codebase``

**Comment by daira** [comment]
Done.
