### ISSUE TITLE
Use higher paralellism -jN on CI builds now that they run on a fast EC2 server

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#1110]
If we're using a c4.2xlarge then I think it would be faster to change it to -j6 or -j8.

**Comment by defuse** [comment]
The whole build.sh process only takes 6 minutes now, so this is probably irrelevant.

**Comment by zookozcash** [comment]
Disagree. 3 minutes would be _much_ better than 6 minutes in terms of developer productivity imho.

**Comment by ebfull** [comment]
Done in https://github.com/Electric-Coin-Company/bbotzc/pull/22
