### ISSUE TITLE
Change `zc.v0.11.2.latest` to `master`

### ISSUE THREAD

**Issue by ebfull** [zcash/zcash#1114]
I think we may have outgrown this convention. Are we still likely to track upstream changes on a version-by-version basis? That may not either be practical or safe. `zc.v0.11.2.latest` seems less likely to meaningfully distinguish code, and more likely to confuse people, since it contains its own version semantics independent from our project.

`master` is more conventional, easier to remember and type, and doesn't pin us to a particular release or development policy.

**Comment by daira** [comment]
Independent but complementary: let's decouple our version number from the upstream version (#1138).

**Comment by ebfull** [comment]
I'm moving this to "engineering meeting agenda" because we haven't made a decision about whether to do this or not.

**Comment by daira** [comment]
I'm in favour. We're likely to be pulling in changes from upstream on a piecemeal basis (as we already did for the DoS mitigation in #1258), so there will be no exact upstream version that our code is derived from.

**Comment by nathan-at-least** [comment]
Yes, let's do this for the Beta 1 release. I'm removing it from the agenda.

**Comment by daira** [comment]
Fixed; master is now the default branch on github.
