### ISSUE TITLE
Remove SignatureHashOld test

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#1117]
We don't really care about backwards compatibility, so maybe we don't need this copy-pasted old version of SignatureHash.

**Comment by defuse** [comment]
Assigning to @nathan-at-least to prioritize/deprioritize.

**Comment by nathan-at-least** [comment]
Acknowledged.

**Comment by nathan-at-least** [comment]
Let's not remove tests until we know we want to remove the code under test, so this is wontfix.
