### ISSUE TITLE
Test the thing that was once tested using the SIGHASH_SINGLE bug before we fixed the latter bug

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#1118]
#1088 removed some sort of test coverage, whatever it is this comment describes, because it was using the SIGHASH_SINGLE bug to make the testing work:

> The following two tests after fixing SIGHASH_SINGLE bug. Finally CHECKMULTISIG removes all signatures prior to hashing the script containing those signatures. In conjunction with the SIGHASH_SINGLE bug this lets us test whether or not FindAndDelete() is actually present in scriptPubKey/redeemScript evaluation by including a signature of the digest 0x01 We can compute in advance for our pubkey, embed it it in the scriptPubKey, and then also using a normal SIGHASH_ALL signature. If FindAndDelete() wasn't run, the 'bugged' signature would still be in the hashed script, and the normal signature would fail."

**Comment by daira** [comment]
There is no `FindAndDelete` in Zcash. That is, the thing that was being tested was something we removed entirely ([spec for the removal](https://zips.z.cash/protocol/protocol.pdf#scripts)) in #1458 ([here](https://github.com/zcash/zcash/pull/1458/files#diff-93c5ddf703879287802d651b68c9c6199644afe23db0dd3ff77e8d1ce3c20045L546)).
