### ISSUE TITLE
Review all uses of block and block header types for ZC commitment / serial storage.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#112]
First step is to catalogue which types add a field to track ZC.  Some of these include [``CBlockIndex``](https://github.com/Electric-Coin-Company/zerocashd/blob/get_being_strange-0.9.4-1/src/main.h#L694) and [``CBlockHeader``](https://github.com/Electric-Coin-Company/zerocashd/blob/get_being_strange-0.9.4-1/src/core.h#L447)

**Comment by daira** [comment]
This ticket is obsolete.
