### ISSUE TITLE
Turn non-locally-verifiable asserts in libsnark into exception throws

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#1125]
For #459 and #69 we only did this for asserts that can get triggered in the verifier. It's a lot more work to do this for all of the other parts of libsnark that we use.

**Comment by nathan-at-least** [comment]
Since the verifier is the "most exposed" attack surface, and we've already done this transition for the verifying path, this isn't necessary for our z8 release. We put it in z9 because it fits with the theme of audit mitigation, test improvements, general hardening.

**Comment by daira** [comment]
I would like this in 1.0, because I don't think there is a well-defined distinction between parts of libsnark that can be affected by network input, and parts that aren't (e.g. there could be an on-line service that did proving). So it would be harder to check that we'd found all such asserts than to change all asserts to throws.

**Comment by ebfull** [comment]
The only assertions left in our fork, that I can see, are:

* Assertions in parameter initialization (no surface area of attack from the network)
* Assertions in zkSNARK parameter generation (no surface area of attack from the network)
* Assertions in profiling code (disabled when zcashd opens, no surface area of attack from the network)
* Assertions in tests (as intended)
* Assertion in Fp3 (which we don't use)
* Assertions in merkle tree data structure in libsnark (no surface of attack from the verifier, and unlikely to be any from the prover)
* Other r1cs circuit construction and proving code (just like the previous point, no surface area of attack from the verifier, unlikely any from the prover)
* Something in the zkSNARK verifier that is, from what I can tell, locally enforced.

I would be fine with what we have for 1.0, but I can turn all of these into exceptions if you aren't convinced.

**Comment by nathan-at-least** [comment]
Let's do this after we launch.

**Comment by tromer** [comment]
The corresponding issue upstream is https://github.com/scipr-lab/libsnark/issues/64 .
