### ISSUE TITLE
Add fee selection to high-level RPC interface

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#1128]

**Comment by nathan-at-least** [comment]
I just punted this from z9 into Beta 1. For z9, let's just use a constant fee, and if the incoming notes can't cover the constant fee plus the outgoing destination value, throw an exception (or somehow signal the error appropriately).

**Comment by nathan-at-least** [comment]
The current fee selection is incredibly simplistic and just uses a constant and users cannot change that except by recompiling. Unfortunately, we need to focus on security for the 1.0 release, and we can fix this after that.

**Comment by daira** [comment]
See also #398. Note that a constant fee for private transactions might be desirable for indistinguishability reasons.

**Comment by bitcartel** [comment]
Closing this ticket.  Issue #1903 added a fee parameter to the to z_sendmany RPC interface.
