### ISSUE TITLE
Check that Equihash uses SIMD implementation of BLAKE2b

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#1130]
Suggested in [#857 (comment)](https://github.com/zcash/zcash/issues/857#issuecomment-228692047) by @solardiz.

**Comment by str4d** [comment]
Currently, Equihash uses the following functions from libsodium:

```
crypto_generichash_blake2b_init_salt_personal()
crypto_generichash_blake2b_update()
crypto_generichash_blake2b_final()
```

These are [nicer wrappers](https://github.com/jedisct1/libsodium/blob/master/src/libsodium/crypto_generichash/blake2/ref/generichash_blake2b.c) around the [internal API](https://github.com/jedisct1/libsodium/blob/master/src/libsodium/crypto_generichash/blake2/ref/blake2.h).

The specific implementation used is determined by `blake2b_pick_best_implementation()` ([source](https://github.com/jedisct1/libsodium/blob/master/src/libsodium/crypto_generichash/blake2/ref/blake2b-ref.c#L427)), which is called in `sodium_init()` ([source](https://github.com/jedisct1/libsodium/blob/29492143ab6aeb3ad160903f10f407d665f0e6aa/src/libsodium/sodium/core.c#L38)). We are [definitely calling this in `zcashd` and `zcash-cli`](https://github.com/zcash/zcash/blob/zc.v0.11.2.latest/src/init.cpp#L909), but I was not calling it in my [standalone miner](https://github.com/str4d/zcash/tree/standalone-miner). I have [fixed this](https://github.com/str4d/zcash/commit/bbabd70d8d165e63e6b8b57493cb5358a9cbdb1e), and doing rough interrupts of the standalone miner, I see that `blake2b_compress_sse41` is now being used on my laptop. I am going to assume that the actual miner in `zcashd` will pick the same implementation on the same hardware, and thus has already been doing so, which in theory negates this issue.

@solardiz, does this seem like a reasonable resolution to you? If none of the implementations in libsodium will ever be suitable on our target hardware, the best resolution for this is probably to submit a PR to libsodium adding one that is.

**Comment by solardiz** [comment]
On Thu, Jul 21, 2016 at 08:52:10PM -0700, str4d wrote:
> @solardiz, does this seem like a reasonable resolution to you?

Yes, it sounds (from your comment; I didn't review the code yet) like it should work right, but I recall interrupting zcashd (not only the standalone miner) in gdb and seeing it use the reference, non-SIMD implementation of BLAKE2b before. So there's probably some detail we're missing. Need to re-test this in zcashd and see what it uses now.

**Comment by nathan-at-least** [comment]
@solardiz are you following up on this?

**Comment by solardiz** [comment]
@nathan-at-least Yes, I intend to experiment with latest zcashd soon, for other reasons, and while at it also see what BLAKE2b implementation it actually uses and post a comment in here.

**Comment by zookozcash** [comment]
Looks like this was a bug that has been fixed in the latest version of libsodium: https://github.com/jedisct1/libsodium/releases/tag/1.0.11

**Comment by solardiz** [comment]
The libsodium 1.0.11 changelog talks specifically about AVX2, whereas we were talking about scalar vs. (any) SIMD.  So it's related but different.  Anyway, we should in fact be building against libsodium 1.0.11+ to take advantage of this bugfix as well.

**Comment by defuse** [comment]
I opened a pull request to upgrade libsodium: #1268. I'm changing this ticket's assignment to @solardiz per https://github.com/zcash/zcash/issues/1130#issuecomment-238648331. Please assign it back to me if you'd rather me do it.

**Comment by defuse** [comment]
Oops, @solardiz doesn't appear in the list of people I can assign, so I'll leave it unassigned.

**Comment by nathan-at-least** [comment]
@str4d, @solardiz: the outcome of this ticket only affects performance, and nothing visible in the byte-wise protocol (disregarding timing), correct?

I've moved it to post 1.0.0 based on assuming that is true.

**Comment by solardiz** [comment]
On Mon, Sep 12, 2016 at 01:20:38PM -0700, Nathan Wilcox wrote:
> @str4d, @solardiz: the outcome of this ticket only affects performance, and nothing visible in the byte-wise protocol (disregarding timing), correct?

That's correct.

**Comment by daira** [comment]
We currently [build against libsodium 1.0.11](https://github.com/zcash/zcash/blob/master/depends/packages/libsodium.mk). Can this ticket be closed, or was there something else to do?
