### ISSUE TITLE
Combine sorting and collision steps in Equihash solver

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#1132]
The current solvers (basic and optimised) operate in two steps each round:
- Sort the current round's list using `std::sort` (which uses a quicksort variant).
- In a single pass, transform the list into the next round's list.

We suspect that we will get a speed increase by combining these two steps, and using a bucket or proxmap sort (because the elements, being XORs of hashes, should be relatively uniformly-distributed).

**Comment by str4d** [comment]
This should also help to address the peak memory usage spike we are seeing [on the CI server ](http://ci.leastauthority.com:8010/builders/zcashperformance/builds/102/steps/memory%20solveequihash/logs/stdio). I believe the spike (which I don't see locally, but is [consistently visible at 2x or 3x the memory usage of the earlier rounds](https://speed.z.cash/timeline/?exe=1&base=1%2B43&ben=memory+solveequihash&env=1&revs=50&equid=off&quarts=on&extr=on)) is caused by the `std::vector` reallocating at the end of the second-to-last round, because the entire ~440MB array must be reallocated if it can't be extended. If we moved to a bucket sort, the main array becomes fixed-length array (with `2^(n/(k+1))` buckets). This removes the chance of large reallocations - but only if we also can recreate the single-pass behaviour.

The authors' implementation uses a bucket sort, but in each round it fills a parallel array of buckets and then uses that in the next round, which doubles the peak memory. To be able to make this single-pass, we would need a way to distinguish between existing entries from the current round and new entries from the next round. The most efficient way I can see to do this is to add one byte per `StepRow` to store its round number. Since `StepRow` is statically initialised at the peak row length, this will add 1 byte for every element. For both `n = 96, k = 3` and `n = 144, k = 5`, that is an additional 32MB on average, which I think is acceptable.

We can then handle the buckets in two ways:

- Fixed-length buckets that can be statically initialised, but either the buckets are too large (wasting memory), or mid-stage entries get dropped (potentially reducing the average number of solutions), or both.
- `std::vector` buckets, which can dynamically resize as necessary, but increases the memory usage by `2^(n/(k+1)) * 3 * 64bit` (three pointers per `std::vector`). For both `n = 96, k = 3` and `n = 144, k = 5`, that is an additional 384MB, which is a considerable overhead.

Incidentally, the authors' implementation uses `std::vector`, but in a fixed-length manner.

**Comment by str4d** [comment]
There's another optimisation we can leverage (from the authors' implementation) by using bucket sort: because there is one bucket for every collision group, we don't actually need to store the first `n/(k+1)` bits of the hash when we insert into the bucket. This saves us 3 bytes per `StepRow`, which means we can fit in the round flag byte and still save 64MB on average! Whether this makes up for the wasted space from empty buckets is another question, but at least the flag cost can be absorbed.

**Comment by nathan-at-least** [comment]
Note: This is a specific optimization that came out of #857.

**Comment by str4d** [comment]
I have a local implementation of this that has been mostly working since Monday - it returns the expected solutions, along with many invalid ones. After not making any progress finding the bug, today I wrote [a tool for visualising Equihash solutions](https://github.com/str4d/zcash-pow/blob/master/print-soln.py). Besides looking very pretty :smile: it showed that the solver was working correctly up until the final round, where it was only colliding half of the `2n/(k+1)` bits in the final round (the bits that weren't converted into a bucket index).

**Comment by bitcartel** [comment]
@str4d Moving this to z9.  Ticket is either closed due to recent commits for z8, or is part of ongoing improvments.

**Comment by nuttycom** [comment]
No longer relevant, can be reopened if someone feels inspired to actually do it.
