### ISSUE TITLE
libsnark: API design change or convention to make silent "use before witnessing" impossible

### ISSUE THREAD

**Issue by daira** [zcash/zcash#1136]
On [#920](https://github.com/zcash/zcash/issues/920#issuecomment-233811236), @ebfull wrote:

> During witnessing, gadgets sometimes use outside variables to inform them about how they should witness their own variables. This is fine, but if those "outside variables" have not been witnessed themselves, your witness might be wrong when those outside variables are witnessed later (changing them), which could violate the constraint system.
> 
> In bellman, I avoid this issue using witness groups; gadgets are only instructed to witness when all of their "input variables" have been witnessed already. This has the added advantage of allowing all gadgets in a group to be witnessed in parallel.

Changing to how bellman does it might be too disruptive, but if I am understanding the problem correctly, it should be possible to assert that an outside variable has already been witnessed before it is used (making this case a reported error rather than a silent failure).

**Comment by nathan-at-least** [comment]
I took this off the meeting agenda and assigned Daira and Sean to figure out how feasible / useful this change would be.
