### ISSUE TITLE
Equihash: figure out why increasing k decreases # of solutions found.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#1142]
This is came out of a discussion about #857.

This is a blocker for parameter selection choices: #856.

**Comment by daira** [comment]
According to the proof of Proposition 1 in the Equihash paper, we should expect 2<sup>n/(k+1) + 1</sup> tuples after each round before the last. We should first check whether this expectation actually holds.

**Comment by nathan-at-least** [comment]
Cross link to #2715

**Comment by daira** [comment]
This is explained in section 3.1 of [Alcock and Ren 2017](http://sci-hub.tw/10.1145/3140649.3140652), "A Note on the Security of Equihash".

**Comment by daira** [comment]
![image](https://user-images.githubusercontent.com/643204/50868764-ec376e80-13a8-11e9-83e5-3e74a4ccbfe5.png)
