### ISSUE TITLE
Fix transaction malleability

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#1145]
PR #1101 demonstrated a minimal solution to tx malleability.  Should be closed.

PR #1144 is a new solution based on suggestions from advisor @gavinandresen.  Needs review.

**Comment by zookozcash** [comment]
You should give credit to the advisor by name.

**Comment by zookozcash** [comment]
(/blame)

**Comment by bitcartel** [comment]
#1144 has been merged.
