### ISSUE TITLE
Make "zcbenchmark solveequihash" take a number-of-threads argument

### ISSUE THREAD

**Issue by daira** [zcash/zcash#1147]
Currently the benchmark is always single-threaded. Multi-threaded mining performance can't be inferred from single-threaded performance, since memory bandwidth shared between cores is a significant constraint.

Note that this is about benchmarking what the effect of genproclimit would be, not making the solver internally multithreaded.

**Comment by Voluntary-zcash** [comment]
Where more than one is available, is it possible to select memory channels via the OS or compiler?

**Comment by nathan-at-least** [comment]
@str4d can you work on this as part of z8 or is your plate already full? It would be nice to have historical benchmarks for multiple threads.

**Comment by str4d** [comment]
I have this implemented locally, but I can't test it because I can't figure out where the `zcbenchmark` inputs are typecast (that is, I can't figure out how to interpret an int input to the RPC as an int instead of a str).

**Comment by str4d** [comment]
Adding to z8 because I have had time for this.
