### ISSUE TITLE
Equihash: remove constraint that n/(k+1) is a multiple of 8

### ISSUE THREAD

**Issue by daira** [zcash/zcash#1148]
I think this will be necessary to choose parameters that solve the time-to-solution problem.

**Comment by nathan-at-least** [comment]
This is related to #1142.

**Comment by nathan-at-least** [comment]
Let's *not* do this *until* these conditions are met:

- we have some latency criteria based on #764,
- we've tried the #1132 optimization and it doesn't meet the above criteria, so we've decided to change parameters,
- we've explored #1142 and determined that this ticket is necessary.
