### ISSUE TITLE
Document all tunables which are different from upstream and estimate their resource impact.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#115]
There are many cases of tunable changes (where the tunable parameters overlap with upstream Bitcoin in contrast to ZC-specific tunables).  Two examples are max script size and max script element size.

Sometime after we are nearing a fully functional MVP prototype, let's review all tunables, estimate resource requirements, compare to Bitcoin, and document it all.

**Comment by ebfull** [comment]
* block size #765 
* difficulty adjustment #147 
* average block interval #764 
* depth of tree #16 

Nothing else has been tuned nor do we plan to tune them.

**Comment by zookozcash** [comment]
Other things we'll need to change:
* FOUNDERS_REWARD_AMOUNT_PER_BLOCK
* FOUNDERS_REWARD_UNTIL_BLOCK
both from https://github.com/zcash/zcash/issues/125
