### ISSUE TITLE
#826 audit: Possible undesired interaction between bitcoin and zcash nework

### ISSUE THREAD

**Issue by arcalinea** [zcash/zcash#1151]
As mentioned in #826 , look for things that create undesired interaction between the bitcoin network and our network, e.g. leads to zcash nodes trying to connect to bitcoin nodes, or leads to zcash nodes' IP addresses being broadcast on the bitcoin network

**Comment by daira** [comment]
I believe the ``pchMessageStart`` and minimum protocol version changes make this impossible.
