### ISSUE TITLE
#826 audit: make partial blockchain torrent available for zcash?

### ISSUE THREAD

**Issue by arcalinea** [zcash/zcash#1153]
With bitcoin you can download a partial blockchain with bittorrent to get your node going. Do we want to host a torrent for zcash?

**Comment by indolering** [comment]
I think the throughput issues that led to torrent distribution of the Bitcoin blockchain early-on have been fixed.  I believe it had to do with verifying the entire chain while downloading, but it was explained to me a looong time ago on IRC so my memory might be incorrect.

**Comment by WyseNynja** [comment]
This shouldn't be necessary. https://bitcoin.org/bin/block-chain/README.txt:

> As of Bitcoin Core version 0.10.0 and later, the block chain bootstrap
torrent hosted here takes more time to download and import than it would
to simply start Bitcoin Core and let it sync itself.
> Forum thread on BitcoinTalk:
> https://bitcointalk.org/index.php?topic=145386.0

**Comment by russianboss69** [comment]
https://mega.nz/#!HSJByCzI!Wgqy_xoWWEyXGkp4rCot4y5fXmH4LRFIIhKR317Zd_c
Zcash Blockchain (12.7 Gb.)
Blocks: 565659
Date: 2019.07.11

for use, simply replace the folders "blocks" and "chainstate" in "C:\Users\Home\AppData\Roaming\Zcash"
