### ISSUE TITLE
P2P distribution of proving parameters

### ISSUE THREAD

**Issue by arcalinea** [zcash/zcash#1155]
As noted in #826 , right now do not have P2P distribution of the proving parameters, might overload our webserver (or huge S3 bill since they're on S3). Solution: P2P distribution?

**Comment by indolering** [comment]
Use Archive.org, they offer Torrents for all uploaded materials and act as an HTTP seed.

**Comment by nathan-at-least** [comment]
This would be nice to have. Do away with ``fetch-params.sh`` altogether, and new nodes fetch the params from peer nodes, just as they do for the blockchain. It would complicate node startup somewhat, because some RPC commands would need to fail with a "params downloading" indicator.

**Comment by nathan-at-least** [comment]
The need for a new wallet state (fetching params) is very similar to #432.

**Comment by str4d** [comment]
It shouldn't be hard to add a new pair of messages to request and return some chunk of the proving key. The desired proving key's version, size, and hash (and probably hashes of the chunks, like in torrent files) would be hard-coded into the software for authentication. We'd also want a "don't have this proving key" reply message (or flag in the reply, depending on how other network messages are already implemented). The trick is in making sure we don't add any DoS vectors over what is already possible with e.g. `getheaders`.

**Comment by str4d** [comment]
@zookozcash pointed out that this is not in 1.0.

**Comment by jasondavies** [comment]
> It shouldn't be hard to add a new pair of messages to request and return some chunk of the proving key.

Is this something that could be supported by adding a new [inventory type](https://en.bitcoin.it/wiki/Protocol_documentation#Inventory_Vectors) and reusing the existing getdata/inv messages, or would it be simpler to add new message types?

**Comment by daira** [comment]
This would be mostly obviated by #3933 / #6661. For the remaining optional use of `sprout-groth16.params` there is not sufficient justification to implement this issue.
