### ISSUE TITLE
Add a standalone miner suitable for use as a subprocess, e.g. from P2Pool

### ISSUE THREAD

**Issue by daira** [zcash/zcash#1156]
Proposed protocol: the miner reads a hex-encoded block header (up to but not including the nonce), terminated by newline, from stdin. It then continuously outputs solutions, also hex-encoded and terminated by newlines, on stdout.

If a new header is sent on stdin, the miner cancels the current solution attempt and restarts mining with that header. Solutions are full block headers -- this includes the prefix up to the nonce, which the client process should check, in order to avoid a race condition where it submits a new block header and then reads a solution for the previous header.

An alternative design would be to  start a new process per header, but that would be slightly more expensive due to process creation and startup overhead.

**Comment by bitcartel** [comment]
This seems like a good candidate for being written in Rust and serve as a training wheel for developers looking to grow skills in that area.

**Comment by daira** [comment]
An implementation in Rust would be great, but I feel some urgency in supporting p2p mining to avoid centralised mining pools becoming established (which has been disastrous for the decentralisation of Bitcoin IMHO, although ASIC-friendliness is also a factor there). Therefore I think that  it would be a good strategy to simply call the existing C++ mining code for the time being.

**Comment by sammy007** [comment]
> being written in Rust

Bullshit.

> An implementation in Rust would be great

Same.

> Therefore I think that it would be a good strategy to simply call the existing C++ mining code for the time being.

Brilliant. Zcash need just minerd to work with rpc.

**Comment by ebfull** [comment]
@sammy007 Comments like that are not very useful or appropriate.

**Comment by sammy007** [comment]
> Comments like that are not very useful or appropriate

Because it uncovered incompetence and vaporware addiction. If you don't wanna screw initial distribution you will listen, but I doubt if anyone care.

**Comment by daira** [comment]
I deleted comments by \@sammy007 that were a violation of the Code of Conduct (and one reply to them).

**Comment by nuttycom** [comment]
Not relevant given the existence of ASIC miners.
