### ISSUE TITLE
RPC test listtransactions.py hangs if the test harness throws an error

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#1161]
See the following example caused by the `generate` RPC returning an error:

http://ci.leastauthority.com:8010/builders/zcash/builds/268/steps/rpc-tests.sh/logs/stdio

I have been able to reproduce this locally, with the bug mentioned in #1146.

**Comment by str4d** [comment]
Note that if you manually cancel the RPC tests and restart them, `listtransactions.py` fails correctly, ie. `rpc-tests.sh` continues on to the remaining tests (which all fail too). If the `cache/` dir is deleted (as is the case on the CI server, which runs the RPC tests from a clean workdir), the behaviour reappears.

**Comment by nuttycom** [comment]
Closing as obsolete; reopen this if we observe flakiness in listtransactions.py.
