### ISSUE TITLE
Consider a deterministic build process using Bazel and NixOS

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#1163]
Many users want to install binaries #1034 and some of those users will want to verify those binaries through a deterministic build process #540 where the results are reproducible i.e. every byte is the same.  

If upstream's Gitian build system is not used, an alternative approach might be to consider:
- Bazel (from Google) for reproducible builds: http://www.bazel.io/

and maybe:
- NixOS for a reproducible Linux system configuration: https://nixos.org/

**Comment by nathan-at-least** [comment]
We're favoring gitian instead of this, so it's off the roadmap.
