### ISSUE TITLE
Fix compile flag issue where -O2 is still being used

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#1168]
Continuation of work from #1064.

Also document whether -O1 is to be used globally, including all dependencies and sub-projects such as leveldb and secp256k1.

**Comment by defuse** [comment]
At least some of the dependencies use -O2. I think we should let upstream package maintainers decide which optimization level to use, and not override their decisions.

**Comment by defuse** [comment]
Problems with the build system I want to fix for this ticket:

- Fix -O1, -O0, and -O2 all showing up in our build.
- Look at -fwrapv, -fno-strict-aliasing
- add CXXFLAGS and LDFLAGS for the libzcash build, and make sure they have all the same hardening options. Make sure the `-W...` flags are in the right one.

**Comment by defuse** [comment]
Parts of bitcoin like libsecp256k1 and leveldb add their own -O2:

```
src/secp256k1/configure
3828:    CFLAGS="-g -O2"
3834:    CFLAGS="-O2"
```

```
src/leveldb/Makefile
10:OPT ?= -O2 -DNDEBUG
14:# OPT ?= -O2 -g2 -DNDEBUG
```

**Comment by defuse** [comment]
The other `-O2` is coming from `src/Makefile`:

```
src/Makefile
1301:CFLAGS = -pipe -O2 
1318:CXXFLAGS = -std=c++11 -pipe -O2 -Wno-deprecated-declarations -Wno-placement-new -Wno-terminate -Werror -O1 -g  -Wstack-protector -fstack-protector-all -fPIE
1379:OBJCXXFLAGS = -std=c++11 -pipe -O2 -Wno-deprecated-declarations -Wno-placement-new -Wno-terminate -Werror -O1 -g  -Wstack-protector -fstack-protector-all -fPIE
```

`src/Makefile` is generated from `src/Makefile.in` which is generated from `src/Makefile.am` but there's no `-O2` in either of those files. Maybe I just need to regenerate it.

**Comment by defuse** [comment]
I think the other -O2 is coming from automake's defaults.

**Comment by defuse** [comment]
Docs: https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/C_002b_002b-Compiler.html

> If output variable CXXFLAGS was not already set, set it to -g -O2 for the GNU C++ compiler (-O2 on systems where G++ does not accept -g), or -g for other compilers. If your package does not like this default, then it is acceptable to insert the line ‘: ${CXXFLAGS=""}’ after AC_INIT and before AC_PROG_CXX to select an empty default instead.

**Comment by defuse** [comment]
Ahhhhh, it's coming from `depends/hosts/linux.mk`:

```
linux_release_CFLAGS=-O2
```

**Comment by defuse** [comment]
For review: #1270.
