### ISSUE TITLE
Write methods for byte array expansion and contraction

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#1175]
We need methods that can convert between:

- A byte array of length `NL/8`, and
- An array of `N` blocks of `ceil(L/8)` bytes.

These methods should then be used to:

- Expand the BLAKE2b output in the Equihash solver (instead of using a larger output and masking the unused bits).
- Store the Equihash solution in minimal representation in the block header.

**Comment by str4d** [comment]
Two ways this could be implemented:

- Direct bit-shifting of the byte array.
  - This would require very careful bit handling to handle the various parameter options.
- Union of the byte array and a bitfield struct (see [here](http://blog.codef00.com/2014/12/06/portable-bitfields-using-c11/) for a portable bitfield implementation).
  - This would require using macros or somesuch to create the `2^K` bitfields in the struct.

**Comment by daira** [comment]
I prefer the former.
```
#!/usr/bin/python

word_size = 32
word_mask = (1<<word_size)-1

def convert(inp, inp_bits):
    inp_bits = 21;
    assert inp_bits >= 8 and word_size >= 7+inp_bits

    # The acc_bits least-significant bits of acc_value represent a bit sequence in big-endian order.
    acc_bits = 0;
    acc_value = 0;

    outlen = inp_bits*len(inp)/8;
    out = [0]*outlen

    j = 0
    for i in xrange(outlen):
        # When we have fewer than 8 bits left in the accumulator, read the next input element.
        if acc_bits < 8:
            acc_value = ((acc_value << inp_bits) & word_mask) | inp[j]
            j += 1
            acc_bits += inp_bits

        acc_bits -= 8
        out[i] = (acc_value >> acc_bits) & 0xFF

    return out

# example from spec
print convert([69-1, 42-1, (1<<21)-1], 21)
```

**Comment by daira** [comment]
@str4d wrote:
> Expand the BLAKE2b output in the Equihash solver (instead of using a larger output and masking the unused bits).

Note that the current spec (on the zips2.reorganisation.0 branch) specifies that exactly ceiling(512/n) elements are obtained from each hash output, which simplifies this step.

**Comment by str4d** [comment]
And the corresponding method for expansion:

```python
def expand_bits(inp, bit_len):
    assert bit_len >= 8 and word_size >= 7+bit_len
    bit_len_mask = (1<<bit_len)-1

    # The acc_bits least-significant bits of acc_value represent a bit sequence in big-endian order.
    acc_bits = 0;
    acc_value = 0;

    outlen = 8*len(inp)/bit_len;
    out = [0]*outlen

    j = 0
    for i in xrange(len(inp)):
        acc_value = ((acc_value << 8) & word_mask) | inp[i]
        acc_bits += 8

        # When we have bit_len or more bits in the accumulator, write the next output element.
        if acc_bits >= bit_len:
            acc_bits -= bit_len
            out[j] = (acc_value >> acc_bits) & bit_len_mask
            j += 1

    return out
```

**Comment by str4d** [comment]
I have implemented the expansion and compression methods, and updated the hash generation to match the spec. Final task before I make the PR is to change the solution form. I'm thinking that I will have the solver output the solutions in minimal form, to minimise conversions on the hot path. For unit tests, I will convert the minimal representation to indices (which is three rounds of conversions: array -> minimal -> array -> indices) for readability, because performance doesn't matter there.

**Comment by daira** [comment]
@str4d: I guess #1260 does not yet include the bug fix we found in our pairing on Monday?

**Comment by str4d** [comment]
@daira yes it does; #1260 should be ready for review. Unless you're seeing another problem?

**Comment by daira** [comment]
Oh ok. I was confused by the commit dates since I thought they were before our pairing, and also I was expecting either an extra commit fixing the bug, or a note on the PR saying it had been force-pushed or superseded another PR.

I'll review it now.
