### ISSUE TITLE
Write unit tests for to cover verification of Minted coin value = base TxOut value.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#118]
I just realized even after an individual code review pass, I don't know the answer to this question. For now I won't pester I.M.M. because I believe he's booked on other work. Instead I'll assign this as a task for myself and if I get stumped, then I'll ping him later.

Well, I *will* ping @daira to see if she knows or if we should hunt down the answer together.

**Comment by daira** [comment]
This ticket is obsolete; we no longer have Mint operations, and there is adequate test coverage for JoinSplits.
