### ISSUE TITLE
Depends tree is reporting an error related to libsnark

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#1180]
Since July 19th,  the depends tree has been reporting an error related to libsnark.

Is this going to block the z8 release?  If so, how to fix?

http://ci.leastauthority.com:8010/builders/depends-sources/builds/185/steps/test-depends-sources-mirror.py/logs/stdio

**Comment by ebfull** [comment]
This is fixed now. depends-sources should start working again, when it does, please close this.

**Comment by bitcartel** [comment]
ACK - ran test locally and it is fixed now.
