### ISSUE TITLE
Update ``security-warnings.md`` to point to a "live url" such as our wiki for up-to-date security findings.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#1186]

**Comment by daira** [comment]
This didn't make it into beta 1.

**Comment by nathan-at-least** [comment]
We need the actual URL. For now, let's fall back to just https://z.cash, because we should have a banner mechanism displayed on the front page (and all pages!) for high-priority announcements like security.

*Soon* we'll also have a security announcement page.

**Comment by arcalinea** [comment]
Added https://z.cash in #1473
