### ISSUE TITLE
Change the memo field size.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#1187]
We've decided in #85 to increase the memo field size. This ticket is for the actual code change, associated tests.

This should probably be done before the #756 work as a separate isolated PR so we can see any notable performance issues.

**Comment by daira** [comment]
The protocol spec change is https://github.com/zcash/zips/issues/60

**Comment by daira** [comment]
I think it would make sense to do this and #1190 at the same time. (I know there was some disagreement about this in the 2016-08-08 engineering meeting.)

**Comment by nathan-at-least** [comment]
So long as #1190 is truly not much work, I'd accept addressing both that issue and this in the same milestone. I still want separate PRs.

However, I'm wary of #1190 being more work than anticipated. How many test vectors contain serialized JoinSplits? Do we need to update a bunch of legacy test vectors or do expensive test vector regenerations, for example? (The only way I could think for that to happen would be a vector with a serialized JoinSplit that's used in PoW tests.)

Let's do this: #1187 is considered an absolute requirement, whereas #1190 is a "nice-to-have" and therefore we should have a fail-to-exclusion timebox for it, where if we haven't landed it by the z9 merge deadline (2016-08-19) then it will be excluded from the 1.0 launch. (Also, don't spend time trying to fit it in if there are any other z9 tickets unresolved.)

**Comment by daira** [comment]
My reasoning is that we need to regenerate the test vectors anyway if the memo size is changing.

**Comment by ebfull** [comment]
It actually isn't hard to move the fields around, it would break a few tests but they are easily regenerated.
