### ISSUE TITLE
Add cleanly-contained documentation to the source repository.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#119]
Let's have one toplevel ``README.zerocash`` and put all other docs under ``./doc/zerocash`` and then strive to touch documentation outside of those locations as little as necessary.

**Comment by daira** [comment]
We have this structure already (although the [docs/zcash](https://github.com/zcash/zcash/tree/zc.v0.11.2.latest/doc/zcash) directory currently only contains calgary.md).
