### ISSUE TITLE
Implement moving ciphertexts to the end of a JoinSplit description

### ISSUE THREAD

**Issue by daira** [zcash/zcash#1190]
Per https://github.com/zcash/zips/issues/59 and https://github.com/zcash/zcash/issues/991#issuecomment-223732455

**Comment by nathan-at-least** [comment]
On @daira's urging, I've moved this into the z9 release as a "nice to have feature" which means it is a lower priority than all other z9 consensus changes, and if it's not merged by the z9 merge cutoff (2016-08-19) then it will be excluded from our 1.0 launch.
