### ISSUE TITLE
Test alert system on Testnet

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#1195]
Ask users to:
1. add to their zcash.conf: `alertnotify=echo %s`
2. relaunch zcashd and watch/grep console output

Alert-key holders should:
1. Build zcashd z8 with the private key
2. Periodically send test messages, perhaps via a cron job, during the z8 release period.

**Comment by bitcartel** [comment]
First alert 1000 was sent today and received by a community member.

**Comment by str4d** [comment]
All five alerts were sent and received; the beta 1 testnet still shows alert 5, and we are still getting user reports (e.g. #1449).

@bitcartel if you are satisfied, could you please close this issue? Cancelling alert 5 is not a blocker, because we will be resetting the testnet for beta 2.

**Comment by bitcartel** [comment]
Test was successful.
