### ISSUE TITLE
Fetch-params.sh failed to download key because it doesn't retry for some HTTP status codes

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#1196]
Script failed to download the verification key during a build test:

http://ci.leastauthority.com:8010/builders/zcash/builds/285/steps/fetch-params.sh%20%28optional%29/logs/stdio

By default, wget will retry a download 20 times but not when it receives a fatal error, such as 404 or 500.  Updating the wget options could help e.g. http://superuser.com/questions/493640/how-to-retry-connections-with-wget

**Comment by nathan-at-least** [comment]
I assigned @ebfull because this is a "freebie" while working on #1312.

**Comment by bitcartel** [comment]
Part of fetch-params improvements.

**Comment by ageis** [comment]
This looks easy to implement via the wget options @nathan-at-least mentioned. I'm assigning myself.

**Comment by bitcartel** [comment]
This ticket can be closed when #1507 is merged.

**Comment by daira** [comment]
ACK
