### ISSUE TITLE
Add note tracking.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#1199]
Add tracking of ``{ zkey → [ note ] }`` into the wallet infrastructure as well as incoming note detection.

Excluded scope: Anything related to RPC stuff or proving work queue.

**Edit:** Earlier revision said note detection was out of scope; moved in scope.

**Comment by str4d** [comment]
@nathan-at-least if incoming note detection is out-of-scope, then what does that mean for the close condition of this issue? Is it simply that the code to do this exists but is completely unused, or should it be used as much as possible (AFAICT the only other source of notes would be change to local addresses).

**Comment by nathan-at-least** [comment]
Oh, yeah, let's change that to include incoming note detection. I'll edit the description to reflect that.
