### ISSUE TITLE
What does an attacker learn if they recover only a target's ``(a_sk, sk_enc)``?

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#120]
Suppose, somehow, a user's wallet leaks only `(a_sk, sk_enc)`. What does an attacker discover from knowing that secret and the blockchain contents?

There are several related but distinct security questions below. Maybe they should have separate tickets.

**Comment by daira** [comment]
@nathan-at-least wrote:
> What if an attacker has the secret keys of two parties, and wants to discover if one party sent coins to the other party?

Suppose coins have been sent from addr<sub>alice</sub> to addr<sub>bob</sub>, and Eve has both secret keys. The answer depends on whether viewing keys are implemented:
* With viewing keys, Eve can derive a<sub>vk,alice</sub> from a<sub>sk,alice</sub> and use it to decrypt the information showing that a coin was sent from addr<sub>alice</sub> to addr<sub>bob</sub>. (Actually, she needs only a<sub>vk,alice</sub> and to be able to recognize a<sub>pk,bob</sub>.) This is part of the requirements for viewing keys.
* Without viewing keys, Eve can tell that addr<sub>bob</sub> received a coin, but cannot tell that it was sent from addr<sub>bob</sub>.

**Comment by daira** [comment]
@nathan-at-least wrote:
> What if an attacker has a single secret key tuple, and a set of candidate public pk<sub>enc</sub> keys, and knows a coin tuple that may have been sent to one of those candidates keys? Can an attacker do trial encryptions with the recovered coins and victim secret key tuple to all of the candidates, comparing the encryption results to the blockchain to discover if a given coin was sent to a given candidate?

Suppose coins have been sent from addr<sub>alice</sub> to addr<sub>bob</sub>, and Eve has only a<sub>sk,alice</sub>. Then the answer is the same as for the preceding question.

If Eve has only a<sub>sk,bob</sub> and a set of candidate addresses from which the coin might have been sent, then disregarding linking attacks based on timing or distinguishable wallet behaviour, she has no advantage over chance in guessing which address the coin came from (and neither does Bob).

**Comment by daira** [comment]
@nathan-at-least, does this answer your questions?

**Comment by daira** [comment]
Let's document these answers.
