### ISSUE TITLE
Implement z_sendmany and async RPC calls.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#1200]
Depends on #1199 for note tracking.

This will require several substantial changes:

* adding a "proving work queue" into the wallet, which executes proofs one at a time.
* adding status tracking for the work queue.
* adding the ``z_sendmany`` call which adds jobs to the queue.
* add status checking calls for checking on work queue status.

Excluded for simplicity:

* cancelling jobs in the queue.
* getting any kind of status information aside from ``queued`` / ``finished-ok`` / ``finished-error``.

**Comment by daira** [comment]
#1274 has been merged.
