### ISSUE TITLE
Zcash integration guide.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#1202]
This is a one-page recommendations/guide thing, probably as a blog post, that recommends how infrastructure / tools / services developers should integrate Zcash. The outline is basically:

**If:** you already use bitcoind, and you want a quick roll-out or you need "advanced" transactions (multisig, CLTV, etc...), and you can handle user errors,

**Then:** deploy the same infrastructure you use with bitcoind for zcashd, and then handle the errors that occur where zaddrs are passed (since this backwards-compatible interface only supports taddrs).

**If:** you want to write new integration code that does not rely on "advanced Bitcoin transactions" and you want strong privacy and you can afford the operational costs (lots of RAM and latency per txn),

**Then:** use our new simple high-level API.

**If:** you use the Bitcoin transaction or blockchain formats/protocol directly instead of bitcoind, or you use a different bitcoin node/library than the bitcoind RPC interface,

**Then:** get in touch with our engineers and we'll see how we can help.

**Comment by daira** [comment]
I suggest we swap the order of the first and second If/Then.

**Comment by bitcartel** [comment]
This ticket is out of date, the integration guide currently lives in a Google Doc.

**Comment by nathan-at-least** [comment]
I'm going to move this into Beta 2, even though it's 99% complete. The next steps are basically to "officially publish" it, and then maybe blog about it, but I'd like to do that next week and consider Beta 1 complete without the fully published ZIG.

**Comment by bitcartel** [comment]
Published: https://z.cash/support/zig.html
Closing this ticket.
