### ISSUE TITLE
Rewrite run-bitcoind-for-test.sh.in in python

### ISSUE THREAD

**Issue by arcalinea** [zcash/zcash#1204]
Came up in engineering meeting 8/8/16

**Comment by nathan-at-least** [comment]
Note: the main impetus is to fix a known race-condition-style bug in [``qa/pull-tester/run-bitcoind-for-test.sh.in`` at ``a8270035``](https://github.com/ThisIsNotOfficialCodeItsJustForks/zcash/blob/a8270035c0d3596a59af35bfdccfc7d807e2aed7/qa/pull-tester/run-bitcoind-for-test.sh.in) ([latest on branch ``zc.v0.11.2.latest``](https://github.com/ThisIsNotOfficialCodeItsJustForks/zcash/blob/zc.v0.11.2.latest/qa/pull-tester/run-bitcoind-for-test.sh.in)):

 Any time zcashd fails to start or takes too long (longer than ``ZCASH_LOAD_TIMEOUT``) then the result is a process hanging forever, which our build system blocks forever on.

The rewrite should not recreate this behavior.

**Comment by nuttycom** [comment]
No longer exists.
