### ISSUE TITLE
Address Sanitizer Finding alloc-dealloc-mismatch

### ISSUE THREAD

**Issue by rcseacord** [zcash/zcash#1215]
0x602004828bd0 is located 0 bytes inside of 16-byte region [0x602004828bd0,0x602004828be0)
allocated by thread T0 here:
    #0 0x560f9b129090 in operator new[](unsigned long) (/home/rcs/Test/zcash/zcash/src/test/test_bitcoin+0x14e090)
    #1 0x560f9b4dec0d in TruncatedStepRow<20ul>::GetTruncatedIndices(unsigned long, unsigned long) const crypto/equihash.cpp:203
    #2 0x560f9b4dec0d in Equihash<96u, 5u>::OptimisedSolve(crypto_generichash_blake2b_state const&, std::function<bool (std::vector<unsigned int, std::allocator<unsigned int> >)>, std::function<bool (EhSolverCancelCheck)>) crypto/equihash.cpp:428
    #3 0x560f9b1e10f3 in EhOptimisedSolve(unsigned int, unsigned int, crypto_generichash_blake2b_state const&, std::function<bool (std::vector<unsigned int, std::allocator<unsigned int> >)>, std::function<bool (EhSolverCancelCheck)>) crypto/equihash.h:224
    #4 0x560f9b1e10f3 in EhOptimisedSolveUncancellable(unsigned int, unsigned int, crypto_generichash_blake2b_state const&, std::function<bool (std::vector<unsigned int, std::allocator<unsigned int> >)>) crypto/equihash.h:236
    #5 0x560f9b1e10f3 in equihash_tests::TestEquihashSolvers(unsigned int, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, arith_uint256 const&, std::set<std::vector<unsigned int, std::allocator<unsigned int> >, std::less<std::vector<unsigned int, std::allocator<unsigned int> > >, std::allocator<std::vector<unsigned int, std::allocator<unsigned int> > > > const&) test/equihash_tests.cpp:72
    #6 0x560f9b1e1acc in equihash_tests::solver_testvectors::test_method() test/equihash_tests.cpp:98
    #7 0xb  (<unknown module>)
    #8 0xac0b210072656460  (<unknown module>)

SUMMARY: AddressSanitizer: alloc-dealloc-mismatch (/home/rcs/Test/zcash/zcash/src/test/test_bitcoin+0x14e570) in operator delete(void*)

**Comment by daira** [comment]
Thanks, looks like a useful traceback.

**Comment by zookozcash** [comment]
I'm surprised to see ASan finding something that valgrind didn't already find. Maybe we should add ASan to our continuous integration suite.

**Comment by rcseacord** [comment]
this looks like a duplicate of https://github.com/zcash/zcash/issues/1214 and it went away when i fixed that problem.
