### ISSUE TITLE
Address Sanitizer Finding

### ISSUE THREAD

**Issue by rcseacord** [zcash/zcash#1229]
0x60200000b990 is located 0 bytes inside of 4-byte region [0x60200000b990,0x60200000b994)
allocated by thread T0 here:
    #0 0x557a4a74ba30 in operator new[](unsigned long) (/home/rcs/Test/zcash/zcash/src/zcash-gtest+0x139a30)
    #1 0x557a4a7a1528 in equihash_tests_is_probably_duplicate_Test::TestBody() gtest/test_equihash.cpp:9

**Comment by daira** [comment]
Not sure what this report is saying.

**Comment by rcseacord** [comment]
looks like a duplicate of https://github.com/zcash/zcash/issues/1229 and was resolved by the same fix
