### ISSUE TITLE
Proving key and verifying key filename can confuse users

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#1232]
Should key filenames have a name which is independent of the release versioning scheme?

From slack:

> The filenames of the proving/verifying params. See boscro's completely understandable confusion: https://zcashcommunity.slack.com/archives/zcash/p1470761025001120
>  boscro
> **im confused.  fetch-params.sh seems to be pulling z7 keys...   zenon@zenon-desktop:~/zcash$ git fetch origin
> zenon@zenon-desktop:~/zcash$ git checkout zc.v0.11.2.z8**
> Already on 'zc.v0.11.2.z8'
> Your branch is up-to-date with 'origin/zc.v0.11.2.z8'.
> zenon@zenon-desktop:~/zcash$ ./zcutil/fetch-params.sh
> zcash - fetch-params.sh
> 
> **Updating testnet3 symlinks to regtest parameters.
> Verifying parameter file integrity via sha256sum...
> regtest/z7-proving.key: OK
> testnet3/z7-proving.key: OK
> regtest/z7-verifying.key: OK
> testnet3/z7-verifying.key: OK**

**Comment by ebfull** [comment]
> Should key filenames have a name which is independent of the release versioning scheme?

Yes! That would be ideal.

**Comment by nathan-at-least** [comment]
In my opinion, the only requirement for the names is that they're unique. They don't actually need ordering that a versioning scheme would provide. I'd be happy with a name like ``zcash-verification-key.XXX`` where ``XXX`` is the first 8 hex digits of the secure hash. (Or even just a random animal name that's unique across all parameters like ".beluga").

**Comment by daira** [comment]
I like the random animal name option; that provides an easy way to refer to them.

**Comment by ebfull** [comment]
The names of the parameters should match our major version codename. So, "sprout".

**Comment by ebfull** [comment]
This will be addressed by #1312 (the key names are changing to be hashes).
