### ISSUE TITLE
Make sure there is a checkpoint

### ISSUE THREAD

**Issue by daira** [zcash/zcash#1243]
In [this forum thread](https://forum.z.cash/t/z8-conf-file-changes-and-connection-issues/1163), users are seeing clients that mine their own chains of empty blocks, I believe because they can't (or are not configured to) connect to alphatestnet.z.cash.

I believe that setting a checkpoint for the actual chain is sufficient to fix this, if I understand correctly how checkpoints work.

**Comment by nathan-at-least** [comment]
The original issue wasn't actually an issue mitigated by checkpoints.
