### ISSUE TITLE
Upgrade bdb

### ISSUE THREAD

**Issue by daira** [zcash/zcash#1255]
https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md#dependency-build-instructions-ubuntu--debian days:

> Ubuntu and Debian have their own libdb-dev and libdb++-dev packages, but these will install BerkeleyDB 5.1 or later, which break binary wallet compatibility with the distributed executables which are based on BerkeleyDB 4.8. If you do not care about wallet compatibility, pass --with-incompatible-bdb to configure.

We should settle on a later version to get any security/stability fixes since 4.8.

**Comment by bitcartel** [comment]
Related in general to #1242

**Comment by daira** [comment]
#1257 was a duplicate.

**Comment by str4d** [comment]
AIUI, upgrading this will require testnet users to delete and recreate their wallets? We should instruct users in the beta 2 release notes to export their keys individually before upgrading, and then import them afterwards (followed by a reindex or rescan, pending resolution of #1394 and #1400).

**Comment by daira** [comment]
Beta 2 is a testnet-reset release, so we don't need to do that: the wallets will in any case be deleted.
