### ISSUE TITLE
Document the details of the current DoS attack on the testnet

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#1256]
We need to know how the DoS attack on the testnet is working so that we can properly mitigate it in #630.

**Comment by daira** [comment]
@str4d wrote [on the #zcash Slack channel](https://zcashcommunity.slack.com/archives/zcash/p1471477943001398):
> I think I see the problem: the miner keeps mining because the config we give in the Public Alpha Guide uses ``addnode``
> So ``vNodes`` is always non-empty, meaning the miner always runs, even if the node can't actually connect to the node given in ``addnode``
> Meanwhile the DDoS is preventing users from connecting to the ``alphatestnet`` node.
> Hence why the workaround given in the forums (using someone else's ``peers.dat``) works, because it circumvents the DDoSed node.

**Comment by ebfull** [comment]
It wasn't a DoS and we've solved the issue by closing #1289.
