### ISSUE TITLE
Read *Zero-Knowledge Contingent Payment* and any other ZK-related posts by gmaxwell.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#126]
https://en.bitcoin.it/wiki/Zero_Knowledge_Contingent_Payment

**Comment by ebfull** [comment]
I'm a huge fan of these, as you know!

But, this is one of *those* titles and isn't specific to this project, so I'm closing it.

**Comment by ebfull** [comment]
Actually, I'll keep it open so you can add it to your reading list. Then feel free to close. :)

**Comment by nathan-at-least** [comment]
I've moved this task to my personal todo list.

**Comment by zmanian** [comment]
Maybe blog about your findings?

**Comment by kanzure** [comment]
also consider reading "Efficient zero-knowledge contingent payments in cryptocurrencies without scripts" https://eprint.iacr.org/2016/451
