### ISSUE TITLE
Founders Reward Ejector Seat

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#1273]
It might be useful for the Founders Reward spend authority holder(s) to also be able to broadcast a message which turns off the Founders Reward for future blocks, effectively destroying (or diverting to miners) all future Founders Reward.

This doesn't give the spend authority holders any extra authority, since they can effectively do the same thing by immediately spending all of the founders reward into a burn address.

It would lessen some attackers' incentives to attack the spend authority holders. One thing this idea does is it makes the spend authority secret useless as a ransom demand, since the legitimate holders can empty the account frequently, and if it ever is demanded by a ransomer, they can just give it up then shut off the founders reward. Without this idea, each new block creates a race between the legitimate spend authority holders and the attacker for who can get their spend into the blockchain first.

On the other hand, it could _increase_ some attackers' incentives to attack the spend authority holders, if their goal is to eliminate the founders' reward. Because the spend authority holders are more willing to turn off the founders reward than to give it to an attacker, the attacker has to do less to trigger that response.

A zero-code way to implement this is to publish an agreement that if the founders reward spend authority signs the message "Please turn off the founders reward." we'll hard-fork out the founders reward.

**Comment by daira** [comment]
See also https://github.com/zcash/zcash/issues/125#issuecomment-196629653 .

**Comment by nathan-at-least** [comment]
It's too late in our process to alter consensus. However the last proposal for a hardfork agreement sounds like an excellent compromise.

**Comment by alfiedotwtf** [comment]
See also #716

**Comment by daira** [comment]
#716 is about revocation of zaddresses; the Founders' Reward goes to a taddress.

**Comment by daira** [comment]
This is obsolete (and I don't think we want anything similar for the Dev Fund; in fact giving ECC the power to do that would be inconsistent with ZIP 1014).
