### ISSUE TITLE
Set OMP_NUM_THREADS to 1 if running multiple JoinSplit operations in parallel

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#1282]
By default libzsnark will try and use all the detected cores on a cpu (see related #408).

On a i3-6100U (dual-core with hyperthreading for 4 threads)

Single operation:
Join split proof generation time: 76.4536

Three operations running in parallel (via async rpc workers):
Join split proof generation time: 206.309
Join split proof generation time: 200.544
Join split proof generation time: 203.85

If we tell libsnark to only use one thread:

OMP_NUM_THREADS=1 ./zcashd -daemon

Performance falls for the single operation:

Join split proof generation time: 139.439

Performance improves for multiple operations running in parallel:

Join split proof generation time: 184.34
Join split proof generation time: 188.428
Join split proof generation time: 196.899

**Comment by daira** [comment]
Isn't it better to serialize the JoinSplits but still do each of them in parallel with the configured number of threads? That should still complete three operations in 76.45 * 3 = 229.36 seconds, which is not too much worse than 196.90 seconds, and the first two of those operations complete sooner than in the "multiple operations running in parallel" case (after 76.45 and 152.90 seconds respectively).

**Comment by daira** [comment]
Also, the memory usage is significantly better if you're only doing one JoinSplit at once.

**Comment by str4d** [comment]
See #1940 for discussion of benchmarking these options.

**Comment by tromer** [comment]
Libsnark is no longer used by zcashd. Is Bellman also affected by OMP_NUM_THREADS (or equivalent)? If not, this issue can be closed.

**Comment by daira** [comment]
bellman does not use OpenMP or `OMP_NUM_THREADS`.
