### ISSUE TITLE
Make "@zkbot try" work

### ISSUE THREAD

**Issue by daira** [zcash/zcash#1287]
See https://github.com/zcash/zcash/pull/1268 for an example of it causing problems. I don't understand the exact issue, maybe @ebfull or @defuse can explain.

**Comment by defuse** [comment]
It would be super nice if @zkbot try worked, but I'm not sure what the problem is.

**Comment by defuse** [comment]
Maybe this is something we should have @arcalinea or @ageis look at?

**Comment by ageis** [comment]
The problem is that nobody has been granted "try" rights, only reviewer rights.
```
# who has r+ rights?
reviewers = ["ebfull","nathan-at-least","daira","str4d","bitcartel"]
# who has 'try' rights? (try, retry, force, clean, prioritization)
try_users = []
```
Is it okay to copy the same list to `try_users`?

**Comment by ageis** [comment]
This should be set. Can someone initiate a **try** to verify and let me know whether it worked out?

**Comment by ageis** [comment]
I see no reason why this shouldn't be working, so I'm closing this issue.
