### ISSUE TITLE
Use myriadcoin-style mining.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#129]
Myriadcoin introduced a mining scheme of `N` PoW algorithms where any single PoW may win a block, but each algorithm has an independent difficulty.

@daira proposed a similar system where there are `N` algorithms but a block is only won with solutions to _any_ `K` of the `N` algorithms (`K < N`).

I just had a whimsical thought: If one of the algorithms is proof-of-stake, then there may be some restrictions tied to the other PoW algorithms in order to prevent "nothing at stake" vulnerabilities.  Proof-of-stake is appealing because it doesn't require capital investment which scales up, so it does not seem to have a centralization tendency.

Anyway, I suspect all three of these ideas should probably be filed under "too radical" to be accepted as feature goals, but I wanted to document them here for posterity.

**Comment by indolering** [comment]
Why not just switch the PoW algorithm when ASICs show up?  Just the threat of doing it should provide a significant barrier to entry.

**Comment by zookozcash** [comment]
The community could certainly consider that option. Ethereum has pioneered that approach -- threatening (credibly) to change the PoW in order to deter ASICs.

**Comment by indolering** [comment]
> The community could certainly consider that option.

I just don't see any comparative advantage to hardcoding a list of hashing algorithms.

**Comment by eldentyrell** [comment]
> Ethereum has pioneered that approach -- threatening (credibly) to change the PoW in order to deter ASICs.

The only reason the threat is credible in the event of a 51% ASIC-mined chain is because Ethereum is [programmed to self destruct](https://github.com/ethereum/go-ethereum/pull/1588/commits/71d32f54f70917c53fd3a691cface3bc73ffa1b7) this winter.  I hope zcash is not programmed for self-immolation.

> there may be some restrictions tied to the other PoW algorithms in order to prevent "nothing at stake" vulnerabilities

The biggest issue with Proof of Stake schemes is stake grinding.  Nothing-at-stake is an issue too, but not as serious.

**Comment by nuttycom** [comment]
We plan to move to proof-of-stake instead.
