### ISSUE TITLE
Optimize wallet

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#1294]
Comment by @str4d on #1205 

> Is there likely to be any wallet-loading benefit to storing Hash(pubkey, privkey) like is done for unencrypted transparent addresses? We don't currently verify that the spending key matches the payment address; would this be cheaper than doing a direct calculation (like is the case for transparent addresses)?

I would say that improving wallet performance should cover both taddr and zaddr keys, and would be something for post 1.0.

**Comment by bitcartel** [comment]
Related to benchmarking wallet performance #2156 and loading #2518

**Comment by defuse** [comment]
Also related to benchmarking: #2587.

**Comment by nuttycom** [comment]
Insufficiently specific.
