### ISSUE TITLE
"Bitcoin server stopping" when stopping daemon

### ISSUE THREAD

**Issue by tarrenj** [zcash/zcash#1295]
From Slack:
blacknaish - . . .If I start the daemon, the message says: "Zcash server starting" ..but if I stop it, it says:  "Bitcoin server stopping"..

Daemon stop function needs to be updated:
https://github.com/zcash/zcash/blob/94f0dcddb4d200d95bafa106047d9020cfc79fd7/contrib/init/bitcoind.init#L40

**Comment by daira** [comment]
Fixed by #1284.

**Comment by daira** [comment]
(The message didn't actually come from bitcoind.init, that's a red herring.)
