### ISSUE TITLE
Consider improving biggest bitcoin flaws

### ISSUE THREAD

**Issue by Tomas-M** [zcash/zcash#1297]
Hello,
just a suggestion. It seems to me that zCash has great potential to replace bitcoin. But before you release zcash, please consider fixing the biggest problems known in bitcoin, so zcash is way better. 

For example, time needed to confirm a transaction (30 minutes) in bitcoin network is not practical. Zcash should work way faster. Similarly, there are many other things which could be improved, I am sure you know them.

No need to reply, just please make sure appropriate person considers. Thank you.

**Comment by ebfull** [comment]
This is a great topic for discussion but is more appropriate on our forum: https://forum.z.cash/

We've planned for Zcash to adapt and grow after release even if it means breaking backwards compatibility, but to start, Zcash is focused on adding zero-knowledge based privacy features and improving their performance and practicality over time.

**Comment by zookozcash** [comment]
We already have reduced block times to 150 seconds from 600 seconds, so that will help with this. (We've also doubled block max size to 2 MB from 1 MB.)
