### ISSUE TITLE
Verify REST interface is disabled by default; add security-warning.md about lack of review.

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#1298]
There's a REST API which I didn't even know existed. We should disable it before 1.0. There are DoS issues with it:

https://github.com/bitcoin/bitcoin/pull/6193
https://github.com/bitcoin/bitcoin/issues/6192

**Comment by nathan-at-least** [comment]
Agenda questions:

* I need to learn about the difference between the REST interface and the standard/other RPC mechanism.
* Is the REST interface popular?

I think I advocate disabling the REST interface and waiting to see if Beta users request it, then we can consider re-enabling it after 1.0 launch.

**Comment by ebfull** [comment]
Assigning this to you @bitcartel :)

**Comment by bitcartel** [comment]
Confirmation that it's disabled by default:
https://github.com/zcash/zcash/blob/f8b73015bc964a8fd953425d972b733d53ecc7e7/src/rpcserver.cpp#L1007

**Comment by nathan-at-least** [comment]
utACK in so far as I agree with @bitcartel's assessment of the linked code. So now we need a PR which just points out that the rest interface is unaudited.

**Comment by str4d** [comment]
@nathan-at-least see #1328
