### ISSUE TITLE
Add utility method to check if a given string is likely to be a taddr or zaddr

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#1299]
There should be a fast and easy way for us to check if a string is _likely_ to a taddr or zaddr, taking into account of mainnet, testnet and regtest mode, so that we don't have to try and actually construct an object from a string and verify it.

From discussion here abour parsing taddr and zaddr from a wallet dump file:

https://github.com/zcash/zcash/pull/1208#discussion_r76043818

> The byte prefixes for mainnet and testnet are defined internally in chainparams.cpp and are not exposed. If we hard-code a string comparison we might forget to change it if the prefix were to ever change. Ideally we should call a utility function somewhere, perhaps on chainparams, which returns a bool e.g. looksLikeTaddr() or looksLikeZaddr().

**Comment by ebfull** [comment]
It's not too expensive to construct the object, fail to deserialize it, and try another thing, is it?

**Comment by bitcartel** [comment]
That's what I'm doing right now and I'm fine with it, but it does lead to ugly code: https://github.com/zcash/zcash/pull/1208#discussion_r76043818

We could move the ugliness (including catching potential exceptions from deserialization) into routines like:

bool parseTaddr(string, out_z)
bool parseZaddr(string, out_t)

Calling code would be slightly more pleasant for a given user input address string:

```
String address = "...";
Taddr t;
Zaddr z;
if (parseTaddr(address, t)) {
..
} else if (parseZaddr(address, z)) {
...
}

```

I've removed the milestone label for now.  Maybe if we have time we can do this.

**Comment by str4d** [comment]
Also see #812

**Comment by nuttycom** [comment]
Obsolete.
