### ISSUE TITLE
New zkSNARK parameters file system schema + zcashd & fetch-params.sh support.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#1312]
- parameter files live in `~/.zcash-params/{proving,verifying}.${SHA256_HEX}`
- each ChainParams specifies which sha256 it expects in zcash. **Edit:** this is an app code change.
- fetch-params specifies the hashes it wants for each of the chainparams (maybe 2 or 3 distinct params?)
- if fetch-params doesn't see the file it wants, it wgets to a tempfile, calculates the sha256 hash, constructs the destination filename and does an mv.
- if the mv fails fetch-params _ignore it_ and continues to the next param file.
- after that, checks that the expected path exists and has the right sha256 checksum. The path may not exist if it fetched a different version from the server (thus the sha256 is different) or another process deleted the file. The checksum would fail if something corrupted the files. In either of these cases, check-params exits with a loud error.
- we host all params files with their full sha256 names and keep old version around.

**Edit 2016-08-31:** I'm moving this item which require zcash app code changes, into a separate followup ticket:
- zcashd always verifies the sha256sum before passing the file on to the deserializer. (Or better would be to verify it as it loads to prevent reading the file twice.)

Note some intentional features of this approach:
- every distinct set of parameters has a unique unambiguous filename, so there's no confusion of which version of parameters lives in a given path.
- if the file downloaded from the webserver doesn't match expectations _it is still saved for diagnosis/forensics_, and the user sees the file they downloaded clearly logged, then an error message pointing out a different sha256 was expected.
- users can freely run different versions of zcashd and run the fetch-params of each different release and there are no conflicts or problems.
- there's no lock file. Concurrent fetch-params processes will both succeed successfully (as they should, since there's no problem there. Well, one problem is duplicate bandwidth.)
- zcashd detects quickly if the correct params are not available instead of trying to deserialize or instantiate the wrong parameters.
- Since filenames all have sha256 hashes, when users post error diagnostics, we can quickly identify which parameter version they are using, and we can notice unknown sha256 sums which would be something we should carefully investigate.

Note: This was originally posted to a PR comment https://github.com/zcash/zcash/pull/1310#issuecomment-242881154 -but that was off topic for that PR, since this is a followup feature change.

**Comment by nathan-at-least** [comment]
This could be a stepping stone to #1155 where the latter uses the same filesystem schema. An advantage of that is if the P2P fetch is failing, users can fall back to ``fetch-params.sh`` or manual work-arounds, and users can chose to forego the P2P scheme (which could be useful during network attacks, for example).

**Comment by nathan-at-least** [comment]
Related tickets:

* #1296 and #600 - both "non-in-band distribution" tickets, both are orthogonal and we can do all three of these tickets in any order.
* #1232 - (arguably) fixes this as a side-effect.
* #659 - fixes this bug, since we no longer user ChainParams or NetParams names in the path.
* #1155 - as stated above, it could be a first step before P2P params which has some operational advantages.
* #621 - Does not address this ticket. Actually we could make #621 a required feature of this so that both are addressed in the same PR. (I'm currently not convinced #621 is very high priority.)

**Comment by ebfull** [comment]
I don't think we should or need to have different parameters between mainnet and testnet. At least, I can't think of a good reason why.

**Comment by bitcartel** [comment]
Maybe as a test run of parameter setup?

**Comment by ebfull** [comment]
Let's not forget #416.

**Comment by daira** [comment]
We might want to test a hard fork that changes parameters on the testnet first.

**Comment by nathan-at-least** [comment]
Let's break out orthogonal concerns:

* #416 - I believe this is orthogonal because this ticket doesn't address serialization or compression at all and thus this and #416 can be done in either order.
* The decision about whether or not testnet & prodnet have the same parameters is orthogonal. Let's make sure the two ChainParams have the *capability* to specify different params, then we can be flexible with that choice moving forward.

**Comment by nathan-at-least** [comment]
Hrm. I had hoped we could do an initial change that only alters ``fetch-params.sh`` and our hosting URL layout, but it looks like we must change app code to make this work:

> * each ChainParams specifies which sha256 it expects in zcash.

Let's keep that bullet in this ticket and do that as part of Beta 1.

**Comment by daira** [comment]
See also #1335 ("Hard-code the verifying key").

**Comment by nathan-at-least** [comment]
@ebfull and PR reviewers: please verify that the new design is not vulnerable to #1346.

**Comment by nathan-at-least** [comment]
ping @ebfull: when doing this, can you address #1196 also (which just requires passing extra args to `wget`). Then the PR can close both tickets.

**Comment by bitcartel** [comment]
Low priority.

**Comment by daira** [comment]
This would be mostly obviated by #3933 / #6661. For the remaining optional use of `sprout-groth16.params` there is not sufficient justification to implement this issue.
