### ISSUE TITLE
RPC call getblocksubsidy to return the subsidy for future blocks

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#1315]
This is a user feature request to help mining clients:

https://github.com/zcash/zcash/pull/1059#issuecomment-242918652

>  mining clients that want to know the subsidy for the next block.

**Comment by daira** [comment]
Why put an upper limit on the height at all? The future block subsidy is deterministic.

**Comment by daira** [comment]
+1 on allowing this for beta 1.
