### ISSUE TITLE
find out why peak Equihash memory usage is high on benchmark

### ISSUE THREAD

**Issue by daira** [zcash/zcash#1321]
https://speed.z.cash/timeline/#/?exe=1&base=1+9&ben=memory%20solveequihash&env=1&revs=50&equid=off&quarts=on&extr=on

This is currently showing quantization between 1.12 GB and 1.67 GB, possibly depending on the number of solutions. The memory usage in htop shows as around 700 MB for most of the run, so I suspect that memory is getting retained across solution checks, and/or the vectors are over-allocating.

**Comment by nathan-at-least** [comment]
So long as users can mine for an hour or so before memory issues or leaks cause their node to fail, I consider this a post-launch issue. (We'll learn pretty quickly from users if we have leaks, I expect.)

**Comment by nuttycom** [comment]
No longer relevant except for RPC testing due to ASICs.
