### ISSUE TITLE
Remove underscores from Google Test test names

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#1324]
Per [this FAQ entry](https://github.com/google/googletest/blob/master/googletest/docs/FAQ.md#why-should-not-test-case-names-and-test-names-contain-underscore), test case names and test names should not contain underscores, and may break in future (with a new compiler version or a new version of Google Test) if they do. For simplicity, we should write test case names and test names with CamelCase.

**Comment by daira** [comment]
Duplicate of #3575 (this is earlier, but that issue has a PR).
