### ISSUE TITLE
Coins missing from wallet and blockchain

### ISSUE THREAD

**Issue by onics** [zcash/zcash#1327]
After mining ~67 clear coins on the z9 network, and receiving 2 coins from a member on the Slack channel, my coins have gone missing!

It isn't apparent yet whether this is due to some fault of my own, or if there is a bug in the software somewhere. Still trying to track down the source of the issue. 

Local wallets in zcashd and the public block explorer report zero balances for both accounts, and show no previous transactions. It's as if the accounts never existed, or were never used.

I was able to salvage a small amount of ZEC in some encrypted notes, and will try to perform JoinSplits with those to test their existence on the blockchain.

The public addresses in question are:
miJz3Yz4Jqm1YMoKiUy77pjqL56WBQd18C
mogaz8qa4sBKWCyHvUJNDQgwXw1izMbGw2

**Comment by sammy007** [comment]
I predict the same on launch when people will waste thousands of dollars for AWS mining.

**Comment by daira** [comment]
The behaviour of transparent coins is essentially the same as for Bitcoin. So I suspect that this is something that would also have happened with Bitcoin in the same situation, although there's not enough information to tell what exactly went wrong.

**Comment by ebfull** [comment]
Regardless, I examined the logs and did not see any large reorgs, and see no evidence the blockchain contained transactions for the addresses you mentioned.

Perhaps you weren't fully connected to the testnet. Are you also aware that we reset the testnet between the z8 and z9 releases? Maybe you mined the coins during z8.

**Comment by nathan-at-least** [comment]
@onics: Can you save your ``~/.zcash`` directory by first shutting down your node then doing ``cp -a ~/.zcash ~/zcash-missing-coins``. Any other logs or data could be important.

Once you've successfully saved that data directory, do you mind sending us a tarball of it? Did you run different releases with the same data directory? Did you mine the coins on previous releases? Can you contact the person who sent coins to you and ask them to also save their data directory for analysis?

**Comment by onics** [comment]
@daira I agree, it doesn't seem like a specifically Zcash issue either, but I don't have enough experience on BTC or other testnets to know if it occurs there as well.

@ebfull Currently testing on the z9 network with current proving and verifying keys. I have only started mining since z9, and never had a working client with z8. Not sure how to have been more connected to the testnet. Compiled from source, was getting regular updates of the blockchain, and was able to receive one transaction from another user.

@nathan-at-least I can run through my ~/.zcash directory, and package it as a tar ball. I can try contacting the person who sent me the coins. Will be sending the file over shortly.

Thanks to all of you for helping me out with this.

**Comment by onics** [comment]
Think I may have found the issue. It looks like my local clock on my computer may have been out of sync. Noticed I was getting clock errors when I tried updating other software. 

Going to try resyncing my clock and begin mining again.

Will close this issue if the experiment is successful.

**Comment by daira** [comment]
https://github.com/bitcoin/bitcoin/commit/c9c017a is an upstream patch to improve the error message in case of bad clock sync.

**Comment by daira** [comment]
See also https://github.com/bitcoin/bitcoin/issues/6989

**Comment by onics** [comment]
Syncing my clock appeared to fixed the problems I was having updating block information. I am continuing mining efforts, and will see if any coins mined from this point forward are retained in my wallet.

My previous transaction I received from another member also reappeared in my transaction list.

Thank you for your help and feedback on solving this.
