### ISSUE TITLE
Remove unused code/dependencies/features

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#1330]
We don't support some features like the Qt Wallet, so leaving the code, docs, and build targets there will mislead users. Let's remove it.

**Comment by daira** [comment]
Relevant upstream PR: https://github.com/bitcoin/bitcoin/pull/8640

**Comment by nathan-at-least** [comment]
Added this as an rc1 goal.

**Comment by daira** [comment]
I am skeptical that we should be doing this before launch. It's not necessary for the success of the launch, and will take up valuable developer time. I suggest doing it in 1.0.1 instead.

**Comment by bitcartel** [comment]
@nathan-at-least I agree with @daira that, at this point in time, removing QT code is lower priority than other tasks.  If you're okay with it, can we move this to 1.0.1 ?

**Comment by bitcartel** [comment]
Postpoining to 1.0.1

**Comment by daira** [comment]
The QT wallet was removed in #1636. The only other thing I can think of is that libconcensus had some unused code IIRC. I think this issue can be closed though.
