### ISSUE TITLE
Increase the coinbase maturity duration

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#1332]
When we decreased the target block interval from 10 minutes to 2.5 minutes (#989), we increased a bunch of associated constants (e.g. increasing the halving interval from 210,000 to 840,000) to keep the monetary curve unchanged. However, one constant we did not change is `COINBASE_MATURITY = 100` (a network consensus rule). In decreasing the block interval, we decreased the amount of work required to generate 100 blocks (only 4hr10 instead of 16hr40), making a potential reorg more likely (though still unlikely). We should consider increasing this, or document our reasoning for not increasing it.

Related issues: #952, #953, #1302

**Comment by str4d** [comment]
Added "needs prioritization" because this affects consensus, so we need to decide on it soon.

Implementation-wise, AFAICT it will require changing the aforementioned constant, and adjusting all RPC and Boost tests to mine that many extra blocks (as all those tests currently assume 100 confirmations).

**Comment by ebfull** [comment]
This maturity rule can be made stricter after launch if necessary, but I'm not convinced we need to do it at all.

**Comment by str4d** [comment]
It can be, but doing so would require a hard fork. If we're happy with that as the resolution, I'm happy; I'd just like the resolution documented for our future benefit :smiley:

**Comment by ebfull** [comment]
It wouldn't require a hardfork to increase the coinbase maturity since you're making previously valid transactions invalid.

**Comment by str4d** [comment]
Oh, yes, you're right. I had my directions backwards :sweat_smile: That was my only concern, so if we're happy with that as the potential resolution, this issue can be closed.

**Comment by daira** [comment]
I'm pretty sure we had already considered this in an engineering meeting, and decided it was fine. We're past consensus freeze, and I don't see a significant security issue, so let's close this.
