### ISSUE TITLE
Typo in params README

### ISSUE THREAD

**Issue by alfiedotwtf** [zcash/zcash#1334]
-This directory stores common zcash zkSNARK parameters. Note that is is
+This directory stores common zcash zkSNARK parameters. Note that it is

**Comment by daira** [comment]
The typo is [here](https://github.com/zcash/zcash/blob/master/zcutil/fetch-params.sh#L52). Can you submit a PR please?

**Comment by daira** [comment]
This help output is also wrong:

> The parameters currently are about 2GiB in size

They are currently "just under 911MB in size" (wording from the Beta Guide).

**Comment by alfiedotwtf** [comment]
No problem. See pull #1403 :)

**Comment by str4d** [comment]
Closed by #1403.
