### ISSUE TITLE
Hard-code the verifying key

### ISSUE THREAD

**Issue by daira** [zcash/zcash#1335]
The [BCTV14 JoinSplit] verifying key is only 1449 bytes. We might as well hard-code it, which would obviate any concern about it getting out-of-sync with the code.

Note that there is value in using a simpler mechanism to obtain the verifying key than the proving key, because accepting a wrong verifying key can lead to acceptance of invalid transactions, while a proof made with the wrong proving key will not convince anyone who has the correct verifying key. (Unfortunately, with the current libsnark deserialization we potentially have memory safety attack vectors if the proving key is replaced. But that is a separable problem.)

The key can be hard-coded into a header file of reasonable size using widely available tools (`xxd` was installed by default on my Debian VM):

```
$ xxd -i z9-verifying.key
unsigned char z9_verifying_key[] = {
  0x30, 0x1a, 0x11, 0x65, 0xc4, 0xc1, 0x1f, 0xac, 0xaf, 0x46, 0x99, 0x05,
[...]
  0x41, 0xc9, 0x49, 0x6c, 0x67, 0xdc, 0xbe, 0xe8, 0x0c
};
unsigned int z9_verifying_key_len = 1449;

$ xxd -i z9-verifying.key |wc --bytes
9017
```

**Comment by daira** [comment]
Note that some software derived from the Zcash codebase might not need proving. If we did this, then such software could strip out the parameter loading mechanism for the proving key.

**Comment by ebfull** [comment]
Yes, I was definitely going to do this as part of #1312.

**Comment by nathan-at-least** [comment]
I assigned @ebfull and placed this into Beta 2, since it is an bonus goal for existing work.

Does this complicate our "release parameter update" story at all? Instead of a patch updating the hash of an expected file, we'll have a patch against a header file. We will see what that looks like as part of #1419.

**Comment by ebfull** [comment]
I nominate moving this out toward when we add the MPC'd parameters in. It's not really hard to change (I'll do it) and there's no point doing it for the current parameters.

**Comment by daira** [comment]
I disagree with waiting until we have the MPC'd parameters for this. We need to find any bugs/problems before then.

**Comment by bitcartel** [comment]
@ebfull @daira Status on this ticket?  Will it go into RC1 or GM?

**Comment by bitcartel** [comment]
Not necessary for launch.  Not enough time.

**Comment by daira** [comment]
@ebfull had started working on this, I think.

**Comment by daira** [comment]
Let's do this for (or before) Sapling.

**Comment by nuttycom** [comment]
We've decided not to do this.
