### ISSUE TITLE
Error in difficulty algorithm calculation

### ISSUE THREAD

**Issue by jyap808** [zcash/zcash#1343]
There are some incorrectly placed parentheses leading to an incorrect calculation.
```
    int64_t AveragingWindowTimespan() const { return nPowAveragingWindow * nPowTargetSpacing; }
    int64_t MinActualTimespan() const { return (AveragingWindowTimespan() * (100 - nPowMaxAdjustUp  )) / 100; }
    int64_t MaxActualTimespan() const { return (AveragingWindowTimespan() * (100 + nPowMaxAdjustDown)) / 100; }
```

TLDR this should be:
```
    int64_t AveragingWindowTimespan() const { return nPowAveragingWindow * nPowTargetSpacing; }
    int64_t MinActualTimespan() const { return (AveragingWindowTimespan() * (100 - nPowMaxAdjustUp  ) / 100); }
    int64_t MaxActualTimespan() const { return (AveragingWindowTimespan() * (100 + nPowMaxAdjustDown) / 100); }
```

You can do the math but incorrect formula results in MinActualTimespan > MaxActualTimespan.

Refers to commit #931

**Comment by ebfull** [comment]
I don't see how the code is any different with your change. Multiplication and division have the same precedence and associativity.

Are you suggesting that `(100 - nPowMaxAdjustUp) / 100` should be multiplied by `AveragingWindowTimespan()`? I don't know the details of the algorithm to say whether or not that's correct.

**Comment by jyap808** [comment]
Er, sorry, wrong on my side. Looks good.
