### ISSUE TITLE
RPC call getbalance can return wrong value as wallet does not always handle utxos consumed entirely by notes

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#1345]
The following two commands use different upstream code to compute the transparent balance, and they should give the same answer as noted in upstream comments.  However, they do not.

```
./zcash-cli getbalance
0.10000000
./zcash-cli getbalance "*" 1 true
0.97740000
```

The correct balance is 0.1. 

The problem is that the second method of computation uses `CWalletTx::GetAmounts` which does not consider a transaction as spent, _when the transaction has no transparent outputs_ because the transaction inputs are being completely consumed (except for a miners fee) by one or more JoinSplits e.g. transferring funds from a Coinbase tx to a zaddr.

**Comment by str4d** [comment]
IIRC this RPC command is being deprecated, but we should still fix this because we will likely be reusing the underlying calculation code in the new RPC command.
