### ISSUE TITLE
What useful metadata should an async sendmany operation return?

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#1354]
A sucessful operation currently returns:

```
{
        "id" : "opid-748be2b7-a21f-4bb7-b582-9327056e90c6",
        "status" : "success",
        "creation_time" : 1473264398,
        "result" : {
            "txid" : "c0c6677fa9625245ff5550538f319b511f521d045965686486ec20c1fbb3ad06"
        },
        "execution_secs" : 53.63568842
    }
```

Should we also include data such as how long the operation was in the queue, what time execution started, etc?

**Comment by nathan-at-least** [comment]
Let's wait until after launch to get feedback from user requests.

**Comment by nathan-at-least** [comment]
This ticket is too open-ended to be easily closed. I'll close this, and when users or engineers have improvement proposals we can track those specifically.
