### ISSUE TITLE
Refactor a few wallet calls for better testability: z_getbalance, z_gettotalbalance

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#1358]
We need to refactor rpcwallet's getBalanceTaddr() and  AsyncRPCOperation_sendmany find_utxos() into the wallet so testing is easier and we can get better test coverage.

Related to #1329. With a test harness in place, it will be easier to check that the balance of notes is correct, while checking the balance of UTXOs calls into existing upstream methods.

Related to #1345 where the wallet internally does not track UTXO balances correctly where there are transaction inputs but no transaction outputs due to funds being consumed by JoinSplit(s).

**Comment by str4d** [comment]
Assigned to @bitcartel because IIRC he is already working on fixing issues here?

**Comment by bitcartel** [comment]
Some tests were written for z_getbalance and z_gettotalbalance as part of #1427.

**Comment by bitcartel** [comment]
More tests in #1431 and #1520.
#1345 was closed.

**Comment by str4d** [comment]
`z_getbalance` and `z_gettotalbalance` have been deprecated, and will be removed in #6326 and #6328.
