### ISSUE TITLE
Check the number of joinsplits in a sendmany transaction is valid

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#1359]
Currently there is no limit set on the number of joinsplits, so the size of tx could be invalid.
We should consider what the maximum number might be and enforce it in z_sendmany.
We should estimate the number of joinsplits required and report that a transaction cannot be created before any joinsplits are created.
Related to #1128 fee selection.

**Comment by nathan-at-least** [comment]
I created #1388 which is about the consensus rule side of this. Let's add a sanity check to z_sendmany for this ticket.

**Comment by leto** [comment]
This has been checked in `z_sendmany` for a while and is also part of the wallet.py tests: https://github.com/zcash/zcash/blob/master/src/wallet/rpcwallet.cpp#L3482

I think this issue can be closed
