### ISSUE TITLE
checkpoints should explicitly declare transactions/blocks that are part of the history but would no longer verify

### ISSUE THREAD

**Issue by daira** [zcash/zcash#136]
Suppose that we want to fix a bug or irregularity in the consensus protocol, but there are transactions or blocks in the consensus block chain history that took advantage of that bug/irregularity. We ideally want it to be possible to verify the entire history using the current protocol, but that is a potential obstacle to making consensus protocol changes, particularly changes that tighten the acceptance rules.

If we include hashes of known transactions and blocks that wouldn't verify under the new rules as part of a checkpoint, that tells any new verifier that their nonverifiability is intentional and not a mistake, thus giving us more flexibility to change the consensus algorithm. The specific reasons why they no longer verify should be documented.

**Comment by nuttycom** [comment]
The zcashd hardforking upgrade approach means that this is no longer relevant.
