### ISSUE TITLE
Should taddr coinbase to zaddr transactions have edge case in change handling?

### ISSUE THREAD

**Issue by ebfull** [zcash/zcash#1363]
Simon and I figured that the change address from a coinbase spend in the wallet on a taddr -> zaddr case could just use the zaddr as the change, so long as the user is required to supply just a single zaddr. It may be non-intuitive though. Instead an alternative might be to force the user to supply a change address in this particular case, but that would make it somewhat irregular compared to other invocations of the command.

**Comment by str4d** [comment]
Third alternative: require transactions containing coinbase to spend all the inputs, without leaving change. That's essentially what the current code enforces, and might be easier for users to comprehend. But it means either the users have to get the correct tally, or they will fail first time and have to redo (the error could tell them what really to use).

**Comment by bitcartel** [comment]
> We can check that the single zaddr belongs to the wallet. So what this means is that miners can only protect coinbase funds by sending them to a zaddr they have the key for. Is this something we should do?

**Comment by daira** [comment]
I thought we'd already addressed this before launch?

**Comment by nuttycom** [comment]
Complete long ago.
