### ISSUE TITLE
Set up network bootstrapping dns hooks for prodnet.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#1369]
This brings the work from #630 to our prodnet.

**Comment by nathan-at-least** [comment]
Now in rc1 milestone.

**Comment by str4d** [comment]
Assigning to @ageis because the codebase used by the testnet dnsseed can be run in both mainnet and testnet mode, so implementing this should now only require infrastructure work and a few changes to constants.

**Comment by ageis** [comment]
DNS seed is running in private mainnet and it looks happy. The only thing I will need to make it happen and run on the primary mainnet node is the final network magic numbers.

The seed address shall be `dnsseed.mainnet.z.cash`. That sound OK? Or should we just use `dnsseed.z.cash`... indicate your preference.

**Comment by ebfull** [comment]
I prefer `dnsseed.z.cash` for mainnet. Down with the mainnet/testnet dichotomy! :peace_symbol:
