### ISSUE TITLE
low-variance reward PoW

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#137]
Low-variance rewards for mining could make the difference between small-time solo miner viability or not.

Suppose the difficulty is such that a given miner expects to win a block within 1 year, and the block reward is `R`.  If they can instead receive `R/365` units per day for the same work, this might affect the barrier to entry.

I haven't yet searched for low-variance PoW but @amiller's talk at MITBTC15 alluded to "many high speed low reward blocks", so I guess I should ask him first.

**Comment by nuttycom** [comment]
@daira doesn't know how to do this securely, and we're planning to move to proof-of-stake anyway.
