### ISSUE TITLE
Make the RPC error clearer when failing to spend coinbase

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#1373]
It appears that some users are having trouble spending coinbase (e.g. [here](https://forum.z.cash/t/can-anyone-use-the-mining-reward/1639?u=str4d)). The RPC error doesn't indicate that the problem is with the consensus rule that coinbase must be spent in a JoinSplit. We should see if we can improve the error message.

**Comment by bitcartel** [comment]
The message below is output in SendMoney which is only used by RPC call sendfrom and sendtoaddress, so user was trying to spend coinbase taddr with upstream RPC, which is not possible since it must goto a zaddr:

> "Error: The transaction was rejected! This might happen if some of the coins in your wallet were already spent, such as if you used a copy of wallet.dat and coins were spent in the copy but not marked as spent here."

**Comment by str4d** [comment]
[Postponed to rc1](https://github.com/zcash/zcash/pull/1431#issuecomment-251469137).

**Comment by bitcartel** [comment]
We should document the current rules around spending coinbase utxos because its confusing.

**Comment by arcalinea** [comment]
Documented in the Mining Wiki: https://github.com/zcash/zcash/wiki/Mining-Guide

**Comment by str4d** [comment]
Fixed by #1431.
