### ISSUE TITLE
Release final software in advance of genesis block

### ISSUE THREAD

**Issue by daira** [zcash/zcash#1379]
Currently the genesis block is compiled into the software. If this is still the case at launch, then it won't be possible to release the final signed binaries before launch. This might cause operational problems such as a rush to download the final binaries, reduced time to test them, etc.

If the mainnet genesis block information were in a separate file, then that could be released on October 28 even though the software can have been signed and tested well in advance. (Note that if it's generated after the software is signed then it can't be authenticated by a hash in the software, but it could be signed by the same mechanism as the software.)

**Comment by ebfull** [comment]
Does the mining slow start not obviate the need to release signed binaries well in advance of the launch?

**Comment by daira** [comment]
I don't think so, because testing the release in advance could reveal issues that might otherwise cause us to need to reset the blockchain, and we don't want to have to do that for PR reasons regardless of how much or little value is at stake.

**Comment by ebfull** [comment]
Why does testing the release in advance require signed binaries?

**Comment by daira** [comment]
Because there are points of failure that could only be detected by testing exactly the same build that we sign.

Remember that testing is only half the issue; the other half is allowing users to install the software, and resolve any installation problems on their system, before the genesis block is available.

**Comment by nathan-at-least** [comment]
We've decided not to do this and to use our normal release procedure because we already know that process and it doesn't introduce new software changes or processes. This introduces risk and takes time to implement.
