### ISSUE TITLE
ZCA-001 - DoS attack if orphan joinsplit transactions were enabled.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#1385]
We've marked this as invalid because _at this time_ (as of ``v1.0.0-beta1`` and planned for launch) any orphan transaction with a JoinSplit is omitted from ``mapOrphans``. I believe this means we take a performance penalty, for the benefit of avoiding this kind of DOS vulnerability.

**Comment by str4d** [comment]
The decision to omit JoinSplit-containing transactions from `mapOrphans` was made in #523.
