### ISSUE TITLE
ZCA­002 - Inheriting FindAndDelete from Bitcoin is considered dangerous

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#1386]

**Comment by nathan-at-least** [comment]
We are going to attempt this fix in Beta 2, but we should timebox it, in case of exploding complexity / or perpetual "just one more snag" risk.

**Comment by daira** [comment]
Can you explain the issue in more detail?

**Comment by SergioDemianLerner** [comment]
FindAndDelete exposes a number of implementation details in the scripting system that should not be visible and should not affect consensus.
Peter Todd wrote an excellent review of the consequences of FindAndDelete() here https://decred.org/research/todd2014.pdf
And there are more reasons.
There is no adverse effect of just removing FindAndDelete() call in zCash.

**Comment by SergioDemianLerner** [comment]
If not, you could merge this improvement in 0.13: https://github.com/bitcoin/bitcoin/pull/7907

**Comment by nathan-at-least** [comment]
We're fairly confident following the audit recommendations is possible for this milestone, so let's do it.

**Comment by nathan-at-least** [comment]
Note: we may have some unittests that relied on the "hash == 1" exceptional case and/or ``FindAndDelete``, so make sure they're updated appropriately, as per #1118.

**Comment by jl2012** [comment]
FYI, segregated witness in Bitcoin has also dropped FindAndDelete
