### ISSUE TITLE
Update `security-warnings.md` to point out reorgs past an anchor will rollback transactions.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#1392]
Bitcoin's coinbase maturity helps ensure that any reorg shorter than the maturity interval will not invalidate any of the rolled-back transactions. (This doesn't prevent doublespends, either accidental or intentional.)

This means if there were, say a 1 day reorg, but the maturity interval is longer than 1 day, users can mostly assume that their transactions over the past day will still (eventually) end up in the new chain. Exceptions to this are double-spends or transactions falling out of all memory pools.

By contrast, JoinSplits which were anchored within the reorg interval all necessarily become invalid (thus reverting the funds to the original owner). This is qualitatively quite different, and could be surprising to users, and is therefore something we should warn them about,

**Comment by nathan-at-least** [comment]
This may be important enough to highlight beyond just ``security-warnings.md``.

**Comment by daira** [comment]
Note that the existing transaction rebroadcast mechanism inherited from Bitcoin will not successfully rebroadcast transactions containing JoinSplits if the anchor needs to change. Only the JoinSplit creator can do that.

**Comment by daira** [comment]
This interacts with the choice of minconf, but I don't think a low minconf itself is the problem. The probability of a reorg at a given depth happening isn't directly affected by the reorg-past-anchor issue (except in terms of attack incentives); that issue only affects the likelihood of a transaction getting back into the chain -- which as @zookozcash said on #1409, isn't something that users can rely on even in Bitcoin.

*However*, reorg probability is affected by the shorter block target time, and therefore might need to be higher than in Bitcoin for that reason. For example if you chose minconf=1 in Bitcoin, you might need to choose up to minconf=4 (which is the same latency) in Zcash. Also, the aggregate hash power of Zcash is going to be lower than Bitcoin for the foreseeable future, making rollback attacks potentially easier.

**Comment by arcalinea** [comment]
Is this an appropriate warning to include in security-warnings.md?

Confirmations and Reorgs
----------------------------

When using a low number of minimum confirmations, users should be aware of new behavior in Zcash that differs significantly from Bitcoin. In the case of a blockchain reorganization, Bitcoin's coinbase maturity helps ensure that any reorg shorter than the maturity interval will not invalidate any of the rolled-back transactions. However for Zcash, all JoinSplits which were anchored within the reorg interval will become invalid, rolling back transactions and reverting funds to the original owner. The transaction rebroadcast mechanism inherited from Bitcoin will not successfully rebroadcast transactions containing JoinSplits if the anchor needs to change--the JoinSplit creator must do that.

**Comment by daira** [comment]
Yes, that looks right. The problem is really with how recent the anchor is, but users currently have no control over that, and so the above warning is accurate as far as it goes.

**Comment by arcalinea** [comment]
Added in PR #1473
