### ISSUE TITLE
Document how to enable funds for imported keys

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#1395]
For 1.0, instead of fixing #1350, we are going to document that after importing a zaddr, a user can just start their node once with `-reindex` in order to enable spending of any funds linked to that address.

Requires #1394.

**Comment by nathan-at-least** [comment]
Example text: https://github.com/zcash/zcash/issues/1350#issuecomment-246858060

**Comment by daira** [comment]
> Due to a known bug, if you import a zkey, the wallet may not detect old funds (/ notes). In order to ensure all funds are seen, please restart with -rescan which may take a while to update your wallet against the blockchain.

The text should reference the ticket URL for the known bug (#1350).

**Comment by str4d** [comment]
Note that the command to use will be `-reindex` for beta 2, not `-rescan` (unless I somehow get the latter finished in time).

**Comment by arcalinea** [comment]
Should this info be included in `payment-api.md`?

**Comment by str4d** [comment]
We sort-of documented this in the blog post for beta 2.

**Comment by arcalinea** [comment]
Documented this in the wiki, under "Protecting your Testcoins": https://github.com/zcash/zcash/wiki/Beta-Guide
