### ISSUE TITLE
Ensure that the consensus rules for the Founders' Reward are consistent

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#1405]
https://github.com/zcash/zcash/pull/1398#r78873403 indicates that there may be a bug in the Founders' Reward consensus rules. We need to ensure that they are consistent with [what we have told users](https://z.cash/blog/funding.html).

**Comment by daira** [comment]
I'm currently writing the spec for this. (The Founders' Reward was previously not specified; that was a TODO.)

**Comment by daira** [comment]
The spec has been updated (2016.0-beta-1.5 on master).
