### ISSUE TITLE
Warn users when using a low minconf, because reorgs are more dangerous than Bitcoin.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#1409]
We might care more about anchors than minconf...

**Comment by zookozcash** [comment]
I don't get why this is "dangerous". Isn't the difference between Bitcoin and Zcash that in Bitcoin almost all (but not necessarily all) of the transactions get automatically re-applied after a reorg, and in Zcash the same is true, but private transactions are more likely to get dropped?

The only danger that I see here is if users get used to the "fire and forget" assumption. They shouldn't! If they come to rely on a fired-and-forgotten transaction to be confirmed, then that's dangerous, and it is dangerous for Bitcoin users as well as for Zcash users.

**Comment by daira** [comment]
@zookozcash : it is still a significant change in behaviour from Bitcoin. I would classify it as a reliability issues rather than calling it "dangerous", though.

**Comment by daira** [comment]
As far as I can see this is a duplicate of #1392, or at least we don't need two separate warnings for this.
