### ISSUE TITLE
Test Fail: [  FAILED  ] wallet_zkeys_tests.write_zkey_direct_to_db

### ISSUE THREAD

**Issue by questulent** [zcash/zcash#1413]
Upgraded according to new Beta guidelines. Ran test - failed. Details here

---

===== BEGIN: /home/andrew/zcash/qa/zcash/check-security-hardening.sh
make: Entering directory '/home/andrew/zcash/src'
Checking binary security of [zcashd zcash-cli bitcoin-tx test/test_bitcoin zcash-gtest   zcash/GenerateParams]...
make: Leaving directory '/home/andrew/zcash/src'
PASS: /home/andrew/zcash/src/zcashd has no RPATH or RUNPATH.
PASS: /home/andrew/zcash/src/zcash-cli has no RPATH or RUNPATH.
PASS: /home/andrew/zcash/src/zcash-gtest has no RPATH or RUNPATH.
PASS: /home/andrew/zcash/src/bitcoin-tx has no RPATH or RUNPATH.
PASS: /home/andrew/zcash/src/test/test_bitcoin has no RPATH or RUNPATH.
PASS: /home/andrew/zcash/src/zcash/GenerateParams has no RPATH or RUNPATH.
PASS: /home/andrew/zcash/src/zcashd has FORTIFY_SOURCE.
PASS: /home/andrew/zcash/src/zcash-cli has FORTIFY_SOURCE.
PASS: /home/andrew/zcash/src/zcash-gtest has FORTIFY_SOURCE.
PASS: /home/andrew/zcash/src/bitcoin-tx has FORTIFY_SOURCE.
PASS: /home/andrew/zcash/src/test/test_bitcoin has FORTIFY_SOURCE.
PASS: /home/andrew/zcash/src/zcash/GenerateParams has FORTIFY_SOURCE.
===== PASSED: /home/andrew/zcash/qa/zcash/check-security-hardening.sh
===== BEGIN: /home/andrew/zcash/qa/zcash/ensure-no-dot-so-in-depends.py
PASS.
===== PASSED: /home/andrew/zcash/qa/zcash/ensure-no-dot-so-in-depends.py
===== BEGIN: make check || { echo === ./src/test-suite.log === ; cat ./src/test-suite.log ; false ; }
Making check in src
make[1]: Entering directory '/home/andrew/zcash/src'
make[2]: Entering directory '/home/andrew/zcash/src'
make  check-TESTS check-local
make[3]: Entering directory '/home/andrew/zcash/src'
make[4]: Entering directory '/home/andrew/zcash/src'
PASS: test/test_bitcoin
FAIL: zcash-gtest
============================================================================
Testsuite summary for Zcash 1.0.0
============================================================================
# TOTAL: 2
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See src/test-suite.log
Please report to https://github.com/zcash/zcash/issues
============================================================================
Makefile:7432: recipe for target 'test-suite.log' failed
make[4]: *** [test-suite.log] Error 1
make[4]: Leaving directory '/home/andrew/zcash/src'
Makefile:7538: recipe for target 'check-TESTS' failed
make[3]: *** [check-TESTS] Error 2
make[3]: Leaving directory '/home/andrew/zcash/src'
Makefile:7651: recipe for target 'check-am' failed
make[2]: *** [check-am] Error 2
make[2]: Leaving directory '/home/andrew/zcash/src'
Makefile:7325: recipe for target 'check-recursive' failed
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory '/home/andrew/zcash/src'
Makefile:644: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1
=== ./src/test-suite.log ===
=====================================
   Zcash 1.0.0: src/test-suite.log
=====================================

# TOTAL: 2
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: zcash-gtest
=================

[==========] Running 90 tests from 16 test cases.
[----------] Global test environment set-up.
[----------] 1 test from json_spirit_tests
[ RUN      ] json_spirit_tests.nested_input_segfault
[       OK ] json_spirit_tests.nested_input_segfault (1 ms)
[----------] 1 test from json_spirit_tests (1 ms total)

[----------] 1 test from tautologies
[ RUN      ] tautologies.seven_eq_seven
[       OK ] tautologies.seven_eq_seven (0 ms)
[----------] 1 test from tautologies (0 ms total)

[----------] 23 tests from checktransaction_tests
[ RUN      ] checktransaction_tests.check_vpub_not_both_nonzero
[       OK ] checktransaction_tests.check_vpub_not_both_nonzero (0 ms)
[ RUN      ] checktransaction_tests.valid_transaction
[       OK ] checktransaction_tests.valid_transaction (0 ms)
[ RUN      ] checktransaction_tests.bad_txns_vin_empty
[       OK ] checktransaction_tests.bad_txns_vin_empty (0 ms)
[ RUN      ] checktransaction_tests.bad_txns_vout_empty
[       OK ] checktransaction_tests.bad_txns_vout_empty (1 ms)
[ RUN      ] checktransaction_tests.bad_txns_oversize
[       OK ] checktransaction_tests.bad_txns_oversize (27 ms)
[ RUN      ] checktransaction_tests.bad_txns_vout_negative
[       OK ] checktransaction_tests.bad_txns_vout_negative (0 ms)
[ RUN      ] checktransaction_tests.bad_txns_vout_toolarge
[       OK ] checktransaction_tests.bad_txns_vout_toolarge (1 ms)
[ RUN      ] checktransaction_tests.bad_txns_txouttotal_toolarge_outputs
[       OK ] checktransaction_tests.bad_txns_txouttotal_toolarge_outputs (0 ms)
[ RUN      ] checktransaction_tests.bad_txns_txouttotal_toolarge_joinsplit
[       OK ] checktransaction_tests.bad_txns_txouttotal_toolarge_joinsplit (0 ms)
[ RUN      ] checktransaction_tests.bad_txns_txintotal_toolarge_joinsplit
[       OK ] checktransaction_tests.bad_txns_txintotal_toolarge_joinsplit (1 ms)
[ RUN      ] checktransaction_tests.bad_txns_vpub_old_negative
[       OK ] checktransaction_tests.bad_txns_vpub_old_negative (0 ms)
[ RUN      ] checktransaction_tests.bad_txns_vpub_new_negative
[       OK ] checktransaction_tests.bad_txns_vpub_new_negative (0 ms)
[ RUN      ] checktransaction_tests.bad_txns_vpub_old_toolarge
[       OK ] checktransaction_tests.bad_txns_vpub_old_toolarge (1 ms)
[ RUN      ] checktransaction_tests.bad_txns_vpub_new_toolarge
[       OK ] checktransaction_tests.bad_txns_vpub_new_toolarge (0 ms)
[ RUN      ] checktransaction_tests.bad_txns_vpubs_both_nonzero
[       OK ] checktransaction_tests.bad_txns_vpubs_both_nonzero (0 ms)
[ RUN      ] checktransaction_tests.bad_txns_inputs_duplicate
[       OK ] checktransaction_tests.bad_txns_inputs_duplicate (0 ms)
[ RUN      ] checktransaction_tests.bad_joinsplits_nullifiers_duplicate_same_joinsplit
[       OK ] checktransaction_tests.bad_joinsplits_nullifiers_duplicate_same_joinsplit (1 ms)
[ RUN      ] checktransaction_tests.bad_joinsplits_nullifiers_duplicate_different_joinsplit
[       OK ] checktransaction_tests.bad_joinsplits_nullifiers_duplicate_different_joinsplit (0 ms)
[ RUN      ] checktransaction_tests.bad_cb_has_joinsplits
[       OK ] checktransaction_tests.bad_cb_has_joinsplits (0 ms)
[ RUN      ] checktransaction_tests.bad_cb_empty_scriptsig
[       OK ] checktransaction_tests.bad_cb_empty_scriptsig (1 ms)
[ RUN      ] checktransaction_tests.bad_txns_prevout_null
[       OK ] checktransaction_tests.bad_txns_prevout_null (0 ms)
[ RUN      ] checktransaction_tests.bad_txns_invalid_joinsplit_signature
[       OK ] checktransaction_tests.bad_txns_invalid_joinsplit_signature (0 ms)
[ RUN      ] checktransaction_tests.non_canonical_ed25519_signature
[       OK ] checktransaction_tests.non_canonical_ed25519_signature (0 ms)
[----------] 23 tests from checktransaction_tests (35 ms total)

[----------] 5 tests from equihash_tests
[ RUN      ] equihash_tests.expand_and_contract_arrays
[       OK ] equihash_tests.expand_and_contract_arrays (0 ms)
[ RUN      ] equihash_tests.minimal_solution_representation
[       OK ] equihash_tests.minimal_solution_representation (0 ms)
[ RUN      ] equihash_tests.is_probably_duplicate
[       OK ] equihash_tests.is_probably_duplicate (0 ms)
[ RUN      ] equihash_tests.check_basic_solver_cancelled
[       OK ] equihash_tests.check_basic_solver_cancelled (10 ms)
[ RUN      ] equihash_tests.check_optimised_solver_cancelled
[       OK ] equihash_tests.check_optimised_solver_cancelled (6 ms)
[----------] 5 tests from equihash_tests (16 ms total)

[----------] 3 tests from joinsplit
[ RUN      ] joinsplit.h_sig
[       OK ] joinsplit.h_sig (0 ms)
[ RUN      ] joinsplit.full_api_test
* QAP number of variables: 1887090
* QAP pre degree: 2068650
* QAP degree: 2097152
* QAP number of input variables: 9
* G1 window: 20
* G2 window: 17
* G1 elements in PK: 13419707
* Non-zero G1 elements in PK: 11258422
* G2 elements in PK: 1887092
* Non-zero G2 elements in PK: 1141155
* PK size in bits: 3721036065
* G1 elements in VK: 11
* G2 elements in VK: 5
* VK size in bits: 6181
[       OK ] joinsplit.full_api_test (370257 ms)
[ RUN      ] joinsplit.note_plaintexts
[       OK ] joinsplit.note_plaintexts (1 ms)
[----------] 3 tests from joinsplit (370258 ms total)

[----------] 2 tests from keystore_tests
[ RUN      ] keystore_tests.store_and_retrieve_spending_key
[       OK ] keystore_tests.store_and_retrieve_spending_key (0 ms)
[ RUN      ] keystore_tests.store_and_retrieve_note_decryptor
[       OK ] keystore_tests.store_and_retrieve_note_decryptor (0 ms)
[----------] 2 tests from keystore_tests (0 ms total)

[----------] 6 tests from noteencryption
[ RUN      ] noteencryption.api
[       OK ] noteencryption.api (171 ms)
[ RUN      ] noteencryption.prf_addr
[       OK ] noteencryption.prf_addr (1 ms)
[ RUN      ] noteencryption.prf_nf
[       OK ] noteencryption.prf_nf (0 ms)
[ RUN      ] noteencryption.prf_pk
[       OK ] noteencryption.prf_pk (1 ms)
[ RUN      ] noteencryption.prf_rho
[       OK ] noteencryption.prf_rho (1 ms)
[ RUN      ] noteencryption.uint252
[       OK ] noteencryption.uint252 (0 ms)
[----------] 6 tests from noteencryption (174 ms total)

[----------] 8 tests from merkletree
[ RUN      ] merkletree.vectors
[       OK ] merkletree.vectors (49938 ms)
[ RUN      ] merkletree.emptyroots
[       OK ] merkletree.emptyroots (0 ms)
[ RUN      ] merkletree.emptyroot
[       OK ] merkletree.emptyroot (0 ms)
[ RUN      ] merkletree.deserializeInvalid
[       OK ] merkletree.deserializeInvalid (0 ms)
[ RUN      ] merkletree.deserializeInvalid2
[       OK ] merkletree.deserializeInvalid2 (0 ms)
[ RUN      ] merkletree.deserializeInvalid3
[       OK ] merkletree.deserializeInvalid3 (0 ms)
[ RUN      ] merkletree.deserializeInvalid4
[       OK ] merkletree.deserializeInvalid4 (0 ms)
[ RUN      ] merkletree.testZeroElements
[       OK ] merkletree.testZeroElements (2 ms)
[----------] 8 tests from merkletree (49940 ms total)

[----------] 1 test from PoW
[ RUN      ] PoW.DifficultyAveraging
[       OK ] PoW.DifficultyAveraging (1 ms)
[----------] 1 test from PoW (1 ms total)

[----------] 1 test from rpc
[ RUN      ] rpc.check_blockToJSON_returns_minified_solution
[       OK ] rpc.check_blockToJSON_returns_minified_solution (0 ms)
[----------] 1 test from rpc (0 ms total)

[----------] 3 tests from circuit
[ RUN      ] circuit.values
[       OK ] circuit.values (0 ms)
[ RUN      ] circuit.endianness
[       OK ] circuit.endianness (0 ms)
[ RUN      ] circuit.merkle_tree_gadget_weirdness
[       OK ] circuit.merkle_tree_gadget_weirdness (29590 ms)
[----------] 3 tests from circuit (29590 ms total)

[----------] 2 tests from txid_tests
[ RUN      ] txid_tests.check_txid_and_hash_are_same
[       OK ] txid_tests.check_txid_and_hash_are_same (0 ms)
[ RUN      ] txid_tests.check_txid_and_hash_are_same_coinbase
[       OK ] txid_tests.check_txid_and_hash_are_same_coinbase (0 ms)
[----------] 2 tests from txid_tests (0 ms total)

[----------] 2 tests from wallet_zkeys_tests
[ RUN      ] wallet_zkeys_tests.store_and_load_zkeys
[       OK ] wallet_zkeys_tests.store_and_load_zkeys (0 ms)
[ RUN      ] wallet_zkeys_tests.write_zkey_direct_to_db
unknown file: Failure
C++ exception with description "locale::facet::_S_create_c_locale name not valid" thrown in the test body.
[  FAILED  ] wallet_zkeys_tests.write_zkey_direct_to_db (1 ms)
[----------] 2 tests from wallet_zkeys_tests (1 ms total)

[----------] 2 tests from libzcash_utils
[ RUN      ] libzcash_utils.convertBytesVectorToVector
[       OK ] libzcash_utils.convertBytesVectorToVector (0 ms)
[ RUN      ] libzcash_utils.convertVectorToInt
[       OK ] libzcash_utils.convertVectorToInt (0 ms)
[----------] 2 tests from libzcash_utils (0 ms total)

[----------] 17 tests from proofs
[ RUN      ] proofs.sqrt_zero
[       OK ] proofs.sqrt_zero (0 ms)
[ RUN      ] proofs.sqrt_fq
[       OK ] proofs.sqrt_fq (69 ms)
[ RUN      ] proofs.sqrt_fq2
[       OK ] proofs.sqrt_fq2 (691 ms)
[ RUN      ] proofs.size_is_expected
[       OK ] proofs.size_is_expected (0 ms)
[ RUN      ] proofs.fq_serializes_properly
[       OK ] proofs.fq_serializes_properly (3 ms)
[ RUN      ] proofs.fq2_serializes_properly
[       OK ] proofs.fq2_serializes_properly (6 ms)
[ RUN      ] proofs.fq_valid
[       OK ] proofs.fq_valid (0 ms)
[ RUN      ] proofs.fq_invalid
[       OK ] proofs.fq_invalid (0 ms)
[ RUN      ] proofs.fq2_valid
[       OK ] proofs.fq2_valid (0 ms)
[ RUN      ] proofs.fq2_invalid
[       OK ] proofs.fq2_invalid (0 ms)
[ RUN      ] proofs.g1_serializes_properly
[       OK ] proofs.g1_serializes_properly (383 ms)
[ RUN      ] proofs.g2_serializes_properly
[       OK ] proofs.g2_serializes_properly (1871 ms)
[ RUN      ] proofs.zksnark_serializes_properly
Swap is not beneficial, not performing
* QAP number of variables: 252
* QAP pre degree: 250
* QAP degree: 256
* QAP number of input variables: 4
* G1 window: 8
* G2 window: 6
* G1 elements in PK: 1783
* Non-zero G1 elements in PK: 1763
* G2 elements in PK: 254
* Non-zero G2 elements in PK: 252
* PK size in bits: 625897
* G1 elements in VK: 6
* G2 elements in VK: 5
* VK size in bits: 4586
[       OK ] proofs.zksnark_serializes_properly (4307 ms)
[ RUN      ] proofs.g1_deserialization
[       OK ] proofs.g1_deserialization (158 ms)
[ RUN      ] proofs.g2_deserialization
[       OK ] proofs.g2_deserialization (1433 ms)
[ RUN      ] proofs.g1_test_vectors
[       OK ] proofs.g1_test_vectors (3888 ms)
[ RUN      ] proofs.g2_test_vectors
[       OK ] proofs.g2_test_vectors (18907 ms)
[----------] 17 tests from proofs (31718 ms total)

[----------] 13 tests from wallet_tests
[ RUN      ] wallet_tests.note_data_serialisation
[       OK ] wallet_tests.note_data_serialisation (1 ms)
[ RUN      ] wallet_tests.find_unspent_notes
[       OK ] wallet_tests.find_unspent_notes (6 ms)
[ RUN      ] wallet_tests.set_note_addrs_in_cwallettx
[       OK ] wallet_tests.set_note_addrs_in_cwallettx (1 ms)
[ RUN      ] wallet_tests.set_invalid_note_addrs_in_cwallettx
[       OK ] wallet_tests.set_invalid_note_addrs_in_cwallettx (0 ms)
[ RUN      ] wallet_tests.find_note_in_tx
[       OK ] wallet_tests.find_note_in_tx (1 ms)
[ RUN      ] wallet_tests.get_conflicted_notes
[       OK ] wallet_tests.get_conflicted_notes (2 ms)
[ RUN      ] wallet_tests.nullifier_is_spent
[       OK ] wallet_tests.nullifier_is_spent (1 ms)
[ RUN      ] wallet_tests.navigate_from_nullifier_to_note
[       OK ] wallet_tests.navigate_from_nullifier_to_note (1 ms)
[ RUN      ] wallet_tests.spent_note_is_from_me
[       OK ] wallet_tests.spent_note_is_from_me (2 ms)
[ RUN      ] wallet_tests.cached_witnesses_empty_chain

[WARNING] ../src/gtest-death-test.cc:825:: Death tests use fork(), which is unsafe particularly in a threaded context. For this test, Google Test couldn't detect the number of threads.
[       OK ] wallet_tests.cached_witnesses_empty_chain (257 ms)
[ RUN      ] wallet_tests.cached_witnesses_chain_tip
[       OK ] wallet_tests.cached_witnesses_chain_tip (3 ms)
[ RUN      ] wallet_tests.UpdatedNoteData
[       OK ] wallet_tests.UpdatedNoteData (1 ms)
[ RUN      ] wallet_tests.MarkAffectedTransactionsDirty
[       OK ] wallet_tests.MarkAffectedTransactionsDirty (2 ms)
[----------] 13 tests from wallet_tests (278 ms total)

[----------] Global test environment tear-down
[==========] 90 tests from 16 test cases ran. (482012 ms total)
[  PASSED  ] 89 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] wallet_zkeys_tests.write_zkey_direct_to_db

 1 FAILED TEST
FAIL zcash-gtest (exit status: 1)

===== FAILED: make check || { echo === ./src/test-suite.log === ; cat ./src/test-suite.log ; false ; }

**Comment by questulent** [comment]
Update: Still seeing this problem. New install today of Beta on sever #1, and an upgrade on server #2, and both failed this test: “wallet_zkeys_tests.write_zkey_direct_to_db”

**Comment by daira** [comment]
```
[ RUN ] wallet_zkeys_tests.write_zkey_direct_to_db
unknown file: Failure
C++ exception with description "locale::facet::_S_create_c_locale name not valid" thrown in the test body.
```

This appears to be a locale-related error. Please paste the output of ``locale``.

**Comment by questulent** [comment]
HI Daira,

locale outputs:

locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_ZA.UTF-8
LANGUAGE=en_ZA:en
LC_CTYPE=UTF-8
LC_NUMERIC="en_ZA.UTF-8"
LC_TIME="en_ZA.UTF-8"
LC_COLLATE="en_ZA.UTF-8"
LC_MONETARY="en_ZA.UTF-8"
LC_MESSAGES="en_ZA.UTF-8"
LC_PAPER="en_ZA.UTF-8"
LC_NAME="en_ZA.UTF-8"
LC_ADDRESS="en_ZA.UTF-8"
LC_TELEPHONE="en_ZA.UTF-8"
LC_MEASUREMENT="en_ZA.UTF-8"
LC_IDENTIFICATION="en_ZA.UTF-8"
LC_ALL=

**Comment by questulent** [comment]
Solved. Had to add 2 lines to etc/default/locale.
LC_CTYPE="en_ZA.UTF-8"
LC_ALL="en_ZA.UTF-8"
Thanks for the direction!
