### ISSUE TITLE
Transparent private keys fail to import into zcash (encoding error)

### ISSUE THREAD

**Issue by ampyx** [zcash/zcash#1414]
According to the specs (section 5.6.2 and 5.6.1) it should be theoretically possible to import a private key from the bitcoin wallet to the zcash wallet, since the spec states that the private and public keys of Zcash have exactly the same encoding as Bitcoin. This spec would also mean that users should be able to use existing 3rd party utilities to generate transparent wallets for Zcash. However it turns out that this is not the case: we get an "invalid private key encoding" error.

Please correct me if I am wrong here, but according to the specs I think this should be possible:

```bash
ampy@euih42-ee:~/zcash/src$ bitcoin-cli getaddressesbyaccount ""
[
  "1MzGN3zeLLko9PCyxfZsvBexHGRN9a9XR", 
  "1BvgsfsZQVtkLS69NvGF8rw6NZW2ShJQHr"
]
ampy@euih42-ee:~/zcash/src$ bitcoin-cli dumpprivkey 1MzGN3zeLLko9PCyxfZsvBexHGRN9a9XR
L2D7Ba7ZeaxSowxMwHGHTq55j5yqoao68ryBFzEs7HqaW7W4XaTv
ampy@euih42-ee:~/zcash/src$ ./zcash-cli importprivkey L2D7Ba7ZeaxSowxMwHGHTq55j5yqoao68ryBFzEs7HqaW7W4XaTv
error: {"code":-5,"message":"Invalid private key encoding"}
ampy@euih42-ee:~/zcash/src$ 
```

Or the other way around

```bash
ampy@euih42-ee:~/zcash/src$ ./zcash-cli getaddressesbyaccount ""
[
    "n1EbdDCXWRsFtJ5ecAo1BLAHY5xrHkMcan"
]
ampy@euih42-ee:~/zcash/src$ ./zcash-cli dumpprivkey n1EbdDCXWRsFtJ5ecAo1BLAHY5xrHkMcan
cNZiv9r95aSmJPkKVn3FjzBvN5wBP6fbZPKL6hcY1UuHfAgDj1Qj
ampy@euih42-ee:~/zcash/src$ bitcoin-cli importprivkey cNZiv9r95aSmJPkKVn3FjzBvN5wBP6fbZPKL6hcY1UuHfAgDj1Qj
error code: -5
error message:
Invalid private key encoding
ampy@euih42-ee:~/zcash/src$ 
```

Don't worry, these private keys will never be used for any wallet! I put them here to proof my point. 

This bug is very unfortunate, because it means that 3rd party utils cannot be used to generate transparent wallets for zcash.

**Comment by bitcartel** [comment]
Hmm.  It looks like your Bitcoin node is running on Mainnet, whereas Zcash is running on Testnet.  Try putting Bitcoin into Testnet mode and repeating the above.  Also note that transparent addresses on Zcash mainnet will have a different prefix from that used by Bitcoin mainnet.

**Comment by ampyx** [comment]
@bitcartel Thanks. It seems to work when both daemons are running in the same mode. Could you tell me which prefix is enforced on zcash transparent addresses?

```bash
ampy@euih42-ee:~/zcash/src$ bitcoin-cli getaddressesbyaccount ""
[
  "myrEh5pmhK3wanYRJhwX7TALpy22Qg97zd"
]
ampy@euih42-ee:~/zcash/src$ bitcoin-cli dumpprivkey myrEh5pmhK3wanYRJhwX7TALpy22Qg97zd
cTQyR1JqwdmFnUTHvP5ddujtVHZjaqMUE5mHg8njj51HXXU6Uhiw
ampy@euih42-ee:~/zcash/src$ ./zcash-cli importprivkey cTQyR1JqwdmFnUTHvP5ddujtVHZjaqMUE5mHg8njj51HXXU6Uhiw
ampy@euih42-ee:~/zcash/src$
```

**Comment by daira** [comment]
I don't think we've decided on that prefix yet. That's why the spec hasn't been updated.

**Comment by ampyx** [comment]
Not to be pushing or anything, but do you have a date for this? 👍

**Comment by daira** [comment]
Probably beta 2.

**Comment by daira** [comment]
See #812.

**Comment by daira** [comment]
And no problem with pushing :-)

**Comment by daira** [comment]
#812 was merged for beta 2, and the spec updated to include the new prefixes.
