### ISSUE TITLE
Document that: Nodes behind the same public IP may not be able to connect independently

### ISSUE THREAD

**Issue by daira** [zcash/zcash#1416]
https://forum.z.cash/t/internal-ips-connection-problem/1801

**Comment by daira** [comment]
It's an upstream issue: https://bitcointalk.org/index.php?topic=877949.0

**Comment by daira** [comment]
I think we want to document this limitation and maybe mention port forwarding as a solution, but we don't have time to change any code to address it before launch.

**Comment by arcalinea** [comment]
add `known-bugs.md` file that note security warnings that are also known bugs

**Comment by marsmensch** [comment]
I don't know if port forwarding is the right approach, it mostly leads to badly configured nodes.

Personally, i think a properly tested tor setup is the best (but more complex) option. This could be documented without even touching the code.

**Comment by Pr0methean** [comment]
Is this limitation still present? The bug is very old. I can't reproduce because I only have one PC.

**Comment by daira** [comment]
I don't think we've changed anything that would affect this.

**Comment by ioptio** [comment]
Moved the tracking of this ticket to the docs repo: https://gitlab.com/zcash-docs/zcash-docs/issues/46
