### ISSUE TITLE
Run throughs of "release parameters update".

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#1419]
There are at least three production release parameters we must update for our launch:

* zkSNARK params
* Founder's Reward address table
* genesis block - timestamp, well-known-news evidence, starting difficulty selection, genesis block generation, and test vector updates.

Let's do practice run-throughs of this release process with test data.

**Comment by nathan-at-least** [comment]
Do we need to change the genesis block subsidy to be 0, thus being consistent with mining slow start? There might be problems with that, so we could test it. It would be nice for avoiding future confusion. (This subsidy cannot be spent anyway, so it doesn't have an effect other than cognitive load / confusion.)

**Comment by daira** [comment]
Yes, the genesis block subsidy should be zero. (That's what is specified by https://github.com/zcash/zips/blob/zips63.specify-founders-reward.0/protocol/protocol.pdf section 6.5.)

**Comment by nathan-at-least** [comment]
@daira I agree for cognitive simplicity. However, there may be some implementation snags, so let's timebox that change, and revert to no-change-from-Bitcoin if we hit the timebox limit.

**Comment by daira** [comment]
I thought the testnet was already using a genesis block reward of zero? (I could be wrong.)

**Comment by bitcartel** [comment]
@daira #1453 was closed, does this mean the protocol spec in section 6.5 mentioned above should change?

**Comment by daira** [comment]
I *can* document this bug, but it goes against the grain (and I would have to analyse why the first block reward can't be spent). Are we sure we can't fix this and test it on the private mainnet?

**Comment by str4d** [comment]
As discussed in the engineering meeting, the problem was that we needed to regenerate the genesis block and miner tests, which we didn't have time to do for beta 2 (since nothing else required it).

**Comment by daira** [comment]
There's no reason we can't leave the current genesis block for testnet, but generate one with a zero block reward for mainnet.

**Comment by daira** [comment]
There's no reason we can't leave the current genesis block for testnet, but generate one with a zero block reward for mainnet.

**Comment by daira** [comment]
There's no reason we can't leave the current genesis block for testnet, but generate one with a zero block reward for mainnet.

**Comment by str4d** [comment]
We could; we'd need to separately set the genesis block reward to 50 ZEC for testnet, since otherwise it would be altered. However, when we generate the genesis block for mainnet, we *will* be regenerating the testnet genesis block too, since it uses the same date and string chosen for mainnet (unless we also persist those inside testnet params).

**Comment by daira** [comment]
Ah OK, I hasn't realised that. I had hoped we wouldn't need to reset the testnet again before launch.

**Comment by str4d** [comment]
It is possible to not do so, but that would require duplicating any mainnet parameter we change for launch into testnet. So, testnet reset vs. difference in parameters / more LoC.

**Comment by nathan-at-least** [comment]
We can use existing "fallback" values when doing this.

**Comment by daira** [comment]
The genesis block coinbase value was set to 0 in rc2. The rest of this ticket is for rc3.

**Comment by nathan-at-least** [comment]
This is no longer necessary since we'll do the actual process for rc4.
