### ISSUE TITLE
Update documentation to refer to a "solution rate" for mining

### ISSUE THREAD

**Issue by tromp** [zcash/zcash#1422]
It seems the very name of the proof of work, "Equihash" inspires confusion,
as it is not a hash function. The often used notion of hashrate could mean
various things, like runs of the equihash algorithm, underlying blake2 hashes,
or final difficulty filtering hashes applied to solutions.
To me, only the last measure is relevant for miner performance, since alternative
solver implementations may have various numbers of expected solutions per run
(e.g. sacrificing fractions of solutions for speed).
Furthermore, that measure is better expressed not as "hashrate" but as
solution rate or solve-rate. I propose to adopt the latter term in discussing miner performance.

**Comment by str4d** [comment]
Putting this into -rc1 but not adding to the engineering agenda, so we will remember to discuss this after beta 2.

**Comment by str4d** [comment]
I think this is a relatively easy change. The only RPC it affects is `getnetworkhashps` (which we could just alias to e.g. `getnetworksolutionps`); otherwise it's just documentation changes (and a UI change in #1375). But I'm not going to think any more about it right now.

**Comment by artlav** [comment]
I can add to that an empirical observation that equihash as implemented in the daemon produces on average 2.8 solutions per run, do the 2/time formula is a little bit off.

**Comment by daira** [comment]
-1 on making any code changes for this (except comments). -1 for changing "Equihash". +1 for changing "hash rate" to "solution rate" in any documentation (actually, the protocol spec already refers only to valid Equihash solutions, it never refers to these as "hashes", which would be very ambiguous).

**Comment by tromp** [comment]
Ok,  "solution rate" is it. I'll point people still using the ambiguous "hashrate" to this discussion
and hope to get them onboard....

**Comment by daira** [comment]
BTW, I'd like "solution rate" to refer only to the actual number of solutions checked, not to a guessed rate based on the expected number of solutions. The latter introduces systematic errors.

**Comment by str4d** [comment]
Reopened this issue to track any documentation changes.

**Comment by zawy12** [comment]
@artlav  At the lower time bins with something like 20, 40, and 60 seconds for a CPU,  1 solution = 20 seconds, but that stops being true at the higher times, which I think is why the average of the times is less than the average of 20 x the average of the runs.  So 2.8 x solutions is correct, and 2 / time is correct. But it is the 2nd one that is needed for solves/time results.

**Comment by zawy12** [comment]
Can someone correct, support, or clarify @artlav 's statement for me?   Daira has said it is a little less, not 40% higher.  I'm thinking it's wrong, either because of how the "0 solution" comes into play, or because the avg(time/run)  is simply >  avg(time/solve x solves/run) because the time for say a 5-solution run is more than 5 x the time than a 1-solve run.

**Comment by daira** [comment]
I should clarify that I haven't measured it. The theoretical expected number of solutions can be calculated as follows:
```
#!/usr/bin/python

# Return product{i = x+1..y}(i/y)
def thingamajig(x, y):
    r = 1.0
    yd = float(y)
    for i in xrange(x+1, y+1):
        r *= i/yd
    return r

def solutions(n, k):
    N = 1<<(n/(k+1)+1)
    return 2 * thingamajig(N - (1<<k), N)

print solutions(200, 9)
```
which gives 1.879.

**Comment by daira** [comment]
And yes, it's not correct to calculate the expected rate as just (expected solutions * mean full solution run time); that would only be correct if the full solution run time were independent of the number of solutions, which it absolutely is not.

**Comment by tromp** [comment]
> which gives 1.879

That closely matches my 18841 total solutions found over 10000 runs of a solver.

**Comment by artlav** [comment]
Correction - my 2.8 number is likely biased, since i made the test suite out of already-mined block found on the testnet, which, by definition, are all with one or more solutions.

However, further observations of the actual solver running on the actual network reveals the existence of some amount of runs with ZERO solutions, which would, i suspect, drive the average down.

**Comment by zawy12** [comment]
The 15 to 20 second solves seen on CPUs are the zero solutions. That's why no solves from CPUs on the testnet are less than 30 seconds.

**Comment by str4d** [comment]
The devs in the mining channels on the community Slack are now using units of Sol/s, so that is what we should use in any documentation changes.

**Comment by arcalinea** [comment]
Documented in the Mining Guide wiki page: https://github.com/zcash/zcash/wiki/Mining-Guide

**Comment by arcalinea** [comment]
Closing this issue since our documentation in the Zcash repo now directs to the wiki for build and mining guides
