### ISSUE TITLE
Cannot build under a directory path containing a space

### ISSUE THREAD

**Issue by barisicm** [zcash/zcash#1425]
I am running linux ubuntu 16.04.
And i am trying to set up my z-cash for mining. However i got stuck at compiling.
Specifically, at this command : 
./zcutil/build.sh -j$(nproc)

(FYI nproc works)

I get a lot of warnings such as : 
funcs.mk:238: warning: overriding recipe for target '/home/marin/Radna'
funcs.mk:238: warning: ignoring old recipe for target '/home/marin/Radna'

And so on for atleast 90 lines.
Then i get a couple of : 
rm: cannot remove '/home/marin/Radna': To je direktorij
rm: cannot remove '/home/marin/Radna': To je direktorij

//("To je direktorij" = "This is a directory")

And in the end : 
Makefile:142: recipe for target 'check-sources' failed
make: **\* [check-sources] Error 1
make: Leaving directory '/home/marin/Radna površina/z-cash/zcash/depends'

I am not sure what is happening, or how to solve it, any help would be very welcome.

**Comment by WyseNynja** [comment]
I think the installer is failing to handle the "š" in your path

**Comment by Aelkeris** [comment]
Aaaaaaaaaaaaaand, you Sir, are very correct. 
Changed the dir, and now it works.

**Comment by daira** [comment]
Note that it could either have been the "š" or the space. (I'd bet on the space.)

**Comment by daira** [comment]
Based on this, it's definitely the space. Reopening.
```
rm: cannot remove '/home/marin/Radna': To je direktorij
```

**Comment by daira** [comment]
It may be sufficient to just detect this case and abort the build with a good error report.

**Comment by nathan-at-least** [comment]
We'll be addressing many issues like this in our 1.0.1 stabilization goal.

**Comment by daira** [comment]
autotools basically doesn't try to support this, so short of a complete overhaul of the build systems of Zcash and all its dependencies, this isn't going to happen.
