### ISSUE TITLE
IndicesBefore conflicts spec?

### ISSUE THREAD

**Issue by tromp** [zcash/zcash#1426]
The two IndicesBefore methods in equihash.h compare the *XORed* hash array,
while page 30 of the spec specifies ordering by the *concatenation* of all hashes.

If this is a real conflict rather than my misunderstanding,
I suggest changing the spec to conform to the code.

**Comment by str4d** [comment]
It doesn't compare the hashes at all, it compares the concatenated indices. Because indices are stored in big endian, and all indices should be unique, it's equivalent to a numerical comparison of the first index in each half of the collision.

**Comment by tromp** [comment]
Oh, then I just misunderstood the code.
When I saw the "memcmp(hash..."
I assumed it compared a hash, but now I remember that array is also
used to hold indices. Sorry for the confusion...

**Comment by daira** [comment]
I will check this.

**Comment by daira** [comment]
You're right, the spec is wrong (and does not match the paper or the implementation). Thanks.

**Comment by nathan-at-least** [comment]
Let's move spec issues over to the zips repo. @daira can you do this?

**Comment by daira** [comment]
Fixed in 2016.0-beta-1.6.
