### ISSUE TITLE
Running zcash issue

### ISSUE THREAD

**Issue by barisicm** [zcash/zcash#1428]
I am currently performing the "Running" section of the z cash github beta guide.
And when running the : "./src/zcashd -daemon"

I get this error (below). And i am again not sure where exactly to go.
I looked up on my filesystem, and there is no "zcash-params" file, or directory in my home/marin directory. 
And also there is no "z9-verifying.key".

EXCEPTION: St13runtime_error  
could not load param file at /home/marin/.zcash-params/z9-verifying.key  
Zcash in AppInit()

**Comment by rickster-gh** [comment]
could it be that you skipped the step: "./zcutil/fetch-params.sh" ? 
which fetches the file in question. 

from the beta-guide:
$ git clone https://github.com/zcash/zcash.git
$ cd zcash/
$ git checkout v1.0.0-beta1
$ ./zcutil/fetch-params.sh
.... build ....
.... test ....
$ ./src/zcashd -daemon

**Comment by Aelkeris** [comment]
I did all the steps besides ./zcutil/fetch-params.sh . 
Then i re did those steps (except testing, since i have a machine with 4 gb ram)
And now i get this  :

EXCEPTION: St13runtime_error       
could not load param file at /home/marin/.zcash-params/z9-verifying.key       
Zcash in AppInit()       

zcashd: scheduler.cpp:19: CScheduler::~CScheduler(): Assertion `nThreadsServicingQueue == 0' failed.

**Comment by WyseNynja** [comment]
Can you include the full output of `./zcutil/fetch-params.sh`? That should help point to why the verifying key isn't available.

**Comment by Aelkeris** [comment]
zcash - fetch-params.sh

Updating testnet3 symlinks to regtest parameters.
Verifying parameter file integrity via sha256sum...
regtest/z9-proving.key: OK
testnet3/z9-proving.key: OK
regtest/z9-verifying.key: OK
testnet3/z9-verifying.key: OK


..Yeah, i do not feel smart

**Comment by rickster-gh** [comment]
So its working now Aelkeris?

**Comment by Aelkeris** [comment]
Nope.

**Comment by Aelkeris** [comment]
Although i think i have an issue with the first part of the running.
Where the docs say that i need to make a directory and then placing the config file. 
When i input the commands specified in the docs, i get no new directory. And i am not sure if the config file already exists somwhere, or do i need to create it myself ?

**Comment by rickster-gh** [comment]
you have to create it like: 
nano ~/.zcash/zcash.conf
or whatever editor you use

**Comment by Aelkeris** [comment]
When i run "mkdir -p ~/.zcash" i get no new directory anywhere.
Or atleas i am not sure where it gets created.

**Comment by Aelkeris** [comment]
Ok, so when i first created directory, i got nothing. 
But when i created the file like you specified : "nano ~/.zcash/zcash.conf"
I got the zcash server to start.

**Comment by rickster-gh** [comment]
You can omit the '-p' as you only try to create 1 dir.
'~' points to your home directory e.g. '/home/Aelkeris'
so what you did was mkdir /home/Aelkeris/.zcash and 
nano /home/Aelkeris/.zcash/zcash.conf
don't know how familiar you are with linux but files + directories starting with a . (dot) are hidden from the default file listing.
you can do 'cd' to get into your home directory, then 'ls -la' to list all files and folders and should see the .zcash directory too.

**Comment by Aelkeris** [comment]
Well, i am a relativley new linux user, so i do not know all the quirks and nuances yet. (Or basic functionalities, depends on your point of view) But i get around.
Anyway, your solution with nano helped me. Thank you very much.

**Comment by rickster-gh** [comment]
glad you got it running now. your welcome 👍 
you can also check the z.cash website and join the slack-channels full of great people

**Comment by Aelkeris** [comment]
Can you tell me, what is the waiting time for a faucet to send me some zcash ? 

since i get nothing with :"./src/zcash-cli listunspent"

by "nothing" i mean : 
"
[
]
"

Should i just wait a bit ?

**Comment by reactivate-gh** [comment]
the listunspent cmd ist to show you coins you have created.
./src/zcash-cli getwalletinfo might be what you are looking for. 
also it takes some time for the coins to show up :)

**Comment by kehugter** [comment]
> the listunspent cmd ist to show you coins you have created.

Not really?

> listunspent ( minconf maxconf  ["address",...] )

> Returns array of unspent transaction outputs
> with between minconf and maxconf (inclusive) confirmations.

**Comment by ioptio** [comment]
This is a discussion about pre-launch zcashd. Let's assume there are no longer issues with this specifically. If there is feel free to reopen to address them.
