### ISSUE TITLE
Upgrade Google Test and Google Mock

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#1432]
Google Test 1.80 was recently released, which is the first release since the Google Mock repository was merged in. We should upgrade to use it.

Split off from #867.

**Comment by daira** [comment]
This is not security-relevant, why do we need to do it now?

**Comment by str4d** [comment]
I was doing it as part of upgrading all our dependencies, and only split it off because I couldn't get it to work immediately. I agree that this is not security-relevant, so I won't mind if it is kicked out later, but if someone did have an easy fix to my PR then it was a trivial inclusion.

**Comment by daira** [comment]
#2110 opened by @nathan-at-least was a duplicate. Its description was:
> Our dependency specification for googletest and googlemock contain [a weird hack](https://github.com/zcash/zcash/blob/be5ac31607befe2ff3796379f94a51c9bf8a6894/depends/packages/googlemock.mk#L18), since at the time googlemock wasn't a well-packaged independent dependency. According to https://github.com/google/googletest/issues/763#issuecomment-280864617 it looks like if we depend on googletest 1.8.0 it will include the mock stuff directly, and we can drop the `googlemock.md` package file completely.

**Comment by nathan-at-least** [comment]
Bumped from 1.0.9 because the PR wasn't cleanly merging.
