### ISSUE TITLE
Have a empty extrabyte between nonce and solutions vector

### ISSUE THREAD

**Issue by ocminer** [zcash/zcash#1439]
May I suggest:

C/C++ will have alignment problems with the current order / size of the vectors when writing miners:

...8045f2c5e80000 fd4005 006e053311165...

Should be changed to reflect:

8045f2c5e80000 00fd4005 006e053311165...

So we need one extra byte between 

https://github.com/zcash/zcash/blob/master/src/primitives/block.h#L32-L33

to get it aligned nicely (reflecting the 00 in example above)

Otherwise you'd have to use a helper cast like:
unsigned char *c = (unsigned char *)data[35];
memcpy(c+3, ..., 1344);

**Comment by daira** [comment]
It's too late to change this. Sorry.

**Comment by daira** [comment]
Anyway, ``nSolution`` is already 32-bit-aligned, so I don't understand how this would have helped.

**Comment by bitbandi** [comment]
not "aligned". std::vector store first the vector lenght in [compact format](https://github.com/zcash/zcash/blob/80259d4b4f193c7c438f3c057ce70af3beb1a099/src/serialize.h#L254) (which is currently 0xfd4005), and after the vector data. so the vector data started in 143 byte position, ended in 1487 byte position.

**Comment by daira** [comment]
I see. It's too late to change, though.
