### ISSUE TITLE
Document new API calls in wallet

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#1447]
New APIs in the wallet such as FindMyNotes are not documented, so using these APIs correctly involves knowledge transfer from author.  We should add comments in the code to document usage and intent before this knowledge is lost or forgotten.

**Comment by bitcartel** [comment]
Assigning @str4d and myself as we have added new methods to the wallet class recently.  May have two PRs for this.

**Comment by str4d** [comment]
Submitted my documentation PR. Leaving @bitcartel assigned to make his PR(s).

**Comment by bitcartel** [comment]
Documented in #1531 and #1533.
