### ISSUE TITLE
This is alert 1005, will disable safe mode

### ISSUE THREAD

**Issue by kost** [zcash/zcash#1449]
$ src/zcash-cli getinfo
{
    "version" : 1000000,
    "protocolversion" : 170002,
    "walletversion" : 60000,
    "balance" : 0.00000000,
    "blocks" : 2704,
    "timeoffset" : 0,
    "connections" : 8,
    "proxy" : "",
    "difficulty" : 47.51500471,
    "testnet" : true,
    "keypoololdest" : 1475037596,
    "keypoolsize" : 101,
    "paytxfee" : 0.00000000,
    "relayfee" : 0.00005000,
    "errors" : "ALERT: Please report seeing this on zcash.slack.com. This is alert 1005, will disable safe mode. Alert tests have now finished."
}

Access to zcash.slack.com is only via z.cash e-mail address.

**Comment by daira** [comment]
It's not necessary to report this alert. We should have cancelled it.
