### ISSUE TITLE
Remove OpenSSL dependency. Ref: NCC-2016-007

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#145]
I hear bitcoin-core plans to remove OpenSSL as a dependency (at least in the consensus path) as it migrates to libsecp256k1.  I _think_ it may be using the latter today for signatures and openssl for verification in a recent release or dev branch.

To close this ticket, find and document answers to these questions:
- Does upstream `v0.10.0` use `libsecp256k1` for signatures in production?
- Does upstream `v0.10.0` use `libsecp256k1` for verification in production?
- How certain is the plan to rely entirely on `libsecp256k1` for sig/verify?
- Are there already (upstream) dev branches or patches which do so?
- If upstream does this, will it still use OpenSSL for other purposes?

-and finally:
- Does ZC-specific code use OpenSSL for anything?

**Comment by daira** [comment]
Note that this ticket is about the dependency of Zcash Core on OpenSSL. #485 is about eliminating it as a dependency of libzerocash.

**Comment by nathan-at-least** [comment]
I did a quick check on the latest upstream release to verify they still have [``depends/packages/openssl.mk`` at tag ``v0.12.1``](https://github.com/bitcoin/bitcoin/blob/v0.12.1/depends/packages/openssl.mk)).

**Comment by noloader** [comment]
Please forgive my ignorance... What ever came of this?

Does libsodium have everything that's needed? Would Botan or Crypto++ be a better choice since Zcash seems to hav a non-trivial amount of C++ code?

**Comment by str4d** [comment]
This is now about half-completed:

- #1706 removes the OpenSSL PRNG
- #1983 removes the OpenSSL PBKDF
- #1984 removes the use of OpenSSL for symmetric encryption

Remaining usage:

- t-addrs still use `CECKey` (a RAII wrapper around OpenSSL's `EC_KEY`) for verification of public keys (AFAICT?)
  - Can this be safely replaced by libsecp256k1 now?
- The QT code uses OpenSSL for X509
  - This can remain, as we don't build the QT code at the moment, and might be removing it entirely (#1636).
- OpenSSL's `BigNum` is used for testing `CScriptNum`.
  - Can we isolate the OpenSSL dependency to the test suite (and QT)?

**Comment by daira** [comment]
Sheesh, OpenSSL's Montgomery arithmetic had [another](https://www.openssl.org/news/secadv/20170126.txt) bug in almost the same place as the [two](https://www.openssl.org/news/secadv/20150108.txt) [previous](https://www.openssl.org/news/secadv/20161110.txt) ones.

**Comment by daira** [comment]
This is next on my hit list after removing the QT code (#1636) :-)

**Comment by daira** [comment]
Upstream still have [openssl.mk at release 0.15.0](https://github.com/bitcoin/bitcoin/blob/v0.15.0/depends/packages/openssl.mk).

**Comment by str4d** [comment]
> - t-addrs still use `CECKey` (a RAII wrapper around OpenSSL's `EC_KEY`) for verification of public keys (AFAICT?)

This was replaced by libsecp256k1 in #2335.

> - The QT code uses OpenSSL for X509

We removed the QT code in #1636.

**Comment by daira** [comment]
Bitcoin Core removed OpenSSL in https://github.com/bitcoin/bitcoin/pull/17265 (not yet released; will probably be in 0.19.1).
