### ISSUE TITLE
Exception safety of WriteWitnessCache

### ISSUE THREAD

**Issue by daira** [zcash/zcash#1452]
What happens if an exception is thrown after ``TxnBegin()`` in ``WriteWitnessCache``? It should call ``TxnAbort`` and rethrow, I think.

**Comment by str4d** [comment]
There's no exception handling above `WriteWitnessCache` until you get to e.g. reading blocks from disk. So IMHO it should behave the same way as if the transaction couldn't be written: log and ignore (which is what the exception handling in e.g. `LoadExternalBlockFile` does anyway).
