### ISSUE TITLE
Change value of genesis block to 0 ZEC

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#1453]
The mining slow start is calculated such that the total monetary curve is unchanged. In order to do that, block 0 must be worth 0 ZEC, but currently it is unchanged from Bitcoin (ie. 50 ZEC).

We should make the following change in `chainparams.cpp`:

```diff
-    txNew.vout[0].nValue = 50 * COIN;
+    txNew.vout[0].nValue = 0 * COIN;
```

We also need to check that this doesn't break any assumptions, either in the codebase or in tests.

**Comment by str4d** [comment]
I'm putting this in rc1 because while I know it was raised during beta 2, I don't know if any beta 2 PR fixes it. Once beta 2 is out, I will check the status of this issue.

**Comment by daira** [comment]
I'd rather we change this now so that we have time to address any problems, if it conflicts with assumptions in upstream Bitcoin code.

**Comment by str4d** [comment]
Fair enough; in the best case it's a trivial change. But I'll wait 24 hours to see if any current PRs cover this.

**Comment by daira** [comment]
Now that I think about it, if this doesn't go into beta 2 then it won't be properly tested until we set up the private mainnet, because (AFAIK) we are not planning to have another testnet reset between beta 2 and launch. Therefore it should go into beta 2.

**Comment by str4d** [comment]
Heh, this is slightly more work than I originally thought, because it changes the genesis block hash. So I need to regenerate the genesis blocks and miner tests.

**Comment by str4d** [comment]
Reminding myself to revert 2d6e97ecc5b750e83375218cb90eb5b772fa0663 when I make a PR for this issue.

**Comment by nathan-at-least** [comment]
We're going to accept this wart from Bitcoin in our blockchain.

**Comment by daira** [comment]
Actually we did fix this before launch.
