### ISSUE TITLE
Document errata and fixes for NCC findings

### ISSUE THREAD

**Issue by daira** [zcash/zcash#1456]

**Comment by daira** [comment]
> Coinbase and nonconfidential-to-confidential transactions are not adequately defined. When a transaction only has a vpub_old—a public input value and no confidential input notes—two dummy input notes are attached to the Zcash transaction. These dummy input notes have a value equal to zero and random values for the spending key (public and private portions), rho and r. While these values are random, the dummy note is still valid; that is, the nullifier and MAC are still well-formed.

This has now been fixed in the protocol spec.

**Comment by daira** [comment]
The link to Bitcoin issue 6211 actually goes to issue 621. We haven't exhaustively checked other links.

**Comment by daira** [comment]
What does the Status column mean in the Table of Vulnerabilities?

**Comment by rcseacord** [comment]
The link to Bitcoin issue 6211 actually goes to issue 621 has been fixed.  I've been clicking on as many links as I can find.  8^)

**Comment by rcseacord** [comment]
We are using the Status column in this particular report to indicate if an issue has been opened.  Updating this now as well.

**Comment by daira** [comment]
I don't know why that PR was set to close this issue. In any case it should be closed.
