### ISSUE TITLE
Testing failure detected

### ISSUE THREAD

**Issue by paolomarin** [zcash/zcash#1457]
After running test:
$ ./qa/pull-tester/rpc-tests.sh
Failure detected:
!!! FAIL: zcjoinsplitdoublespend.py !!!

**Comment by daira** [comment]
Can you attach the full build log and test output please?

**Comment by str4d** [comment]
This is probably an out-of-memory issue; IIRC this particular RPC test creates two JoinSplits at once, requiring twice the RAM.

**Comment by paolomarin** [comment]
Confirming an out of memory issue. Started a new new build on more capable AWS (m4.xlarge) and testing was successful.

**Comment by paolomarin** [comment]
Confirming an out of memory issue. Started a new new build on more capable AWS (m4.xlarge) and testing was successful.
