### ISSUE TITLE
NCC-2016-015 - Out-of-bounds Read in Boost date Class

### ISSUE THREAD

**Issue by rcseacord** [zcash/zcash#1459]
[Edit by Daira]

A two-byte stack based overflow in a date constructor in the Boost libraries is undefined
behavior and may result in data leaks.

**Comment by daira** [comment]
\@sehetw on Twitter [pointed out](https://twitter.com/sehetw/status/789238220013830148) that
> Last time I checked the epoch for chrono clocks is unspecified (implementation defined). (different for various clocks?)

**Comment by daira** [comment]
Actually I'll open another ticket for that.
