### ISSUE TITLE
getblocktemplate coinbasevalue inconsistent with getblocksubsidy

### ISSUE THREAD

**Issue by ocminer** [zcash/zcash#1461]
Testnet block 345:

getblocktemplate:

    },
    "coinbasevalue" : 17260000,
    "longpollid" : "03430d2499a66f3e5994c8f97ed52ce582c3a9c9778a705ffa6a97c4c6e4915e345",
    "target" : "054fb60000000000000000000000000000000000000000000000000000000000",
    "mintime" : 1475240272,
    "mutable" : [
        "time",
        "transactions",
        "prevblock"
    ],
    "noncerange" : "00000000ffffffff",
    "sigoplimit" : 20000,
    "sizelimit" : 2000000,
    "curtime" : 1475246327,
    "bits" : "20054fb6",
    "height" : 345
}

Getblocksubsidy:

zcash/src/zcash-cli getblocksubsidy 345
{
    "miner" : 0.17250000,
    "founders" : 0.04312500
}

So Coinbasevalue reports 17260000 but getblocksubsidy 17250000 

Why ?

**Comment by daira** [comment]
Transaction fee, I think.

**Comment by daira** [comment]
... but this does look like a miscomputation actually. @str4d?

**Comment by str4d** [comment]
I'm not sure that this is actually a bug. [BIP 22](https://github.com/bitcoin/bips/blob/master/bip-0022.mediawiki#block-template-request) defines `coinbasevalue` as "total funds available for the coinbase (in Satoshis)". Thus I think what is being seen here is correct:

- `getblocktemplate` shows in `coinbasevalue` the total ZEC that can be taken by the miner as coinbase, ie. the sum of the miner reward and all fees.
- `getblocksubsidy` shows only the miner reward.

If someone else can confirm my interpretation of BIP 22, we can close this issue.

**Comment by daira** [comment]
Confirmed. So in this case, there were 10000 zatoshi of fees payable to the miner. We should document this a bit more clearly when we write the getblocktemplate ZIP, but I don't think we need this ticket open for that.
