### ISSUE TITLE
NCC-2016-008 - Potential uninitialized reads

### ISSUE THREAD

**Issue by daira** [zcash/zcash#1464]
Various reads of uninitialized data (listed in the NCC report). Some and possibly all of them are false positives because the data does get initialized in actual usage of the relevant classes; just not in a way that Coverity can determine to be statically guaranteed. We're changing them so that Coverity can tell they are initialized.

**Comment by nathan-at-least** [comment]
Let's narrow the scope of this for only code we've altered from Bitcoin + the portions of libsnark we use, and exclude dependencies, and ensure we do that for rc1.
