### ISSUE TITLE
Node not syncing blockchain, lots of invalid header messages

### ISSUE THREAD

**Issue by whyrusleeping** [zcash/zcash#1470]
I've got three zcash nodes running on different machines on my LAN. One of them is working just fine and mining, another isnt mining (on purpose) but its blockchain appears to be in sync. The third node is not having a great time. Starting it from scratch, it never got any connections and wasnt syncing, so i read elsewhere that copying the testnet3 folder (minus wallet.dat) over from a different working machine would help, so i did that, and it appeared to work for a bit, but as far as i can tell, it was just a fluke, its blockchain hasnt moved forward since it loaded the other nodes directory.

In that nodes debug.log ([full log here](https://ipfs.io/ipfs/QmdK7jLwVkVfGott9WLrVdLwniabStnwg7tbt7n9Kp3UX1/debug.log)) I see a lot of error messages like:

```
2016-10-02 19:06:55 ERROR: AcceptBlockHeader: block is marked invalid
2016-10-02 19:06:55 ERROR: invalid header received
2016-10-02 19:06:55 ProcessMessages(headers, 16369 bytes) FAILED peer=30
```

and

```
2016-10-02 19:00:30 ERROR: AcceptBlockHeader: prev block invalid
2016-10-02 19:00:30 Misbehaving: 198.199.112.230:18233 (0 -> 100) BAN THRESHOLD EXCEEDED
```

Anyone have any idea whats happening here?

**Comment by whyrusleeping** [comment]
When starting that machine over from scratch, i get:
```
2016-10-03 19:47:48 Misbehaving: 198.199.112.230:18233 (0 -> 100) BAN THRESHOLD EXCEEDED
```

where the ip its talking about refers to the betatestnet.z.cash machine.

**Comment by samlavery** [comment]
I just ran into this issue too, you've built the master branch, you need to checkout the branch in the beta guide.  Once you check out the right branch, make clean, and rebuild. :)

**Comment by whyrusleeping** [comment]
@samlavery thanks! that was it
