### ISSUE TITLE
Memory issue?

### ISSUE THREAD

**Issue by Yzord** [zcash/zcash#1484]
I use Zcash miner on the testnet of Komodo and i was wondering if somebody experiences a memory leak which crashes the daemon. After a few hours suddenly my memory spikes (I have gave it 8GB) to the max and kills the daemon. So i guess it is related with the miner.

Anyone familiar with this issue?

**Comment by bitcartel** [comment]
Please file an issue with the Komodo developers.  We don't support the use of Zcashd on other networks so I'm closing this ticket for now. If you experience this issue running Zcashd on the Zcash testnet, please re-open this ticket and provide any debugging output you might have and information about your system environment.  Thanks.
