### ISSUE TITLE
unsupported option '-fopenmp' [OSX]

### ISSUE THREAD

**Issue by lunokhod** [zcash/zcash#1485]
I am trying to build the dependencies on OSX, but I encounter a fatal error when building libsnark: `unsupported option '-fopenmp'`

In the depends directory, the dependencies were compiled using

```
make HOST=x86_64-apple-darwin15.6.0
```

and the fatal error is the following

```
Building libsnark...
c++ -o src/algebra/curves/alt_bn128/alt_bn128_g1.o   src/algebra/curves/alt_bn128/alt_bn128_g1.cpp -c -MMD -fPIC -DBINARY_OUTPUT -DNO_PT_COMPRESSION=1 -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wno-comment -Wfatal-errors -O2 -march=native -mtune=native -DMONTGOMERY_OUTPUT -DCURVE_ALT_BN128 -I/Users/lunokhod/Coin/zcash/depends/x86_64-apple-darwin15.6.0/include -Isrc -DNO_PROCPS -static -DSTATIC -DMULTICORE -fopenmp
clang: fatal error: unsupported option '-fopenmp'
make[1]: *** [src/algebra/curves/alt_bn128/alt_bn128_g1.o] Error 1
make: *** [/Users/lunokhod/Coin/zcash/depends/work/build/x86_64-apple-darwin15.6.0/libsnark/0.1-7648794e724/./.stamp_built] Error 2
```

**Comment by daira** [comment]
We don't support building Zcash with clang. (It's not just libsnark; there's a warning in the libgmp docs saying that clang miscompiles it, or used to.) You would need to use GCC instead (*not* the LLVM-GCC wrapper).

**Comment by lunokhod** [comment]
Thanks. Do you know how to override the default c compiler when building the dependencies?

**Comment by lunokhod** [comment]
```make CC=gcc-6 HOST=x86_64-apple-darwin15.6.0``` partially worked (gcc-6 is the brewed version of gcc). However, this gives rise to another problem:

```
Building libsodium...
Making all in dist-build
make[2]: Nothing to be done for `all'.
Making all in msvc-scripts
make[2]: Nothing to be done for `all'.
Making all in src
Making all in libsodium
Making all in include
make[4]: Nothing to be done for `all'.
  CC       crypto_aead/chacha20poly1305/sodium/libsodium_la-aead_chacha20poly1305.lo
gcc-6: error: unrecognized command line option '-Qunused-arguments'; did you mean '-Wunused-argument'?
gcc-6: error: unrecognized command line option '-Wsometimes-uninitialized'; did you mean '-Wmaybe-uninitialized'?
```

**Comment by daira** [comment]
I would suggest asking about that on the libsodium mailing list (subscription into at https://github.com/jedisct1/libsodium ), and/or looking at OS X-related tickets on its tracker: https://github.com/jedisct1/libsodium/issues?q=is%3Aissue%20"OS%20X". I don't personally have any experience with development on OS X.

**Comment by daira** [comment]
Did you regenerate the headers using autoconf? https://github.com/jedisct1/libsodium/issues/245#issuecomment-77280002

**Comment by omaralvarez** [comment]
Any updates on this? 

I would like to know how to avoid compiling only certain packages. Lets say I don't want to compile boost and just use brew version. I think only compiling certain packages could make it easier, or being able to change stuff in their source after download.

**Comment by daira** [comment]
To change stuff in the source of a package after download, add a patch in the [depends/patches](https://github.com/zcash/zcash/tree/master/depends/patches) directory and update the .mk file; see https://github.com/zcash/zcash/commit/21fb88a34804ba031142af89d2e4df66752b12d3 for an example.

To avoid compiling a package using the depends system, I *think* you can just remove its depends directory and .mk file.

**Comment by omaralvarez** [comment]
Ok, I tried removing .mk file but not depends directory, I will see if I can get further doing that.

**Comment by daira** [comment]
The important thing is actually removing it from https://github.com/zcash/zcash/blob/master/depends/packages/packages.mk .

**Comment by daira** [comment]
This is fixed.
