### ISSUE TITLE
What does cache=0.0MiB mean?

### ISSUE THREAD

**Issue by Yzord** [zcash/zcash#1489]
I have two servers. Both are identical in software (Ubuntu 14.04 minimal with dependencies installed). If you see the picture....the left one is receiving rewards with 2 threads at 2.0GHz. Rights isn't receiving any rewards at all and is mining with 2 threads at 3.2GHz.

No matter what i try (reinstalled it 3 times), the server does not get any reward at all. So i checked the log and found only one thing. In the UpdateTip rule the server which receives rewards has a cache of 1.6MiB. The other one (the doomed one) has a cache of 0.0MiB.

So i was wondering. Is this preventing me for getting rewards? Or is it just a formality? 

![screen shot 2016-10-05 at 21 59 46](https://cloud.githubusercontent.com/assets/5834848/19129314/38d6c75a-8b47-11e6-91d4-92e3cf16f3bd.png)

**Comment by ioptio** [comment]
Hmm.. this ticket seems to have been dropped somehow and was filed pre-launch. I know it's been a while @Yzord but did you find a solution here?

**Comment by michaeljwei** [comment]
@Yzord  I am experiencing the same issue with zcashd 1.0.13 and znomp for mining.
How did you solve this issue? Or have you tried to narrow down the problem?
