### ISSUE TITLE
Ensure ZC-specific uses of secp256k1 are strict (and disallow malleability).

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#149]
It may be that ZC-specific code uses Bitcoin signature/verification for Pour non-malleability, in which case we need to lock down looseness in verification acceptance along the same lines as upstream non-malleability changes.

(This is currently, merely a suspected issue on Nathan's part, and he needs to review the code to determine how it maps to ``H_sig``, ``H_1``, and ``H_2`` in the paper.)

**Comment by daira** [comment]
We do not use ECDSA for JoinSplit nonmalleability. We use Ed25519 (see #977), and have taken into account malleability issues for that algorithm -- in particular, we enforce that S is in range.
