### ISSUE TITLE
relocation R_X86_64_PC32 against undefined symbol `secp256k1_nonce_function_rfc6979' can not be used when making a shared object; recompile with -fPIC

### ISSUE THREAD

**Issue by zazimir** [zcash/zcash#1495]
anyone had isuses with compiling zcash+standalone miner?

libtool: link: /tmp/zminer1/depends/x86_64-unknown-linux-gnu/native/bin/ccache g++ -m64 -std=c++11 -pipe -O1 -fPIC -fwrapv -fno-strict-aliasing -Werror -g -Wformat -Wformat-security -Wstack-protector -fstack-protector-all -fPIE -pthread -Wl,-z -Wl,relro -Wl,-z -Wl,now -pie -o zcash-gtest gtest/zcash_gtest-main.o gtest/zcash_gtest-json_test_vectors.o gtest/zcash_gtest-test_foundersreward.o gtest/zcash_gtest-test_jsonspirit.o gtest/zcash_gtest-test_tautology.o gtest/zcash_gtest-test_checktransaction.o gtest/zcash_gtest-test_equihash.o gtest/zcash_gtest-test_joinsplit.o gtest/zcash_gtest-test_keystore.o gtest/zcash_gtest-test_noteencryption.o gtest/zcash_gtest-test_merkletree.o gtest/zcash_gtest-test_pow.o gtest/zcash_gtest-test_rpc.o gtest/zcash_gtest-test_circuit.o gtest/zcash_gtest-test_txid.o gtest/zcash_gtest-test_wallet_zkeys.o gtest/zcash_gtest-test_libzcash_utils.o gtest/zcash_gtest-test_proofs.o wallet/gtest/zcash_gtest-test_wallet.o -fopenmp  -L/tmp/zminer1/depends/x86_64-unknown-linux-gnu/lib -lgtest -lgmock libbitcoin_server.a libbitcoin_cli.a libbitcoin_common.a libbitcoin_util.a crypto/libbitcoin_crypto.a univalue/libbitcoin_univalue.a ./leveldb/libleveldb.a ./leveldb/libmemenv.a -lboost_filesystem-mt -lboost_program_options-mt -lboost_thread-mt -lboost_chrono-mt -lboost_unit_test_framework-mt secp256k1/.libs/libsecp256k1.a libbitcoin_wallet.a ./.libs/libbitcoinconsensus.a -ldb_cxx-5.3 -lssl -ldl -lminiupnpc libzcash.a -lsnark /tmp/zminer1/depends/x86_64-unknown-linux-gnu/lib/libgmpxx.a /tmp/zminer1/depends/x86_64-unknown-linux-gnu/lib/libgmp.a -lboost_system-mt -lcrypto /tmp/zminer1/depends/x86_64-unknown-linux-gnu/lib/libsodium.a -lanl -fopenmp -pthread
libbitcoin_common.a(libbitcoin_common_a-key.o): In function `CKey::SetPrivKey(std::vector<unsigned char, secure_allocator<unsigned char> > const&, bool)':
/tmp/zminer1/src/key.cpp:33: undefined reference to`secp256k1_ec_privkey_import'
libbitcoin_common.a(libbitcoin_common_a-key.o): In function `CKey::GetPubKey() const':
/tmp/zminer1/src/key.cpp:56: undefined reference to`secp256k1_ec_pubkey_create'
libbitcoin_common.a(libbitcoin_common_a-key.o): In function `ECC_Stop()':
/tmp/zminer1/src/key.cpp:221: undefined reference to`secp256k1_context_destroy'
libbitcoin_common.a(libbitcoin_common_a-key.o): In function `CKey::SignCompact(uint256 const&, std::vector<unsigned char, std::allocator<unsigned char> >&) const':
/tmp/zminer1/src/key.cpp:95: undefined reference to`secp256k1_nonce_function_rfc6979'
/usr/bin/ld: libbitcoin_common.a(libbitcoin_common_a-key.o): relocation R_X86_64_PC32 against undefined symbol `secp256k1_nonce_function_rfc6979' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
Makefile:3114: recipe for target 'zcash-miner' failed
make[2]: **\* [zcash-miner] Error 1
make[2]: **\* Waiting for unfinished jobs....
make[2]: Leaving directory '/tmp/zminer1/src'
Makefile:7436: recipe for target 'all-recursive' failed
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory '/tmp/zminer1/src'
Makefile:643: recipe for target 'all-recursive' failed
make: **\* [all-recursive] Error 1

tried adding the fpic option, edited the build.sh that it compiles everything with fPIC (assuming that it would compile the libbitcoin common with fPIC) but no luck

thanks!

**Comment by nathan-at-least** [comment]
@zazimir, is this still an issue with our latest release?

**Comment by zazimir** [comment]
@nathan-at-least it's no longer an issue,
thanks
