### ISSUE TITLE
ecwrapper.cpp won't build on Mac or Windows ('ECDSA_SIG_get0' was not declared in this scope)

### ISSUE THREAD

**Issue by radix42** [zcash/zcash#1503]
The line numbers are off a few compared to the source in github due to includes that had to be added (openssl/ec.h and openssl/ecdsa.h), but on both Windows with gcc6 and mac with gcc5, I get the following errors when building zcash:

ecwrapper.cpp: In function 'int {anonymous}::ECDSA_SIG_recover_key_GFp(EC_KEY*, ECDSA_SIG*, const unsigned char*, int, int, int)':
ecwrapper.cpp:67:41: error: 'ECDSA_SIG_get0' was not declared in this scope
     ECDSA_SIG_get0(ecsig, &sig_r, &sig_s);

ecwrapper.cpp: In member function 'bool CECKey::Recover(const uint256&, const unsigned char*, int)':
ecwrapper.cpp:187:48: error: 'ECDSA_SIG_set0' was not declared in this scope
     bool ret = ECDSA_SIG_set0(sig, sig_r, sig_s);

**Comment by daira** [comment]
That call was added when upgrading to OpenSSL 1.1.0b. Are you using that version (it probably will not compile against any previous OpenSSL).

**Comment by radix42** [comment]
yes, I'm linking against 1.1.0b

**Comment by daira** [comment]
Hmm. Can you grep for ``ECDSA_SIG_get0`` in OpenSSL to see where it's declared please? (I'd do it but my VM is broken right now.)

**Comment by radix42** [comment]
It's in ec.h....I'm going to double check that ./configure isn't doing the build with the older openssl version on my system

**Comment by radix42** [comment]
There was a problem with my openssl source build that was not apparent, causing it to link against the system libraries. As soon as I get it building against the right version I imagine this will go away and I'll close the issue.

**Comment by radix42** [comment]
Found the issue with my build and install of openssl 1.1.0b that was causing ./configure to not use it, and this issue went away. it would be awfully nice if it told you what version and/or location of each of the dependencies it found that it was using. In lieu of that, a version check on openssl would be very nice.
