### ISSUE TITLE
Failing zcash-gtest test

### ISSUE THREAD

**Issue by lakesidedan** [zcash/zcash#1505]
I have a clean updated ubuntu 16.04 LTS installation running the zcash beta2 miner and following the guide.  When running the full-test.suite.sh, it fails the zcash-gtest.  Attached is the log.  Running on an E6300 on an Intel G45 chipset with 2GB of RAM.  Newbie to ubuntu and mining so any help will be appreciated.

[test-suite.txt](https://github.com/zcash/zcash/files/520041/test-suite.txt)

**Comment by bitcartel** [comment]
2GB is not enough memory to run the test suite.  To avoid these errors and issues, perhaps zcash-gtest should check how much memory is available before executing, and if there isn't enough memory, output an appropriate error message.

**Comment by arcalinea** [comment]
Related to #1498

**Comment by nuttycom** [comment]
Closing as ancient; this can be reopened if anyone has ongoing issues.
