### ISSUE TITLE
Issue with ./src/zcash-cli getinfo GIVES me 0 blocks and "difficulty" : 1.00000000

### ISSUE THREAD

**Issue by przeor** [zcash/zcash#1508]
Hi guys,

What I may do wrong? Screenshot:
<img width="967" alt="screen shot 2016-10-11 at 14 05 25" src="https://cloud.githubusercontent.com/assets/5995/19269630/f20e83d4-8fbb-11e6-9b6d-12d1f496274b.png">

What could be wrong? :-) 

When I was testing  with  ./qa/zcash/full-test-suite.sh I got this output:

<img width="714" alt="555screen shot 2016-10-11 at 13 18 06" src="https://cloud.githubusercontent.com/assets/5995/19269663/2b662f42-8fbc-11e6-8a1c-b40fe48383f1.png">

I've read that it may be a problem with my Locale but I don't know how to fix ? :-( 

My guide was: https://github.com/zcash/zcash/wiki/Beta-Guide

**Comment by daira** [comment]
I can't see the output from the test failure, but it sounds like you're not connected to the testnet. What made you think it was a locale problem?

**Comment by przeor** [comment]
@daira I have two computers running testnet:

1) AWS EC2 Ubuntu 14.04 instance - WORKS FINE:
<img width="1118" alt="screen shot 2016-10-11 at 14 51 35" src="https://cloud.githubusercontent.com/assets/5995/19270826/3ab66c86-8fc2-11e6-9bcf-19763bc7f525.png">


2) Dedicated ubuntu 14.04 machine:
<img width="1017" alt="screen shot 2016-10-11 at 14 52 14" src="https://cloud.githubusercontent.com/assets/5995/19270853/516ec694-8fc2-11e6-8781-5a3bff9088d6.png">


Hmmm, I think it's not locale after checking the one which is working ( had the same  two tests failed but connects and shows the ./src/zcash-cli getinfo correctly.

How to test and debug if I am connected to the testnet correctly? May it be the port issues? Any idea how to fix it?

**Comment by przeor** [comment]
Fixed:
```testnet=1
addnode=betatestnet.z.cash
rpcuser=username
rpcpassword=password```

The zcash.conf file was corrupted (misscopied), above is the correct one.
