### ISSUE TITLE
Connecting via Tor to Zcash hidden server still peers with non-tor nodes

### ISSUE THREAD

**Issue by arcalinea** [zcash/zcash#1510]
After connecting via Tor to Zcash hidden server, there should be only a single peer connection.

**Comment by bitcartel** [comment]
@arcalinea Try using this parameter when launching zcashd. `-dnsseed=0`.  If successful, this ticket can be closed by updating tor.md.

**Comment by arcalinea** [comment]
@bitcartel That doesn't seem to work, but turns out using -connect=hiddenservice.onion instead of -addnode=hiddenservice.onion does the trick. Will change documentation to reflect. Closing issue
