### ISSUE TITLE
Avoid selecting coinbase inputs if possible when sending to transparent output(s)

### ISSUE THREAD

**Issue by daira** [zcash/zcash#1519]
As Tim Olson [pointed out on Slack](https://zcashcommunity.slack.com/archives/zcash/p1476286628010250):
> If the wallet selected any UTXO's from a coinbase and you are trying to send to a transparent address, then you will get an error.

I believe that currently, the wallet doesn't try to avoid sending from a coinbase when any of the outputs are transparent. (Different code paths are used by the legacy send* methods and by z_sendmany, but neither do this as far as I can see.) Therefore, this failure can occur even when sufficient non-coinbase funds are available.

**Comment by bitcartel** [comment]
@daira This is addressed in #1431 (which I updated recently and is ready for review) where if the chainparams enforces the consensus rule that coinbase utxos must goto zaddrs, the legacy send* methods will not be allowed to select the coinbase utxos.  See here: https://github.com/zcash/zcash/pull/1431/files#diff-b2bb174788c7409b671c46ccc86034bdR2246

**Comment by daira** [comment]
Fixed by #1431.
