### ISSUE TITLE
Sketch out protocol changes necessary for parameter upgrades / new parameter sets.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#152]
Parameter upgrades may be necessary for (at least) three distinct reasons:
- A new circuit will be deployed, thus requiring new parameters.
- A new parameter set will be deployed for the existing circuit because a different set of SMC participants (or a union of old and new participants) appeals to a larger user base.
- A new parameter generation protocol is invented with better security properties.

Let's sketch out a minimal roadmap for the upgrade, and see if there are any future proofing protocol changes needed.

**Close Criteria:** We only need to convince ourselves that an upgrade is _relatively feasible_ to close this ticket. We don't need to hammer out every detail. Keep in mind, though, that upgrade pains are often in little details.

**Comment by daira** [comment]
"We only need to convince ourselves that an upgrade is *relatively feasible* to close this ticket."

Done :-)
