### ISSUE TITLE
Building fails

### ISSUE THREAD

**Issue by xaoseric** [zcash/zcash#1527]
Building from source is failing on Ubuntu, latest version. See attached screenshot. 

![zcash_compileerror](https://cloud.githubusercontent.com/assets/643544/19363449/83e975aa-9158-11e6-935d-575ec67ff329.png)

**Comment by nathan-at-least** [comment]
Is this a problem in our most recent release? @xaoseric

**Comment by xaoseric** [comment]
@nathan-at-least I can check this later today

**Comment by daira** [comment]
Please reopen if this is still a problem. I suspect it is a compiler or binutils version issue. We are now [requiring gcc/g++ 4.9 or later](https://github.com/zcash/zcash/wiki/1.0-User-Guide#compile-it-yourself)).
