### ISSUE TITLE
Merge bitcore-3 changes

### ISSUE THREAD

**Issue by daira** [zcash/zcash#1534]
https://github.com/str4d/zcash/tree/v1.0.0-beta2-bitcore-3

So that the block explorer can use plain zcashd.

**Comment by prusnak** [comment]
I believe the latest work is now in https://github.com/str4d/zcash/tree/v1.0.4-bitcore-3

Is there any objective reason why not to merge this work into mainline?

The current situation is very frustrating for people that want to run Insight node.

**Comment by str4d** [comment]
@prusnak several reasons, which basically add up to "it requires work that I haven't had time to do":

- There are commits in the branch that need to be filtered out or handled separately (e.g. the ZMQ stuff has been independently merged).
- The branch is out-of-date with upstream Bitcore, which changed its branching mechanism just after I cherry-picked `bitcore-3`.

**Comment by prusnak** [comment]
JFYI because of unresponsive bitcore upstream (bitpay) we forked bitcore + dependencies to our @satoshilabs organization where we continue development. Most of the heavy lifting is done by @runn1ng.

**Comment by runn1ng** [comment]
FYI: this is bitcore patchset rebased on the newest stable bitcore

https://github.com/satoshilabs/bitcoin

(We also have our own bitcore with some patches for segwit, but zcash should *not* use that directly - since the segwit detection is broken on zcash, since zcash tx can have 0 inputs)

**Comment by daira** [comment]
Moving 1.0.10 tickets back into 1.0.9 since the latter has been rescheduled.

**Comment by nathan-at-least** [comment]
This sounds like significant work. I've placed it in a triage queue (which is a new process for us) and removed it from 1.0.9 for the time being.

**Comment by nathan-at-least** [comment]
Ah, it looks like these changes are necessary for Trezor support, which I had not realized: https://github.com/str4d/zcash/issues/19

It's too late for 1.0.9, but I intend to prioritize it after.

**Comment by nathan-at-least** [comment]
Let's migrate all the tickets from the issue tracker in https://github.com/str4d/zcash here then close that issue tracker.

**Comment by nathan-at-least** [comment]
We also want to adopt https://github.com/str4d/bitcore-lib-zcash and maybe https://github.com/str4d/insight-api-zcash as ZcashCo forks, rather than relying on poor @str4d to maintain these on his own.

**Comment by runn1ng** [comment]
From my experiences with this + dash bitcore + litecoin bitcore, it's obvious to me now that the whole setup with C++ patches and tons of JS modules that need slight edits for each coin is a PITA :/

Long-term plan is to build something else, that will be coin-agnostic (just general btc-like RPC/ZMQ) and won't need constant maintenance, but we are not there yet.

**Comment by slush0** [comment]
Adopting address index patches to upstream would be the best solution at this time. We're relying on binary of 1.0.4 which we made few months ago. So far Zcash support on TREZOR works, but if it break, we cannot maintain it also because broken dependencies in build process. I understand you won't fit it in current development window, but I appreciate any move forward soon. If something will go wrong with our current instance, we'll need to terminate support in our wallet.

**Comment by daira** [comment]
@nathan-at-least wrote:
> Let's migrate all the tickets from the issue tracker in https://github.com/str4d/zcash here then close that issue tracker.

Doing that now.

**Comment by daira** [comment]
Ticket migration done. The migrated ticket #2382 was a duplicate of this one; its description was:

> <a href="https://github.com/slush0"><img src="https://avatars1.githubusercontent.com/u/565341?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [slush0](https://github.com/slush0)**
_Thursday May 11, 2017 at 15:23 UTC_
> _Originally opened as https://github.com/str4d/zcash/issues/19_
>
> ----
>
> Hello,
>
> bitcore fork stil uses zcash  v1.0.4. Not only it is outdated, buggy and unsupported, but it even cannot build, because you remove dependencies from z.cash site (namely https://z.cash/depends-sources/zeromq-4.0.4.tar.gz).
>
> Please update zcash for bitcore to latest binary, otherwise we'll have to stop supporting zcash in TREZOR :(.

**Comment by slush0** [comment]
Sorry for disturbing, but is there any chance to put back build dependencies to z.cash site as a hotfix of this issue? I urgently need to recompile zcashd 1.0.4, because I have binary which works only for Ubuntu 16+ and I need binary for Debian 8 for production machine.

**Comment by str4d** [comment]
@slush0 we never had that as a dependency on the Zcash website - we only added v4.2.1 when ZeroMQ support landed in 1.0.6. The depends system in the Bitcore branch should have been using the fallback to the original source, which is http://download.zeromq.org/zeromq-4.0.4.tar.gz - has that URL become unreachable for you?

**Comment by str4d** [comment]
Note that if for some reason the dependency downloader is failing, you can manually download the dependency archive `zeromq-4.0.4.tar.gz` and place it in `depends/sources`. The depends system *should* see that the hash matches and use it. You may also need to create the file `depends/sources/download-stamps/.stamp_fetched-zeromq-zeromq-4.0.4.tar.gz.hash` containing:
```
1ef71d46e94f33e27dd5a1661ed626cd39be4d2d6967792a275040e34457d399  zeromq-4.0.4.tar.gz
```
(I have not verified that the stamp is unnecessary for manual downloads).

**Comment by sennevb** [comment]
+1 we need 1.08 version..

**Comment by slush0** [comment]
From what place can I download all dependencies for building zcashd 1.0.4? Somebody mentioned that dependencies were removed from z.cash site because they were unaware that somebody is still using them.

I know there's no dependency for website. Sorry, I meant the build process depends on libraries downloading from z.cash website.

**Comment by slush0** [comment]
>  has that URL become unreachable for you?

@str4d no, it does not fail for me, but the script kept crashing saying that it cannot download it from z.cash website. I'll try again, putting zmq image locally, but all this is total mess. I have no time to study all the build system and dependencies. Putting all dependencies back to your site seems like the easiest hotfix for now.

**Comment by slush0** [comment]
Ok, it seems that the build process works now, the script successfully downloaded zeromq from backup location. Sorry for being a bit nervous, I do this sometimes when running production servers with obsolete binaries which I'm unable to recompile :-).

**Comment by radix42** [comment]
@slush0 If I were you I'd run the `build-debian-package.sh` script and stash the resulting `.deb` file aside somewhere. Alternatively I also have that package tucked away for the bitcore-3 version of 1.0.4 and can post it for download.

**Comment by str4d** [comment]
I have re-ported the 0.12.1-bitcore branch to 1.0.8-1:

https://github.com/str4d/zcash/tree/v1.0.8-1-bitcore

@slush0 could you test and confirm it works for you? Note you will need to `-reindex` because I changed the `txdb` prefixes for the additional indices (to fix namespace collisions).

**Comment by radix42** [comment]
I will do a build later today, upgrade my Insight node(s) and let you know how it goes

**Comment by nathan-at-least** [comment]
Hi folks, we hope to get the Zcash changes necessary here into 1.0.10 release if possible.

Meanwhile, for bitcore support, I'm not familiar enough with the codebase to know what next steps are necessary. If SatoshiLabs is the de facto maintainer, should @str4d submit the zcash tweaks as a branch to SatoshiLabs repositories?

It sounds like that code isn't yet in a state that can merge both Bitcoin and Zcash support into a single master branch, so maybe for the time being there will be a zcash support branch?

**Comment by radix42** [comment]
No, its a fork, and not in a way that you'd be able to support both coins
in the same tree.

**Comment by runn1ng** [comment]
It's not impossible, but it will be hard :)

Parsing transaction is hard for both zcash and (especially segwit) bitcoin... not impossible, but hard. :)

Also, in one of the bitcoin repos, there is a script that downloads and installs a binary locally *during npm install*. What could be done is to add both the binaries there or something like that, but again, it's gonna be hard.

That's just from top of my head, maybe there is more lurking in there.

Also you still need to do the c++ code patching.

**Comment by nathan-at-least** [comment]
I'd like to include the changes on the Zcash side into our 1.0.11 release. However, I'm not sure how feasible this is, so I'd like to hear @str4d's assessment.

**Comment by str4d** [comment]
Thanks to @LarryRuane's efforts, the changes necessary for the Insight explorer have now been merged into `zcashd`.
