### ISSUE TITLE
Disable wallet encryption.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#1552]
Our wallet encryption feature isn't working well enough to launch with, atm. We're going to disable it so users aren't confused into using an unstable feature.

This temporarily mitigates #1528.

**Comment by bitcartel** [comment]
To make it easy for developers to continue work on improving wallet encryption:

- For users, add warning in help message of `encryptwallet` that its disabled, and call does nothing
- Unless the runtime parameter `-developerencryptwallet` is present (but do not put this in help file)

**Comment by mowens785** [comment]
[scripts/build.sh]() @str4d 

>  #3545
