### ISSUE TITLE
Generate new genesis blocks

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#1554]
We need to make the following changes in `src/chainparams.cpp`:

- [ ] Set `pszTimestamp` to a more recent headline than 2009/01/03 .
- [ ] Change `486604799` in ` txNew.vin[0].scriptSig` to whatever we set `genesis.nBits` to.
- [x] Set `txNew.vout[0].nValue` to `0`.
- [x] ~~Set `txNew.vout[0].scriptPubKey` to either a valid pubkey encoding, or something that is invalid but acceptable (and won't cause issues).~~ Leave the `scriptPubKey` as-is.
- [x] Set `genesis.nVersion` to 4 (the only currently-defined block version for Zcash).
- [ ] Set `genesis.nTime` to the current time.
- [ ] Set `genesis.nBits` to our desired minimum difficulty.
- [x] Remove `fMinerTestModeForFoundersRewardScript`.

And the following change in `src/chainparams.h` and `src/test/miner_tests.cpp`:

- [x] Remove `fMinerTestModeForFoundersRewardScript`.

Then perform the following actions:
- Mine the mainnet genesis block.
- Mine the testnet genesis block.
- Mine the regtest genesis block.
- Regenerate miner tests.
- Regenerate any other tests that break.

**Comment by alfiedotwtf** [comment]
"The Guardian 17/Oct/2016 The privacy of citizens is being eroded"

Missed this aptly timed headline by a day: https://www.theguardian.com/commentisfree/2016/oct/16/the-guardian-view-on-data-sharing-the-privacy-of-citizens-is-being-eroded

**Comment by daira** [comment]
If we were generating the genesis block now, I'd be inclined to use:
"The Guardian 18/Oct/2016 UK security agencies unlawfully collected data for 17 years, court rules."
I'm sure we'll find something similarly appropriate.

**Comment by str4d** [comment]
Idea: instead of a newspaper headline, we could set `pszTimestamp` to recent Bitcoin and Ethereum block hashes, as a symbol of how we think Zcash can [find a balance between Bitcoin's stability and Ethereum's agility](https://z.cash/blog/consensual-currency.html).

Or we could have all three! It's not like we have to worry about the size of the genesis block :stuck_out_tongue_winking_eye:

**Comment by kdping** [comment]
hello, I want to create genesis on my own, then what value should I fill nSolution with ?
thx in advance.
