### ISSUE TITLE
reject block versions < 4

### ISSUE THREAD

**Issue by daira** [zcash/zcash#1556]
The spec currently says that versions < 4 are rejected. We must either do that, or change the spec.

Note that code inherited from Bitcoin might do unintended things for lower block versions; by enforcing this rule, we would be reducing the number of code paths and improving auditability.

**Comment by daira** [comment]
The history of block versions in Bitcoin is documented at https://bitcoin.org/en/developer-reference#block-versions .

**Comment by str4d** [comment]
Resolving this may require rebuilding the genesis block.

**Comment by str4d** [comment]
This definitely requires rebuilding the genesis block. I'm going to hold off making a PR for this issue until #1578 (or later equivalent) is merged.

**Comment by daira** [comment]
@str4d #1578 is merging now.

**Comment by str4d** [comment]
Merged, working on a PR for this now.
