### ISSUE TITLE
Dependency Configuration Issue | libsnark missing

### ISSUE THREAD

**Issue by bradycoye** [zcash/zcash#1572]
I'm running Tails 2.6 x86_64 off a live usb with persistence and am having trouble compiling zcash

```
checking for gmp.h... yes
checking for _gmpnsub_n in -lgmp... yes
checking gmpxx.h usability... yes
checking gmpxx.h presence... yes
checking for gmpxx.h... yes
checking for main in -lgmpxx... yes
Hunting for libsnark include directory...
Found libsnark include directory: /home/amnesia/Persistent/zcash/zcash/depends/x86_64-unknown-linux-gnu/include/libsnark
checking libsnark/gadgetlib1/gadget.hpp usability... yes
checking libsnark/gadgetlib1/gadget.hpp presence... yes
checking for libsnark/gadgetlib1/gadget.hpp... yes
checking for main in -lsnark... no
configure: error: libsnark missing
```

I've installed the packages listed in the beta guide and attempted to compile from a new checkout. 
[Full Attempted Build Output](https://gist.github.com/bradycoye/401cfd5c1af1c3b41b311f7559ec36bd)

**Comment by daira** [comment]
I haven't compared this with a correct build, but the path here looks wrong:
```
Staging libsnark...
mkdir -p /home/amnesia/Persistent/zcash/zcash/depends/work/staging/x86_64-unknown-linux-gnu/libsnark/0.1-bd7eaedfe8d//home/amnesia/Persistent/zcash/zcash/depends/x86_64-unknown-linux-gnu
```

**Comment by nathan-at-least** [comment]
@bradycoye, are you building with `./zcutil/build.sh` ?

**Comment by daira** [comment]
This is a very old ticket, and is probably going to be obviated by moving libsnark in tree.

**Comment by ebfull** [comment]
We've moved libsnark in tree, I'm closing this. Please reopen if it's still a problem.
