### ISSUE TITLE
More precise/well-defined error reporting from z_sendmany

### ISSUE THREAD

**Issue by daira** [zcash/zcash#1573]
Conversation with Dave Merril:

> We'd also like to know whether it's possible to split the process of creating and sending the transaction in two steps: first, create the transaction and get a hash, and then send it forward to the miners. As we understand, currently there's only the "Z_sendmany" call...

@daira:

> That is definitely technically possible, although it isn't supported by any of the current RPC calls.
> I think it would be relatively straightforward to split the code implementing `z_sendmany` so that the raw transaction could be accessed before sending.
> 
> Note that making modifications to a private transaction before sending it could potentially distinguish it from other private transactions, reducing privacy. I don't think that's a strong argument against the feature, though; just something to warn about in the docs.
> 
> Also note that if you get a _signed_ transaction back from a hypothetical `z_preparesendmany` call, then you wouldn't be able to modify it without invalidating it. What's the use case, so that we know whether you would need to modify it or not?

Dave Merril:

> [...] As for the use case: for example, after the z_sendmany something goes wrong, and we need to know whether the transaction was created or not, added to the pool or received by network.
> If we receive an error after calling `z_preparesendmany`, we consider this transaction as failed, and the coins are safe and sound.
> If we receive an error after calling `z_preparesendmany`, we need a ID/error code which helps to understand what exactly happened and how the transaction was (or was not) processed.

@daira:

> Would adding a `failed_with_no_effect` status for async operations suffice? That could probably be done more quickly than adding a new call.
> 
> Ah, there's already an error code:
> 
> ```
> error: error object if the status is 'failed'. The error object has the following key-value pairs:
> code : number
> message: error message
> ```
> 
> but the error codes are not defined in the API doc.
> 
> So, we could ensure that errors in a given range imply that the transaction has definitely not been submitted to the network. (JSON-RPC reserves a few error codes and leaves the rest up to the application protocol: http://www.jsonrpc.org/specification#error_object .)

**Comment by nathan-at-least** [comment]
Let's address this, as a first pass, by simply documenting the existing error results in our API documentation.

**Comment by arcalinea** [comment]
Started with documenting z_sendmany error codes and messages in #1842

**Comment by ebfull** [comment]
If this has a PR, what is it?

I am considering booting this out of 1.0.3.

**Comment by ebfull** [comment]
Was this solved by #1842?

**Comment by bitcartel** [comment]
Yes, partially solved.  Moving this to 1.0.4 now.

**Comment by nathan-at-least** [comment]
Let's say #1842 is sufficient for this ticket. If anyone wants further improvement let's specify that and implement it in a follow up ticket.
