### ISSUE TITLE
The Beta Guide should recommend reading security-warnings.md

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#1579]
The beta guide, or whichever page on the website has instructions for installing Zcash now, should include a link to `security-warnings.md` and explain what it is. It's unlikely that people following the guide will bother to look at the README.md (which does link to it) or browse around inside `doc/`.

**Comment by defuse** [comment]
Here's a way to word it:

> Before you install Zcash, it's important to read the [list of security warnings](https://github.com/zcash/zcash/blob/master/doc/security-warnings.md). Without checking that document, you may end up using Zcash in an insecure way, so please go read through it now.

**Comment by nathan-at-least** [comment]
Just added this section: https://github.com/zcash/zcash/wiki/Beta-Guide#security-resources
