### ISSUE TITLE
Insufficient funds, no UTXOs found for taddr from address

### ISSUE THREAD

**Issue by Ales999** [zcash/zcash#1592]
Hello!

After simple hours mining with gen=1

$ ./src/zcash-cli listunspent          
[
    {
        "txid" : "1fa3c4e101f21ca1ea79a39c99bdf0c44cae6d1d4d309a715007fc7ee0c2348a",
        "vout" : 0,
        "address" : "tmJpBanAyNKhQiAJk457Ck1QFfKFMPzL8pr",
        "scriptPubKey" : "2103b200b79006f12e61ff5b1534502f567d315ccd390ed0d894a32405130597c5bcac",
        "amount" : **4.57100000**,
        "confirmations" : 441,
        "spendable" : true
    }
]

$ /src/zcash-cli z_sendmany "$TADDR" "[{\"address\": \"$ZADDR\", \"memo\": \"48656c6c6f20ceb221\", \"amount\": **0.23**}]"
opid-0d52dd0f-3fbe-4623-b1ac-8caa67b2d7e4

$ ./src/zcash-cli z_getoperationstatus 
[
    {
        "id" : "opid-0d52dd0f-3fbe-4623-b1ac-8caa67b2d7e4",
        "status" : "failed",
        "creation_time" : 1477042598,
        "error" : {
            "code" : -6,
            "message" : "Insufficient funds, no UTXOs found for taddr from address."
        }
    }
]

Why "Insufficient funds, no UTXOs found for taddr from address." ?

PS Sorry for my bad english please.

**Comment by ampyx** [comment]
The amount you are trying to send might not have enough confirmations yet. You could see this information when executing: 

```bash
zcash-cli getwalletinfo
```

Under immature balance you would probabaly see that 4.571 TAZ

**Comment by Ales999** [comment]
./src/zcash-cli getwalletinfo
{
    "walletversion" : 60000,
    "balance" : **4.57100000**,
    "unconfirmed_balance" : 0.00000000,
    "immature_balance" : 0.00000000,
    "txcount" : 1,
    "keypoololdest" : 1476964230,
    "keypoolsize" : 30003
}

**Comment by Ales999** [comment]
And again:
./src/zcash-cli z_sendmany "$TADDR" "[{\"address\": \"$ZADDR\", \"memo\": \"48656c6c6f20ceb221\", \"amount\": 1.23}]"
opid-07edc76c-fd7b-45e3-9dad-2511a1814922

./src/zcash-cli z_getoperationstatus 
[
    {
        "id" : "opid-07edc76c-fd7b-45e3-9dad-2511a1814922",
        "status" : "failed",
        "creation_time" : 1477045181,
        "error" : {
            "code" : -6,
            "message" : "Insufficient funds, no UTXOs found for taddr from address."
        }

**Comment by reactivate-gh** [comment]
Ales999 did you set TADDR to 'tmJpBanAyNKhQiAJk457Ck1QFfKFMPzL8pr' before? 

pls try:

$ ./src/zcash-cli z_sendmany "tmJpBanAyNKhQiAJk457Ck1QFfKFMPzL8pr" "[{\"address\": \"$ZADDR\", \"memo\": \"48656c6c6f20ceb221\", \"amount\": 1.23}]"

**Comment by Ales999** [comment]
Hm... strange, my $TADDR is bad
$ echo $TADDR
tmTAbPgqw1rTv417HCzZPUsnDemrdLKXGEm

??? ):-O How different? A'm only **ONE** start _cli getnewaddress and save data to TADDR ...

and, if using itsa0xa - success pocess (executed):

$ ./src/zcash-cli z_getoperationstatus              
[
    {
        "id" : "opid-1997cee6-afeb-4f81-b26b-d3695b3de696",
        "status" : "executing",
        "creation_time" : 1477048863
    }
]

Thanks all responded

**Comment by itsa0xa** [comment]
Ales999:
the TAZ that show up in 'listunspent' have its own TADDR. So every entry is an other TADDR.

you could use this script https://gist.github.com/itsa0xa/718e4927668f59def9cea646913d4d65

change the zAddress to your ZADDR and change '/home/deploy/zcash...' to the path where your zcash is... if you execute the script it will move all unspent+confirmed coins to your ZADDR.

**Comment by Ales999** [comment]
A-a-a ... thans **itsa0xs** !
I'm just beginning to understand this.

Simple confused current:
$ zcash-cli listunspent
[
]
Why **all** moved to ZADDR ? and Why wallet balance is null ?
$ zcash-cli z_getbalance "$ZADDR"
4.57090000
$ ./src/zcash-cli getwalletinfo 
...
    "balance" : 0.00000000,
    "unconfirmed_balance" : 0.00000000,
    "immature_balance" : 0.00000000,
...

It's normal ?

**Comment by itsa0xa** [comment]
yes i think it is as you balance is hidden now at your ZADDR.
did u use my script to move the cash? that would explain why its all moved.

**Comment by Ales999** [comment]
If try get script: This page is taking way too long to load.  :-(
Please check link.

**Comment by itsa0xa** [comment]
Link is fine, looks like a temp. github issue

**Comment by Ales999** [comment]
Script loaded by IE :-) Thanks. 

Сonspicuously 'zcash core' **auto-transfer** remain generated TAZ:

~$ zcash-cli z_listreceivedbyaddress "$ZADDR"
"amount" : 1.23000000,
        "memo" : "48656c6c6f20ceb22100...
}
{
"amount" : 3.34090000,
        "memo" : "f600000000000000...

**Comment by Ales999** [comment]
Thanks all responded
