### ISSUE TITLE
Merge libevent-based http server from Bitcoin for better stability in RPC

### ISSUE THREAD

**Issue by ampyx** [zcash/zcash#1593]
I encounter random lockups of the zcash RPC thread when I query the RPC interface on simple commands like getinfo,getblocktemplate,getblocksubsidy and more. Typically when this happens, the whole RPC daemon is stuck and non-responsive to new requests.

The same issues existed in bitcoins RPC implementation based on boost-asio:
https://github.com/bitcoin/bitcoin/issues/6454
https://github.com/bitcoin/bitcoin/issues/2889

Related:
https://github.com/bitcoin/bitcoin/pull/5655

They fixed these issues by replacing the RPC server from boost-asio to libevent:
https://github.com/bitcoin/bitcoin/pull/5677

For better stability, I think it would be wise to consider the same pull for zcash. A typical workaround proposed is to set rpckeepalive=0, however miners using getblocktemplate wont be able to use longpolling.

**Comment by daira** [comment]
Thanks. I looked at the diff, and no way can we do this before launch (it touches 38 files, and depends on the UniValue refactoring).

Desired for 1.0.1, especially since it will help in getting rid of OpenSSL (delenda est).

**Comment by ocminer** [comment]
I can confirm this with the default setting of rpcthreads=4. You have to edit your config file and set rpcthreads to something reasonable like 16 or even 32 for it to work reliably. This problem occurs with every coind in conjunction with pools.

**Comment by daira** [comment]
Yeah that's unfortunate, but the diff is huge, and too disruptive for 1.0. We could put that rpcthreads workaround in the ``zcash.conf`` used in the Beta Guide (and Launch Guide when it's published).

**Comment by nathan-at-least** [comment]
@daira is on vacation, so we can't ask her about her prioritization decision. Right now in our meeting we thought this was too invasive of a change for 1.0.3, so we bumped it into 1.0.[Soon].

**Comment by daira** [comment]
I put it in 1.0.3 because it's a major problem for any services trying to use zcashd at scale for all their users. Basically it *will* lock up too regularly to enable a reliable service without some very ugly workarounds to recover from deadlocks (and we know each kill-restart cycle carries a risk of database corruption with BDB).

**Comment by daira** [comment]
Re: invasiveness, my rejection of this for 1.0 was simply because it was way too risky to do before launch -- but now that we're not under as tight schedule constraints I think it's perfectly feasible.

**Comment by bitcartel** [comment]
I'm going to take a look and try to replicate the issue.

**Comment by daira** [comment]
The rpckeepalive option and acceptance of HTTP keep-alive connections were disabled by PR #1847 to resolve ticket #1680, which was a temporary workaround instead of the merge suggested in this ticket.

**Comment by str4d** [comment]
Another reason for merging this: once done, we can pull in bitcoin/bitcoin#6639 essentially as-is to get Tor ephemeral HS support.
