### ISSUE TITLE
faucet.zeropond.com does not seem to deliver test coins -> update doc

### ISSUE THREAD

**Issue by chaica** [zcash/zcash#1595]
Trying to follow the Beta guide (https://github.com/zcash/zcash/wiki/Beta-Guide), section Getting coins (https://github.com/zcash/zcash/wiki/Beta-Guide#getting-testcoins) mentions using faucet.zeropond.com but some from the forums.z.cash told me it was delivering old test coins, maybe not compatible with the rc1.

so I guess this part of the documentation should be updated.

**Comment by str4d** [comment]
The beta guide has been removed.
