### ISSUE TITLE
!!! FAIL: wallet_protectcoinbase.py !!!

### ISSUE THREAD

**Issue by canadaonline** [zcash/zcash#1597]
=== Running testscript wallet_protectcoinbase.py ===
  File "/home/zcashminer/zcash/qa/rpc-tests/test_framework/test_framework.py", line 118, in main
    self.run_test()
  File "/home/zcashminer/zcash/qa/rpc-tests/wallet_protectcoinbase.py", line 81, in run_test
    assert_equal(Decimal(resp["private"]), Decimal('29.9999'))
  File "/home/zcashminer/zcash/qa/rpc-tests/test_framework/util.py", line 342, in assert_equal
    raise AssertionError("%s != %s"%(str(thing1),str(thing2)))
  Initializing test directory /tmp/testRHuMc1
  Mining blocks...
  waiting for async operation opid-a6dea533-4f60-4c88-b4eb-19b94bc99305
  ...returned status: success
  Assertion failed: 0.00 != 29.9999
  Stopping nodes
  Cleaning up
  Failed
!!! FAIL: wallet_protectcoinbase.py !!!

**Comment by str4d** [comment]
@canadaonline Coud you please give us the following information:

- `git show HEAD -s`
- `gcc --version`
- `python --version`
- `uname -a`

**Comment by canadaonline** [comment]
commit 1218603f7357c0649545fbf0ea59e47508d4298f
Author: Simon <simon@bitcartel.com>
Date:   Mon Oct 17 11:47:51 2016 -0700

    Update Debian changelog.

gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

Python 2.7.6

Linux zcashminer001 3.13.0-45-generic #74-Ubuntu SMP Tue Jan 13 19:36:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by str4d** [comment]
Interesting. This is the same test failure we are currently fighting on the CI server. The fact you see it on RC1 indicates it isn't related to anything we recently merged...

**Comment by str4d** [comment]
The failing RPC test was added in 2b1cda3b6a2102eb007fc3f9d86046588fa9b823 as part of #1431, which was merged in RC 1. So it's possible that the test itself has always been broken, or that the PR has a bug.
