### ISSUE TITLE
Release 1.0.0-rc2

### ISSUE THREAD

**Issue by daira** [zcash/zcash#1605]
* [x] Write blog post.
* [x] Write release notes.
* [x] Merge all PRs.
* [x] Follow https://github.com/zcash/zcash/blob/master/doc/release-process.md
* [x] Update https://github.com/zcash/zcash/wiki/Beta-Guide

**Comment by shiftaET** [comment]
what does this mean? im still trying to get it running! :(

**Comment by daira** [comment]
@shiftET: I suggest you join the #zcash [Slack channel](https://inviteme.z.cash) and ask for help there.

**Comment by daira** [comment]
https://z.cash/blog/new-release-candidate-less-than-one-week.html

**Comment by jewseppi** [comment]
I ran the new daemon and on first run the metrics work great.  After stopping the daemon and restarting there are no longer any metrics on the screen. 


:(

**Comment by str4d** [comment]
@jewseppi check that you don't have `printtoconsole` or `daemon` in either your `zcashd` start command or your `zcash.conf` file.

**Comment by novemberdelta241** [comment]
Same here, I just recompiled and started again and there are no metrics, all cores are mining 100% but the terminal window looks the same..

Conf File
testnet=1
addnode=betatestnet.z.cash
rpcuser=username
rpcpassword=password
gen=1
genproclimit=-1
equihashsolver=tromp

jarid@Zcash:~/zcash$ ./src/zcashd -daemon
Zcash server starting
jarid@Zcash:~/zcash$ ./src/zcash-cli getinfo
{
    "version" : 1000026,
    "protocolversion" : 170002,
    "walletversion" : 60000,
    "balance" : 0.00000000,
    "blocks" : 1905,
    "timeoffset" : 0,
    "connections" : 1,
    "proxy" : "",
    "difficulty" : 13712.69863726,
    "testnet" : true,
    "keypoololdest" : 1477425760,
    "keypoolsize" : 101,
    "paytxfee" : 0.00000000,
    "relayfee" : 0.00005000,
    "errors" : "This is a pre-release test build - use at your own risk - do not use for mining or merchant applications"
}
jarid@Zcash:~/zcash$

**Comment by itsa0xa** [comment]
start with ./src/zcashd -showmetrics and do not use the '-daemon' switch

**Comment by novemberdelta241** [comment]
wow, you definitely said that in your previous post. my bad, thank you for the follow up!

**Comment by novemberdelta241** [comment]
Since starting this node 1 minutes, 50 seconds ago:
- You have validated 92 transactions!
- You have contributed 28.0364 Sol/s on average to the network solution rate.
- You have completed 1599 Equihash solver runs.

[Press Ctrl+C to exit] [Set 'showmetrics=0' to hide]

YAAAAAAY!!!!!!

**Comment by jewseppi** [comment]
What are your system specs?

I've got 12GB RAM and 6 CORES...still nothing mined. 👎 

**Output**
You are running 6 mining threads.

Since starting this node 48 minutes, 54 seconds ago:
- You have validated 1103 transactions!
- You have contributed 6.7239 Sol/s on average to the network solution rate.
- You have completed 10482 Equihash solver runs.

**Comment by novemberdelta241** [comment]
64 gigs of ram - dual Xeon 2630v4 (40 cores hyperthreaded)

**Comment by novemberdelta241** [comment]
With the difficulty as high as it is now it could take days to generate a block, if not longer

**Comment by str4d** [comment]
@novemberdelta241 @jewseppi please move discussion into our [forum](https://forum.z.cash/) :smiley:
