### ISSUE TITLE
RPC tests: FAIL: wallet_nullifiers.py

### ISSUE THREAD

**Issue by daira** [zcash/zcash#1608]
christophersanborn on Slack:

> I received a "FAIL: wallet_nullifiers.py" failure when running the extended tests.   All other tests passed.  Ubuntu 16 recent install.  zCash v1.0.0-rc1 release.  Error message included text: "Assertion failed: success != executing".

@str4d:

> sounds like a timeout failure
> The test waits IIRC 2 minutes for a JoinSplit to finish
> If the machine you are testing on is too slow, it won't be done in time and the test will fail

**Comment by bitcartel** [comment]
Yes,  timeout is 120 seconds.  We could increase this.

**Comment by Zenitur** [comment]
I've found another test RPC Wallet test fail: http://pastebin.com/LWXFL8YH
Debian Linux 7.0 "Wheezy", x86_64 arch, GCC 4.7.2.

**Comment by daira** [comment]
@Zenitur: that's a build error, unrelated to the failure above. Please open another ticket.

**Comment by arcalinea** [comment]
This was closed by #2123 -- not fixed by increasing the timeout, but rather by fixing race condition where `z_getoperationresult` would return a stale status object with "executing" state
