### ISSUE TITLE
Mainnet mining does not work

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#1609]
When connectiong local nodes in a private network, no mining occurs.  Problem observed from z7 to master (pending rc2 release).  Have not tested z6 or earlier.

**Comment by bitcartel** [comment]
@nathan-at-least has more info.

**Comment by nathan-at-least** [comment]
I removed 'needs prioritization'. The prioritization is that this blocks our release. ;-)

For my test setup I had three localhost nodes in a V topology with the central node being the only one with ``gen=1``. Here are the three nodes' config files:

```
==> node00/zcash.conf <==
onlynet=ipv4
connect=127.0.0.1:24331
connect=127.0.0.1:24333
bind=127.0.0.1
port=24329
rpcbind=127.0.0.1
rpcport=24330
rpcuser=node00
rpcpassword=2CUsjSH6g9WpT4FsaM1b1FZ+LoMtrlukoUQ73UG9fV8
gen=1
debug=pow

==> node01/zcash.conf <==
onlynet=ipv4
dnsseed=0
bind=127.0.0.1
port=24331
rpcbind=127.0.0.1
rpcport=24332
rpcuser=node01
rpcpassword=k6tESzItsL+8PgDe1xfm0kIFJPle6mLPxzwXEhz8z20
gen=0
debug=pow

==> node02/zcash.conf <==
onlynet=ipv4
dnsseed=0
bind=127.0.0.1
port=24333
rpcbind=127.0.0.1
rpcport=24334
rpcuser=node02
rpcpassword=RwKpY/5oMFsDJ14lc+Npc3JUcGrg0zh5dmVmCF5W0S0
gen=0
debug=pow
```

With ``v1.0.0-rc1`` the `node00/debug.log` ends with:

```
2016-10-24 15:22:58 ZcashMiner started
2016-10-24 15:22:58 addcon thread start
2016-10-24 15:22:58 receive version message: /MagicBean:1.0.0rc1/: version 170002, blocks=0, us=0.0.0.0:0, peer=1
2016-10-24 15:22:58 Added time data, samples 2, offset +0 (+0 minutes)
2016-10-24 15:22:58 receive version message: /MagicBean:1.0.0rc1/: version 170002, blocks=0, us=0.0.0.0:0, peer=2
```

-and there are no mining updates. I determined with @str4d's help and through adding debug prints that an initialization loop never exits. I'll post more details about that soon.

**Comment by nathan-at-least** [comment]
Note, I made a tool to automate configuration and running localhost nodes. You can use it like this:

(This example keeps `mainnetfarm` install inside /tmp/venv-mnf without clobbering anything else on your system, except `mainnetfarm` itself will create `~/.mainnetfarm`.)

```
$ virtualenv /tmp/venv-mnf
$ source /tmp/venv-mnf/bin/activate # Note: This will tweak your current shell's environment.
$ pip install git+https://github.com/nathan-at-least/mainnetfarm.git
$ mainnetfarm init
$ mainnetfarm run --zcashd ~/zcash-repos/v1.0.0-rc1/src/zcashd # Use your own appropriate path.
```

**Comment by nathan-at-least** [comment]
The initialization loop that hangs is in [``src/miner.cpp`` L470-L479 on tag ``v1.0.0-rc1``](https://github.com/zcash/zcash/blob/v1.0.0-rc1/src/miner.cpp#L470-L479), and by adding debug prints I've determined that ``IsInitialBlockDownload`` always returns ``true``.

**Comment by daira** [comment]
I tracked this down; the problem is that the timestamp on the genesis block for mainnet is more than 24 hours (``nMaxTipAge`` seconds) out of date. Therefore, the condition ``pindexBestHeader->GetBlockTime() < GetTime() - chainParams.MaxTipAge()`` in ``IsInitialBlockDownload()`` is always true, so the best available block (the genesis block) is always considered too old.

The timestamp on the genesis block for testnet is also more than 24 hours out of date, but for testnet, ``nMaxTipAge`` is set to 2<sup>31</sup>-1 seconds so this check is effectively disabled.

**Comment by nathan-at-least** [comment]
Because this issue only affects 'stale' genesis blocks, it won't affect out launch. Closing as wontfix.
