### ISSUE TITLE
Zcash Beta Guide (for rc2)

### ISSUE THREAD

**Issue by BobDoe** [zcash/zcash#1633]
Everything was working great till I got to Here

Running

Create the ~/.zcash directory using mkdir -p ~/.zcash.
^^^^^ which directory should I be in when I do this??

Then place a configuration file at ~/.zcash/zcash.conf with the following contents (you don't need to modify anything):
testnet=1
addnode=betatestnet.z.cash
rpcuser=username
rpcpassword=password

new to lynux  How is this done exactly? ^^^^^

**Comment by BobDoe** [comment]
Bob@TVPC:~$ mkdir -p ~/.zcash
Bob@TVPC:~$ cd zcash/
Bob@TVPC:~/zcash$ mkdir -p ~/.zcash
Bob@TVPC:~/zcash$ ~/.zcash/zcash.conf
bash: /home/Bob/.zcash/zcash.conf: No such file or directory
Bob@TVPC:~/zcash$ ~/.zcash/nano zcash.conf
bash: /home/Bob/.zcash/nano: No such file or directory
Bob@TVPC:~/zcash$ cd .zcash/
bash: cd: .zcash/: No such file or directory
Bob@TVPC:~/zcash$ cd .
Bob@TVPC:~/zcash$ cd .
Bob@TVPC:~/zcash$ cd /
Bob@TVPC:/$ cd .zcash/
bash: cd: .zcash/: No such file or directory
Bob@TVPC:/$ sudo mkdir -p ~/.zcash
Bob@TVPC:/$ cd .zcash/
bash: cd: .zcash/: No such file or directory
Bob@TVPC:/$



WHAT AM I DOING WRONG?

**Comment by daira** [comment]
``sudo apt-get install nano`` (if not already installed)
``mkdir -p ~/.zcash``
``nano ~/.zcash/zcash.conf``

**Comment by BobDoe** [comment]
Thank You ! Looking at http://linuxcommand.org/  Now.  So much to Learn

**Comment by BobDoe** [comment]
Zcash Daemon version v1.0.0-rc2

Usage:
  zcashd [options]                     Start Zcash Daemon

Options:

  -?
       This help message

  -alerts
       Receive and display P2P network alerts (default: 1)

  -alertnotify=<cmd>
       Execute command when a relevant alert is received or we see a really
       long fork (%s in cmd is replaced by message)

  -blocknotify=<cmd>
       Execute command when the best block changes (%s in cmd is replaced by
       block hash)

  -checkblocks=<n>
       How many blocks to check at startup (default: 288, 0 = all)

  -checklevel=<n>
       How thorough the block verification of -checkblocks is (0-4, default: 3)

  -conf=<file>
       Specify configuration file (default: zcash.conf)

  -daemon
       Run in the background as a daemon and accept commands

  -datadir=<dir>
       Specify data directory

  -dbcache=<n>
       Set database cache size in megabytes (4 to 16384, default: 100)

  -loadblock=<file>
       Imports blocks from external blk000??.dat file on startup

  -maxorphantx=<n>
       Keep at most <n> unconnectable transactions in memory (default: 100)

  -par=<n>
       Set the number of script verification threads (-2 to 16, 0 = auto, <0 =
       leave that many cores free, default: 0)

  -pid=<file>
       Specify pid file (default: zcashd.pid)

  -prune=<n>
       Reduce storage requirements by pruning (deleting) old blocks. This mode
       disables wallet support and is incompatible with -txindex. Warning:
       Reverting this setting requires re-downloading the entire blockchain.
       (default: 0 = disable pruning blocks, >550 = target size in MiB to use
       for block files)

  -reindex
       Rebuild block chain index from current blk000??.dat files on startup

  -sysperms
       Create new files with system default permissions, instead of umask 077
       (only effective with disabled wallet functionality)

  -txindex
       Maintain a full transaction index, used by the getrawtransaction rpc
       call (default: 0)

Connection options:

  -addnode=<ip>
       Add a node to connect to and attempt to keep the connection open

  -banscore=<n>
       Threshold for disconnecting misbehaving peers (default: 100)

  -bantime=<n>
       Number of seconds to keep misbehaving peers from reconnecting (default:
       86400)

  -bind=<addr>
       Bind to given address and always listen on it. Use [host]:port notation
       for IPv6

  -connect=<ip>
       Connect only to the specified node(s)

  -discover
       Discover own IP addresses (default: 1 when listening and no -externalip
       or -proxy)

  -dns
       Allow DNS lookups for -addnode, -seednode and -connect (default: 1)

  -dnsseed
       Query for peer addresses via DNS lookup, if low on addresses (default: 1
       unless -connect)

  -externalip=<ip>
       Specify your own public address

  -forcednsseed
       Always query for peer addresses via DNS lookup (default: 0)

  -listen
       Accept connections from outside (default: 1 if no -proxy or -connect)

  -maxconnections=<n>
       Maintain at most <n> connections to peers (default: 125)

  -maxreceivebuffer=<n>
       Maximum per-connection receive buffer, <n>*1000 bytes (default: 5000)

  -maxsendbuffer=<n>
       Maximum per-connection send buffer, <n>*1000 bytes (default: 1000)

  -onion=<ip:port>
       Use separate SOCKS5 proxy to reach peers via Tor hidden services
       (default: -proxy)

  -onlynet=<net>
       Only connect to nodes in network <net> (ipv4, ipv6 or onion)

  -permitbaremultisig
       Relay non-P2SH multisig (default: 1)

  -port=<port>
       Listen for connections on <port> (default: 8233 or testnet: 18233)

  -proxy=<ip:port>
       Connect through SOCKS5 proxy

  -proxyrandomize
       Randomize credentials for every proxy connection. This enables Tor
       stream isolation (default: 1)

  -seednode=<ip>
       Connect to a node to retrieve peer addresses, and disconnect

  -timeout=<n>
       Specify connection timeout in milliseconds (minimum: 1, default: 5000)

  -upnp
       Use UPnP to map the listening port (default: 0)

  -whitebind=<addr>
       Bind to given address and whitelist peers connecting to it. Use
       [host]:port notation for IPv6

  -whitelist=<netmask>
       Whitelist peers connecting from the given netmask or IP address. Can be
       specified multiple times. Whitelisted peers cannot be DoS banned and
       their transactions are always relayed, even if they are already in the
       mempool, useful e.g. for a gateway

Wallet options:

  -disablewallet
       Do not load the wallet and disable wallet RPC calls

  -keypool=<n>
       Set key pool size to <n> (default: 100)

  -paytxfee=<amt>
       Fee (in BTC/kB) to add to transactions you send (default: 0.00)

  -rescan
       Rescan the block chain for missing wallet transactions on startup

  -salvagewallet
       Attempt to recover private keys from a corrupt wallet.dat on startup

  -sendfreetransactions
       Send transactions as zero-fee transactions if possible (default: 0)

  -spendzeroconfchange
       Spend unconfirmed change when sending transactions (default: 1)

  -txconfirmtarget=<n>
       If paytxfee is not set, include enough fee so transactions begin
       confirmation on average within n blocks (default: 2)

  -maxtxfee=<amt>
       Maximum total fees to use in a single wallet transaction; setting this
       too low may abort large transactions (default: 0.10)

  -upgradewallet
       Upgrade wallet to latest format on startup

  -wallet=<file>
       Specify wallet file (within data directory) (default: wallet.dat)

  -walletbroadcast
       Make the wallet broadcast transactions (default: 1)

  -walletnotify=<cmd>
       Execute command when a wallet transaction changes (%s in cmd is replaced
       by TxID)

  -zapwallettxes=<mode>
       Delete all wallet transactions and only recover those parts of the
       blockchain through -rescan on startup (1 = keep tx meta data e.g.
       account owner and payment request information, 2 = drop tx meta data)

Debugging/Testing options:

  -debug=<category>
       Output debugging information (default: 0, supplying <category> is
       optional). If <category> is not supplied, output all debugging
       information.<category> can be: addrman, alert, bench, coindb, db, lock,
       rand, rpc, selectcoins, mempool, net, proxy, prune.

  -gen
       Generate coins (default: 0)

  -genproclimit=<n>
       Set the number of threads for coin generation if enabled (-1 = all
       cores, default: 1)

  -equihashsolver=<name>
       Specify the Equihash solver to be used if enabled (default: "default")

  -help-debug
       Show all debugging options (usage: --help -help-debug)

  -logips
       Include IP addresses in debug output (default: 0)

  -logtimestamps
       Prepend debug output with timestamp (default: 1)

  -minrelaytxfee=<amt>
       Fees (in BTC/Kb) smaller than this are considered zero fee for relaying
       (default: 0.00005)

  -printtoconsole
       Send trace/debug info to console instead of debug.log file

  -shrinkdebugfile
       Shrink debug.log file on client startup (default: 1 when no -debug)

  -testnet
       Use the test network

Node relay options:

  -datacarrier
       Relay and mine data carrier transactions (default: 1)

  -datacarriersize
       Maximum size of data in data carrier transactions we relay and mine
       (default: 80)

Block creation options:

  -blockminsize=<n>
       Set minimum block size in bytes (default: 0)

  -blockmaxsize=<n>
       Set maximum block size in bytes (default: 750000)

  -blockprioritysize=<n>
       Set maximum size of high-priority/low-fee transactions in bytes
       (default: 50000)

RPC server options:

  -server
       Accept command line and JSON-RPC commands

  -rest
       Accept public REST requests (default: 0)

  -rpcbind=<addr>
       Bind to given address to listen for JSON-RPC connections. Use
       [host]:port notation for IPv6. This option can be specified multiple
       times (default: bind to all interfaces)

  -rpcuser=<user>
       Username for JSON-RPC connections

  -rpcpassword=<pw>
       Password for JSON-RPC connections

  -rpcport=<port>
       Listen for JSON-RPC connections on <port> (default: 8232 or testnet:
       18232)

  -rpcallowip=<ip>
       Allow JSON-RPC connections from specified source. Valid for <ip> are a
       single IP (e.g. 1.2.3.4), a network/netmask (e.g. 1.2.3.4/255.255.255.0)
       or a network/CIDR (e.g. 1.2.3.4/24). This option can be specified
       multiple times

  -rpcthreads=<n>
       Set the number of threads to service RPC calls (default: 4)

  -rpckeepalive
       RPC support for HTTP persistent connections (default: 1)

RPC SSL options: (see the Bitcoin Wiki for SSL setup instructions)

  -rpcssl
       Use OpenSSL (https) for JSON-RPC connections

  -rpcsslcertificatechainfile=<file.cert>
       Server certificate file (default: server.cert)

  -rpcsslprivatekeyfile=<file.pem>
       Server private key (default: server.pem)

  -rpcsslciphers=<ciphers>
       Acceptable ciphers (default:
       TLSv1.2+HIGH:TLSv1+HIGH:!SSLv2:!aNULL:!eNULL:!3DES:@STRENGTH)

**Comment by BobDoe** [comment]
Bitcoin version v1.0.0-rc2 (2016-10-23 03:03:00 +0100)
Using OpenSSL version OpenSSL 1.1.0b  26 Sep 2016
Using BerkeleyDB version Berkeley DB 5.3.28: (September  9, 2013)
Default data directory /home/Bob/.zcash
Using data directory /home/Bob/.zcash/testnet3
Using config file /home/Bob/.zcash/zcash.conf
Using at most 125 connections (2048 file descriptors available)
Using 2 threads for script verification
Loading verifying key from /home/Bob/.zcash-params/beta2-verifying.key
Loaded verifying key in 0.000000s seconds.
Binding RPC on address ::1 port 18232 (IPv4+IPv6 bind any: 0)
ERROR: Binding RPC on address ::1 port 18232 failed: bind: Address already in use
Binding RPC on address 127.0.0.1 port 18232 (IPv4+IPv6 bind any: 0)
ERROR: Binding RPC on address 127.0.0.1 port 18232 failed: bind: Address already in use
Error: An error occurred while setting up the RPC address 127.0.0.1 port 18232 for listening: bind: Address already in use
Error: An error occurred while setting up the RPC address 127.0.0.1 port 18232 for listening: bind: Address already in use
scheduler thread start
Using wallet wallet.dat
init message: Verifying wallet...
CDBEnv::Open: LogDir=/home/Bob/.zcash/testnet3/database ErrorFile=/home/Bob/.zcash/testnet3/db.log
Unable to bind to [::]:18233 on this computer. Bitcoin Core is probably already running.
Unable to bind to 0.0.0.0:18233 on this computer. Bitcoin Core is probably already running.
Error: Unable to bind to 0.0.0.0:18233 on this computer. Bitcoin Core is probably already running.
Error: Unable to bind to 0.0.0.0:18233 on this computer. Bitcoin Core is probably already running.
Error: Failed to listen on any port. Use -listen=0 if you want this.
Error: Failed to listen on any port. Use -listen=0 if you want this.
Shutdown: In progress...
StopRPCThreads: waiting for async rpc workers to stop
StopNode()
Shutdown: done
zcashd: scheduler.cpp:19: CScheduler::~CScheduler(): Assertion `nThreadsServicingQueue == 0' failed.
Aborted (core dumped)
Bob@TVPC:~/zcash$

ports 18232 and 18233 always show as in use, even after fresh reboot???

**Comment by BobDoe** [comment]
Bob@TVPC:~/zcash$ ./src/zcashd -daemon
Zcash server starting
Bob@TVPC:~/zcash$ ./src/zcashd -printtoconsole

Bitcoin version v1.0.0-rc2 (2016-10-23 03:03:00 +0100)
Using OpenSSL version OpenSSL 1.1.0b  26 Sep 2016
Using BerkeleyDB version Berkeley DB 5.3.28: (September  9, 2013)
Default data directory /home/Bob/.zcash
Using data directory /home/Bob/.zcash/testnet3
Using config file /home/Bob/.zcash/zcash.conf
Using at most 125 connections (2048 file descriptors available)
Using 2 threads for script verification
Loading verifying key from /home/Bob/.zcash-params/beta2-verifying.key
Loaded verifying key in 0.000501s seconds.
Binding RPC on address ::1 port 18232 (IPv4+IPv6 bind any: 0)
ERROR: Binding RPC on address ::1 port 18232 failed: bind: Address already in use
Binding RPC on address 127.0.0.1 port 18232 (IPv4+IPv6 bind any: 0)
ERROR: Binding RPC on address 127.0.0.1 port 18232 failed: bind: Address already in use
Error: An error occurred while setting up the RPC address 127.0.0.1 port 18232 for listening: bind: Address already in use
Error: An error occurred while setting up the RPC address 127.0.0.1 port 18232 for listening: bind: Address already in use
scheduler thread start
Using wallet wallet.dat
init message: Verifying wallet...
CDBEnv::Open: LogDir=/home/Bob/.zcash/testnet3/database ErrorFile=/home/Bob/.zcash/testnet3/db.log
Unable to bind to [::]:18233 on this computer. Bitcoin Core is probably already running.
Unable to bind to 0.0.0.0:18233 on this computer. Bitcoin Core is probably already running.
Error: Unable to bind to 0.0.0.0:18233 on this computer. Bitcoin Core is probably already running.
Error: Unable to bind to 0.0.0.0:18233 on this computer. Bitcoin Core is probably already running.
Error: Failed to listen on any port. Use -listen=0 if you want this.
Error: Failed to listen on any port. Use -listen=0 if you want this.
Shutdown: In progress...
StopRPCThreads: waiting for async rpc workers to stop
StopNode()
Shutdown: done
scheduler thread interrupt
Bob@TVPC:~/zcash$


zcashd  shows that it is still running in task manager  45 to 50 % cpu

**Comment by daira** [comment]
You're trying to run ``zcashd`` more than once at the same time. Run a single instance of ``zcashd``, and then use ``zcash-cli`` to communicate with it.

**Comment by BobDoe** [comment]
Ok Thanks for ALL your HELP :)
