### ISSUE TITLE
Block nVersion not limited to 4

### ISSUE THREAD

**Issue by 4zec** [zcash/zcash#1638]
Seems like nothing is enforcing the block's version number. I mined block 11899: `00081c4f818756f012fba664b4740cb9e45ec067e010be0184349c0d277633af` on the older testnet3 (rc1?) with version of 5.

I don't have the hash power to do the same on the current testnet, sorry.

**Comment by str4d** [comment]
From RC2 we enforce that the block version must be at least 4, to ensure that no block accidentally indicates lack of support for Bitcoin-inherited features we expect to be there. However, we didn't add an upper block limit. I'm not sure what best practice is for this amongst blockchains.

@daira we should look at this.

**Comment by daira** [comment]
There's no upper block limit in Bitcoin. I considered this issue carefully; if we want to create blocks in future that current nodes will reject, there are several possible ways to do that (for example changing the Equihash solution length field). So the current behaviour allows us all the flexibility we might need in future, whereas enforcing a block version of exactly 4 would close off some options. I will clarify this in the spec.

**Comment by daira** [comment]
I forgot to clarify this in the spec; see #2439.
