### ISSUE TITLE
Release 1.0.0-rc3 and rc4

### ISSUE THREAD

**Issue by daira** [zcash/zcash#1641]
* [x] Write blog post
* [x] Merge all PRs for rc3
* [x] Follow https://github.com/zcash/zcash/blob/master/doc/release-process.md for rc3
* [x] Merge all PRs for rc4
* [x] Follow https://github.com/zcash/zcash/blob/master/doc/release-process.md for rc4
* [x] Update https://github.com/zcash/zcash/wiki/Beta-Guide
* [x] Publish blog post.

Note that rc3 is *not* a testnet reset release, but rc4 is.

**Comment by str4d** [comment]
Done!
