### ISSUE TITLE
gitian builds of libsnark are different depending on processor

### ISSUE THREAD

**Issue by radix42** [zcash/zcash#1645]
gitian builds still have differences in the build of libsnark depending on the processor/chipset used to compile. In #1549 this difference was resolved for the build of libgmp, but some difference still remains when libsnark is built, for example, on i7 vs Xeon processor systems with gitian.

**Comment by str4d** [comment]
We unfortunately won't have time to fix this before the 1.0.0 launch, but it should be prioritised for 1.0.1.

**Comment by radix42** [comment]
I'll keep doing gitian builds for rc3/4 and 1.0 when it drops, of course. If I have time I'll also work on adapting one of the AWS vm providers I've seen for other altcoins so that vagrant can do builds on AWS, which uses Xeon processors.
