### ISSUE TITLE
Balance is 0 after 8 hours of mining.

### ISSUE THREAD

**Issue by orenyodfat** [zcash/zcash#1650]
./src/zcash-cli getinfo
{
    "version" : 1000026,
    "protocolversion" : 170002,
    "walletversion" : 60000,
    "balance" : 0.00000000,
    "blocks" : 2162,
    "timeoffset" : 0,
    "connections" : 2,
    "proxy" : "",
    "difficulty" : 13623.63882829,
    "testnet" : true,
    "keypoololdest" : 1477430577,
    "keypoolsize" : 108,
    "paytxfee" : 0.00000000,
    "relayfee" : 0.00005000,
    "errors" : "This is a pre-release test build - use at your own risk - do not use for mining or merchant applications"
}

**Comment by orenyodfat** [comment]
What am I doing wrong ?:
Here is my cons file:
testnet=1
addnode=betatestnet.z.cash
rpcuser=username
rpcpassword=password
gen=1
genproclimit=-1

**Comment by daira** [comment]
The difficulty on testnet is high enough that you shouldn't necessarily expect to find a note in 8 hours of mining. Use the ``listtransactions`` call to see whether you have mined anything, and the ``getmininginfo`` call to check the mining configuration. In any case, github is not the right place to ask; I suggest asking on the #zcash-mining channel on the [Community Slack](https://inviteme.z.cash).

**Comment by mearvk** [comment]
I too have this issue.  Site is up but no wallet movement.  Using Litecoin not Zeta.  Miner runs 12 hours doing work and no transactions can be found.
