### ISSUE TITLE
Build error on my Gentoo machine

### ISSUE THREAD

**Issue by kristapsk** [zcash/zcash#1654]
```
Building boost...
mkdir -p /XXX/zcash/depends/work/build/x86_64-unknown-linux-gnu/boost/1_62_0-8100bd437b7/.
cd /XXX/zcash/depends/work/build/x86_64-unknown-linux-gnu/boost/1_62_0-8100bd437b7/.; PATH=/XXX/zcash/depends/x86_64-unknown-linux-gnu/native/bin:/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/x86_64-pc-linux-gnu/gcc-bin/4.9.3:/usr/x86_64-pc-linux-gnu/arm-none-eabi/gcc-bin/4.8.3:/usr/x86_64-pc-linux-gnu/armv7a-hardfloat-linux-gnueabi/gcc-bin/5.3.0:/opt/android-sdk-update-manager/tools:/opt/android-sdk-update-manager/platform-tools:/usr/games/bin   ./b2 -d2 -j2 -d1 --prefix=/XXX/zcash/depends/work/staging/x86_64-unknown-linux-gnu/boost/1_62_0-8100bd437b7/XXX/zcash/depends/x86_64-unknown-linux-gnu --layout=tagged --build-type=complete --user-config=user-config.jam threading=multi link=static -sNO_BZIP2=1 -sNO_ZLIB=1 variant=release   threadapi=pthread runtime-link=shared    stage
/XXX/zcash/depends/work/build/x86_64-unknown-linux-gnu/boost/1_62_0-8100bd437b7/tools/build/src/build/feature.jam:494: in feature.validate-value-string from module feature
error: "none" is not a known value of feature <optimization>
error: legal values: "off" "speed" "space"
/XXX/zcash/depends/work/build/x86_64-unknown-linux-gnu/boost/1_62_0-8100bd437b7/tools/build/src/build/property.jam:276: in validate1 from module property
/XXX/zcash/depends/work/build/x86_64-unknown-linux-gnu/boost/1_62_0-8100bd437b7/tools/build/src/build/property.jam:302: in property.validate from module property
/XXX/zcash/depends/work/build/x86_64-unknown-linux-gnu/boost/1_62_0-8100bd437b7/tools/build/src/tools/builtin.jam:381: in variant from module builtin
/usr/share/boost-build/site-config.jam:9: in modules.load from module site-config
/XXX/zcash/depends/work/build/x86_64-unknown-linux-gnu/boost/1_62_0-8100bd437b7/tools/build/src/build-system.jam:249: in load-config from module build-system
/XXX/zcash/depends/work/build/x86_64-unknown-linux-gnu/boost/1_62_0-8100bd437b7/tools/build/src/build-system.jam:351: in load-configuration-files from module build-system
/XXX/zcash/depends/work/build/x86_64-unknown-linux-gnu/boost/1_62_0-8100bd437b7/tools/build/src/build-system.jam:524: in load from module build-system
/XXX/zcash/depends/work/build/x86_64-unknown-linux-gnu/boost/1_62_0-8100bd437b7/tools/build/src/kernel/modules.jam:295: in import from module modules
/XXX/zcash/depends/work/build/x86_64-unknown-linux-gnu/boost/1_62_0-8100bd437b7/tools/build/src/kernel/bootstrap.jam:139: in boost-build from module
/XXX/zcash/depends/work/build/x86_64-unknown-linux-gnu/boost/1_62_0-8100bd437b7/boost-build.jam:17: in module scope from module

funcs.mk:238: recipe for target '/XXX/zcash/depends/work/build/x86_64-unknown-linux-gnu/boost/1_62_0-8100bd437b7/./.stamp_built' failed
make: *** [/XXX/zcash/depends/work/build/x86_64-unknown-linux-gnu/boost/1_62_0-8100bd437b7/./.stamp_built] Error 1
```

Happens with both v1.0.0-rc1 and v1.0.0-rc2.

Any ideas?

**Comment by YoukaiCat** [comment]
To build boost on Gentoo, you should use b2 option "--ignore-site-config" (depends/packages/boost.mk) or define gentoorelease/gentoodebug targets in /etc/site-config.jam.

You can also use ZCash ebuild from my [overlay](https://github.com/YoukaiCat/NamelessOverlay/tree/master/net-p2p/zcash).

**Comment by kristapsk** [comment]
Thanks, building with your ebuilds works!

**Comment by daira** [comment]
Reopening so that we can document this or make ebuilds work out-of-the-box.

**Comment by dakk** [comment]
On my funtoo env, I fixed by inflating "--ignore-site-config" in b2 arguments in /depends/packages/boost.mk:
`dakk ~ diff boostold.mk boost.mk
6c6
< $(package)_patches=deprecated_auto_ptr.patch include_poll.patch
---
> $(package)_patches=deprecated_auto_ptr.patch
30,31c30
<    patch -p1 < $($(package)_patch_dir)/deprecated_auto_ptr.patch && \
<    patch -p1 < $($(package)_patch_dir)/include_poll.patch
---
>    patch -p1 < $($(package)_patch_dir)/deprecated_auto_ptr.patch
39c38
<   ./b2 -d2 -j2 -d1 --prefix=$($(package)_staging_prefix_dir) $($(package)_config_opts) stage
---
>   ./b2 -d2 -j2 -d1 --ignore-site-config --prefix=$($(package)_staging_prefix_dir) $($(package)_config_opts) stage 
43c42
<   ./b2 -d0 -j4 --prefix=$($(package)_staging_prefix_dir) $($(package)_config_opts) install
---
>   ./b2 -d0 -j4 --ignore-site-config --prefix=$($(package)_staging_prefix_dir) $($(package)_config_opts) install`

**Comment by tekhedd** [comment]
FYI: same error here (Funtoo), dakk's workaround does fix the build. (thx)

**Comment by nathan-at-least** [comment]
Bumped out of 1.0.9 because we are focusing on performance and stability, rather than portability for 1.0.9.

The next step on this front would be to set up a gentoo build worker and ensure our build works, out-of-the-box on it.

**Comment by darkicekeel** [comment]
please, can't wait for something to emerge and work! <3

**Comment by bitcartel** [comment]
@kristapsk @darkicekeel @tekhedd @dakk @YoukaiCat Does this ebuild fix proposed here https://github.com/zcash/zcash/issues/2442#issuecomment-312499629 work for you?

**Comment by tekhedd** [comment]
Do you mean specifically csmk's overlay? (https://github.com/csmk/frabjous/tree/master/net-p2p/zcash)

I have not tried it yet, but it patches in the "--ignore-site-config" fix, which does work for me. Trying the ebuild now.

**Comment by tekhedd** [comment]
And.. waiting for the zcash build ALL THE LIBRARY.. :) .. and... OK out to get lunch.. 

Build successful. Fetching params and configuring etc. Seems to work fine.

**Comment by dakk** [comment]
yep, I confirm it works also  for me

**Comment by csmk** [comment]
@tekhedd and @dakk, thank you for testing the ebuild.

I just made a new revbump, it's now possible to build with `network-sandbox` in
FEATURES. So no more dependency on `net-misc/wget`.

If it's not too much to ask, could you guys test the [-r1](https://github.com/csmk/frabjous/blob/538c7353f5f146b4153b7595aa37fddd65c7002f/net-p2p/zcash/zcash-1.0.10_p1-r1.ebuild) too? Thanks.

To be clear, this is the [diff](https://gist.github.com/csmk/3b00ff7b3ae04f913f30da599bf30621) in the new revision.

**Comment by tekhedd** [comment]
"-r1" builds and launches fine here. And built much faster.  :)

**Comment by ioptio** [comment]
Closing this because it seems to be resolved. If issue is still a problem, feel free to reopen this ticket.
