### ISSUE TITLE
Determine if we should reapply the boost atomic patches.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#166]
As part of #154 work, I'm upgrading the version of boost installed (rationale c++11 support, #56), but [the patches](https://github.com/Electric-Coin-Company/zerocashd/tree/99e95aea77d470667e9aff932881527acf409c9c/depends/patches/boost) no longer apply.

I couldn't find how the upstream boost code evolved in order to update the patches, and ended up removing them on the hope that any bug/security issue they applied were integrated into upstream boost.

**This is risky**, especially since it seems related to atomicity of bignum operations.

Meanwhile [I asked upstream for the rationale behind the patches](https://github.com/bitcoin/bitcoin/commit/1dec09b341f61836147d87656aea7f7be02aab6d#commitcomment-11224082).

This ticket is opened to follow up on the rationale of the patches and to ensure to repair any regression caused by removing them.

**Comment by daira** [comment]
This ticket is obsolete. (We have since upgraded to Boost 1.62.0.)
