### ISSUE TITLE
[low] Upload public key to GitHub

### ISSUE THREAD

**Issue by jonathancross** [zcash/zcash#1667]
I noticed @daira signed the latest release with key `067F492098CF2762`. However this public key has not been added to her GitHub profile, thus preventing this system from verifying commit signatures. Would be nice if all devs / release engineers added your keys to your GitHub profile(s).  Of course I get that this is not essential and should not be trusted alone, but it gives users one more way to quickly verify integrity of releases.

Ideally the dev team should also sign each other's keys.

**Comment by daira** [comment]
Away from my computer with my key on it -- I'll get to this tonight.

**Comment by daira** [comment]
I'm unable to fix this because github incorrectly thinks the key is expired, even after uploading a new export of it with an expiration date of 2018-03-16.

**Comment by jonathancross** [comment]
Hmmm...
Did you follow the GUI [instructions here](https://help.github.com/articles/adding-a-new-gpg-key-to-your-github-account/)?
If it is rejecting a good key, then you should contact support: https://github.com/contact

**Comment by daira** [comment]
I no longer sign releases. Reassigning to @ageis to make sure that the current release signing key is on github.

**Comment by nuttycom** [comment]
All recent releases show as signed.
