### ISSUE TITLE
read error

### ISSUE THREAD

**Issue by BobDoe** [zcash/zcash#1669]
2016-10-27 15:19:59 (7.21 KB/s) - Read error at byte 493832889/910173851 (Success). Retrying.

--2016-10-27 15:20:02--  (try: 4)  https://s3.amazonaws.com/zcashfinalmpc/sprout-proving.key
Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.121.18|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 910173851 (868M), 416340962 (397M) remaining [application/octet-stream]
Saving to: ‘/home/Bob/.zcash-params/sprout-proving.key.dl’
 I keep getting download errors???????????

**Comment by BobDoe** [comment]
Bob@TVPC:~/zcash$ ./zcutil/fetch-params.sh
Zcash - fetch-params.sh

Retrieving: https://z.cash/downloads/sprout-proving.key
--2016-10-27 15:15:23--  https://z.cash/downloads/sprout-proving.key
Resolving z.cash (z.cash)... 104.236.171.172
Connecting to z.cash (z.cash)|104.236.171.172|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://s3.amazonaws.com/zcashfinalmpc/sprout-proving.key [following]
--2016-10-27 15:15:29--  https://s3.amazonaws.com/zcashfinalmpc/sprout-proving.key
Resolving s3.amazonaws.com (s3.amazonaws.com)... 54.231.121.18
Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.121.18|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 910173851 (868M), 420639289 (401M) remaining [application/octet-stream]
Saving to: ‘/home/Bob/.zcash-params/sprout-proving.key.dl’

        [ skipping 458752K ]
458752K ,,,,,,,, ,,,,,,,, ,,.               53% 9.33K=35s

2016-10-27 15:16:39 (9.33 KB/s) - Read error at byte 489864831/910173851 (Success). Retrying.

--2016-10-27 15:16:40--  (try: 2)  https://s3.amazonaws.com/zcashfinalmpc/sprout-proving.key
Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.121.18|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 910173851 (868M), 420309020 (401M) remaining [application/octet-stream]
Saving to: ‘/home/Bob/.zcash-params/sprout-proving.key.dl’

        [ skipping 458752K ]
458752K ,,,,,,,, ,,,,,,,, ,,,...            54% 31.9K=1m54s

2016-10-27 15:18:55 (31.9 KB/s) - Connection closed at byte 493607068. Retrying.

--2016-10-27 15:18:57--  (try: 3)  https://s3.amazonaws.com/zcashfinalmpc/sprout-proving.key
Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.121.18|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 910173851 (868M), 416566783 (397M) remaining [application/octet-stream]
Saving to: ‘/home/Bob/.zcash-params/sprout-proving.key.dl’

        [ skipping 458752K ]
458752K ,,,,,,,, ,,,,,,,, ,,,,,,            54% 7.21K=31s

2016-10-27 15:19:59 (7.21 KB/s) - Read error at byte 493832889/910173851 (Success). Retrying.

--2016-10-27 15:20:02--  (try: 4)  https://s3.amazonaws.com/zcashfinalmpc/sprout-proving.key
Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.121.18|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 910173851 (868M), 416340962 (397M) remaining [application/octet-stream]
Saving to: ‘/home/Bob/.zcash-params/sprout-proving.key.dl’

        [ skipping 458752K ]
458752K ,,,,,,,, ,,,,,,,, ,,,,,,.           54% 19.7K=42s

2016-10-27 15:21:14 (19.7 KB/s) - Read error at byte 494685398/910173851 (Success). Retrying.

--2016-10-27 15:21:17--  (try: 5)  https://s3.amazonaws.com/zcashfinalmpc/sprout-proving.key
Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.121.18|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 910173851 (868M), 415488453 (396M) remaining [application/octet-stream]
Saving to: ‘/home/Bob/.zcash-params/sprout-proving.key.dl’

        [ skipping 458752K ]
458752K ,,,,,,,, ,,,,,,,, ,,,,,,,. .....    54% 20.4K=4m27s

2016-10-27 15:26:14 (20.4 KB/s) - Read error at byte 500247067/910173851 (Success). Retrying.

--2016-10-27 15:26:17--  (try: 6)  https://s3.amazonaws.com/zcashfinalmpc/sprout-proving.key
Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.121.18|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 910173851 (868M), 409926784 (391M) remaining [application/octet-stream]
Saving to: ‘/home/Bob/.zcash-params/sprout-proving.key.dl’

        [ skipping 458752K ]
458752K ,,,,,,,, ,,,,,,,, ,,,,,,,, ,,,,,... 55%  226K 5h19m
491520K                                     55% 36.0K=2m29s

2016-10-27 15:28:46 (21.1 KB/s) - Read error at byte 503458656/910173851 (Interrupted system call). Retrying.

--2016-10-27 15:28:49--  (try: 7)  https://s3.amazonaws.com/zcashfinalmpc/sprout-proving.key
Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.121.18|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 910173851 (868M), 406715195 (388M) remaining [application/octet-stream]
Saving to: ‘/home/Bob/.zcash-params/sprout-proving.key.dl’

        [ skipping 491520K ]
491520K
491520K                                     55% 25.6K=6.0s

2016-10-27 15:29:26 (25.6 KB/s) - Read error at byte 503614845/910173851 (Success). Retrying.

--2016-10-27 15:29:29--  (try: 8)  https://s3.amazonaws.com/zcashfinalmpc/sprout-proving.key
Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.121.18|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 910173851 (868M), 406559006 (388M) remaining [application/octet-stream]
Saving to: ‘/home/Bob/.zcash-params/sprout-proving.key.dl’

        [ skipping 491520K ]
491520K

**Comment by radix42** [comment]
What network are you downloading it to? I suspect it may be congestion between your ISP and Amazon, as I have within the last hour successfully downloaded the Sprout keys with fetch-param from multiple networks (CenturyLink in Arizona and within AWS itself).

**Comment by BobDoe** [comment]
ISP CenturyLink in Texas,  Ok that explains it wish I had another ISP in this service area only get 3Mb/s at best. They will not upgrade the equipment and no long sell any new connections

**Comment by bitcartel** [comment]
Already discussed in #1296 - we should not rely on a single storage provider and implement this for the next release.

**Comment by daira** [comment]
We intend to make this more robust, but there's no need for a separate ticket to be open for it.

**Comment by xia542046446** [comment]
I'm in China. i also can not download   "sprout-proving.key". 
 the error infomations is  fellowing:
--2017-06-27 21:56:42--  (尝试次数： 2)  https://s3.amazonaws.com/zcashfinalmpc/sprout-proving.key
正在连接 s3.amazonaws.com|54.231.73.2|:443... 已连接。
无法建立 SSL 连接。

please add new resource point!!!!!!!

**Comment by radix42** [comment]
try downloading from my mirror at https://zcash.dl.mercerweiss.com/sprout-proving.key
I am actually very interested to see if I am blocked there, too or not

**Comment by daira** [comment]
Shouldn't this be a new ticket? The original problem appears to have been with the user's ISP; this one appears to be a Great Firewall blocking issue. They require different solutions, since Chinese users can't practically get round the GFW just by changing or raising a support request with their ISP.

Making the proving key available as a Debian package, as I suggested in https://github.com/zcash/zcash/issues/890#issuecomment-233800513 , would in practice solve this problem, since as far as I know the GFW doesn't block package repos. It would also improve usability for all users by removing the fetch-params step entirely, since the zcash package could depend on the relevant proving key package.

Related: #621.

**Comment by xia542046446** [comment]
thank you ,radix42. i download it .then i uplaod it to "http://pan.baidu.com/s/1eSGeMau". Chinese people can download from  "http://pan.baidu.com/s/1eSGeMau"

**Comment by ioptio** [comment]
@bitcartel you reopened this but it's still in "Complete" in user support. Can we do anything else here or should this be closed?

**Comment by ioptio** [comment]
Closing this in lieu of opening another ticket to host proving on gitlab (like how we host dependencies #2498)
