### ISSUE TITLE
Not compiling on Ubuntu 14.04 nor Debian

### ISSUE THREAD

**Issue by dondreytaylor** [zcash/zcash#1672]
I've tried installing zcash on both Ubuntu 14.04 and Debian following the instructions listed. For some reason the installation errors once it attempts to build. I made sure to install all of the dependencies prior. Below is a screenshot of where it errors. It's telling me there is no compiler found. Any help would be greatly appreciated. Thanks

![untitled](https://cloud.githubusercontent.com/assets/3202583/19790037/c7f79f12-9c82-11e6-950a-2c18ad4bed45.png)

**Comment by ageis** [comment]
@dondreytaylor Just want to note, there are binary packages available for your platform, so you don't have to compile it yourself if you don't want to. https://github.com/zcash/zcash/wiki/Debian-binary-packages

**Comment by dondreytaylor** [comment]
Oh wow, completely missed this. Thanks, I'll install it using the binary instead.

**Comment by bharath-g** [comment]
When I try to follow the instructions [on this page](https://github.com/zcash/zcash/wiki/Debian-binary-packages) I get the following error.

`
W: Failed to fetch https://apt.z.cash/dists/jessie/Release  Unable to find expected entry 'main/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)
`

Can you please help me. I am also not able to build it see ticket I opened #1723
