### ISSUE TITLE
compiler error

### ISSUE THREAD

**Issue by fake2013** [zcash/zcash#1677]
sorry i don't know enough about Linux to give a good bug report but

Linux mint 18 /w cinnamon
./zcutil/build.sh -j$(nproc)
responses with:

```
home/forcemode/zcash/src/bitcoind.cpp:38: undefined reference to `ShutdownRequested()'
/home/forcemode/zcash/src/bitcoind.cpp:43: undefined reference to`ShutdownRequested()'
zcashd-bitcoind.o: In function `AppInit(int, char**)':
/home/forcemode/zcash/src/bitcoind.cpp:76: undefined reference to`LicenseInfo[abi:cxx11]()'
/home/forcemode/zcash/src/bitcoind.cpp:83: undefined reference to `HelpMessage[abi:cxx11](HelpMessageMode)'
/home/forcemode/zcash/src/bitcoind.cpp:147: undefined reference to`AppInit2(boost::thread_group&, CScheduler&)'
/home/forcemode/zcash/src/bitcoind.cpp:164: undefined reference to `Shutdown()'
libbitcoin_server.a(libbitcoin_server_a-noui.o): In function`boost::shared_ptr<boost::signals2::detail::signal_impl<bool (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int), boost::signals2::last_value<bool>, int, std::less<int>, boost::function<bool (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int)>, boost::function<bool (boost::signals2::connection const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int)>, boost::signals2::mutex> >::operator_() const':
/home/forcemode/zcash/depends/x86_64-unknown-linux-gnu/share/../include/boost/smart_ptr/shared_ptr.hpp:703: undefined reference to `uiInterface'
libbitcoin_server.a(libbitcoin_server_a-noui.o): In function`boost::shared_ptr<boost::signals2::detail::signal_impl<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>, boost::function<void (boost::signals2::connection const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>, boost::signals2::mutex> >::operator_() const':
/home/forcemode/zcash/depends/x86_64-unknown-linux-gnu/share/../include/boost/smart_ptr/shared_ptr.hpp:703: undefined reference to `uiInterface'
libbitcoin_common.a(libbitcoin_common_a-transaction.o): In function`boost::array<libzcash::Note, 2ul>::array()':
/home/forcemode/zcash/depends/x86_64-unknown-linux-gnu/share/../include/boost/array.hpp:60: undefined reference to `libzcash::Note::Note()'
/home/forcemode/zcash/depends/x86_64-unknown-linux-gnu/share/../include/boost/array.hpp:60: undefined reference to`libzcash::Note::Note()'
libbitcoin_common.a(libbitcoin_common_a-transaction.o): In function `CTxIn::ToString[abi:cxx11]() const':
/home/forcemode/zcash/src/primitives/transaction.cpp:117: undefined reference to`CScript::ToString[abi:cxx11]() const'
libbitcoin_common.a(libbitcoin_common_a-transaction.o): In function `CTxOut::ToString[abi:cxx11]() const':
/home/forcemode/zcash/src/primitives/transaction.cpp:137: undefined reference to`CScript::ToString[abi:cxx11]() const'
libbitcoin_common.a(libbitcoin_common_a-key.o): In function `CKey::VerifyPubKey(CPubKey const&) const':
/home/forcemode/zcash/src/key.cpp:87: undefined reference to`CPubKey::Verify(uint256 const&, std::vector<unsigned char, std::allocator<unsigned char> > const&) const'
libbitcoin_common.a(libbitcoin_common_a-key.o): In function `CKey::Derive(CKey&, uint256&, unsigned int, uint256 const&) const':
/home/forcemode/zcash/src/key.cpp:122: undefined reference to`BIP32Hash(uint256 const&, unsigned int, unsigned char, unsigned char const_, unsigned char_)'
/home/forcemode/zcash/src/key.cpp:125: undefined reference to `BIP32Hash(uint256 const&, unsigned int, unsigned char, unsigned char const*, unsigned char*)'
libzcash.a(libzcash_a-JoinSplit.o): In function`libzcash::JSInput::JSInput()':
/home/forcemode/zcash/src/zcash/JoinSplit.cpp:336: undefined reference to `libzcash::Note::Note()'
/home/forcemode/zcash/src/zcash/JoinSplit.cpp:337: undefined reference to`libzcash::random_uint256()'
/home/forcemode/zcash/src/zcash/JoinSplit.cpp:337: undefined reference to `libzcash::random_uint256()'
/home/forcemode/zcash/src/zcash/JoinSplit.cpp:339: undefined reference to`libzcash::Note::cm() const'
libzcash.a(libzcash_a-JoinSplit.o): In function `libzcash::input_note_gadget<libsnark::Fp_model<4l, libsnark::alt_bn128_modulus_r> >::generate_r1cs_witness(libzcash::MerklePath const&, libzcash::SpendingKey const&, libzcash::Note const&)':
/home/forcemode/zcash/src/./zcash/circuit/note.tcc:155: undefined reference to`libzcash::Note::cm() const'
libzcash.a(libzcash_a-JoinSplit.o): In function `libzcash::JSInput::nullifier() const':
/home/forcemode/zcash/src/zcash/JoinSplit.hpp:30: undefined reference to`libzcash::Note::nullifier(libzcash::SpendingKey const&) const'
/home/forcemode/zcash/src/zcash/JoinSplit.hpp:30: undefined reference to `libzcash::Note::nullifier(libzcash::SpendingKey const&) const'
libzcash.a(libzcash_a-JoinSplit.o): In function`libzcash::JoinSplitCircuit<2ul, 2ul>::prove(boost::array<libzcash::JSInput, 2ul> const&, boost::array<libzcash::JSOutput, 2ul> const&, boost::array<libzcash::Note, 2ul>&, boost::array<boost::array<unsigned char, 601ul>, 2ul>&, uint256&, uint256 const&, uint256&, boost::array<uint256, 2ul>&, boost::array<uint256, 2ul>&, boost::array<uint256, 2ul>&, unsigned long, unsigned long, uint256 const&, bool)':
/home/forcemode/zcash/src/zcash/JoinSplit.cpp:190: undefined reference to `libzcash::random_uint256()'
/home/forcemode/zcash/src/zcash/JoinSplit.cpp:196: undefined reference to`libzcash::random_uint252()'
/home/forcemode/zcash/src/zcash/JoinSplit.cpp:201: undefined reference to `libzcash::random_uint256()'
/home/forcemode/zcash/src/zcash/JoinSplit.cpp:201: undefined reference to`libzcash::random_uint256()'
/home/forcemode/zcash/src/zcash/JoinSplit.cpp:208: undefined reference to `libzcash::Note::cm() const'
/home/forcemode/zcash/src/zcash/JoinSplit.cpp:208: undefined reference to`libzcash::Note::cm() const'
/home/forcemode/zcash/src/zcash/JoinSplit.cpp:214: undefined reference to `libzcash::NoteEncryption<585ul>::NoteEncryption(uint256)'
/home/forcemode/zcash/src/zcash/JoinSplit.cpp:218: undefined reference to`libzcash::NotePlaintext::NotePlaintext(libzcash::Note const&, boost::array<unsigned char, 512ul>)'
/home/forcemode/zcash/src/zcash/JoinSplit.cpp:220: undefined reference to `libzcash::NotePlaintext::encrypt(libzcash::NoteEncryption<585ul>&, uint256 const&) const'
/home/forcemode/zcash/src/zcash/JoinSplit.cpp:218: undefined reference to`libzcash::NotePlaintext::NotePlaintext(libzcash::Note const&, boost::array<unsigned char, 512ul>)'
/home/forcemode/zcash/src/zcash/JoinSplit.cpp:220: undefined reference to `libzcash::NotePlaintext::encrypt(libzcash::NoteEncryption<585ul>&, uint256 const&) const'
libzcash.a(libzcash_a-Address.o): In function`libzcash::ViewingKey::pk_enc()':
/home/forcemode/zcash/src/zcash/Address.cpp:16: undefined reference to `libzcash::NoteEncryption<585ul>::generate_pubkey(uint256 const&)'
libzcash.a(libzcash_a-Address.o): In function`libzcash::SpendingKey::viewing_key() const':
/home/forcemode/zcash/src/zcash/Address.cpp:20: undefined reference to `libzcash::NoteEncryption<585ul>::generate_privkey(uint252 const&)'
libzcash.a(libzcash_a-Address.o): In function`libzcash::SpendingKey::random()':
/home/forcemode/zcash/src/zcash/Address.cpp:24: undefined reference to `libzcash::random_uint252()'
libzcash.a(libzcash_a-Address.o): In function`libzcash::ViewingKey::pk_enc()':
/home/forcemode/zcash/src/zcash/Address.cpp:16: undefined reference to `libzcash::NoteEncryption<585ul>::generate_pubkey(uint256 const&)'
collect2: error: ld returned 1 exit status
Makefile:3112: recipe for target 'zcashd' failed
make[2]: **\* [zcashd] Error 1
make[2]: Leaving directory '/home/forcemode/zcash/src'
Makefile:7453: recipe for target 'all-recursive' failed
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory '/home/forcemode/zcash/src'
Makefile:640: recipe for target 'all-recursive' failed
make: **\* [all-recursive] Error 1
```

**Comment by Doccos** [comment]
same error 

full compile log
[pastbin](http://pastebin.com/0bHGKR7P)

**Comment by fake2013** [comment]
tried to follows Doccos institutions:
i did:
cd /
rm -r zcash/
then followed the new 1.0 guide 
this time ./zcutil/build.sh -j$(nproc) responses with:

{standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Makefile:4047: recipe for target 'libbitcoin_server_a-main.o' failed
make[2]: *** [libbitcoin_server_a-main.o] Error 4
make[2]: *** Waiting for unfinished jobs....
mv -f .deps/libbitcoin_server_a-init.Tpo .deps/libbitcoin_server_a-init.Po
make[2]: Leaving directory '/zcash/src'
Makefile:7453: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/zcash/src'
Makefile:640: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by fake2013** [comment]
binaries anyone?

**Comment by radix42** [comment]
If zcashco's Debian Binaries for Jessie aren't working for you, I have one built on Ubuntu 16.04 that should work on Mint Cinnamon at: https://zcash.dl.mercerweiss.com/zcash-1.0.0-sprout-amd64.deb

After you download it, "sudo dpkg -i zcash-1.0.0-sprout-amd64.deb" and then you should be able to run zcashd and zcash-cli without "./src/" or anything in front of them.

**Comment by fake2013** [comment]
Thanks radix42
I'm currently trying the instutions at: https://www.youtube.com/watch?v=ZoRFLkZG0zg&feature=youtu.be
as root it looks like it might work. if not i'll try that next.

**Comment by radix42** [comment]
I'm actually curious to know if my build works on Mint Cinnamon, as I don't have a current Mint machine and the one I do have is in storage over 1000 miles away!

**Comment by fake2013** [comment]
I can build another Mint vbox and test it for you. (it will take a little while)

**Comment by fake2013** [comment]
unless you need to test on hardware only :)

**Comment by radix42** [comment]
that'd be great, thanks

**Comment by fake2013** [comment]
the instructions at: https://www.youtube.com/watch?v=ZoRFLkZG0zg&feature=youtu.be
works as long as you signed in as root.

radix42,
will update soon ...

**Comment by fake2013** [comment]
radix42,
your .deb installed fine but ..
zcashd returns:

Thank you for running a Zcash node!
You're helping to strengthen the network and contributing to a social good :)

You are currently not mining.
To enable mining, add 'gen=1' to your zcash.conf and restart.

Since starting this node 0 seconds ago:
- You have validated 0 transactions!

Init message: 

[Press Ctrl+C to exit] [Set 'showmetrics=0' to hide]


************************
EXCEPTION: St13runtime_error       
could not load param file at /root/.zcash-params/sprout-verifying.key       
Zcash in AppInit()       

zcashd: scheduler.cpp:19: CScheduler::~CScheduler(): Assertion `nThreadsServicingQueue == 0' failed.
Aborted


---- there no such directory "/root/.zcash-params" theres a "/root/.zcash"

I'm am running zcash-fetch-params from /usr/bin 
I believe this will make it work

**Comment by fake2013** [comment]
well ... zcash-fetch-params from /usr/bin  created the directory but the file sprout-verifying.key is missing

**Comment by radix42** [comment]
what user did you run zcash-fetch-params as? it must be the same user that
will run zcashd, on a login shell (if you are root, switch to one with
"sudo su - USERNAME-I-WILL-RUN-ZCASHD-AS")

**Comment by fake2013** [comment]
i am running everything as root 
I do not know why the files are being installed to /usr/bin 

I'm logging in under my reg username and executing:
cd /usr/bin
zcash-fetch-params 

i'll see what happens
FYI:
the user folder for root is: /root/
My user folder is: /home/{username}/

**Comment by radix42** [comment]
you do not want to run zcash-fetch-params or zcashd as root, you want to
run them as a normal user....when the deb was installed it put the binaries
in /usr/bin/, which is normal, and they are now in regular user's defautl
PATH

**Comment by fake2013** [comment]
after logging in as a reg user
and typing
cd /usr/bin
zcash-fetch-params
cd/
zcashd

it stated i needed a zcash.conf file in /home/{username}/
i create it and now it is working

i installed it as root because i keep getting permission denied even using 'sudo'
mint does not let the user do much.

**Comment by radix42** [comment]
Excellent!!!

**Comment by daira** [comment]
If you run it sometimes as root and sometimes not, that cannot be expected to work, because the invocations as root will create files that the later invocations as non-root will not be able to read. In general, running anything as root usually causes more permissions problems than it done, even independent of the security issues with doing so.

**Comment by shouhuas** [comment]
make clean
make

I had soloved

**Comment by nathan-at-least** [comment]
@fake2013, did you resolve this issue by not running the build process as root?

**Comment by fake2013** [comment]
@nathan-at-least, no i solved the problem by following the instructions at: https://www.youtube.com/watch?v=ZoRFLkZG0zg&feature=youtu.be
works as long as you signed in as root. The instructions on GitHub due not work on Linux mint.
the not logging on as root was in response to @radix42 binaries.

**Comment by fake2013** [comment]
Also I believe if you type "sudo --login" before the other commands you would not need to login as root.
I've had some luck with this method.

**Comment by fake2013** [comment]
I found out why i need to login as root to get the instructions at: https://www.youtube.com/watch?v=ZoRFLkZG0zg&feature=youtu.be to work.
according to https://help.ubuntu.com/community/RootSudo you cannot redirect output use sudo be the video say to.

"Redirecting the output of commands run with sudo requires a different approach. For instance consider sudo ls > /root/somefile will not work since it is the shell that tries to write to that file. You can use ls | sudo tee -a /root/somefile to append, or ls | sudo tee /root/somefile to overwrite contents. You could also pass the whole command to a shell process run under sudo to have the file written to with root permissions, such as sudo sh -c "ls > /root/somefile".

**Comment by daira** [comment]
The video no longer says to redirect the output of sudo. Closing.

**Comment by nicola** [comment]
I am having the same problem with the same exact error log right now :(
