### ISSUE TITLE
./src/zcashd -daemon    ISSUE

### ISSUE THREAD

**Issue by dahvidhill** [zcash/zcash#1678]
Trying to run 

./src/zcashd -daemon 

but it says there is no file or directory??

when i look in cd src 
i search the dir
and dont find a zcashd ... only a zcash

**Comment by daira** [comment]
This probably indicates that the build failed. Can you paste the output of the build?

**Comment by dahvidhill** [comment]
is that the original build file or the build-essential run? @daira

**Comment by daira** [comment]
The shell output from the ``zcutil/build.sh`` command.

**Comment by hjhart** [comment]
@dahvidhill specifically, what outputs when you execute this step: https://github.com/zcash/zcash/wiki/1.0-User-Guide#build

**Comment by daira** [comment]
@dahvidhill Have you been able to build zcash successfully since this ticket was opened?

**Comment by daira** [comment]
Please reopen if this is still an issue.

**Comment by traderhanson** [comment]
Hello.  I followed this link:  

https://github.com/zcash/zcash/wiki/1.0-User-Guide

when i was about to run : ./src/zcashd

it says no such file or directory

:(  please help
