### ISSUE TITLE
Test Failed. So you guys know. RC4

### ISSUE THREAD

**Issue by kgrgpg** [zcash/zcash#1679]
FAIL: zcash-gtest
../build-aux/test-driver: line 135: echo: write error: No space left on device
../build-aux/test-driver: line 136: echo: write error: No space left on device
../build-aux/test-driver: line 137: echo: write error: No space left on device
../build-aux/test-driver: line 138: echo: write error: No space left on device
Makefile:7694: recipe for target 'zcash-gtest.log' failed
make[4]: *** [zcash-gtest.log] Error 1
make[4]: Leaving directory '/home/ubuntu/zcash/src'
Makefile:7666: recipe for target 'check-TESTS' failed
make[3]: *** [check-TESTS] Error 2
make[3]: Leaving directory '/home/ubuntu/zcash/src'
Makefile:7779: recipe for target 'check-am' failed
make[2]: *** [check-am] Error 2
make[2]: Leaving directory '/home/ubuntu/zcash/src'
Makefile:7453: recipe for target 'check-recursive' failed
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory '/home/ubuntu/zcash/src'
Makefile:640: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1
=== ./src/test-suite.log ===
cat: ./src/test-suite.log: No such file or directory
===== FAILED: make check || { echo === ./src/test-suite.log === ; cat ./src/test-suite.log ; false ; }

**Comment by 0x626b61** [comment]
so '../build-aux/test-driver: line 135: echo: write error: No space left on device'

looks like your disk is full ?

**Comment by kgrgpg** [comment]
Yes, +1. Increased the disk space. Thanks
