### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by cryptomonk** [zcash/zcash#1686]
Still problems!

**/home/denwer/zcash/depends/x86_64-unknown-linux-gnu/share/../include/boost/variant/detail/visitation_impl.hpp:268:1: internal compiler error: in clear_marks, at ggc-page.c:1871**
 }
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Makefile:7330: recipe for target 'zcashd-bitcoind.o' failed
make[2]: *** [zcashd-bitcoind.o] Error 1
make[2]: *** Waiting for unfinished jobs....
mv -f .deps/libbitcoin_server_a-asyncrpcqueue.Tpo .deps/libbitcoin_server_a-asyncrpcqueue.Po
mv -f .deps/libbitcoin_server_a-alert.Tpo .deps/libbitcoin_server_a-alert.Po
mv -f .deps/libbitcoin_server_a-asyncrpcoperation.Tpo .deps/libbitcoin_server_a-asyncrpcoperation.Po
make[2]: Leaving directory '/home/denwer/zcash/src'
Makefile:7453: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/denwer/zcash/src'
**Makefile:640: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1**

**Comment by cfdtlee** [comment]
Same problem!
