### ISSUE TITLE
Getting a Bus error

### ISSUE THREAD

**Issue by zenjakes** [zcash/zcash#1687]
After entering the command to start the miner in terminal i get a momentary shot of the heart and z coin with the normal text the a line with bus error
`Bus error`
Someone please help???

**Comment by bitcartel** [comment]
@zenjakes What is your computing system/environment?  Did you do a clean of build of v1.0.0?

**Comment by zenjakes** [comment]
@bitcartel I use linux as a second OS and I follwed the guide to upgrade to sprout, please don't tell me I will have to download the key's again?

**Comment by str4d** [comment]
@zenjakes the network parameters in 1.0.0 are the same as for RC4.

**Comment by daira** [comment]
Can you try again with the current User Guide, please?

**Comment by daira** [comment]
Please reopen if this is still an issue.
