### ISSUE TITLE
add info to the mining metrics screen

### ISSUE THREAD

**Issue by zookozcash** [zcash/zcash#1688]
Things I would like to see on the "mining metrics" screen:
- which solver am I using (“default”) or (“tromp”)
- how many peers am I connected to

**Comment by zookozcash** [comment]
![2016-10-28-105222_2560x1440_scrot](https://cloud.githubusercontent.com/assets/16416064/19816716/46639c8c-9cfd-11e6-994e-4282fa8e812b.png)

**Comment by daira** [comment]
Also, estimated total network solution rate.

**Comment by daira** [comment]
@nathan-at-least also wants the block height (#1682, which I merged into this ticket).
