### ISSUE TITLE
Does "balance" ever update?

### ISSUE THREAD

**Issue by imkane** [zcash/zcash#1689]
Been running zcash 1.0 daemon for a couple hours now.

root@z:~/zcash# ./src/zcash-cli getinfo

"balance" : 0.00000000,

Not sure if anyone has a positive balance yet?

Also, how does it know to store the balance in the wallet we created by:
./src/zcash-cli z_getnewaddress
?

Sorry if this is the wrong place to ask this, I couldn't find a forum or anywhere else to post a question.

**Comment by daira** [comment]
You can see at https://explorer.zcha.in/accounts that mining rewards are working correctly and some addresses do have balances. You just haven't mined a block. Mining is very difficult, since the total estimated network solution rate is ~275000 Sol/s as I write this.

**Comment by daira** [comment]
Mining rewards are created at randomly generated t-addresses, which can be seen using ``listtransactions`` if there are any.

**Comment by imkane** [comment]
Thanks @daira!

**Comment by imkane** [comment]
So another (probably dumb) question:

"balance" : 0.00000000

Does this typically get updated to the 8th decimal place?  So I may, at some point, eventually, expect to see:

"balance" : 0.00000001

?

**Comment by daira** [comment]
No, mining rewards during slow start are always multiples of 0.00062500 ZEC. Mining a block is very unlikely for an individual miner, but there is a quite significant reward if you do.

**Comment by r0br0dz** [comment]
Mining a block is very unlikely for an individual miner, but there is a quite significant reward if you do.

What makes it unlikely? New and would love an explanation. What is the reward?
Thank you

**Comment by hazinstore** [comment]
Best advice is to go to the forums and research how mining works.  What makes it unlikely is the same thing that makes it unlikely you will win the lottery, i.e. statistics.

**Comment by arcalinea** [comment]
Probably would be best to move this conversation to the forum, https://forum.z.cash/
