### ISSUE TITLE
could not load param file at /root/.zcash-params/sprout-verifying.key

### ISSUE THREAD

**Issue by coinnodenl** [zcash/zcash#1693]
I compiled mainnet 1.0 getting the following error running;

could not load param file at /root/.zcash-params/sprout-verifying.key

**Comment by zenbooster** [comment]
i have same problem...

**Comment by coinnodenl** [comment]
Solved the issue i quess; 

remove the .zcash-params folder if you used beta then run the following command in your zcash folder

./zcutil/fetch-params.sh

**Comment by zenbooster** [comment]
It's work!

**Comment by bitcartel** [comment]
Users resolved ticket. Closing.
