### ISSUE TITLE
"prev block not found" error when mining on mainnet.

### ISSUE THREAD

**Issue by miningpoolhub** [zcash/zcash#1695]
I have no idea what's the problem currently.
It worked well at beta testnet, but can't mine any block at mainnet.

Daemon outputs "prev block not found" error.
Seems like it is saying that block.hashPrevBlock is not found from block map index.

What is causing the difference between mainnet and testnet?

Is it related to zcash-params directory?
Now I'm trying to delete that directory and redownload them but not sure.

Please advise me.

**Comment by sakamoto1255** [comment]
Did you tried https://github.com/zcash/zcash/wiki/1.0-User-Guide upgrade process??

**Comment by miningpoolhub** [comment]
@sakamoto1255 
Yeah, I tried that too.
One different thing is that I commented out `reservekey.KeepKey();` as below link says.
https://github.com/zcash/zcash/wiki/Mining-Guide#mine-to-a-single-address
Rest of all source codes are same, fetched zcash params again but no luck.

Pool software is same, mined several blocks on RC4.
Maybe I have to dig deep debugging what is causing this error.

I still don't understand that how mapBlockIndex can't find previous block. Any hints about it?

```
    CBlockIndex* pindexPrev = NULL;
    if (hash != chainparams.GetConsensus().hashGenesisBlock) {
        BlockMap::iterator mi = mapBlockIndex.find(block.hashPrevBlock);
        if (mi == mapBlockIndex.end())
            return state.DoS(10, error("%s: prev block not found", __func__), 0, "bad-prevblk");
        pindexPrev = (*mi).second;
        if (pindexPrev->nStatus & BLOCK_FAILED_MASK)
            return state.DoS(100, error("%s: prev block invalid", __func__), REJECT_INVALID, "bad-prevblk");
    }
```

**Comment by miningpoolhub** [comment]
This problem has gone away when I rebuilt from scratch.
Previously, I reused source directory (intermediate obj files from testnet rc4), and seems like it made some constant values conflict.
