### ISSUE TITLE
How can I increase the number of threads tromp's miner uses?

### ISSUE THREAD

**Issue by Jamie452** [zcash/zcash#1696]
Can't see anything in the documentation to increase the number of threads tromp's miner uses when running via ./src/zcashd.

**Comment by Jamie452** [comment]
To answer my own question (found it by adding -help argument):

./src/zcashd -genproclimit=2 - run on 2 threads
./src/zcashd -genproclimit=-1 - automatically use a thread per core

**Comment by imkane** [comment]
You can also just edit /.zcash/zcash.conf and add something like:

`genproclimit=4`
