### ISSUE TITLE
Secure Multiparty Computation for setup parameters.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#17]

**Comment by ebfull** [comment]
I'm placing engineering meeting agenda on this ticket because I suspect we should close it as we have other means to discuss and sync up on the work done on this, and it's not really appropriately placed in the milestones anyway.

**Comment by nathan-at-least** [comment]
@ebfull +1 We're tracking this at a higher level so this ticket is just a distracting nuisance.
