### ISSUE TITLE
zcbenchmarks.cpp build fail on GCC 4.7.2

### ISSUE THREAD

**Issue by Zenitur** [zcash/zcash#1707]
http://pastebin.com/rwpVjRQv

**Comment by bitcartel** [comment]
Are you able to upgrade to GCC 5.x or even GCC 6 ?

**Comment by Zenitur** [comment]
Yes, I have been copied binaries compiled with GCC 4.9.2 from another PC. Now I just tell you about an error in code

**Comment by JanKalin** [comment]
Known problem. You can compile with a few edits. See https://github.com/zcash/zcash/issues/838#issuecomment-248610250 for details

**Comment by radix42** [comment]
This same thing happens when building on some other platforms with gcc 5 or 6 (different flags were given than on linux when gcc itself was built than when it was built on mac for brew or windows for msys2, yay). I'll try the patch in 838 for my Windows build.

**Comment by Zenitur** [comment]
After applying @JanKalin patch, I haven't compiling errors anymore

**Comment by daira** [comment]
We're now requiring gcc/g++ 4.9 or later (and the User Guide documents that), so I think this can be closed.
