### ISSUE TITLE
overshoot in difficulty adjustment

### ISSUE THREAD

**Issue by daira** [zcash/zcash#1708]
The block time according to https://explorer.zcha.in/ is 287s (mean of 120 blocks) as of Oct 28 02:19 UTC. It's supposed to be 150s, and has overshot from the period of too-short blocks just after launch. I'm not sure whether this is a long-term problem yet, but it's something we need to keep our eye on, and may indicate a bug in the difficulty adjustment.

**Comment by lustr0** [comment]
Luckily enough, in this case it's merely a bug in my hastily modified chain sync algorithm - the displayed block time was off by a factor of two.

For reference: https://gist.github.com/lustr0/d60c4786fef9a79cceb3d4b224af123b

**Comment by daira** [comment]
Thanks. Incidentally, you can do that mean calculation equivalently and more simply by subtracting the block times 120 blocks apart, rather than explicitly computing the sum. Note that this is subject to manipulation of the block times at the start and end of the window, which is why the difficulty adjustment algorithm uses the *median* of 11 block times around the start and end of its (17-block) window.
