### ISSUE TITLE
cant send transparent funds from coinbase

### ISSUE THREAD

**Issue by feeleep75** [zcash/zcash#1709]
```z_gettotalbalance``` gives me:
```
{
    "transparent" : "5.9697113",
    "private" : "0.00",
    "total" : "5.9697113"
}
```

when i try to send it with ```z_sendmany``` i have this debug.log
```
2016-10-29 04:31:01 async rpc opid-2a03899e-661d-477e-a5db-072f06bda298 finished (status=failed, error=Insufficient transparent funds, have 20950000, need 596971130)
```

**Comment by bitcartel** [comment]
1. Are all these transparent coins mined, i.e. coinbase utxos?
2. What is the z_sendmany command you are entering on the command line?  Please copy here.  Thanks.

**Comment by feeleep75** [comment]
for some reason coinbase address has changed - we can close this one
