### ISSUE TITLE
disable RPC interface if you detect you are on the short side of a fork

### ISSUE THREAD

**Issue by zookoatleastauthoritycom** [zcash/zcash#171]
A couple of weeks ago, the day that Andrew left IEEE ("Oakland") and came to stay with Nathan, Andrew and Brian and I had a conversation about "forward-compatibility" and "future-proofing" features for Zcoin. Out of that conversation, only two of the options seemed to me to be "shallow rabbit holes", where I could see the bottom of how many decisions and how much work we'd have to do in order to implement the thing: shipping with The Update Framework (TUF) http://theupdateframework.com/ (or any other comparable secure software updater), and having the Zcoin node freeze with a warning message if it detects that it is on the short side of a fork. This ticket is about the second one of those. https://github.com/Electric-Coin-Company/zerocashd/issues/170 is about TUF.

**Comment by defuse** [comment]
Let's not merge #131 and #171.

**Comment by defuse** [comment]
Nathan says a lot of the feature might already be implemented in upstream.

**Comment by defuse** [comment]
(At least warning.)

**Comment by defuse** [comment]
There might already be a mechanism for disabling the wallet too.

**Comment by defuse** [comment]
Some functionality already exists in `main.cpp` in `CheckForkWarningConditions()`. It checks for (at least) two things: 2. If there's a valid fork more than 72 blocks ahead 2. If there's an invalid fork (e.g. hard fork where blocks are still parseable) with at least least 6 blocks worth of PoW effort (according to the current chain tip's difficulty) expended on it.

**Comment by defuse** [comment]
There are four fork cases I envision:

1. A hard fork which makes new blocks unparsable by old blocks, or changes the proof of work. I'm pretty sure these can't be detected without adding a DoS vector.
2. A hard fork which doesn't do the above. These can be detected by following the best chain of invalid blocks, which is what it looks like the Bitcoin code is doing (case 2 above).
3. A long "network split" style fork, which is detected by case 1 above.
4. A soft fork where miners change their mind later, which will look something like a hard fork to everyone who updated to the software with the soft fork.

It's ambiguous which of these cases the RPC interface should be disabled for.

**Comment by defuse** [comment]
I'm going to assume this ticket is about disabling the RPC interface for cases 2 and 3 (which should also catch case 4, but I'm not sure). In that case it really is a duplicate of #131.

**Comment by defuse** [comment]
Bitcoin has a built-in Safe Mode feature which is for disabling RPCs related to sending money or viewing money that you've received. Turning that on when a fork is detected is probably sufficient for this ticket, but we may want to make it more conservative, e.g. it doesn't turn off the mining RPCs.

**Comment by mcelrath** [comment]
FWIW I'm leaning toward the following algorithm with braids:
1. Keep track of the highest work ever seen on the network.
2. Instead of "confirmations", dynamically compute the confirmation time, assuming any "missing" hashrate is trying to construct an alternate chain.
3. This algorithm results in finite confirmation times as long as the observed hashrate remains at least 51% of the maximum hashrate ever seen.
4. If the observed hashrate is below 50% of the maximum ever seen, the computed "confirmation times" are infinite.
5. Transactions can still be accepted and mined on the minority chain, and when it rejoins the main chain they will be confirmed, if they are not double-spends.
6. All double-spends on the minority chain will be rejected when the chains re-join.

See also #975

**Comment by defuse** [comment]
Oh wow, it looks like safe mode already gets turned on by the hard fork detection in `GetWarnings()` inside main.cpp.

**Comment by defuse** [comment]
I'll make sure the RPC tests are testing this.

**Comment by defuse** [comment]
#1009 makes it run the `-alertnotify` command when there's a hard fork adds an RPC test that checks the hard fork detection.
