### ISSUE TITLE
Too many errors while installing zcash on debian!

### ISSUE THREAD

**Issue by sakamoto1255** [zcash/zcash#1710]
Hello,
I've tried to install zcash on debian, but it comes with so many errors!
I've reinstalled debian and tried it again, however, It ends up with errors.
I'm frustrated that Since I am living in Korea, It takes so many time to download key file.

Here, I will paste the error below that occured last install.

{standard input}: Assembler messages:
{standard input}:185815: Warning: end of file not at end of a line; newline inserted
{standard input}:186030: Error: unknown pseudo-op: `.alig'
g++: internal compiler error: dead (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See file:///usr/share/doc/gcc-4.9/README.Bugs for instructions.
Makefile:4006: recipe for target 'libbitcoin_server_a-init.o' failed
make[2]: **\* [libbitcoin_server_a-init.o] Error 4
make[2]: Leaving directory '/zcash/src'
Makefile:7440: recipe for target 'all-recursive' failed
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory '/zcash/src'
Makefile:628: recipe for target 'all-recursive' failed
make: **\* [all-recursive] Error 1

**Comment by bitcartel** [comment]
@sakamoto1255  Thanks for your message.  There is already a ticket about hosting copies of the key file #1296 across different storage providers around the world, which should be in the next release.

**Comment by leshaze** [comment]
Is it an VM? try to increase the ram to at least 4gb and compile it again. I had the same dump while running the vm with 1GB of ram.

**Comment by sakamoto1255** [comment]
@leshaze Oh, That might be the reason of errors.
When I installed on local hardware, not VM, It worked properly.
And My Hardware: i5 6600 8GB rx 480(with 8GB GDDR5)

**Comment by Charkel** [comment]
I have the same error but I have 4GB on RAM and no VM

**Comment by ITH4Coinomia** [comment]
@sakamoto1255 Seems you are trying to install zcash with limited dependencies which can't be possible. Did you tried installing zcash using VM? As mentioned earlier, you already have the sufficient requirement needed to install zcash.
