### ISSUE TITLE
Dockerfile to simplify build / portability

### ISSUE THREAD

**Issue by alexellis** [zcash/zcash#1711]
I've put this tutorial together which provides a Dockerfile for Ubuntu based upon the official instructions.

http://blog.alexellis.io/mine-zcash-with-docker/

Would you be willing to take a PR to add the Dockerfile and/or a link to the tutorial?

Thanks,
Alex

**Comment by joaocc** [comment]
You may want to take a look at https://github.com/zcash/zcash/pull/1700, which has zcash running as a service

**Comment by mms710** [comment]
The team is going to review this and determine if this can be added to Read The Docs

**Comment by str4d** [comment]
ECC now publishes official Docker images here: https://hub.docker.com/r/electriccoinco/zcashd
