### ISSUE TITLE
Daemon crashing: terminate called after throwing an instance of 'std::bad_alloc

### ISSUE THREAD

**Issue by krilson** [zcash/zcash#1712]
This is the output in the console:
`terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
^C
`
Nothing in the debug.log, the log output just stops.

Since the launch happened about 7 times at random times. I don't run any services on top of the node, just using it as a wallet. 

Running ubuntu 14.04.

I am also having this issue if it might be connected in any way: #1705 maybe the wallet crashes when it is trying to receive the missing transaction? I don't know...

**Comment by abrain** [comment]
Had this `bad_alloc` problem as well. It went away when I increased the RAM of my Debian VM from 768 MB to 2048 MB.

**Comment by krilson** [comment]
I am still having this problem on a 8GB and 16GB ram machine. (not a VM)

Strange...

**Comment by bitcartel** [comment]
@krilson Hi, is this still an issue?  If yes, how much free memory do you have on your system?

**Comment by krilson** [comment]
@bitcartel Hi, I am not running a node 24/7 anymore, just use it as a wallet occasionally. But at the time, the free memory was around 6GB (out of 8) and 8GB (out of 16GB).

**Comment by bitcartel** [comment]
Filed ticket https://github.com/zcash/zcash/issues/2155 to investigate memory usage further.
