### ISSUE TITLE
How will I know I mined some ZEC?

### ISSUE THREAD

**Issue by urza** [zcash/zcash#1713]
Hi,
I am running the full node with mining enabled.
How will I know that I mined some ZTC and at what address will they appear?

THanks

**Comment by CalldiDoctor** [comment]
I have the same question. 
In the 1.0 User Guide page they just say how to start mining, but I've not found anything related to how to know if you have earned some ZTC. 

Well, the documentation says that the reward can only go to a t_addr, but I don't know how to see the list of available t_adrr's.

**Comment by ebfull** [comment]
@CalldiDoctor Use `listunspent` to see value you've received on your t-addrs.

**Comment by urza** [comment]
It will supposedly appear in your wallen on new address, you can check status like this: "zcash-cli listunspent"

**Comment by CalldiDoctor** [comment]
Thanks, I'll try that one.

**Comment by CalldiDoctor** [comment]
I don't see any address executing this command...
I just see this:
[
]

Am I doing something wrong?

**Comment by ostegm** [comment]
Thats an indication that you have not yet mined any ZEC.

**Comment by arcalinea** [comment]
It looks like str4d also added some improvements to the metrics screen, tagged in the commit above--at any rate, `listunspent` should show you the balance on your t-addrs.
