### ISSUE TITLE
Exorbitant Dust and TX Fee

### ISSUE THREAD

**Issue by timolson** [zcash/zcash#1719]
The dust threshold currently appears to be 0.00015 ZEC which at the moment is over USD 50¢.  Also, a minRelayTxFee of 0.00005 (5000 Zatoshis) is currently 15¢.

https://github.com/zcash/zcash/blob/dcea8593c8b52cd2702441945afb535d3252033e/src/main.cpp#L72
`CFeeRate minRelayTxFee = CFeeRate(5000);`

https://github.com/zcash/zcash/blob/30d3d2dfd438a20167ddbe5ed2027d465cbec2f0/src/primitives/transaction.h#L265

```
CAmount GetDustThreshold(const CFeeRate &minRelayTxFee) const
    {
        // "Dust" is defined in terms of CTransaction::minRelayTxFee,
        // which has units satoshis-per-kilobyte.
        // If you'd pay more than 1/3 in fees
        // to spend something, then we consider it dust.
        // A typical txout is 34 bytes big, and will
        // need a CTxIn of at least 148 bytes to spend:
        // so dust is a txout less than 546 satoshis 
        // with default minRelayTxFee.
        size_t nSize = GetSerializeSize(SER_DISK,0)+148u;
        return 3*minRelayTxFee.GetFee(nSize);
    }
```

**Comment by daira** [comment]
This might be contributing to the problem in #1705.

**Comment by str4d** [comment]
The comment in `GetDustThreshold` was written in October 2014, while `minRelayTxFee` was bumped from 1000 Satoshis to 5000 in October 2015. The comment should have been updated to read:

```
        // "Dust" is defined in terms of CTransaction::minRelayTxFee,
        // which has units satoshis-per-kilobyte.
        // If you'd pay more than 1/3 in fees
        // to spend something, then we consider it dust.
        // A typical txout is 34 bytes big, and will
        // need a CTxIn of at least 148 bytes to spend:
        // so dust is a txout less than 2730 satoshis 
        // with default minRelayTxFee.
```

However, the threshold observed by @timolson is still 5.5x larger than the actual threshold... How were you arriving at that figure?

**Comment by str4d** [comment]
Note that the upstream codebase [has been updated in light of segwit](https://github.com/bitcoin/bitcoin/blob/master/src/primitives/transaction.h#L165) to explicitly say that the dust threshold for a non-segwith txout is `546*minRelayTxFee/1000` (which is the same result I give above).

**Comment by timolson** [comment]
I could be totally wrong about the amounts.  We experienced dust problems when trying to pay our users via `sendmany`, then I quickly dug around the code and found the above.  Since we needed to be expedient, we just made sure payments were above 30000 zatoshis and moved on.  I'll try reducing our payout algorithm's dust threshold to 2730 and report back.

**Comment by nathan-at-least** [comment]
@timolson, is this still a problem for you with the lower price?

**Comment by timolson** [comment]
Sorry we haven't tried it yet.  Will try to remember for our next payout
process.

**Comment by nathan-at-least** [comment]
Let's figure out a longer term strategy. In the short term, let's re-evaluate this issue in light of the continually lowering price.

**Comment by bitcartel** [comment]
PR #1855 sets minrelaytxfee to 1000 to match upstream:
https://github.com/bitcoin/bitcoin/commit/536766c903c8dc84e6709e4bd387aad5acf8e433
https://github.com/bitcoin/bitcoin/blob/master/src/main.h#L52
Also see user reaction to the experiment/fiddling with 5000:
https://bitcointalk.org/index.php?topic=1214993.0;all
