### ISSUE TITLE
Do not understand how to miining...

### ISSUE THREAD

**Issue by 4815162342lost** [zcash/zcash#1722]
Sorry, but how to mining?

I downloaded files and compiled it. 
I generate new taddress and zaddress via command 

```
./src/zcash-cli z_getnewaddress
./src/zcash-cli getnewaddress
```

I modified ~/.zcash/zcash.conf files and added my addresses:

```
addnode=mainnet.z.cash
rpcuser=username
rpcpassword="MY_PASS_HAS_BEEN_GEN_AUTOMATICLY"
gen=1
genproclimit=4
equihashsolver=tromp
TADDR='MY_ADR'
ZADDR='MY_ADR
```

And what is next? Should i modify rpcuser entry? Or I may to start to mining via ./src/zcashd?
Where will my balance be maintained? How to manage money?

**Comment by jeteon** [comment]
There's a mining guide I found on the repo here: https://github.com/zcash/zcash/wiki/Mining-Guide. I think you do basically just run `.src/zcashd` and it'll do the rest. If I had to guess, I'd say it'll mine to the default address in the wallet and you'd use the CLI commands to transact with the mined coins.

**Comment by hjhart** [comment]
You can start mining by running `./src/zcashd -daemon` to run a daemoned process.

To start, it's good to see some feedback so it's good to simply run `./src/zcashd`, and make sure you get output like: 

```
Thank you for running a Zcash node!
You're helping to strengthen the network and contributing to a social good :)

You are running 8 mining threads.

Since starting this node 8 minutes, 41 seconds ago:
- You have validated 955 transactions!
- You have contributed 15.0499 Sol/s on average to the network solution rate.
- You have completed 4169 Equihash solver runs.

```

Once you've confirmed it works you can run it as a daemon.

**Comment by bitcartel** [comment]
@4815162342lost Is everything ok now?

**Comment by 4815162342lost** [comment]
@bitcartel yes, thanks, all clear now for me.
