### ISSUE TITLE
when building on vmware with ubuntu I get tar file name too long error

### ISSUE THREAD

**Issue by bharath-g** [zcash/zcash#1723]
tar: <doxygen file path.xml> : cannot open: filename too long

`
tar: libs/geometry/doc/doxy/doxygen_output/xml/structboost_1_1geometry_1_1dispatch_1_1envelope_3_01_geometry_00_01detail_1_1buffer_1_1buffered__ring__collection__tag_01_4.xml: Cannot open: File name too long
`

`
tar: Exiting with failure status due to previous errors
make: *** [/mnt/hgfs/share/code/zcash_proj/zcash/depends/work/build/x86_64-unknown-linux-gnu/boost/1_62_0-8100bd437b7/.stamp_extracted] Error 2
make: Leaving directory`/mnt/hgfs/share/code/zcash_proj/zcash/depends'
`

Is there some way to remove these doxygen files short of manually editing the makefiles?

I am building on 

`
Linux ubuntu 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
`
on vmware windows 10

**Comment by ioptio** [comment]
@bharath-g this is an old ticket from launch. Are you having issues still?

**Comment by yushizhao** [comment]
@ioptio Well, I have the same issue. Would you suggest a solution?

**Comment by daira** [comment]
Are you building on a filesystem that is shared with the host Windows? If so then that's probably the problem; use an ext4 filesystem in the VM.

**Comment by yushizhao** [comment]
@daira Yes. That solve the problem. Thank you!
