### ISSUE TITLE
Offline build option request

### ISSUE THREAD

**Issue by DAP-DarkneSS** [zcash/zcash#1725]
Hello.
I'd like to make a package for open build service (OBS) but failed because build requires wget to download something.
[   21s] Fetching native_ccache...
[   21s] /bin/sh: wget: command not found
However OBS requires 100 % offline build to make it 100 % reproducible. I any way to configure offline build? Can something be downloaded and added to sources by me not by build script?

**Comment by daira** [comment]
Duplicate of #1663.

**Comment by DAP-DarkneSS** [comment]
Sorry and thank you. I'll repack deb package so.

**Comment by daira** [comment]
No need to apologise -- deduplicating tickets makes it much easier to keep track.
