### ISSUE TITLE
Test suite fail after install

### ISSUE THREAD

**Issue by wlbentley** [zcash/zcash#1726]
Installed using instructions at: https://github.com/zcash/zcash/wiki/1.0-User-Guide

Mint Linux VM under Virtual Box: Linux Mint 17.2 64-bit

See Gist: https://gist.github.com/wlbentley/4b7cdd414924f195531854f90c8d51f1

**Comment by wlbentley** [comment]
Also with output for `./zcutil/build.sh -j$(nproc)`

See Gist: https://gist.github.com/wlbentley/4f45ffc9906f4f8391e4f0e3b4ecd4bb

**Comment by bitcartel** [comment]
@wlbentley How much memory does your VM have?  You should allocate >4GB to the VM, preferably 8GB, as creating joinsplits (zero knowledge proofs) requires around 4 GB and the tests involve creating joinsplits.

**Comment by wlbentley** [comment]
Indeed it was only 2GB. I increased it to 6GB and re-ran the first test suite. It failed again at multiple points. The Gist of the output is here: [https://gist.github.com/wlbentley/8f30761f4939d53dda7f5493f4ecd6c9](https://gist.github.com/wlbentley/8f30761f4939d53dda7f5493f4ecd6c9)

**Comment by wlbentley** [comment]
Ok. I upped the VM memory to 8192 MB (8GB) and the first test suite passed without an issue. All green. Even 6GB was not enough. Thanks.

**Comment by wlbentley** [comment]
...however, the second test suite failed, but only for `wallet_nullifiers.py`.

See this Gist for the output: https://gist.github.com/wlbentley/2bf04f8de52fe698610a181cd9a28af0

**Comment by arcalinea** [comment]
Could be a timeout failure? See #1608

**Comment by bitcartel** [comment]
@wlbentley Have you tried changing the timeout from 120 to something like 1200?  On this line here: https://github.com/zcash/zcash/blob/master/qa/rpc-tests/wallet_nullifiers.py#L30
The same would apply tothe tests wallet.py and wallet_protectcoinbase.py.  When running in a VM, the time to create a JoinSplit could be several times slower than on native hardware.

**Comment by ioptio** [comment]
Since it's been a while, let's close this issue. If you find the issue persists, feel free to re-open with answers to questions above.
