### ISSUE TITLE
Fail to compile "RPC Wallet test" with GCC 4.7.2

### ISSUE THREAD

**Issue by Zenitur** [zcash/zcash#1727]
Debian Linux 7.0 "Wheezy", x86_64 arch, GCC 4.7.2.
Build log: http://pastebin.com/LWXFL8YH

**Comment by ITH4Coinomia** [comment]
@Zenitur Did you tested "RPC Wallet" on VM?

**Comment by daira** [comment]
GCC 4.7.2 is not supported; please use GCC 4.9 or later.
