### ISSUE TITLE
Add mining statistics to `getmininginfo`

### ISSUE THREAD

**Issue by amiller** [zcash/zcash#1730]
`zcashd -gen` (without the `-daemon` info) shows the mining performance in solutions per second on the splash/metrics screen, but this information can't be accessed through the API. It seems like this would be a good fit for an extra field in the `getmininginfo` API response

**Comment by str4d** [comment]
I already have a PR open for this: #1642 ☺️

**Comment by str4d** [comment]
Closed by #1642.
