### ISSUE TITLE
fetch-params doesn't delete lockfile

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#1731]
I got this error...

```
$ zcash-fetch-params
/usr/bin/zcash-fetch-params: line 50: //tmp/fetch_params.lock: Permission denied flock: 200: Bad file descriptor
Only one instance of fetch-params.sh can be run at a time.
```

...because I set up Zcash as one user, then wanted to set it up again under a different user. `fetch-params.sh` doesn't delete the lock file, and so until the system reboots it sits there being inaccessible by other users.

**Comment by ageis** [comment]
Yup, this is an issue that I'm aware of, but it seemed like a bit of an edge case that people would be fetching params with all different users. rm'ing the lock at the end of the script should be sufficient.
