### ISSUE TITLE
Measure potential performance improvement from -O2 or -O3 optimization and enable where/if justified

### ISSUE THREAD

**Issue by hazinstore** [zcash/zcash#1733]
I've been trying to build an optimized version of this and you guys are defining O1 in a handful of places where it really doesn't belong.
I read up on issues #1170 #1064 and #1168 and feel your reasons for going to O1 are illegitimate.
O flags should default to 1 for debug builds and 2 for release builds, that's been the default for about 10 years now.  Doing this will prevent build conflicts and improve overall performance.

If you're uncomfortable with the optimizations the compiler is making, please specify specifically what it is you are uncomfortable with, or switch over to a different compiler that doesn't do that.  If you don't know what it's doing, then you don't have any business being uncomfortable.

It's bad practice to override user preference and both O2 and O3 each make processor specific optimizations that yield an order of magnitude speed up on some of these calcs.

If you want to verify the hardening then use an external toolkit to verify because none of you is actually reading the ASM output to see exactly what is going on anyways.  That means you're moving forward on your subjective assumptions rather than hard data.  In the meantime you're burning CPU cycles and consuming RAM meaninglessly.

I'll fix this in my fork and submit a PR if there is any chance of getting it accepted.

**Comment by daira** [comment]
I am opposed to changing this until we have had time to actually measure the performance impact and review in more detail the optimizations involved, or unless more substantive technical arguments are presented for -O2. Assertions that we "don't have any business" making this engineering decision are not technical arguments.

It is simply not true that -O2 ever has an "order of magnitude" advantage over -O1, except in trivial dead-code situations that don't occur in real programs.

We are already verifying that the available hardening is enabled.

**Comment by nathan-at-least** [comment]
@daira and @hazinstore, we're moving this into 1.0.[soon] which means we'd like to do it soonish, but it's not scheduled for the next (1.0.5) release.

The next step is to set up performance comparisons for different flags.

**Comment by nathan-at-least** [comment]
Also, personally, I'm not clear on which portions of code use which optimizations flags. Can someone summarize here?

**Comment by nuttycom** [comment]
We now build with -O3 as a matter of course.
