### ISSUE TITLE
My z_address are invalid

### ISSUE THREAD

**Issue by skrew** [zcash/zcash#1736]
Hi,

Followed the 1.0 wiki guide, i generated an z-address and mining with this address on a pool.
BUT:
- zchain block explorer tell my address are invalid.
- Pool sended 2 payments but got nothing in my wallet. (more than 24h now)
- When i try to add my z-address to suprnova, he tell me invalid address.

How it's possible to have an invalid address ?
What i can do for checking my address ?

Some infos:

getwalletinfo:

```
{
    "walletversion" : 60000,
    "balance" : 0.00000000,
    "unconfirmed_balance" : 0.00000000,
    "immature_balance" : 0.00000000,
    "txcount" : 0,
    "keypoololdest" : 1477672285,
    "keypoolsize" : 107
}
```

getinfo:

```
{
    "version" : 1000050,
    "protocolversion" : 170002,
    "walletversion" : 60000,
    "balance" : 0.00000000,
    "blocks" : 1851,
    "timeoffset" : 0,
    "connections" : 15,
    "proxy" : "",
    "difficulty" : 59130.30273076,
    "testnet" : false,
    "keypoololdest" : 1477672285,
    "keypoolsize" : 107,
    "paytxfee" : 0.00000000,
    "relayfee" : 0.00005000,
    "errors" : ""
}
```

**Comment by bitcartel** [comment]
How did you create your address?
./zcash-cli getnewaddress (which gives you a transparent address)
or
./zcash-cli z_getnewaddress (which gives you a private z address)

**Comment by skrew** [comment]
I followed the guide: https://github.com/zcash/zcash/wiki/1.0-User-Guide

```./src/zcash-cli z_getnewaddress```

**Comment by bitcartel** [comment]
Please check with suprnova.  From the forums it seems most pools will only accept transparent addresses and not private z addresses.

**Comment by skrew** [comment]
Ok i will test, but i stll had lost 2 payments mined on the pool with my z-address... (or coinsforall.io are scam ?)

zcg71awSNV8pWDrJP9NmAwotSPeENSmgYjqCVvHypSJHACwdru1MfcT8pXMmUVbwub6W1jUQQDwU4Zjz1nY4jUi84syJqd6

**Comment by sammy007** [comment]
zchain will not show you address until there is balance.

**Comment by buzztiaan** [comment]
explorer.zcha.in wont show any z_ addresses balances or transaction because its running without txindex

**Comment by skrew** [comment]
Ok got payment, all look goods...
BTW, a better explanation for t-address and z-address will be a good idea for noobs like me.

Thanks
