### ISSUE TITLE
could not load param file sprout-verifying.key

### ISSUE THREAD

**Issue by rebroad** [zcash/zcash#1738]
Have just compiled zcash/master and it fails at run time with:-

```
************************
EXCEPTION: St13runtime_error       
could not load param file at /home/rebroad/.zcash-params/sprout-verifying.key       
Zcash in AppInit()       
```

I don't have a .zcash-params directory - what ought to have created this?

**Comment by ebfull** [comment]
`zcash-fetch-params` or `./zcutil/fetch-params.sh` depending on whether you installed via the Debian package or compiled from source, respectively. Sorry for the confusion!
