### ISSUE TITLE
[q] Adding new miners from the competition

### ISSUE THREAD

**Issue by breznak** [zcash/zcash#1739]
https://zcashminers.org/submissions 

or already working from eg. https://github.com/nicehash/nheqminer

**Comment by sammy007** [comment]
AFAIK nothing unique implemented in this miner, it uses MIT licensed solvers.

**Comment by str4d** [comment]
Yes, we will consider PRs to merge any solver from the Miner Challenge. IMHO the more solver options there are inside `zcashd`, the more likely that a user can quickly find something that works well for their setup.
