### ISSUE TITLE
DNS peer discovery never comes back with peers

### ISSUE THREAD

**Issue by buzztiaan** [zcash/zcash#1740]
It seems something is lacking in peer discovery

 $ dig dnsseed.z.cash

only returns the mainnet.z.cash (which is getting highly overflooded now) , 0 of the other nodes

**Comment by str4d** [comment]
@buzztiaan I have just executed this myself, and received the expected response (a list of 25 IPs). Could you try again and see if the issue has resolved itself? If it still doesn't work for you, it may be an issue with your configured DNS provider caching old non-working results (as for the first few hours, dnsseed.z.cash *did* only return mainnet.z.cash).

**Comment by buzztiaan** [comment]
Ah yep, both google (8.8.8.8) and opendns (4.2.2.2) have this cached and indeed only report mainnet. 

Maybe the TTL is a bit high?

Thanks

**Comment by str4d** [comment]
@ageis is there something we can configure in either the DNS seeder or the DNS front-end to decrease the TTL?

**Comment by ageis** [comment]
Default TTL is 300 seconds which should be ok. One thing I can try is flushing the cache through this tool. https://developers.google.com/speed/public-dns/cache

**Comment by buzztiaan** [comment]
Yez, google now reports a whole lot more of em. Opendns still mainnet.z only.

I'll close it for now

**Comment by ageis** [comment]
That seems to have fixed the problem. Just cleared the cache at OpenDNS too via this tool: https://cachecheck.opendns.com/

**Comment by buzztiaan** [comment]
@4.2.2.2 now also returns a lot more peers :)
