### ISSUE TITLE
I enter z and t address commands and get error, couldn't connect to server. why? 

### ISSUE THREAD

**Issue by haegon123** [zcash/zcash#1743]
i run the t and z wallet address commands and get "error: couldn't connect to server"              
 Please advise on how to fix this.                                                                                                    

My config file in .zcash folder shows: addnode=mainnet.z.cash; rpcuser=username; rpcpassword= (string of letters and numbers); gen=1; genproclimit=1﻿

**Comment by vinniejames** [comment]
do any other commands work for you? what system are you on?

**Comment by bitcartel** [comment]
@hegon123 Are you able to connect now?  If so, please let us know so we can close this ticket.  Thanks.

**Comment by arcalinea** [comment]
Please reopen this issue if there's an update, closed since it's been > 2 weeks.
