### ISSUE TITLE
zcash address issuer

### ISSUE THREAD

**Issue by toomany008** [zcash/zcash#1751]
I use zcash-cli getnewaddress   get the addrress 
and use dumpprivkey  to get private key 
but  I use  h160(public(privatekey))+checksum   get the address does not same as address that output by"zcash-cli getnewaddress"

**Comment by str4d** [comment]
Remember that you need to include the two-byte prefix before applying base58 encoding. Zcash address use a two-byte prefix.

**Comment by toomany008** [comment]
@str4d of course I  add the prefix , is it t1?

**Comment by Voluntary-zcash** [comment]
Check out section 5.6 https://github.com/zcash/zips/blob/master/protocol/protocol.pdf

**Comment by bitcartel** [comment]
For mainnet, use the byte prefix 0x1C, 0xB8 which will generate the 't1'.  See page 25, section 5.6.1 of protocol linked above.
