### ISSUE TITLE
Disable "height in coinbase" rule for genesis block

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#1753]
Since Bitcoin block version 2, the coinbase transaction must contain the block height. When we updated the consensus rules to only allow a minimum block version of 4, we regenerated the genesis block to update its `nVersion`, but forgot to also update its coinbase transaction to include a height. For some reason, the standard launch path does not enforce this for the genesis block, which is why it was missed (I am still identifying the issue). However, `-reindex` *does* enforce it for all blocks, which is why several users have reported that `-reindex` hangs on `Activating best chain...`.

The fix is to relax the consensus rule to only apply if `nHeight > 0`. This will not cause any forks because any fork would require a new genesis block, which would therefore be a completely separate blockchain.

**Comment by str4d** [comment]
The disparity is caused by the fact that the default codepath calls `InitBlockIndex()`, which loads the genesis block directly without calling `ContextualCheckBlock()`, while when reindexing the genesis block is loaded from disk using `LoadExternalBlockFile()` which performs all checks.

**Comment by bitcartel** [comment]
The problem can be seen in debug.log when trying to reindex.
```
2016-11-02 04:56:40 Waiting for genesis block to be imported...
2016-11-02 04:56:40 Reindexing block file blk00000.dat...
2016-11-02 04:56:40 ERROR: ContextualCheckBlock: block height mismatch in coinbase
2016-11-02 04:56:40 ERROR: ProcessNewBlock: AcceptBlock FAILED
2016-11-02 04:56:40 ERROR: AcceptBlockHeader: prev block invalid
2016-11-02 04:56:40 ERROR: ProcessNewBlock: AcceptBlock FAILED
2016-11-02 04:56:40 Reindexing finished
```

**Comment by ebfull** [comment]
I reviewed this before but I guess my comment never made it through. ACK
