### ISSUE TITLE
compile error during running  build.sh

### ISSUE THREAD

**Issue by makeupforever** [zcash/zcash#1764]
Hi，I got a error during running "./zcutil/build.sh -j$(nproc)",
////////////////////////// /error info ///////////////////////////////////////////////////
libbitcoin_wallet.a(libbitcoin_wallet_a-zcbenchmarks.o): In function `benchmark_verify_equihash()':
/home/bobo/zcash/src/zcbenchmarks.cpp:160: undefined reference to `CheckEquihashSolution(CBlockHeader const*, CChainParams const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [test/test_bitcoin] error 1
//////////////////////////////////////////////////////////////////////////////
My OS is Centos 7 running in VMware10.

Could someone help me to deal with this problem? 
Thanks very much!

**Comment by ITH4Coinomia** [comment]
@makeupforever Actually I don't have zcash binaries for Centos 7, Did you run zcash-fetch-params as? it must be the same user that will run zcashd, on a login shell (if you are root, switch to one with "sudo su - USERNAME-I-WILL-RUN-ZCASHD-AS")

**Comment by arcalinea** [comment]
As @ITH4Coinomia mentioned, this looks like you might not have run the fetch-params script: `./zcutil/fetch-params.sh`
Have you tried this with the most recent version, following the build instructions in the [1.0 User Guide](https://github.com/zcash/zcash/wiki/1.0-User-Guide)?
Closing unless there are updates--if so, please feel free to re-open.
