### ISSUE TITLE
Debian fetch error

### ISSUE THREAD

**Issue by rugk** [zcash/zcash#1768]
Just as [this user](https://github.com/zcash/zcash/issues/1672#issuecomment-257122375) I got this error when using the [Debian binary packages](https://github.com/zcash/zcash/wiki/Debian-binary-packages):

> W: Failed to fetch https://apt.z.cash/dists/jessie/Release Unable to find expected entry 'main/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)

Debian Jessie x64

It would be nice if you could fix this.

**Comment by ageis** [comment]
Hi @rugk. Please add [arch=amd64] to your sources.list file, e.g.
`deb [arch=amd64] https://apt.z.cash/ jessie main`
That will fix the problem. I will update the guide to reflect this.
