### ISSUE TITLE
rpc call getblocktemplate returns error messages referring to Bitcoin instead of Zcash

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#1773]
if (vNodes.empty())
        throw JSONRPCError(RPC_CLIENT_NOT_CONNECTED, "Bitcoin is not connected!");

    if (IsInitialBlockDownload())
        throw JSONRPCError(RPC_CLIENT_IN_INITIAL_DOWNLOAD, "Bitcoin is downloading blocks...");

**Comment by daira** [comment]
This might have been fixed by now, I'm not sure.

**Comment by daira** [comment]
Yes it was fixed by #1845.
