### ISSUE TITLE
Insufficient transparent funds

### ISSUE THREAD

**Issue by sammy007** [zcash/zcash#1774]
TESTNET (private, block height 139)

`getinfo`
```
{
"balance" : 0.39000000,
"blocks" : 139
}
```

I am shielding `0.3899` from it (`- 0.0001` for tx fee). And op status is "Insufficient transparent funds, have 38950000, need 39000000”.

**Comment by ebfull** [comment]
`listunspent` please?

**Comment by sammy007** [comment]
https://gist.github.com/sammy007/d4b613ac028f61c6e47d9f53a2b51c15

**Comment by bitcartel** [comment]
What does z_gettotalbalance show?

**Comment by bitcartel** [comment]
And also z_getbalance tmD6KZMaBiCmQT1jioJqKbqApyg7BSHftZC ?

**Comment by sammy007** [comment]
`z_gettotalbalance`

```
{
    "transparent" : "1.278",
    "private" : "0.00",
    "total" : "1.278"
}
```

`z_getbalance tmD6KZMaBiCmQT1jioJqKbqApyg7BSHftZC` #=> `1.27750000` 😕

**Comment by sammy007** [comment]
I dunno if it's related somehow, I applied this patch in order to run private net:

```
diff --git a/src/chainparams.cpp b/src/chainparams.cpp
index 8691455..0c9d308 100644
--- a/src/chainparams.cpp
+++ b/src/chainparams.cpp
@@ -59,7 +59,7 @@ public:
         vAlertPubKey = ParseHex("04b7ecf0baa90495ceb4e4090f6b2fd37eec1e9c85fac68a487f3ce11589692e4a317479316ee814e066638e1db54e37a10689b70286e6315b1087b6615d179264");
         nDefaultPort = 8233;
         nMinerThreads = 0;
-        nMaxTipAge = 24 * 60 * 60;
+        nMaxTipAge = 0x7fffffff;
         nPruneAfterHeight = 100000;
         const size_t N = 200, K = 9;
         BOOST_STATIC_ASSERT(equihash_parameters_acceptable(N, K));
@@ -302,7 +302,7 @@ public:
         pchMessageStart[2] = 0x3f;
         pchMessageStart[3] = 0x5f;
         nMinerThreads = 1;
-        nMaxTipAge = 24 * 60 * 60;
+        nMaxTipAge = 0x7fffffff;
         const size_t N = 48, K = 5;
         BOOST_STATIC_ASSERT(equihash_parameters_acceptable(N, K));
         nEquihashN = N;
```

**Comment by bitcartel** [comment]
Ok I see the problem.  

I took your snippet, cleaned it up, and imported into a spreadsheet.  The total was 1.278 so the balance computation is correct.

However, the z_sendmany operation is short by 0.00050000.

Looking for this amount in the .json output I see this unspent output:

    {
        "txid" : "ff148cbe25748023359633dfdc700603d6d4f69913c920c246798fce026067e1",
        "vout" : 0,
        "address" : "tmT7UjToEpF3sqjzzQHhdPc7rdJ6StZ5vv2",
        "account" : "",
        "scriptPubKey" : "21020fcb7a4ef1b024ff0fbe85e47dc1cc3d2a7a62ada15072f9cd845a4a89ede753ac",
        "amount" : 0.00050000,
        "confirmations" : 171,
        "spendable" : true
    },

Note that the address is different from your sending address of tmD6KZMaBiCmQT1jioJqKbqApyg7BSHftZC.

So you should see the following:
z_getbalance tmD6KZMaBiCmQT1jioJqKbqApyg7BSHftZC --> 1.27750000
z_getbalance tmT7UjToEpF3sqjzzQHhdPc7rdJ6StZ5vv2 --> 0.00050000

z_gettotalbalance and getbalance returns the *total* of all yout transparent outputs, which is 1.2780000.

**Comment by sammy007** [comment]
Ah finally nailed it, I didn't notice this addy. This is prolly because I generated yet another t-address and getblocktemplate used it for some reason. Usually blocks rain to a single address.
