### ISSUE TITLE
Daemon crashes when sending from z address to multiple z addresses

### ISSUE THREAD

**Issue by etherchain-org** [zcash/zcash#1779]
I tried to send a quite large transaction from a z address to multiple z addresses. After that the daemon crashed with the following exception:

> zcashd: zcash/JoinSplit.cpp:307: libzcash::ZCProof libzcash::JoinSplitCircuit<NumInputs, NumOutputs>::prove(const boost::array<libzcash::JSInput, NumInputs>&, const boost::array<libzcash::JSOutput, NumOutputs>&, boost::array<libzcash::Note, NumOutputs>&, boost::array<boost::array<unsigned char, 601ul>, NumOutputs>&, uint256&, const uint256&, uint256&, boost::array<uint256, NumInputs>&, boost::array<uint256, NumInputs>&, boost::array<uint256, NumOutputs>&, uint64_t, uint64_t, const uint256&, bool) [with long unsigned int NumInputs = 2ul; long unsigned int NumOutputs = 2ul; uint64_t = long unsigned int]: Assertion `pb.is_satisfied()' failed.

The transaction was quite large with more than 150 recipients.

Edit: I am getting the same error when sending to just 10 recipients. Sending just to a single recipient seems to work.

**Comment by bitcartel** [comment]
@etherchain-org Please try the transaction with 1.0.1 released today; it has better error reporting around JoinSplits.

@ebfull Ping.

**Comment by etherchain-org** [comment]
All the tx were issued with version 1.0.1. Unfortunately there was no error in the application log except the crash message.

**Comment by bitcartel** [comment]
Is this a reproducible problem?  If you try to send to those 10 recipients, will it fail every time?  If you change the amounts involved does it crash?    If possible, please copy and paste the z_sendmany command you are trying to execute from the terminal (mask the zaddrs and amounts for privacy)  Thanks.

**Comment by bitcartel** [comment]
Also try running with -debug=zrpc which prints out specific information related to z_sendmany to debug.log.

**Comment by etherchain-org** [comment]
I tried firt to send to 150+ recipients which crashed the client. After that I tried with just 10 recipients and it also crashed. After that i tried it with just one recipient and it worked. Unfortunately testing is very time consuming for me as a crash deletes all information in regards to the ongoing operations and I need to recover from them manually. Ideally the status of ongoing transactions should be saved across restarts so that we can properly recover from such crashes.

**Comment by bitcartel** [comment]
Thanks.  Have you tried making a new 150+ recipient send?  Or are you now only sending with <10 recipients?

**Comment by etherchain-org** [comment]
Right now I am not doing any sends at all and try to migrate user balances over to regular t addresses. It is simply to risky to run payouts that might result in a client crash as it is impossible to recover from those crashes properly (as all the information on ongoing opid's is lost.

It would be good to have an automated test case where some blocks are mined, the mined coins are protected and after that sent to a large number of randomly generated t and z addresses.

**Comment by bitcartel** [comment]
In the z-address you were sending from, roughly how many unspent notes were at that address and how many do you think should have been used to complete the send to the 10 recipients?  e.g. do you have 1 big note e.g. 10.0 which  is sufficient to send 0.5 x 10, or do you have a bunch of smaller notes?

**Comment by etherchain-org** [comment]
Could you point me in the right direction in order to find out how many unspent notes are available for a given address?

**Comment by bitcartel** [comment]
No rpc call exists for that right now.  This would help debugging if you have time:
1. On a new clean system, install zcashd, copy wallet.dat (or export/import the zaddr key)
2. Launch and wait for node to sync. Balance for the zaddr should match that of your real node.
3. Shut down node and disconnect system from the internet
4. Launch node with debug=zrpc
5. Execute the z_sendmany
6. After crash, examine output in debug.log (this will show the unspent notes when z_sendmany invoked, and the creation of joinsplits).  If you can sanitize the output and share here or via email, that would be great.

**Comment by bitcartel** [comment]
@etherchain-org I have replicated the issue. Did you find this problem existed with 1.0.0 release or only after you started using 1.0.1 ?

**Comment by etherchain-org** [comment]
Thanks for your efforts. I did not experience the issue with 1.0.0 only with 1.0.1.
