### ISSUE TITLE
Address the Faerie gold attack from Protect/Mint operation.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#178]
Distinct from #98 which focuses on a vulnerability in the current Pour semantics, there's also a potential vulnerability when a malicious user A creates a Protect/Mint operation whose recipient is B.

Because the protection against the Pour case relies on Pour semantics, it does not protect against this Protect/Mint case.

The current "engineering hack" we prefer to protect against this is to make the canonical client simply ignore Protect/Mint coins which aren't locally generated (ie come from someone else).

**Comment by daira** [comment]
Relevant to Sapling.

**Comment by daira** [comment]
Done (see #2277).
