### ISSUE TITLE
zcashd never completes any equihash solver runs

### ISSUE THREAD

**Issue by edhardie** [zcash/zcash#1784]
Hi, I have an ubuntu machine running the debian binary packages. 

zcashd starts ok and is sucessfully validating transactions, however no matter how long I leave it running I never see any solved equihashes. 

Running a `zcash-cli zcbenchmark solveequihash 1` just to try and see it do something also causes an indefinite hang.

Has anyone else experienced similar issues? Is there a log or any debug information anyone can point me in the direction of? Thanks.

**Comment by buzztiaan** [comment]
did you set gen=1 in zcash.conf ?

**Comment by buzztiaan** [comment]
fyi there is no 'need' for the wallet to do equihash solutions, solomining is kinda pointless

if you want to mine, use a miner, if you want a wallet, use a wallet, you -can- mix functionality but its not so beneficial

**Comment by edhardie** [comment]
hey @buzztiaan, yeah `gen=1` is set in zcash.conf. Understand what you're saying about solo mining, I'm just experiementing at the moment trying to get an idea of what kind of hashrate my hardware can achieve, but at the moment I'm solidly stuck on 0;

**Comment by buzztiaan** [comment]
not sure if zcbenchmark uses actual diff from network, if so, it might take nearly infinite time to hit it

if you want to analyze solutionrate for mining, use a miner's benchmarking, not the wallets ;) its not optimized or fast in general

**Comment by buzztiaan** [comment]
mind closing the 'issue' when its not relevant anymore?

**Comment by bitcartel** [comment]
Let's not close this.  @edhardie Yes I have seen this on a laptop before, where the benchmark hung.  What version OS and what cpu are you running?

**Comment by buzztiaan** [comment]
@bitcartel; could you say if the benchmark uses current network diff?

**Comment by Zwilla** [comment]
Debian compiled yesterday:

/root/zcash/src/ ; ./zcash-cli zcbenchmark solveequihash 10 ..
[
    {
        "runningtime" : 119.12624600
    },
    {
        "runningtime" : 93.58569300
    },
    {
        "runningtime" : 20.43742500
    },
    {
        "runningtime" : 131.10978600
    },
    {
        "runningtime" : 93.43080700
    },
    {
        "runningtime" : 18.59975900
    },
    {
        "runningtime" : 94.28605400
    },
    {
        "runningtime" : 44.84501800
    },
    {
        "runningtime" : 93.76968400
    },
    {
        "runningtime" : 69.08444900
    }
]

All works normal here!

**Comment by arcalinea** [comment]
You could try setting 'equihashsolver=tromp' in zcash.conf, this is faster than using the default miner (although it is not as well reviewed). This might speed up your equihash solution rate. 

Let us know the results if you've tried this with a more recent version of the software.

**Comment by daira** [comment]
Also note that mining is initially suspended when a node is started until it has caught up with the current chain (#2139), which can take a long time. That would not explain ``zcash-cli zcbenchmark solveequihash 1`` hanging, though.

**Comment by edhardie** [comment]
Hi all, oops I've not been paying attention to my notifications, I apologise. 

@bitcartel if I remember correctly it was Ubuntu 14.04 (VM) running v1.0. That machine is long gone and I'm not in a position to try later versions of the software so I'm going to close this ticket. I never did manage to get it working though so feel free to re-open if you think this is related to a wider issue.

Once again, sorry for not responding & thanks everyone who tried to help.
