### ISSUE TITLE
Add rpc call to shield multiple taddrs to a zaddr

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#1785]
Add new call, a variant of z_sendmany, to allow user to sweep utxos from multple taddrs to a zaddr.

Brainstorming:
`z_shieldmany zaddr memo` --> take all available utxos, subject to tx size limits, and send them to a zaddr.
`z_shield taddr zaddr memo` --> take all available utxos from a taddr and send them to a zaddr.  This differs from z_sendmany as you don't have to specify an amount.  Fee will be auto deducted from funds sent to zaddr.

**Comment by tromer** [comment]
The requested `z_shieldmany` is similar to #1811: both are about RPC for transactions with multiple t-address inputs and a z-address output.

I would argue that the requested `z_shield` is not needed, since it can be easily done by wallets using the existing RPC calls,

**Comment by bitcartel** [comment]
The name `z_shieldmany` implies some level of control over selecting which taddrs to send from, so how about:

`z_shieldunspent zaddr [minconf=1] [fee=0.0001] [memo='']`

where it grabs all available utxos, sorted by ascending order (smallest first are consumed to reduce bloat), upto tx size limit and sends them to the zaddr.

other parameters are optional, with default shown above.

**Comment by sammy007** [comment]
Please consider shield_all RPC call to shield everything with a single call.

**Comment by bitcartel** [comment]
Coinbase UTXO maturity is 100 blocks so the minconf parameter doesn't really work.  If a user is unaware of the maturity rule they will get confused as the operation will succeed for some utxos, but fail for others.  User feedback in the JSON response becomes more complicated.  It may be that we need multiple`z_shield` type calls.

**Comment by tromer** [comment]
There are two different use cases for shielding multiple UTXOs (and in particular, multiple t-addresses):
* To complete the shielding ASAP, just bunch everything into a single transaction (subject to transaction size limit)
* To minimize privacy violation by linkability, issue a separate transaction for each UTXO (ideally with randomized delays inbetween)

**Comment by str4d** [comment]
Related: #2448.

**Comment by arielgabizon** [comment]
Hey, I independently wrote something similar  https://github.com/arielgabizon/zcash/tree/simple-z_shield
The syntax is `zcash-cli z_shield x`   and it takes x transparent (currently non coin-base) value and puts it into one of your z-addrs

**Comment by mms710** [comment]
Closed by #2797
