### ISSUE TITLE
Add configure option to not compile tests

### ISSUE THREAD

**Issue by radix42** [zcash/zcash#1787]
When building for production deployment, building the tests is not needed, and on constrained build machines it can cause compilation to fail. Also on some non-linux platforms (Mac specifically), the gtest tests will not compile at all. So a flag to configure is desired to skip compiling tests.

**Comment by radix42** [comment]
Also add an option to build.sh to not build tests that is passed through to the above requested configure option.

**Comment by str4d** [comment]
@radix42 Looks like `./configure` already has the flag `--enable-tests`, which defaults to `yes`. Could you test with this and see if it is sufficient for your needs? If so, I'll expose it in `build.sh`.

**Comment by radix42** [comment]
yes, thank you, I don't know how I missed that!

**Comment by radix42** [comment]
Right now it looks broken in configure.ac from my reading of it:
```
# Check whether --enable-tests was given.
if test "${enable_tests+set}" = set; then :
  enableval=$enable_tests; use_tests=$enableval
else
  use_tests=yes
fi
```

**Comment by str4d** [comment]
I just edited `build.sh` to add `--enable-tests=no` to `./configure`, and neither `test_bitcoin` nor `zcash-gtest` were built, so AFAICT we've not managed to break that flag yet with our changes from Bitcoin 0.11.2 :stuck_out_tongue_winking_eye:

However, the dependencies subsystem would also need modification or patching to prevent Google Test itself from being built.

**Comment by radix42** [comment]
Yeah, I've already ripped Google Test out of my Mac branches in my fork, it
won't build under gcc5 on OS X and it the root of my desire for this flag.
Ethereum Core and I collectively burned a few days trying to get it build,
but to no avail, and so they tossed up their hands and ripped it out root
and branch in the patchset they sent me.

**Comment by str4d** [comment]
Okay, so regarding this ticket, the close condition will be that `build.sh` supports the `--enable-tests` flag, since that's something that will directly benefit both yourself and others in terms of compilation simplicity.

Enabling this flag to also disable building of Google Test itself is outside the scope of this ticket, because AFAICT the depends subsystem is not controlled by `./configure` (Bitcoin doesn't disable building the Boost Unit Test framework, at least in 0.11.2), and disabling it is a one-line patch for downstream:

```diff
diff --git a/depends/packages/packages.mk b/depends/packages/packages.mk
index babc159..2d63882 100644
--- a/depends/packages/packages.mk
+++ b/depends/packages/packages.mk
@@ -1,5 +1,5 @@
 zcash_packages := libsnark libgmp libsodium
-packages := boost openssl $(zcash_packages) googletest googlemock
+packages := boost openssl $(zcash_packages)
 native_packages := native_ccache
 
 wallet_packages=bdb
```

**Comment by radix42** [comment]
Thanks for the patch, but applying it is a no-op for us :-)

```
sleipnir:zcash-test djm$ patch -p1 <no-gtest-depends.patch 
patching file depends/packages/packages.mk
Reversed (or previously applied) patch detected!  Assume -R? [n] 
```
