### ISSUE TITLE
Balance 0 but not 0 in ZCash chain

### ISSUE THREAD

**Issue by MuriLOCO** [zcash/zcash#1792]
Hi, I am mining ZCash and I got some ZCash already, if I check my balance on-line with my T-Address I see some balance but when I run ./src/zcash-cli z_getbalance "$TADDR" the balance return is always 0.

I followed the guide and I am not using it to mine, just to have a Wallet. Is it a bug? Or I am doing something wrong? Thanks.

**Comment by ITH4Coinomia** [comment]
@MuriLOCO Please check the balance of both the address. Try using Normal address balance retrieval.

**Comment by MuriLOCO** [comment]
Today the command worked. I think I know why. The ZCash needs a balance of at least 0.1ZCash to show up. That is my guess.

Thank you for the answer.
