### ISSUE TITLE
Translate Zcash documentation

### ISSUE THREAD

**Issue by ITH4Coinomia** [zcash/zcash#1793]
Hey @laanwj ,

I'm willing to translate zcash strings on transifex. Please let me know the zcash transifex link so that I can able to translate Zcash in our local language: Hindi(hi) .

Cheers,
@ITH4Coinomia

**Comment by laanwj** [comment]
I have the slight suspicion that you're highlighting the wrong person.

**Comment by ITH4Coinomia** [comment]
@laanwj Why? 
Actually ".tx" folder is contributed by @laanwj and that's why I contacted you.

**Comment by zookozcash** [comment]
@laanwj: are there docs in that folder that are shared between Bitcoin core and Zcash and you would want them to get translated into Hindi?

**Comment by ITH4Coinomia** [comment]
@laanwj I'm up for spanish Language also! If possible, Please ping the right person here itself.

**Comment by laanwj** [comment]
I really don't know what the zcash transifex URL is, nor who is in charge of translations of zcash. That configuration was likely copied directly from bitcoin, and still needs to be adapted, but I'm not even sure about that.

**Comment by arcalinea** [comment]
@laanwj you're right, that configuration is copied from Bitcoin, and still needs to be adapted for zcash. I'm helping coordinate the website translations and can take the lead on looking into doing the same for documentation.

**Comment by ITH4Coinomia** [comment]
@arcalinea I'm ready to translate zcash document in spanish & french. Please let me know the transifex URL and assign me for it.

**Comment by arcalinea** [comment]
I don't think I'll be able to get the transifex configuration within the zcash repo integrated right away, but I created a Transifex project and separate repo for Zcash documentation in other languages. The 1.0 user guide and mining guide only exist in English right now, it would be great if you wanted to help translate those. 

Link to Transifex project is here: https://www.transifex.com/zcash/zcash-documents-other-assets-than-websiteblog/
zcash-docs repo: https://github.com/zcash/zcash-docs

Let me know if you have any questions or run into any issues with transifex; I'm @arcalinea on irc and rocketchat

**Comment by radix42** [comment]
Also, merely listing "Chinese" is not nearly specific enough! For instance, google has 3 different variants of chinese in the language settings for their main search page. I can ping people I know in china (mainland and taiwan) for what would be good things to list them as.
