### ISSUE TITLE
Add config flags to disable inclusion of the miner

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#1795]
We want the default zcashd binary to be as usable as possible for causal users to be able to participate in the network. Part of this includes providing usable miners in the binary, so that users can install-and-go. But some users may not want the additional bloat - in particular, mining pool operators. We should add a configuration flag to disable inclusion of the mining code at compile-time, to reduce the size of the binaries for those who don't need it.

**Comment by radix42** [comment]
Yes, we'd also very much appreciate this downstream in our Mac port. Developers including it as a fullnode in native apps very much do not want nor need the miners included in their builds.
