### ISSUE TITLE
wget: unable to resolve host address ‘z.cash’

### ISSUE THREAD

**Issue by Aaronminer1** [zcash/zcash#1799]
I get the following error while trying to install 

05:15 PM /home/zcash # ./zcutil/fetch-params.sh
Zcash - fetch-params.sh

This script will fetch the Zcash zkSNARK parameters and verify their
integrity with sha256sum.

If they already exist locally, it will exit now and do nothing else.
Retrieving: https://z.cash/downloads/sprout-proving.key
--2016-11-05 17:15:31--  https://z.cash/downloads/sprout-proving.key
Resolving z.cash (z.cash)... failed: Name or service not known.
wget: unable to resolve host address ‘z.cash’

**Comment by ageis** [comment]
hi @Aaronminer1. You are receiving old, cached DNS responses from somewhere. Can you try to clear the local DNS cache for your operating system? Which DNS nameservers are you using?

**Comment by ioptio** [comment]
Closing this due to time threshold for response from @Aaronminer1. Feel free to reopen to comment if the problem persists.
