### ISSUE TITLE
getblocktemplate broken for private testnet

### ISSUE THREAD

**Issue by FelixWeis** [zcash/zcash#1802]
On a private testnet the "initial block download" does not gets triggered.
This makes it impossible to mine or create blocks on that testnet. 

To create a private testnet start 2 isolated nodes (e.g. in a docker environment):
````
$ zcashd -testnet=1 -dnsseed=0 -printtoconsole=1 -rpcuser=user -rpcpassword=pass
````
````
$ zcashd -testnet=1 -connect=node_a -dnsseed=0 -printtoconsole=1 -rpcuser=user -rpcpassword=pass 
````

This is regression bug. It works without a problem with TAG `v1.0.0-rc2`.
``` 
$ zcash-cli -testnet=1 -rpcuser=user -rpcpassword=pass getblocktemplate
{
    "capabilities" : [
        "proposal"
    ],
    "version" : 4,
    "previousblockhash" : "01f4137ae8aced18e017119ec1a5ddd7f29a163e84e5809eb37aa6bd736b86a2",
...
````

Does not work with TAG `v1.0.1`.
``` 
$ zcash-cli -testnet=1 -rpcuser=user -rpcpassword=pass getblocktemplate
error: {"code":-10,"message":"Bitcoin is downloading blocks..."}
````

**Comment by sammy007** [comment]
Apply this patch

```
diff --git a/src/chainparams.cpp b/src/chainparams.cpp
index b6bd2df..ccfdd41 100644
--- a/src/chainparams.cpp
+++ b/src/chainparams.cpp
@@ -60,7 +60,7 @@ public:
         vAlertPubKey = ParseHex("04b7ecf0baa90495ceb4e4090f6b2fd37eec1e9c85fac68a487f3ce11589692e4a317479316ee814e066638e1db54e37a10689b70286e6315b1087b6615d179264");
         nDefaultPort = 8233;
         nMinerThreads = 0;
-        nMaxTipAge = 24 * 60 * 60;
+        nMaxTipAge = 0x7fffffff;
         nPruneAfterHeight = 100000;
         const size_t N = 200, K = 9;
         BOOST_STATIC_ASSERT(equihash_parameters_acceptable(N, K));
@@ -306,7 +306,7 @@ public:
         pchMessageStart[2] = 0x3f;
         pchMessageStart[3] = 0x5f;
         nMinerThreads = 1;
-        nMaxTipAge = 24 * 60 * 60;
+        nMaxTipAge = 0x7fffffff;
         const size_t N = 48, K = 5;
         BOOST_STATIC_ASSERT(equihash_parameters_acceptable(N, K));
         nEquihashN = N;
```

**Comment by sammy007** [comment]
Does not work for me anymore :(

**Comment by bitcartel** [comment]
@sammy007 In your `zcash.conf` did you remove `mainnet.z.cash` ?

**Comment by sammy007** [comment]
@bitcartel I have no any nodes in config. IIRC I commented out 3 additional seednodes and also:

```
onlynet=ipv4
dns=0
dnsseed=0
```

For now I just edited `src/main.cpp` and it works, but I am curious if I can do that in more clean way.

```
 bool IsInitialBlockDownload()
 {
+    return false;
```

**Comment by ioptio** [comment]
Checking in to see if this is still an issue for @sammy007

**Comment by sammy007** [comment]
I didn't test post 1.0.3 versions, running with this workaround.

**Comment by ioptio** [comment]
ok. I'm going to close this for now. Feel free to re-open if you find the problem persists and are still looking for a fix.

**Comment by sammy007** [comment]
Any commits since 1.0.3 regarding this issue? if you don't know if it fixed or not, maybe it's not ok to just blindly close it because it barely 2 weeks old?

**Comment by ioptio** [comment]
ok, understood. Wonder if @bitcartel has any follow-up then?

**Comment by bitcartel** [comment]
Sure, this can be re-opened.  I will take a look at this post 1.0.4 release.

**Comment by ioptio** [comment]
@bitcartel did you get a chance to look into this one?

**Comment by nathan-at-least** [comment]
ping @arcalinea, please check if you run into this issue when experimenting with testnet. If so, let's re-open it and fix it in an upcoming release.

I'm not sure how to test this well.

**Comment by bitcartel** [comment]
After discussion, we will in a future update loosen the restriction on nMaxTipAge for testnet, and add documentation on how to set up a private testnet.

**Comment by nathan-at-least** [comment]
Bumped from 1.0.9 due to time constraints. Added to the 'Development Infrastructure' project to ensure we follow up on it.

**Comment by nuttycom** [comment]
Private testnets are recommended to be set up using https://github.com/zcash-hackworks/zcash-testnet-in-a-box
