### ISSUE TITLE
Build fails checking for boost-system 

### ISSUE THREAD

**Issue by daschmidty** [zcash/zcash#1803]
Trying to compile on OpeneSUSE and I am encountering a build error where the configure script finds boost-system but then throws a seemingly contradictory error. I do have the boost libs installed by the system, but if I understand correctly they should also be provided by this build itself in the depends. 

`checking for boostlib >= 1.20.0... yes
checking whether the Boost::System library is available... yes
configure: error: Could not find a version of the boost_system library!
`

**Comment by radix42** [comment]
Try passing --with-boost= set to the depends/x86_64-unknown-linux-gnu directory inside your build...I have to do that when I do mingw64 builds on windows and some non-debian derived linux platforms (but not OS X)...why is a mild mystery

**Comment by daschmidty** [comment]
adding --with-boost-libdir=...depends/x86.../lib to the configure line in the build script seemed to get past that issue. I wonder if it is due to non-debian systems looking for 'lib64' by default instead of 'lib'.

Thanks for the help!
