### ISSUE TITLE
getbalance and z_getbalance $TADDR have different opinion about available funds

### ISSUE THREAD

**Issue by ocminer** [zcash/zcash#1809]
It happened to me two times already that 

getinfo and getbalance 
show different results than 
z_getbalance $TADDR

The node never had any z coins. 

z_getbalance $TADDR shows the correct amount which is higher than getbalance or getinfo

**Comment by computerlyrik** [comment]
I can confirm this.
Adding *listunspent* together gets same value as *getbalance*.
If i add all single *z_getbalance $taddr* together, i get a higher value.

Also, i do not know if it is uncommon, that in *listunspent* a $taddr appears twice.

**Comment by bitcartel** [comment]
`getinfo` and `getbalance` return the balance of utxos across all taddrs, whereas `z_getbalance taddr` shows the balance for just one taddr.

Another user in #1774 had a similar issue but it tourned out that one single utxo had a different address from all the other utxos.

If this is still an issue, please advise and post any output if possible.

**Comment by computerlyrik** [comment]
Not an issue anymore on v1.0.3-g26fb4db testing one address.
