### ISSUE TITLE
Document security implications of using SHA-256 compression rather than full hash function.

### ISSUE THREAD

**Issue by daira** [zcash/zcash#181]
https://github.com/Electric-Coin-Company/zerocashd/blob/095fa640c858f4782ad30f7cb46b6338c84670ce/src/libzerocash/utils/sha256.cpp#L114

I think this is secure only if the input is always less than one block.

**Comment by defuse** [comment]
(@daira I assigned you because I noticed you got de-assigned by the org switch)

**Comment by daira** [comment]
The API is wrong for a compression function; it makes it seem as though you can hash multiple blocks even though we never actually do that, and it would be insecure if we did. Let's replace the API with a single sha256_compress function.

(Also, the comment at https://github.com/zcash/zcash/blob/095fa640c858f4782ad30f7cb46b6338c84670ce/src/libzerocash/utils/sha256.cpp#L147 is confused. There's no byte order "reversal" going on there, nor is the implementation little-endian in any meaningful sense.)
