### ISSUE TITLE
sendtoaddress cannot send to a z address

### ISSUE THREAD

**Issue by ethernomad** [zcash/zcash#1811]
`sendtoaddress` is very effective because it automatically chooses which address(es) to send from. However it cannot send to a `z` address.

`z_sendmany` can send from a `t` address to a `z`, but I have to specify from which address.

It would be great if `sendtoaddress` could send to a `z` address.

**Comment by tromer** [comment]
Worse yet, `z_sendmany` cannot consume funds from multiple addresses. Not even multiple t-addresses, which is straightforward to implement (and already done by `sendtoaddress` or `sendmany`).

Workaround until the RPC is extended: one can send the requisite funds to a new "aggregator" t-address, and then `z_sendmany` from the aggregator t-address to the destination z-address.

**Comment by daira** [comment]
Closing as duplicate of #1785.
