### ISSUE TITLE
v1.0.1 build fails on debian 8.6 x64 and ubuntu 16.0.4.1 x64

### ISSUE THREAD

**Issue by matt2hews** [zcash/zcash#1813]
When I attempt to build zcash 1.0.1, I get the error below.  I start with a fresh OS install and copy/paste the commands directly from the wiki, including apt-getting the dependencies.

libtool: compile:  /root/zcash/depends/x86_64-unknown-linux-gnu/share/../native/bin/ccache g++ -m64 -DHAVE_CONFIG_H -I. -I../src/config -I/root/zcash/depends/x86_64-unknown-linux-gnu/include -I./obj -DBUILD_BITCOIN_INTERNAL -I/root/zcash/depends/x86_64-unknown-linux-gnu/share/../include/libsnark -I/root/zcash/depends/x86_64-unknown-linux-gnu/share/../include/ -DBOOST_SPIRIT_THREADSAFE -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -std=c++11 -pipe -O1 -fwrapv -fno-strict-aliasing -Werror -g -Wformat -Wformat-security -Wstack-protector -fstack-protector-all -MT crypto/libzcashconsensus_la-equihash.lo -MD -MP -MF crypto/.deps/libzcashconsensus_la-equihash.Tpo -c crypto/equihash.cpp -fPIC -DPIC -o crypto/.libs/libzcashconsensus_la-equihash.o
{standard input}: Assembler messages:
{standard input}:61236: Warning: end of file not at end of a line; newline inserted
{standard input}:63032: Error: invalid operands (*UND* and .gcc_except_table sections) for `-'
{standard input}:63082: Error: invalid operands(.text._ZN8EquihashILj96ELj3EE15                                                    IsValidSolutionERK32crypto_generichash_blake2b_stateSt6vectorIhSaIhEE and *UND* sections) for `-'
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
Makefile:6080: recipe for target 'crypto/libzcashconsensus_la-equihash.lo' failed
make[2]: *** [crypto/libzcashconsensus_la-equihash.lo] Error 1
make[2]: Leaving directory '/root/zcash/src'
Makefile:7442: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/zcash/src'
Makefile:664: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by DooblyNoobly** [comment]
I am reporting the same problem as above (same log), have also tried v1.0.2 but that also fails.

Using VM with fresh ubuntu 16.0.4.1 x64 install

**Comment by matt2hews** [comment]
Fedora build fails also.  Log from fresh install of Fedora 24 x64 after running dnf install and subsequent commands:

[root@fedora-zcash zcash]# ./zcutil/build.sh
+++ readlink -f ./zcutil/build.sh
++ dirname /root/zcash/zcutil/build.sh
+ cd /root/zcash/zcutil/..
+ LCOV_ARG=
+ HARDENING_ARG=--enable-hardening
+ '[' x = x--enable-lcov ']'
++ pwd
+ PREFIX=/root/zcash/depends/x86_64-unknown-linux-gnu/
+ HOST=x86_64-unknown-linux-gnu
+ BUILD=x86_64-unknown-linux-gnu
+ make -C ./depends/ V=1 NO_QT=1
./zcutil/build.sh: line 38: make: command not found

**Comment by ayleph** [comment]
> make -C ./depends/ V=1 NO_QT=1 ./zcutil/build.sh: line 38: make: command not found

Your issue is different. You don't have `make` installed on your system. Install that and try again.

**Comment by matt2hews** [comment]
Yes, I recognize make is missing.  I don't plan to use Fedora; I was just testing the build process on it since the build failed on Ubuntu and Debian.  In any case, the build instructions in the wiki do not work as written, regardless of platform.

**Comment by DooblyNoobly** [comment]
Here is my terminal output. Tried v1.0.1 as per wiki and v1.0.2. Not sure how far back you want me to go:

 -Wformat-security -Wstack-protector -fstack-protector-all -MT libzcashconsensus_la-hash.lo -MD -MP -MF .deps/libzcashconsensus_la-hash.Tpo -c hash.cpp  -fPIC -DPIC -o libzcashconsensus_la-hash.o >/dev/null 2>&1
libtool: compile:  /home/logos/zcash/depends/x86_64-unknown-linux-gnu/share/../native/bin/ccache g++ -m64 -DHAVE_CONFIG_H -I. -I../src/config -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/include -I./obj -DBUILD_BITCOIN_INTERNAL -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/share/../include/libsnark -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/share/../include/ -DBOOST_SPIRIT_THREADSAFE -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -std=c++11 -pipe -O1 -fwrapv -fno-strict-aliasing -Werror -g -Wformat -Wformat-security -Wstack-protector -fstack-protector-all -MT libzcashconsensus_la-pubkey.lo -MD -MP -MF .deps/libzcashconsensus_la-pubkey.Tpo -c pubkey.cpp  -fPIC -DPIC -o libzcashconsensus_la-pubkey.o >/dev/null 2>&1
mv -f .deps/libzcashconsensus_la-hash.Tpo .deps/libzcashconsensus_la-hash.Plo
mv -f .deps/libzcashconsensus_la-pubkey.Tpo .deps/libzcashconsensus_la-pubkey.Plo
/bin/bash ../libtool  --tag=CXX   --mode=compile /home/logos/zcash/depends/x86_64-unknown-linux-gnu/share/../native/bin/ccache g++ -m64 -DHAVE_CONFIG_H -I. -I../src/config  -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/include -I./obj -DBUILD_BITCOIN_INTERNAL -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/share/../include/libsnark -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/share/../include/  -DBOOST_SPIRIT_THREADSAFE -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2  -std=c++11 -pipe -O1 -fwrapv -fno-strict-aliasing -Werror -g  -Wformat -Wformat-security -Wstack-protector -fstack-protector-all -fPIE -MT libzcashconsensus_la-uint256.lo -MD -MP -MF .deps/libzcashconsensus_la-uint256.Tpo -c -o libzcashconsensus_la-uint256.lo `test -f 'uint256.cpp' || echo './'`uint256.cpp
/bin/bash ../libtool  --tag=CXX   --mode=compile /home/logos/zcash/depends/x86_64-unknown-linux-gnu/share/../native/bin/ccache g++ -m64 -DHAVE_CONFIG_H -I. -I../src/config  -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/include -I./obj -DBUILD_BITCOIN_INTERNAL -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/share/../include/libsnark -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/share/../include/  -DBOOST_SPIRIT_THREADSAFE -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2  -std=c++11 -pipe -O1 -fwrapv -fno-strict-aliasing -Werror -g  -Wformat -Wformat-security -Wstack-protector -fstack-protector-all -fPIE -MT libzcashconsensus_la-utilstrencodings.lo -MD -MP -MF .deps/libzcashconsensus_la-utilstrencodings.Tpo -c -o libzcashconsensus_la-utilstrencodings.lo `test -f 'utilstrencodings.cpp' || echo './'`utilstrencodings.cpp
libtool: compile:  /home/logos/zcash/depends/x86_64-unknown-linux-gnu/share/../native/bin/ccache g++ -m64 -DHAVE_CONFIG_H -I. -I../src/config -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/include -I./obj -DBUILD_BITCOIN_INTERNAL -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/share/../include/libsnark -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/share/../include/ -DBOOST_SPIRIT_THREADSAFE -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -std=c++11 -pipe -O1 -fwrapv -fno-strict-aliasing -Werror -g -Wformat -Wformat-security -Wstack-protector -fstack-protector-all -MT libzcashconsensus_la-utilstrencodings.lo -MD -MP -MF .deps/libzcashconsensus_la-utilstrencodings.Tpo -c utilstrencodings.cpp  -fPIC -DPIC -o .libs/libzcashconsensus_la-utilstrencodings.o
libtool: compile:  /home/logos/zcash/depends/x86_64-unknown-linux-gnu/share/../native/bin/ccache g++ -m64 -DHAVE_CONFIG_H -I. -I../src/config -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/include -I./obj -DBUILD_BITCOIN_INTERNAL -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/share/../include/libsnark -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/share/../include/ -DBOOST_SPIRIT_THREADSAFE -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -std=c++11 -pipe -O1 -fwrapv -fno-strict-aliasing -Werror -g -Wformat -Wformat-security -Wstack-protector -fstack-protector-all -MT libzcashconsensus_la-uint256.lo -MD -MP -MF .deps/libzcashconsensus_la-uint256.Tpo -c uint256.cpp  -fPIC -DPIC -o .libs/libzcashconsensus_la-uint256.o
libtool: compile:  /home/logos/zcash/depends/x86_64-unknown-linux-gnu/share/../native/bin/ccache g++ -m64 -DHAVE_CONFIG_H -I. -I../src/config -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/include -I./obj -DBUILD_BITCOIN_INTERNAL -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/share/../include/libsnark -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/share/../include/ -DBOOST_SPIRIT_THREADSAFE -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -std=c++11 -pipe -O1 -fwrapv -fno-strict-aliasing -Werror -g -Wformat -Wformat-security -Wstack-protector -fstack-protector-all -MT libzcashconsensus_la-uint256.lo -MD -MP -MF .deps/libzcashconsensus_la-uint256.Tpo -c uint256.cpp  -fPIC -DPIC -o libzcashconsensus_la-uint256.o >/dev/null 2>&1
libtool: compile:  /home/logos/zcash/depends/x86_64-unknown-linux-gnu/share/../native/bin/ccache g++ -m64 -DHAVE_CONFIG_H -I. -I../src/config -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/include -I./obj -DBUILD_BITCOIN_INTERNAL -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/share/../include/libsnark -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/share/../include/ -DBOOST_SPIRIT_THREADSAFE -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -std=c++11 -pipe -O1 -fwrapv -fno-strict-aliasing -Werror -g -Wformat -Wformat-security -Wstack-protector -fstack-protector-all -MT libzcashconsensus_la-utilstrencodings.lo -MD -MP -MF .deps/libzcashconsensus_la-utilstrencodings.Tpo -c utilstrencodings.cpp  -fPIC -DPIC -o libzcashconsensus_la-utilstrencodings.o >/dev/null 2>&1
mv -f .deps/libzcashconsensus_la-uint256.Tpo .deps/libzcashconsensus_la-uint256.Plo
/home/logos/zcash/depends/x86_64-unknown-linux-gnu/share/../native/bin/ccache g++ -m64 -DHAVE_CONFIG_H -I. -I../src/config  -I. -I./obj -pthread -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/share/../include -I./leveldb/include -I./leveldb/helpers/memenv -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/include -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/include -I./secp256k1/include  -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/share/../include/libsnark -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/share/../include/  -DBOOST_SPIRIT_THREADSAFE -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2  -std=c++11 -pipe -O1 -fwrapv -fno-strict-aliasing -Werror -g  -Wformat -Wformat-security -Wstack-protector -fstack-protector-all -fPIE -MT zcashd-bitcoind.o -MD -MP -MF .deps/zcashd-bitcoind.Tpo -c -o zcashd-bitcoind.o `test -f 'bitcoind.cpp' || echo './'`bitcoind.cpp
mv -f .deps/libzcashconsensus_la-utilstrencodings.Tpo .deps/libzcashconsensus_la-utilstrencodings.Plo
/home/logos/zcash/depends/x86_64-unknown-linux-gnu/share/../native/bin/ccache g++ -m64 -DHAVE_CONFIG_H -I. -I../src/config  -I. -I./obj -pthread -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/share/../include -I./leveldb/include -I./leveldb/helpers/memenv -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/include -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/include -I./secp256k1/include   -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/share/../include/libsnark -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/share/../include/  -DBOOST_SPIRIT_THREADSAFE -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2  -std=c++11 -pipe -O1 -fwrapv -fno-strict-aliasing -Werror -g  -Wformat -Wformat-security -Wstack-protector -fstack-protector-all -fPIE -MT libbitcoin_server_a-sendalert.o -MD -MP -MF .deps/libbitcoin_server_a-sendalert.Tpo -c -o libbitcoin_server_a-sendalert.o `test -f 'sendalert.cpp' || echo './'`sendalert.cpp
mv -f .deps/libbitcoin_server_a-sendalert.Tpo .deps/libbitcoin_server_a-sendalert.Po
/home/logos/zcash/depends/x86_64-unknown-linux-gnu/share/../native/bin/ccache g++ -m64 -DHAVE_CONFIG_H -I. -I../src/config  -I. -I./obj -pthread -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/share/../include -I./leveldb/include -I./leveldb/helpers/memenv -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/include -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/include -I./secp256k1/include   -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/share/../include/libsnark -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/share/../include/  -DBOOST_SPIRIT_THREADSAFE -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2  -std=c++11 -pipe -O1 -fwrapv -fno-strict-aliasing -Werror -g  -Wformat -Wformat-security -Wstack-protector -fstack-protector-all -fPIE -MT libbitcoin_server_a-addrman.o -MD -MP -MF .deps/libbitcoin_server_a-addrman.Tpo -c -o libbitcoin_server_a-addrman.o `test -f 'addrman.cpp' || echo './'`addrman.cpp
mv -f .deps/libbitcoin_server_a-addrman.Tpo .deps/libbitcoin_server_a-addrman.Po
/home/logos/zcash/depends/x86_64-unknown-linux-gnu/share/../native/bin/ccache g++ -m64 -DHAVE_CONFIG_H -I. -I../src/config  -I. -I./obj -pthread -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/share/../include -I./leveldb/include -I./leveldb/helpers/memenv -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/include -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/include -I./secp256k1/include   -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/share/../include/libsnark -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/share/../include/  -DBOOST_SPIRIT_THREADSAFE -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2  -std=c++11 -pipe -O1 -fwrapv -fno-strict-aliasing -Werror -g  -Wformat -Wformat-security -Wstack-protector -fstack-protector-all -fPIE -MT libbitcoin_server_a-alert.o -MD -MP -MF .deps/libbitcoin_server_a-alert.Tpo -c -o libbitcoin_server_a-alert.o `test -f 'alert.cpp' || echo './'`alert.cpp
mv -f .deps/libbitcoin_server_a-alert.Tpo .deps/libbitcoin_server_a-alert.Po
/home/logos/zcash/depends/x86_64-unknown-linux-gnu/share/../native/bin/ccache g++ -m64 -DHAVE_CONFIG_H -I. -I../src/config  -I. -I./obj -pthread -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/share/../include -I./leveldb/include -I./leveldb/helpers/memenv -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/include -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/include -I./secp256k1/include   -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/share/../include/libsnark -I/home/logos/zcash/depends/x86_64-unknown-linux-gnu/share/../include/  -DBOOST_SPIRIT_THREADSAFE -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2  -std=c++11 -pipe -O1 -fwrapv -fno-strict-aliasing -Werror -g  -Wformat -Wformat-security -Wstack-protector -fstack-protector-all -fPIE -MT libbitcoin_server_a-asyncrpcoperation.o -MD -MP -MF .deps/libbitcoin_server_a-asyncrpcoperation.Tpo -c -o libbitcoin_server_a-asyncrpcoperation.o `test -f 'asyncrpcoperation.cpp' || echo './'`asyncrpcoperation.cpp
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Makefile:7332: recipe for target 'zcashd-bitcoind.o' failed
make[2]: *** [zcashd-bitcoind.o] Error 4
make[2]: *** Waiting for unfinished jobs....
mv -f .deps/libbitcoin_server_a-asyncrpcoperation.Tpo .deps/libbitcoin_server_a-asyncrpcoperation.Po
make[2]: Leaving directory '/home/logos/zcash/src'
Makefile:7455: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/logos/zcash/src'
Makefile:676: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by daira** [comment]
@DooblyNoobly's issue is not the same as @matt2hews'. Please open another ticket, @DooblyNoobly.

**Comment by daira** [comment]
The issue on Fedora is also not the same as the one in the first comment.

**Comment by ioptio** [comment]
@DooblyNoobly can you try with latest version and report back please?

**Comment by ioptio** [comment]
Closing this, feel free to reopen if you find relevant issues in latest versions.
