### ISSUE TITLE
See if we can revert our upgrade to boost (assuming upstream now supports C++11 out of the box)

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#182]
In work on #163, specifically commit f3c8e5a22c54d9f7273f3c1474ba8c1591fea630, we remove some boost patches. This is based on a belief that that functionality is present in boost 1.57.0 already and the patches (which no longer apply) are needed, based on a comment from #bitcoin-dev on irc.

However, @daira and I have been unable to confirm that the same functionality that lives in the patches exists in 1.57.0.

The reason we've upgraded to 1.57.0 in the first place is to support C++11. Upstream now supports C++11, and 0.11 now has another boost patch which looks C++11 related. If this is all true, we could revert our upgrade of boost, and follow upstream directly.

**Comment by daira** [comment]
This ticket is obsolete; we have upgraded to Boost 1.62.0 which cleanly supports C++11.
