### ISSUE TITLE
Add RPC call to abort async operations

### ISSUE THREAD

**Issue by tromer** [zcash/zcash#1821]
Add an RPC call to abort ongoing asynchronous operations (e.g., `z_sendmany`) and roll back their effects on the account balance..

Asynchronous operations can take minutes (or longer, if several queued or if they require multiple JoinSplits), and users may change their mind in the meanwhile.

Proposed syntax:
`z_abortoperation (["operationid", ... ]) `
where the default is to abort all ongoing asynchronous operations.

**Comment by nuttycom** [comment]
Sapling and Orchard have improved proving times sufficiently that this is no longer really necessary. This can be reopened if someone needs it.
