### ISSUE TITLE
error: {"code":-5,"message":"Invalid Bitcoin address: t1NKV6xngyBKcYPmkkntdp2weNjLnyjh4Bd"}

### ISSUE THREAD

**Issue by nisang** [zcash/zcash#1826]
#### 1.
`zcash-cli listunspent`

#### 2.
 `zcash-cli createrawtransaction '[{"txid":"51affea57cbf5b272d82a8be82ae181beb70263fa81665aece388dd818ec4a8b","vout":0}]' '{"t1NKV6xngyBKcYPmkkntdp2weNjLnyjh4Bd":0.01}'`

error: {"code":-5,"message":"Invalid Bitcoin address: t1NKV6xngyBKcYPmkkntdp2weNjLnyjh4Bd"}
#### 3.why
bug or it is my error operate

**Comment by ioptio** [comment]
Hi @nisang are you still having issues with `createrawtransaction`?

**Comment by ioptio** [comment]
Closing this since no response for a few months. Feel free to re-open if this still poses a problem.
