### ISSUE TITLE
Update libsnark include paths for cleaner installation.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#183]
Currently libsnark expects application code to include either ``<libsnark/...>`` or ``<gadgetlib1/...>``. However, in the source code ``gadgetlib1`` is a subdirectory of ``libsnark``, so both the parent directory of ``libsnark`` and the ``libsnark`` directory itself must be on the include path.

This breaks any installation *unless* the include path is modified when building any application on top of libsnark. The design of both autotools and bitcoin's ``./depends`` system makes detecting or modifying the include path very difficult.

Therefore, the cleanest fix here is to modify upstream ``libsnark`` so that it and its dependent applications always include gadgets as ``<libsnark/gadgetlib1/...>``.

**Comment by daira** [comment]
This is no longer relevant since we moved libsnark in-tree.

**Comment by daira** [comment]
If there is still something to do here, the ticket should be in https://github.com/zcash/libsnark/issues .
