### ISSUE TITLE
[1.0.2 ]  $ ./zcash-cli getinfo error: {"code":-1,"message":"ReserveKeyFromKeyPool(): read failed"}  

### ISSUE THREAD

**Issue by alphaaurigae** [zcash/zcash#1834]
$ ./zcash-cli getinfo
error: {"code":-1,"message":"ReserveKeyFromKeyPool(): read failed"}

compiled from source on ubuntu 16.04 , synced chain, copied wallet.dat from another machine.

Any idea what goes wrong?

**Comment by ebfull** [comment]
This seems like it is an issue with your filesystem or hardware.

**Comment by Voluntary-zcash** [comment]
Could this be due to file system permissions?

**Comment by alphaaurigae** [comment]
Could also be usererror from my side by confusing a wallet from a different client, due to a total system crash. Will check for that matter in the coming days.

**Comment by mtompkins** [comment]
Same experience. Installed precompiled with apt from: https://apt.z.cash/
Followed guide: https://www.linuxbabe.com/cryptocurrency/how-to-mine-zcash-mining-guide
v1.0.3

**Comment by arcalinea** [comment]
@mtompkins the error message you're getting is probably unrelated, this one usually occurs when you've just started up the daemon and the blockchain has not finished syncing. Did your zcash-cli command work when you tried it again after a few minutes?

And @alphaaurigae , did trying a different wallet resolve this issue?

**Comment by alphaaurigae** [comment]
As ive got this in my inbox again. I can not reproduce the error or could ever figure what got me there. There are multiple things that could have gone wrong. In worst case this was simple userfail, i eventually confused a wallet from zerocash, only explanation i have looking back.

If you experience a similar error, skip this thread and open a new issue.
