### ISSUE TITLE
Repeated hash on seeds

### ISSUE THREAD

**Issue by ITH4Coinomia** [zcash/zcash#1836]
**How can we submit a seed within infinitesimal timeframe?**

Actually hashed seeds are combined to form one number. The idea is that there is not enough time within the submission phase for any party to calculate the final hash value of all of the seeds, thus they cannot predict or influence the final random number.

In order to verify the computationally intensive process, we require a security deposit and allow challengers to demonstrate the incorrectness of a hash via an interactive binary search process.

**Comment by str4d** [comment]
I don't understand the purpose of this issue; it looks like a misplaced FAQ entry for an unrelated project.

@ITH4Coinomia please re-open this if there was a legitimate issue, and explain it if so.
