### ISSUE TITLE
Proposed Zcash scratchcard

### ISSUE THREAD

**Issue by davidhedlund** [zcash/zcash#1837]
Tokens can sometimes be used instead of money. Unlike Bitcoin, Zcash transactions are anonymous, but tokens missing only for the latter.

# Bitcoin tokens that can be cold stored in real wallets
Example of printable token papers from https://mircoin.com/
![paperwallethd](https://cloud.githubusercontent.com/assets/6416073/20242267/f629402c-a928-11e6-9d4e-55b67e857d54.jpg)

Example of plastic cards from http://prypto.com/
![giftcard](https://cloud.githubusercontent.com/assets/6416073/20240991/e505a656-a927-11e6-85fb-df14900b61cc.png)
![step2](https://cloud.githubusercontent.com/assets/6416073/20242256/781459a6-a928-11e6-9d04-016175baf020.jpg)

Example of money like token papers from unknown source:
![mike-caldwell-paper-btc-1020](https://cloud.githubusercontent.com/assets/6416073/20240836/fe2aa578-a922-11e6-8303-1be7060cade2.jpg)

# Proposed Zcash scratchcard
Zcash is the leading anonymous cryptocurrency. The [Zcash team](https://z.cash/team.html) consist of the Zcash Electric Coin Company backed up by a handful of investors.

DIY recipe:
* Make scratchcards to hide the QR code, do not use holographic seals: physical Bitcoin [Casascius was cracked in 2013](http://www.coindesk.com/defcon-hackers-crack-physical-bitcoin-casascius-coins/).
* Compatible with a regular black/white printer: Plastic card printers are not generally available, and they are quite expensive too.

**Comment by davidhedlund** [comment]
mineZcash says "I dont think they would use it, graphics are a tricky thing, a more complex logo like mine will not work well on things like letterhead and t-shirts. I know the devs pretty well, if they see your issue and want to use it I will be happy to let them "

z.cash can use this logo, but print it in black/white for fabrics.

**Comment by davidhedlund** [comment]
[mylabel:important](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aimportant%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by arcalinea** [comment]
Cool idea! Want to raise this in our forum (https://forum.z.cash) so that the wider community can see? This seems more like a community project than something directly related to the zcash codebase.

**Comment by davidhedlund** [comment]
@arcalinea Yeah, I posted it in https://forum.z.cash/t/physical-zcash-tokens-proposed/7978 at the same time.
