### ISSUE TITLE
Windows 10  sub system ubuntu error

### ISSUE THREAD

**Issue by saower** [zcash/zcash#1840]
Could it run on the Windows bash (ubuntu ) and it throw error 
zcashd: /usr/lib/x86_64-linux-gnu/libgomp.so.1 : version 'GOMP_4.0'  not found (required by zcashd)

**Comment by radix42** [comment]
```sudo apt-get install libgomp1``` its a known issue, the dependency is missing from the package definition file for the deb file, too

**Comment by ITH4Coinomia** [comment]
@saower Try this: 
    ITH4Coinomia$ sudo apt-get install libjpeg62        # for RCurl and httr
   # NOTE: libcurl4-ssl-dev may also be installed at 

    # http://community.linuxmint.com/software/view/lbcurl4-openssl-dev.
    # This is noted in case it’s not available in the default repos.
    $ sudo apt-get install libcurl4-ssl-dev  # for RCurl and httr
    $ sudo sh -c ‘echo “deb http://cran.rstudio.com/bin/linux/ubuntu precise/” >> /etc/apt/sources.list’

   # The  following step did not work for me, but I think it's a gpg config problem which I haven't gotten to.

    $ sudo apt-key adv –keyserver keyserver.ubuntu.com –recv-keys E084DAB9
    $ sudo apt-get install r-base-dev libjpeg-dev libpng12-dev

**Comment by saower** [comment]
thanks

**Comment by arcalinea** [comment]
@saower did the suggestions @ITH4Coinomia made work?

**Comment by arcalinea** [comment]
Closing this issue--feel free to re-open if there are updates.
