### ISSUE TITLE
Zcash 1.0 "Sprout" Guide lacks build testing instructions

### ISSUE THREAD

**Issue by noloader** [zcash/zcash#1843]
My apologies for this issue. My instinct tells me there's a better place for it, but I don't think the users forums is it.

The [Zcash 1.0 "Sprout" Guide](https://github.com/zcash/zcash/wiki/1.0-User-Guide) lacks build testing instructions. It would be helpful to have a README in the `qa/` folder. It would also be helpful to add a section in the [Zcash 1.0 "Sprout" Guide](https://github.com/zcash/zcash/wiki/1.0-User-Guide). Tell us how to test things once `./build.sh` completes.

My apologies if the instructions exist and I missed them.

**Comment by arcalinea** [comment]
Thanks for opening this, it looks like our Beta Guide included build testing instructions, but that section didn't make it into the Sprout Guide. I'll update.
