### ISSUE TITLE
Debian start up guide assumes sudo is installed 

### ISSUE THREAD

**Issue by cinnamoncoin** [zcash/zcash#1844]
Just a small suggestion here Kevin or whoever is maintaining...

Install notes for debian may not work , i just created a few new 64 bit debian machines in virtual  box and I had to install sudo (it does not come installed !!)
so a reall newb may have trouble..

maybe before your checkout section add some directions like this

Switch to root user by typing this command in terminal
> su
then enter your root password as prompted, 

should change your system prompt 

to install sudo type in terminal:

>apt-get install sudo

Then add user assume your user name is xx
>adduser xx sudo

**Comment by arcalinea** [comment]
Thanks, I added a note on troubleshooting and linked to this issue on the Debian guide.
