### ISSUE TITLE
Change install guide to copy zcash and zcash-cli to /usr/local/bin

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#1850]
Instructions can then refer to `zcashd` and `zcash-cli` instead of having to use the `./src/` prefix as in `./src/zcashd` and `./src/zcash-cli`.

Also means the instructions will match usage when installing from the debian package, where `zcashd` and `zcash-cli` are added to a location in a user's default path.

**Comment by str4d** [comment]
Once we finish #58, users should be able to achieve this by default with `make install`.
