### ISSUE TITLE
How to backup an existing wallet

### ISSUE THREAD

**Issue by lpellegr** [zcash/zcash#1852]
I have read the explanations on the Wiki pages. However, it is not clear for me how a wallet is created and how to backup, import and use it with a new installation. Adding such information in the Wiki would be I think valuable to many people.

**Comment by computerlyrik** [comment]
`zcash-cli dumpwallet filename`

with zcashd running and started up completely

**Comment by bitcartel** [comment]
@lpellegr To back-up all your keys, for both transparent and private z addresses, please use: `zcash-cli z_exportwallet filename`

**Comment by lpellegr** [comment]
@computerlyrik I get the following error when I try to execute your command:

```
./zcash-cli dumpwallet mywallet
error: couldn't connect to server
```

@bitcartel Same with your command:

```
./zcash-cli help z_exportwallet mywallet
error: couldn't connect to server
```

My client version:

```
$ ./zcash-cli --version
Zcash RPC client version v1.0.2
```

Is there something wrong?

**Comment by computerlyrik** [comment]
@lpellegr, please check:

> with zcashd running and started up completely.

**Comment by lpellegr** [comment]
@computerlyrik Thank you for your help but I still get this message if I try to backup just after zcashd is started:

```
./src/zcash-cli dumpwallet mywallet
error: {"code":-28,"message":"Verifying blocks..."}
```

Also, let's say that I have started to work with _zcashd_, then switched to _nheqminer_ for instance. 

Is there a common way to backup my wallet when zcashd is not used? should I stop my "exotic" miner, relaunch _zcashd_ and use _zcash_cli_?

**Comment by computerlyrik** [comment]
just wait.

Monitor your zcashd output.
Please, keep reading. 

It will tell you when it is `Done loading`

And get familiar with cryptocurrencies before doing something stupid.

**Comment by ebfull** [comment]
@computerlyrik Please read our [code of conduct](https://github.com/zcash/zcash/blob/master/code_of_conduct.md), there's no need to talk to other users like that!

**Comment by ioptio** [comment]
@lpellegr try the above commands again after zcashd is finished syncing. I'm closing this for now but if you are still having issues, feel free to re-open to comment.

**Comment by geekmichael** [comment]
To make it simple: 
`zcashd -exportdir=/tmp/zcash-backup -daemon`
Wait 2-5 seconds, then run this command:
`zcash/src/zcash-cli dumpwallet "myzcashwallet"`
