### ISSUE TITLE
Handle transparent change from z_sendmany which is considered dust

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#1854]
Currently when using z_sendmany to send from a taddr (assume non-coinbase utxos) any change is sent to a new taddr.  However, this change may be small e.g. 0.00000001 which would be considered dust, and thereby cause the transaction to be rejected as non-standard. e.g. "error code 64: dust"

Currently, the dust threshold with a minrelaytxfee of 5000 is 2730.  There is proposed patch to restore minrelaytxfee back to 1000 (this is the same as what upstream is using).  The result is that the dust threshold will become 546.

Currently,when zcash is creating a pure taddr transaction with upstream rpc calls, any change which would be considered dust is increased until it becomes a standard tx output.  This is achived by reducing the amount a recipient receives while increasing the change amount: http://bitcoin.stackexchange.com/questions/39344/how-does-bitcoin-cores-coin-selection-prevent-change-to-be-a-dust-output

Update after meeting:
- We should try to select as input, available utxos, sorted by smallest in value first, to add to the change output until it is above the dust threshold.
- If this is not possible return an appropriate error to the user.

**Comment by daira** [comment]
I would like to entirely switch off "dust" checks. I think they are useless and counterproductive in Zcash, because it simply is not valid to use only public amounts to decide what transactions get prioritised.
