### ISSUE TITLE
Re-enable HTTP persistent connections (keep-alive) for RPC

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#1856]
The rpckeepalive option and accepting HTTP keep-alive connection were disabled by PR #1847 to resolve ticket #1680.

When the RPC networking layer is ready to support persistent connections, we should re-enable the option.

**Comment by daira** [comment]
See also #1593, which may be a blocker for this.

**Comment by nathan-at-least** [comment]
Because #1593 is quite invasive, we want to ensure its necessary, so first step is to see if any users would benefit from having long-poll re-enabled, and also seeing if there are alternative solutions for those users and seeing how they stack up with a libevent refactor.

**Comment by bitcartel** [comment]
@str4d Merging libevent will close this ticket, right?  In that PR there is no mention of rpckeepalive.

**Comment by str4d** [comment]
@bitcartel it will close it in the same fashion as upstream did: the libevent PR reverts our commit that disabled `rpckeepalive`, and then applies upstream changes.

**Comment by daira** [comment]
@str4d was this fixed by merging #2176?

**Comment by str4d** [comment]
@daira yes inasmuch as it was fixed upstream: https://github.com/bitcoin/bitcoin/pull/5677 mentions that it avoids https://github.com/bitcoin/bitcoin/pull/5655 (which added `-rpckeepalive`).

**Comment by str4d** [comment]
More specifically, we are relying on upstream's assertion that migrating to libevent solved the problem that they added `-rpckeepalive` to address.
