### ISSUE TITLE
Increase priority of transactions involving joinsplits

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#1857]
Related to #1855 and #1851.

One factor the built-in miner uses to select mempool transactions is to sort by priority, where priority is calculated in CTransaction::ComputePriority() and used here: https://github.com/zcash/zcash/blob/master/src/miner.cpp#L214

To ensure that transactions involving joinsplits (which are large in size) are mined in a timely fashion, we may want to consider adjusting the priority algorithm to include joinsplits as a factor.

**Comment by zookozcash** [comment]
Proposal from today's engineering meeting:

* If your transaction has > 0 JoinSplits in it, then add `joinsplit_priority_boost` to your priority. `joinsplit_priority_boost` is equal to `1,000,000,000 * fee_per_kilobyte`.
* change DEFAULT_BLOCK_MAX_SIZE from 750 KB to 2 MB
* change DEFAULT_BLOCK_PRIORITY_SIZE from 50 KB to 1 MB

**Comment by zookozcash** [comment]
We're going to split the first bullet point from https://github.com/zcash/zcash//issues/1857#issuecomment-263419605 into a separate ticket and PR from the other two.

**Comment by nathan-at-least** [comment]
Zooko's comment https://github.com/zcash/zcash/issues/1857#issuecomment-263419605 describes our short term goal. Here's our rationale:

One of the few kinds of "transaction prioritization policy" we plan to reinforce are those that promote use of JoinSplits (thus improving systemic privacy).

In a purely fee-per-kb regime, transactions with JS would require much larger absolute fees to compete with non-JS txns. Our plan to address this long term is to have some kind of dual bandwidth-accounting for the two categories of transactions, to remove (some of the) contention between the two kinds of transactions.

Zooko's comment is the first step in that direction, by altering the default mining policy. Note this is not a consensus rule change.
