### ISSUE TITLE
watch-only does not work

### ISSUE THREAD

**Issue by feeleep75** [zcash/zcash#1860]
Hi,

I imported address as watch-only and it seems to be imported correctly (at least there is no error message) however transactions are not being displayed with ```listtransactions "" 10 0 true``` or ```listsinceblock```

**Comment by ioptio** [comment]
I have not personally tried importing watch-only addresses. Can you clarify whether this is a t-addr or z-addr? Watch only z-addrs are not supported, yet.

**Comment by str4d** [comment]
I have just tried a watch-only t-addr, and it works fine for me (in 1.0.3, but we haven't changed anything relating to them).

**Comment by str4d** [comment]
(If it's relevant, I used `zcash-cli importaddress t1.....`)

**Comment by ioptio** [comment]
Hey, @feeleep75 does the above suggestion work for you?

**Comment by ioptio** [comment]
I'm going to close this for now. Feel free to reopen if the issue persists.
