### ISSUE TITLE
How to send zcashcoin to my TADDR in Poloniex

### ISSUE THREAD

**Issue by solhof6** [zcash/zcash#1861]
I find a difficulty to do this by TADDR and ZADDR

**Comment by ioptio** [comment]
Hi, have you tried looking through the payment section api? https://github.com/zcash/zcash/blob/v1.0.1/doc/payment-api.md#payment

It would be helpful to know what have you tried and how it failed so any detail on that is appreciated!

**Comment by arcalinea** [comment]
This is probably not an issue related to zcashd, with future questions about Zcash integration with other services, please see our forum: https://forum.z.cash/
