### ISSUE TITLE
Coinbase input script documentation required

### ISSUE THREAD

**Issue by sammy007** [zcash/zcash#1867]
First of all I see that It's not like in bitcoin, so please clarify.

On height 17 script is `03011100` -> length is 3 and `0111` is 17 what is `00`? Is it missing `coinbaseaux` or is it trailing `OP_0`?

```
OP_0, OP_FALSE	0	0x00	Nothing.	(empty value)	An empty array of bytes is pushed onto the stack. (This is not a no-op: an item is added to the stack.)
```

**Comment by str4d** [comment]
For miners using a coinbase generated by `zcashd`, it's unchanged from Bitcoin 0.11.2. See https://github.com/zcash/zcash/blob/master/src/miner.cpp#L354 :

```cpp
txNew.vin[0].scriptSig = CScript() << nHeight << OP_0;
```
