### ISSUE TITLE
z_dumpprivkey, z_importprivkey API missing.

### ISSUE THREAD

**Issue by miningpoolhub** [zcash/zcash#1872]
I think dumpprivkey, importprivkey API for z-addr is missing.
Please add these API.

**Comment by str4d** [comment]
@miningpoolhub They exist, but are named `z_exportkey` and `z_importkey`. There is also `z_exportwallet` and `z_importwallet` for dumping both t-addrs and z-addrs at the same time.

**Comment by miningpoolhub** [comment]
Thanks!
