### ISSUE TITLE
Make metrics output more useful for log/journal

### ISSUE THREAD

**Issue by lucaswerkmeister** [zcash/zcash#1875]
When running zcashd under systemd (cf. #1732), the metrics output has some snags:

- The ASCII art clutters the journal.
- The ANSI terminal escape codes (cursor movement) are pointless (output is not a terminal) and clutter the journal (“[59B blob data]”).
- There’s no point in telling the user to exit with Ctrl+C (it’s a service, no terminal), and the info about `showmetrics=0` doesn’t need to be repeated every interval.
- Updating the metrics every second is too frequent, I think.

Currently, I think it’s better to run zcashd with `showmetrics=0` than without it (or with `StandardOutput=null` in the service, I guess), but I think improved metrics output would be much better than none at all. Ideally, the ASCII art and cursor movement escape sequences would be automatically disabled if the output isn’t a terminal (perhaps with an option to force-enable/disable them), and there would be an option to configure the metrics interval (e. g. one minute).

**Comment by str4d** [comment]
@lucaswerkmeister I implemented it to disable metrics by default if either `printtoconsole` or `daemon` were set, but I guess neither of those are common in actual daemon setups *sigh*.

Interesting idea to leave the option of printing metrics to the logs! I'll have a think about how that would best be implemented. Agreed that if implemented, you'd only want the metrics printed far less frequently (maybe every 10 minutes) by default; the 1-second update is only necessary when it's a user-facing UI. All the UI-relevant stuff (ASCII art, escape codes etc.) would of course not be logged.

Question: do you think it would be better to log to the existing `debug.log`, or to stdout (but without refreshing)? The latter would be simpler to implement, but either is possible. We could even make it configurable, although I think we start getting a combinatorial explosion of configuration options...

**Comment by lucaswerkmeister** [comment]
(I should preface all of this by saying that I only discovered zcash today after keybase added support – I’m still learning :) )

> I implemented it to disable metrics by default if either `printtoconsole` or `daemon` were set, but I guess neither of those are common in actual daemon setups *sigh*.

I wasn’t aware of `printtoconsole`, but that also looks like a lot of data. Good to have the option, but probably too much for a default setup, I’d say. `daemon` is, at least under systemd, not what you want – it’s better to let systemd handle the forking. (Another nice systemd-ism would be to support receiving the socket from systemd – aka socket activation, though the on-demand activation part doesn’t make much sense in this case – but that’s for another issue.)

> Question: do you think it would be better to log to the existing `debug.log`, or to stdout (but without refreshing)?

For capturing the output in the systemd journal, stdout is definitely better. (You could also use the journal API – see `sd_journal_print(3)` – but that’s more work.)

**Comment by str4d** [comment]
> I wasn’t aware of printtoconsole, but that also looks like a lot of data. Good to have the option, but probably too much for a default setup, I’d say.

What that does is print Zcash logs to stdout instead of `debug.log` (same as in Bitcoin, independent of the metrics screen).

> For capturing the output in the systemd journal, stdout is definitely better.

In that case, for the purposes of this issue I'll narrow the focus to two things:

- Add a `metricsui` flag that enables/disables the UI-specific metrics output.
- Attempt to detect the absence of a TTY, and set the default for `metricsui` to false in that case.

**Comment by lucaswerkmeister** [comment]
And the interval is left for later?

**Comment by str4d** [comment]
Oh! Somehow managed to forget about the interval in the intervening 18 minutes. Amended :)

**Comment by daira** [comment]
I'm confused, I thought that showmetrics already was disabled when stdout is not connected to a terminal. Is systemd running it with output to a terminal?

**Comment by str4d** [comment]
@daira no, that has not been implemented. The change that was made was to fix the divide-by-zero by detecting if stdout was a tty, and defaulting the column count to 80 if it wasn't (and therefore would return a column count of 0).

**Comment by str4d** [comment]
@lucaswerkmeister Could you test #1878 and see if it satisfies your use case?

**Comment by lucaswerkmeister** [comment]
Yup, much better now, thanks! (Though I missed at first that I needed `-showmetrics=1` in the service file… not sure if I agree with that part, but it’s easy enough to fix.)

**Comment by str4d** [comment]
You can also just use `-showmetrics` if as an argument, FYI.

The decision here is one of expectation. For an interactive user, there's an expectation that they run the program and see something, hence `-showmetrics` defaults on. Conversely, I'd argue that metrics endlessly filling up a journal is something that most people would only expect if they explicitly enable that verbosity.
