### ISSUE TITLE
Reduce the reward halving interval ↔ increase distribution rate

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#188]
This is a proposal to increase the rate at which all coins are disbursed through mining rewards, as implemented by reducing the reward halving interval.

**Rationale** - given these assumptions:

*A1.* A goal of ZC is to promote "decentralization".
*A2.* Distributing ZC units to more participants with low barrier to entry qualifies as "decentralization".
*A3.* Over time, mining industry centralizes as big players scale up and drive smaller actors out of business due to economies of scale.
*A4.* Initially the barrier to entry for mining is low, and "most average enthusiasts" can afford this barrier.

-then impications are:

*I1.* A faster reward disbursement schedule spreads ZC units to more "low barrier to entry participants / early enthusiasts" compared to the "later high capital investment / large scale miner" population.

If there's a desire to keep the total theoretical maximum number of units fixed, the reward-per-block can also be altered along with a different halving schedule. eg: If the halving period is cut by half, but the reward per block starts twice as large, then the same total number of coins will ever be disbursed by mining rewards.

**Pros:**

If the assumptions are true and the implication follows, more ZC units will end up spread out to more early adopters and enthusiasts with a smaller investment.

**Cons:**

This is a deviation from upstream Bitcoin, so requires explanation and may have unforeseen consequences.

**Unknowns:**

If we speed up the block reward enough, the curve will reach 0 before Bitcoin, so there would be some point in time where the monetary base expansion rate goes from more than Bitcoin to less than Bitcoin, and it's not clear how this would affect the relation between the two currencies.

**Comment by zookozcash** [comment]
Let's close this ticket as "won't do it". :-)

**Comment by daira** [comment]
+1 on closing this.

**Comment by zookozcash** [comment]
not gonna do it.
