### ISSUE TITLE
upgraded to 1.0.3 and now all existing addresses and balances gone

### ISSUE THREAD

**Issue by lubah** [zcash/zcash#1882]
I cleaned the ~/.zcash directory out post successful compilation leaving only the zcash.conf and wallet.dat files.   started zcashd successfully and after running for 2 hours z_listaddresses is empty and z_gettotalbalance shows 0.00 for transparent, private, and total...   

thoughts?

**Comment by daira** [comment]
What options did you start zcashd with?

**Comment by bitcartel** [comment]
If you had z addresses, it is very strange for z_listaddresses to be empty as there is no code which ever removes a z key from the wallet.  Do you have a history of the commands you entered into your terminal?

**Comment by ebfull** [comment]
What does `getinfo` say?

**Comment by lubah** [comment]
started zcashd alone it crashed/failed the first 3 times post upgrade,  

then I cleaned out .zcash directory leaving only zcash.conf and wallet.dat  -   

yes I have all commands still in terminal
 git fetch origin
 git checkout v1.0.3
./zcutil/fetch-params.sh
./zcutil/build.sh -j$(nproc)
./src/zcashd

get info says:
~/zcash $ ./src/zcash-cli getinfo
{
    "version" : 1000350,
    "protocolversion" : 170002,
    "walletversion" : 60000,
    "balance" : 0.00000000,
    "blocks" : 12624,
    "timeoffset" : -1,
    "connections" : 10,
    "proxy" : "",
    "difficulty" : 463668.26125445,
    "testnet" : false,
    "keypoololdest" : 1479479838,
    "keypoolsize" : 101,
    "paytxfee" : 0.00000000,
    "relayfee" : 0.00001000,
    "errors" : ""
}

**Comment by bitcartel** [comment]
Did you backup your wallet.dat, before cleaning out the .zcash directory?

Are you expecting to see a transparent balance as well as a z balance?

**Comment by sammy007** [comment]
What is `zcash-cli listtransactions` output?

**Comment by lubah** [comment]
both show nothing - 

linuxmint18 ~/zcash $ ./src/zcash-cli listtransactions
[
]
linuxmint18 ~/zcash $ ./src/zcash-cli z_listaddresses
[
]

**Comment by lubah** [comment]
and yes I should have like 0.02 on taddress and another 0.02 on zaddress - I've been pool mining and I earn like 0.01 / day.
I left wallet.dat in the .zcash dir  but now have that file as well as wallet.1479479829.bak file in there that I did not create...

simple as renaming it to wallet.dat and restarting??

**Comment by lubah** [comment]
tried the rename wallet.1479479829.bak to wallet.dat and restarting zcashd to no avail...

I know its not a lot of zcash / money but something is fucked up...

**Comment by lubah** [comment]
originally was running v1.0.0  upgraded to v1.0.1 last week - never saw 1.0.2 so went straight to v1.0.3 is the only other info I can share...   no issues from 100 to 101 but screwed going from 101 to 103...

**Comment by sammy007** [comment]
Copy wallet to somewhere, then try:

```
db_dump -f dump wallet.1479479829.bak
db_load -f dump wallet.dat
```

Then launch `zcashd` and check balance.

**Comment by lubah** [comment]
looks like another .bak was created = both much larger than wallet.dat:

linuxmint18 ~/.zcash $ ls
blocks                    db.log             peers.dat              wallet.dat
bu-wallet.dat.lou-postup  debug.log          wallet.1479479829.bak  zcash.conf
chainstate                fee_estimates.dat  wallet.1479498765.bak

linuxmint18 ~/.zcash $ cp wallet.* ~/Documents/
linuxmint18 ~/.zcash $ cd ~/Documents/
linuxmint18 ~/Documents $ ls -al

total 3144
drwxr-xr-x  2 lubah lubah    4096 Nov 18 15:16 .
drwxr-xr-x 35 lubah lubah    4096 Nov 18 10:15 ..
-rw-------  1 lubah lubah 1560576 Nov 18 15:16 wallet.1479479829.bak
-rw-------  1 lubah lubah 1560576 Nov 18 15:16 wallet.1479498765.bak
-rw-------  1 lubah lubah   90112 Nov 18 15:16 wallet.dat

**Comment by lubah** [comment]
regardless db_dump fails:

linuxmint18 ~/.zcash $ db_dump -f dump wallet.1479479829.bak 
db_dump: BDB1009 wallet.1479479829.bak: unsupported btree version: 10
db_dump: BDB5115 open: wallet.1479479829.bak: Invalid argument

**Comment by sammy007** [comment]
`unsupported btree version: 10`

Looks like format is new and `db-util` shipped with your distro is unable to work with it, it even does not work for me on ubuntu 16.04 so I wonder what version to use :-/ i fixed a lot of wallets with `db_dump/load` so it can actually help.

**Comment by ocminer** [comment]
you'll need to use libdb 6.2 and it'll work fine. 

Download from here:
http://download.oracle.com/berkeley-db/db-6.2.23.tar.gz
Compile that, and in "build_unix" you'll find newer versions of db_dump and db_load

What is happening to you is the "standard-bug" of this coin, I'm doing the restore/rescan think every 2nd day with one of my wallets.. It's common when you have lots of transactions. 
You'll need to load the reloaded dump.db with 

zcashd -rescan (NOT reindex!!!) -salvagewallet -daemon 

and after 6-10 hours your balance is back 

Be sure not to stop the wallet after it has been rescanned and move the balance out of the wallet asap as the file WILL get corrupted again after you do some sending/receiving with z_transactions involved.

**Comment by str4d** [comment]
@ocminer have you tested 1.0.3 yet? The "standard-bug" you refer to (#1715) was fixed in 1.0.3 (and the reindex bug in 1.0.1). If you're seeing a different bug, please open a new issue.

**Comment by ocminer** [comment]
I've updated one (payout) node to 1.0.3 yet and i'm testing it for 24h to see if it runs stable. Do I need to recreate wallet.dat's or are old wallet.dat's fully compatible and I won't run into that error anymore even with the old wallets ?

**Comment by str4d** [comment]
The problem was in cached values, so if your old wallet was not encountering the assertion failure, it means it did not at that point contain any problematic cached values, and so should be fine with 1.0.3. If it did encounter the assertion failure, a reindex would resolve the problem.

**Comment by bitcartel** [comment]
@lubah Did you shutdown `zcashd` with `zcash-cli stop` before you started deleting files in `~/.zcash`?    The wallet.(timestamp).bak file is created when the node detects a wallet.dat file is corrupted.

**Comment by bitcartel** [comment]
May be related to #1694.

Also may be related to a ticket about dependency management and having the correct version of bdb linked rather than using the system libraries. Cannot find the ticket number at the moment.

**Comment by lubah** [comment]
on the shutdown question -- I did a cntrl-c to kill the client first...   I mentioned the client crashed at least 3 times - so guessing the .bak were created then.   still rescanning per ocminer's suggestion but 2 hrs later still no balance.

**Comment by ebfull** [comment]
@ocminer Next time your daemon crashes, send us the output from `debug.log` please!

**Comment by daira** [comment]
``unsupported btree version: 10`` is a smoking gun that this is due to a mismatch between the version of Berkeley DB that is being used by 1.0.3, and the version that was used by 1.0.1. The BDB database format isn't stable across releases (and it seems to do a really poor job of recovering from or even properly reporting that).

The depends system is supposed to stop us linking with whatever random version(s) of bdb, if any, are installed on the system, and reliably link to the statically built bdb 6.2. It's clearly failing to do that, and the possible reasons can be categorised as: a) a problem with the upstream Bitcoin dependency system or its bdb.mk recipe or the linking of bdb; b) something we've broken in that system; and/or c) something we've broken by updating to bdb 6.2.

We should probably determine the BDB version we're linking against at run-time and hard-fail if it is not the correct version. That would be preferable to creating an incompatible wallet.dat that the user may end up losing keys from.

**Comment by daira** [comment]
@lubah was this build directory previously upgraded from a version of zcash before rc3?

**Comment by daira** [comment]
@bitcartel wrote:
> Also may be related to a ticket about dependency management and having the correct version of bdb linked rather than using the system libraries. Cannot find the ticket number at the moment.

That's #209. #1420 would also help a great deal, and is essentially what I suggested above but for all dependencies.

**Comment by bitcartel** [comment]
I don't think it's the issue though, at least not with ubuntu.  For both 1.0.1 and 1.0.3 built on different systems, with bdb v5 installed on the system, zcashd is statically linked with v6.2.
```
file wallet.dat
wallet.dat: Berkeley DB (Btree, version 10, native byte-order)
```

```
ldconfig -p | grep bdb
	libdb_cxx-5.3.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libdb_cxx-5.3.so
	libdb-5.3.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libdb-5.3.so
	libdb-5.1.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libdb-5.1.so
```

**Comment by str4d** [comment]
@daira 
> `unsupported btree version: 10` is a smoking gun that this is due to a mismatch between the version of Berkeley DB that is being used by 1.0.3, and the version that previously wrote the `wallet.dat` file.

[snip]

> The depends system is supposed to stop us linking with whatever random version(s) of bdb, if any, are installed on the system, and reliably link to the statically built bdb 6.2. It's clearly failing to do that

I think https://github.com/zcash/zcash/issues/1882#issuecomment-261634569 is a more likely cause of the `unsupported btree version` error, in which case the `wallet.dat` version *was* written with the correct BDB version for Zcash.

**Comment by daira** [comment]
Huh. Why is the file format parsing of a statically-linked bdb 6.2 dependent on the version of some random system utility library? I thought the whole point of BDB was that it was supposed to be a standalone application-library db.

**Comment by buzztiaan** [comment]
stop suggesting libdb6 , this wont end well for anyone

**Comment by str4d** [comment]
@daira 
> Why is the file format parsing of a statically-linked bdb 6.2 dependent on the version of some random system utility library?

It isn't. I'm saying that https://github.com/zcash/zcash/issues/1882#issuecomment-261632620 occurred because the system utility library was using the system version of bdb (likely 5.X), which was too old to read the `wallet.dat` written by `zcashd` using the statically-linked bdb 6.2. That implies that the `wallet.dat` was correctly-written with the correct version of bdb, but we won't know that until the OP tries using `db_dump` from bdb 6.2.

**Comment by bitcartel** [comment]
@lubah Thanks for the update.  I'd appreciate a few data points if you have time:
For the VM configuration:
- what is the host OS e.g. Windows X ?
- what is the guest OS e.g. Ubuntu X.X ?
- how much memory did you assign the VM?
- how many cpu cores?
- what type of hard disk e.g. fixed size 10GB or dynamic?

**Comment by lubah** [comment]
VMware Workstation 12
Host Win10
Guest Linux Mint 18 (Sarah)
8Gb mem
4cores
20gb dynamic

**Comment by buzztiaan** [comment]
anyway, this 'bug' is the reason practically -all- cryptocoins stick to libdb4.8 forever

upgrading it -can- work but causes incompatible wallets and loss of funds, as demonstrated here, sadly

please follow the norm zcash, its there for a purpose ;)

**Comment by nathan-at-least** [comment]
Hey @lubah I see that we had put this into the 1.0.4 milestone, but then we decided to postpone it to 1.0.5 which doesn't have a release date yet. We'll look into it more thoroughly after 1.0.4 release.

**Comment by daira** [comment]
@buzztiaan Zcash has used BDB 6.2.x since launch. Upgrade from BDB 4.8 is not an issue. When I wrote about the ``unsupported btree version`` error, I'd missed the fact that the error only occurred when the OP tried to use ``db_dump``, which is not part of Zcash. So the BDB version is a red herring for this ticket.

**Comment by bitcartel** [comment]
@nathan-at-least User has given us all information possible.  Are there any action items for this ticket or can it be closed?
