### ISSUE TITLE
Should I change the username in the zcash.conf file?

### ISSUE THREAD

**Issue by eric1688** [zcash/zcash#1890]
I read the guide for 1.0 User Guide for the Configuration section, it says:

mkdir -p ~/.zcash
echo "addnode=mainnet.z.cash" >~/.zcash/zcash.conf
echo "rpcuser=username" >>~/.zcash/zcash.conf
echo "rpcpassword=`head -c 32 /dev/urandom | base64`" >>~/.zcash/zcash.conf

I know the password should be random generated, but there's no any description about the rpcuser value username, it is default username.

Should I set the unique username? or use the default value "username"? Please help me, thank you.

**Comment by ioptio** [comment]
It's up to you... but might as well change it since there's no harm in doing so!
