### ISSUE TITLE
zcash-cli broken after z_importkey

### ISSUE THREAD

**Issue by Ayms** [zcash/zcash#1894]
Maybe I am not using it correctly (see https://github.com/Ayms/zcash-wallets#use---generate-wallets) but after using z_importkey zcash-cli does not return (but adds the key in the wallet), then killing it and retrying another zcash-cli command seems to have no effect, the command does not return either, the only way to recover seems to be to kill zcashd and relaunch it.

**Comment by str4d** [comment]
It's not returning because by default when you import a key, your node scans the blockchain for any transactions related to that key. Hence why you see it added, but the command doesn't immediately return. You can tell the RPC to just add the key and not rescan - see `zcash-cli help z_importkey`.

**Comment by Ayms** [comment]
Well ok "Set rescan to true (the default) to rescan the entire local block database" is not very clear (why to set rescan to the default?), default should be false, when you import a new key it's unlikely that you have already used it

**Comment by str4d** [comment]
The default was set to true to match `importprivkey` (inherited from Bitcoin).

**Comment by Ayms** [comment]
When people use this they know what they are doing, then the default should clearly be false, because if they want to rescan then they will explicitely specify rescan=true

z_commands probably don't have to follow bitcoin behavior (mistakes?)

**Comment by Ayms** [comment]
I tried `` zcash-cli z_importkey key rescan=false`` and got ``error: Error parsing JSON:rescan=false``

This is not the correct command?

**Comment by str4d** [comment]
`zcash-cli z_importkey KEY false`

**Comment by Ayms** [comment]
So am I misreading the docs (https://github.com/zcash/zcash/blob/master/doc/payment-api.md)? Why does it state [rescan=something]?
