### ISSUE TITLE
how can i mining joining a pool on linux ?

### ISSUE THREAD

**Issue by xuzhiping7** [zcash/zcash#1897]
i am testing mining on linux , it works ,but i want to join a pool to test some params.

how can i mining joining a pool on linux .

thanks~

**Comment by DATSEC** [comment]
## Zcash Mining Guide

Welcome! This guide is intended to get you mining Zcash, a.k.a. "ZEC", on the Zcash mainnet. The unit for mining is Sol/s (Solutions per second).

If you run into snags, please let us know. There's plenty of work needed to make this usable and your input will help us prioritize the worst sharpest edges earlier. For user help, we recommend using our forum:

https://forum.z.cash/
## Compile it yourself

On Ubuntu/Debian-based systems:

    $ sudo apt-get install \
          build-essential pkg-config libc6-dev m4 g++-multilib \
          autoconf libtool ncurses-dev unzip git python \
          zlib1g-dev wget bsdmainutils automake

On Fedora-based systems:

    $ sudo dnf install \
          git pkgconfig automake autoconf ncurses-devel python wget \
          gtest-devel gcc gcc-c++ libtool patch

Fetch our repository with git and run `fetch-params.sh` like so:

    $ git clone https://github.com/zcash/zcash.git
    $ cd zcash/
    $ git checkout v1.0.0
    $ ./zcutil/fetch-params.sh

This will fetch our Sprout proving and verifying keys (the final ones created in the [Parameter Generation Ceremony](https://github.com/zcash/mpc)), and place them into `~/.zcash-params/`. These keys are just under 911MB in size, so it may take some time to download them.

The message printed by `git checkout` about a "detached head" is normal and does not indicate a problem.

## Build

Ensure you have successfully installed all system package dependencies as described above. Then run the build, e.g.:

`$ ./zcutil/build.sh -j$(nproc)`

This should compile our dependencies and build `zcashd`. (Note: if you don't have `nproc`, then substitute the number of your processors.)

## Configuration

Create the `~/.zcash` directory and place a configuration file at `~/.zcash/zcash.conf` using the following commands:

    mkdir -p ~/.zcash
    echo "addnode=mainnet.z.cash" >~/.zcash/zcash.conf
    echo "rpcuser=username" >>~/.zcash/zcash.conf
    echo "rpcpassword=`head -c 32 /dev/urandom | base64`" >>~/.zcash/zcash.conf

Note that this will overwrite any `zcash.conf` settings you may have added from testnet. You can retain a `zcash.conf` from testnet, but make sure that the `testnet=1` and `addnode=betatestnet.z.cash` settings are removed; use `addnode=mainnet.z.cash` instead. We strongly recommend that you use a random password to avoid [potential security issues with access to the RPC interface.](https://github.com/zcash/zcash/blob/master/doc/security-warnings.md#rpc-interface)

## Enabling CPU mining:

If you want to enable CPU mining, run these commands:

    $ echo 'gen=1' >> ~/.zcash/zcash.conf
    $ echo "genproclimit=$(nproc)" >> ~/.zcash/zcash.conf

The default miner is not efficient, but has been well reviewed. To use a much more efficient but unreviewed solver, you can run this command:

`$ echo 'equihashsolver=tromp' >> ~/.zcash/zcash.conf`

## Mining

Now, start Mining!

`$ ./src/zcashd`

To run it in the background (without the node metrics screen that is normally displayed):

    $ ./src/zcashd -daemon

You should see the following output in the debug log (`~/.zcash/debug.log)`:

`Zcash Miner started`

Congratulations! You are now mining on the mainnet.

## Spending Mining Rewards

Coins are mined into a t-addr (transparent address), but can only be spent to a z-addr (shielded address). Refer to our [1.0 User Guide](http://thebitcointalk.org/t/zcash-user-guide/345) for instructions on how to use the `z_sendmany` command to send coins from a t-addr to a z-addr. You will need at least 4GB of RAM for this operation.

## Modifications

Mine to a single address

The internal `zcashd` miner uses a new transparent address for each mined block. If you want to instead use the same address for every mined block, find the following line in both `src/miner.cpp` (in the function `ProcessBlockFound()`) and `src/wallet/wallet.cpp` (in the function `CommitTransaction()`):

`reservekey.KeepKey();`

Remove or comment out that line in both places.

## Use P2PKH transactions

The internal `zcashd` miner inherited from Bitcoin uses P2PK for coinbase transactions. The trend in the Bitcoin blockchain has been to use P2PKH instead; we are considering [changing the internal miner to use P2PKH](https://github.com/zcash/zcash/issues/945), but not for the 1.0 release.

If you want to use P2PKH for your coinbase transactions, find the following line in `src/miner.cpp` (in the function `CreateNewBlockWithKey()`):

`CScript scriptPubKey = CScript() << ToByteVector(pubkey) << OP_CHECKSIG;`

Change it to:

`CScript scriptPubKey = CScript() << OP_DUP << OP_HASH160 << ToByteVector(pubkey.GetID()) << OP_EQUALVERIFY << OP_CHECKSIG;`

**Comment by arcalinea** [comment]
@DATSEC posted a good summary. This info is generally available in our [1.0 user guide](https://github.com/zcash/zcash/wiki/1.0-User-Guide) and [Mining Guide](https://github.com/zcash/zcash/wiki/Mining-Guide)

**Comment by xuzhiping7** [comment]
hello ,i already done those step before .

my question is how to join a miner-pool on linux for mining ?
