### ISSUE TITLE
gtest/zcash_gtest-test_joinsplit.o: file not recognized: File format not recognized

### ISSUE THREAD

**Issue by ztmorris** [zcash/zcash#1899]
Trying to set this up on Bash on Ubuntu on Windows 10. Tried removing everything and re-cloning several times and no joy. This is the end of it building. Cannot seem to find a log. Any suggestions?

/home/user/zcash/depends/x86_64-unknown-linux-gnu/lib/libgmp.a -lboost_system-mt -lcrypto 
/home/user/zcash/depends/x86_64-unknown-linux-gnu/lib/libsodium.a -lanl -fopenmp -pthread
gtest/zcash_gtest-test_joinsplit.o: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
make[2]: *** [zcash-gtest] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/home/user/zcash/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/user/zcash/src'
make: *** [all-recursive] Error 1

**Comment by str4d** [comment]
@bitcartel any ideas?

**Comment by bitcartel** [comment]
@ztmorris What build # and version of Windows 10 and Bash for Windows are you running?
Also what output do you get from `file zcash_gtest-test_joinsplit.o`  ?

**Comment by ztmorris** [comment]
What I pasted is above is all the output I have. That is what it says right at the end. 
I keep thinking it's a compiler issue. I reinstalled the compiler.


**The version is below.**
GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)

**Comment by ioptio** [comment]
@ztmorris any luck with upgraded compiler? If not, can you please run the command @bitcartel posed above and paste the output?

**Comment by ztmorris** [comment]
No luck after updating it. I just ran the coomand above and it says:

zcash_gtest-test_joinsplit.o: ERROR: cannot open `zcash_gtest-test_joinsplit.o' (No such file or directory)

Going to start all over and see what happens. I will let you know how it goes.

**Comment by ztmorris** [comment]
Went into /home/user/zcash/src and ran file gtest/zcash_gtest-test_joinsplit.o and it returned 
gtest/zcash_gtest-test_joinsplit.o: data

**Comment by arcalinea** [comment]
@ztmorris Several users have run into errors trying to build zcash and its dependencies with older versions of the gcc compiler. One user upgraded from gcc 4.7 to 4.8, and that fixed it. Relevant issue numbers are #1931, #1702, and #1707, and #838

**Comment by nathan-at-least** [comment]
@ztmorris which version of ubuntu on windows do you have? You can check with ``lsb_release -a``.  I think release 14.04 is too old. If you upgrade to 16.04 it should come with a newer version of ``gcc`` that can perform Zcash builds.

Here are instructions for upgrading the ubuntu subsystem: http://www.omgubuntu.co.uk/2016/10/windows-10-linux-subsystem-ubuntu-16-04

(HT @bitcartel who told me most of this info.)

**Comment by ztmorris** [comment]
Thank you. It is working now and passed the full suite test. Took a little bit to upgrade but after that, it all worked good. Thanks again.

**Comment by ioptio** [comment]
Glad this solution worked!
