### ISSUE TITLE
Enable Ctrl+C during rescan

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#1908]
As reported in https://github.com/zcash/zcash/issues/1749#issuecomment-262451170 and https://github.com/zcash/zcash/pull/1878#pullrequestreview-9953018. This is related to rescanning itself, not to the metrics UI.

**Comment by daira** [comment]
I just hit this and it was mildly irritating.

**Comment by nuttycom** [comment]
Completed in #6374
