### ISSUE TITLE
Fix ``merkle_block_1`` unit test regression.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#191]
After creating (uncommitted, hacky) workarounds for #187 and #190, I've discovered a regression in merkle tree computation in the ``merkle_block_1`` unit test [when constructing a ``CMerkleBlock``](https://github.com/Electric-Coin-Company/zerocashd/blob/211dc15b44a8b630c0f69431cc337bd7ab75f8b2/src/test/bloom_tests.cpp#L196).

Note: It may simply be that the test vector needs to be updated, since we've introduced new block headers fields (such as the coin commitment root).

**Comment by daira** [comment]
This ticket is obsolete or long-fixed.
