### ISSUE TITLE
Z-addresses can't yet be verified by an arbitrator in case of a dispute

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#1910]
From https://chat.zcashcommunity.com/channel/zcash?msg=Jzi2EWzWNeuyA4dqp

> Hi all... I tried to make a z_address transaction via bitsquare but couldn't... they say: 
> > "hi, u used a z address, which cannot be verified by the arbitrator in case of a dispute. please use only the transparent addresses (t) as only those can be verified. please delete your zec account and set up a new one with a t address. i will close the case and both get back their btc."

**Comment by arcalinea** [comment]
Replied saying most exchanges don't support z_addresses yet. 
https://chat.zcashcommunity.com/channel/zcash?msg=DnpcEPNuFEaYNoTg5

Is this ticket related to any future code changes, integration goals, or milestones we can link to?

**Comment by ioptio** [comment]
Ya, Jay and I were talking about this earlier and it _seems_ like this would be solved when viewing key is accessible in API. Is that accurate?

**Comment by tromer** [comment]
Related to #406.

**Comment by bitcartel** [comment]
Related to #1997

**Comment by bitcartel** [comment]
Related/Duplicate to #1937
