### ISSUE TITLE
FAIL: test/test_bitcoin

### ISSUE THREAD

**Issue by pinootto** [zcash/zcash#1914]
I installed zcash 1.0.3 on Slackware64 14.2. The installation was successful. When I ran the tests (./qa/zcash/full-test-suite.sh), I got this error:

../build-aux/test-driver: line 107: 18870 Aborted                 "$@" > $log_file 2>&1
FAIL: test/test_bitcoin

The full error log is reported in the attached file.

How can I do to correct this problem?

[test-suite.log.txt](https://github.com/zcash/zcash/files/629414/test-suite.log.txt)

**Comment by arcalinea** [comment]
@pinootto In my recollection, test_bitcoin needs at least 4GB RAM to run, so this could be an out-of-memory error. How much memory do you have on that machine?

**Comment by pinootto** [comment]
I have 16GB DDR4 RAM.

**Comment by ebfull** [comment]
This error looks like a problem with your filesystem or something. Not sure.

**Comment by arcalinea** [comment]
Ok it's not a memory issue then. On closer inspection this looks like it's failing on a test at checkblock_tests.cpp line 43.  The relevant snippet in the logs: 

```
unknown location(0): fatal error: in "CheckBlock_tests/May15": boost::filesystem::filesystem_error: boost::filesystem::current_path: No such file or directory
test/checkblock_tests.cpp(43): last checkpoint: "May15" entry.
test_bitcoin: main.cpp:1533: void InvalidChainFound(CBlockIndex*): Assertion `tip' failed.
```

Looks like it's failing on a bitcoin test that shouldn't even be running--that Mar12Fork.dat file isn't even hosted on sourceforge anymore, and you probably didn't download it. But my guess is it somehow looked for the file and couldn't find it, then set the active chain tip to May15, causing an invalid chain error and all subsequent tests to fail... can someone more familiar with the codebase confirm?

Relevant snippet at checkblock_tests.cpp line 43:
```
BOOST_AUTO_TEST_CASE(May15)
{
   // Putting a 1MB binary file in the git repository is not a great
   // idea, so this test is only run if you manually download
   // test/data/Mar12Fork.dat from
   // http://sourceforge.net/projects/bitcoin/files/Bitcoin/blockchain/Mar12Fork.dat/download
   unsigned int tMay15 = 1368576000;
   SetMockTime(tMay15); // Test as if it was right at May 15

   CBlock forkingBlock;
   if (read_block("Mar12Fork.dat", forkingBlock))
   {
       CValidationState state;

       // After May 15'th, big blocks are OK:
       forkingBlock.nTime = tMay15; // Invalidates PoW
       BOOST_CHECK(CheckBlock(forkingBlock, state, false, false));
   }

   SetMockTime(0);
}
```

**Comment by nathan-at-least** [comment]
Hm… it looks like the error is coming from ``boost::filesystem::current_path`` which says ``No such file or directory``, so I wonder if the tests were started in a directory which was then deleted while the tests were running.

Is this possible, @pinootto ?

Can you reproduce this error when you rerun tests, or not?

**Comment by pinootto** [comment]
I didn't delete the directory from where I started the tests.

**Comment by ioptio** [comment]
@pinootto are you still having issues with this?

**Comment by pinootto** [comment]
I didn't try again.

**Comment by jbsturgeon** [comment]
I'm failing the same test - I haven't dug down to find out why.  I'm on "HEAD detached at v1.0.10-1"

**Comment by ioptio** [comment]
@jbsturgeon can you please provide more information such as a log output and information about your system? Do you have enough memory for the test as asked above?

**Comment by Maximilianko** [comment]
Hello, I Have the same error. I just finished with installation of Zcash 1.0 Sprout and did test ./qa/zcash/full-test-suite.sh
The error is:FAIL: test/test_bitcoin

**Comment by daira** [comment]
@Maximilianko note that this error is displayed for *any* problem with that part of the test suite. We would need the complete output.
