### ISSUE TITLE
Host zcash .deb package on download page for easy install

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#1921]

**Comment by arcalinea** [comment]
Discussed with @ageis , he prefers to let people get it through their package manager and set up our repo, that way they get updates and the built-in cryptographic verification. Right now the download page links to the zcash wiki page with [instructions for downloading the debian package](https://github.com/zcash/zcash/wiki/Debian-binary-packages), I propose we leave it like this for now. Thoughts?

**Comment by bitcartel** [comment]
Closing this as we now have a tarball .tgz available on the download page.
