### ISSUE TITLE
Configure zkbot to always do (non-fast-forward) merge commits.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#1926]
We'd like the git history itself to name every merge that went through zkbot with a consistent message, so that by examining the git history of master we can see the sequence of merges and which commits are associated with which merges.

Note: someone could always spoof the zkbot commit message and push to master, so this isn't a secure log, just a consistency benefit in the absence of malice.

Note: we want to have this record outside of github to be able to react well to github outages or take-overs.

**Comment by nathan-at-least** [comment]
Moved out of 1.0.5 and added needs-prioritization to put it in the monday meeting queue.

**Comment by tromer** [comment]
#1981 closed this issue (#1926), but seems unrelated. Mistake?
