### ISSUE TITLE
Persistent async op-id and/or async operation logging

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#1929]
Some users have asked if there is a way to persist async operations. Currently they're cleared from memory as soon as the operation result is sent to a client.

Some users are curious if we could have persistence for these, such as storing them in a db or logging them. One motivation might be there are multiple "stateless clients" but a secondary system needs to audit or review. Without persistence those clients would need to send results to a central db / logging service.

**Comment by nathan-at-least** [comment]
We need to circle back with users to have a clearer specification for this ticket.

**Comment by tromer** [comment]
On related note, we'd want to persist/log maximally informative async op results, including sub-causes of `bad-txns-joinsplit-requirements-not-met` and aborted transactions (#1821).

**Comment by bitcartel** [comment]
Closing as users requirements are captured by #1937
