### ISSUE TITLE
I also meet the same problem like #1702

### ISSUE THREAD

**Issue by joyivan** [zcash/zcash#1931]
I git the 1.0.3 but I meet the same problem like this " src/common/assert_except.hpp: In function ‘void assert_except(bool)’:
src/common/assert_except.hpp:8:15: error: ‘runtime_error’ is not a member of ‘std’
compilation terminated due to -Wfatal-errors."

WHY ?
my zcash was v1.0.3

**Comment by arcalinea** [comment]
This looks like an outdated compiler error. There's some sort of incompatibility with how old versions of gcc declare the scope of exceptions like "runtime_error". 
- Did you build with `./zcutil/build.sh`?
- What version of gcc are you using? Maybe try upgrading your version of gcc and building again?

**Comment by joyivan** [comment]
thanks @arcalinea 
My gcc version was 4.7 ,after  I have updated to 4.8 ,that works.  thanks again .The problem muzzles me 2 days .

**Comment by arcalinea** [comment]
No problem, glad it worked!
