### ISSUE TITLE
Zombie balance in imported z-address

### ISSUE THREAD

**Issue by tromer** [zcash/zcash#1936]
I encountered a problem with an imported z-address key causing a nullified note to be treated, by the local node, as an unspent note.

Details:
On one machine, I generated a z-address, accepted some ZEC and sent it back out.
I then `z_importkey`ed that z-address into a second machine. After the import (involving a lengthy blockchain rescan) was done, it then showed a balance corresponding to the aforementioned ZEC. So apparently it correctly processed the incoming transaction but not the outgoing one.
When I tried to send this zombie balance from the second machine, it created a JoinSplit that consumes the already-nullified note. Then, as expected, it locally rejected this transaction with `18: bad-txns-joinsplit-requirements-not-met` and `We think the nullifier is spent already: ...ERROR: AcceptToMemoryPool: joinsplit requirements not met`.

This is with v1.0.3 plus @ebfull's `debugging-eran.diff` patch (which just says prints the `nullifier is spent` message). Both machines are in sync with the mainnet.

**Comment by str4d** [comment]
When a transaction containing notes we receive is added to the wallet, `CWallet::UpdateNullifierNoteMapWithTx(wtx)` is called, which takes the nullifier for each note in the transaction that we received, and adds it to `mapNullifiersToNotes`.

When any transaction is checked by the wallet to see if it is ours, one of the checks is to search `mapNullifiersToNotes` for every nullifier in the transaction. Thus as long as the spend tx is seen after the receive tx (which will be true for a valid block chain), and the wallet was unlocked when the receive tx was seen (which is always true currently), the spend tx should be detected.

The fact that it isn't being detected indicates that one of the assertions or assumptions above is invalid in at least some cases :joy:

**Comment by daira** [comment]
The first step for this ticket is to reproduce the problem manually; the second is to write an automated test that fails.

**Comment by arcalinea** [comment]
@tromer Do you remember whether you let z_importkey use the default rescan option (`default=whenkeyisnew`) or whether you specified `rescan=True`?

**Comment by tromer** [comment]
This bug was encountered with an ancient version of zcash, with a state that I can no longer reproduce. I have not encountered it since. So closing.
