### ISSUE TITLE
When importing z-addresses, rescan does not see transactions older than wallet birthday

### ISSUE THREAD

**Issue by tromer** [zcash/zcash#1941]
Wallet bug:

When importing a z-address key via `z_importkey`, the wallet automatically does a rescan to recognize associated transactions. However, the rescan code skips over blocks that are older than the time the wallet was created, so if the node is a new installation, it will not see historical transactions.

Culprit code in `CWallet::ScanForWalletTransactions()`:
```
        // no need to read and scan block, if block was created before
        // our wallet birthday (as adjusted for block time variability)
        while (pindex && nTimeFirstKey && (pindex->GetBlockTime() < (nTimeFirstKey - 7200)))
            pindex = chainActive.Next(pindex);
```

This optimization may make sense in some contexts, but not when importing keys.

Related to #1860, #1350.

**Comment by tromer** [comment]
After commenting out the above loop, `z_importkey` indeed scans the whole blockchain and recognizes the correct balances.

**Comment by bitcartel** [comment]
Thanks, will look into this.  Rescan can be called upon start-up, so just commenting out the loop above will lead to a full scan at launch.

**Comment by str4d** [comment]
This is an inconsistency between our `z_importkey` and the existing `importprivkey` from Bitcoin. The latter has the following before the `ScanForWalletTransactions()` call:

```cpp
        // whenever a key is imported, we need to scan the whole chain
        pwalletMain->nTimeFirstKey = 1; // 0 would be considered 'no value'
```
