### ISSUE TITLE
Add sha256 hash of tarball to download page

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#1944]
sha256sum zcash-1.0.3-linux64.tar.gz
c8a2ec2b38df498c108e425c1f45c338ef04355922c35b8bbfc70bd311606c0f

It's also in the gitian.sigs repo.
https://github.com/zcash/gitian.sigs/blob/master/v1.0.3/simon/zcash-1.0.3-build.assert

So perhaps display and/or link to the hash.

Upstream https://bitcoin.org/en/download has a link "Verify Release Signatures" which downloads file:
https://bitcoin.org/bin/bitcoin-core-0.13.1/SHA256SUMS.asc

**Comment by arcalinea** [comment]
This was completed in https://github.com/Electric-Coin-Company/z.cash/pull/636
