### ISSUE TITLE
Verify 1.0.4 fixes problem creating transaction

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#1945]
A problem was observed in a VM snapshot, where creating a z_sendmany transaction fails with an error message `AcceptToMemoryPool: joinsplit requirements not met`.

Verify that this problem is resolved when one of the following is applied:

1. Disable networking

2a. Shut down zcashd, upgrade to 1.0.4, relaunch zcashd.
or
2b. Shut down zcashd, upgrade to 1.0.4, relaunch zcashd with `-reindex` option.

The problem is resolved when the transaction is created and accepted into the node's mempool without error.  To see transactions in the mempool, run: `zcash-cli getrawmempool`.

**Comment by tromer** [comment]
Yes, the transaction succeeds with v1.0.4, but only after a reindex.

**Comment by tromer** [comment]
Note that the transaction succeeded after a reindex also with v1.0.3.
It also succeeded after a *rescan* with v1.0.3, though in that case, it used a different anchor.
