### ISSUE TITLE
Create separate builds with and without mining

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#1951]
@zookozcash believes that having to do *any* configuration to enable mining is too much configuration. Instead, he proposes that we have two different `zcashd` packages/binaries: one containing mining code, and one without.

If the user installs the former, then we enable mining by default, using the best configuration we can for their machine. If the user installs the latter, there is no mining possible because none of the mining code exists (which satisfies the use case in #1795).

**Comment by nuttycom** [comment]
The `--enable-mining` configure flag is available for those who want to build without the mining code included.
