### ISSUE TITLE
Mine to single address option proposal.

### ISSUE THREAD

**Issue by miningpoolhub** [zcash/zcash#1955]
I know that there's some workaround to mine to single address by modifying the source code.
https://github.com/zcash/zcash/wiki/Mining-Guide#mine-to-a-single-address
But modifying source code is not that ideal I think.

It would be much better if there's some option for it like
changeminingaddress=true/false
or some compile option to specify enable/disable this thing.

**Comment by sammy007** [comment]
IMO it's much better to offer `coinbase=t-addr` option in `zcash.conf` instead, this way you can run wallet-less node for mining, and I guess `getblocktemplate` rpc call also can use it.

BTW, in-daemon mining especially CPU-only mining few minutes after launch does not make sense anyway, even with GPU it will take a year to find a block, I wonder why not completely purge `gen` feature.

**Comment by sammy007** [comment]
And of course for pools would be ideal to build `coinbasetxn` on a pool side and don't rely on `getblocktemplate.coinbasetxn`.

**Comment by bitcartel** [comment]
We'll probably choose a different parameter name e.g. `mineraddress`.

**Comment by daira** [comment]
This is merged, but there's a follow-up PR to fix an error-reporting issue: https://github.com/zcash/zcash/pull/2081

**Comment by daira** [comment]
#2081 was also merged.
