### ISSUE TITLE
transactions from z to t addresses not propagated

### ISSUE THREAD

**Issue by feeleep75** [zcash/zcash#1956]
Hi,

4 sendmany transactions were not propagated in network for some reason. They were in mempool of sending instance but only there. I had to manually send transaction on mining node to process transaction. If you need any information let me know please.

EDIT: It started to happen after upgrade to 1.0.4

feeleep

**Comment by bitcartel** [comment]
What's the priority of those transactions when you examine the mempool?

Any error messages in debug.log or on any non mining nodes you have connected,  related to the TX?

**Comment by feeleep75** [comment]
I did not check the priority but it was visible on the node for payments only. When i used sendrawtransaction on mining node it appeared on another nodes as well.

TX example is: 4eb54996b644b755baa42b3862f0cb76ecca5eaed0b1d5dedfc3fe783c7abf37

it is minorityas I am probably having more than 50 each day. So probably 1-2% failed

All my nodes are 1.0.4

**Comment by tromer** [comment]
How large are the transactions? With the default 0.0001 fee, transactions over 10kB will be subject to rate-limiting and so may be dropped.

(This issue is an example for #1959.)

**Comment by feeleep75** [comment]
According to my node it is already in blockchain but user says it did not
appear in his wallet. When I check official block explorer I can't find
this transaction. Also user wallet in block explorer is not updated with
sent amount. When you check blockhash in block explorer it does not show
any transaction... So what actually happened?

**Comment by tromer** [comment]
How did you check that it's in your node's blockchain? What's the block hash and does _that_ appear in the explorer?

**Comment by feeleep75** [comment]
Damn... I messed up this ticket with the other one I created today...) :

**Comment by nathan-at-least** [comment]
@feeleep75, this may have been due to a 'rate limiting' bug which we've subsequently fixed. Would you be able to retest this issue (as much as possible) with a recent release (eg 1.0.7)?

**Comment by nathan-at-least** [comment]
Actually, for the 'rate-limiting' bug I mentioned, the transaction should have _eventually_ been mined, even if it took a long time. Could you verify if that happened or not?

**Comment by daira** [comment]
Closing due to lack of response. @feeleep75 please reopen if you see this problem with a more recent version.
