### ISSUE TITLE
Help users understand "transaction not mined" situations

### ISSUE THREAD

**Issue by tromer** [zcash/zcash#1959]
There are various circumstances that can cause locally-generated transactions to remain unmined, for a long time or indefinitely. For example:
* Loss of network connectivity to peer nodes
* Transaction fees too low (e.g., below the 0.00001 ZEC/kB, transactions are considered "free" and are rate-limited, #1969)
* Transaction mining priorities
* Miners using stricter inclusion rules than the `zcashd` mempool
* Network overload
* Shielded transaction's anchor was invalidated by a reorg (#1614, #2311)
* Transaction has too many transparent inputs (e.g., local `-mempooltxinputlimit` is too high - #2818)

We should help users easily assess the status of their locally-generated transactions: when and whether they're mined, and if not, why. We should also help them recover (e.g., #1958).

This may be done by a combination of:
* RPC calls
* Analysis by block explorer / observatory (#1922)
* Guidelines to wallet developers
* Instructions for manual investigation

**Comment by tromer** [comment]
Another feature that would be helpful:
When a node rejects a incoming transaction, send the error message (e.g., `<txid> was not accepted into the memory pool: bad-txns-joinsplit-requirements-not-met`) back to the peer that sent it, for logging there.

**Comment by tromer** [comment]
Edited issue description to add another cause:
* Shielded transaction's anchor was invalidated by a reorg

**Comment by tromer** [comment]
Edited issue description to add another cause:
* Transaction has too many transparent inputs (e.g., local `-mempooltxinputlimit` is too high - #2818)

**Comment by ioptio** [comment]
Let's update this question in the user FAQ to reference a more explicit process with regards to transaction expiry https://z.cash/support/faq.html#safe-zcash-upgrade

**Comment by lindanlee** [comment]
@tromer, to address your concerns, we are: 

1. updating the answer to [ Are my funds safe during the transition?](https://z.cash/support/faq.html#safe-zcash-upgrade) to talk about transaction expiry. The updated text is as follows: 

```
Are my funds safe during the transition?
—
If your wallet has upgraded, you don’t need to do anything to 'transfer' your money. For safe keeping of funds during any version upgrade and as a general practice, we highly recommend making and keeping regular backups of your wallet.
It is best practice to stop sending transactions  near the network upgrade activation height; we recommend not sending transactions an hour or so beforehand. Transactions that are not mined before the activation height will need to be resent after the upgrade. 
If you have sent a transaction after the upgrade and it has not been mined, wait for the transaction to expire (the transaction expiry period is about ~10 minutes/20 blocks) and try your transaction again. For understanding various situations and responses to unmined transactions, see this question.
```
2. adding another question to be put at the bottom of the “Zcash Ecosystem” section (first section, new question as last question).

```
What do I do if my transaction is not being mined? 
After the Overwinter network upgrade, all transactions expire after ~10 minutes/20 blocks, and the best thing to do is to try your transaction again with some modifications. When your transaction expires, your funds will be returned to you. 

There may be various reasons why your transaction is not included in a block: 
- Loss of connectivity 
- Transaction fee too low 
- Network overload
- Too many transparent inputs (transaction size too large) 

We suggest trying your transaction again with: 
- Try again with a better connection 
- Use the standard fee (0.0001 ZEC) 
- Try again later, or increase the fee for high priority transactions 
- Use a minimal amount of inputs to limit the size, or increase the fee for large transactions
```
For this question, we tried to address your original concerns, mentioned in your [first comment](https://github.com/zcash/zcash/issues/1959#issue-196982254), but we excluded "loss of connectivity to peer nodes" (it will error out, or just send; not be in limbo), "transaction mining priorities" (a possibility but zcash hasn't experienced this as far as we know),  "miners using stricter rules" (seems to be same as too many transaction inputs), and "anchor reorg" (uncommon/we didn't know what to say). 

We hope that adding additional information to the [FAQ page](https://z.cash/support/faq.html) will help users understand their transaction not mined situations.

**Comment by lindanlee** [comment]
@copernicus-mogley, please update https://z.cash/support/faq.html so that: 

1.  the sentence right near the title, "For troubleshooting, please see our Github wiki." is reworded to "For troubleshooting the zcashd client, please see our Github wiki."
2. the question "[Are my funds safe during the transition?](https://z.cash/support/faq.html#safe-zcash-upgrade)" is updated with the text above (or if it's easier, it's also in this [google doc](https://docs.google.com/document/d/1Ducz4iNN3OEC5WwQkQRa1z7wh96AukZKgmjcA0N2SK0/edit?usp=sharing)). 
3. add a question "What do I do if my transaction is not being mined?" to the bottom on the first section; specifically, in the "Zcash Ecosystem" section after the " What is the difference between Zcash and Bitcoin?" question. The text is above or in this [google doc](https://docs.google.com/document/d/1Ducz4iNN3OEC5WwQkQRa1z7wh96AukZKgmjcA0N2SK0/edit?usp=sharing). 

Let me or @ioptio know if there are any questions!

**Comment by lindanlee** [comment]
@str4d, if you have some spare cycles, could you look at the text in this [google doc](https://docs.google.com/document/d/1Ducz4iNN3OEC5WwQkQRa1z7wh96AukZKgmjcA0N2SK0/edit?usp=sharing) and wordsmith it to be more accurate if you see fit? If you don't respond, we'll just go ahead with our wording.
