### ISSUE TITLE
write science investigation into privacy-preserving mobile-support/SPV

### ISSUE THREAD

**Issue by zookoatleastauthoritycom** [zcash/zcash#196]
possible features:
* support mobile clients
* support mobile miners
* SPV -- which can mean various things in the context of a privacy-preserving coin like Zcoin

@matthewdgreen and @amiller, please collaborate to write a document about this issue.

Goals:

1. Inform Zooko about what the issues and trade-offs are.
2. Make recommendations to Zooko about a good strategy for SPV support in the "Zcoin 1.0" protocol.
3. This document may subsequently be useful for publicity purposes: explaining to the world what we've done and why, or why we've not done it, how it differs from alternatives, etc.
4. This document may be useful for science purposes: documenting possibilities and impossibilities in this space.

**Comment by nathan-at-least** [comment]
@amiller Can you link or publish your notes here, then close this ticket?

**Comment by amiller** [comment]
Here are notes from myself and Matt Green https://docs.google.com/document/d/1gF3_BTP7IwoLOIXoxDxAK1AEdY5QPVL0dXf4EQef3p0/edit?usp=drive_web

**Comment by nathan-at-least** [comment]
Thanks.
