### ISSUE TITLE
Include operation details in `z_getoperation{status,results}` responses.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#1960]
If `z_getoperationstatus` returned the 'operation specification' in the resulting JSON it makes implementing a simplistic logging system which does not need to coordinate with any processes which are initiating operations.

I believe this changes the privacy implications of the RPC interface in an acceptable manner, but we need to define a 'privacy policy' to clarify this. It's already the case that `z_listoperationids` can retrieve `opids`, and then `z_getoperationresult` will return a result, so any authenticated client can already retreive *results* such as TxIds.

This would expose even more information, such as destination z-addrs and memos. If we have a simplistic privacy/security policy that all authenticated RPC clients are in the same class, that's ok. Otherwise we need some policy that says they can all retrieve operation results and statuses from eachother but can't see operation specifications (which to me is confusing and convoluted, so I argue against it).

**Comment by tromer** [comment]
We can also log the randomness used, and thereby provide a fallback for (or a poor man's version of) selective disclosure for outgoing transactions.
