### ISSUE TITLE
Ghost transaction

### ISSUE THREAD

**Issue by feeleep75** [zcash/zcash#1963]
Hi,

Another issue on the pool. I send with sendmany transaction id: c7a70f0c571727da9be08158e9fa25299113f615aeb787d48b6d4460b2a25eb0 

This transaction is visible on sending node, also visible on other nodes (using getrawtransaction) but it is for example not visible in explorer - transaction does not exist and address did not receive any zecs in explorer.

```
zcash-cli gettransaction c7a70f0c571727da9be08158e9fa25299113f615aeb787d48b6d4460b2a25eb0
{
    "amount" : 0.00000000,
    "confirmations" : 196,
    "blockhash" : "000000004d54dfb9ad71895e424fdc1de69da7408d6ed7916d184ee8afc2ebf7",
    "blockindex" : 18,
    "blocktime" : 1482398192,
    "txid" : "c7a70f0c571727da9be08158e9fa25299113f615aeb787d48b6d4460b2a25eb0",
    "walletconflicts" : [
    ],
    "time" : 1482397781,
    "timereceived" : 1482397781,
    "vjoinsplit" : [
        {
            "anchor" : "c9520c3b150650585926a6f1ebf1902f340405b477916d783d1470f05a49e7fc",
            "nullifiers" : [
                "bdb3d9a1d8a36a252a55b8e47916a4b8f15811cb9cc846898c6fb6a0f29a8890",
                "77849886e82dc517c59888a7d12f97e19ba1e51a727a5512fe211c8597e5a2b2"
            ],
            "commitments" : [
                "51aa356a82e90facf56525c080cc30f2d85d514133e756777b73f46f6e0d6e05",
                "6b23cf13a0b265a96a22f1532f69b062a79334d566c5fce1c39f969bd4394877"
            ],
            "macs" : [
                "024b742f10bf7ac5d4284e86c0fb5a8490796e0b9dc83f369eb431ab1921cfe6",
                "b8cd83fe36234d6b5d606621e5acea209fad1fc32cce542faf6f87b5a9e8f7be"
            ],
            "vpub_old" : 0.00000000,
            "vpub_new" : 14.82493670
        }
    ],
    "details" : [
    ],

```

**Comment by tromer** [comment]
This is the expected behavior when the transaction has not been mined yet.

(It should be easier to figure out why, cf. #1959).

**Comment by feeleep75** [comment]
As you can see it has over 200 confirmations

**Comment by str4d** [comment]
What is interesting about this transaction is its block hash. If you search that (I'm looking on zcha.in), you find it is its current chain head, but if you navigate backwards and then forwards, you reach a different block at the same height, ie. this block is an orphan. However, *this transaction isn't in that block*! This means two things:

- Your local state is somehow corrupted to think the transaction is in that block.
- Your local state is somehow corrupted to think that block is in the main chain.

**Comment by feeleep75** [comment]
Are you able to get TX details on your node with getrawtransaction command?

If it is orphan, what should I do to get those zec back then?

On Dec 23, 2016 5:47 AM, "str4d" <notifications@github.com> wrote:

What is interesting about this transaction is its block hash. If you search
that (I'm looking on zcha.in), you find it is its current chain head, but
if you navigate backwards and then forwards, you reach a different block at
the same height, ie. this block is an orphan. However, *this transaction
isn't in that block*! This means two things:

   - Your local state is somehow corrupted to think the transaction is in
   that block.
   - Your local state is somehow corrupted to think that block is in the
   main chain.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/zcash/zcash/issues/1963#issuecomment-268940242>, or mute
the thread

**Comment by ioptio** [comment]
@feeleep75 Did you figure this out? Since an orphaned block is not in the Zcash blockchain, if you sync your wallet to correct chain it should simply show those that txn was never mined and the ZEC should be in the original address.

**Comment by daira** [comment]
If there is not one already, let's add a test to make sure that when a transaction (with JoinSplits) is mined in a block that is orphaned, then the wallet correctly shows the amount sent as being included in the address balance again.

This would be an RPC test that causes a network split between nodes A and B, mines the transaction on chain A and mines two other blocks on chain B, then heals the split, lets the client reorg to the best chain B that does not have the transaction, and checks the balance. I'm pretty sure there are existing RPC tests of this form but they might not take into account JoinSplits.

**Comment by nuttycom** [comment]
This transaction seems to be visible now: https://blockchair.com/zcash/transaction/c7a70f0c571727da9be08158e9fa25299113f615aeb787d48b6d4460b2a25eb0

**Comment by nuttycom** [comment]
On further inspection, there *is* something odd about this transaction; while blockchair.com has it, it does not appear in `gettransaction` output:

```
nuttycom@sword:~/work/zcash/release (master)λ ./src/zcash-cli gettransaction c7a70f0c571727da9be08158e9fa25299113f615aeb787d48b6d4460b2a25eb0
error code: -5
error message:
Invalid or non-wallet transaction id
```
