### ISSUE TITLE
z->t transactions leak information on values of consumed notes

### ISSUE THREAD

**Issue by tromer** [zcash/zcash#1971]
Consider using `z_sendmany` to send _v_ ZEC from a z-address to a t-address, and suppose this happens to consume 3 nodes owned by the z-address. with values _v1_,_v2_,_v3_ (such that _v1_+_v2_+_v3_ >  _v_). The current code creates a transaction with two JoinSplits: the JoinSplit consumes the _v1_ and _v2_ notes and outputs _vpub_=_v1_+_v2_, and a second JoinSplit consumes the _v3_ notes and outputs _vpub_ with the remainder.

This breaks privacy: the value _v1_+_v2_ is leaked unnecessarily, and may be used to link this transaction to prior ones.

It would be much better, for privacy, to have the first JoinSplit merge two notes into a single one of value _v1_+_v2_ (with no public value), and the second JoinSplit consume that note along with the _v3_, so that the only (inevitably) exposed value is _v_.

Drawbacks:
* Requires creating two separste transactions
* Requires a blockchain roundtrip between these two transasctions (to produce the anchor for the second JoinSplit)
* In the case of 4 input notes, requires 3 JoinSplits instead of 2

Of course, this generalizes to a larger number of notes.

Related to #1961 (opportunistic note merging) and #778 (randomizing note order).

**Comment by bitcartel** [comment]
Also related to https://github.com/zcash/zcash/issues/1277 where notes to be spent should be locked throughtout the transaction generation process.

**Comment by str4d** [comment]
This was already raised in https://github.com/zcash/zcash/issues/1360#issuecomment-246109488, and a note selection heuristic is being designed there that would resolve this issue, so closing as duplicate.

**Comment by tromer** [comment]
My claim above, that JoinSplit chaining requires multiple transactions and a blockchain roundtrip, is incorrect. The current protocol spec already allows intra-transaction chaining:
> The anchor of each JoinSplit description in a transaction must refer to either some earlier block ’s final treestate, or to the output treestate of any prior JoinSplit description in the same transaction.

**Comment by nathan-at-least** [comment]
@tromer: There is still some information leakage from chaining joinsplits. A user who requires best-possible privacy may want to split up those JoinSplits into separate transactions and emit them slowly (and with some timing to maximize indistinguishability given timing info).

Currently `z_sendmany` either creates a single transaction or fails. In the future we may allow it (or probably a new RPC method) to create multiple transactions, and then the user might be able to select between 'faster' or 'more private' modes.
