### ISSUE TITLE
Windows port can't sync past block 395

### ISSUE THREAD

**Issue by radix42** [zcash/zcash#1989]
Yes, I have a Windows build of v1.0.4, but it never is able to sync the blockchain from scratch past block 395. The debug.log output is below (doesn't matter what peers, which are different each time I try from scratch, they always end up getting banned):

2017-01-05 23:16:13 UpdateTip: new best=000000988ed3eb5ad686aaa8469f87a8771da822e9ce1c084d77d295783ad472  height=395  log2_work=29.16189  tx=396  date=2016-10-28 17:35:13 progress=0.000379  cache=0.1MiB(395tx)
2017-01-05 23:16:13 ERROR: CheckTransaction(): joinsplit does not verify
2017-01-05 23:16:13 ERROR: CheckBlock(): CheckTransaction failed
2017-01-05 23:16:13 ERROR: ProcessNewBlock: CheckBlock FAILED
2017-01-05 23:16:13 Misbehaving: 192.168.0.17:8233 (0 -> 100) BAN THRESHOLD EXCEEDED
2017-01-05 23:16:16 ERROR: CheckTransaction(): joinsplit does not verify
2017-01-05 23:16:16 ERROR: CheckBlock(): CheckTransaction failed
2017-01-05 23:16:16 ERROR: ProcessNewBlock: CheckBlock FAILED
2017-01-05 23:16:16 Misbehaving: 213.239.217.106:8233 (0 -> 100) BAN THRESHOLD EXCEEDED
2017-01-05 23:17:08 receive version message: /MagicBean:1.0.4/: version 170002, blocks=40269, us=67.1.162.72:50173, peer=3
2017-01-05 23:17:08 Added time data, samples 4, offset -1 (+0 minutes)
2017-01-05 23:17:16 ERROR: CheckTransaction(): joinsplit does not verify
2017-01-05 23:17:16 ERROR: CheckBlock(): CheckTransaction failed
2017-01-05 23:17:16 ERROR: ProcessNewBlock: CheckBlock FAILED
2017-01-05 23:17:16 Misbehaving: 31.162.134.181:8233 (0 -> 100) BAN THRESHOLD EXCEEDED

**Comment by radix42** [comment]
wow, when I manually copy over the blockchain from a linux machine, it says that the block database is corrupted, and wants to reindex, and still gets stuck at block 395

**Comment by str4d** [comment]
Block 395 is a red herring. The actual problem block is 396 (000000e869e3a0fa79858a51b4b1d09a6480dcdb37bae63653fcb11a718abf3f), which was the first block to contain a version 2 transaction with a JoinSplit. You can see from the `debug.log` output that the JoinSplit verification is failing, causing your Windows node to reject block 396 and thus fail to sync past it.

**Comment by radix42** [comment]
ah, then I'll go over the verifier code and make sure nothing touched it I'm not aware of in the port

**Comment by radix42** [comment]
I (finally!) got the test suite to build, here's the log of which of the tests fail, looks like (mostly?) serialization/deserializtion tests:

http://pastebin.com/sXWhHvny

**Comment by bitcartel** [comment]
@ebfull Please look at log output above.  See line 226 "C++ exception with description "point is not in G2" thrown in the test body."

**Comment by radix42** [comment]
Thanks for the pointer, @ebfull, I've been trying to read the tea leaves of
that test log to figure out what, if any, single (or few) problems might be
at the root of the failures

**Comment by daira** [comment]
Assigning to me to check:
* whether the "point is not in G2" check was released in 1.0.4 or is only on master
* whether block 396 is actually valid

If block 396 violates the "in G2" check and this is not just a bug specific to the Windows port, we need to block the 1.0.5 release on resolving this.

**Comment by ebfull** [comment]
This is a bug with the arithmetic on the Windows port. One explanation might be that your port is using the wrong curve implementation. We assume 64 bit words in a lot of places, so perhaps the build is violating one of those invariants.

Notice the other test failures such as `circuit.values` and `fq2_serializes_properly`.

**Comment by radix42** [comment]
yeah the top of my todo list is to check that everything that should be 64 bits, is. I would not be shocked if some things stayed 32 bits that should have become 64 in mingw64

**Comment by radix42** [comment]
@ebfull I found a flag that is supposed to be passed to 64 bit Windows builds of gmp that wasn't needed for linux to ensure that it uses 64 bit values in various places that it might not by default, I'm in the middle of a build right now testing if that fixes any of the failures.

**Comment by daira** [comment]
Oh, if ``fq2_serializes_properly`` fails then it isn't surprising that the "point in G2" check would also fail.

**Comment by radix42** [comment]
I think that this may be where the root of the problem lies, not sure why its happening yet, though:

```
Program: D:\msys64\home\djm\zcash\src\test\test_bitcoin.exe
File: D:/msys64/home/djm/zcash/depends/x86_64-pc-mingw64/include/libsnark/gadgetlib1/gadgets/basic_gadgets.tcc, Line 50

Expression: this->pb.lc_val(packed).as_bigint().num_bits() <= bits.size()
FAIL test/test_bitcoin.exe (exit status: 3)
```

**Comment by radix42** [comment]
I just realized/discovered that the libgmp version in the msys2 distro of mingw64 is the same version that the depends system builds from source, so I'm going to try a build with that and see what happens.

**Comment by radix42** [comment]
I found the source of the trouble by doing a stand-alone build of libsnark:

```
src/algebra/fields/tests/test_bigint.cpp: In function 'void test_bigint()':
src/algebra/fields/tests/test_bigint.cpp:14:5: error: static assertion failed: unsigned long not 64-bit
     static_assert(ULONG_MAX == 0xFFFFFFFFFFFFFFFFul, "unsigned long not 64-bit");
     ^~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
```

Turns out that on Windows a long is ALWAYS 32-bits, except if you are using cygwin, in which case they built gcc to fudge things and be linux compatible. Not sure the best way forward, this will hold up windows whether the compiler is gcc or Visual Studio

**Comment by radix42** [comment]
I'm gonna do the Right Thing and convery my fork of libsnark to use all C++11 types, and go from there

**Comment by tromer** [comment]
@radix42, great! Can you do that as a clean standalone patch, and submit a pull request to libsnark? Likewise for other improvements you feel we merge into libsnark upstream.

**Comment by radix42** [comment]
yup, no problem, @tromer, I can either generate a patch once I'm done, or submit a pull request against the upstream repo, whichever works best for you

**Comment by tromer** [comment]
A pull request against upstream libsnark (master branch) would be best. Thanks!

**Comment by daira** [comment]
I think this can be closed, because the Windows port is working, and https://github.com/scipr-lab/libsnark/issues/66 is the upstream libsnark ticket.
