### ISSUE TITLE
Address generation is under specified

### ISSUE THREAD

**Issue by FiloSottile** [zcash/zcash#1995]
At 5.6.3 I read

> *apk* is a SHA-256 compression output.

There is no mention of what the input is. (The first function of 5.4.4, maybe? But then what is t?)

At 5.6.4 there is no mention of how *ask* is formed. (Random I guess?)

Finally, there is no mention of what the private key of the Curve25519 public key is. (*ask*?)

**Comment by zmanian** [comment]
Here is what I've figured out so far.

1. _ask_ is 252 random bits.

2. Curve25519 PK is the scalar mult of _ask_ * the generator point

3. _apk_ is prf_addr of _ask_ https://github.com/zcash/zcash/blob/master/src/zcash/prf.cpp#L24

**Comment by FiloSottile** [comment]
More specifically, *apk* is prf_addr(0) of *ask*. (*t* is 0.)

**Comment by FiloSottile** [comment]
*pkenc* (Curve25519 PK) is the scalar mult of **prf_addr(1)**(*ask*) * the generator point.

With this, I have working code, but it should really be called out in the spec.

**Comment by daira** [comment]
This is described in section 4.2 Key Components. To help other spec users find this, I'm adding cross references from sections 5.6.3 and 5.6.4 to section 4.2, which will be in the next revision of the spec.

**Comment by daira** [comment]
The cross references are now in the current spec (2016.0-beta-1.12).

**Comment by zmanian** [comment]
Just some additional thoughts

1. The term SHA256 Compress is not widely used. I.E. it doesn't appear in NIST documents etc. It will be helpful to have some sort of verbal description of how you get a SHA256 compression function from a SHA256 implementation. We have examples of doing this in Golang and Rust now as a result of this exercise. But this doesn't have to be protocol spec.

2. I think 5.4.4 and 5.4.6 should be cross referenced from 4.2 in addition to the others for a definition of KA.FormatPrivate and the PRF functions.

**Comment by daira** [comment]
1. Filed https://github.com/zcash/zips/issues/100
2. Will do.
