### ISSUE TITLE
Define a serialization format for viewing keys

### ISSUE THREAD

**Issue by zmanian** [zcash/zcash#1996]
Byte prefixes for the viewing key for a protected address are not defined.

when you define them, we will add them to our offline address generator.

https://github.com/FiloSottile/zcash-mini

**Comment by daira** [comment]
This doesn't depend on #406; that ticket is (now) about extensions to selective disclosure that weren't implemented in Zcash 1.0. @zmanian is I think referring to a format for the incoming viewing key, sk<sub>enc</sub>.

**Comment by daira** [comment]
Moved to https://github.com/zcash/zips/issues/101 .
