### ISSUE TITLE
Debian support for apt-transport-tor

### ISSUE THREAD

**Issue by ghost** [zcash/zcash#1998]
As a Debian user I prefer to use apt-transport-tor with the Debian onion service repositories. It would be nice if there was a Tor onion service available for apt.z.cash so I'd be able to have increased security when downloading it to my computer. This would not only hide the fact that I am installing Zcash but also keep a malicious exit node from tampering with the binary.

**Comment by ageis** [comment]
@jdoe976 Hi, we are now operating a hidden service for the package repository at http://zcaptnv5ljsxpnjt.onion/ which you may use.

Although, I think your specific concerns (about fingerprinting and tampering) should be mitigated by using tor+https:// transport with the regular apt.z.cash HTTPS repository. Malicious modification should not occur as long as the connection is encrypted end-to-end and apt is enforcing signature verification. That said, we do like Tor hidden services, so there you go!

**Comment by jdoe976** [comment]
@ageis Wow thank you, I did not expect it to happen so fast. I do know that I would be able use tor+https however I trust the security of a Tor onion service a lot more. Will this link be added to the official documentation for other users?
