### ISSUE TITLE
If zcashd finds no config file, exit with user friendly message.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#2002]
Also, provide a config file with all of the default options commented out with explanations of the option's effect.

**Comment by radix42** [comment]
One thing about the sample zcash.conf that's in the debian package right now, which does have all options in it commented out, is that if there is a blank newline in a zcash.conf, zcashd crashes when you launch it!

**Comment by bitcartel** [comment]
@radix42 I can't reproduce that behaviour with a blank newline causing a crash.  Can you upload the config file somewhere or hex dump it?  What character(s) are being used for the newline?

**Comment by radix42** [comment]
oh, maybe this was a mac specific problem

**Comment by radix42** [comment]
ok now I'm scratching my head, I can't reproduce on mac now either...maybe it was arm64...in any event, disregard this for now then
