### ISSUE TITLE
Set up Local orphan chain tip detector based on zcashd.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#2003]
This is a `zcashd` with some monitoring process that calls `getchaintips` and if any chain length is greater than K, issue an alert.

(Problem: That same tip will be reported every time, so we'll keep seeing alerts, so improve the alert system somehow.)

**Comment by bitcartel** [comment]
This detector should have a basic web ui.

**Comment by ageis** [comment]
@nathan-at-least What's the value of K? What's the condition to alert upon, is it if `branchlen > 1`?

**Comment by nathan-at-least** [comment]
Let's say `K=2` for now, and if that turns out to be too noisy, we can increase it later.
