### ISSUE TITLE
Error: wallet encryption is disabled

### ISSUE THREAD

**Issue by zz0412** [zcash/zcash#2011]
hi
`zcash-cli encryptwallet "test"`  note ：error: {"code":-16,"message":"Error: wallet encryption is disabled."}
version：zcash-1.0.4
Zcash wallet can not add password?

**Comment by arcalinea** [comment]
Hi @zz0412 , wallet encryption was disabled before launch, since we could not be fully confident in the security of this feature. See #1552 for more info. We've been working on improving the encryption scheme--to check out an open pull request, see #1983

**Comment by daira** [comment]
#1528 and #1515 give more information about the reasons why we disabled wallet encryption.
