### ISSUE TITLE
Clean up old branch names while somehow preserving history.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#202]
It would be nice if the drop-down menu of branches on github, and also the output for `git branch -a` only showed "recent, relevant" branches and excluded historical branches for tickets-now-closed, or even more ancient clutter that doesn't follow our modern conventions.

Note: It would also be nice to keep our tag namespace simple as the union of upstream tags (which appear to be only release tags) and our own tags.

Meanwhile, there's a potentially competing desire to keep a full history for posterity. If we can't find a way to meet both goals, I'm inclined to sacrifice full history on github (and I'll try to track it locally).

**Comment by nuttycom** [comment]
Important commits have been tagged, and old branches have been cleaned up. For cleaning up individual forks, the script at https://gist.github.com/sellout/36e6090d080d3fe39608c9c851569208 is useful.
