### ISSUE TITLE
zmq feature like bitcoin

### ISSUE THREAD

**Issue by ucwong** [zcash/zcash#2020]
Zcash cut the zmq feature of bitcoin?

**Comment by bitcartel** [comment]
Zcash is forked from Bitcoin 0.11.2.  ZMQ was added to a later release, 0.12.0.

**Comment by str4d** [comment]
I ported the ZMQ feature to Zcash in my Bitcore branch because the Bitcore+Insight block explorer requires it. So we *could* pull the PR in properly, which would reduce the diff between my Bitcore branch and mainline.
