### ISSUE TITLE
Allow users to specify a portion of the blockchain to scan when importing z_addresses

### ISSUE THREAD

**Issue by Voluntary-zcash** [zcash/zcash#2032]
https://github.com/zcash/zcash/pull/1978#issuecomment-273937381

Bearing in mind that some users may know in advance that the z_addresses they're importing only have transactions from a particular point in the blockchain, give them the option to avoid needlessly scanning prior blocks.

**Comment by nathan-at-least** [comment]
This sounds like it could be an RPC interface option to `z_importkey`.
