### ISSUE TITLE
Unified documentation for zcash-cli

### ISSUE THREAD

**Issue by ioptio** [zcash/zcash#2034]
There seems to be general confusion regarding Zcash and upstream RPC. It would be nice to have unified documentation of these calls - extending the payment api doc: https://github.com/zcash/zcash/blob/v1.0.0-beta1/doc/payment-api.md

**Comment by amitkumarj441** [comment]
@ioptio Alright! 
How can I start with this task and in which folder should I initiate the PR?

**Comment by bitcartel** [comment]
@ioptio By 'unified' do you mean combining upstream RPC with Z_ RPC calls?  Is it sufficient to point to upstream RPC documentation on the Bitcoin Wiki and Bitcoin.org (for version 0.11.2 which we forked from)?  Or perhaps make a table listing the differences between upstream and zcash RPC - this would include listing/linking the payment api z_calls as well as bitcoin rpc calls where we change behaviour e.g. extra json output related to joinsplits.

**Comment by ioptio** [comment]
@bitcartel I was just thinking a single, unified document with all commands so we don't have to keep linking to upstream rpc.

**Comment by daira** [comment]
+1 on a single unified document, but let's mark the changes from upstream (e.g. in a different colour, as the protocol spec does for changes from Zerocash).

**Comment by ioptio** [comment]
I'm starting this project... could take a little while. My process is comparing https://bitcoin.org/en/developer-reference with the help references for each command, then I'll add in the zcash specific commands and post for developer review before publishing.

**Comment by ioptio** [comment]
Related https://github.com/zcash/zcash/pull/3734

**Comment by ioptio** [comment]
Moving this issue to the documentation repo: https://gitlab.com/zcash-docs/zcash-docs/issues/44
