### ISSUE TITLE
Add experimental feature framework to config system.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#2035]
We want to have a global opt-in to enable experimental features, plus an 'experimental namespace' for specific feature parameters.

**Comment by str4d** [comment]
This could tie in well with having "beta" or "edge" builds of zcashd that some users test with. I could see us enabling the global experimental flag by default for "edge" builds (that are always up-to-date with master), and maybe also for "beta" releases? Or would two levels be useful, where larger new features start as experimental, and then become medium-stable in a "beta" but still requiring a "beta" flag? (Setting "experimental" would imply "beta")

**Comment by daira** [comment]
Let's not overcomplicate things; I doubt we need two levels, and if we do we can always add that later.

**Comment by bitcartel** [comment]
Add example e.g. developer wallet enc.
