### ISSUE TITLE
Add secret change addresses.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#2037]
In order to improve a privacy leak in the 'payment disclosure' feature, we need to prevent anyone from learning change addresses, because knowing both the payment disclosure and the change address will reveal a js output's plaintext.

**Comment by daira** [comment]
We could generate the change address a<sup>change</sup><sub>sk</sub> as PRF<sup>addr</sup><sub>a<sub>sk</sub></sub>(2).

**Comment by nathan-at-least** [comment]
We're leaning towards an alternative which is a new encryption key derivation for change outputs, rather than separate change addresses. #2102

**Comment by nuttycom** [comment]
This is fixed by use of separate derivation for change addresses as part of ZIP 316
