### ISSUE TITLE
Allow users to pick their own weak passwords for deterministic secret seeds. (strawman)

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#2040]
This ticket exists just to make it really clear we're not proposing a dangerous and non-useful idea. The term 'brainwallet' in #18 has confused people into thinking someone was proposing this bad idea.

**Comment by leafcutterant** [comment]
"Pick their own" can be defined in various ways.

If the "password" (but I would pivot towards calling it a passphrase) contains sufficient entropy - for example, it's a securely generated 12-word BIP39 mnemonic from 128 bits of entropy from a trustworthy source - why shouldn't I be able to pick that?

The use case situations I believe are wider than what you have considered.
