### ISSUE TITLE
Debian binaries repo - invalid signature

### ISSUE THREAD

**Issue by mrplow** [zcash/zcash#2041]
### Describe the issue
Bad Debian apt signature

### Can you reliably reproduce the issue?
1. follow steps on https://github.com/zcash/zcash/wiki/Debian-binary-packages
2. sudo apt update

### Expected behaviour
no invalid signature

### Actual behaviour + errors
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://apt.z.cash jessie Release: The following signatures were invalid: BADSIG 63C4A2169C1B2FA2 Zcash Master Signing Key
W: Failed to fetch https://apt.z.cash/dists/jessie/Release.gpg  The following signatures were invalid: BADSIG 63C4A2169C1B2FA2 Zcash Master Signing Key

### The version of Zcash you were using:
Zcash Daemon version v1.0.4

**Comment by ebfull** [comment]
This was fixed a couple hours ago, can you let us know if you're still having trouble?

**Comment by mrplow** [comment]
Working as expected now
