### ISSUE TITLE
Extend `zrpc_unsafe` logging by including `z_sendmany` arguments and result status.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#2057]
- make it grep-friendly by putting the info on a single line.
- include opid on each line produced.

**Comment by nathan-at-least** [comment]
Note, this should address the user request in #1937. Let's check with @SterL if this is the case.

**Comment by SterL** [comment]
Yep! I think this will do exactly what I need. Thank you zcash team!

**Comment by bitcartel** [comment]
https://github.com/zcash/zcash/pull/2058
