### ISSUE TITLE
Refactor Logging API to facilitate mock/fake-based unit testing.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#2059]
Let's make a mockable (or perhaps a fake-able) API for logging so that unit tests can make assertions about log output. I'm using roughly the distinction in [The Difference Between Mocks and Stubs](https://www.martinfowler.com/articles/mocksArentStubs.html#TheDifferenceBetweenMocksAndStubs) here (and in other tickets).

The first step is to refactor the logging API to facilitate dependency injection. The second is to provide a useful mock or fake abstraction. I'm guessing a fake which logs to a `StringStream`, which test code can then retrieve the in-memory bytes from, would be the easiest API for most needs.

For the first step to refactor for dependency injection, I think there are two approaches:

1. Introduce a logging interface abstraction, then pass an instance of it all thoughout the codebase. This would be quite a tedious and large-impact change, but all of the individual changes should be fairly straightforward and unproblematic. Then change all call sites to use the local parameter or member.
2. Introduce a logging interface abstraction, then replace the global functions/macros with a standard global instance. No construction sites need to be updated. All call sites can be updated in a similar manner, so maybe even search-and-replace is good enough.

When testing, approach 1 is much more 'direct / natural' since you just pass the mock/fake instance to whichever component is under test, whereas approach 2 needs some kind of bracketed global variable swapping (and can't handle multiple threads).

I prefer approach 1, even though it has a large number of affected lines.

Prioritization: This is _necessary_ if we want deterministic unit tests that make assertions about log output, so it's only as urgent as those assertions. (The bottom of this PR review comment, https://github.com/zcash/zcash/pull/2058#pullrequestreview-19491058, is an example of this kind of assertion.) This is _helpful_ whenever we want deterministic tests of 'large scale' components that do logging and we don't want to clutter up unittest output or write to temporary files or do other such hacks.

**Comment by nuttycom** [comment]
This is probably not worth spending the time on.

**Comment by str4d** [comment]
Closing as lacking a motivating use case. That being said, if someone wanted to do this, it could probably now be done by having the test harness install a custom `tracing` subscriber that stored the globally-logged logs in memory and provided some way to inspect them.
