### ISSUE TITLE
~/.zcash/zcash.conf nproc value results in genproclimit 0 and localsolps 0

### ISSUE THREAD

**Issue by mk6032** [zcash/zcash#2062]
### Describe the issue
Wiki page ( https://github.com/zcash/zcash/wiki/1.0-User-Guide ) states ..
---
Enabling CPU mining:

If you want to enable CPU mining, run these commands:

$ echo 'gen=1' >> ~/.zcash/zcash.conf
$ echo "genproclimit=$(nproc)" >> ~/.zcash/zcash.conf
---

If one follows these instructions the zcashd daemon doesn't seem to pick up the nproc value. The result is zcashd will report "genproclimit" : 0" and "localsolps" will always be 0. 

### Can you reliably reproduce the issue?
Yes.

#### If so, please list the steps to reproduce below:
1. $ echo "genproclimit=$(nproc)" >> ~/.zcash/zcash.conf
2. start zcashd

### Expected behaviour
Number of processors defined as a variable. 

### Actual behaviour + errors
Number of processors is a empty value.

### The version of Zcash you were using:
Zcash Daemon version v1.0.5 ( zcash-1.0.0-beta2-amd64.deb )

### Machine specs:
- OS name + version: Debian 8
- CPU: Tested on both Intel i7 and AMD FX-8120
- RAM: 16GB
- Disk size: N/A
- Disk Type (HD/SDD): N/A
- Linux kernel version (uname -a): 3.16.0-4-amd64
- Compiler version (gcc -version): N/A

**Comment by daira** [comment]
``$(nproc)`` might not be defined on all systems. You can replace it manually with the number of cores on your system. I'll update the User Guide to note this.

**Comment by daira** [comment]
We could improve this by allowing ``genproclimit`` to be some flag value such as -1 or ``all`` that dynamically finds the number of cores, e.g. using ``omp_get_num_procs()``.

**Comment by str4d** [comment]
@daira `-genproclimit=-1` already does this.

**Comment by mk6032** [comment]
@daira Yeah, it works perfectly when you define it static. I just wanted to point that out in case others don't figure it out quickly and complain of localsolps 0. It looks like there were a few already. Thanks for all your hard work by the way! I love the direction this project is heading.

**Comment by bitcartel** [comment]
Note that `$(nproc)` is also featured in the user guide for building:
`./zcutil/build.sh -j$(nproc)`

**Comment by daira** [comment]
Should we change that line in the docs to:
```
$ echo "genproclimit=-1" >> ~/.zcash/zcash.conf
```
?

**Comment by arcalinea** [comment]
Using `genproclimit=-1` is suggested as a note in the user guide, but should it be the default recommendation?

**Comment by arcalinea** [comment]
Changed documentation to use -1 as default, closing issue.
