### ISSUE TITLE
aclocal-1.14 needed but there is 1.15 in system , why can't use in some system.

### ISSUE THREAD

**Issue by ucwong** [zcash/zcash#2065]
in some ubuntu systems I occurs this problem, can I modify the version of aclocal?

CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /opt/zcash/build-aux/missing aclocal-1.14 -I build-aux/m4
/opt/zcash/build-aux/missing: line 81: aclocal-1.14: command not found
WARNING: 'aclocal-1.14' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
Makefile:562: recipe for target 'aclocal.m4' failed
make: *** [aclocal.m4] Error 127

**Comment by bitcartel** [comment]
Did you follow the instructions on the user guide to build?  You need to install autoconf as shown here:
```
$ sudo apt-get install \
      build-essential pkg-config libc6-dev m4 g++-multilib \
      autoconf libtool ncurses-dev unzip git python \
      zlib1g-dev wget bsdmainutils automake
```

**Comment by ucwong** [comment]
@bitcartel I just do the upgrade operation. but failed in some ubuntu systems.

**Comment by ucwong** [comment]
![image](https://cloud.githubusercontent.com/assets/22344498/22680201/b83319ca-ed41-11e6-9fa8-672d5540588a.png)

**Comment by daira** [comment]
aclocal-1.15 works for me. I think ./configure is supposed to detect the version on your system. What are the distributions on which it fails or succeeds, and can you attach the full build output of a failing build?

**Comment by ioptio** [comment]
We're closing this due to timeout. Feel free to reopen if problem persists, however.
