### ISSUE TITLE
Add ability to pass in autoconf options to build.sh

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#2066]
Users may want to create custom builds with certain features enabled or disabled.

Currently they can do so by modifying build.sh.

Let's add an option so that users can simply pass in autoconf options when calling build.sh.

**Comment by radix42** [comment]
Fyi right now I have separate scripts to build on mac and windows, I'd need to be able to override all the options passed to ./configure in build.sh to be able to use it on other platforms.

**Comment by daira** [comment]
@radix42 I think this is orthogonal to needing separate build scripts per platform (although it would be useful if each script supported passing in autoconf options, not just the Linux one).

**Comment by radix42** [comment]
yes, I agree on both points

**Comment by str4d** [comment]
In #2120 I am adding an environment variable `CONFIGURE_FLAGS` for passing in arbitrary flags. This should be sufficient until we remove `build.sh` entirely (#58).
