### ISSUE TITLE
Zclassic has the same network magic values

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2067]
https://github.com/z-classic/zclassic/issues/25

Perhaps we (and they) should document that a client intended to be running on one network should avoid adding nodes from the other. I think there's little risk of actual harm because the genesis blocks are different, but it could trigger fork detection or other confusing behaviour.

**Comment by bitcartel** [comment]
They did change the mainnet and testnet ports so that mitigates the risk of a node connecting, although not completely as someone could configure a node to use any port they wish.

**Comment by str4d** [comment]
Another option would be for them to change [the client name](https://github.com/z-classic/zclassic/blob/master/src/clientversion.cpp#L22) (which should be done anyway, to distinguish their differing feature-set), and then add a standard rule to drop connections when the client name is `MagicBean`.

**Comment by aayanl** [comment]
ACK, since changing it would cause a hard fork, phasing it in with 2 mo the wouldn't be that hard

**Comment by daira** [comment]
They seem to have changed the ports again for Zclassic 1.0.8: https://github.com/z-classic/zclassic/pull/81/files

**Comment by ioptio** [comment]
Moving this issue over to the documentation repo: https://gitlab.com/zcash-docs/zcash-docs/issues/42
