### ISSUE TITLE
Debian update broken

### ISSUE THREAD

**Issue by JamborJan** [zcash/zcash#2079]
### Describe the issue
I have installed zcash some time ago like described here: https://github.com/zcash/zcash/wiki/Debian-binary-packages. Now I'm not able to update the package via `apt-get`.

#### If so, please list the steps to reproduce below:
1. `sudo apt-get update` works fine
2. `sudo apt-get upgrade` times out when trying to load from apt.z.cash
![img_2920](https://cloud.githubusercontent.com/assets/7508960/22804280/a53f634a-ef18-11e6-8ee6-a92fb5bf3a68.PNG)

### Expected behaviour
`sudo apt-get upgrade` should upgrade zcash.

### The version of Zcash you were using:
1.0.3

### Machine specs:
- OS name + version: Debian 8
- CPU: 2 (virtual)
- RAM: 8 (virtual)
- Disk size: 19GB, 15GB free
- Disk Type (HD/SDD): HD (virtual) 
- Linux kernel version (uname -a): 3.16.0-4-amd64
- Compiler version (gcc -version): na

### Do you have a back up of `~/.zcash` directory and/or take a VM snapshot?
- I can take snapshots at any time

**Comment by ageis** [comment]
@JamborJan can you share your sources.list? Is that the only server in there?

**Comment by JamborJan** [comment]
I'm using a clean and minimalistic setup for this so the default `/etc/apt/sources.list` is:

```
# deb cdrom:[Debian GNU/Linux 8.6.0 _Jessie_ - Official amd64 NETINST Binary-1 20160917-14:20]/ jessie main

#deb cdrom:[Debian GNU/Linux 8.6.0 _Jessie_ - Official amd64 NETINST Binary-1 20160917-14:20]/ jessie main

deb http://ftp.ch.debian.org/debian/ jessie main
deb-src http://ftp.ch.debian.org/debian/ jessie main

deb http://security.debian.org/ jessie/updates main
deb-src http://security.debian.org/ jessie/updates main

# jessie-updates, previously known as 'volatile'
deb http://ftp.ch.debian.org/debian/ jessie-updates main
deb-src http://ftp.ch.debian.org/debian/ jessie-updates main
```

As mentioned in the documentation here: https://github.com/zcash/zcash/wiki/Debian-binary-packages I have run

```
echo "deb [arch=amd64] https://apt.z.cash/ jessie main" | sudo tee /etc/apt/sources.list.d/zcash.list
```

to add the sources for zcash. I also tried to add the line to `/etc/apt/sources.list` like this:

```
# zcash
deb https://apt.z.cash/ jessie main
```

which obviously makes no difference.

**Comment by daira** [comment]
Does ``sudo apt-get install --upgrade zcash`` work?

**Comment by JamborJan** [comment]
Hey @daira, somehow that worked. Thanks a lot. `zcash` was the only not up to date package also before. Only by explicitly mentionning the package name solved the issue. How can that be possible?

**Comment by daira** [comment]
I'm not sure. There may be something wrong with your apt configuration that is not specific to zcash. When we release 1.0.6 (some time today), can you try ``sudo apt-get upgrade`` again to see whether the problem persists?

**Comment by JamborJan** [comment]
I sure can test it. Would be strange if its a reason in my config as it is a fresh Debian setup with no specific changes.

**Comment by ageis** [comment]
@JamborJan While the fetching stalled at 0%, there is a chance it may not be related to Zcash. Your apt cache was already aware there's an upgrade available for Zcash, but it might be trying to load something from somewhere else (who knows what else is going on under the hood), in essence a networking issue.

**Comment by JamborJan** [comment]
I absoluetly see your point @ageis and if I wouldn't see it directly in front of me I wouldn't belive it.

Basis is an empty minimalistic Debian setup on an virtual machine.

`sudo apt-get upgrade` doesn't work, no matter if `zcash` is the only package which is in the update or not.

`sudo apt-get upgrade zcash` works.

From my point of view we can close this issue. I know how to solve the problem for me now.
