### ISSUE TITLE
libzmq not yet uploaded into z.cash/depends-sources?

### ISSUE THREAD

**Issue by Maroc-OS** [zcash/zcash#2091]
file zeromq-4.2.1.tar.gz not found on z.cash mirror and not falling back to github link to download from. because of the default response from z.cash in not 404 ?

maybe am wrong about this last, but the package is not uploaded or it's name is not valid

edit : 

__this also happens for libsnark and maybe other archives__ : libsnark working now i don't know if it was my mistake

**Comment by Maroc-OS** [comment]
cat $PATH/zcash/depends/work/download/zeromq-4.2.1/zeromq-4.2.1.tar.gz.temp 

gives an html page output

**Comment by bitcartel** [comment]
@Maroc-OS Should be up now, can you try again and let us know if the issue is resolved?  Thanks.

**Comment by Maroc-OS** [comment]
Thank you, ll try in a minute

**Comment by Maroc-OS** [comment]
Great it's working now. thank you. am gonna close this issue.
