### ISSUE TITLE
v1.0.6 - python qa tests don't run on Bash on Windows (windows subsystem for linux)

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#2097]
System: Windows 10 Professional, Bash on Windows (using default Ubuntu 14.04.5 image)

What works:

- Zcash v1.0.6 builds, runs and is able to send/receive shielded transactions.
- test_bitcoin passes
- zcash-gtest passes

What doesn't work:

- python qa tests don't run, appear to hang, probably environment related.

Note: Zcash on Windows is not officially supported.  This ticket simply serves as a reminder for those interested.

**Comment by str4d** [comment]
This will likely be improved when the upstream PRs migrating the QA tests completely to Python 3 are merged (#2074).

**Comment by Eirik0** [comment]
I am able to run the python tests using WSL. Perhaps something has changed since this ticket was filed. Closing.
