### ISSUE TITLE
"KDF Tweak" method of preventing information leakage from payment disclosure

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2102]
(This is an alternative to #2037.)

The proposed design for payment disclosure (#2036) reveals both outputs of a given JoinSplit, which is an information leak. It's sufficient to ensure that the second output is only used for change (which is the case for our current and [proposed](https://github.com/zcash/zcash/issues/1360) multijoinsplit construction algorithms), and to solve this information leak only for change payments.

In #2037, it was proposed to do this by having a secret change address for each "ordinary" address, which would have the effect of making one of the inputs to the KDF for the change payment a secret. This would prevent an adversary from being able to derive the secret key K<sup>enc</sup><sub>i</sub> for the change payment. (See section 4.10.1 of the protocol spec, where pk<sub>enc,i</sub> is a KDF input.) However, this has two main disadvantages:
* It is conceptually more complex, both at the protocol level and for end-users, to have separate change addresses rather than just sending change back to the original address. If we tried to hide the fact that there is a separate change address from end-users (whether by deriving the change spending key from the original spending key, or bundling them together), there would inevitably be abstraction leaks.
* When scanning transactions, a wallet must trial-decrypt for each spending key it holds, which would be double the number of keys in this approach, and therefore double the number of Curve25519 multiplications. This is important because scanning is already a significant performance bottleneck (see e.g. #1749).

@ebfull suggested the following clever idea: instead of using a separate change address, we can tweak the KDF so that in the case of a change payment, it takes sk<sub>enc,i</sub> as an input instead of pk<sub>enc,i</sub>. (For example, use Blake2b-256("ZcashKDF" || (i-1) || [0]<sup>8</sup> || "Change", hSig || sharedSecret<sub>i</sub> || epk || sk<sub>enc,i</sub>).) This has the effect that even if esk is known (e.g. from a payment disclosure), the change note ciphertext can only be decrypted with knowledge of the viewing key sk<sub>enc,i</sub>. The wallet would then trial-decrypt each note ciphertext with both KDFs, but only one address and one Curve25519 multiplication (per JoinSplit per address) would be needed.

**Comment by daira** [comment]
Note that it is still possible to distinguish that the second note output is not using the old KDF with a known output address. This is not really a problem; the sender of a transaction will only produce payment disclosures for transactions that use the new KDF for change. (It needs to remember esk, so payment disclosures can't be produced until the wallet software has been upgraded.)

**Comment by str4d** [comment]
#2103 currently implements the simplest form of this idea (that @ebfull and I discussed in our pairing): use `sk_enc` instead of `pk_enc` in the existing KDF. Using a more substantially-different KDF is certainly possible, but will result in a strictly-larger implementation change.

**Comment by bitcartel** [comment]
The tweak may not be sufficient; see here: https://github.com/zcash/zcash/issues/2036#issuecomment-282357855

**Comment by tromer** [comment]
Is there a ZIP and `protocol.pdf` change for this?

**Comment by daira** [comment]
This is obsolete, since it applied to Sprout and we're not going to make any consensus changes related to Sprout at this point.
