### ISSUE TITLE
"help" on RPC commands is printing output as error string

### ISSUE THREAD

**Issue by arcalinea** [zcash/zcash#2108]
### Expected behaviour
Help text prints out, properly formatted, when user enters `./src/zcash-cli <command> help`

### Actual behaviour + errors
Prints as error message, not very legible

`$ ./src/zcash-cli getpeerinfo help`
error: {"code":-1,"message":"getpeerinfo\n\nReturns data about each connected network node as a json array of objects.\n\nbResult:\n[\n  {\n    \"id\": n,                   (numeric) Peer index\n    \"addr\":\"host:port\",      (string) The ip address and port of the peer\n    \"addrlocal\":\"ip:port\",   (string) local address\n    \"services\":\"xxxxxxxxxxxxxxxx\",   (string) The services offered\n    \"lastsend\": ttt,           (numeric) The time in seconds since epoch (Jan 1 1970 GMT) of the last send\n    \"lastrecv\": ttt,           (numeric) The time in seconds since epoch (Jan 1 1970 GMT) of the last receive\n    \"bytessent\": n,            (numeric) The total bytes sent\n    \"bytesrecv\": n,            (numeric) The total bytes received\n    \"conntime\": ttt,           (numeric) The connection time in seconds since epoch (Jan 1 1970 GMT)\n    \"timeoffset\": ttt,         (numeric) The time offset in seconds\n    \"pingtime\": n,             (numeric) ping time\n    \"pingwait\": n,             (numeric) ping wait\n    \"version\": v,              (numeric) The peer version, such as 170002\n    \"subver\": \"/MagicBean:x.y.z[-v]/\",  (string) The string version\n    \"inbound\": true|false,     (boolean) Inbound (true) or Outbound (false)\n    \"startingheight\": n,       (numeric) The starting height (block) of the peer\n    \"banscore\": n,             (numeric) The ban score\n    \"synced_headers\": n,       (numeric) The last header we have in common with this peer\n    \"synced_blocks\": n,        (numeric) The last block we have in common with this peer\n    \"inflight\": [\n       n,                        (numeric) The heights of blocks we're currently asking from this peer\n       ...\n    ]\n  }\n  ,...\n]\n\nExamples:\n> zcash-cli getpeerinfo \n> curl --user myusername --data-binary '{\"jsonrpc\": \"1.0\", \"id\":\"curltest\", \"method\": \"getpeerinfo\", \"params\": [] }' -H 'content-type: text/plain;' http://127.0.0.1:8232/\n"}

### The version of Zcash you were using:
1.0.4

**Comment by str4d** [comment]
The correct command for accessing properly-formatted help is `./src/zcash-cli help <command>`. I'm not sure we can reliably solve this particular case, because `./src/zcash-cli <command> <stringarg>` is a common pattern, and therefore we must return an error. The best we could do is maybe override `zcash-cli`'s rendering of errors in the CLI, but even that is error-prone because we can't assume that just because `zcash-cli` is run in the CLI (as opposed to a backend script), the error message will go to the console and not be sent to another process.

**Comment by arcalinea** [comment]
Ok, perhaps the solution to this is just better documentation. It's probably a common user error--I've heard other people complain about it, and obviously I was doing it myself. :sweat_smile:

**Comment by arcalinea** [comment]
Improved documentation on 1.0 User Guide and Troubleshooting FAQ, closing issue.

**Comment by daira** [comment]
https://github.com/zcash/zcash/pull/2099/commits/83d6e40fb3e5ba041c7ca11961c582f6646beb68 will improve this.
