### ISSUE TITLE
Block progress measurement never reaches 1.0.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#2111]
In `debug.log` I see lines like this:

> 2017-02-20 07:03:53 UpdateTip: new best=0000000069f2e8771d96e59e30803998041af9c69e823547d9d90d53f3ef07ab  height=66212  log2_work=48.619301  tx=320573  date=2017-02-20 07:03:44 progress=0.999998  cache=45.1MiB(2353tx)

I verify that https://zcha.in and other nodes have the same block height, but `progress` is still just barely less than 1.0. Bitcoin-core 0.13.2 definitely shows `progress=1.000000` in the equivalent situation.

I smell an off-by-one bug here.

**Comment by daira** [comment]
Zcash's current block height is 66253, and 66252/66253 ~= 0.9999849... which would round to 0.999985. So progress=0.999998 for Zcash is not consistent with this being a straightforward off-by-one error.

(Bitcoin's current block height is 453873. If it had an off-by-one error, 453872/453873 ~= 0.9999977... which would round to 0.999998, but I assume that's a coincidence.)

**Comment by nathan-at-least** [comment]
Hm. Curious. I'll experiment with a patch on that node that LogPrints the consistuent parts of that calculation sometime (not a high priority for me, atm).

**Comment by nathan-at-least** [comment]
Next step: hunt for upstream merges that fix this. Anecdotally, it doesn't look like 0.13.2 has this problem.

**Comment by daira** [comment]
I see progress reach 1.000000. One possible explanation is that this was more likely to occur when there were fewer than 1000000 blocks (the Zcash mainnet chain reached that height in October 2020). In any case, this is not a priority.
