### ISSUE TITLE
Upgrade testnet to fix bug in test and update fr addresses

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#2113]
Due to a bug in a unit test used to create addresses, the testnet fr addresses did not have their corresponding keys retained.

Address 1 t2UNzUUx8mWBCRYPRezvA363EYXyEpHokyi was used between blocks 1-17708
Address 2 t2N9PH9Wk9xjqYg9iin1Ua3aekJqfAtE543 was used between blocks 17709 - 35417 (count of 17709)
Address 3 t2NGQjYMQhFndDHguvUw4wZdNdsssA6K7x2 is being used for blocks 35418 - 53126 (count of 17709)
Address 4 will be used from block 53127 (based on historical rate of blocks, estimated to arrive around 20th March 2017)

Testnet is currently around block 42650 - see https://explorer.testnet.z.cash/

This PR fixes the bug and introduces new addresses 4-48.  This will change consensus so all testnet nodes are required to update.  To be more conservative so users have more time to upgrade their testnet nodes, we could start with address 5.

If this PR is merged for 1.0.7,
- testnet.z.cash will be upgraded to 1.0.7
- testnet alert will be sent, putting testnet nodes running 1.0.0-1.0.6 into safe mode (wallet rpc commands will be disabled), to encourage users to upgrade

**Comment by daira** [comment]
I think it's fine to change consensus from address 4. Reviewing now.

**Comment by daira** [comment]
Reviewed; needs a test fix.

**Comment by daira** [comment]
Review needed for https://github.com/zcash/zips/pull/116

**Comment by daira** [comment]
In the engineering meeting, we decided that:
* the roughly two weeks between the 1.0.7 release and the expected fork block is sufficient time for testnet users to upgrade;
* we should do a dry run of the alert on testnet.

**Comment by bitcartel** [comment]
@daira 
- Should the protocol version be bumped up?  This would impact both mainnet and testnet since they share the same constant.
- Should 1.0.7 nodes running on testnet refuse connection from older nodes (whether by version string or protocol version) when block >= 53127 ?

**Comment by bitcartel** [comment]
Testnet alert #1 sent and documented:  https://github.com/zcash/zcash/wiki/specification

**Comment by daira** [comment]
* I think it is too complicated to have different protocol versions for testnet and mainnet, so no, that should not be bumped. (Strictly speaking bumping the version shouldn't affect mainnet, as long as the minimum required version is kept the same, however, there's no need to risk it for this.)
* The old nodes should detect a chain fork anyway, I think, and I'd like to see whether that actually works.

**Comment by bitcartel** [comment]
Confirming that a fresh install of testnet node sees alert 1:
`This is just a test of the alert system on testnet.  Zcash 1.0.7 will be released soon which upgrades testnet.  Come chat at: https://chat.zcashcommunity.com`
