### ISSUE TITLE
Host a Testnet faucet to help developers building zcash related projects

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#2119]
Find an open-source faucet we can adapt for use with Testnet.

A good candidate would:
- have minimal system requirements
- be easy to install
- feature a small code base for security review

Another option would be to donate Testnet coins to an existing community run faucet which has high availability.

**Comment by arcalinea** [comment]
Zeropond runs a faucet, but I've never seen any ZEC in it: http://faucet.zeropond.com/

**Comment by lustr0** [comment]
I'm willing to host a faucet (on Zchain) - I'm not particularly familiar with faucet software, however; were you looking at any existing options (or is anyone familiar with one)? Looked around Github but didn't see anything particularly promising.

It would probably be beneficial to have the faucet support z-addresses, which will likely require some modification.

**Comment by arcalinea** [comment]
@lustr0 Zeropond is willing to share their code for this currently abandoned testnet faucet:  http://faucet.zeropond.com/, will let you know when they put it up on Github :)

**Comment by arcalinea** [comment]
@lustr0 Here's the testnet faucet code, I forked the repo from 5a1t and am intending on making a few changes: https://github.com/arcalinea/zfaucet  

Would be happy to collaborate on putting this up, you can ping me on the[ community chat](https://chat.zcashcommunity.com/home) @arcalinea

**Comment by arcalinea** [comment]
Testnet faucet is up and running, so we can close this issue: https://github.com/zcash/zfaucet

ZECC zfaucet repo is here: https://github.com/zcash/zfaucet

I improved the documentation, should be easy for people to fork and run their own faucets.
