### ISSUE TITLE
zcashd rpc calling not work

### ISSUE THREAD

**Issue by AtomicProject** [zcash/zcash#2122]
i am trying to setup zcash payment method in a website i setup zcashd daemon on server but rpc calling is not work when i call rpc to show a blank page any one here to help: 

Here is zcash.conf details which is use

server=1
daemon=1
listen=1
rpcuser=zcashrpc
rpcpassword=***Hiden***
rpcport=8232
txindex=1
enableaccounts=1
addnode=mainnet.z.cash

**Comment by bitcartel** [comment]
If you are accessing zcashd from a different computer, you need to:
- set option rpcallowip in zcash.conf 
- open port 8232 on your server

Note security considerations when exposing the RPC interface over the internet (for both Zcash and upstream Bitcoin):
https://github.com/zcash/zcash/blob/master/doc/security-warnings.md

**Comment by daira** [comment]
@AtomicProject did @bitcartel's reply help you to solve the issue?

**Comment by AtomicProject** [comment]
@daira no but i am also a developer i try to solved it but its same problem if you have any idea please share

**Comment by daira** [comment]
What tool are you using to make the HTTP request? Does zcash-cli work?

**Comment by arcalinea** [comment]
@AtomicProject Did you resolve this issue, or is there any other information we could use to figure out what's going on? 

Leaving this issue open for a few more days, then timing out.

**Comment by arcalinea** [comment]
Closing this issue, if the problem recurs after using @bitcartel's suggestions feel free to re-open
