### ISSUE TITLE
Enable interactive questions to be answered on metrics screen

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#2131]
See #2095 for motivation.

**Comment by nathan-at-least** [comment]
I'm anti-prompts of any sort anyway, which I consider an antipattern for daemons. If there are other prompts I think we should remove them. If we really really need to prompt the user for something, it needs to be done in a way that's compatible with all user interfaces, including third party GUIs, which suggests an RPC interface issue, to me.

**Comment by nuttycom** [comment]
Closing as wontfix; any interactive functionality should be performed via zcash-cli or the RPC interface.
