### ISSUE TITLE
Add log message directing users to see our security guide.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#2142]
Add a snippet to the copyright notice text (so that it appears in both the logfile and `zcash-cli --help` for example) with this text:

> In order to ensure you are adequately protecting your privacy when using Zcash, please see https://z.cash/support/security.html

That page needs to be updated with sufficient user education, including what is necessary to describe about IP address privacy (which this ticket originally focused on). 

** Old ticket contents follow **

> !!!WARNING!!!! Zcash by itself only protects ledger information privacy. Without *also* using strong IP address privacy protection, such as Tor or I2P, you are at a high-risk of being identified or located based on your Zcash behavior. Please visit https://z.cash/support/security.html for a basic privacy overview.

This is because network observers (without too much effort/infrastructure) can narrow down the originating IP address of a newly generated transaction. By combining this with other metadata, privacy can be quickly compromised.

Example scenario: Citizens in a repressive regime wish to donate funds to a democracy activism organization which is being persecuted by local authorities. The organization advertises the total donations they have received. The local authorities observe the network traffic of Zcash and correlate every emitted transaction to an IP address. When they see the donation total increase on the organization's website, they infer the donator used one of the IPs which recently emitted a transaction, and they discover the physical address of the donator.

**Comment by bitcartel** [comment]
> In order to ensure you are adequately protecting your privacy when using Zcash, please see https://z.cash/support/security.html

@nathan-at-least How about something like:

`To protect your privacy when using Zcash, help and tutorials are available at: https://z.cash/support/privacy.html`

**Comment by daira** [comment]
I think that's not strong enough. I suggest something like:

To understand the privacy protections of Zcash, their limitations, and what you need to do to ensure that your privacy is not compromised, please see the help and tutorials available at: https://z.cash/support/privacy.html

**Comment by arcalinea** [comment]
ping @nathan-at-least 

Are we aiming for a PR for this to be included in 1.0.7? If so we'll need it soon

**Comment by daira** [comment]
@nathan-at-least wrote:
> Example scenario: Citizens in a repressive regime wish to donate funds to a democracy activism organization which is being persecuted by local authorities. The organization advertises the total donations they have received. The local authorities observe the network traffic of Zcash and correlate every emitted transaction to an IP address. When they see the donation total increase on the organization's website, they infer the donator used one of the IPs which recently emitted a transaction, and they discover the physical address of the donator.

So, Tor or I2P do not actually help against such an adversary. They don't add significant latency, and therefore any end-to-end timing correlation will be preserved. In order to effectively increase the anonymity set toward a time-correlating eavesdropper, the payment recipient should wait for a random number of blocks before revealing or doing anything that depends on having received the payment.

**Comment by arcalinea** [comment]
This is waiting on security page update on website, I believe

**Comment by daira** [comment]
This is no longer blocked; the security page is up.

**Comment by arcalinea** [comment]
@nathan `zcash-cli --help` doesn't currently display a copyright notice

**Comment by str4d** [comment]
I believe @nathan-at-least was referring to `zcash-cli --version`.

**Comment by arcalinea** [comment]
Ah ok, thanks. I'm submitting a PR for this

**Comment by tromer** [comment]
#2206 suggests to show privacy-related alerts in the metrics screen, for example, whenever the network connection doesn't use Tor/I2P.

**Comment by daira** [comment]
Fixed by #2203.
