### ISSUE TITLE
CI: run "make check" on the gmp library built by depends

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2144]
libgmp prints this when it is built:
```
+-------------------------------------------------------------+
| CAUTION:                                                    |
|                                                             |
| If you have not already run "make check", then we strongly  |
| recommend you do so.                                        |
|                                                             |
| GMP has been carefully tested by its authors, but compilers |
| are all too often released with serious bugs.  GMP tends to |
| explore interesting corners in compilers and has hit bugs   |
| on quite a few occasions.                                   |
|                                                             |
+-------------------------------------------------------------+
```

We should run "make check" for gmp on the CI server, at least, and possibly every time it is built if the tests complete fast enough. (Caveat: I don't know how long the tests take.)

**Comment by str4d** [comment]
We currently don't have a nice way to trigger tests of dependencies. If we did, we would realistically only want to run it whenever we change either the dependencies themselves or the CI workers (to check the tests still pass on the updated worker environment).

**Comment by daira** [comment]
What I'd like is to be able to write something like "@‌zkbot try gmp" to run the gmp tests, or "@‌zkbot try deps" to run all of the dependency tests.

**Comment by daira** [comment]
The gmp dependency was removed with libsnark, in #4060.
