### ISSUE TITLE
Pause mining during joinsplit creation w/out unnecessary subsystem coupling

### ISSUE THREAD

**Issue by arcalinea** [zcash/zcash#2145]
@aniemerg's PR #1932 was merged as a temporary/partial solution to ticket #1522, but it would be best to pause mining 
+ outside of the async operation z_sendmandy
+ in a way that was compartmentalized so that the async operation does not need to know or care about the miner
+ that takes into account race conditions which could be caused by parallel joinsplits. Possibly with an atomic counter that the halt signal handler increments and the resume signal handler decrements?

From @bitcartel's comment:

> **Concept: Design Pattern**

> Why should an async operation care or even know about the miner? We should try to avoid unnecessary coupling between two subsystems. It would be better if the JSDescription class signaled to interested listeners, like the miner, that it was about to generate a JoinSplit and signal again when it has finished (say in JSDescription::Randomized or create a wrapper which we call).

> To handle the race condition mentioned in (3)*, you could use an atomic counter which the halt signal handler will increment and the resume signal handler decrements. At launch state, the counter is 0 which the miner treats as a green light to mine. If there are parallel JoinSplits, the counter will increase but when all the JoinSplits have finished, the counter will be back at 0 and mining can resume.

> *If there are parallel joinsplits, which we can do by re-enabling the option to have multiple async worker threads, there is a race condition where one joinsplit tx completes successfully and re-enables mining, while another joinsplit tx is still being processed.

**Comment by nuttycom** [comment]
This is no longer relevant; we don't do CPU mining except for tests.
