### ISSUE TITLE
Rename wallet_protectcoinbase.py to wallet_shieldcoinbase.py

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2149]
Minor cleanup &mdash; we changed the "protect" terminology to "shield" but forgot to rename this test file.

**Comment by bitcartel** [comment]
The filename and "protect" terminology was chosen because the test enforces a coinbase consensus rule:

https://github.com/zcash/zcash/blob/master/src/chainparams.cpp#L40

https://github.com/zcash/zcash/blob/master/src/chainparams.cpp#L378

**Comment by daira** [comment]
Ah, but ``fCoinbaseMustBeProtected`` should be ``fCoinbaseMustBeShielded``, no?

I know this is low priority.
