### ISSUE TITLE
Improve performance of pairing by using mcl

### ISSUE THREAD

**Issue by herumi** [zcash/zcash#2158]
I am developing a pairing library [mcl](https://github.com/herumi/mcl).
It is faster than `alt_bn128` on x64 and ARM64 architecture and more portable than `bn128` in [libsnark](https://github.com/scipr-lab/libsnark).

I make  [a pull request for libsnark](https://github.com/scipr-lab/libsnark/pull/63).
Actually, I want to make a pull request for [zcash/libsnark](https://github.com/zcash/libsnark), but I could not how to test it. Could you show me the documents for it?

**Comment by tromer** [comment]
For reference, the libsnark pull request is https://github.com/scipr-lab/libsnark/pull/63 .
