### ISSUE TITLE
add anchor to output of getblock

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2164]
Add the note commitment anchor to the JSON output.

**Comment by bitcartel** [comment]
Should this be: Include in the JSON output the final treestate for the block, which can be used by third parties as a note commitment anchor?

**Comment by daira** [comment]
The treestate is defined to include the whole commitment tree and nullifier set (see protocol spec section 3.4). An anchor is defined as the Merkle tree root of a commitment tree. So 'anchor' is correct.

**Comment by ebfull** [comment]
The treestate is defined over the nullifier set too? I wasn't aware of that and it seems confusing...

**Comment by daira** [comment]
A given state of the commitment tree is always supposed to be used with a given state of the nullifier set. So it makes sense to have a term to refer to them both, and that term is "treestate" (even though the nullifier set is not specified as a tree).
