### ISSUE TITLE
Add documentation about how to connect and use testnet on the wiki

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#2165]
e.g. add 'testnet=1' and 'addnode=testnet.z.cash' to your zcash.conf.

**Comment by arcalinea** [comment]
Added this line:
> If you wish to run zcashd on testnet, change the lines in zcash.conf indicating the network and node discovery: testnet=1 instead of mainnet=1 and addnode=testnet.z.cash instead of addnode=mainnet.z.cash.

An improvement: we should consider separating out a Testnet wiki guide that covers available faucets and other potentially useful info, once there is a working testnet faucet running (#2119)
