### ISSUE TITLE
Not Valid After / transaction expiration

### ISSUE THREAD

**Issue by zookozcash** [zcash/zcash#2166]
If you initiate a payment and then it doesn't get mined, it would help you if you knew, after a certain point, that it would never get mined. Then you could forget about it and reissue a new payment or otherwise take care of the payment failure. We can implement this by adding a "Not Valid After" field to the transaction. It should contain a block height, not a time stamp.

Bitcoin upstream has a policy of not adding features that would lose "reorg-safety", meaning that a transaction that got mined should also be valid on a reorged blockchain of the same height. I don't see why "reorg-safety" is important. I think being able to manage the case that your transaction isn't getting mined is more important.

https://github.com/bramcohen/NotValidAfter/blob/master/Transaction_expirations.txt
http://bitcoin.stackexchange.com/questions/43180/is-there-any-way-to-make-a-transaction-invalid-if-it-is-not-confirmed-before-a-c/43181#43181
https://twitter.com/lopp/status/839867969878523906

**Comment by str4d** [comment]
@zookozcash is this a duplicate of #754? If not, can you clarify the difference?

**Comment by daira** [comment]
I'm pretty sure this is a duplicate. Let's discuss "reorg safety" on #754.

**Comment by daira** [comment]
Note that this does not require a hard fork, modulo the issue of where to put the field in the transaction encoding. If that issue were solved, then it could be a soft fork because it only restricts which blocks are valid.

**Comment by zookozcash** [comment]
Duplicate of https://github.com/zcash/zcash/issues/754
