### ISSUE TITLE
Remove /share, /src/obj, and /src/obj-test

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2169]
``/share`` looks to have only Bitcoin icons and other left-overs that we don't use.

**Comment by daira** [comment]
``/src/obj`` and ``/src/obj-test`` have only ``.gitignore`` files.

**Comment by nathan-at-least** [comment]
Bumped from 1.0.9, since we're constrained for time/resources and improving performance / robustness / testing is the primary objective of 1.0.9.

**Comment by syd0** [comment]
Hi @daira - I'm noticing that some things in /share are still referenced by Makefile.am, eg some pixmaps as part of WINDOWS_PACKAGING and a windows installer. It looks like this is stale code from bitcoin so can I get rid of it or is there a plan to support windows and I should keep this around? If we can get rid of those then I can probably get rid of most of what is in /share.

Relatedly: I notice that you commented out the OSX related QT code. Could I delete those lines from Makefile.am? It just seems cleaner unless we plan on reinstating that OSX code.

Finally, /src/obj houses a build.h that is generated by /share/genbuild.sh. This gets included in clientversion.cpp which ends up showing the build date + revision if you run strings against the binary (albeit perhaps not in the most verbose or obvious way, but it's in there). So I don't think we can get rid of /src/obj.

/src/obj-test does seem unused, we can get rid of that one.

**Comment by daira** [comment]
@radix42 maintains the Windows and Mac ports, and would know better than me whether the code you mention is used by those ports. I suspect it is not. In any case the worst that can happen from removing it is to add a conflict when those ports are merged, which can be easily resolved at that time.

The commented out lines for Mac in ``Makefile.am`` can indeed be removed.

I didn't think we used ``share/genbuild.sh``. It's unnecessary to have build timestamps and they interfere with deterministic builds. (Our Gitian release builds already avoid that problem, but it's not necessary to have build timestamps in source builds either.)

**Comment by syd0** [comment]
Thanks @daira, I will start ripping things out from the Makefile.am and /share.

re: deterministic builds, makes sense. FYI there are 2 pieces of information that are currently included via genbuild.sh: the current time, and the current git info (revision, and whether it is clean or dirty). I think it might be useful to keep the git-info, but I will get rid of the current time.
