### ISSUE TITLE
Reduce memory usage of JoinSplit by splitting the circuit

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2171]
There's a generic way to reduce the memory usage of proving a statement in a zk-SNARK (generic meaning it works for any not-too-small statement), at the cost of increasing proof size. It works in a similar way to #2134, but with a single proving system. You split the statement into sections, preferably with as few as possible components of the witness shared between sections. Then you publicly commit to the shared witness components. Each section checks the validity of this commitment wrt its own copy of the shared witness components (and the associated commitment randomness). The overall proof is the public commitment &ndash;which does not itself reveal information&ndash; and the proofs of each section. Asymptotically, if there are n roughly equal-sized sections, this reduces the memory usage by a factor of roughly n, and increases proof size by a factor of roughly n.

If some sections of the circuit might not be used, then those sections can be omitted (the fact that you're not using them is leaked, though). #647 can be seen as a specialised case of this. We could also do the same on the output side of the circuit: we could have one circuit section for the input commitment check, and one circuit section for each output. You would only need as many output sections as actual shielded outputs. A transaction would then have a vector of input sections and a vector of output sections, with commitments to the available value being carried between them. This would leak the number of shielded inputs and outputs but we essentially do that already (and you could always add dummy sections).

**Comment by daira** [comment]
This scheme fits quite well with FlexTrans (#2071), where each proof section would be a token entry. Then you could add a new type of proof at whatever point it needs to be in the value chain, without needing to change the transaction format. (It would still need a hard fork, because all full nodes would need to be able to verify the new proof type, but it wouldn't disrupt external wallets or transaction parsers.)

**Comment by daira** [comment]
An input section would need d<sub>Merkle</sub> + 7 = 36 SHA256Compress hashes. An output section would need 7 SHA256Compress hashes [*]. So they are a bit unbalanced, and in practice you'd also have to split an input section halfway up the Merkle tree to make it worthwhile. In that case there would be an extra three SHA256Compress hashes to split the circuit at that point, and so the two input stages would have 19 and 20 [*] hashes. This would likely be more than a 50% memory usage reduction on top of #647.

By comparison an unsplit circuit for #647 (with one input and two outputs) has d<sub>Merkle</sub> + 13 = 42 hashes, so there is an overhead of 19 + 20 + 2\*7 - 42 = 11 extra hashes overall attributable to the circuit split suggested in this ticket. (This is for the case where the #647 circuit exactly fits the number of inputs and outputs, which is an unfavourable case for this proposal.)

[*] Because the zk-SNARK is not simulation-sound, there needs to be a way to link knowledge of the input keys to the JoinSplit signature, which currently is done using PRF<sup>pk</sub>. I'm assuming that an extra PRF is needed to do this for the output section and for the input stage that would not otherwise have the PRF<sup>pk</sub> hash. It is possible that these extra hashes (3 of them for the one-input two-output case) could be eliminated by some clever trick.

**Comment by daira** [comment]
Another way of doing the split is to allow more than one, say N<sup>new</sup>, outputs in a single output section. This takes 3\*N<sup>new</sup> + 3 hashes. For N<sup>new</sup> = 2, this reduces the overhead relative to #647 to 6 hashes.

**Comment by daira** [comment]
#647 requires a proof + commitment size of 296 + 32 = 328 bytes. With the input section in two stages and with N<sup>new</sup> = 2, the proof + commitment size overhead is 3\*296 + 3\*32 = 984 bytes. Note that the majority of a JoinSplit description is taken up by the encrypted memo fields, which do not increase in size.

**Comment by daira** [comment]
Note that if you do this instead of #2170, then for a "Mint"-style transaction, you only need an output section, which has 5 hashes (i.e. probably about an eighth of the memory and proving time of a #647 JoinSplit, or less then 7% of the memory and proving time of a current JoinSplit).

**Comment by daira** [comment]
Let's say we are a hardware wallet and we want to do the proof involving a<sub>sk</sub> ourself in order to spend a shielded note, and outsource the other proofs. To do that we split an input section into three stages: we need to prove a stage which has 6 hashes (PRF<sup>addr</sup>, PRF<sup>pk</sup>, PRF<sup>nf</sup>, NoteCommitment, and a proof-linking commitment), and the other two input stages that we outsource each have 17 hashes. We leak only the note commitment to the proving service.

**Comment by daira** [comment]
It's possible to apply batch verification (#320) to the proofs even if you only have a single transaction to verify, so the verification cost is not necessarily increased in proportion to the number of stages in that case.

**Comment by daira** [comment]
Another advantage of this is that you can increase the note commitment Merkle tree depth (#821) without increasing memory usage; instead you would increase the number of stages into which an input section is split.

**Comment by nathan-at-least** [comment]
I just renamed the `Sapling` label to `Sapling wishlist`, so we know to review all of those tickets for Sapling feature selection. That's sufficient for prioritization, and we'll discuss this in depth at a later time, so I'll remove those labels.

**Comment by arielgabizon** [comment]
I only read the initial message of the ticket so far. At first glance, it does not seem this is worthwhile for reducing memory consumption; as a lot of the memory consumption is an incidental artifact of current implementation, that keeps the whole proving key in memory, although the prover just needs a one time pass over the proving key.
 As a sidenote, it might be a useful idea for reducing prover time for *very large* circuits, and in fact, I suspect this is what's going on in the Gepetto paper - as they have something called Commit and Prove scheme https://eprint.iacr.org/2014/976.pdf.

So the natural things seems to split the proving key in blocks according to the order the Prover reads things, and load each block into memory when the Prover uses it.

**Comment by daira** [comment]
In combination with #43, this is not just improving memory usage, it's providing opportunities for precomputation and caching of proof stages.

**Comment by arielgabizon** [comment]
Is it worth  tripling the proof size for partial precomputation? My opinion is that is isn't

**Comment by prusnak** [comment]
> Is it worth tripling the proof size for partial precomputation? My opinion is that is isn't

Storage is cheap. CPU time (and this human time) is not.

**Comment by daira** [comment]
Updating https://github.com/zcash/zcash/issues/2171#issuecomment-285960788 :

A Groth16 proof is 195 bytes. The size of a JoinSplit description, with #647 and with N<sup>old</sup> = 1 and N<sup>new</sup> = 2, is 32 (value commitment) + 32 (anchor) + 32 (nullifier) + 64 (output note commitments) + 32 (ephemeral key) + 32 (random seed) + 32 (MAC; might no longer be needed) + 195 (proof) + 1202 (note ciphertexts) = 1653 bytes. With the circuit split into three, there are two extra proofs and two extra commitments, i.e. the total is 1653 + 2\*(195 + 32) = 2107 bytes. That's a 27.5% relative overhead (for a JoinSplit description; a little less for a minimal shielded transaction).

**Comment by daira** [comment]
So to me, the main argument against this would be complexity, not space overhead.

**Comment by arielgabizon** [comment]
I understand Gepetto a little better now; anyways they do something more general, so their notation is super complicated . Here's a simpler case that covers what you want here I think.  
Say you have t circuits that have separate inputs, but also have a common input of size s.
You make s copies of the common variables, and take the union of the separate variables from all t QAPs; and all these together are your variable set for the following QAP/R1CS.

You build a QAP/R1CS with all constraints from all t QAPs (corresponding to the t circuits)
When you have a constraint using the common variables in the i'th QAP you of course use the variables from the i'th copy.

Except that you add (t-1)s equality constraints saying all t copies of each variable are equal
So you only have one proof
The proving time will roughly match the time for t proofs,
will be somewhat smaller or larger depending on s 
(can write exact expressions if you want)

**Comment by daira** [comment]
This is not in Sapling, and given the improvements in memory usage it seems unlikely to be useful for future circuit upgrades. We can always reopen the ticket if this changes.
