### ISSUE TITLE
CSP and Public Key Pins problems in z.cash website

### ISSUE THREAD

**Issue by indian-websites-engineer-support** [zcash/zcash#2172]
The CSP policy contains 'unsafe-inline' which is dangerous in the script-src directive, it also contains 'unsafe-eval' which is dangerous in the script-src directive. For Public Key Pins the "max-age" directive is too small. The minimum recommended value is 2592000 (30 days). Also no Referrer Policy is found in the z.cash website.

**Comment by nathan-at-least** [comment]
This looks like potentially 3 or 4 distinct issues. Let's track those separately. @ageis can you look into these issues and let me know in our infrastructure channel how you think we should prioritize them?

**Comment by ageis** [comment]
I don't consider this ticket extremely high priority as a majority of websites don't even have a Content Security Policy—though we do. IIRC, `unsafe-eval` and `unsafe-inline` are a deliberate relaxation which was required to get some things to work. In any case, I can fix up all of these directives relatively quickly this week.

**Comment by daira** [comment]
@ageis please move this ticket to the infrastructure repo, then close it.

**Comment by ageis** [comment]
Thanks for the advice @indian-websites-engineer-support. Closing this.
