### ISSUE TITLE
Add AMQP 1.0 support to Zcash

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#2188]
AMQP is messaging middleware, supporting both broker and brokerless messaging, and is suitable for applications ranging from enterprise to internet-of-things.

AMQP 1.0 is an International Standard (ISO/IEC 19464) and an OASIS standard.
http://www.amqp.org/

Currently Zcash supports ZeroMQ, as inherited from upstream, to facilitate notifications.

Adding AMQP support would expand the range of options available for the community looking to integrate Zcash into their systems.

**Comment by bitcartel** [comment]
PR https://github.com/zcash/zcash/pull/2189 has documentation, contributor script and test to match current ZMQ support.  Of interest to reviewers is that SSL and SASL have currently been disabled in the AMQP dependency (Apache Proton library) since we are currently in the process of deprecating OpenSSL.

**Comment by daira** [comment]
I reviewed #2189.

**Comment by nathan-at-least** [comment]
I have a few requests:

- Let's have this enabled to build by default.
- Let's put this behind the experimental feature flag, so that users understand it's new/immature.
