### ISSUE TITLE
User Patronage of Proposals

### ISSUE THREAD

**Issue by jackgavigan** [zcash/zcash#2192]
Allow users to specify that their transaction can only be mined by a miners whose support for (or opposition to) a proposal(s) matches the user's preferences. 

Consensus rules would reject blocks that include transactions that don't match the miner's specified position.

The goal is to allow users to refuse to pay transaction fees to a miner whose position they disagree with.

**Comment by daira** [comment]
Note the similarity to https://github.com/zcash/zcash/issues/1162#issuecomment-236422870 , although it's not quite the same. (Signalling for a fork proposal doesn't imply that the proposal has taken effect.)

**Comment by daira** [comment]
I added the "anonymity" tag because the choice of proposal support criteria acts as a distinguisher between users.

**Comment by jackgavigan** [comment]
@luke-jr made a [similar proposal for Bitcoin](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2017-May/014321.html). Rusty Russell's [refinement](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2017-May/014335.html) seems closest to what I originally had in mind - specifying support for or opposition to specific proposals by flagging which bits must be set (and what they must be set to) by the miner. 

Note that the idea didn't garner much support on bitcoin-dev. @petertodd doesn't think it's a good idea _[at all](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2017-May/014322.html)_.

**Comment by nuttycom** [comment]
This is not really relevant to the way that the zcash ecosystem has evolved, and as we have plans to move to proof-of-stake this is better served by stake-weighted voting (#1112)
