### ISSUE TITLE
Non-deterministic test failure of prioritisetransaction.py

### ISSUE THREAD

**Issue by ebfull** [zcash/zcash#2193]
http://ci.z.cash:8010/builders/zcash/builds/372/steps/rpc-tests.sh/logs/stdio (See #2183)

**Comment by arcalinea** [comment]
Number of txs in the mempool at the point in the test where it fails *occasionally* is 115, which is likely too low. Increasing the number of transactions generated to populate the mempool at the beginning will lessen the likelihood of this occurring again, but not sure how to totally prevent from happening

**Comment by mms710** [comment]
There's still a race condition in this test but we aren't noticing it getting triggered often. If we start having this issue again, we'll reopen this issue.
