### ISSUE TITLE
Alert message suggests upgrading to outdated Zcash version

### ISSUE THREAD

**Issue by arcalinea** [zcash/zcash#2204]
Line 91 in `sendalert.cpp` suggests users upgrade to a version of Zcash that is now out of date. 

`alert.strStatusBar  = "Your client is out of date and potentially vulnerable to denial of service. 
Please update to the most recent version of Zcash (1.0.5). 
More info at: https://z.cash/support/security.html";`

Also, when I was adding security message logging, @daira suggested that the url we point people to should be https://z.cash/support/security/index.html in case the redirect ever goes away.

**Comment by daira** [comment]
``sendalert.cpp`` just records the alert we sent, but we do need to send a new one. I suggest not including the version number so that we don't need to do this again.
