### ISSUE TITLE
RPC tests: FAIL: zmq_test.py, ImportError: No module named zmq

### ISSUE THREAD

**Issue by CESLincoln** [zcash/zcash#2209]
When I run the RPC test I receive the following error:

-----------------------------------------------------------------------------
=== Running testscript zmq_test.py ===
Traceback (most recent call last):
  File "/home/ces/zcash/qa/rpc-tests/zmq_test.py", line 12, in <module>
    import zmq
ImportError: No module named zmq
!!! FAIL: zmq_test.py !!!

Tests completed: 30
successes 29; failures: 1
------------------------------------------------------------------------------

Please advise on how to solve this issue.

Thank you!

**Comment by str4d** [comment]
You need to have `python-zmq` installed for that test to run.

**Comment by daira** [comment]
You need to install the ``python-zmq`` package.

This wasn't in the [User Guide](https://github.com/zcash/zcash/wiki/1.0-User-Guide); I've just added it.

**Comment by CESLincoln** [comment]
Sorry if this sounds elementry, this is my first time using linux.

Is this the correct command I should use to install the python-zmq package?:

$ git python-zmq

**Comment by CESLincoln** [comment]
Thank you.  I just installed the package python-zmq.

Is there a way for me to run just the zmq_test.py test without running the entire rpc test?

**Comment by str4d** [comment]
`./qa/pull-tester/rpc-tests.sh zmq_test`

**Comment by CESLincoln** [comment]
Thank you str4d!

Also, thank you daira.  I just ran the test and it was successful.
