### ISSUE TITLE
Describe the case where a Pour's public output == 0 in ``CWallet::MakePourTx``

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#221]
When a Pour is encoded into a base transaction, its encoding differs (specifically the txout of the ``CTransaction``) depending on if the public output == 0 or not. See [CWallet::MakePourTx](https://github.com/Electric-Coin-Company/zerocashd/blob/582c90c50e09a50ef48d3afc0186783d594e935a/src/wallet.cpp#L1176-L1182).

Document why this is the case in a comment in that code to close this ticket.

Also, we should consider this special case as part of the #68 design review.

**Edit 2015-09-10:** Changed the link to a range of the relevant if-branch.

**Comment by daira** [comment]
Is this relevant any longer?

**Comment by ebfull** [comment]
Not relevant.
