### ISSUE TITLE
Handle C string escapes in Tor reply parser

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#2210]
`ParseTorReplyMapping` in `torcontrol.cpp` detects escapes but does not unescape them, and neither do any of its callers. We should fix the parser to implement the following suggested rules from section 2.1.1 of the [Tor control spec](https://spec.torproject.org/control-spec):

```
  For future-proofing, controller implementors MAY use the following
  rules to be compatible with buggy Tor implementations and with
  future ones that implement the spec as intended:

    Read \n \t \r and \0 ... \377 as C escapes.
    Treat a backslash followed by any other character as that character.
```

**Comment by nathan-at-least** [comment]
@str4d: I'm bumping this out of 1.0.9 on the assumption that it does *not* fix a suspected dangerous security issue. Please insert it into the triage queue of at least one project so that we don't drop it. (If it does address an urgent security issue, ping me directly.)
