### ISSUE TITLE
Print the versions of compilers and related tools in build logs

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2218]
Print the versions of compilers and related tools, either in ``build.sh`` or in the Makefile:
```
gcc --version
g++ --version
as --version
ld --version
```

**Comment by nathan-at-least** [comment]
I prefer the Makefile, due to my preference for #58.

**Comment by nathan-at-least** [comment]
@daira, I'm work-stealing this from you.

**Comment by nathan-at-least** [comment]
@zkbot try

**Comment by str4d** [comment]
@zkbot try

**Comment by str4d** [comment]
@zkbot force
