### ISSUE TITLE
Corruption: block checksum mismatch after clear start

### ISSUE THREAD

**Issue by 3junit** [zcash/zcash#2228]
### Describe the issue
Corruption: block checksum mismatch after clear start 

#### If so, please list the steps to reproduce below:
1. Start zcash
2. Sync
3. Crash

### Expected behaviour
Running node.

### Actual behaviour + errors
Zcash crash after about 30k blocks with Corruption: block checksum mismatch.
https://ibb.co/ngYTQa - screen 

### The version of Zcash you were using:
Zcash Daemon version v1.0.6 and v1.0.8
Copyright (C) 2009-2017 The Bitcoin Core Developers
Copyright (C) 2015-2017 The Zcash Developers

### Machine specs:
- OS name + version: Debian
- CPU: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
- RAM: 64GB
- Disk size: 2TB
- Disk Type (HD/SDD): HD
- Linux kernel version (uname -a): Linux Debian-85-jessie-64-minimal 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03) x86_64 GNU/Linux
- Compiler version (gcc -version): debian binary

### Any extra information that might be useful in the debugging process.
i share 2 wallet.dat +debug logs with jay@z.cash, daira@z.cash, nathan@z.cash 

debug.log
```
2017-03-27 14:07:56 UpdateTip: new best=000000003a5ea371bef80074f2f1fdb6e66a02bc58ab74dcb7990fc07bda9047 height=31489 log2_work=47.005671 tx=182716 date=2016-12-21 15:15:06 progress=0.188306 cache=40.9MiB(1662tx)
2017-03-27 14:07:56 LevelDB read failure: Corruption: block checksum mismatch
2017-03-27 14:07:56 Corruption: block checksum mismatch
2017-03-27 14:07:56 Error: Error reading from database, shutting down.
2017-03-27 14:07:56 Error reading from database: Database corrupted
```

debug.log
```
eb51985a1d5be7244c180e46 height=31450 log2_work=47.002788 tx=182533 date=2016-12-21 14:04:16 progress=0.186867 cache=56.5MiB(5193tx)
2017-03-28 06:17:41 UpdateTip: new best=00000000689442684612dfe4f86c843e0a7b8894fc35c1d306ddf3c8c84bacea height=31451 log2_work=47.002861 tx=182536 date=2016-12-21 14:06:42 progress=0.186875 cache=56.5MiB(5195tx)
2017-03-28 06:17:41 UpdateTip: new best=0000000046b8f7bdbe176c6f88c215908710641ef91c3a7527ca474f55698df2 height=31452 log2_work=47.002933 tx=182540 date=2016-12-21 14:09:51 progress=0.186884 cache=59.5MiB(5275tx)
2017-03-28 06:17:42 Corruption: block checksum mismatch
2017-03-28 06:17:42 *** System error while flushing: Database corrupted
2017-03-28 06:17:42 Error: Error: A fatal internal error occurred, see debug.log for details
2017-03-28 06:17:42 ERROR: ProcessNewBlock: ActivateBestChain failed
```

**Comment by arcalinea** [comment]
@daira @nathan-at-least FYI this was the same user who had problems in #2094

**Comment by 3junit** [comment]
@arcalinea  and this is the same server where i got my last problem

**Comment by daira** [comment]
A "block checksum mismatch" is a fatal error because it should not be able to happen unless there is disk or memory corruption, or an incorrect computation of the checksum.

Here are similar tickets for Bitcoin: https://github.com/bitcoin/bitcoin/issues/6528 and Dogecoin: https://github.com/dogecoin/dogecoin/issues/1216 https://github.com/dogecoin/dogecoin/issues/1321 .

At least one person on the Bitcoin ticket had [memory errors](https://github.com/bitcoin/bitcoin/issues/6528#issuecomment-219520277) causing this issue, and at least one person had [disk errors](https://github.com/bitcoin/bitcoin/issues/6528#issuecomment-219615400) causing it. This doesn't preclude the possibility that there is also a software bug, but for the time being I would suspect hardware.

**Comment by 3junit** [comment]
@daira  thx for unswer, problem is....that my enviroment - is VDS and i cant replace or remove memory sticks \ change disc. Could you give any suggestions how i can confirm that my disk or memory corrupted?

**Comment by daira** [comment]
Can you either run memtest86 or ask the vendor to do so?

**Comment by arcalinea** [comment]
@3junit What other cryptocurrency daemons were you running in that environment?

**Comment by 3junit** [comment]
@arcalinea Ethereum, Blackcoin, Novacoin, Namecoin 

@daira personaly i cant cuz its vds, and probably i cant ask vendor right now cuz im only dev-ops + dev, but not the owner

**Comment by daira** [comment]
You can do memory testing from user space. Install the ``memtester`` package and run ``memtester`` with the maximum amount of memory you're able to allocate in the VM.

**Comment by ioptio** [comment]
Closing this ticket due to inactivity + probable hardware memory limits for user. Feel free to reopen if this problem persists.

**Comment by CrabbyR** [comment]
I Have the same issue...I will deal with the hardware aspect...and if I have a bad stick I will change it (memory)...but is the program itself repairable at this point...or will I have to do a fresh install?
