### ISSUE TITLE
Help fill out specifications

### ISSUE THREAD

**Issue by davidhedlund** [zcash/zcash#2229]
Can you please provide me with some info so I can add the missing data for your currency at https://en.bitcoin.it/wiki/Comparison_of_cryptocurrencies

Distribution: Zero-knowledge proofs[1]
Market cap: ?
Unit Cap: ?
Notes: ?

[1] Note that Distribution an be highly variable on https://en.bitcoin.it/wiki/Comparison_of_cryptocurrencies. Examples:
* Proof-of-work
* Proof-of-work (fixed, halving)
* Proof-of-work (random)
* Proof-of-work (fixed, curve)
* Proof-of-work (random, smooth)
* Proof-of-work/stake

**Comment by daira** [comment]
The monetary supply curve is almost the same as Bitcoin, with the following differences:
* The target block interval is 2.5 minutes, i.e. 4 times as fast as Bitcoin. Therefore the total block subsidy is a quarter of the Bitcoin block subsidy at the corresponding time after genesis.
* For the first 4 years (until the first halving), 2.5 ZEC per block is distributed as Founders' Reward to the [investors and developers](https://z.cash/blog/continued-funding-and-transparency.html), and the rest to the miner. After 4 years, all of the block subsidy goes to the miner of the block.

The proof-of-work function is [Equihash](https://z.cash/blog/why-equihash.html) with parameters n = 200, k = 9. The difficulty adjusts every block.

For current monetary base and approximate market cap, see https://explorer.zcha.in/ .

**Comment by davidhedlund** [comment]
@dabaopku Thank you for taking your time.

**Comment by davidhedlund** [comment]
@daira So is:
* Market cap: $66.63 million?
* What's the Unit cap?

**Comment by davidhedlund** [comment]
@daira Also, should I change "Distribution:  	Zero-knowledge proofs, Proof-of-work (Equihash) " to just "Distribution: Proof-of-work (Equihash)"?

**Comment by daira** [comment]
If by "unit cap" you mean total monetary base, that's also given at https://explorer.zcha.in/ . Otherwise I don't know what you mean by that term.

"Distribution: Proof-of-work (Equihash), with a portion of each block subsidy distributed to founders for the first four years."

**Comment by daira** [comment]
By the way, Zclassic is "Proof of work (Equihash)", and Zcoin also uses proof of work for mining/distribution, not zk proofs.

**Comment by daira** [comment]
Oh, inferring from the other entries, "unit cap" means the total eventual count of coins (ignoring loss of private keys or provable burning of coins). That's 20,999,999.9769 ZEC.

**Comment by daira** [comment]
@davidhedlund if all of your questions are answered, please close the ticket.

**Comment by davidhedlund** [comment]
@daira Thank you again.

I updated https://en.bitcoin.it/wiki/Comparison_of_cryptocurrencies. Where should I specifically add "Zclassic"?

**Comment by davidhedlund** [comment]
```
{| class="wikitable sortable" style="width: 100%; text-align: center; font-size: smaller; "
! style="width: 1;" | Coin
! style="width: 1;" | Ticker
! style="width: 1;" | Launched
! style="width: 99;" | Consensus tool
! style="width: 1;" | Distribution
! style="width: 1;" | Market cap
! style="width: 1;" | Unit cap
! style="width: 1;" | Status
! Notes
|-
| style="text-align: left;" | [[Zcash]]
| ZEC
| 28 Oct 2016
| Zerocash
| [[Zero-knowledge proofs]], Proof-of-work ([https://z.cash/blog/why-equihash.html Equihash]), with a portion of each block subsidy distributed to founders for the first four years.
| [https://explorer.zcha.in/ $66.63 million]
| 21,000,000
| {{yes|Active}}
| Less prone to [http://blog.zcoin.tech/zcoin-and-zcash/ privacy timing attacks] than Zcoin.
|-
| style="text-align: left;" | [[Zclassic]]
| ZCL
| {{?}}
| Zerocash
| (See Zcash)
| {{?}}
| {{?}}
| {{yes|Active}}
| {{?}}
```

**Comment by davidhedlund** [comment]
@daira Can you please modify the source above?

**Comment by ioptio** [comment]
Hey @davidhedlund I'm going to close this ticket - we have more appropriate channels for general questions that you're asking here such as the [forum](https://forum.z.cash) and the [community chat] (https://chat.zcashcommunity.com).
