### ISSUE TITLE
Integrate Zcash commitments / serials into the upstream undo mechanism.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#223]
There is an "undo tracking" mechanism in upstream which I believe *reverts* previous mutations to local state whenever doing a block re-org. The zerocash protocol isn't hooked into this. A concise example is the [``UpdateCoins``](https://github.com/Electric-Coin-Company/zerocashd/blob/582c90c50e09a50ef48d3afc0186783d594e935a/src/main.cpp#L1432) body.

**Comment by daira** [comment]
Is this done?

**Comment by ebfull** [comment]
This is done.
