### ISSUE TITLE
ensure all transitive rust dependencies are fetched via our depends system.

### ISSUE THREAD

**Issue by riordant** [zcash/zcash#2231]
build fail with librustzcash while using a proxy.
affected repository: https://github.com/rust-lang/crates.io-index

output:
```
cd /home/riordant/Documents/Project/zcash/depends/work/build/x86_64-unknown-linux-gnu/librustzcash/0.1-2078cca28b9/.; PATH=/home/riordant/Documents/Project/zcash/depends/x86_64-unknown-linux-gnu/native/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin   cargo build --release
    Updating registry `https://github.com/rust-lang/crates.io-index`
warning: spurious network error (2 tries remaining): [12/-2] [7] Couldn't connect to server (Unsupported proxy scheme for 'https://www-proxy.scss.tcd.ie:8080/')
warning: spurious network error (1 tries remaining): [12/-2] [7] Couldn't connect to server (Unsupported proxy scheme for 'https://www-proxy.scss.tcd.ie:8080/')
error: failed to fetch `https://github.com/rust-lang/crates.io-index`
```

zcash version: v1.0.8

- OS name + version: Ubuntu 16.04.2 (VM)
- RAM: 8GB
- Disk size: 39GB
- Linux kernel version (uname -a):Linux riordant-virtual-machine 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- Compiler version (gcc -version): gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

**Comment by ebfull** [comment]
I was just thinking about this yesterday; we will probably want to fetch all of the crate dependencies via the depends system so the build process doesn't need networking!

**Comment by daira** [comment]
How does this work for the Gitian builds &mdash; are they currently built without Rust, or are these downloads a source of nondeterminism?

**Comment by daira** [comment]
@riordant You can work around this problem for now by building with ``--disable-rust``.

**Comment by ebfull** [comment]
Gitian _should_ be building with Rust enabled.

The Rust dependencies are locked (and hashed) [here](https://github.com/zcash/librustzcash/blob/master/Cargo.lock) and we use a specific compiler version so there should not be any nondetermism. We should simply mirror the dependencies we use so that the depends system doesn't need to contact the crates.io repository.

**Comment by riordant** [comment]
Thanks Daira, successfully installed.

**Comment by nathan-at-least** [comment]
Let's close this ticket by following Sean's suggestion, to add all rust dependencies into our depends system as explicit packages.

**Comment by str4d** [comment]
The Rust devs have put out a Call for Help to [improve Cargo's offline build support](https://internals.rust-lang.org/t/call-for-help-cargo-airplane-mode/6134).

**Comment by str4d** [comment]
Cargo supports [Source Replacement](https://doc.rust-lang.org/cargo/reference/source-replacement.html), which can be used for vendoring dependencies. There are two ways in which it can be used:

- *Local Registry Source* - Create a directory that contains all the `*.crate` files you want, and an `index` folder following the crates.io format.
- *Directory Source* - Create a directory that contains the unpacked version of all the `*.crate` files you want, along with some additional metadata to ensure the files aren't accidentally modified.

Neither of these directly work with our depends system, which assumes it can download a single archive per package in one step, and then process it in a different step. I think the easiest to emulate is the Local Registry Source:

- Create a new depends package per crate we need.
- When fetching, download the crate file from either our package mirror, or fall back to crates.io
- When processing, copy the file to the local repository folder, and create an index entry matching the crates.io format (which should be doable from metadata we can list in the depends package file).
- In the librustzcash depends package, configure cargo to use the local registry source.
