### ISSUE TITLE
Save wallet-specific transaction data created by z_sendmany to the wallet

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#2242]
While researching https://github.com/zcash/zcash/issues/2216#issuecomment-292448352 I discovered that `z_sendmany` calls `sendrawtransaction` to send its transaction output. This means that the transaction is never saved to the wallet, but is only placed in the mempool. Thus the transaction only appears in the wallet once it has been mined and the local node has processed the block containing it.

This does not match the behaviour for transparent transactions: `CWallet::CommitTransaction()` (which calls `AddToWallet()` before sending the transaction) is called directly after `CWallet::CreateTransaction()` in both `sendmany` and the general `SendMoney()` function.

We should alter `z_sendmany` to call `CommitTransaction()` instead of `sendrawtransaction`. I believe this will become necessary anyway in order to properly store payment disclosures (#2036), but it would also enable us to store other wallet-specific transaction metadata that we can't get from the block chain.

**Comment by bitcartel** [comment]
In pairing we discussed this.  When `sendrawtransaction` broadcasts the transaction, `acceptomemorypool` will invoke `addtowallet`.  Currently the experimental payment disclosure will store data in a separate leveldb database and not as part of a `CWalletTx` transaction in the wallet file.

**Comment by radix42** [comment]
if that data is in the wallet, you can easily migrate it to another instance/machine. If not, the user may end up very surprised.

**Comment by str4d** [comment]
@radix42 this problem is related to #1885 and #2221. We really have several different types of information we want to store:

- General private key material (spending keys)
- Per-transaction private key material (payment disclosures)
- Per-transaction contextual information (time created, "payment notes" etc.)
- Per-transaction cached information (the transaction itself, cached witnesses for notes, etc.)

The wallet code inherited from Bitcoin Core stores the first and last two types all in `wallet.dat`, and we extended the last type for Zcash-specific cached information. But now we are discussing the trade-offs of maintaining a single `wallet.dat` vs. splitting it into several files:

- Storing key material in the same file as transaction information is good for backups and migration, but increases the risk of wallet corruption and lost keys / funds (particularly for the Bitcoin-like case of new t-addrs being generated all the time).
- Storing key material in a separate file to transaction information means that the key files are being touched less often (especially if separate files for spending keys and payment disclosures), reducing their risk of corruption. But it makes backups and migrations less intuitive (for people from Bitcoin land), and also increases the required engineering effort to handle the problem of inconsistent state between the various files.

If we did split up the files, then we'd probably use `wallet.dat` for the general key material for human-backwards-compatibility, and split other data into other files. Even though it would no longer match the metaphor of "keeping your notes/coins in your wallet", if that is all users back up, they don't lose access to funds.

**Comment by radix42** [comment]
So long as its well named/labelled I think it'd be ok for view keys to be outside wallet.dat, since they woulnd't lost funds if the other fine, say `view-keys.dat`, were lost.

**Comment by radix42** [comment]
also, RPC calls to backup the view keys into json regardless of what file they are in when in a binary database format would be great (ignore this comment if that's already somewhere in the design....I'm guessing it is but wanted to make note of it)

**Comment by nathan-at-least** [comment]
Bumped from 1.0.9 due to no apparent PR and lack of time.

**Comment by daira** [comment]
Eek! I'd forgotten about this, but it is pretty bad: since we don't have mempool persistence (yet), the transaction could be completely lost if the local node stops running before it is mined. (I guess it might re-receive the tx from one of its peers, but let's not rely on that.)

**Comment by Eirik0** [comment]
This is fixed by https://github.com/zcash/zcash/pull/4035
