### ISSUE TITLE
zcash.conf example contains inaccuracies

### ISSUE THREAD

**Issue by arcalinea** [zcash/zcash#2250]
In trying to improve documentation, I came across the example zcash.conf file under `contrib/debian/examples`, which I think contains inaccurate example settings.

https://github.com/zcash/zcash/blob/master/contrib/debian/examples/zcash.conf

To enable mining, you need `gen=1`, not `gen=0`.
Same with commands related to testnet and regtest.

**Comment by str4d** [comment]
That file shows the defaults for settings, which AIUI is standard practice for example config files (thinking of Apache, nginx, PHP etc.). Whether that is a *good* standard practice is something we may wish to discuss :)

**Comment by arcalinea** [comment]
It doesn't say these are defaults -- in reading it, it very much appears to be recommending `gen=0` enables mining. I would like to direct users to this example zcash.conf from the download page, but it's too confusing.

```
# Enable attempt to mine zcash.
#gen=0
```

**Comment by arcalinea** [comment]
Can we change it or should we host a better example elsewhere?

**Comment by mdr0id** [comment]
Closing as this has been updated in https://zcash.readthedocs.io/en/latest/rtd_pages/zcash_conf_guide.html
