### ISSUE TITLE
BitGo hard-fork criterion 1: on-chain activation mechanism and grace period

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2253]
https://blog.bitgo.com/bitgos-approach-to-handling-a-hard-fork-71e572506d7d

"The hard fork must be coordinated via a clear on-chain activation mechanism, and should have a generous grace period between activation and the fork taking effect."

**Comment by ebfull** [comment]
> The hard fork must be coordinated via a clear on-chain activation mechanism, and should have a generous grace period between activation and the fork taking effect.

I think a clear on-chain activation mechanism is totally compatible with a "after X block height, all older protocol blocks are not accepted, only newer protocol blocks are accepted." I treat "activation" as a release of our software that includes the hardcoded hardfork, and the fork takes effect at the pre-determined time.

In essence, I don't trust signaling, and I don't think any of our partners require us to.

**Comment by daira** [comment]
Specified in [ZIP 200](https://github.com/zcash/zips/blob/master/zip-0200.rst).
