### ISSUE TITLE
Unmet Dependancies

### ISSUE THREAD

**Issue by Cleanshooter** [zcash/zcash#2257]
When following this guide https://github.com/zcash/zcash/wiki/Debian-binary-packages

When I try this command: `sudo apt-get update && sudo apt-get install zcash`

I get the following error

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 zcash : Depends: libgomp1 (>= 4.9) but 4.8.4-2ubuntu1~14.04.3 is to be installed
         Depends: libstdc++6 (>= 4.9) but 4.8.4-2ubuntu1~14.04.3 is to be installed
E: Unable to correct problems, you have held broken packages.
```

### Machine specs:
- OS name + version:  Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
- CPU: 2.4 GHz Quad Core
- RAM: 32 GB
- Disk size: 366 GB
- Disk Type (HD/SDD): RAID 6
- Linux kernel version (uname -a): 3.13.0-115-generic #162-Ubuntu SMP Fri Mar 24 16:03:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Compiler version (gcc -version): Not installed.

**Comment by Cleanshooter** [comment]
I'm guessing this means it only works on Ubuntu 16 now-a-days.

**Comment by daira** [comment]
Try this: https://askubuntu.com/questions/428198/getting-installing-gcc-g-4-9-on-ubuntu

**Comment by Cleanshooter** [comment]
@daira too late just finished rebooting after a do-release-upgrade 😢

**Comment by ioptio** [comment]
@ageis do you have any insight on this one?

**Comment by ageis** [comment]
I'll look into this. I had thought both Trusty and Xenial would work fine but I guess I was mistaken.

**Comment by ageis** [comment]
Can reproduce and confirm that our Zcash package doesn't work on Ubuntu Trusty (14.04) due to the dependencies. The `control` file is written by `dpkg-shlibdeps`, which calculates shared libraries within executables. So long as we are building the package on Debian jessie, with a slightly newer version of libgomp1 and libstdc++6, the binary will not work on this dist. Even hacking the .deb to change the required version(s) to >= 4.8 yields negative results:

```
zcashd: /usr/lib/x86_64-linux-gnu/libgomp.so.1: version `GOMP_4.0' not found (required by zcashd)
zcashd: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by zcashd)
zcashd: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by zcashd)
```

**Comment by daira** [comment]
I believe our answer to getting Zcash working on Trusty should be to tell users to do https://askubuntu.com/a/456849 .

**Comment by daira** [comment]
I added that to the User Guide.

**Comment by daira** [comment]
Assigning myself to open a new ticket for the issue about creating a package that works on Ubuntu Trusty.

**Comment by daira** [comment]
Filed as #2358.
