### ISSUE TITLE
RPC test: FAIL: wallet_protectcoinbase.py

### ISSUE THREAD

**Issue by CESLincoln** [zcash/zcash#2263]
When I run the RPC test I receive the following error and the test is unable to continue:

```
 File "/home/ces/zcash/qa/rpc-tests/test_framework/test_framework.py", line 134, in main
  ...returned status: failed
  ...returned error: Insufficient transparent funds, have 10.00, need 0.00000053 more to avoid creating invalid change output 0.00000001 (dust threshold is 0.00000054)
    stop_nodes(self.nodes)
  waiting for async operation opid-9ce296ee-1fb9-435e-8ebf-f9beeca4942a
  File "/home/ces/zcash/qa/rpc-tests/test_framework/util.py", line 224, in stop_nodes
  ...returned status: failed
  ...returned error: Insufficient transparent funds, have 10.00, need 10000.0001
  waiting for async operation opid-ed59042c-52cd-4197-884c-52476f3401f8
  ...returned status: failed
  ...returned error: Insufficient protected funds, have 9.9998, need 10000.0001
  Unexpected exception caught during testing: global name 'BrokenPipeError' is not defined
  Stopping nodes
```

Please advice on how to solve this issue.

Thank you.

**Comment by ebfull** [comment]
Thanks for the bug report and for running our tests! We'll check into this.

**Comment by daira** [comment]
Bug introduced in https://github.com/zcash/zcash/commit/2edad86b2d130fa424ce63220dbf536c3efa9b55

**Comment by daira** [comment]
This code hasn't changed since, upstream: https://github.com/bitcoin/bitcoin/blob/master/test/functional/test_framework/authproxy.py#L133

I'm a bit confused because the RPC tests work for me on Python 2, even though the code appears as though it shouldn't work. Are the classes specified in ``except:`` clauses only evaluated when there is an exception that reaches that clause?

**Comment by daira** [comment]
In any case I suggest this fix:
```
        except Exception as e:
            # Python 3.5+ raises BrokenPipeError instead of BadStatusLine when the connection was reset
            # ConnectionResetError happens on FreeBSD with Python 3.4
            # These classes don't exist in Python 2.x, so we can't refer to them directly.
            if e.__class__.__name__ not in ('BrokenPipeError', 'ConnectionResetError'):
                raise
            self.__conn.close()
            self.__conn.request(method, path, postdata, headers)
            return self._get_response()
```

**Comment by daira** [comment]
Note that the above fix would only correct the error reporting; presumably, the test that @CESLincoln ran would still have failed but would have reported the correct exception on Python 2.

**Comment by bitcartel** [comment]
@daira @ebfull This is the same error I was seeing yesterday.

**Comment by daira** [comment]
@bitcartel can you try again with the referenced PR?

**Comment by bitcartel** [comment]
Yes, the test still fails.

The PR itself does mean that BrokenPipeError not existing in Python 2 is replaced with exception `[Errno 32] Broken pipe` getting thrown and caught.

**Comment by daira** [comment]
Does it attempt to retry the request once on a broken pipe, as it should (to correctly support HTTP 1.1 persistent connections)?

**Comment by daira** [comment]
That is, is the ``[Errno 32] Broken pipe`` exception thrown from the original request, or the retry?

**Comment by bitcartel** [comment]
Here is the terminal output with tracerpc enabled (scroll to end), looks like the original request is sent and then the error (can't tell if retry or not): https://gist.github.com/bitcartel/35ad8c997b753869d457eb1e3c2c0ac2

**Comment by daira** [comment]
The ``httplib.CannotSendRequest`` traceback is apparently interleaved with output from other threads. Here it is cleaned up:
```
Traceback (most recent call last):
  File "/home/USERNAME/projects/zcash/qa/rpc-tests/wallet_protectcoinbase.py", line 299, in <module>
    WalletProtectCoinbaseTest().main()
  File "/home/USERNAME/projects/zcash/qa/rpc-tests/test_framework/test_framework.py", line 134, in main
  File "/home/USERNAME/projects/zcash/qa/rpc-tests/test_framework/util.py", line 224, in stop_nodes
    node.stop()
  File "/home/USERNAME/projects/zcash/qa/rpc-tests/test_framework/authproxy.py", line 143, in __call__
    response = self._request('POST', self.__url.path, postdata)
  File "/home/USERNAME/projects/zcash/qa/rpc-tests/test_framework/authproxy.py", line 119, in _request
    self.__conn.request(method, path, postdata, headers)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1091, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/lib/python2.7/httplib.py", line 939, in putrequest
    raise CannotSendRequest()
httplib.CannotSendRequest
```

Here's the code from ``httplib.py`` that raised that exception:
```
        # in certain cases, we cannot issue another request on this connection.
        # this occurs when:
        #   1) we are in the process of sending a request.   (_CS_REQ_STARTED)
        #   2) a response to a previous request has signalled that it is going
        #      to close the connection upon completion.
        #   3) the headers for the previous response have not been read, thus
        #      we cannot determine whether point (2) is true.   (_CS_REQ_SENT)
        #
        # if there is no prior response, then we can request at will.
        #
        # if point (2) is true, then we will have passed the socket to the
        # response (effectively meaning, "there is no prior response"), and
        # will open a new one when a new request is made.
        #
        # Note: if a prior response exists, then we *can* start a new request.
        #       We are not allowed to begin fetching the response to this new
        #       request, however, until that prior response is complete.
        #
        if self.__state == _CS_IDLE:
            self.__state = _CS_REQ_STARTED
        else:
            raise CannotSendRequest()
```

(the last line here is line 939, in my system Python which is 2.7.12rc1).

**Comment by daira** [comment]
Note that this is raised from the original request (``CannotSendRequest`` does not trigger a retry).

**Comment by bitcartel** [comment]
@CESLincoln Did you manage to resolve this issue?  If yes, what steps did you take?  Thanks.

**Comment by daira** [comment]
Reading the comment in ``httplib.py``, it seems to me that these are cases where we should probably retry (once), i.e. ``CannotSendRequest`` should be handled the same way as ``BadStatusLine``, ``BrokenPipeError``, or ``ConnectionResetError``.

**Comment by bitcartel** [comment]
Debian 8 Jessie ships with Python 2.7.9 and the test runs fine.

**Comment by daira** [comment]
@bitcartel Well, the issue you're seeing now might not be the same as the one associated with the backtrace inhttps://github.com/zcash/zcash/issues/2263#issuecomment-294361860 . Can you get a similar cleaned-up backtrace for your current issue?

**Comment by daira** [comment]
Oh, maybe there was a fix in Python 2.7.9 or another version after you were using before. Which Python version was that?

**Comment by bitcartel** [comment]
@daira Same problem, emanating from the exact same location in the python test.  I didn't keep a copy of the backtrace, sorry.  I am running Python 2.7.12 locally.  Using a VM with Debian 8 Jessie and Python 2.7.9, the test runs fine.

**Comment by daira** [comment]
Ah, so it could be a regression in Python (or a change that exposes a bug in our code), rather than a fix.

**Comment by hirishh** [comment]
I have the same issue on Ubuntu 16.04.3 with Python 2.7.12.
I tried to downgrade to Python 2.7.9 but it doesn't solve the issue.

**Comment by bitcartel** [comment]
Same problem with Python 2.7.14 on Ubuntu.
