### ISSUE TITLE
Priority-related security vulnerability (2017-04-11.a)

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2264]
This will be updated to describe in detail the vulnerability that was fixed in release 1.0.8-1, after users have been given time to upgrade.

**Comment by nathan-at-least** [comment]
@bitcartel please coordinate with @daira on this issue.

**Comment by daira** [comment]
This was an undefined behaviour bug, fixed in #2259. A fix for a previous bug (#1895) had resulted in the priority for transactions containing JoinSplits being a very large `double`. Then looking up that value in the fee `bucketMap` resulted in a "at end" iterator, which caused UB when dereferenced (in the `bucketMap.lower_bound(val)->second` expressions that are replaced with calls to `FindBucketIndex` in #2259). The fix was to add a +Inf (`std::numeric_limits<double>::infinity()`) value to bound the largest fee bucket.
