### ISSUE TITLE
Change default regtest port of 18444 which is the same as (inherited from) upstream

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#2269]
https://github.com/zcash/zcash/blob/master/src/chainparams.cpp#L322
via
https://github.com/zcash/zcash/pull/2150#issuecomment-293670166

**Comment by daira** [comment]
Concept ACK.

**Comment by daira** [comment]
We don't have time to do this for 1.0.9 though, do we?

**Comment by bitcartel** [comment]
It's a simple change and easy to review, so we should be able to squeeze it in.

How about 18344 ?

This would follow the pattern we've used so far of subtracting 100 e.g. 8333 -> 8233 and 18333 -> 18233.  

Also it's free according to: https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers

**Comment by daira** [comment]
PR is #2270
