### ISSUE TITLE
relayfee doesn't work

### ISSUE THREAD

**Issue by ucwong** [zcash/zcash#2282]
![image](https://cloud.githubusercontent.com/assets/22344498/25163093/4eb4a5cc-24fa-11e7-885a-685960f6031a.png)
![image](https://cloud.githubusercontent.com/assets/22344498/25163100/5b965cf4-24fa-11e7-9d6e-3e67012a215d.png)

**Comment by daira** [comment]
There is no ``relayfee`` option (maybe there should be). Unrecognised options are ignored, which is probably a bad idea for usability.

**Comment by nathan-at-least** [comment]
@ucwong, is the first image from your `zcash.conf`?

**Comment by str4d** [comment]
@ucwong the correct option to configure the relay fee is `minrelaytxfee`, same as in Bitcoin.

**Comment by ioptio** [comment]
Closing this, feel free to reopen if you have troubles with `minrelaytxfee`

**Comment by bitcartel** [comment]
From `rpcmisc.cpp`, we can see `obj.push_back(Pair("relayfee",      ValueFromAmount(::minRelayTxFee.GetFeePerK())));` so we could rename the option.

**Comment by daira** [comment]
We don't know whether there are clients relying on the existing field name, and I'm loath to include two fields with the same contents. Let's leave it as it is.
