### ISSUE TITLE
rpc api or python lib to create private key directly

### ISSUE THREAD

**Issue by openalmeida** [zcash/zcash#2291]
e.g simple as Bitcoin used a sha256sum or any standalone library's last output result as input,
it is friendly for brain based key, such as:

birthday ---> some map/hash/algorithm write my self ---> standalone library ---> private_key

which make me remember private_key just based my brain,
instead of zcashd random created only,
maybe with a prompt such as secure question only i know etc.

just let a way make the private key create process standalone.

maybe it is exists i do not know, or any tips to create it ?
maybe i can write one.

thanks a lot

**Comment by daira** [comment]
See #18.

**Comment by openalmeida** [comment]
I'm closing this ticket because i think i should read the code or docs more
