### ISSUE TITLE
RPC API zcrawjoinsplit stuff

### ISSUE THREAD

**Issue by openalmeida** [zcash/zcash#2292]
as [public alpha guide](https://github.com/zcash/zcash/wiki/Public-Alpha-Guide/6a02e21a735876db45c9c6247d854887fdbcef50) said

```
$ RAWTX=$(./src/zcash-cli createrawtransaction '[{"txid":"e3eb7d6...","vout":0}]' '{}')
$ ./src/zcash-cli zcrawjoinsplit "$RAWTX" '{}' "{\"$ZCADDRESS\":49.9}" 49.9 0
```

and said

```
In this case, I'm taking 50 testcoins from my UTXO,
sending 49.9 of them to my zcaddress,
and producing 0.1 as a fee for the transaction.
The balance of your transaction `must work out` or you will get errors!
```

**`Does the "must work out" mean`**
**`UTXO must synced with ZCASH network or from data pulled yet at least` ?**

because i create a transaction but get an error here

```
error code: -1
error message:
invalid joinsplit balance
```

after some google and github search,
i found [unittest code lines as comments at 452 and 482](https://github.com/zcash/zcash/blob/a3981215033b4d1203fccedfa5b36d58c2a9e7b6/src/gtest/test_joinsplit.cpp#L452) mentioned "Absurd total input value" or "Absurd total output value" etc.

so, i am confused does it need networking synced to check or not.

because it seems `createrawtransaction` do not have field to specialized `input amount`,
but `zcrawjoinsplit` said so (with success) or output `invalid joinsplit balance` (as error).

if answer is yes, how could it be,
it may takes such a long time and a full node to run even user just wanna a wallet,
and blocks only means local store exists,
the nodes still need a check out first when broadcasting.

if answer is no, why check balance is required (but seems no field to specialize input amount )
and seems no api to check blocks/transactions
partially addresses about only (only sync data about addresses user care, to save time and harddrive)

.

.

**Comment by daira** [comment]
First I should emphasise that the ``zcrawjoinsplit`` interface is deprecated and might be removed at any time.

To answer your question, "invalid joinsplit balance" means the the sum of input values is different from the sum of output values, for a particular JoinSplit. When using the raw interface, it is your responsibility to ensure that inputs and outputs of each JoinSplit balance, and you'll need to read the protocol spec in detail to understand this and other requirements. This error is not anything to do with how recently the node has synced to the block chain (although you will have to sync to the block that you are using as the JoinSplit anchor).

**Comment by bitcartel** [comment]
Closing as this API is deprecated.
