### ISSUE TITLE
[Sapling] Encode the root of the Merkle tree over commitments in the header of each block

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2298]
(Prompted by [this Twitter conversation](https://twitter.com/Tracy_Hu17/status/853793471588585472) with Tracy Hu.)

A block doesn't currently explicitly encode the root of the Merkle tree over commitments. Each node must recompute it from scratch starting from the genesis block. If a node were to compute a different root than the consensus value (e.g. due to a memory glitch), then it would fail to verify valid JoinSplits. This doesn't by itself introduce a security problem, but it is potentially undesirable in two ways:

* it does not support verification of a suffix of the block chain, with SPV security for the prefix;
* the error reporting on the node that miscomputed the Merkle tree root will not pinpoint the exact point at which that occurred, and will instead reject the next block containing a JoinSplit, forking it from the network.

**Comment by str4d** [comment]
I'm wondering whether we should reconsider this for Sapling, as I think it is required for light clients to implement Sapling support safely.

A light client that implements Sapling will rely on a third party to provide them with:

- block headers
- anchors
- a way to calculate paths from each of their notes to each anchor

The block headers can easily be validated as part of the chain (including PoW), and the Merkle tree paths can be trivially validated against the provided anchor. However, the anchors themselves cannot currently be validated without the light client seeing every commitment in every JoinSplit in every transaction in every block in the blockchain, which completely breaks the point of a light client. Including the root in each block does not increase the required header bandwidth over sending the anchor separately, and enables light clients to be certain that the anchors are valid.

We do have the reserved field in the block header, so we can add this without needing to change the header format. We will still need to do outreach to ensure mining pools behave correctly, but we are already doing that as part of the Overwinter release (which changes transaction formats for coinbase transactions).

**Comment by daira** [comment]
In the engineering meeting on 2018-02-19 we decided to include this in Sapling.

**Comment by str4d** [comment]
Note that in block N we want to store the root corresponding to the tree *after* adding the transactions in block N; otherwise, SPV clients would need to be given the full list of transaction IDs in a particular block in order to verify the latest anchor. The root corresponding to the tree *before* adding the transactions in block N can be trivially found by looking at block header `N - 1`.

**Comment by daira** [comment]
This is specified in [the Sapling protocol spec](https://github.com/zcash/zips/blob/master/protocol/sapling.pdf) (section 7.5) since 2018.0-beta-10.

**Comment by str4d** [comment]
Per above, this is specified. Implementation is covered by #3056 and #3065.
