### ISSUE TITLE
Check that we use an RNG that blocks until sufficient entropy has been gathered, and then never subsequently

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2299]
We use libsodium's RNG (#1706 removed our use of the OpenSSL RNG, including from Bitcoin-derived code).

The Right Thing for a general-purpose cryptographic RNG is to block for calls made before sufficient entropy has been gathered at startup, and then never block subsequently.

On Linux, the default libsodium RNG implementation (which we do not override) tries where possible to use the same [system call](https://lwn.net/Articles/606141/) that the [getrandom](http://man7.org/linux/man-pages/man2/getrandom.2.html) libc function uses. This is implemented in [src/libsodium/randombytes/sysrandom/randombytes_sysrandom.c](https://github.com/jedisct1/libsodium/blob/master/src/libsodium/randombytes/sysrandom/randombytes_sysrandom.c#L196-L234), and is enabled provided that this preprocessor directive holds:
```
# if defined(__dietlibc__) || (defined(SYS_getrandom) && defined(__NR_getrandom))
```

(It doesn't use the ``getrandom()`` function itself because [the glibc maintainers obstructed getting this trivial syscall wrapper into libc for two and a half years](https://lwn.net/Articles/711013/).)

I have **not** verified that the preprocessor directive holds; we need to do this. I don't know what happens if you try to run on, and/or compile with headers for, a Linux kernel version < 3.17 (the version that introduced the getrandom syscall).

The libsodium code appears to perform correct error handling around the syscall, including ``EINTR`` and ``EAGAIN`` handling. For requests larger than 256 bytes, it loops limiting the amount it attempts to read on each syscall to a maximum of 256 bytes. The syscall has almost the same semantics as documented for the ``getrandom()`` function, except that it is not a cancellation point. From the [getrandom man page](http://man7.org/linux/man-pages/man2/getrandom.2.html):

> If the urandom source has been initialized, reads of up to 256 bytes will always return as many bytes as requested and will not be interrupted by signals.  No such guarantees apply for larger buffer sizes.  For example, if the call is interrupted by a signal handler, it may return a partially filled buffer, or fail with the error ``EINTR``.

[...]

> By default, when reading from the random source, ``getrandom()`` blocks if no random bytes are available, and when reading from the urandom source, it blocks if the entropy pool has not yet been initialized.  If the ``GRND_NONBLOCK`` flag is set, then ``getrandom()`` does not block in these cases, but instead immediately returns -1 with ``errno`` set to ``EAGAIN``.

Since the libsodium code does not set ``GRND_NONBLOCK`` (or ``GRND_RANDOM``), the effect should be for ``randombytes_linux_getrandom`` to block until the entropy pool has been initialized, and then not subsequently, as desired.

(Strictly speaking, the kernel could repeatedly return ``EINTR`` or ``EAGAIN`` causing libsodium to spin in [this loop](https://github.com/jedisct1/libsodium/blob/master/src/libsodium/randombytes/sysrandom/randombytes_sysrandom.c#L203-L209), which is effectively the same as blocking. It shouldn't actually do this unless there is something very wrong.)

I have **not** checked what happens on any other platform than Linux.

**Comment by radix42** [comment]
on Windows the system random number generator is used everywhere that I've seen. I cannot tell you without spelunking in the code which precise system call that is in the Windows api, so I do not know how it handles entropy or the lack thereof

**Comment by radix42** [comment]
I also do not know what RNG is used on mac :-(

**Comment by daira** [comment]
On Windows [libsodium uses RtlGenRandom](https://github.com/jedisct1/libsodium/blob/master/src/libsodium/randombytes/sysrandom/randombytes_sysrandom.c#L31-L45), which is documented [https://msdn.microsoft.com/en-us/library/windows/desktop/aa387694(v=vs.85).aspx](on MSDN here). (See [here](https://bugzilla.mozilla.org/show_bug.cgi?id=504270) for why it is safe to rely on this function despite the scary warning in the doc.)

The MSDN documentation says nothing about blocking behaviour. There's some discussion of its security on [the Wikipedia article for CryptGenRandom](https://en.wikipedia.org/wiki/CryptGenRandom), which is a wrapper around RtlGenRandom. The [paper by Dorrendorf et al]() referenced there is interesting reading, although it refers to the implementation in Windows 2000 and earlier.

**Comment by daira** [comment]
The Fortuna RNG used by recent versions of Windows was designed by Ferguson and Schneier and is described in Chapter 10 of their book [Practical Cryptography](https://sisis.rz.htw-berlin.de/inh2008/12361083.pdf). For RNG nerds, [this paper](https://eprint.iacr.org/2014/167) analyses and improves on Fortuna.

**Comment by daira** [comment]
Fortuna uses a seed file (updated periodically from the RNG state) to initialise the RNG on startup. From the discussion in Practical Cryptography section 10.6.2, it sounds to me as though this mechanism is probably *not* robust against VM replay attacks. Microsoft might have improved it since, I don't know.

**Comment by daira** [comment]
This is what needs to be checked for 1.0.9:
> I have not verified that the preprocessor directive holds; we need to do this. I don't know what happens if you try to run on, and/or compile with headers for, a Linux kernel version < 3.17 (the version that introduced the getrandom syscall).

**Comment by nathan-at-least** [comment]
ping @daira: Any update on this investigation?

**Comment by nathan-at-least** [comment]
Bumped from 1.0.9 due to lack of time.

**Comment by daira** [comment]
I verified that the preprocessor condition ``defined(__dietlibc__) || (defined(SYS_getrandom) && defined(__NR_getrandom))`` does in fact hold at the relevant point in randombytes/sysrandom/randombytes_sysrandom.c when Zcash is compiled on my (Debian testing) virtual machine.

**Comment by daira** [comment]
Note that we use a different RNG in Rust; I don't know much about it but I believe it uses `getrandom` when available. @str4d's has a branch that will remove libsodium, so I think we'll be using the Rust RNG for everything then.

**Comment by str4d** [comment]
We use `rand::rngs::OsRng` in Rust, which is a wrapper around `getrandom`, which itself is a wrapper around OS random APIs. By default, compiling `getrandom` for an unsupported target [results in a compilation error](https://docs.rs/getrandom/0.1.14/getrandom/#unsupported-targets).

**Comment by str4d** [comment]
In #4654 we replaced our usage of libsodium's RNG in C++ with `rand::rngs::OsRng`. We therefore use `getrandom` directly everywhere for randomness, which [implements best practices matching this issue](https://docs.rs/getrandom/0.2.3/getrandom/).
