### ISSUE TITLE
Where possible, use crypto that is resilient to re-used RNG outputs

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2300]
@zookozcash wrote:
> We should use crypto algorithms which are resilient to re-used RNG outputs. This is a well-understood crypto concept (there's an RFC and everything), and our cryptographers can help us make sure we're doing it right.

I'm not sure what RFC Zooko is referring to. [RFC 6979](https://tools.ietf.org/html/rfc6979) (Deterministic Usage of [ECDSA]) is an example of this technique, but does not consider the general case. [RFC 4086](https://tools.ietf.org/html/rfc4086) (Randomness Requirements for Security) does not cover this technique.

We use libsecp256k1 for ECDSA signature generation, which implements RFC 6979.

Ed25519 signature generation is inherently deterministic.

Our main protocol construction for JoinSplits tries to improve robustness against RNG failure by mixing in the nullifiers, which are enforced to be unique, to the computation of hSig. Then hSig is used to derive ρ, which ensures that notes have a nonrepeating random component. The KDF for deriving note encryption keys also mixes in hSig. (Since the note encryption is an authenticated stream cipher, it is essential that those keys not repeat.)

However, we obtain [spending keys](https://github.com/zcash/zcash/blob/master/src/zcash/Address.cpp#L24) and [ECDSA signature keys](https://github.com/zcash/zcash/blob/master/src/key.cpp#L24-L26) directly as RNG outputs. This could probably be improved.

**Comment by indolering** [comment]
> re-used RNG outputs

Maybe @zookozcash was thinking about nonce-misuse resistance?  The primary problem has been the use of random nonces in stream ciphers instead of counters.  The primary solution there has been to include as much "associated" data as possible into the encrypted payload, such as altering the API to include public and private "message numbers" instead of "nonces".

**Comment by daira** [comment]
@indolering Right, and we already do that. Specifically, the inputs to the note encryption KDF are:
* the index i of the output note in a given JoinSplit
* hSig, which is in turn a hash of:
  * a random seed
  * the two input nullifiers, which are required to be unique per JoinSplit that gets into a given block chain (although they can repeat across orphan blocks)
  * the JoinSplit signature public key
* the ECDH shared secret
* the ephemeral public key epk
* the public key to which the note is encrypted.

The random seed and epk are specified to be chosen independently at random per JoinSplit. The JoinSplit signature public key is specified to be chosen independently at random per JoinSplit-containing transaction.

(See sections 5.4.2 and 5.4.7 of the protocol spec.)

**Comment by indolering** [comment]
@daira Ah yes, I understood that.  Sorry, I'll try to keep my ticket comments to a minimum.

**Comment by daira** [comment]
Not at all, didn't mean to discourage you. It was a useful thing to point out.

**Comment by indolering** [comment]
I already knew that's what you were getting at so I didn't add anything.  And I *really* hate it when my Github feed gets cluttered up with useless chatter : P

**Comment by daira** [comment]
This was a significant consideration in the design of Sapling, for example:
* PRF<sup>ock</sup> takes ``cv``, ``cmu`` and ``ephemeralKey`` as input;
* RedDSA hashes the message as well as a random input to obtain the nonce.
