### ISSUE TITLE
try to update to 1.0.8-1 from 1.0.5, met error when build

### ISSUE THREAD

**Issue by archerhu77** [zcash/zcash#2301]
OS:CentOS7
gcc,g++:6.3.0

When I start my zcash 1.0.5, system told me that need to upgrade, so I do following in zcash's directory:
git fetch origin
git checkout v1.0.8
./zcutil/fetch-params.sh
./zcutil/build.sh --disable-rust -j32

But met following error when run build.sh:
....
/root/zcash/src/gtest/test_libzcash_utils.cpp:24: undefined reference to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)'
/root/zcash/src/gtest/test_libzcash_utils.cpp:25: undefined reference to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)'
/root/zcash/src/gtest/test_libzcash_utils.cpp:26: undefined reference to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)'
/root/zcash/src/gtest/test_libzcash_utils.cpp:27: undefined reference to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)'
/root/zcash/src/gtest/test_libzcash_utils.cpp:28: undefined reference to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)'
gtest/zcash_gtest-test_libzcash_utils.o:/root/zcash/src/gtest/test_libzcash_utils.cpp:29: more undefined references to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)' follow
libbitcoin_server.a(libbitcoin_server_a-txdb.o): In function `bool CLevelDBWrapper::Exists<char>(char const&) const':
/root/zcash/src/leveldbwrapper.h:138: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
libbitcoin_server.a(libbitcoin_server_a-txdb.o): In function `bool CLevelDBWrapper::Read<char, int>(char const&, int&) const':
/root/zcash/src/leveldbwrapper.h:105: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
libbitcoin_server.a(libbitcoin_server_a-txdb.o): In function `bool CLevelDBWrapper::Read<std::pair<char, uint256>, bool>(std::pair<char, uint256> const&, bool&) const':
/root/zcash/src/leveldbwrapper.h:105: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
libbitcoin_server.a(libbitcoin_server_a-txdb.o): In function `bool CLevelDBWrapper::Exists<std::pair<char, uint256> >(std::pair<char, uint256> const&) const':
/root/zcash/src/leveldbwrapper.h:138: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
libbitcoin_server.a(libbitcoin_server_a-txdb.o): In function `bool CLevelDBWrapper::Read<std::pair<char, uint256>, CDiskTxPos>(std::pair<char, uint256> const&, CDiskTxPos&) const':
/root/zcash/src/leveldbwrapper.h:105: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
libbitcoin_server.a(libbitcoin_server_a-txdb.o):/root/zcash/src/leveldbwrapper.h:105: more undefined references to `leveldb::Status::ToString[abi:cxx11]() const' follow
libbitcoin_server.a(libbitcoin_server_a-leveldbwrapper.o): In function `CLevelDBWrapper::CLevelDBWrapper(boost::filesystem::path const&, unsigned long, bool, bool)':
/root/zcash/src/leveldbwrapper.cpp:61: undefined reference to `leveldb::DestroyDB(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, leveldb::Options const&)'
/root/zcash/src/leveldbwrapper.cpp:67: undefined reference to `leveldb::DB::Open(leveldb::Options const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, leveldb::DB**)'
collect2: error: ld returned 1 exit status
make[2]: *** [zcash-gtest] Error 1
make[2]: *** Waiting for unfinished jobs....
libbitcoin_server.a(libbitcoin_server_a-leveldbwrapper.o): In function `HandleError(leveldb::Status const&)':
/root/zcash/src/leveldbwrapper.cpp:20: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
libbitcoin_server.a(libbitcoin_server_a-leveldbwrapper.o): In function `CLevelDBWrapper::CLevelDBWrapper(boost::filesystem::path const&, unsigned long, bool, bool)':
/root/zcash/src/leveldbwrapper.cpp:61: undefined reference to `leveldb::DestroyDB(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, leveldb::Options const&)'
/root/zcash/src/leveldbwrapper.cpp:67: undefined reference to `leveldb::DB::Open(leveldb::Options const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, leveldb::DB**)'
libbitcoin_server.a(libbitcoin_server_a-txdb.o): In function `bool CLevelDBWrapper::Exists<char>(char const&) const':
/root/zcash/src/leveldbwrapper.h:138: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
libbitcoin_server.a(libbitcoin_server_a-txdb.o): In function `bool CLevelDBWrapper::Read<char, int>(char const&, int&) const':
/root/zcash/src/leveldbwrapper.h:105: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
libbitcoin_server.a(libbitcoin_server_a-txdb.o): In function `bool CLevelDBWrapper::Read<std::pair<char, uint256>, bool>(std::pair<char, uint256> const&, bool&) const':
/root/zcash/src/leveldbwrapper.h:105: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
libbitcoin_server.a(libbitcoin_server_a-txdb.o): In function `bool CLevelDBWrapper::Exists<std::pair<char, uint256> >(std::pair<char, uint256> const&) const':
/root/zcash/src/leveldbwrapper.h:138: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
libbitcoin_server.a(libbitcoin_server_a-txdb.o): In function `bool CLevelDBWrapper::Read<std::pair<char, uint256>, CDiskTxPos>(std::pair<char, uint256> const&, CDiskTxPos&) const':
/root/zcash/src/leveldbwrapper.h:105: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
libbitcoin_server.a(libbitcoin_server_a-txdb.o):/root/zcash/src/leveldbwrapper.h:105: more undefined references to `leveldb::Status::ToString[abi:cxx11]() const' follow
collect2: error: ld returned 1 exit status
make[2]: *** [zcashd] Error 1
libbitcoin_server.a(libbitcoin_server_a-leveldbwrapper.o): In function `HandleError(leveldb::Status const&)':
/root/zcash/src/leveldbwrapper.cpp:20: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
libbitcoin_server.a(libbitcoin_server_a-leveldbwrapper.o): In function `CLevelDBWrapper::CLevelDBWrapper(boost::filesystem::path const&, unsigned long, bool, bool)':
/root/zcash/src/leveldbwrapper.cpp:61: undefined reference to `leveldb::DestroyDB(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, leveldb::Options const&)'
/root/zcash/src/leveldbwrapper.cpp:67: undefined reference to `leveldb::DB::Open(leveldb::Options const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, leveldb::DB**)'
libbitcoin_server.a(libbitcoin_server_a-txdb.o): In function `bool CLevelDBWrapper::Exists<char>(char const&) const':
/root/zcash/src/leveldbwrapper.h:138: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
libbitcoin_server.a(libbitcoin_server_a-txdb.o): In function `bool CLevelDBWrapper::Read<char, int>(char const&, int&) const':
/root/zcash/src/leveldbwrapper.h:105: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
libbitcoin_server.a(libbitcoin_server_a-txdb.o): In function `bool CLevelDBWrapper::Read<std::pair<char, uint256>, bool>(std::pair<char, uint256> const&, bool&) const':
/root/zcash/src/leveldbwrapper.h:105: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
libbitcoin_server.a(libbitcoin_server_a-txdb.o): In function `bool CLevelDBWrapper::Exists<std::pair<char, uint256> >(std::pair<char, uint256> const&) const':
/root/zcash/src/leveldbwrapper.h:138: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
libbitcoin_server.a(libbitcoin_server_a-txdb.o): In function `bool CLevelDBWrapper::Read<std::pair<char, uint256>, CDiskTxPos>(std::pair<char, uint256> const&, CDiskTxPos&) const':
/root/zcash/src/leveldbwrapper.h:105: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
libbitcoin_server.a(libbitcoin_server_a-txdb.o):/root/zcash/src/leveldbwrapper.h:105: more undefined references to `leveldb::Status::ToString[abi:cxx11]() const' follow
collect2: error: ld returned 1 exit status
make[2]: *** [test/test_bitcoin] Error 1
make[2]: Leaving directory `/root/zcash/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/zcash/src'
make: *** [all-recursive] Error 1

How can I solve this problem?

**Comment by daira** [comment]
Sorry that this ticket seems to have slipped through the cracks. Can you try again with a more recent version of Zcash to see whether you still have this problem, please?

**Comment by ioptio** [comment]
Closing this ticket due to lack of response. Feel free to reopen if this is still a problem for you.
