### ISSUE TITLE
Set up a 'dev-ci' environment.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#2302]
Right now we change our single CI environment as we go. This causes context-switching and coordination costs during releases.

Set up a new dev-ci environment. We prototype changes here. Initially it's fine it Homu doesn't trigger it and we need to manually trigger builds to test out new CI changes.

Eventually it might be nice to have every trigger of production CI also trigger dev CI, but maybe that gets messy. Dunno. Let's figure that out later.

**Comment by ageis** [comment]
This is like 90% done at https://dev-ci.z.cash/#/ with Homu disabled. A couple things left to do:

* Use different secrets for the development environment, but which still work
* Set up separate EC2 AMIs for the development environment

**Comment by ageis** [comment]
We're going to use the https://github.com/Electric-Coin-Company/zcash repository with dev-ci. This ticket is almost complete, I just have to finish generating/rotating secrets and separate AMI images. That may have to wait for a lull in merges, as the prod build system will get confused if I try to do anything with latents.
 (maybe I can attempt to proxy it off, hrm)

**Comment by arcalinea** [comment]
Don't know where the status of this was at, but I couldn't access the dev-ci.z.cash instance, so I created a new one. 

- renamed the Electric-Coin-Company/zcash repo to  Electric-Coin-Company/dev-ci-zcash 
- created new dev-ci.z.cash server from ansible role
