### ISSUE TITLE
[ZIP 0] Standardize ZIP process

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2307]
<a href="https://github.com/ebfull"><img src="https://avatars2.githubusercontent.com/u/3794471?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ebfull](https://github.com/ebfull)**
_Monday Dec 14, 2015 at 17:57 UTC_
_Originally opened as https://github.com/zcash/zips/issues/1_

----

We need to standardize a "Zcash Improvement Proposals" process for making significant changes to Zcash's protocol or even minor changes to the zk-SNARK circuit.

Note: We should not adopt a ZIP process in our development efforts until a public beta.

**Comment by daira** [comment]
<a href="https://github.com/nathan-at-least"><img src="https://avatars2.githubusercontent.com/u/4369700?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nathan-at-least](https://github.com/nathan-at-least)**
_Monday Dec 14, 2015 at 19:43 UTC_

----

Agreed.

Here's my understanding so far: We want our process to be as thorough as necessary while also as light and nimble as possible. Before we commit to changes, we want to ensure the code, design, and security analysis all match, so we need to get the engineering and science teams synchronized on these kinds of changes.

However, for nimbleness and speed, we don't want a process that's too heavy. For that reason, I suggest that for now we:
- _can_ make design changes first, then do both engineering implementation and science review independently from there. This means we may do engineering work on something only to learn later than some scientific flaw is discovered, but I think that risk is worth it in order to have faster engineering progress.
- do review / analysis process with a combination of github PRs to the specs / design docs (in this repo) as well as meeting topics, ml posts, etc...
- don't use bip/pip-style proposal / acceptance review until "1.0 feature freeze" timeframe.

**Comment by daira** [comment]
<a href="https://github.com/daira"><img src="https://avatars1.githubusercontent.com/u/643204?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [daira](https://github.com/daira)**
_Monday Sep 19, 2016 at 09:38 UTC_

----

I have a draft ZIP 0 describing the process, which is based very loosely on BIP 1.

**Comment by daira** [comment]
<a href="https://github.com/nathan-at-least"><img src="https://avatars2.githubusercontent.com/u/4369700?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nathan-at-least](https://github.com/nathan-at-least)**
_Tuesday Jan 24, 2017 at 22:35 UTC_

----

We're now revisiting this goal and talking about the ZIP process.

**Comment by ioptio** [comment]
This can be closed once https://github.com/zcash/zips/pull/206 is merged

**Comment by daira** [comment]
ZIP 0 is at https://github.com/zcash/zips/blob/master/zip-0000.rst .
