### ISSUE TITLE
[ZIP 32] Specify BIP32 for Zcash

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2320]
<a href="https://github.com/Ayms"><img src="https://avatars0.githubusercontent.com/u/759202?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Ayms](https://github.com/Ayms)**
_Friday Nov 25, 2016 at 16:50 UTC_
_Originally opened as https://github.com/zcash/zips/issues/95_

----

One implementation/suggestion inspired from https://github.com/zcash/zcash/issues/1893 is [here]( https://github.com/Ayms/zcash-wallets)

**Comment by daira** [comment]
<a href="https://github.com/daira"><img src="https://avatars1.githubusercontent.com/u/643204?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [daira](https://github.com/daira)**
_Friday Nov 25, 2016 at 17:45 UTC_

----

The Code of Conduct link from README.md has been fixed.

**Comment by str4d** [comment]
https://github.com/zcash/zips/pull/157 has been merged, and there is now plenty of precedent for how to handle Zcash t-addresses (simply follow BIP 44 with the Zcash `coin_type` defined in SLIP 44).
