### ISSUE TITLE
ZIP process README preamble formatting and year incorrect

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2329]
<a href="https://github.com/arcalinea"><img src="https://avatars1.githubusercontent.com/u/12245008?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [arcalinea](https://github.com/arcalinea)**
_Wednesday Mar 08, 2017 at 23:09 UTC_
_Originally opened as https://github.com/zcash/zips/issues/121_

----

The preamble in the daira-zip-process appears in markdown with `<pre></pre>` html tags exposed, and no formatting. Might be a spacing issue?

Also, the year for the "Created" field says 2011 which can't be right, Zcash wasn't around back then :)

**Comment by ioptio** [comment]
ping @acityinohio FYI for your ZIP 0 PR

**Comment by ioptio** [comment]
This is fixed in https://github.com/zcash/zips/blob/master/zip-0000.rst
