### ISSUE TITLE
ZCash Upgrade Build Issue

### ISSUE THREAD

**Issue by ChadA1997** [zcash/zcash#2349]
### Describe the issue
Went to upgrade zcash 1.3.0 to the current version on our pool and we have been dealing with several errors. We use Ubunta 14.0 on linux, we had v1.3.0 running fine. We noticed our zcash-cli was reporting out of date error. Went to upgrade to current zcash build and obtained some all-recursive fails, make fails and undefined reference errors. Is it possible a space issue? Can someone help us identify the issue. A snippet of the errors below.

### Can you reliably reproduce the issue?
libbitcoin_server.a(libbitcoin_server_a-txdb.o):/home/zcashnowjosh/code/zcash/src/leveldbwrapper.h:105: more undefined references to `leveldb::Status::ToString[abi:cxx11]() const' follow
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
Makefile:2143: recipe for target 'test/test_bitcoin' failed
make[2]: *** [test/test_bitcoin] Error 1
Makefile:2215: recipe for target 'zcash-gtest' failed
make[2]: *** [zcash-gtest] Error 1
make[2]: Leaving directory '/home/zcashnowjosh/code/zcash/src'
Makefile:5179: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/zcashnowjosh/code/zcash/src'
Makefile:625: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

### The version of Zcash you were using:
we were using v1.3.0, went to upgrade to v1.8.0

**Comment by daira** [comment]
Ubuntu 14 is slightly ambiguous; do you mean [14.04 LTS](http://releases.ubuntu.com/14.04/)? That has gcc 4.8, which is likely your problem here.

Can you record the full transcript of following the "Compile it yourself" instructions in the [1.0 User Guide](https://github.com/zcash/zcash/wiki/1.0-User-Guide#or-compile-it-yourself), and post them here if they fail, please?

**Comment by ChadA1997** [comment]
operating system is Ubuntu 1604 x86_64

**Comment by ChadA1997** [comment]
followed their user guide here are the errors
make[2]: *** [test/test_bitcoin] Error 1
Makefile:2215: recipe for target 'zcash-gtest' failed
make[2]: *** [zcash-gtest] Error 1
collect2: error: ld returned 1 exit status
Makefile:2143: recipe for target 'test/test_bitcoin' failed
make[2]: Leaving directory '/home/zcashnowjosh/code/zcash/src'
Makefile:5179: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/zcashnowjosh/code/zcash/src'
Makefile:625: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by ChadA1997** [comment]
i redownloaded the dependencies and now we get this:

In function `HandleError(leveldb::Status const&)':
/home/zcashnowjosh/code/zcash/src/leveldbwrapper.cpp:20: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
libbitcoin_server.a(libbitcoin_server_a-leveldbwrapper.o): In function `CLevelDBWrapper::CLevelDBWrapper(boost::filesystem::path const&, unsigned long, bool, bool)':
/home/zcashnowjosh/code/zcash/src/leveldbwrapper.cpp:61: undefined reference to `leveldb::DestroyDB(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, leveldb::Options const&)'
/home/zcashnowjosh/code/zcash/src/leveldbwrapper.cpp:67: undefined reference to `leveldb::DB::Open(leveldb::Options const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, leveldb::DB**)'
libbitcoin_server.a(libbitcoin_server_a-txdb.o): In function `bool CLevelDBWrapper::Exists<char>(char const&) const':
/home/zcashnowjosh/code/zcash/src/leveldbwrapper.h:138: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
libbitcoin_server.a(libbitcoin_server_a-txdb.o): In function `bool CLevelDBWrapper::Read<char, int>(char const&, int&) const':
/home/zcashnowjosh/code/zcash/src/leveldbwrapper.h:105: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
libbitcoin_server.a(libbitcoin_server_a-txdb.o): In function `bool CLevelDBWrapper::Read<std::pair<char, uint256>, bool>(std::pair<char, uint256> const&, bool&) const':
/home/zcashnowjosh/code/zcash/src/leveldbwrapper.h:105: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
libbitcoin_server.a(libbitcoin_server_a-txdb.o): In function `bool CLevelDBWrapper::Exists<std::pair<char, uint256> >(std::pair<char, uint256> const&) const':
/home/zcashnowjosh/code/zcash/src/leveldbwrapper.h:138: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
libbitcoin_server.a(libbitcoin_server_a-txdb.o): In function `bool CLevelDBWrapper::Read<std::pair<char, uint256>, CDiskTxPos>(std::pair<char, uint256> const&, CDiskTxPos&) const':
/home/zcashnowjosh/code/zcash/src/leveldbwrapper.h:105: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
libbitcoin_server.a(libbitcoin_server_a-txdb.o):/home/zcashnowjosh/code/zcash/src/leveldbwrapper.h:105: more undefined references to `leveldb::Status::ToString[abi:cxx11]() const' follow
collect2: error: ld returned 1 exit status
Makefile:2235: recipe for target 'zcashd' failed
make[2]: *** [zcashd] Error 1
make[2]: Leaving directory '/home/zcashnowjosh/code/zcash/src'
Makefile:5179: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/zcashnowjosh/code/zcash/src'
Makefile:625: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by ChadA1997** [comment]
Here is our latest list of Errors, I am really hoping someone can help, the Developers Site for ZNomp are no help right now, they just said "We dont know it must be an issue with ZCash Cli.  So our Mining Pool is down and no one has any answers :(  

libbitcoin_server.a(libbitcoin_server_a-leveldbwrapper.o): In function `HandleError(leveldb::Status const&)':
/home/zcashnowjosh/code/zcash/src/leveldbwrapper.cpp:20: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
libbitcoin_server.a(libbitcoin_server_a-leveldbwrapper.o): In function `CLevelDBWrapper::CLevelDBWrapper(boost::filesystem::path const&, unsigned long, bool, bool)':
/home/zcashnowjosh/code/zcash/src/leveldbwrapper.cpp:61: undefined reference to `leveldb::DestroyDB(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, leveldb::Options const&)'
/home/zcashnowjosh/code/zcash/src/leveldbwrapper.cpp:67: undefined reference to `leveldb::DB::Open(leveldb::Options const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, leveldb::DB**)'
libbitcoin_server.a(libbitcoin_server_a-txdb.o): In function `bool CLevelDBWrapper::Exists<char>(char const&) const':
/home/zcashnowjosh/code/zcash/src/leveldbwrapper.h:138: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
libbitcoin_server.a(libbitcoin_server_a-txdb.o): In function `bool CLevelDBWrapper::Read<char, int>(char const&, int&) const':
/home/zcashnowjosh/code/zcash/src/leveldbwrapper.h:105: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
libbitcoin_server.a(libbitcoin_server_a-txdb.o): In function `bool CLevelDBWrapper::Read<std::pair<char, uint256>, bool>(std::pair<char, uint256> const&, bool&) const':
/home/zcashnowjosh/code/zcash/src/leveldbwrapper.h:105: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
libbitcoin_server.a(libbitcoin_server_a-txdb.o): In function `bool CLevelDBWrapper::Exists<std::pair<char, uint256> >(std::pair<char, uint256> const&) const':
/home/zcashnowjosh/code/zcash/src/leveldbwrapper.h:138: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
libbitcoin_server.a(libbitcoin_server_a-txdb.o): In function `bool CLevelDBWrapper::Read<std::pair<char, uint256>, CDiskTxPos>(std::pair<char, uint256> const&, CDiskTxPos&) const':
/home/zcashnowjosh/code/zcash/src/leveldbwrapper.h:105: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
libbitcoin_server.a(libbitcoin_server_a-txdb.o):/home/zcashnowjosh/code/zcash/src/leveldbwrapper.h:105: more undefined references to `leveldb::Status::ToString[abi:cxx11]() const' follow
collect2: error: ld returned 1 exit status
Makefile:2235: recipe for target 'zcashd' failed
make[2]: *** [zcashd] Error 1
make[2]: *** Waiting for unfinished jobs....
libbitcoin_server.a(libbitcoin_server_a-txdb.o): In function `bool CLevelDBWrapper::Exists<char>(char const&) const':
/home/zcashnowjosh/code/zcash/src/leveldbwrapper.h:138: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
libbitcoin_server.a(libbitcoin_server_a-txdb.o): In function `bool CLevelDBWrapper::Read<char, int>(char const&, int&) const':
/home/zcashnowjosh/code/zcash/src/leveldbwrapper.h:105: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
libbitcoin_server.a(libbitcoin_server_a-txdb.o): In function `bool CLevelDBWrapper::Read<std::pair<char, uint256>, bool>(std::pair<char, uint256> const&, bool&) const':
/home/zcashnowjosh/code/zcash/src/leveldbwrapper.h:105: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
libbitcoin_server.a(libbitcoin_server_a-txdb.o): In function `bool CLevelDBWrapper::Exists<std::pair<char, uint256> >(std::pair<char, uint256> const&) const':
/home/zcashnowjosh/code/zcash/src/leveldbwrapper.h:138: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
libbitcoin_server.a(libbitcoin_server_a-txdb.o): In function `bool CLevelDBWrapper::Read<std::pair<char, uint256>, CDiskTxPos>(std::pair<char, uint256> const&, CDiskTxPos&) const':
/home/zcashnowjosh/code/zcash/src/leveldbwrapper.h:105: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
libbitcoin_server.a(libbitcoin_server_a-txdb.o):/home/zcashnowjosh/code/zcash/src/leveldbwrapper.h:105: more undefined references to `leveldb::Status::ToString[abi:cxx11]() const' follow
libbitcoin_server.a(libbitcoin_server_a-leveldbwrapper.o): In function `CLevelDBWrapper::CLevelDBWrapper(boost::filesystem::path const&, unsigned long, bool, bool)':
/home/zcashnowjosh/code/zcash/src/leveldbwrapper.cpp:61: undefined reference to `leveldb::DestroyDB(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, leveldb::Options const&)'
/home/zcashnowjosh/code/zcash/src/leveldbwrapper.cpp:67: undefined reference to `leveldb::DB::Open(leveldb::Options const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, leveldb::DB**)'
collect2: error: ld returned 1 exit status
Makefile:2215: recipe for target 'zcash-gtest' failed
make[2]: *** [zcash-gtest] Error 1
libbitcoin_server.a(libbitcoin_server_a-leveldbwrapper.o): In function `HandleError(leveldb::Status const&)':
/home/zcashnowjosh/code/zcash/src/leveldbwrapper.cpp:20: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
libbitcoin_server.a(libbitcoin_server_a-leveldbwrapper.o): In function `CLevelDBWrapper::CLevelDBWrapper(boost::filesystem::path const&, unsigned long, bool, bool)':
/home/zcashnowjosh/code/zcash/src/leveldbwrapper.cpp:61: undefined reference to `leveldb::DestroyDB(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, leveldb::Options const&)'
/home/zcashnowjosh/code/zcash/src/leveldbwrapper.cpp:67: undefined reference to `leveldb::DB::Open(leveldb::Options const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, leveldb::DB**)'
libbitcoin_server.a(libbitcoin_server_a-txdb.o): In function `bool CLevelDBWrapper::Exists<char>(char const&) const':
/home/zcashnowjosh/code/zcash/src/leveldbwrapper.h:138: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
libbitcoin_server.a(libbitcoin_server_a-txdb.o): In function `bool CLevelDBWrapper::Read<char, int>(char const&, int&) const':
/home/zcashnowjosh/code/zcash/src/leveldbwrapper.h:105: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
libbitcoin_server.a(libbitcoin_server_a-txdb.o): In function `bool CLevelDBWrapper::Read<std::pair<char, uint256>, bool>(std::pair<char, uint256> const&, bool&) const':
/home/zcashnowjosh/code/zcash/src/leveldbwrapper.h:105: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
libbitcoin_server.a(libbitcoin_server_a-txdb.o): In function `bool CLevelDBWrapper::Exists<std::pair<char, uint256> >(std::pair<char, uint256> const&) const':
/home/zcashnowjosh/code/zcash/src/leveldbwrapper.h:138: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
libbitcoin_server.a(libbitcoin_server_a-txdb.o): In function `bool CLevelDBWrapper::Read<std::pair<char, uint256>, CDiskTxPos>(std::pair<char, uint256> const&, CDiskTxPos&) const':
/home/zcashnowjosh/code/zcash/src/leveldbwrapper.h:105: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
libbitcoin_server.a(libbitcoin_server_a-txdb.o):/home/zcashnowjosh/code/zcash/src/leveldbwrapper.h:105: more undefined references to `leveldb::Status::ToString[abi:cxx11]() const' follow
collect2: error: ld returned 1 exit status
Makefile:2143: recipe for target 'test/test_bitcoin' failed
make[2]: *** [test/test_bitcoin] Error 1
make[2]: Leaving directory '/home/zcashnowjosh/code/zcash/src'
Makefile:5179: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/zcashnowjosh/code/zcash/src'
Makefile:625: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by radix42** [comment]
did you do a `make clean` before building the new version....since you said upgrade I'm assuming you meant you did a `git pull` and built in the same directory. You should always do a `make clean` before running `zcutil/build.sh`....and if you're NOT using the build.sh script and are invoking `make` directly, that can cause errors too, especially if upgrading, as the dependencies have changed.

**Comment by daira** [comment]
A better option than using ``make clean`` is to create a new git clone. @ChadA1997: How did you re-download the dependencies?

**Comment by ChadA1997** [comment]
Thanks so Much for all your help, we did a clean up and rebuild from scratch in order to correct.  Appreciate all your help.   Thanks again

**Comment by daira** [comment]
I [added instructions to the 1.0 User Guide](https://github.com/zcash/zcash/wiki/1.0-User-Guide/_compare/65f585b51fe761110e29d76e7cb1e2c74a3e6495...14a0238e2ce04d4f4d0a9ecfe380f4b289940a0c) to rebuild from scratch if an incremental rebuild fails.
