### ISSUE TITLE
Signal error when making a PourTx w/ fee greater than the vpub output.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#235]
In a (not-yet committed) branch I'm adding fee payment into [``MakePourTx`` (in rev a5a8c9od without the change described)](https://github.com/Electric-Coin-Company/zerocashd/blob/a5a8c0d667a61df39c1f85d877aa9c152ac90ea3/src/wallet.cpp#L1171).  If the fee given by the caller is larger than the ``vpub`` this is incoherent, and my current hack is to clip the fee to ``vpub`` in that case, silently.

However, this should really be an error, but I don't want to spend the effort to figure out how to properly handle errors (exceptions? error return values? What does upstream tend to do? What about for RPC commands?), so I'm filing this ticket instead.

**TODO:** After making the commit, fix the source link above to be revision-specific.

**Comment by daira** [comment]
@defuse can this be closed?

**Comment by ebfull** [comment]
Right now you will get a "constraint not satisfied by inputs" error from the pour prover. We could be more specific here.

**Comment by defuse** [comment]
Okay I think this can be closed, so I'm closing it.
