### ISSUE TITLE
Not receiving payments while transactions can be found on ZCHAIN

### ISSUE THREAD

**Issue by RedTong** [zcash/zcash#2350]

**Comment by daira** [comment]
Hi @FuTong. Can you restore your description and say how the problem was resolved, please? Otherwise it is not clear what the resolution was.

**Comment by RedTong** [comment]
### Describe the issue
Hi guys, from May'1, my local wallet(zcash-1.0.8-1 on centos7.2) did not receive payments, while the transactions can be found on "explorer.zcha.in". 
I use the command `zcash-cli gettransactions | grep amount` to get the number of the transactions I have finished, however, I did only receive the payments from Apr'29 to Apr'30.
What's more, I tried to generate a new t-address, but it still not works. Also I tried to use another zchah pool, the problem was still the same, i.e. transactions can be found on ZCHAIN while my local wallet didnot have any changes.

[root@localhost zcash]# ./src/zcash-cli getinfo
{
  "version": 1000851,
  "protocolversion": 170002,
  "walletversion": 60000,
  "balance": 0.04034971,
  "blocks": 106118,
  "timeoffset": -3677,
  "connections": 8,
  "proxy": "",
  "difficulty": 936511.565646379,
  "testnet": false,
  "keypoololdest": 1492885940,
  "keypoolsize": 101,
  "paytxfee": 0.00000000,
  "relayfee": 0.00000100,
  "errors": ""
}

Please help.

**Comment by RedTong** [comment]
The issue was resolved by using `zcashd -reindex`, that means I found my total balance, but I am not sure it can still work when new balance or transactions are paid. I am validating it.

**Comment by RedTong** [comment]
It is ok until now, so I close the issue.
