### ISSUE TITLE
Create package(s) that work on Ubuntu

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2358]
Ideally, Ubuntu Trusty and later should be supported.

Note that Trusty has gcc 4.8 which uses a different version of libgomp; I *think* it is sufficient to just compile with a later gcc and declare a dependency on the correct libgomp, but if that doesn't work then it might be necessary to have more than one package.

[Edit: oh, just declaring a dependency doesn't work because the correct libgomp is not in the default Ubuntu Trusty repos.]

**Comment by daira** [comment]
See #2257 for how the Debian package fails to install on Ubuntu Trusty.

**Comment by daira** [comment]
See also #1692 about libgomp errors.

**Comment by mms710** [comment]
@mdr0id Do we have CI for Ubuntu that uses the Debian package?

**Comment by mdr0id** [comment]
I'd assume the binary would more or less work. Besides random compiler
specific stuff per platform, the issues are likely embedded in the
packaging system.

**Comment by mdr0id** [comment]
NVM it seems those are not binary compatible

**Comment by str4d** [comment]
We provide Debian packages, and [Ubuntu 20.04 is a Tier 1 platform](https://zcash.github.io/zcash/user/platform-support.html#tier-1).
