### ISSUE TITLE
Add timestamps to individual `rpc-tests.sh` outputs.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#2368]
Running `rpc-tests.sh` is the longest single step in the merge-acceptance CI process. There's no timing information in the stdout log. This would be helpful in case the cost were disproportionately from a few tests which we could refactor, or if the costs are spread throughout the common framework code, we may be able to optimize that also.

**Comment by mms710** [comment]
This is in progress.

**Comment by str4d** [comment]
The RPC test outputs have had timestamps since #4874.
