### ISSUE TITLE
[str4d's standalone miner fork] Standalone miner becomes blocked after some time

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2379]
<a href="https://github.com/sarath-hotspot"><img src="https://avatars2.githubusercontent.com/u/8268944?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sarath-hotspot](https://github.com/sarath-hotspot)**
_Wednesday Oct 19, 2016 at 05:34 UTC_
_Originally opened as https://github.com/str4d/zcash/issues/12_

----

[logs.zip](https://github.com/str4d/zcash/files/538002/logs.zip)

Hi str4d, 
I ran standalone miner for ~20 minutes.  All threads in the miner blocked and it stopped generating hashes. 
I could not figure out the bug from stacktrace. 

Attached coredump & log file.

It was after integrating https://github.com/str4d/zcash/pull/11

**Comment by daira** [comment]
<a href="https://github.com/JanKalin"><img src="https://avatars3.githubusercontent.com/u/18305372?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [JanKalin](https://github.com/JanKalin)**
_Thursday Oct 20, 2016 at 13:38 UTC_

----

I can confirm that there are problems. I have two machines:
- `Ubuntu 16.04.1 LTS` in a VM with `gcc (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609` and
- `Debian GNU/Linux 7.11 (wheezy)` natively with  `gcc (Debian 4.7.2-5) 4.7.2`

Because the Debian's GCC is older, I need to make some edits to get Zcash to compile. However:
- These edits are nowhere near the solver code - see [mydiff.txt](https://github.com/str4d/zcash/files/541473/mydiff.txt)
- I need to make the same edits for both the Zcash official release and str4d's fork for the standalone miner
- Both the Zcash and and the fork work perfectly on both machines, all the tests pass, the zcashd from the official release mines, as does zcash-miner.

But the `zcash-miner` with Tromp's solver works only on the Ubuntu machine - well, it has now been running for around 40 minutes and is still mining. If I run it without arguments, it starts running test solves on Ubuntu, while on Debian it just hangs. If I connect to a stratum server (zec.suprnova.cc or zmine.io) from Debian it segfaults.

Note that Tromp's solver from https://github.com/tromp/equihash works fine on both machines.

EDIT: Moved this from the pull request comments

EDIT: Another physical machine with `Ubuntu 16.04.1 LTS` also works fine

**Comment by daira** [comment]
<a href="https://github.com/jinsu1701"><img src="https://avatars3.githubusercontent.com/u/23018950?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jinsu1701](https://github.com/jinsu1701)**
_Sunday Oct 23, 2016 at 22:34 UTC_

----

I seem to face similar problems. I usually then stop the miner and restart to get it working again. 
As far as I can see, I did not observe these problems on the RC1 version. 
I am using 1 core only for execution and memory usage is also not very high.
My miner is using the Zmine pool and the tromp solver,

The situation presents itself as follows:
The miner is running for some time (the last attempt was 77 minutes), then the following entry appears in the log:
`ZcashMinerThread runtime error: write: Broken pipe`

After this, there is no further processing as the CPU load drops to minimal levels.

Following this event, the miner seems to have lost the pool connection and tries to reconnect:

```
Connecting to stratum server zmine.io:1337
Connected!
```

Then this warning is logged and the connection seems to be lost again:

```
[WARN] read_until: End of file
Reconnecting in 3 seconds...
```

This situation repeats for several times, sometimes this log entry appears also:
`[WARN] read_until: Connection reset by peer`

After some time of retrying to connect, the miner seems to have a stable connection again, a target is logged and the worker is authorised, But the miner does only log the reception of new jobs but does no processing anymore.

**Comment by daira** [comment]
<a href="https://github.com/JanKalin"><img src="https://avatars3.githubusercontent.com/u/18305372?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [JanKalin](https://github.com/JanKalin)**
_Tuesday Oct 25, 2016 at 12:55 UTC_

----

At least for the `Debian GNU/Linux 7.11 (wheezy)` natively with `gcc (Debian 4.7.2-5) 4.7.2` the problem is most likely some issue with the compiler, templates and bad C++11 support.

I had the same issue with https://github.com/nicehash/nheqminer - it would run benchmarks just fine, but when connecting to a stratum server it segfaulted. I ran it with debugger and it failed in the function

```
template <typename Miner, typename Job, typename Solution>
void StratumClient<Miner, Job, Solution>::workLoop()
```

of the `src/libstratum/StratumClient.cpp`.

Apparently the object is not properly constructed and the very first line `while (m_running)` references a null pointer and crashes the program.

EDIT: And solved

```
diff --git a/src/libstratum/StratumClient.cpp b/src/libstratum/StratumClient.cpp
index 1faba59..9969c8b 100644
--- a/src/libstratum/StratumClient.cpp
+++ b/src/libstratum/StratumClient.cpp
@@ -64,7 +64,7 @@ template <typename Miner, typename Job, typename Solution>
 void StratumClient<Miner, Job, Solution>::startWorking()
 {
     m_work.reset(new std::thread([&]() {
-        workLoop();
+        this->workLoop();
     }));
 }
```

**Comment by daira** [comment]
<a href="https://github.com/str4d"><img src="https://avatars3.githubusercontent.com/u/4993799?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [str4d](https://github.com/str4d)**
_Saturday Oct 29, 2016 at 06:05 UTC_

----

Thanks for the feedback! I'll put some time into improvements after I get some sleep :sweat_smile:

**Comment by nuttycom** [comment]
Closing as stale.
