### ISSUE TITLE
[str4d's standalone miner fork] Exits immediately (core dumped)

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2380]
<a href="https://github.com/Artazor"><img src="https://avatars3.githubusercontent.com/u/185374?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Artazor](https://github.com/Artazor)**
_Friday Oct 28, 2016 at 23:04 UTC_
_Originally opened as https://github.com/str4d/zcash/issues/13_

----

Just compiled the standalone-miner version branch

```
Thank you for running a Zcash miner!
You're helping to strengthen the network :)

You are running 20 mining threads.

Since starting this node 0 seconds ago:
- You have validated 0 transactions...
- You have contributed 0.0000 Sol/s on average to the network solution rate.
- You have completed 0 Equihash solver runs.

Init message: Done loading

[Press Ctrl+C to exit] [Set 'showmetrics=0' to hide]
terminate called without an active exception
Aborted (core dumped)
```

**Comment by daira** [comment]
<a href="https://github.com/atomicpirate"><img src="https://avatars0.githubusercontent.com/u/9212221?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [atomicpirate](https://github.com/atomicpirate)**
_Saturday Oct 29, 2016 at 04:00 UTC_

----

I see the exact same issue, using gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2). gdb shows this backtrace:

```
(gdb) run -stratum=stratum+tcp://zmine.io:1337 -user=<taddress> -equihashsolver=tromp -genproclimit=-1

<snip>

[Press Ctrl+C to exit] [Set 'showmetrics=0' to hide]
terminate called without an active exception
[Thread 0x7ffff6b29700 (LWP 5854) exited]

Thread 1 "zcash-miner" received signal SIGABRT, Aborted.
0x00007ffff6d63428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54  ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff6d63428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff6d6502a in __GI_abort () at abort.c:89
#2  0x00007ffff7ae484d in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff7ae26b6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff7ae2701 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00005555555966eb in std::thread::~thread (this=<optimized out>, __in_chrg=<optimized out>) at /usr/include/c++/5/thread:151
#6  std::default_delete<std::thread>::operator() (__ptr=<optimized out>, this=0x7fffffffd7a0) at /usr/include/c++/5/bits/unique_ptr.h:76
#7  std::unique_ptr<std::thread, std::default_delete<std::thread> >::~unique_ptr (this=0x7fffffffd7a0, __in_chrg=<optimized out>) at /usr/include/c++/5/bits/unique_ptr.h:236
#8  StratumClient<ZcashMiner, ZcashJob, EquihashSolution>::~StratumClient (this=0x7fffffffd620, __in_chrg=<optimized out>) at libstratum/StratumClient.h:38
#9  0x00005555555ca6a6 in main (argc=<optimized out>, argv=<optimized out>) at standaloneminer.cpp:247
(gdb) quit
```

**Comment by daira** [comment]
<a href="https://github.com/hazinstore"><img src="https://avatars1.githubusercontent.com/u/22350191?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hazinstore](https://github.com/hazinstore)**
_Saturday Oct 29, 2016 at 05:02 UTC_

----

> Thread 1 "zcash-miner" received signal SIGABRT, Aborted.
> 0x00007ffff6d63428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
> 54  ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
> (gdb) bt
> #0  0x00007ffff6d63428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
> #1  0x00007ffff6d6502a in __GI_abort () at abort.c:89

http://man7.org/linux/man-pages/man3/abort.3.html

> SIGABRT
> The SIGABRT signal is sent to a process to tell it to abort, i.e. to terminate. The signal is usually initiated by the process itself when it calls abort function of the C Standard Library, but it can be sent to the process from outside like any other signal.

Looks like DNS lookup failure or something caused to abort and nothing caught it.

**Comment by arcalinea** [comment]
@str4d Can this be closed?

**Comment by nuttycom** [comment]
Closing as stale.
