### ISSUE TITLE
[str4d's bitcore fork] Please update zcash for bitcore

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2382]
<a href="https://github.com/slush0"><img src="https://avatars1.githubusercontent.com/u/565341?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [slush0](https://github.com/slush0)**
_Thursday May 11, 2017 at 15:23 UTC_
_Originally opened as https://github.com/str4d/zcash/issues/19_

----

Hello,

bitcore fork stil uses zcash  v1.0.4. Not only it is outdated, buggy and unsupported, but it even cannot build, because you remove dependencies from z.cash site (namely https://z.cash/depends-sources/zeromq-4.0.4.tar.gz).

Please update zcash for bitcore to latest binary, otherwise we'll have to stop supporting zcash in TREZOR :(.

**Comment by daira** [comment]
<a href="https://github.com/radix42"><img src="https://avatars1.githubusercontent.com/u/6250192?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [radix42](https://github.com/radix42)**
_Thursday May 11, 2017 at 17:06 UTC_

----

I agree that it's bitrotted a bit, and needs some work to be updated to 1.0.8-1...but I just built it last week

**Comment by daira** [comment]
<a href="https://github.com/nathan-at-least"><img src="https://avatars2.githubusercontent.com/u/4369700?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nathan-at-least](https://github.com/nathan-at-least)**
_Thursday May 11, 2017 at 17:30 UTC_

----

Hello. I apologize for the trouble. I had not realized anyone was relying on this fork other than our own internal explorer projects. I've raised the priority of this, but unfortunately it's too late for 1.0.9 (due out early next week).

Please see the upstream Zcash ticket, and comment there to ensure more of the zcash-dev team notices it: https://github.com/zcash/zcash/issues/1534#issuecomment-300859932

**Comment by daira** [comment]
<a href="https://github.com/nathan-at-least"><img src="https://avatars2.githubusercontent.com/u/4369700?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nathan-at-least](https://github.com/nathan-at-least)**
_Thursday May 11, 2017 at 17:46 UTC_

----

Note, Trezor and @radix42 are relying on this branch: https://github.com/str4d/zcash/tree/v1.0.4-bitcore-3

**Comment by daira** [comment]
Duplicate of #1534.

**Comment by sennevb** [comment]
+1 we need V1.08
