### ISSUE TITLE
Node-configured wall-clock mempool transaction expiry

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#2384]
Upstream Bitcoin, since 0.12, has a config option `mempoolexpirytime` which evicts unconfirmed transactions when they have been in the mempool for too long.

The default value was 72 hours.  It was recently changed to 2 weeks.
https://github.com/bitcoin/bitcoin/blame/08a7316c144f9f2516db8fa62400893f4358c5ae/src/validation.h#L72

We currently do not have a mempool expiry by time option.  Should we add one?  Also related to limiting the mempool by size #2344.

**Comment by nathan-at-least** [comment]
We like this as a 1.0.10 candidate over limiting mempool size as a robustness improvement because the implementation and systemic-effects seem simpler.

**Comment by nathan-at-least** [comment]
Upstream PR: https://github.com/bitcoin/bitcoin/pull/9312

**Comment by bitcartel** [comment]
@str4d You mentioned you had a branch with some related backports which were in progress?

**Comment by daira** [comment]
Out of time for 1.0.11.

**Comment by daira** [comment]
Is this obviated by Overwinter transaction expiry?

**Comment by daira** [comment]
The consensus-level transaction expiry added by Overwinter, is optional for the sender. The advantage of having a node-enforced expiry based on wall clock time, would be that it also applies to transactions that have consensus-level expiry disabled, including transactions created for a denial-of-service attack.

**Comment by nuttycom** [comment]
Adding complexity beyond ZIP 203 and ZIP 401 is probably not useful.
