### ISSUE TITLE
Remove redundant release instructions in favor of ./zcutil/build-debian-package.sh

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#2387]

**Comment by str4d** [comment]
AFAICT there is nothing redundant either in current release process or #2281. The Debian-related changes in the release process are to update the Debian changelog, which is stored in-repo. `build-debian-package.sh` is a separate step that uses the repo contents to build the package.

**Comment by nathan-at-least** [comment]
@str4d: You are correct that there are no redundant high-level steps, but the particular pipeline to generate particular debian-specific versions is duplicate code and easy to mess up. Anyway, I'm going to close this in favor of #2391.
