### ISSUE TITLE
zeromq configure script posix compliance

### ISSUE THREAD

**Issue by xcko** [zcash/zcash#2405]
### Describe the issue
Please provide a general summary of the issue you're experiencing

Compiling zcash on linux x86_64 fails while running configure from zeromq

#### If so, please list the steps to reproduce below:
1. run ./zcutil/build.sh from version 1.0.9
2. or go into depends/work/build/$arch/zeromq/4.2.1-xxxxxx and ./configure
3. use dash as posix bourne shell

### Expected behaviour
Tell us what should happen

configure script should succeed and continue

### Actual behaviour + errors
Tell us what happens instead including any noticable error output (any messages displayed on-screen when e.g. a crash occurred)

warnings of test failing, unknown symbol x near line 
20352     if test "x$with_poller" == "x"; then
20357    if test "$pollers" == "auto"; then
This is caused by == not being posix. Replace with = and configure runs as expected.

### The version of Zcash you were using:
Run `zcashd --version` to find out

As this is before zcashd has compiled, I can't supply a version, but it is applicable to git version 1.0.8, 1.0.8-1, and 1.0.9.

If zcash is not responsible for zeromq, I can raise an issue upstream.

### Machine specs:
- OS name + version: Linux CRUX 3.3
- CPU: x86_64 sandybridge
- RAM: 4G
- Disk size: 150G
- Disk Type (HD/SDD): SSD
- Linux kernel version (uname -a): Linux 4.11.0 #14 SMP Wed May 24 16:20:37 PDT 2017 x86_64 Intel(R) Core(TM) i5-2540M CPU @ 2.60GHz GenuineIntel GNU/Linuxu
- Compiler version (gcc -version): gcc (CRUX-x86_64-multilib) 6.3.0

**Comment by daira** [comment]
``./configure`` is generated by autotools, so this is an autotools bug.

**Comment by daira** [comment]
Note that using dash as /bin/sh is likely to cause a lot more breakage than it is worth IMHO, not just for autotools-based packages: https://bugs.launchpad.net/ubuntu/+source/dash/+bug/141481

**Comment by xcko** [comment]
My distro uses dash as /bin/sh by default, so I'm comfortable leaving it as is.
Thanks for the heads up though.
As this issue does not pertain to zcash, I'll close it.

**Comment by daira** [comment]
Reopening to reproduce and then document the need to use bash in the User Guide if necessary.

**Comment by daira** [comment]
Case of #2677.

**Comment by ioptio** [comment]
@daira any update on documentation needs here?

**Comment by nuttycom** [comment]
Closing as stale; anyone who needs to be able to build without `bash` please open a new ticket. This is likely obsolete due to the several upgrades we've made to zeromq over the years, and the steps described to reproduce the error are no longer usable given changes in the depends system over the intervening years.
