### ISSUE TITLE
New general multi-input, multi-output, multi-transaction RPC call.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#2408]
There are a variety of user needs and code architecture improvements all related to issuing and tracking transactions. I have an (unverified) suspicion we may be able to provide a single interface to meet all of the needs, or if not it will at least be a useful exercise to do before improving or developing separate RPC calls.

The needs include:

- sending from many addresses (t- or z-) to many addresses
- merging many UTXOs or JoinSplits into fewer
- sweeping mining rewards
- paying out mining rewards to many pool participants

A given request for any of these may always potentially hit the transaction size limitation, or may hit other edge cases such as rate limiting, ad-hoc miner policies guarding against the quadratic signing performance problem, etc… So, *if* the API could issue multiple transactions it might be more usable.

Additionally, if there were a multi-transaction-possible RPC interface, we may be able to introduce privacy-versus-performance knobs. For example, merging many UTXOs from many t-addrs into a z-addr could be a single transaction, or for a 'very high privacy mode' might shield each UTXO individually, and then merge those notes over time in many single-JS transactions.

Multi-transaction implies a long-running process. I think this is orthogonal to the 'async + polling' design of `z_sendmany` versus a synchronous call.

**Comment by tromer** [comment]
This is a generalization of #1785 and #1811. See discussion there for use cases.

**Comment by nuttycom** [comment]
superseded by https://github.com/zcash/zcash/issues/6123
