### ISSUE TITLE
Provider user support (documentation or feature work) for merging many UTXOs

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#2409]
Right now merging many UTXOs is a challenge due to several factors: performance problems, RPC trickiness. I filed #2408 as a brainstorm for a broad technical solution. That may be too broad of a scope to meet users needs in the shorter term. This ticket is about helping users merge many UTXOs in the shorter term, whether through documentation changes or API tweaks or publishing 'client recipe' examples.

**Comment by chengevo** [comment]
For exchanges, it's possible to accept mining rewards, which are mostly small amount of UTXOs. To create a transaction from a large number of UTXOs usually takes a long time. 

I think for this situation, a possible solution is to transfer all the balance to another wallet, which clears all UTXOs, and then transfers all the ZEC back.

**Comment by ioptio** [comment]
This is complete with `z_mergetoaddress` RPC
