### ISSUE TITLE
configure fails to detect libdb_cxx libraries

### ISSUE THREAD

**Issue by kondor6c** [zcash/zcash#2410]
### Describe the issue
While attempting to make an RPM of zcash for further distribution I could not get past this dependency issue.

#### If so, please list the steps to reproduce below:
1. install libdb-cxx-devel (on fedora 25)
2. run autogen.sh then configure
3. Fails to detect berkelydb libraries.

### Expected behaviour
configure should be picking up on the library, RPM shows it is installed:
```
[root@example-machine ~]# rpm -ql libdb-cxx-devel
/usr/include/db_cxx.h
/usr/include/libdb/db_cxx.h
/usr/lib64/libdb_cxx.so
```

### Actual behaviour + errors
```
checking for MSG_NOSIGNAL... yes
checking for visibility attribute... yes
checking for Berkeley DB C++ headers... no
configure: error: libdb_cxx headers missing, Bitcoin Core requires this library for wallet functionality (--disable-wallet to disable wallet functionality)
```

### The version of Zcash you were using:
1.0.9

### Machine specs:
- OS name + version: Fedora 25
- CPU: E5-2620v3
- RAM:64GB ECC
- Disk size: 7.5T
- Disk Type (HD/SDD): both
- Linux kernel version (uname -a): 4.10.16-200.fc25.x86_64
- Compiler version (gcc -version): 6.3.1

**Comment by daira** [comment]
Make sure that libdb-cxx-devel is giving you the BerkeleyDB 6.2.23 headers (the precise version is important not just because configure makes assumptions about the major version, but because BDB does *not* maintain database compatibility across even minor versions). I suspect it is giving you 5.x headers. You may have to package BDB 6.2.23 for Fedora if someone else hasn't done that.

**Comment by daira** [comment]
BTW, thanks for taking on trying to build an RPM! :-)

**Comment by kondor6c** [comment]
@daira you are correct I do have the 5.2, thank you for the clarification. Not a problem, I'll make a PR for the spec file when it is finished, I plan on putting in COPR (think PPA's/AUR's/overlay for Fedora)

**Comment by daira** [comment]
To work around this for now you can try to build and install BDB 6.2.23 from source. Please ask if you need help with that. I think there are articles floating around the net on how to do it for 5.x that probably still work for 6.2.23.

**Comment by radix42** [comment]
Is the depends system not building BDB, or is configure just not finding it?
If its just a case of configure not finding the 6.2.23 that got built in depends/, you can hack it on configure and/or pass in stuff via command line to it. I've had to do similar on other platforms (win and mac) before.

**Comment by grote** [comment]
@kondor6c did you get around to build a package?

**Comment by grote** [comment]
@daira Are you aware that linking in BDB6 makes zcash essentially AGPL3+ licensed instead of the intended MIT license?

**Comment by daira** [comment]
@grote see #1469. (It's not correct that this makes Zcash AGPL3+ licensed &ndash; see https://github.com/zcash/zcash/issues/1469#issuecomment-256109335 &ndash; but yes we consider it undesirable.)

**Comment by daira** [comment]
This is no longer relevant. Note that the correct versions of BDB utilities needed to debug/recover the wallet database are copied into `zcutil/bin` as part of building the dependency.
