### ISSUE TITLE
Rejected Transactions Cache

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#2414]
We need a rejected transaction cache. We should review what upstream has for this, although I want to prioritize a simple design.

**Comment by nathan-at-least** [comment]
This seems like a prerequisite for any mempool size limiting *or* new rejection policies, such as #2344, #2384, or #2342 / #2343.

**Comment by nathan-at-least** [comment]
There are two different reasons to reject transactions:

a. they violate a local policy.
b. they were ejected due to resource constraints, but are otherwise acceptable.

**Comment by nathan-at-least** [comment]
Given that we are heading towards a _transaction expiry model_ (see below) I'm in favor of a very simple rejected transactions cache design: keep a set of txids with a memory size limit. When the limit is hit, eject the oldest entries first. No other features.

I would then use this cache for both cases a. and b. above. If a transaction gets rejected or ejected from a node, there's no point in adding more complexity to the rejection cache (such as to distinguish between cases a. and b.) since those transactions will expire anyway.

The _transaction expiry model_ is that any transaction has a bounded time as a candidate for mining. This means users/clients must resubmit transactions when they fail to mine. An example of a node-side policy for expiry is #2384 and an example of wallet-selected expiry is #754.

**Comment by nathan-at-least** [comment]
Note: if we adopt upstream wall-clock node transaction expiry (see #2384), the may have their own design around transaction rejection, so we may not implement this *in that case*. If we implement our own expiry, we may want this rejection cache.

**Comment by mms710** [comment]
@nathan-at-least In backlog grooming last week we made a note to request you go through the Zcash Kawa process for this item if you're still interested in it getting worked on.

**Comment by daira** [comment]
This was added in #4145, to fix #2344. The design is described in [ZIP 401](https://zips.z.cash/zip-0401).
