### ISSUE TITLE
SIGHASH_ANYONE hack for efficient many-input transactions (Bitcoin #6482 inspired.)

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#2415]
**Motivation:** Many real users want to merge many UTXOs. The current method of doing this using many `SIGHASH_ALL` signed inputs has a quadratic scaling cost to verification, which makes block time validation expensive, and causes a worse problem for `GetBlockTemplate` calls which process the entire mempool. One improvement to this situation may be to give users a tool to create cheaper-to-verify transactions. (This doesn't help against malicious users.)

**Proposed Solution:** A variation of https://github.com/bitcoin/bitcoin/pull/6482 in which @gavinandresen proposes a hack to create many-input transactions which are efficient to verify. The hack introduces some subtle security-vulnerability edge cases which must be addressed if we were to adopt this approach.

**Comment by daira** [comment]
@nathan-at-least Bitcoin have closed their PR, and I'm not sure it works anyway. Should we close this ticket?

**Comment by ioptio** [comment]
ping @nathan-at-least see Daira's question above
