### ISSUE TITLE
Sync trouble

### ISSUE THREAD

**Issue by praneethmendu** [zcash/zcash#2417]
### Describe the issue
I was sent coins when my local wallet/zcashd was not running. Now my wallet will not show this transaction. can I force sync my wallet or is it lost forever

from terminal:
```
*****@#######:~$ zcash-cli getaddressesbyaccount ""
[
  "t1RuvpZJKgcP----------------------",
  "t1anBXQrGxix-----------------------"
]
*****@#######:~$ zcash-cli getbalance
0.00000000
```
my minepool redirected me to insight.mercerweiss.com where the transaction was visible, is it wise to post that here? I really do not know. 

anyway from that info there I tried : 
```
*****@#######:~$ zcash-cli getblock 000000001730946206906efe5a39ab14b2c590c690c5952b21d02d1140398b59
error code: -5
error message:
Block not found
```
### The version of Zcash you were using:
Zcash Daemon version v1.0.9

### Machine specs:
- ubuntu 16.04
- CPU:i5
- RAM:12g
- Disk size:
- Disk Type (HD/SDD):
- Linux kernel version (uname -a):4.4.0-62-generic
- Compiler version (gcc -version):5.4.0 2

### Any extra information that might be useful in the debugging process.
this keeps showing up in the debug.log  : ERROR: AcceptToMemoryPool: joinsplit requirements not met

I understand this may not exactly github issues material but no one on the forums seems to have the tech ability to solve this.

**Comment by nathan-at-least** [comment]
Hi, can you view the transaction in a block explorer like https://zcha.in ? Also, verify that your node is up to date with the whole network by running `zcash-cli getinfo` and checking that the `blocks` field is close to what https://zcha.in reports.

Finally, if you _can_ see the transaction in zcha.in _and_ your node is up to date, try stopping it, then restarting it with the `-rescan` option:

```
$ zcashd -rescan
```

Let me know if that helps.

**Comment by ioptio** [comment]
ping @praneethmendu any update on this? Have you tried Nathan's suggestion above?

**Comment by praneethmendu** [comment]
-reindex is what worked for me. It took 3 days on my slow net connection and it downloaded in a very inconsistent way but it did work eventually
