### ISSUE TITLE
Failed to connect to apt.z.cash port 443

### ISSUE THREAD

**Issue by CiraciNicolo** [zcash/zcash#2418]
### Describe the issue
I can't install zcash on debian

#### If so, please list the steps to reproduce below:
1.  New debian virtual machine
2. Follow user guide 1.0
3. Can't install zcash

### Expected behaviour
I should be able to install zcash

### Actual behaviour + errors
Err https://apt.z.cash/ jessie/main zcash amd64 1.0.9
  Failed to connect to apt.z.cash port 443: Connessione rifiutata

### Machine specs:
- OS name + version: Debian GNU/Linux 8.8 (jessie)
- CPU: 2 CPU via Parallels Desktop
- RAM: 4 GB
- Disk size: 32 GB
- Disk Type (HD/SDD): Virtual on SSD
- Linux kernel version (uname -a): Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64 GNU/Linux
- Compiler version (gcc -version):

**Comment by ioptio** [comment]
ping @CiraciNicolo were you successful in future attempts? We haven't heard any other reports like this afaik and I'd like to close this if it's no longer an issue.

**Comment by ioptio** [comment]
Closing this due to lack of response from user.

**Comment by Alex201712** [comment]
Hello! I have same troubles today. "Failed to connect to apt.z.cash port 443". 
OS Name - Ubuntu
Tell me please, may be I have to change "apt.z.cash" on something other?

**Comment by koenvaneijk** [comment]
Looks like the apt key is offline. Building from sources still works for me.
