### ISSUE TITLE
"No working boost sleep implementation found" when building

### ISSUE THREAD

**Issue by daira** [zcash/zcash#242]
zcutil/build.sh or make clean:

```
[...]
checking for dynamic linked boost test... no
configure: error: No working boost sleep implementation found.
make: *** [config.status] Error 1
```

**Comment by daira** [comment]
@defuse wrote on slack:
> ``checking for dynamic linked boost test... no``
> ``configure: error: No working boost sleep implementation found.``
>
> I got that after ``git clean -dfx; ./zcutil/build.sh -j7``. Is the build broken? I think this came up in in ncc-audit a while ago?
> Trying again
> Might have something to do with the flags I was adding

daniel wrote:
> :)
> fixed that using BOOST_VERSION >= 105200
> (when linking against distro boost)

@defuse :
> Hmm it was related to CXXFLAGS I was trying to add
> I guess when autoconf (or configure or whatever it is) tries to compile the feature-test code those flags were making it fail, and it misrepresented that as the boost sleep implementation being missing... Ugh, awful tools.

**Comment by bitcartel** [comment]
I just ran into this problem.
