### ISSUE TITLE
Update wiki

### ISSUE THREAD

**Issue by M1dgard** [zcash/zcash#2421]
Some outdated things I noticed. There may be more.

### Mining Guide
In several places it still says "zcashd 1.0.6 *will*", but that version has already been released! :smile: 

### release policy
> Note: We are actively considering adding an 'auto-senescence' feature to halt nodes when they detect they are older than this threshold. See issue 2274.

Referenced issue has been closed.

**Comment by daira** [comment]
@M1dgard wrote:
> ### Mining Guide
> In several places it still says "zcashd 1.0.6 *will*", but that version has already been released! :smile: 

[Fixed](https://github.com/zcash/zcash/wiki/Mining-Guide/_compare/b4bd5baa7554cf37494596b9e82165b82e6f6891...3a1d1003b9b56463c5de9f2e01d3e3202a86601f).

> ### release policy
> > Note: We are actively considering adding an 'auto-senescence' feature to halt nodes when they detect they are older than this threshold. See issue 2274.
>
> Referenced issue has been closed.

[Fixed](https://github.com/zcash/zcash/wiki/release-policy/_compare/7bff7ae9d749ce67cf2f00eb6d6323f7e2af272c...599ff91f34dfdffea362dc4a937a6f4da379338a).
