### ISSUE TITLE
compile failed on power pc 8 14.04 Ubuntu

### ISSUE THREAD

**Issue by gotope** [zcash/zcash#2422]
cpu  : POWER8 (raw), altivec supported

$ uname -ar
Linux   3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:17:43 UTC 2015 ppc64le ppc64le ppc64le GNU/Linux

:~/minerApp/zcash$ HOST=powerpc64le-linux-gnu  BUILD=powerpc64le-linux-gnu  ./zcutil/build.sh --disable-rust -j$(nproc)
+++ readlink -f ./zcutil/build.sh
++ dirname /home/user/minerApp/zcash/zcutil/build.sh
+ cd /home/user/minerApp/zcash/zcutil/..
+ LCOV_ARG=
+ HARDENING_ARG=--enable-hardening
+ TEST_ARG=
+ '[' x--disable-rust = x--enable-lcov ']'
+ '[' x--disable-rust = x--disable-tests ']'
+ MINING_ARG=
+ '[' x--disable-rust = x--disable-mining ']'
+ RUST_ARG=
+ '[' x--disable-rust = x--disable-rust ']'
+ RUST_ARG=--enable-rust=no
+ shift
+ PROTON_ARG=--enable-proton=no
+ '[' x-j160 = x--enable-proton ']'
++ pwd
+ PREFIX=/home/user/minerApp/zcash/depends/powerpc64le-linux-gnu/
+ eval make --version
++ make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for powerpc64le-unknown-linux-gnu
+ eval gcc --version
++ gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

+ eval g++ --version
++ g++ --version
g++ (Ubuntu 4.9.4-2ubuntu1~14.04.1) 4.9.4
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

+ as --version
GNU assembler (GNU Binutils for Ubuntu) 2.24
Copyright 2013 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or later.
This program has absolutely no warranty.
This assembler was configured for a target of `powerpc64le-linux-gnu'.
+ ld --version
GNU ld (GNU Binutils for Ubuntu) 2.24
Copyright 2013 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
+ HOST=powerpc64le-linux-gnu
+ BUILD=powerpc64le-linux-gnu
+ NO_RUST=--enable-rust=no
+ NO_PROTON=--enable-proton=no
+ make -j160 -C ./depends/ V=1
make: Entering directory `/home/user/minerApp/zcash/depends'
echo Configuring openssl...
Configuring openssl...
rm -rf /home/user/minerApp/zcash/depends/powerpc64le-linux-gnu; mkdir -p /home/user/minerApp/zcash/depends/powerpc64le-linux-gnu/lib; cd /home/user/minerApp/zcash/depends/powerpc64le-linux-gnu;
mkdir -p /home/user/minerApp/zcash/depends/work/build/powerpc64le-linux-gnu/openssl/1.1.0d-b88a604e80d/.
cd /home/user/minerApp/zcash/depends/work/build/powerpc64le-linux-gnu/openssl/1.1.0d-b88a604e80d/.; AR="powerpc64le-linux-gnu-ar" RANLIB="powerpc64le-linux-gnu-ranlib" CC="powerpc64le-linux-gnu-gcc"     PKG_CONFIG_LIBDIR=/home/user/minerApp/zcash/depends/powerpc64le-linux-gnu/lib/pkgconfig PKG_CONFIG_PATH=/home/user/minerApp/zcash/depends/powerpc64le-linux-gnu/share/pkgconfig PATH=/home/user/minerApp/zcash/depends/powerpc64le-linux-gnu/native/bin:/opt/OpenBLAS/include:/usr/local/cuda-7.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games   ./Configure --prefix=/home/user/minerApp/zcash/depends/powerpc64le-linux-gnu --openssldir=/home/user/minerApp/zcash/depends/powerpc64le-linux-gnu/etc/openssl no-afalgeng no-asm no-async no-bf no-blake2 no-camellia no-capieng no-cast no-chacha no-cmac no-cms no-comp no-crypto-mdebug no-crypto-mdebug-backtrace no-ct no-des no-dgram no-dsa no-dso no-dtls no-dtls1 no-dtls1-method no-dynamic-engine no-ec2m no-ec_nistp_64_gcc_128 no-egd no-engine no-err no-gost no-heartbeats no-idea no-md2 no-md4 no-mdc2 no-multiblock no-nextprotoneg no-ocb no-ocsp no-poly1305 no-posix-io no-psk no-rc2 no-rc4 no-rc5 no-rdrand no-rfc3779 no-rmd160 no-scrypt no-sctp no-seed no-shared no-sock no-srp no-srtp no-ssl no-ssl3 no-ssl3-method no-ssl-trace no-stdio no-tls no-tls1 no-tls1-method no-ts no-ui no-unit-test no-weak-ssl-ciphers no-whirlpool no-zlib no-zlib-dynamic -pipe -O1 -I/home/user/minerApp/zcash/depends/powerpc64le-linux-gnu/include -DPURIFY    -fPIC -Wa,--noexecstack
Configuring OpenSSL version 1.1.0d (0x1010004fL)
    no-afalgeng     [option]   OPENSSL_NO_AFALGENG
    no-apps         [forced]   OPENSSL_NO_APPS
    no-asan         [default]  OPENSSL_NO_ASAN
    no-asm          [option]   OPENSSL_NO_ASM
    no-async        [option]   OPENSSL_NO_ASYNC
    no-bf           [option]   OPENSSL_NO_BF (skip dir)
    no-blake2       [option]   OPENSSL_NO_BLAKE2 (skip dir)
    no-camellia     [option]   OPENSSL_NO_CAMELLIA (skip dir)
    no-capieng      [option]   OPENSSL_NO_CAPIENG
    no-cast         [option]   OPENSSL_NO_CAST (skip dir)
    no-chacha       [option]   OPENSSL_NO_CHACHA (skip dir)
    no-cmac         [option]   OPENSSL_NO_CMAC (skip dir)
    no-cms          [option]   OPENSSL_NO_CMS (skip dir)
    no-comp         [option]   OPENSSL_NO_COMP (skip dir)
    no-crypto-mdebug [option]   OPENSSL_NO_CRYPTO_MDEBUG
    no-crypto-mdebug-backtrace [option]   OPENSSL_NO_CRYPTO_MDEBUG_BACKTRACE
    no-ct           [option]   OPENSSL_NO_CT (skip dir)
    no-des          [option]   OPENSSL_NO_DES (skip dir)
    no-dgram        [option]   OPENSSL_NO_DGRAM
    no-dsa          [option]   OPENSSL_NO_DSA (skip dir)
    no-dso          [option]
    no-dtls         [option(dtls)] OPENSSL_NO_DTLS
    no-dtls1        [option(dtls1-method)] OPENSSL_NO_DTLS1
    no-dtls1-method [option]   OPENSSL_NO_DTLS1_METHOD
    no-dtls1_2      [option(dtls)] OPENSSL_NO_DTLS1_2
    no-dynamic-engine [option]
    no-ec2m         [option]   OPENSSL_NO_EC2M
    no-ec_nistp_64_gcc_128 [option]   OPENSSL_NO_EC_NISTP_64_GCC_128
    no-egd          [option]   OPENSSL_NO_EGD
    no-engine       [option]   OPENSSL_NO_ENGINE (skip engines)
    no-err          [option]   OPENSSL_NO_ERR
    no-fuzz-afl     [default]  OPENSSL_NO_FUZZ_AFL
    no-fuzz-libfuzzer [default]  OPENSSL_NO_FUZZ_LIBFUZZER
    no-gost         [option]   OPENSSL_NO_GOST
    no-heartbeats   [option]   OPENSSL_NO_HEARTBEATS
    no-idea         [option]   OPENSSL_NO_IDEA (skip dir)
    no-md2          [option]   OPENSSL_NO_MD2 (skip dir)
    no-md4          [option]   OPENSSL_NO_MD4 (skip dir)
    no-mdc2         [option]   OPENSSL_NO_MDC2 (skip dir)
    no-msan         [default]  OPENSSL_NO_MSAN
    no-multiblock   [option]   OPENSSL_NO_MULTIBLOCK
    no-nextprotoneg [option]   OPENSSL_NO_NEXTPROTONEG
    no-ocb          [option]   OPENSSL_NO_OCB
    no-ocsp         [option]   OPENSSL_NO_OCSP (skip dir)
    no-poly1305     [option]   OPENSSL_NO_POLY1305 (skip dir)
    no-posix-io     [option]   OPENSSL_NO_POSIX_IO
    no-psk          [option]   OPENSSL_NO_PSK
    no-rc2          [option]   OPENSSL_NO_RC2 (skip dir)
    no-rc4          [option]   OPENSSL_NO_RC4 (skip dir)
    no-rc5          [option]   OPENSSL_NO_RC5 (skip dir)
    no-rdrand       [option]   OPENSSL_NO_RDRAND
    no-rfc3779      [option]   OPENSSL_NO_RFC3779
    no-rmd160       [option]   OPENSSL_NO_RMD160 (skip dir)
    no-scrypt       [option]   OPENSSL_NO_SCRYPT
    no-sctp         [option]   OPENSSL_NO_SCTP
    no-seed         [option]   OPENSSL_NO_SEED (skip dir)
    no-shared       [option]
    no-sock         [option]   OPENSSL_NO_SOCK
    no-srp          [option]   OPENSSL_NO_SRP (skip dir)
    no-srtp         [option]   OPENSSL_NO_SRTP
    no-ssl-trace    [option]   OPENSSL_NO_SSL_TRACE
    no-ssl3         [option(tls)] OPENSSL_NO_SSL3
    no-ssl3-method  [option]   OPENSSL_NO_SSL3_METHOD
    no-stdio        [option]   OPENSSL_NO_STDIO
    no-tests        [forced]   OPENSSL_NO_TESTS
    no-tls1         [option(tls1-method)] OPENSSL_NO_TLS1
    no-tls1-method  [option]   OPENSSL_NO_TLS1_METHOD
    no-tls1_1       [option(tls)] OPENSSL_NO_TLS1_1
    no-tls1_2       [option(tls)] OPENSSL_NO_TLS1_2
    no-ts           [option]   OPENSSL_NO_TS (skip dir)
    no-ubsan        [default]  OPENSSL_NO_UBSAN
    no-ui           [option]   OPENSSL_NO_UI (skip dir)
    no-unit-test    [option]   OPENSSL_NO_UNIT_TEST
    no-weak-ssl-ciphers [option]   OPENSSL_NO_WEAK_SSL_CIPHERS
    no-whirlpool    [option]   OPENSSL_NO_WHIRLPOOL (skip dir)
    no-zlib         [option]
    no-zlib-dynamic [option]
Configuring for
Warning! target  doesn't exist!
Usage: Configure [no-<cipher> ...] [enable-<cipher> ...] [-Dxxx] [-lxxx] [-Lxxx] [-fxxx] [-Kxxx] [no-hw-xxx|no-hw] [[no-]threads] [[no-]shared] [[no-]zlib|zlib-dynamic] [no-asm] [no-dso] [no-egd] [sctp] [386] [--prefix=DIR] [--openssldir=OPENSSLDIR] [--with-xxx[=vvv]] [--config=FILE] os/compiler[:flags]

pick os/compiler from:
BS2000-OSD BSD-generic32 BSD-generic64 BSD-ia64 BSD-sparc64 BSD-sparcv8
BSD-x86 BSD-x86-elf BSD-x86_64 Cygwin Cygwin-i386 Cygwin-i486 Cygwin-i586
Cygwin-i686 Cygwin-x86 Cygwin-x86_64 DJGPP MPE/iX-gcc OS390-Unix QNX6
QNX6-i386 UEFI UWIN VC-CE VC-WIN32 VC-WIN64A VC-WIN64A-masm VC-WIN64I aix-cc
aix-gcc aix64-cc aix64-gcc android android-armeabi android-mips android-x86
android64 android64-aarch64 bsdi-elf-gcc cc darwin-i386-cc darwin-ppc-cc
darwin64-debug-test-64-clang darwin64-ppc-cc darwin64-x86_64-cc dist gcc
haiku-x86 haiku-x86_64 hpux-ia64-cc hpux-ia64-gcc hpux-parisc-cc
hpux-parisc-gcc hpux-parisc1_1-cc hpux-parisc1_1-gcc hpux64-ia64-cc
hpux64-ia64-gcc hpux64-parisc2-cc hpux64-parisc2-gcc hurd-x86 ios-cross
ios64-cross iphoneos-cross irix-mips3-cc irix-mips3-gcc irix64-mips4-cc
irix64-mips4-gcc linux-aarch64 linux-alpha-gcc linux-aout linux-arm64ilp32
linux-armv4 linux-c64xplus linux-elf linux-generic32 linux-generic64
linux-ia64 linux-mips32 linux-mips64 linux-ppc linux-ppc64 linux-ppc64le
linux-sparcv8 linux-sparcv9 linux-x32 linux-x86 linux-x86-clang linux-x86_64
linux-x86_64-clang linux32-s390x linux64-mips64 linux64-s390x linux64-sparcv9
mingw mingw64 nextstep nextstep3.3 purify qnx4 sco5-cc sco5-gcc
solaris-sparcv7-cc solaris-sparcv7-gcc solaris-sparcv8-cc solaris-sparcv8-gcc
solaris-sparcv9-cc solaris-sparcv9-gcc solaris-x86-gcc solaris64-sparcv9-cc
solaris64-sparcv9-gcc solaris64-x86_64-cc solaris64-x86_64-gcc tru64-alpha-cc
tru64-alpha-gcc uClinux-dist uClinux-dist64 unixware-2.0 unixware-2.1
unixware-7 unixware-7-gcc vms-alpha vms-alpha-p32 vms-alpha-p64 vms-ia64
vms-ia64-p32 vms-ia64-p64 vos-gcc vxworks-mips vxworks-ppc405 vxworks-ppc60x
vxworks-ppc750 vxworks-ppc750-debug vxworks-ppc860 vxworks-ppcgen
vxworks-simlinux debug debug-erbridge debug-linux-ia32-aes debug-linux-pentium
debug-linux-ppro debug-test-64-clang

NOTE: If in doubt, on Unix-ish systems use './config'.
make: *** [/home/user/minerApp/zcash/depends/work/build/powerpc64le-linux-gnu/openssl/1.1.0d-b88a604e80d/./.stamp_configured] Error 1
make: Leaving directory `/home/user/minerApp/zcash/depends'

**Comment by marcofortina** [comment]
Hello folks!
Sorry for the O.T. Has anyone compiled on SPARC64? What is the Sol/s on this platform?

Thanks
Marco

**Comment by Klimenos** [comment]
The reason why you're getting "Warning! target doesn't exist!" with openSSL is because the target isn't specified when ./Configure is executed.

```
cd ./depends/work/build/xxxxxxxxxxxx/openssl/x.x.x-xxxxx
./Configure LIST # Print the list of available targets
```

The list should give you the list of available targets for openSSL:

```
BS2000-OSD
BSD-generic32
BSD-generic64
BSD-ia64
BSD-sparc64
BSD-sparcv8
BSD-x86
BSD-x86-elf
BSD-x86_64
Cygwin
Cygwin-i386
Cygwin-i486
Cygwin-i586
Cygwin-i686
Cygwin-x86
Cygwin-x86_64
DJGPP
MPE/iX-gcc
QNX6
QNX6-i386
UEFI
UWIN
VC-CE
VC-WIN32
VC-WIN64A
VC-WIN64A-masm
VC-WIN64I
aix-cc
aix-gcc
aix64-cc
aix64-gcc
android
android-armeabi
android-mips
android-x86
android64
android64-aarch64
bsdi-elf-gcc
cc
darwin-i386-cc
darwin-ppc-cc
darwin64-debug-test-64-clang
darwin64-ppc-cc
darwin64-x86_64-cc
debug
debug-erbridge
debug-linux-ia32-aes
debug-linux-pentium
debug-linux-ppro
debug-test-64-clang
dist
gcc
haiku-x86
haiku-x86_64
hpux-ia64-cc
hpux-ia64-gcc
hpux-parisc-cc
hpux-parisc-gcc
hpux-parisc1_1-cc
hpux-parisc1_1-gcc
hpux64-ia64-cc
hpux64-ia64-gcc
hpux64-parisc2-cc
hpux64-parisc2-gcc
hurd-x86
ios-cross
ios64-cross
iphoneos-cross
irix-mips3-cc
irix-mips3-gcc
irix64-mips4-cc
irix64-mips4-gcc
linux-aarch64
linux-alpha-gcc
linux-aout
linux-arm64ilp32
linux-armv4
linux-c64xplus
linux-elf
linux-generic32
linux-generic64
linux-ia64
linux-mips32
linux-mips64
linux-ppc
linux-ppc64
linux-ppc64le
linux-sparcv8
linux-sparcv9
linux-x32
linux-x86
linux-x86-clang
linux-x86_64
linux-x86_64-clang
linux32-s390x
linux64-mips64
linux64-s390x
linux64-sparcv9
mingw
mingw64
nextstep
nextstep3.3
purify
qnx4
sco5-cc
sco5-gcc
solaris-sparcv7-cc
solaris-sparcv7-gcc
solaris-sparcv8-cc
solaris-sparcv8-gcc
solaris-sparcv9-cc
solaris-sparcv9-gcc
solaris-x86-gcc
solaris64-sparcv9-cc
solaris64-sparcv9-gcc
solaris64-x86_64-cc
solaris64-x86_64-gcc
tru64-alpha-cc
tru64-alpha-gcc
uClinux-dist
uClinux-dist64
unixware-2.0
unixware-2.1
unixware-7
unixware-7-gcc
vms-alpha
vms-alpha-p32
vms-alpha-p64
vms-ia64
vms-ia64-p32
vms-ia64-p64
vos-gcc
vxworks-mips
vxworks-ppc405
vxworks-ppc60x
vxworks-ppc750
vxworks-ppc750-debug
vxworks-ppc860
vxworks-ppcgen
vxworks-simlinux
```

Your PowerPC 64bits LE target is in the list: `linux-ppc64le`

All you have to do is edit the **./depends/packages/openssl.mk** file to add this target when ./Configure is called:

`./Configure $($(package)_config_opts) linux-ppc64le`

**Comment by daira** [comment]
Is there still interest in compiling zcashd on POWER8? Our build system has changed quite a bit in ways that improve architecture portability, so it might be worth trying this again (especially after #4613 has merged). In particular the OpenSSL dependency has been removed, so that will no longer be a problem.
