### ISSUE TITLE
qa test failure ./qa/pull-tester/rpc-tests.sh

### ISSUE THREAD

**Issue by fourtwenty420** [zcash/zcash#2430]
After setting up zcash and running first test sucesfully I've ran second test with 

./qa/pull-tester/rpc-tests.sh

and got 

=== Running testscript zcjoinsplitdoublespend.py ===
  File "/home/ubuntu/.git/zcash/qa/rpc-tests/test_framework/test_framework.py", line 118, in main
    self.run_test()
  File "/home/ubuntu/.git/zcash/qa/rpc-tests/zcjoinsplitdoublespend.py", line 59, in run_test
    pool[i] = self.nodes[i].zcrawjoinsplit(pool[i], {}, {zcaddress:39.99}, 39.99, 0)
  File "/home/ubuntu/.git/zcash/qa/rpc-tests/test_framework/authproxy.py", line 145, in __call__
    raise JSONRPCException(response['error'])
  Initializing test directory /tmp/testn92mZ7
  JSONRPC error: std::bad_alloc
  Stopping nodes
  Cleaning up
  Failed
!!! FAIL: zcjoinsplitdoublespend.py !!!

=== Running testscript getblocktemplate.py ===
  Initializing test directory /tmp/testBM_lHs
  Stopping nodes
  Cleaning up
  Tests successful
--- Success: getblocktemplate.py ---

=== Running testscript zmq_test.py ===
Traceback (most recent call last):
  File "/home/ubuntu/.git/zcash/qa/rpc-tests/zmq_test.py", line 12, in <module>
    import zmq
ImportError: No module named zmq
!!! FAIL: zmq_test.py !!!

Tests completed: 30
successes 27; failures: 3

Failing tests: wallet_nullifiers.py zcjoinsplitdoublespend.py zmq_test.py

### Machine specs:
- OS name + version: ubuntu 16.04.02
- CPU: AWS
- RAM: 7GB
- Disk size: 15GB
- Disk Type (HD/SDD): SSD
- Linux kernel version (uname -a): Linux mine1 4.4.0-1013-aws #22-Ubuntu SMP Fri Mar 31 15:41:31 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Compiler version (gcc -version): gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)

let me know if you'd need anything else

**Comment by fourtwenty420** [comment]
actually I've had only 7Gigs of ram, I switched to 15Gig and its all good, please close this

**Comment by daira** [comment]
In addition to the extra RAM, the ZMQ tests require the python-zmq package (on Debian or Ubuntu).
