### ISSUE TITLE
[macOS] Dependency download fallback does not work

### ISSUE THREAD

**Issue by kozyilmaz** [zcash/zcash#2431]
While downloading non-existing Zcash dependencies from FALLBACK_DOWNLOAD_PATH on macOS (e.g. rust-1.16.0-apple-darwin), an error page is received and fallback path is not tried. As a result package signature checks fail

Zcash Version : v1.9.0 tag
OS Version: macOS 10.12.5 (16F73)

**Comment by daira** [comment]
There are three possibilities I can think of:
1. There is a portability problem in the script that is causing the fallback to fail on OS X (and possibly other platforms than Linux).
2. The problem is caused by the rust-1.16.0-apple-darwin file not existing at either path, and this was misinterpreted as a problem with the fallback.
3. The fallback actually isn't working on any platform, and just hasn't been tested well.

@kozyilmaz How did you ascertain which path(s) were tried (to eliminate possibility 2)?

Note: the name ``FALLBACK_DOWNLOAD_PATH`` is really confusing since this path is intentionally checked first. It needs to be renamed to ``PRIORITY_DOWNLOAD_PATH`` as per #1621.

**Comment by kozyilmaz** [comment]
1 and 3 are most likely because I did not observe this issue when project url is checked before FALLBACK_DOWNLOAD_PATH

Below is the complete macOS build log, it seems that it download some kind of an html doc as a response to non-existent rust-darwin package

```
mkdir -p /Users/loki/Desktop/devel/zcash-apple/zcash/zcash_v1.0.9/depends/sources/download-stamps /Users/loki/Desktop/devel/zcash-apple/zcash/zcash_v1.0.9/depends/sources
rm -f /Users/loki/Desktop/devel/zcash-apple/zcash/zcash_v1.0.9/depends/sources/download-stamps/.stamp_fetched-rust-rust-1.16.0-x86_64-apple-darwin.tar.gz.hash
touch /Users/loki/Desktop/devel/zcash-apple/zcash/zcash_v1.0.9/depends/sources/download-stamps/.stamp_fetched-rust-rust-1.16.0-x86_64-apple-darwin.tar.gz.hash
cd /Users/loki/Desktop/devel/zcash-apple/zcash/zcash_v1.0.9/depends/sources/download-stamps; (test -f /Users/loki/Desktop/devel/zcash-apple/zcash/zcash_v1.0.9/depends/sources/rust-1.16.0-x86_64-apple-darwin.tar.gz || ( mkdir -p /Users/loki/Desktop/devel/zcash-apple/zcash/zcash_v1.0.9/depends/work/download/rust-1.16.0 && echo Fetching rust... && ( curl --connect-timeout 10 --retry 3 -L -o "/Users/loki/Desktop/devel/zcash-apple/zcash/zcash_v1.0.9/depends/work/download/rust-1.16.0/rust-1.16.0-x86_64-apple-darwin.tar.gz.temp" "https://z.cash/depends-sources/rust-1.16.0-x86_64-apple-darwin.tar.gz" || curl --connect-timeout 10 --retry 3 -L -o "/Users/loki/Desktop/devel/zcash-apple/zcash/zcash_v1.0.9/depends/work/download/rust-1.16.0/rust-1.16.0-x86_64-apple-darwin.tar.gz.temp" "https://static.rust-lang.org/dist/rust-1.16.0-x86_64-apple-darwin.tar.gz" ) && echo "2d08259ee038d3a2c77a93f1a31fc59e7a1d6d1bbfcba3dba3c8213b2e5d1926  /Users/loki/Desktop/devel/zcash-apple/zcash/zcash_v1.0.9/depends/work/download/rust-1.16.0/rust-1.16.0-x86_64-apple-darwin.tar.gz.temp" > /Users/loki/Desktop/devel/zcash-apple/zcash/zcash_v1.0.9/depends/work/download/rust-1.16.0/.rust-1.16.0-x86_64-apple-darwin.tar.gz.hash && shasum -a 256 -c /Users/loki/Desktop/devel/zcash-apple/zcash/zcash_v1.0.9/depends/work/download/rust-1.16.0/.rust-1.16.0-x86_64-apple-darwin.tar.gz.hash && mv /Users/loki/Desktop/devel/zcash-apple/zcash/zcash_v1.0.9/depends/work/download/rust-1.16.0/rust-1.16.0-x86_64-apple-darwin.tar.gz.temp /Users/loki/Desktop/devel/zcash-apple/zcash/zcash_v1.0.9/depends/sources/rust-1.16.0-x86_64-apple-darwin.tar.gz && rm -rf /Users/loki/Desktop/devel/zcash-apple/zcash/zcash_v1.0.9/depends/work/download/rust-1.16.0 ))
Fetching rust...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8626  100  8626    0     0   8826      0 --:--:-- --:--:-- --:--:--  8820
/Users/loki/Desktop/devel/zcash-apple/zcash/zcash_v1.0.9/depends/work/download/rust-1.16.0/rust-1.16.0-x86_64-apple-darwin.tar.gz.temp: FAILED
shasum: WARNING: 1 computed checksum did NOT match
make[3]: *** [/Users/loki/Desktop/devel/zcash-apple/zcash/zcash_v1.0.9/depends/sources/download-stamps/.stamp_fetched-rust-rust-1.16.0-x86_64-apple-darwin.tar.gz.hash] Error 1
make[2]: *** [zcash_build] Error 2
make[1]: *** [build] Error 1
make: *** [zcash_all] Error 2
```
Attached is the downloaded file (only added .txt extension to keep GitHub happy), if you open it with a text editor you'll see that it's an html doc with `© 2017 Zerocoin Electric Coin Company` footer text.
[rust-1.16.0-x86_64-apple-darwin.tar.gz.temp.txt](https://github.com/zcash/zcash/files/1059177/rust-1.16.0-x86_64-apple-darwin.tar.gz.temp.txt)

Here is the curl version on macOS Sierra
```
bash-3.2$ curl --version
curl 7.51.0 (x86_64-apple-darwin16.0) libcurl/7.51.0 SecureTransport zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets 
```

I'll update the issue as soon as I try with Linux

**Comment by radix42** [comment]
@kozyilmaz I pass --no-rust to configure in all my mac builds, as it is not needed right now

**Comment by kozyilmaz** [comment]
@radix42 Yes, it works with --no-rust for sure but it's better to keep Linux and macOS build similar. This also reveals another issue that I won't go into detail here but in short `$(package)_file_name` and `$(package)_sha256_hash` are not customizable per platform. 

@daira It seems scenario 1 is the case, fallback works on Linux, log below 

```
mkdir -p /home/loki/devel/zcash/depends/sources/download-stamps /home/loki/devel/zcash/depends/sources
rm -f /home/loki/devel/zcash/depends/sources/download-stamps/.stamp_fetched-rust-rust-1.16.0-x86_64-apple-darwin.tar.gz.hash
touch /home/loki/devel/zcash/depends/sources/download-stamps/.stamp_fetched-rust-rust-1.16.0-x86_64-apple-darwin.tar.gz.hash
cd /home/loki/devel/zcash/depends/sources/download-stamps; (test -f /home/loki/devel/zcash/depends/sources/rust-1.16.0-x86_64-apple-darwin.tar.gz || ( mkdir -p /home/loki/devel/zcash/depends/work/download/rust-1.16.0 && echo Fetching rust... && ( wget --timeout=10 --tries=3 -nv -O "/home/loki/devel/zcash/depends/work/download/rust-1.16.0/rust-1.16.0-x86_64-apple-darwin.tar.gz.temp" "https://z.cash/depends-sources/rust-1.16.0-x86_64-apple-darwin.tar.gz" || wget --timeout=10 --tries=3 -nv -O "/home/loki/devel/zcash/depends/work/download/rust-1.16.0/rust-1.16.0-x86_64-apple-darwin.tar.gz.temp" "https://static.rust-lang.org/dist/rust-1.16.0-x86_64-apple-darwin.tar.gz" ) && echo "2d08259ee038d3a2c77a93f1a31fc59e7a1d6d1bbfcba3dba3c8213b2e5d1926  /home/loki/devel/zcash/depends/work/download/rust-1.16.0/rust-1.16.0-x86_64-apple-darwin.tar.gz.temp" > /home/loki/devel/zcash/depends/work/download/rust-1.16.0/.rust-1.16.0-x86_64-apple-darwin.tar.gz.hash && sha256sum -c /home/loki/devel/zcash/depends/work/download/rust-1.16.0/.rust-1.16.0-x86_64-apple-darwin.tar.gz.hash && mv /home/loki/devel/zcash/depends/work/download/rust-1.16.0/rust-1.16.0-x86_64-apple-darwin.tar.gz.temp /home/loki/devel/zcash/depends/sources/rust-1.16.0-x86_64-apple-darwin.tar.gz && rm -rf /home/loki/devel/zcash/depends/work/download/rust-1.16.0 ))
Fetching rust...
https://z.cash/depends-sources/rust-1.16.0-x86_64-apple-darwin.tar.gz:
2017-06-07 23:30:13 ERROR 404: Not Found.
2017-06-07 23:30:40 URL:https://static.rust-lang.org/dist/rust-1.16.0-x86_64-apple-darwin.tar.gz [89962356/89962356] -> "/home/loki/devel/zcash/depends/work/download/rust-1.16.0/rust-1.16.0-x86_64-apple-darwin.tar.gz.temp" [1]
/home/loki/devel/zcash/depends/work/download/rust-1.16.0/rust-1.16.0-x86_64-apple-darwin.tar.gz.temp: OK
cd /home/loki/devel/zcash/depends/sources; sha256sum rust-1.16.0-x86_64-apple-darwin.tar.gz >> /home/loki/devel/zcash/depends/sources/download-stamps/.stamp_fetched-rust-rust-1.16.0-x86_64-apple-darwin.tar.gz.hash;
touch /home/loki/devel/zcash/depends/sources/download-stamps/.stamp_fetched-rust-rust-1.16.0-x86_64-apple-darwin.tar.gz.hash
echo Extracting rust...
Extracting rust...
mkdir -p /home/loki/devel/zcash/depends/work/build/x86_64-unknown-linux-gnu/rust/1.16.0-539cfaf1c83
cd /home/loki/devel/zcash/depends/work/build/x86_64-unknown-linux-gnu/rust/1.16.0-539cfaf1c83; mkdir -p /home/loki/devel/zcash/depends/work/build/x86_64-unknown-linux-gnu/rust/1.16.0-539cfaf1c83 && echo "2d08259ee038d3a2c77a93f1a31fc59e7a1d6d1bbfcba3dba3c8213b2e5d1926  /home/loki/devel/zcash/depends/sources/rust-1.16.0-x86_64-apple-darwin.tar.gz" > /home/loki/devel/zcash/depends/work/build/x86_64-unknown-linux-gnu/rust/1.16.0-539cfaf1c83/.rust-1.16.0-x86_64-apple-darwin.tar.gz.hash &&  sha256sum -c /home/loki/devel/zcash/depends/work/build/x86_64-unknown-linux-gnu/rust/1.16.0-539cfaf1c83/.rust-1.16.0-x86_64-apple-darwin.tar.gz.hash && tar --strip-components=1 -xf /home/loki/devel/zcash/depends/sources/rust-1.16.0-x86_64-apple-darwin.tar.gz
/home/loki/devel/zcash/depends/sources/rust-1.16.0-x86_64-apple-darwin.tar.gz: OK
```

**Comment by radix42** [comment]
I think that you can use platform suffixes to customize things like $(package)_sha256_hash, I presume you're talking about the libsnark differences here?

The things to make a patched libsnark that is good on both linux and mac are pretty minor if that's the case...its Windows that is a bear. the zcash/libsnark.git repo just needs those minor patches applied to it with the right #ifdef guards, like used in zclassic's libsnark fork

**Comment by radix42** [comment]
at least, at the revision where it was just linux and mac, with Windows in the mix they switch to their own fork of gmp, too

**Comment by kozyilmaz** [comment]
Well I may be wrong but as far as I see `$(package)_file_name_$(host_arch)` and `$(package)_sha256_hash_$(host_arch)` does not work.

**Comment by radix42** [comment]
I'm thinking of stuff like the following from boost.mk:

```
$(package)_config_opts_linux=threadapi=pthread runtime-link=shared
$(package)_config_opts_darwin=--toolset=darwin-4.2.1 runtime-link=shared
$(package)_config_opts_mingw32=binary-format=pe target-os=windows threadapi=win32 runtime-link=static
$(package)_config_opts_x86_64_mingw32=address-model=64
$(package)_config_opts_i686_mingw32=address-model=32
```

so in this case it'd be

```
$(package)_sha256_hash_linux=.......
$(package)_sha256_hash_darwin=.....
```

and similar stuff for different filenames per platform...all of which is icky if it actually works...getting the OS X/darwin stuff merged into the zcashco fork of libsnark is I think the right way rather than attempting the above

**Comment by kozyilmaz** [comment]
It is getting a bit off-topic and I am no expert at all but `$(package)_sha256_hash_linux` or `$(package)_file_name_darwin` will not work. `depends/funcs.mk`takes care of other vars you mention (config_opts, flags, ldflags etc.) but not file_name or sha256_hash as far as I see.

The problem here is not related to libsnark. For Rust, Linux and Darwin installation files are completely different this is why I mentioned these two variables.

**Comment by radix42** [comment]
ah ok got ya! any zcashco employees able to chime in on which features may require rust down the road, and/or how soon it may be needed and not optional? I know its just for some experimental feature IIRC?

**Comment by daira** [comment]
Rust is very likely to be required for Sapling, and possibly before. At the moment we don't do anything with it, the dependency is there just to shake out portability problems (like this one! :-) ) in advance of using it in earnest.

**Comment by kozyilmaz** [comment]
Fix was in two parts: https://github.com/zcash/zcash/commit/d5934e9268ccd9991a0178ab50fc54474cdfe8e6 was already committed and remaining fix is done in https://github.com/zcash/zcash/pull/2697
