### ISSUE TITLE
bitnow.co.nz down

### ISSUE THREAD

**Issue by davidhedlund** [zcash/zcash#2434]
https://z.cash/blog/third-party-support.html lists [bitnow.co.nz](https://bitnow.co.nz/) but it is down.

**Comment by daira** [comment]
@ioptio If it's down permanently then it can be deleted from third-party-support, otherwise close this.

**Comment by arcalinea** [comment]
This is a blog post from October 2016 about third party wallets and exchanges that existed at launch, so it should not be considered an up-to-date list that we maintain. 

@davidhedlund the Zcash community blog maintains a more up to date list, linked to from our "getting started" page: https://zcashblog.wordpress.com/zcash-exchanges/

As a next step, I can link to these external resources which keep lists of third party services from our Support page.

**Comment by davidhedlund** [comment]
@arcalinea @daira https://z.cash/support/faq.html under "How can I acquire Zcash (ZEC)?" says
> We put together a list of exchanges supporting Zcash trades at launch [here](https://z.cash/blog/third-party-support.html) but these are just a few of the first exchanges and wallets that supported Zcash at launch. There have been many more that have come into existence. We encourage the community to host their own lists and repositories of successful providers such as in this [Zcash community blog](https://zcashblog.wordpress.com/zcash-exchanges/) (https://zcashblog.wordpress.com/zcash-exchanges/).

**Comment by mineZcash** [comment]
There is also a list of exchanges I try to keep as up-to date as I can here: https://www.zcashcommunity.com/markets/

**Comment by davidhedlund** [comment]
@arcalinea In https://z.cash/support/faq.html can you please replace 
> We encourage the community to host their own lists and repositories of successful providers such as in this [Zcash community blog](https://zcashblog.wordpress.com/zcash-exchanges/) (https://zcashblog.wordpress.com/zcash-exchanges/).

with

> We encourage the community to host their own lists and repositories of successful providers such as on [Zcashcommunity.com - Zcash Markets](https://www.zcashcommunity.com/markets/)(https://www.zcashcommunity.com/markets/).

**Comment by davidhedlund** [comment]
@mineZcash Or can you do it?

**Comment by mineZcash** [comment]
@davidhedlund I don't have admin on z.cash site to make any changes, perhaps @ioptio would be able to help

**Comment by davidhedlund** [comment]
@mineZcash Ok.

**Comment by nathan-at-least** [comment]
Let's also remove the FAQ link which points to [Third Party Support at Launch](https://z.cash/blog/third-party-support.html). That blog post is historical and will remain outdated, so directing users there will only lead to confusion.

**Comment by davidhedlund** [comment]
@arcalinea In https://z.cash/support/faq.html can you please replace 
> We encourage the community to host their own lists and repositories of successful providers such as in this [Zcash community blog](https://zcashblog.wordpress.com/zcash-exchanges/) (https://zcashblog.wordpress.com/zcash-exchanges/).

with

> We encourage the community to host their own lists and repositories of successful providers such as on [Zcashcommunity.com - Zcash Markets](https://www.zcashcommunity.com/markets/)(https://www.zcashcommunity.com/markets/).

**Comment by davidhedlund** [comment]
@ioptio Or can you?

**Comment by davidhedlund** [comment]
@daira @ioptio

> https://z.cash/support/faq.html mentions https://z.cash/blog/third-party-support.html with [bitnow.co.nz](https://bitnow.co.nz/) on the list but it is down.

Its still down

**Comment by davidhedlund** [comment]
https://github.com/zcash/zcash/issues/2495
