### ISSUE TITLE
New exchange: Cryptopia

### ISSUE THREAD

**Issue by davidhedlund** [zcash/zcash#2437]
Cryptopia now offers Zcash: https://www.cryptopia.co.nz/Exchange?market=ZEC_BTC

Cryptopia are on position #41 according to [CoinMarketCap](https://coinmarketcap.com/exchanges/Cryptopia/).

Can you please add Cryptopia to your list of cryptocurrency exchanges that offers Zcash?: https://z.cash/blog/third-party-support.html

**Comment by arcalinea** [comment]
@davidhedlund The page you're linking to is a blog post from launch with lists of wallets and exchanges that existed back then. We are not actively maintaining such a list, although MineZCash, a community member, is. You can ping him on our community chat: https://chat.zcashcommunity.com/

He maintains this website with a list of zcash exchanges: https://www.zcashcommunity.com/markets/

**Comment by davidhedlund** [comment]
@arcalinea Can you please add Cryptopia to https://z.cash/blog/third-party-support.html ?

**Comment by nathan-at-least** [comment]
Hi @davidhedlund I just saw this. I see that cryptopia is already listed at https://www.zcashcommunity.com/markets/ which is best place for that listing.

I didn't think about how that old blogpost may be what some people still refer to. I don't think it's appropriate to modify that post to add new services. However, it totally makes sense to add a retro-active edit to the top directing people to https://www.zcashcommunity.com/markets/.

**Comment by davidhedlund** [comment]
@arcalinea Can you please add Cryptopia to https://z.cash/blog/third-party-support.html under "EXCHANGES" ?
