### ISSUE TITLE
Update protocol spec to be consistent with block version >= 4 (not ==) and transaction version >= 1

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2439]
The block version is enforced [here](https://github.com/zcash/zcash/blob/5b3bc9716ec1095b7a4624cfe6e1b03d739ab90f/src/main.cpp#L2966-L2969), to be >= 4. Section 6.3 of the protocol spec says "The block version number MUST be 4." (i.e. *equal* to 4) as a consensus rule.

We should consider this carefully as part of HF0. It would be incorrect to immediately change the code to enforce nVersion == 4 since that could allow a miner to cause a chain split, I believe.

**Comment by aayanl** [comment]
Implementing something like BIP9 won't be possible this way

**Comment by daira** [comment]
@aayanl *If* we added signaling bits, they would likely be in another field (either the ``reserved`` field or a new one added in a hard fork), not in the version. The only reason Bitcoin used the version field was to allow the first use of BIP 9 to be a soft fork.

**Comment by daira** [comment]
Our current thinking is to force a [bilateral hard fork](http://cryptocentral.info/topic/947/hard-forks-soft-forks-defaults-and-coercion-by-vitalik-buterin) by incrementing both block and transaction version numbers at the activation point of the fork. However if we do not change the implementation of the block version consensus rule, then this will not by itself force bilateral-incompatibility of blocks (in practice, if the coinbase transaction version is incremented then that will force bilateral-incompatibility, but I don't want to rely on that).

It's quite straightforward to reliably force block bilateral-incompatibility in other ways, though; for example we can set the redundant ``solutionSize`` field to something other than 1344 (say 0), which will cause all old-version nodes to reject the block.

**Comment by daira** [comment]
By the way, the reason to want old-version blocks to be invalid on the new chain is wipe-out protection (#2255).

**Comment by daira** [comment]
I apparently chose this behaviour explicitly (see https://github.com/zcash/zcash/issues/1638#issuecomment-256073046), but forgot to update the spec.

**Comment by daira** [comment]
Similarly for transaction versions. (See https://github.com/zcash/zcash/issues/1557#issuecomment-255500250 for where I decided that should also be a *minimum* version of 1.)

**Comment by daira** [comment]
This is already done (protocol spec 2017.0-beta-2.7).
