### ISSUE TITLE
Add field indicating coinbase tx in output of listunspent

### ISSUE THREAD

**Issue by arcalinea** [zcash/zcash#2446]
This comes from a user support request. Would be useful, in particular for large wallets, to not have to use gettransaction to determine whether an input is a coinbase reward. Suggestion is to add a field such as `"generated": true`

Unless I'm overlooking some existing way to find out from the output of listunspent?

**Comment by arcalinea** [comment]
related to #2449

**Comment by milakamila29** [comment]
how long deposit addres bittrex open ?

**Comment by dannylac** [comment]
Whats the ETA on this for wallet deposits?
