### ISSUE TITLE
Verify that we exclude coinbase UTXOs from selection/use in Bitcoin RPCs.

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#2449]
Zcash has a consensus rule that coinbase UTXOs must be shielded. This causes problems for e.g. exchanges using the Bitcoin-inherited RPCs, where they run into errors. As the only way coinbase can be spent is via `z_sendmany`, it should never be considered for transparent RPCs.

We should modify the transparent coin selection rules used by the inherited transparent RPCs to exclude coinbase. One usability issue is that mining users might get confused if they can't spend everything they appear to have; we should ensure that if users try to spend more than can be funded without coinbase, but could be funded with coinbase, that they still receive an appropriate error.

**Comment by daira** [comment]
I had thought we fixed this in #1431, before launch.

**Comment by str4d** [comment]
@daira we might have, but I want to ensure this is the case, given we have had several user reports of running into problems here. Specifically, there's no way to easily discover the coinbase amounts in an address or a wallet, other than by trial and error.

**Comment by nathan-at-least** [comment]
I think we should do this, and it should be done in concert with #2448.

**Comment by daira** [comment]
I reviewed https://github.com/zcash/zcash/pull/1431/files again, and it certainly looks to me as though it should have fixed this. Do we have any contrary evidence that it isn't fixed?

**Comment by ebfull** [comment]
This was indeed done.
