### ISSUE TITLE
Check if coinIndex should be uint64_t instead of int.

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#245]
In `MakePour` inside `wallet.cpp`, `coinIndex` is a map from coin hashes to the position of that coin in the Merkle tree. There's another variable, `ctr`, which keeps track of the current index in the Merkle tree as it gets built.

Indexes are stored as `int` type, which is not sufficient if the Merkle tree grows larger than 2^32, or if we build on a system where `sizeof(int) = 2`. Should they be changed to `uint64_t`?

**Comment by daira** [comment]
This ticket is obsolete; the relevant code has been rewritten.
