### ISSUE TITLE
HF0 activation plan

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#2451]
We've discussed having HF0 activate merely on a predefined block height, in contrast to (or in addition to?) signaling #2286.

If all clients use versions ≥ 1.0.9 which introduced autosenescence, _and_ only a tiny majority has disabled it, _and_ the oldest version which has not autosenescenced has the new HF0 logic, this should work.

If an important subpopulation is running versions < 1.0.9, or has disabled autosenescence, then this may be dangerous.

**Comment by nathan-at-least** [comment]
How do we deprecate versions < 1.0.9?

- We could trigger safe-mode on older versions < 1.0.9.

**Comment by daira** [comment]
If we do that then we should send them a non-safe mode alert in advance saying what will happen and when.

**Comment by daira** [comment]
Note that the safe-mode alerts can also be overridden (which is fine).

**Comment by bitcartel** [comment]
Safe mode won't work for non-zcashd clients, e.g. Parity fork, etc.

**Comment by daira** [comment]
We're using predefined block heights. We'll see how well this works with Overwinter!
