### ISSUE TITLE
Deprecate nodes < 1.0.9 (pre-autosenescence) at an appropriate time.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#2452]

**Comment by nathan-at-least** [comment]
One danger here is if we have important services which support many users which haven't upgraded.

**Comment by str4d** [comment]
This will happen naturally as a result of #2919 and the Overwinter upgrade itself.

**Comment by str4d** [comment]
We will use the alert keys to notify pre-1.0.9 users about the 1.1.0 release, and put them into safe mode.

**Comment by daira** [comment]
This was done just before Overwinter activation.
