### ISSUE TITLE
urge ! where I can got my ZEC back

### ISSUE THREAD

**Issue by anakin629** [zcash/zcash#2455]
### Describe the issue
yesterday I transfer some ZEC 100+ to a Z_address , after the transfer I got the following info : 
==================================================
    "id": "opid-1d0dbaa0-0f20-48a6-a713-7392aa9a0f8d",
    "status": "success",
    "creation_time": 1497858803,
    "result": {
      "txid": "3a15ebdf385e32386da0f709baa63f9cf46c3dd8179db389c55b3e5e6269f772"
    },
    "execution_secs": 46.511633667,
    "method": "z_sendmany",
    "params": {
      "fromaddress": "zcKynsu61kWc7RvRvPfgWoqAefJ48uDwMesxgEEWhLvEiJ15TvkDD6ud9dKHZgCchCHnuRnHpVopQJHgwYhgtxzf1kCThrU",
      "amounts": [
        {....
====================================================
### The problem is
the ZEC did not send to the destination Z_Addr,  and the ZEC is gone , I can not get balance from local address ! 

I also check the https://explorer.zcha.in/ for the txid , I also can not get any information ! what a pity !
I really worried about the money !

**Comment by anakin629** [comment]
can someone help ? it makes me really sad !

**Comment by bitcartel** [comment]
@anakin629 The transaction was mined in block 134906 about two hours ago: https://explorer.zcha.in/transactions/3a15ebdf385e32386da0f709baa63f9cf46c3dd8179db389c55b3e5e6269f772  and if you do `zcash-cli z_getbalance the_destination_z_address` you should see the balance there.
