### ISSUE TITLE
conftest.cpp:71:6: error: declaration of 'char exit()' conflicts with built-in declaration 'void exit(int)' [-Werror=builtin-declaration-mismatch]

### ISSUE THREAD

**Issue by vrfpk** [zcash/zcash#2459]
Hi there,

running `zcutils/build.sh` and basically, I have the same error message as #2304 q.e.
```
checking for boostlib >= 1.20.0... yes
checking whether the Boost::System library is available... yes
checking for exit in -lboost_system-mt... no
configure: error: Could not link against boost_system-mt !
```
in config.log it is more detailed:
```
configure:22324: checking for exit in -lboost_system-mt
configure:22349: g++ -m64 -o conftest -std=c++11 -pipe -O1 -fwrapv -fno-strict-aliasing -Werror -g  -Wformat -Wformat-security -Wstack-protector -fstack-protector-all -fPIE -I/home/user1/gits/zec/zcash/depends/x86_64-unknown-linux-gnu/share/../include/  -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I/home/user1/gits/zec/zcash/depends/x86_64-unknown-linux-gnu/share/../include -L/home/user1/gits/zec/zcash/depends/x86_64-unknown-linux-gnu/share/../lib   -Wl,-z,relro -Wl,-z,now -pie -L/home/user1/gits/zec/zcash/depends/x86_64-unknown-linux-gnu/share/../lib conftest.cpp -lboost_system-mt  -lanl  >&5
conftest.cpp:71:6: error: declaration of 'char exit()' conflicts with built-in declaration 'void exit(int)' [-Werror=builtin-declaration-mismatch]
 char exit ();
      ^~~~
cc1plus: all warnings being treated as errors
```
I think that the problem is with `'-Werror'` flag (which is passed to the `./configure` via `zcutils/build.sh`) and calling `AX_BOOST_SYSTEM`.
Maybe it's an issue in autoconf, which itself generates builtin with erroneous signature by a little not encouraged `AC_LANG_CALL`. Anyway, without `-Werror` everything works fine.

**Comment by daira** [comment]
@vrfpk Please tell us your platform and g++ version.

**Comment by glebtv** [comment]
Same problem
arch linux
```
> gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc-multilib/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release
Thread model: posix
gcc version 7.1.1 20170528 (GCC) 
```

**Comment by daira** [comment]
Ah interesting, I don't think we've tried compiling with gcc 7.

**Comment by daira** [comment]
See also https://github.com/MyHush/hush/issues/2 . That's enough to confirm this is a gcc 7 issue, or more precisely the boost build process is using an autoconf macro that is incompatible with gcc 7.

**Comment by daira** [comment]
Added a note at https://github.com/zcash/zcash/wiki/1.0-User-Guide#check-gcc-version .

**Comment by vrfpk** [comment]
Well, my platform is Arch 4.11.7-1, gcc 7.1.1 and autoconf 2.69. But, could it be, that earlier versions of gcc didn't gave warning about conflicts with built-in declaration of `void exit(int)`? Because that `char exit()` is generated from autoconf's `libs.m4` and I think that those macros didn't changed too much recently. I think it's an autoconf's issue, I would go complain them I had the courage.

**Comment by radix42** [comment]
You must install and use gcc 5.x on arch, this is a known issue with zcash (and all of its forks)

**Comment by daira** [comment]
Yes it is an autoconf issue, but the path of least resistance is probably just to patch boost to not use that macro.

**Comment by vrfpk** [comment]
Yes, I've changed all `exit` to e.g. `main` in build-aux/m4/ax_boost_*.m4 macros and it's working.

**Comment by bitcartel** [comment]
There is a PR to fix this issue for gcc 7 here: https://github.com/zcash/zcash/pull/2545
