### ISSUE TITLE
Decide whether to use Groth16 or PHGR13/BCTV14 for Sapling

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2465]
PHGR13/BCTV14 is our current proving system. (See section 5.7 of the protocol spec and references there. The minor differences from the PHGR13 paper include adapting to Type 3 pairings, and a slight change to the verification key.)

Groth16 is a more recent proving system designed by Jens Groth and described in https://eprint.iacr.org/2016/260 . It has smaller proofs (about <sup>4</sup>/<sub>9</sub> the size of PHGR13/BCTV14 for a given curve), and faster proving and verification. It is proven secure in the Subversion Generic Bilinear Group Model (Sub-GBGM); see https://eprint.iacr.org/2017/599 .
(The Sub-GBGM is a more realistic model than the GBGM used in Groth's paper, so this is a stronger result than the original one by Groth. The changes made by Abdolmaleki et al are only to the CRS generation and verification, not to proving or verifying.)

Proofs in the Sub-GBGM model a Type 3 pairing abstractly, only allowing the adversary to use certain operations on group elements (group addition in G<sub>1</sub> or G<sub>2</sub>; multiplication in G<sub>T</sub>; pairing; picking a random G<sub>{1, 2, T}</sub> element with unknown discrete log; and comparison of group elements). Of course a real adversary is not limited to using these operations when manipulating group elements, so proofs in this model are only proofs of the difficulty of a certain class of generic attacks. The realism of the model is therefore an issue when assessing the value of the security proof, relative to security proofs based only on standard and/or knowledge assumptions which are available for PHGR13/BCTV14.

@ebfull has implemented Groth16 (several times! :-) ) in Rust. It's likely that we would be using a Rust implementation if we switched to Groth16; also, it's likely that we would be using the [BLS12-381](https://z.cash/blog/new-snark-curve.html) curve. However we could also do each of these things (switch to Groth16, BLS12-381, or Rust) independently, so we need to consider the concrete performance improvement (and other features; see Sean's [comment below](https://github.com/zcash/zcash/issues/2465#issuecomment-310802052)) of Groth16 while holding other factors constant, before making a decision about whether any risk associated with using the newer proving system is justified.

**Comment by daira** [comment]
Note that the proof of (subversion-resistant) zero-knowledgeness of Groth16 does not rely on the Sub-GBGM; only the proof of knowledge-soundness does.

**Comment by arielgabizon** [comment]
A small efficiency comparison
PHGR:
Proof size: 7 G1 elems 1 G2 elem
Proof time: 7 G1 multiexps 1 G2 multiexp
Verificationt time: 12 pairings
Groth:
Proof size: 2 G1 elements 1 G2 elem
Proof time: 2 G1 multiexps 1 G2 multiexp
Verfication time: 3 pairings

**Comment by arielgabizon** [comment]
Personally I think we should wait another two years to give cryptographers time to try to break Groth16

**Comment by daira** [comment]
How does the batched verification time compare?

**Comment by daira** [comment]
We have a Sapling planning meeting on 3 July; it would be good to have performance numbers by then.

**Comment by arielgabizon** [comment]
Thanks for figuring out the batch numbers - I'm also checking that now and will post here

**Comment by arielgabizon** [comment]
Continuing what Daira wrote, verifying a batch of size t in BCTV14 requires
12t G1 - scalar multiplications, t+6 Miller loops, and one Final Exponentiation

I don't have the performance numbers for these 3 operations so can't convert this to a number

**Comment by daira** [comment]
Here's a description of batched Groth16. I'll use multiplicative notation for G<sub>T</sub>, which is not the same as the Groth paper but makes things more easily comparable with Ariel's description.

We want to check a proof (π<sub>A</sub>, π'<sub>B</sub>, π<sub>C</sub>) using the verification equation:

> e(π<sub>A</sub>, π'<sub>B</sub>) = e(π<sub>C</sub>, δ) · e(Z, γ) · Y

where Y = [α]<sub>1</sub> · [β]<sub>2</sub> and Z = ∑<sub>i = 0..ℓ </sub>(a<sub>i</sub> · [(β·u<sub>i</sub>(x) + α·v<sub>i</sub>(x) + w<sub>i</sub>(x)) / γ]<sub>1</sub>.

This can be written as:

> e(π<sub>A</sub>, -π'<sub>B</sub>) · e(π<sub>C</sub>, δ).e(Z, γ) · Y = 1

Raising to the power of random r ≠ 0:

> e(r·π<sub>A</sub>, -π'<sub>B</sub>) · e(r·π<sub>C</sub>, δ) · e(r·Z, γ) · Y<sup>r</sup> = 1

Unlike in PHGR13/BCTV14, there are no factors with the same G<sub>2</sub> part that we can merge.

So, we accumulate as follows:

* a<sub>1</sub> accumulates the product of ML(r·π<sub>A</sub>, -π'<sub>B</sub>)
* a<sub>2</sub> accumulates the sum of r·π<sub>C</sub>
* a<sub>3</sub> accumulates the sum of r·Z
* a<sub>4</sub> accumulates the sum of r

Then the batch verifier checks:

> FE(a<sub>1</sub> · ML(a<sub>2</sub>, δ) · ML(a<sub>3</sub>, γ) · Y<sup>a<sub>4</sub></sup>) = 1

This requires requires 3 multiexps in G<sub>1</sub> and one Miller loop to accumulate each batch element. The verification for a batch requires a double Miller loop, an exponentiation in G<sub>T</sub>, and a final exponentiation.

Since one Miller loop is required to accumulate a batch element in both proving systems, and this will dominate the cost of the multiexps, I believe the Groth16 batched verification will be only slightly faster per element than the PHGR13/BCTV14 batched verification.

**Comment by arielgabizon** [comment]
Thanks a lot for writing this out! I wish there was a good place with measurements?
You're saying miller loop take much more time than scalar mult? (Btw Is it custom to call scalar mult multiexp?)

**Comment by daira** [comment]
Oops, I hadn't noticed that @arielgabizon had already posted :-) Well, that is good because we can check each other's results. I got a different answer for the number of multiexps needed per element in a Groth16 batch (3 vs Ariel's 1); perhaps I missed an optimization. In any case, the conclusion is the same, because in either case the cost of the Miller loop dominates.

**Comment by arielgabizon** [comment]
Ohh no my one was a mistake , we got the same number then

**Comment by daira** [comment]
I probably used the wrong terminology. In any case we're computing (r·π<sub>A</sub>, r·π<sub>C</sub>, r·Z).

My assertion that the cost of the Miller loop dominates is based on section 8.3.2 of https://eprint.iacr.org/2017/334 . The curve they consider there is a bit more conservative than BLS12-381, but it is a BLS12 curve targeting 128-bit security, and they say that the Miller loop requires 77 curve doublings and 2 curve additions.

**Comment by daira** [comment]
Oh but wait, that doesn't dominate; it may be less than a scalar multiplication, depending on how many bits r has. So there is indeed a substantial advantage for Groth16 also when comparing batched verification.

**Comment by arielgabizon** [comment]
Yeah scalar mult requires a number of doublings an additions like the number of bits of r,
or rather the number of set bits in the scalar, which on average would be r/2.
I found something @ebfull sent me once, that in his experiments scalarmult in G1 took 0.634 milliseconds,
he didn't have a result on Miller Loop there, he had a result for the whole pairing of 7 ms
The old version of BCTV reports Miller Loop taking: 0.283 ms.
They don't report scalar mult but they report
  doubling taking 242 NS in G1, and addition taking 335 NS in G1, 
which would give a similar result to Sean's for G1- scalar mult assuming we're doing r/2 of each

**Comment by daira** [comment]
Hmm, I think each r does not have to be uniformly distributed on the exponent field, it's sufficient for it to be, say, 128 bits. We can compute an addition-subtraction chain for r and use it simultaneously to scalar-multiply π<sub>A</sub>, π<sub>C</sub>, and Z; I think I'm correct in saying that requires ~1.6 curve additions/subtractions per bit, i.e. 3 \* 128 \* 1.6 ~= 614 additions/subtractions.

**Comment by ebfull** [comment]
There are other important considerations for choosing Groth16 than just performance. See #2247 and #2425 for examples.

**Comment by arielgabizon** [comment]
@daira - I partially follow, we can take r to have 128 bits, and do things simultaneously for the three elements multiplied by r. I'm not sure how you get to a 1/3 on average additions/subtractions.

**Comment by daira** [comment]
The factor of 1/3 on average is due to the use of [Non-Adjacent Form](https://en.wikipedia.org/wiki/Non-adjacent_form) (with digits {-1, 0, 1}).

**Comment by daira** [comment]
According to https://github.com/zcash/zcash/issues/2502#issue-240031489 , a Miller loop costs around 300 G<sub>1<sub> additions in the ate-pairing implementation of BN254, and around 500 G<sub>1<sub> additions in the current Rust implementation of BLS12-381. Let's split the difference and call it 400 G<sub>1<sub> additions (i.e. assuming that the BLS12-381 Miller loop implementation can be optimised a little more relative to an addition). This is more than I estimated above, so if this is correct then the relative performance advantage of Groth16 batch verification is reduced: the cost of Groth16 to accumulate a batch element is about 3 \* (0.8 \* 127 + 128 / 3) + 400 ~= 833, while the corresponding cost of PHGR13/BCTV14 is about 12 \* (0.8 \* 127 + 128 / 3) + 400 ~= 2131. So Groth16 would be about 2.6 times faster, not 3.6 as I said before.

**Comment by daira** [comment]
@ebfull wrote:
> There are other important considerations for choosing Groth16 than just performance. See #2247 and #2425 for examples.

I think I remember you or @arielgabizon saying recently that the two-round MPC (#2247) could be adapted to PHGR13/BCTV14 as well.

**Comment by daira** [comment]
Unbatched verification requires doing a subgroup check on π'<sub>B</sub>. I tried to figure out whether it was possible to do that check only once per batch, i.e. on Acc<sub>1</sub> = ML(r·π<sub>A</sub>, -π'<sub>B</sub>), but that wasn't clear to me because I don't know how ML behaves on points outside the subgroup.

**Comment by arielgabizon** [comment]
I don't think ML behaves in any predictable manner outside the subgroup.
One way to do a batched subgroup test would be to take a random linear combination of the pi'_B's
and check that that's in the subgroup, but just multiplying an element by a random scalar is as expensive as the subgroup check I think.

**Comment by matthewdgreen** [comment]
Difficulty underatanding the notation. Does this use small exponents (scalars)?

**Comment by arielgabizon** [comment]
Yeah groups are in additive notation.

**Comment by daira** [comment]
@arielgabizon claimed [here](https://github.com/zcash/zcash/issues/2465#issuecomment-310915925) that it was possible to take each r to be 128 bits.

**Comment by daira** [comment]
We will be using a close variant of Groth16 (with subversion soundness). Can this ticket to be closed, or is there any more to decide here?

**Comment by arielgabizon** [comment]
It can be closed

**Comment by nicola** [comment]
@daira is there more material that shows:
- why you decided for groth16
- what changes you have from groth16

**Comment by arielgabizon** [comment]
The changes from Groth are extending its CRS for MPC purposes; detailed in Section 5 here   https://eprint.iacr.org/2017/1050.pdf

**Comment by daira** [comment]
@nicola In addition to faster verification, the bellman implementation of Groth16 has about double the proving speed for the "same" circuit &ndash;reimplemented using the bellman API&ndash; relative to PHGR13 in libsnark. This comparison doesn't isolate the effect of the proving system (for instance the arithmetic and the implementation language is different), but my understanding is that the proving system is the most significant factor in this improvement.

We also commissioned a review of the Groth16 security proof which was important in bolstering our confidence in it. (Not sure if we're ready to publish further details about that yet.)

**Comment by daira** [comment]
@nicola Mary's independent security proof of Groth16-with-extended-CRS is linked from https://electriccoin.co/blog/reinforcing-the-security-of-the-sapling-mpc/

Note that the decision to use Groth16 had already been taken before the flaw in BCTV14 was found. Nevertheless that was another reason to use Groth16 after that point (for the people who knew about the flaw, i.e. Ariel, Sean, Nathan and Zooko).
