### ISSUE TITLE
1.0-User-Guide: Finish the Requirements

### ISSUE THREAD

**Issue by davidhedlund** [zcash/zcash#2467]
https://github.com/zcash/zcash/wiki/1.0-User-Guide says:

> # Requirements
>
> Currently, you will need:
>    Linux (easiest with a Debian-based distribution)
>    64-bit
>    4GB of free memory

First of all, "4GB of free memory" does not mention if its RAM or HDD space.
* Please add RAM
* Please add HDD space

**Comment by daira** [comment]
Is this sufficient? https://github.com/zcash/zcash/wiki/1.0-User-Guide/_compare/fb9824cfb0063df7f1bd22a46b54d6ebdcfd0762...0466ad1fbf5f1c6f793c0cefd7124f2e2a3cc337 It's not possible to give a final disk space requirement, since the size of the block chain increases over time, but it's currently ~3.5 GB.

**Comment by davidhedlund** [comment]
@daira Much better. The block chain won't decrease right?

Then it should be safe to mention "Hard disk space: At least 3.5 GB".

**Comment by daira** [comment]
I'll say "at least 10 GB".

**Comment by davidhedlund** [comment]
@daira That should be safe.

**Comment by davidhedlund** [comment]
@daira 

> gcc/g++ 4.9 or later is required. Use g++ --version to check which version you have.

I could use g++ (Ubuntu 4.8.5-2ubuntu1~14.04.1) 4.8.5 so this is not true.

**Comment by davidhedlund** [comment]
@daira Using a Ubuntu Trusty-base distro.

**Comment by daira** [comment]
I'm surprised that worked. Maybe some of the fixes from gcc 4.9 made it into later 4.8.x point releases. Nevertheless, we only officially support 4.9+.

**Comment by davidhedlund** [comment]
@daira I ask for a final update

"at least 10 GB of free disk space (the size of the block chain increases over time)". The Zcash software itself is 2.4 Gb.

I would put it something like this.

* Operating system: GNU/Linux (easiest with a Debian-based distribution)
* Computer architecture: 64-bit
* RAM: 4 GB
* Hard disk drive space: 10 GB -- At this writing the Zcash is 2.4 GB, the block chain is 3.5 GB and growing.

**Comment by davidhedlund** [comment]
@daira Can you please add that "You need additional 2.4 GB if you compile Zcash yourself"?
