### ISSUE TITLE
Debian binary packages: unmet dependencies

### ISSUE THREAD

**Issue by davidhedlund** [zcash/zcash#2468]
I get error when I follow https://github.com/zcash/zcash/wiki/Debian-binary-packages

```
$ sudo apt install zcash
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 zcash : Depends: libgomp1 (>= 4.9) but 4.8.4-2ubuntu1~14.04.3 is to be installed
         Depends: libstdc++6 (>= 4.9) but 4.8.4-2ubuntu1~14.04.3 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by daira** [comment]
Please try upgrading gcc/g++ as described at https://github.com/zcash/zcash/wiki/1.0-User-Guide#check-gcc-version .

**Comment by daira** [comment]
Added to https://github.com/zcash/zcash/wiki/Debian-binary-packages#troubleshooting

**Comment by ioptio** [comment]
@davidhedlund have you tried upgrading gcc/g++ as requested above?

**Comment by davidhedlund** [comment]
@ioptio I don't have time, sorry.

**Comment by davidhedlund** [comment]
@ioptio There's to many packages and repositories installed on my system right now so its impossible to easily evaluate this. I don't have time to re-evaluate it on a fresh distro install, sorry.

**Comment by daira** [comment]
#2513 would fix this.
