### ISSUE TITLE
CI Worker: xubuntu

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#2470]
Dependency of #1283

**Comment by nathan-at-least** [comment]
I just posted this proposed prioritization for workers: https://github.com/zcash/zcash/labels/CI%20Worker

According to that, we should support the variant of Ubuntu most Zcash users use first, then if that doesn't address Xubuntu problems specifically, consider adding Xubuntu worker separately.

**Comment by str4d** [comment]
@nathan-at-least Do we still want to set up an Xubuntu-specific worker, or is the Ubuntu 16.04 worker sufficient?

**Comment by str4d** [comment]
#1283 has been closed; de-prioritising this issue.
