### ISSUE TITLE
Invalid Signature on Debian Binaries for 1.0.10

### ISSUE THREAD

**Issue by gesker** [zcash/zcash#2472]
### Describe the issue
Bad Debian apt signature

#### If so, please list the steps to reproduce below:
apt update

### Expected behaviour
No signature errors

### Actual behaviour + errors
Err:10 https://apt.z.cash jessie Release.gpg                                         
  The following signatures were invalid: F1E214037E94E950BA8577B263C4A2169C1B2FA2
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://apt.z.cash jessie Release: The following signatures were invalid: F1E214037E94E950BA8577B263C4A2169C1B2FA2
W: Failed to fetch https://apt.z.cash/dists/jessie/Release.gpg  The following signatures were invalid: F1E214037E94E950BA8577B263C4A2169C1B2FA2
W: Some index files failed to download. They have been ignored, or old ones used instead.

### The version of Zcash you were using:
1.0.9 trying to go to 1.0.10

### Machine specs:
- OS name + version: ubuntu

**Comment by martinium** [comment]
I am also having the same issue when I tried to update just now.

**Comment by BRFreshness** [comment]
same here:
```
W: GPG error: https://apt.z.cash jessie Release: The following signatures were invalid: BADSIG 63C4A2169C1B2FA2 Zcash Master Signing Key
```

**Comment by ic16b040** [comment]
Same here. Upgrade to 1.0.10 yesterday morning worked, but now I get the same apt error

**Comment by ic16b040** [comment]
It's working again with updates version 1.0.10-1. thanks guys

**Comment by daira** [comment]
Good to know that it works with 1.0.10-1. Note that for people who haven't already upgraded to that, we are recommending sticking with 1.0.9 for now (in fact, you won't be able to upgrade because the packages have been pulled), due to a regression in the network behaviour of 1.0.10[-1].

**Comment by daira** [comment]
Fixed for 1.0.10-1.

**Comment by daira** [comment]
Incidentally, the problem was that the packages were signed with SHA-1 as the hash algorithm, which is not accepted by recent versions of apt.

**Comment by trou** [comment]
Reopening as packages are not installable anymore on Debian Sid because of SHA-1 signatures.

**Comment by gesker** [comment]
Seems to have popped up again on 1.0.11 -- Ubuntu 17.04

Get: 1 https://apt.z.cash jessie Release.gpg [819 B]                                                                                                                    
Err https://apt.z.cash jessie Release.gpg                                                             
  The following signatures were invalid: F1E214037E94E950BA8577B263C4A2169C1B2FA2                                                                                                                                                                                 
Fetched 819 B in 2min 0s (6 B/s)
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://apt.z.cash jessie Release: The following signatures were invalid: F1E214037E94E950BA8577B263C4A2169C1B2FA2
W: Failed to fetch https://apt.z.cash/dists/jessie/Release.gpg: The following signatures were invalid: F1E214037E94E950BA8577B263C4A2169C1B2FA2
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by gesker** [comment]
Oops... Renamed this ticket. Mean to open new one.
 New Ticket is:  Invalid Signature on Debian Binaries for 1.0.11 #2590
