### ISSUE TITLE
Eliminate hard-coded x86_64-unknown-linux-gnu

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#248]
This path shouldn't be baked-in anywhere, as it will change for different build targets.

**Comment by str4d** [comment]
Partially addressed in #1905.

**Comment by sellout** [comment]
Is this issue resolved? Considering CI currently builds on ARM, devs build on Intel Macs, and we have the Windows cross-build, it seems like this is probably good.
(cc: @str4d)

**Comment by str4d** [comment]
Yeah, this has been closed ever since we had cross-compilation working for Windows.
