### ISSUE TITLE
User writes "Witness for note commitment is null on spending from imported Zaddr"

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#2486]
Source: https://forum.z.cash/t/witness-for-note-commitment-is-null-on-spending-from-imported-zaddr/18153

Post 1
> After importing a z spending key from one wallet to a new wallet I want to send coin from the corresponding zaddr in the second wallet to a new zaddr in that second wallet. I see the correct amount in the zaddr with z_getbalance. I have this message when trying to do the shielded TX with z_sendmany from the second wallet: "Witness for note commitment is null". I did reindex the second wallet but it still does not want to send doing the same message. How can this be resolved and what does it mean? Documentation is sparse on this issue. When trying to do the TX from the first wallet it works. I thought just importing the spending key was sufficient to spend the zec out of a zaddr.
Also reindex is very slow using most of the time only one core cannot this be multi threaded? Or maybe can I reindex only part of the block chain? Thx

Post 2
> After reindex of the new wallet ended (was done offline) I stopped zcashd and launched it again online to finish synchronization. It aborted with this error:
zcashd: wallet/wallet.cpp:659: void CWallet::IncrementNoteWitnesses(const CBlockIndex*, const CBlock*, ZCIncrementalMerkleTree&): Assertion `(nd->witnessHeight == -1) || (nd->witnessHeight == pindex->nHeight - 1)' failed.
Aborted

**Comment by bitcartel** [comment]
From Lou on the forum post:

> I imported the keys, several in a row in fact, with "zcash-cli z_importkey spendingkey no" for the first ones then "zcash-cli z_importkey spendingkey yes" for the last one (to not do rescan everytime). I then closed the second wallet for 2 weeks.
> Later, I opened the second wallet, synch it, tried to send from one of the zaddress in common between the two wallets to one of the zaddress only in the second wallet (all this was to change of wallet while keeping traceability by importing the relevant key from the first wallet, so I could show with the viewkey later from where the coin came). At this time it failed with "Witness for note commitment is null". I did -rescan it changed nothing. I did -reindex then. 
> Meanwhile as reindexing was so long I sent from the common same zaddress in the first wallet to one of the z address in the second wallet (same TX I tried to do from the second wallet and that failed with the error). This worked from the first wallet. I thought it shall not be an issue to do this while reindexing the second wallet because it was months backward in time at this index. After reindexing finished (offline), I stopped the second wallet, put internet and run zcashd to synch the last blocks (that shall have contained the spend TX). During the initial rescan at opening it crashed with the zcashd: wallet/wallet.cpp:659 error. Then I took my backup of the second wallet, synched it, got the coin and moved them to taddress to be sure :wink:
> 
> I wanted to use the z_exportwallet and z_importkey feature to save my wallet on paper, but now that I see this issue with the zkeys I will only put on paper the t_address which I am sure give no error on importation as it is well known code. BTW z_importwallet "walletfile" does not work, the exported file is not found even tough the folder is specified in zcash.conf and the name of file is the same than used with z_exportwallet "walletfile".
> 
> But can you explain briefly what is this note commitment and why it is not possible for me using the SKey and the common state of the blockchain to use the coins in the imported Z_address (which I can see with z_getbalance).

**Comment by ioptio** [comment]
Perhaps related: https://github.com/zcash/zcash/issues/1936

**Comment by bitcartel** [comment]
We can split out part of the comment into a new ticket: 

> BTW z_importwallet "walletfile" does not work, the exported file is not found even tough the folder is specified in zcash.conf and the name of file is the same than used with z_exportwallet "walletfile".

**Comment by bitcartel** [comment]
Closing this ticket, duplicate of #2524
