### ISSUE TITLE
Active Note / UTXO merging.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#2493]
Active Note/UTXO merging is a feature which generates transactions explicitly to merge notes or UTXOs. This is in contract to Opportunistic Note Merging (#1961) which merges notes/utxos incidentally while fulfilling other user requests.

If #1961 is implemented and can also be explicitly triggered if necessary, then it would _be_ an implementation of Active Note Merging.

The reason to file this ticket apart from #1961 is only to introduce a shorter term work-around for users encountering note/utxo-growth performance issues. Active Note Merging may already be possible with the existing API. If so, let's document it explicitly as a recommendation for users who are having note/utxo-growth performance problems, and close this ticket.

**Background and Motivation:**

Note/UTXO merging is important for managing performance issues (primarily). Transactions which require more input notes or UTXOs begin to hit performance limits. There are several to consider:

- too many inputs results in transactions with sizes over the 100,000 byte consensus rule limit. (This is one delta of Zcash from Bitcoin.)
- too many UTXO inputs which use `SIGHASH_ALL` leads to a quadratic hashing performance degradation. This is well known and inherited from Bitcoin. (Segwit and flextrans both address this performance problem.) Currently, Zcash has a hacky default mempool policy that introduces an arbitrary node-configurable limit: #2342. 
- more input notes results in more JoinSplits, which may exceed latency requirements for some use cases. (Note that merging notes before making a transfer still requires many JoinSplits, and the primary benefit would seem to be "responsiveness": the time between learning of the need to make a transfer to transfer completion.)

There is a trade-off between concurrent transfers and minimal note/utxo count, especially for JoinSplits: A JoinSplit may not refer to an input unless that input has been confirmed in at least 1 block. This constraint when combined with a wallet policy that attempts to maintain all funds in a single note would cause all transfers out of that account to become fully serialized with at least one block confirmation between each (thus low throughput and no-concurrent transfers). It would seem a more sensible policy anticipates some concurrency and makes some decision based on note-count and/or note values when to merge.

Can users already explicitly merge? Is it possible for users to cause note and UTXO merges with explicit requests? If so, let's clearly document that

**Comment by nathan-at-least** [comment]
Ever since https://github.com/zcash/zcash/pull/2342 some users are experiencing "confirmation time hell" with a poor UX because they can't predict, control, or measure when that will happen, see https://github.com/zcash/zcash/issues/2668#issuecomment-337757090 .

Active UTXO merging would be one way to indirectly alleviate this issue, because it would help high-volume users (and all other users) quickly reach a state where normal transactions will never have too many inputs.

Here's a sketch of what the UX would look like:

- introduce new config non-negative int `active-merge-utxo-goal` which defaults to 0 (and must be non-negative). [1], [2]
- introduce new config non-negative int `active-merge-utxo-input-limit` which defaults to 25.
  - If this is ≤ 1 or >25, fail on startup with an error requiring it to be in`[2, 50]` inclusive. [3]
- if `active-merge-utxo-goal != 0` then periodically [4]:
  - count the total number `N` of UTXOs controlled by the wallet (across all addresses). [5]
  - if that `N > active-merge-utxo-goal`, create a transaction with `active-merge-utxo-input-limit` txins (or fewer, if fewer are available) and a new t-addr as destination, then emit that transaction.

[1] I use hyphens in the name for readability. `-istronglydislikethenohyphennocapitlizationstyleofbitcoinnamingwhichmakesithardtoparse=true`

[2] A default of 0 means when users upgrade there will be no difference in behavior unless they add this config value, making the feature opt-in. In the future, we may want to change the default to something else, turning the feature on by default and leaving opt-out configuration.

[3] The upper bound of this range needs some more thought. I think ~25 might be good enough even for really high volume exchanges or mining pools or miners, on the assumption that they don't receive > 25 UTXOs per block. If the upper bound is larger than what most miners set for `mempooltxinputlimit`, then each active merge transaction will take days to execute! That will be surviveable (see [4]), although bad UX.

[4] "periodically" is underspecified. I think once per block is good, and would help all users quickly reach the goal. It *should* also serialize this process so that there's only ever at most 1 "active UTXO merge" transaction outstanding, just in case something prevents these transactions from being mined, we don't want to emit many transactions that lock up all UTXOs!

**BUG:** What if `active-merge-utxo-input-limit` > median `mempooltxinputlimit` so that the active merge transactions take days to mine. In that case, the wallet may depend on the outputs of the active merge transactions for other non-active-merge transactions, adding a very large latency to those other 'normal' transactions. I don't know when the wallet chooses to use unconfirmed UTXOs as inputs. If they are always deprioritized over already confirmed UTXOs, I believe this is good enough. This requires more research.

[5] This is intended to work with the current wallet status quo of using many addresses and combining from them in inputs. I don't like this design. I think the only motivation is privacy, and it's terrible privacy. However, many existing users who need to merge UTXOs most likely have those UTXOs spread across many addresses. (I initially started describing a per-address mode of this feature, and decided that's premature.)

As a *separate feature* / PR we could implement the same for notes with `active-merge-note-goal` and `active-merge-note-input-limit` with similar behavior, although the tuning of those parameters are quite different for a few reasons (one being that you cannot chain unconfirmed note merges across transactions).

**Comment by str4d** [comment]
This could also (either instead of, or in addition) be implemented as an RPC method that users can call.

**Comment by str4d** [comment]
@daira and I decided to prioritise this for 1.0.14, over other potential non-NU0 work.

**Comment by nathan-at-least** [comment]
Hm, this kind of feature has been stewing in the back of my mind for a while. I've now developed a preference for a design which requires an RPC call for each consolidating transaction, and that call provides "continuation information" similar to the design of `z_shieldcoinbase`.

This is in contrast with my thinking above where there would be a cron-job-like functionality that would periodically emit transactions.

The reason I prefer the explicit transaction-per-RPC call is that it gives more operational control to the user. For example some users may want a constant low rate of consolidation, others may prefer to batch consolidations into periods due to their cold-storage architecture, someday users may want to schedule "maintenance transactions" around low-fee periods, etc…

Also, it feels like a substantial behavioral change to `zcashd` operations for it to start "actively scheduling" actions rather than the current design which only maintains the blockchain state via the peer network, then responds to explicit user requests.

**Comment by nathan-at-least** [comment]
So in following the 'explicit RPC call per transaction' design, the requirements I propose look like the following:

**Request Inputs:**

- specify consolidation *from* either an explicit set of addresses (both t-addr and z-addr) or a flag indicating "all addresses" the wallet controls. Let's call that flag `ANY`.
- specify consolidation *to* an explicit single address.
- specify two limits `max_in_transparent` and `max_in_shielded`.
- if the destination is a z-addr, allow a memo field parameter.

**Semantics:**

This uses the same async RPC framework as `z_sendmany` and `z_shieldcoinbase`, where an `opid` is immediately returned and the following logic takes place as part of the operation execution.

Select up to `max_in_transparent` UTXOs from the subset of input addresses which are t-addrs. Which UTXOs are selected from which addresses in the input set are not otherwise constrained by the caller.

Additionally, select up to `max_in_shielded` notes from the subset of input addresses which are z-addrs, with no other caller-specified constraints on the selection.

Generate a transaction with the required txins and JoinSplit inputs to consume all selected UTXOs and notes.

**Output Value:**

The result of the operation is these fields:

```{
  "txid": TXID or null,
  "error": string or null,
  "utxos_remaining": uint,
  "notes_remaining": uint,
}```

The `txid` is `null` if the input constraints were impossible to fulfill (example: `max_in_transparent == 0` and no t-addresses were in the input set). IFF `txid` is not `null`, then `error` must be `null`. IFF `txid` is `null` then `error` is a string describing the error message. (**FIXME:** See [1] about internationalization.)

The `*_remaining` values count the remaining UTXOs/notes that were not included in this consolidation transaction. *Warning:* Can calculating these numbers become prohibitively expensive for very large wallets? It would be good to benchmark this call with something like 1 million UTXOs and 1 million notes which is an OOM larger than any case we know of today.

**Notes on Constraints:**

Providing `max_in_transparent` and `max_in_shielded` both as 0 along with the `all addresses` input set provides a query that returns an `error` string like `"Both max_in_transparent and max_in_shielded are 0 so now inputs can be selected"`. The caller may use this just for the output `*_remaining` values.

Providing either of `max_in_transparent` or `max_in_shielded` as 1 is weird, but could be useful? In the sub-case that the input address set is identical to the output address, it seems nonsensical, so maybe in that one subcase, there's a constraint `error`.

If `max_in_transparent` > 0 and there are 0 t-addrs in the input set, that is a constraint error that should be reported.

**Footnotes:**

[1]  What error message about internationalization? I think in general we should give *every* error message output by the RPC interface a unique numeric code along with a short English description, then provide separate resources such as a website for understanding those errors along with translations. This is inspired by the `rustc` error system. But let's not include that in this specification and follow that up as a separate ticket, since it's a large scale refactor.
