### ISSUE TITLE
mention zcashcommunity.com/markets/

### ISSUE THREAD

**Issue by davidhedlund** [zcash/zcash#2495]
# https://z.cash/blog/third-party-support.html
Many people are still using https://z.cash/blog/third-party-support.html to find where to buy Zcash and other things.

As mentioned [here](https://github.com/zcash/zcash/issues/2437#issuecomment-311761415), please add a disclaimer at the top of the page saying: "a blog post from launch with lists of wallets and exchanges that existed back then. We are not actively maintaining such a list, although you can use https://www.zcashcommunity.com/markets/"

# https://z.cash/support/faq.html
Also, in https://z.cash/support/faq.html can you please replace these links with https://www.zcashcommunity.com/markets/ ?

* https://z.cash/blog/third-party-support.html
* https://zcashblog.wordpress.com/zcash-exchanges/

**Comment by davidhedlund** [comment]
@nathan-at-least Thanks.

**Comment by davidhedlund** [comment]
Also, in https://z.cash/support/faq.html can you please replace these links with https://www.zcashcommunity.com/markets/ ?

* https://z.cash/blog/third-party-support.html
* https://zcashblog.wordpress.com/zcash-exchanges/
> We encourage the community to host their own lists and repositories of successful providers such as in this [Zcash community blog](https://zcashblog.wordpress.com/zcash-exchanges/) (https://zcashblog.wordpress.com/zcash-exchanges/).

with

> We encourage the community to host their own lists and repositories of successful providers such as on [Zcashcommunity.com - Zcash Markets](https://www.zcashcommunity.com/markets/)(https://www.zcashcommunity.com/markets/).

**Comment by ioptio** [comment]
This was completed. Not sure how we missed the ticket when it was created, however.

**Comment by davidhedlund** [comment]
> This was completed. Not sure how we missed the ticket when it was created, however.

I just verified that everything has been fixed. Thanks.
