### ISSUE TITLE
Improve implementation of Bitcoin Script by enabling disabled opcodes

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#2508]
Currently the interpreter has disabled many potentially useful opcodes.

https://github.com/zcash/zcash/blob/02e5fffadc466a2015b501873de486fcc38916d9/src/script/interpreter.cpp#L291

Opcodes described here:

https://en.bitcoin.it/wiki/Script

This would diverge from upstream ~~design~~ implementation but allow us to have more advanced scripting ability.

**Comment by radix42** [comment]
Just last night I was contemplating doing this in a downstream fork of zcash, so official support of this here would be great imho :-)
Note that I am also biased, as I have been using FORTH on and off for 32 years, and it'd be trivial to slap a FORTH interpreter on top of the full set of opcodes, which was the original design IIRC.

**Comment by radix42** [comment]
In other words, pretty please with sugar on top do this, and I'll contribute an interpreter to ride on top of it for FORTH-like smart contracts

**Comment by daira** [comment]
I don't know why some of these opcodes were disabled, since they incur no significant DoS risk. Obviously we have to review their implementation and make sure they are properly tested. ``OP_CODESEPARATOR`` should remain disabled.

**Comment by daira** [comment]
I'm currently pretty negative on adding any new script functionality, because that is going further away from deprecating t-addresses.

**Comment by nuttycom** [comment]
Closing as wontfix; we will not be updating transparent script functionality.
