### ISSUE TITLE
CI Worker: CentOS

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#2510]
ref: #2294

**Comment by str4d** [comment]
For CentOS 7, we just need to install pip manually (as it isn't part of the standard repository). I can create a worker for it relatively easily.

For CentOS 6, there's a larger problem: the standard repository includes Python 2.6, but we need 2.7 for Buildbot. I'm trying a few different avenues to hook this into the ci-workers playbook, but it would really help to get some feedback from CentOS 6 users as to how they usually run Python 2.7 as "standard software".

**Comment by mdr0id** [comment]
Closing. We now have a functioning Centos8 builder containerized and functioning successfully in production. Also we are now past Python2.7 EOS
