### ISSUE TITLE
Place the parameters in a proper CDN.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#2514]
Currently @radix42 is hosting a CDN copy of the params because S3 has such frequent failures. ZcashCo or the Foundation should provide this piece of infrastructure (or pay for @radix42 or another community member to administer it).

**Comment by nathan-at-least** [comment]
I see this as distinct from #1296 which seems to be more about making `fetch-params.sh` smarter and adding more hosting options, and #600 which is similar but about using Bittorrent instead of a "standard" CDN.

**Comment by mms710** [comment]
This has been completed.

**Comment by gojomo** [comment]
For reference, what CDN(s) were chosen & what canonical URLs are now preferred?

**Comment by ianamunoz** [comment]
@gojomo
