### ISSUE TITLE
Reproduce z_importkey bugs in test

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#2515]
Bonus if this test can reproduce any of these:

- #1936 
- #2486 / #2524

**Comment by nathan-at-least** [comment]
Note, since this ticket was filed we've added a `key_import_export.py` test for t-addr keys in #2616.

**Comment by arcalinea** [comment]
Changed name from `Add an RPC test that exercises z_importkey` to `Reproduce z_importkey bug in test` since a test for z_importkey has now been added.
