### ISSUE TITLE
 ZEC is currently under maintenance or experiencing wallet/network issues.

### ISSUE THREAD

**Issue by gotope** [zcash/zcash#2520]
hello,

Lots of website declare the ZEC network is very slow, is there any solution to go?

**Comment by daira** [comment]
If you're referring to Poloniex, see https://forum.z.cash/t/statement-from-zcashco-on-poloniex-situation-july-2017/18937/15 . Otherwise, we're not aware of any Zcash network-wide performance issues at the moment.

**Comment by bbenites** [comment]
Zcash Network is definitely down, I tried to send from a ledger wallet its not working, and I try from two different exchanges there was an error displayed. So something is wrong
