### ISSUE TITLE
[Sapling] Analyse post-quantum effect of Sapling

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2527]
There's already a ticket about post-quantum Zcash (#805), but this one has a narrower scope: determine how any Sapling protocol changes affect quantum resistance, and identify and fix or justify any regressions or unnecessary deficiencies.

In particular, we conjectured that Sprout has post-quantum privacy for z-addresses that are kept secret between payer and payee against a quantum adversary, and Sapling should at least preserve that property.

**Comment by daira** [comment]
For example, we intend to replace SHA256Compress for the Merkle tree hashes, note commitments, and possibly the PRFs by Pedersen hashes. A Pedersen hash is not post-quantum binding (you can break it by solving ECDLP for the inner curve), whereas SHA256Compress can reasonably be conjectured to be post-quantum binding. I think that this doesn't matter because in a post-quantum setting you can solve ECDLP for the outer curve and break soundness of the proving system. That would allow you to do everything you could do by breaking the hashes/commitments/PRFs, so there is no loss from moving to a scheme that allows the latter.

**Comment by defuse** [comment]
I'm not sure if this is a privacy regression from Sprout but I think a quantum adversary who is a recipient of a Sapling transaction can tell whether the sender included any dummy notes.

Looking at Section 4.12 of the protocol.... Suppose you know all rcv<sup>new</sup> and their corresponding values but you're lacking knowledge of *two* rcv<sup>old</sup> and their values, call them values A and B. You can already infer A+B (because balance holds) but you shouldn't know anything else about A and B. If you can break discrete log, you can check whether one of A or B is zero as follows. Hypothesize that A is zero. Compute bvk' the same way as bvk, but exclude the commitment to A. Define bsk' the same way as bsk, except exclude the trapdoor for A. If A = 0, it's still the case that bvk' = ValueComit<sub>bsk'</sub>(0), meaning that bvk' = [bsk']R. Find bsk' by computing the discrete log of bvk' w.r.t. R. Now, bsk' is the [+]-sum of B's trapdoor and some other trapdoors you know, so you can solve for B's trapdoor. Once you know B's trapdoor, you can check if B is a commitment to the known value A+B. If this fails, repeat the same steps reversing the roles of A and B, and if that fails, then neither value is zero.

**Comment by defuse** [comment]
Diversified addresses can be linked because unlinkability relies on the Decisional Diffie-Hellman assumption. Maybe that's worth mentioning in the [FAQ answer](https://z.cash/support/faq/#quantum-computers).

**Comment by daira** [comment]
The attack on privacy doesn't work. Intuitively, here's why attacks of this kind can't work:
* each cv information-theoretically doesn't give any information about the corresponding v, because all the rcv are chosen independently;
* the validity of the binding signature only tells you something you already knew, i.e. that balance holds.

But the description of the attack sounded plausible, so what actually goes wrong if you try to run it?

Let's try the simplest case where you only have two Sapling inputs v<sup>old</sup><sub>0</sub> and v<sup>old</sup><sub>1</sub>, one of which is zero. v<sup>balance</sup> is then just equal to the other input.

The attack says to compute bvk' as cv<sup>old</sup><sub>1</sub> - ValueCommit<sub>0</sub>(v<sup>balance</sup>). This is equal to [v<sup>old</sup><sub>1</sub>] V + [rcv<sup>old</sup><sub>1</sub>] R - [v<sup>balance</sup>] V. Then we compute bsk' as the discrete log of bvk' wrt R. This will give bsk' = (v<sup>old</sup><sub>1</sub> - v<sup>balance</sup>).x + rcv<sup>old</sup><sub>1</sub>, where x is such that V = [x] R. (If the hypothesis that v<sup>old</sup><sub>0</sub> = 0 is correct, we will have v<sup>old</sup><sub>1</sub> = v<sup>balance</sup> and so bsk' will be rcv<sup>old</sup><sub>1</sub>.)

The attack then asks us to "check if B's commitment is a commitment to the known value A+B", i.e. to check that cv<sup>old</sup><sub>1</sub> = ValueCommit<sub>bsk'</sub>(v<sup>balance</sup>). This is equivalent to cv<sup>old</sup><sub>1</sub> = [bsk'] R + [v<sup>balance</sup>] V, which is equivalent to cv<sup>old</sup><sub>1</sub> = bvk' + [v<sup>balance</sup>] V. Subsitituting bvk' with its definition above and cancelling cv<sup>old</sup><sub>1</sub>, this is true iff ValueCommit<sub>0</sub>(v<sup>balance</sup>) = [v<sup>balance</sup>] V, which is true by definition.

But wait! The ValueCommit check will *always* pass, even if v<sup>old</sup><sub>0</sub> is *not* zero. Indeed, we could have swapped indices 0 and 1 in the above, and we would still end up with a ValueCommit check that always passes.

More generally, hypothesize that v<sup>old</sup><sub>0</sub> = v<sup>guess</sup><sub>0</sub>. Then v<sup>old</sup><sub>1</sub> = v<sup>balance</sup> - v<sup>guess</sup><sub>0</sub> and so bsk' = - v<sup>guess</sup><sub>0</sub>.x + rcv<sup>old</sup><sub>1</sub>. Since we excluded cv<sup>old</sup><sub>0</sub>, to proceed we need to adjust the balancing value by subtracting v<sup>guess</sup><sub>0</sub> from it. Hence we compute bvk' as cv<sup>old</sup><sub>1</sub> - ValueCommit<sub>0</sub>(v<sup>balance</sup> - v<sup>guess</sup><sub>0</sub>). This will be equal to [v<sup>old</sup><sub>1</sub>] V + [rcv<sup>old</sup><sub>1</sub>] R - [v<sup>balance</sup> - v<sup>guess</sup><sub>0</sub>] V. Then we compute bsk' as the discrete log of bvk' wrt R as before. This will give bsk' = (v<sup>guess</sup><sub>0</sub> + v<sup>old</sup><sub>1</sub> - v<sup>balance</sup>).x + rcv<sup>old</sup><sub>1</sub>. (If the hypothesis is correct, v<sup>guess</sup><sub>0</sub> + v<sup>old</sup><sub>1</sub> - v<sup>balance</sup> will be 0 and so bsk' will be rcv<sup>old</sup><sub>1</sub>.)

Now we continue as before, but with the adjusted balancing value in place of v<sup>balance</sup>. That is, in order to test the hypothesis we are supposed to check that cv<sup>old</sup><sub>1</sub> = ValueCommit<sub>bsk'</sub>(v<sup>balance</sup> - v<sup>guess</sup><sub>0</sub>). This is equivalent to cv<sup>old</sup><sub>1</sub> = [bsk'] R + [v<sup>balance</sup> - v<sup>guess</sup><sub>0</sub>] V, which is equivalent to cv<sup>old</sup><sub>1</sub> = bvk' + [v<sup>balance</sup> - v<sup>guess</sup><sub>0</sub>] V. Now, subsituting the definition of bvk' and cancelling cv<sup>old</sup><sub>1</sub>, we have ValueCommit<sub>0</sub>(v<sup>balance</sup> - v<sup>guess</sup><sub>0</sub>) = [v<sup>balance</sup> - v<sup>guess</sup><sub>0</sub>] V which is true by definition. So the check will always pass regardless of the value of v<sup>guess</sup><sub>0</sub>.

**Comment by defuse** [comment]
@daira's reasoning is correct! My mistake was to intuitively think it's a contradiction/unlikely to have found a different opening to B's commitment and so the check would fail in the A!=0 case, but actually if the attacker is computing discrete logs it's not unreasonable at all that they find a different opening (and indeed they do).

**Comment by daira** [comment]
This is done in my presentation for Zcon3 ([video](https://youtu.be/f6UToqiIdeY), [slides](https://github.com/daira/zcash-security)).
