### ISSUE TITLE
[Sapling] Define z-key and z-address structure, derivation, and encoding

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2528]
The scope of this ticket includes:

* what kinds of key or address there are &mdash; for instance, viewing keys, diversified addresses, etc.;
* how Sprout and Sapling keys/addresses coexist and which operations are valid on each;
* how Sapling z-addresses are derived;
* how Sapling addresses and keys are encoded (raw and string encodings).

Address registration protocols are out of scope.

We might need smaller tickets once the design space becomes clearer.

**Comment by daira** [comment]
I'd really like Sapling z-addresses to include robust error detection as  in [Bech32](https://bitcoin.sipa.be/bech32/demo/demo.html) (see the video or transcript for rationale). Although this is technically orthogonal to other Sapling goals, address format changes cause a great deal of user disruption, so IMHO we should take the opportunity to bundle this change with the necessary introduction of new addresses.

**Comment by daira** [comment]
Playing around with address sizes:

Base58Check t-addr (35 chars)
``t14oHp2v54vfmdgQ3v3SNuQga8JKHTNi2a1``

Sprout Base58Check z-addr (95 chars)
``zcBqWB8VDjVER7uLKb4oHp2v54v2a1jKd9o4FY7mdgQ3gDfG8MiZLvdQga8JK3t58yjXGjQHzMzkGUxSguSs6ZzqpgTNiZG``

Bech32 t-addr (43 chars)
``ts1z9lq7fgmzges4kf9c62q86ugz9l3k878pvpqjd98``

Sapling Base58Check z-addr w/ 80-bit diversifier + 1-byte version/flags (65 chars)
``zsP5Qx7BRmdqUNX4HdvsixjorrdxjQgu9cCbSi86aQxeUkqhd4539kcjX1zFgVJ5W``

Sapling Bech32 z-addr w/ 80-bit diversifier + 1-byte version/flags (78 chars)
``zs1gda87hkazaa3754hmmtqvdqty9zvtqxatz05u48kmpv5z55tx8q8sptajvqzz95n4y4ly96t2wt``

Sapling Bech32 vanity z-addr w/ 80-bit non-random diversifier + 1-byte version/flags (78 chars)
``zsvanjtyelectrjcc0jnsw0wjxqx93uaj382h6038urn94duvx83knw99m3tg0eptfp7fw7g90yn7y``

Sapling Base58Check z-addr w/ 2 group elements + 1-byte version/flags (96 chars)
``zshMi394kAU2KE8ezz8MLQk4DrQnYprYBgsyUsMxu8eQ8jbwioVVuxQiugrnEvzUY6nbABKgSVRkVprfUDPdRdVxkvcUXLeZ``

Sapling Bech32 z-addr w/ 2 group elements + 1-byte version/flags (113 chars)
``zs1a9st8djdnvkm04cjkgdtmhatgxu5n4fypxtkl7t0tpyt82sl6jatzldauutama00uw0v9hmp2lp4nkqw8fv6n2pzpu24dzp9pkv8pqnugtmeme``

```
$ python
from base58 import b58_encode  % PyPI
b58encode_check(b'\x05\x24' + b'\xff'*((256+256+8)/8))

% https://github.com/sipa/bech32 : ref/python
from segwit_addr import bech32_encode, convertbits
import os
bech32_encode(b'zs', convertbits(map(ord, os.urandom((256+80+8)/8)), 8, 5))
```

**Comment by ebfull** [comment]
I assume that we want the diversifier to come before the group element to help vanity address generators? :)

**Comment by daira** [comment]
*Shrug*, not sure if we actually want to encourage that or not. But wanting a vanity address is mutually exclusive with wanting address unlinkability, so I guess there's no harm. (Don't prohibit what you can't prevent.)

**Comment by daira** [comment]
Raw addresses:
* prefix "zs", 80-bit d || 1 zero bit || 255-bit Montgomery-x pk<sub>d</sub>

Raw spending key:
* prefix "sk", 256-bit sk

Raw incoming viewing key:
* prefix "zivk", 6 zero bits || 250-bit unclamped vk

We haven't yet decided whether we want to support separate formats for incoming, outgoing, and (both incoming and outgoing) viewing keys.

**Comment by bitcartel** [comment]
Also see Bitcoin Cash cashaddr format which was deployed a few days ago, a variant of bech32.

Spec: https://github.com/bitcoincashorg/spec/blob/master/cashaddr.md

**Comment by daira** [comment]
That document says:

> This format reuses the work done for Bech32 and is similar in some aspects, but improves on others.

but unhelpfully doesn't say how it "improves" on Bech32. I suggest we ignore it and just use Bech32 as deployed in Bitcoin Core.

**Comment by bitcartel** [comment]
https://github.com/zcash/zcash/issues/2893 says that Bech32 will not be used with Sapling transparent addresses. 
https://github.com/zcash/zcash/issues/3058 implies that Bech32 will be used in some capacity.

What's the latest on this?

**Comment by str4d** [comment]
Per section 5.6 of the Sapling protocol spec (2018.0-beta12), Bech32 will be used for all Sapling-specific key and address formats. That means Sapling z-keys, z-addrs, and viewing keys. t-addrs will not be Sapling-specific, so are unchanged.

**Comment by str4d** [comment]
Per above, this has been specified. Implementation is tracked in #3058.

**Comment by zookozcash** [comment]
> I assume that we want the diversifier to come before the group element to help vanity address generators? :)

Yikes! I'm sorry I didn't see this before. I consider vanity addresses to be a security risk because they increase the power of "address-phishing" or "address-partial-collision" attacks. By the way we've actually seen such attacks in _practice_ in the wild before, so this is not purely hypothetical on my part. So I would have strongly pushed for the opposite design: make the group element come first in order to hinder vanity address generators.

However, even if we did that and hindered vanity address generators, it wouldn't prevent them from being able to do their work, so while this design increases their power, which is dangerous, going the opposite way would not be able to eliminate their power entirely.

So:

1. It's too late to change this for Sapling.

2. Please, everyone, in the next round of design (Post-Sapling) think of this aspect of addresses — "mutability" and "partial-collidability" of addresses — as a real, and currently unsolved security issue.

**Comment by daira** [comment]
Personally I think that the problem @zookozcash mentions is not one that is solvable in terms of the address encoding (in particular, just putting the diversifier last would not be sufficient) and that it will be necessary to teach users to compare the whole address.
