### ISSUE TITLE
Replace "height in coinbase" with a field in the block header

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2539]
Encoding the height in the coinbase transaction is ugly and was only done to avoid changing the block header format. [Edit: not quite; see [below](https://github.com/zcash/zcash/issues/2539#issuecomment-346095464).] Hard fork ~~required~~ would be the simplest way of doing this.

**Comment by h4x3rotab** [comment]
My solution is to embed the block height inside the first 4bytes of `hashReserved`. Maybe this can be a soft fork if Zcash doesn't check the value of `hashReserved` in validation logic?

**Comment by daira** [comment]
Well, there's likely to be an opportunity to hard fork anyway (either HF0 or Sapling), and we'll need to at least change the block version number in order to make it a bilateral hard fork, so we could bundle this change. Zcash doesn't really have the same incentives to prefer soft forks as Bitcoin.

**Comment by daira** [comment]
Also, if we remove the enforcement of height in the coinbase transaction at the same time as enforcing it in the header, that would obviously require a hard fork.

**Comment by daira** [comment]
Note that [BIP 34 claims](https://github.com/bitcoin/bips/blob/master/bip-0034.mediawiki#Motivation) that a motivation for putting the height in each coinbase transaction is that all transactions will then have unique hashes. That is a desirable property, although there are other ways to achieve it.

**Comment by scravy** [comment]
[BIP 30 explains](https://github.com/bitcoin/bips/blob/master/bip-0030.mediawiki) problems with duplicate transactions. Having the height in the coinbase transaction is a very good way of making the coinbase's transaction unique.
@daira What "other ways to achieve it" do you see?

**Comment by daira** [comment]
We can no longer use `hashReserved` for this because it is now used for `hashFinalSaplingRoot`.
