### ISSUE TITLE
Style bug on https://z.cash: signup banner partially obscures × "close" icon

### ISSUE THREAD

**Issue by jasondavies** [zcash/zcash#2540]
Hopefully this is clear from the attached image below: the div#persistent-banner-message partially obscures the close icon, at least in terms of event handling, making it hard to click the icon.

Browser version: Chrome Version 59.0.3071.115 (Official Build) (64-bit) on macOS 10.12.5.

<img width="855" alt="screen shot 2017-07-16 at 19 21 06" src="https://user-images.githubusercontent.com/31223/28288635-c1d34328-6b37-11e7-89b3-907ae263162d.png">

**Comment by arcalinea** [comment]
Thank you! Very helpful bug report.
