### ISSUE TITLE
https://z.cash: JavaScript error in dev console

### ISSUE THREAD

**Issue by jasondavies** [zcash/zcash#2541]
This doesn't seem to affect anything as far as I can tell, but may be worth looking into anyway:

> Uncaught TypeError: document.URL.contains is not a function

<img width="660" alt="screen shot 2017-07-17 at 21 38 14" src="https://user-images.githubusercontent.com/31223/28288823-699a78ce-6b38-11e7-9d5a-c0d48d4994a7.png">

**Comment by arcalinea** [comment]
That was a bug temporarily introduced by a contractor we were working with, is fixed now. Thanks
