### ISSUE TITLE
Wrong total wallet balance

### ISSUE THREAD

**Issue by avelrl** [zcash/zcash#2544]
### Describe the issue
Wrong total wallet balance

### Can you reliably reproduce the issue?
No

### Expected behaviour
Send 0.0046 ZEC to the address t1TUHoEXbBB3jZi5Cau3Eojsz4DKPsWEoyd with fee 0.001, after that total balance not equal sum of addresses balance

### Actual behaviour + errors
```
{"jsonrpc": "1.0", "id":"curltest", "method": "z_gettotalbalance", "params": [0] }
{
    "result": {
        "transparent": "0.00170101",
        "private": "0.00",
        "total": "0.00170101"
    },
    "error": null,
    "id": "curltest"
}
```
```
{"jsonrpc": "1.0", "id":"curltest", "method": "getbalance", "params": ["",0] }

{
    "result": 0.00170101,
    "error": null,
    "id": "curltest"
}
```
```
{"jsonrpc": "1.0", "id":"curltest", "method": "listreceivedbyaddress", "params": [0, false] }

{
    "result": [
        {
            "address": "t1MkTt4eTjZbnkKSycZp7wWvLvDCnsFB1JW",
            "account": "",
            "amount": 0.0009,
            "confirmations": 215,
            "txids": [
                "695fc925bc073093550fb0e0a8dcd11c2bb937697d1ac8eab3ae434f8c90c911",
                "e2034021467be9abb2c0550ef53899d424fd4383df0404862b61c24de314b173"
            ]
        },
        {
            "address": "t1dBSuk9fQG7oosJFFnwNVp8vKPKCV5omPd",
            "account": "",
            "amount": 0.0055,
            "confirmations": 154,
            "txids": [
                "6a2e7cbf03470d662052eafb2218f5a4796de6fd17f7d8f82f79caa76686ff5f",
                "142366e3a8639cd7ebefc6478e2a4c191daa0dff24a0643972f33274ce7d8a85"
            ]
        }
    ],
    "error": null,
    "id": "curltest"
}
```
```
{"jsonrpc": "1.0", "id":"curltest", "method": "z_getbalance", "params": ["t1MkTt4eTjZbnkKSycZp7wWvLvDCnsFB1JW",0] }

{
    "result": 0.0009,
    "error": null,
    "id": "curltest"
}
```
```
{"jsonrpc": "1.0", "id":"curltest", "method": "z_getbalance", "params": ["t1dBSuk9fQG7oosJFFnwNVp8vKPKCV5omPd",0] }

{
    "result": 0.0006,
    "error": null,
    "id": "curltest"
}
```
### The version of Zcash you were using:
Zcash Daemon version v1.0.10-1

### Machine specs:
bash-3.2$ docker info
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 102
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.36-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: moby
ID: HKC3:EA3T:EKG2:JS7G:QSE5:FSTR:GFTV:2WI2:T4XL:CIU7:K2PO:OBP7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 48
 Goroutines: 58
 System Time: 2017-07-19T22:53:54.854817753Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

Darwin MacBook-Pro-Avel.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64

### Any extra information that might be useful in the debugging process.
2017-07-19 14:30:35 CommitTransaction:
CTransaction(hash=533ecab0c2, ver=1, vin.size=1, vout.size=2, nLockTime=151844)
    CTxIn(COutPoint(142366e3a8, 0), scriptSig=304402207f7f0596765d2921, nSequence=4294967294)
    CTxOut(nValue=0.00020101, scriptPubKey=OP_DUP OP_HASH160 fce8331786de)
    CTxOut(nValue=0.00460000, scriptPubKey=OP_DUP OP_HASH160 69487dabda14)
2017-07-19 14:30:35 keypool keep 6
2017-07-19 14:30:35 AddToWallet 533ecab0c2264fc7265f034b44cb3c6ea9f22c4193572ea2b73fc6776c12e9aa  new
2017-07-19 14:30:35 AddToWallet 533ecab0c2264fc7265f034b44cb3c6ea9f22c4193572ea2b73fc6776c12e9aa..
2017-07-19 14:30:35 Relaying wtx 533ecab0c2264fc7265f034b44cb3c6ea9f22c4193572ea2b73fc6776c12e9aa
...

update
first transaction https://explorer.zcha.in/transactions/533ecab0c2264fc7265f034b44cb3c6ea9f22c4193572ea2b73fc6776c12e9aa
second
https://explorer.zcha.in/transactions/2432b583d87952b51b14bddb13938cb9925c2209f517971467b2a28cb0737eb2
total balance 0.0002958 
balance 
t1dBSuk9fQG7oosJFFnwNVp8vKPKCV5omPd =0 
and 
t1MkTt4eTjZbnkKSycZp7wWvLvDCnsFB1JW = 0

**Comment by bitcartel** [comment]
Hi @avelrl , can you please tell us what the initial balance was, what you sent, what you expect the balance to be, and what it actually shows in your wallet?  Is there a difference between that figure and what you see in explorers?  Thanks.

**Comment by avelrl** [comment]
Hi @bitcartel .
Initial balance was 0.0049 ZEC
I sent  0.0046 ZEC and fee was 0.0003 (t1gvrTBm7kJDuGdpjRSfU5NZQXK3pP6zkC3 0.00020101 ZEC + 0.00009899 ZEC)
z_getbalance t1dBSuk9fQG7oosJFFnwNVp8vKPKCV5omPd return 0 ZEC balance, that's right, but z_gettotalbalance or getbalance return 0.00020101 ZEC
I expected to see total balance 0 ZEC

https://explorer.zcha.in/transactions/533ecab0c2264fc7265f034b44cb3c6ea9f22c4193572ea2b73fc6776c12e9aa

Best regards

**Comment by bitcartel** [comment]
@avelrl Any update?

I see that two outputs received funds. 

- t1gvrTBm7kJDuGdpjRSfU5NZQXK3pP6zkC3 received 0.00020101 ZEC
- t1TUHoEXbBB3jZi5Cau3Eojsz4DKPsWEoyd received 0.0046 ZEC

There was a transaction fee of 0.00009899 ZEC

The input of 0.0049 ZEC matches the total value of the outputs and fee (0.00020101 + 0.0046 + 0.00009899)

Why do you say the "fee was 0.0003" when it was in fact 0.00009899 ?

Does the address t1gvrTBm7kJDuGdpjRSfU5NZQXK3pP6zkC3 belong to you i.e. it's an address in your local wallet?  If so, the balance in that address of 0.00020101 ZEC would be returned via z_gettotalbalance and getbalance.

**Comment by ioptio** [comment]
Closing this due to lack of response. @avelrl feel free to reopen if you come back to this.
