### ISSUE TITLE
Get rid of GH wikis

### ISSUE THREAD

**Issue by ioptio** [zcash/zcash#2546]
Currently WIP

**Comment by daira** [comment]
:+1:

**Comment by garethtdavies** [comment]
Adding some generic comments here after spending some time going through these. First of all the format of these docs is very welcomed, and a vast improvement both in style but also in being in one place.

My first observation is that there are a few guides hidden away and the main (left-side) navigation could be drastically improved. The zcashd config guide, wallet backup guide and notably the mining guide are links buried inside the "User Guide" and not easy to find. These should be given prominence in the left-hand sidebar as you can assume some users will immediately want this information.

I appreciate how these docs were formed (from a disparate number of sources) and in some cases this shows itself in perhaps a slightly unintuitive manner of presenting the information. For example, the "Getting Started" should be _the_ pivotal document and stand on its own and not immediately jump to an upgrading guide. This document should be targetted at first-time users who are most likely concerned about the package installer or the binaries and should be offered a guide to install in the simplest manner and subsequently conduct their first transaction. Currently, the majority of this document is concerned with building from source and I think it is the build instructions that can be linked from the "Getting Started" guide and not the other way around. In such a "Getting Started" guide, I'd like to read a bit about the gitian builds to educate new users how they can verify what they are downloading.

There is still a huge chunk sitting outside of these docs namely all the stuff listed here: https://z.cash/support/zig.html. Is the intention to migrate all of this into the main docs too? I think at a minimum all of this extra stuff should be links in the main navigation.

**Comment by garethtdavies** [comment]
On reviewing some other projects the Decred docs are something that should be aspired to. I could have avoided writing the above and just linked to https://docs.decred.org/ :smiley:

**Comment by mdr0id** [comment]
@garethtdavies Thank you for your feedback. It is much appreciated! Many of the above items will be discussed in upcoming sprints.

We intend to migrate the majority of mentioned documentation soon. Preliminary work on several phase 1 tasks is nearing completion. Once these documents are migrated, we can fine-tune the flow and UX.

**Comment by ioptio** [comment]
Let's close this when we nuke/redirect the GH wiki pages

**Comment by ioptio** [comment]
We can't get rid of the pages explicitly due to browser caching and bookmarking so let's replace with links to new locations.

**Comment by ioptio** [comment]
We noticed that Github traffic analytics showed the wiki User guide as the 2nd most visited part of this repo behind zcash/zcash. Once that number drops (zcashcommunity.com was contributing to referrals but updated to point to RTDs) and the release process is properly moved, we can get rid of the wiki all together (after backing up/archiving).
