### ISSUE TITLE
Fix or remove estimate fee

### ISSUE THREAD

**Issue by ioptio** [zcash/zcash#2552]
### Describe the issue
`estimatefee` always returns -1

#### If so, please list the steps to reproduce below:
1. Try `estimatefee 1`
2. Try `estimatefee 10`
3. Try `estimatefee 100`

### Expected behaviour
An estimation of the approximate fee per kilobyte needed for a transaction to begin confirmation within nblocks blocks.

### Actual behaviour + errors
Always returns -1

### The version of Zcash you were using:
1.0.10-1

**Comment by ioptio** [comment]
Tried this after realizing that `sendtoaddress` doesn't use default fee which is described in #2551

**Comment by bitcartel** [comment]
If nobody relies on this rpc call, given that this is the first ticket about the issue, it could be a candidate for removal and simplifying the code base.

**Comment by bitcartel** [comment]
This doesn't always return -1, depends on the mempool.  When empty, the code path eventually returns -1.

**Comment by salisbury-espinosa** [comment]
> If nobody relies on this rpc call, given that this is the first ticket about the issue, it could be a candidate for removal and simplifying the code base.

```bash
curl -s -X POST -u ***:*** -H "Content-type: application/json" ***:8232  -d '{"method":"getrawmempool", "params":[true],"jsonrpc":"1.0"}'
```
response:
```
{"result":{"b1ec73e82df16c0f510df0d0f05e7e608d63ad29f1533255facfc557ea24e820":{"size":244,"fee":0.00000245,"time":1543942464,"height":440197,"startingpriority":17857136.90721649,"currentpriority":17857136.90721649,"depends":[]},"1b79c277964c68a586752716a624fe9e3a903bf739758b16c8a78208fb353b35":{"size":2119,"fee":0.00010000,"time":1543942493,"height":440197,"startingpriority":1e+16,"currentpriority":1e+16,"depends":[]},"3bb992d1bc622802b328015a4cc8f8779cab1b8192e3571b02353220d99feeee":{"size":1891,"fee":0.00010000,"time":1543942437,"height":440196,"startingpriority":1e+16,"currentpriority":1.0000000000225e+16,"depends":[]}},"error":null,"id":null}
````
---------------------------
```bash 
curl -s -X POST -u ***:*** -H "Content-type: application/json" ***:8232  -d '{"method":"estimatefee", "params":[1],"jsonrpc":"1.0"}'
```
response:
```
{"result":-1,"error":null,"id":null}
```

 `estimatefee` is not working @bitcartel @daira :(

**Comment by mms710** [comment]
Will prioritize https://github.com/zcash/zcash/issues/2942 instead and check back on this ticket when that one has been closed.

**Comment by daira** [comment]
`estimatefee` will be removed (#6591).
