### ISSUE TITLE
https://z.cash: CSS only allows first page to be printed

### ISSUE THREAD

**Issue by jasondavies** [zcash/zcash#2556]
As reported by [Alex Biryukov](https://twitter.com/alexcryptan/status/890605331499204608).

I believe this is due to the CSS rule `html, body { height: 100% }` in `_common.scss`.  Disabling this rule in Chrome dev tools seems to allow multi-page printing.

**Comment by jasondavies** [comment]
Reproduced in Chrome 60.0.3112.78 (macOS, 64-bit) and Firefox 55.0b12 (macOS, 64-bit).

**Comment by nuttycom** [comment]
No longer relevant.
