### ISSUE TITLE
[Sapling] Choose depth of Merkle tree over commitments

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2568]
We chose a Merkle tree depth of 29 for Sprout; the discussion of why is on #16 and (primarily) #994. This needs to be revisited for Sapling, even if we end up making the same decision.

In particular, there are a few considerations that are different for Sapling:

* @ebfull chose a depth of 29 in order to make the number of constraints for the Sprout circuit just under a power of two. This will need to be recalculated for Sapling (and if we use Groth16, it might have different performance discontinuities).
* The calculation of the maximum commitment creation rate will be different, in particular I think the worst case (relevant to denial of service)  will be a block packed with transactions consisting of many Mint operations, which have smaller descriptions.
* There could be more incentive to perform a denial-of-service attack on Zcash now than there was at launch (see @elibensasson and @defuse's argument [here](https://github.com/zcash/zcash/pull/994#issuecomment-224671113)), and the cost of performing such an attack would be lower, *especially* for Mints.
* Our plans on how to handle Merkle tree upgrades might have changed.

We won't know enough to make this decision until the rest of the circuit has been designed, so let's not bikeshed too much now.

**Comment by daira** [comment]
Groth16 apparently has the same power-of-2 discontinuities, if I understand correctly.

**Comment by daira** [comment]
We're not doing Mints, however we *are* doing separate Output descriptions per shielded output. This makes the proofs for outputs efficient enough that they would not be the bottleneck in a denial-of-service attack. The size of an Output description is 580 bytes. The transaction size overhead is a negligible proportion for maximum-size transactions.

The current proposal by @nathan-at-least is a depth of 32, which has been included in the current 2018.0-beta-15 spec. The spec ticket was https://github.com/zcash/zips/issues/143 and the implementation ticket is https://github.com/zcash-hackworks/sapling-crypto/issues/55 .

2 MB blocks can fit no more than 3448 Output descriptions. Therefore 2<sup>32</sup> commitments last a worst case of 1245640 blocks &ndash;5.9 years at the target block rate&ndash; if all blocks are full of Output descriptions. This would no longer be a worst case if we expanded block capacity without changing the circuit. 2<sup>29</sup> commitments would have been a worst case of 0.74 years.

**Comment by str4d** [comment]
Per the referenced spec PR above, the chosen depth is 32.
