### ISSUE TITLE
Add gitlab mirror of proving and verifying keys

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2569]
#1669  is about being unable to download the proving key due to network-specific issues (e.g. Great Firewall blocking).

For #2498, which is a similar ticket about downloading dependencies, @bitcartel added a [mirror of the dependencies on gitlab](https://gitlab.com/zcashcommunity/depends). This should also include the proving/verifying keys.

**Comment by ioptio** [comment]
This is complete https://gitlab.com/zcashcommunity/params
