### ISSUE TITLE
Add automated gitian builder which reacts to signed git tag.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#2571]
In the [current release process](https://github.com/zcash/zcash/blob/master/doc/release-process.md#make-and-deploy-deterministic-builds), after signing a tag, multiple engineers need to run deterministic builds, and we require two independent matching builds.

There's no loss of security if we add an automated gitian builder and require it to match the other two independent builds. This builder should be triggered automatically by noticing the git tag, and validating the signature **including ensuring the signature comes from a hard-coded public key hash**. (AFAIK, gpg will happily tell you something is validly signed without letting you restrict which public key you require for the signature, which can lead to keypair conflation attacks.)

**Comment by mms710** [comment]
This will be completed after we put the new CI system in place; this will be in the backlog until then.

**Comment by nuttycom** [comment]
@mdr0id Can this now be closed?

**Comment by mdr0id** [comment]
This can be closed now. It is done from a tag
