### ISSUE TITLE
Automatically generate a debian package as gitian side effect.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#2572]
When gitian completes one of the build artifacts should be the `.deb` package.

With #2571 in place, this means after the release coordinator signs a git tag, with no other human involvement an automated process will create a debian package.

This should not be signed with a key that end-users will accept (so that compromise of this automation doesn't allow backdooring our users). Instead, the release coordinator or a package engineer can then sign and publish that package on our apt repository.

**Comment by mms710** [comment]
This will be completed after we put the new CI system in place; this will be in the backlog until then.

**Comment by mms710** [comment]
This should generate a package for all Debian versions that we support.

**Comment by nuttycom** [comment]
@mdr0id Should this be transferred to the infrastructure repo?

**Comment by mdr0id** [comment]
This is blocked on the current signing process(as it is human dependent on air gaped rig), but we are working to update this to support the automation. We can close for now because other tickets have this as a north star
