### ISSUE TITLE
Ensure full build logs from gitian are committed to gitian.sigs for each contributor.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#2575]
Having full build logs available in the repo would be helpful for a variety of cases. One common one I imagine is a new gitian build operator comes along, and their build fails, and they want to see how their build log compares to existing build logs for the same release.

Another is that we discover after the fact some flaw, vuln, or bug in our release packages, even though gitian manifests matched, and we want to determine as much as possible about the actual build process for the package, including logs from all independent builders.

**Comment by mms710** [comment]
This will be completed after we put the new CI system in place; this will be in the backlog until then.

**Comment by nuttycom** [comment]
@mdr0id If this has been addressed, please close.
