### ISSUE TITLE
Shouldn't we check that the coin is spendable here?

### ISSUE THREAD

**Issue by arielgabizon** [zcash/zcash#2583]
https://github.com/zcash/zcash/blob/2a42478bff3e1298f73e0411eb6d69d83b89f6a0/src/wallet/asyncrpcoperation_sendmany.cpp#L805

i.e. that `out.fSpendable == true`
This should usually not be a problem,  unless the user would use a watch only address or something.

It came up for me cause I'm working on a version that doesn't require an input address

**Comment by bitcartel** [comment]
Yes, good spot, I think that check should be added.  It's present in SelectCoins in main.cpp to filter results after calling AvailableCoins.

**Comment by str4d** [comment]
@bitcartel has this been implemented anywhere?

**Comment by bitcartel** [comment]
@str4d Made PR #2583 for this in z_sendmany.  Already part of #2615 for z_shieldcoinbase.
