### ISSUE TITLE
The confirmation number of the transaction record is -1. What does it mean

### ISSUE THREAD

**Issue by liuxun1977** [zcash/zcash#2589]
The confirmation number of the transaction record is -1.

**Comment by daira** [comment]
This message doesn't appear in the zcashd source code, so it must be from some other software such as a wallet. What software were you using exactly?

At a guess, it might mean that the transaction hasn't been mined yet.

**Comment by ioptio** [comment]
Closing this due to lack of response from original user. Please reopen if the issue is still occurring.
