### ISSUE TITLE
Create a performance / reliability report for high-load users.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#2591]
Let's create a document internal to ZcashCo + invited devs which documents the performance or reliability problems of each of our high-load users. For each user we should link to one or more tickets which capture their issues.

The two purposes of this document are to ensure we're not dropping any problems some of these users have due to focusing only on other issues, and also to notice if we have any apparently conflicting reports that we should look into closer.

Let's also let each of those high-load users know we're doing this.

**Comment by str4d** [comment]
This has been done.
