### ISSUE TITLE
Looking for private key in "# Wallet dump created by Zcash"

### ISSUE THREAD

**Issue by RayLucchesi** [zcash/zcash#2592]
Newbie here, apologies if you see multiples of this issue or if this is the wrong place for the issue. 

I was using zcash4mac but it started crashing and never came back up (see issue: https://github.com/radix42/zcash4mac/issues/6).

Moved onto Jaxx for ZEC wallet support but would like to get ZECs from old wallet. 

I had a Wallet dump that created two files a "privatekeys" file and "zcashwallet" file. The zcashwallet file appears encrypted to me so of no use the privatekeys file does have a block at the end of it indicating # Zkeys followed by aline with looks like my private key and my Zaddr. 

Is the key before the Zaddr my private key?

Running Zcash v1.0.4-eb3e2e0, 
OSX 10.11.6

**Comment by nathan-at-least** [comment]
We are not yet clear on what caused your problem and need some more information:

- How did you create the backup files? Was it with the `zcash4mac` GUI or a `zcash-cli` terminal command?
- Why do you believe `zcashwallet` is encrypted? `zcashd` does not encrypt backup files, and we are not sure what `zcash4win` does. (Does @radix42 or @vaklinov happen to know about backup encryption here?)

**Comment by radix42** [comment]
We do not do any

**Comment by RayLucchesi** [comment]
Not sure if I am duplicating answers I already tried to send via iPhone but:

1) I used zCash4Mac gui to create the backups. 
2) I suspect the wallet was encrypted because when I look at it with a text editor (on Mac) most of the characters don’t display in anything that’s readable. Its quite possible its just binary data and not displayable ascii characters.

hope this clears up any misconceptions.

Regards,
Ray Lucchesi

**Comment by radix42** [comment]
the wallet.dat file is NOT a text file, it is a Berkeley DB database file,
which is a binary file format!

if you change it AT ALL with a text editor you will hopelessly corrupt it
and lose your funds....it is NOT encrypted, just not a text file

**Comment by ioptio** [comment]
Closing this issue due to lack of user response. If issue is still a problem, feel free to reopen this ticket.

**Comment by RayLucchesi** [comment]
I haven’t changed the wallet.dat file but I did copy it out to save it.  If its a berkleyDB is there some way I can dump the table/row entries in text…

Ray

**Comment by radix42** [comment]
it IS possible to dump it out @RayLucchesi  but I have not done it for a zcash wallet.dat before....it'd be messy......dropping the wallet.dat file into an installation of zcash on linux or win may be easier

Is it a lot of ZEC locked up in it?

**Comment by RayLucchesi** [comment]
Not a lot of zcash. I don’t have WIN but may be able to get linux running someplace. Let me take a look.

Ray

**Comment by radix42** [comment]
If you want me to try to pry it apart with command line tools to extract
your key(s), email me at radix42 at gmail dot com

It'd actually be a useful exercise to whip up a script to extract them, as
BerkeleyDB issues are....not uncommon

**Comment by radix42** [comment]
Not uncommon in the larger scheme of things that is, rather than with zcash specifically....this situation isn't common, but its not exactly rare either
