### ISSUE TITLE
Zcashd disable transactions verification

### ISSUE THREAD

**Issue by ellegance** [zcash/zcash#2603]
Hello ZCash community,

Can I launch zcashd without transactions verification, only to download new generated blocks?

Thanks in advance

**Comment by ioptio** [comment]
We're not aware of a way to do this. Are you looking for headers or full blocks? Bitcoin light clients work for headers but there doesn't exist any for Zcash, yet.

**Comment by ioptio** [comment]
This is likely not to be implemented so I'm closing this issue. Feel free to add more discussion.

**Comment by mrx23dot** [comment]
gen=0 doesnt seem to help

**Comment by daira** [comment]
Indeed, `gen=0` only turns off CPU mining, which is what is documented to do.

It's still the case that we don't support downloading blocks without verifying transactions.
