### ISSUE TITLE
getrawtransaction and gettransaction does not work.

### ISSUE THREAD

**Issue by martinpeterbauer** [zcash/zcash#2604]
Environment:  Ubuntu 16, zcashd version v1.0.11, Sync block height: 177823, mainnet

With zcash-cli and via RPC-Calls via java some requests work as expected, like getblockhash, getblock, getnewaddress, z_getnewaddress, getblockcount.s

But if i try to request getrawtransaction or gettransaction the server send to the RPC the message 

> "Server returned HTTP response code: 500 for URL: " 

and with the same data to zcash-cli, e.g.

> zcash-cli  -rpcuser=XXXXXXXXX -rpcpassword=XXXXXXXX getrawtransaction 8f84fa48dd106ed0e4d62053f3b0a2b4fdb749d0320c23411073ae177deffc49
> error code: -5
> error message:
> No information available about transaction

I tried some tx-ids .... some taken from the getblock (with blockid 33) which contain the transaction id 8f84fa48dd106ed0e4d62053f3b0a2b4fdb749d0320c23411073ae177deffc49 - verified in the zchain-explorer.

The java rpc will call:

> {"jsonrpc": "1.0", "id":"curltest", "method": "getblockhash", "params": [33] }

then put the result in the next request below ... 

> {"jsonrpc": "2.0", "id":"curltest", "method": "getblock", "params":["00024cbd2a722c0101cc3d22a81bb5cef26db2454f3b2899a53a7706acc11e30"] }

then put the result into the next request

> {"jsonrpc": "1.0", "id":"curltest", "method": "getrawtransaction", "params": ["8f84fa48dd106ed0e4d62053f3b0a2b4fdb749d0320c23411073ae177deffc49"]}

and the result is HTTP 500 state .... 

Any idea what is wrong ?

**Comment by radix42** [comment]
on the command line you have to be the txid in double quotes, like so:
![image](https://user-images.githubusercontent.com/6250192/30000203-e049fbbc-9017-11e7-8205-583367228d51.png)

**Comment by martinpeterbauer** [comment]
.... unfortunately this doesn't work for me .... 

Remark: i have tried with/without " and ' and prefix of 0x ...... no luck at all

**Comment by martinpeterbauer** [comment]
short update:   i deleted the .zcash folder, created conf file new ...... started the deamon .... let it sync afte 50 blocke .... and it sees the 'getrawtransaction' ......   strange ..... but it works right now ....

**Comment by martinpeterbauer** [comment]
Another test showed .... 

Problem at block [6591] TXid 77a09e54b32fb9d74b851a2f4ad62fec0fd160f2f40356c6025e61b8536cb51b   HTTP 500
Problem at block [6591] TXid c811951d1d1899f34a7801e015b07c58602ff186f09b0d19adc1681f8bfc1c6f   HTTP 500
OK      at block [6591] TXid 932ae9b16698c8144bfa92dcfed40acd20c187446a8abb2801dfaca651c07833
Problem at block [6591] TXid 28984525fe9cbf64b4c06c663881a9e26d93de171d20c3b00e891fed2dec89ec   HTTP 500
OK      at block [6591] TXid 9770b9ae5992dba9d99624a1d565facb67cd9f9eeb857c5d6544bd1630c580f5
Problem at block [6591] TXid 9b99d47d02099f5a260014360276b6365a4bdd54f778d8603db8b4420b62ec59   HTTP 500
Problem at block [6592] TXid 648fcc8c3468322d7a30b5f2f92bfebe68998a4bf55b7429ca6e8ae735064b9d   HTTP 500
OK      at block [6592] TXid bebc023280872f2a05ca20510605ddcd0b05a77d15c46eb8a8b8667a34585129
Problem at block [6592] TXid ff858076a2fd20e051e506003b44eec6243ab2d019ee593fcedb952d14403ba0   HTTP 500
Problem at block [6593] TXid f60ab35a5941b680662164a7a975600ac44c9b0f0a7e73e5f439974c9de3c37d   HTTP 500
OK      at block [6593] TXid 101e2975ff522b2c2710f997d8ddb13894a37368b349c9b853a1a5f8ebfd0688
OK      at block [6593] TXid c80e4819235863e208dc21ac535b3c0ff83d80418d7b9b423576fe4b3f707497
OK      at block [6593] TXid a693dabfbbd3650c13da3f57888dc68a053a3ab062b6783a2466d1b76bd65c13
OK      at block [6593] TXid 022d3abaf058f2955561cdfd620b2d5d231a5f3ea88647e2c99d20436e2e98fc
OK      at block [6593] TXid ce0352315f3d8bb83c211c95de8e8a353f57419d49204be763680e882d29db33
Problem at block [6594] TXid 9be7d8281deb94b7a4c28fa69e1672ef8ab1abc47de5e5f9cb1c0575bc85e811   HTTP 500
OK      at block [6594] TXid a4f37f41fd499d29404d6834bda1d98b46525adb4968f5e2a3e9426d0c538971
Problem at block [6594] TXid 74ba2bc6f1ae7bfea2e4f0f80b965234b541536fbb9fe014820ed1df121ba6c3   HTTP 500
Problem at block [6594] TXid 4b943cc7e909d0369e529a402c56d3ba2ebad487394bd769cdcd17aed4396100   HTTP 500
Problem at block [6594] TXid 3bea7d3e684096e08d5fd2c736fe3dec0d623378d498d177fb586150c47335ed   HTTP 500
OK      at block [6594] TXid c20a778ee6cb4617f9dcb9c45057200e1bc773f1cc4c672bf39ebc358d24e1f8
Problem at block [6594] TXid 8df7d7aacdc3aeb72403421c51a9af24a7f0df412c717e8d13af1a7ca93ec4b8   HTTP 500
Problem at block [6595] TXid 0bfe14dea820216fc35e17b99b4ba287f8c1b75fe661ddc6ccc370dcca95f950   HTTP 500

**Comment by str4d** [comment]
`gettransaction` looks for transaction data in your wallet, so that will fail to find information about any transaction that does not involve one of your addresses.

`getrawtransaction` returns more generic transaction data from the block chain itself. However, by default the only places it can get data from are the wallet and the mempool; if a txid is not in either of these places, it will return the JSON-RPC error "No information available about transaction", as you saw when you tried with `zcash-cli`. To get data about any transaction, you need to index the block chain first, by adding `txindex=1` to your `zcash.conf` and then reindexing.

**Comment by martinpeterbauer** [comment]
Thank you for this answer......

Another question regarding your answer:  

If i just want to check my wallet transactions - i can scan all transactions like i did and if i encounter any error - like the HTTP 500 - i can skip that becuase it won't brother me ...

**Comment by str4d** [comment]
If you want to just check your own wallet transactions, look at `zcash-cli help` under the wallet section for methods like `listtransactions`, `listunspent` etc.

**Comment by martinpeterbauer** [comment]
Thank you. I'll close this ticket because now (after reindexing) it works like a charm.
