### ISSUE TITLE
Port zcash-fetch-params to rust

### ISSUE THREAD

**Issue by kpcyrd** [zcash/zcash#2607]
I'm creating a seperate issue to follow up on the discussion with @str4d from #2597:

>> Since zcash seems to be into rust, is there interest to have those scripts translated? I can see why shell might be preferable, but I could offer porting them if you give me some instructions on how you would like to have it integrated into the repo. (I'd prefer to handle this in a followup pull request though).
>
> Interesting idea. Are you envisaging that we build a binary for downloading parameters instead of using a script? It would certainly be more portable, and it would also be a self-contained chunk of code which would make integration easier. We are still figuring out how exactly we will integrate Rust into Zcash, but a separate binary like this would likely be done in a different way to rewriting or extending internal zcashd code. You should open an issue for discussing this!

This is basically what I'm suggesting. :)

From the top of my head, I can think of the following:
- Add it to librustzcash and export a function that can be called from zcashd with C++
- `cargo init` a small project in a subfolder, compile it during the build and install the binary as `zcash-fetch-params`. If the build system changes to cargo, this can be moved to `src/bin/` and cargo is going to build it as one of the resulting binaries.

**Comment by bitcartel** [comment]
I think some users prefer to have human readable scripts for set-up/install actions such as downloading data from the Internet and saving to local disk.  Bash and Python are pretty much universal and easy to read and verify.

Also, librustzcash is currently focused on being an interface for zcashd C++ to call into Rust crypto related functions.  It's not yet a general purpose API for calling components written in Rust, and one day if we need that, we might use a separate library to keep things modular.

**Comment by daira** [comment]
This would be mostly obviated by #3933 / #6661. For the remaining optional use of `sprout-groth16.params` there is not sufficient justification to implement this issue.
