### ISSUE TITLE
cost 6s to run z_getbalance

### ISSUE THREAD

**Issue by ucwong** [zcash/zcash#2612]
![image](https://user-images.githubusercontent.com/22344498/30416681-ba078a2c-995f-11e7-9989-1152d40afcaf.png)
![image](https://user-images.githubusercontent.com/22344498/30416692-c6760702-995f-11e7-999e-b54118218c7d.png)

The latest version of zcashd

**Comment by gotope** [comment]
I don't understand use z_get*  to get a t-address?

**Comment by ucwong** [comment]
@gotope it is the method of zcash rpc to get a t address balance

**Comment by ucwong** [comment]
![image](https://user-images.githubusercontent.com/22344498/30423780-7c63f64e-9976-11e7-8996-3ce159fc2fcd.png)

**Comment by gotope** [comment]
I'm used to  list in group:
zcash-cli listaddressgroupings 

## and test the z_getbalance in version v1.0.11
 $ time zcash-cli z_getbalance   t1Ko 
real	0m0.116s
user	0m0.000s
sys	0m0.004s

**Comment by ucwong** [comment]
@gotope I think it will be slower when there are too many addresses in one wallet

I have generated 3000+ addresses in one wallet. 

I am afraid it will be slower and slower.

**Comment by daira** [comment]
Related to #1294 and #2156.

**Comment by str4d** [comment]
@ucwong could you post the output of the following:

- The `txcount` value from `zcash-cli getwalletinfo`
- `zcash-cli listunspent | grep "{" | wc -l`
- `zcash-cli getaddressesbyaccount "" | grep "\"" | wc -l`
- The lines in `debug.log` just after start that look like this:

```
2017-09-19 08:59:51 Keys: 107 plaintext, 0 encrypted, 107 w/ metadata, 107 total
2017-09-19 08:59:51 ZKeys: 1 plaintext, 0 encrypted, 1 w/metadata, 1 total
2017-09-19 08:59:51  wallet                   15ms
```

**Comment by ucwong** [comment]
@str4d 
zcash-cli getwalletinfo
txn count 23361
./zcash-cli listunspent | grep "{" | wc -l
3243
zcash-cli getaddressesbyaccount "" | grep "\"" | wc -l
2341

**Comment by str4d** [comment]
`z_getbalance` has been deprecated, and will be removed in #6326.
