### ISSUE TITLE
Compilation on linux fails due to invalid libsnark download.

### ISSUE THREAD

**Issue by xanvincent** [zcash/zcash#2614]
### Describe the issue
Failing to compile zcash from source on linux (openSUSE or Ubuntu)

**this same error is affecting zcash, zclassic, and zen**

### Can you reliably reproduce the issue?
Yes
#### If so, please list the steps to reproduce below:
1.  Run ./zcutil/build.sh -j4
2. Boost, etc, builds normally
3. Fails when trying to download libsnark

### Expected behaviour
Makefile should point to a file that exists.

### Actual behaviour + errors
`Fetching libsnark...
https://z.cash/depends-sources/libsnark-3854b20c25e8bc567aab2b558dec84d45f4a3e73.tar.gz:
2017-09-13 22:10:33 ERROR 404: Not Found.
2017-09-13 22:10:34 URL:https://codeload.github.com/z-classic/libsnark/tar.gz/3854b20c25e8bc567aab2b558dec84d45f4a3e73 [144924] -> "/home/crypto/daemons/zcash/depends/work/download/libsnark-/libsnark-3854b20c25e8bc567aab2b558dec84d45f4a3e73.tar.gz.temp" [1]
/home/crypto/daemons/zcash/depends/work/download/libsnark-/libsnark-3854b20c25e8bc567aab2b558dec84d45f4a3e73.tar.gz.temp: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
funcs.mk:238: recipe for target '/home/crypto/daemons/zcash/depends/sources/download-stamps/.stamp_fetched-libsnark-libsnark-3854b20c25e8bc567aab2b558dec84d45f4a3e73.tar.gz.hash' failed
make: *** [/home/crypto/daemons/zcash/depends/sources/download-stamps/.stamp_fetched-libsnark-libsnark-3854b20c25e8bc567aab2b558dec84d45f4a3e73.tar.gz.hash] Error 1
make: Leaving directory '/home/crypto/daemons/zcash/depends'

crypto@crypto1:~/daemons/zcash> git pull

Already up-to-date.`

Makefile tries to download **https://z.cash/depends-sources/libsnark-3854b20c25e8bc567aab2b558dec84d45f4a3e73.tar.gz** but the file doesn't exist. Which file should it point to instead?

### The version of Zcash you were using:
Doesn't compile

### Machine specs:
- OS name + version: OpenSUSE LEAP 42.2
- CPU: Intel(R) Xeon(R) CPU E3-1240 V2 @ 3.40GHz
- RAM: 8G
- Disk size: 80G
- Disk Type (HD/SDD): SSD
- Linux kernel version (uname -a): 4.4.79-18.26-default
- Compiler version (gcc -version): gcc version 6.2.1 20160826

**Comment by csmk** [comment]
That commit `3854b20c25e8bc567aab2b558dec84d45f4a3e73` seems to has never existed in the first place. The latest commit should be [`9ada3f84ab484c57b2247c2f41091fd6a0916573`](https://github.com/zcash/zcash/blob/master/depends/packages/libsnark.mk).

**Comment by daira** [comment]
Zclassic have fixed their issue (https://github.com/z-classic/zclassic/issues/103), and so have Zencash (https://github.com/ZencashOfficial/zen/issues/62). Closing since I've seen no reports of this affecting Zcash. Please reopen if you confirm the contrary.
