### ISSUE TITLE
Debian build out of date now?

### ISSUE THREAD

**Issue by reppolice** [zcash/zcash#2619]
Hi,

I haven't used my debian binary for a few weeks, upon starting it yesterday on Ubuntu 16.04 it wasn't syncing for an hour or two, I built it from git and the new binary started syncing immediately. Coincidence or is the debian binary in a bad place right now?

**Comment by daira** [comment]
Is there anything in ``.zcash/debug.log`` that seems relevant to the lack of syncing?

We're not aware of anything wrong with the Debian binary. Could it have been a network problem?

**Comment by ioptio** [comment]
Closing this issue due to lack of response. Feel free to re-open if this is still an issue.
