### ISSUE TITLE
Ensure that transparent input UTXOs are locked by z_sendmany

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2621]
``z_shieldcoinbase`` (#2615) does this; check that ``z_sendmany`` does so as well.

**Comment by bitcartel** [comment]
I was about to file a ticket for this. z_sendmany does not do this currently, but we should do so.  It does require changing the internal API so probably not enough time for the 1.0.12 RC.

**Comment by mms710** [comment]
Note that this relates to https://github.com/zcash/zcash/issues/1277

**Comment by nuttycom** [comment]
Related to #5568
