### ISSUE TITLE
New install error

### ISSUE THREAD

**Issue by sunsetblues** [zcash/zcash#2622]
### Describe the issue
Installing zcash getting this error:

sudo apt-get update && sudo apt-get install zcash
Ign:1 http://deb.debian.org/debian stretch InRelease
Hit:2 http://deb.debian.org/debian stretch-updates InRelease
Err:2 http://deb.debian.org/debian stretch-updates InRelease                           
  Splitting up /var/lib/apt/lists/deb.debian.org_debian_dists_stretch-updates_InRelease into data and signature failed
Get:3 http://security.debian.org/debian-security stretch/updates InRelease [62.9 kB]   
Hit:4 http://deb.debian.org/debian stretch Release        
Err:5 http://deb.debian.org/debian stretch Release.gpg        
  At least one invalid signature was encountered.
Err:3 http://security.debian.org/debian-security stretch/updates InRelease
  Splitting up /var/lib/apt/lists/partial/security.debian.org_debian-security_dists_stretch_updates_InRelease into data and signature failed
Ign:6 https://apt.z.cash jessie InRelease
Hit:7 https://apt.z.cash jessie Release
Err:8 https://apt.z.cash jessie Release.gpg
  At least one invalid signature was encountered.
Fetched 62.9 kB in 0s (174 kB/s)
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://deb.debian.org/debian stretch-updates InRelease: Splitting up /var/lib/apt/lists/deb.debian.org_debian_dists_stretch-updates_InRelease into data and signature failed
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://deb.debian.org/debian stretch Release: At least one invalid signature was encountered.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://security.debian.org/debian-security stretch/updates InRelease: Splitting up /var/lib/apt/lists/partial/security.debian.org_debian-security_dists_stretch_updates_InRelease into data and signature failed
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://apt.z.cash jessie Release: At least one invalid signature was encountered.
W: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/InRelease  Splitting up /var/lib/apt/lists/partial/security.debian.org_debian-security_dists_stretch_updates_InRelease into data and signature failed
W: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/InRelease  Splitting up /var/lib/apt/lists/deb.debian.org_debian_dists_stretch-updates_InRelease into data and signature failed
W: Failed to fetch http://deb.debian.org/debian/dists/stretch/Release.gpg  At least one invalid signature was encountered.
W: Failed to fetch https://apt.z.cash/dists/jessie/Release.gpg  At least one invalid signature was encountered.
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
zcash is already the newest version (1.0.11).
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.

----------------------------------------------------------------------------------------
When running command: ./zcutil/build.sh --disable-rust -j$(nproc) Get this after a while:

collect2: error: ld returned 1 exit status
Makefile:2294: recipe for target 'zcashd' failed
make[2]: *** [zcashd] Error 1
make[2]: *** Waiting for unfinished jobs....
collect2: error: ld returned 1 exit status
Makefile:2196: recipe for target 'test/test_bitcoin' failed
make[2]: *** [test/test_bitcoin] Error 1
make[2]: Leaving directory '/root/zcash/src'
Makefile:5298: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/zcash/src'
Makefile:623: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by daira** [comment]
It appears that there's some problem with the state of your apt configuration that is independent of Zcash, since there are errors from apt sources other than https://apt.z.cash/ . If you remove the https://apt.z.cash/ source, does ``sudo apt-get update`` still report errors or warnings?

The log from ``build.sh`` is not complete enough to diagnose. Can you upload the full log somewhere, please? We at least need the lines just before "collect2: error: ld returned 1 exit status".

**Comment by ioptio** [comment]
Closing this issue due to lack of response. Feel free to re-open and comment on your problem if this is still an issue.
