### ISSUE TITLE
Unconfirmed Transaction

### ISSUE THREAD

**Issue by walison33** [zcash/zcash#2624]
Olá, estou tendo problema com uma transação está dando UNCONFIRMED TRANSACTION!
(google translate) Hello!, there I'm having problem with a transaction
o tx é ff4be354a1188a8871a044ac372f5d9403b50b10fa05be7925e85c1e8e0d50b9
,

amount | -1.69924809
-- | --
confirmations | 0
details[0].account | ""
details[0].address | "t1dJhjPpk9wTvrEJVJUX7yFyiKmg5PgoCgY"
details[0].amount | -1.69924809
details[0].category | "send"
details[0].fee | -0.00010000
details[0].size | 22169
details[0].vout | 0
fee | -0.00010000
hex | 
time | 1506015053
timereceived | 1506015053
txid | ff4be354a1188a8871a044ac372f5d9403b50b10fa05be7925e85c1e8e0d50b9

**Comment by bitcartel** [comment]
Tx was confirmed in block 188650
https://explorer.zcha.in/transactions/ff4be354a1188a8871a044ac372f5d9403b50b10fa05be7925e85c1e8e0d50b9

**Comment by Karlmaster2k3** [comment]
Hello Guys,

i got a big problem.

I send from cryptonator 6.x ZEC to my hardware ledger wallet, after 30Hours its dont confirmed in my wallet.

<a href="https://www.pic-upload.de/view-34115934/zec2.jpg.html" target="_blank"><img src="https://www2.pic-upload.de/thumb/34115934/zec2.jpg" title="Bilder oder Fotos hochladen"></a>

Transaction ID : 821810a34670614f645e8775337da8b6a952642369308df8bdc27178e7455730

<a href="https://www.pic-upload.de" target="_blank"><img src="https://www2.pic-upload.de/img/34115932/LEDGER.jpg" title="Bilder oder Fotos hochladen"></a>

Yesterday i found the transaction id there:
https://zcashnetwork.info/tx/821810a34670614f645e8775337da8b6a952642369308df8bdc27178e7455730
At this morning, the transaction id wasnt found with that link/id.
Now 8Hours later, i see the transaction id at that link, but with a other date and time. 

<a href="https://www.pic-upload.de" target="_blank"><img src="https://www2.pic-upload.de/img/34115933/PM.jpg" title="Bilder oder Fotos hochladen"></a>

Normaly the transactions need max 10-15 Minutes.

I send 3 Zec from my hardware ledger wallet to a exchange and there is too not confirmed near 24 Hours.

Fee is on 0.0001 ZEC

Can me explain some one, what i have to do, or whats going on here?

I opened a ticket today on cryptonator, but i think they dont can do something.

I am mining self ZEC, can i mine my transaction self?

Umpf, i am confused.

Thats my wallet address
https://zcashnetwork.info/address/t1JQ2YxhbKpd8npsSKwyuMiYH7WT6SECAUG

I know, it gives much more peoples like me, if you see the unconfirmed transactions
https://minergate.com/blockchain/zec/transpool

Best Regards
Karlmaster

**Comment by Stephen2929** [comment]
I have a similar small transaction from 3 nov (20 days ago) that shows the (S) at the end that hasnt come through
What does (S) mean ?
