### ISSUE TITLE
Build fails and occur this infomation:funcs.mk:242: recipe for target '/root/zcash/depends/sources/download-stamps/.stamp_fetched-boost-boost_1_62_0.tar.bz2.hash' failed

### ISSUE THREAD

**Issue by imjunwei** [zcash/zcash#2626]
### Describe the issue
I had install all the dependencies，but can not finish the ./zcutil/build.sh, it show a fail below:

Fetching boost...
Unable to establish SSL connection.
funcs.mk:242: recipe for target '/root/zcash/depends/sources/download-stamps/.stamp_fetched-boost-boost_1_62_0.tar.bz2.hash' failed
make: *** [/root/zcash/depends/sources/download-stamps/.stamp_fetched-boost-boost_1_62_0.tar.bz2.hash] Error 4
make: Leaving directory '/root/zcash/depends'

### Actual behaviour + errors
make: Entering directory '/root/zcash/depends'
mkdir -p /root/zcash/depends/sources/download-stamps /root/zcash/depends/sources
rm -f /root/zcash/depends/sources/download-stamps/.stamp_fetched-boost-boost_1_62_0.tar.bz2.hash
touch /root/zcash/depends/sources/download-stamps/.stamp_fetched-boost-boost_1_62_0.tar.bz2.hash
cd /root/zcash/depends/sources/download-stamps; (test -f /root/zcash/depends/sources/boost_1_62_0.tar.bz2 || ( mkdir -p /root/zcash/depends/work/download/boost-1_62_0 && echo Fetching boost... && ( wget --timeout=10 --tries=3 -nv -O "/root/zcash/depends/work/download/boost-1_62_0/boost_1_62_0.tar.bz2.temp" "https://z.cash/depends-sources/boost_1_62_0.tar.bz2" || wget --timeout=10 --tries=3 -nv -O "/root/zcash/depends/work/download/boost-1_62_0/boost_1_62_0.tar.bz2.temp" "http://sourceforge.net/projects/boost/files/boost/1.62.0/boost_1_62_0.tar.bz2" ) && echo "36c96b0f6155c98404091d8ceb48319a28279ca0333fba1ad8611eb90afb2ca0  /root/zcash/depends/work/download/boost-1_62_0/boost_1_62_0.tar.bz2.temp" > /root/zcash/depends/work/download/boost-1_62_0/.boost_1_62_0.tar.bz2.hash && sha256sum -c /root/zcash/depends/work/download/boost-1_62_0/.boost_1_62_0.tar.bz2.hash && mv /root/zcash/depends/work/download/boost-1_62_0/boost_1_62_0.tar.bz2.temp /root/zcash/depends/sources/boost_1_62_0.tar.bz2 && rm -rf /root/zcash/depends/work/download/boost-1_62_0 ))
Fetching boost...
Unable to establish SSL connection.
funcs.mk:242: recipe for target '/root/zcash/depends/sources/download-stamps/.stamp_fetched-boost-boost_1_62_0.tar.bz2.hash' failed
make: *** [/root/zcash/depends/sources/download-stamps/.stamp_fetched-boost-boost_1_62_0.tar.bz2.hash] Error 4
make: Leaving directory '/root/zcash/depends'

### Machine specs:
- OS name + version: Ubuntu LTS 16.04
- CPU: AMD 1700x
- RAM: 8G
- Disk size: 20GB
- Disk Type (HD/SDD): HD
- Linux kernel version (uname -a): Linux 4.4.0-87-generic #110-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
- Compiler version (gcc -version):gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

### Any extra information that might be useful in the debugging process.
did not complete the install yet ,so the debug.log didn't show in ./zcash/debug.log

### The infomations for dependencies i had install
root@junwei:~/zcash# sudo apt-get install       build-essential pkg-config libc6-dev m4 g++-multilib       autoconf libtool ncurses-dev unzip git python python-zmq       zlib1g-dev wget bsdmainutils automake
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libncurses5-dev' instead of 'ncurses-dev'
autoconf is already the newest version (2.69-9).
automake is already the newest version (1:1.15-4ubuntu1).
bsdmainutils is already the newest version (9.0.6ubuntu3).
build-essential is already the newest version (12.1ubuntu2).
g++-multilib is already the newest version (4:5.3.1-1ubuntu1).
libncurses5-dev is already the newest version (6.0+20160213-1ubuntu1).
libtool is already the newest version (2.4.6-0.1).
m4 is already the newest version (1.4.17-5).
pkg-config is already the newest version (0.29.1-0ubuntu1).
python is already the newest version (2.7.11-1).
unzip is already the newest version (6.0-20ubuntu1).
python-zmq is already the newest version (15.2.0-0ubuntu4).
git is already the newest version (1:2.7.4-0ubuntu1.2).
libc6-dev is already the newest version (2.23-0ubuntu9).
wget is already the newest version (1.17.1-1ubuntu1.2).
zlib1g-dev is already the newest version (1:1.2.8.dfsg-2ubuntu4.1).

### Do you have a back up of `~/.zcash` directory and/or take a VM snapshot?
yes ,but i dont now how to sent you the snapshot

**Comment by daira** [comment]
Downloading https://z.cash/depends-sources/boost_1_62_0.tar.bz2 works for me and it has the correct hash, so this could be a temporary networking or connection problem. Does ``wget --timeout=10 --tries=3 -nv "https://z.cash/depends-sources/boost_1_62_0.tar.bz2"`` work outside the build process?

I notice you're building as root which is not recommended. (You can't build as root and then run as a non-root user due to permissions problems, and we do not advise running zcashd as root for security reasons.) It shouldn't cause the error above though.

**Comment by ioptio** [comment]
Closing this issue due to lack of user response. If issue is still a problem, feel free to reopen this ticket.

**Comment by daira** [comment]
We removed the SourceForge URL for boost in #3123.
