### ISSUE TITLE
Mining rewards issue?

### ISSUE THREAD

**Issue by marcofortina** [zcash/zcash#2628]
Hello there,
may be I have a problem on the mining rewards. My zcashd is running on my laptop since 1 days, 17 hours, 38 minutes but my wallet is still completely empty. I know my poor perfromance but it's stange that on nothing is moving on:

This is the console of zcashd:

------------------------------- cut here ---------------------------
Thank you for running a Zcash node!
You're helping to strengthen the network and contributing to a social good :)

In order to ensure you are adequately protecting your privacy when using Zcash,
please see <https://z.cash/support/security/index.html>.

           Block height | 190186
            Connections | 8
  Network solution rate | 327979537 Sol/s
    Local solution rate | 5.1392 Sol/s

You are mining with the tromp solver on 4 threads.

Since starting this node 1 days, 17 hours, 39 minutes, 31 seconds ago:
- You have validated 578945 transactions!
- You have completed 409829 Equihash solver runs.
------------------------------- cut here ---------------------------

And this is the output of zcash-cli getwalletinfo:

------------------------------- cut here ---------------------------
{
  "walletversion": 60000,
  "balance": 0.00000000,
  "unconfirmed_balance": 0.00000000,
  "immature_balance": 0.00000000,
  "txcount": 0,
  "keypoololdest": 1505950290,
  "keypoolsize": 101,
  "paytxfee": 0.00000000
}
------------------------------- cut here ---------------------------

zcash-cli getblockchaininfo:

------------------------------- cut here ---------------------------
{
  "chain": "main",
  "blocks": 190188,
  "headers": 190188,
  "bestblockhash": "0000000003129e32e8fc753347e8e50b76c26fe6a98f0fe5f362d96fba4c20e2",
  "difficulty": 6297467.750451759,
  "verificationprogress": 0.9999985941101929,
  "chainwork": "000000000000000000000000000000000000000000000000000b7980bd0efa5b",
  "pruned": false,
  "commitments": 557512,
  "softforks": [
    {
      "id": "bip34",
      "version": 2,
      "enforce": {
        "status": true,
        "found": 4000,
        "required": 750,
        "window": 4000
      },
      "reject": {
        "status": true,
        "found": 4000,
        "required": 950,
        "window": 4000
      }
    },
    {
      "id": "bip66",
      "version": 3,
      "enforce": {
        "status": true,
        "found": 4000,
        "required": 750,
        "window": 4000
      },
      "reject": {
        "status": true,
        "found": 4000,
        "required": 950,
        "window": 4000
      }
    },
    {
      "id": "bip65",
      "version": 4,
      "enforce": {
        "status": true,
        "found": 4000,
        "required": 750,
        "window": 4000
      },
      "reject": {
        "status": true,
        "found": 4000,
        "required": 950,
        "window": 4000
      }
    }
  ]
}
------------------------------- cut here ---------------------------

zcash-cli getinfo:

------------------------------- cut here ---------------------------
{
  "version": 1001150,
  "protocolversion": 170002,
  "walletversion": 60000,
  "balance": 0.00000000,
  "blocks": 190188,
  "timeoffset": -1,
  "connections": 8,
  "proxy": "",
  "difficulty": 6357599.777523521,
  "testnet": false,
  "keypoololdest": 1505950290,
  "keypoolsize": 101,
  "paytxfee": 0.00000000,
  "relayfee": 0.00000100,
  "errors": ""
}
------------------------------- cut here ---------------------------

zcash-cli getmininginfo:

------------------------------- cut here ---------------------------
{
  "blocks": 190189,
  "currentblocksize": 153996,
  "currentblocktx": 6,
  "difficulty": 6157483.661383335,
  "errors": "",
  "genproclimit": -1,
  "localsolps": 5.138557301607358,
  "networksolps": 333409776,
  "networkhashps": 333409776,
  "pooledtx": 7,
  "testnet": false,
  "chain": "main",
  "generate": true
}
------------------------------- cut here ---------------------------

Could someone help me?

Thanks,
Marco

**Comment by ioptio** [comment]
@marcofortina Are you trying to solo-mine or are you part of a pool? It is very unlikely that you will see a block reward from solo mining without a significant amount of GPU.

**Comment by ioptio** [comment]
I'm closing this issue due to lack of response. Feel free to reopen if you'd like.
