### ISSUE TITLE
[Sapling] Choose CRH used to derive ivk and nr

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2630]
(Split from #2234 and #2277.)

We need a one-way, collision-resistant hash that can be efficiently verified in the Sapling circuit, for [CRH<sup>ivk</sup> and CRH<sup>ρ</sup>](https://github.com/zcash/zcash/issues/2277#issuecomment-331748455). [Edit: in the most recent circuit design we need PRF<sup>nr</sup> instead of the latter.] The Pedersen hash construction in #2234 is only designed to be collision-resistant and not necessarily one-way, so I'm not sure it is sufficient. On the other hand, something that reuses the optimization effort spent on the Pedersen hash would be nice.

A collision-resistant PRF would suffice; however we need to be careful because the standard definition of a PRF does not imply collision resistance, and therefore algebraic PRF constructions proposed in the literature might not have that property.

Note that we do not need "hashing into the curve" (i.e. constructing points with unknown discrete logs) here, because ivk and ρ [edit: or nr] are scalars, not points or point coordinates. So, using BLAKE2s for GH wouldn't imply that we need to use it for CRH<sup>ivk</sup> or CRH<sup>ρ</sup>. BLAKE2s would certainly work, but it is expensive: about 26390 constraints according to @ebfull in https://github.com/zcash/zcash/issues/705#issuecomment-181088770 .

**Comment by daira** [comment]
On the other hand, it would be fine to use BLAKE2s for the prototype and replace it with something more efficient later.

**Comment by ebfull** [comment]
My vague memory was that BLAKE2s was closer to 20000 constraints after I had done further optimizations, which contradicts that comment. I should re-investigate.

**Comment by daira** [comment]
I see how to do BLAKE2s in 20736 constraints (256 for each G evaluation, so 10 \* 8 \* 256 constraints for all of the G evaluations and then 8 \* 32 for the output XORs).

**Comment by daira** [comment]
The implementations of XOR and addition end up being nicely self-contained.

To implement 32-bit addition, i.e. (a + b) mod 2<sup>32</sup> = c, boolean-constrain the 32 output bits and then constrain a + b - c to be either 0 or 2<sup>32</sup>:

    (∑<sub>i ∈ {0..31}</sub> (a<sub>i</sub> + b<sub>i</sub> - c<sub>i</sub>).2<sup>i</sup>) × (2<sup>32</sup> - ∑<sub>i ∈ {0..31}</sub> (a<sub>i</sub> + b<sub>i</sub> - c<sub>i</sub>).2<sup>i</sup>) = 0

This works similarly for (a + b + m<sub>j</sub>) mod 2<sup>32</sup> = c.

Each bit of a 32-bit XOR, i.e. a XOR b = c, can be implemented as:

    (a) × (b) = (a + b - c)

which boolean-constrains c for free.

Rotations are free, so that's all there is to it besides wiring everything up correctly.

**Comment by daira** [comment]
Note that the XORs with the initial chaining variable at the end of block processing are free in the case where only one block is processed.

**Comment by khovratovich** [comment]
If Pedersen is not one-way, then it is probably not collision-resistant as two found preimages would constitute a collision. Should it be PRF rather than one-way? Depending on what the key is in Pedersen, I can believe it is not a PRF.

**Comment by daira** [comment]
That argument isn't correct because it could be the case that only one preimage is feasible to find for a given output.

In any case, I was too vague in saying "one-way function". See  https://eprint.iacr.org/2010/022 : for keyed hashes, Coll implies eSec and (with some security loss) Pre, but does not imply aSec, aPre or ePre. We seem to need at least aPre and Coll. None of these properties imply that the keyed hash is a PRF.

Note that contrary to what I thought when I opened this ticket, we do seem to need a PRF to derive ρ (see https://github.com/zcash/zcash/issues/2277#issuecomment-334971413 ). We'll probably end up using BLAKE2s for that.

**Comment by daira** [comment]
I looked briefly (well, it would have been briefly if the Skein spec were less confusing) at the circuit performance of Skein-256 and Skein-512. TL;DR: awful.

Skein is an ARX construction like BLAKE2, but using 64-bit words (for both the Skein-256 and Skein-512 variants). A 64-bit addition costs 65 constraints, a 64-bit XOR costs 64 constraints, and rotations are free. As in BLAKE2, there seems little scope for optimization beyond the obvious and straightforward implementation, due to the alternation of XOR and addition.

For Skein-512, the UBI function (effectively a compression function) has 8 \* 72 Mix operations each requiring 1 addition and 1 XOR; 8 \* 19 subkey additions; 8 XORs and 3 additions for the key schedule; and 8 XORs for the message feed-forward. This gives a total cost per UBI of 8 \* 72 \* (65 + 64) + 8 \* 19 \* 65 + 8 \* 64 + 3 \* 65 + 8 \* 64 = 85403 constraints.

For Skein-256, the UBI function has 4 \* 72 Mix operations each requiring 1 addition and 1 XOR; 4 \* 19 subkey additions; 4 XORs and 3 additions for the key schedule, and 4 XORs for the message feed-forward. This gives a total cost per UBI of 4 \* 72 \* (65 + 64) + 4 \* 19 \* 65 + 4 \* 64 + 3 \* 65 + 4 \* 64 = 42799 constraints. However note that it isn't possible to construct a 512 → 256-bit hash from a single 256 → 256-bit UBI function.

If we were using the full hashing mode, for a 512 → 256-bit hash, Skein-512 would require 2 UBIs and Skein-256 would require 3 UBIs. We could get away with just using a single UBI for truncated Skein-512 (and there's a slight saving on the last round and feed-forward), but the need to do so is a clear disadvantage relative to BLAKE2 which has no overhead for the full hash.

So, even if I were wrong about the scope for optimization by a factor of 3, Skein would still perform poorly compared to BLAKE2.

The high cost is explained by Skein just having far more bit operations than BLAKE2[s,b] for the same input and output sizes. It gets away with this in terms of software performance because 64-bit addition and XOR are fast in software. However, we get no benefit from this approach in a circuit implementation (this is the same reason [Skein is inefficient in hardware](https://ehash.iaik.tugraz.at/wiki/SHA-3_Hardware_Implementations#High-Speed_Implementations_.28ASIC.29)).

**Comment by khovratovich** [comment]
A full Skein is clearly an overkill. As it is slower than Blake2, it inevitably requires a bigger circuit.

**Comment by daira** [comment]
Keccak/SHA-3 is apparently efficient in hardware, so we might hope that it is also circuit-efficient. Let's see. (Spoiler: no, not even close.)

SHA-3 is constructed from a permutation Keccak-p[1600, 24] in a sponge mode. This has parameters w=64, b=1600, and n<sub>r</sub>=24.

The costs of the step mappings are:
* θ: 50 \* w
* ρ: free
* π: free
* χ: 50 \* w
* ι: free

θ, ρ, and π are straightforward. χ requires two constraints for each A' = A XOR ((1 - B) AND C) operation. ι is free because the XORs are with constants, and so any bit flips can be substituted into subsequent uses of those bits.

So, a round requires 100 \* w = 6400 constraints. In general, Keccak-p[b, n<sub>r</sub>] requires 4 \* b \* n<sub>r</sub> constraints (because w = b/25). SHA-3 uses Keccak-p[1600, 24] which takes a whopping 153600 constraints. For SHA3-256, we use Keccak[512](padded message, 256). So the block size is 512 bits (comparable to BLAKE2s), and we use the Keccak permutation twice for the full hash with a single input block, for a hair-raising total of 307200 constraints.

Even if we reduce the number of rounds to 12 as proposed for [KangarooTwelve](https://keccak.team/kangarootwelve.html), and also cheat by using the truncated Keccak permutation directly (which could be argued to be secure for a single block, but might still raise eyebrows), it's still 76800 constraints which is far too expensive &mdash; 3.65 times as many constraints as BLAKE2s.

Notice that the only XOR-nonlinear operations are the ANDs in the χ mapping. There may be some scope for optimising consecutive XORs; I'm not sure. However, it seems very unlikely that such optimizations could overcome the cost disadvantage relative to BLAKE2s.

(I'm not quite sure how Keccak manages to be as fast in hardware as is claimed. Perhaps I've missed something, but I don't think so; it seems to have a huge number of bit operations.)

**Comment by daira** [comment]
@khovratovich : Remember that we don't only need a secure hash; we need to convince people that we have a secure hash (for the particular usage). Reducing the number of rounds is a hard sell, and would inevitably lead to accusations that we'd compromised on security, even if the reduction can be justified cryptographically. Also note that the main point of doing this cost analysis is to exclude candidates. We can now definitively exclude Skein and Keccak/SHA-3 in comparison to BLAKE2s.

If we're going to fiddle with numbers of rounds, then I'd much rather increase the number of rounds of MiMC than reduce the number of rounds of Skein, Keccak or BLAKE2. MiMC, in the [LongsightF-322/p/3](https://github.com/zcash/zcash/issues/2233#issuecomment-292807839) variant, requires only 644 constraints! That's 32.7 times cheaper than BLAKE2s; we could multiply the number of rounds by 10 and still be cheaper.

**Comment by daira** [comment]
Also note that the our performance goals for Sapling are already met by using BLAKE2s for CRH<sup>vk</sup>, PRF<sup>ρ</sup> and GH, and by using Pedersen hashes and commitments elsewhere, which are uncontroversial choices from a security point of view.

The remaining question for this ticket is whether we can do even better by choosing different primitives.

We're working in a setting with unusual-enough performance characteristics that it *might* be worth using an algebraic PRF even though those aren't normally considered efficient in the usual setting. However, it isn't worth it if doing so would significantly affect our ability to argue for the security of that choice.

**Comment by daira** [comment]
More detail on why we can't just use the Pedersen hash here. Suppose for example that we know the output X of a Pedersen hash for message M, but we do not know M. If the hash behaved pseudorandomly or as a random oracle, we'd expect that it would not be possible to find some simple relation between M and another message M' such that the hash of M' can be computed from X. But in fact this is possible for a Pedersen hash, for example:

* if M is obtained by flipping the negation bits in each window of M, the resulting hash is −X.
* if M is found by changing only the bits in a single known 4-bit window relative to M, then there are only 33 possibilities for the resulting hash as a function of X (that is, { X + k . g<sub>i</sub> for k ∈ {-16..16} }).

So we cannot analyse a Pedersen hash as a random oracle, which would make it quite complicated to prove security of the protocol if it were used for CRH<sup>vk</sup> or PRF<sup>ρ</sup> or GH.

**Comment by khovratovich** [comment]
Do you have a formal definition of what Pedersen hash would be? Would the underlying prime field be the same for all tree levels or different? The answer is not evident.

**Comment by khovratovich** [comment]
@daira I do not suggest using an insecure hash as is, I rather suggest using something more constraint-efficient than the Merkle tree. I think one do not need full hash functions in the nodes of a collision-resistant hash function with logarithmic commitment witnesses, like we do not need such for PMAC or GCM.

**Comment by daira** [comment]
@khovratovich wrote:
> Do you have a formal definition of what Pedersen hash would be?

https://github.com/zcash/zcash/issues/2234#issuecomment-334121434 , but with 4-bit windows.

> Would the underlying prime field be the same for all tree levels or different?

The same, since that's critical to performance. (It must be the scalar field of the BLS12-381 curve used for the zk-SNARK.)

> I do not suggest using an insecure hash as is, I rather suggest using something more constraint-efficient than the Merkle tree. I think one do not need full hash functions in the nodes of a collision-resistant hash function with logarithmic commitment witnesses, like we do not need such for PMAC or GCM.

That sounds interesting (although it might be too late for Sapling), but we should discuss it on #2258.

**Comment by daira** [comment]
We currently have no more efficient candidate that meets the security requirements (collision-resistant, one-way, established history of cryptanalysis, sufficient block and output sizes) than BLAKE2s.

**Comment by daira** [comment]
We'll truncate the BLAKE2s output to 250 bits and assume that is collision-resistant. BLAKE2s has an output length parameter but it's specified in bytes, and we don't want to discard 2 extra bits (reducing security against Pollard kangaroo attacks against vk by a factor of 2) unnecessarily.

**Comment by daira** [comment]
The BLAKE2s personalisation for CRH<sup>vk</sup> will be "Zcash_vk", and the personalisation for PRF<sup>ρ</sup> (it needs to be a collision-resistant PRF) will be "Zcashrho".

**Comment by daira** [comment]
The blinding of ask by nr is very similar to the scheme in https://www-users.cs.umn.edu/~hopper/basic-proof.pdf . However, I don't see in that paper where the range of the hash function H<sub>e</sub>, which roughly corresponds to PRF<sup>nr</sup>, is specified. It seems as though the proof assumes it to be 2b bits (like H<sub>r</sub> and H<sub>m</sub>), without saying so explicitly. b is 255 in the case of Ed25519.

**Comment by daira** [comment]
This is done. We're no longer using nr; we have a PRF<sup>nfSapling</sup>, instantiated by BLAKE2s, which directly outputs the nullifier (much like in Sprout, except that it is keyed by nk rather than a<sub>sk</sub>). CRH<sup>ivk</sup> is also instantiated by BLAKE2s.
