### ISSUE TITLE
[Sapling] Specify hashing into the group (GH)

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2635]
GH may be used for several purposes, depending on other design decisions:
* address diversification (#570);
* [generalized value commitments](https://github.com/zcash/zcash/issues/2277#issuecomment-321106819) for User-Issued Tokens (#830);
* to choose generators for the Pedersen hashes (#2234) and commitments (#2634);

It's convenient for GH to have a tag input and a counter input; the former would be a byte string and the latter an integer. It need not be a total function, some inputs (probably half) may fail to hash to the group.

**Comment by daira** [comment]
It is essential that GH produces outputs with unknown discrete log. An obvious way to do this is to use a conservative "bit-twiddling" hash unrelated to the curve arithmetic, such as BLAKE2s. See #2630 for discussion of the circuit cost of BLAKE2s. However, note that even a small number of instances of GH might end up being a substantial part of the total circuit cost: if, say, BLAKE2s costs 20000 constraints and a Pedersen hash 2360 constraints, then just two instances of GH inside the circuit &ndash;which is sufficient for diversified addresses and UIT&ndash; already cost 58% of the cost of the whole Merkle tree (of depth 29 as in Sprout).

**Comment by daira** [comment]
I suggest the following algorithm, which is designed to also be circuit-efficient:

* let F<sub>q</sub> the BLS12-381 scalar field
* let C be a 4-byte little-endian encoding of the counter input
* let D be the byte string consisting of ASCII "ZcashGH" followed by a 1-byte domain separator
* let U be a byte string that rigidly and verifiably depends on some future event I could not have known when specifying this algorithm, and that has at least 64 bits of entropy that cannot be easily influenced
* let T be the tag input
* let Y = BLAKE2s<sub>D</sub>(U || C || T)
* interpret Y as a 256-bit integer y0 in little-endian byte order
* let s = y0 mod 2 and y1 = floor(y0 / 2)
* if y1 ≥ q then return ⊥
* perform three [y-coordinate-only doublings](https://github.com/zcash/zcash/issues/2277#issuecomment-330046533) of y1, giving y
* find an x-coordinate x such that (x, y) is an affine point on the curve and x mod 2 = s
* return (x, y)

The three doublings ensure that (x, y) is on the prime-order subgroup with cofactor 8.

**Comment by ebfull** [comment]
> let F<sub>q</sub> the BLS12-381 scalar field

You mean r (also later in the comment.)

> let C be a 4-byte little-endian encoding of the counter input

I prefer big-endian here (it's simple inside of circuits, and for consistency)

> interpret Y as a 256-bit integer y0 in little-endian byte order

I would prefer to interpret it in big-endian (since it's what we currently have code for doing)

> let s = y0 mod 2 and y1 = floor(y0 / 2)

I would prefer to mask the most significant bit away and use that for s, so that we don't need to do bitshifting outside the circuit.

> and that has at least 64 bits of entropy that cannot

bytes*

**Comment by daira** [comment]
@ebfull wrote:
> @daira wrote:
> > let F<sub>q</sub> the BLS12-381 scalar field
> 
> You mean r (also later in the comment.)

ACK.

> > let C be a 4-byte little-endian encoding of the counter input
> 
> I prefer big-endian here (it's simple inside of circuits, and for consistency)

We use little-endian almost everywhere else in Zcash, except for the IEEE Std 1363-inspired point formats and for the packing/unpacking of the Equihash solution.

> > interpret Y as a 256-bit integer y0 in little-endian byte order
> 
> I would prefer to interpret it in big-endian (since it's what we currently have code for doing)

This might make sense as big-endian for consistency with the point formats though.

(If we were designing from scratch, I would much prefer big-endian everywhere. Protocols that do that tend to be consistent in ordering, whereas nominally little-endian protocols tend to end up as a mishmash. But we started with Bitcoin, which is mostly &ndash;but not entirely big-endian&ndash; so the mishmash was probably inevitable.)

> > let s = y0 mod 2 and y1 = floor(y0 / 2)
> 
> I would prefer to mask the most significant bit away and use that for s, so that we don't need to do bitshifting outside the circuit.

Okay.

> > and that has at least 64 bits of entropy that cannot
> 
> bytes*

That was intentional: 64 bytes so that U takes up a BLAKE2s block and has no overhead in the circuit (since the intermediate chaining variable is fixed), and at least 64 bits of entropy. The latter is sufficient to ensure the resulting points can't feasibly be from up anyone's sleeve.

**Comment by ebfull** [comment]
Sounds good.

> We use little-endian almost everywhere else in Zcash, except for the IEEE Std 1363-inspired point formats and for the packing/unpacking of the Equihash solution.

Eh, I still advocate for big-endian here. I think we're already inconsistent enough with the rest of Zcash that we don't win much being little endian here. We *gain* code/circuit clarity if anything.

**Comment by daira** [comment]
As noted in https://github.com/zcash/zcash/issues/2277#issuecomment-346165540 , we need GH to product a point on the Montgomery-form Jubjub curve. (Actually we need twisted Edwards points for the Pedersen generators and Montgomery points for the key agreement. So it would be possible to define GH as producing a twisted Edwards point and then map to a Montgomery one where necessary. However, the converse is better because it simplifies the circuit, which must be able to verify the GH used for the key agreement; we care more about avoiding complexity inside the circuit than outside.)

**Comment by daira** [comment]
Here's a proposed algorithm that produces a Montgomery point, makes @ebfull's suggested changes, and drops the counter argument (because we can always format T to include a counter where necessary):

* let F<sub>r</sub> be the BLS12-381 scalar field
* let D be the byte string consisting of ASCII "ZcashGH" followed by a 9-byte domain separator
* let U be a 64-byte string that rigidly and verifiably depends on some future event I could not have known when specifying this algorithm, and that has at least 64 bits of entropy that cannot be easily influenced. (For prototyping, use 64 zero bytes.)
* let T be the tag input
* let H = BLAKE2s<sub>D</sub>(U || T)
* interpret H as a bit string with the bits in each byte from ordered from MSB to LSB. Let s be the first bit and x0 the integer corresponding to the remaining bits in big-endian order.
* if x0 ≥ r then return ⊥
* find a y-coordinate y0 such that (x0, y0) is an affine point on the curve and y0 mod 2 = s. If there is no solution for y0, return ⊥
* perform three [affine Montgomery doublings](https://github.com/zcash/zcash/issues/2234#issuecomment-348243024) of (x0,
y0), giving (x, y). Before each doubling assert that the y-coordinate y' is non-zero using the constraint (y') × (z) = 1 for fresh z.
* return (x, y).

The three doublings ensure that (x, y) is on the prime-order subgroup with cofactor 8.

Note that unlike the previous algorithm, this doesn't depend on doubling points that night not be on the curve.

**Comment by daira** [comment]
I wrote:
> Before each doubling assert that the y-coordinate y' is non-zero using the constraint (y') × (z) = 1 for fresh z.

This requires 3 inversions to compute the witness. We can reduce it to one inversion: in order to prove that y0, y1 and y2 are all non-zero, let y' = y0 × y1 × y2, and prove that y' is non-zero using the constraint (y') × (z) = 1 for fresh z.

**Comment by daira** [comment]
The circuit cost of GH is the sum of the costs of:
* BLAKE2s ([21136 constraints](https://github.com/zcash/zcash/issues/2630#issuecomment-336887601))
* constraining x0 < r ([102 constraints](https://github.com/zcash/zcash/issues/2234#issuecomment-338985293), plus another 255 constraints if we don't merge the output boolean constraints of BLAKE2s with the comparison)
* constraining y0 < r (102 + 255 constraints)
* checking the curve equation y0<sup>2</sup> = x0<sup>3</sup> + 40962.x0<sup>2</sup> + x0 (3 constraints)
* (no cost for checking y0 mod 2 = s, because we can merge the variables for the low bit of y0 and for s)
* three affine Montgomery doublings ([12 constraints](https://github.com/zcash/zcash/issues/2234#issuecomment-348243024))
* three non-zero checks ([3 constraints](https://github.com/zcash/zcash/issues/2635#issuecomment-351902556)).

So that is 21136 + 102 + 102 + 255 + 3 + 12 + 3 = 21613 constraints (plus another 255 if we don't merge the output boolean constraints of BLAKE2s with the x0 comparison).

**Comment by daira** [comment]
I worked out how to avoid requiring GH to be implemented in the circuit (for diversified addresses). I still want it to be reasonably circuit-efficient in case that doesn't work out or we need it later for user-issued tokens, for example.

**Comment by daira** [comment]
We decided that the circuit would be specified only in terms of the Edwards curve, not the Montgomery curve. So GH needs to be modified as follows:

* let F<sub>r</sub> be the BLS12-381 scalar field
* let D be the byte string consisting of ASCII "ZcashGH" followed by a 9-byte domain separator
* let U be a 64-byte string that rigidly and verifiably depends on some future event I could not have known when specifying this algorithm, and that has at least 64 bits of entropy that cannot be easily influenced. (For prototyping, use 64 zero bytes.)
* let T be the tag input
* let H = BLAKE2s<sub>D</sub>(U || T)
* interpret H as an encoding of a compressed Edwards point (using the same format as EdDSA). Decompress this representation to (u0, v0), returning ⊥ if v ≥ r or the point is not on the curve.
* perform three [affine Edwards doublings](https://github.com/zcash/zcash/issues/2230#issuecomment-361097292) of (u0, v0), giving (x, y). In each doubling, if C<sup>2</sup> = 1 then return ⊥. (To assert that w is non-zero in the circuit, use the constraint (w) × (z) = 1 for fresh z.)
* return (u, v).

The three doublings ensure that (u, v) is in the prime-order subgroup with cofactor 8.

Note that unlike the previous algorithm, this doesn't depend on doubling points that might not be on the curve.

**Comment by daira** [comment]
This was done in 2018.0-beta-9 (section 5.4.8.5). It's not necessary to check whether u is 0 on each doubling.

U is still to be decided.
