### ISSUE TITLE
Delay in transaction confirmation

### ISSUE THREAD

**Issue by ivanmkt** [zcash/zcash#2643]
I sent a greater than 1.4 Zcash with a fee of 0.0004 Zec, has been several hours and still appears as "UNCONFIRMED TRANSACTION" [on the zcashnetwork.info explorer].

Is there any solution to recover my Zcash?

https://zcashnetwork.info/tx/4441eb991b68eede336f5db49400739d9efbb091bc57d4eb8778825dcc8cac41

**Comment by daira** [comment]
There's a spike in the size of the mempool (which holds unmined transactions on each node) at the moment, so transactions may take a bit longer to be mined. There doesn't appear to be anything wrong with the transaction, it will be mined eventually.

**Comment by dmistr** [comment]
Hello. How much time can it take? I encountered the same problem when sending 3.52 zсash - it's been more than 13 hours, and the transaction has not yet been confirmed.
txid 02b960437839c151cb718717c7e0153c37cdec7c71b8b427448c1126cee869ec

**Comment by krausedj** [comment]
Is it correct that transactions are built from enough inputs on the blockchain to generate a high enough total output.  So even sending from 1 to 1 address, may require hundreds of inputs, and be a very large transaction?  This appears to be the case looking at the mempool.

**Comment by daira** [comment]
That's correct; however, the transactions with many inputs currently in the mempool happen to be generated with custom code that is intentionally adding inputs that would not otherwise be needed for the transaction itself. My understanding is that they are generated by an exchange that currently has a very large UTXO set and needs to clear it.

**Comment by ivanmkt** [comment]
has not yet been confirmed and my balance in zcash4win remains the same since the shipment.
is there any way to retrieve what I have sent?


amount | -1.43040000
-- | --
confirmations | 0
details[0].account | ""
details[0].address | "t1fN6LES5tvUZhDqhcEqVZweGYy7Q6MsBYR"
details[0].amount | -1.43000000
details[0].category | "send"
details[0].fee | -0.00040000
details[0].size | 20467
details[0].vout | 0
details[1].account | ""
details[1].address | "t1P4yFTvfSRYsWZhDxe81UT3UUHVNYuEzjR"
details[1].amount | -0.00040000
details[1].category | "send"
details[1].fee | -0.00040000
details[1].size | 20467
details[1].vout | 1
fee | -0.00040000
time | 1506541925
timereceived | 1506541925
txid | "4441eb991b68eede336f5db49400739d9efbb091bc57d4eb8778825dcc8cac41"

**Comment by ioptio** [comment]
@ivanmkt did this transaction go through?

**Comment by dmistr** [comment]
Yes, it's okay

2017-10-02 20:16 GMT+03:00 Paige Peterson <notifications@github.com>:
