### ISSUE TITLE
Add a listunspent benchmark

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#2645]
Per a user report: they have moved from using `sendtoaddress` to manually creating transactions for efficiency, and `listunspent` is now their bottleneck. We should benchmark that independently of `sendtoaddress` - the former will be a component of the latter's performance, so by tracking both we should be able to get better insight into performance improvements.

**Comment by ioptio** [comment]
@str4d is there a user the user support team can do follow-up with for this issue once 1.0.13 is out?
