### ISSUE TITLE
Transactions are stuck in the mempool

### ISSUE THREAD

**Issue by tax79** [zcash/zcash#2646]
Hello.
My two transactions are stuck in the mempool for more than 30 hours.
They are not seen at http://zcashnetwork.info, but present as pending deposits at https://bittrex.com:
https://i.imgur.com/nauDjas.png

```
$ zcash-cli getrawmempool true
{
  "e1f7b36d154a4b82dfcb9e98e0a76f0cee2b4d861d6f549355f104c9af710b01": {
    "size": 70560,
    "fee": 0.00010000,
    "time": 1506679839,
    "height": 193038,
    "startingpriority": 159985575626.6125,
    "currentpriority": 160323631508.0125,
    "depends": [
    ]
  }
```

  

```
 "22fc8a8f2882e1bf5ee4a48a008441eab6103feba8cee7618882a1a7b42967b8": {
    "size": 26183,
    "fee": 0.00010000,
    "time": 1506679844,
    "height": 193038,
    "startingpriority": 45232356891.39744,
    "currentpriority": 45371596743.6282,
    "depends": [
    ]
  }
```

**Comment by tax79** [comment]
After running "zcashd -reindex" I get none of these transactions in the mempool.
But when I run just "zcashd" I get these transactions in the mempool.

**Comment by tax79** [comment]
Ok. I deleted all files in .zcash directory except wallet.dat and zcash.conf and ran "zcashd". After 7 hours downloading of blocks it seems problem solved. None of these transactions in the mempool. And the wallet balance is as it was before transactions.

**Comment by arcalinea** [comment]
If the transactions were pending for a long time in the mempool, it could have been related to the increase in tx volume a few days ago where some took a long time to confirm. But if your balance never changed, perhaps you did not actually send the transactions? Did these end up going through?

**Comment by tax79** [comment]
My balance changed locally and Bittrex saw these transactions but they had no confirmations. 
Only after doing several manipulations as I mentioned earlier I got my tokens back and could send them to Bittrex again.

**Comment by ioptio** [comment]
The original issue looks resolved so I'll close this. If we implement #2482 then the user would have been able to resolve this easier.

**Comment by ioptio** [comment]
#1963, #1062, #1063, #1059 are also relevant
