### ISSUE TITLE
I mined a block,but it looks the block  has disappeared

### ISSUE THREAD

**Issue by past2017** [zcash/zcash#2653]
### Describe the issue
I mined a block 196303, but I cannot find it in explorer.zcha.in
![image](https://user-images.githubusercontent.com/25541244/31217524-d51a4b5c-a9e9-11e7-96eb-1d4ba6218c78.png)

My coinbase address is t1c8sptRzXA96FAHT4L7mgbRZ44TSxfVvdQ
Balance is listed in my local wallet
![image](https://user-images.githubusercontent.com/25541244/31217998-7a88e0de-a9eb-11e7-8dd3-da60d069d690.png)

But when I use z_sendmany to transfer this balance to one z address ,there is one error in wallet log 
`07:23:44 opid-aee316bd-7903-42bb-8866-dfc4cf05cb8b: z_sendmany finished (status=failed, error=general exception: std::bad_alloc)`

### The version of Zcash I am using:
Zcash Daemon version v1.0.12

**Comment by daira** [comment]
The ``std::bad_alloc`` error suggests insufficient memory; how much memory do you have on this machine/VM?

**Comment by daira** [comment]
Zcha.in sometimes misses blocks. Block 196303 is visible in other block explorers though:
* https://minergate.com/blockchain/zec/block/196303
* http://zcashnetwork.info/block/000000000d9dfcb6e4c06577de2d667d24ca01c7df8d1812531c4f6f645547ea

**Comment by past2017** [comment]
@daria My memory
![image](https://user-images.githubusercontent.com/25541244/31231615-f0f3d868-aa19-11e7-9130-749aa90cd4dd.png)

**Comment by past2017** [comment]
@daira it looks zcashd eat so much money, and i restart zcashd, so payment is executed normally
So thanks very much, this issue will be closed, thanks again
