### ISSUE TITLE
Building libsnark : missing files

### ISSUE THREAD

**Issue by nyue** [zcash/zcash#2655]
### Describe the issue
To build zcash, I need to build libsnark.
libsnark Makefile refers to missing gadgetlib2 files

make: *** No rule to make target `src/gadgetlib2/examples/tutorial.cpp', needed by `src/gadgetlib2/examples/tutorial.o'.  Stop.

There is no issue tab for libsnark so I cannot lodge an issue specifically there.

Cheers

**Comment by radix42** [comment]
The zcash build script and the depends system build it with the correct
options, run zcutil/build.sh

**Comment by ioptio** [comment]
@nyue does the suggestion above help you so we can close this ticket?

**Comment by nyue** [comment]
I was hoping to learn about the various parts that goes into zcash by building each of them independently.

I am now using zcutil/build.sh to build

Yes you can close the ticket.
