### ISSUE TITLE
zcash4win no balance despite multiple transactions

### ISSUE THREAD

**Issue by AbsolutePower** [zcash/zcash#2656]
Hi, I synchronized the blockchain to 100% hours ago, still the balance in the GUI shows 0. I received multiple transactions by my mining pool on my t-address and see them in the zchain explorer. Starting the GUI with or without the daemon (tested 0 and 1 in the config file) didn't help.

OS: Windows 10. 
Using v1.0.11 of the zcash4win wallet software.

Could you help me please?

Btw: I'm new to mining and Zcash.

**Comment by radix42** [comment]
The taddr is in the addresses tab in the GUI?

**Comment by AbsolutePower** [comment]
Hi radix42, that seems to be the problem. I'm running the wallet on 2 different computers (mining at home and in my parents house) and at home the taddr is only available in the "Address book", but I didn't find a way yet to move it to the "own addresses" tab, despite me having imported my private key. On my parents' place I need to check if the sync worked to 100% and the balances are displayed at least there.

Still there must be a way to use the wallet on several computers, isn't there? Can you tell me, how I can move/import my taddr to the "own adresses" tab? I don't see any option on how to do that.

Thank you very much!

**Comment by radix42** [comment]
If you copy the entire wallet.dat file (while it is stopped!) From one
machine to the other, it should pick up all the addresses, otherwise you
need to export/import them one at a time. So copy from the machine with the
missing ones

**Comment by AbsolutePower** [comment]
Replacing the wallet.dat file didn't work. Removing the blockchain files and rechronizing the blockchain didn't work either. I still see the old addresses in the GUI. D

id you mean to replace all .dat files one by one, not "just" the wallet.dat file?

**Comment by daira** [comment]
@radix42 what do you suggest as a next step?

**Comment by AbsolutePower** [comment]
Hi, I replaced by now ALL files in all zcash4win related folders via copy pasting from an USB stick so that I'll have the same wallet files present on my 2nd computer. Finally a balance appears: BUT according to ZChain explorer the balance is incorrect on both computers: The wallet shows about 0.01 more ZEC, than ZChain. 

How's this possible and how can I trust the wallet long term if it gives me wrong numbers?

Thanks for your assistance/advice, guys!

**Comment by daira** [comment]
It's entirely possible that Zchain is wrong. Try also with a different block explorer such as https://minergate.com/blockchain/zec/blocks

**Comment by radix42** [comment]
there's also the explorer I run at https://www.zcashnetwork.info

**Comment by AbsolutePower** [comment]
Thanks. Minergate doesn't even find the taddr. But zcashnetwork shows the same balance as the zcash4win wallet. So should I trust zcashnetwork then over the other 2 explorer sites? Struggling a bit to understand how they could show different balances.

Anyway, closing this, since my wallet seems to work on both computers now and the balance issue is resolved as well now.

Thanks for all your support!

**Comment by daira** [comment]
Zchain is known to sometimes miss blocks under conditions of high load (when blocks are large / have many transactions, and therefore take longer to verify). An explorer that misses blocks cannot always compute balances correctly; it will not take into account transactions in those blocks.

I'm less familiar with minergate so I don't know whether it's subject to the same problem.
