### ISSUE TITLE
z_exportwallet does not list all transactions

### ISSUE THREAD

**Issue by gman77** [zcash/zcash#2657]
### Describe the issue
upgraded to 1.0.12 z_exportwallet does not list all transactions.
Balance is correct when using z_gettotalbalance however
when using z_export to get full list not all are there.

#### If so, please list the steps to reproduce below:
1. run z_exportwallet and investigate transactions not all listed after Sept24

### Expected behaviour
All transactions in human readable form should show

### Actual behaviour + errors
No error

### The version of Zcash you were using:
1.0.12

### Machine specs:
- Linux 
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):
- Linux kernel version (uname -a): 4.10.0-35-generic
- Compiler version (gcc -version): 5.4.0 20160609

**Comment by ioptio** [comment]
@gman77 the `z_exportwallet` function does not list transactions, just the private keys of associated addresses owned by the wallet.

Please explain if you mean something else or if you misinterpreted the function of the call so we can close this ticket. Thanks!

**Comment by gman77** [comment]
Hi @ioptio , 
I reduced the size by removing the others but it shows the following:
I thought the detail lines were the transactions. If this is normal I can go ahead and close.

# Wallet dump created by Zcash v1.0.12 (2017-09-28 01:29:24 -0700)
# * Created on 2017-10-08T21:53:55Z
# * Best block at time of backup was 198473 (000000000cc4f5423ce0081d12eeeef42131de4a84a7f192c0c460bc2113a870),
#   mined on 2017-10-08T21:51:46Z

L2Ac5HjZNoDgK2rkbwBYXt8Q1hwrvv9tDACrsof4Ver7Mtc9Wdrj 2017-09-16T19:02:04Z reserve=1 # addr=t1J3MrwgT4sTXNoAK1hdyvRpSt4XxsCxyNa
L19RGMY6gz3ckNpjufchMuXj5UrX5iniQc23KRe2VbhNaFzrrf5F 2017-09-16T19:02:04Z reserve=1 # addr=t1JEj9ryuzM4r27XBEqiCLK7vNjDPniGiF3

And then the keys are listed here.

**Comment by daira** [comment]
@gman77 Please note that the spending keys for t1J3MrwgT4sTXNoAK1hdyvRpSt4XxsCxyNa and t1JEj9ryuzM4r27XBEqiCLK7vNjDPniGiF3 are now compromised because they were published in the above comment. I strongly recommend that you move any remaining funds from those addresses and stop using them. (I redacted them to avoid opportunists deciding to use them after seeing my comment, but you should in any case assume that they're compromised.)

**Comment by gman77** [comment]
Ok great! tks.

**Comment by daira** [comment]
It looks like there are no transactions involving those two addresses, so yes, you can just create new addresses and stop using the two that were compromised.
