### ISSUE TITLE
zcashd ubuntu 16.04 extreme network load with rpc calls

### ISSUE THREAD

**Issue by joshyOcuk** [zcash/zcash#2660]
### Describe the issue
after so long, can be 1 hour can be 2 days, local network load from zec slowly starts to climb well above 1Mbps if not kept in check by restarting the node. it will continue to grow until its above 100Mbps, the worst iv seen, and cripples the network. this node is being used by a znomp pool and the issue seems to be with rpc calls, pool is also connecting to kmd zcl zen hush nodes fine with same or similar configs.

attempted resolves in zcash.conf: rpckeepalive=0, rpcworkqueue=124 
attempted resolves in znomp: increase block polling to +1 second(seemed to allow node to operate longer before network load started to increase)

same issue still remains. 

attempted fixes with OS, wondershaper cap up down to 3Mbps

causes new issue, pool operates fine until network load starts to spike then pool fails to poll the full block, receives with missing headers until thread dies.

note, traffic is one way, node sending to pool.

vm resources dedicated to zcashd
4 cores 2.6Ghz (cpu goes between 30-70% at peak)
6 GB ram (ram usage never exceeds 70%)

### Can you reliably reproduce the issue?
yes 
#### If so, please list the steps to reproduce below:
allow znomp to connect to node

versions tested 1.0.12 1.0.11

i am going to build v1.0.10-1 to see if the same issue remains and will report back.

any help would be greatly appreciated.

**Comment by ioptio** [comment]
@joshyOcuk for testing purposes, can you remove connection to znomp pool and let us know if the problem persists?

**Comment by ioptio** [comment]
Closing this ticket due to lack of response. Please let us know if you resolved your problem and how. Or if it's still an issue, feel free to reopen this ticket and explain further.

**Comment by joshyOcuk** [comment]
thanks for your replies sorry for my lack of response, i was able to get around this by using "peermagic" (pchMessageStart) for block notifications to the pool instead of polling with rpc this reduced alot of load on the daemon, also more cores and more ram helped
