### ISSUE TITLE
Please help receiving "Aborted (Core dumped)" have log

### ISSUE THREAD

**Issue by SgtH2OUSMC** [zcash/zcash#2661]
#### If so, please list the steps to reproduce below:
1.  Power on VM
2. start zcashd
3. 

### Expected behaviour
Tell us what should happen
node starts running then I can open my wallet

### Actual behaviour + errors
Tell us what happens instead including any noticable error output (any messages displayed on-screen when e.g. a crash occurred)

Aborted (Core dumped)

### Any extra information that might be useful in the debugging process.
This includes the relevant contents of `~/.zcash/debug.log`. You can paste raw text, attach the file directly in the issue or link to the text via a pastebin type site.
Please also include any non-standard things you did during compilation (extra flags, dependency version changes etc.) if applicable.

Since starting this node 18 seconds ago:
- You have validated 7935 transactions!

Init message: Loading wallet...

[Press Ctrl+C to exit] [Set 'showmetrics=0' to hide]
[New Thread 0x7fffcbd3b700 (LWP 3241)]
[Thread 0x7fffcbd3b700 (LWP 3241) exited]
[New Thread 0x7fffcb53a700 (LWP 3242)]
[New Thread 0x7fffcad39700 (LWP 3243)]
[New Thread 0x7fffca538700 (LWP 3244)]
[New Thread 0x7fffc9d37700 (LWP 3245)]
Since starting this node 19 seconds ago:
     Downloading blocks | 194267 / ~199180 (97%)
            Connections | 1
  Network solution rate | 458215784 Sol/s

Thread 22 "zcash-msghand" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffc8d35700 (LWP 3247)]
0x00007ffff6956428 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) 

### The version of Zcash you were using:
Run `zcashd --version` to find out

### Machine specs:

Running on Virtual Machine 

### Do you have a back up of `~/.zcash` directory and/or take a VM snapshot?
- Backing up / making a copy of the `~/.zcash` directory might help make the problem reproducible. Please redact appropriately.
- Taking a VM snapshot is really helpful for interactively testing fixes

Restored snapshot of VM and same result..

**Comment by Flare183** [comment]
I'm having the exact same issue, once it gets to a certain percent it just dies

**Comment by ioptio** [comment]
@SgtH2OUSMC & @Flare183 

Can you both provide the version of the software you are running and what system you use to run it on? 

@Flare183 can you provide a debug.log output?
