### ISSUE TITLE
How do I move balance from private to transparent? 

### ISSUE THREAD

**Issue by neurans** [zcash/zcash#2664]
How do I move balance from private to transparent?  for some reason, I do not have enough balance in the transparent address and my pool can't send payments, but it is in the private wallet.

{
  "transparent": "0.0626199",
  "interest": "0.00",
  "private": "2.9269801",
  "total": "2.9896"
}

**Comment by ioptio** [comment]
Are you using the official Zcash client? If not, you'll want to inquire with the mining software developers.

**Comment by lindanlee** [comment]
We're closing this ticket. Feel free to reopen if you're still having issues.
