### ISSUE TITLE
Dynamically add BuildSteps to CI for all defined test stages

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#2667]
Now that we have a test driver (#429), we should use it to discover the full list of defined test stages, instead of needing to modify our CI configuration every time we add a new test stage. Roughly:

- Add a new flag to the test driver that outputs a list of all defined stages.
- Add a new CI step that collects the list of stages from the test driver.
- Replace the existing per-stage CI steps with a step that [dynamically adds test stage steps](https://docs.buildbot.net/latest/manual/cfg-buildfactories.html#dynamic-build-factories).

**Comment by daira** [comment]
The latter two parts might as well be the same build step.
