### ISSUE TITLE
Indicate whether experimental features is enabled in output of getinfo

### ISSUE THREAD

**Issue by arcalinea** [zcash/zcash#2671]
Would be nice to have an `"experimentalfeatures": boolean` field in the output of `getinfo` command.

**Comment by bitcartel** [comment]
Instead of a boolean, it might be more useful to return a list of the experimental options which have been enabled e.g. `experimentalfeatures: ["paymentdisclosure","superduper","redbutton"]`

**Comment by tomonoris** [comment]
I want to make the patch for this issue, and writing codes now.
I noticed the comment in rpcmisc.cpp:30.
/**
 * @note Do not add or change anything in the information returned by this
 * method. `getinfo` exists for backwards-compatibility only. It combines
 * information from wildly different sources in the program, which is a mess,
 * and is thus planned to be deprecated eventually.
 *
 * Based on the source of the information, new information should be added to:
 * - `getblockchaininfo`,
 * - `getnetworkinfo` or
 * - `getwalletinfo`
 *
 * Or alternatively, create a specific query method for the information.
 **/

Is it better to make new function such as getexperimentalfeaturesinfo to get information about experimental features?

**Comment by oxarbitrage** [comment]
In https://github.com/zcash/zcash/pull/4293 i used the format suggested by @bitcartel to return enabled experimental features in the output of `getblockchaininfo`.
Also added a new call `getexperimentalfeatures` to return just the array of enabled features when called.

By following the note highlighted here by @tomonoris i didn't touched `getinfo`.

**Comment by daira** [comment]
It's not really blockchain-related information, so I think just the new `getexperimentalfeatures` call is sufficient.

**Comment by oxarbitrage** [comment]
Removed that at https://github.com/zcash/zcash/pull/4293/commits/531d85bbfc9b20601fe82cde19f45d5f8ec7dbd7
