### ISSUE TITLE
Remove bashisms from build scripts

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2677]
This will fix #2676.

**Comment by syd0** [comment]
Hi @daira - I'm unable to reproduce this issue. I'm running on Debian which has dash as it's default /bin/sh. Were you able to reproduce the issue? Is this an Ubuntu-specific thing?

**Comment by fishouttah20** [comment]
I was just able to reproduce #2676 on my bash for windows (ubuntu on win10) with similar errors to the previous user:
/bin/sh: 1: Syntax error: "(" unexpected
funcs.mk:242: recipe for target

**Comment by radix42** [comment]
i have fixed the funcs.mk issue in my downstream ports to other platforms, but I can't recall off the top of my head which commits its in, as that was about a year ago
