### ISSUE TITLE
Ensure that large prover data structures can be released without process memory retention

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2679]
In #2235 / #2670 we change from loading the whole proving key in advance, to loading the part needed for each query as we make a proof. However, the parts are allocated on the stack. [Edit: it's actually unclear how much of the problem is stack allocation and how much is heap memory retention.]

This causes memory retention for the lifetime of the process, at least on Linux, as discussed at https://github.com/zcash/zcash/pull/2243#discussion_r120993316 :
> If large structures are put on the stack, [that memory will never be reclaimed in Linux](https://stackoverflow.com/questions/14389525/linux-stack-resident-memory-not-reclaimed-after-stack-unwind). Well, the physical pages currently backing that part of the stack might be reused for other processes, but the memory will be reported as being used for the rest of the lifetime of that process, and I believe that it will also influence OOM killer decisions (increasing the likelihood of the zcashd process being OOM killed).

> Confirmed that the OOM killer uses memory estimates that include reserved memory, not just mapped physical pages: https://unix.stackexchange.com/a/153586/82702
(I think this is a ridiculous policy, but we can't change it.)

**Comment by daira** [comment]
@arielgabizon created a branch that moves the ``ifstream`` for the proving key to the heap: https://github.com/arielgabizon/zcash/compare/lowmemprover...arielgabizon:lowmemmovetoheap . That looks good as far as it goes, but we also need the ``knowledge_commitment_vector``s on the heap, or ``mmap``ped.

**Comment by arielgabizon** [comment]
@daira  Aren't vectors on the heap anyways, except the pointer? In that case is it worth doing that?

**Comment by daira** [comment]
Oh yes, probably. In C++ there's a bias toward assuming that it is more efficient to stack-allocate whenever the representation length is known, and I had assumed it was known in this case. But looking at the definition of ``knowledge_commitment_vector`` in [knowledge_commitment.hpp](https://github.com/zcash/zcash/blob/master/src/snark/src/algebra/knowledge_commitment/knowledge_commitment.hpp#L77-L78), we have:
```
template<typename T1, typename T2>
using knowledge_commitment_vector = sparse_vector<knowledge_commitment<T1, T2> >;
```
and a [sparse_vector](https://github.com/zcash/zcash/blob/master/src/snark/src/common/data_structures/sparse_vector.hpp) uses ``std::vector``s to hold its [indices and values](https://github.com/zcash/zcash/blob/master/src/snark/src/common/data_structures/sparse_vector.hpp#L35-L36), which will probably allocate them on the heap as you say.

**Comment by arielgabizon** [comment]
I'm saying that also cause I initially put these variables on the heap and didn't see any difference in memory released.

**Comment by daira** [comment]
It seems like we'll need to mmap them, or use a custom allocator that avoids retention, in order to make more progress on this.

**Comment by daira** [comment]
I suspect that this is no longer a problem with the Sapling change to proving via bellman, rather than libsnark. @ebfull, can we close this?
