### ISSUE TITLE
How to make own chain

### ISSUE THREAD

**Issue by kensukekita** [zcash/zcash#2681]
hello all my question is how to make my own chain to can make my own coin based on zcash?
i was editing the chain params but i dont know where to get the genesis block hash

**Comment by chenhuan14** [comment]
you can use the regtest mode lik bitcoin.

**Comment by marcofortina** [comment]
Hello folks!
I have the same problem. It's not really clear on how to generate genesis block for regtest that include an equihash solution. I used the GenesisZ python script with silentarmy for mainnet and testnet but this software does not support regtest. Any advise?
Thanks.

**Comment by chenhuan14** [comment]
hello, 
 see https://www.youtube.com/watch?v=86jqAfySi64 <https://www.youtube.com/watch?v=86jqAfySi64> for building private chain.

**Comment by marcofortina** [comment]
@chenhuan14 I've already create my altcoin and the video that you posted here is for using scrypt as POW... I use equihash so it's not usefull for me.

What I need, as I wrote before, is to generate only the regtest genesis equihash solution (I've already done it for mainnet and testnet)

Thanks,
Marco

**Comment by aleqx** [comment]
I'm also interested in this. Are there any guides out there on how to do this?

**Comment by braravind** [comment]
I also want  to create my own chain. so please guide me how to create genesis block and how to setup this.

**Comment by ioptio** [comment]
Duplicate of https://github.com/zcash/zcash/issues/3029 which is now tracked at https://gitlab.com/zcash-docs/zcash-docs/issues/41
