### ISSUE TITLE
Make Error while building

### ISSUE THREAD

**Issue by adityamakkar** [zcash/zcash#2683]
Getting this error:

collect2: error: ld returned 1 exit status
Makefile:2280: recipe for target 'zcash-gtest' failed
make[2]: *** [zcash-gtest] Error 1
make[2]: *** Waiting for unfinished jobs....
collect2: error: ld returned 1 exit status
Makefile:2300: recipe for target 'zcashd' failed
make[2]: *** [zcashd] Error 1
make[2]: Leaving directory '/home/aditya/zcash/src'
Makefile:5319: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/aditya/zcash/src'
Makefile:623: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

followed the usual steps on 1.0 user guide for Build. Also while executing commands for installing system dependencies, I get this:

```
ditya@aditya-VirtualBox:~/zcash$ sudo apt-get install 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 39 not upgraded.
aditya@aditya-VirtualBox:~/zcash$       build-essential pkg-config libc6-dev m4 g++-multilib 
build-essential: command not found
aditya@aditya-VirtualBox:~/zcash$       autoconf libtool ncurses-dev unzip git python python-zmq 
autoconf: error: invalid number of arguments
Try `autoconf --help' for more information.
aditya@aditya-VirtualBox:~/zcash$       zlib1g-dev wget bsdmainutils automake
zlib1g-dev: command not found
```

On Ubuntu 17.10 G++ 7.2

Need help 
thanks

**Comment by daira** [comment]
It's a single command, ``sudo apt-get install build-essential pkg-config libc6-dev m4 g++-multilib autoconf libtool ncurses-dev unzip git python python-zmq zlib1g-dev wget bsdmainutils automake``.

**Comment by adityamakkar** [comment]
All the dependencies are installed, still the make error during test suite persists

**Comment by adityamakkar** [comment]
This is what I get at the end after executing build command (./zcutil/build.sh --disable-rust -j$(nproc))


Making all in src
make[1]: Entering directory '/home/zcubuntu/zcash/src'
make[2]: Entering directory '/home/zcubuntu/zcash/src'
make  -C secp256k1 libsecp256k1.la
make[3]: Entering directory '/home/zcubuntu/zcash/src/secp256k1'
make[3]: Leaving directory '/home/zcubuntu/zcash/src/secp256k1'
make[2]: Leaving directory '/home/zcubuntu/zcash/src'
make[1]: Leaving directory '/home/zcubuntu/zcash/src'
Making all in doc/man
make[1]: Entering directory '/home/zcubuntu/zcash/doc/man'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/zcubuntu/zcash/doc/man'
make[1]: Entering directory '/home/zcubuntu/zcash'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/home/zcubuntu/zcash'

After this when I run Test suite commands, I get the error that has been posted as a seperate issue

**Comment by bitcartel** [comment]
The test suite error ticket is #2690.  Closing this ticket.
