### ISSUE TITLE
Regtest network bug with wrong values in K,N

### ISSUE THREAD

**Issue by evgenyundefined** [zcash/zcash#2684]
Regtest network have init K and N params different from mainnet and testnet. 
On mainnet and testnet K, N
        const size_t N = 200, K = 9;  // Same as mainchain.
        BOOST_STATIC_ASSERT(equihash_parameters_acceptable(N, K));
        nEquihashN = N;
        nEquihashK = K;
On regtest K, N (chainparams.cpp:344)
        const size_t N = 48, K = 5;
        BOOST_STATIC_ASSERT(equihash_parameters_acceptable(N, K));
        nEquihashN = N;
        nEquihashK = K;

With public miners on mainnet and testnet all works fine, but if you make regtest network (for some test) daemon reject all shares from public miners. (this problem have all forks of zerocash). 

Please make regtest params same mainnet and make genesis block for regtest with K,N 200,9 and not with K,N 48,5

**Comment by daira** [comment]
regtest is intended only for unit tests. The regtest parameters are intentionally not the same in order to make the testing time shorter. Is there any reason you can't use a private testnet network?

**Comment by evgenyundefined** [comment]
i use regtest for developming public pools, and cant use public miners for this tests

**Comment by daira** [comment]
I think it's quite unlikely that we would change this, sorry. That's simply not what regtest mode is intended for. Why specifically can't you use testnet mode for developing public pools?

**Comment by str4d** [comment]
If you need a Stratum miner that supports the regtest parameters, my standalone miner should work: https://github.com/str4d/zcash/tree/standalone-miner

(I don't recall whether the "tromp" miner engine supports the regtest params, but the "default" miner engine definitely does)
