### ISSUE TITLE
IPv4 RPC socket dies after some time

### ISSUE THREAD

**Issue by jfcg** [zcash/zcash#2685]
### Describe the issue
ipv4 rpc connection is gone after some time

#### If so, please list the steps to reproduce below:
1. run zcashd
2. observe
sudo lsof -i :8232
COMMAND  PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
zcashd  2687 zcashu    9u  IPv6 578368      0t0  TCP localhost:8232 (LISTEN)
zcashd  2687 zcashu   10u  IPv4 578370      0t0  TCP localhost:8232 (LISTEN)

2. wait for some time
3. ipv4 rpc socket is gone
sudo lsof -i :8232
COMMAND  PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
zcashd  2687 zcashu    9u  IPv6 578368      0t0  TCP localhost:8232 (LISTEN)
 
### Expected behaviour
usual operation of zcash-cli

### Actual behaviour + errors
zcash-cli says
error: couldn't connect to server: unknown (code -1)
(make sure server is running and you are connecting to the correct RPC port)

### The version of Zcash you were using:
v1.0.12-gb86b9feb6

### Machine specs:
- OS name + version: 64 bit linux
- CPU: ryzen 1600
- RAM: 16 gb
- Disk Type (HD/SDD): ssd
- Linux kernel version (uname -a): 4.9.53
- Compiler version (gcc -version): 7.2.0

**Comment by bitcartel** [comment]
How long is "3. wait for some time"?  mins, hours, days?

Also do you see anything in debug.log regarding the socket closing?

**Comment by weixingsun** [comment]
Hi there,

I am getting this issue from my new miner machine
I just compiled source from latest github

1. started zcashd
2. wait for about 8 hours
3.run top
  PID USER       PR   NI    VIRT    RES       SHR S   %CPU  %MEM     TIME+ COMMAND
51882 root      20   0  73.483g 9.981g  17748 S 417.6 1.984   4489:37 zcashd
# src/zcash-cli getinfo
error: couldn't connect to server: unknown (code -1)
(make sure server is running and you are connecting to the correct RPC port)

# cat ~/.zcash/zcash.conf
addnode=mainnet.z.cash
rpcuser=myusername
rpcpassword=mypassword
gen=1
genproclimit=8
equihashsolver=tromp

does anybody have any idea to fix this?
Thanks

**Comment by lindanlee** [comment]
@jfcg any updates? 

@weixingsun is this still a problem? has your zcashd been shut down by the system?

**Comment by jfcg** [comment]
running 1.0.14 straight for 4 days, no problem for now

**Comment by lindanlee** [comment]
@jfcg glad to hear it!

**Comment by ioptio** [comment]
Closing this issue since it seems to be resolved. @weixingsun open a new ticket if you're still having RPC connection issues.
