### ISSUE TITLE
Change auto-senescence cycle to 16 weeks.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#2686]
Currently, autosenescence is defined to be approximately 18 weeks, which is a multiple of our target 6 week release cycle.

TODO: Explain rationale.

**Comment by daira** [comment]
I'm in favour of this, because I think there should be a clear choice of most recent release to upgrade to, rather than the possibility of waiting "just a little longer" for the next release. It will also slightly reduce the latency for hard fork activation. Concept ACK.

**Comment by str4d** [comment]
Concept ACK.

This can be easily implemented during any release process. @nathan-at-least should this target 1.0.13 or 1.0.14?

**Comment by daira** [comment]
+1 for 1.0.13.
