### ISSUE TITLE
Make rust compilation mandatory.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#2688]
We want to move forward with implementing new consensus rules in rust, so the first step is to make rust compilation mandatory to flush out issues on all platforms and downstream codebases.

**Comment by radix42** [comment]
yeah my windows port currently breaks as I have still not had a chance to
cherry pick out the patch from komodo that cross compiles with rust support

**Comment by bitcartel** [comment]
What does "new consensus rules in rust" mean?

**Comment by daira** [comment]
It means code that implements consensus rules (either reimplementations of existing rules, or new rules for Sapling) being written in Rust.

**Comment by str4d** [comment]
There are two components to "mandatory":

- Always build the Rust code (i.e. remove the flags to disable it).
- Require that users have `rustc` and `cargo` installed (like they must have `gcc` installed, or `clang` on Darwin), instead of downloading the Rust binaries inside the depends system.

Are we going to do the latter? cc @ebfull

**Comment by bitcartel** [comment]
Regarding the latter... the official way to install rust is `curl https://sh.rustup.rs -sSf | sh` which for many people has an unsafe smell around it.  https://www.rust-lang.org/en-US/install.html

**Comment by daira** [comment]
The reason that kind of installation has an unsafe smell, for me at least, is that with that method I can't do any verification of what I've downloaded before running the script. (I've installed Rust that way, but I don't have to like it.)

**Comment by daira** [comment]
Also, we have enough problems supporting different GCC versions without multiplying that by the number of Rust versions.

**Comment by str4d** [comment]
I agree that we should stick with the simpler option for now of removing the ability to disable Rust, but leaving the Rust binaries in the depends system.
