### ISSUE TITLE
check-security-hardening.sh - False negative result depending on locale

### ISSUE THREAD

**Issue by mmoussouni** [zcash/zcash#2691]
### Issue description
After clean compilation from source on CentOS7 by following step-by-step "1.0 User Guide" wiki page, Executing the full test suite on a non-english locale gives some fails while changing local to en_GB or en_US, rebooting, relaunching full test suite gives clean output with no error.

#### Those steps are all made with the software versions described right below
```bash
$ git clone https://github.com/zcash/zcash.git
$ cd zcash/
$ git checkout v1.0.12
$ ./zcutil/fetch-params.sh

$ ./zcutil/build.sh --disable-rust -j 2

$ ./qa/zcash/full-test-suite.sh
```

I could reproduce the error with fr_FR, de_DE, es_ES, it_IT (all used as .utf8 variant)

### With en_US.utf8 or en_GB.utf8 locale : Partial output
``` bash
===== BEGIN: /usr/src/zcash/qa/zcash/check-security-hardening.sh
make: Entering directory `/usr/src/zcash/src'
Checking binary security of [zcashd zcash-cli zcash-tx]...
make: Leaving directory `/usr/src/zcash/src'
PASS: /usr/src/zcash/src/zcashd has no RPATH or RUNPATH.
PASS: /usr/src/zcash/src/zcash-cli has no RPATH or RUNPATH.
PASS: /usr/src/zcash/src/zcash-gtest has no RPATH or RUNPATH.
PASS: /usr/src/zcash/src/zcash-tx has no RPATH or RUNPATH.
PASS: /usr/src/zcash/src/test/test_bitcoin has no RPATH or RUNPATH.
PASS: /usr/src/zcash/src/zcash/GenerateParams has no RPATH or RUNPATH.
PASS: /usr/src/zcash/src/zcashd has FORTIFY_SOURCE.
PASS: /usr/src/zcash/src/zcash-cli has FORTIFY_SOURCE.
PASS: /usr/src/zcash/src/zcash-gtest has FORTIFY_SOURCE.
PASS: /usr/src/zcash/src/zcash-tx has FORTIFY_SOURCE.
PASS: /usr/src/zcash/src/test/test_bitcoin has FORTIFY_SOURCE.
PASS: /usr/src/zcash/src/zcash/GenerateParams has FORTIFY_SOURCE.
===== PASSED: /usr/src/zcash/qa/zcash/check-security-hardening.sh
```

### With fr_FR.utf8 locale : Partial output
``` bash
===== BEGIN: /usr/src/zcash/qa/zcash/check-security-hardening.sh
make: Entering directory `/usr/src/zcash/src'
Checking binary security of [zcashd zcash-cli zcash-tx]...
zcash-cli: failed NX RELRO
zcash-tx: failed NX RELRO
make: *** [check-security] Erreur 1
make: Leaving directory `/usr/src/zcash/src'
===== FAILED: /usr/src/zcash/qa/zcash/check-security-hardening.sh
```

### Build tool versions (Zcashd v1.0.12)
```
autoconf.noarch                         2.69-11.el7              @base
automake.noarch                         1.13.4-3.el7             @base

autotools-latest.x86_64                 1-14.el7.centos          @praiskup-autotools-epel-7-x86_64
autotools-latest-autoconf.noarch        2.69-4.el7.centos        @praiskup-autotools-epel-7-x86_64
autotools-latest-automake.noarch        1.15-4.el7.centos        @praiskup-autotools-epel-7-x86_64
autotools-latest-libtool.x86_64         2.4.2-16.el7.centos      @praiskup-autotools-epel-7-x86_64
autotools-latest-m4.x86_64              1.4.17-4.el7.centos      @praiskup-autotools-epel-7-x86_64
autotools-latest-runtime.x86_64         1-14.el7.centos          @praiskup-autotools-epel-7-x86_64

devtoolset-3.x86_64                               3.1-12.el7                        @centos-sclo-rh
devtoolset-3-binutils.x86_64                      2.24-18.el7                       @centos-sclo-rh
devtoolset-3-elfutils.x86_64                      0.161-1.el7                       @centos-sclo-rh
devtoolset-3-elfutils-libelf.x86_64               0.161-1.el7                       @centos-sclo-rh
devtoolset-3-elfutils-libs.x86_64                 0.161-1.el7                       @centos-sclo-rh
devtoolset-3-gcc.x86_64                           4.9.2-6.el7                       @centos-sclo-rh
devtoolset-3-gcc-c++.x86_64                       4.9.2-6.el7                       @centos-sclo-rhh
devtoolset-3-gdb.x86_64                           7.8.2-38.el7                      @centos-sclo-rh
devtoolset-3-icu4j.noarch                         1:54.1.1-4.4.el7                  @centos-sclo-rh
devtoolset-3-ide.x86_64                           3.1-12.el7                        @centos-sclo-rhlo-rh
devtoolset-3-libstdc++-devel.x86_64               4.9.2-6.el7                       @centos-sclo-rh
devtoolset-3-runtime.x86_64                       3.1-12.el7                        @centos-sclo-rh
devtoolset-3-toolchain.x86_64                     3.1-12.el7                        @centos-sclo-rh
devtoolset-3-xmlrpc-client.noarch                 1:3.1.3-8.4.el7                   @centos-sclo-rh
devtoolset-3-xmlrpc-common.noarch                 1:3.1.3-8.4.el7                   @centos-sclo-rh
devtoolset-3-xmlrpc-server.noarch                 1:3.1.3-8.4.el7                   @centos-sclo-rh
```

### Machine specs:
- Virtualization Software : Virtualbox 5.1.30
- OS name + version: CentOS Linux release 7.4.1708 (Core) - Hosted on Windows 10
- CPU: Physical i5-4430 / Virtual Quad-Threaded
- RAM Setup1: Physical 8Go / Virtual 2Go + 25Go swap
- RAM Setup2: Physical 8Go / Virtual 5Go + 25Go swap
- Disk size: LVM PV 500Go + 20Go / LV 495Go Root + 25 Go Swap
- Disk Type (HD/SDD): Physical HDD 7200rpm
- Linux kernel version (uname -a): 3.10.0-693.5.2.el7.x86_64
- Compiler version (gcc -version): devtoolset-3-gcc.x86_64 - 4.9.2-6.el7

### Link to forum
https://forum.z.cash/t/test-check-security-hardening-failed-solved/22652 - My case
https://forum.z.cash/t/check-security-hardening-failed/3625 - Another case, may be related **(no proof!)**

### TODO Proposition
 - If possible, temporarily set locale to en_US.utf8 (locale used by buildbot) during tests.
 - Else, adapt wiki "1.0-User-Guide.md" and root "doc/unit-tests.md" to precise how to change locale so newcomers won't be destabilized.

_PS: Full log file will be attached tomorrow_

**Comment by daira** [comment]
Note that I added the SECURITY label not because this issue affects security per se, but because it prevents some users from easily verifying an aspect of security.

**Comment by daira** [comment]
Thanks for the very complete bug report @mmoussouni !

**Comment by radix42** [comment]
an additional note on this is platforms that have a locale where the comma is used as a decimal separator have issues with the json rpc calls from some apps, but that is not zcash specific per se, but is a related issue for zcash app developers to be aware of

**Comment by bitcartel** [comment]
Hi @mmoussouni is the log file available yet?  Thanks.

**Comment by syd0** [comment]
FWIW I think this can be closed once #2752 is merged in. The issue here stems from how arguments were passed to the security-check.py via the Makefile. I'm not sure why it worked at all for the "en_US.utf8" locale (it probably should have failed just like it did for the FR and other locales), but perhaps this is a non-issue now.

**Comment by fnzv** [comment]
I cannot replicate any more the issue so i guess it's solved on newer code?
I'm using CentOS Linux release 7.4.1708 (Core), i think that would have helped having a dump of all Linux env variables & locales (from shell env | grep LC)

**Comment by lindanlee** [comment]
We think this is fixed! Feel free to reopen if you think it isn't.
