### ISSUE TITLE
metrics display advised to add gen=1 to mine even if not mining for another reason

### ISSUE THREAD

**Issue by radix42** [zcash/zcash#2699]
When -showmetrics=1 is passed to zcashd, it displays the following no matter why your node is not mining at the moment:
```
You are currently not mining.
To enable mining, add 'gen=1' to your zcash.conf and restart.
```

Ideally it would display a different, more detailed message if it is not solo mining if, for example, the node was not synced 100% or there was not enough free RAM.

**Comment by daira** [comment]
As far as I know,
* it does already display a different message while syncing
* it doesn't avoid solo mining because of insufficient RAM; it is just OOM-killed or causes excessive paging in that case.

**Comment by awanksodik** [comment]
my RAM :16Gb why not mining? "to enable mining, add 'gen=1' to your zcash.conf and restart"

**Comment by ioptio** [comment]
@awanksodik do you have gen=1 in zcash.conf?

**Comment by ioptio** [comment]
This needs to be tested and confirmed as still in need of a fix or not

**Comment by garethtdavies** [comment]
On 2.0.2 it says "Mining is paused while downloading blocks" if not synced so appears to be resolved.

http://i.imgur.com/ENuF6K3.png
![image](https://user-images.githubusercontent.com/135382/50190271-7ece7b80-02dd-11e9-8d59-e93d512e9e4d.png)

**Comment by ioptio** [comment]
Thanks @garethtdavies!
