### ISSUE TITLE
Issues with fetch-params.sh

### ISSUE THREAD

**Issue by clumsyzombie** [zcash/zcash#2709]
I am trying to install a setup a node via 
https://zdeveloper.org/wiki:seed_node_install

I get to
Building the Wallet
./zcutil/build.sh -j$(nproc)
./zcutil/fetch-params.sh

Once I run ."/zcutil/fetch-params.sh"
It gose to connect and then just hangs at a amazonaws.com is there something wrong with the server where this script is trying to connect to. 

I just did a git clone today on git clone https://github.com/zcash/zcash.git

So i should have the latest and greatest but it is not able to contact the server and times out basically and locking up my Ubuntu 16.10

```
clumsy@ubuntu:~/zcash$ ./zcutil/fetch-params.sh
Zcash - fetch-params.sh

This script will fetch the Zcash zkSNARK parameters and verify their
integrity with sha256sum.

If they already exist locally, it will exit now and do nothing else.
The parameters are currently just under 911MB in size, so plan accordingly
for your bandwidth constraints. If the files are already present and
have the correct sha256sum, no networking is used.

Creating params directory. For details about this directory, see:
/home/dsadler/.zcash-params/README


Retrieving (wget): https://z.cash/downloads/sprout-proving.key
--2017-11-05 13:56:32--  https://z.cash/downloads/sprout-proving.key
Resolving z.cash (z.cash)... 104.28.11.251, 104.28.10.251
Connecting to z.cash (z.cash)|104.28.11.251|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://s3.amazonaws.com/zcashfinalmpc/sprout-proving.key [following]
--2017-11-05 13:56:33--  https://s3.amazonaws.com/zcashfinalmpc/sprout-proving.key
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.131.109
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.131.109|:443... connected.
```
right here and stops nothing else

**Comment by clumsyzombie** [comment]
Can this file it i s trying to get be downloaded on lets say another system and moved over to this other system I have and if so where dose it place the time do you all know

**Comment by jasondavies** [comment]
There are two files downloaded to `.zcash-params/` in your home directory (`$HOME`): you should be fine to simply copy these files from another system into the same directory, and then re-run `./zcutil/fetch-params.sh` as you did above to ensure the checksums are as expected.  You should get the following output:

```
$ ./zcutil/fetch-params.sh
Zcash - fetch-params.sh

This script will fetch the Zcash zkSNARK parameters and verify their
integrity with sha256sum.

If they already exist locally, it will exit now and do nothing else.
```

The two files are called `sprout-proving.key` (869MB) and `sprout-verifying.key` (1.5KB).

**Comment by clumsyzombie** [comment]
So what I have done is this
/home/clumsy/.zcash_params
clumsy@ubuntu:~/.zcash_params$ ll
total 888860
drwxrwxr-x 2 clumsy clumsy      4096 Nov  5 18:54 ./
drwxr-xr-x 7 clumsy clumsy      4096 Nov  5 18:55 ../
-rw-r--r-- 1 clumsy clumsy 910173851 Nov  5 14:19 sprout-proving.key
-rw-r--r-- 1 clumsy clumsy      1449 Nov  5 18:47 sprout-verifying.key

So I also have all the zcash wallet in
/home/clumsy/zcash

When I ran fetch it tried to download again it just keeps trying to hit this amazonaws.com  even that I have it where even in the screen says it is goign to bee in
/home/clumsy/.zcash_params/README

So not sure what is going on there.

**Comment by radix42** [comment]
I have a fast mirror at https://zcash.dl.mercerweiss.com/sprout-proving.key
(and the verifier key too), you can pop that into the script and you should
be fine for now, not sure what's up with zcash's url

**Comment by clumsyzombie** [comment]
So I did all that and what I am getting is this now

Thank you for running a Zcash node!
You're helping to strengthen the network and contributing to a social good :)

In order to ensure you are adequately protecting your privacy when using Zcash,
please see <https://z.cash/support/security/index.html>.

Since starting this node 0 seconds ago:
- You have validated no transactions.

Messages:
- Error: Cannot find the Zcash network parameters in the following directory:
"/home/clumsy/.zcash-params"
Please run 'zcash-fetch-params' or './zcutil/fetch-params.sh' and then restart.

Init message:

[Press Ctrl+C to exit] [Set 'showmetrics=0' to hide]
zcashd: scheduler.cpp:19: CScheduler::~CScheduler(): Assertion `nThreadsServicingQueue == 0' failed.
Aborted (core dumped)
clumsy@ubuntu:~/zcash$

What is crazy in directory it is talking about I have 
/home/clumsy/.zcash-params

clumsy@ubuntu:~/.zcash_params$ ll
total 888860
drwxrwxr-x 2   clumsy clumsy    4096 Nov  5 18:54 ./
drwxr-xr-x 9    clumsy clumsy  4096 Nov  5 19:07 ../
-rw-r--r-- 1     clumsy clumsy  910173851 Nov  5 14:19 sprout-proving.key
-rw-r--r-- 1     clumsy clumsy 1449 Nov  5 18:47 sprout-verifying.key
clumsy@ubuntu:~/.zcash_params$

Do I have something wrong Still?

**Comment by jasondavies** [comment]
Looks like you used an underscore `_` instead of a dash `-` in the directory name.  It should be `.zcash-params`.

**Comment by clumsyzombie** [comment]
WOW you are right man been a long long long day  sorry

**Comment by daira** [comment]
@jasondavies wrote:
> you should be fine to simply copy these files from another system into the same directory, and then re-run ./zcutil/fetch-params.sh as you did above to ensure the checksums are as expected.

``fetch-params.sh`` currently doesn't check the hashes if the files already exist. If you copy/download them manually, you must also check the hashes manually using ``sha256sum``. The expected hashes are in ``fetch-params.sh``.

**Comment by jasondavies** [comment]
Thanks for the correction, @daira!

**Comment by clumsyzombie** [comment]
Well I got the zcash working on I am 

           Block height | 214904
            Connections | 8
  Network solution rate | 344496775 Sol/s

You are currently not mining.
To enable mining, add 'gen=1' to your zcash.conf and restart.

Since starting this node 13 hours, 9 minutes, 11 seconds ago:
- You have validated 3630498 transactions!


You all have been a great help honestly. 
So now that I have that I am on to the next step I am looking at this site now. 
https://zdeveloper.org/wiki:z-nomp_install
I know this is not the place to ask but wanted to know if you all had a better place I should be looking?
What OS most the time do people use I am currently on uduntu 16.10 is this ok? Should I go to 17?

When I do nomp I get tons of errors when I go to the first step
sudo apt-get install build-essential libsodium-dev npm redis-server git
sudo npm install n -g
sudo n stable
git clone https://github.com/joshuayabut/node-open-mining-portal.git z-nomp
cd z-nomp
npm update  <<<<<<<<<<  Errors 100%
npm install

So when I run npm update  I get a ton of errors like 
clumsy@ubuntu:~/z-nomp$ npm update
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning ENODATA: Cache input stream was empty
npm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
npm ERR! code EINTEGRITY
npm ERR! errno EINTEGRITY
npm ERR! Invalid response body while trying to fetch https://registry.npmjs.org/bignum: Integrity verification failed for sha512-0q2FCJCYvsaAka9QvhRiRmz9eDqjYudUKRUUu/qRgQKHN+QSPCQ9UQQJA2/wDlRc3gznKsTWQjL3cs7gxBWhNw== (/home/dsadler/.npm/_cacache/content-v2/sha512/d2/ad/85089098bec68091af50be1462466cfd783aa362e754291514bbfa9181028737e4123c243d510409036ff00e545cde0ce72ac4d64232f772cee0c415a137)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/clumsy/.npm/_logs/2017-11-06T15_03_57_470Z-debug.log

So I checked the log and well all it says same that was printed on the screen so just looking for some input because the z-nomp git is about dead. 
SHould I even use z-nomp?
am I using the right version of OS?

**Comment by jasondavies** [comment]
> I know this is not the place to ask but wanted to know if you all had a better place I should be looking?

You should probably join the community chat for general queries like this: <https://chat.zcashcommunity.com/>
