### ISSUE TITLE
Change Consensus Mechanism

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#2716]
This is a high level "catch all" for any consensus mechanism changes.

The scope *includes*:

- how the network arrives at consensus on a set of valid recent transactions.
- changes to PoW function or parameters (ex: #2715)
- changes to difficulty adjustment algorithm.
- broader changes to consensus mechanism (ex: GHOST, Bitcoin-NG, proof-of-stake, etc…)
- changes to block size, or other block structure changes that impact consensus mechanism.

The scope *excludes*:

- changes to block headers unrelated to consensus mechanism (ex: add UTXO tree commitment)
- transaction validity unrelated to consensus mechanism (ex: add malleability-protected signature scheme, changes to fee system, new opcodes, new zkSNARK circuits, etc…)

**Warning:** The second category of consensus rules changes may subtly impact consensus mechanism, so we must carefully scrutinize all proposals for that. A great case study from Bitcoin is ASICBOOST where the "specification" allowed an unforeseen optimization (ASICBOOST) that was broken by a proposed non-consensus-mechanism change (segwit).

**Comment by daira** [comment]
This ticket seems really vague. In practice you can find a similar list of potential consensus changes by looking at the [NU2 wishlist](https://github.com/zcash/zcash/labels/NU2%20wishlist) label.

**Comment by nathan-at-least** [comment]
I'm not sure what I was thinking.
