### ISSUE TITLE
It is not obvious to users that private keys are stored in wallet.dat

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2719]
See https://forum.z.cash/t/trouble-with-zcash4win/22985/14 . Indeed there's no reason this should be obvious to Zcash users who have no experience with Bitcoin.

**Comment by arcalinea** [comment]
Should we add a line to the user guide, and getting-started page?

**Comment by daira** [comment]
Yes I think so.

**Comment by ioptio** [comment]
Moving this issue to docs repo: https://gitlab.com/zcash-docs/zcash-docs/issues/45
