### ISSUE TITLE
Renew the SoYouStart servers (next due: Dec 2nd, 2016)

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#272]
There's no automatic recurring billing, so I need to remember to manually renew every month (or every 3 months, or whatever).

**Comment by nathan-at-least** [comment]
I added a team calendar event for 2016-07-31 with an email reminder (but I'm not sure if that reminder goes only to my account).  Is that sufficient for closing this ticket?

**Comment by defuse** [comment]
No, this ticket will be open forever, to remind us whenever we need to renew those servers.

**Comment by defuse** [comment]
Some of those dates are near our 1.0 release crunch so while I was logged into the account I renewed them some more. Now the expirations are:

```
Jan 31, 2017
Dec 02, 2016
Nov 25, 2016
```

**Comment by defuse** [comment]
I'll be gone when these servers expired so I added the engineering meeting agenda label to bring that up, and unassigned myself.

**Comment by str4d** [comment]
@ageis status?

**Comment by ageis** [comment]
No action required, we have three machines with the following expiration dates:

25 May 2017
2 Jun 2017
31 Jul 2017

**Comment by ageis** [comment]
Closing as this belongs in the internal repository.
