### ISSUE TITLE
[Sapling] Specify note encryption scheme

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2721]
This will still be half-ephemeral Diffie-Hellman as in Sprout, but it will:

* be over the Jubjub curve;
* possibly use the Montgomery form of the curve, and/or scalar encoding tricks like signed digits or adjacent XORs (see #2277);
* possibly do scalar clamping in a different way than Curve25519 (depending on whether we use Montgomery or Edwards form);
* support diversified addresses;
* use a separate ephemeral public key per ciphertext;
* use different personalisation for the KDF;
* possibly use a different KDF.

It will probably still use AEAD_CHACHA20_POLY1305.

**Comment by daira** [comment]
@ebfull and I discussed this today and nailed down a few more details.

The representation of pkenc<sub>d</sub> and epk will be compressed affine Montgomery form. This enables the circuit to use XY Montgomery coordinates which is the most circuit-efficient option (3 constraints per non-unified addition and 4 constraints per doubling). Outside the circuit we can either use a Montgomery ladder and then [recover the Y coordinate using the Okeya-Sakurai method](https://github.com/zcash/zcash/issues/2277#issuecomment-346850979), or convert to twisted Edwards form and use the complete addition/doubling formulae (which is what the current prototype code does).

The scalars vk and esk will be clamped by clearing above bit 250, setting bit 250, and clearing bit 249. This ensures that the clamped scalar is <= (s-1)/2 where s is the prime subgroup order, [which ensures that non-unified addition can be used safely](https://github.com/zcash/zcash/issues/2234#issuecomment-348243024). Cofactor multiplication will be done explicitly (rather than as part of the scalar clamping as in Curve25519), i.e.
* Key generation:
  * Calculate pk<sub>d</sub> = [vk] GH(d).
  * Compress pk<sub>d</sub> for use in the address.
* Decryption:
  * Decompress epk and check it is on the curve.
  * Calculate [8] epk and check it is not 𝓞.
  * Calculate dhresult = [vk] [8] epk (and apply the KDF and AEAD).
* Encryption:
  * Decompress pk<sub>d</sub> and check it is on the curve.
  * Calculate epk = [esk] GH(d).
  * Calculate [8] pk<sub>d</sub> and check it is not 𝓞.
  * Calculate dhresult = [esk] [8] pk<sub>d</sub> (and apply the KDF and AEAD).
  * Compress epk for use in the ciphertext.

Note that LSB compression is used because that matches the spec of GH and makes checking the compression efficient in the circuit. The point validation checks are useful, even though Jubjub is twist-secure, because we're not necessarily using the Montgomery ladder.

**Comment by str4d** [comment]
@daira says the final version of this has been specified.
