### ISSUE TITLE
transaction has no confirmations after 4 hours

### ISSUE THREAD

**Issue by Kenbob22** [zcash/zcash#2734]
Hi, I'm having an issue with a zcash transaction that is not going through after 4 hours and no confirmations. I sent 4 ZEC from my zcash4win wallet to my Bittrex wallet. Shortly before that I sent .2 ZEC to the same wallet and the confirmations were rather fast. Bittrex shows the 4 ZEC transaction is recognized but there are no confirmations. the tix number is c2dcf52fc9e81151af485d0042579e81c8795c10c30f19515c224b5a33ce5ae2. Can someone help a noobie? Thanks

**Comment by daira** [comment]
There's currently a transaction backlog due to many large transactions with a large  of inputs having been submitted.

**Comment by Kenbob22** [comment]
Thank you for the reply, daira.  The transaction has still not been completed after 27 hours.  I'm just hoping I don't lose my ZEC.  All I know to do is wait, I guess.

**Comment by radix42** [comment]
Dom’t worry, you won’t lose it. The transaction will eventually either get
mines or drop out of everyone’s mempool and be spendable again. It just
make take....some days for that to go one way or the other

**Comment by Kenbob22** [comment]
Thank you, Radix...and for how fast you replied.  I suppose if it drops out of the mempool it will reappear in my zcash4win wallet?  Again, much appreciation and sorry for my crypto ignorance.

**Comment by arcalinea** [comment]
Yes, if it drops out of the mempool it should appear back in your wallet as spendable.

**Comment by arcalinea** [comment]
I just looked up that tx in the mempool, here's the result: 
`./src/zcash-cli getrawmempool | grep c2dcf52fc9e81151af485d0042579e81c8795c10c30f19515c224b5a33ce5ae2
  "c2dcf52fc9e81151af485d0042579e81c8795c10c30f19515c224b5a33ce5ae2",`

So it's still sitting there in the mempool. This looks like a huge transaction with many inputs, which is why it hasn't been mined yet.

**Comment by ULCER63** [comment]
![default](https://user-images.githubusercontent.com/33725406/32979668-63f6f63a-cc73-11e7-8512-b8e7f01984d6.jpg)
``

**Comment by ULCER63** [comment]
please help

**Comment by ULCER63** [comment]
please help already 3 days waiting for the transaction

**Comment by ioptio** [comment]
Looks like this transaction was mined: http://explorer.zcha.in/transactions/c2dcf52fc9e81151af485d0042579e81c8795c10c30f19515c224b5a33ce5ae2
