### ISSUE TITLE
Add prefix to payment disclosures

### ISSUE THREAD

**Issue by tromer** [zcash/zcash#2746]
Payment disclosures (as output by the experimental `z_getpaymentdisclosure`) are currently a raw hex blob. For example:

```
$ ./src/zcash-cli  z_getpaymentdisclosure d29b3c3b884baf97f15c949c585fb2f9c1d22199581ffd707f72cb109c408a4e 0 1 "Robots are Red"
706462ff004c561a0447ba2ec51184e6c204fa49c0b5cf421ad907d3441cbb1cac9405209e4e8a409c10cb727f70fd1f589921d2c1f9b25f589c945cf197af4b883b3c9bd200000000000000000110b0d669c284461e3c64e320209d1a09f1aadee792c8371d800957c0f5bab2d30a18c3e273ce49da6aa9f5b5b5143c294675bffc6e6736be4c2614e92969a75f0e526f626f74732061726520526564de379c0d97dd613d7a7dd4155eb2178cb596e8c1f01e4998d9b953b876d30f5cbc12097011d8d3d84f3495dc633bfc26a07cd16671ce8dc1fb811be5a589170e
```
I suggest to add a prefix, say `zpd1` ("Zcash payment disclosure, version 1").

We already have some raw hex blobs floating around (txid, blocks, raw transactions), so things get confusing when you can't even tell at a glance what's the type of the object you're looking at, other than by guesstimating its length. And as new types of selective disclosure keys get incorporated, it's important that people can tell which one of _those_ they're looking at.

**Comment by bitcartel** [comment]
Something like "zpd:" work work, with a : as separator, so visually obvious what the prefix is.  The version number doesn't really need to be included as that's already in the blob.

On versioning and serialization, we could end up using flatbuffers, protobuf etc. but for now sticking with standard bitcoin style serialization.

**Comment by tromer** [comment]
There's an ongoing discussion of the analogous encoding question for incoming view keys (see https://github.com/zcash/zcash/pull/2143#issuecomment-345933703 and atm most of the subsequent comments). The conventions should be consistent.

**Comment by bitcartel** [comment]
@tromer Should the `zpd:` prefix be lowercase only?  Makes it easier to check.  Some protocols apply a checksum over the prefix and the payload, so having a case-insensitive prefix is not allowed.  Internally we could convert to lowercase first.  Perhaps for this current experimental version we leave it as lowercase only since the PR is already done.  We can adjust if necessary at a later date.

**Comment by tromer** [comment]
The only argument I see for making it case-insensitive is that if we pretend that it's a URI following RFC 3986, and then the `zpd` would be the URI scheme, defined as case-insensitive but canonically lowercase.

I can't bring myself to care... If case-insensitive is awkward then lowercase-only is fine by me.

**Comment by bitcartel** [comment]
Lowercase only for now. Can revisit at a later date if necessary.
