### ISSUE TITLE
CDBEnv::Salvage: Database salvage found errors, all data may not be recoverable.

### ISSUE THREAD

**Issue by quatrosoftware** [zcash/zcash#2753]
### Describe the issue
I can not load wallet.dat after computer crash. I had saved file wallet.dat but can`t import it.

### Can you reliably reproduce the issue?
Yes, I tried Win10 and Linux (Ubuntu).

#### If so, please list the steps to reproduce below:
1. Copy paste wallet.dat to zcash dir
2. fire zcashd deamon (after clear all blocks data)
3. Deamon is shutting down. I had in debug.log

### Expected behaviour
Client should start normally and get blocks.

### Actual behaviour + errors
Deamon shutting down with log:

`2017-11-20 10:02:27 Renamed wallet.dat to wallet.1511172147.bak

2017-11-20 10:02:27 CDBEnv::Salvage: Database salvage found errors, all data may not be recoverable.

2017-11-20 10:02:27 Salvage(aggressive) found no records in wallet.1511172147.bak.`

### The version of Zcash you were using:
Zcash Daemon version v1.0.12

### Machine specs:
- Ubuntu 14.04
- Intel i5 4c
- 16 GB DDR3
- 128 GB SSD
- Linux kuba 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Compiler version (gcc -version):
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609

### Do you have a back up of `~/.zcash` directory and/or take a VM snapshot?
Have only backup wallet.dat (created about 3 months ago when I installed zcash)

**Comment by ioptio** [comment]
For a sure fix, we recommend renaming your ~/.zcash folder then creating a new `~/.zcash` folder and copy the config and wallet files in there then restarting with a fresh sync of the blockchain. Make sure you have a copy of your wallet file backed up before moving it into the folder for resyncing.

Let us know if this resolves it for you.

**Comment by quatrosoftware** [comment]
Problem is that I have only wallet.dat, didn`t backup zcash.conf. Then I uninstall zcash4win and install again with previous wallet.dat.
Of course I tried to remove all dirs in AppData but still have same error.
