### ISSUE TITLE
Zcash balance showing 0

### ISSUE THREAD

**Issue by lakmereddy** [zcash/zcash#2754]
I am new to zcash mining and need help

my zcash is showing zero balance from the past 2 days

![zcash](https://user-images.githubusercontent.com/19896548/33017212-72881814-ce17-11e7-91d7-d61a1870040f.png)

**Comment by ioptio** [comment]
Are you mining with a pool? Are you using just the zcash client to mine or are you using a separate software for GPU mining?

**Comment by bourger** [comment]
same here
I'm mining zcl with a separate miner on a pool, the pool made several payments to my t-addr but `zcash-cli z_getbalance` shows 0.000000

**Comment by tiagovaz** [comment]
Same here. Almost two days after a first transaction and I keep getting "balance": 0.00000000 from zcash-cli.

From [this website](https://explorer.zcha.in/) I get the proper balance tough. Any hints?

**Comment by ioptio** [comment]
Closing this ticket since OP has not responded, feel free to reopen if it's still a problem. Opened up ticket about sync documentation.
