### ISSUE TITLE
Link to "gold" icon doesn't work on website

### ISSUE THREAD

**Issue by mattcoxonline** [zcash/zcash#2774]
On https://z.cash/press.html the link to the gold logo doesn't work.

<img width="568" alt="screen shot 2017-11-27 at 15 07 37" src="https://user-images.githubusercontent.com/673542/33270570-cd777ebe-d384-11e7-829a-76ce9ed18507.png">

**Comment by arcalinea** [comment]
Thanks, fixed the link. It should work if you refresh the page
