### ISSUE TITLE
Design and document testnet upgrade deployment and test plan

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#2776]
Here's a proposal to be evaluated:

- one testnet has the new ruleset enabled with no upgrade mechanism.
- one or more testnet for testing "testnet activation" logic.

**Comment by nathan-at-least** [comment]
I just changed the title here. The goal for this ticket is simply to specify the test plan clearly in a document in a way that we believe should exercise all new functionality and some regression smoke tests.

Actually *automating* any of that can be followed up on in separate tickets.

**Comment by mms710** [comment]
We have documented a test plan for Sapling and we have work in the dev-infra backlog to start automation work for testing.
