### ISSUE TITLE
How to rollback unconfirmed Zcash transaction?

### ISSUE THREAD

**Issue by meldo8** [zcash/zcash#2782]
Hello. My zcash transaction has been unconfirmed for over40 hours and I would like to take it back. I know that function -zapwallettxes=2 should do that but I have no idea how to use it :/ Could anyone explain me how can I get back my funds?

**Comment by daira** [comment]
Existing tickets describing a complete solution are #2482 and #1958. I don't know what a workaround would be for current Zcash.

**Comment by bitcartel** [comment]
Sorry, at the moment you'll have to wait for the transaction to be mined.  Can you share the txid with us and maybe we can think of a solution? If you prefer to discuss privately, please e-mail info@z.cash and reference this ticket.  Thanks.

**Comment by meldo8** [comment]
Problem solved, thanks for help anyway :)
