### ISSUE TITLE
Add timestamps to GetWarnings messages

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#2783]
Currently, when an alert like "WARNING: check your network connection, [snip]" occurs, `strMiscWarning` is set. This string is then used in `GetWarnings()` to show the alert in the `getinfo` call. This global variable is never unset anywhere, meaning that the alert will persist until restart. It also doesn't have an associated timestamp, so users can't tell via the RPC whether the warning just occurred, or if it occurred hours previously (though they could configure an `-alertnotify` to get this). Finally, the alerts are not consistently logged, so there's not always a possibility to look there for a timestamp.

We should add a timestamp to the message, or store a timestamp beside it, so that when the warnings are printed in the RPC, they have an associated timestamp.

**Comment by str4d** [comment]
Upstream refactored the warning code in bitcoin/bitcoin#9236, to something along the lines of what I was imagining we'd do for this, so we should pull in that PR.

**Comment by daira** [comment]
I don't see that PR doing what @str4d asked for in the description of this ticket.

**Comment by oxarbitrage** [comment]
Thank you @daira , i overlooked. 

The global variable issue is resolved by the mentioned PR but the timestamp requested still need to be added.

I created a pr to do so at https://github.com/zcash/zcash/pull/4570
