### ISSUE TITLE
Cannot install Zcash: no valid OpenPGP data found

### ISSUE THREAD

**Issue by Maixmko** [zcash/zcash#2789]
### Describe the issue
Problem installing install zcash

### Can you reliably reproduce the issue?
Following the official gyideline

#### If so, please list the steps to reproduce below:
$ wget -qO - https://apt.z.cash/zcash.asc | sudo apt-key add -

### Expected behaviour
Should add the key

### Actual behaviour + errors
gpg: no valid OpenPGP data found.

This response is observed from several independent Ubuntu machines from different private network spaces.

### The version of Zcash you were using:
Latest

### Machine specs:
- OS name + version: Ubuntu 16.04
- CPU: 
- RAM: 8Gb
- Disk size: 250 Gb
- Disk Type (HD/SDD): SDD
- Linux kernel version (uname -a): Linux argo 4.4.0-101-generic #124-Ubuntu SMP Fri Nov 10 18:29:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Compiler version (gcc -version): gcc (Ubuntu 5.4.1-2ubuntu1~16.04) 5.4.1 20160904

**Comment by stefanomarty** [comment]
I can confirm https://apt.z.cash/ is not accepting requests (ERR_CONNECTION_REFUSED).

As a consequence, apt-get is not updating the repository (package repository added as explained [here](https://github.com/zcash/zcash/wiki/Debian-binary-packages)), and you cannot get the zcash.asc key.

I tried the Tor alternative on tor+http://zcaptnv5ljsxpnjt.onion/ but it looks like there's just a plain vanilla ngnix there, no key, no packages as well.

**Comment by arcalinea** [comment]
This was due to an update of nginx that changed some conf files. After the issues was reported by several users, we fixed the configuration, and the apt server is once again functioning normally. Thank you for reporting this!
