### ISSUE TITLE
Inconsistent results from getbalance commands

### ISSUE THREAD

**Issue by letonchanh** [zcash/zcash#2791]
I was playing with my zcash testnet and when I tried several getbalance commands, they returned inconsistent results. I attached a screenshot to illustrate the problem. My wallet has 4 t_addresses and 1 z_address. When I checked the balance of each address separately, their total is 553.12500000, while the getbalance command returns 1561.24998070 and z_gettotalbalance returns a total of 1458.12499774. They are all different numbers. Is there any explanation for this inconsistency?

Thank you.

![capture](https://user-images.githubusercontent.com/5548342/33783918-55cc3b14-dc91-11e7-93fe-763d48c578f8.JPG)

**Comment by bitcartel** [comment]
If you run `zcash-cli -regtest getnewaddress` and then check the balances again, what do you see?

**Comment by ioptio** [comment]
Closing this ticket due to lack of response. Feel free to reopen if the issue is still happening.
