### ISSUE TITLE
Slow syncing on HDD, default dbcache should be increased

### ISSUE THREAD

**Issue by aprx4** [zcash/zcash#2793]
I notice that `zcashd` and `zcash-cli` RPC commands become very unresponsive after started syncing for a while. Blocks syncing is also slow. Everything goes smoothly again if I set `dbcache` parameter to much higher number. My SSD laptop is running Windows so I can't test if it has same issue, but I guess default `dbcache` setting (100MB) on `zcashd` is too low for HDD.

My desktop PC specs: i7 7700k, 32GB of RAM, 1TB HDD. Ubuntu 17.10.

I don't know if anyone having same experience on HDD machine, but I guess default `dbcahe` setting might be the problem and should be increased.

**Edit:** I realized that Zcash is forked from Bitcoin Core 0.11.2 but from 0.13 this default `dbcache` was bumped to 300MB and then again to 450MB. However in Zcash it is still 100.

**Comment by bitcartel** [comment]
Thanks, will take a look!
