### ISSUE TITLE
transaction has not been confirmed

### ISSUE THREAD

**Issue by ucwong** [zcash/zcash#2801]
![image](https://user-images.githubusercontent.com/22344498/34051046-11060b60-e1f8-11e7-9a6b-b637bfb21d5f.png)
f52713fabebfd8f4742e2ad7de444ebbfbd71c7d62e9aea44568c20f9ea0a019

**Comment by daira** [comment]
According to https://minergate.com/blockchain/zec/transaction/f52713fabebfd8f4742e2ad7de444ebbfbd71c7d62e9aea44568c20f9ea0a019 there is no such transaction in the mempool or any block, so it has not propagated.

**Comment by ucwong** [comment]
@daira But this tx is successful  in my node's mempool.

**Comment by ioptio** [comment]
If there were a lot of inputs into the transaction, it could be large enough for some miners to not include it in blocks. This should eventually be mined, though. We're working on addressing issues with large transactions via https://github.com/zcash/zcash/pull/2797

**Comment by arcalinea** [comment]
If you shut off the node and restart, your local mempool should be flushed, the funds should be returned to your wallet, and you can try creating the transaction again. 

If this doesn't work, you can try restarting the node with `-reindex`.

**Comment by ioptio** [comment]
Closing this ticket. Reopen if you have more information.
