### ISSUE TITLE
REQUEST: Add Centos 7 build 

### ISSUE THREAD

**Issue by jerodmoore** [zcash/zcash#2817]
### Describe the issue
Create distribution for Centos 7 

Suggested install behavior:

sudo vim /etc/yum.repos.d/zcashd.repo

[zcash]
name = Zcash
baseurl = https://yum.z.cash/XXX/centos7-amd64
gpgkey=https://yum.z.cash/RPM-GPG-KEY-Zcash
gpgcheck=1

yum update
yum install zcash
zcash-fetch-params

Enter RPCUSER: XXXXXXX
Re-Enter RPCUSER: XXXXXXX
.......
Generating RPCUSERPASSWORD....
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
You can change your RPCUSERPASSWORD at any time in ./path/zcash.conf
You can use service zcashd start | stop | restart 
Find more commands with zcashd --help
Press Enter to Accept and Start zcashd
........

### Machine specs:
- OS name + version: Centos 7
- CPU: -- 
- RAM: --
- Disk size: --
- Disk Type (HD/SDD): --
- Linux kernel version (uname -a): current
- Compiler version (gcc -version): --

**Comment by str4d** [comment]
We have a CI builder for CentOS 7: https://ci.z.cash/#/builders/13

The first step towards making it a supported build would be getting this to pass all tests :smiley:

Side-note: it isn't necessary to set `rpcuser` or `rpcpassword` any more, because we have random-cookie authentication (#1999). It is simply sufficient to have a (possibly-empty) `zcash.conf` present.

**Comment by daira** [comment]
Related to #1053.

**Comment by mdr0id** [comment]
@jerodmoore There exists a couple options to compile on CentOS 7, or use a container variant. Please let us know if you like details regarding this. As str4d mentioned, once we have integrated this into CI we can provide more formal yum packages.

**Comment by mms710** [comment]
We need to address the issues with our CentOS 7 builders. This is in the team's backlog.

**Comment by str4d** [comment]
We haven't had a CentOS 7 builder for some time now (it didn't survive the death of Buildbot). If someone still wants this (especially given that we are dropping CentOS 8 support in #6340), they should comment here.

**Comment by daira** [comment]
Since no-one has expressed interest, we can close this.
