### ISSUE TITLE
Update license information for files under build-aux/m4

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2827]
https://github.com/zcash/zcash/blob/master/build-aux/m4/l_atomic.m4#L4 says that file is sourced from http://bugs.debian.org/797228 , which in turn references this file from Filezilla: https://svn.filezilla-project.org/filezilla/FileZilla3/trunk/m4/check_atomic.m4?revision=6938&view=markup&pathrev=6938

Filezilla is [GPLv2-licensed](https://svn.filezilla-project.org/filezilla/FileZilla3/trunk/COPYING?view=markup), and I cannot find any exception for the license of the Autoconf macros it uses.

This is a problem because the GPLv2 license affects everything else. Note that the output of the macro is arguably *also* implicitly GPLv2-licensed as a derived work of the macro (since there's no exception that would exclude it from being so licensed). I think we need to replace this file, or get permission to include it under a more permissive license.

**Comment by daira** [comment]
Some other files in that directory:
* ax_check_compile_flag.m4;
* ax_check_link_flag.m4;
* ax_check_preproc_flag.m4
* ax_openmp.m4
* ax_pthread.m4
are licensed under GPLv3 with an "Autoconf Macro exception" which looks like this:
```
 As a special exception, the respective Autoconf Macro's copyright owner
 gives unlimited permission to copy, distribute and modify the configure
 scripts that are the output of Autoconf when processing the Macro. You
 need not follow the terms of the GNU General Public License when using
 or distributing such scripts, even though portions of the text of the
 Macro appear in them. The GNU General Public License (GPL) does govern
 all other use of the material that constitutes the Autoconf Macro.

 This special exception to the GPL applies to versions of the Autoconf
 Macro released by the Autoconf Archive. When you make and distribute a
 modified version of the Autoconf Macro, you may extend this special
 exception to the GPL to apply to your modified version as well.
```
Since we're distributing the macros, not just their outputs, it's not clear whether this gets us off the hook for those files.

**Comment by daira** [comment]
bitcoin_find_bdb.m4 and bitcoin_subdir_to_include.m4 have no licence text. They look as though they might have been written by Bitcoin Core but I can't be sure.

**Comment by str4d** [comment]
Based on https://github.com/bitcoin/bitcoin/pull/8784 those files are all available under the MIT license; we should pull in that PR to make it clear.

**Comment by daira** [comment]
bitcoin/bitcoin#8784 addresses the problems with l_atomic.m4 and the files that currently have no specific license. However, the 5 files mentioned in https://github.com/zcash/zcash/issues/2827#issuecomment-353473175 are still under GPLv3 with the Autoconf Macro exception. In particular, for these files,

> The GNU General Public License (GPL) does govern all other use of the material that constitutes the Autoconf Macro.

IANAL, but as I read this the viral aspect of the GPL (clause 5 c) of the GPLv3) still applies to the whole of any work that includes these macros:

> You must license the entire work, as a whole, under this License to anyone who comes into possession of a copy. This License will therefore apply, along with any applicable section 7 additional terms, to the whole of the work, and all its parts, regardless of how they are packaged. This License gives no permission to license the work in any other way, but it does not invalidate such permission if you have separately received it.

I'm not sure that this was intended. It makes a large portion of the macros in the Autoconf Archive questionable for use in permissively licensed projects, unless you run [autogen](https://www.gnu.org/software/autogen/) only once and consider the resulting output to be the source (i.e. never run autogen on those m4 files again).

**Comment by daira** [comment]
The Autoconf maintainers seem to have been aware of this problem (since 2005): https://lists.gnu.org/archive/html/ac-archive-maintainers/2005-01/msg00030.html
(The page on gnu.org linked from that email has moved [here](https://www.gnu.org/prep/maintain/html_node/License-Notices-for-Other-Files.html).) At that point most of the macros that we have ended up using were changed to the "simple all-permissive license". So it's possible that the 5 macros I mentioned have also been relicensed at some point, but I haven't checked.

**Comment by daira** [comment]
See also the thread starting here: https://lists.gnu.org/archive/html/ac-archive-maintainers/2005-01/msg00161.html

**Comment by daira** [comment]
This blocks on getting permission from the authors of the 5 macros mentioned. Those authors are:
* Guido U. Draheim \<guidod at gmx.de> (ax_check_{compile,link,preproc}_flag)
* Maarten Bosmans \<mkbosmans at gmail.com> (ax_check_{compile,link,preproc}_flag)
* Steven G. Johnson \<stevenj at alum.mit.edu> (ax_openmp, ax_pthread)
* John W. Peterson \<jwpeterson at gmail.com> (ax_openmp)
* Nick R. Papior \<nickpapior atgmail.com> (ax_openmp)
* Daniel Richard G. \<skunk at iSKUNK.ORG> (ax_pthread)

**Comment by daira** [comment]
Template for permission request:

----

Hi \<name>,

I'm writing on behalf of the Zcash project (https://z.cash).

Your autoconf macros \<names of macros> are currently included in several
software projects, including Zcash, Bitcoin, and probably other Bitcoin forks,
that are distributed under the MIT license.

It recently came to our attention that the license of these macros is GNU GPLv3
with the "Autoconf license exception", which does not clearly allow redistribution
under the MIT license. Although the wording of the Autoconf license exception gives
"unlimited permission to copy, distribute and modify the configure scripts that are
the output of Autoconf when processing the Macro", this doesn't apply to the macro
source itself. In the case of Zcash, Bitcoin, and their forks, the current build system
requires the macro source rather than its output. Our issue ticket about this is at
\<https://github.com/zcash/zcash/issues/2827>.

In January 2005, most of the macros in the Autoconf macro archive were relicensed,
with permission of their respective authors, to allow redistribution in permissively
licensed software projects. The related thread on the Autoconf archive mailing
list can be read at
\<https://lists.gnu.org/archive/html/ac-archive-maintainers/2005-01/msg00030.html>.
The page on gnu.org linked from that email has moved to
<https://www.gnu.org/prep/maintain/html_node/License-Notices-for-Other-Files.html>.
However, your macros either weren't in the archive in 2005 or weren't
relicensed with the others.

I would like to request your permission to redistribute these macros under the
terms of either the "Simple all-permissive license":

    Copying and distribution of this file, with or without modification,
    are permitted in any medium without royalty provided the copyright
    notice and this notice are preserved.  This file is offered as-is,
    without any warranty.

or the MIT license (please indicate which).

Thanks in advance.

**Comment by daira** [comment]
Note: ax_openmp isn't used in Bitcoin (although it is used in Zcash forks), so I'll modify the wording of the emails to John W. Peterson and Nick R. Papior accordingly.

**Comment by daira** [comment]
Pinging the copyright holders on Github (I think these are the right people) in case the emails don't get through: @gdraheim @mkbosmans @stevengj @jwpeterson @zerothi @iskunk

**Comment by zerothi** [comment]
First, thanks for your careful follow up on the licence issue.

From my perspective, you are granted to redistribute and use the source under whichever licence you prefer. So long as the notification of my contribution stays. 

Nick R. Papior

**Comment by jwpeterson** [comment]
You have my permission to redistribute under either the "Simple all-permissive license" or MIT, though it looks like I only changed 1 line of the macro in question 😄 .

**Comment by daira** [comment]
I received this by email:

> I don't care about a specific license, you may choose as you like. MIT sounds fine.
> - best regards, Guido Draheim.

**Comment by stevengj** [comment]
I think you may be misunderstanding the GPL in general (or rather, copyright law) and the autoconf macro exception in particular.  The GPL only applies to your work if your code is a *derived work* of the GPLed code.  Here, this only applies to the `configure` script (which falls under the autoconf macro exception), not to your other code.

For example, consider the `ax_openmp.m4` macro, originally written by me, which determines what compiler flags are required to compile code with OpenMP:

* The code in the GPLed `ax_openmp.m4` is directly incorporated into the `configure` script produced by `autoconf`, and so the `configure` script is unquestionably a derived work of `ax_openmp.m4` under US copyright law.  Hence, the `configure` script would normally be governed by the terms of the GPL.  However, the "autoconf macro exception" attached as an addendum to the ax_openmp.m4 license specifically exempts the `configure` scripts from the usual GPL restrictions.

* Neither code in your `src` directory nor the compiled `zcash-cli` executable (etcetera) incorporates or links to any part of `ax_openmp.m4`, as far as I can tell.  So, `zcash-cli` is *not* a derived work of `ax_openmp.m4` and hence the license of `ax_openmp.m4` is irrelevant to it.

* Of course, you distributing `ax_openmp.m4` alongside your `zcash` source code.  But the GPL terms explicitly exempt "mere aggregation" — simply distributing another work X alongside a GPLed work Y does *not* make X subject to the license of Y if X does not derive from or link to Y in such a way as to make X a derived work of Y under copyright law.

**Comment by iskunk** [comment]
Hi @stevengj,

I've been in communication with Daira via e-mail, and have been telling him the same thing (albeit not as succinctly as you). None of us here are as sharp as the debian-legal eagles, and at this point in time, about the only way anyone should believe there is an actual licensing problem with Autoconf[-Archive macros] and permissively-licensed projects is if RMS himself says so.

Daira expressed an interest in having the Zcash distribution be MIT licensed through-and-through (build system and all), not due to actual licensing issues but for subjective uniformity. I responded that he's welcome to do this, but I am not interested in helping with such a goal.

(Steven, on an unrelated note: This is literally the first time I've ever seen you respond about your Autoconf macros. Could you verify that your alum address is forwarding correctly?)

**Comment by daira** [comment]
#3505 adds several more files that are under the GPLv3-or-later with "Autoconf license exception":

* build-aux/m4/ax_compiler_vendor.m4 (copyright Steven G. Johnson \<stevenj@alum.mit.edu\>, Matteo Frigo, and John Zaitseff \<J.Zaitseff@zap.org.au\>)
* build-aux/m4/ax_gcc_archflag.m4 (copyright Steven G. Johnson, Matteo Frigo, Tsukasa Oi, and Alexey Kopytov)
* build-aux/m4/ax_gcc_x86_cpuid.m4 (copyright Steven G. Johnson, Matteo Frigo, and Michael Petch \<mpetch@capp-sysware.com\>)

Supposing that we accept the argument made above by Steven G. Johnson, the `contrib/debian/copyright` file still needs to be updated.
