### ISSUE TITLE
Improve serialization of MerklePath

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#2831]
`MerklePath` contains vectors of `bool`. Currently, these are [directly serialized](https://github.com/zcash/zcash/blob/master/src/zcash/IncrementalMerkleTree.hpp#L15), which causes the `bool`s to be converted to `char`s [](https://github.com/zcash/zcash/blob/master/src/serialize.h#L230). This is an ambiguous serialization ([which prevents the MacOS CI builder from building](https://ci.z.cash/#/builders/16/builds/91/steps/3/logs/stdio)), but is also very inefficient. A more efficient format would be to use bit arrays ([see e.g. `CPartialMerkleTree` uses](https://github.com/zcash/zcash/blob/master/src/merkleblock.h#L91-L104)). If we needed to reconstruct exactly (rather than rounding up to a multiple of 8), we could serialize the original length before the bit vector.

One question I haven't yet determined the answer to is, where is `MerklePath` actually serialized? If it is being used, then migration will be trickier. If it isn't being used, then do we even need any code here? I don't currently recall whether #2120 (which *does* serialize related structures) might start using it.

**Comment by str4d** [comment]
As always, the quickest way to figure out what uses something is to remove it and see what breaks! Here is the only compile error I get:

```
In file included from gtest/test_merkletree.cpp:16:0:
./serialize.h: In instantiation of ‘void Serialize(Stream&, const T&, long int, int) [with Stream = CBaseDataStream<std::vector<char, zero_after_free_allocator<char> > >; T = libzcash::MerklePath]’:
./streams.h:286:20:   required from ‘CBaseDataStream<SerializeType>& CBaseDataStream<SerializeType>::operator<<(const T&) [with T = libzcash::MerklePath; SerializeType = std::vector<char, zero_after_free_allocator<char> >]’
gtest/json_test_vectors.h:39:9:   required from ‘void expect_test_vector(T&, const U&) [with T = const UniValue; U = libzcash::MerklePath]’
gtest/test_merkletree.cpp:121:39:   required from ‘void test_tree(UniValue, UniValue, UniValue, UniValue, UniValue) [with Tree = libzcash::IncrementalMerkleTree<4ul, libzcash::SHA256Compress>; Witness = libzcash::IncrementalWitness<4ul, libzcash::SHA256Compress>]’
gtest/test_merkletree.cpp:201:146:   required from here
./serialize.h:573:5: error: ‘const class libzcash::MerklePath’ has no member named ‘Serialize’
     a.Serialize(os, (int)nType, nVersion);
     ^
cc1plus: error: unrecognized command line option ‘-Wno-builtin-declaration-mismatch’ [-Werror]
cc1plus: all warnings being treated as errors
Makefile:5204: recipe for target 'gtest/zcash_gtest-test_merkletree.o' failed
```

So we can safely improve this serialization format without affecting users.

**Comment by ebfull** [comment]
I haven't looked at this, but from memory, we only made the MerklePath serializable so we could compare with test vectors easily. :)

**Comment by str4d** [comment]
That seems to be the case for now, but I need to check whether the newly-serialized `JSProofWitness` in #2120 includes a `MerklePath` anywhere.

**Comment by str4d** [comment]
I discussed this in a pairing with @ebfull, and realised that the `std::vector<std::vector<bool>> authentication_path` in `MerklePath` is actually originally a `std::vector<uint256>`, i.e. a vector of hashes. It is only converted to a vector of vector of `bool` because that is the format libsnark requires. We should store it in memory as such, and convert to the libsnark representation when we actually create a proof. There should be no performance hit, because we only create the `MerklePath` inside the libsnark circuit code, so we are just moving the point at which we perform the conversion to inside the relevant libsnark gadget.

**Comment by str4d** [comment]
The `std::vector<bool> index` in `MerklePath` could be converted to a `std::vector<unsigned char>`, but could also just be converted into a `uint64_t` (which inherently puts a limit of 64 on the Sprout depth).

**Comment by daira** [comment]
I would like us to think of positions in the tree as integers because:
* that is how the protocol specification represents them;
* it avoids any ambiguity in bit ordering; if you think of a position as a bit sequence specifying which path to take then it could be ordered either leaf-to-root or root-to-leaf, but if you think of it as an integer then there is only one sensible representation :&ndash; the index at the leaf layer;
* the Sapling circuit uses the position as an integer in the specification of how ρ is computed (i.e. ρ = cm + [pos] J).
