### ISSUE TITLE
User guide provides no way to list t-addresses with zcash-cli

### ISSUE THREAD

**Issue by FlorinAndrei** [zcash/zcash#2834]
Regarding the wiki here: https://github.com/zcash/zcash/wiki/1.0-User-Guide

If you're completely new to Zcash, a basic question you need to answer is - what are my current t-addresses? This question is not answered in the guide.

Please add some info about that, such as running:

```
./src/zcash-cli getaddressesbyaccount ""
```

It should be added at the top of the `Using Zcash` section, before the `Generating a t-addr` paragraph, because most users will go ahead and generate a new address without realizing that they may already have one. I know I made that mistake.

**Comment by daira** [comment]
Added at https://github.com/zcash/zcash/wiki/1.0-User-Guide#using-zcash
