### ISSUE TITLE
valgrind reports 519 memory leaks on zcashd

### ISSUE THREAD

**Issue by rex4539** [zcash/zcash#2835]
### Describe the issue
valgrind reports 519 memory leaks on zcashd

### Can you reliably reproduce the issue?
Yes, 100% reproducible.

#### If so, please list the steps to reproduce below:
`valgrind --leak-check=full --show-leak-kinds=all zcashd`

### Expected behaviour
No leaks.

### Actual behaviour + errors
519 leaks.

### The version of Zcash you were using:
Zcash Daemon version v1.0.14-rc1-8912a064-dirty

### Machine specs:
- OS name + version: macOS 10.13.3 (17D25b)
- CPU: Intel Core i7 2,2GHz
- RAM: 8GB
- Disk size: 250,14GB
- Disk Type (HD/SDD): SSD
- Linux kernel version (uname -a): Darwin Kernel Version 17.4.0: Mon Dec 11 21:15:27 PST 2017; root:xnu-4570.40.9~4/RELEASE_X86_64 x86_64
- Compiler version (gcc -version): Apple LLVM version 9.0.0 (clang-900.0.39.2)

### Any extra information that might be useful in the debugging process.
[valgrind leaks zcashd.log](https://github.com/zcash/zcash/files/1584092/valgrind.leaks.zcashd.log)

### Do you have a back up of `~/.zcash` directory and/or take a VM snapshot?
Yes

**Comment by shwuhk** [comment]
I think this issue may be the same as mine. #2825

**Comment by bitcartel** [comment]
Thanks for the report.  We'll track this in ticket #2825 for now.

**Comment by daira** [comment]
Note that the vast majority of the valgrind-reported leaks are for totally insignificant amounts of memory, that are intentionally not tracked.

**Comment by mdr0id** [comment]
To Daira's point : 

(from attached valgrind log)
```
==45271== LEAK SUMMARY:
==45271==    definitely lost: 32 bytes in 2 blocks
==45271==    indirectly lost: 4,096 bytes in 2 blocks
==45271==      possibly lost: 72 bytes in 3 blocks
==45271==    still reachable: 1,226,352 bytes in 1,006 blocks
==45271==         suppressed: 24,450 bytes in 164 blocks
```
Besides the `definitely lost` category , the other leaks from this report would need to be further profiled to gauge whether or not they are even valid.

**Comment by mdr0id** [comment]
Closing since other tickets encompass this context (e.g. #3135 & #2825 ).

Valgrind verification data will be provided from CI, in the coming sprints.
