### ISSUE TITLE
Where i can download the latest node indexes

### ISSUE THREAD

**Issue by ApeZhangz** [zcash/zcash#2837]
Local wallet synchronized too slow, 60% cost nearly 5 days, can i download the latest node indexes any where?

**Comment by ioptio** [comment]
Can you confirm the slowness is due to download speed? Because I think the sync process bottlenecks more on the verifying side.

**Comment by rex4539** [comment]
Took me a couple of days to sync thr blockchain.

But if you kept syncing since the original post, you should be at 100% by now :)

**Comment by bitcartel** [comment]
User is probably synced by now.  Re-open the ticket if not.
