### ISSUE TITLE
This still assembling since 12.21.17

### ISSUE THREAD

**Issue by cwrocksnyc** [zcash/zcash#2840]
This issue tracker is only for technical issues related to zcashd.

General Zcash questions and/or support requests and are best directed to the [Zcash Forums](https://forum.z.cash) or [Community Rocket.Chat](https://chat.zcashcommunity.com).

For reporting security vulnerabilities or for sensitive discussions with our security team, please contact [security@z.cash](mailto:security@z.cash). You can use the [GPG key](https://z.cash/gpg-pubkeys/security.asc) (fingerprint: `AF85 0445 546C 18B7 86F9  2C62 88FB 8B86 D8B5 A68C`) to send an encrypted message. The key and fingerprint are duplicated on our [Public Keys page](https://z.cash/support/pubkeys.html).

### Describe the issue
Please provide a general summary of the issue you're experiencing

#### If so, please list the steps to reproduce below:
1. 
2. 
3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour + errors
Tell us what happens instead including any noticable error output (any messages displayed on-screen when e.g. a crash occurred)

### The version of Zcash you were using:
Run `zcashd --version` to find out

### Machine specs:
- OS name + version:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):
- Linux kernel version (uname -a):
- Compiler version (gcc -version):

### Any extra information that might be useful in the debugging process.
This includes the relevant contents of `~/.zcash/debug.log`. You can paste raw text, attach the file directly in the issue or link to the text via a pastebin type site.
Please also include any non-standard things you did during compilation (extra flags, dependency version changes etc.) if applicable.

### Do you have a back up of `~/.zcash` directory and/or take a VM snapshot?
- Backing up / making a copy of the `~/.zcash` directory might help make the problem reproducible. Please redact appropriately.
- Taking a VM snapshot is really helpful for interactively testing fixes

**Comment by cwrocksnyc** [comment]
Hi 

I sent 15.6998 zec from my cryptonator wallet to my bittrex wallet  t1UmEzCkPGAEfouc2Pnv5CHAuQzgDDzTMdq
I finally saw that the transaction I'd is still assembling and it'd a week later. This literally cost me 4000 dollars in lost profit if nut the entire 10k. Plesse help me. I don't know what the problem is but I'm quite sure that if this got leaked out the value of zcash would plummet. And I have millions of people emails so believe me I could it very widely known. I've contacted cryptonator and bittrex in regards to this issue but have yet tiki receive a response.

Please help me get my zcash out if limbo.

Thank you

**Comment by ioptio** [comment]
I responded to your email inquiry about this. Closing this issue.

**Comment by cwrocksnyc** [comment]
I replied to the email the same day, I still haven't heard back from
Cryptonator. Maybe if I cc'ed you on the follow up email they will actually
address the question this time rather than just close the ticket even
though I tried to reply to the email is it indicates only to receive a
notice that the ticket closed early thud morning. Could you please help
me.  15.6998

**Comment by cwrocksnyc** [comment]
please help me what is going on cryptonator hasnt even replied to my support request for 2 weeks now ticket
