### ISSUE TITLE
Python-based tools for zcash

### ISSUE THREAD

**Issue by ioptio** [zcash/zcash#2841]
From third-party developer via forum DM:

Please advise if you guys have any dev tools for zcash like Gavin Andresen bitcoin tools https://github.com/harrigan/bitcointools i.e. Python-based tools but for zcash such as fixwallet.py dumpwallet.py?

We are experiencing issues with one of our hot wallets due to a hardware failure.

**Comment by bitcartel** [comment]
We don't have any tools right now but it's something that might be useful in the future.  At the moment folk will have to try and use third-party developer tools.
