### ISSUE TITLE
Transaction

### ISSUE THREAD

**Issue by 1SERZH1** [zcash/zcash#2843]
![screenshot_110](https://user-images.githubusercontent.com/20666863/34457934-40ede8a2-edc9-11e7-9f87-d3cc97386480.png)

![screenshot_61](https://user-images.githubusercontent.com/20666863/34457931-28600892-edc9-11e7-9aec-ae9c56703959.png)

![screenshot_10](https://user-images.githubusercontent.com/20666863/34457927-11a89704-edc9-11e7-93a3-353fc350ad90.png)
Hello, help me please, why the ZEC address in explorer.zcha.in and on zchain.online shows a different balance !?? Translated ZEC to the address through the exchanger 60cek.com 12/29/2017. The transaction was confirmed and the address in the purse of JAXX showed the correct balance. After checking for zchain.online, the balance appeared to be correct. When looked at explorer.zcha.in i saw the balance is not correct and shows that the address does not contain a transaction. All the operations i have done can be confirmed by screenshots of my monitor ...
![screenshot_55](https://user-images.githubusercontent.com/20666863/34457923-01e9df80-edc9-11e7-94e4-cd3710e8adf6.png)

**Comment by jasondavies** [comment]
Unfortunately <https://explorer.zcha.in> sometimes seems to have problems keeping its index updated.  I have manually checked and the balance shown in your wallet for t1cHvbRskerCamZdKQFwyVwEk8j9FrLGCAk seems correct.

**Comment by madtomic** [comment]
Sometimes, it just take time to update and reflect the correct balance.

**Comment by 1SERZH1** [comment]
Thanks for answers !!!

**Comment by daira** [comment]
Yes, the zcha.in explorer misses transactions and is unreliable for reporting balances.
