### ISSUE TITLE
I need your help - Help me recover my permanently deleted Zcash wallet 

### ISSUE THREAD

**Issue by zcashangelgood** [zcash/zcash#2844]
Hello,

I deleted a wallet accidentally without saving a form that had an encrypted z address with Zcash in it. I used EaseUS Data recovery to get a form of the wallet back that is accepted by the daemon by some extent.

This is the message it gives me:

Messages:age: Loading wallet…

Warning: Warning: error reading wallet.dat! All keys read correctly, but transaction data or address book entries might be missing or incorrect.
My question to you is - can you recover the private keys from this wallet.dat file as they are being ready correctly and I can import them into a new wallet? (This would work with the z address I hope)

Secondly, is there a way to fix this wallet? Some program I can use?

Please help me with programs and methods to help with recovering the private keys of this wallet or recover the wallet itself.

Happy New Years!

CJ

I recovered a wallet.dat file, along with wallet.dat.2017-12-xx-xx-xx - 2 of these. Upon trying to put it into VoteCoin (A Zcash relative - votecoind and votcoin-cli/vot.bat) I get an error: Messages:
- Warning: Warning: error reading wallet.dat! All keys read correctly, but transaction data or address book entries might be missing or incorrect.
  be missing or incorrect.t 'showmetrics=0' to hide]
[Press Ctrl+C to exit] [Set 'showmetrics=0' to hide]
I can use votecoin-cli to look at addresses but using validateaddress, both t addresses that were used to make a big z address transaction are not mine. Can you refer me to a recovery tool for your benefit? Can you refer me to a tool to access the wallet.d file I would like to see and get the private keys out of there to construct a new wallet with the true z address and the full balance (including 1 t address 3000x and 1 z address 20000x) and therefore restore my full wallet - I will pass on the.

This is for an AltCoin, VoteCoin - it will work well.

I tried the verifyaddress command.

{
“isvalid”: true,
“address”: “txxx”,
“scriptPubKey”: “xyz”,
“ismine”: false,
“iswatchonly”: false,
“isscript”: false
}

The quote is "" good.

**Comment by daira** [comment]
Use the ``z_exportwallet`` command as described [here](https://github.com/ioptio/zcash/blob/4088ac68dbabb0216e1fb008c19cb81d6292abfd/doc/wallet-backup.md#using-z_exportwallet--z_importwallet), then stop zcashd, switch to the new wallet, and use ``z_importwallet`` to reimport those keys. Good luck.

**Comment by zcashangelgood** [comment]
Thank you Daira - I have an update for you. I believe I have found the true proper wallet that includes the zaddress - the wallet I was speak of above was the first version of the wallet that did not include the zaddress that was made in the wallet and received coins.

When I open that wallet, instead of being accessible to some extent as the above post was describing, I couldn't find what the wallet was saying and so I found a new wallet that enabled me to try to open it but I got the: Age: Error -17 and then the entire zcashd just shut down, the same as that kept happening when I reopened and reopened the file.

Now, I heard that I can briefly use zcash-cli to z_exportwallet in a very minute windows before zcashd shuts down with the new corrupt wallet to glean the private keys (including the one for the z address) into a text file.

My question to anyone is this: every time I try z_exportwallet it keeps saying:

error code: -4
error message:
Cannot export wallet until the zcashd -exportdir option has been set

I have tried running zcashd with the -exportdir from the cmd line in windows along with trying, zcashd -exportdir test but I still get the same error.

Can someone help me with how -exportdir works as it's hard to find this information easily online.
What can I do to make error code: -4 go away and be able to export my wallet? Thank you.

I appreciate your help very much so and think you're a great person.

**Comment by str4d** [comment]
That is a safety measure to prevent you accidentally overwriting important files. Run `zcashd` with the argument `-exportdir=/path/to/some/directory`, where `/path/to/some/directory` should be the directory you want to export the wallet into. I would recommend making a new directory for this purpose.

**Comment by arcalinea** [comment]
Hi @zcashangelgood , did setting the `exportdir` as str4d suggested fix this issue?

**Comment by arcalinea** [comment]
There's an RPC error that returns -17, could this have been it?
```
    RPC_WALLET_ALREADY_UNLOCKED     = -17, //! Wallet is already unlocked
```

**Comment by zcashangelgood** [comment]
![votecoinprob6](https://user-images.githubusercontent.com/34976877/34508499-fc039cbc-f0a4-11e7-9084-fb0d9edced9c.png)
![votecoinprob7](https://user-images.githubusercontent.com/34976877/34508501-fd024848-f0a4-11e7-8848-590a7aa9cc03.png)

Error 17 - the wallet cannot even load. Regardless of using the -exportdir =votecoin/

the votecoind isn't open long enough to do anything with the votecoin-cli and I am in windows which makes it much slower to try fast grabs. I feel I could make a macro on linux to pull votecoind dumpwallet (which would theoretically dump the t and z address priv keys) otherwise I need some help. If someone could show me - how would I make said macro?

Any other ideas. I appreciate your computer insight and your will to work on amazing problems.

**Comment by ioptio** [comment]
Can you please dump your debug log into a gist? Make sure you set debug=1 in your config file.

**Comment by ioptio** [comment]
I'm going to close this ticket due to lack of response. Feel free to reopen if you have further information.
