### ISSUE TITLE
Sending ZEC from z-addr to t-addr getting slow over time.

### ISSUE THREAD

**Issue by miningpoolhub** [zcash/zcash#2856]
### Describe the issue
I am running a zcash mining pool.

I move mined rewards in this order.
mining t-addr -> z-addr -> pool's main t-addr to distribute -> miners

The problem is that z-addr -> pool's main t-addr to distribute is getting slow over time.
Last transaction took 3 days but did not finish so I had to kill it.
It worked well at first but I ran it for many weeks and it's unbelievable slow.
I think it's because of so many UTXO in z-addr that can not be grouped easily.

#### If so, please list the steps to reproduce below:
1. run zcash
2. send 100 ZEC z-addr to t-addr many times.

### Expected behaviour
It should work in few minutes or hours, not days.

### Actual behaviour + errors
It's getting slow everyday. Now it doesn't finish at all for 3 days on modern cloud hardware.

### The version of Zcash you were using:
1001350

### Machine specs:
- OS name + version: Ubuntu 16.04
- CPU: 8 core.
- RAM: 16G
- Disk size: 160GB
- Disk Type (HD/SDD): SSD
- Linux kernel version (uname -a): Linux xxx 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- Compiler version (gcc -version): gcc (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609

I'm moving 100 ZEC for every try.
I think it would take less time if I lower this value but I doubt that it will not solve the core problem.
I don't know how UTXO lies internally with zk-snark.
What is the recommend practice for it?

1) Do I have to flush and make new z-addr every few month to avoid this?
2) Is it okay to send 5~10 ZEC from z-addr to t-addr several times? Or would it make things worse over time? (plenty of small separated transactions)
3) Send all z-addr amounts to t-addr except fee(0.0001)?
I don't need to leave some amounts in z-addr. I just need them all moved eventually

Any adivce would be helpful.

**Comment by daira** [comment]
The shielded equivalent of a UTXO is called a "note". If you send funds from a z-addr to a t-addr and the amount (including fee) does not exactly use up a note, then the change will go back to the z-addr. If you're also sending funds to that z-addr, then the number of notes associated with the address will increase over time, which may cause the slowdown you've seen.

Tickets intended to address this include #2493, #1961, and #1360.

**Comment by miningpoolhub** [comment]
ah.. I understand. Is there any workaround for now?
I can't even find my unspent transactions because there's no z_listunspent api call.
z_listreceivedbyaddress is giving me +10000 txid and it doesn't help this situation.

I also tried z_mergetoaddress from str4d repo but it doesn't seem to work yet.
Giving me "logic error: input note not authorized to spend with given key"

**Comment by bitcartel** [comment]
Ignoring fees...

You can call `z_shieldcoinbase` to shield N coinbase utxos to your zaddr, e.g. N=140 (data on the blockchain indicates that FlyPool have a limit around 150 using the mempooltxinputlimit option, but other miners do not and accept tx with higher number of inputs).  This creates 1 transaction, consuming N coinbase utxos, and generating 1 note.

I would recommend than using `z_sendmany` to spend that entire note value, so there is no change, to your transparent payout address.  From there, you can use transparent sendmany operation to payout your members.

z_mergetoaddress, once finished, can help clean up your notes by merging them to a single address.  However, if you have many small notes, it will still take time to do this.

I agree and think we need to implement z_listunspent to help diagnose these issues.  Before launch we did discuss having a low-level note RPC interface but it dropped down the priority list as few users were expected to use such calls.

**Comment by ioptio** [comment]
@miningpoolhub does `z_mergetoaddress` help you here?

**Comment by ioptio** [comment]
Let us know if `z_mergetoaddress` wasn't the solution for you and feel free to reopen the issue to continue discussion.
