### ISSUE TITLE
Please help me I lost 15.6698 zec

### ISSUE THREAD

**Issue by cwrocksnyc** [zcash/zcash#2857]
Hi

I sent 15.6698 zcash on Dec 21 2017, it still stays tx id assembling check back later on cryptonator and I sent it to bittrex who never recieved it. I think I figured out the problem appartently there was a space at the end of the wallet and I think that perhaps that space sent it to an invalid wallet. Please tell me there is some way to retrieve my zec? Its a huge amount of money for me I was just about to cash it out thats why I was sending it and for longest time I have been trying to get it back. Does anyone know what I can do???

**Comment by daira** [comment]
Do you hold the private keys to the funds that were sent, or does Cryptonator?

If you hold the keys, and the transaction was never sent, then it should be possible to retrieve the funds.

If Cryptonator holds the keys, then your only recourse is with Cryptonator's user support.

Please note that in general we can't provide support for third-party wallets, especially on-line wallets.

**Comment by ioptio** [comment]
Closing this ticket. Feel free to reopen if you have more information.
