### ISSUE TITLE
[Sapling] Specify what spend authorization signatures cover

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2859]
We intend to use an EdDSA signature on the Jubjub curve to authorize each spend. See #2853 for the cryptographic specification of the signature scheme. This ticket is to specify precisely what these signatures cover.

**Comment by daira** [comment]
Section 4.6 of the protocol spec describes this for Sprout, but is a bit vague.

**Comment by daira** [comment]
Section 4.6 of the protocol spec describes this for Sprout, but is a bit vague.

**Comment by daira** [comment]
See also #2907 which covers changes to the sighash algorithm.

**Comment by arielgabizon** [comment]
Please,please,please let's just sign the whole transaction including all scriptsigs in transparent inputs, to easily get non-malleability for transactions containing a shielded part.  This will also make life easier in the security proof.

**Comment by arielgabizon** [comment]
(Everything except the signatures of other inputs)

**Comment by daira** [comment]
This is done in the 2018.0-beta-16 spec.
