### ISSUE TITLE
Testing plan for tx format modifications

### ISSUE THREAD

**Issue by arcalinea** [zcash/zcash#2860]
When the transaction format is modified, hardcoded hashes such as the asserts in `chainparams.cpp` and in test cases will break. 

Need a plan for how to test tx format changes. Do we change all the test cases for the new formats? Do we specify which tests will run on which tx version number? Need to have plan in place for future network upgrades, as Sapling will also modify tx format again.

**Comment by str4d** [comment]
#2966 covers this ticket.
