### ISSUE TITLE
[Sapling] Raise the 100000-byte tx size limit

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2864]
Before launch we imposed a consensus rule limiting the size of a transaction to 100000 bytes (Bitcoin already had this limit as a standard rule). #1475 #1501

A substantial part of the rationale for this limit was the quadratic hashing problem. Overwinter will fix that problem, so it isn't clear that 100000 bytes will still be the right limit at that point. We should consider raising it (which we can do straightforwardly because Overwinter is a bilateral hard fork).

**Comment by bitcartel** [comment]
Related: increase the block size, benchmark, to determine potential improvement to overall throughput of system.

**Comment by str4d** [comment]
Concept ACK, if we have time. Our [large transaction benchmark](https://speed.z.cash/timeline/?exe=1&base=1%2B178&ben=time+validatelargetx&env=1&revs=50&equid=off&quarts=on&extr=on) should improve significantly once the SigHash changes land, at which point we can look into raising this limit.

**Comment by daira** [comment]
This would eliminate all the code that currently estimates transaction size before trying to create a transaction.
