### ISSUE TITLE
Zcashd binary not working on CentOS 7

### ISSUE THREAD

**Issue by got3nks** [zcash/zcash#2866]
```
[zcash@local ~]$ ./zcashd
./zcashd: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./zcashd)
./zcashd: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./zcashd)
```

**Comment by per-gron** [comment]
If it's not obvious: This error means that the version of stdlibc++ used when building zcashd is newer than the version installed on the machine where this error was generated. The quickest way to fix this is probably to install a newer version of libstdc++.

A more permanent fix would be to link zcashd statically against libstdc++. AFAIK this is safe if zcashd does not depend on any system-provided shared library that has C++ in it (it might be safe even then but it's less obviously safe). If the linking step is invoked with `g++`, the `-static-libstdc++` flag can be used (that flag is a no-op if there only is a shared libstdc++ on the machine that does the linking). If `g++` is not used, `-l:libstdc++.a` should do the trick.

**Comment by daira** [comment]
Linking zcashd statically against libstdc++ is a surprisingly deep rathole. I would love to, but see #2513. The problem that eventually blocked me was getting the resulting executable to pass the security-hardening check, which requires PIE.

**Comment by str4d** [comment]
Also of note: CentOS 7 builds were broken somehow by #2771 ([before](https://ci.z.cash/#/builders/13/builds/162), [after](https://ci.z.cash/#/builders/13/builds/163)), so if that isn't fixed in the next few weeks, 1.0.15 will not be buildable on CentOS 7 (which is not technically a regression, as it is still an unsupported platform, but it's not great).

**Comment by per-gron** [comment]
#2891 links statically against libstdc++ and libgomp, and it does so by using a reproducibly built libgomp.a (and libstdc++.a) with -fPIC. The toolchain build script could be of independent value in case the whole Bazel PR is not used: https://github.com/per-gron/zcash-toolchain

**Comment by mdr0id** [comment]
@got3nks The functionality of the zcashd binary has been verified on CentOS 7. There are a few minor steps needed prior to building this. These steps will be in an upcoming documentation update. Please let us know if you still encounter issues with the binary. 

(Please note: CentOS 7 is not a fully supported platform at the current time, but we hope to have this resolved soon. Details regarding our support policy can be found in the documentation update.)

**Comment by mdr0id** [comment]
Solution can be found at: http://zcash.readthedocs.io/en/latest/rtd_pages/rtd_docs/user_guide.html in CentOS 7 section.

**Comment by netnut404** [comment]
> Solution can be found at: http://zcash.readthedocs.io/en/latest/rtd_pages/rtd_docs/user_guide.html in CentOS 7 section.

I have tried this on Centos 7.6 and seen several reports online..
this does not seem to work on centos 7 as  it fails to detect the yum installed openssl and tries to compile it's own which should not be done from everything I have read.

it gets as far as..

install libssl.a -> /home/username/zcash/depends/work/staging/x86_64-unknown-linux-gnu/openssl/1.1.0h-f156af2bd6a/home/username/zcash/depends/x86_64-unknown-linux-gnu/lib/libssl.a
basename: missing operand
Try 'basename --help' for more information.
make[1]: *** [install_dev] Error 1

I am wondering if maybe a switch in the build switch to tell it where to find openssl would help ?
