### ISSUE TITLE
Zcash std::bad_alloc

### ISSUE THREAD

**Issue by JDongian** [zcash/zcash#2867]
I'm new to Zcash so forgive if this is duplicate or a known issue.

### Describe the issue

Seems to be an out-of-memory error, crash due to bad allocation.

![z](https://user-images.githubusercontent.com/3201248/34908644-bbf4a0c4-f858-11e7-9302-ce93240f4133.png)

### Can you reliably reproduce the issue?

Will update issue if it happens again

#### If so, please list the steps to reproduce below:

1. Config is:
```
rpcuser=username
rpcpassword=<secret>
gen=1
genproclimit=-1
```
Where secret is generated from /dev/urandom as per the instructions
2. Run ./bin/zcashd

### Expected behaviour
No crash

### Actual behaviour + errors
std::bad_alloc

### The version of Zcash you were using:
1.0.14

### Machine specs:
- OS name + version: Arch Linux
- CPU: `Intel G3930 Kaby Lake Dual-Core 2.9 GHz LGA 1151 51W BX80677G3930 Desktop Processor Intel HD Graphics 610`
- RAM: `Corsair Value Select 4GB Unbuffered CL15` (DDR3 2133MHz, 15-15-15-36 latency)
- Disk size: 500GB
- Disk Type (HD/SDD): HD
- Linux kernel version (uname -a): `Linux peat 4.14.12-1-ARCH #1 SMP PREEMPT Fri Jan 5 18:19:34 UTC 2018 x86_64 GNU/Linux`
- Compiler version (gcc -version): compiled with `gcc-7.2.1`

### Do you have a back up of `~/.zcash` directory and/or take a VM snapshot?
No, I had just begun and unfortunately did not make a backup.

**Comment by JDongian** [comment]
There is 1G swap (enabled) and there is no X server running, only sd-pam,
ssh-agent, sshd, tmux, and a few other tiny processes. I will report here
if it happens again after increasing the swap space to 4GB.

**Comment by ioptio** [comment]
Hey @JDongian any follow up on increasing swap space?

**Comment by ioptio** [comment]
Feel free to reopen this issue if it persists.
