### ISSUE TITLE
Communicate that explorer.zcha.in is broken

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2868]
It frequently misses blocks and transactions; the total transaction count is wildly wrong; and it reports incorrect (sometimes negative) balances.

**Comment by daira** [comment]
The statistics at https://zcha.in/statistics/network and pie chart at https://zcha.in/statistics/value are also incorrect.

I wrote:
> total monetary base calculated as cumulative miner reward + founders' reward according to that page: 2906015 + 726503.75 = 3632518.75 ZEC (as of block 300600 I think)
> total monetary base calculated as "Transparent Value" + "Transparent Value (Unspent Block Rewards)" + "Shielded Value" = 3389099.87744 + 3633366.11698 + 243306.37256 = 7265772.36698 ZEC
> the figure most likely to be wrong is "Transparent Value (Unspent Block Rewards)". It's clear from the pie chart at https://zcha.in/statistics/value that they intended that to be exclusive of other transparent value (i.e. not in unspent block rewards), but that can't be correct
> if we sum just "Transparent Value" and "Shielded Value" then we get 3632406.25 ZEC which is closer to 3632518.75 ZEC
>
> note that if this were fixed then the "Shielded Value" proportion on that pie chart would be roughly twice as large (edited)
> @str4d earlier gave the Sprout shielded value from `getblockchaininfo` as 222836.21037821 ZEC at block 280390 so the zcha.in value for that is roughly accurate

**Comment by str4d** [comment]
I think I'll add the transparent value pool to the ones we track in zcashd
alongside the Sprout pool (and soon Sapling). That way, we can just sum up
all reported values (on a node that has reindexed) to get the total ZEC
amount.

**Comment by braddmiller** [comment]
This seems like we should just send bug reports in to zcha.in when we notice issues instead of making tickets on our github? I'm going to close this since it's pretty old. Reopen it if you think it's still relevant.

**Comment by daira** [comment]
At the time this ticket was filed, the maintainer of explorer.zcha.in was unresponsive. The maintenance situation is better now, but note that the bug in https://github.com/zcash/zcash/issues/2868#issuecomment-379551987 is still not fixed.
