### ISSUE TITLE
Zcash sprout-proving.key not available

### ISSUE THREAD

**Issue by pedropabloDM** [zcash/zcash#2875]
Following [1.0 User Guide](https://github.com/zcash/zcash/wiki/1.0-User-Guide#or-compile-it-yourself) I decided to create a wallet and start minning some Zcash (ZEC) by compiling the source code myself. Everything was fine until I had to download the **sprout-proving** keys. Turns out those keys are hosted on an Amazon server which is blocked to my country due to an economic embargo. Could you, **PLEASE**, hosting these keys to be downloaded from a direct link and maybe create a tutorial to manually put them into the Zcash files (the one downloaded using git). I'm so sorry if this is not the proper place to post this issue. Thanks in advance. The [zcash4win](https://zcash.dl.mercerweiss.com/zcash4win-1.0.12.msi) client cannot be downloaded for the same reason. Sometimes we make life harder when it should be simpler.

![error_the_request_could_not_be_satisfied_-_2018-01-16_16 05 47](https://user-images.githubusercontent.com/10564444/35012271-40822fa2-fad7-11e7-85dd-b9a4a668da66.png)

**Comment by bitcartel** [comment]
This is related to #1296.

**Comment by bitcartel** [comment]
@pedropabloDM Can you download them from here? https://gitlab.com/zcashcommunity/params

**Comment by pedropabloDM** [comment]
@bitcartel I'd like to thank you for your reply, I do can download the files using that link. Now I can start mining some ZEC :) :). Another question, once I have downloaded these keys, do I need to download them again for another worker or can I copy that files to the same location in another worker?
How can I mark this thread as solved?

**Comment by bitcartel** [comment]
You can copy the files / .zcash-params folder to another worker.

**Comment by Iwanttosetmyownnickname** [comment]
> This is related to #1296.

This link is dead. Error 404 is appearing.

> @pedropabloDM Can you download them from here? https://gitlab.com/zcashcommunity/params
