### ISSUE TITLE
Auto-senescence (deprecation) does not take into consideration testnet and regtest mode

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#2876]
DEPRECATION_HEIGHT is set to a block height relevant for mainnet.

When `EnforceNodeDeprecation(DEPRECATION_HEIGHT)` is called, there are no checks for testnet or regtest, so nodes on those networks could shut down.

If auto-senescence is not applicable to testnet and regtest mode, conditional logic should be added before calling  `EnforceNodeDeprecation` (and any other relevant call points).

**Comment by str4d** [comment]
Heh, good point! I'd prefer to add this logic inside `EnforceNodeDeprecation`, as an early return (if we decide to not deprecate on testnet).

**Comment by daira** [comment]
I don't think we should senesce at all on testnet or regtest.

**Comment by arcalinea** [comment]
Should there an option to configure a deprecation height on testnet and regtest? Having a feature of the mainnet code such as auto-senescence that is not testable on either testnet or regtest does not seem great. If it were configurable on regtest, it could allow third-parties using the zcash client to test how their interface will react when auto-senescence kicks in, for example.

**Comment by braddmiller** [comment]
I agree there should be a way to test senescence behavior on testnet and regtest. So my follow up question would be is `EnforceNodeDeprecation` the only place where deprecation is enforced? Meaning is there a way to manually specify deprecation for testing purposes? If not this seems like the place to add that.
