### ISSUE TITLE
 zcash/src/streams.h

### ISSUE THREAD

**Issue by textbrowser** [zcash/zcash#2880]
feof() should not be called with a NULL parameter.

```
 bool eof() const {
        return nReadPos == nSrcPos && feof(src); // ... src != NULL && ...
}
```
```CBufferedFile f(NULL, 0, 0, 0, 0); f.eof();``` will abort.

**Comment by bitcartel** [comment]
@textbrowser Are you referring to this line of code?
 https://github.com/zcash/zcash/blob/45faa928ec2b10dea8f5a072e8a24d5ea5061cd0/src/streams.h#L528

...as I don't see the `// ... src != NULL && ...` comment on that line.  Thanks.

**Comment by textbrowser** [comment]
Yes.
