### ISSUE TITLE
Funds overwritten on Z adres.

### ISSUE THREAD

**Issue by Laurentius26** [zcash/zcash#2881]
Forgive me for my English but I do have an issue with the wallet and hope someone can help me.

Here's the problem:

I've send bitcoinz from the exchange to the public T adres of BitcoinZWallet 1.1.0_1.3.
In the wallet I had an amount of bitcoinz already located on a private Z adress.

Probably I did wrong but I've send the new bitcoinz on the T adress arrived to the already 
stored bitcoinz located in the private Z adress to make one amount.

The new bitcoinz value transfered has overwritten the value that was already there on the private Z adress. I've lost a lot of bitcoinz now.

I do have all adresses plus private keys.

Is there anything I can do to get the bicoinz back that were there on the Z Private adress in the first place?
After a fresh setup and a new sync of the blockchain the wallet says the Z adress is not listed even with imported private keys.

I would much appriciate your help, thank you.

**Comment by daira** [comment]
> The new bitcoinz value transfered has overwritten the value that was already there on the private Z adress. I've lost a lot of bitcoinz now.

That's not how it works; receiving new transfers to a z-address can't overwrite existing notes. It may be a wallet bug that the wrong balance is shown.

Note that we cannot provide support for wallets specific to non-Zcash coins, even if they use Zcash code. I suggest moving this to the BitcoinZ bug tracker: https://github.com/bitcoinz-pod/bitcoinz/issues
