### ISSUE TITLE
Initial block download slowdown

### ISSUE THREAD

**Issue by nothingismagick** [zcash/zcash#2889]
I am downloading the blocks for the first time after successfully installing according to the wiki instructions. The rate of downloading blocks seems to shrink over time, to the point where it seems unlikely that network congestion is the problem. For example within about 30 minutes, I downloaded the first 12% of the blocks, and over the next 2 hours only 2% more even though it still showed that I had 8 connections. After exiting and immediately restarting, the download rate picked up again, rinse and repeat.

### Zcashd Version
zcashd v1.0.14

### Machine specs:
- OS name + version: Ubuntu 16.4.2
- CPU: i5-2520M
- RAM: 8gb
- Disk size: 256GB (20GB free at this moment)
- Disk Type (HD/SDD): SDD
- Linux kernel version (uname -a): 4.13.0-26
- Compiler version (gcc -version): 5.4.0-6

**Comment by daira** [comment]
The progress isn't linear; see #2852. Just be patient.

**Comment by nothingismagick** [comment]
No problem. Just wanted to report it.
