### ISSUE TITLE
[Sapling] Decide whether or not to allow Bech32 t-addresses

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2893]
I think we may have decided not to allow these for Sapling, but I can't remember.

**Comment by bitcartel** [comment]
Are there any functional differences between Sprout and Sapling t-addresses that would merit two separate address formats?

**Comment by daira** [comment]
No.

I think we won't have time for this, in any case.

**Comment by daira** [comment]
I don't see any good reason to allow this, given the compatibility disruption it would cause.
