### ISSUE TITLE
Bought zcash, but it never showed up in my wallet

### ISSUE THREAD

**Issue by raggot** [zcash/zcash#2900]
On January 5th, I have bought 100 euros of ZCash (about 0.21). I can see the balance associated to the address I provided the seller online [on this website](https://explorer.zcha.in/accounts/t1V9e1V84uUrgcryxjigrXSgJa8i2zPzkY6) but I am unable to see it using the terminal application in Ubuntu.

### Actual behaviour + errors
Running zcash-cli getinfo, I get
{
  "version": 1001450,
  "protocolversion": 170002,
  "walletversion": 60000,
  **"balance": 0.00000000,**
  "blocks": 122215,
  "timeoffset": 0,
  "connections": 8,
  "proxy": "",
  "difficulty": 1925729.623203483,
  "testnet": false,
  "keypoololdest": 1515144475,
  "keypoolsize": 101,
  "paytxfee": 0.00000000,
  "relayfee": 0.00000100,
  "errors": ""
}

And the account addresses confirm the one associated to the zcash in the link.
zcash-cli getaddressesbyaccount "" gives me:
[
  "t1JMPQqQTUfe1iKWDJRaaKqjLKEdDhCweJi",
  **"t1V9e1V84uUrgcryxjigrXSgJa8i2zPzkY6"**
]

I also run a command to check the transactions, which seem to be none:
zcash-cli listtransactions 
[
]

### The version of Zcash you were using:
Zcash Daemon version v1.0.14

### Machine specs:
- OS name + version: Ubuntu 16.04
- CPU: Intel i7
- RAM: 16GB
- Disk size: 255 GB
- Disk Type (HD/SDD): SDD
- Linux kernel version (uname -a): 4.13.0-26-generic
- Compiler version (gcc --version):  gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609

**Comment by gojomo** [comment]
The current chain-height is around 259,647 blocks - your `getinfo` output shows 122,215 – so your local install is showing the state from an earlier time. Give the node time to catch up, and you should see an accurate balance.

**Comment by ioptio** [comment]
Closing this. Reopen if you're still having issues.
