### ISSUE TITLE
Add branch IDs to protocol handshake

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#2904]
The Overwinter network protocol upgrade should add branch IDs to the initial handshake. Specifically:

- Nodes should communicate the branch ID for the branch they are currently on.
- Nodes should communicate any branch IDs they know they will follow in future.

These can then be used by peers for deciding whether (and when) to disconnect from peers that will diverge at future upgrades.

**Comment by bitcartel** [comment]
Hmm, "any branch IDs" sounds like this could be many, so essentially a set of branch IDs.  Is there a scenario where this would realistically occur?

Having two fields in the handshake, "current branch" and "future branch" might suffice, in the scenario of Overwinter nodes connecting to Sapling nodes.

If the handshakes accepts a vector of "future branch IDs", a misbehaving node might include an extremely large set of incompatible branch IDs, right upto the legally permitted size of a network message ( MAX_PROTOCOL_MESSAGE_LENGTH is 2MB ).

So if we were to restrict the size of the vector, what would it be - 5, 10, ? branch IDs?

**Comment by str4d** [comment]
We decided against doing this for Overwinter, but we may still consider it for a future network upgrade.

**Comment by bitcartel** [comment]
Closing for now.
