### ISSUE TITLE
Handle sapling testnet rollback

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#2905]
It is possible that a user wants to follow an upgrade, but does not update their node software to a compatible version until *after* the upgrade occurs. If they subsequently upgrade their software, the node should be able to gracefully handle this case.

This has two components:

- Base chain reorganization (which is also a requirement for #713).
- Note witness cache handling (#1302).

**Comment by str4d** [comment]
In a meeting earlier this week, we decided that this should be subject to the same rollback limit as #713. We also decided we wouldn't implement #1302 for 1.0.15.

Additionally, I realised I forgot to outline one important reason for having this: if we push out a testnet activation, and then discover issues that need addressing, we will want to rollback the testnet and continue. If we do in fact need to do this, either the need will become obvious within 100 blocks, or we will need to implement #1302 at the same time as changing the testnet activation height.

**Comment by daira** [comment]
@str4d Has this been fixed by #3132 and #3166?
