### ISSUE TITLE
Implement sapling transaction format changes

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#2907]
Implement whatever changes are specified as part of the Sapling upgrade.

**Comment by daira** [comment]
For sighash changes, we want to exclude the proofs from Spend and Output descriptions. The proofs cannot change the meaning of the transaction, and excluding them allows them to be computed in parallel with, e.g. a hardware wallet confirming the transaction with the user.

**Comment by str4d** [comment]
This was closed by #3197.
