### ISSUE TITLE
Testnet configuration docs are hard to find leading users to misconfigure their testnet nodes and unable to sync up

### ISSUE THREAD

**Issue by 0xbaadf00d** [zcash/zcash#2908]
Hello,

I have no response from your other officiels channels. So I post here with hope to get answers and the issue resolved. 

The testnet network doesn't work, zcashd stay with 0 connections and synchronization frozen at 0%.

Firstly, it could be nice to allow user to download a bootstrap.dat file cause your P2P network sooo slow and please, add new testnet fullnode on the network.

Related links :
- https://www.reddit.com/r/zec/comments/7sdatj/is_testnet_broken/
- https://forum.z.cash/t/is-testnet-broken/26219

**Comment by bitcartel** [comment]
What version of zcashd are you running?  Please copy and paste your `zcash.conf` here so we can check the config, it's strange that you're not connecting to testnet.z.cash and able to sync up.  Thanks.

**Comment by 0xbaadf00d** [comment]
I'm using the last version from Debian repos (apt install zcash). I have follow the tutorial from our website.

I run the daemoin with the console command

```
> zcashd -testnet=1 -gen=1
```

![image](https://user-images.githubusercontent.com/1005086/35430820-366b4062-027a-11e8-860b-cfa2980ce2be.png)

**Comment by bitcartel** [comment]
In `zcash.conf`, do you have the line `addnode=testnet.z.cash` ?

**Comment by 0xbaadf00d** [comment]
Nice it working,  maybe it could be a good thing to add this node be default (hardcoded?) on the daemon when it run with the flag `-testnet` ?

**Comment by bitcartel** [comment]
Great.  It is documented in the user guide under Configuration https://github.com/zcash/zcash/wiki/1.0-User-Guide#configuration, but it looks like it could be better worded/organized.

I'm updating the title of this ticket and putting it into the next milestone.  Should be a quick fix.

**Comment by braddmiller** [comment]
I updated and split up the configuration section in the 1.0 user guide to better clarify setting up mainnet and testnet. I think this can probably be closed.

**Comment by braddmiller** [comment]
I think these edits should have resolved this issue. I'm going to close it, but feel free to reopen if necessary.
