### ISSUE TITLE
Change z_listreceivedbyaddress to return an empty string if the memo field is empty

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#2909]
Currently output looks like this:
```
  {
    "txid": "abcd0123...",
    "amount": 0.12345678,
    "memo": "f600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "txid": "beef0123...",
    "amount": 1.23456789,
    "memo": "f600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
  },
...
```

This results in verbose output on the command line.  It would be better if output looked like:

```
{
    "txid": "beef0123...",
    "amount": 1.23456789,
    "memo": ""
}
```
To implement this, the call will check the deciphered memo to see if the leading bytes is 0xf6 and that the rest of the memo field is zero-padded as detailed in the Zcash protocol spec.

One issue with updating the call is that third-party applications which make use of the memo field might assume the memo field is always returned by the RPC call and they assume it is a fixed length hex string.

**Comment by bitcartel** [comment]
Hi @radix42 Do the GUI wallets display the memo field and do they expect "f60000...00" to be returned in order to render an empty memo string/widget to the user?

**Comment by nathan-at-least** [comment]
-1

Here are my reasons:

RPC Interface Consistency:

The RPC interface is intended to be a programmatic interface, not a nice-to-use commandline interface. Instead of altering the RPC interface to be programmatic but kind of nice in some cases, we should keep the RPC interface primarily focused on being programmatic, unambiguous, and strict. 

Then, we (or someone else) should develop a separate, nice-to-use commandline interface. (I've been prototyping one over at https://github.com/nejucomo/zcli although I completely recommend against it for normal users right now, since it's pre-alpha prototype-ware.)

**Disambiguation / Strictness:**

This would obscure information from the caller, because a memo of all `\0` bytes without an `\xF6` prefix is possible, as well as a memo that begins with `\xF6` then has other non-zero bytes.

**Comment by nathan-at-least** [comment]
Just filed #2933, which is an alternative to this proposal.

**Comment by Tomas-M** [comment]
I suggest simply truncate trailing zeros from the output. So the empty memo is printed as "memo": "f6". Programmers like me never assume fixed-length result, we simply get string of bytes and handle it regardless of size

**Comment by bitcartel** [comment]
Closing as this ticket won't be implemented.
