### ISSUE TITLE
How can I get change t-address balance for user specific. 

### ISSUE THREAD

**Issue by emdadgithaub** [zcash/zcash#2915]
I have created user specific zcash  t-address. For example,

I have two users like A and B who have two address tA and tB respectively. tA address has 5 and tB has 10 in UTXO balance respectively. Now user A has sent 2 to user B. As a result, change amount 3 has sent to another newly generated address of t1A. 

Now, user knows address tA and wants to get balance. How can I get balance of newly created address of t1A? Further once user A will want to transfer 1 to user B, how system can recognize the  newly created address balance?

Please assist me to solve this problem.

**Comment by lindanlee** [comment]
Could you try using the command `listreceivedbyaddress "" ` ? This should return the amount received by each address.

**Comment by garethtdavies** [comment]
`zcash-cli listreceivedbyaddress` won't list the change address. 

`zcash-cli listaddressgroupings` should do the trick though.

**Comment by ioptio** [comment]
@emdadgithaub let us know if the above suggestion worked for you or not.

**Comment by ioptio** [comment]
Feel free to reopen if the issue still persists.
