### ISSUE TITLE
Compile fails with "expected '}' before 'class'" in gtest-internal.h

### ISSUE THREAD

**Issue by dncohen** [zcash/zcash#2916]
I'm trying to follow the instructions on https://github.com/zcash/zcash/wiki/1.0-User-Guide#or-compile-it-yourself, my first time compiling zcash.

compile fails with 

```
In file included from /home/user/zcash/depends/x86_64-unknown-linux-gnu/share/../incl\
ude/gtest/gtest.h:58:0,
                 from gtest/test_proofs.cpp:1:
/home/user/zcash/depends/x86_64-unknown-linux-gnu/share/../include/gtest/internal/gte\
st-internal.h:1215:1: error: expected ‘}’ before ‘class’
 class GTEST_TEST_CLASS_NAME_(test_case_name, test_name) : public parent_class {\
 ^
```
The first of several similar errors.  Just me?

### Expected behaviour
I hoped the compile would succeed without errors.

### Actual behaviour + errors
The error pasted above.

### The version of Zcash you were using:
I used `git checkout v1.0.14` before compiling

### Machine specs:
- OS name + version: 
Fedora 26

- Linux kernel version (uname -a):
Linux devel-zcash 4.9.56-21.pvops.qubes.x86_64 #1 SMP Tue Oct 17 23:58:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- Compiler version (gcc -version):
gcc (GCC) 7.2.1 20170915 (Red Hat 7.2.1-2)

### Any extra information that might be useful in the debugging process.
Please also include any non-standard things you did during compilation (extra flags, dependency version changes etc.) if applicable.

I compile with `./zcutil/build.sh --disable-rust -j$(nproc)`, as documented.

**Comment by lindanlee** [comment]
We're currently not sure why this error is happening. We will try to recreate the error and report back in the issue if we do.  However, we don't have the infrastructure to easily test Fedora right now.

**Comment by ioptio** [comment]
Perhaps a faster alternative is linking to this ticket from the [Zcash community chat #zcash-dev channel](https://chat.zcashcommunity.com/channel/zcash-dev) requesting community support

**Comment by str4d** [comment]
It's been several years; closing as likely fixed by some ancillary change. Please reopen this if it is still an issue with current `master`.
