### ISSUE TITLE
Update contrib/devtools/fix-copyright-headers.py to handle Zcash copyright headers

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2921]
As suggested at https://github.com/zcash/zcash/issues/2887#issuecomment-361712150 .

For bonus points, robustify this script and add running it to the automatic release process.

**Comment by jadijadi** [comment]
I'm working on this.

**Comment by jadijadi** [comment]
Sent this PR: https://github.com/zcash/zcash/pull/4926

**Comment by str4d** [comment]
Closed by #6362 which will be in v5.4.0-rc2.
