### ISSUE TITLE
Include authenticatable change-indicator in change note memo fields.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#2935]
**Synopsis:**

When viewing `z_listreceivedbyaddress` output or potentially other future output note RPC calls (ex: #2910) users or UX-designs probably want to distinguish between funds coming from "outside" versus "change notes" which are necessarily generated by the wallet.

I added the usability flag, because it seems like almost every good wallet UX would need this distinction.

**Implementation Requirements:**

A wallet could include a change-indicator memo field. To be secure, it would need to be authenticatable by the holder of the viewkey, such that only the spending authority secret key could create valid change-indicators. (Also, they need to be secure against replay attacks assuming a malicious viewkey holder.)

**Related:**

- We'd want to provide a standardized encoding of this change-indicator, thus #1849.
- If the RPC calls (such as `z_listreceivedbyaddress`) detect these and treat them differently (such as by adding a `"change": True` field), this would imply #2933 or at least a special case of it.
- #2911 *might be* a case where a user is confused by the presence of change inputs.

**Comment by nathan-at-least** [comment]
Question: Is it possible to implement viewkey-authenticatable change-indicators without a protocol change from Sprout? What about Sapling?

**Comment by daira** [comment]
Sapling includes "full" viewing keys which can view both outgoing and incoming transfers. Given a full viewing key, change can be detected because the transaction has both an outgoing transfer from an address, and an incoming change transfer to the same address.

**Comment by daira** [comment]
Given that Sapling doesn't need a separate change-indicator, shall we make this ticket be about having ``z_listreceivedbyaddress``, and ``z_listunspent`` if it is added (#2910), include a ``"change": True`` field for change notes detected by the above method?

**Comment by Eirik0** [comment]
Submitted pull request #3156 to add the change indicator.

**Comment by Eirik0** [comment]
#3156 has been merged.

**Comment by nathan-at-least** [comment]
Does the patch follow the original proposal to have a change indicator in the memo field, or does it follow @daira's suggestion here: https://github.com/zcash/zcash/issues/2935#issuecomment-375622322 ?

**Comment by daira** [comment]
@Eirik0 wrote:
> If I remember correctly, unlike the suggestion, however, we do not do any work to omit the field when the the status is unknown. I think it will just show up as false.

Oh, that's unfortunate. I must have missed it when I reviewed #3156. I think it should be changed to what I suggested.

**Comment by daira** [comment]
Filed #3424 for that problem.

**Comment by nathan-at-least** [comment]
Does the patch follow the original proposal to have a change indicator in the memo field, or does it follow @daira's suggestion here: https://github.com/zcash/zcash/issues/2935#issuecomment-375622322 ?

**Comment by Eirik0** [comment]
@nathan-at-least We have done follow up to this and after https://github.com/zcash/zcash/issues/3424 has been reviewed and merged the logic will follow @daira's suggestion.
