### ISSUE TITLE
Bugfix: z_importviewingkey RPC call missing startHeight

### ISSUE THREAD

**Issue by Tomas-M** [zcash/zcash#2937]
If I call RPC command z_importviewingkey with one or two arguments, it works OK.
But if I call RPC with three arguments, adding startHeight, RPC returns with error (usage text).

So it seems to me RPC is not configured properly, it does not understand the third argument.

Using zcash 1.0.14

**Comment by Tomas-M** [comment]
Also the returned help text which prints correct usage example with zcash-cli does not have the third parameter in the example usage for JSON-RPC call with curl.

**Comment by Tomas-M** [comment]
I believe this patch would probably fix it

    diff --git a/src/rpcclient.cpp b/src/rpcclient.cpp
    index def3250..59dbe95 100644
    --- a/src/rpcclient.cpp
    +++ b/src/rpcclient.cpp
    @@ -117,7 +117,7 @@ static const CRPCConvertParam vRPCConvertParams[] =
         { "z_getoperationstatus", 0},
         { "z_getoperationresult", 0},
         { "z_importkey", 2 },
    -    { "z_importviewingkey", 2 },
    +    { "z_importviewingkey", 3 },
         { "z_getpaymentdisclosure", 1},
         { "z_getpaymentdisclosure", 2}
     };

**Comment by Tomas-M** [comment]
The previously mentioned patch is not sufficient. This is probably also needed:

    diff --git a/src/wallet/rpcdump.cpp b/src/wallet/rpcdump.cpp
    index 1177cfc..ca4193d 100644
    --- a/src/wallet/rpcdump.cpp
    +++ b/src/wallet/rpcdump.cpp
    @@ -653,7 +653,7 @@ UniValue z_importviewingkey(const UniValue& params, bool fHelp)
         if (!EnsureWalletIsAvailable(fHelp))
             return NullUniValue;

    -    if (fHelp || params.size() < 1 || params.size() > 2)
    +    if (fHelp || params.size() < 1 || params.size() > 3)
             throw runtime_error(
                 "z_importviewingkey \"vkey\" ( rescan startHeight )\n"
                 "\nAdds a viewing key (as returned by z_exportviewingkey) to your wallet.\n"

**Comment by Tomas-M** [comment]
By the way, if my identification of the problem was correct, there may be several more bugs regarding the number of accepted parameters in he structure defined in rpcclient.cpp.

For example `z_listreceivedbyaddress` accepts 2 parameters (address and minconf), but rpcclient.cpp has 
 `{ "z_listreceivedbyaddress", 1}`. So you may consider reviewing all of the numbers to see if all newly added parameters are accounted for.

**Comment by str4d** [comment]
The entries in `rpcclient.cpp` (which are zero-indexed) define whether a parameter is parsed as a JSON value, or left as a string. In the case of `z_listreceivedbyaddress`, the first parameter is a string, while the second is an integer, so there is only the line `{ "z_listreceivedbyaddress", 1}`.

Your later diagnosis [here](https://github.com/zcash/zcash/issues/2937#issuecomment-364186695) looks like the actual bug. Thanks for catching this!

**Comment by Tomas-M** [comment]
Thanks for clarification. I still do not fully understand, why there are things like

    { "listtransactions", 1 },
    { "listtransactions", 2 },
    { "listtransactions", 3 },

then. But no need to explain this to me, just make sure you know it :)
