### ISSUE TITLE
Change ``libzerocash`` include paths to be "standard" / friendly w/ ./depends.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#294]
Currently building apps against an installed `libzerocash` requires passing a special `-I` flag. This is because the include paths it uses internally are not relative to the current file, nor are they the "standard installed paths", but something in between. Building it directly works only because it hardcodes `-I .` [in the Makefile](https://github.com/Electric-Coin-Company/libzerocash/blob/master/Makefile#L12).

An example is the include in [`./libzerocash/Zerocash.h` line 69](https://github.com/Electric-Coin-Company/libzerocash/blob/master/libzerocash/Zerocash.h#L69) which is:

``` c++
 #include "libzerocash/utils/util.h"
```

A relative include wouln't require a custom `-I` and would be:

``` c++
#include "utils/util.h"
```

-whereas the "system" include path would be:

``` c++
#include <libzerocash/libzerocash/utils/util.h>
```

-based on the current installation layout.

**Comment by ebfull** [comment]
I'm not sure that this is a problem anymore.

**Comment by nuttycom** [comment]
`libzerocash` no longer exists.
