### ISSUE TITLE
remove configuration option for turning off EOS halt (was called "auto-senescence")

### ISSUE THREAD

**Issue by zookozcash** [zcash/zcash#2943]
Remove the configuration option with which one can turn off the auto-senescence behavior.

This _communicates_ to users that _only the auto-senescing version of zcashd_ is supported by the Zcash Company. If the only way that they can disable auto-senescence is either to (a) edit and recompile their code, or (b) get a binary from someone else who has done so, then it will be clear to them that the thing they are running is not supported by the Zcash company.

Another argument, which I also believe, is that it is safer for a user to be unable to use Zcash at all that for them to use an obsolete, unsupported, and hard-fork-prone version of Zcash.

**Comment by daira** [comment]
I expressed some concerns about this change, in particular concerning the difficulty of compiling on Windows.

In practice that is not just "edit and recompile", it is "have experience of having wrestled with Windows compilation issues in multiple other projects for a decade, have an expensive toolchain already set up [*], and then spend several weeks sorting out the issues specific to this project (which will be subtly different from anyone else's issues with this project, because no two Windows dev environments are alike)."

So, in practice this policy will break our unofficial support for Windows, which makes up a substantial portion of our user base. I would be happy to support it *after* we have working *automated* Windows and OS X builds.

Concerning the "it is safer for a user to be unable to use Zcash at all" argument, I don't agree that is actually the case for most releases. On the other hand, it may be the case for the next few releases that prepare for Overwinter and Sapling.

[*] in theory you can compile most things with open-source tools, but there's always some dependency that is unreasonably difficult to get working without the paid-for version of Visual Studio.

**Comment by radix42** [comment]
Needless to say I Have Thoughts on this issue, but as Zooko and I are
having coffee in a few minutes, I will refrain from expressing them in
public until after we chat, as they very well may change in the next hour
:-)

**Comment by zookozcash** [comment]
Here's something I just wrote in the Zcash Company's private Slack. I try not to let conversations that are meaningful/useful/relevant to the public live in there, so here it is copied to out here:

I think the principle should be "you have to edit your own source code — thus ritually demonstrating that _you_ are the maintainer of the resulting version — if you want to do anything that isn't supported by the Zcash Co".
If there _is_ someone who has some burning need, like a big exchange who is serving millions of requests (and raking in tens of thousands of dollars in fees) every day, and they say "We really need this other behavior which the default source code doesn't support!" then that is _great_. Now we get to have a conversation with them about whether (a) they are going to be the maintainers of their version, or (b) they are somehow going to convince us to start maintaining the variant that they require.
Whereas if there is a config option, then they won't say that to us. Instead they'll set the config option, then they'll _assume_ that we support it, so when something later goes wrong, they'll demand that we fix whatever it is. Much worse starting point for that conversation.
And saying "BTW we do not support this" in some doc somewhere will probably not make any difference to that flow. They'll go ahead and use the option, not mention it to us, and then blame us later for not supporting it.

**Comment by leto** [comment]
I can understand the reasoning behind this, and even agree with the principles that motivated this, but ultimately I think it makes the lives of downstream porters/packagers/developers more complicated with little benefit.

If this is truly motivated by the fact of a hard fork coming up, I think something specific to that situation could be developed, this seems to be overboard. My guess is that many downstream Zcash forks that have infinitely less resources than ZcashCo will not merge this as it makes their life harder, especially people who package GUI wallets. 

Just 2 satoshis from the Hush project, who as disabled the auto-senescence feature.

**Comment by zookozcash** [comment]
I think this ticket is very important, and that the sooner it gets implemented the better, because the point of this ticket is to communicate to end users that unsupported releases of Zcash are unsupported, and it takes 18 weeks from the release date to communicate that to them, and after they receive the message then it will take them time to process the message (such as by upgrading to a supported version of `zcashd`, or by abandoning Zcash and moving to a different blockchain that offers a longer support cycle, or by finding an alternative supplier of Zcash software who offers longer support cycles, whatever). So it is going to take, let's say, maybe 6 months from when we implement and merge this ticket until when people have understood the message and adjusted to it and the knowledge has started propagating through journal articles and mutual-tech-support forums and things like that.

So let's please prioritize this ticket.

**Comment by daira** [comment]
I remain opposed to this until we have working Windows and Mac automated builds.

**Comment by zookozcash** [comment]
Daira, would you rather people using unsupported software (a) follow a chainfork that is not the dev-supported chain, or (b) have their software stop and emit an error message telling them that they need to upgrade? The definition of "unsupported software" is "software that you have to compile to use". Therefore, if someone (e.g. @radix42) makes software that disables auto-deprecation then _that_ software is supported — by him.This pull request should be merged over Daira's objection.

**Comment by zookozcash** [comment]
I continue to think it is very important and urgent to implement this ticket.

**Comment by daira** [comment]
Given the progress toward supporting Windows and Mac, I withdraw my objection.

**Comment by bitcartel** [comment]
If this is removed, maybe there should be a build flag that enables this option to make it easier for third party developers to build the zcashd they want?  For example: `zcutil/build.sh -enable-eos-option`

**Comment by bitcartel** [comment]
@mdr0id Here is @str4d's PR which you can rebase and test for closing this ticket. https://github.com/zcash/zcash/pull/3137
