### ISSUE TITLE
Build fails with --disable-wallet

### ISSUE THREAD

**Issue by randombit** [zcash/zcash#2946]
### Describe the issue

If `--disable-wallet` is used, the build fails with link errors. It looks to be because `src/utiltest.cpp` is part of libbitcoin_wallet which is not built with `--disable-wallet`. Then a test in `src/gtest/test_validation.cpp` refers to `GetValidReceive` which is defined in the skipped source file.

This causes the overall build to fail, even with `make -k` it seems the `zcash-cli` and related tools are not built.

However I notice the Travis build seems to be testing this configuration (NO_WALLET=1) so perhaps there is some other problem and my diagnosis above is incorrect.

### Can you reliably reproduce the issue?

Yes

1. ./configure --disable-wallet --disable-rust --disable-zmq
2. make

### Expected behaviour
Build should succeed

### Actual behaviour + errors

```
...
CXXLD    zcash-gtest
gtest/zcash_gtest-test_validation.o: In function `Validation_ReceivedBlockTransactions_Test::TestBody()':
/home/jack/work/zcash/zcash/src/gtest/test_validation.cpp:82: undefined reference to `GetValidReceive(libzcash::JoinSplit<2ul, 2ul>&, libzcash::SpendingKey const&, long, bool)'
/home/jack/work/zcash/zcash/src/gtest/test_validation.cpp:89: undefined reference to `GetValidReceive(libzcash::JoinSplit<2ul, 2ul>&, libzcash::SpendingKey const&, long, bool)'
libbitcoin_server.a(libbitcoin_server_a-paymentdisclosuredb.o): In function `PaymentDisclosureDB::Get(JSOutPoint const&, PaymentDisclosureInfo&)':
/home/jack/work/zcash/zcash/src/paymentdisclosuredb.cpp:78: undefined reference to `JSOutPoint::ToString[abi:cxx11]() const'
libbitcoin_server.a(libbitcoin_server_a-paymentdisclosuredb.o): In function `PaymentDisclosureDB::Put(JSOutPoint const&, PaymentDisclosureInfo const&)':
/home/jack/work/zcash/zcash/src/paymentdisclosuredb.cpp:64: undefined reference to `JSOutPoint::ToString[abi:cxx11]() const'
```

### The version of Zcash you were using:
git master (e6850571dd0abea08d6f4a9c77270361fcdc4185)

### Machine specs:
- OS: Arch Linux
- CPU: x86-64
- Linux kernel version (uname -a): 4.15.1
- Compiler version (gcc -version): 7.3.0

**Comment by str4d** [comment]
#6571 added a CI workflow which includes step to build with `--disable-wallet`. The workflow is currently passing, so the above issue was likely fixed at some point.
