### ISSUE TITLE
Refactor python RPC tests

### ISSUE THREAD

**Issue by arcalinea** [zcash/zcash#2947]
There's a lot of commonly used code that's being repeated in a non-standard way, such as `wait_and_assert_operationid_status` for shielded txs, which is a function repeated in multiple tests. These can be extracted from individual tests into helper functions available to all RPC tests.

**Comment by Eirik0** [comment]
I think this is solved with https://github.com/zcash/zcash/pull/3093 and/or https://github.com/zcash/zcash/pull/3479. Please let us know if you had anything else in mind.
