### ISSUE TITLE
Document libsnark's -lz and -ldl dependencies

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#295]
Add their corresponding packages to the `apt-get install` command on the wiki. Debian comes with those by default, so we never noticed they were a dependency. (Should we build them using the `depends` system? I think not: too much work for what it's worth, as we aren't aiming for reproducible builds at the moment. Just document it).

**Comment by tromer** [comment]
The `-lzm` is gone in upstream libsnark for a while now (https://github.com/scipr-lab/libsnark/commit/69f312f149cc4bd8def8e2fed26a7941ff41251d).

**Comment by tromer** [comment]
Libsnark is no longer used by zcashd, so this issue can be closed.
