### ISSUE TITLE
Implicit double to long conversions in RPC tests

### ISSUE THREAD

**Issue by randombit** [zcash/zcash#2956]
### Describe the issue

Compiling with Clang warns about two implicit conversions that were probably not intended in `src/test/rpc_wallet_tests.cpp` lines 1064 and 1071:

```
        CAmount amount = 123.456;
        ...
        amount = 1.111;
```

These are strange values for CAmount, which is a typedef for `int64_t`.

This doesn't seem like a major issue, but it does imply the code isn't testing quite what the author intended so maybe it's worth taking a further look.

Both uses were added in cff6f0ac4

**Comment by daira** [comment]
It looks like the actual values weren't the focus of the test, and could easily be replaced with similar integers.

**Comment by oxarbitrage** [comment]
It looks this issue is already fixed.

https://github.com/zcash/zcash/blob/master/src/wallet/test/rpc_wallet_tests.cpp#L1228

https://github.com/zcash/zcash/blob/master/src/wallet/test/rpc_wallet_tests.cpp#L1235

Close?

**Comment by randombit** [comment]
lgtm
