### ISSUE TITLE
z_sendmany no longer creates v1 transactions for t->t, in violation of a SHOULD

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2964]
@str4d wrote in a [comment](https://github.com/zcash/zcash/pull/2925#discussion_r167727060) on #2925:
> A side-effect of this is that ``z_sendmany`` no longer creates v1 transactions for t->t. This should be fine though, as anyone who has made the effort to use ``z_sendmany`` should already support parsing v2 transactions.

But this violates a SHOULD in section 6.1 of the protocol spec:
> Software that creates transactions **SHOULD** use version 1 for transactions with no JoinSplit descriptions.

This was motivated by maximizing compatibility with Bitcoin transaction parsing code. Note that @str4d's comment doesn't take into account that in general it will be different code (perhaps run by an entirely different party) parsing the transaction, than that calling ``z_sendmany``.

Either the implementation should be fixed or the spec should be relaxed.

**Comment by bitcartel** [comment]
I already fixed this locally and thought I had pushed up a PR for review... will find it and create PR again if necessary... it was a quick fix.
