### ISSUE TITLE
Create an RPC method that returns the current and next branches

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#2974]
#2785 will provide information about each upgrade, and its current status (pending or active). However, a user wanting to figure out when to e.g. stop creating Sprout transactions and start creating Overwinter transactions, needs to do additional non-obvious post-processing on the data. We should do that post-processing for them, and provide a new RPC method that returns both the current branch ID, and the branch ID that will be applied to the next block. Users can then use whichever is applicable to their use-case.

**Comment by bitcartel** [comment]
It could be part of an existing rpc call, e.g. `getblockchaininfo` where a new field is included:
```
{
...
  {
    "consensus":
      { "currentblock" : "sprout_branch_id" },
      { "nextblock" : "overwinter_branch_id"}
  }
...
}
```

**Comment by str4d** [comment]
Ooh, I like that better. I'll wrap that into #2808.
