### ISSUE TITLE
Refactor common code from z_sendmany, z_shieldcoinbase, z_mergetoaddress

### ISSUE THREAD

**Issue by arielgabizon** [zcash/zcash#2979]

**Comment by bitcartel** [comment]
Yes, we will do this after 1.0.15 is out the door.  There might already be a ticket about this.

**Comment by str4d** [comment]
The first part of this (adding Sprout support to the transaction builder) was implemented in #3848.

**Comment by daira** [comment]
This has been fixed, mainly by #6377.

**Comment by nuttycom** [comment]
@daira the `z_shieldcoinbase` and `z_mergetoaddress` changes have not yet been merged.
