### ISSUE TITLE
Do a "delta minimization pass" - make diff from upstream smaller.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#298]
Let's make our diff from upstream smaller, *after* we reach a point of developmental stability (probably at least post-private-alpha).

I call this a "pass" because the goal isn't to minimize the code delta to the extreme, but rather to run through and revert low-hanging fruit. For example, we changed from boost syntax to C++11 initializer syntax in [``./src/chainparams.cpp`` L161-L165 at ``7ad6f5cb``](https://github.com//Electric-Coin-Company/zerocashd/blob/7ad6f5cb0e33ed3a5cb899ac0e6d9c34461cab0b/./src/chainparams.cpp#L161-L165). Here's the changing commit: https://github.com/Electric-Coin-Company/zerocashd/commit/ab1fc6cc6ae6c1468145a1895efc8b274a4bdf1b

This *might* be no longer necessary given the version of boost we use and updates to upstream since that time. So this would be one example of something we could cleanup in a "low hanging fruit pass".

Note, this is related to #24 except it's a smaller scope: this shouldn't involve much "refactoring", just simpler revert-where-possible.

**Comment by daira** [comment]
I'm not sure this is relevant to post-public-alpha.

**Comment by ebfull** [comment]
Not relevant.
