### ISSUE TITLE
How to create new genesis block in zcash 

### ISSUE THREAD

**Issue by braravind** [zcash/zcash#3029]
Hello,

How to create new genesis block. I want to forking of zcash an my own currency chain. I have clone this zcash core code. and try to create new genesis block in chainparams.cpp  in src.

please help me how to generate new genesis block and create my own currency chain.

Thank You!
Aravind

**Comment by rex4539** [comment]
Hello Aravind,

I'm not a developer so I couldn't help you with your request but I will tell you this. If you don't know how to create the genesis block, then perhaps it is not a good idea to create a new coin in the first place :)

**Comment by daira** [comment]
It's a perfectly legitimate question and the answer should be documented.

**Comment by ioptio** [comment]
Created a replacement issue in the documentation repo: https://gitlab.com/zcash-docs/zcash-docs/issues/41

**Comment by uwxpro** [comment]
> Hello Aravind,
> 
> I'm not a developer so I couldn't help you with your request but I will tell you this. If you don't know how to create the genesis block, then perhaps it is not a good idea to create a new coin in the first place :)

Why Not?? You should elaborate your response as it does not make any kind of sense to me and many others!!

**Comment by Saurabgami977** [comment]
hey folks, I couldn't find documentation on how to create genesis block in Zcash

**Comment by Saurabgami977** [comment]
@daira

**Comment by Saurabgami977** [comment]
Can you guide please? Thank you :)
