### ISSUE TITLE
zkSNARK parameters are getting 403 http response

### ISSUE THREAD

**Issue by allan4229** [zcash/zcash#3041]
### Description
- When trying to exec 
```
./zcutil/fetch-params.sh
```
- The result is always HTTP 403 (Forbidden).

### Reproducing the issue
- All steps were made in linux
#### From https://z.cash/download.html
0. Install wget
1. Install zcash as described
2. Exec zcash-fetch-params
#### From git
0. Install wget
1. Clone zcash
2. Change either to v1.0.15 or v1.0.14
3. Go to cloned zcash dir
3. Exec ./zcutil/fetch-params.sh
#### Browser
0. Open any browser
1. Go to https://s3.amazonaws.com/zcashfinalmpc/sprout-proving.key

### Expected behaviour
Fetch params properly.

### Actual behaviour + errors
The following message appears in all script methods :
```
Zcash - fetch-params.sh

This script will fetch the Zcash zkSNARK parameters and verify their
integrity with sha256sum.

If they already exist locally, it will exit now and do nothing else.

Retrieving (wget): https://z.cash/downloads/sprout-proving.key
--2018-03-03 13:04:56--  https://z.cash/downloads/sprout-proving.key
Resolving z.cash (z.cash)... 104.28.11.251, 104.28.10.251, 2400:cb00:2048:1::681c:afb, ...
Connecting to z.cash (z.cash)|104.28.11.251|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://s3.amazonaws.com/zcashfinalmpc/sprout-proving.key [following]
--2018-03-03 13:04:57--  https://s3.amazonaws.com/zcashfinalmpc/sprout-proving.key
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.0.99
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.0.99|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2018-03-03 13:04:58 ERROR 403: Forbidden.


Failed to fetch the Zcash zkSNARK parameters!
Try installing one of the following programs and make sure you're online:

 * ipfs
 * wget
```
For the browser, the following message will be shown:
```xml
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>24373BEFE5FFD58F</RequestId><HostId>o1o6CkWJLLH5sOZrRWhxBpoAruV9WSpxbdbb5tdVkfYBADUjWUX2ZheaPF3hutceba9qZLD0Sz4=</HostId></Error>
```

### Zcash version:
- v1.0.15 from z.cash
- v1.0.15 from git
- v1.0.14 from git

### Machine specs:
- OS : GNU/Linux
- Linux kernel version : 4.14 x86_64 SMP
- Bash version : 4.4
- Wget version : 1.19

**Comment by shutup-r** [comment]
Same problem here. [This workaround](https://github.com/zcash/zcash/issues/2709)  appears to be working. Haven't finished downloading blocks yet.

**Comment by bitcartel** [comment]
@shutup-r @allan4229 You can also download from here: https://gitlab.com/zcashcommunity/params

@nathan-at-least This is the third such report of issues downloading the parameters in recent days.

**Comment by allan4229** [comment]
Thanks for the tip.
I was in a weekend trip and that's why I did not report anything else.
Fetching params is working out of the box right now, so the issue can be closed.

**Comment by daira** [comment]
This is apparently intermittent and/or network-dependent; see #3075.
