### ISSUE TITLE
Update download instructions to rely on cookie authentication.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#3042]
Current download instructions at https://z.cash/download.html say:

>  You'll need to create a zcash.conf file before starting zcashd for the first time:
>> echo "rpcuser=username" >> ~/.zcash/zcash.conf
>> echo "rpcpassword=`head -c 32 /dev/urandom | base64`" >> ~/.zcash/zcash.conf 

-but this is outdated and no longer recommended due to the cookie-based authentication. Update these instructions.

**Comment by ioptio** [comment]
Done in https://zcash.readthedocs.io/en/latest/rtd_pages/user_guide.html#configuration
