### ISSUE TITLE
Integrate sapling-crypto Rust library as a C wrapper API

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#3052]
This ticket can be closed when we have a C API we can call from inside the C++ codebase, to interact with the Sapling circuit implemented in https://github.com/zcash-hackworks/sapling-crypto. It might be included as a dependency of `librustzcash`, or directly itself.

**Comment by braddmiller** [comment]
This is mostly complete but will ongoing until zcashd wallet development is finished.
