### ISSUE TITLE
Make Sapling the default for shielded operations

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#3064]
Between #3059 and #3063, we will have the ability to use Sapling addresses in transactions. This ticket is about making that the default shielded address type that users will encounter (instead of Sprout addresses).

Upstream implemented the config options `-addresstype` and `-changetype` for implementing this in SegWit. We may want to do the same, or we may want to have the default change when Sapling activates, or possibly both.

**Comment by bitcartel** [comment]
This ticket is only feasible when shielded operations which are available for Sprout are also available for Sapling.

**Comment by nathan-at-least** [comment]
Can someone describe what `-addresstype` and `-changetype` behaviors would be?

My opinions for an initial RPC support feature set:

- Sapling support will only be present in the existing `z_*` operations which already support Sprout. (So no support for Bitcoin-style APIs for now.)
- Anywhere a Sprout address may appear in an RPC operation, a Sapling address will be supported. (If v2.0.0 doesn't do this in every case, it would be nice to have a "not-supported-yet" error message if users pass a Sapling address where we don't yet support them.)
- Change when sending from a shielded address should always be back to the sending address. Is there any good reason to deviate from this? If there are multiple sending addresses, the API call for a specific transfer should require an explicit change address, or perhaps an explicit sensible default (maybe "the first listed send address will receive all change").
- Add a 'type' parameter to `z_getnewaddress`. In v2.0.0 have this default to `"sprout"`, and later we can change the default to `"sapling"`. This way early versions of the Sapling wallet require users to explicitly opt-in. (I prefer this until we have some amount of testnet testing from multiple vendors.)

That's it. Does this miss anything?

The overall result is that users who install v2.0.0 but change _no_ behavior will continue using Sprout _but can still send_ to Sapling. Meanwhile, users who want to opt-in to using Sapling call `z_getnewaddress "sapling"` and start using the result.

This also is orthogonal to whether or not there is an "upgrade button" to help users migrate from Sprout to Sapling with some kind of privacy-preserving support. That can either be present initially or later.

**Comment by daira** [comment]
@nathan-at-least wrote:
> Meanwhile at some point in the future (maybe v2.0.1) we might switch the z_getnewaddress default to "sapling" and even users who haven't altered their infrastructure deployments begin using Sapling addresses. (This might break deployments! For example an exchange that uses this call with no argument and then has middleware / webapp logic expecting a Sprout address will have bugs or UX issues.)

Technically true, but how many deployments are actually relying on getting a Sprout address, rather than an arbitrary shielded address that they then use through the zcashd RPC API? Are there any?

**Comment by nathan-at-least** [comment]
There are a few such deployments which integrate Sprout addresses. Some like PriveInternetAccess, Shapeshift, and others may have a significant number of users and business operations. Some may be more hobbyist/tinkerer projects such as z-board.net.

There may be multiple which we are not even aware of, so I still want to communicate about the upcoming change through a clearly communicated deprecation / switch-over process.

Also a note on the switch-over timeframe: it needn't be "as soon as possible". It may be wise to wait even after Sapling has fully functional RPC support so that there's a phase for "early Sapling adopters" separate from "default-for-everyone" migration.

**Comment by bitcartel** [comment]
v2.0.2 should have RPC support for `z_mergetoaddress` completing Sapling shielded address support for `z_*` RPC calls.  Should we make Sapling the default when calling `z_getnewaddress`?

**Comment by radix42** [comment]
Imho, yes, please!

**Comment by ioptio** [comment]
Since #3671 is merged and documented, can we close this?
