### ISSUE TITLE
Build on Ubuntu 16.04 error

### ISSUE THREAD

**Issue by jiangzhongbai** [zcash/zcash#3067]
at this level
./zcutil/build.sh --disable-rust -j$(nproc)
I received this message. 

make V=1
Making all in src
make[1]: Entering directory '/home/infmine/zcash/src'
make[2]: Entering directory '/home/infmine/zcash/src'
make -C secp256k1 libsecp256k1.la
make[3]: Entering directory '/home/infmine/zcash/src/secp256k1'
make[3]: Leaving directory '/home/infmine/zcash/src/secp256k1'
make[2]: Leaving directory '/home/infmine/zcash/src'
make[1]: Leaving directory '/home/infmine/zcash/src'
Making all in doc/man
make[1]: Entering directory '/home/infmine/zcash/doc/man'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/infmine/zcash/doc/man'
make[1]: Entering directory '/home/infmine/zcash'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/home/infmine/zcash'

**Comment by str4d** [comment]
That's not an error. It's saying that you've already compiled Zcash previously, and there is nothing to do. You should see the binaries (`zcashd`, `zcash-cli` etc.) in the `src/` directory as usual.

**Comment by ioptio** [comment]
If you have any other concerns, feel free to reopen this ticket.
