### ISSUE TITLE
Question, spent coins.

### ISSUE THREAD

**Issue by hosseamin** [zcash/zcash#3068]
Hi,

I heard zcash is keeping track of spent coins instead of unspent ones.

1. I know bitcoin's tracker db is keeping track of unspent coins. Is it still true for zcash node's.
2. What i think they meant is that each wallet is keeping track of all z_... address related stuff. Is this true?

I didn't found useful information about this. Maybe it's good idea to put a line in FAQ about this.

**Comment by ioptio** [comment]
Longer term goal (and the reason for keeping this ticket open) is to document (outside of the spec) how the wallet tracks spent/unspent notes as compared to transparent/bitcoin.

**Comment by ioptio** [comment]
This is replaced by https://gitlab.com/zcash-docs/zcash-docs/issues/43
