### ISSUE TITLE
Shielded transaction change and z_listreceivedbyaddress

### ISSUE THREAD

**Issue by ADumaine** [zcash/zcash#3070]
Would it possible to get some clarification on how change is returned in a shielded address?

I have worked with transparent transactions and created raw transaction programatically with UTXOs so have a basic understanding of how that works.

I expected a shielded tx to work similarly but can't seem to find answers to the underlying designation of inputs and how z_listreceivedbyaddress works (since there is no z_listunspent)

Scenario: in a new shielded address 2 amounts (0.4 and 0.6) are sent into the address.  These can be seen by running z_listreceivedbyaddress.

If an amount of 0.1 is sent from the shielded address I expected the transaction to use one of the received amounts and the z_listreceivedbyaddress to return change of 0.4 (disregarding fees). But instead the z_listreceivedbyaddress returns 0.9.

It does appears that the entire address balance (all unspent received amounts) are used in the tx as the balance is 0 if checked after the tx is sent but before included in a block. 

Question 1: Why does z_listreceivedbyaddress show the entire new address balance instead of the change returned from a unspent note after a transaction?

Question 2: Does sending shielded transactions (of an amount less than one of the previous input amounts) result in all of the inputs being used and 'consolidated' when the change is returned? i.e. is there always just one unspent note after a shielded transaction assuming there is change sent back and no other amounts are sent to that address?

Is there some clear/simple explanation posted somewhere for developers of what happens within a shielded address transaction (at the note or nullifier level) that is not filled with equations?

This would be helpful to understand the impact when building application using shielded addresses.

Thanks!

https://github.com/zcash/zcash/issues/2911
https://github.com/zcash/zcash/issues/1962
https://github.com/zcash/zips/blob/master/protocol/protocol.pdf

**Comment by daira** [comment]
If you already understand the UTXO model: shielded transactions work in essentially the same way but they send change back to the sending address by default. ``z_listreceivedbyaddress`` is showing the total received at that address, i.e. any notes that weren't spent (which must have previously been received) plus the change. So in your example, 0.9 ZEC (minus the fee) is the expected balance of the address after the transaction, subject to the issue in #1962. It is unspecified which note(s) are used to fulfill the transaction, probably the smallest if I remember correctly.

Does this answer your questions?

**Comment by ADumaine** [comment]
Almost :-)

If the 0.4 note was the only one used in the transaction, is the 0.6 node essentially 'left behind' and just flagged as unavailable until the change is returned?  Or is the 0.6 nullified along with the 0.4 note and a new note for the 0.9 (minus fees) created as unspent?

I am trying to determine/verify if the result of the transaction is just one unspent note or multiple remain if existed and not used before the tx.

Maybe the method should be called z_listbalanceafterreceviedbyaddress ;-)

Thank you!

**Comment by daira** [comment]
Notes that are not used in a transaction are still available for subsequent transactions.

To answer your Question 2, there is no automatic consolidation of notes at the moment. That would be issue #1961.

**Comment by ADumaine** [comment]
Thank you for your patience.

I now understand the unspent notes remain untouched until used.  It was not clear since there is no way to list them for a shielded address.
