### ISSUE TITLE
Zcash: there is no transaction information

### ISSUE THREAD

**Issue by jiangzhongbai** [zcash/zcash#3072]
I have installed the Zcash on ubuntu 16.04. However, after I enter ./src/zcash-cli listtransactions, there is no information. Is it normal? Is there anything wrong with my zcash?

**Comment by leto** [comment]
@jiangzhongbai yes, that is normal, you have no transaction history in a fresh install

**Comment by ioptio** [comment]
@leto is correct. @jiangzhongbai what behavior are you expecting with this call? If you haven't created any transactions then it shouldn't show anything.

**Comment by jiangzhongbai** [comment]
@leto I am trying to mine zcash. I just want to check out if I have mined the zcash

**Comment by ioptio** [comment]
How are you mining? If you are mining with zcashd, it is very unlikely you will find a block. If you are expecting payouts from a pool, you'll want to check with the pool to see if any payouts have been made.

**Comment by ioptio** [comment]
Closing this ticket. Feel free to reopen if necessary.
