### ISSUE TITLE
Overwinter: dns seeders are running with protocol version 170002

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#3073]
During an experiment (https://chat.zcashcommunity.com/channel/zcash-dev?msg=fjBDNiMmBbDLoM7pf)  of activating Overwinter on testnet at block 200000 we saw that upgrading nodes (protocol version 170003) which were stuck at block 199999, waiting for an Overwinter block, would still receive inbound connections from Sprout nodes (protocol version 170002).

This is probably due to the dns seeder running with protocol version 170002: https://github.com/zcash/zcash-seeder/blob/master/serialize.h#L63dn

These Sprouts nodes are eventually banned as they relay Sprout transactions and blocks which the upgrading node rejects.

**Comment by bitcartel** [comment]
Before activation, the testnet dns seeder will be updated with this branch: https://github.com/zcash/zcash-seeder/pull/4

**Comment by daira** [comment]
Superceded by #3099.
