### ISSUE TITLE
Question about anonymity

### ISSUE THREAD

**Issue by Tomas-M** [zcash/zcash#3085]
I'd like to ask about anonymity in ZCash.
Lets assume I have some coins on two transparent addresses, T1 and T2
Then, I send coins from T1 to a shielded address Z, and also I send coins from T2 to Z.

T1 -> Z
T2 -> Z

Is it possible to tell, in the blockchain, that the coins from T1 and T2 ended up on THE SAME shielded  address? This has very important security implications so I would like to be 100% sure about this.

Thank you very much

**Comment by bitcartel** [comment]
No.  An observer of the blockchain can only see that the T1 and T2 funds were shielded.  The observer learns nothing about the recipient's shielded address.  They cannot determine if the same shielded address was used or not.

**Comment by daira** [comment]
@Tomas-M if @bitcartel sufficiently answered your question, feel free to close this ticket.

**Comment by Tomas-M** [comment]
Thank you
