### ISSUE TITLE
Reconfigure Sapling builders to use --verbose in cargo test.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#3088]
Here's an example failing build for Sapling that doesn't give sufficient diagnostic information about why the build failed:

https://ci.z.cash/#/builders/17/builds/20

**Comment by nathan-at-least** [comment]
There's also an environment variable to convince rust to show stack traces, I believe, let's enable that.

**Comment by mms710** [comment]
This will be done in the new GitLab implementation

**Comment by str4d** [comment]
The Buildbot CI is long gone, and the Tekton CI probably does this? In any case this issue is stale.
