### ISSUE TITLE
Implement sapling as rust library for transaction generation and validation

### ISSUE THREAD

**Issue by imichaelmiers** [zcash/zcash#3102]
Zcash currently has challenges  on the horizon with cross platform support, lite clients, and network privacy, as well as the maintainability of a fork of the Bitcoin codebase.  Looking longer term, there is the possibility that zcash switches codebases or changes consensus mechanisms.  At the same time with sapling's new crypto,  the transaction generation and validation code needs a near complete rewrite for the new protocol. This is an opportunity.

Solutions to the above issues would all be considerably easier  if all of the code necessary to generate transactions, including maintaining a copy of the merkle tree and "wallet" code that stores, selects, and  assembles notes as inputs to a transaction , was in a separate library  distinct from networking and "consensus facing code"  (even though tx validation is part of  consensus  and probably should be a part of the library).

This would make it easy to support lite clients and to switch codebases. It would also make it easier to later produce software that submitted transactions via a mechanism that never touches the P2P network. This is important because both passive and active attacks can fingerprint the P2P network in ways that persist even if connections are over Tor.

It would also allow for improved security by keeping this library in a separate address space or other such countermeasures. 

Since the proof generation code is already in rust, the principle code that needs to be redone is for the merkle tree and a "wallet" code

**Comment by tromer** [comment]
This is an excellent idea.
There are different places to put the boundary of this library. For example a storage-constrained client may be be unable to store the nullifiers Merkle tree and forced to delegate this (perhaps at a cost to privacy). And a computationally-constrained client may be forced to outsource the zkSNARK proving. Ideally the library should support the corresponding modes of operation.

**Comment by str4d** [comment]
Upstream have made various improvements to the Bitcoin Core codebase that create better separation between the wallet and the network node. It's entirely possible that we could implement a wallet in Rust with support for (at least importing) the current `wallet.dat` files, and then hook it up to the existing C++ code via a C API.

We have not yet implemented the Merkle tree code for Sapling (#3056). At this stage it will likely be an extension of the Sprout code, and get serialized in the same coins database as the UTXOs and current Sprout tree. We could possibly implement that in Rust and access via a C API, but it might take more work to design an effective abstraction than we have time for.

**Comment by zookozcash** [comment]
Would this make it easier for third-parties to build Sapling-supporting wallets?

**Comment by str4d** [comment]
@zookozcash Probably. In particular, it could be compiled to JavaScript or WASM and then used in the various JS-based libraries and wallets.

**Comment by imichaelmiers** [comment]
By the way,  backward compatibility with sprout is probably not important for this code. If the migration mechanism for anyone with shielded TXs is run the original code or a migration mechanism, its fine. 99% of the userbase as zcash expands post sapling, will never have used sprout.

**Comment by mms710** [comment]
This is being done as part of the wallet work now.

**Comment by jsamol** [comment]
Hey! Any update on that? My team and I would love to use such a library in our JS-based library. I believe `librustzcash` provides the functionality that we actually need, but it seems quite heavy and not WASM-compilable at the moment.

**Comment by str4d** [comment]
This was completed in 2019/2020. The `zcash_primitives` Rust crate includes a transaction builder, which is exposed via `zcash_client_sqlite` for use as a light client (and is used as such in the Android and iOS SDKs).
