### ISSUE TITLE
Overwinter: Update insight explorer to support Overwinter tx

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#3105]
1. There is a fork https://github.com/str4d/bitcore-lib-zcash which supports v1 and v2 (Sprout) tx, and we should update this to support **_parsing_** of v3 (Overwinter) tx.

2. The explorer API should be updated to support **_returning_** new fields in v3 tx such as versionGroupId, nExpiryHeight, etc.

3. The explorer should be updated to visually **_display_** any relevant new fields related to v3 tx, such as nExpiryHeight and what branch the explorer is on e.g. Overwinter/Sapling.

**Comment by mms710** [comment]
This has been done! Closing.
