### ISSUE TITLE
equihash into yiimp

### ISSUE THREAD

**Issue by goodthebest** [zcash/zcash#3108]
Hi @str4d 
Do you have any implementation of equihash into Yiimp software] or any guide on this to accomplish it?

**Comment by goodthebest** [comment]
Perhaps your developers can place a 'pull request' code is here.
https://github.com/goodthebest/yiimp

**Comment by ioptio** [comment]
Hi @goodthebest check out this thread in the forums https://forum.z.cash/t/easy-to-follow-description-of-the-equihash-algorithm/12689/4 and the Equihash blog post https://blog.z.cash/why-equihash/

**Comment by lindanlee** [comment]
We're closing this ticket. Feel free to reopen.

**Comment by hashbook** [comment]
https://github.com/aabc/equihash-zcash-c/blob/master/basicSolver.c
https://github.com/aabc/equihash-zcash-c/blob/master/basicSolver-opt.c

this might help you

**Comment by DeckerSU** [comment]
https://github.com/DeckerSU/yiimp-stratum-equihash - here is public equihash implementation for yiimp.
