### ISSUE TITLE
Upgrade OpenSSL to 1.1.0h

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#3129]
We are currently using OpenSSL 1.1.0d.

Here are the CVEs fixed since that release:

https://www.openssl.org/news/vulnerabilities-1.1.0.html

To close this ticket:

- [x] Create a PR to upgrade openssl to 1.1.0h
- [x] Upload openssl 1.1.0h to our server

**Comment by daira** [comment]
*reads* https://www.openssl.org/news/openssl-1.1.0-notes.html

Yet more arithmetic bugs? Sigh. So glad we're not using that except in tests.

**Comment by str4d** [comment]
I have fetched the package to our depends server.
