### ISSUE TITLE
Time based nullifier

### ISSUE THREAD

**Issue by hosseamin** [zcash/zcash#3133]
Hi zcashco.
I'm not a cryptographer. I have some idea in mind. Would like to share....

I would like to know if there's a way to have shielded address with two valid spending keys and nullifiers.
 
If that's possible. I hope so. Then read the rest.

Just like bitcoin's OP_CHECKSEQUENCEVERIFY.  We can have reverse for that having a key that can only spend until (for example) one year and after that the other key should be able to revive it.

Then first key is time based and second one can revive forever.

After that zcash can detect all of time based nullifiers and prune them when can't get spent anymore.

Thanks for reading :)

**Comment by hosseamin** [comment]
I figured this is not possible. Because there's no way of linking nullifiers unless they both stored until spent, thus it's useless.

**Comment by daira** [comment]
Nullifiers are associated with notes, not addresses.

The closest potential feature to what you're asking for that we've considered is address expiry (#718).

**Comment by hosseamin** [comment]
@daira I don't think that's related. I'm thinking of a way to have life time for storing nullifiers. 
Probably there's a need in future to do recycling of nullifiers in order to store less and search less.
