### ISSUE TITLE
Least Authority Issue E: CTxMemPool::check()​ does nothing when turned on

### ISSUE THREAD

**Issue by daira** [zcash/zcash#3134]
Synopsis:​ ``​CTxMemPool::setSanityCheck``​ converts a float to a 32-bit unsigned integer. When doing so, the exponent part is discarded. However, if the integer part overflows the target size of the integer, then the behaviour is undefined.
```
void setSanityCheck(double dFrequency = 1.0) { nCheckFrequency = dFrequency * 4294967296.0; }
```
Impact: ​The value of ``​nCheckFrequency``​ is undefined. On x86-64 platform running Debian GNU/Linux with g++ 7.3.0, the value was set to ​0​. So, the sanity check (the ​check​ function in ​txmempool.cpp ​that makes sure that the pool does not contain two transactions that spend the same input, etc) returns without doing any checks.

**Comment by bitcartel** [comment]
Confirming that the value is undefined.

0 is returned here:
https://repl.it/repls/EdibleIndigoServer

4294967295 is returned here:
http://cpp.sh/7vyud

This was fixed upstream with two commits:
https://github.com/bitcoin/bitcoin/commit/e9e616323bc44daf61f4358f5b2de58e90b5c602
https://github.com/bitcoin/bitcoin/commit/53a6590f496b25174c740927243bf8307541b0b9#diff-8304b3e94624036c3673f31eeb7e9de0R510
