### ISSUE TITLE
Zcashd eats all of memory

### ISSUE THREAD

**Issue by DeaVulTan** [zcash/zcash#3135]
#### If so, please list the steps to reproduce below:
1. Install latest zcashd version
2. Run it with configuration above

**Conf**
`datadir=/var/lib/zcash
rpcuser=**********
rpcpassword=*************
mainnet=1
addnode=mainnet.z.cash
rpcport=8232
daemon=1
server=1
testnet=0
gen=0`

### Expected behaviour
Zcashd eats full of my memory (27GB of 32GB)
For the day, he dials 10GB of RAM. And it continues to increase

### Actual behaviour + errors
Next, the server kills the process

### The version of Zcash you were using:
Zcash Daemon version v1.0.15

### Machine specs:
- OS name + version: Ubuntu + 16.04.4 LTS (Xenial Xerus)
- CPU: Intel(R) Xeon(R) CPU E3-1230 V2 @ 3.30GHz
- RAM: 32919572 kB ~ 32 GB
- Disk size: 512 GB
- Disk Type (HD/SDD): SSD
- Linux kernel version: 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Compiler version: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609

**Comment by mdr0id** [comment]
@DeaVulTan Is your Zcashd fully synced on mainnet when you encountered the issue above? 

More specifically, what is the current block height shown in your zcashd?

**Comment by DeaVulTan** [comment]
My Zcashd is fully synced.
  "blocks": 299746,

**Comment by mdr0id** [comment]
@DeaVulTan Thank you for your quick response.

Now that your node is fully synced, do you still see the memory spikes while zcashd is running?

I am actively investigating this and noticed a considerable spike during the initial full sync(expected). However, once the node is fully synced I am not seeing noticeable spikes. 

Can you confirm whether the 10GB/day was prior to the full sync?

**Comment by DeaVulTan** [comment]
This is not a spikes. Spike return to their original position, but ZCashd - takes more and more memory.

Yep, i can, my zcashd is eating 14GB now.

Tasks: 53
Memory: 14.0G
CPU: 4h 24min 46.077s

**Comment by mdr0id** [comment]
@DeaVulTan Thank you for the provided information. We will continue to investigate this.

**Comment by bitcartel** [comment]
What does `zcash-cli getmempoolinfo` show?  Currently there are almost 2000 txs in the mempool which are waiting to be mined.  Have those txs propagated to your node?

**Comment by DeaVulTan** [comment]
mempoolinfo

  "size": 1571,
  "bytes": 111421232,
  "usage": 236310816

**Comment by lindanlee** [comment]
We don't have any meaningful feedback at this time. We may be able to investigate more once we set up additional testing infrastructure. Sorry about this problem.

**Comment by cannonballdex** [comment]
Same Problem, Eating up 16 Gb and shutting down after running about two days.

**Comment by daira** [comment]
If this still happens with recent zcashd, feel free to reopen.
