### ISSUE TITLE
add paramsdir option for zcash.conf and the commandline

### ISSUE THREAD

**Issue by taw00** [zcash/zcash#3145]
I want to be able to move the .zcash-params directory, name it anything I want, and then reference it with commandline and/or conf file options. fetch-params.sh would have to have a target commandline option I suppose.

Why? Because I want to be able to systemd-ify zcashd so that it can be managed like a system-level service (make it "properly" sysadmin friendly). I.e., well-controlled start, stop, etc. and have systemd be able to do cool things like send status emails, alert if zcashd crashes, and of course, auto-recover cleanly. And... to be able to do things like `dnf upgrade -y ; reboot` without concern of data corruption, etc. And finally, I may be able to make zcashd friendlier for selinux "out of the box" so to speak.

What is making this complicated is that to enable zcashd as a systemd service, it should be run as a system user. System users (zcashuser username in this case) don't generally have a $HOME.  You would stick .zcash-params in a zcashuser owned /var/lib or /usr/share directory or some such.

In the meantime, I am creating the zcashuser with a home dir of /var/lib/zcash, but depending on that just doesn't seem to be "correct". So....

-paramsdir and an option for the zcash.conf file would be grand.

Thanks! -t

**Comment by lindanlee** [comment]
We plan to implement something that addresses your concerns eventually--see the linked ticket above. Let us know if we misunderstood!

**Comment by taw00** [comment]
Yup. That is exactly it.

FYI. I have worked around this by creating a location in the place I want... and then symlinking to it from .zcash-params but, of course, that is not ideal. :) Thanks for responding.

**Comment by lindanlee** [comment]
@taw00, thanks for that information! :)
