### ISSUE TITLE
[dependency package not available] proton 0.17.0 URL => 404

### ISSUE THREAD

**Issue by ca333** [zcash/zcash#3174]
The download URL for [proton](https://github.com/zcash/zcash/blob/master/depends/packages/proton.mk#L3) results in 404. 
Current hosted versions on utah.edu servers are 0.21.0. and 0.22.0 according to http://apache.cs.utah.edu/qpid/proton/ - apache.org is still hosting 0.17.0 under http://archive.apache.org/dist/qpid/proton/0.17.0/qpid-proton-0.17.0.tar.gz

**Comment by bitcartel** [comment]
@ca333 Are you using AMQP in a project?  Can you share details?  Thanks!
