### ISSUE TITLE
Make note class polymorphic to support Sprout, Sapling and future types of notes.

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#3194]
In a meeting @str4d @daira @bitcartel felt that this would be a good design, which #3061 would depend on.

**Comment by daira** [comment]
We can define methods that return higher-level abstractions, like a payment address, *if* those are known. (A Sprout note, for instance, doesn't have the pk<sub>enc</sub> component of the payment address, and a Sapling note only knows its ρ value if it is a "positioned" note.)

**Comment by daira** [comment]
Note that even if the interface isn't common, there are many places where we are just passing through notes or addresses to another layer of the code, and so the benefit of polymorphism isn't necessarily lost.
