### ISSUE TITLE
DB corruption introduced in latest commits

### ISSUE THREAD

**Issue by rex4539** [zcash/zcash#3200]
### Describe the issue
After the commits of April 19-20 I'm getting a 100% reproducible DB corruption.

### Can you reliably reproduce the issue?
100% reproducible.
Just compile from master on macOS.

### Expected behaviour
No DB corruption.

### Actual behaviour + errors
```
2018-04-23 17:56:05 ERROR: CheckTransaction(): joinsplit does not verify
2018-04-23 17:56:05 ERROR: CheckBlock(): CheckTransaction failed
2018-04-23 17:56:05 ERROR: VerifyDB(): *** found bad block at 311006, hash=000000000601be88250c4425079a2158ffde4e9129bad63f3a639f0a2ce776ca

2018-04-23 17:56:05 : Corrupted block database detected.
Please restart with -reindex to recover.
2018-04-23 17:56:05 Aborted block database rebuild. Exiting.
2018-04-23 17:56:05 Shutdown: In progress...
2018-04-23 17:56:05 StopRPC: waiting for async rpc workers to stop
2018-04-23 17:56:05 StopNode()
2018-04-23 17:56:05 scheduler thread interrupt
2018-04-23 17:56:05 Shutdown: done
```

### The version of Zcash you were using:
1.1.0-0e65c245f-dirty

### Machine specs:
- OS name + version: macOS 10.13.5 (17F45c)
- CPU: Intel Core i7 2,2 GHz
- RAM: 8 GB
- Disk size: 250,14 GB
- Disk Type (HD/SDD): SSD
- Linux kernel version (uname -a):  Darwin Kernel Version 17.6.0: Fri Apr 13 19:57:44 PDT 2018; root:xnu-4570.60.17.0.1~3/RELEASE_X86_64 x86_64
- Compiler version (gcc -version): Apple LLVM version 9.1.0 (clang-902.0.39.1)

### Any extra information that might be useful in the debugging process.
[debug.log](https://github.com/zcash/zcash/files/1939681/debug.log)

The bug was introduced somewhere between April 19-20. I have been compiling daily and previous builds were fine.

After restarting with `-reindex` I enter in a corruption loop and the corruption is never actually fixed.

**Comment by str4d** [comment]
Have you been testing master after 1.1.0 but before now? If so, what was the last commit on master that you tried, which worked for you?

**Comment by rex4539** [comment]
I'm pretty confident that the following commit broke it.

https://github.com/zcash/zcash/commit/77889933e72a7bcc68928a1b8964087092c4bd58

According to my post https://chat.zcashcommunity.com/channel/zcash?msg=sMeJjYCH7ZmTWzrTk I was running `Zcash Daemon version v1.1.0-5821bb0a4-dirty` without issues.

**Comment by rex4539** [comment]
ok, I will test once it's merged.

**Comment by rex4539** [comment]
Fixed with latest commits.
