### ISSUE TITLE
Make SpendingKey and PaymentAddress classes polymorphic to support Sprout, Sapling, and future types of addresses

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#3204]
See also #3194 (note polymorphism) and #3202 (pulls in part of upstream's transparent address encoding polymorphism).

**Comment by str4d** [comment]
@arcalinea and I looked into this, trying to decide what the best way to approach this would be. Here are the options we looked at, which we'd like to get more thoughts on:

## 1: Interface with subclasses

We extract some common API out of the current `PaymentAddress` etc. classes, making it a virtual parent class. We then rework the internals of the current `PaymentAddress` etc. classes to fit the APIs, and rename them `SproutPaymentAddress` etc.

Pros:
- Maybe we don't need to alter the API calls in too many places?

Cons:
- Maybe we *do* still need to alter or introduce API calls in many places?
  - Classes can no longer be subclasses of basic datatypes if they are a single-element class (e.g `SpendingKey`), so we'd need to introduce more abstraction / getters.
- For APIs that need e.g. diversifiers, we'd need to either make the interface always take them (and ignore when necessary), or figure out the actual class type and cast, then use it appropriately.

Example type layout:

```cpp
class PaymentAddress;

class IncomingViewingKey;
{
    virtual PaymentAddress address(uint32_t d = 0);
}

class SpendingKey
{
    virtual PaymentAddress address();
}

class SproutPaymentAddress : PaymentAddress
{
    uint256 a_pk;
    uint256 pk_enc;
}

class SproutSpendingKey : SpendingKey
{
    uint252 sk;
    PaymentAddress address(uint32_t d) {
        return ConvertToSproutPaymentAddress(sk);
    }
}

class SaplingPaymentAddress : PaymentAddress
{
    uint32_t d;
    uint256 pkd;
}

class SaplingIViewingKey : IncomingViewingKey
{
    uint256 ivk;
    PaymentAddress address(uint32_t d) {
        return ConvertToSaplingPaymentAddress(sk);
    }
}

class SaplingSpendingKey : SpendingKey
{
    uint256 sk;
    PaymentAddress address() {
        return ConvertToSaplingPaymentAddress(sk);
    }
}
```

## 2a: Variants

This is what upstream does (and thus we do) for t-addrs. We rename `PaymentAddress` etc. to `SproutPaymentAddress`, and then define a `boost::variant` named `PaymentAddress` etc., which can be one of the supported types, or an "invalid" type. We then use plain functions to convert between generic types via `boost::static_visitor`.

Pros:
- No changes to Sprout classes aside from naming
- Classes that encapsulate a single element can be subclasses of that element's datatype.
- Each class can deal with its own conversions, and the generic conversion functions just call into them.
- Slightly more flexible than the class interface case?
  - In e.g. diversifier case, can write a context-specific visitor for e.g. the wallet, which can take the wallet pointer as input, and looks up the default diversifier for Sapling `ivk`s when converting to addresses.
- Decoding doesn't use exceptions to indicate invalid addresses anymore, which makes for a cleaner and more reliable API.

Cons:
- Need to update every generic API call to instead use the new functions (like #3202 is doing for t-addrs).
- Still need to convert to the underlying type when necessary (but Boost has a nice API to work around this).
- Need an explicit "invalid" type in the variant.
- Upstream have [concerns about the memory usage](https://github.com/bitcoin/bitcoin/pull/11117#issue-137111261) of `boost::variant`, and appear to want to replace it with a native type (which may mean going back in the direction of virtual classes, or something else).

```cpp
class SproutPaymentAddress
{
    uint256 a_pk;
    uint256 pk_enc;
}

class SproutSpendingKey : uint252
{
    SproutPaymentAddress address() {
        return ConvertToSproutPaymentAddress(sk);
    }
}

class SaplingPaymentAddress
{
    uint32_t d;
    uint256 pkd;
}

class SaplingIViewingKey : uint256
{
    SaplingPaymentAddress address(uint32_t d) {
        return ConvertToSaplingPaymentAddress(sk);
    }
}

class SaplingSpendingKey : uint256
{
    SaplingPaymentAddress address() {
        return ConvertToSaplingPaymentAddress(sk);
    }
}

class InvalidEncoding
{}

typedef boost::variant<InvalidEncoding, SproutPaymentAddress, SaplingPaymentAddress> PaymentAddress;
typedef boost::variant<InvalidEncoding, SproutSpendingKey, SaplingSpendingKey> SpendingKey;
```

Then to convert between types generically you'd use something like:

```cpp
class SpendingKeyToPaymentAddress : public boost::static_visitor<std::string>
{
public:
    SpendingKeyToPaymentAddress() {}

    PaymentAddress operator()(const SproutSpendingKey& k) const
    {
        return k.address();
    }

    PaymentAddress operator()(const SaplingSpendingKey& k) const
    {
        return k.address();
    }

    PaymentAddress operator()(const InvalidEncoding& no) const { return no; }
};

class IViewingKeyToPaymentAddress : public boost::static_visitor<std::string>
{
public:
    IViewingKeyToPaymentAddress(const CChainParams& pwallet) : pwallet(pwallet) {}

    PaymentAddress operator()(const SproutIViewingKey& k) const
    {
        return k.address();
    }

    PaymentAddress operator()(const SaplingIViewingKey& k) const
    {
        return k.address(pwallet->GetDefaultSaplingDiversifier(k));
    }

    PaymentAddress operator()(const InvalidEncoding& no) const { return no; }
};

PaymentAddress GetPaymentAddress(SpendingKey k) {
    return boost::apply_visitor(SpendingKeyToPaymentAddress(), k);
}

PaymentAddress GetPaymentAddress(IViewingKey k, pwallet) {
    return boost::apply_visitor(IViewingKeyToPaymentAddress(pwallet), k);
}
```

Or if you know you have a specific type:

```cpp
assert(boost::get<SproutPaymentAddress>(&address) != nullptr);
SproutPaymentAddress addr = boost::get<SproutPaymentAddress>(address);
```

Encoding and decoding would happen similarly to t-addrs:

```cpp

std::string EncodePaymentAddress(const PaymentAddress& addr)
{
    return boost::apply_visitor(PaymentAddressEncoder(Params()), addr);
}

PaymentAddress DecodePaymentAddress(const std::string& str)
{
    std::vector<unsigned char> data;
    if (DecodeBase58Check(str, data)) {
        if (MatchesSproutPaymentAddress(data)) {
            return SproutPaymentAddress(data);
        }
        if (MatchesSaplingPaymentAddress(data)) {
            return SaplingPaymentAddress(data);
        }
    }
    return InvalidEncoding();
}

bool IsValidPaymentAddress(PaymentAddress addr) {
    return addr.which() != 0;
}
```

## 2b: Variants + optionals

Same as above, but instead of having an explicit "invalid" type in the variant, return a `boost::optional` from the decoding function.

Pros:
- No "invalid" type in variant

Cons:
- Assumes we will never need an "invalid" type outside of decoding (is this true?)
- After decoding, need to dereference to get at the variant inside

```cpp
typedef boost::variant<SproutPaymentAddress, SaplingPaymentAddress> PaymentAddress;

boost::optional<PaymentAddress> DecodePaymentAddress(str);
```

**Comment by bitcartel** [comment]
For #3194, after some experimenting, I'm leaning towards good old fashioned classes because:

1. familiarity for engineers
2. less Boost!
3. std::variant not available for C++11, requires C++17
4. upstream experience of using variants

**Comment by str4d** [comment]
After some experimenting, I'm enjoying the use of `boost::optional` as a return-type for `DecodePaymentAddress`, so if we end up using classes for address polymorphism, then I'll go with what I'll call "1b": interface classes, with `boost::optional` to return either a valid generic `PaymentAddress` or `boost::none` if the given string was invalid.

**Comment by str4d** [comment]
After more experimenting, I've now switched to option 2a: `typedef boost::variant<InvalidEncoding, SproutPaymentAddress> PaymentAddress` etc., because `boost::optional<boost::variant<...>>` is very un-ergonomic, and I found that context-specific visitors were an easier way to implement per-type address semantics than virtual functions. I have a working branch [here](https://github.com/str4d/zcash/tree/3058-sapling-addresses), tested [here](https://ci.z.cash/#/builders/6/builds/147).
