### ISSUE TITLE
Change check that at least one of tx_in_count, nShieldedSpend or nJoinSplit are nonzero

### ISSUE THREAD

**Issue by ebfull** [zcash/zcash#3209]

**Comment by Eirik0** [comment]
This ended up being included in PR #3191, but there was an issue with checking the outputs, so we are fixing that as part of this issue.

**Comment by Eirik0** [comment]
Also as part of this I will be doing "Spend descriptions and output descriptions are not present in coinbase transactions" which is part of #3065
