### ISSUE TITLE
build zcash error,somebody help.

### ISSUE THREAD

**Issue by JJslive** [zcash/zcash#3222]
I build from source in my centos6.5. stop in './zcutil/build.sh -j$(nproc)' this step. 
info:"configure.ac:914:error: possibly undefined macro:PKG_CONFIG_LIBDIR 
               If this token and others are legitimate,plaease use m4_pattern_allow.
               See the Autoconf documentation.
       autoconf: /usr/local/bin/autoconf failed with exit status: 1".

Similarly, I execute "make clean" in the zcash root directory, but it prompts "* * * can create a target" clean "Stop it"。

**Comment by mdr0id** [comment]
We don't support CentOS 6.5, but we are working to support CentOS 7
