### ISSUE TITLE
Zcash Wallet: Retreive All keys when using RPC API

### ISSUE THREAD

**Issue by 5-digits** [zcash/zcash#3224]
Hi Zcash Team,
is there any recipes or methods used to escape saving the private key in the zcash daemon 
because i found many problems to fix that even when sending a raw transaction to the network

**Comment by ioptio** [comment]
Can you clarify what you mean by "escape saving"? Are you trying to save your private key outside the client?

**Comment by 5-digits** [comment]
No, i mean how to check unspent input for a z-adress wallet without save it in wallet.dat ( import the private key)

**Comment by leto** [comment]
FYI, when importing a viewing key, just like a normal address, it can (currently) never be removed from that wallet.dat

**Comment by ioptio** [comment]
Considering this ticket addressed. Please re-open if you have more related questions.
