### ISSUE TITLE
Update FAQ entry about equihash mining

### ISSUE THREAD

**Issue by kiwseb** [zcash/zcash#3241]
Hi All
It's time to think about changing the algorithm in ZEC because Chinese friends came up with the idea to make an equihash miner 
Z9 mini will be delivered on this summer 
regards :) 
any ideas ?
any plans 4 changing algo ? 
BTW Yours FAQ in section mining is now outdated :P

 Specifications and other information of the Antminer Z9 mini are as mentioned below.
   Hashing algorithm: Equihash
    Power consumption: 300W
    Hashrate: 10k Sol/s ± 5%

Shipping: 20-30 June No shipping to HongKong, Macau and Taiwan.

**Comment by ioptio** [comment]
Updated https://z.cash/support/faq.html#mining-algorithm and https://blog.z.cash/why-equihash/
