### ISSUE TITLE
Difficulty adjustment as protection against ASICs

### ISSUE THREAD

**Issue by zawy12** [zcash/zcash#3244]
update: See next comment. <strike>The current difficulty algorithm may be sufficient protection if ASICs cause 10x jumps in hash rate.  Zcash typically sees 3x jumps in hash rate everyday and it's doing well.  But if sudden changes in hash rate get any larger, a faster algorithm will be necessary.  Small and medium-sized Monoero / Cryptonote coins (35 of them that I track) have been switching to my **[LWMA](https://github.com/zawy12/difficulty-algorithms/issues/3)** algorithm which is faster with 1/2 as many delays as Zcash's, with nearly as good stability (StdDev in D of 0.13 instead of 0.12). We are now testing an improved **[D-LWMA](https://github.com/zawy12/difficulty-algorithms/wiki/Dynamic-LWMA)** version that dynamically switches to a faster algorithm via a smaller N window if a clear "hash attack" event begins.  Here is how it compares to Zcash when hashrate suddenly changes </strike>

![image](https://user-images.githubusercontent.com/18004719/39660901-3a8c0bd8-5016-11e8-90dd-3eb4a3ddef15.png)

**Comment by zawy12** [comment]
For complex reasons I no longer recommend D-LWMA, but incorporated the good part of the idea in LWMA so there is now LWMA-2. 

But if Zcash desires an enhancemed DA, LWMA (safer than LWMA-2) is now live on two Zcash clones. They are performing better than Zcash in my "delays" and "on-off mining" metrics, despite one being very small (Zelcash) and the other having a T=600 instead of T=150 (BTG). At least BTG's POW is different and part of the improvement (by being new if nothing else).  The LWMA code is by @h4x3rotab, but [my modification of his code](https://github.com/zawy12/difficulty-algorithms/issues/3#issuecomment-388386175) with comments may be helpful. 

Here are last-24 hour images for comparison from my Difficulty Watch page. Red is "blocks obtained at low difficulty from on-off minig" and blue spikes or dots is "delays".  The red spike for BTG is about the worst it's had since their fork. BTG is smoother because it's only 144 blocks per day.

![image](https://user-images.githubusercontent.com/18004719/43136672-79fd422e-8f17-11e8-942a-94b41d14e704.png)

![image](https://user-images.githubusercontent.com/18004719/43136717-87b86bb4-8f17-11e8-8500-95078156d6c2.png)

![image](https://user-images.githubusercontent.com/18004719/43136734-94737308-8f17-11e8-9736-fe1cacdf07e1.png)

Zelcash used to look like HUSH and Zencash, which still have Zcash's algorithm:

![image](https://user-images.githubusercontent.com/18004719/43136879-0dba06be-8f18-11e8-83b5-21ff451df463.png)

![image](https://user-images.githubusercontent.com/18004719/43138763-eee95d4c-8f1d-11e8-85d7-77bccca21905.png)

**Comment by mms710** [comment]
@str4d can you take a look at this and give your thoughts?

**Comment by zawy12** [comment]
I do not explicitly recommend Zcash do anything because their algorithm is good.  But for comparison sake here is a history of my charts for Zcash verses BTG and then Hush verses Zelcash.  (Digishield verses LWMA).  Note that some of the plots for Zcash and Hush are obviously invalid.

http://wordsgalore.com/diff/coins/zcash.html
http://wordsgalore.com/diff/coins/btg.html

http://wordsgalore.com/diff/coins/hush.html
http://wordsgalore.com/diff/coins/zelcash.html

**Comment by mms710** [comment]
We're closing this ticket because there's nothing for us to do, but this data will be available in the archives for future reference.
