### ISSUE TITLE
Compile without download each time Boost, OpenSSL etc...

### ISSUE THREAD

**Issue by miranos** [zcash/zcash#3245]
Hi,

I want compile Zcash without downloading each time Boost, OpenSSL, Rust etc... ?

I want install them one time only, and compile it using:
```
./autogen.sh
./configure
make
sudo make install
```

Your help is very appreciated !

--
I noticied that when i launch:
`./zcutil/build.sh -j$(nproc)`

They are downloaded and installed, but when i try to recompile, they are downloaded again !

**Comment by rex4539** [comment]
I don't see this behavior.

After I compile once, then I just do a `git pull` and then run `./zcutil/build.sh`

This doesn't download anything. It directly compiles the changes.

**Comment by str4d** [comment]
If you run `build.sh` twice, almost nothing should happen the second time (dependencies will be re-extracted from their now-pre-compiled cache, and configure checks will happen, but that's about it).

If you build, then `git pull` and rebuild, you *may* see some dependencies re-download if they have been changed recently. This is currently the case for Sapling dependencies (specifically librustzcash, which is being altered regularly). But only the dependencies that changed (and other dependencies that depend on them) should get rebuilt; the rest should be extracted from cache.

**Comment by ioptio** [comment]
Feel free to reopen if you have additional thoughts on this.
