### ISSUE TITLE
Create a document on transaction expiry to circulate to wallets/exchanges

### ISSUE THREAD

**Issue by lindanlee** [zcash/zcash#3254]
After the overwinter network upgrade, a feature called transaction expiry will make unmined transactions expire after ~10 minutes/20 blocks. This is great, because people will get their funds back at the end of the expiry period, and the expiry cleans out the mempool congestion.

Typical "UX behavior" as in wallet behavior is not outlined anywhere yet. This is what we need to do. Specifically:

There could be various reasons why a transaction would expire and that you should try to help the user troubleshoot
Address the interface elements and interaction methods to use before, when, and after a transaction is expired. 

TODO: 
- add the transaction expiry instructions to the UX developer guidelines
- add a note in the overwinter countdown/network upgrade pages about it to point to the UX guidelines 
- draft an email for Brad to send in conversations

**Comment by ioptio** [comment]
We did this in https://zcash.readthedocs.io/en/latest/rtd_pages/nu_dev_guide.html#overwinter & https://zcash.readthedocs.io/en/latest/rtd_pages/ux_wallet_checklist.html
