### ISSUE TITLE
z_signmessage RPC does not exist

### ISSUE THREAD

**Issue by leto** [zcash/zcash#3260]
### Describe the issue

One may prove they own a Zcash taddr by using `signmessage`, just as in Bitcoin, but there is no corresponding z_signmessage to prove the ownership of a shielded address.

### Can you reliably reproduce the issue?
Yes

### Expected behaviour
A Zcash user should be able to prove they own a specific zaddr by producing a signed message, by calling a new z_signmessage or perhaps extending the existing signmessage to also handle zaddrs.

### Actual behaviour + errors
Current docs do not specify that signmessage only works on taddrs and gives: 
```
error code: -3
error message:
Invalid address
```

### The version of Zcash you were using:

master branch

**Comment by mdr0id** [comment]
duplicate #1770 , resolution #3159
