### ISSUE TITLE
Importing t-address crashes the Zcash Daemon

### ISSUE THREAD

**Issue by 5-digits** [zcash/zcash#3261]
when i'm trying to import an existant t-address by passing the private key, the Zcash daemon stop working and crush as Process on ubuntu, so restart the Zcash-cli again I have to kill zcashd from Terminal 

How to fix that issue ?

**Comment by ioptio** [comment]
Ping @5-digits we'd like to better understand this issue, can you please address the question above? Thanks!

**Comment by ioptio** [comment]
Feel free to reopen this ticket if the issue still persists.
