### ISSUE TITLE
Emergency Preparedness and Response for halting Sapling activation

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#3270]
Project teams should know how to respond if Sapling activation must be halted.  This ticket is for project teams to decide on the response process and prepare in advance any required material to be used and shared with relevant third-parties.

Related to https://github.com/zcash/zcash/issues/3040 "Contingency plans for consensus flaws found before activation of an upgrade"

**Comment by nathan-at-least** [comment]
A specific contingency for the most extreme cases is specified in #3311. That contingency would be suitable if we have very little time between when the flaw is discovered and activation is planned.

**Comment by nathan-at-least** [comment]
If we discover a fatal flaw in Sapling in time for the 2.0.1 timeframe, then we should almost certainly disable the activation logic in the 2.0.1 release with the minimal code changes. This may look something like setting the activation height to infinity.

If we discover the flaw after 2.0.1 ships, we should immediately release a #3311 hotfix release with the activation height set prior to Sapling activation.

Then we should start developing the best possible consensus rule fix as part of the standard release cycle. If we don't have confidence we can repair the Sapling flaw entirely within a release cycle, then we should set up new consensus rules that re-enable pre-sapling functionality (thus ending the #3311 coinbase-transaction-only restrictions).

**Comment by bitcartel** [comment]
In a single commit, for the release:

- Change branch id
- Remove activation height
- Bump protocol version of Sapling activation
- Bump protocol version of node

**Comment by braddmiller** [comment]
I'm going to close this issue since we're past Sapling activation and we have emergency response prep in place.
