### ISSUE TITLE
Zcash Master Signing Key Signature Invalid

### ISSUE THREAD

**Issue by durbanpoison** [zcash/zcash#3276]
### Describe the issue

When I try to update zcashd I receive an error message.

#### If so, please list the steps to reproduce below:

1. sudo apt-get update
2. error shows up

Note that I am downloading the update over Tor.

### Expected behaviour
Tell us what should happen

zcashd should update without an error message

### Actual behaviour + errors

When I try to update zcashd I receive this error:

`W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: tor+http://zcaptnv5ljsxpnjt.onion jessie Release: The following signatures were invalid: BADSIG 63C4A2169C1B2FA2 Zcash Master Signing Key  `

`W: Failed to fetch tor+http://zcaptnv5ljsxpnjt.onion/dists/jessie/Release.gpg  The following signatures were invalid: BADSIG 63C4A2169C1B2FA2 Zcash Master Signing Key  `

`W: Some index files failed to download. They have been ignored, or old ones used instead.`

### The version of Zcash you were using:

Zcash Daemon version v1.1.0

### Machine specs:
- OS name + version: Ubuntu 16.04 64bit
- Linux kernel version (uname -a): 4.4.0-119-generic #143-Ubuntu SMP Mon Apr 2 16:08:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mms710** [comment]
We'd like to fix this by migrating our CI to a different tool. Once we're done with this we'll verify this is fixed and update this issue.

**Comment by mms710** [comment]
This has been fixed. Closing.
