### ISSUE TITLE
Use correct Sapling encoding format

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#3277]
Users building and running from master over the past two weeks (since https://github.com/zcash/zcash/commit/1f8be05b635661a2f5472dda6c96be624d58dbcb) will have had Sapling state for the best anchor (the empty tree root) flushed to disk.  This would have used an incorrect encoding format.

To resolve this issue:

1. Use the version of librustzcash with the fixed encoding

2. Change the prefix used for Sapling anchors from 'X' and 'x' to something else.  This means any data currently stored under 'X' and 'x' will never be used, and this prefix should not be used in future without first deleting any data stored under it.

3. (Optional) Gate existing calls which result in Sapling state being cached and then flushed to disk, so that they only execute when Sapling is active.

**Comment by bitcartel** [comment]
1 and 2 are handled by https://github.com/zcash/zcash/pull/3275

**Comment by daira** [comment]
It looks like #3275 also handled 3: https://github.com/zcash/zcash/pull/3275/files#diff-81e4f16a1b5d5b7ca25351a63d07cb80R142 . Can this be closed?
