### ISSUE TITLE
16: mandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element)

### ISSUE THREAD

**Issue by liuxun1977** [zcash/zcash#3280]
./zcash-cli sendrawtransaction "030000807082c40301df1dc0c4f938bef1744e26789ff84e1685983ad6ec5655acc8fa3d4d8a1e8225010000006b483045022100be9d71a9b50929f530d86a283106cb3d85519b566108ecc2dab5845d4472067702202c91579521e090344d72569dc9da73475abc83f894ece600ffa9f745407cb3d901210266f3c737189855ce44710b09ed2106c0bf28c57f6e89869e773305130140df25ffffffff02180a2707000000001976a914cfd30c70ec20ab8d46eb0ac28fc8f7ce72368b3388ac1b95ba0a000000001976a914c92336d9ad37ac0671aea7cdecb40056b4be13c988ac00000000a4a6030000"
error code: -26
error message:
16: mandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element)

**Comment by ioptio** [comment]
Can you give more context with how you created the transaction? Did you use zcash-cli for this? Also, is this on main or testnet? As much information you can provide will help us diagnose with you.

**Comment by liuxun1977** [comment]
@ioptio

**Comment by ioptio** [comment]
Let's continue the discussion on referenced issue above and close this one @liuxun1977.

We're investigating this now.

**Comment by liuxun1977** [comment]
@ioptio  Did you find that out?
