### ISSUE TITLE
Compile problem.

### ISSUE THREAD

**Issue by liangstein** [zcash/zcash#3282]
Centos 7,  gcc5.5, binutils2.28, newest zcash source tarball,  after running ./zcutil/build.sh -j20,  compilation cannot pass, error below:

mv -f compat/.deps/libbitcoin_util_a-glibcxx_sanity.Tpo compat/.deps/libbitcoin_util_a-glibcxx_sanity.Po
/home/liangstein/zcash-1.1.0/depends/x86_64-unknown-linux-gnu/share/../native/bin/ccache g++ -m64 -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config  -fPIC -DBINARY_OUTPUT -DCURVE_ALT_BN128 -DBOOST_SPIRIT_THREADSAFE -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Wstack-protector -fstack-protector-all -Wl,-z,relro -Wl,-z,now -pie -pipe  -O1 -g -Wstack-protector  -fstack-protector-all -fPIE -fvisibility=hidden -DSTATIC -I. -I./obj -pthread -I/home/liangstein/zcash-1.1.0/depends/x86_64-unknown-linux-gnu/share/../include -I./leveldb/include -I./leveldb/helpers/memenv -I/home/liangstein/zcash-1.1.0/depends/x86_64-unknown-linux-gnu/include   -I/home/liangstein/zcash-1.1.0/depends/x86_64-unknown-linux-gnu/include   -I./secp256k1/include -I./snark -I./snark/libsnark -I./univalue/include  -DMONTGOMERY_OUTPUT -I/home/liangstein/zcash-1.1.0/depends/x86_64-unknown-linux-gnu/share/../include/  -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -DMULTICORE  -Wformat -Wformat-security -Wstack-protector -fstack-protector-all -fwrapv -fno-strict-aliasing -pipe -O1 -g -fopenmp -fwrapv -fno-strict-aliasing -Wno-builtin-declaration-mismatch -MT zcash/libzcash_a-Address.o -MD -MP -MF zcash/.deps/libzcash_a-Address.Tpo -c -o zcash/libzcash_a-Address.o `test -f 'zcash/Address.cpp' || echo './'`zcash/Address.cpp
/home/liangstein/binutils2.28/bin/ld: cannot find -lpthread
/home/liangstein/binutils2.28/bin/ld: cannot find -lm
/home/liangstein/binutils2.28/bin/ld: cannot find -ldl
/home/liangstein/binutils2.28/bin/ld: cannot find -lpthread
/home/liangstein/binutils2.28/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
make[3]: *** [libsnark/gtests] Error 1
make[3]: Leaving directory `/home/liangstein/zcash-1.1.0/src/snark'
make[2]: *** [snark/libsnark.a] Error 2
make[2]: *** Waiting for unfinished jobs....

**Comment by ioptio** [comment]
Related to https://github.com/zcash/zcash/issues/2817

Any insight, @ianamunoz ?

**Comment by ianamunoz** [comment]
You could try following this prescription in this Dockerfile which compiles functionally:
https://github.com/ianamunoz/docker-zcash/blob/centos-v1.1.0/Dockerfile

**Comment by liangstein** [comment]
Follow the Dockerfile and compilation passed.
