### ISSUE TITLE
Expand + migrate after OW: network upgrade guidelines 

### ISSUE THREAD

**Issue by lindanlee** [zcash/zcash#3290]
Move information in [the network upgrade guide](https://z.cash/support/network-upgrade-guide.html) to read the docs after the upgrade. 

Will keep on updating the page and expanding on it until after overwinter is done.

**Comment by mdr0id** [comment]
https://gitlab.com/mdr0id/test-rtd-docs/merge_requests/10 closes this.

**Comment by ioptio** [comment]
Done http://zcash.readthedocs.io/en/latest/rtd_pages/rtd_docs/nu_dev_guide.html
