### ISSUE TITLE
Expand + migrate asap: UX developer guidelines

### ISSUE THREAD

**Issue by lindanlee** [zcash/zcash#3292]
Move the content on the [ux developer guidelines](https://z.cash/support/ux-checklist.html) into read the docs as soon as possible. 

This isn't dependent on overwinter, and does not fit the scope for pages to keep in the upcoming website redesign.

**Comment by lindanlee** [comment]
Currently, getting the public-ready version of read the docs, with just the user guide + github stuff, is priority.

**Comment by lindanlee** [comment]
Overwinter happened! Let's move these two pages over into read the docs. 

https://z.cash/support/network-upgrade-guide.html
https://z.cash/support/ux-checklist.html

**Comment by ioptio** [comment]
Done. http://zcash.readthedocs.io/en/latest/rtd_pages/rtd_docs/ux_wallet_checklist.html
