### ISSUE TITLE
Table reflecting which features third-party services support

### ISSUE THREAD

**Issue by lindanlee** [zcash/zcash#3293]

**Comment by ioptio** [comment]
Initial feature list: 

- shielded addresses
- memo field
- user-control of private keys
- custodial control of private keys
- t-addr multi sig
- HD wallets (when ready)

**Comment by lindanlee** [comment]
A table that looks like this: 

![image](https://user-images.githubusercontent.com/6580269/42597810-ab32f624-851f-11e8-9a06-811e4129d041.png)

**Comment by ioptio** [comment]
Wallets to highlight on first iteration:
- zcashd
- WinZEC
- Trezor
- Jaxx
- Exodus

**Comment by ioptio** [comment]
Features to highlight on first iteration (in order):
- type (command-line vs desktop UX vs web vs mobile vs hardware)
- shielded address
- memo field
- t-addr multisig
- private key control (user vs custodial vs both)

**Comment by lindanlee** [comment]
We did it! 

https://docs.google.com/spreadsheets/d/1WOyTr_deO7djGtVuQCDNWGJi4HjP8W8okDM71BMa4ZI/edit#gid=0
