### ISSUE TITLE
Add: Research section in read the docs

### ISSUE THREAD

**Issue by lindanlee** [zcash/zcash#3295]
Organize the science-y stuff in scattered blog posts and in the [technology section of z.cash](https://copernicus.staging.z.cash/technology/index.html). 

We want to avoid having copies of the same information, so a good starting point would be to have a table of contents of all the information out there, with the appropriate links to the relevant pages or blog posts.

**Comment by ioptio** [comment]
If we want to do this, let's make a ticket in the gitlab repo: https://gitlab.com/mdr0id/test-rtd-docs/issues
