### ISSUE TITLE
Add: Community section in read the docs

### ISSUE THREAD

**Issue by lindanlee** [zcash/zcash#3296]
We're not quite sure on what this page would look like quite yet, but the idea is that this page will bootstrap people who want to represent Zcash at certain events, but aren't formally a part of Zcash Co. 

Some things that could be on this page: 
* guidelines on phrases to say, others to avoid, preferences on messaging, and list of zcash mission and vision 
* diagrams, pictures, gifs, and other helpful things to reference in a Zcash presentation 
* some links to educational content that would get them up to speed on Zcash and its technology

**Comment by ioptio** [comment]
If we want to do this, let's make a ticket in the gitlab repo: https://gitlab.com/mdr0id/test-rtd-docs/issues
