### ISSUE TITLE
RPC call getnetworksolps returns an error when passing in blocks or height

### ISSUE THREAD

**Issue by garethtdavies** [zcash/zcash#3298]
### Describe the issue
When specifying the number of blocks or a height to use an error of `JSON value is not an integer as expected` is returned even when an integer is passed. I think I am using it correctly?!

### Can you reliably reproduce the issue?
1.  Try `zcash-cli getnetworksolps 120 -1` which are the default values albeit it I have tried on a variety of integer values.

### Expected behaviour
Returns network solps

### Actual behaviour + errors
```
error code: -1
error message:
JSON value is not an integer as expected
```

### The version of Zcash you were using:
Zcash Daemon version v1.1.0

**Comment by garethtdavies** [comment]
Notably `zcash-cli getnetworkhashps 120 -1` works albeit that command is deprecated in favour of `getnetworksolps`

**Comment by Eirik0** [comment]
This is a bug. The parameters were not being flagged as needing to be converted. I have submitted https://github.com/zcash/zcash/pull/3318 as a fix.

**Comment by ioptio** [comment]
@garethtdavies this is fixed in master, you can use the deprecated `getnetworkhashps` since it does the same thing or test the current master branch. The fix will will be in the next release.
