### ISSUE TITLE
zcash-cli return error when using getrawtransaction， testnet， 1.1.0

### ISSUE THREAD

**Issue by zhangdaoling** [zcash/zcash#3306]
### Describe the issue
zcash-cli getrawtransaction return error，many tx return this error.
error code: -5
error message:
No information available about transaction

#### If so, please list the steps to reproduce below:
1. version 1.1.0， testnet
2. zcash-cli  getrawtransaction 637022bab237276870bb3296f358a9f1d67d128de2f0b217d8f3efe7ca013532
3. return error：
error code: -5
error message:
No information available about transaction

**Comment by garethtdavies** [comment]
Just ruling out the obvious do you have `txindex=1` in your conf file?

**Comment by ioptio** [comment]
The transaction is mined as seen on the block explorer: https://explorer.testnet.z.cash/tx/637022bab237276870bb3296f358a9f1d67d128de2f0b217d8f3efe7ca013532

**Comment by ioptio** [comment]
We're closing this due to lack of response but feel free to reopen with more feedback.
