### ISSUE TITLE
Zcashd randomly not confirming transactions

### ISSUE THREAD

**Issue by ppratscher** [zcash/zcash#3312]
### Describe the issue
We are sending several hundreds of Z -> T transactions per day. On a regular basis a single transaction is not getting confirmed by the network. The transaction have a few shielded inputs and several hundred transparent outputs.

When such a transaction is added to the wallet we see the following in the log file (tx hash: dbf6601ef3abbb170013de32e616a53e6bdcba6fdc1d88f426803510be058434):
```
AddToWallet dbf6601ef3abbb170013de32e616a53e6bdcba6fdc1d88f426803510be058434  new
opid-b70475c3-d4cc-4a02-a5a7-09f30623ce04: z_sendmany finished (status=success, txid=dbf6601ef3abbb170013de32e616a53e6bdcba6fdc1d88f426803510be058434)
UpdateTip: new best=0000000009594aa311130875ace81bfe47535621078e8b16062e452478ced6e0  height=332848  log2_work=53.412346  tx=3205624  date=2018-05-31 12:01:48 progress=0.999999  cache=177.4MiB(4550tx)
AddToWallet dbf6601ef3abbb170013de32e616a53e6bdcba6fdc1d88f426803510be058434
```
After that we don't get any other log message in the output for this transaction.

Furthermore we get the following:
```
zcash-cli getrawtransaction dbf6601ef3abbb170013de32e616a53e6bdcba6fdc1d88f426803510be058434
error code: -5
error message:
No information available about transaction
```

### Can you reliably reproduce the issue?
Unfortunately we were unable to reliably reproduce the issue up to now.

### The version of Zcash you were using:
Zcash Daemon version v1.1.0

### Machine specs:
- OS name + version: Ubuntu 16.04

**Comment by leto** [comment]
@ppratscher to clarify, are you running with `txindex=1` ? Without that, the above command will not work reliably.

```
$ zcash-cli help getrawtransaction

NOTE: By default this function only works sometimes. This is when the tx is in the mempool
or there is an unspent output in the utxo for this transaction. To make it always work,
you need to maintain a transaction index, using the -txindex command line option.```

**Comment by ppratscher** [comment]
Ah rights, sorry I mixed up the call with the gettransaction call.

gettransaction works and returns -1 confirmations and a tx hash under walletconflict. I assume this means that one of the tx inputs was spent by a previous transaction.

My question now is how we can prevent that issue?

**Comment by ioptio** [comment]
Try looking at symptoms listed in this FAQ: https://z.cash/support/faq.html#transaction-not-mined

Do you have `debug=1` enabled for more verbose debug output?

**Comment by ppratscher** [comment]
I can rule out all the issues mentioned in the FAQ. As stated above the transaction gets invalidated because its inputs were already spent by a different transaction.

I assume the issue is related to the fact that z_sendmany does not lock the used notes when sending from a z address.

**Comment by bitcartel** [comment]
z_sendmany uses a queue to process z_sendmany requests so locking zaddress notes (whilst desirable) is not necessary.

Are you running a single instance of zcashd?

**Comment by ppratscher** [comment]
Yes all transactions are generated on a single instance of zcashd.

**Comment by ioptio** [comment]
We're curious if you're doing anything simultaneously to having the `z_sendmany` queues in background?

**Comment by ioptio** [comment]
Transaction expiry is now active and all mempool transactions were cleared at the Overwinter upgrade. We're still curious about your situation so feel free to reopen and comment on the issue.
