### ISSUE TITLE
annotation_prefix == "" at gadget.tcc

### ISSUE THREAD

**Issue by wo01** [zcash/zcash#3315]
I have built zcashd with DEBUG=1.
Zcashd always crashes when using z_sendmany from/to zaddr .

zcashd: ./snark/libsnark/gadgetlib1/gadget.tcc:18: libsnark::gadget<FieldT>::gadget(libsnark::protoboard<FieldT>&, const string&) [with FieldT = libsnark::Fp_model<4l, ((const libsnark::bigint<4l>&)(& libsnark::alt_bn128_modulus_r))>; std::__cxx11::string = std::__cxx11::basic_string<char>]: Assertion `annotation_prefix != ""' failed.

https://github.com/zcash/zcash/blob/master/src/snark/libsnark/gadgetlib1/gadget.tcc#L18
This assert statement may be no need.

https://github.com/zcash/zcash/blob/master/src/snark/libsnark/gadgetlib1/gadget.hpp#L21
https://github.com/zcash/zcash/blob/master/src/zcash/circuit/gadget.tcc#L44

Above code always set annotation_prefix="".
Therefore, the code crashes.

**Comment by ebfull** [comment]
Yeah, the annotations are not always provided in our gadgets. It'd be interesting to see how many actually have to be added to satisfy this assertion, but I think the assertion can just be removed.

**Comment by daira** [comment]
This is no longer relevant because after Sapling activation, we do not use the JoinSplit circuit written to the libsnark API. (We use the verification key to verify pre-Sapling blocks, but this does not actually use the circuit code.)
