### ISSUE TITLE
zcashd doesn't not detect network parameters in ~/.zcash-params

### ISSUE THREAD

**Issue by s-tikhomirov** [zcash/zcash#3316]
### Describe the issue
zcashd doesn't not detect network parameters in ~/.zcash-params.

#### If so, please list the steps to reproduce below:
1. Follow the [installation instructions](https://z.cash/download.html)
2. Launch `zcashd`

### Expected behaviour
zcashd runs, block sync begins.

### Actual behaviour + errors
```
- Error: Cannot find the Zcash network parameters in the following
  directory:
"/home/sergei/.zcash-params"
Please run 'zcash-fetch-params' or
  './zcutil/fetch-params.sh' and then restart.
```
The parameter files are actually in that directory.

### The version of Zcash you were using:
Zcash Daemon version v1.1.1

### Machine specs:
- OS name + version: Ubuntu 16.04 LTS
- CPU: Intel(R) Core(TM) i5-3337U CPU @ 1.80GHz
- RAM: 4 GB
- Disk size: 500 GB
- Disk Type (HD/SDD): HD
- Linux kernel version (uname -a): 4.13.0-43-generic #48~16.04.1-Ubuntu SMP Thu May 17 12:56:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Compiler version (gcc -version):
[debug.log](https://github.com/zcash/zcash/files/2065127/debug.log)

**Comment by garethtdavies** [comment]
Are you running on testnet or mainnet?

**Comment by s-tikhomirov** [comment]
Tried to run on mainnet, but turns out my config file was incorrect (included `testnet=1`, but `addnode=mainnet.z.cash`). Now it works for  mainnet, but still shows the same error for testnet (`testnet=1` and `addnode=mainnet.z.cash` in zcash.conf; launching with `zcashd -testnet`).

**Comment by garethtdavies** [comment]
This is actually correct for testnet. There is much more detail [here](https://blog.z.cash/new-release-1-1-1/) but the critical bit is:

> Sapling will activate on testnet with dummy Sapling parameters at height 252500

So 1.1.1 includes these dummy parameters which you'll need to download. So you'll need to run `./zcutil/fetch-params.sh --testnet` if built from source or `zcash-fetch-params --testnet` for (for binary / Debian).

**Comment by mdr0id** [comment]
@s-tikhomirov Did @garethtdavies suggestion resolve your issue?

**Comment by s-tikhomirov** [comment]
Yes, thanks!

**Comment by xianaofei** [comment]
How did you solve it? I also encountered this problem. How to configure it. Thank you

**Comment by garethtdavies** [comment]
@xianaofei see my post above. Assuming are running on testnet you'll need to run `./zcutil/fetch-params.sh --testnet` if built from source or `zcash-fetch-params --testnet` for (for binary / Debian).

**Comment by xianaofei** [comment]
@garethtdavies  hi,  I'm a downloaded zcash-1.1.1-linux64.tar.gz. 

This is the wrong message
root@java-wallet-2-91:~/.zcash# Zcash server starting
Error: Cannot find the Zcash network parameters in the following directory:
"/root/.zcash-params"
Please run 'zcash-fetch-params' or './zcutil/fetch-params.sh' and then restart.

How should I configure or download what files I want to download?

**Comment by xianaofei** [comment]
Before running zcashd for the first time, run zcash-fetch-params first and generate /root/.zcash-params.
CD /usr/local/zcash/bin executes./zcash-fetch-params

zcash.conf
regtest=1
daemon=1
gen=1
showmetrics=0
rpcuser=XXX
rpcpassword=XXX
rpcallowip=0.0.0.0/0
datadir=/data/zcash

zcashd &
The test network starts to be normal
Thank you for giving a beginner's help
