### ISSUE TITLE
v3 transaction feature: expiry height

### ISSUE THREAD

**Issue by algerpan** [zcash/zcash#3317]
Hi there,

currently in v3, the
expiry height = current height + expiry_height_delta
and the expiry height is required when sending a transaction. 
What if I put my node under offline environment, how can it know current height and calculate hash correctly?

**Comment by daira** [comment]
You have two options:
1. Don't set an expiry height (this is encoded as zero in the ``nExpiryHeight`` field).
2. Get the current block height by some out-of-band method; this depends on whether you can communicate at all with the outside world when offline.

**Comment by ioptio** [comment]
Let us know if this answers your question. Please close the ticket if so. Thank you!

**Comment by woodywang** [comment]
Hi, @algerpan  is my workmate. We have to put a zcash node into a offline environment to sign transaction because of some security reasons. I prefer option 2 @daira . However I don't find any API that can accept 'expiryHeight'. I hope I can pass expiryHeight directly (not height_delta) when I call 'createrawtransaction'. But the API's document doesn't say how to do it.

```
Arguments:
1. "transactions"        (string, required) A json array of json objects
     [
       {
         "txid":"id",  (string, required) The transaction id
         "vout":n        (numeric, required) The output number
         "sequence":n    (numeric, optional) The sequence number
       }
       ,...
     ]
2. "addresses"           (string, required) a json object with addresses as keys and amounts as values
    {
      "address": x.xxx   (numeric, required) The key is the Zcash address, the value is the ZEC amount
      ,...
    }
3. locktime                (numeric, optional, default=0) Raw locktime. Non-0 value also locktime-activates inputs
```

**Comment by daira** [comment]
I agree this should be possible, we're looking at it now.

**Comment by arcalinea** [comment]
You can set the `expiryheight` on a raw transaction from an offline node using the `zcash-tx` tool, i.e. `./src/zcash-tx <raw-tx-hex> expiry=<expiry-height>`

We currently don't support passing expiryheight to `createrawtransaction` in the RPC interface, however. Will open an issue for adding this, agree that this should be supported.

**Comment by arcalinea** [comment]
Let us know if using the `zcash-tx` tool to set the expiry height works for you, or if you'd strongly prefer being able to modify it per-transaction in the `createrawtransaction` RPC call.

**Comment by ioptio** [comment]
@woodywang let us know if you got it to work. We'll work on documentation in the meantime.

**Comment by algerpan** [comment]
well, thank you all guys. we will waiting for docs
