### ISSUE TITLE
Discard new spending key if it results in ivk == 0

### ISSUE THREAD

**Issue by arcalinea** [zcash/zcash#3319]
Per section 4.2.2 of the Sapling spec, we need to discard spending keys that result in ivk == 0, and loop around.

Will not be necessary if ZIP 32 gets in wallet, otherwise needs to be added before 2.0.0
https://github.com/zcash/zcash/pull/3269

**Comment by bitcartel** [comment]
We don't know when ZIP32 will get into the wallet so let's prioritize this.

**Comment by arcalinea** [comment]
Closed by #3390
