### ISSUE TITLE
zcash testnet mining ERROR (ProcessNewBlock: AcceptBlock FAILED)

### ISSUE THREAD

**Issue by c2h2** [zcash/zcash#3323]
### zcash testnet mining ERROR
Linux 16.04 running z-nomp and testnet zcash deamon.

from .zcash/testnet3/debug.log:
```
...
2018-06-06 18:00:46 ERROR: ContextualCheckTransaction: overwinter is active
2018-06-06 18:00:46 ERROR: ProcessNewBlock: AcceptBlock FAILED
2018-06-06 18:00:46 ERROR: ReadBlockFromDisk: OpenBlockFile failed for CBlockDiskPos(nFile=-1, nPos=0)
... and repeat
```

mining program tells the miner connects via stratum+tcp ok, and getting job ok

this is frontend: http://45.76.158.225:8080/workers/tmBURopfSysgy2aSXMLQ15Ck47wipfVq5SH

Everytime reproduce

### Expected behaviour
I should be able to mine some blocks (given network only ~20Sols/s, One GPU is output 300+Sols/s)

### Actual behaviour + errors
Z-nomp reports: 

```
2018-06-06 18:06:48 [Pool]      [zcash_testnet] (Thread 1) We thought a block was found but it was rejected by the daemon, share data: {"job":"ccdd","ip":"::ffff:58.32.23.248","port":3032,"worker":"tmBURopfSysgy2aSXMLQ15Ck47wipfVq5SH.xxx","height":247961,"difficulty":1,"shareDiff":"1.13926462","blockDiff":0.301610833,"blockDiffActual":0.301610833,"blockHash":"000705a69d2839a18fa3e09b4786cb8641fd66d1e135eaf504216ecceb5baf17","error":{"unknown":"check coin daemon logs"}}
2018-06-06 18:06:53 [Pool]      [zcash_testnet] (Thread 1) Submitted Block using submitblock successfully to daemon instance(s)

```
### The version of Zcash you were using:
Version = Zcash Daemon version v1.1.1-b4874e9

### Machine specs:
- OS name + version: Linux 16.04
- CPU: vultr vps 2cores
- RAM: 8GB
- Disk size: 60GB
- Disk Type (HD/SDD): SSD
- Linux kernel version (uname -a): Linux vultr.guest 4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Compiler version (gcc -version): gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)

**Comment by c2h2** [comment]
```
root@vultr:~# ~/zcash/src/zcash-cli listunspent
[
]
root@vultr:~# ~/zcash/src/zcash-cli getinfo
{
  "version": 1010050,
  "protocolversion": 170005,
  "walletversion": 60000,
  "balance": 0.00000000,
  "blocks": 247965,
  "timeoffset": 0,
  "connections": 8,
  "proxy": "",
  "difficulty": 76.26976433892325,
  "testnet": true,
  "keypoololdest": 1528304699,
  "keypoolsize": 101,
  "paytxfee": 0.00000000,
  "relayfee": 0.00000100,
  "errors": ""
}
```

**Comment by mineZcash** [comment]
You can enable test net mining in your Zcash config file by adding `gen=1`,  z-nomp is not necessary.  

Z-nomp is not Zcash supported software.

**Comment by c2h2** [comment]
I konw gen=1, it says on the zcashd, but i need to test mining pool.

**Comment by mineZcash** [comment]
You may try asking on the z-nomp GitHub: 
https://github.com/z-classic/z-nomp

**Comment by c2h2** [comment]
Thanks, But I still suspect this zcashd has something to do with it? maybe different founder_accounts? or overwinter releases?

**Comment by ioptio** [comment]
We suspect z-nomp hasn't updated their backend to support Overwinter. Might be worth asking z-nomp devs.

**Comment by biozahard** [comment]
Any solution? Have the same problem. What changed with overwinter?

**Comment by c2h2** [comment]
@biozahard have to look into it ourselves

**Comment by Tomas-M** [comment]
Also having this issue.
Updated to latest z-nomp, no difference.
Any suggestions?

**Comment by mineZcash** [comment]
From what I have seen, z-nomp is no longer compatible with Zcash since the Overwinter Upgrade. Someone will need to update z-nomp to be compatible.

Z-nomp was developed by the Zclassic team, you may try asking there.

**Comment by Tomas-M** [comment]
Here is how to fix this problem:
https://github.com/karel-3d/bitcoinjs-lib/pull/3

**Comment by c2h2** [comment]
with my custom patch and v1.1.0 zcash testnet. it‘s working！and v4 transaction is also implemented by me. Thanks to @hellcatz!, will donate some coins to him.

 https://github.com/c2h2learnstocode/bitcoinjs-lib/commit/55f5ec4876a9527c409f3daeced28f5b9315db14
