### ISSUE TITLE
Zcashd v1.1.2 and below into safe mode a few days before Sapling activates

### ISSUE THREAD

**Issue by mdr0id** [zcash/zcash#3329]
Per discussion in Zashd sprint planning meeting on 6/7/2018

**Comment by bitcartel** [comment]
v1.1.2 nodes [shut down on Oct 23rd](https://twitter.com/IanAMunoz/status/1054719917763715072), where the v1.1.2 release removed the option to disable EOS halting.
> This release removes the -disabledeprecation option so that zcashd software versions made by the Zcash Company will always shut down in accordance with the defined EOS policy (currently 16 weeks after release).https://z.cash/blog/new-release-1-1-2/

**Comment by daira** [comment]
@radix42 the option is `-alerts=0`.
