### ISSUE TITLE
Pass expiryheight as param to createrawtransaction

### ISSUE THREAD

**Issue by arcalinea** [zcash/zcash#3333]
Can currently modify expiryheight using `zcash-tx` tool, but not directly through `createrawtransaction`. 

Requested in #3317 for offline tx creation

**Comment by oxarbitrage** [comment]
This issue seems to be resolved by https://github.com/zcash/zcash/pull/3336

Please close.

**Comment by rex4539** [comment]
@steven-ecc this can be closed.
