### ISSUE TITLE
Wallet RPC commands not working for pruned node

### ISSUE THREAD

**Issue by s-tikhomirov** [zcash/zcash#3339]
### Describe the issue
Can not create a transaction from a pruned node.

#### If so, please list the steps to reproduce below:
1. `zcashd --prune=600`
2. wait till synced
3. `zcash-cli sendtoaddress <addr> <amount>`

### Expected behaviour
Transaction sent.

### Actual behaviour + errors
```
error code: -32601
error message:
Method not found (disabled)
```

`zcash-cli help` shows only `zcsamplejoinsplit` in the `== Wallet ==` section.

### The version of Zcash you were using:
1.1.1

### Machine specs:
- OS name + version: Ubuntu 16.04
- CPU: Intel core i5
- RAM: 4 GB
- Disk size:
- Disk Type (HD/SDD):
- Linux kernel version (uname -a): 4.13.0-45-generic
- Compiler version (gcc -version):

**Comment by jasondavies** [comment]
I don't think `prune` is compatible with wallet support:

```
  -prune=<n>
       Reduce storage requirements by pruning (deleting) old blocks. This mode
       disables wallet support and is incompatible with -txindex. Warning:
       Reverting this setting requires re-downloading the entire blockchain.
       (default: 0 = disable pruning blocks, >550 = target size in MiB to use
       for block files)
```

Zcash was forked from an older version of Bitcoin; I believe Bitcoin 0.12 allows you to use pruning along with a wallet.

**Comment by s-tikhomirov** [comment]
Yes, that's what got me confused: I thought that if I can issue Bitcoin txs from a pruned node, I can also do so in Zcash. Thanks for the information.
