### ISSUE TITLE
overwinter testnet for mining?

### ISSUE THREAD

**Issue by miningpoolhub** [zcash/zcash#3348]
I've found that testnet.z.cash is already running on Sapling activated mode.

Is there any testnet that is still on Overwinter?
I'm trying to test mining for pool.

Any idea?

**Comment by garethtdavies** [comment]
Yes, there is a testnet for Overwinter and the explorer here is on that chain https://explorer.testnet.z.cash.

You'll need to be running v1.1.0 as opposed to the latest release of v1.1.1. As per the release post here: https://blog.z.cash/new-release-1-1-1/

> Users who want to continue testing Overwinter should continue to run version 1.1.0 on testnet, and then upgrade to 2.0.0 (which will be released after Overwinter activates).

**Comment by miningpoolhub** [comment]
Thanks!
