### ISSUE TITLE
zcashd installation instructions do not work

### ISSUE THREAD

**Issue by JohnSmall** [zcash/zcash#3357]
### Describe the issue
Please provide a general summary of the issue you're experiencing
I can't install zcashd on Ubuntu 14.04

### Can you reliably reproduce the issue?
Yes
#### If so, please list the steps to reproduce below:
1. Follow the exact steps (I copied and pasted) given in this repo

### Expected behaviour
zcashd should be installed

### Actual behaviour + errors
Err https://apt.z.cash jessie/main amd64 Packages                              
  gnutls_handshake() failed: Handshake failed
Ign https://apt.z.cash jessie/main Translation-en_GB                           
Ign https://apt.z.cash jessie/main Translation-en                              
W: Failed to fetch https://apt.z.cash/dists/jessie/main/binary-amd64/Packages  gnutls_handshake() failed: Handshake failed

### The version of Zcash you were using:
zcashd not installed

### Machine specs:
- Ubuntu 14.04
- CPU: AMD64
- RAM: 8GB
- Disk size: > 2 TB
- Disk Type (HD/SDD): mixed
- Linux kernel version (uname -a):
 3.13.0-108-generic #155-Ubuntu SMP Wed Jan 11 16:58:52 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Compiler version (gcc --version):
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4

**Comment by str4d** [comment]
I believe this error is due to `apt-transport-https` not being installed. See the [Debian binary packages guide](https://github.com/zcash/zcash/wiki/Debian-binary-packages).

**Comment by c2h2** [comment]
is your server able to visit any other https sites? is server time correct? this is https connection problem.

**Comment by mdr0id** [comment]
@JohnSmall This might be an uphill battle as 14.04.4 reached EOL Aug 2016. Several issues have been documented around 14.04.+ versions. 

Is it possible to upgrade to a newer version such as 14.04.5 or 16.04+?

**Comment by mdr0id** [comment]
Closed due to inactivity. Please feel free to re-open.
