### ISSUE TITLE
How often does zcash-params change? Should I often update it?

### ISSUE THREAD

**Issue by DinoStray** [zcash/zcash#3358]
Before run zcash node, we should run zcutil/fetch-params.sh first.
How often does zcash-params change? 
Or it will be never changed?

After node running, should I run zcutil/fetch-params.sh again frequently?

**Comment by gojomo** [comment]
Only a major software upgrade (as with the planned later-this-year 'Sapling' evolution) will require a update or expansion of those parameters - so you never need to refresh these spontaneously on your own initiative. As long as your node is running OK, don't touch them!
