### ISSUE TITLE
Prioritisation of Funding Towards Critical Infrastructure

### ISSUE THREAD

**Issue by Enegnei** [zcash/zcash#3362]
### Describe the issue

On June 26th, 2018, the Zcash Foundation hosted **Zcon0**, "[a three day conference for people who are working on building the privacy infrastructure for the public good](https://z.cash.foundation/zcon/)" at USD$900 per ticket. As part of his [keynote presentation](https://z.cash.foundation/zcon/schedule/), the [**Zcash Company**'s founder and CEO](https://z.cash/team.html) Zooko Wilcox shared a slide with a [basic breakdown of company finances and statistics about Zcash issuance](https://twitter.com/bcrypt/status/1011602573873336320), including the allocation of the so-called "Founders' Reward." Of relevance from the pie chart:

- **Zcash Foundation** receives 6,563 ZEC per month
- **Zcash Company** receives 6,125 ZEC per month
- 34 individuals (out of group of 44 individuals who are "employees, advisors, and founders") together receive 3.4% / amount of ZEC unspecified
- CEO Zooko Wilcox receives 2,033 ZEC per month

At the current Zcash price respectively, this would roughly equate to:

- USD$1.06 million per month
- USD$1 million per month
- USD$1.2 million per month
- USD$330,000 per month

Days before the conference, a [controversy surfaced on social media](https://www.coindesk.com/zcash-pays-off-angry-developer-avoid-blockchain-split/) regarding whether the maintainer(s) of Zcash's cross-platform GUI wallets were being fairly compensated for their work, with [the threat of a possible chain split](https://twitter.com/radix42/status/1009144438348832768). The situation was at least temporarily resolved via [an anonymous donation](https://twitter.com/radix42/status/1009501290014134284). However, despite being someone who was responsible for "building the privacy infrastructure," they [reported receiving no assistance in attending Zcon0](https://twitter.com/radix42/status/1011415909804765184).

### Suggested behaviour

The Zcash community should applaud this endeavor towards corporate financial transparency by those who have established a company and foundation tasked with providing development funding and direction for innovation in the Zcash ecosystem, but also use it as an opportunity to re-evaluate whether this [distribution](https://blog.z.cash/continued-funding-and-transparency/) [plan](https://z.cash.foundation/blog/grant-awards/) still satisfies (or has ever satisfied) the "public good" needs and long-term sustainability of the ecosystem, specifically regarding prioritising critical work like the creation and maintenance of wallets and other basic infrastructure.

[Suggested labels: community, Founders' Reward, ZIP idea]

### Related

- Copying Monero's crowdfund system: https://twitter.com/zooko/status/1009554213603454977

**Comment by mineZcash** [comment]
The Foundation has a Grant Program for the very purpose of funding things like Radix42s Windows GUI development and last year Radix42s [received funds](https://z.cash.foundation//blog/grant-awards/) for work. 

The Q2 2018 deadline was [widely published](https://z.cash.foundation//blog/q2-grant-program/)  but for personal reasons Radix42s was unable to file but many other proposers [did not have an issue](https://github.com/ZcashFoundation/GrantProposals-2018Q2) meeting the deadline.  Had Radix42s been able to submit a proposal for this round of Grants I'm confident that he would have received funding for his work.

**Comment by Enegnei** [comment]
I am aware of the Grant Program and have it linked in the last paragraph. I have not added specific suggestions for improvement at this point, but for that matter I think they have more than enough money to accommodate developers they have approved before, who miss deadlines for personal reasons.

**Comment by tromer** [comment]
@Enegnei, you're right that the competitive grants program is indeed not the only way for the Foundation to support developers, and there was discussion of @radix42 applying for ongoing funding outside the program. So far, they have chosen not to apply for such funding.

**Comment by ioptio** [comment]
@Enegnei, let's move this discussion to the forum, which is a more appropriate channel for discussing funding and direction for the Zcash ecosystem.
