### ISSUE TITLE
16: mandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element)

### ISSUE THREAD

**Issue by samosudov** [zcash/zcash#3372]
Hello!
I'm from Guarda wallet dev team (@guardaco). We change creating and signing for a transaction to support overwinter in android light wallet.

### Describe the issue
We try to change our SPV library (it worked fine before the fork).
I've created the pull request with all changes.
https://github.com/guardaco/zcash-SPV/pull/6
The PR contains only overwinter changes (ZIP200-203 and ZIP143) 
and Blake2b library (https://github.com/alphazero/Blake2b).

### Expected behaviour
The transaction is successfully broadcasted. Its TXID is obtained.

### Actual behaviour + errors
`sendrawtransaction` fails with `mandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element)` error message.

Saw #3280, #3327. 
Our node is online.
Amount for inputs was setted.
Branch id is `0x5ba81b19`.

### The version of Zcash you were using:
Node version is 1.1.1. Actual version is 1.1.2. 
But I don't think it matters.

**Comment by braddmiller** [comment]
Hi @samosudov, there is a change in the `signrawtransaction` command as of Overwinter. 

When you sign the transaction, it is now mandatory to set the `amount` if you set the `prevtxs` parameter. This is a change from the previous version of Zcash. This field should be the full amount of the UTXO. Try that and see if it solves your issue.

You can view the RPC call here https://zcash-rpc.github.io/signrawtransaction.html

**Comment by samosudov** [comment]
Hi @braddmiller,

We don't use sign, only send.
Build and sign transactions on the device and send transaction's hex with `sendrawtransaction` method. By this flow all our wallets are made.

eg, builded hex for send:
030000807082c403017926ac5fb8f243c875485fc459c3e93399319f816a2a2725036bb78872f56404010000006a47304402204978981a9763f20209c669fa885acdb237329c759d0796d281c4a003d619f1ad022013b4cb04d6325d2231b3d678dad3c51fa3ea6e44b4d6090ba6aec5e24fcd6bb50121024266da2abde93e72f3e4bf135718ae05cd11a205934ddd696853b2b16b93daffffffffff02ba010000000000001976a914d5030f231e7bb1d60b5702b5598d6606b5151c8988acaa160000000000001976a91456834de9cc75a4242708b15bb49926c625d8d96188ac00000000ff64cd1d00
__
I tried to send this hex to `signrawtransaction`, but in the response, among other things, there was the same error

**Comment by ricmoo** [comment]
Is there another PR where the `prevtxs` is added s mandatory? Is it mandatory in the binary format?

We found [this PR](https://github.com/zcash/zcash/pull/2925/files) which adds the Overwintered support, but don't see the prevout value included in the binary transaction.

Is there an updated protocol specification? I've only been able to find [this one](https://github.com/zcash/zcash/wiki/specification), which has not been updated for Overwintered.

**Comment by braddmiller** [comment]
@samosudov The transaction has to be created and signed somewhere, if that's happening on the device as you say, then the amount will have to be included in `signrawtransaction` at that point. I'm assuming that makes sense for your setup, I'm not deeply familiar.

@ricmoo `prevtxs` is not mandatory, but if you do specify it `amount` must also be specified.

**Comment by str4d** [comment]
At the specification level, what you need is [ZIP 143](https://github.com/zcash/zips/blob/master/zip-0143.rst). Note that when creating a signature hash for a particular input, you need to specify the value being spent by that input (like for SegWit inputs in Bitcoin). That is what the `amount` field of `prevtxs` in the `signrawtransaction` API is being used for.

**Comment by str4d** [comment]
For exhaustive specification of the Overwinter upgrade, see our [Network Upgrade Guide](https://z.cash/support/network-upgrade-guide.html) and the ZIPs that it links to (of which ZIP 143 is one).

**Comment by Herry143** [comment]
hi @str4d ,I have update the zcashd to 1.1.2,and I try to sendrawtransaction,it returns "tx-overwinter-active",
so what i should do?thank you

**Comment by xianaofei** [comment]
@samosudov 
hashPrevouts：
BLAKE2b-256（'ZcashPrevoutHash'，b''）
= d53a633bbecf82fe9e9484d8a0e727c73bb9e68c96e72dec30144f6a84afa136
I want to know that this algorithm implements BLAKE2b-256
Thank you

**Comment by braddmiller** [comment]
I am closing this ticket due to inactivity. If issues still persist please reopen the ticket or create a new one.

**Comment by samosudov** [comment]
There is an updated library supporting overwinter
https://github.com/guardaco/zcash-SPV
