### ISSUE TITLE
Bad zcash-1.1.2-linux64.tar.gz.asc signature!

### ISSUE THREAD

**Issue by shshshsh** [zcash/zcash#3377]
[zcash-1.1.2-linux64.tar.gz.asc](https://z.cash/downloads/zcash-1.1.2-linux64.tar.gz.asc) (sha256sum 2c75b11932010f54ec15da6376047be06e3a35a821cbb135fb70d4388de68dae)
 is a `BAD signature` for [zcash-1.1.2-linux64.tar.gz](https://z.cash/downloads/zcash-1.1.2-linux64.tar.gz) (sha256sum 78281e0767528c73c7919196efcfdbb3457965ca1867a7c4da102051a334d43f). What's up?

(I can verify the 1.1.1 sig, both are using the same key -> I don't think the issue is on my end)

**Comment by mdr0id** [comment]
@shshshsh This a Github UX related issue, not an internal  process release thing. Please let us know if you have any other concerns or questions

**Comment by shshshsh** [comment]
What? I'm talking about this:

```
$ gpg2 --verify zcash-1.1.2-linux64.tar.gz.asc
gpg: assuming signed data in 'zcash-1.1.2-linux64.tar.gz'
gpg: Signature made Tue Jul  3 05:01:40 2018 UTC
gpg:                using RSA key 63C4A2169C1B2FA2
gpg: BAD signature from "Zcash Master Signing Key" [ultimate]
```

Similar to #3037 for v1.0.15. It has nothing to do with GitHub.

**Comment by daira** [comment]
Indeed this doesn't look like a Github issue to me. The problem *might* be (I'm not entirely sure) that Github is changing the tar.gz file after we upload it, but in that case we shouldn't sign it.

**Comment by shshshsh** [comment]
> The problem _might_ be (I'm not entirely sure) that Github is changing the tar.gz file after we upload it

Did the upload process change after 1.1.1? Cause that version can be verified:

```
$ gpg2 --verify zcash-1.1.1-linux64.tar.gz.asc
gpg: assuming signed data in 'zcash-1.1.1-linux64.tar.gz'
gpg: Signature made Wed May 30 03:18:35 2018 UTC
gpg:                using RSA key 63C4A2169C1B2FA2
gpg: Good signature from "Zcash Master Signing Key" [ultimate]
```

**Comment by ianamunoz** [comment]
I can verify your assertion. It looks like the signed binary may have been uploaded with a bad signature. You could pull the .deb in the meantime for 1.1.2 which has the correct signature till I can correct the signature error.

**Comment by mdr0id** [comment]
@shshshsh I thought you were describing the ``Verified`` and ``Unverified`` widget that accompanies tagged releases.

**Comment by ianamunoz** [comment]
@shshshsh I have fixed the signature. I think it was just a fat finger but I have verified the correct signature now.
