### ISSUE TITLE
Implement ZIP 32 for Sprout addresses

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#3381]
This can only be done for brand-new wallets. I expect it will be integrated the same way that upstream implemented BIP 32 (which we should pull in at the same time).

**Comment by mms710** [comment]
We should revisit this once we have a more defined plan for retiring Sprout addresses.

**Comment by daira** [comment]
As far as I remember, the rationale for including this in the ZIP is we want it to be possible for a wallet to be backed up once-and-for-all, without needing to do so every time new addresses are generated. But I think it's more likely that a fully ZIP32 wallet would just refuse to generate new Sprout addresses, instead.

**Comment by jackgavigan** [comment]
> As far as I remember, the rationale for including this in the ZIP is we want it to be possible for a wallet to be backed up once-and-for-all, without needing to do so every time new addresses are generated. But I think it's more likely that a fully ZIP32 wallet would just refuse to generate new Sprout addresses (#3752), instead.

That's a good point. I suspect the best way to avoid a negative user experience is to remove the ability to create new Sprout addresses at the same time that we implement full HD support.

**Comment by daira** [comment]
#5474 removes the ability to create Sprout addresses in zcashd. As I pointed out in https://github.com/zcash/zcash/issues/3752#issuecomment-450485731 , that makes this ticket redundant.
