### ISSUE TITLE
Create a Windows CI Worker

### ISSUE THREAD

**Issue by mdr0id** [zcash/zcash#3384]
- [x] Create a Windows CI Worker
- [x] Investigate factory for Windows CI Worker
- [x] Create factory for Windows CI Worker
- [x] Deploy  Windows worker to development CI
- [x]  Verify Windows worker in development CI
- [x] Deploy Windows worker to production CI
- [x] Document details around specific toolchain used in Windows cross-compile
```
I've had success cross-compiling for windows using the Ubuntu 18.04 WSL environment provided by Microsoft. However this did not provide an approach to running tests on Windows. For answers on how to do that I've been investigating using the msys2 family of tools. -Charlie
```
- [ ] Document details around Windows CI deployment 

User story:
```
As a Zcash engineer, I want to have a Window CI worker/builder to verify commits against the Windows platforms.
```

**Comment by mms710** [comment]
Includes the request from Nathan: "As a Windows developer, I want to be able to build zcashd `master`  with minimal "fuss" compared to other platforms."

**Comment by mdr0id** [comment]
@veikkoeeva #2944 is addressed in https://github.com/zcash/zcash/pull/3172. Please let us know if you have any other questions

**Comment by veikkoeeva** [comment]
@mdr0id Thanks for taking care of that one issue. I remembed I saw something else while lurking but didn't spot it.

Later on I could imagine it would be useful to have new Windows builds easily available every time the CI (when it's working) compiles. This way the executable could be integrated with other components and tested with them (like rolling the executable into .NET [Nuget](https://www.nuget.org/) and run a test harness on .NET on the library).

Oh, and just noting, it would be great to compile natively in Windows or if it were possible to develop on Windows and cross-compiling on Linux. E.g. something like https://docs.microsoft.com/en-us/cpp/linux/configure-a-linux-project?view=vs-2017 and then later natively.

**Comment by mdr0id** [comment]
@veikkoeeva Many of the items you mentioned are actively being implemented/tested. We hope to have more information on all of this soon, but we have been occupied with v2.0.1 release. 

Additionally, if you are interested in CI related topics, we now have a channel in rocket chat: https://chat.zcashcommunity.com/channel/dev-infrastructure 

In the next few months we will be rolling out some new design/fixes to the system. The intention is to provide some cool projects that allow public to participate, in some form.  We greatly appreciate community feedback.

**Comment by mdr0id** [comment]
Closing this ticket as we now have a Linux builder that cross compiles Windows binary. Newer CI/CD will not follow the original criteria of this ticket since it is using other tools.
