### ISSUE TITLE
Update zcbenchmarks.cpp to include sapling note data

### ISSUE THREAD

**Issue by Eirik0** [zcash/zcash#3395]
This is follow up from #3353

**Comment by bitcartel** [comment]
@Eirik0 What would the tests measure?  Does #3611 capture some of those tests?

**Comment by Eirik0** [comment]
The comment in #3353 was referring to `benchmark_increment_note_witnesses` which benchmarks `wallet.ChainTip(&index2, &block2, sproutTree, saplingTree, true);` but does not have any interesting Sapling data.

It looks like we could also create a Sapling benchmark for `benchmark_try_decrypt_notes` which is benchmarking `auto nd = wallet.FindMySproutNotes(tx);`

Also, I wonder about `benchmark_connectblock_slow` which appeals to the inner class `FakeCoinsViewDB` which doesn't look like it's been updated for Sapling.

Probably some of the work in #3611 could be reused for these tests, but it doesn't capture it per se.
