### ISSUE TITLE
The "Encrypted Memo Field" can be more read-ably described as the "Encrypted Message Field"

### ISSUE THREAD

**Issue by zancas** [zcash/zcash#3397]
The "Encrypted Memo Field" was so named by analogy to the space on a bank note where one specifies why the transfer is happening.   This is certainly a valid use for the unstructured data associated with shielded transactions, but (hopefully) this data transport will have much more general utility.

  Given the above it seems that the "Encrypted Message Field" is a more accurate name for the data.
  In addition to being more accurate, this name will reduce cognitive friction (increase readability) for developers seeking to understand how to use zcash as a data transport platform.   I think that the increase in readability makes the name change not simply correct, but important.

**Comment by zancas** [comment]
@gojomo, when I hear the words "memo" and "message" I don't map them as synonyms.   In particular my brain attaches a connotation of less importance to "memo".  From my perspective, that data sumply isn't a "memo".

I agree with all of your other points, which I believe can be summarized as:  It will take effort to make this change.

**Comment by gojomo** [comment]
@zancas I hear you, but suspect the perception that a 'memo' has "less importance" is far from universal. Dictionary definitions tend to primarily describe 'memo' as "written message", with various secondary connotations of "business use", "short", "internal communication", and "official". To the extent it derives from 'memorandum', that full word to my mind signifies *more* importance, often specifying things that *must* be remembered or put-into-effect.

**Comment by daira** [comment]
I agree with @gojomo. I also don't perceive the importance distinction. Note that some of the points raised here were considered when the term "memo field" was chosen (unfortunately that's not documented in any GitHub ticket). In general I tend to assess the cost of changing terminology as high, so that there has to be a *very* compelling reason to do so, and I don't think this case meets the bar.

**Comment by zancas** [comment]
I thought about this more and I think I was mistaken to emphasize "importance".   The fact is, when I first encountered "encrypted memo field" I thought:

 Oh this is where I enter data like 'For Rent' if I am sending zcash to my landlord.

If that is, in fact, the purpose of the field then the field is well named.  If that's not the purpose, then the name is confusing, at least to me.   It's clear to me that the purpose of the field is much more general than that.

**Comment by daira** [comment]
I propose to close this as wontfix.
