### ISSUE TITLE
signrawtransaction :Operation not valid with the current stack size?

### ISSUE THREAD

**Issue by Herry143** [zcash/zcash#3400]
This issue tracker is only for technical issues related to zcashd.

General Zcash questions and/or support requests and are best directed to the [Zcash Forums](https://forum.z.cash) or [Community Rocket.Chat](https://chat.zcashcommunity.com).

For reporting security vulnerabilities or for sensitive discussions with our security team, please contact [security@z.cash](mailto:security@z.cash). You can use the [GPG key](https://z.cash/gpg-pubkeys/security.asc) (fingerprint: `AF85 0445 546C 18B7 86F9  2C62 88FB 8B86 D8B5 A68C`) to send an encrypted message. The key and fingerprint are duplicated on our [Public Keys page](https://z.cash/support/pubkeys.html).

### Describe the issue
Please provide a general summary of the issue you're experiencing

#### If so, please list the steps to reproduce below:
1. I want to send a transaction,so I createrawtransaction first,
./src/zcash-cli createrawtransaction "[{\"txid\":\"1ec22e34540e8748a369272d858421ff607c2b7991a88e154b352a9f7acd9431\",\"vout\":0}]" "{\"t1SauyDAndQRXDeLVyqo6o5xefK2fsXLySg\":0.01}"
return:
030000807082c403013194cd7a9f2a354b158ea891792b7c60ff2184852d2769a348870e54342ec21e0000000000ffffffff0140420f00000000001976a9145f910e46881f8ea215a8e757c7f91b74cf6c1db388ac00000000717f050000
2. then ./src/zcash-cli signrawtransaction "030000807082c403013194cd7a9f2a354b158ea891792b7c60ff2184852d2769a348870e54342ec21e0000000000ffffffff0140420f00000000001976a9145f910e46881f8ea215a8e757c7f91b74cf6c1db388ac00000000717f050000" "[{\"txid\":\"1ec22e34540e8748a369272d858421ff607c2b7991a88e154b352a9f7acd9431\",\"vout\":0,\"scriptPubKey\":\"76a914a0e556e5beb3045a67daa59842825f4f0de199ad88ac\",\"amount\":0.01}]"
return:
{
  "hex": "030000807082c403013194cd7a9f2a354b158ea891792b7c60ff2184852d2769a348870e54342ec21e0000000000ffffffff0140420f00000000001976a9145f910e46881f8ea215a8e757c7f91b74cf6c1db388ac00000000717f050000",
  "complete": false,
  "errors": [
    {
      "txid": "1ec22e34540e8748a369272d858421ff607c2b7991a88e154b352a9f7acd9431",
      "vout": 0,
      "scriptSig": "",
      "sequence": 4294967295,
      "error": "Operation not valid with the current stack size"
    }
  ]
}
 

### Expected behaviour
Tell us what should happen
it should return the signed hex string
### Actual behaviour + errors
Tell us what happens instead including any noticable error output (any messages displayed on-screen when e.g. a crash occurred)
it returns "Operation not valid with the current stack size",but I am sure I am right,I want to use first output 0f the transaction to finish the transaction,so the vout is 0.and i am not sure the amount(0.01) ,it means the amount that I want to spent or the total amount of the utxo?
### The version of Zcash you were using:
Run `zcashd --version` to find out
zcash 1.1.2lastest
### Machine specs:
- OS name + version:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):
- Linux kernel version (uname -a):
- Compiler version (gcc -version):

### Any extra information that might be useful in the debugging process.
This includes the relevant contents of `~/.zcash/debug.log`. You can paste raw text, attach the file directly in the issue or link to the text via a pastebin type site.
Please also include any non-standard things you did during compilation (extra flags, dependency version changes etc.) if applicable.

### Do you have a backup of `~/.zcash` directory and/or take a VM snapshot?
- Backing up / making a copy of the `~/.zcash` directory might help make the problem reproducible. Please redact appropriately.
- Taking a VM snapshot is really helpful for interactively testing fixes

**Comment by braddmiller** [comment]
Hi @Herry143 glancing over your transaction here, I don't think an amount of 0.1 would be right for txid `1ec22e34540e8748a369272d858421ff607c2b7991a88e154b352a9f7acd9431`, not sure if that is the problem but you can run the RPC command `listunspent` to confirm. Just find that txid and confirm you are inputting the right amount. I'd also suggest asking this question on chat.zcashcommunity.com in the user-support channel.

**Comment by irsdkv** [comment]
Hi all
I have the same problem.

I try to create p2sh redeem transaction for crosschain swaps and also have "Operation not valid with the current stack size".

Thisi is my actions log:

# Find unspent
**zcash-cli listunspent 0 9999999 '''["t291TwC4KQN7U6khtQmB831LVHYShq23tiL"]'''**
[
  {
    "txid": "1b1ed68277db1d412a1f2b4614fd3e8a0b45812399500834e4b74600287ce727",
    "vout": 0,
    "generated": false,
    "address": "t291TwC4KQN7U6khtQmB831LVHYShq23tiL",
    "account": "",
    "scriptPubKey": "a9141afac0de4beae0d23a4eb2cfb909e3d3e39250ec87",
    "amount": 0.00150000,
    "confirmations": 50,
    "spendable": false
  }
]

# Create tx
**zcash-cli createrawtransaction '''
[
 {
   "txid":"1b1ed68277db1d412a1f2b4614fd3e8a0b45812399500834e4b74600287ce727",
   "vout":0
 }
]''' '{"tmUvvA5nbZ7i6dYrkNBdxhj9kG8NVRUcamH":0.00150000}' **
0400008085202f890127e77c280046b7e4340850992381450b8a3efd14462b1f2a411ddb7782d61e1b0000000000ffffffff01f0490200000000001976a914d2cac8833010d5909c3797a51422aeb3fd6fc26188ac000000008caa04000000000000000000000000

# Sign
**zcash-cli signrawtransaction 0400008085202f890127e77c280046b7e4340850992381450b8a3efd14462b1f2a411ddb7782d61e1b0000000000ffffffff01f0490200000000001976a914d2cac8833010d5909c3797a51422aeb3fd6fc26188ac000000008caa04000000000000000000000000 '''
 [
  {
   "txid":"1b1ed68277db1d412a1f2b4614fd3e8a0b45812399500834e4b74600287ce727",
   "vout":0,
   "scriptPubKey":"a9141afac0de4beae0d23a4eb2cfb909e3d3e39250ec87",
   "redeemScript":"210342fd4a475f9a2a02c6fd40bff4ab635829d527b97260f97a29439d7d7e9a40c5209998e5fb8eb341fad94dce6b08556cbd08a9461e320ebfcaa2445974229379be514c5b63a8206bcff3c7bee18449d229f5cf27aa47ac7db18b665772029faadbb94388a210b08876a914d2cac8833010d5909c3797a51422aeb3fd6fc2616702e279b17576a914884bfb33789a8659109c856e07e758a831dce40c6888ac"
  }
 ]''' '''[
  "cPendc89zSR6omympUyZ6d4NKwErt2MNbw7TByNh5s2fCXwyWydT"
 ]''' ALL **
 {
   "hex": "0400008085202f890127e77c280046b7e4340850992381450b8a3efd14462b1f2a411ddb7782d61e1b0000000000ffffffff01f0490200000000001976a914884bfb33789a8659109c856e07e758a831dce40c88ac0000000075aa04000000000000000000000000",
   "complete": false,
   "errors": [
     {
       "txid": "1b1ed68277db1d412a1f2b4614fd3e8a0b45812399500834e4b74600287ce727",
       "vout": 0,
       "scriptSig": "",
       "sequence": 4294967295,
       "error": "Operation not valid with the current stack size"
     }
   ]
 }

Also I check mistakes and all seems ok:

 # Unspent tx script
 **bx script-decode a9141afac0de4beae0d23a4eb2cfb909e3d3e39250ec87**
 hash160 [1afac0de4beae0d23a4eb2cfb909e3d3e39250ec] equal

 # Redeem script
 **bx script-decode 210342fd4a475f9a2a02c6fd40bff4ab635829d527b97260f97a29439d7d7e9a40c5209998e5fb8eb341fad94dce6b08556cbd08a9461e320ebfcaa2445974229379be514c5b63a8206bcff3c7bee18449d229f5cf27aa47ac7db18b665772029faadbb94388a210b08876a914d2cac8833010d5909c3797a51422aeb3fd6fc2616702e279b17576a914884bfb33789a8659109c856e07e758a831dce40c6888ac**
 [0342fd4a475f9a2a02c6fd40bff4ab635829d527b97260f97a29439d7d7e9a40c5] [9998e5fb8eb341fad94dce6b08556cbd08a9461e320ebfcaa2445974229379be] 1 [63a8206bcff3c7bee18449d229f5cf27aa47ac7db18b665772029faadbb94388a210b08876a914d2cac8833010d5909c3797a51422aeb3fd6fc2616702e279b17576a914884bfb33789a8659109c856e07e758a831dce40c6888ac]

 # Check HASH160 for P2SH's script
 **bx bitcoin160 63a8206bcff3c7bee18449d229f5cf27aa47ac7db18b665772029faadbb94388a210b08876a914d2cac8833010d5909c3797a51422aeb3fd6fc2616702e279b17576a914884bfb33789a8659109c856e07e758a831dce40c6888ac **
 1afac0de4beae0d23a4eb2cfb909e3d3e39250ec

 # P2SH's script:
 **bx script-decode 63a8206bcff3c7bee18449d229f5cf27aa47ac7db18b665772029faadbb94388a210b08876a914d2cac8833010d5909c3797a51422aeb3fd6fc2616702e279b17576a914884bfb33789a8659109c856e07e758a831dce40c6888ac **
 if sha256 [6bcff3c7bee18449d229f5cf27aa47ac7db18b665772029faadbb94388a210b0] equalverify dup hash160 [d2cac8833010d5909c3797a51422aeb3fd6fc261] else [e279] checklocktimeverify drop dup hash160 [884bfb33789a8659109c856e07e758a831dce40c] endif equalverify checksig

 # Check public key to sign
 **zcash-cli validateaddress tmUvvA5nbZ7i6dYrkNBdxhj9kG8NVRUcamH**
 {
   "isvalid": true,
   "address": "tmUvvA5nbZ7i6dYrkNBdxhj9kG8NVRUcamH",
   "scriptPubKey": "76a914d2cac8833010d5909c3797a51422aeb3fd6fc26188ac",
   "ismine": true,
   "iswatchonly": false,
   "isscript": false,
   "pubkey": "0342fd4a475f9a2a02c6fd40bff4ab635829d527b97260f97a29439d7d7e9a40c5",
   "iscompressed": true,
   "account": ""
 }
 ## Check pubkey hash
 **bx bitcoin160 0342fd4a475f9a2a02c6fd40bff4ab635829d527b97260f97a29439d7d7e9a40c5**
 d2cac8833010d5909c3797a51422aeb3fd6fc261

 # Get privkey
 **zcash-cli dumpprivkey tmUvvA5nbZ7i6dYrkNBdxhj9kG8NVRUcamH**
 cPendc89zSR6omympUyZ6d4NKwErt2MNbw7TByNh5s2fCXwyWydT

**zcashd --version
**
Zcash Daemon version v1.1.2

I will be grateful for any help.
Also attach file with all actions.
[create_transaction_log_tmp.txt](https://github.com/zcash/zcash/files/2393746/create_transaction_log_tmp.txt)

Thank you!

**Comment by ioptio** [comment]
If you are open to resolving this still, can you retry with updated zcashd software and a fully synced blockchain?

**Comment by ioptio** [comment]
Closing this due to lack of response, but you can reopen with new comments if you have them.
