### ISSUE TITLE
How to use coinbase funds

### ISSUE THREAD

**Issue by growlot** [zcash/zcash#3404]
I am running zcash testnet, and mining by specifying command line option **-gen=1** to zcashd. 
I have got some coins after for a while. But I cant transfer mined coins(block reward) to taddr or zaddr. I think it is related Coinbase protected flag. How can I withdraw mined coins?
I am looking forward to get solution as soon as possible.
Thanks

**Comment by garethtdavies** [comment]
Coinbase funds must first be shielded before they may be used i.e. sent to a z-addr. Additionally all funds must be spent and no change is allowed. Fortunately there is a specific command which aids in this process `z_shieldcoinbase`. The docs are [here](https://zcash.readthedocs.io/en/latest/rtd_pages/rtd_docs/payment_api.html#z-shieldcoinbase) but should you wish to simply shield all of your coinbase transactions you can simply run `z_shieldcoinbase "*" "you-z-addr-here"`. Once you have them in a z-addr, simply use `z_sendmany` to [send as normal](https://zcash.readthedocs.io/en/latest/rtd_pages/rtd_docs/payment_api.html#z-sendmany).

**Comment by growlot** [comment]
Thank you. It works.
