### ISSUE TITLE
connect() to [2001:41d0:2:eedb::]:8233 failed: Network is unreachable (101)

### ISSUE THREAD

**Issue by Smurfy303** [zcash/zcash#3405]
Hi,

I have download zcash & now its synced upto block 347499 but after that it stucks syncing process.
debug.log contains below error,

> **2018-07-19 05:44:14 connect() to [2001:41d0:2:eedb::]:8233 failed: Network is unreachable (101)**
> 2018-07-19 05:44:15 Misbehaving: 95.216.24.211:8233 (0 -> 1)
> 2018-07-19 05:44:15 ProcessMessages(reject, 43 bytes) FAILED peer=1664
> 2018-07-19 05:44:15 Misbehaving: 95.216.24.211:8233 (1 -> 2)
> 2018-07-19 05:44:15 ProcessMessages(ping, 8 bytes) FAILED peer=1664
> 2018-07-19 05:44:15 Misbehaving: 128.77.37.214:8233 (0 -> 1)
> 2018-07-19 05:44:15 ProcessMessages(reject, 43 bytes) FAILED peer=1665
> 2018-07-19 05:44:15 Misbehaving: 128.77.37.214:8233 (1 -> 2)
> 2018-07-19 05:44:15 ProcessMessages(ping, 8 bytes) FAILED peer=1665
> 2018-07-19 05:44:15 Misbehaving: 128.77.37.214:8233 (2 -> 3)
> 2018-07-19 05:44:15 ProcessMessages(getheaders, 997 bytes) FAILED peer=1665
> 2018-07-19 05:44:18 Misbehaving: 193.70.36.138:8233 (0 -> 1)
> 2018-07-19 05:44:18 ProcessMessages(reject, 43 bytes) FAILED peer=1666
> 2018-07-19 05:44:18 Misbehaving: 193.70.36.138:8233 (1 -> 2)
> 2018-07-19 05:44:18 ProcessMessages(ping, 8 bytes) FAILED peer=1666
> 2018-07-19 05:44:18 Misbehaving: 128.199.168.99:8233 (0 -> 1)
> 2018-07-19 05:44:18 ProcessMessages(reject, 43 bytes) FAILED peer=1667
> 2018-07-19 05:44:18 Misbehaving: 128.199.168.99:8233 (1 -> 2)
> 2018-07-19 05:44:18 ProcessMessages(ping, 8 bytes) FAILED peer=1667
> 2018-07-19 05:44:19 Misbehaving: 84.19.36.203:8233 (0 -> 1)
> 2018-07-19 05:44:19 ProcessMessages(reject, 43 bytes) FAILED peer=1668
> 2018-07-19 05:44:19 Misbehaving: 84.19.36.203:8233 (1 -> 2)
> 2018-07-19 05:44:19 ProcessMessages(ping, 8 bytes) FAILED peer=1668
> 2018-07-19 05:44:19 Misbehaving: 84.19.36.203:8233 (2 -> 3)
> 2018-07-19 05:44:19 ProcessMessages(getheaders, 997 bytes) FAILED peer=1668
> 2018-07-19 05:44:19 Misbehaving: 92.222.77.84:8233 (0 -> 1)
> 2018-07-19 05:44:19 ProcessMessages(reject, 43 bytes) FAILED peer=1669
> 2018-07-19 05:44:19 Misbehaving: 92.222.77.84:8233 (1 -> 2)
> 2018-07-19 05:44:19 ProcessMessages(ping, 8 bytes) FAILED peer=1669
> 2018-07-19 05:44:19 Misbehaving: 92.222.77.84:8233 (2 -> 3)
> 2018-07-19 05:44:19 ProcessMessages(getheaders, 997 bytes) FAILED peer=1669

this error comes continously from 1day. Does anyone have solution to come out of this error ?

**Comment by garethtdavies** [comment]
Are you on a Overwinter compatible release i.e. > 1.1.0 as the pre-Overwinter chain is in safe mode. Run `zcashd --version` or `zcash-cli --version`. If you are on a version less than 1.1.0 you need to upgrade.

**Comment by Smurfy303** [comment]
My zcashd version is :  **Zcash Daemon version v1.1.1**
& Zcash-cli :  **Zcash RPC client version v1.1.1**

**Comment by bitcartel** [comment]
What is the output of `zcash-cli getpeerinfo`?  I'd like to see what kind of peers you are connected to.  Thanks.

**Comment by Smurfy303** [comment]
I am not able to hit `getpeerinfo`  because it gives me an error while starting `zcash-bitcore-node` as below,

> Press Ctrl+C to exit] [Set 'showmetrics=0' to hide]
> [2018-07-23T05:30:43.116Z] warn: Zcash process unexpectedly exited with code: 1
> [2018-07-23T05:30:43.116Z] warn: Restarting zcash child process in 5000ms
> [2018-07-23T05:30:48.117Z] info: Using zcash config file: /root/.zcash/data/zcash.conf
> [2018-07-23T05:30:48.118Z] warn: Stopping existing spawned zcash process with pid: 13901

and 

> zcash-cli getpeerinfo
> error: couldn't connect to server: unknown (code -1)
> (make sure server is running and you are connecting to the correct RPC port)

**Comment by garethtdavies** [comment]
I tried to replicate this by firing up a new Ubuntu 18.04 machine on 1.1.2 and syncing from scratch and get the same result with it just hanging on height `347499`. Here are the last lines of debug.log. It got stuck arouund 7 hours ago and hasn't progrssed.

```
2018-07-23 08:23:54 UpdateTip: new best=000000000361d0525aa389933174bd3b1fdb6003a71ad9f671ec388d9b208107  height=347490  log2_work=53.543605  tx=3457407  date=2018-06-26 00:51:14 progress=0.976824  cache=210.2MiB(9733tx)
2018-07-23 08:23:55 UpdateTip: new best=0000000007b7928a08c6a17fc8793724e8a3d69d174f9c96be095e88f764d320  height=347491  log2_work=53.543614  tx=3457423  date=2018-06-26 00:59:22 progress=0.976829  cache=210.3MiB(9758tx)
2018-07-23 08:23:55 UpdateTip: new best=000000000c3a6de2a02a7b7f0f15db6a04381b92dbf5a1dab43cf971225179c8  height=347492  log2_work=53.543623  tx=3457425  date=2018-06-26 01:00:57 progress=0.976830  cache=210.3MiB(9761tx)
2018-07-23 08:23:55 UpdateTip: new best=000000000e2ea93d5f0efa0c3573a3e07ac92daaa022bc917b19289ab2b5817e  height=347493  log2_work=53.543631  tx=3457438  date=2018-06-26 01:05:30 progress=0.976833  cache=212.2MiB(9854tx)
2018-07-23 08:23:56 UpdateTip: new best=0000000007a51b034b92e04f6eeeb5fec5765fb3a18e2b60b51199731e077032  height=347494  log2_work=53.543639  tx=3457447  date=2018-06-26 01:10:14 progress=0.976836  cache=214.6MiB(10008tx)
2018-07-23 08:23:57 UpdateTip: new best=000000000b4dfb99fbcca8f2efc407a2170a8364cea4bed87265ca84c2f8c9eb  height=347495  log2_work=53.543648  tx=3457464  date=2018-06-26 01:20:16 progress=0.976841  cache=215.1MiB(10056tx)
2018-07-23 08:23:57 UpdateTip: new best=0000000007561ebdfc133bf3c99144d15a71f5d7dea859a538dbc2cca981e815  height=347496  log2_work=53.543656  tx=3457466  date=2018-06-26 01:20:43 progress=0.976842  cache=215.1MiB(10057tx)
2018-07-23 08:23:57 UpdateTip: new best=00000000019a399daba875cab48f6e6a441c985d85eddea375a3ab89d7880464  height=347497  log2_work=53.543664  tx=3457468  date=2018-06-26 01:21:58 progress=0.976842  cache=215.1MiB(10059tx)
2018-07-23 08:23:57 UpdateTip: new best=000000000704f869d10cf1e02198b517fcc1832299a8d29a930d5d01b958136d  height=347498  log2_work=53.543673  tx=3457477  date=2018-06-26 01:35:48 progress=0.976850  cache=215.1MiB(10072tx)
2018-07-23 08:23:58 UpdateTip: new best=000000000c4e12f913c1d5f75ca55928653398d6ffde9eff11d2ea3d364fb502  height=347499  log2_work=53.543682  tx=3457487  date=2018-06-26 01:35:56 progress=0.976851  cache=215.2MiB(10089tx)
```

Here is result of `getpeerinfo` https://gist.github.com/garethtdavies/df6482b892a9123f34848541cb38bf26

Here is result of `getblockchaininfo`

```
{
  "chain": "main",
  "blocks": 347499,
  "headers": 362934,
  "bestblockhash": "000000000c4e12f913c1d5f75ca55928653398d6ffde9eff11d2ea3d364fb502",
  "difficulty": 9287309.929070316,
  "verificationprogress": 0.9766135162899678,
  "chainwork": "000000000000000000000000000000000000000000000000002ea5607947726b",
  "pruned": false,
  "commitments": 1081336,
  "valuePools": [
    {
      "id": "sprout",
      "monitored": true,
      "chainValue": 230376.04248978,
      "chainValueZat": 23037604248978
    },
    {
      "id": "sapling",
      "monitored": true,
      "chainValue": 0.00000000,
      "chainValueZat": 0
    }
  ],
  "softforks": [
    {
      "id": "bip34",
      "version": 2,
      "enforce": {
        "status": true,
        "found": 4000,
        "required": 750,
        "window": 4000
      },
      "reject": {
        "status": true,
        "found": 4000,
        "required": 950,
        "window": 4000
      }
    },
    {
      "id": "bip66",
      "version": 3,
      "enforce": {
        "status": true,
        "found": 4000,
        "required": 750,
        "window": 4000
      },
      "reject": {
        "status": true,
        "found": 4000,
        "required": 950,
        "window": 4000
      }
    },
    {
      "id": "bip65",
      "version": 4,
      "enforce": {
        "status": true,
        "found": 4000,
        "required": 750,
        "window": 4000
      },
      "reject": {
        "status": true,
        "found": 4000,
        "required": 950,
        "window": 4000
      }
    }
  ],
  "upgrades": {
    "5ba81b19": {
      "name": "Overwinter",
      "activationheight": 347500,
      "status": "pending",
      "info": "See https://z.cash/upgrade/overwinter.html for details."
    }
  },
  "consensus": {
    "chaintip": "00000000",
    "nextblock": "5ba81b19"
  }
}
```

**Comment by garethtdavies** [comment]
This eventually moved past the Overwinter activation height (after circa 12 hours of being stuck) and is now at the correct height which I imagine is also what happened here: https://forum.z.cash/t/zcash-blockchain-is-not-sync/30358

**Comment by Smurfy303** [comment]
and my `getblockchaininfo` is,

> {
>   "chain": "main",
>   "blocks": 347499,
>   "headers": 347499,
>   "bestblockhash": "000000000c4e12f913c1d5f75ca55928653398d6ffde9eff11d2ea3d364fb502",
>   "difficulty": 9287309.92907032,
>   "verificationprogress": 0.95877900,
>   "chainwork": "000000000000000000000000000000000000000000000000002ea5607947726b",
>   "pruned": false,
>   "softforks": [
>     {
>       "id": "bip34",
>       "version": 2,
>       "enforce": {
>         "status": true,
>         "found": 4000,
>         "required": 750,
>         "window": 4000
>       },
>       "reject": {
>         "status": true,
>         "found": 4000,
>         "required": 950,
>         "window": 4000
>       }
>     },
>     {
>       "id": "bip66",
>       "version": 3,
>       "enforce": {
>         "status": true,
>         "found": 4000,
>         "required": 750,
>         "window": 4000
>       },
>       "reject": {
>         "status": true,
>         "found": 4000,
>         "required": 950,
>         "window": 4000
>       }
>     },
>     {
>       "id": "bip65",
>       "version": 4,
>       "enforce": {
>         "status": true,
>         "found": 4000,
>         "required": 750,
>         "window": 4000
>       },
>       "reject": {
>         "status": true,
>         "found": 4000,
>         "required": 950,
>         "window": 4000
>       }
>     }

Now its 1 day 21 ahours zcash syncing gives me an same error.
What should I do to resolve this issue ?? Should I wait -OR- do something else to solve this issue ??

**Comment by Smurfy303** [comment]
Hello 
Is anybody here ??
Please someone help to solve this problem

**Comment by garethtdavies** [comment]
From another issue so I am not sure it would help but worth a try. Run `zcash-cli clearbanned` and if that fails try to restart zcashd by stopping and then restarting.

**Comment by Smurfy303** [comment]
It gives `Method not found` error

**Comment by ichthuss** [comment]
Probably related to #3399

**Comment by Smurfy303** [comment]
Hi, I solved this problem by reinstalling zcash with version 1.1.2 and sync again
