### ISSUE TITLE
Fix missing ifdef lost during rpc refactor

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#3407]
https://github.com/zcash/zcash/pull/3350#pullrequestreview-138819820

**Comment by bitcartel** [comment]
'RegisterWalletRPCCommands' is _currently_ only invoked from inside an `#ifdef ENABLE_WALLET` block, but a future developer could introduce a new call site.  As a defensive measure, the RPC calls can be placed inside a conditional compile block.

**Comment by daira** [comment]
As discussed at https://github.com/zcash/zcash/pull/3411#issuecomment-407566630 , @str4d and I established that #3411 is not necessary (and if another call into the wallet code were added, I don't think that PR would help).
