### ISSUE TITLE
"ZcashSigHash" || CONSENSUS_BRANCH_ID

### ISSUE THREAD

**Issue by xianaofei** [zcash/zcash#3413]
"ZcashSigHash" || CONSENSUS_BRANCH_ID 

hashPrevouts:
  BLAKE2b-256('ZcashPrevoutHash', b'')
= d53a633bbecf82fe9e9484d8a0e727c73bb9e68c96e72dec30144f6a84afa136
hashPrevouts key is ZcashPrevoutHash.
this ZcashSigHash What is the whole? 
 BLAKE2b-256('ZcashSigHash...?', 'XXX')

**Comment by daira** [comment]
The last 4 bytes are a little-endian encoding of the consensus branch ID.

**Comment by str4d** [comment]
> The consensus branch ID for Sapling will be 0x76b809bb.

This is incorrect. That is the consensus branch ID for Sapling on the *current* testnet, but when we release 2.0.0 we will be resetting testnet to switch to the new parameters, which requires changing the consensus branch ID.
