### ISSUE TITLE
ZCash reboots trigger a very long rescan.

### ISSUE THREAD

**Issue by DaveWK** [zcash/zcash#3414]
When zcash restarts, it always rescans from a very old block; this means that it takes a very long time with a large wallet. This process currently means I am waiting several days if I reboot the node.

#### If so, please list the steps to reproduce below:
1. Have a zcash wallet with a large number of addresses and uxtos
2. restart node
3. observe that it takes several days to rescan the blockchain, and that it starts rescanning the chain from a very far back point in time; IE:
Rescanning last 175179 blocks (from block 184445)...

### Expected behaviour:

It should start re scanning from a post-overwinter activation block, preferably a fixed number from the head rather than an absolute block. This would allow as the chain grows for it to not be bounded back in a particular point in time for a rescan.

### The version of Zcash you were using:
1.1.0, 1.1.1 and 1.1.2

### Machine specs:
- OS name + version: AWS Linux, Docker (Debian:Stable)
AWS: r4.2xlarge

**Comment by bitcartel** [comment]
A post-Overwinter checkpoint might help here.

**Comment by daira** [comment]
There are criteria for a checkpoint that wouldn't be met for an arbitrary block a given distance back in the chain: https://github.com/zcash/zcash/blob/a7a62b724b8baeef564fd908c8a25366a9674f52/src/chainparams.cpp#L71-L75

**Comment by daira** [comment]
We should merge #3246 first. I don't know why that PR languished.

**Comment by str4d** [comment]
@daira that PR was left so that we could collect IBD performance data before merging, to see the effect.

**Comment by daira** [comment]
#3246 has been merged and includes checkpoints up to block 304600. The current height is 376939. I don't know whether we want to consider this fixed, or do more to address the underlying issue? Leaving open for now.

**Comment by ioptio** [comment]
@DaveWK has this issue since been resolved for you?

**Comment by str4d** [comment]
I wonder if this was in fact the same issue as #3495?

**Comment by DaveWK** [comment]
that issue does indeed sound similar to mine.. about 3 hours to load the wallet, and about 3 days to rescan the chain. I do see that ` SetBestChain(): Failed to write CWalletTx, aborting atomic write` int the logs sometimes

**Comment by ioptio** [comment]
We're going to try and reproduce this and see what we find.

**Comment by daira** [comment]
This should have been fixed by #3711. Please reopen if not.
