### ISSUE TITLE
Some question about BN-254 used in zk-SNARKs

### ISSUE THREAD

**Issue by NickyYangYang** [zcash/zcash#3418]
Hello,
        In Zcash , you use a BN-254 curve in zk-SNARKs.  There are many different  curves whose length of p is 254 bits ,like curve described in http://cryptojedi.org/papers/dclxvi-20100714.pdf  or curves described in  paper "Pairing-Friendly Elliptic Curves of Prime Order".  
       Then， I have some question about the BN-254 curve.
1、Why you choose this BN-254 curve? 
2、Does the BN-254 curve described in a paper? If so , which paper you reference?
3、You use the BN-254 curve in zk-SNARKs. Does this curve security used to do sign and verify?

**Comment by str4d** [comment]
1) was answered in #3352. Leaving this issue open for the follow-up questions.

**Comment by NickyYangYang** [comment]
Thanks for your answer.  
And I hope you can answer question 2 and question 3.

**Comment by ebfull** [comment]
> Does the BN-254 curve described in a paper? If so , which paper you reference?

It's not explicitly described, but the rationale for it is given in [BCGTV13](http://eprint.iacr.org/2013/507).

> You use the BN-254 curve in zk-SNARKs. Does this curve security used to do sign and verify?

We are moving away from BN254 to BLS12-381 for security purposes. BLS12-381 (or BN254 ignoring the NFS optimizations) is appropriate for BLS signatures, yes, but BN254/BLS12-381 have some features (like a large 2^n root of unity) that you wouldn't need for BLS signatures, so you could use another similarly-sized curve or something like BLS24/KSS16 without those features if you wanted.

**Comment by NickyYangYang** [comment]
OK，Thanks for your answer.
I will go to study this paper.

**Comment by ioptio** [comment]
Closing this since it looks like we answered your questions. Thanks for the inquiry!

**Comment by amit-supraoracles** [comment]
Hi !

Does BN254 curve supports distributed key generation ?
Is it possible to perform threshold signature using this ?
