### ISSUE TITLE
How can I pass params in z_sendmany method?

### ISSUE THREAD

**Issue by VtpVlan-oo7** [zcash/zcash#3419]
rpc.z_sendmany("tmRQyUsncVLY6QkSy6HuZwzhWyy7PNeqnTq",[{"tmU2nsehywScV4MY2bwXiCMD1BgP2z16BDP":1}]).then(data => {
            console.log("data==>>", data)
        }).catch(err => {
            console.log("err==>>" + JSON.stringify(err))
        })

**Comment by garethtdavies** [comment]
Have you checked out the[docs](https://zcash.readthedocs.io/en/latest/rtd_pages/rtd_docs/payment_api.html#z-sendmany) and the [examples](https://zcash-rpc.github.io/z_sendmany.html) from the CLI?

**Comment by VtpVlan-oo7** [comment]
I am successfully done with z_sendmany from cli .
But i facing problem through API. Can you tell me what is wrong in this sytax.

rpc.z_sendmany("tmRQyUsncVLY6QkSy6HuZwzhWyy7PNeqnTq",[{"tmU2nsehywScV4MY2bwXiCMD1BgP2z16BDP":1}]).then(data => {
console.log("data==>>", data)
}).catch(err => {
console.log("err==>>" + JSON.stringify(err))
})

**Comment by garethtdavies** [comment]
What library are you using to make this request? Did you see the syntax of the curl example?

```curl --user myusername --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "z_sendmany", "params": ["t1M72Sfpbz1BPpXFHz9m3CdqATR44Jvaydd", [{"address": "ztfaW34Gj9FrnGUEf833ywDVL62NWXBM81u6EQnM6VR45eYnXhwztecW1SjxA7JrmAXKJhxhj3vDNEpVCQoSvVoSpmbhtjf" ,"amount": 5.0}]] }' -H 'content-type: text/plain;' http://127.0.0.1:8232/```

**Comment by ioptio** [comment]
@VtpVlan-oo7 Can you provide the output as well?

**Comment by ioptio** [comment]
Timing out on this one but feel free to reopen if you have more info.
