### ISSUE TITLE
v1.1.2-bitcore?

### ISSUE THREAD

**Issue by Herry143** [zcash/zcash#3421]
do you have the latest zcash code,and have add the  rpc,such as: getaddressbalance,getaddresstxids....

**Comment by garethtdavies** [comment]
Have you seen this repo https://github.com/zcash-hackworks/bitcore-node-zcash which I believe is most up-to-date?

**Comment by braddmiller** [comment]
This has been dormant for quite a while. I'm going to close this issue, please feel free to reopen the issue if the latest updates to the repo that Gareth linked do not solve the problem.
