### ISSUE TITLE
Not working faucet + explorer + zcashd in testnet

### ISSUE THREAD

**Issue by blockplus** [zcash/zcash#3423]
These days:
I did run zcashd v1.1.2. and did try to get zcash faucet using https://faucet.testnet.z.cash
It said success with 3 ZEC and I did confirm it on https://explorer.testnet.z.cash, but my zcashd said afterwards 9K blocks than https://explorer.testnet.z.cash/blocks
So I did try again with zcashd v1.0.15 rc1, but it said behind 2K blocks than https://explorer.testnet.z.cash/blocks.
How can I get zcash faucet now? I am looking forward to get solution. Best

**Comment by garethtdavies** [comment]
There are currently two testnet chains. The faucet for the current Sapling activated testnet (v1.1.1 & v1.1.2) is here https://sapling-faucet.testnet.z.cash/

There is also a block explorer here which is a bit wonky but will show latest transactions https://explorer.beta.z.cash/.

Alternatively, use v1.1.0 and wait for it to sync and stay on the Overwinter testnet.

**Comment by blockplus** [comment]
Thank you, it working!
