### ISSUE TITLE
RpcError: AcceptToMemoryPool: absurdly high fees f577b41bd5370d73717fa04588d07299752c7fef8f564ba3bd60f0d11ff2649b, 1799829000 > 210000

### ISSUE THREAD

**Issue by VtpVlan-oo7** [zcash/zcash#3432]
RpcError: AcceptToMemoryPool: absurdly high fees f577b41bd5370d73717fa04588d07299752c7fef8f564ba3bd60f0d11ff2649b, 1799829000 > 210000

**Comment by garethtdavies** [comment]
As per the error, you have attached too high a fee to the transaction (this could be from the fee itself or you could have undercalculated change amounts). Reduce the fee and it'll work.

You may also find more help with these implementation problems using the [Zcash forums](https://forum.z.cash/) and [Zcash Community Chat](https://chat.zcashcommunity.com/).

**Comment by ioptio** [comment]
@VtpVlan-oo7 let us know if your transaction worked with a lower fee.

**Comment by ioptio** [comment]
It's worth documenting errors like this in the troubleshooting guide in the documentation http://zcash.readthedocs.io/en/latest/rtd_pages/rtd_docs/troubleshooting_guide.html#troubleshooting-guide

**Comment by ioptio** [comment]
This is documented here: https://zcash.readthedocs.io/en/latest/rtd_pages/troubleshooting_guide.html
