### ISSUE TITLE
[compile error]zcashd-bitcoind.o: file not recognized

### ISSUE THREAD

**Issue by nitrieu** [zcash/zcash#3440]
### Describe the issue
zcashd-bitcoind.o: file not recognized: File truncated
collect2: error: ld returned 1 exit status
Makefile:2379: recipe for target 'zcashd' failed

#### steps to reproduce below:
I follow https://github.com/zcash/zcash/wiki/1.0-User-Guide. The error occurs at "$ ./zcutil/build.sh -j$(nproc)"

### The version of Zcash you were using:
Zcash Daemon version v1.0.0

### Machine specs:
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
GNU assembler (GNU Binutils for Ubuntu) 2.26.1
GNU ld (GNU Binutils for Ubuntu) 2.26.1
+ HOST=x86_64-unknown-linux-gnu
+ BUILD=x86_64-unknown-linux-gnu
+ NO_PROTON=--enable-proton=no
+ make -j10 -C ./depends/ V=1

### Any extra information that might be useful in the debugging process.
.zcash/debug.log: No such file or directory

### Do you have a backup of `~/.zcash` directory and/or take a VM snapshot?
![image](https://user-images.githubusercontent.com/16380791/43554462-5c3b1ee4-95a9-11e8-8218-eca2cb88f8ce.png)

**Comment by mdr0id** [comment]
Please update to a more recent zcashd version. 

You can reference http://zcash.readthedocs.io/en/latest/rtd_pages/rtd_docs/user_guide.html#setup

**Comment by ioptio** [comment]
@nitrieu let us know if that works for you.

**Comment by nitrieu** [comment]
thanks @ioptio  and @mdr0id, the updated version works well.

**Comment by ioptio** [comment]
Good to hear!
