### ISSUE TITLE
Document supported Debian versions, rename apt repository [keyword: stretch]

### ISSUE THREAD

**Issue by need-debian-stretch** [zcash/zcash#3456]
[In Zcash forum](https://forum.z.cash/t/installing-on-debian-stretch/17977/3), 2017-06-25 17:17:49 UTC, @bitcartel wrote:

> Can you file a ticket on Github about renaming the apt repository? Thanks.

I found this on web search, because...

For past 15 months, I am maintaining a special Debian jessie (oldstable) installation for Zcash only. Major pain -- especially since jessie is now EOL, and my dev environment is long time on stretch (stable).

I do this, [because even today](https://archive.is/i3rnL), the only official `apt.z.cash` [repository distribution](https://apt.z.cash/dists/) is named `jessie`. The Zcash Supported Platorms policy says nothing useful about this. Searching the web [and the issues tracker](https://github.com/zcash/zcash/issues?utf8=%E2%9C%93&q=is%3Aissue+stretch), I found **no** documentation of supported Debian versions. Only some old Github bugs of zcash bad on stretch (when it was not yet stable), such as #2212, #2366; with indication that stretch was "unsupported". Then web search found the above quoted forum post.

*That forum post is the very best documentation of support status for Debian stretch!?*

- If the `apt.z.cash` binary can be installed on stretch, please be renaming the apt repository!
- Please add documentation of what Debian version(s) are *currently* supported!
- If it is answered in this issue that stretch is indeed being supported in the official .deb, I will switch my Zcash away from jessie straightaway. :) I am uncomfortable configuring "jessie" repository on stretch, without clarification.

Thank you.

**Comment by ioptio** [comment]
We'll look into stretch documentation & we'll have dev infrastructure team look into official support for both versions.

Thank you!

**Comment by need-debian-stretch** [comment]
Thank you, @ioptio!

To be clear, is the binary from `apt.z.cash` safe to run on Debian 9 (stretch)? This is indicated in the [14 month old forum thread](https://forum.z.cash/t/installing-on-debian-stretch/17977) I linked before... but I don't want to risk losing coins!

Debian 9 ("stretch", "stable") was [released on June 17th, 2017](https://www.debian.org/News/2017/20170617). Debian 8 ("jessie", "oldstable") ended ordinary updates, entered [Long Term Support](https://wiki.debian.org/LTS) phase [on June 23rd, 2018](https://www.debian.org/News/2018/20180623). Are all users of `apt.z.cash` still on jessie? I would be very surprised... but it is confusing, the only repository dist name is "jessie".

**Comment by huertanix** [comment]
Hi there, I am also interested in a Debian stretch deb. Any update on this?

**Comment by mms710** [comment]
We're putting this near the top of the backlog and hope to get to it in the next sprint, which starts in a week.

**Comment by need-debian-stretch** [comment]
This is now critical, as there is a code execution vulnerability in the `apt` updater that is apparently not being fixed in jessie. Therefore, jessie cannot be safely updated anymore!

https://www.debian.org/security/2019/dsa-4371

Is everybody still running zcash on jessie? (Is *anybody* still running zcash on jessie?) Is stretch officially supported from the `apt.z.cash` repo? I have not seen any documentation of this issue, and it is still "jessie" under dists. https://archive.is/KS4oF

**Comment by mms710** [comment]
This is currently prioritized for us to take a look at it in the next month.

**Comment by daira** [comment]
Yes, the current distribution works fine on Stretch. However, I agree this is misleading. We should rename it to "stable".

**Comment by ioptio** [comment]
We are retargetting 2.0.6 and above for Debian stretch and will no longer be supporting Jessie for those versions.

We can close this ticket once 2.0.6 is out with proper updated documentation. In the meantime, we've included instructions for updating to stretch for those who have not, yet: https://zcash.readthedocs.io/en/latest/rtd_pages/install_debian_bin_packages.html#upgrading-debian-8-jessie-to-debian-9-stretch

**Comment by mdr0id** [comment]
Closing as it is implemented.
