### ISSUE TITLE
Building application (ICO) ontop of zcash

### ISSUE THREAD

**Issue by fatnjazzy** [zcash/zcash#3457]
Hi,
We are a niche ICO who is seeking for a private and anonymous blockchain.
I have a use case where I need to onboard my users and give them private and anonymous storage. 
The storage supposed to be searchable (among all users).
The ICO needs to offer ERC20 based token.
Is Zcash something I should look into? Is the SDK production?
if not, can you recommend an alternative technology?
Thanks

**Comment by ioptio** [comment]
@fatnjazzy please direct general questions like this to more suitable channels the community chat: https://chat.zcashcommunity.com

Thank you!
