### ISSUE TITLE
Instructions do not clearly indicate dependencies.

### ISSUE THREAD

**Issue by MicahZoltu** [zcash/zcash#3460]
### Describe the issue
Attempting to install ZCash into a clean docker image via instructions at https://zcash.readthedocs.io/en/latest/rtd_pages/rtd_docs/install_debian_bin_packages.html#install-debian-bin-packages-guide doesn't work.

#### If so, please list the steps to reproduce below:
```
FROM ubuntu:18.04
RUN apt-get update \
	&& apt-get install --yes apt-transport-https \
	&& rm -rf /var/lib/apt/lists/*
RUN install gnupg2
RUN wget -qO - https://apt.z.cash/zcash.asc | apt-key add -
RUN echo "deb [arch=amd64] https://apt.z.cash/ jessie main" | tee /etc/apt/sources.list.d/zcash.list
```
Failure on missing `wget`, then failure on missing `gnupg, gnupg2 or gnupg1`.

**Comment by MicahZoltu** [comment]
This can be fixed by installing `wget` and `gnupg` in the second docker layer, along with `apt-transport-https`.

**Comment by ioptio** [comment]
Glad you fixed it!

**Comment by MicahZoltu** [comment]
@ioptio I worked around it and shared the workaround here, but the issue persists and is not fixed for all future new users.  The linked instructions should be updated to reflect the actual dependencies.

**Comment by ioptio** [comment]
@MicahZoltu we do not officially support installing on docker at this time. If that changes, we'll be sure to provide appropriate documentation then.

**Comment by MicahZoltu** [comment]
This isn't a docker specific problem, it is a problem installing on any Ubuntu machine with a minimal distribution.  Using Docker is just a really easy way to reproduce the problem, which is why I provided it as the repro steps.  You could similarly reproduce the problem by installing Ubuntu with minimal packages on a new computer, but repro steps that include "buy a new computer" kind of suck.  :)
