### ISSUE TITLE
Blocking mode for zcash-cli when calling async RPC methods

### ISSUE THREAD

**Issue by daira** [zcash/zcash#3466]
It now takes on the order of a few seconds to make a shielded transaction in Sapling. This is short enough that it would be useful to have a mode in which `zcash-cli` blocks until the outcome is available. 

With the current RPC interface this would be implemented by polling on `z_getoperationstatus`/`z_getoperationresult`, but that's an implementation detail and would not prevent implementing it in some other way in future.

It is an independent decision whether to make this the default for async methods and have a flag to obtain non-blocking behaviour, or the reverse.

**Comment by daira** [comment]
I suggest `-blocking=0/1` for the option name.

**Comment by ch4ot1c** [comment]
Ack. If useful, here is a mildly refactored version of `AsyncRPCOperation`:
https://github.com/BTCPrivate/BTCP-Rebase/pull/33

**Comment by tromer** [comment]
Duplicate of #1952?

**Comment by oxarbitrage** [comment]
Yes, i think is a duplicate. I am after a solution in the cli level as suggested at https://github.com/zcash/zcash/issues/1952#issuecomment-271128885 as this will avoid the rpc thread block.

> Adding this to zcash-cli is possible, effectively moving what appears to be a common use-case into the tool. The result is that zcash-cli will have to use the result from z_sendmany and start polling internally at some interval e.g. 1 second.

@daira let me know when you can if you agree with that approach to go over this.

**Comment by daira** [comment]
Closing as duplicate.
