### ISSUE TITLE
ZMQ alternative to z_listunspent

### ISSUE THREAD

**Issue by ch4ot1c** [zcash/zcash#3474]
Would a PR adding a ZMQ notification that deserializes (uses commitments/nullifiers/anchor) and exposes shielded transaction data, at a given z-address(es), be acceptable?

I read over https://github.com/zcash/zcash/blob/master/doc/zmq.md#block-and-transaction-broadcasting-with-zeromq, but am unsure whether a JSON-formatted shielded transaction would be appropriate outside the daemon. The only alternative I see, however, is to poll with repeated RPC `z_listunspent` calls.

Thank you

**Comment by ioptio** [comment]
We'll raise this in the zcashd team. Have you written the code already?

**Comment by ch4ot1c** [comment]
No, but I am up for the challenge.

**Comment by daira** [comment]
Do you mean a way of subscribing to all transactions that involve an address (or set of addresses)? That seems useful.

**Comment by ch4ot1c** [comment]
Yes, and z addresses in particular. I'll keep up with https://github.com/bitcoin/bitcoin/issues/13850 and see if I can work toward this

**Comment by ioptio** [comment]
Engineering is busy with Sapling but if you can elaborate on what you're trying to do (and be patient) then we can provide better feedback.

**Comment by ch4ot1c** [comment]
I'm trying to determine the contents of a shielded tx added to the mempool, e.g. arriving via the `rawtx` ZMQ event, if its destination belongs to our wallet. Is there an RPC for decrypting the `rawtx` for a shielded transaction, of course failing if it is not ours? Sorry if that is a dumb question.

In other words, trying to detect new shielding spends arriving at our wallet over ZMQ instead of `z_listreceivedbyaddress` x `z_listaddresses`.

**Comment by Eirik0** [comment]
@ch4ot1c Are you looking in to this?

Having tried something similar for the initial implementation of lightwalletd we eventually found that zmq was unreliable. We would sometimes miss blocks/transactions and end up in a state that was recoverable only by making rpc calls to zcashd. As a result we aren't really sure that we would recommend doing this anymore.

**Comment by ioptio** [comment]
Closing this but feel free to reopen if you have further comments.
