### ISSUE TITLE
compile error on master branch  

### ISSUE THREAD

**Issue by truelv** [zcash/zcash#3476]
1. version info : just the latest version , I just git pull at 10:30 on 2018-8-20.

this is the last commit on git log.
commit 20f87bc226ea27ec5023ab4a182f566a84f48d3e
Merge: d960b75 c9339bb
Author: Homu <sysadmin@z.cash>
Date:   Fri Aug 17 14:42:52 2018 -0700

    Auto merge of #3422 - bitcartel:3061_track_notes_based_on_3062, r=str4d
    
    Track Sapling notes and nullifiers in the wallet (in-memory only, no persistence to disk)
    
    Part of #3061.  Add in-memory tracking of Sapling notes and nullifiers to the wallet.

2. I compile on three computer , all of them have errors .  I only use ./zcutil/build.sh -j$(nproc) for compiling .

- one is :

make[1]: Entering directory '/home/wyh/gosrc/src/github.com/zcash/src'
make[2]: Entering directory '/home/wyh/gosrc/src/github.com/zcash/src'
  CXX      wallet/gtest/zcash_gtest-test_wallet_zkeys.o
Makefile:5249: recipe for target 'wallet/gtest/zcash_gtest-test_wallet_zkeys.o' failed
make[2]: *** [wallet/gtest/zcash_gtest-test_wallet_zkeys.o] Error 1

- the other is：

make  -C secp256k1 libsecp256k1.la
make[3]: Entering directory '/home/wyh/gosrc/src/github.com/zcash/src/secp256k1'
make[3]: Leaving directory '/home/wyh/gosrc/src/github.com/zcash/src/secp256k1'
ranlib libzcash.a
rm -f libbitcoin_zmq.a
ar cr libbitcoin_zmq.a zmq/libbitcoin_zmq_a-zmqabstractnotifier.o zmq/libbitcoin_zmq_a-zmqnotificationinterface.o zmq/libbitcoin_zmq_a-zmqpublishnotifier.o 
/home/wyh/gosrc/src/github.com/zcash/depends/x86_64-unknown-linux-gnu/share/../native/bin/ccache g++ -m64 -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I. -I./obj -pthread -I/home/wyh/gosrc/src/github.com/zcash/depends/x86_64-unknown-linux-gnu/share/../include -I./leveldb/include -I./leveldb/helpers/memenv -I/home/wyh/gosrc/src/github.com/zcash/depends/x86_64-unknown-linux-gnu/include -I/home/wyh/gosrc/src/github.com/zcash/depends/x86_64-unknown-linux-gnu/include -I./secp256k1/include -I./snark -I./snark/libsnark -I./univalue/include  -I/home/wyh/gosrc/src/github.com/zcash/depends/x86_64-unknown-linux-gnu/share/../include/  -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -DMULTICORE  -Wformat -Wformat-security -Wstack-protector -fstack-protector-all -Werror -fPIE -pipe -O1 -g -fopenmp -fwrapv -fno-strict-aliasing -Wno-builtin-declaration-mismatch -MT wallet/libbitcoin_wallet_a-rpcwallet.o -MD -MP -MF wallet/.deps/libbitcoin_wallet_a-rpcwallet.Tpo -c -o wallet/libbitcoin_wallet_a-rpcwallet.o `test -f 'wallet/rpcwallet.cpp' || echo './'`wallet/rpcwallet.cpp
Makefile:4038: recipe for target 'wallet/libbitcoin_wallet_a-rpcwallet.o' failed
make[2]: *** [wallet/libbitcoin_wallet_a-rpcwallet.o] 段错误 (core dumped)
make[2]: *** 正在等待未完成的任务....
ranlib libbitcoin_zmq.a
mv -f .deps/libbitcoin_server_a-main.Tpo .deps/libbitcoin_server_a-main.Po
make[2]: Leaving directory '/home/wyh/gosrc/src/github.com/zcash/src'
Makefile:5651: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/wyh/gosrc/src/github.com/zcash/src'
Makefile:627: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

- third one is:

Makefile:5669: recipe for target 'zcashd-bitcoind.o' failed
make[2]: *** [zcashd-bitcoind.o] Error 139
make[2]: *** 正在等待未完成的任务....
Makefile:3226: recipe for target 'libbitcoin_server_a-alert.o' failed
make[2]: *** [libbitcoin_server_a-alert.o] Error 139
/bin/bash: 行 1: 14416 段错误               (核心已转储) /home/wyh/gosrc/src/github.com/zcash.bak/depends/x86_64-unknown-linux-gnu/share/../native/bin/ccache g++ -m64 -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I. -I./obj -pthread -I/home/wyh/gosrc/src/github.com/zcash.bak/depends/x86_64-unknown-linux-gnu/share/../include -I./leveldb/include -I./leveldb/helpers/memenv -I/home/wyh/gosrc/src/github.com/zcash/depends/x86_64-unknown-linux-gnu/include -I/home/wyh/gosrc/src/github.com/zcash/depends/x86_64-unknown-linux-gnu/include -I./secp256k1/include -I./snark -I./snark/libsnark -I./univalue/include -I/home/wyh/gosrc/src/github.com/zcash/depends/x86_64-unknown-linux-gnu/include -pthread -I/home/wyh/gosrc/src/github.com/zcash/depends/x86_64-unknown-linux-gnu/include -I/home/wyh/gosrc/src/github.com/zcash.bak/depends/x86_64-unknown-linux-gnu/share/../include/ -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -DMULTICORE -Wformat -Wformat-security -Wstack-protector -fstack-protector-all -Werror -fPIE -pipe -O1 -g -fopenmp -fwrapv -fno-strict-aliasing -Wno-builtin-declaration-mismatch -MT libbitcoin_server_a-addrman.o -MD -MP -MF .deps/libbitcoin_server_a-addrman.Tpo -c -o libbitcoin_server_a-addrman.o `test -f 'addrman.cpp' || echo './'`addrman.cpp
Makefile:3212: recipe for target 'libbitcoin_server_a-addrman.o' failed
make[2]: *** [libbitcoin_server_a-addrman.o] Error 139
/bin/bash: 行 1: 14415 段错误               (核心已转储) /home/wyh/gosrc/src/github.com/zcash.bak/depends/x86_64-unknown-linux-gnu/share/../native/bin/ccache g++ -m64 -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I. -I./obj -pthread -I/home/wyh/gosrc/src/github.com/zcash.bak/depends/x86_64-unknown-linux-gnu/share/../include -I./leveldb/include -I./leveldb/helpers/memenv -I/home/wyh/gosrc/src/github.com/zcash/depends/x86_64-unknown-linux-gnu/include -I/home/wyh/gosrc/src/github.com/zcash/depends/x86_64-unknown-linux-gnu/include -I./secp256k1/include -I./snark -I./snark/libsnark -I./univalue/include -I/home/wyh/gosrc/src/github.com/zcash/depends/x86_64-unknown-linux-gnu/include -pthread -I/home/wyh/gosrc/src/github.com/zcash/depends/x86_64-unknown-linux-gnu/include -I/home/wyh/gosrc/src/github.com/zcash.bak/depends/x86_64-unknown-linux-gnu/share/../include/ -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -DMULTICORE -Wformat -Wformat-security -Wstack-protector -fstack-protector-all -Werror -fPIE -pipe -O1 -g -fopenmp -fwrapv -fno-strict-aliasing -Wno-builtin-declaration-mismatch -MT libbitcoin_server_a-sendalert.o -MD -MP -MF .deps/libbitcoin_server_a-sendalert.Tpo -c -o libbitcoin_server_a-sendalert.o `test -f 'sendalert.cpp' || echo './'`sendalert.cpp
Makefile:3198: recipe for target 'libbitcoin_server_a-sendalert.o' failed
make[2]: *** [libbitcoin_server_a-sendalert.o] Error 139
make[2]: Leaving directory '/home/wyh/gosrc/src/github.com/zcash.bak/src'
Makefile:5721: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/wyh/gosrc/src/github.com/zcash.bak/src'
Makefile:627: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

Thx a lot .

**Comment by rex4539** [comment]
Do you see the same if you compile with `./zcutil/build.sh` without `-j$(nproc)`?

**Comment by mdr0id** [comment]
Also, can you please provide the amount of RAM on each platform you built on?

**Comment by truelv** [comment]
I need to update this problem . I update to the latest version and tried several times. 

Zcash on one of my computers can be compiled correctly though I haven't change anything and just use ./zcutil/build.sh -j4 or make .  this one have only one RAM of 3G. Ubuntu version is Linux wyh-Z97X-UD3H 4.15.0-29-generic #31~16.04.1-Ubuntu SMP Wed Jul 18 08:54:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux.    gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 


Zcash on the other one can't be compiled corretly even update to today version. I use ./zcutil/build.sh without -j$(nproc) and see nothing changes. What I only do is tye in git pull and ./zcutil/build.sh . gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10) and Linux wyh-B85M-D3V 4.15.0-29-generic #31~16.04.1-Ubuntu SMP Wed Jul 18 08:54:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux.one RAM and it's size is 1673248 kB.  The compile error codes is as follow :
Makefile:3198: recipe for target 'libbitcoin_server_a-sendalert.o' failed
make[2]: *** [libbitcoin_server_a-sendalert.o] 段错误 (core dumped)
make[2]: Leaving directory '/home/wyh/gosrc/src/github.com/zcash/src'
Makefile:5721: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/wyh/gosrc/src/github.com/zcash/src'
Makefile:627: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
wyh@wyh-B85M-D3V:~/gosrc/src/github.com/zcash$ git log
commit 622751da12790eb83432db9b26bca7129e856026
Merge: 20f87bc c0aa34a
Author: Homu <sysadmin@z.cash>
Date:   Mon Aug 20 09:48:51 2018 -0700

    Auto merge of #3444 - LarryRuane:2982-mininode-version, r=str4d
    
    generalize mininode.py protocol versioning
    
    Fixes #2982 -- replace `overwintered` boolean argument to NodeConn constructor with a protocol version integer, so that adding Sapling (and beyond) will be easier.


third of my computer ,Ubuntu version: Linux wyh-Z97X-UD3H 4.15.0-29-generic #31~16.04.1-Ubuntu SMP Wed Jul 18 08:54:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux    gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10),one 3G RAM , I also just do git pull and ./zcutil/buid.sh without -j$(nproc) then errors come,here is the error code:

+ make V=1
Making all in src
make[1]: Entering directory '/home/wyh/gosrc/src/github.com/zcash.bak/src'
make[2]: Entering directory '/home/wyh/gosrc/src/github.com/zcash.bak/src'
/home/wyh/gosrc/src/github.com/zcash.bak/depends/x86_64-unknown-linux-gnu/share/../native/bin/ccache g++ -m64 -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I. -I./obj  -pthread -I/home/wyh/gosrc/src/github.com/zcash.bak/depends/x86_64-unknown-linux-gnu/share/../include -I./leveldb/include -I./leveldb/helpers/memenv -I/home/wyh/gosrc/src/github.com/zcash/depends/x86_64-unknown-linux-gnu/include -I/home/wyh/gosrc/src/github.com/zcash/depends/x86_64-unknown-linux-gnu/include -I./secp256k1/include -I./snark -I./snark/libsnark -I./univalue/include -I/home/wyh/gosrc/src/github.com/zcash.bak/depends/x86_64-unknown-linux-gnu/share/../include/  -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -DMULTICORE  -Wformat -Wformat-security -Wstack-protector -fstack-protector-all -Werror -fPIE -pipe -O1 -g -fopenmp -fwrapv -fno-strict-aliasing -Wno-builtin-declaration-mismatch -MT zcashd-bitcoind.o -MD -MP -MF .deps/zcashd-bitcoind.Tpo -c -o zcashd-bitcoind.o `test -f 'bitcoind.cpp' || echo './'`bitcoind.cpp
Makefile:5669: recipe for target 'zcashd-bitcoind.o' failed
make[2]: *** [zcashd-bitcoind.o] 段错误 (core dumped)
make[2]: Leaving directory '/home/wyh/gosrc/src/github.com/zcash.bak/src'
Makefile:5721: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/wyh/gosrc/src/github.com/zcash.bak/src'
Makefile:627: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
wyh@wyh-Z97X-UD3H:~/gosrc/src/github.com/zcash.bak$ git log
commit 622751da12790eb83432db9b26bca7129e856026
Merge: 20f87bc c0aa34a
Author: Homu <sysadmin@z.cash>
Date:   Mon Aug 20 09:48:51 2018 -0700

    Auto merge of #3444 - LarryRuane:2982-mininode-version, r=str4d
    
    generalize mininode.py protocol versioning
    
    Fixes #2982 -- replace `overwintered` boolean argument to NodeConn constructor with a protocol version integer, so that adding Sapling (and beyond) will be easier.

Thx for two of you.

**Comment by mdr0id** [comment]
@truelv It has been noticed that there exists a couple issues when building with systems that have less than 5GB. If it is possible to use a system with at least 5GB, that should resolve the above issues?

I did have success on 3.5GB to 4.5GB systems, but successful builds were not consistent until the 5GB mark.

Please let us know if this still does not resolve your problem.

Also, we have additional documentation, once the build succeeds: https://zcash.readthedocs.io/en/latest/

**Comment by truelv** [comment]
Ok,I think it's a good explaination . If the problem comes from the size of memory then I know how to figure it. Thx a lot@mdr0id.

I go to the fortum https://chat.zcashcommunity.com/channel/zcash-dev before and ask a question about Equihash but have no responce ...
