### ISSUE TITLE
[ZIP 205] Add ZIP for Sapling

### ISSUE THREAD

**Issue by daira** [zcash/zcash#3480]
This needs the consensus branch ID, activation height, etc. It can be simpler than the Overwinter ZIPs because the protocol spec defines most of Sapling.

**Comment by bitcartel** [comment]
Should this include v4 transaction format, or should that be a separate ZIP?

**Comment by str4d** [comment]
The protocol spec defines the format (section 7.1), so it's probably fine to just reference that.
