### ISSUE TITLE
Simplify Sprout class names to make them consistent with Sapling names

### ISSUE THREAD

**Issue by daira** [zcash/zcash#3484]
* [x] ``CSproutNotePlaintextEntry`` -> ``SproutNoteEntry`` (to match ``SaplingNoteEntry``)
* [x] ``CUnspentSproutNotePlaintextEntry`` ~-> ``UnspentSproutNoteEntry`` (to match ``UnspentSaplingNoteEntry``)~ removed

Please add any other examples.

**Comment by daira** [comment]
This is similar to, but distinct from #3446. They could be done at the same time though.

**Comment by daira** [comment]
Another similar renaming ticket: #3188

**Comment by rex4539** [comment]
Looks like this has been addressed?

**Comment by daira** [comment]
#4036 fixed the first part of this (`CSproutNotePlaintextEntry` -> `SproutNoteEntry`). #3581 removed `CUnspentSproutNotePlaintextEntry`.

**Comment by daira** [comment]
Aside: [how to search for deleted code in git](https://stackoverflow.com/a/24011402/393146).
