### ISSUE TITLE
Make NU peer management logic in ProcessMessage() upgrade-agnostic

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#3487]
**Narrator**: _They never did._
> @ebfull [said](https://github.com/zcash/zcash/pull/2919#issuecomment-367540251):
> > I just wish this PR was more agnostic to the upgrade. As it stands, it's too overwinter-specific.
>
> @str4d [said](https://github.com/zcash/zcash/pull/2919#issuecomment-367540683):
> > We can always clean this up in 1.1.0 to be more generic.

We forgot to change this in 2.0.0. We should make this generic so that the NU levers are all in one place, and thus much less likely to be overlooked. Then at least 2.0.1 peers will benefit from the peer management strategy.

**Comment by daira** [comment]
#3338 was a duplicate.

**Comment by str4d** [comment]
It covered the logic in `net.cpp`, not `ProcessMessages()`, but I agree with folding it into this issue.
