### ISSUE TITLE
Build opensuse problems with db

### ISSUE THREAD

**Issue by red0bear** [zcash/zcash#3493]
i have db berkley installed but it fails to find it. Im using opensuse leap 15. 

checking for Berkeley DB C++ headers... no
configure: error: libdb_cxx headers missing, Bitcoin Core requires this library for wallet functionality (--disable-wallet to disable wallet functionality)

**Comment by ioptio** [comment]
Have you followed the user guide? And it's worth noting that opensuse is not officially supported.
https://zcash.readthedocs.io/en/latest/rtd_pages/user_guide.html

**Comment by red0bear** [comment]
i see more problems with dependecy than distro. do you think in near future make portable to cmake ?

**Comment by ioptio** [comment]
We don't anticipate any near future work on this. You might want to add more context to this ticket: https://github.com/zcash/zcash/issues/1993

**Comment by ioptio** [comment]
Since we don't have plans to support opensuse I'll close this ticket but feel free to ask for community support: https://chat.zcashcommunity.com
