### ISSUE TITLE
Can anyone give me a little test coin?

### ISSUE THREAD

**Issue by ztlovemst11** [zcash/zcash#3497]
Although I got some test coins on [,](https://faucet.testnet.z.cash/), because [it](https://explorer.testnet.z.cash) doesn't work, I found another test network exploer [](https://chain.so/testnet/zcash) , but I didn't receive the test coins at the address, obviously they are not the same network.

I hope that someone who is favored by God can give me some test coins.
very thanks

**Comment by ioptio** [comment]
Thanks @garethtdavies 

Closing this.

**Comment by AllenYaoya** [comment]
> If you are running v2.0.0 (download from https://z.cash/download.html) then simply put an address into https://faucet.testnet.z.cash/ and it'll work. You'll need to let the blockchain fully sync before any balance would be displayed.

Hi,

I'm running v2.0.0 testnet and I used https://faucet.testnet.z.cash/ to fetch some test coins. It shows successful in the webpage. But in fact I can receive no coins.

If convenient, could you send me some test coins directly? My address is 

tmMFDnyLnBHgknjkgYNZwbqQ9CxgoDwju9H

Thanks so much!

**Comment by ztlovemst11** [comment]
@garethtdavies Can you give me some zec insight_api? I want to use it to query some data on my website.

**Comment by garethtdavies** [comment]
@ztlovemst11 just stick your address in https://faucet.testnet.z.cash/  and it'll work but you must be running v2.0.1.
