### ISSUE TITLE
sending a raw transaction shows  tx-overwinter-active error

### ISSUE THREAD

**Issue by alishaagupta** [zcash/zcash#3498]
This issue tracker is only for technical issues related to zcashd.

General Zcash questions and/or support requests and are best directed to the [Zcash Forums](https://forum.z.cash) or [Community Rocket.Chat](https://chat.zcashcommunity.com).

For reporting security vulnerabilities or for sensitive discussions with our security team, please contact [security@z.cash](mailto:security@z.cash). You can use the [GPG key](https://z.cash/gpg-pubkeys/security.asc) (fingerprint: `AF85 0445 546C 18B7 86F9  2C62 88FB 8B86 D8B5 A68C`) to send an encrypted message. The key and fingerprint are duplicated on our [Public Keys page](https://z.cash/support/pubkeys.html).

### Describe the issue
Please provide a general summary of the issue you're experiencing

#### If so, please list the steps to reproduce below:
1. Create a new signed transaction using zcash-bitcore-lib.Transaction() function
2. This gives the transaction hash 
3. use sendrawtransaction in zcash-cli with the obtained hash

I did use -
transaction.version = 3
transaction.fOverwintered = true
transaction.nVersionGroupId = 0x03C48270
transaction.nExpiryHeight = 384561

### Expected behaviour
Tell us what should happen
Transaction id should be the output of cli command used
### Actual behaviour + errors
Tell us what happens instead including any noticable error output (any messages displayed on-screen when e.g. a crash occurred)
tx-overwinter-active error 

### The version of Zcash you were using:
Run `zcashd --version` to find out
v2.0.0
### Machine specs:
- OS name + version: ubuntu 18.04
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):
- Linux kernel version (uname -a): 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Compiler version (gcc -version):

### Any extra information that might be useful in the debugging process.
This includes the relevant contents of `~/.zcash/debug.log`. You can paste raw text, attach the file directly in the issue or link to the text via a pastebin type site.
Please also include any non-standard things you did during compilation (extra flags, dependency version changes etc.) if applicable.

### Do you have a backup of `~/.zcash` directory and/or take a VM snapshot?
- Backing up / making a copy of the `~/.zcash` directory might help make the problem reproducible. Please redact appropriately.
- Taking a VM snapshot is really helpful for interactively testing fixes

**Comment by ioptio** [comment]
What library are you using? Looks like javascript...

**Comment by ioptio** [comment]
Closing this due to lack of response. Feel free to reopen if you have a response or more questions. You can also look for community support: https://chat.zcashcommunity.com

**Comment by LitecoinZ** [comment]
Hi @ioptio ,
I think he is using the https://github.com/zcash-hackworks/bitcore-lib-zcash

Now V3 transaction works fine but, V4 transactions are still not working due a bad signature.Can you please help me to fix it adding a full sapling support to https://github.com/zcash-hackworks/bitcore-lib-zcash ?

Thanks
Mark
