### ISSUE TITLE
Sapling shielding: decide what "from" ovk should be for transparent input being shielded

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#3506]
> It needs to be done as part of 2.0.1, as otherwise it is just using the empty FVK's ovk, which IIRC is the all-zeroes byte string. @daira suggested that we use the FVK of one of the recipients, but that only works if one of the recipients is us, which is not guaranteed. I'm wondering whether we should define a way to derive a synthetic ovk from a transparent spending key, so that the semantics (from corresponds to sender's address) are maintained?

https://github.com/zcash/zcash/pull/3489/commits/e54c4d2ca120c6bbc632a95542056d3587632fee#r213943577

**Comment by daira** [comment]
@bitcartel wrote:
> @daira suggested that we use the FVK of one of the recipients. [...]

Wait when did I suggest that? I don't remember doing so. I recommend using the FVK of the ZIP 32 account that sent the transfer.

**Comment by str4d** [comment]
@daira if the transaction is from a t-addr to a Sapling address, there isn't a ZIP 32 account that sent the transfer.

Now, we *could* just say "use the FVK of the first account in the wallet's ZIP 32 hierarchy, even if the user has not generated any Sapling addresses before". That technically works (as from 2.0.1 all wallets will have HDSeeds), but isn't as clean an abstraction. However, it's an improvement over the current setup (using the all-zeroes FVK) which makes the recipient details decryptable by everyone.

**Comment by ebfull** [comment]
I think we need a stop-gap and the only thing that seems acceptable to me is to randomly sample the key (emphemerally) instead of using a null key. This fixes the issue and doesn't solidify a solution for the future (which should be deliberately specified) at little cost. We shouldn't rush into a design decision just before a release.

**Comment by bitcartel** [comment]
@arielgabizon Nice idea, but if there are many taddr inputs, which private key do you choose?

**Comment by arielgabizon** [comment]
Don't know..you could just use the first, it's not too clean maybe..but actually there's the same issue with multiple shielded inputs and outputs, what input do we choose the ovk from?
