### ISSUE TITLE
Confusing error message w/ Debian package if you didn't re-run fetch-params for the sapling upgrade

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#3508]
In response to a `getwalletinfo` my Zcashd (installed/upgraded using the official Debian repo) was giving me this error message:

```
error code: -28
error message:
Loading block index...
```

Restarting/rebooting did not help, and in `debug.log` I saw that it was missing the sapling parameters...

```
Error: Cannot find the Zcash network parameters in the following directory: [redacted]
```

Re-running `zcash-fetch-params` fixed the problem. I suggest two improvements:

1. `zcashd` should give a more informative error message when the parameters are missing (so that the problem is apparent from the result of running `getwalletinfo`, and you don't have to find out by reading the log).
2. When a network upgrade happens and the parameters change, the debian package installer and/or zcashd itself should automatically upgrade the parameters to prevent the node from breaking until someone realizes they have to run `zcash-fetch-params`.

**Comment by ianamunoz** [comment]
The `debug.log` or the systemd logs give a little better information but it takes some intuition to check or know where to look if your daemon is not running as an interactive process.
```
systemctl status zcashd
● zcashd.service - Zcash daemon
   Loaded: loaded (/etc/systemd/system/zcashd.service; enabled)
   Active: active (running)
 Main PID: 16871 (zcashd)
   CGroup: /system.slice/zcashd.service
           └─16871 /usr/bin/zcashd

systemd[1]: Starting Zcash daemon...
systemd[1]: Started Zcash daemon.
zcashd[16871]: Error: Cannot find the Zcash network parameters in the following directory:
zcashd[16871]: "/home/user/.zcash-params"
zcashd[16871]: Please run 'zcash-fetch-params' or './zcutil/fetch-params.sh' and then restart.
```

**Comment by daira** [comment]
Given that this ticket is not in the 2.0.1 milestone, we need to address it in the release notes and release blog post.

**Comment by Eirik0** [comment]
Because it has been so long since Sapling upgrade we are considering this ticket obsolete. Please reopen if this is not the case.
