### ISSUE TITLE
Add newly-discovered Sapling addresses to wallet when decrypting notes

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#3511]
If we successfully decrypt a Sapling note with an IVK the wallet knows about, but it *doesn't* know about the corresponding address, then that means funds were sent to a diversified address generated outside the wallet. We need to add it to the wallet's internal `address -> ivk` mapping, so that we can then use that address in e.g. `z_sendmany`.

**Comment by str4d** [comment]
Could happen in [`FindMySaplingNotes`](https://github.com/zcash/zcash/blob/master/src/wallet/wallet.cpp#L1617-L1652) somewhere? Or maybe in `AddToWallet`.

**Comment by arielgabizon** [comment]
Hmm.. this could be view is an odd attack on HD wallet, where someone forces you to use a diversifier outside the ones generated by the wallet.
