### ISSUE TITLE
Link to CI server view on website

### ISSUE THREAD

**Issue by mms710** [zcash/zcash#3514]
This is referencing https://github.com/Electric-Coin-Company/z.cash/issues/780. We got a request to add the Homu and CI links, below, to either the website or Read the Docs.
CI: https://ci.z.cash
Homu: https://ci.z.cash/queue/zcash

**Comment by ioptio** [comment]
https://gitlab.com/zcash-docs/zcash-docs/merge_requests/81 will satisfy this

**Comment by ioptio** [comment]
This is done per above merge request in readthedocs
