### ISSUE TITLE
Sapling & Overwinter compatible pool software and miners

### ISSUE THREAD

**Issue by oliverw** [zcash/zcash#3519]
I'm currently trying to add support for Overwinter & Sapling to [MiningCore](https://github.com/coinfoundry/miningcore/blob/dev/src/MiningCore/Blockchain/ZCash/ZCashJob.cs) (pool engine).

I'm testing against testnet (Zcash Daemon version v2.0.0). So far I haven't been able to mine a single testnet block due to various errors (mostly involving invalid solutions - StepRows).

Is there any known CPU or GPU Miner that's compatible with Overwinter & Sapling and/or a reference implementation for both features and node-stratum-pool (z-nomp)?

It's hard to get things working if you are fighting on multiple fronts :)

**Comment by ioptio** [comment]
It would be helpful to know more about the errors to help diagnose.

**Comment by ioptio** [comment]
There is a change in the block header for Zcash for the Sapling upgrade that you should be aware of.

Specifically the hashReserved field currently in the header will be replaced with the hashFinalSaplingRoot field which is detailed in section 7.5 of the specification (linked below). Our engineers have alerted me that this will impact the Stratum protocol used by mining pools and perhaps other implementations. Please reach out if you have any additional questions.https://github.com/zcash/zips/blob/master/protocol/protocol.pdf

**Comment by oliverw** [comment]
Thanks. I've figured it out a couple days ago.
