### ISSUE TITLE
RPCs not supporting sapling addresses should not terminate when presented with one

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#3533]
Reminder to fix for v2.0.1:
https://github.com/zcash/zcash/pull/3518/files#diff-12d992d118addcbb5a6a0f616b845434L78
```
        // TODO: Add Sapling support. For now, ensure we can freely convert.
        assert(boost::get<libzcash::SproutPaymentAddress>(&address) != nullptr);
```
This should be replaced with a `throw JSONRPCError` so that if a user passes in a sapling address to an rpc which does not support it yet, the application will return an error, instead of throwing an assert and terminating.

**Comment by str4d** [comment]
Closed by #3536.
