### ISSUE TITLE
Patch our `libzerocash` to separate install of libzerocash.a and test binaries

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#354]
We currently needlessly build the libzerocash test binaries. The build on travis is currently broken because the `-lrt` flag needs to be passed for the tests, this is done conditionally, so we're forced to either do something fancy in the `.travis.yml` to tell it to set `LINK_RT=1` or disable building the tests, or always enable `LINK_RT=1` even for non-travis builds.

**Comment by daira** [comment]
This ticket is obsolete; Buildbot does not have this issue.
