### ISSUE TITLE
Network Solution Rate 0 sol/s

### ISSUE THREAD

**Issue by potadibyo** [zcash/zcash#3543]
i write in conf file
showmetrics=1
addnode=someipaddress
rpcuser=someuser
rpcpassword=my-password
gen=1
genproclimit=-1
equihashsolver=tromp
maxconnections=32
rpcport=6252
rpcbind=my-server:6225
but it shows in time of run my newly created cryptocurrency
vmi153581:~/ws/moonroomcash# ./src/moonroomcashd

Thank you for running a Moonroomcash node!
You're helping to strengthen the network and contributing to a social good :)

In order to ensure you are adequately protecting your privacy when using
Moonroomcash,
Block height | 0
Connections | 2
Network solution rate | 0 Sol/s
Local solution rate | 1.1022 Sol/s

You are mining with the tromp solver on 2 threads.

Since starting this node 9 minutes, 20 seconds ago:

    You have validated no transactions.
    You have completed 334 Equihash solver runs.

members advice indeed,

Thanks,
Dibyajit

**Comment by ioptio** [comment]
Have you tried asking the Moonroomcash developers on their repository? You can also join the zcash community chat to ask others for support: https://chat.zcashcommunity.com

Since this is not about Zcash, it falls out of the scope for our support team.
