### ISSUE TITLE
zcash_gtest crashes on `make check`

### ISSUE THREAD

**Issue by rex4539** [zcash/zcash#3545]
### Describe the issue
When running `make check` zcash_gtest crashes several times.

### Can you reliably reproduce the issue?
Reproducibility: always

#### If so, please list the steps to reproduce below:
1. `make check`

### Expected behaviour
zcash_gtest does not crash.

### Actual behaviour + errors
zcash_gtest crashes 5 times in 3 functions.

CChainParams::GetFoundersRewardAddressAtHeight(int) const + 189
CChainParams::GetFoundersRewardScriptAtHeight(int) const + 409 (chainparams.cpp:534)
CWallet::DecrementNoteWitnesses(CBlockIndex const*) + 314 (wallet.cpp:1052)

[zcash-gtest_2018-09-27-093539_MacBook-Pro-2011.log](https://github.com/zcash/zcash/files/2422840/zcash-gtest_2018-09-27-093539_MacBook-Pro-2011.log)
[zcash-gtest_2018-09-27-093539-1_MacBook-Pro-2011.log](https://github.com/zcash/zcash/files/2422843/zcash-gtest_2018-09-27-093539-1_MacBook-Pro-2011.log)
[zcash-gtest_2018-09-27-093539-2_MacBook-Pro-2011.log](https://github.com/zcash/zcash/files/2422845/zcash-gtest_2018-09-27-093539-2_MacBook-Pro-2011.log)
[zcash-gtest_2018-09-27-093539-3_MacBook-Pro-2011.log](https://github.com/zcash/zcash/files/2422846/zcash-gtest_2018-09-27-093539-3_MacBook-Pro-2011.log)
[zcash-gtest_2018-09-27-095144_MacBook-Pro-2011.log](https://github.com/zcash/zcash/files/2422848/zcash-gtest_2018-09-27-095144_MacBook-Pro-2011.log)

### The version of Zcash you were using:
v2.0.0-e6f6c5d08

### Machine specs:
- OS name + version: macOS 10.13.6 (17G65)
- CPU: Intel Core i7 2,2 GHz
- RAM: 8GB
- Disk size: 250,14 GB
- Disk Type (HD/SDD): SSD
- Linux kernel version (uname -a): Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
- Compiler version (gcc -version): Apple LLVM version 10.0.0 (clang-1000.11.45.5)

**Comment by mdr0id** [comment]
Thank you for the information. I'm not sure this flow of Mac, per make target, has been exercised.  I will take a look at this soon, since I am fixing other portions of the test-suite on Mac as we speak.

**Comment by ioptio** [comment]
Just an update: we know about this issue and have plans to fix it.

**Comment by daira** [comment]
Possibly related to #4389?

**Comment by daira** [comment]
I think this is fixed.
