### ISSUE TITLE
Rename HaveJoinSplitRequirements

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#3550]
Checking whether or not a Sapling note has already been spent was added to the function HaveJoinSplitRequirements().  Since the function now checks both Sprout joinsplits and Sapling spends, the function should be renamed e.g. HaveShieldedRequirements() and the error message updated too.
```
        // are the joinsplit's requirements met?
        if (!view.HaveJoinSplitRequirements(tx))
            return state.Invalid(error("AcceptToMemoryPool: joinsplit requirements not met"),
                                 REJECT_DUPLICATE, "bad-txns-joinsplit-requirements-not-met");
```

**Comment by daira** [comment]
The function was renamed in #3631. The error message is fixed by #4054.
