### ISSUE TITLE
Unable to find docs and specs for basic Zcash functionalities.

### ISSUE THREAD

**Issue by eddywm** [zcash/zcash#3551]
I'm trying to implement Zcash in a wallet and I'm having a problem of lacking documentation and clear straightforward specs.

 1. The format of` T-Addresses` ? `Length` ? `Encoding` ? How are they derived from public keys, which cryptographic functions are used ? 

 2. The `format` of a Zcash transaction and it's structure, how are inputs and outputs formatted inside ?
   
3. How are Zcash transactions `signed` ? which functions, `curves` are used ?

4. How are private keys created ? Is there a standard on that ? How are public key derived from private keys, functions, elliptic curves used ?

For Bitcoin, almost all these info are available in the developer guide, but didn't find anything straight forward in the Zcash docs, guide, pdfs ,...

**Comment by daira** [comment]
This kind of information is all in the protocol spec: https://github.com/zcash/zips/blob/master/protocol/sapling.pdf

**Comment by eddywm** [comment]
I have already seen this doc, unfortunately I didn't really get anything from it.
I just couldn't find what I was looking for.

I was expecting some straight forward specs, like for instance in the Bitcoin Guide,

`Address = RIPMD160(SHA256(PUBKEY)) `// This is pretty direct and I can make an implementation right away.

But in that document nothing is like that.

**Comment by daira** [comment]
That's in section 5.6.1.

**Comment by ioptio** [comment]
We'll look at narrowing down various aspects of the spec to be more accessible in the documentation.

**Comment by ioptio** [comment]
Replacing the tracking of this with: https://gitlab.com/zcash-docs/zcash-docs/issues/43
