### ISSUE TITLE
Update boost tests where necessary for any Sapling changes to RPC parameters

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#3563]
For example:

> In regards to BOOST_AUTO_TEST_CASE(rpc_z_listunspent_parameters), the parameters have not changed. We could add some lines to get a new sapling address and then test that we do not throw when we pass that in,

via https://github.com/zcash/zcash/pull/3510#issuecomment-426704906

**Comment by Eirik0** [comment]
Timing out on this ticket.
