### ISSUE TITLE
Test links on speed.z.cash/about are broken

### ISSUE THREAD

**Issue by rbkhmrcr** [zcash/zcash#3570]
### Describe the issue

If you go to https://speed.z.cash/about/ and click through the 'here' and 'here' in:
"About the benchmarks
The code can be found here and here."
You get links (https://github.com/zcash/zcash/blob/zc.v0.11.2.latest/qa/zcash/performance-measurements.sh and https://github.com/zcash/zcash/blob/zc.v0.11.2.latest/src/zcbenchmarks.cpp) that 404. The working links (assuming this is the same test code!) are https://github.com/zcash/zcash/blob/master/qa/zcash/performance-measurements.sh and https://github.com/zcash/zcash/blob/master/src/zcbenchmarks.cpp which can be found pretty straightforwardly, but originally I was like 'oh no these must be internal i'm dooomed' so opening an issue because idk how to fix the links myself, sorry :)

**Comment by mms710** [comment]
Internal ticket to track this: https://gitlab.com/Electric-Coin-Company/infrastructure/issues/261

**Comment by daira** [comment]
This is obsolete.
