### ISSUE TITLE
LoadSaplingZKeyMetadata etc. shouldn't return a bool if they can never fail

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#3571]
https://github.com/zcash/zcash/pull/3517#discussion_r223424630

**Comment by Eirik0** [comment]
IMO it would be sufficient to just remove the assertion. If there is an easy way to verify the input data then we may as well add it, but, without looking, it's likely that the rest of the test depends on this working correctly, so shouldn't really be necessary.
Also, if this is always returning true then we aren't really asserting anything interesting, so we don't loose anything by removing the assertion.

**Comment by mdr0id** [comment]
@zkbot r+
