### ISSUE TITLE
Rename all gtest test case names and test names to use CamelCase

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#3575]
https://github.com/google/googletest/blob/master/googletest/docs/faq.md#why-should-test-case-names-and-test-names-not-contain-underscore

**Comment by avnish98** [comment]
@str4d I would like to work on this one

**Comment by str4d** [comment]
@avnish98 go ahead! 😃

**Comment by avnish98** [comment]
@str4d Thanks, I cannot find zcash-gtest file, am I looking for wrong file? can you tell me where should I change?

**Comment by str4d** [comment]
The relevant files are in `src/gtest` and `src/wallet/gtest`. Any `TEST(foo_test_case, bar_test)` line in any file in those folders should be rewritten as `TEST(FooTestCase, BarTest)`.

**Comment by avnish98** [comment]
@str4d Thanks

**Comment by Eirik0** [comment]
Here is the PR for this https://github.com/zcash/zcash/pull/3583

**Comment by rex4539** [comment]
By the way, there is a duplicate issue https://github.com/zcash/zcash/issues/1324 that can be closed.
