### ISSUE TITLE
TransactionBuilder should prevent adding Sapling spends and outputs if the underlying transaction doesn't support them

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#3597]
This is the root cause of #3595. The transaction builder constructs the transaction as if the Sapling inputs, outputs, and `valueBalance` are there, but because the serialization code ignores them, the signatures and sending end up excluding them. If the `valueBalance` is sufficiently-positive (i.e. the transaction is relying on Sapling inputs), the overall fee of the without-Sapling transaction would be negative and rejected. If it is only a small positive or is negative (i.e. the transaction is spending to Sapling addresses), the fee ends up much larger (and the Sapling outputs go to the miner).

The solution is to check the transaction version when calling `TransactionBuilder::AddSaplingSpend` and `TransactionBuilder::AddSaplingOutput`, and returning `false` if it has been called incorrectly.

**Comment by bitcartel** [comment]
There might also be unexpected code paths that don't use the transaction builder but still result in a v3 transaction being created by the async operation.

**Comment by bitcartel** [comment]
I think a sanity check at the end of the creation process would help e.g. assert(minerfeeparameter == transaction.minerfee)
