### ISSUE TITLE
Zcashd build fails on macOS 10.14 (Mojave)

### ISSUE THREAD

**Issue by garethtdavies** [zcash/zcash#3603]
### Describe the issue
During a build of zcashd errors such as the below are encountered and the build fails.

```
In file included from libs/thread/src/pthread/thread.cpp:9:
In file included from ./boost/thread/detail/config.hpp:11:
In file included from ./boost/config.hpp:57:
In file included from ./boost/config/platform/macos.hpp:28:
./boost/config/detail/posix_features.hpp:18:15: fatal error: 'unistd.h' file not found
#     include <unistd.h>
              ^~~~~~~~~~
```

### Can you reliably reproduce the issue?
Yes. Only on 10.14 is this an issue. See the related Bitcoin discussion here: https://github.com/bitcoin/bitcoin/issues/14327

### The version of Zcash you were using:
Latest on master (#3602 )

### Any extra information that might be useful in the debugging process.
As per the discussion on the Bitcoin thread running `open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg` fixes the issue and it builds correctly. See also  https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes.

**Comment by nuttycom** [comment]
This appears to have been resolved by xcode updates some time in the past few years.
