### ISSUE TITLE
Warn user about unrecognized settings in zcash.conf

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#3609]
You can add...

```
unrecognizedoptionjsdklafjlsakd=askdlfjalskdfassf
```

...to `zcash.conf` and there is no warning in any log or UI output. This means that if someone makes a typo in the name of a setting that's really important (e.g. password-protecting the RPC), there is no warning. Ideally zcashd should refuse to start if it doesn't fully comprehend what's in `zcash.conf`.

**Comment by daira** [comment]
Duplicate of #2284.
