### ISSUE TITLE
z_listunspent help incorrect for "spendable" indication

### ISSUE THREAD

**Issue by LarryRuane** [zcash/zcash#3610]
Running `zcash-cli help z_listunspent` includes this:
```
"spendable" : true|false  (boolean) true if note can be spent by wallet, false if note has zero confirmations, false if address is watchonly
```
The part about zero confirmations is incorrect and should be removed. `spendable` will be `true` even if the note has zero confirmations; it's an indication only that the wallet possesses the spending key. (The rpc tests check this.)

The transparent-address version of this RPC, `listunspent` does correctly describe this result:
```
"spendable" : xxx         (bool) Whether we have the private keys to spend this output
```
(This message is otherwise arguably inferior to that of `z_listunspent`, but it matches current bitcoin.)

**Comment by garethtdavies** [comment]
Shouldn't it actually be `false` though for zero confirmations and the description is describing the intended behaviour? It seems confusing to me at least to have `"spendable": true` and it's not spendable...

**Comment by LarryRuane** [comment]
@garethtdavies, I thought so too at first -- you may be right! My uncertainty is why I made a ticket for this instead of going directly to a PR. What do you think about this description of bitcoin's `listunspent`: 

> Set to true if the private key or keys needed to spend this output are part of the wallet. Set to false if not (such as for watch-only addresses)

This is from https://bitcoin.org/en/developer-reference#listunspent

**Comment by garethtdavies** [comment]
That description seems spot on for Bitcoin. Isn't the key difference here in Bitcoin you can spend an unconfirmed UTXO whereas in Zcash you can't do the same with a note? So if in Bitcoin you have the private key you can always spend a UTXO? I don't think it's a huge deal, just obviously could be confusing, something like `has_key_in_wallet` (that's terrible but you get my point) would have been a better choice.

I personally like spendable being true in Zcash to act as the description currently states i.e. it has at least one confirmation and it's in the wallet. Given it's always been this way though probably just fixing up the help message is the better solution as you originally proposed 😄

**Comment by LarryRuane** [comment]
Good point, you're right about that difference between Bitcoin UTXOs and Zcash notes. I agree it's confusing that this result is called `spendable` since it may not be!

I'm pretty sure changing the behavior of `spendable` would be highly undesirable, as users are likely depending on its current implementation. Therefore I think fixing the help is the right thing to do. We could add a new result boolean as you suggest, but the output also includes  the number of confirmations so with a little logic, the caller can determine if the note is really spendable (`spendable && confirmations > 0`).

**Comment by garethtdavies** [comment]
Agreed, it's pretty trivial to handle the 0 conf case and making the help clearer would probably clear most confusion. I think having `spendable` and `is_it_really_spendable` might be overkill 😆

**Comment by garethtdavies** [comment]
As it's the same RPC method, when tidying this up is there any reason in the example why `jsindex` doesn't have (sprout) next to it as similarly to `jsoutindex` it's only present for Sprout txs?

**Comment by daira** [comment]
@garethtdavies: no reason.

**Comment by daira** [comment]
After #1614 is implemented, notes will only be spendable after 10 confirmations. That makes the difference between "spending key is in the wallet" and "spendable right now" somewhat more acute.
