### ISSUE TITLE
transaction broadcast error

### ISSUE THREAD

**Issue by waliguder** [zcash/zcash#3614]
An error occured:
16: bad-sapling-tx-version-group-id. Code:-26

**Comment by ztlovemst11** [comment]
use lib QuoineFinancial/bitcore-lib-zcash

**Comment by ioptio** [comment]
Sorry we missed this issue. Can you clarify whether you fixed your fork to work or are still having issues with the original error?

**Comment by mdr0id** [comment]
Closed due to response period . Please re open if issue still exists.
