### ISSUE TITLE
Document in release notes the fix for the apt-get upgrade problem

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#3616]
From:

https://github.com/zcash/zcash/issues/3612

> Err https://apt.z.cash jessie Release.gpg
The following signatures were invalid: EXPKEYSIG 63C4A2169C1B2FA2 Zcash Master Signing Key...

**Comment by garethtdavies** [comment]
I submitted a PR for this https://gitlab.com/zcash-docs/zcash-docs/merge_requests/61 (though of course, it doesn't solve the underlying issue of why Ubuntu's keyservers see this key as revoked).

**Comment by mdr0id** [comment]
This should now be fully document in : https://gitlab.com/zcash-docs/zcash-docs/merge_requests/61, which is public facing at zcash.readthedocs.io
