### ISSUE TITLE
build Error on Ubuntu: "curl: (35) gnutls_handshake() failed: Error in the pull function."

### ISSUE THREAD

**Issue by zhanghuahua0708** [zcash/zcash#3617]
there is a error when I build the source :
```
curl: (35) gnutls_handshake() failed: Error in the pull function.
funcs.mk:257: recipe for target '/work/zcash/depends/sources/download-stamps/.stamp_fetched-libsodium-libsodium-1.0.15.tar.gz.hash' failed
make: *** [/work/zcash/depends/sources/download-stamps/.stamp_fetched-libsodium-libsodium-1.0.15.tar.gz.hash] Error 35
make: Leaving directory '/work/zcash/depends'
```
my cmd are these:
```
cd zcash
git fetch origin
git checkout v2.0.1
./zcutil/fetch-params.sh
./zcutil/build.sh -j4
```

who can tell me why And how to fix this error?Thanks!

**Comment by ucwong** [comment]
same issue

**Comment by zhanghuahua0708** [comment]
> same issue

hi， have you solved the problem ?

**Comment by ucwong** [comment]
No just roll back

**Comment by zhanghuahua0708** [comment]
> No just rollThe old version can't run 

> No just roll back

The old version can't run

**Comment by zhanghuahua0708** [comment]
![image](https://user-images.githubusercontent.com/25762167/47484648-dc5ec280-d86e-11e8-98a6-3744e7c60aa3.png)
I will  reinstall the system

**Comment by zhanghuahua0708** [comment]
> 2.0.0 is OK for ubuntu16.04

I still have a error like this after I change my vervion to V2.0.0:
![image](https://user-images.githubusercontent.com/25762167/47599452-2e275a00-d9e1-11e8-8bda-cc960f80b982.png)

**Comment by zhanghuahua0708** [comment]
I changed the way ,  I install the zcash by cmd "apt install "
