### ISSUE TITLE
Make SPROUT_URL in zcutil/fetch-params.sh configurable with an env parameter 

### ISSUE THREAD

**Issue by ms4720** [zcash/zcash#3623]
## Describe the issue
Please provide a general summary of the issue you're experiencing

Make SPROUT_URL configurable by using env variables.  We are having issues with Cloudflare blocking access to content, see #3618 , and I would like to set up a local https mirror to use without maintaining a patch.  

### Expected behavior

set an env variable via the k8s config file and it goes to the new location and fetches files

**Comment by daira** [comment]
`SPROUT_URL` no longer exists, but the download URL can be configured using the `ALTERNATIVE_DOWNLOAD_URL` environment variable, so this is fixed.
