### ISSUE TITLE
Allow z_sendmany to use multiple transparent inputs from different addresses

### ISSUE THREAD

**Issue by peterbitfly** [zcash/zcash#3640]
In order for mining pools and exchanges to support mass payouts to the new sapling z addresses the z_sendmany call should allow to spend multiple transparent inputs in one transaction. Assume a mining pool or exchange holds their hot wallet funds in a legacy transparent wallet generated by zcashd. The only way to send transactions to sapling shielded addresses is via the z_sendmany rpc call which can currently send only from one transparent address. So the users have to merge all their transparent outputs into one address before being able to spend them.

Ideally the z_sendmany call should support the same input parameters as the z_mergetoaddress call ("*", "ANY_TADDR", "ANY_ZADDR") which would perfectly resolve the problem.

After evaluating the performance of the new sapling shielded addresses we are confident that we are able to support them on Flypool once this issue has been resolved.

**Comment by ppratscher** [comment]
Thanks for your update. Please note that this ticket refers to the z_sendmany call and not to the z_mergetoaddress one.

**Comment by Eirik0** [comment]
I think it would be nice to have one rpc that encapsulates the functionality of both, but I don't know where that fits on our roadmap. This will be brought up with the zcashd team.

**Comment by ppratscher** [comment]
For us this feature is really important. Currently in order to support mass payouts from a t address to zs addresses we need to manually manage unspent outputs which is quite complicated an error prone as every z_sendmany call sends coins to a new t change address.

**Comment by Eirik0** [comment]
The Zcashd team has decided that this is something that we would like to do, but has not yet set a specific timeline for doing so. One thing to mention is that this would be harder to do using sprout-based shielded transactions because of how the joinsplits would have to be constructed. If this feature were sapling/transparent transactions only, that would simplify things, but still requires more discussion on exactly how this would work.

This could be done with two rpc calls: `z_mergetoaddress ["ANY_TADDR" "ANY_SAPLING"] toAddress` followed by `z_sendmany toAddress [{addr1, amount1}, {addr2, amount2} ...]` which a bit cumbersome to have to do manually and may require two transaction fees. `z_sendmany` could probably be updated pretty straight forwardly to automate this process. It would however be nicer, but require more thought, to update `z_sendmany` to do this without the need for to go through another address.

If it's not too much to ask, some examples of how exactly you are expecting this to work would be greatly appreciated!

**Comment by ppratscher** [comment]
Why what this closed? This issue has nothing to do with #1785?! Using multiple inputs when using z_sendmany is something different compared to what z_mergetoaddress covers.

**Comment by jackgavigan** [comment]
Looks like we've failed to understand the requirements here. 

@ppratscher Does the "ppratcher's request" line in the table below correctly describe what you're looking for? Would you want it to be asynchronous (i.e. capable of executing the instructions in multiple transactions as opposed to a single transaction) and/or able to consume coinbase UTXOs?

<img width="992" alt="screen shot 2019-01-25 at 13 08 51" src="https://user-images.githubusercontent.com/1176633/51747846-85050400-20a2-11e9-8e9e-0e68572d47d8.png">

**Comment by tromer** [comment]
@jackgavigan, the `z_sendmany` line in your table erroneously lists it as not async. It's definitely async.

**Comment by daira** [comment]
@ppratscher wrote:
> Using multiple inputs when using z_sendmany is something different compared to what z_mergetoaddress covers.

Yes sorry, that was just a mistake. We intended to leave open one ticket for this, and closed the wrong one.

**Comment by naconner** [comment]
This feature would be ideal for us to enable sending to customer's z-addrs on @Lamassu ATMs, as operators' zcashd wallets presently maintain UTXOs across multiple t-addrs. We'd want to automatically pick from any and all available inputs, so as not to need to periodically merge the balance to a single t-addr. Thus:

**From:** Multiple t-addrs
**To:** Single z-addr + change t-addr

Ideally, that RPC command also works for sending to a single t-addr + change t-addr.

**Comment by naconner** [comment]
This feature would be ideal for us to enable sending to end-users' z-addrs on ATMs, as operators' zcashd wallets presently maintain UTXOs across multiple t-addrs. We'd want to automatically pick from any and all available inputs, so as not to need to periodically merge the balance to a single t-addr. Thus:

**From:** Multiple t-addrs
**To:** Single z-addr + change t-addr

Ideally, that RPC command also works for sending to a single t-addr + change t-addr.

**Comment by str4d** [comment]
This issue was blocking on someone having time to sit down and figure out how to integrate an `ANY_TADDR` special string into `z_sendmany`. Today, I had time 😄

@peterbitfly @naconner LMK if #4696 is sufficient for your use-cases.

**Comment by naconner** [comment]
Awesome, thanks @str4d! Works for our use-case. We'll be awaiting inclusion. :grin:
