### ISSUE TITLE
Zcash master signing key has been revoked

### ISSUE THREAD

**Issue by garethtdavies** [zcash/zcash#3643]
### Describe the issue
When updating the master signing key from keyservers the master Zcash signing key has been revoked.

### Can you reliably reproduce the issue?
Yes. Steps to reproduce below:

Import the key directly from https://z.cash/support/pubkeys
`wget -qO - https://apt.z.cash/zcash.asc | gpg --import -`

Check it:

`gpg --list-keys`

Returns:

```
pub   rsa4096 2018-10-19 [SC] [expires: 2020-10-20]
      A2CB84F248C7DDC96C2C55C8AEFD26F966E279CD
uid           [  full  ] Zcash Master Signing Key (Zcash Electric Coin Company)
sub   rsa4096 2018-10-19 [E] [expires: 2020-10-20]
```

Update the key from keyserver:

`gpg --refresh-keys --keyserver hkps://hkps.pool.sks-keyservers.net AEFD26F966E279CD`

Outputs:

```
gpg: refreshing 1 key from hkps://hkps.pool.sks-keyservers.net
gpg: key AEFD26F966E279CD: "Zcash Master Signing Key (Zcash Electric Coin Company)" revocation certificate added
gpg: key AEFD26F966E279CD: "Zcash Master Signing Key (Zcash Electric Coin Company)" 3 new signatures
gpg: Total number processed: 1
gpg:         new signatures: 3
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: bad data signature from key B6464E58E32CBEAD: Wrong key usage (0x19, 0x2)
gpg: depth: 0  valid:   3  signed:   2  trust: 0-, 0q, 0n, 0m, 0f, 3u
gpg: depth: 1  valid:   2  signed:   0  trust: 1-, 0q, 0n, 0m, 1f, 0u
gpg: next trustdb check due at 2020-08-09
```

Listing the keys again with `gpg --list-keys` sees it as revoked:

```
pub   rsa4096 2018-10-19 [SC] [revoked: 2018-10-19]
      A2CB84F248C7DDC96C2C55C8AEFD26F966E279CD
uid           [ revoked] Zcash Master Signing Key (Zcash Electric Coin Company)
```

### Expected behaviour
The key shouldn't be revoked (assuming it is to be used).

**Comment by mms710** [comment]
We're going to push out a new key with the 2.0.2 release set for Nov 26th. Please let me know if you have further issues we need to address, otherwise I'll make sure we provide an update to this after the 2.0.2 launch.

**Comment by mdr0id** [comment]
Please see: https://gitlab.com/zcash-docs/zcash-docs/merge_requests/86

As of 12/4/18, the above update should be visible at: https://zcash.readthedocs.io/en/latest/rtd_pages/install_debian_bin_packages.html

**Comment by garethtdavies** [comment]
Not sure the best place for this but see that trailing ` on https://z.cash/support/pubkeys/ for the new master signing key. Best to clean up to remove silly copy/paste errors.
