### ISSUE TITLE
no fee_estimates.dat exists after 2.0.0

### ISSUE THREAD

**Issue by lcgogo** [zcash/zcash#3644]
### Describe the issue

I start zcash 2.0.0 and zcash 2.0.1, but no fee_estimates.dat file is created and
``` 
curl --data-binary '{"jsonrpc":"1.0","id":"curltext","method":"estimatefee","params":[2]}' -H 'content-type:text/plain;'
```
returns
```
{"result":-1,"error":null,"id":"curltext"}
```

#### If so, please list the steps to reproduce below:
1. start a zcash 2.0.1 node
2. `curl --data-binary '{"jsonrpc":"1.0","id":"curltext","method":"estimatefee","params":[2]}' -H 'content-type:text/plain;'`
3. And no fee_estimates.dat exists
```
/data/zcash # ls -l
total 9812
drwxr--r--    3 root     root         12288 Oct 24 03:32 blocks
drwxr--r--    2 root     root         24576 Oct 30 10:45 chainstate
-rw-r--r--    1 root     root       7421582 Oct 30 10:50 debug.log
-rw-------    1 root     root       2533470 Oct 30 10:43 peers.dat
-rw-rw-r--    1 root     root           230 Sep 18 09:22 zcash.20180918
-rw-rw-r--    1 root     root           230 Sep 18 09:22 zcash.conf
-rw-------    1 root     root             2 Oct 30 10:45 zcashd.pid
```

### Expected behaviour

An old zcash folder which upgrade from 1.10.0 to 2.0.1 has fee_estimates.dat and estimatefee rpc returns ok.
```
root@coin-node1:~# ls /data/group1/zcash -l
total 10716
drwx------ 3 nobody nogroup   12288 Oct 30 13:08 blocks
drwx------ 2 nobody nogroup   20480 Oct 30 18:58 chainstate
-rw------- 1 nobody nogroup 8208627 Oct 30 19:25 debug.log
-rw------- 1 nobody nogroup   33910 Sep 19 20:36 fee_estimates.dat
-rw-r--r-- 1 root   root          0 Jun 26 13:56 json.log
-rw------- 1 root   root    2675216 Oct 30 19:13 peers.dat
-rw-r--r-- 1 nobody nogroup     156 May 16 01:28 zcash.conf
-rw------- 1 nobody nogroup       2 Oct 30 18:57 zcashd.pid

root@coin-node1:~# curl --data-binary '{"jsonrpc":"1.0","id":"curltext","method":"estimatefee","params":[2]}' -H 'content-type:text/plain;' http://$rpcuser:$rpcpassword@$ip:$port/
{"result":0.00043234,"error":null,"id":"curltext"}
```

### The version of Zcash you were using:
```
./zcashd --help
Zcash Daemon version v2.0.1-ge8f5e592b8
```

**Comment by daira** [comment]
See also #2552.

**Comment by Eirik0** [comment]
@lcgogo What are you using this rpc for? I am wondering because it is relevant to https://github.com/zcash/zcash/issues/2552#issuecomment-317579049

**Comment by lcgogo** [comment]
> @lcgogo What are you using this rpc for? I am wondering because it is relevant to [#2552 (comment)](https://github.com/zcash/zcash/issues/2552#issuecomment-317579049)

I want to show the transaction fee to my user. Now I set it as 0.0001.

**Comment by ioptio** [comment]
Let's continue this discussion in #2552.
