### ISSUE TITLE
Add Debian 9.5 Stretch as an officially supported release platform.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#3651]
Add official support for Debian 9.5 Stretch, the current stable release. Our current platform is Debian 8 Jessie which was superceded in 2017-06-17.

Let's wait to deprecate Jessie support for at least one or more release cycles. In other words, do not *remove* Debian 8 Jessie support as part of implementing this ticket.

**Comment by zebambam** [comment]
Jessie is now unsupported, so not doing this is now a security issue.

**Comment by zebambam** [comment]
Sorry, just noticed that LTS is actually until 2020.

**Comment by zebambam** [comment]
Although support isn't by the debian security team so we should really look at doing this soon.

**Comment by mdr0id** [comment]
Resolved. Closing unless folks have experience issues
