### ISSUE TITLE
Kill sprout-proving.key

### ISSUE THREAD

**Issue by tromer** [zcash/zcash#3652]
The public parameters `sprout-proving.key` (869MB) was needed for generating shielded transactions prior to Sapling activation, but is not used after activation. Legacy Sprout notes are now spent using the new `sprout-groth16.params`, and Sapling notes use the new `sapling-*.params`.

Thus, `sprout-proving.key` becomes useless once the checkpoint in `src/chainparams.cpp` advances beyond Sapling activation height, meaning we can avoid the associated download and storage costs. Specifically:

1. Remove the fetching of `sprout-proving.key` from `fetch-params.sh`.

2. Have `zcashd` automatically delete `sprout-proving.key` if found. (This feels rather aggressive, but I can't think of another place to put this code without burdening users.)

It may make sense to add command-line or config-file options to revert the above, in case people want to run benchmarks or regressions on the old code. If we _don't_ need that, then:

3. Remove the legacy Sprout libsnark-based proving code from `zcashd`.

(The Sprout libsnark-based _verification_ code, and the related `sprout-verifying.key` and libsnark code, are still needed in order to verify old Sprout proofs.)

**Comment by radix42** [comment]
I would recommend against number 2 above, of deleting the key
automatically, as their are GUI front ends that download it themselves
rather than fetch-params.sh, and they’d redownload on launch.

**Comment by radix42** [comment]
Also there are servers running multiple coins that use it and share one
copy.

**Comment by tromer** [comment]
I agree, these takes 2 off the table.

So I suppose we'll just have to put it in the upgrade instructions, and encourage packagers (`.deb` etc.) to use their packaging system's interactive feature to _suggest_ deletion during upgrades.

**Comment by daira** [comment]
-1 on point 2; +1 on the rest.

**Comment by mms710** [comment]
This should be done before https://github.com/zcash/zcash/issues/2513
