### ISSUE TITLE
z_listreceivedbyaddress help output is incomplete

### ISSUE THREAD

**Issue by zancas** [zcash/zcash#3661]
### Describe the issue
Please provide a general summary of the issue you're experiencing
  The output generated by invoking:
`zcash-cli z_listreceivedbyaddress ${ADDRESS}`

does not match the expected output documented by:

`zcash-cli help z_listreceivedbyaddress`

In particular the "help" output makes no mention of an "outindex" field. 

#### If so, please list the steps to reproduce below:
1.   Run:   `zcash-cli help z_listreceivedbyaddress`
2.    Compare that output to the actual output generated by:
`zcash-cli z_listreceivedbyaddress ${ADDRESS}`

### Expected behaviour
The `help` system should be synced to the actual procedures invoked such that it is not possible for an invocation of the procedure to generate a different output than the `help` system (I think of Python's `doctest`). 

### Actual behaviour + errors
There _is_ a discrepancy.

This is an example of actual output:
```BASH
USER@REDACTED:~/zcash# ./src/zcash-cli z_listreceivedbyaddress ztestsapling1fpf39y8htnhepvhzrw5ht5ma69gkwnnv9vnz6yxeaqmf7u6q6qawmfedtpmpjgzhq5zmvfdx533
[
  {
    "txid": "a2a184cf2acd1769cc8d840426463b4782fbbbe8701903a3fb2bd5720ad0b31a",
    "amount": 25.00000000,
    "memo": "
REDACTED.....0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "outindex": 0,
    "change": false
  }
]

```

Here's an example of the help documentation:

```BASH
USER@REDACTED:~/zcash# ./src/zcash-cli help z_listreceivedbyaddress
z_listreceivedbyaddress "address" ( minconf )

Return a list of amounts received by a zaddr belonging to the node’s wallet.

Arguments:
1. "address"      (string) The private address.
2. minconf          (numeric, optional, default=1) Only include transactions confirmed at least this many times.

Result:
{
  "txid": xxxxx,           (string) the transaction id
  "amount": xxxxx,         (numeric) the amount of value in the note
  "memo": xxxxx,           (string) hexademical string representation of memo field
  "change": true|false,    (boolean) true if the address that received the note is also one of the sending addresses
}

Examples:
> zcash-cli z_listreceivedbyaddress "ztfaW34Gj9FrnGUEf833ywDVL62NWXBM81u6EQnM6VR45eYnXhwztecW1SjxA7JrmAXKJhxhj3vDNEpVCQoSvVoSpmbhtjf"
> curl --user myusername --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "z_listreceivedbyaddress", "params": ["ztfaW34Gj9FrnGUEf833ywDVL62NWXBM81u6EQnM6VR45eYnXhwztecW1SjxA7JrmAXKJhxhj3vDNEpVCQoSvVoSpmbhtjf"] }' -H 'content-type: text/plain;' http://127.0.0.1:8232/


``` 

NOTE:   The `outindex` is not mentioned in the help documentation.

Here's another interface to (what I believe is) the same output:

https://zcash-rpc.github.io/z_listreceivedbyaddress.html

**Comment by daira** [comment]
There are several obstacles that prevent doctest-like testing of the RPC help. doctest works well for deterministic, pure-functional operations, but almost none of the RPC interfaces are in that category. Even the "read-only" methods depend on chain and wallet state. Moreover, trying to doctest any of the state-changing methods would alter that state in ways that would make it difficult to run the tests more than once, or to find a consistent order in which they could be run. Snapshotting and restoring the state is probably not practical because you would need to restart the node on every restore, and it would take too long before the RPC interface becomes available again.

Another possible approach is to make sure that the doc and code are consistent by construction, rather than by testing:

* To ensure that output examples are consistent, factor out a function that constructs the output JSON, and call it both to construct that part of the doc string and to construct the actual output.
* To check example parameters, factor out the parameter parser and call it on those parameters when constructing the doc string.
* To ensure that the general descriptions of parameters and outputs are correct, construct template parser and emitter objects that can both be pretty printed and used as the actual parser and emitter.

This approach is feasible; however, it is a lot of work. I'm somewhat skeptical that, for the RPC interface written in C++, it would be cost-effective relative to just doing more thorough review of the existing code and PRs that change it. For any new RPC code, perhaps written in Rust, that trade-off would be more favourable to the template-based approach.

**Comment by daira** [comment]
Note that a nice side benefit of constructing the examples programmatically is that you could automatically generate both the `zcash-cli` and `curl` examples from the same arguments.

**Comment by daira** [comment]
Incidentally, there's also a typo "hexademical" in the `z_listreceivedbyaddress` help.

**Comment by zancas** [comment]
Hmmm...   there's a lot here, so I am going to interweave my responses into a quote of the original (Inset lines are a quotation from [daira](https://github.com/daira)'s [comment](https://github.com/zcash/zcash/issues/3661#issuecomment-437578843)):

> There are several obstacles that prevent doctest-like testing of the RPC help. doctest works well for deterministic, pure-functional operations, but almost none of the RPC interfaces are in that category. Even the "read-only" methods depend on chain and wallet state.

Now that you say this, I agree that "doctest" seems totally inadequate.

What happens if the [RPC element](https://gitlab.com/ZingO-Labs/emflib/issues/7) is isolated from the chain and wallet state?  Could this be done with a test framework that includes patches?  Perhaps this would take the form of a set of [declarative macros](https://doc.rust-lang.org/book/2018-edition/appendix-04-macros.html) that apply relevant test `Traits` to the code under test?

> Moreover, trying to doctest any of the state-changing methods would alter that state in ways that would make it difficult to run the tests more than once, or to find a consistent order in which they could be run. 

We could mock out interactions to control state transitions/context.

Do we want the tests to run in order?

If we want evidence that there's _not_ between test interactions, i.e. that their run order does not effect their outcomes, then we could used seeded pseudorandom orders for each run.  

If we detect surprising transitions then we could use that test set and the `seed` to create a new test that makes assertions about the particular transition order.

> Snapshotting and restoring the state is probably not practical because you would need to restart the node on every restore, and it would take too long before the RPC interface becomes available again.

I _think_ a Docker container might work well in this problem space:

  1  You can store all the state needed to have a running zcashd with fully synced blockchain Docker container up and networking in an order of seconds (possibly less).  (This is current up to the last time the container ran, and requires sufficient space to store the entire blockchain.)
      * we could also use caches of hotloads if our tests start to outperform `docker run`
  
  2  Docker states are recorded as `sha256` referenced images, i.e. snapshots.

> 
> Another possible approach is to make sure that the doc and code are consistent by construction, rather than by testing:


   I like this idea!   Could it be complementary with a test based approach?
   A comprehensive test suite for the original RPC, could be used to assert that the new implementation conforms to the same expectations?   

>    To ensure that output examples are consistent, factor out a function that constructs the output JSON, and call it both to construct that part of the doc string and to construct the actual output.

I will create an issue for this.

>    To check example parameters, factor out the parameter parser and call it on those parameters when constructing the doc string.

I will create an issue for this.

>    To ensure that the general descriptions of parameters and outputs are correct, construct template parser and emitter objects that can both be pretty printed and used as the actual parser and emitter.

I will create an issue for this. 
> 
> 
> This approach is feasible; however, it is a lot of work. I'm somewhat skeptical that, for the RPC interface written in C++, it would be cost-effective relative to just doing more thorough review of the existing code and PRs that change it. For any new RPC code, perhaps written in Rust, that trade-off would be more favourable to the "consistent by construction" approach.

  I'm pretty invested in Rust, and frankly don't have the bandwidth to learn C++ in any depth.  I know this because I lost some time studying C++ recently before concluding that I can't afford the time (for the benefit).

**Comment by zancas** [comment]
Ok, I have created the promised issues:

https://gitlab.com/ZingO-Labs/emflib/issues/8
https://gitlab.com/ZingO-Labs/emflib/issues/9
https://gitlab.com/ZingO-Labs/emflib/issues/10

**Comment by mms710** [comment]
This PR fixes this issue: https://github.com/zcash/zcash/pull/3663
In addition, we are working on this PR to create nicely formatted RPC documentation that can more easily be made consistent: https://github.com/zcash/zcash/pull/3734
