### ISSUE TITLE
Use batch verification for RedJubjub signatures

### ISSUE THREAD

**Issue by daira** [zcash/zcash#3666]
This is similar to batch SNARK verification (#320), and a similar strategy can be used to mitigate the risk of consensus divergence (https://github.com/zcash/zcash/issues/320#issuecomment-438199204). We can either implement them at the same time and use the same experimental feature flag, or we can implement them separately.

**Comment by daira** [comment]
Note that sapling-crypto already has an API for batched RedJubjub verification, which was added in https://github.com/zcash-hackworks/sapling-crypto/pull/80 . There is a ticket https://github.com/zcash-hackworks/sapling-crypto/issues/82 to improve its performance.

**Comment by str4d** [comment]
This was implemented in #6048.
