### ISSUE TITLE
Transaction Confirmation Sec-UX feature requirements

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#3674]
From [Announcing Zcash Blossom and proposed feature goals](https://forum.zcashcommunity.com/t/announcing-zcash-blossom-and-proposed-feature-goals/31891):

> # Transaction Confirmation Usability and Security Improvements
>
> - **What is it?** Improve usability and security of fees and confirmations while accounting for growing transaction volume, demand spikes, and transaction-based DOS scenarios.
> - **Who does this affect?** Transaction senders and receivers.
> - **Why is this a goal?** We cannot prevent demand shocks or growth approaching scalability limits, but we can and should help users understand what is happening and help them protect themselves.

**Close Criteria:** Close this ticket when there are well-specified precise requirements for this feature goal.

**Comment by ioptio** [comment]
A note about terminology to avoid clashing with the concept of a single block confirmation: "transaction settlement" or "transaction acceptance" seem accessible as a replacement.

**Comment by nathan-at-least** [comment]
We're going to replace this with two more specific goals:

- #1133 Block size limits for transparent transactions.
- #3690 Shorter block times.

**Comment by nathan-at-least** [comment]
We're replacing this with two more specific goals for Blossom:

- #1133 Restrict block size for transparent 
- #3690 Shorter block time

We considered other more specific goals that follow this, including a "min fee scheme" that isn't written down anywhere that @zookozcash described to me.
