### ISSUE TITLE
BOLT Support feature requirements

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#3676]
From [Announcing Zcash Blossom and proposed feature goals](https://forum.zcashcommunity.com/t/announcing-zcash-blossom-and-proposed-feature-goals/31891):

> # BOLT Support
>
> - **What is it?** Base consensus support for the BOLT second-layer protocol (see our [introductory blog post](https://z.cash/blog/bolt-private-payment-channels/)).
> - **Who does this affect?** (Future potential) Users of BOLT-enabled light wallets.
> - **Why is this a goal?** Second-layer channel-based protocols may enable use cases that allow substantially more transactions with minimized capacity impact on the base consensus protocol. A direct BOLT integration with Zcash would have stronger privacy protections than existing second layer systems, which may be especially important if service providers centralize.

**Close Criteria:** Close this ticket when there are well-specified precise requirements for this feature goal.

**Comment by daira** [comment]
I'm merging this ticket into #2353.
