### ISSUE TITLE
Fix comments and variable names in wallet_addresses.py

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#3686]
https://github.com/zcash/zcash/pull/3680#discussion_r234128383

**Comment by josephnicholas** [comment]
@bitcartel working on this and I want to clarify if I understood the comments.

### Requirements:
- Need to correct comments to denote on other address types `sprout and sapling`.
- Separate default_type tests with named types.

Please correct / agree before I proceed on making a PR. Thanks :)

**Comment by daira** [comment]
The [current code](https://github.com/zcash/zcash/blob/master/qa/rpc-tests/wallet_addresses.py) looks fine to me and no longer requires this fix.

(Aside: bitcartel is no longer working on Zcash.)

**Comment by josephnicholas** [comment]
@daira Thanks, will find more task to work on.
