### ISSUE TITLE
[ZIP 208] [Blossom NU] Shorter Block Target Spacing

### ISSUE THREAD

**Issue by zookozcash** [zcash/zcash#3690]
Who is affected: all users
What: shorter target blocktimes
Why: faster finalisation [*] and greater throughput of transactions per hour.

[*] It's controversial whether this change actually provides this benefit.

Data:

 * BTC has 1 MB blocks, 600 second blocktimes, [please reply and insert typical BTC full block verification time here] and has often sustained full load without failing.
 * LTC has 1 MB blocks, 150 second blocktimes, but I don't know if it has ever sustained full load.
 * ETH has sustained full load at about 20 KB blocks about every 15 seconds, and according to [according to Frederick](https://twitter.com/zooko/status/1061719812701736960) with verification time around 300 ms. (Edit: after other changes to the difficulty in ETH, the [average block time for ETH is currently 12.5 seconds](https://www.trustnodes.com/2019/03/03/ethereum-blocks-drop-to-12-seconds).)
 * BCH may have sustained load during "stress tests" on their mainnet — I'm not sure about that. Please reply and add that data.
 * ZEC (1.0 “Sprout“ and 2.0 “Sapling”) have 2 MB max block size, 150 second block times, estimated worst-case verification time of maybe 20s (??? Please reply and add this data), but to my knowledge we've never sustained full load, not even on testnet or a simulation.

Expert opinion: I've heard from Bitcoin Core developers, Vitalik Buterin, Arthur Breitman, James Prestwich, Daira Hopwood, and Emin Gün Sirer, and probably from lots of other well-informed people who I'm momentarily forgetting (sorry), and they seem to be in rough agreement that if the worst-case block verification time (i.e. the time for a miner to verify a winning block that a different miner just supplied to them, and which that other miner might have maliciously constructed with their own transactions designed to be slow to verify) is no more than 10% of the target block time, then you're probably okay.

Proposal:

1. Write benchmarks of worst-case block verification time.
2. Wire them up to https://speed.z.cash so that we can all see their current results (on a typical 64-bit modern multicore Intel/AMD machine).
3. Optimize the verification code (batch verification of the SNARKs is allowed, SIMD implementation is allowed, multi-core and multi-threading are allowed).
4. Change the target blocktime to be 10X the new worst-case block verification time.

**Comment by str4d** [comment]
@gtank points out that we also need to model how an increase of users of 2x, 10x, etc. (e.g. due to Sapling light wallets being deployed) can be handled by the current block size and interval. Knowing at what point the chain reaches its limits will tell us how important it is to make these changes.

**Comment by defuse** [comment]
Here's the ticket where we discussed the block time originally: https://github.com/zcash/zcash/issues/764

@ebfull made a good point on that ticket which I'll repeat here to make sure it's not accidentally forgotten:

> Reminde[r]: when we do this, we must modify the founders' reward code, because it is based on the assumption we have 10 minute blocks, and thus that the "first four years" end on block 210000 -- the first halving of the block reward.

**Comment by nathan-at-least** [comment]
I want this renamed to reflect what it means for users. I think that might be "lower the time that users need to wait for finalization and/or increase txn throughput".

**Comment by daira** [comment]
I had been assuming that the worst case verification time would be for a block full of Sapling spends. However, it might actually be for a block full of JoinSplits if those are reduced to 400 bytes by #3677. (Either Spends or JoinSplits can use dummy inputs, so a DoS attacker wouldn't necessarily need Sapling or Sprout notes to start with.)

**Comment by mms710** [comment]
Notes from discussion today: we have reached agreement that this is something we'd like to do and on the general approach above, we just haven't yet agreed on what the new target blocktime should be. Good thing the first step of this is to do research and benchmarking!

**Comment by zookozcash** [comment]
My current proposal is:

* Write benchmarks of worst-case block verification time.
* Wire them up to https://speed.z.cash so that we can all see their current results (on a typical 64-bit modern multicore Intel/AMD machine).
* Optimize the verification code (batch verification of the SNARKs is allowed, SIMD implementation is allowed, multi-core and multi-threading are allowed).
* Change the target blocktime to be 3X the new worst-case block verification time.

This means that if the worst-case block can't be verified any faster than 50s then we can't increase the block rate at all! So fire up those optimisers, folks! :-)

Ooh, fun idea, possibly a bad idea: have two teams in competition! The "generate a worst-case block" team and the "optimize the verifier" team. We could even have the two teams submit their latest submissions blinded from one another in multiple rounds. :-) ❤

**Comment by zookozcash** [comment]
Important note about the timing of this: we have to specify everything about the faster blocks in the January 22 specification, but we don't have to choose the constant for the new target block time until the end of March (in time for the code implementation audit). So we have a few weeks to determine the answer!

If we don't determine this empirically by the end of March, then I propose we reduce the target block time from 150 seconds to 60 seconds. Rationale for that is that it seems roughly in keeping with the empirical evidence from other blockchains (listed in [the O.P.](https://github.com/zcash/zcash/issues/3690#issue-381886781)), and 60 seconds is a nice easy constant for humans to remember and work with.

If you think 60 seconds is too low then go generate a worst-case block which takes longer than 20 seconds for the current verifier to verify. :-)

**Comment by lindanlee** [comment]
(Context: @zookozcash asked about the UX benefits of faster blocktimes on slack. Posted here so it doesn't get lost.) 

I think that faster block times == less waiting for confirmations is generally better, but 45 minutes to 30 minutes will not make any significant impact on UX.  33% less time, is NOT 33% better, because wait times tolerance are more threshold-based. If it's too slow, it's too slow (even if it's less slow). I'd say it's closer to 2-3% better for UX (purely based on wait time reduction, not network-related effects like making Zcash network more reliable).  

_45 minutes and 30 minutes are both too slow_. They both would not feel instantaneous,  interrupt the user's flow of thought, and  require signaling users that the task was complete. 

The literature/founding father of usability, Jakob Nielsen (https://www.nngroup.com/articles/response-times-3-important-limits/) states:
> • 0.1 second is about the limit for having the user feel that the system is *reacting instantaneously*, meaning that no special feedback is necessary except to display the result.
> • 1.0 second is about the limit for the *user’s flow of thought to stay uninterrupted*, even though the user will notice the delay. Normally, no special feedback is necessary during delays of more than 0.1 but less than 1.0 second, but the user does lose the feeling of operating directly on the data.
> • 10 seconds is about the limit for *keeping the user’s attention focused on the dialogue*. For longer delays, users will want to perform other tasks while waiting for the computer to finish, so they should be given feedback indicating when the computer expects to be done.

Given this information, I think the best way to improve UX is to notify the user when a transaction has been confirmed. It is also known that users would prefer less variability over shorter wait times, provided that it's in the same time range (i.e. 5 vs vs 3 seconds, or in our case, 45 min vs 30 min). I personally think it'd be better to have it reliably be 45 minutes, rather than improving the current times to be faster but to keep the same variability, i.e. 20-45 minutes. This way, we can have features like a semi-reliable progress bar for transaction confirmation/we can have the client ping to see if a transaction has been confirmed after ~45 min.

IF there are other additional benefits other than wait time reduction, I would re-evaluate the benefit of shorter wait times.

**Comment by mms710** [comment]
Zcash Company has decided to move forward with pursuing shorter blocktimes for Blossom. As a note, there are three more points along the network upgrade timeline below where we may need to abort this goal if we find significant issues with our approach as a result of issues that come up in specification auditing (end of Feb) inability to finish the code in time (end of March) or issues that come up as a result of code auditing or testing (end of May).

![image](https://user-images.githubusercontent.com/25780612/50850865-5f54cc80-1338-11e9-9ad1-0867a145e89d.png)

In addition to this goal, Zcash Company will be pursuing Harmony Mining (https://github.com/zcash/zcash/issues/3672) and splitting the founder's reward (https://github.com/zcash/zcash/issues/3673) while maintaining transaction version 4 (https://github.com/zcash/zcash/issues/3739).

**Comment by solardiz** [comment]
FWIW, here's a commit I made to a still unreleased Zcash fork changing the block interval to 60 seconds, please feel free to use it as-is or as a checklist (needed since constants related to the block interval are scattered over the tree):

```diff
Date:   Fri Nov 16 16:51:17 2018 +0100

    Reduce block interval from 2.5 minutes to 1 minute

diff --git a/src/chainparams.cpp b/src/chainparams.cpp
index 3e17bf1..636b43c 100644
--- a/src/chainparams.cpp
+++ b/src/chainparams.cpp
@@ -94,7 +94,7 @@ public:
         assert(maxUint/UintToArith256(consensus.powLimit) >= consensus.nPowAveragingWindow);
         consensus.nPowMaxAdjustDown = 32; // 32% adjustment down
         consensus.nPowMaxAdjustUp = 16; // 16% adjustment up
-        consensus.nPowTargetSpacing = 2.5 * 60;
+        consensus.nPowTargetSpacing = 60;
         consensus.nPowAllowMinDifficultyBlocksAfterHeight = boost::none;
         consensus.vUpgrades[Consensus::BASE_SPROUT].nProtocolVersion = 170002;
         consensus.vUpgrades[Consensus::BASE_SPROUT].nActivationHeight =
@@ -188,7 +188,7 @@ public:
             0,              // * total number of transactions between genesis and last checkpoint
                             //   (the tx=... number in the SetBestChain debug.log lines)
             0               // * estimated number of transactions per day after checkpoint
-                            //   total number of tx / (checkpoint block height / (24 * 24))
+                            //   total number of tx / (checkpoint block height / (24 * 60))
         };
 
         // Founders reward script expects a vector of 2-of-3 multisig addresses
@@ -274,7 +274,7 @@ public:
         assert(maxUint/UintToArith256(consensus.powLimit) >= consensus.nPowAveragingWindow);
         consensus.nPowMaxAdjustDown = 32; // 32% adjustment down
         consensus.nPowMaxAdjustUp = 16; // 16% adjustment up
-        consensus.nPowTargetSpacing = 2.5 * 60;
+        consensus.nPowTargetSpacing = 60;
         consensus.nPowAllowMinDifficultyBlocksAfterHeight = 299187;
         consensus.vUpgrades[Consensus::BASE_SPROUT].nProtocolVersion = 170002;
         consensus.vUpgrades[Consensus::BASE_SPROUT].nActivationHeight =
@@ -363,7 +363,7 @@ public:
             0,              // * total number of transactions between genesis and last checkpoint
                             //   (the tx=... number in the SetBestChain debug.log lines)
             0               // * estimated number of transactions per day after checkpoint
-                            //   total number of tx / (checkpoint block height / (24 * 24))
+                            //   total number of tx / (checkpoint block height / (24 * 60))
         };
 
         // Founders reward script expects a vector of 2-of-3 multisig addresses
@@ -406,7 +406,7 @@ public:
         assert(maxUint/UintToArith256(consensus.powLimit) >= consensus.nPowAveragingWindow);
         consensus.nPowMaxAdjustDown = 0; // Turn off adjustment down
         consensus.nPowMaxAdjustUp = 0; // Turn off adjustment up
-        consensus.nPowTargetSpacing = 2.5 * 60;
+        consensus.nPowTargetSpacing = 60;
         consensus.nPowAllowMinDifficultyBlocksAfterHeight = 0;
         consensus.vUpgrades[Consensus::BASE_SPROUT].nProtocolVersion = 170002;
         consensus.vUpgrades[Consensus::BASE_SPROUT].nActivationHeight =
@@ -472,7 +472,7 @@ public:
             0,              // * total number of transactions between genesis and last checkpoint
                             //   (the tx=... number in the SetBestChain debug.log lines)
             0               // * estimated number of transactions per day after checkpoint
-                            //   total number of tx / (checkpoint block height / (24 * 24))
+                            //   total number of tx / (checkpoint block height / (24 * 60))
         };
 
         // These prefixes are the same as the testnet prefixes
diff --git a/src/deprecation.h b/src/deprecation.h
index 91d8539..989dd69 100644
--- a/src/deprecation.h
+++ b/src/deprecation.h
@@ -10,10 +10,10 @@
 // * A warning is shown during the 2 weeks' worth of blocks prior to shut down.
 static const int APPROX_RELEASE_HEIGHT = 411500;
 static const int WEEKS_UNTIL_DEPRECATION = 16;
-static const int DEPRECATION_HEIGHT = APPROX_RELEASE_HEIGHT + (WEEKS_UNTIL_DEPRECATION * 7 * 24 * 24);
+static const int DEPRECATION_HEIGHT = APPROX_RELEASE_HEIGHT + (WEEKS_UNTIL_DEPRECATION * 7 * 24 * 60);
 
 // Number of blocks before deprecation to warn users
-static const int DEPRECATION_WARN_LIMIT = 14 * 24 * 24; // 2 weeks
+static const int DEPRECATION_WARN_LIMIT = 14 * 24 * 60; // 2 weeks
 
 /**
  * Checks whether the node is deprecated based on the current block height, and
diff --git a/src/miner.cpp b/src/miner.cpp
index 747deed..f1a50aa 100644
--- a/src/miner.cpp
+++ b/src/miner.cpp
@@ -614,7 +614,7 @@ void static BitcoinMiner()
                     break;
                 if ((UintToArith256(pblock->nNonce) & 0xffff) == 0xffff)
                     break;
-                if (mempool.GetTransactionsUpdated() != nTransactionsUpdatedLast && GetTime() - nStart > 60)
+                if (mempool.GetTransactionsUpdated() != nTransactionsUpdatedLast && GetTime() - nStart > 24)
                     break;
                 if (pindexPrev != chainActive.Tip())
                     break;
diff --git a/src/policy/fees.cpp b/src/policy/fees.cpp
index f08cec3..9984132 100644
--- a/src/policy/fees.cpp
+++ b/src/policy/fees.cpp
@@ -217,8 +217,8 @@ void TxConfirmStats::Read(CAutoFile& filein)
         throw std::runtime_error("Corrupt estimates file. Mismatch in tx count bucket count");
     filein >> fileConfAvg;
     maxConfirms = fileConfAvg.size();
-    if (maxConfirms <= 0 || maxConfirms > 6 * 24 * 7) // one week
-        throw std::runtime_error("Corrupt estimates file.  Must maintain estimates for between 1 and 1008 (one week) confirms");
+    if (maxConfirms <= 0 || maxConfirms > 60 * 24) // one day
+        throw std::runtime_error("Corrupt estimates file.  Must maintain estimates for between 1 and 1440 (one day) confirms");
     for (unsigned int i = 0; i < maxConfirms; i++) {
         if (fileConfAvg[i].size() != numBuckets)
             throw std::runtime_error("Corrupt estimates file. Mismatch in fee/pri conf average bucket count");
```

The last hunk corrects a (non-)issue present in almost(?) all coins based off Bitcoin yet with block interval other than 10 minutes (including current Zcash), e.g. https://github.com/dashpay/dash/issues/2556

**Comment by daira** [comment]
I changed the title because "block target spacing" is the term used in the protocol spec (and in the constant `PoWTargetSpacing`). I've assigned ZIP number 208 (ZIP 206 is for deployment of the upgrade, and ZIP 207 is for split FR; 208 ends up depending on 207 so this order makes most sense).

**Comment by daira** [comment]
Choosing a target spacing is blocked on #893 and #3790. The sum of worst-case block verification and propagation time should be a small fraction of the target spacing.

**Comment by daira** [comment]
@str4d, @Marshall and I paired on simulating the behaviour of the difficulty adjustment algorithm following a change in block target spacing. The summary is that the adjustment works as expected; for example, if the block target spacing is halved (to 75 seconds), then it takes around 300 blocks or ~6.6 hours to adjust:

![pow-target-spacing-sim-2](https://user-images.githubusercontent.com/643204/52316662-6e20b480-29b4-11e9-84c4-92ee0650350d.png)

When the block target spacing is reduced by a factor of 10 (to 15 seconds), it again takes around 300 blocks to adjust (I didn't record the length of time):

![pow-target-spacing-sim-10](https://user-images.githubusercontent.com/643204/52316659-68c36a00-29b4-11e9-883a-3a11352185be.png)

**Comment by solardiz** [comment]
Adding to the checklist of what block counts to possibly reconsider or at least edit the comment, here's one more place in `main.cpp`:

```c
    // If our best fork is no longer within 288 blocks (+/- 12 hours if no one mines it)
    // of our head, drop it
    if (pindexBestForkTip && chainActive.Height() - pindexBestForkTip->nHeight >= 288)
        pindexBestForkTip = NULL;
```

**Comment by str4d** [comment]
@daira, @mdr0id and I had a pairing discussing this:

- Batch verification doesn't necessarily help in the worst case:
  - If we batch-verify in the mempool, a worst-case block will still contain all-fresh transactions (if the attacker is the miner).
  - If we batch-verify in the consensus rules, we have to worry about both false negatives (which you solve by falling back to individual verification), and false positives (have to ensure we get the math and impl right).
- Easiest to focus on parallelisation - split block transactions across threads, leaving the per-transaction verification single-threaded.
  - Note that we would probably do this in C++ instead of Rust for Sapling, because the FFI assumes we pass individual parts of a transaction across, not the entire transaction
- Ballpark estimate of worst-case verification time is a single transaction contain (no more than) 5208 Sapling spends, at 8ms per proof validation spend, giving around 42s.

**Comment by daira** [comment]
Note that the 42s estimate above considers only the proof validation time; each Spend description also has a RedJubjub spend authorisation signature to be verified. This will likely take much less time than the proof validation, though.

**Comment by str4d** [comment]
@ebfull in my pairing with him, estimated that the verification cost for a single proof could be reduced by around 80% solely with improvements to the existing single-threaded implementation. Additionally, he pointed out that we could parallelise Sapling proof verification within a transaction pretty easily, by storing the proofs in the context object (along with the value balance) and then verifying in parallel alongside the binding signature check. The same could be done for RedJubjub signatures within a single transaction.

**Comment by hosseinamin** [comment]
@zookozcash Shorter block target time increases the likelihood of empty blocks by miners for near future. To get the subsidy reward. We don't know how this end up when adoption is at limit of the block-size.
It may end up having less throughput. We can already see it in bitcoin.

**Comment by str4d** [comment]
I have partially-migrated upstream's micro-benchmarking framework (before its rewrite in December 2017, but the numbers I was seeing were similar to what our benchmarks return), and created a worst-case block simulator with a couple of different strategies:

```
$ ./contrib/simulations/worstcase.py
Collecting benchmarks...
WARNING: Clock precision is worse than microsecond - benchmarks may be less accurate!
Times (ns): {'proof': 4300500, 'ecdsa': 54604, 'redjubjub': 393900, 'ed25519': 85621}

Running worst-case simulations...
One Sapling spend per transaction:
- Block size:           1999915 bytes
- Transactions:         4225
- Proofs:               4225
- ECDSA signatures:     0
- RedJubjub signatures: 8450
- Ed25519 signatures:   0
- Verification time:    21.50 seconds

One transaction containing Sapling spends:
- Block size:           1999915 bytes
- Transactions:         1
- Proofs:               5204
- ECDSA signatures:     0
- RedJubjub signatures: 5205
- Ed25519 signatures:   0
- Verification time:    24.43 seconds

One Sapling output per transaction:
- Block size:           1999789 bytes
- Transactions:         1927
- Proofs:               1927
- ECDSA signatures:     0
- RedJubjub signatures: 1927
- Ed25519 signatures:   0
- Verification time:    9.05 seconds

One transaction containing Sapling outputs:
- Block size:           1999963 bytes
- Transactions:         1
- Proofs:               2108
- ECDSA signatures:     0
- RedJubjub signatures: 1
- Ed25519 signatures:   0
- Verification time:    9.07 seconds

One JoinSplit per transaction:
- Block size:           1998752 bytes
- Transactions:         1098
- Proofs:               1098
- ECDSA signatures:     0
- RedJubjub signatures: 0
- Ed25519 signatures:   1098
- Verification time:    4.82 seconds

One transaction containing JoinSplits:
- Block size:           1998459 bytes
- Transactions:         1
- Proofs:               1176
- ECDSA signatures:     0
- RedJubjub signatures: 0
- Ed25519 signatures:   1
- Verification time:    5.06 seconds
```

Taking into account the fact that my desktop verifies proofs almost twice as fast as the 8ms benchmark above, my simulation finds that a current worst-case block would be a single transaction packed with Sapling inputs, and it would take about 45.5 seconds to verify on the benchmark server.

**Comment by str4d** [comment]
If you want to run the simulation yourself, the code is in this branch: https://github.com/str4d/zcash/tree/worst-case-benchmarks (build Zcash first, then run the simulation).

**Comment by garethtdavies** [comment]
I got 58.16 seconds on a dated PC with the following specs:

OS: Ubuntu 18.04.2 LTS x86_64
CPU: AMD FX-6100 (6) @ 3.300GHz 
Memory: 3693MiB / 16022MiB 

```
Times (ns): {'proof': 9939125, 'ecdsa': 161132, 'redjubjub': 1235785, 'ed25519': 344389}
```

```
One transaction containing Sapling spends:
- Block size:           1999915 bytes
- Transactions:         1
- Proofs:               5204
- ECDSA signatures:     0
- RedJubjub signatures: 5205
- Ed25519 signatures:   0
- Verification time:    58.16 seconds
```

**Comment by str4d** [comment]
My run above was with:

OS: Ubuntu 18.04.1 running in WSL on Windows 10
CPU: Intel Core i7-8700K @ 3.70GHz
Memory: 16GiB

**Comment by str4d** [comment]
On my older laptop:

OS: Ubuntu 18.04.2
CPU: Intel Core i7-6600U CPU @ 2.60GHz
Memory: 16GiB
```
$ ./contrib/simulations/worstcase.py 
Collecting benchmarks...
WARNING: Clock precision is worse than microsecond - benchmarks may be less accurate!
Times (ns): {'proof': 5938731, 'ecdsa': 75855, 'redjubjub': 573618, 'ed25519': 119840}

Running worst-case simulations...
One Sapling spend per transaction:
- Block size:           1999915 bytes
- Transactions:         4225
- Proofs:               4225
- ECDSA signatures:     0
- RedJubjub signatures: 8450
- Ed25519 signatures:   0
- Verification time:    29.94 seconds

One transaction containing Sapling spends:
- Block size:           1999915 bytes
- Transactions:         1
- Proofs:               5204
- ECDSA signatures:     0
- RedJubjub signatures: 5205
- Ed25519 signatures:   0
- Verification time:    33.89 seconds
```

**Comment by str4d** [comment]
I manually ran the benchmarks on the benchmark server:

OS: Debian 8
CPU: Intel Xeon CPU E3-1225 V2 @ 3.20GHz
Memory: 32GiB
```
$ ./contrib/simulations/worstcase.py 
Collecting benchmarks...
WARNING: Clock precision is worse than microsecond - benchmarks may be less accurate!
Times (ns): {'ecdsa': 79478, 'proof': 7392106, 'redjubjub': 613299, 'ed25519': 129130}

Running worst-case simulations...
One Sapling spend per transaction:
- Block size:           1999915 bytes
- Transactions:         4225
- Proofs:               4225
- ECDSA signatures:     0
- RedJubjub signatures: 8450
- Ed25519 signatures:   0
- Verification time:    36.41 seconds

One transaction containing Sapling spends:
- Block size:           1999915 bytes
- Transactions:         1
- Proofs:               5204
- ECDSA signatures:     0
- RedJubjub signatures: 5205
- Ed25519 signatures:   0
- Verification time:    41.66 seconds

One Sapling output per transaction:
- Block size:           1999789 bytes
- Transactions:         1927
- Proofs:               1927
- ECDSA signatures:     0
- RedJubjub signatures: 1927
- Ed25519 signatures:   0
- Verification time:    15.43 seconds

One transaction containing Sapling outputs:
- Block size:           1999963 bytes
- Transactions:         1
- Proofs:               2108
- ECDSA signatures:     0
- RedJubjub signatures: 1
- Ed25519 signatures:   0
- Verification time:    15.58 seconds

One JoinSplit per transaction:
- Block size:           1998752 bytes
- Transactions:         1098
- Proofs:               1098
- ECDSA signatures:     0
- RedJubjub signatures: 0
- Ed25519 signatures:   1098
- Verification time:    8.26 seconds

One transaction containing JoinSplits:
- Block size:           1998459 bytes
- Transactions:         1
- Proofs:               1176
- ECDSA signatures:     0
- RedJubjub signatures: 0
- Ed25519 signatures:   1
- Verification time:    8.69 seconds
```

**Comment by zookozcash** [comment]
Updated [the O.P.](https://github.com/zcash/zcash/issues/3690#issue-381886781) to mention that currently the average block time in Ethereum is 12.5 seconds.

**Comment by mdr0id** [comment]
Another reference point FWIW:

OS: Ubuntu 18.04.1 LTS
CPU: AMD A8-3850 APU with Radeon(tm) HD Graphics @ 2900 MHz
Memory:        8163168 kB

```
Collecting benchmarks...
WARNING: Clock precision is worse than microsecond - benchmarks may be less accurate!
Times (ns): {'proof': 10607538, 'ecdsa': 149620, 'redjubjub': 898023, 'ed25519': 248934}

Running worst-case simulations...
One Sapling spend per transaction:
- Block size:           1999915 bytes
- Transactions:         4225
- Proofs:               4225
- ECDSA signatures:     0
- RedJubjub signatures: 8450
- Ed25519 signatures:   0
- Verification time:    52.41 seconds

One transaction containing Sapling spends:
- Block size:           1999915 bytes
- Transactions:         1
- Proofs:               5204
- ECDSA signatures:     0
- RedJubjub signatures: 5205
- Ed25519 signatures:   0
- Verification time:    59.88 seconds

One Sapling output per transaction:
- Block size:           1999789 bytes
- Transactions:         1927
- Proofs:               1927
- ECDSA signatures:     0
- RedJubjub signatures: 1927
- Ed25519 signatures:   0
- Verification time:    22.17 seconds

One transaction containing Sapling outputs:
- Block size:           1999963 bytes
- Transactions:         1
- Proofs:               2108
- ECDSA signatures:     0
- RedJubjub signatures: 1
- Ed25519 signatures:   0
- Verification time:    22.36 seconds

One JoinSplit per transaction:
- Block size:           1998752 bytes
- Transactions:         1098
- Proofs:               1098
- ECDSA signatures:     0
- RedJubjub signatures: 0
- Ed25519 signatures:   1098
- Verification time:    11.92 seconds

One transaction containing JoinSplits:
- Block size:           1998459 bytes
- Transactions:         1
- Proofs:               1176
- ECDSA signatures:     0
- RedJubjub signatures: 0
- Ed25519 signatures:   1
- Verification time:    12.47 seconds
```

**Comment by solardiz** [comment]
Are these benchmarks single-threaded? Will the production code perform verification from multiple threads, and thus be several times faster on those CPUs?

**Comment by str4d** [comment]
@solardiz yes, they are single-threaded. The above benchmarks use the current production code.

**Comment by str4d** [comment]
In https://github.com/zcash/zcash/issues/3690#issuecomment-462994352 I mis-understood @ebfull's comment to me: the verification cost for a single proof can be reduced by around 80% via **batching**. This means it can be easily applied to many proofs within a transaction (by batching inside the existing Sapling verification context), but can't be as easily applied to many proofs across many transactions (it would require some additional accumulator context, which is more complex to implement). So the "one Sapling spend per transaction" benchmark is likely to be the most relevant to us.

**Comment by the-metalworker** [comment]
A few comments/ questions after reading through the thread:

> @zookozcash: Updated [the O.P.](https://github.com/zcash/zcash/issues/3690#issue-381886781) to mention that currently the average block time in Ethereum is 12.5 seconds.

This is not a useful comparison imo. Ethereum is able to get away with such short block times because they use GHOST and also their block sizes (in byte terms) are very small compared to Zcash or Bitcoin, so faster to verify. So unless you are also proposing to use GHOST it is confusing to compare Zcash block time to Ethereum.

Additional questions:

- I see discussions about miners here, but has there been any discussion of the impact on home full node operators i.e. what kind of increased hardware/ bandwidth costs they will have to incur to keep up with the chain tip and store the full chain on disk? I run my own full node to get the most privacy / security using Zcash and will not adopt any changes that impedes my ability to do so.

- Why reduce the block time rather than increase the block size limit? As @lindanlee points out "45 minutes and 30 minutes are both too slow" so reducing the block time is not a significant UX improvement. However increasing the block size limit would have the same positive effect on throughput, and you wouldn't have to worry about how this effects the emission or founder's reward schedule since block times would stay the same.

**Comment by tearodactyl** [comment]
What's the problem being solved here, faster time to some magic number of confirmations? Not fast enough to buy coffee with, since that's so important for a privacy coin.

Because Zcash blockchain is not at all swamped with transactions (but please do correct me if I'm wrong). It's been running at below 5K transactions / day for maybe ten months now, even more like 4K, excluding coinbase. That's 7 transactions / block.

**Comment by Eirik0** [comment]
Closing this ticket because ZIP208 has been merged and we are currently working on implementing it in zcashd v2.0.7.

**Comment by bitzec** [comment]
Was  all this  work worth it at all.. ? Sounds like zec needs faster transactions .. whats the reason for this anyway ?  I dont get it .. marketing ?

**Comment by petertodd** [comment]
> Expert opinion: I've heard from **Bitcoin Core developers**, Vitalik Buterin, Arthur Breitman, James Prestwich, Daira Hopwood, and Emin Gün Sirer,

(emphasis mine)

@zookozcash I'm curious, who did you talk too?

**Comment by bitzec** [comment]
@petertodd  what are the benefits of shorter blocktarget    sir ?
