### ISSUE TITLE
RPC call z_exportviewingkey is not supported for sapling addresses

### ISSUE THREAD

**Issue by Tomas-M** [zcash/zcash#3695]
RPC call `z_exportviewingkey` is not supported for sapling addresses (zcashd version 2.0.1)

    main.rpc('z_exportviewingkey',["zs123456..."])
    --> throws error: Currently, only Sprout zaddrs are supported

I would expect it to print an exported key for sapling shielded address.
There is a TODO in source codes (rpcdump.cpp) so you maybe forgot to implement it.
Please consider adding in 2.0.2

**Comment by ioptio** [comment]
That call is not supported yet. Here's the associated ticket: https://github.com/zcash/zcash/issues/3060

Let's continue the discuss in that ticket and close this one as a duplicate.
