### ISSUE TITLE
bash: ./src/zcashd: No such file or directory

### ISSUE THREAD

**Issue by RussiaVk** [zcash/zcash#3696]
~/zcash/./src/zcashd -daemon
help

**Comment by daira** [comment]
This indicates that the zcashd build didn't complete successfully. Did you follow all of the instructions at https://zcash.readthedocs.io/en/latest/rtd_pages/user_guide.html ? What platform are you using, and were any error messages shown in the build output? (Usually it's sufficient to give the last 100 lines or so of the build output to see what went wrong.)

**Comment by daira** [comment]
How much memory do you have free? Typically around 8 GB is needed to build zcash.

**Comment by ioptio** [comment]
We're going to time out on this ticket but feel free to reopen if you come back to this with the same issue.
