### ISSUE TITLE
support for fundrawtransaction with includingWatchOnly outputs 

### ISSUE THREAD

**Issue by piyush-bittmax** [zcash/zcash#3700]
Hey,
I need to call fundrawtransaction rpc which uses utxos from watch only addresses too.
I was able to achieve this in bitcoin by using importpubkey and then calling fundrawtransaction with an includeWatching flag set to true.
But, in zcash, there isn't support for this flag in rpc call.

Can this flag be introduced in fundrawtransaction rpc?
https://bitcoincore.org/en/doc/0.16.0/rpc/rawtransactions/fundrawtransaction/

Currently, I am running zcash 2.0.1 version.

Thanks

**Comment by daira** [comment]
As far as I know there's no obstacle to including this. I think it was supported upstream in https://github.com/bitcoin/bitcoin/pull/6415 . In fact I believe this was almost included in a previous round of porting (https://github.com/zcash/zcash/pull/2100#issuecomment-284107638), but didn't quite make the cut.

**Comment by piyush-bittmax** [comment]
@daira : thanks for your reply.
will be waiting for this.

**Comment by piyush-bittmax** [comment]
Hello,
Any update on this?

Thanks

**Comment by bitcartel** [comment]
@piyush-bittmax Are the addresses you watch mostly P2PKH?  Any P2SH?

**Comment by piyush-bittmax** [comment]
they are P2SH
