### ISSUE TITLE
Debian Binary packages: Insight/blocks API calls result in 400 method not found 

### ISSUE THREAD

**Issue by chersicm** [zcash/zcash#3701]
### Description
Installing zcash binaries, as by [documentation](https://zcash.readthedocs.io/en/latest/rtd_pages/install_debian_bin_packages.html), and then wrapping the zcash daemon with bitcore-node-zcash (+ insight-api-zcash) results in some Insight API endpoints being unreachable (e.g. /blocks, /addr).

#### Install zcash binaries:
1. wget -qO - https://apt.z.cash/zcash.asc | sudo apt-key add -
2. echo "deb [arch=amd64] https://apt.z.cash/ jessie main" | sudo tee /etc/apt/sources.list.d/zcash.list
3. sudo apt-get update && sudo apt-get install zcash
#### Install nodejs
4. curl -sL https://deb.nodesource.com/setup_8.x | bash -
5. sudo apt-get install -y nodejs
6. sudo npm install -g npm@latest
#### Install bitcore-node + Insight API
7. sudo npm -g install zcash-hackworks/bitcore-node-zcash --unsafe-perm
8. cd
9. bitcore-node create zc
10. cd zc
11. bitcore-node install zcash-hackworks/insight-api-zcash
12. zcash-fetch-params --testnet
####  Configuration
13. Extract [config_files.zip](https://github.com/zcash/zcash/files/2607983/config_files.zip) and place them at
14. ~/zc/bitcore-node.json (adjust home folder in bitcoind datadir)
15. ~/.zcash/zcash.conf
#### Launch bitcore-node
16. ~/zc/node_modules/bitcore-node-zcash/bin/bitcore-node start

### Expected behaviour
[http://127.0.0.1/insight-api/blocks](http://127.0.0.1/insight-api/blocks) should respond 200:

`{
"blocks": [],
"length": 0,
"pagination": {
"next": "2018-11-23",
"prev": "2018-11-21",
"currentTs": 1542931199,
"current": "2018-11-22",
"isToday": true,
"more": false
}
}`

### Actual behaviour + errors
Response: 400 method not found

### The version of Zcash:
2.0.1

### Machine specs:
- OS name + version:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):
- Linux kernel version (uname -a):
- Compiler version (gcc -version):

### Any extra information that might be useful in the debugging process.
I'm convinced the issue concerns the zcash daemon, because building from source (as suggested [here](https://github.com/str4d/insight-ui-zcash/issues/4#issuecomment-354084455)), the Insight API works as expected.

**Comment by ioptio** [comment]
You'll want to use the patched version here: https://github.com/zcash-hackworks/zcash-patched-for-explorer

**Comment by garethtdavies** [comment]
But this is the same issue as the testnet explorer (or is this not using the patched version?) https://explorer.testnet.z.cash/blocks

![zcash_blocks_solved_today___insight](https://user-images.githubusercontent.com/135382/49053374-be092100-f1a4-11e8-9cf3-8ad16cc1068c.jpg)

**Comment by ioptio** [comment]
@bitcartel @ianamunoz do you know about the explorer using the patched version or not?

@chersicm did you try the patched version? If not, can you?

**Comment by ianamunoz** [comment]
So explorer uses the patched version of zcash to enable a flag for the explorer. That is a bug in the API call specifically for the `/blocks` endpoint that we know about. I think it is failing somewhere in parsing v4 blocks?

So this issue could remain open to address that explorer cannot complete a known `blocks` api request. 

I think @radix42 runs this explorer: https://zcash.blockexplorer.com/

Which correctly parses the block endpoint? I had a thought also that it was just a socket error. I haven't looked at this in a bit.

**Comment by chersicm** [comment]
Are there any binaries of the patched version, or does it require building from source?
I'm using Docker so building from source is less appealing than installing binaries.

**Comment by ianamunoz** [comment]
@chersicm 
I've been using this [Dockerfile](https://github.com/ianamunoz/docker-zcash/blob/master/Dockerfile)
for building zcashd.

I started a 'insight explorer' compose style stack:
https://github.com/ianamunoz/zcash-insight-explorer

I need to incorporate the patched version into the above still though.

Might give you a start until I get to incorporating the patched zcashd into the above docker stack.

**Comment by daira** [comment]
In my opinion the best way to some support problems with the insight-patched zcashd, is to merge the patches into master as described in #3708. That would ensure that binaries were available without any additional effort.

**Comment by mms710** [comment]
It looks like there's an issue for this in hackworks as well! I'm going to close the ticket here and we are actively working on the issue here: https://github.com/zcash-hackworks/zcash-patched-for-explorer/issues/2, which it turns out there's a PR for already. Heck yeah!
