### ISSUE TITLE
Decouple consensus changes from Network Upgrades in the zcashd code

### ISSUE THREAD

**Issue by daira** [zcash/zcash#3722]
The aim of this proposal is to increase decentralization by making it easier for Zcash forks, and Zcash itself, to develop consensus changes without their implementation being coupled to a particular Network Upgrade.

For Overwinter and Sapling, code implementing new or changed consensus checks was essentially gated on "is Overwinter active?" or "is Sapling active?". I propose to add a layer of indirection, so that such checks are gated on "is consensus change X active?", and there is separate configuration (still hard-coded, but easier for developers to change) of which consensus changes are activated by each upgrade.

This does introduce some complication, particularly when changes interact, and somewhat in testing. There would be no guarantee that arbitrary subsets of consensus changes would work together securely, and so security auditing still needs to be done on the combination of changes proposed for a specific upgrade.

If consensus changes are dependent on each other, then we would add code to assert that the dependencies hold after each configured upgrade. If developers of a fork disagree and want to try to disentangle those changes, they can do so.

As a motivating example, consider the "Harmony mining" dual-PoW proposal for Zcash Blossom. Many Zcash forks have already [changed their PoW](https://forum.zcashcommunity.com/t/list-of-all-coins-projects-on-equihash-asic-resistant-not-resistant/29085) to use Equihash parameters that decrease the advantage of ASICs relative to GPUs (or to use ProgPoW, in one case). Those forks may not see any advantage to the complexity of dual PoW, or may want to separate it from other components of Blossom. The above proposal allows them to easily do so without having to perform delicate surgery on consensus-critical code. (Even if the PRs adding dual PoW support were cleanly separated, omitting them would create a significant ongoing maintenance burden.)

This proposal also has advantages for the decentralised governance of Zcash itself. If a proposal by ZcashCo ends up being controversial, preparing a code fork to disable it will be accessible to any developer without needing a deep understanding of Zcash consensus code.

**Comment by daira** [comment]
Note (my personal opinion): this is not intended to make chain forks easier. Chain forks split the anonymity set and the developer community, and for the Zcash protocol there are specific privacy problems associated with reuse of nullifiers for notes duplicated in a chain fork. I believe that the wider privacy community will better achieve its goals by focussing on a small number of coins with strong development teams and larger user bases. However, I also believe that the software development and governance advantages outweigh any potential disadvantage of facilitating poorly motivated chain forks.

**Comment by daira** [comment]
As well as consensus checks per se, this would also apply to modifications of transaction and block formats. There's some trickiness here because a version group ID would need to express a *combination* of changes. But what you could do is to express the combination representing a new transaction format or block format, as a change that is dependent on its constituent changes.

**Comment by nuttycom** [comment]
Putting this back into in-progress; I'm factoring the machinery for this out from #4480
