### ISSUE TITLE
feature request: rpc introduce call for per-block fee statistics

### ISSUE THREAD

**Issue by salisbury-espinosa** [zcash/zcash#3723]
original: https://github.com/ElementsProject/elements/pull/185
related:
RPC: Introduce getblockstats to plot things https://github.com/bitcoin/bitcoin/pull/10757 
Qt: Show transaction size in transaction details window https://github.com/bitcoin/bitcoin/pull/8672

**Comment by ioptio** [comment]
We anticipate moving to a default fee as per https://github.com/zcash/zcash/issues/2942

@ianamunoz perhaps this is interesting to you

**Comment by daira** [comment]
We are removing fee estimation (#6591).
