### ISSUE TITLE
Feature Request: z_listreceivedbyaddress should return 'confirmations' and 'time' fields

### ISSUE THREAD

**Issue by adityapk00** [zcash/zcash#3724]
The RPC call `z_listreceivedbyaddress` currently returns only a handful of fields, but doesn't contain enough detail to make sense of the transactions. Most of the time, wallets need to make an additional call to `gettransaction` with the Tx hash to get details of the transaction like `time`, `confirmations` and `blockindex`.

### Expected behaviour
It would be awesome if `z_listreceivedbyaddress` returned these additional fields, so wallets wouldn't need to make an extra RPC call. 

```
  {
    "txid": "064f876326a1025233a7cbf08298jd92a3bc2ee2ab71e9a21be596fe7008e8fd",
    "amount": 1.99990000,
    "memo": "f6",
    "outindex": 0,
    "confirmations": 30984,
    "time": 1541108561,
    "change": false
  }
```

It would be quite easy to add in `rpcwallet.cpp`.
```
obj.push_back(Pair("confirmations", entry.confirmations));
if (pwalletMain->mapWallet.count(entry.jsop.hash)) {
    const CWalletTx& wtx = pwalletMain->mapWallet[entry.jsop.hash];
    obj.push_back(Pair("time", wtx.GetTxTime()));
}
```

### The version of Zcash you were using:
2.0.1

### Any extra information that might be useful in the debugging process.
This improves wallet performance almost 2x, as an additional `gettransaction` RPC call can be avoided.

**Comment by Eirik0** [comment]
Related: https://github.com/zcash/zcash/pull/3836

**Comment by holmesworcester** [comment]
FWIW, this would be helpful to us too in our work on [Zbay](https://zbay.app)
