### ISSUE TITLE
Feature Request: getblockchaininfo should return 'estimatedheight' while syncing

### ISSUE THREAD

**Issue by adityapk00** [zcash/zcash#3726]
When zcashd is syncing, the `getblockchaininfo` RPC call provides useful information about the syncing. However, it is missing the `estimatedheight` field, which is the estimated total height of the blockchain. The zcashd UI shows this on the console when syncing.

### Expected behaviour
`getblockchaininfo` should return the `estimatedheight` field when the blockchain is syncing. It is calculated in the code at `metrics.cpp:EstimateNetHeight()`, and can simply be returned in `blockchain.cpp:getblockchaininfo()`

I made a PR that has this change: 
https://github.com/zcash/zcash/pull/3727

### The version of Zcash you were using:
2.0.1

### Any extra information that might be useful in the debugging process.
Wallets can calculate this info and show it, but the calculation is tedious when done in an external UI wallet. It would be simpler, while syncing, to just show the estimated height that zcashd calculates

**Comment by daira** [comment]
Can you rebase or reopen the PR without the client name change, please?

**Comment by adityapk00** [comment]
Oops. Sorry, I'm new to working with github.

I made a new PR: https://github.com/zcash/zcash/pull/3727

**Comment by daira** [comment]
Thanks. See my comments there.

**Comment by LarryRuane** [comment]
Perhaps the `verificationprogress` field in the `getblockchaininfo` response is sufficient? I'd think wallet users would care about percentage synced more than estimated height. When `zcashd` was 99% synced (according to the metrics UI on the `zcashd` console window), this field returned as `"verificationprogress": 0.9979518801147546,`. For ZECwallet, this field can be trivially be added to the `GetLightdInfo()` response. (My thanks to @str4d for pointing out this field to me.)
