### ISSUE TITLE
whats the minimum memory required for blockchain sync only node ?

### ISSUE THREAD

**Issue by openalmeida** [zcash/zcash#3728]
not all node generate shielded transactions,
so memory requirements for block chain sync only node should list at

https://zcash.readthedocs.io/en/latest/rtd_pages/troubleshooting_guide.html#system-requirements

this is important for memory sensitive environment such as docker/vm instance, business cloud, etc.

**Comment by daira** [comment]
Sapling proof generation takes little enough memory, that the memory requirements for a sync-only node are basically identical to those of a full node that is generating proofs.

**Comment by daira** [comment]
I assumed that by "sync-only node" (which isn't a standard term), you meant a full node that doesn't generate proofs.

Generating proofs is no longer a significant proportion of a node's memory usage. So the memory recommendation is 4 GB regardless of whether proofs are generated.

**Comment by daira** [comment]
That looks like normal memory usage. "Dirty" means that there have been modifications to files in the repository that have not been committed.

**Comment by openalmeida** [comment]
> That looks like normal memory usage. "Dirty" means that there have been modifications to files in the repository that have not been committed.

thanks a lot,
suffix "dirty" is not dynamic created but hard coded as const string at:

```
https://github.com/zcash/zcash/blob/v2.0.2/share/genbuild.sh#L29-L31
```
- why i asked here because const string always mean something, such as puppy's or kitty's name etc.
  - whatever, it is just a user's warmth care or funny about Zcash.

feel tons of sorry to boring you, and, thanks again.
