### ISSUE TITLE
Define MultiRedDSA signature scheme

### ISSUE THREAD

**Issue by daira** [zcash/zcash#3729]
This is [MuSig](https://eprint.iacr.org/2018/068.pdf) adapted to RedDSA. It will be useful for #2914 and #782.

**Comment by daira** [comment]
Differences between RedDSA and the Schnorr variant used by MuSig:

* MuSig-Schnorr (in additive notation) uses verification equation [S] P = R + [c] vk.  RedDSA uses [h] (‑[S] P + R + [c] vk) = 𝓞. This is just rearrangement and multiplication by the cofactor, which does not affect the rest of the scheme.
* MuSig-Schnorr uses c = H(vk, R, M) where RedDSA uses c = H<sup>⊛</sup>(R || vk || M). The ordering of arguments does not affect anything else.
* RedDSA ensures that H<sup>⊛</sup> produces an output that is a uniform scalar. This does not affect anything else so far.

Now, when we move to the full MuSig scheme, we change the challenge computation to c<sub>i</sub> = H<sub>agg</sub>(〈L〉, vk<sub>i</sub>) · H<sup>⊛</sup>(R || vk~ || M), where vk~ = ∑<sub>i</sub> [a<sub>i</sub>] vk<sub>i</sub>. For RedDSA we need the resulting challenge to be uniformly distributed on {0..r<sub>G</sub>-1} where r<sub>G</sub> is the group order. We can guarantee this by instantiating H<sub>agg</sub>(B) as LEOS2IP<sub>ℓ<sub>H</sub></sub>(H("Zcash_RedJKeyAgg", B)) (mod r<sub>G</sub>-1) + 1. 〈L〉 is defined as "some unique encoding of the multiset of public keys [...]". Since H for RedJubjub is BLAKE2b-512 which is not subject to length extension attacks, and since each key encoding is fixed-length, we can simply take 〈L〉 as the concatenation of the keys. Actually I prefer to take B as 〈L〉 || I2LEOSP<sub>4</sub>(i) which is equivalent.

(MuSig treats the keys as a multiset. I prefer to treat them as a list, and require that the signatures be combined in a well-defined order. The reason is that when we're using the scheme for an aggregate signature, we need to show that replacing the individual signatures with the aggregate signature preserves the original semantics. But this depends on using the right key for each signature. We can always construct a multisignature scheme that treats the keys as a multiset from one that treats them as a list, just by sorting the keys in the client protocol, but we cannot easily do the reverse.)

**Comment by daira** [comment]
Actually, I think H<sub>agg</sub> doesn't strictly need to be uniformly distributed, just non-zero (mod r<sub>G</sub>). The multiplication by H<sup>⊛</sup>(R || vk~ || M) effectively blinds the output of H<sub>agg</sub> because R is random per signature, and therefore H<sup>⊛</sup>(R || vk~ || M) is uniformly distributed per signature.

**Comment by burdges** [comment]
Just curious, why put the message last?  Isn't that purely a defense against length extension attacks?

**Comment by daira** [comment]
Just because I prefer prefix-free encodings, and because standard RedDSA does.

Note that Chelsea Komlo is working on multisignature RedDSA now. I'll post her proposal here when it's ready.

**Comment by str4d** [comment]
Chelsea's proposal was FROST, which is now being adapted to RedDSA as ZIP 312: https://github.com/zcash/zips/issues/382. Closing this issue in favour of that one.
