### ISSUE TITLE
Allow transaction version 4 through Blossom upgrade

### ISSUE THREAD

**Issue by mms710** [zcash/zcash#3739]
Relates to https://github.com/zcash/zcash/issues/3655

**Comment by mms710** [comment]
We think this will take about a couple weeks of effort. After the latest round of feature culling this is still on the list to do as part of the Blossom upgrade.

**Comment by str4d** [comment]
Given the now-defined scope of the Blossom upgrade, I believe that this will be a no-op:

- #3672 (Harmony Mining) requires block header changes, not transaction format changes.
- #3673 (Split Founders' Reward) requires consensus rule changes to the contents of the coinbase transaction, but that does not require transaction format changes.
- #3690 (shorter block times) requires no format changes.

So I think all that needs to happen here is to document this in the network upgrade guide for Blossom.

**Comment by mms710** [comment]
Note that this goal will likely not require additional work for Blossom, but we're keeping this as a reminder for ourselves. The final goal selection for Blossom includes this goal, pursuing Harmony Mining (https://github.com/zcash/zcash/issues/3672), splitting the founder's reward (https://github.com/zcash/zcash/issues/3673) and Shorter Blocktimes (https://github.com/zcash/zcash/issues/3690).

**Comment by nathan-at-least** [comment]
I disagree that this will take no work for Blossom. This will be the first upgrade where we support multiple concurrent versions explicitly (although we've supported concurrent "legacy Bitcoin" versions).

Therefore, we need to ensure we have test plans and test code to catch any issues related to this plan, especially around activation time/logic.

**Comment by str4d** [comment]
See https://github.com/zcash/zcash/issues/3655#issuecomment-459152274 for why it's now a baseline requirement that the Zcash ecosystem handle the change in consensus branch ID at each network upgrade.

**Comment by daira** [comment]
Also, there's no reason to change the transaction version number at all in Blossom given the current scope. So this will indeed be a no-op.

**Comment by mms710** [comment]
@nathan-at-least thoughts on Daira's comment above? Do you think we can close this as a no-op?

**Comment by daira** [comment]
This was indeed a no-op.
