### ISSUE TITLE
Runtime Assert mechanism leaves user with no recovery command

### ISSUE THREAD

**Issue by mdr0id** [zcash/zcash#3747]
### Describe the issue
After removing the `blocks` dir from the zcash stack and attempting to start `zcashd`, a runtime assertion is thrown:

```
Messages:
- Error: Error: A fatal internal error occurred, see debug.log for details
[Press Ctrl+C to exit] [Set 'showmetrics=0' to hide]
zcashd: main.cpp:2897: bool ConnectTip(CValidationState&, CBlockIndex*, CBlock*): Assertion `pcoinsTip->GetSproutAnchorAt(pcoinsTip->GetBestAnchor(SPROUT), oldSproutTree)' failed.
Aborted`
```

This is expected from standard runtime asserts, but it is does not inform the user that they can actually gracefully recover from this. 

Per conditional, around this area of code, you can trigger a more informative error message (since it's not wrapped in an assert) to indicate this node can restart gracefully after issuing `zcashd -reindex`

I was not able to find the suggested core_dump file, so I'm not sure if the `SIG` is getting handled properly by the system to generate the core_dump file. Looking forward, we will likely run into similar issues on Windows. 

A few of us have discussed tools to overcome this cross-platform, so we can provide details later.

### Can you reliably reproduce the issue? 
Yes

#### If so, please list the steps to reproduce below:
1.  rm -rf blocks dir
2.  start zcashd

### Expected behaviour
A message should at least indicate a recovery procedure for the user, since earlier conditionals will indicate this. 

### Actual behaviour + errors
zcashd throws an assert and the node stops

### The version of Zcash you were using:
v2.0.2 (documented in version 1+ though, see issues related to bool ConnectTip(CValidationState&, CBlockIndex*, CBlock*): Assertion )

**Comment by Eirik0** [comment]
It may not be possible to recover from this state. We have opened a ticket to do better error reporting: https://github.com/zcash/zcash/issues/4096

**Comment by vwas2** [comment]
users unable to recover means: network stress and frustration due resync. 
current approach 'sync new from scratch'  puts users off and imo is unacceptable. eg https://github.com/zcash/zcash/issues/2228#issuecomment-358984297

expected: if checksum mismatch, get the extent of damage, and overwrite via network data.
