### ISSUE TITLE
Place buildbot config into revision control and modularize it.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#375]
An important issue here is to split out the secrets (such as passwords) into a separate thing which can be imported by the config.  The rest of the config can be in a repository here on github.

**Comment by ageis** [comment]
I realize this ticket is closed, but I just want to note that the bbotzc repo shall be deprecated in favor of the new processes for configuring Buildbot in the Electric-Coin-Company/infrastructure repository.

Ansible allows us to template the `master.cfg` file, and store the secrets in an AES256-encrypted vault (so they can be safely committed to version control). Additionally, we have a working Vagrant VM for our CI server, so it can be tested locally.
