### ISSUE TITLE
Fix transfer issues and logs when coinbase is unprotected

### ISSUE THREAD

**Issue by growlot** [zcash/zcash#3750]
Hello,

As you know there is an option to unprotect coinbase, https://github.com/zcash/zcash/blob/66e39a0dd6ffd77bcbede1943195dd456f859cd6/src/chainparams.cpp#L86

I did try to transfer coinbase funds after set as `consensus.fCoinbaseMustBeProtected = false;`
But I had some issues and invalid logs when I did try to transfer coinbase funds from mineraddr/taddr to taddr directly.

**Comment by daira** [comment]
Yes this option being `false` probably hasn't been tested at all, except in regtest mode. I would like to change this for NU3 (instead allowing coinbase transactions to directly shield the fee), so we'd better fix whatever the problem is here.

**Comment by ioptio** [comment]
This is a consensus rule, not an option (yet).

**Comment by nathan-at-least** [comment]
@daira's suggestion blocks on #2488.

**Comment by daira** [comment]
Protected coinbase is not intended to be a configurable feature; the flag was added only to make some upstream tests work.
