### ISSUE TITLE
Remove ability to create new Sprout addresses from RPC calls

### ISSUE THREAD

**Issue by jackgavigan** [zcash/zcash#3752]
Remove the ability to create Sprout shielded addresses from zcashd in order to reduce usage of the Sprout shielded pool. 

This is the logical next step after #3064.

**Comment by daira** [comment]
Either this or #3381 is necessary to enable a zcashd wallet that doesn't have to be backed up every time new keys are generated (or else risk losing funds).

**Comment by daira** [comment]
What's the plan for this ticket? After [ZIP 212](https://zips.z.cash/zip-0212) activates, it will still technically be possible to send funds to new Sprout addresses, provided that they come from other Sprout addresses. But it won't be particularly useful.

**Comment by nuttycom** [comment]
Fixed in #5474
