### ISSUE TITLE
./src/zcashd - no such file or directory

### ISSUE THREAD

**Issue by johnbokker** [zcash/zcash#3753]
[no other information given]

**Comment by daira** [comment]
This message usually indicates that the build failed. Please make sure you follow the build instructions precisely, and give your platform and the last 100 lines of build output.

**Comment by daira** [comment]
https://chat.zcashcommunity.com/channel/zcash-mining?msg=oiZvFyATgFfHTcdek

**Comment by ioptio** [comment]
Feel free to reopen this if you're still having issues.
