### ISSUE TITLE
Upgrade the buildbot configuration to use docker.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#376]
See also: #375

**Comment by ageis** [comment]
As previously noted, we have Homu to manually approve building PRs. However, there could still be some theoretical benefits to containerization of the builds. I'm capable and enthusiastic about Docker, so I'll be continuing to think about it, but I don't think it's a high priority or that the existing uncontained processes pose a significant risk.

**Comment by nuttycom** [comment]
Superseded by `tekton`.
