### ISSUE TITLE
Display the network (mainnet, testnet, regtest) on the metrics screen

### ISSUE THREAD

**Issue by daira** [zcash/zcash#3760]
I was just looking at a node's metrics screen and couldn't remember whether it was running mainnet or testnet. The text starts with "Thank you for running a Zcash node!", which would be an ideal place to put this information (e.g. "Thank you for running a Zcash testnet node!"). I realise most people don't run both mainnet and testnet nodes, but this would be useful for those of us who do.

**Comment by josephnicholas** [comment]
I will work on this please.

**Comment by daira** [comment]
This is already being fixed by #3765.
