### ISSUE TITLE
digital signature algorithm used in ZCASH

### ISSUE THREAD

**Issue by kbyb0417** [zcash/zcash#3764]
I am not sure which digital signature algorithm is used in ZCASH.
I found some website said it used ECDSA, and some said it change to Ed25519.

**Comment by daira** [comment]
Transparent input signatures use ECDSA over the secp256k1 curve, as in Bitcoin.

Sprout JoinSplit signatures use Ed25519.

Sapling spend authorization and binding signatures use RedDSA, a rerandomizable signature scheme similar to Schnorr and EdDSA, over the Jubjub curve.

**Comment by ioptio** [comment]
Feel free to reopen this if you have more related questions.

**Comment by schadokar** [comment]
> Transparent input signatures use ECDSA over the secp256k1 curve, as in Bitcoin.
> 
> Sprout JoinSplit signatures use Ed25519 (as implemented in libsodium 1.0.15).
> 
> Sapling spend authorization and binding signatures use RedDSA, a rerandomizable signature scheme similar to Schnorr and EdDSA, over the Jubjub curve.
> 
> Please let us know whether you have any further questions.

Exactly which algorithm then used in ZCASH? I was reading about zcash and unable to find the exact answer for this. There are many terms used Sprout JoinSplit, Sapling in the documentation.

**Comment by daira** [comment]
We use three different signature algorithms. It might be useful to refer to [section 7 of the protocol spec](https://zips.z.cash/protocol/protocol.pdf#consensusfrombitcoin) which describes transaction formats and how they are different from Bitcoin.

Signatures on transparent inputs [work exactly as in Bitcoin](https://medium.com/@blairlmarshall/how-does-ecdsa-work-in-bitcoin-7819d201a3ec), using ECDSA. Signatures are typically encoded in scripts, again using the same script system as Bitcoin.

"Sprout" is the shielded protocol implemented at launch, which uses [Ed25519](https://ed25519.cr.yp.to/ed25519-20110926.pdf) as described in [section 5.4.5 of the protocol spec](https://zips.z.cash/protocol/protocol.pdf#concretejssig). A "JoinSplit description" is the encoding of part of a transaction, with two Sprout shielded inputs and two Sprout shielded outputs. Any transaction that has at least one JoinSplit description must have a JoinSplit signature, using Ed25519.

"Sapling" is the more efficient shielded protocol that was activated in October 2018. It uses a custom signature scheme called RedDSA, described in [section 5.4.6 of the protocol spec](https://zips.z.cash/protocol/protocol.pdf#concretereddsa). When this scheme is used over the Jubjub elliptic curve, it is called RedJubjub. There is one RedJubjub signature to authorize each Sapling spend. Any transaction that has at least one Sapling spend or output has another RedJubjub "binding signature", described in [section 4.12 of the protocol spec](https://zips.z.cash/protocol/protocol.pdf#saplingbalance).
