### ISSUE TITLE
Implement consensus rules to enforce our counterfeiting policy

### ISSUE THREAD

**Issue by mms710** [zcash/zcash#3768]
Potential NU3 goal - implement consensus rules to enforce our counterfeiting policy. We have documented a policy regarding counterfeiting here: https://z.cash/blog/defense-against-counterfeiting-in-shielded-pools/ and the proposed goal is to implement consensus rules where possible to enforce this policy.

**Comment by mms710** [comment]
Relates to https://github.com/zcash/zcash/issues/2351

**Comment by bitcartel** [comment]
Implemented by #3768
