### ISSUE TITLE
gen_base58_test_vectors.py issue

### ISSUE THREAD

**Issue by MarkLTZ** [zcash/zcash#3772]
Hi there!

I would like to create `base58_keys_valid.json` and `base58_keys_invalid.json` using the contrib script [gen_base58_test_vectors.py](https://github.com/zcash/zcash/blob/master/contrib/testgen/gen_base58_test_vectors.py), but this is not yet modified for working with multi-byte prefix required for zcash and  its forks.

Could you please fix it or tell me if exists another script to generate these 2 files?

Thanks,
Mark

**Comment by daira** [comment]
At first sight that script doesn't look difficult to fix; the code already supports multi-byte prefixes, and it's just the `prefix` elements of the `templates` array that need changing: https://github.com/zcash/zcash/blob/8df7a073ce13ec057b94b5a813bb5534cdfa6809/contrib/testgen/gen_base58_test_vectors.py#L27-L38

You can find the prefixes in section 5.6.1 of the [protocol spec](https://github.com/zcash/zips/blob/master/protocol/protocol.pdf): they are:
* `(0x1C, 0xB8)` in place of `(PUBKEY_ADDRESS,)`
* `(0x1C, 0xBD)` in place of `(SCRIPT_ADDRESS,)`
* `(0x1D, 0x25)` in place of `(PUBKEY_ADDRESS_TEST,)`
* `(0x1C, 0xBA)` in place of `(SCRIPT_ADDRESS_TEST,)`.

Let us know whether those changes work, and we can file a PR.

**Comment by ioptio** [comment]
@daira do you think a PR is helpful here or should we close the ticket if there's no response?

**Comment by daira** [comment]
When making the PR, if you can make all of the {``PUBKEY_ADDRESS``, ``SCRIPT_ADDRESS``, ``PUBKEY_ADDRESS_TEST``, ``SCRIPT_ADDRESS_TEST``, ``PRIVKEY``, ``PRIVKEY_TEST``} constants into tuples rather than single byte values, that would be more elegant.

**Comment by LitecoinZ** [comment]
Take a look, please

**Comment by ioptio** [comment]
Thanks, we'll have to review that next.
