### ISSUE TITLE
Need to fix libsodium download url

### ISSUE THREAD

**Issue by growlot** [zcash/zcash#3775]
I notice libsodium-1.0.15 was moved to `old` folder.
https://github.com/zcash/zcash/blob/8df7a073ce13ec057b94b5a813bb5534cdfa6809/depends/packages/libsodium.mk#L3
To:
`$(package)_download_path=https://download.libsodium.org/libsodium/releases/old/`

**Comment by ioptio** [comment]
Should be fixed by https://github.com/zcash/zcash/pull/3766
