### ISSUE TITLE
Set up Continuous Integration build/testing for mobile platforms.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#380]
We're currently setting up buildbot, so if we want to be integrated with that system we would need to setup the target mobile platforms as buildslaves.

@tromer suggests in https://github.com/Electric-Coin-Company/zerocashd/issues/364#issuecomment-151273418 that using IaaS CI for those platforms could be convenient and he already uses Scaleway for libzerocash testing.

**Comment by nuttycom** [comment]
Not relevant for zcashd.
