### ISSUE TITLE
listtransactions sort

### ISSUE THREAD

**Issue by EremitCash** [zcash/zcash#3801]
Can i specify sort order with listtransactions command？

**Comment by garethtdavies** [comment]
There is no (documented) argument to specify sort order but you could pipe the output of `listtransactions` into a tool such as jq (https://stedolan.github.io/jq/).  So this would sort by confirmations:

`zcash-cli zcash-cli listtransactions | jq 'sort_by(.confirmations)'`

To reverse the order add another filter.

`zcash-cli listtransactions | jq 'sort_by(.confirmations)' | jq reverse`

**Comment by ioptio** [comment]
Worth investigating if bitcoin does any sorting of transactions. We'll check into it.

**Comment by ioptio** [comment]
Doesn't seem like bitcoin supports it and adding this feature is likely not a priority unless there's more demand shown since other tools can sort.
https://bitcoincore.org/en/doc/0.17.0/rpc/wallet/listtransactions/

**Comment by ioptio** [comment]
We can assume this won't be added so we're going to close this. Feel free to reopen if you have further discussion points.
