### ISSUE TITLE
Migrate all Python code to Python 3 before 1/1/20 when Python 2 reaches end of life

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#3802]
https://pythonclock.org/

https://www.python.org/dev/peps/pep-0373/#update

https://devguide.python.org/#status-of-python-branches

Given the status of Python branches, we should consider targeting Python 3.7.

**Comment by oxarbitrage** [comment]
I think this need to be closed by https://github.com/zcash/zcash/pull/4236

**Comment by mdr0id** [comment]
Agreed, major components are updated. Closing.
