### ISSUE TITLE
Consider Dimitry's ZIP 307 improvements

### ISSUE THREAD

**Issue by lindanlee** [zcash/zcash#3803]
This is old (Dec 2017!):

Hi, everyone!
We are working on a privacy focused non-custodial “Snark wallet” Android app with Zcash Sapling shielded txn’s support.
1. We would like to contribute to ZIP307 with the suggestion, which could reduce traffic required to detect incoming inputs by 3.5 times, through a soft-fork.
Have a look, please! We hope Zcash engineers will embrace it!
2. We need to check clock with Zcash wallet team lead Linda & Jack.
Looking forward for corresponding inputs to decide, should we wait for Zcash reference code implementation or would it be faster to write our own implementation & introduce it to zcash community afterwards?
In the latter case, we do not want to waste our resources & end up with two independent code implementations, our own & reference Zcash.
------------------
The Proposal.

The idea is based on the following prerequisites:

1. Retrieving the absolute minimal data set, sufficient for detection of an incoming input.
2. Creating a tag to verify that the minimal data is decrypted correctly.
3. Keeping computation cheap in terms of smart-phone battery budget constraints.
4. Feasibility of enforcing the changes through a soft-fork.

Implementation
As long as symmetrical and asymmetrical encryption is used for notes, a symmetrical key K should be obtained first to decrypt the note.

let sharedSecret = KASapling.Agree(ivk, epk)
let Kenc = KDFSapling(sharedSecret, epk)

epk is all we need to derive the symmetrical key. However, current Zcash implementation does not provide a mechanism to validate the derived K unambiguously without downloading the note.

Without changing the protocol such a check can be done through a collision of the K and epk in the checksum. Thus, the equation

CRC8(K)==CRC8(epk)

Is a sign (with high probability) that there is an input note for the recipient.

Having detected such a sign, the recipient downloads a bucket with notes and other necessary data to create the outputs.

The size of the bucket and the retrieving interval randomization depend on privacy concerns of the recipient’s software implementation. However, Zcash team may wish to set the standard for reference.

To create a note tagged with such a signal the sender should brute force the epk to get a described CRC8 collision.

The described approach allows detecting input notes by downloading 32 bytes of each note, compared to 116 originally proposed in ZIP307.

To receive the signals  the service described in ZIP307 should be complemented with the following (bold) endpoint:

service CompactTxStreamer {
    rpc GetEPK(RangeFilter) returns (stream EPK) {}

    rpc GetLatestBlock(ChainSpec) returns (BlockID) {}
    rpc GetBlock(BlockID) returns (CompactBlock) {}
    rpc GetBlockRange(RangeFilter) returns (stream CompactBlock) {}
    rpc GetTransaction(TxFilter) returns (FullTransaction) {}
}

Light client should include a logic for epk brute force (in the cource of txn creation), so, while executing, the following condition is met: CRC8(epk) == CRC8(K).

Thanks!
Looking forward for reply!

**Comment by str4d** [comment]
This was already posted in https://github.com/zcash/zcash/issues/3638#issuecomment-445239591 and the decision by the acting ZIP editor was that it should be proposed as a separate ZIP, not a modification to ZIP 307.
