### ISSUE TITLE
About Quadratic Arithmetic Program(QAP)

### ISSUE THREAD

**Issue by kbyb0417** [zcash/zcash#3805]
### Describe the issue
For now, I'm learning about how zk-snarks work.
And I have some question about QAP.

1. In my memory, I thought I had read some paper(website) said that in a ZCASH system, we need to construct QAP when it is in SETUP step, so just construct QAP one time for all transaction?

2. I know we need to transform formula to R1CS to QAP. But how to transform transaction to formula?

**Comment by daira** [comment]
1. There is a fixed QAP for each circuit (the Sprout JoinSplit circuit, the Sapling Spend circuit, and the Sapling Output circuit). In practice we write an implementation for each circuit that calls into a proving library (e.g. bellman) to construct the QAP. The circuit is implemented in its R1CS form (with whatever abstraction mechanisms are provided by the library and implementation language); we don't go via an arithmetic circuit.

2. See section 4.15 and the whole of Appendix A of the [protocol spec](https://github.com/zcash/zips/blob/master/protocol/protocol.pdf).

**Comment by ioptio** [comment]
Closing this but feel free to reopen if you have follow up questions or ask in the community: https://chat.zcashcommunity.com
