### ISSUE TITLE
RPC Tests Fail Because of Python3

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#3808]
The RPC tests fail for me because I have python3:

```
$ ./qa/zcash/full_test_suite.py
...
Running stage rpc
=================

=== Running testscript paymentdisclosure.py ===
  File "/home/firexware/zcash/zcashfresh1/qa/rpc-tests/paymentdisclosure.py", line 6
    import sys; assert sys.version_info < (3,), ur"This script does not run under Python 3. Please use Python 2.7.x."
                                                                                                                    ^
SyntaxError: invalid syntax
!!! FAIL: paymentdisclosure.py !!!

=== Running testscript prioritisetransaction.py ===
  File "/home/firexware/zcash/zcashfresh1/qa/rpc-tests/prioritisetransaction.py", line 6
    import sys; assert sys.version_info < (3,), ur"This script does not run under Python 3. Please use Python 2.7.x."
                                                                                                                    ^
SyntaxError: invalid syntax
!!! FAIL: prioritisetransaction.py !!!

=== Running testscript wallet_treestate.py ===
  File "/home/firexware/zcash/zcashfresh1/qa/rpc-tests/wallet_treestate.py", line 6
    import sys; assert sys.version_info < (3,), ur"This script does not run under Python 3. Please use Python 2.7.x."
                                                                                                                    ^
SyntaxError: invalid syntax
!!! FAIL: wallet_treestate.py !!!

=== Running testscript wallet_anchorfork.py ===
  File "/home/firexware/zcash/zcashfresh1/qa/rpc-tests/wallet_anchorfork.py", line 6
    import sys; assert sys.version_info < (3,), ur"This script does not run under Python 3. Please use Python 2.7.x."
                                                                                                                    ^
SyntaxError: invalid syntax
!!! FAIL: wallet_anchorfork.py !!!
```
I can't figure out an easy workaround so I'm going to change the first line in those files from `#!/usr/bin/env python` to `#!/usr/bin/env python2`.

**Comment by defuse** [comment]
Related: https://github.com/zcash/zcash/pull/3781, https://github.com/zcash/zcash/pull/3780 (maybe this conflicts with that work)

**Comment by rex4539** [comment]
I was under the impression that the plan was to migrate the scripts to Python3, instead of forcing the tests to run with Python2.

https://github.com/zcash/zcash/issues/3802

**Comment by daira** [comment]
Please note that #3538 intentionally changed the shebang lines from ``python2`` to ``python``, in order to get them working on MacOS. It was known that this would break Arch Linux: https://github.com/zcash/zcash/pull/3538#issuecomment-425625091 Which distribution are you using, @defuse?

**Comment by daira** [comment]
(Note that if running the current tests under Python 3 didn't break at the assert line, then it would still break in more subtle ways.)

**Comment by defuse** [comment]
I'm on Arch Linux. Okay, I'll figure out a workaround (I was experimenting with prefixing my PATH with a new directory and putting a symlink in there to python2 but that didn't work for some reason).

**Comment by mdr0id** [comment]
FWIW, some of this is being update here (https://github.com/zcash/zcash/pull/3799). Otherwise, there are a couple ways around this.

**Comment by mdr0id** [comment]
#3799 addresses this. Closing for now.
