### ISSUE TITLE
-reindex causes zcashd metrics screen to show "Downloading blocks" even though it isn't

### ISSUE THREAD

**Issue by zebambam** [zcash/zcash#3813]
Downloading blocks | A / ~X (y%)

Is a count of reading them off the disk, rather than downloading them from peers, so there's a speed change part way through if you're re-indexing from somewhere pretty old that makes it hard, as a user, to know when you'll be fully synched.

**Comment by gladcow** [comment]
Hi. Just to be sure, all we need to fix this issue is to change output 'Downloading blocks" to "Reindexing blocks" in metrics according to reindex state?

**Comment by daira** [comment]
Yes; ideally, if you're reindexing but have already read all the blocks on disk and need to download more, it should switch to "Downloading".

**Comment by rex4539** [comment]
@steven-ecc this can be closed.

**Comment by daira** [comment]
Fixed by #4368.
