### ISSUE TITLE
Bonsai: private payments on a succinct (or partially succinct) blockchain

### ISSUE THREAD

**Issue by daira** [zcash/zcash#3818]
Bonsai is based on [Coda](https://codaprotocol.com/static/coda-whitepaper-05-10-2018-0.pdf)'s technique of verifying state transitions between trees of mutable accounts. In Coda, this requires you to know the states of both the sending and receiving accounts, which interferes with the needed privacy properties.

If we were to switch to a UTXO model and directly adapt Zerocash's commitment/nullifier protocol, then we'd have to be able to prove both updates of, and non-membership in the nullifier accumulator. That would be difficult and/or complicated to do efficiently.

Instead, Bonsai allows direct transfers between accounts for which you know the state; then transfers between accounts held by different users are built on top of that.

More precisely, each account has a *spending keypair* and a *receiving keypair*. Its *address* authenticates both public keys. There can be distinct accounts with the same address, at different positions in the account tree. You can do a transfer from account A to account B when:

* you know *both* tuples of account (address, position-in-tree, state); and
* you know the spending private key of A; and
* either account B is fresh, *or* you know the receiving private key of B.

A transfer between users is performed as follows. You transfer from your account to a fresh account with the recipient's address. You can do this using just the address. Then you privately tell the recipient what the state of that account is. From then on they can treat it as their account. Because it was created with their address, they have the spending private key so that they can send from the account, and they have the receiving private key so that they can send *to* it. As the sender of the transfer, you cannot do either. (It's important that you also can't send to it after its creation, since that would change its state, and then the recipient would not know the state.)

Optionally, the recipient can transfer from the fresh account to one that they created, but they can delay doing that.

This is similar to the intended usage of the capability-based "simple money" protocol described as an example in [Cryptographic Capabilities for Distributed Smart Contracting](http://erights.org/elib/capability/ode/ode-capabilities.html), where accounts correspond to "purses" in that protocol.

Because the account tree is mutable (using version numbers that are incremented when money is transferred *out* of an account, exactly as in Coda), there are no nullifiers, and so no need to maintain an accumulator for a nullifier set.

Note that you still need private communication between users in the indirect transfer case. But this doesn't have to be on the block chain. In many cases you'll already have a communication channel between the sender and receiver, and can use that. (Making this channel resistant to traffic analysis is an orthogonal problem that you need to solve anyway if that's important for the use case.)

Alternatively, you can have a blackboard-based anonymous communication protocol (using key-private encryption) built into the currency as Zcash does now, but
* it only has to handle transfers between users that aren't already handled out of band;
* it doesn't have to be long-term persistent or resistant to rollbacks.

**Comment by daira** [comment]
@nathan-at-least wrote:
> When thinking about succinct blockchain tech, I believe one of the biggest potential advantages is to enable horizontal scalability, so that new validators/miners/consensus-nodes joining also increases the total network capacity.
>
> However, there are also "vertical scale" improvements possible with concise blockchains, and to me that seems like a much more limited payoff. (I assume it's the different between a constant capacity improvement versus horizontal scalability.)
>
> Can Bonsai help to enable horizontal scalability?

I don't understand what you mean by "vertical scale". The scalability improvement is horizontal in the sense that adding transaction aggregators increases capacity. But I haven't talked about that layer yet. For how Coda does it, see https://codaprotocol.com/blog/scanning_for_scans.html .

**Comment by bitsbetrippin** [comment]
Is there a reference diagram drawn up for this? I started based on what I was reading but have stopped figuring if there was something sketched up I could build a graphic based on the sketch? Draw on paper and I can turn it into a graphic.

![image](https://user-images.githubusercontent.com/26424771/52180370-19f6b400-27ab-11e9-9d07-8a2bc2f1e7c3.png)

**Comment by dlubarov** [comment]
Just to clarify, this is private in the sense that account state is hidden, but the transaction graph would be public right? Nullifiers or decoys seem necessary if we want to obscure the transaction graph.

> If we were to switch to a UTXO model and directly adapt Zerocash's commitment/nullifier protocol, then we'd have to be able to prove both updates of, and non-membership in the nullifier accumulator. That would be difficult and/or complicated to do efficiently.

Did you mean switch to an account model? Zcash seems like a UTXO model to me.

**Comment by str4d** [comment]
> Just to clarify, this is private in the sense that account state is hidden, but the transaction graph would be public right? Nullifiers or decoys seem necessary if we want to obscure the transaction graph.

The intention is for the transaction graph to be hidden. See @daira's comment:

> Because the account tree is mutable (using version numbers that are incremented when money is transferred out of an account, exactly as in Coda), there are no nullifiers, and so no need to maintain an accumulator for a nullifier set.

As an aside, I would certainly not support the introduction of a new shielded pool with worse privacy properties than our existing ones.

> Did you mean switch to an account model? Zcash seems like a UTXO model to me.

The neat thing is, it can be both! Each shielded pool (currently Sprout and Sapling) has its own payment model and address system, and funds are moved between them in the clear (revealing value). So it becomes trivial at a consensus level to have a new shielded pool use an account-based payment model, since it would have new addresses. It would probably be trickier at the UX level to make the addresses completely interoperable, but given that even in Sprout and Sapling we advocate treating an address as a "bucket of money", we're already part-way there in terms of user education and understanding.

**Comment by daira** [comment]
I think I've made a mistake in my adaptation of Coda, and that actually the above idea doesn't work, at least on its own :-(

The Coda blockchain is succinct in the sense that, for a system with a limit of N accounts, you have O(log N) data needed to verify an account state *given a witness for that account*. The witness is a Merkle tree path from the leaf account state to the current root. Because Merkle tree paths are self-authenticating (i.e. if you know the root, you can verify that you've been given a correct leaf state and path), you don't need to trust whoever gives you the path *for integrity*. So a light node can determine the correct root according to Nakamoto consensus (or PoS or whatever), and then be told the state of its account(s) by a party that is not trusted for integrity &mdash; but *is* trusted for privacy.

How do the account witnesses get updated? The answer is that some party or parties that see *all* of the transactions, must update them. So Coda is not fully succinct in terms of bandwidth usage. (It carefully isn't claimed to be, although this is a point that is easily misunderstood and is perhaps not clear from some descriptions of succinct block chains.)

In a Coda-style account-based model, each transaction modifies two account states. Suppose that we're maintaining a witness for account A, and we see a transaction that sends from account B to account C. Even though A and B may be unrelated, the path for B will intersect the path for A at some node, and each sibling hash in A's authentication path from that point up to the root will need to be updated. Similarly for A and C. This corresponds to updating of note witnesses in Zcash, and I had naively thought that updating account witnesses could be done in the same way. However, the difference is that in Zcash, changes to the note commitment tree are always additions at the next unused position. This does not give away information about which UTXOs are being spent. In Coda, on the other hand, changes to the account tree are at positions that reveal the accounts being spent from. (They also reveal the account being spent to, but we could always send to a fresh account to fix that; revealing the account we are spending *from* is the real problem.)

This doesn't have to leak amounts, since commitments to account states are hiding, and the SNARK can check that updates to account states are correct given these commitments. However, it does leak the transaction graph, which is an unacceptable privacy loss.

How do we fix this? Well, I think we have to go back to a more Zerocash-like protocol. On the other hand, I've worked out a reasonably SNARK-efficient way to implement the nullifier accumulator. I'll describe that in my next comment.

**Comment by daira** [comment]
Here's my suggestion for how to implement the nullifier accumulator. Consider a bucketed hash table of revealed nullifiers. (A cuckoo hash table is also possible, but a bucketed one is easier to describe.) Nullifiers are N bits long, and are assigned to buckets according to a B-bit prefix. Each bucket holds up to K nullifiers.

The buckets are assigned to leaves of a binary Merkle tree of depth B. Each leaf represents a list of K nullifier suffixes, each of length N-B bits. The B-bit prefixes are implied by the bucket position. The idea of the bucketing is so that we can reduce the tree depth B needed to obtain a low enough collision-or-full-bucket probability.

To maintain a witness, we store the authentication path for its bucket, and whenever a nullifier is added, we update this path. If the added nullifier is in the same bucket, we append it to the list and update the whole path. If the list either already contained this nullifier *or* already had K items, we consider this to be a double-spend. (Minor optimization: only store K-1 items and a "full" flag.)

Apart from writing an R1CS circuit to verify a bucket update, that's all there is to it. In principle this is not difficult; the only mildly tricky thing is working out where the new nullifier suffix needs to be added in the bucket representation. (If you include K-1 redundant bits then it's easy.)

It remains to choose N and B so that the probability of a false-positive collision (either an N-bit collision or a collision with a full bucket) is low. A similar, although not identical, problem was considered in the design of the post-quantum hash-based signature algorithm SPHINCS (see point 3 of [this post](https://tahoe-lafs.org/pipermail/tahoe-dev/2010-July/004587.html)). I'll work out the details tomorrow.

**Comment by daira** [comment]
There's a generalization of the above idea that might allow the Merkle tree depth B to be further reduced. Consider that the contents of a bucket represent a subset of the possible nullifiers that fall into that bucket. The representation suggested in the preceding comment is a full-flag and a list, such that:

* if the full-flag is set, then the represented set is all possible nullifiers with the given prefix;
* otherwise, the represented set is given by the elements of the list (ignoring order), each prepended with the given prefix.

However we can consider other concise approximate set representations.

We want to maximize the number of randomly chosen nullifiers m, so that we are able to bound below a security threshold the probability that when we add each of these nullifiers to the hash table one-by-one, some nullifier is already in the *approximated* set. (This is a generalization of the "balls-into-bins maximum load problem", which considers the case of exactly represented sets.)

In addition, we want maintaining the approximate set representation to be cheap, in an R1CS circuit, relative to increasing the depth B.

[To be continued...]

**Comment by dlubarov** [comment]
@str4d thanks for clarifying; glad to hear that the goal is a scheme which doesn't leak any transaction graph information.

@daira, it seems like that bucketing scheme could work nicely with honest users, but couldn't an attacker target a bucket and cause it to fill up? (I assume B would be small enough that finding partial collisions would be easy.) If an unlucky user's nullifier fell into that full bucket, presumably they wouldn't be able to spend their UTXO?

I think the most practical option may be to just use a sorted (not sparse) Merkle tree, giving nonmembership proofs with n hashes for 2^n nullifiers.

**Comment by daira** [comment]
Denial of service / destruction of other people's funds is a legitimate concern, but I believe it can be made infeasible (more analysis of that in following comments).

Yes, the tree needs to support an authenticated "assert not already present and insert" operation.

**Comment by swasilyev** [comment]
Does RSA-acc from [Scaling Verifiable Computation Using Efficient Set Accumulators](https://eprint.iacr.org/2019/1494) work here?

**Comment by daira** [comment]
This idea didn't work out; see the previous comment.
