### ISSUE TITLE
zcashd assertion `onlyMaybeDeadlock' failed (with --enable-debug build)

### ISSUE THREAD

**Issue by LarryRuane** [zcash/zcash#3823]
See also https://github.com/zcash/zcash/issues/1347

I built zcashd master branch with debugging enabled:
```
CONFIGURE_FLAGS='--enable-debug' zcutil/build.sh
```
Then I started `zcashd` with testnet configured, and the following appeared within a couple of minutes:
```
(.....)
Since starting this node 1 minutes, 57 seconds ago:
- You have validated 46 transactions!

Init message: Loading wallet...

[Press Ctrl+C to exit] [Set 'showmetrics=0' to hide]
zcashd: sync.cpp:112: void potential_deadlock_detected(const std::pair<void*, void*>&, const LockStack&, const LockStack&): Assertion 'onlyMaybeDeadlock' failed.
Aborted (core dumped)
```
The following appeared in `~/.zcashd/testnet3/debug.log`
```
2019-02-01 16:14:51 POTENTIAL DEADLOCK DETECTED
2019-02-01 16:14:51 Previous lock order was:
2019-02-01 16:14:51  pwallet->cs_wallet  wallet/walletdb.cpp:878
2019-02-01 16:14:51  (1) cs_SpendingKeyStore  wallet/crypter.cpp:486
2019-02-01 16:14:51  (2) cs_KeyStore  wallet/crypter.cpp:190
2019-02-01 16:14:51 Current lock order is:
2019-02-01 16:14:51  pwallet->cs_wallet  wallet/walletdb.cpp:878
2019-02-01 16:14:51  (2) cs_KeyStore  wallet/crypter.cpp:382
2019-02-01 16:14:51  (2) cs_KeyStore  wallet/crypter.cpp:190
2019-02-01 16:14:51  (1) cs_SpendingKeyStore  wallet/crypter.cpp:190
```
I wasn't able to reproduce this on mainnet. The difference may be that my testnet wallet contains a fairly substantial number keys, while in mainnet I have only a few. 

Note that it is common (I think) for some `POTENTIAL DEADLOCK DETECTED` messages to appear in `debug.log` but they don't cause an assertion failure, even with a debug build, because `onlyMaybeDeadlock` is `true`. (I will create a ticket for these, as I don't see an existing one.) These non-fatal deadlock detections involve a completely different set of locks.

This one is, apparently, a more "certain" deadlock -- although of course it's not at all certain, because, as far as I'm aware, no actual deadlock has occurred with a non-debug build (at least, there's no ticket that I can find). But this one is "certain" enough to trip the assertion.

I believe I have a simple fix for this; I will create the PR in a moment.

**Comment by daira** [comment]
That definitely looks like a classic lock-order violation to me.
