### ISSUE TITLE
Example Sapling address in documentation is not valid

### ISSUE THREAD

**Issue by yaccz** [zcash/zcash#3830]
Page https://zcash.readthedocs.io/en/latest/rtd_pages/addresses.html shows `zs1z7rejlpsa98s2rrrfkwmaxu53e4ue0ulcrw0h4x5g8jl04tak0d3mm47vdtahatqrlkngh9sly` as an example sapling address but it is only 77 chars long and does not validate against v2.0.2 zcashd:

```
$ zcash-cli z_validateaddress 'zs1z7rejlpsa98s2rrrfkwmaxu53e4ue0ulcrw0h4x5g8jl04tak0d3mm47vdtahatqrlkngh9sly'
{                
  "isvalid": false
}                 
```

**Comment by garethtdavies** [comment]
There's an open issue in the Zcash docs related to this here: https://gitlab.com/zcash-docs/zcash-docs/issues/19

**Comment by daira** [comment]
In my opinion we should simply say in the docs that the address is invalid, rather than giving a valid address that people could accidentally send to and lose funds.

**Comment by yaccz** [comment]
I'd be ok with removing the address. However, showing an invalid address as an adress example is confusing. If you think it would be good to still display an address that passes validation check, maybe something in the spirit of rfc 2606 could be created?

**Comment by ioptio** [comment]
Let's track this in the gitlab issue: https://gitlab.com/zcash-docs/zcash-docs/issues/19
