### ISSUE TITLE
Distribute per-block merkle tree deltas for light wallets

### ISSUE THREAD

**Issue by ebfull** [zcash/zcash#3835]
Light clients which are synchronizing with the network currently must receive every commitment from every transaction in order to update e.g. their local merkle tree witnesses, even though the information needed to perform such an update can be communicated per block such that it is logarithmic in the number of transactions in the block. You just distribute deltas of the treestate changes to users.

This avoids the need to change the merkle tree, and potentially gives us flexibility to change the granularity of the deltas over time.

**Comment by daira** [comment]
How is the data needed logarithmic in the number of transactions? It looks linear in the number of shielded outputs to me.

**Comment by ebfull** [comment]
Sorry, I meant logarithmic in the number of outputs.

**Comment by str4d** [comment]
As of 5.6.0, we now provide the roots of the depth-16 subtrees (#6336). This is more efficient for traversing longer chain intervals between receiving and spending a note: it isn't affected by per-block output count variability, and has an upper bound of around 10 MiB of data per pool (over half of which is amortized over all notes). Within the single subtree a note is in (at most 65k note commitments), per-block deltas could provide a small efficiency boost, but that is probably outweighed by the benefit of fetching the entire subtree and scanning it as a unit.
