### ISSUE TITLE
Certificate for `faucet.testnet.z.cash` expired

### ISSUE THREAD

**Issue by mms710** [zcash/zcash#3845]
Our cert for faucet.testnet.z.cash expired. Please renew it.

**Comment by garethtdavies** [comment]
Can we get this updated? We shouldn't be asking users to bypass these security warnings and there isn't an alternate testnet faucet.

**Comment by mms710** [comment]
This is being worked on now - we wanted to fix some underlying inefficiencies to make this easier to update in the future, which is why this is taking so long. Thanks for your patience and we haven't forgotten!

**Comment by mms710** [comment]
Sorry for the accidental ticket closure - this is still being worked.

**Comment by garethtdavies** [comment]
Bump. Following the instructions here about the webserver https://github.com/zcash-hackworks/zfaucet#configuring-the-webserver, which presumably is how you have configured it, I was able to simply get a Let's Encrypt cert via:

```
sudo apt install python-certbot-nginx
sudo certbot --nginx -d faucet.yoursite.com
```

then a simple `sudo certbot renew` will resolve this.

**Comment by str4d** [comment]
https://faucet.testnet.z.cash/ has been shut down (and the site currently resolves to a placeholder saying so, which currently has a valid unexpired certificate).
