### ISSUE TITLE
Develop a replacement CLI wallet that uses lightwalletd

### ISSUE THREAD

**Issue by zebambam** [zcash/zcash#3879]
This ticket describes beginning of the separation of payment secrets from the network daemon, in an attempt to begin operating with the modular benefits described in ticket #3877.

Develop a replacement for the builtin zcashd wallet. It should use OS level security controls to separate access to wallet secrets from zcashd, providing a boundary between zcashd access by the wallet except via lightwalletd, and wallet access by zcashd except by lightwalletd.

User secrets would then no longer have to be available directly by code running in zcashd process address space.

Let’s develop a replacement for zcash-cli wallet commands that is Sapling- and shielded-first (although works with Sprout and transparent) and keeps secrets away from the complexity of Zcashd.

Documentation will be required for both users and developers for this.

**Comment by defuse** [comment]
We could also build lightwalletd into `zcashd` as a module without replacing the actual wallet, to get a lightwalletd server in every node to make them more available (although there are privacy downsides to trusting light wallet servers run by random unknown people).

**Comment by geffenz** [comment]
NU5 and grants have been created since this ticket was made, making it obsolete. Zecwallet has accomplished this now. 

This is a useful future product requirement @steven-ecc
