### ISSUE TITLE
Indicate expired transactions in gettransaction

### ISSUE THREAD

**Issue by tromer** [zcash/zcash#3893]
Wallets UIs and other RPC users need to know if a sent transaction has expired (and thus will not get mined, and its consumed utxo's/notes are free for spending in other transactions).

Currently, if a transaction expires, the only direct indication given by RPC is that `gettransaction` starts returning `"confirmations": -1` for that txid. The `"confirmations": -1` is undocumented, and presumably is ambiguous (the transaction may by rejected for other reasons).

Indicate expiry explicitly in the `gettransaction` output, either as `"expired": true`" or as `"status": "expired"`.

Context:
* Expiry is recorded in the log as `Removing expired txid: ...` (courtesy of #3084).
* A common situation causing expired transactions is generating transations when not synced up (#3393). 
* Resending the expired transaction, and more generally spending the notes that were already attempted to be spent in the expired transaction, has privacy/linkability issues (#679).

**Comment by mms710** [comment]
Also adding the documentation project to update the documentation for this section:
Currently, if a transaction expires, the only direct indication given by RPC is that gettransaction starts returning "confirmations": -1 for that txid. The "confirmations": -1 is undocumented, and presumably is ambiguous (the transaction may by rejected for other reasons).
