### ISSUE TITLE
Rename librustzcash to avoid the perception that using it requires knowledge of Rust

### ISSUE THREAD

**Issue by daira** [zcash/zcash#3895]
On several occasions (most recently #3894) we've had to dispel the perception that librustzcash is a Rust-only thing or that using it requires knowledge of Rust. That's incorrect: it provides a C-compatible API, that doesn't use any particularly complicated types, and so can be used from a wide variety of languages. The fact that it (and libraries that it depends on) are written in Rust is an implementation detail, from that point of view.

A name change would of course involve some disruption, which would have to be weighed against the advantage of avoiding this misperception.

**Comment by daira** [comment]
I suggest just `libzcash` as the new name.

**Comment by mms710** [comment]
@ebfull @str4d What do you think about this proposed solution?

**Comment by str4d** [comment]
`librustzcash` is now a `zcashd`-internal library, and is not intended to provide a C-compatible API for other users. The migration to the `cxx` crate is increasing the coupling between `librustzcash` and the rest of `zcashd`, and it's not really feasible to use it standalone anymore.
