### ISSUE TITLE
Fix RPC getwalletinfo help message

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#3911]
During testing it was reported that the 'balance' field returned by RPC `getwalletinfo` might be incorrect.

It appears that the balance reported is the total confirmed ~and unconfirmed balance (but excluding immature coinbase)~ [EDIT: strikethrough as the filter ISMINE_SPENDABLE is applied] . `GetCredit` https://github.com/zcash/zcash/blob/master/src/wallet/wallet.cpp#L1922 and `GetAvailableCredit` https://github.com/zcash/zcash/blob/master/src/wallet/wallet.cpp#L2609 which are invoked by `GetBalance` https://github.com/zcash/zcash/blob/master/src/wallet/wallet.cpp#L2785.

Note that upstream Bitcoin has the same help message referring only to confirmed balance.
https://github.com/bitcoin/bitcoin/blob/717fd58c4ba5c64778fa9a8bf6bbf5ae1164df3f/src/wallet/rpcwallet.cpp#L2398

**Comment by bitcartel** [comment]
I have edited the above post to clarify that zcashd correctly shows the confirmed balance as expected.  Verifed on testnet.  The help message should clarify that this is the transparent confirmed balance.

**Comment by garethtdavies** [comment]
I just noticed that `getinfo` has a similar issue whereby it only reports a transparent balance whereas the RPC help message states `the total Zcash balance of the wallet`. 

On my testnet node:

```
./src/zcash-cli getinfo
{
  "version": 2000450,
  "protocolversion": 170007,
  "walletversion": 60000,
  "balance": 0.00000000,
  "blocks": 470857,
  ...
}
```

but there is a shielded balance:

```
./src/zcash-cli z_gettotalbalance
{
  "transparent": "0.00",
  "private": "0.2198",
  "total": "0.2198"
}
```

I guess this one should also be updated to be consistent with the `getwalletinfo` message.
