### ISSUE TITLE
Build script did not detect when an enabled option (proton) failed to build required library

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#3923]
When the `--enable-proton` option is passed to the build script, it continues to build zcashd even if there was a problem building/finding the proton library.
https://github.com/zcash/zcash/issues/3916

In this case, subsequently, the proton QA test would not run and thus, for CI testing passes, silently pass.

Expected behaviour would be for the build to fail if an option has been enabled and it is not possible to build zcashd with that option.

**Comment by mms710** [comment]
Next step is to research the build script and see why this is happening.

**Comment by str4d** [comment]
`--enable-proton` was removed in #4588.
