### ISSUE TITLE
Faster variable-base scalar multiplication in zk-SNARK circuits

### ISSUE THREAD

**Issue by daira** [zcash/zcash#3924]
The best general way to perform a variable-base scalar multiplication in an R1CS circuit, required (before this write-up) [9 constraints per scalar bit](https://github.com/zcash/zcash/issues/2230#issuecomment-427991414). There's a way that requires [8.5 constraints/bit](https://github.com/zcash/zcash/issues/2230#issuecomment-361074797), but only with a recoded scalar using a nonstandard and inconvenient digit set (e.g. [0, 1, 2, -1]).

I believe it's possible to implement this in **6 constraints/bit**, by using a modification of a technique from [[Eisentraeger, Lauter, and Montgomery]](https://arxiv.org/abs/math/0208038). They state their technique for curves in short Weierstrass form, but it is also applicable to Montgomery form. (Everything in this ticket is easily adapted to both.) The basic idea is that when we need to find [2] P + Q, where P is the accumulator in a double-and-add algorithm, we compute it as (P + Q) + P. This allows two optimizations:

* we do not need to compute the y-coordinate of the intermediate point P + Q (details below);
* we've replaced a doubling with an addition, which is more efficient in R1CS by one constraint.

Here we adapt [Eisentraeger, Lauter, and Montgomery]'s formulae to a Montgomery curve with equation B·y<sup>2</sup> = x<sup>3</sup> + A·x<sup>2</sup> + x. The constraint system for the incomplete addition P + Q = R on its own would be:

    (x<sub>Q</sub> - x<sub>P</sub>) × (λ<sub>1</sub>) = (y<sub>Q</sub> - y<sub>P</sub>)
    (B·λ<sub>1</sub>) × (λ<sub>1</sub>) = (A + x<sub>P</sub> + x<sub>Q</sub> + x<sub>R</sub>)
    (x<sub>P</sub> - x<sub>R</sub>) × (λ<sub>1</sub>) = (y<sub>R</sub> + y<sub>P</sub>)

When computing (P + Q) + P = S, we drop the last constraint which is only needed for y<sub>R</sub>. The outer addition requires the gradient λ<sub>2</sub> = (y<sub>P</sub> - y<sub>R</sub>)/(x<sub>P</sub> - x<sub>R</sub>), but we have:

    λ<sub>1</sub> = (y<sub>R</sub> + y<sub>P</sub>)/(x<sub>P</sub> - x<sub>R</sub>)

therefore

    λ<sub>2</sub> = 2·y<sub>P</sub>/(x<sub>P</sub> - x<sub>R</sub>) - λ<sub>1</sub>.

So in R1CS we can write:

    (x<sub>Q</sub> - x<sub>P</sub>) × (λ<sub>1</sub>) = (y<sub>Q</sub> - y<sub>P</sub>)
    (B·λ<sub>1</sub>) × (λ<sub>1</sub>) = (A + x<sub>P</sub> + x<sub>Q</sub> + x<sub>R</sub>)
    (x<sub>P</sub> - x<sub>R</sub>) × (λ<sub>1</sub> + λ<sub>2</sub>) = (2·y<sub>P</sub>)

and then complete the outer addition with:

    (B·λ<sub>2</sub>) × (λ<sub>2</sub>) = (A + x<sub>R</sub> + x<sub>P</sub> + x<sub>S</sub>)
    (x<sub>P</sub> - x<sub>S</sub>) × (λ<sub>2</sub>) = (y<sub>S</sub> + y<sub>P</sub>)

The practical problem with applying this technique in an R1CS circuit is that we cannot efficiently implement a conditional that sometimes computes [2] P, and sometimes [2] P + Q. (Conditionally replacing Q with 𝓞 does not work, because 𝓞 does not have an affine Montgomery representation.)

The following trick works around this. Suppose that r is of length n bits. Consider the following algorithm:

    Acc := [2] T
    for i from n-1 down to 0 {
        Q := r<sub>i</sub> ? T : −T
        Acc := (Acc + Q) + Acc
    }

For each step we can compute the y-coordinate of Q using:

    (y<sub>T</sub>) × (2.r<sub>i</sub> - 1) = (y<sub>Q</sub>)

This requires a total of 6 constraints per scalar bit. However, at the end we have computed [2<sup>n+1</sup> - (2<sup>n</sup> - 1) + 2·r] T = [2<sup>n</sup> + 1 + 2·r] T.

Not to worry. Suppose that we actually want to compute [2<sup>n</sup> + k] T, where k < 2<sup>n+1</sup>. Without loss of generality, assume k is odd (if it is even then add one to k and subtract T from the result). Let k = 1 + 2·r, and solve to give r = (k - 1)/2. Conveniently, this is equivalent to setting r = k >> 1 where >> is the bitwise right-shift operator.

So the full algorithm is:

    Acc := [2] T
    for i from n-1 down to 0 {
        Q := k<sub>i+1</sub> ? T : −T
        Acc := (Acc + Q) + Acc
    }
    return (k<sub>0</sub> = 0) ? (Acc - T) : Acc

This requires 4C for the initial doubling, n \* 6C for the loop, 3C to compute Acc - T, and 2C for the conditional. 

There is a minor further improvement by specializing for k<sub>n</sub> = 0. In that case the first iteration of the loop calculates Acc = [3] T, which can be implemented directly as [2] T + T saving 3C (since we have replaced one loop iteration by an incomplete addition):

    Acc := [2] T + T
    for i from n-2 down to 0 {
        Q := k<sub>i+1</sub> ? T : −T
        Acc := (Acc + Q) + Acc
    }
    return (k<sub>0</sub> = 0) ? (Acc - T) : Acc

Let s be the order of the large prime-order subgroup. Assume that T is of order s and that 2<sup>n+1</sup> - 1 ≤ (s-1)/2. Under these conditions, we can calculate [2<sup>n</sup> + k] T for k < 2<sup>n</sup> in (n+1) \* 6C.

It remains to check that the x-coordinates of each pair of points to be added are distinct.

When adding points in the large prime-order subgroup, we can rely on Theorem A.3.4 from the Zcash protocol spec, which says that if we have two such points with nonzero indices wrt a given odd-prime order base, where the indices taken in the range -(s-1)/2..(s-1)/2 are distinct disregarding sign, then they have different x-coordinates. This is helpful, because it is easier to reason about the indices of points occurring in the scalar multiplication algorithm than it is to reason about their x-coordinates directly.

So, the required check is equivalent to saying that the following "indexed version" of the above algorithm never asserts:

    acc := 3
    for i from n-2 down to 0 {
        q = k<sub>i+1</sub> ? 1 : −1
        assert acc ≠ ± q
        assert (acc + q) ≠ acc    // X
        acc := (acc + q) + acc
        assert 0 < acc ≤ (s-1)/2
    }
    if k<sub>0</sub> = 0 {
        assert acc ≠ 1
        acc := acc - 1
    }

The assertion labelled X obviously cannot fail because q ≠ 0. It is easy to see that acc is monotonically increasing except in the last conditional. It reaches its largest value when k is maximal, i.e. 2<sup>n+1</sup> - 1, which justifies the condition on n above. This discharges all of the other assertions.

[Edit: the constraint count was off-by-one.]

**Comment by arielgabizon** [comment]
I'm wondering how much this improves the circuit size for batched Groth16 verification..perhaps I'll do the computation later.
This might end up being very useful for batch Sonic verification where scalar multiplication might be the main cost.

**Comment by daira** [comment]
@arielgabizon The Miller loop curve arithmetic is in G<sub>2</sub>, so the constraint counts are different; also in the Miller loop we need all the intermediate points in order to compute the line functions. It might still be possible to apply this optimization, but it needs more analysis.

It can definitely be applied to the double-and-add steps in the subgroup checks. There the exponent is fixed so we should find addition-subtraction chains that minimize the constraint cost taking into account this optimization.

We can also apply it to [z<sub>j</sub>] π<sub>j,A</sub> and to the multiscalar multiplications in the computation of Accum<sub>AB</sub>, Accum<sub>Δ</sub>, and [Accum<sub>Γ,i</sub>] Ψ<sub>i</sub>.

**Comment by daira** [comment]
For comparison, a *fixed*-base scalar multiplication takes 2 constraints/bit. One way of doing it using 3-bit windows is described in https://github.com/zcash/zcash/issues/2230#issuecomment-361063268 . I think there's a simpler way using 2-bit windows: that requires 1C to AND each pair of scalar bits, the lookup is free because linear, and 3C for an incomplete addition, for a total of 4C per 2-bit window. The adjustment to avoid zero points does not affect the per-bit cost.

**Comment by daira** [comment]
I reread this and experienced a pang of guilt that I was maybe teaching people to do something that would cause security bugs in their constraint systems in general:

> The constraint system for the incomplete addition P + Q = R on its own would be:
>
>     (x<sub>Q</sub> - x<sub>P</sub>) × (λ<sub>1</sub>) = (y<sub>Q</sub> - y<sub>P</sub>)
>     (B·λ<sub>1</sub>) × (λ<sub>1</sub>) = (A + x<sub>P</sub> + x<sub>Q</sub> + x<sub>R</sub>)
>     (x<sub>P</sub> - x<sub>R</sub>) × (λ<sub>1</sub>) = (y<sub>R</sub> + y<sub>P</sub>)
>
> When computing (P + Q) + P = S, we drop the last constraint which is only needed for y<sub>R</sub>. The outer addition requires the gradient λ<sub>2</sub> = (y<sub>P</sub> - y<sub>R</sub>)/(x<sub>P</sub> - x<sub>R</sub>), but we have:
>
>     λ<sub>1</sub> = (y<sub>R</sub> + y<sub>P</sub>)/(x<sub>P</sub> - x<sub>R</sub>)
>
> therefore
>
>     λ<sub>2</sub> = 2·y<sub>P</sub>/(x<sub>P</sub> - x<sub>R</sub>) - λ<sub>1</sub>.
>
> So in R1CS we can write:
>
>     [2 constraints not important to this point snipped]
>     (x<sub>P</sub> - x<sub>R</sub>) × (λ<sub>1</sub> + λ<sub>2</sub>) = (2·y<sub>P</sub>)

Notice that we *drop* a constraint that is equivalent to λ<sub>1</sub> = (y<sub>R</sub> + y<sub>P</sub>)/(x<sub>P</sub> - x<sub>R</sub>), and then we rely on that equation!

What is going on here that allows us to drop a constraint and then apparently rely on it? In general this can definitely cause bugs. For example, there's are two similar attempted optimizations in the MiMC and LowMC constraint systems in section 6.1 of the MiMC paper ([[Albrecht, Grassi, Rechberger, Roy, and Tiessen](https://eprint.iacr.org/2016/492)], page 22), which are completely insecure as a result.

The argument for why this is okay in this case goes as follows:
* Under the assumption x<sub>P</sub> ≠ x<sub>R</sub> (which we discharge later), the first constraint determines λ<sub>1</sub> as a function of variables {x<sub>P</sub>, x<sub>Q</sub>, y<sub>P</sub>, y<sub>Q</sub>}.
* The second constraint determines x<sub>R</sub> as a function of variables {λ<sub>1</sub>, x<sub>P</sub>, x<sub>Q</sub>} (and some constants).
* Under the assumption x<sub>P</sub> ≠ x<sub>R</sub>, the last constraint determines λ<sub>2</sub> as a function of variables {λ<sub>1</sub>, x<sub>P</sub>, x<sub>R</sub>, y<sub>P</sub>}.

Combining these dependencies in a quite mechanical way (not depending on any higher-level understanding of the elliptic curve math), we find that under the assumption x<sub>P</sub> ≠ x<sub>R</sub>, λ<sub>2</sub> is determined by {x<sub>P</sub>, x<sub>Q</sub>, y<sub>P</sub>, y<sub>Q</sub>}, both before and after the optimization.

Notice that this is the kind of analysis that can and should be doable by an automated tool. Given:

* two constraint systems, before and after a purported optimization;
* a set of "variables of interest";
* a set of assumptions (here, and for many similar problems, it's sufficient to specify a set of linear combinations that are assumed to be nonzero)

we should be able to ask the tool whether the dependency relations between the variables of interest changed, and what they are. This would help to catch a class of mistakes without requiring any sophisticated machinery for equivalence-proving. For instance, it would catch the mistakes in the MiMC paper (although tbh the manual analysis is sufficient for that).

**Comment by daira** [comment]
A subtlety is that the assumption x<sub>P</sub> ≠ x<sub>R</sub> depends on x<sub>R</sub> being sufficiently constrained, and so x<sub>R</sub> should be one of our "variables of interest" even though it is an intermediate. In this case, we can infer that under the assumption x<sub>P</sub> ≠ x<sub>Q</sub>, x<sub>R</sub> is determined as a function of variables {x<sub>P</sub>, x<sub>Q</sub>, y<sub>P</sub>, y<sub>Q</sub>}. Note that the assumption here does not itself depend on x<sub>R</sub> (which would be circular reasoning).

**Comment by daira** [comment]
For #3425 we need to be able to implement multiplications on E'/F<sub>p<sup>2</sup></sub>.

A conditional negation takes 2C (since both elements of the y-coordinate need to be negated). So processing each scalar bit requires 3m~ + 2s~ + 2C, which is (9 + 4 + 2)C = 15C using [Karatsuba multiplication and Complex squaring](https://github.com/zcash/zcash/issues/3425#issuecomment-408818642). The overall cost is (10 + 8)C to compute [3] T, (n-1) \* 15C for the loop, 8C to compute Acc - T, and 4C for the final conditional, for a total of (n+1) \* 15C.

If the scalar is fixed, it is more efficient to use the (P + Q) + P technique only for the double-and-add steps (13C each) and not for the plain doublings (10C each). No conditional negation is needed in this case.

**Comment by hdevalence** [comment]
This is possibly a tangent from the topic in this issue, but it may be possible to use this together with a Ristretto-for-JubJub along the following lines:

As described in [cite:2017/costello-smith](https://arxiv.org/abs/1703.01863v1) section 4.3, it's possible to recover the y-coordinate of the output point from data computed during the montgomery ladder (Algorithm 5, Okeya-Sakurai y-coordinate recovery).

Since Ristretto can be implemented using a Montgomery curve internally, it seems possible to implement Ristretto inside of a circuit using @daira's few-constraints Montgomery formulas above plus Okeya-Sakurai y-coordinate recovery, and to implement it outside of a circuit using the Hisil-Wong-Carter-Dawson extended coordinates.

**Comment by daira** [comment]
Okeya-Sakurai in R1CS is described [here](https://github.com/zcash/zcash/issues/2277#issuecomment-346850979). However, it's cheaper to do variable-based scalar multiplication in R1CS without the Montgomery ladder. A ladder-based multiplication would require [10 constraints per scalar bit](https://github.com/zcash/zcash/issues/2277#issuecomment-341897766). The method described in this issue requires only 6 constraints/bit. Note that it doesn't require Okeya-Sakurai at the end since it computes both coordinates already.

The difference in trade-offs is due to the fact that R1CS greatly favours using (x, y) affine coordinates, because division is cheap. The [Eisentraeger, Lauter, and Montgomery] method does avoid computing *some* of the intermediate y-coordinates, but as far as I can see, there's no further improvement to be made by staying x-coordinate-only, because computing the y-coordinate is the fastest way to compute the needed slope (λ) for the next addition or doubling.

The additional Ristretto operations can be implemented just by following the [affine Ristretto formulae](https://ristretto.group/formulas/index.html). I haven't calculated the exact costs, but it looks straightforward. Note that the inverse square root operation is particularly efficient in R1CS because you basically just need to confirm the square. You do need to also constrain the square root to be positive, which I think can only be done by boolean-unpacking it (similar to appendix A.3.3.2 in the protocol spec).

**Comment by hdevalence** [comment]
Ah, thanks for the explanation on the Montgomery formulas, and the pointer on checking positivity!

I'm not sure but I think that rather than converting to/from Edwards and following the affine Edwards Ristretto formulas, it will be simpler to use the Ristretto-to-Montgomery formulas directly (since the affine Edwards formulas are [those formulas, composed with the Montgomery-to-Edwards](https://ristretto.group/details/conceptual_diagram.html) map).  @cathieyun and I have been planning to prototype this using Bulletproofs, which could be useful as a test case.

**Comment by daira** [comment]
Using the prime-order subgroup turns out to be always more efficient in R1CS than Ristretto: https://github.com/zcash/zcash/issues/4024#issuecomment-500473198

**Comment by kidker** [comment]
Daira, please give me a book for reading;) thanks;)

**Comment by daira** [comment]
``multiply_fast`` in https://github.com/ebfull/halo/blob/master/src/gadgets/ecc.rs implements this algorithm (for Halo, not bellman/R1CS).

**Comment by daira** [comment]
This technique can be adapted to double-variable-base scalar multiplication, i.e. [u<sub>1</sub>] P<sub>1</sub> + [u<sub>2</sub>] P<sub>2</sub> where P<sub>1,2</sub> are both variable (but P<sub>1</sub> ≠ +/- P<sub>2</sub>). We can compute Q in each iteration as the sum of two conditionally-negated points, which costs 2C for the conditional negations and 3C for incomplete addition. Therefore the overall cost is (5+2+3)C = 10C per bit &mdash; a modest improvement over 12C per bit when computing [u<sub>1</sub>] P<sub>1</sub> + [u<sub>2</sub>] P<sub>2</sub> naively.

The fixed-and-variable case (as above but with P<sub>1</sub> fixed) is interesting for EdDSA, RedDSA, or ECDSA signature verification. We can do a fixed-base scalar multiplication [in 2C per bit](https://github.com/zcash/zcash/issues/3924#issuecomment-478244290), so naively adding the fixed- and variable-base results gives 8C per bit (or 0.5C per bit to prepare the fixed-base scalar and 7.5C per bit for the double multiplication). I cannot find any improvement on this; adapting the approach used for double-variable-base above would take 9C per bit.

**Comment by daira** [comment]
In general we can do a k-way variable-base multiplication in (2+4k)C per bit using the same approach.

**Comment by daira** [comment]
Note that the correctness argument for using incomplete addition does not work for the multiple-base variant without additional work.

**Comment by daira** [comment]
There's nothing left to do here; see #4254 for further optimizations specific to PLONK. The techniques in this ticket was also described in my ZK Study Club presentation ([video](https://m.youtube.com/watch?v=IQVGIqcdxL4&t=1176s), [slides](https://github.com/daira/halographs/blob/master/halographs.pdf)).

**Comment by weikengchen** [comment]
An additional note. For the R1CS-based universal setup---such as Marlin---this scalar multiplication may also enjoy lower density (i.e., non-zero elements in the constraint), which can make the proving cost lower.

**Comment by vanishreerao** [comment]
An additional note on the scalar inputs for this algorithm: Of course, the scalar can't be p, the prime order, but also it can't be p-1, since the algorithm computes [scalar + 1]T along the way whenever the scalar is even.
