### ISSUE TITLE
bitcore-lib-zcash: z-addr generation & ZKP tx-builder examples?

### ISSUE THREAD

**Issue by dmorris99** [zcash/zcash#3930]
### Describe the issue
bitcore-lib-zcash -- documentation/example usage for z-addr generation and transaction construction

Hi all, 

I'm building a browser-based wallet and looking to extend its ZEC support for shielded transactions and addresses. I'm currently using bitgo-utxo-lib for t->t addr ZEC transactions with various Sapling bits set on its TransactionBuilder object, but I'm quite open to switching to bitcore-lib-zcash if it can help me enable shielded transactions.

Is anybody able please to provide a code example of what is required to;

(a) generate a new **z-addr** (HDNode-derived) keyPair (my current t-addr code using bitgo's lib is below for reference)

```
    const entropySha256 = utils.sha256_shex(entropySeed)
    var root = bitgoUtxoLib.HDNode.fromSeedHex(entropySha256, network) // bitgo HDNode 
    ...
        const path = `m/44'/${meta.bip44_index}'/${accountNdx}'/${chainNdx}/${i}`
        const child = root.derivePath(path)
        var keyPair = child.keyPair // bitgo
        var wif = keyPair.toWIF()
```

(b) build a **t->z** (and/or z->z, z->t) transaction? (again, current t-addr bitgo code is below, but any example or equivalent z-addr extended code for bitcore-lib-zcash would be highly appreciated)

```
const txb = new bitgoUtxoLib.TransactionBuilder(network)
txb.setVersion(bitgoUtxoLib.Transaction.ZCASH_SAPLING_VERSION) // sapling: v4
txb.setVersionGroupId(2301567109) // sapling
txb.setExpiryHeight(0)
for (var i = 0; i < res.inputs.length; i++) {
  txb.addInput(res.inputs[i].utxo.txid, res.inputs[i].utxo.vout)
}
res.outputs.forEach(output => {
  txb.addOutput(output.address, output.value)
})
for (var i = 0; i < res.inputs.length; i++) {
  var wif = addrPrivKeys.find(p => { return p.addr === res.inputs[i].utxo.address }).privKey
  var keyPair = bitgoUtxoLib.ECPair.fromWIF(wif, network)
  txb.sign(i, keyPair, '', bitgoUtxoLib.Transaction.SIGHASH_SINGLE, res.inputs[i].utxo.satoshis)
}
...
```
I'm unclear what additional ZPK proof generation needs to happen, how to do it if so, or if bitcore-lib-zcash supports this internally in some way (it isn't evident to me that it does). Any inputs or assistance are greatly appreciated!

Thank you,
D.

**Comment by ioptio** [comment]
We don't have plans to support z-addrs beyond running insight explorer and API. This would require substantial additional support which we can't provide right now. Would this be something you would be interested in looking into perhaps?

**Comment by dmorris99** [comment]
Hi @ioptio - thanks for the input, and confirming my understanding on the limits of the current library. 

It's on my roadmap, indeed if I can bump it up my internal priority queue I will sync up with you on to incorporate it into bitcore-lib-zcash.

**Comment by ZeroChaininfo** [comment]
is there any solution to deal with z-address in bitcore-lib-zcash ?
