### ISSUE TITLE
Bundle all ≥2.0 zkSNARK params except the Sprout-on-Groth proving params into the binary

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#3933]
Currently users need to download the zkSNARK parameters with `zcash-fetch-params` prior to using their node the first time. This is an annoying hurdle.

What if the params came with the binary distribution? Well, they are large, so that may be cumbersome. However, the size of the parameters may be dominated by the Sprout proving key which is only necessary for users who need to send _from_ Sprout addresses. New users shouldn't ever need to send from Sprout addresses and old users have probably already fetched the parameters.

So, if all the parameters aside from the Sprout-on-groth proving key were small enough, we could bake them into the binary, and leave `zcash-fetch-params` to retrieve only the Sprout-on-groth spending key. Then the wallet could detect when sending from Sprout if the proving parameters are missing and request to the user to fetch them. Most users would never hit that case, presumably, and so most users would have an improved onboarding experience with one fewer steps and startup delay.

**Comment by rex4539** [comment]
Does it really matter for someone who is about to sync ~23GB (and growing) of blockchain data if he needs to download a few hundred MBs more?

Also, concept NACK for having a fat binary.

**Comment by daira** [comment]
@rex4539 The main benefit here has nothing to do with bandwidth; it's eliminating a step from zcashd installation, that has to be triggered manually and that can go wrong. (One way in which it can go wrong is that the download is blocked by state-level network censorship, which is quite common for an important subset of our users -- even though other network access needed by zcashd isn't being blocked.)

We can and will address the bandwidth and time requirements of syncing separately.

**Comment by Eirik0** [comment]
Is there a reason why the `zcash-fetch-params` script is a separate process and not built in to zcashd? Would it would to add this as a step in initialization prior to downloading blocks?

**Comment by daira** [comment]
It's mainly because the original Sprout parameters were so large.

**Comment by str4d** [comment]
We have also previously discussed other distribution mechanisms that leverage existing channels. For example, we could package the parameters in Debian packages, and then not only do we get automatic distribution of them at install time, but we also get de-duplication across multiple applications that depend on the same parameters.

**Comment by nathan-at-least** [comment]
I now prefer the #4491 approach for a variety of reasons.
