### ISSUE TITLE
Add fields for shielded {confirmed, unconfirmed, immature} balances to the output of getwalletinfo

### ISSUE THREAD

**Issue by daira** [zcash/zcash#3939]
As noted in #3911, the ``balance``, ``unconfirmed_balance``, and ``immature_balance`` fields in the output of the ``getwalletinfo`` RPC only include *transparent* balances.

The absence of corresponding fields for shielded balance is missing functionality that impedes shielded adoption.

**Comment by bitcartel** [comment]
Might be useful to return shielded balance values by value pool as well as aggregate.
