### ISSUE TITLE
"Hash sum mismatch" error message when updating

### ISSUE THREAD

**Issue by the-metalworker** [zcash/zcash#3943]
### Describe the issue
I am getting this error when updating:

```
sudo apt-get update
Get:7 tor+http://zcaptnv5ljsxpnjt.onion jessie InRelease
Ign:7 tor+http://zcaptnv5ljsxpnjt.onion jessie InRelease
Get:9 tor+http://zcaptnv5ljsxpnjt.onion jessie Release.gpg
Err:10 tor+http://zcaptnv5ljsxpnjt.onion jessie/main amd64 Packages
  Hash Sum mismatch
Fetched 3,954 B in 4s (916 B/s)
Reading package lists... Done
E: Failed to fetch tor+http://zcaptnv5ljsxpnjt.onion/dists/jessie/main/binary-amd64/Packages.bz2  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by ioptio** [comment]
Also reported here https://github.com/zcash/zcash/issues/3867

**Comment by ioptio** [comment]
This would be helpful to have dev-infra to reproduce

**Comment by the-metalworker** [comment]
sorry about that @ioptio I did a search for the error message and got no results. I can't tell if gothlacroix is having the same issue as me or a different one, not enough information in their report to tell but it does seem similar. I will let you decide whether to close this as duplicate or not.

**Comment by garethtdavies** [comment]
I just successfully installed via tor to rule out any issues with the package:

```
...
Ign:12 tor+http://zcaptnv5ljsxpnjt.onion jessie InRelease
Get:13 tor+http://zcaptnv5ljsxpnjt.onion jessie Release [2,288 B]
Get:14 tor+http://zcaptnv5ljsxpnjt.onion jessie Release.gpg [833 B]
Get:15 tor+http://zcaptnv5ljsxpnjt.onion jessie/main amd64 Packages [6,883 B]
Fetched 10.0 kB in 6s (1,732 B/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  zcash
0 upgraded, 1 newly installed, 0 to remove and 6 not upgraded.
Need to get 4,207 kB of archives.
After this operation, 15.8 MB of additional disk space will be used.
Get:1 tor+http://zcaptnv5ljsxpnjt.onion jessie/main amd64 zcash amd64 2.0.4 [4,207 kB]
Fetched 4,207 kB in 34s (125 kB/s)
Selecting previously unselected package zcash.
(Reading database ... 202713 files and directories currently installed.)
Preparing to unpack .../archives/zcash_2.0.4_amd64.deb ...
Unpacking zcash (2.0.4) ...
Setting up zcash (2.0.4) ...
Processing triggers for man-db (2.8.5-2) ...
```

Seems quite a common issue with Debian packages in general. Might want to try one of the solutions listed here? https://stackoverflow.com/questions/15505775/debian-apt-packages-hash-sum-mismatch

**Comment by the-metalworker** [comment]
@garethtdavies thanks for checking. What happens when you run `sudo apt-get update` or `sudo apt-get upgrade`?

**Comment by garethtdavies** [comment]
> @garethtdavies thanks for checking. What happens when you run sudo apt-get update or sudo apt-get upgrade?

Nothing unexpected.

Have you installed the latest key as the old one expired and was rotated. See https://zcash.readthedocs.io/en/latest/rtd_pages/install_debian_bin_packages.html

**Comment by ioptio** [comment]
@the-metalworker can we close this issue since you've opened a new one and this one is no longer relevant?

**Comment by the-metalworker** [comment]
I followed the instructions for fixing the "Expired key error" that @garethtdavies linked to, and replaced the apt info with the Tor apt info. Both errors I encountered have now gone away. Thank you.
