### ISSUE TITLE
build.sh broken on OS X

### ISSUE THREAD

**Issue by leto** [zcash/zcash#3945]
### Describe the issue

I regularly compile Zcash master branch on OS X and I expect that it continues to work.

The command `./zcutil/build.sh` can no longer finish linking zcashd, though it does get close.

This happens on both the `master` branch (e73326eed) and `v2.0.4` release tag.

### Can you reliably reproduce the issue?

Yes

#### If so, please list the steps to reproduce below:
1. ./zcutil/build.sh on OS X
2. 
3. 

### Expected behaviour
zcashd is compiled

### Actual behaviour + errors

```
Undefined symbols for architecture x86_64:
  "FakeCoinsViewDB::DB_COINS", referenced from:
      FakeCoinsViewDB::GetCoins(uint256 const&, CCoins&) const in libbitcoin_wallet.a(libbitcoin_wallet_a-zcbenchmarks.o)
      FakeCoinsViewDB::HaveCoins(uint256 const&) const in libbitcoin_wallet.a(libbitcoin_wallet_a-zcbenchmarks.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [zcashd] Error 1
make[2]: *** Waiting for unfinished jobs....
```

### Machine specs:

OS X 10.13.4

```
Darwin hostname.local 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64
```

```
Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by leto** [comment]
For reference, `v2.0.2` tag compiles correctly on the same machine.

**Comment by garethtdavies** [comment]
This is the same issues as https://github.com/zcash/zcash/issues/3860

Fix is here: https://github.com/zcash/zcash/pull/3907

**Comment by ioptio** [comment]
@leto if you can try that patch and let us know if it fixes it, that's one way forward until we have time to merge the fix in. If you're interested in reviewing that PR, that's what it's waiting on, too.

**Comment by leto** [comment]
@ioptio I can confirm that master commit 5eb7f89980c builds successfully on the same OS X machine :+1:
