### ISSUE TITLE
build warning boost integer_log2.hpp deprecated

### ISSUE THREAD

**Issue by LarryRuane** [zcash/zcash#3947]
Building `zcash` on (at least) Linux debian Ubuntu 18.04.2 LTS generates the following compile warning (irrelevant path prefix removed):
```
In file included from [...]include/boost/random/detail/integer_log2.hpp:19:0,
                 from [...]include/boost/random/detail/large_arithmetic.hpp:19,
                 from [...]include/boost/random/detail/const_mod.hpp:23,
                 from [...]include/boost/random/detail/seed_impl.hpp:26,
                 from [...]include/boost/random/mersenne_twister.hpp:30,
                 from [...]include/boost/uuid/random_generator.hpp:17,
                 from [...]include/boost/uuid/uuid_generators.hpp:17,
                 from wallet/gtest/test_paymentdisclosure.cpp:26:
[...]include/boost/pending/integer_log2.hpp:7:59: note: #pragma message: This header is deprecated. Use <boost/integer/integer_log2.hpp> instead.
 BOOST_HEADER_DEPRECATED("<boost/integer/integer_log2.hpp>");
```
Since this is just a warning, the build completes successfully, but the warning is still disconcerting. This problem was introduced as described here: https://github.com/zcash/zcash/issues/3786#issuecomment-480393016. The fix is to upgrade to boost version 1.70.0 when it becomes available (until then, fixing this issue is blocked).

**Comment by rex4539** [comment]
According to https://www.boost.org/development/index.html 1.70.0 is being released in 2 days.
