### ISSUE TITLE
Mining Wallet Bug, Reward stuck somewhere 

### ISSUE THREAD

**Issue by goodthebest** [zcash/zcash#3950]
Hey Devs @zkbot 

My pool mined a block **513155** mining wallet: t1Xddvk9ZXxdK5MfSSE9jJ4DQRGcCE3XXP8 but it's been over a day it shows zero balance, no immature or any kind of balance just zero. 

By z nomp Generated block transfered to **account ""** but where is it? Is it somewhere in my wallet I'm pretty much lost. Checking explorer shows generated block was sent to my wallet address. However, checking listtransactions shows it was then sent to **account "" **. I've appended the output below, please help sort this out.

Could ZEC developers help me figure out where has the balance gone. 

# getwallinfo output

{
  "walletversion": 60000,
  "balance": 0.00000000,
  "unconfirmed_balance": 0.00000000,
  "immature_balance": 0.00000000,
  "txcount": 2,
  "keypoololdest": 1554998310,
  "keypoolsize": 101,
  "paytxfee": 0.00000000,
  "seedfp": "3e10702b14252a14d91d711acbcdd34ff85dafe71c52339c05cbc74bdc796b07"
}

# listtransactions output

It shows generated block and then next **send** transactions but not mentioning any account. I'm confused, could any one help please

[
  {
    "account": "",
    "address": "t1Xddvk9ZXxdK5MfSSE9jJ4DQRGcCE3XXP8",
    "category": "generate",
    "amount": 10.00418480,
    "vout": 0,
    "confirmations": 395,
    "generated": true,
    "blockhash": "0000000001e7d65e38629f05d44f654aa0141db7239ce151c4453977f6356cb0",
    "blockindex": 0,
    "blocktime": 1554937307,
    "expiryheight": 0,
    "txid": "4b9ba2661130a6f89af099951f2c5e2f17b453b1dab8c7dc6ebdb5eaf27dd33a",
    "walletconflicts": [
    ],
    "time": 1554937307,
    "timereceived": 1554937318,
    "vjoinsplit": [
    ],
    "size": 216
  },
  {
    "account": "",
    "category": "send",
    "amount": -10.00408480,
    "vout": 0,
    "fee": -0.00010000,
    "confirmations": 294,
    "blockhash": "00000000025723852bb10039a421a64cd38fc6c0752deb5e316b4c21699629e4",
    "blockindex": 4,
    "blocktime": 1554953767,
    "expiryheight": 513276,
    "txid": "a751c8696f76436badf9c5b4be6d90adf7f9148ef8a4f759867382c78b88b1fa",
    "walletconflicts": [
    ],
    "time": 1554953716,
    "timereceived": 1554953716,
    "vjoinsplit": [
    ],
    "size": 1189
  }
]

**Comment by daira** [comment]
`"account": ""` is just a holdover from Bitcoin's API design; it can be ignored. There is only one account.

The output of `listtransactions` shows that your wallet received 10.00418480 ZEC and then shielded it (excluding the standard fee) in another transaction. We can't see where it went from this information.
