### ISSUE TITLE
Output of benchmarks for Sapling phgr proving time is unclear

### ISSUE THREAD

**Issue by cszz12** [zcash/zcash#3963]
### Describe the issue
I downloaded zcash-2.0.4, run the joinsplit.full_api_test, but found the pghr proving costs 73030346us, groth proving costs 28628649us. However, sapling blog promises 2.3 seconds proving time in https://z.cash/blog/reducing-shielded-proving-time-in-sapling/. 

Is there anything that I did wrong?
Thanks!

### Can you reliably reproduce the issue?
./src/zcash-gtest

### Expected behaviour
proving time should cost 2.3 seconds

### Actual behaviour + errors
phgr proving time: : 73030346us
groth proving time: : 28628649us 
phgr verifying time: : 33135us
groth verifying time: : 7172us

### The version of Zcash you were using:
zcash-2.0.4

### Machine specs:
- OS name + version: Ubuntu 18.04
- CPU:Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
- RAM:7738MiB

**Comment by daira** [comment]
First, PHGR (also called BCTV14) is no longer used, so that benchmark isn't relevant any more. It should be removed.

Second, "groth proving time" looks like the benchmark for the Sprout JoinSplit circuit on Groth16. This time only applies when spending or creating Sprout notes. The proving time for a Sapling spend is indeed roughly 2.3 seconds, per note being spent.

**Comment by cszz12** [comment]
Thanks Daira for the reply!

This "growth proving time" is indeed for the Sprout circuit, 23 seconds for one note spent.
But I cannot find the sapling spend test case, which is weird.

**Comment by daira** [comment]
The 23s is not per note spent, it's per JoinSplit. There is a complicated relationship between the number of JoinSplits and the number of notes spent and produced. But the Sprout circuit is not so relevant any more.

#3467 added Sapling benchmarks to the benchmark suite. I don't think they were added to https://speed.z.cash .

**Comment by cszz12** [comment]
I see. In the new protocol, sprout circuit should be replaced by Sapling Spends or Outputs, but it still exists for compatible reasons? 

And there should exist somewhere in the code for the Sapling Spends or Outputs? Proved with sapling-spend key and verified with sapling-output key?

**Comment by daira** [comment]
@cszz12 wrote:
> I see. In the new protocol, sprout circuit should be replaced by Sapling Spends or Outputs, but it still exists for compatible reasons?

Yes.

> And there should exist somewhere in the code for the Sapling Spends or Outputs? Proved with sapling-spend key and verified with sapling-output key?

Spends and Outputs use separate circuits. Each has a proving key and a verifying key.

**Comment by cszz12** [comment]
Thanks Daira! When I was looking at the librustzcash lib, I found that sapling spend proving&verifying are included in the same file, sapling-spend.params, if I understand correctly. So does the output keys in sapling-output.params.

Besides, is there any document to describe the sapling crypto upgrade? The new protocol paper contains too many math expression.... a bit hard to read, even though comprehensible.

**Comment by daira** [comment]
That's correct, proving and verifying keys are in a single `.params` file for each Groth16 circuit.

There is no other document than the protocol spec that fully describes Sapling. There are blog posts that describe some of the motivations behind it: https://z.cash/blog/tag/sapling/

I encourage trying to plough through the spec and asking about anything you find unclear on https://chat.zcashcommunity.com/channel/zcash-apprentices

**Comment by cszz12** [comment]
Thanks a lot Daira for your patient answer!  :-)
I think I figured out almost all the problems, but need more time for the technical details.

**Comment by benediamond** [comment]
Hi. As a belated follow-up, where can I find benchmarks?

of course this is tough because it depends on the number of notes. for example, how long does it take to generate and verify a proof where 2 sapling notes are consumed and 2 are produced? Thank you.

**Comment by daira** [comment]
If you merge #4635, then you can see the times at which various events occur when making a payment, to microsecond resolution.

**Comment by str4d** [comment]
Closing as questions were answered.
