### ISSUE TITLE
review ZC/"Bitcoin layer" integration design for anonymity and security

### ISSUE THREAD

**Issue by daira** [zcash/zcash#397]

**Comment by daira** [comment]
I'm happy that this has had sufficient review. (It hadn't when this ticket was opened, and in fact we made significant design simplifications, such as only using a single JoinSplit signature covering the whole transaction.)

**Comment by LawrenceMan131** [comment]
This is just one of the ways binary option scams can defraud you. There are many fraudulent binary option trading platforms and brokers out there taking advantage of nice investors daily. However, if you’ve fallen victim to a bitcoin scam, there are different steps you can try to get your money back through (webrootrecovery@ gmail .com) your best recovery adept when it comes to Binary options
