### ISSUE TITLE
equihash_tests.cpp:10:27: fatal error: arith_uint256.h: No such file or directory

### ISSUE THREAD

**Issue by XuDafang** [zcash/zcash#3970]
I tried to compile the equihash_tests.cpp by "g++ equihash_tests.cpp", but it couldn't find arith_uint256.h file. After I changed the path of arith_uint256.h in source code,  it couldn't find the other files.

I tried it in Win/Ubuntu/Debian, and I got the same error.

**Comment by XuDafang** [comment]
I tried to compile the file in Win/Ubuntu/Debian, I tried g++-5, g++-6, g++-7, g++-8, I also tried it in command line and IDE, but I still get the same error.

**Comment by ioptio** [comment]
Can you try to compile using the directions at https://zcash.readthedocs.io/en/latest/rtd_pages/user_guide.html

Let us know how that goes.

**Comment by ioptio** [comment]
Closing this due to lack of response, you can reopen with new comments if you have any.
