### ISSUE TITLE
Building Zcash on Fedora failed, missing static libs (cannot find -lm -lc -lpthread) 

### ISSUE THREAD

**Issue by hdevalence** [zcash/zcash#3975]
### Describe the issue

Linker errors while building Zcash

#### If so, please list the steps to reproduce below:
1. Followed build steps to [build from source](https://zcash.readthedocs.io/en/latest/rtd_pages/user_guide.html) on Fedora 29, and got the following linker errors in `build.sh` after installing the recommended dependencies:

```
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lstdc++
/usr/bin/ld: cannot find -lm
/usr/bin/ld: cannot find -ldl
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:229: libsnark/gtests] Error 1
make[3]: Leaving directory '/home/hdevalence/code/zcash/src/snark'
make[2]: *** [Makefile:6905: snark/libsnark.a] Error 2
make[2]: *** Waiting for unfinished jobs....
```

### Expected behaviour

Makefile should link successfully

### Actual behaviour + errors

After running `sudo dnf install glibc-static libstdc++-static`, `build.sh` ran without errors.

### The version of Zcash you were using:
2.0.4

### Machine specs:
- OS name + version: Fedora 29

### Any extra information that might be useful in the debugging process.

This seems like just a tiny documentation issue, so I'm filing this issue in case someone else runs into the same problem.

**Comment by garethtdavies** [comment]
I was able to replicate this as above on Fedora 29. Given this is the current release (albeit 30 is out as soon as tomorrow) I submitted a merge request to the docs repo to add these missing dependencies https://gitlab.com/zcash-docs/zcash-docs/merge_requests/109.

**Comment by taw00** [comment]
I've been building zcash successfully on Fedora (as RPMs) for some time (note, 2.0.5 is currently failing -- working on that). If you want to see what I am doing...
https://github.com/taw00/zcash-rpm

**Comment by ioptio** [comment]
Since the above docs were merged, (thanks @garethtdavies!) I'll close this ticket.
