### ISSUE TITLE
Mitigate partitioning of the anonymity set  by fee selection (and avoid excessive transaction costs)

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#398]
In current bitcoin land, wallets are free to implement fee estimation differently, and even within the same wallet, later versions can select fees differently than earlier versions. This all serves to partition the anonymity set.

If users are allowed to select fees manually, then habitual "human" patterns (like selecting round base-10 numbers) will also reduce anonymity.

Heuristic fee selection algorithm may also use external sources of information, for example the fees of other transactions in the mempool. If external sources are used, active attackers may be able to "poison" some nodes with strange fee-selection inputs, and then by watching transaction fees, see which ones came from the poisoned nodes.

**Comment by daira** [comment]
See https://github.com/OpenBazaar/OpenBazaar-Client/issues/1693 for an example of how uncertainty over fees can lead to excessive transaction costs. The API for Bitcoin transaction fees linked from there (here's a snapshot to avoid spanning the API endpoint: https://defuse.ca/b/7DY2WMJEPJIVYx0XvPlftq ) confirms that many Bitcoin transactions are paying fees that are unnecessarily high, i.e. that obtain no benefit in confirmation time.

**Comment by jl777** [comment]
I have a radical idea on this issue. The big problem with txfees are that they can leak privacy or at least make it that much harder to deal with keeping things private.

But of course, we need txfees to prevent spam, but maybe there is a way to have some portion of mining rewards allocated for public use txfees. That creates zero correlations, even if it is transparent as it comes from the miner. So it would dramatically reduce the space on the blockchain by eliminating the need for zkp for the txfee outputs.

The issue that needs to be solved is how to limit the number of free tx anybody can use. If there was a txfee faucet that could be protected from mass abuse, that could solve this issue external to the zcashd.

With 1 ZEC able to fund 1000+ transactions, it seems worth allocating that collectively. I guess when blockchain activity is much higher, it becomes more and more painful, but when the network is young and small it is much more vulnerable to external analysis, and when it is much bigger that the txfee faucet cant fund all the txfees, there will by definition be thousands of transactions per day, which makes the external analysis not so useful

**Comment by daira** [comment]
So, I'm not sure there is much difference between having a zero fee and having a public faucet that pays fees, except that the public faucet can be turned off in case of spam. The faucet is unlikely to be able to distinguish between legitimate and spammer requests, so turning it off is pretty much all you can do. I like the radical thinking on this issue though.

**Comment by jl777** [comment]
having zero txfee wont work as there wont be any protection from infinite spam, especially from competitive anon coins with aggressive community.

having a public faucet funded by the blockchain directly solves the txfee contamination issue and also prevent any bloat from txfee (assuming you can use transparent txfee to pay for joinsplit funds

the faucet will simply run out of funds during a spam attack and the free txfees automatically turn into not free, thus making the spam attack cost real funds.

If we end up with a constant amount of spam attacks that makes the faucet useless, then plan B can be used.

**Comment by jl777** [comment]
Plan B would be a heuristic that is regression tested against all prior spam attacks, ie find a pattern that would identify the spam attack vs normal transactions. I am sure a very high accuracy discriminator can be created using SVM.

So each spam attack would require retraining the SVM to detect a similar pattern spam attack. Since each attack is an annoyance and not costing people money, making each attack automatically make the spam detector smarter actually extracts value from each spam attack

**Comment by daira** [comment]
The difference between the fee faucet idea, and having miners increase their fee requirements (from zero) in case of a span attack, is that the fee faucet is more centralised. That does allow for easier detection of attacks, but it's not coat to me that centralisation is a good thing here. (It's not as bad as other forms of centralisation because only relatively small transaction fees are at stake, but it still goes against the grain.)

**Comment by jl777** [comment]
my prediction is that if it is left up to the miners, we wont have many free txfee, ie they will always set the fee to non-zero to maximize revenues.

so, it seems the practical choice is to fund the fee faucet in a decentralized way, ie part of the protocol, and have the relatively small amount of funds managed in a distributed fashion. Nothing says there cant be half a dozen fee faucets run by community volunteers. So there doesnt even have to be centralization of the fee faucet policy making, each of the distributed set of fee faucets could have discretion over its own share of funds.

zcash is already going completely against the grain! you guys actually listen to external feedbacks

**Comment by daira** [comment]
In the case of Bitcoin, it's not so much that miners are demanding high fees, as that transaction creators --or the writers of wallet software-- don't know what fees to use (I think the API I linked to is probably not well-known, and can't be used automatically because it's limited to 5000 requests/hour). So they overestimate.

**Comment by jl777** [comment]
well using a public website API seems like centralization and a single point of failure.
I just point out that a lot of miners are in it just for the money and if given a choice of charging txfee or not, will charge txfees.

**Comment by daira** [comment]
Right, I wasn't suggesting using a centralised API (although there are Varro's decentralised ways you could imagine to communicate expected fee information). Note that we can't prevent miners from refusing to include transactions that don't include a minimum fee. Whether they do so is at least as much about social expectations as it is a protocol issue.

**Comment by nuttycom** [comment]
This will probably be fixed by ZIP 317.
