### ISSUE TITLE
Temporarily select highest fee per kilobyte transactions for block templates

### ISSUE THREAD

**Issue by zebambam** [zcash/zcash#3991]
Alter the zcashd code in getblocktemplate to return a template containing transactions with the highest fees within the block to be mined.

This is intended to be coupled with #2344 (limit the mempool size) as part of a structured solution to fix #3983 (filling blocks with useless transactions is straightforward and cheap).

A structured solution is one that answers the following questions with action: 

1. What can we do right now to limit the damage? 
2. What can we do in the next couple of updates to reduce the damage?
3. What can we do in the next few updates to eliminate the danger?

This ticket falls into the category (along with #2344) of answering question 1. although unlike #2344 (which should remain), it might be removed later by the answers to 2 and 3.

On its own, this update does nothing. Without UI changes, users are unlikely to be able to issue transactions with higher fees to be able to overcome a DoS like that described in #3983. However, once this code change IS in place and being used by miners, third parties who require Zcash functionality for continuation of their business would be far better positioned to continue operating: Miners would be ready to accept higher transaction fees and the affected businesses could still operate Zcash (albeit possibly at a slightly higher cost) on behalf of their users with only small changes to their own software, setting a transaction fee higher than those in use by the DoS attacker.

This is the slower, miner-level upgrade that will "take the edge off" a DoS attack should it occur in the time frame of the next two software releases of Zcashd.

It does represent a tiny and temporary step in the direction that we ultimately don't want to go. It is only a tiny step though, and one that is reversed easily enough as we implement our tactical and strategic fixes to DoS problems.

**Comment by tearodactyl** [comment]
Why so coy about having a fee market?
If and when Zcash actually becomes popular and blocks fill up, what other technique do you propose to arbitrate utilization?
BTC or ETH fees have kinks, but a flat fee for all transactions and all sizes is not workable.

**Comment by zebambam** [comment]
@tearodactyl if I've understood the concern around fee markets, it's that they need to be carefully selected so as not to ultimately inhibit Zcash's usefulness as a medium of exchange. It's possible that I may be mischaracterizing the concerns though as I don't believe that they are as pressing a concern as ensuring that the network continues to function in the short term.

**Comment by zebambam** [comment]
The scope of this work includes significant automated testing of the creation of block templates to ensure that transactions are still available.

**Comment by zebambam** [comment]
We need some engineering estimations for how long this will take.

**Comment by defuse** [comment]
With this in place, while a DoS is ongoing, different wallets may adopt different fee-selection policies and fragment the anonymity set. That's acceptable as a short-term solution while the network is otherwise non-functional, if users opt-in to having weaker privacy in order to get their transaction sent. In the long term though we should lead the charge on standardizing fee selection if we take this route, which is what #3473 is about.

**Comment by zebambam** [comment]
Okay, after more analysis I think it's become clear that this isn't the right approach, and that instead ticket #4026 should be implemented.
