### ISSUE TITLE
question about generating parameter files

### ISSUE THREAD

**Issue by bitdaric** [zcash/zcash#3998]
how can I generate sprout and sapling files? is there any tools to do it?

**Comment by daira** [comment]
Do you mean the zk-SNARK parameter files?

**Comment by bitdaric** [comment]
> 
> 
> Do you mean the zk-SNARK parameter files?

yes

**Comment by ioptio** [comment]
Are you referring to the groth16 parameters used in Sapling and Sprout since Sapling activation?

Here are instructions to verify the Sapling mpc: https://gist.github.com/ebfull/bf62068eda56ce2e8731666fa21d1414

And perhaps more information on this ticket: https://github.com/zcash/zcash/issues/2247 (there's also a link in the comments to a forum discussion which you can join if you have more questions.)

**Comment by bitdaric** [comment]
> 
> 
> Are you referring to the groth16 parameters used in Sapling and Sprout since Sapling activation?
> 
> Here are instructions to verify the Sapling mpc: https://gist.github.com/ebfull/bf62068eda56ce2e8731666fa21d1414
> 
> And perhaps more information on this ticket: #2247 (there's also a link in the comments to a forum discussion which you can join if you have more questions.)

I do not want to verify, I want to generate such parameters myself

**Comment by ioptio** [comment]
Do you want to run your own MPC or generate the parameters on a single machine? 
If the former, you can reuse the powers of tau parameters and see instructions here for generating the phase two parameters:
https://docs.rs/phase2/0.2.2/phase2/
https://github.com/ebfull/phase2

**Comment by bitdaric** [comment]
> 
> 
> Do you want to run your own MPC or generate the parameters on a single machine?
> If the former, you can reuse the powers of tau parameters and see instructions here for generating the phase two parameters:
> https://docs.rs/phase2/0.2.2/phase2/
> https://github.com/ebfull/phase2

thanks for help. would like to run my own MPC.

**Comment by ioptio** [comment]
Ok, so those resources should get you going, then. Does that resolve our question?

**Comment by bitdaric** [comment]
> 
> 
> Ok, so those resources should get you going, then. Does that resolve our question?

I still have difficulties generating parameters myself, could you give me exact commands ?

**Comment by daira** [comment]
The code that was used for the Sapling phase 2 MPC is at https://github.com/zcash-hackworks/sapling-mpc . There are instructions in the README for how to run it; you'll have to modify the code in [src/bin/new.rs](https://github.com/zcash-hackworks/sapling-mpc/blob/master/src/bin/new.rs) to use your own circuit.

**Comment by ioptio** [comment]
Closing this but you can reopen if you have further questions.
