### ISSUE TITLE
support 2-factor auth

### ISSUE THREAD

**Issue by daira** [zcash/zcash#4]
https://www.reddit.com/r/Bitcoin/comments/2njz9j/blockchaininfo_wallet_robbed/

**Comment by str4d** [comment]
We disabled wallet encryption before launch (#1552), so this issue blocks on re-enabling it (#1528) because 2FA doesn't make sense without a first factor.

**Comment by str4d** [comment]
We are not going to do this in the C++ wallet, and unlikely to ever do this in `zcashd`. This should be considered by the various mobile wallets.
