### ISSUE TITLE
evaluate subset-sum-based hash function for commitment accumulator

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#40]
<a href="https://github.com/daira"><img src="https://avatars.githubusercontent.com/u/643204?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [daira](https://github.com/daira)**
_Sunday Nov 30, 2014 at 02:36 GMT_
_Originally opened as https://github.com/Electric-Coin-Company/libzerocash/issues/3_

---

As noted in http://eprint.iacr.org/2014/595 ("Scalable Zero Knowledge via Cycles of Elliptic Curves") sections 1.4.2 and 5.2, hashing based on modular subset-sum functions can have great advantages in reducing SNARK circuit size: ~300 gates for the function used in that paper (80-bit security level) compared to 27904 gates for the current hand-optimised SHA-256 compression function in the Zerocash implementation (128-bit security level). Note that this idea is independent of the other contributions of the paper and can be used in non-recursive SNARKs.

Subset-sum hashes can be collision-resistant, but they have more structure than "bit-twiddling" hashes, and because they are less efficient on conventional architectures, they have not been explored to the same extent for cryptographic applications. We should ask the hash function gurus we have contacts with --DJB and the BLAKE2 designers-- for their advice about this approach. If we decide to use it, we need to be particularly careful with parameter choices, and that we are using a hash with security properties that are actually sufficient for use in a Merkle tree. Nevertheless, the reduction in circuit size of a factor of possibly 100 for the tree hashing (on top of any reduction in tree depth due to decreasing the limit on number of coins) is extremely tempting.

Note that we do not necessarily have to use the same hash to instantiate the Merkle tree over coin commitments as for the COMM and PRF schemes; I argued at the hack fest that the latter should be more conservative because they can only be changed by recreating all coins. There is no circuit size penalty from using more than one hash per se, since circuits must be duplicated as often as they are used.

**Comment by daira** [comment]
A subset-sum hash *might* also allow for a larger input block and therefore a higher-arity tree, reducing the required depth. We should take this into account in any efficiency calculations.

**Comment by daira** [comment]
A spreadsheet showing the potential circuit size improvement is at https://docs.google.com/spreadsheets/d/1GCZEHqpf3PPDfqujNXgD46RpckJO3_hOczsNB-gTnGc/edit#gid=0
(Despite the /edit in the URL, this is a comment-only share.)

**Comment by daira** [comment]
Note that the spreadsheet doesn't take into account any change in block size. I'd really like to know what the block size of the hash considered there is.

**Comment by daira** [comment]
From https://github.com/Electric-Coin-Company/zcash/issues/426#issuecomment-179296593 , we conclude that a sumset-sum hash of dimension 5 costs in terms of constraints about 7% of a SHA-256 hash: C1 = C2*0.0698 by the definitions of https://github.com/Electric-Coin-Company/zcash/issues/426#issuecomment-179229799

**Comment by daira** [comment]
Reminder: the commitment Merkle tree absolutely requires collision-resistance.

If an attacker can collide treestates, they can forge coins with arbitrary value: If they create two coins with commitments in colliding treestates, then only one of them will go through a balance check, and then they can spend the other that was never balance-checked.

**Comment by zookozcash** [comment]
Just so you know, I'm pretty sure that we're going to target this feature for 2.0, not 1.0, in part because of "project management choo choo train" reasons, i.e., to get a feature like this into 1.0, it already needs to be cryptographically-analyzed, security-reviewed, and merged into trunk before 2016-03-01, so that it has time to undergo testing, review, and deployment in the codebase before 1.0 launch. For the moment I'm leaving the "maybe in 1.0" label on it, but soon — maybe at next week's ZCEng meeting? — I'd like to create a "maybe in 2.0" label to put it into.

**Comment by zookozcash** [comment]
Also, at this week's Zdep meeting, Eli stated quite clearly that he was not confident in the security of subset sum hashing for the parameters we've been talking about, and in fact that he thought it would be broken.

**Comment by daira** [comment]
Cool, now we can stop worrying about that and focus on other ways to improve memory usage if needed :-)

**Comment by daira** [comment]
I strongly prefer MiMC to this, because it's a published cryptanalysis target rather than something where we would have to make up the parameters ourselves. I think we should narrow down the options to Pedersen hashes (#2234) and MiMC (#2233).

**Comment by daira** [comment]
Closing; if anyone wants to make the case for subset-sum hashing to be used in Sapling, please reopen.
