### ISSUE TITLE
403 Forbidden for https://z.cash/depends-sources/boost_1_70_0.tar.bz2

### ISSUE THREAD

**Issue by daira** [zcash/zcash#4001]
The download of https://z.cash/depends-sources/boost_1_70_0.tar.bz2 fails with the following error from Cloudfront:
```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>94916B3538611AE1</RequestId> 
  <HostId>1znHPrPG0Z3tyQ+0GpreXS3AodXqOkuHWDV3uFY+yYpA7KxgZK+Tpdhtjgo3Dys8ssm8i4BmDvk=</HostId>
</Error>
```

The fallback to https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.tar.bz2 succeeds.

**Comment by renuzit** [comment]
I am seeing a 403 `Forbidden!` from https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.tar.bz2 as well.

The boost download works occasionally, but at this point it fails more times than it works.

**Comment by daira** [comment]
This works now.
