### ISSUE TITLE
Add a whitelist for buildbot CI

### ISSUE THREAD

**Issue by ebfull** [zcash/zcash#401]
We currently build every pull request we're sent, which means our CI architecture is somewhat open to attack or vandalism. #376 involves adding docker, which gives us some security, not not much. Let's add a whitelist to only consider certain users' pull requests on buildbot builds.

Currently we do not rely on our build infrastructure for public releases of any kind, but we should consider this eventually.

This applies to both libzerocash and zerocashd repositories.

**Comment by defuse** [comment]
I think homu solves this, so we can close this issue?

**Comment by ebfull** [comment]
Yes! :)
