### ISSUE TITLE
Zcash How to calculate the finalsaplingroot？

### ISSUE THREAD

**Issue by saymissme** [zcash/zcash#4018]
I do not know the principles of calculation finalsaplingroot
like block 530082
> “hash”: “00000000006656b89e9ba007cc6217efd6bdd62217e0f2f407a6aa13c09704c3”,
> “confirmations”: 3002,
> “size”: 7183,
> “height”: 530082,
> “version”: 4,
> “merkleroot”: “facbdb862fceddad4babd694a59a9868ca9288bbc3668a5328d8fcff8db57c1f”,
> “finalsaplingroot”: “554421b799bd5916b24b82f1c701b449083ab8852c1339bde7b63235b090d2dc”,
> “tx”: [
> “8799a7f68a503ebfa2f243be28c1af9512ff1122240d022ad56cc0ef26ab3fe5”,
> “eedda8648423b3d4a59d018ce01e47b40c3d281c49d7d9e23fa0f167eda0d6dc”,
> “f29e7554837273ac2fa2b384b3d0c9ba4298cc163ca079a3432e7daa5b57a4c3”,
> “060bff33b347e59ea66dfa811519f12d2d031b0c0811b2d2f26a2faeb7332159”,
> “9cab070a58ceac38c8004884f48380d89b510bbfae8ffb9e421d5993e63860ba”,
> “5250b3a50b3876781f10b786da06db583f16b5dfff9c26732f97a52b27008945”,
> “4b820e63cb26535ebfc57cd1148ea6d3fb13104633e30962bd6799506c95bdc2”,
> “41e939628e9cdc7edbe4a66ea31b0cc519161dadb4efa6ff96121ec2f5150eba”
> ],
> “time”: 1557487325,

how to got 554421b799bd5916b24b82f1c701b449083ab8852c1339bde7b63235b090d2dc
thx

**Comment by ioptio** [comment]
Sections 7.5, 3.7 and 5.4.1.7 in the protocol spec should direct you towards the answer, let us know if you have further questions.
https://github.com/zcash/zips/blob/master/protocol/protocol.pdf

**Comment by ioptio** [comment]
Closing this due to lack of response. You can reopen this ticket if you have further comments/questions.
