### ISSUE TITLE
How to enable GPU

### ISSUE THREAD

**Issue by zhd785576549** [zcash/zcash#4027]
Has supported CUDA or other GPU?And how to enable it?

**Comment by ioptio** [comment]
Here's a good resource on mining hardware: https://www.zcashcommunity.com/mining/zcash-mining-hardware/
Note, that as the resource above mentions: "with the recent introduction of ASIC miners it is clear that ASICS have a big advantage over GPU rigs."

There's also several threads in the forum about CUDA: https://forum.zcashcommunity.com/search?q=cuda

**Comment by zhd785576549** [comment]
> Here's a good resource on mining hardware: https://www.zcashcommunity.com/mining/zcash-mining-hardware/
> Note, that as the resource above mentions: "with the recent introduction of ASIC miners it is clear that ASICS have a big advantage over GPU rigs."
> 
> There's also several threads in the forum about CUDA: https://forum.zcashcommunity.com/search?q=cuda

Thanks, I will try it.

**Comment by ioptio** [comment]
Closing this but if you have follow up you can reopen.
