### ISSUE TITLE
Can testnet faucet transfer value to address started with ztestsapling?

### ISSUE THREAD

**Issue by yueawang** [zcash/zcash#4028]
Hi,

I successfully set up a zcash followed the instruction in https://zcash.readthedocs.io/en/latest/rtd_pages/user_guide.html and made a transparent transaction using https://faucet.testnet.z.cash/.
The problem is my test shield address generated by z_getnewaddress starts with "ztestsapling" rather than "zs" or "zc" as user guide told, and nothing happened when I tap faucet using this "ztestsaplingxxx" address.
Is there anything wrong in my setup??

My test env:
zcash 2.0.4-rc1

Zcash Conf:
$ cat ~/.zcash/zcash.conf 
testnet=1
addnode=testnet.z.cash

$ ./src/zcash-cli getinfo
{
  "version": 2000425,
  "protocolversion": 170007,
  "walletversion": 60000,
  "balance": 0.00000000,
  "blocks": 3969,
  "timeoffset": 0,
  "connections": 8,
  "proxy": "",
  "difficulty": 1549.694281194795,
  "testnet": true,
  "keypoololdest": 1558355731,
  "keypoolsize": 101,
  "paytxfee": 0.00000000,
  "relayfee": 0.00000100,
  "errors": ""
}

$ ./src/zcash-cli z_getnewaddress
ztestsapling13tnsrstxqy8j2eprrsecxjnlx54qnt3exwlr55thjpjf3p8lqfdl4gxezm30eykgt0xg6q2vy33

**Comment by garethtdavies** [comment]
No, it'll only work with transparent or Sprout addresses see the issue here: https://github.com/zcash/zfaucet/issues/3

You can obviously send to a transparent one and then subsequently to a Sapling one.

**Comment by yueawang** [comment]
Got it, Thanks @garethtdavies
