### ISSUE TITLE
Is there a mock to replace Zcash node for unit testing?

### ISSUE THREAD

**Issue by lsmobile** [zcash/zcash#4051]
Hi Everyone.

Is there a mock to replace Zcash node for unit testing?

Thank you in advance for the answer.
Regards,
Leo S.

**Comment by daira** [comment]
The unit tests run nodes in two ways:
* You can run a Zcash node in "regtest" mode. Similar to Bitcoin regtest mode, this allows cheap mining of coins for use in tests; in Zcash it also allows network upgrades to be activated at arbitrary heights, as described by @str4d [here](https://forum.zcashcommunity.com/t/sending-funds-to-z-addr-in-regtest-mode/32612/2).
* There is a "mininode" implementation in the Python RPC test framework, implemented [https://github.com/zcash/zcash/blob/master/qa/rpc-tests/test_framework/mininode.py](here). This is probably closer to what you're looking for as a mock.

**Comment by lsmobile** [comment]
Thanks so much. I'll try.

**Comment by ioptio** [comment]
Closing this ticket assuming your question was answered. Feel free to reopen if you have further comments.
