### ISSUE TITLE
Could you upload a stable tarball during release?

### ISSUE THREAD

**Issue by swedebugia** [zcash/zcash#4063]
I looked here and on z.cash and found none.

**Comment by garethtdavies** [comment]
https://z.cash/download/ is linked to here: https://zcash.readthedocs.io/en/latest/rtd_pages/install_binary_tarball.html where you will find the latest.

**Comment by swedebugia** [comment]
Thanks!

**Comment by got3nks** [comment]
Version 2.0.6 is not available yet though?
