### ISSUE TITLE
v2.0.6 binary not working on Ubuntu 16.04

### ISSUE THREAD

**Issue by got3nks** [zcash/zcash#4068]
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

`./zcashd: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by ./zcashd)`

**Comment by daira** [comment]
Are you trying to use the Debian Jessie binaries on Ubuntu, or are you building from source as per https://zcash.readthedocs.io/en/latest/rtd_pages/user_guide.html#installation ?

**Comment by got3nks** [comment]
Using binaries provided on this page: https://zcash.readthedocs.io/en/latest/rtd_pages/install_binary_tarball.html

**Comment by garethtdavies** [comment]
The binary uploaded is actually built via Debian Stretch. The docs linked above link to the Gitian Jessie build whereas the provided hash is that of the Stretch build https://github.com/zcash/gitian.sigs/blob/master/v2.0.6_stretch/hello/zcash-2.0.6-build.assert.

On a 16.04 image I get the following:

```
root@18eb04a540bb:/zcash-2.0.6/bin# ./zcashd --help
./zcashd: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by ./zcashd)
```

So probably the binary should be replaced with the Jessie one? cc @charlieok

**Comment by daira** [comment]
Both Jessie and Stretch binaries should be provided. There isn't an Ubuntu binary, so that page should tell users of Ubuntu and other operating systems / distributions to build from source.

**Comment by charlieok** [comment]
yes the tar binary is built on stretch as Gareth says above. I'm not actually sure which use cases that release is for -- as this issue suggests, you can't really assume it will just work on any Linux system, and if you're running Debian we have packages for that.

**Comment by charlieok** [comment]
[zcash-2.0.6-linux64-debian-jessie.tar.gz](https://github.com/zcash/zcash/files/3389097/zcash-2.0.6-linux64-debian-jessie.tar.gz)

Here is a jessie tar.gz binary. It comes from exactly the same build that generated the 2.0.6 jessie debian package that is now published on apt.z.cash.

Sounds like we should update our release process to accommodate multiple tar.gz binary archives, to go with the distro binary packages?

**Comment by got3nks** [comment]
Thanks, it works.

**Comment by charlieok** [comment]
I'm wondering if it's a common occurrence that a user will a) have a system we build on (say, Debian Jessie) and b) want a tar.gz binary release rather than a .deb package.

Is that something people want? Or is this more about trying these tar.gz releases on other non-debian platforms?

**Comment by garethtdavies** [comment]
Not exactly sure how often this would occur but I think in this example these binaries have always worked with Ubuntu 16.04 and suddenly don't anymore due to only publishing the Stretch binaries. I assume the same thing will happen for those using the .deb package on Ubuntu 16.04 when support for Jessie is dropped (in the next release?) and those users will then have to build from source. I think it's more of a documentation issue as noted above that should be clarified but I would assume Ubuntu 16.04 is still very popular as it is still supported out to 2021.

**Comment by daira** [comment]
I think we should treat Ubuntu (several versions, if necessary) as a first-class platform and provide packages for it. I know that is more work, but the work of generalizing the package building to more than one platform has already been done, which helps.

**Comment by str4d** [comment]
Both `zcashd 2.0.6` and Ubuntu 16.04 have reached their respective End-of-Support dates.
