### ISSUE TITLE
zcashd 2.0.6 exits with "EXCEPTION: N5boost10wrapexceptINS_15condition_errorEEE"

### ISSUE THREAD

**Issue by gojomo** [zcash/zcash#4072]
`zcashd` recently built from source `HEAD detached at v2.0.6` on a `Ubuntu 14.04.5 LTS` machine quit with the following boost exception message, some time after catchup to latest blocks had completed:

~~~
************************
EXCEPTION: N5boost10wrapexceptINS_15condition_errorEEE       
boost::condition_variable::do_wait_until failed in pthread_cond_timedwait: Invalid argument       
Zcash in scheduler       

terminate called after throwing an instance of 'boost::wrapexcept<boost::condition_error>'
  what():  boost::condition_variable::do_wait_until failed in pthread_cond_timedwait: Invalid argument
Aborted
~~~

(I see one [closed similar-exception-message report](https://github.com/bitcoin/bitcoin/issues/15379) against Bitcoin Core `bitcoind`.)

The machine had gone through an OS-level "suspend-to-RAM"/"resume" cycle before the error was noticed - but unsure if the error coincided with that step. (Machine has gone through many prior suspend-resumes, with `zcashd` running, without triggering same error – and relaunched latest `zcashd` is running fine, including through another suspend-resume cycle.)

I've now enabled core-dumps where I'm running `zcashd`, in case it recurs – but likely a very-rare threading issue, and just recording here to capture the data point.

**Comment by Eirik0** [comment]
We think what happened here is that during the suspend/resume something that zcashd was expecting to happen quickly ended up taking longer than the allocated timeout. We know that this behavior is broken. We recommend shutting down zcashd before suspending. Closing and copying the information to the related ticket #2523
