### ISSUE TITLE
Testnet minimum difficulty interaction with zip208

### ISSUE THREAD

**Issue by Eirik0** [zcash/zcash#4073]
Currently on testnet if no blocks are mined for 6 * 2.5 minutes then the difficulty target for the next block is reduced to the minimum. This is affected by zip208, but how so is not reflected in the zip. See PR #4025

**Comment by Eirik0** [comment]
Also changes made to GetBlockProofEquivalentTime need to be documented.

**Comment by daira** [comment]
I will file a PR for these soon.

**Comment by daira** [comment]
I checked #4025 for additional issues and found none.

**Comment by daira** [comment]
Fixed in https://github.com/zcash/zips/pull/258
