### ISSUE TITLE
WIP:  RPC Tests Improvement List

### ISSUE THREAD

**Issue by zancas** [zcash/zcash#4076]
This issue is currently a scratch pad for collecting ideas/observations related to RPC tests.

Codecs:
   * a well defined single transformer between Decimal and struct?
   * test_framework, _response or get_response, should deserialize:
            * some field to bytes
            * some to Decimal
   * check for lurking floats

Possible Duplicated Functionality:
   * e.g. in initialize_chain and start_node
   * make classes use proper constructors where relevant

Compare Py3 implementation with bitcoin core

Efficiency:
   * how often is it necessary to run e.g. "initiate_chain"?  Could test run time be cut...  by a constant factor?

Etc:
   * Is it necessary to call mininode operations during a test?  Perhaps use mininode to precompute test vectors, and then store them in explicit form.
   * generate coverage data from a test run, is there dead code in the test code base?
   * increase granularity of tests
   * use standard assertion checking (pytest)
   * type hints?
   * unit tests?
   * implement components in Rust (e.g. mininode.rs)?

Enhancements:
  * run against bitcoin
  * run against zebrad
  * run against YEC

Code Quality:
   * BitcoinTestFramework should inherit from `unittest.Testcase`
   * order tests by time
   * coverage of test code, do we have dead code?

**Comment by zancas** [comment]
What about the 2638 lines of Python that aren't in the `qa` directory, and aren't generated by the build process?
```
/home/ghurder/freshzcash: 0 $
cloc --exclude-dir qa --include-lang Python .
    1191 text files.
    1176 unique files.
    1172 files ignored.

github.com/AlDanial/cloc v 1.82  T=0.09 s (240.3 files/s, 37452.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          22            467            324           2638
-------------------------------------------------------------------------------
SUM:                            22            467            324           2638
-------------------------------------------------------------------------------
```

**Comment by zancas** [comment]
```BASH
/home/ghurder/freshzcash: 0 $
for i in `ls -1`; do PYLINES=`cloc --include-lang Python $i | grep Python | awk '{print $NF}'`; if [ "$PYLINES" != "" ]; then echo $PYLINES $i; fi done
1656 contrib
11411 qa
299 src
683 zcutil
```

**Comment by Eirik0** [comment]
Hey! Thanks for putting this together. We will look in to this when we look in to the py2->py3 migration.

**Comment by zancas** [comment]
Obsolete.
