### ISSUE TITLE
Set up zcash explorer insight-ui

### ISSUE THREAD

**Issue by SotaTek-HungVu** [zcash/zcash#4079]
How can i set up a proper and up to date zcash insight-ui ( block explorer ) for my own local fullnode. Need help cause i have try many way but none of them working.

**Comment by Sotatek-AnhDao** [comment]
I have an idea! turn off your pc and pray! (:

**Comment by Eirik0** [comment]
We are currently working on building in this functionality to zcashd and expect that to be completed for v2.0.7 which is being released soon. I am not sure if we have finished the formal documentation, but we will post that here as soon as possible.

**Comment by garethtdavies** [comment]
@SotaTek-HungVu I have completed a write up of installing the Insight explorer that works on 2.0.7-rc1 here https://garethtdavies.com/crypto/zcash-insight-blockchain-explorer.html

**Comment by SotaTek-HungVu** [comment]
@garethtdavies Thank you so much

**Comment by bitzec** [comment]
https://github.com/ZECmate/bitcore-node-zecmate

Cheeck this .. its insight and has an zcash richlist

**Comment by daira** [comment]
@garethtdavies Typo in https://garethtdavies.com/crypto/zcash-insight-blockchain-explorer.html : s/hohup/nohup/

**Comment by SotaTek-HungVu** [comment]
@garethtdavies i cant install the bitcore-node-zcash lib with npm, any help
