### ISSUE TITLE
Incorrect if-clause in CBlockTreeDB::ReadAddressUnspentIndex

### ISSUE THREAD

**Issue by growlot** [zcash/zcash#4081]
Found an issue to be corrected in CBlockTreeDB::ReadAddressUnspentIndex.
https://github.com/zcash/zcash/blob/0ba07d5842dcafedb35097accb7204e7a0bee8f0/src/txdb.cpp#L329
I think it should be:
```
if (!pcursor->GetValue(nValue))
            return error("failed to get address unspent value");
```
Thanks

**Comment by str4d** [comment]
This was fixed in #3926.
