### ISSUE TITLE
All my Zcash is missing 

### ISSUE THREAD

**Issue by pche725** [zcash/zcash#4091]
### Describe the issue
All my 21 Zcash is missing.

I am using Atomic wallet and all my ZEC missing, gone during update a new version of Atomic wallet 2.5.1 from 2.4.0
My original ZEC address in Atomic wallet version 2.4.0 is t1QoKeDodWhdmPqwioEG5hFNV9VP4UkLkk8

I clicked on download bar. ( it says New version of Atomic Wallet is available) and it’s loading for a few hours so I was waiting for the updating but update was failed.
I found out that My balance was 0 in Atomic wallet version 2.4.0 after failed to update. 
I checked all my transaction history and all my ZEC was sent to t1hCNVpCgDCrAA9enzNebRvSLYN2YMMbV5R  and then finally it was sent to   t1g63BuSxWUhsStSS6icTqG4igFfBz7vgTw  

 [[t1g63BuSxWUhsStSS6icTqG4igFfBz7vgTw]](https://zecblockexplorer.com/address/t1g63BuSxWUhsStSS6icTqG4igFfBz7vgTw)
Please refer to mined Aug 8, 2019 10:24:31 PM.

Plz check this suspicious ZEC address t1g63BuSxWUhsStSS6icTqG4igFfBz7vgTw   since all other ZEC were sent to this address when I checked all transaction history for Z cash. 

This transaction never made by me and I downloaded a genuine Atomic (Atomic confirmed it)
Nothing wrong from my side and Atomic.
I don't know about these two Zcash address  t1hCNVpCgDCrAA9enzNebRvSLYN2YMMbV5R
t1g63BuSxWUhsStSS6icTqG4igFfBz7vgTw
I never shared my private keys or saved on my device.
I want you to get back to all my Zcash ASAP.
Please reply me ASAP.

**Comment by daira** [comment]
@pche725 did you close this ticket intentionally, or by accident?

**Comment by braddmiller** [comment]
@pche725 We haven't had a response on this for about a month. If this is still an issue please reopen the ticket.
