### ISSUE TITLE
Exploring SNARK Recursion without pairing cycles

### ISSUE THREAD

**Issue by ebfull** [zcash/zcash#4092]
In order to achieve recursive composition of zk-SNARK proofs we need to somehow verify a proof within the circuit over Fq (the scalar field of the pairing friendly curve), which involves extensive arithmetic over Fp (the base field of the pairing-friendly curve). The current approach used by e.g. Coda is to leverage a pairing-friendly cycle of MNT4 and MNT6 curves to bridge between the fields, and there are no other known (practical) methods of finding secure pairing-friendly cycles with other embedding degrees. As a result, they are forced to use large primes (over 700 bits) to compensate for the security loss.

I'd like to explore a different approach. Instead of a pairing-friendly cycle, let's use a cycle where only one of the curves is pairing-friendly. The curve over Fq (which has subgroup order p) can be used e.g. to instantiate a proving system for all of the arithmetic over Fp. **Crucially, it's not necessary for the inner proving system to be succinct, it just needs to allow us to outsource Fp arithmetic more efficiently than it can be naively simulated in Fq.** ~As an example, we could perhaps use [Spartan.](https://eprint.iacr.org/2019/550.pdf)~ [Nevermind, use Halo!](https://eprint.iacr.org/2019/1021)

It is trivial to build cycles of the kind needed using BN curves. In order to meet conservative security margins, we need primes roughly around 2^384 at least. However, if the inner proving system is efficient enough to verify within the circuit this could potentially be considerably more efficient than the larger >700 bit primes used by Coda. (Large primes increase the cost of FFTs, increase the size of parameters, increase the cost of group arithmetic, increase the cost of multi-exponentiations, increase the cost of the pairing function, and increase the size of keying material.)

**Comment by ebfull** [comment]
# Terminology Reference

Fp is the base field of the pairing-friendly curve.
Fq is the scalar field of the pairing-friendly curve.

E0/Fp is the pairing-friendly elliptic curve constructed over Fp, with order q.
E1/Fq is the embedded elliptic curve constructed over Fq, with order p.

**Comment by daira** [comment]
Here is a sage program to find such cycles of BN curves: https://github.com/daira/curvesearch/blob/master/halfpairing.sage

Run using `sage halfpairing.sage <minbitlength>`. For example:
```
$ sage halfpairing.sage 394
bitlength 394
p = 0b1011011110000100100100000000000000000000000000000000000000000000000001010110010111001000000000000101011001011100100000000000000000000000000011110011110110000000000000011110011110110000000000000001010001010010000100110010000000000000000000111001011000000000000000000100110010000000000010010000001100110000000000100100000000000000000000000100100000000000000000000000011000000000000000000000000001 (weight 80), towering-friendly
q = 0b1011011110000100100100000000000000000000000000000000000000000000000001010110010111001000000000000101011001011100100000000000000000000000000011110011110110000000000000011110011110110000000000000001101100011000000100110010000000000000000000111001011000000000000000000110011000000000000010010000001100110000000000100100000000000000000000000110000000000000000000000000011000000000000000000000000001 (weight 81)
u = 0b10001000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000 (weight 3)
E0/Fq : y^2 = x^3 + 10
E1/Fp : y^2 = x^3 + 26

bitlength 394
p = 0b1001000000000000010010000000000000001110000100000000000101010110000000000011001111110110000011100001110110000001111001101110000100011100010101110010010000000100010000010111011100111101100100101010010001000000011101110100000101000101010111110000010101011001111110000010011001000001001000001000000100000000100100001111000000000100100000001100000000010010000000000000000000110000000000000000000001 (weight 123), towering-friendly
q = 0b1001000000000000010010000000000000001110000100000000000101010110000000000011001111110110000011100001110110000001111001101110000100011100010101110010010000000100010000010111011100111101100100101010101001000000011110001100000101000101011110100000010101011010010110000010011100000001100000001001100100000000100100010010000000000100100000001100000000011000000000000000000000110000000000000000000001 (weight 120)
u = 0b10000000000000000001000000000000000000000010000000000000000000000000000000001000000000000000000000 (weight 4)
E0/Fq : y^2 = x^3 + 5
E1/Fp : y^2 = x^3 + 10
```

**Comment by daira** [comment]
In the case of Spartan with arithmetic circuits over Fp and group E0/Fq, we require arithmetic in both Fp and Fq for the verification. However, it appears that the amount of Fp arithmetic needed is quite limited, in particular the number of multiplications (and more importantly, reductions) in Fp for circuit size |C| is O(log(|C|)), even though the overall verification is O(sqrt(|C|)).

**Comment by daira** [comment]
In order to maximize the efficiency of the recursion, we should have the Spartan circuit batch-verify as many SNARK (e.g. Groth16) proofs as possible, and have the SNARK circuit verify only one Spartan proof. This is optimal because:
* batch Groth16 verification is very efficient in terms of constraint cost (see #3425);
* the quadratic cost of Spartan verification means that it is wasteful to use a small Spartan circuit; if we multiply the circuit size by 4 then the verification cost in the SNARK is less than double (because part of the cost is logarithmic), whereas verifying 4 Spartan proofs in the SNARK would cost 4 times as much.

**Comment by daira** [comment]
Note that this approach to recursion obtains the security advantages of a [SHARK](https://dci.mit.edu/zksharks) (the two leafmost layers of recursion are essentially the generic construction of a SHARK; alternatively we could use the optimized SHARK construction for those two layers). That is, we can retain the non-pairing-based proofs and be able to reconstruct the rest even if the SNARK is broken, or if there's some implementation problem with the recursion such as a circuit error.

Note that only the leafmost proof system needs to provide zero knowledge. We might be able to instantiate the non-pairing proof system used for higher layers without zero knowledge, if that turns out to be more efficient.

**Comment by daira** [comment]
BN curves are always "towering-friendly", i.e. p is 1 (mod 6), which allows efficient implementation of extension fields Fp<sup>k</sub> outside the circuit.

p-1 and q-1 are always multiples of 3, which means that cubing is never a permutation in Fp* or Fq* (several of the proposed circuit-efficient hashes are more efficient when cubing is a permutation).

**Comment by daira** [comment]
BTW, a cycle of curves, not necessarily all pairing-friendly, is called an *aliquot cycle* [[Stange and Silverman 2009]](https://arxiv.org/abs/0912.1831). If the cycle is of length 2 then it is called an *amicable pair*. So what we're using here is a "half-pairing-friendly amicable pair".

**Comment by ebfull** [comment]
The inner product amortization technique from Halo can possibly allow this half-pairing idea to be much faster than SNARKs over the MNT4/MNT6 cycle; at the very least it should be competitive, which is great for avoiding giant fields.

**Comment by bpfarmer** [comment]
I would be curious to learn a bit more about the half-pairing recursion approach with curves E_1(F_q) with order p and E_2(F_p) . It seems as though the approaches are to (1) use Groth-Spartan, (2) use Groth-a variation of the Halo amortization technique, or (3) use Groth-some other proving system that uses a dlog polynomial commitment/evaluation scheme rather than one based on pairings. Is it the case that the challenges for each approach are the following?

(1) To my knowledge, there isn't an implementation of a Spartan prover, and the cost of non-native field arithmetic in F_p might be prohibitive.

(2) The cost of verifying the amortized Halo checks might be expensive.

(3) It's unclear whether there exists an efficient proving system with this property.

Just trying to get a sense of whether the half-pairing idea is immediately feasible and lacking an implementation or still requires theory, thanks!

**Comment by ebfull** [comment]
Spartan is a non-starter and I should edit the OP comment to point at Halo. You'll want to use Halo with Sonic or PLONK or Marlin. I am not aware of any theoretical barriers for achieving the half-pairing recursion.

**Comment by daira** [comment]
@imeckler is actively working on this approach; not sure about the detail of which proof systems: https://twitter.com/izmeckler/status/1203755421053276160

**Comment by imeckler** [comment]
Currently using a system based on Marlin, instantiated on the pairing friendly side with Kate and on the non friendly side with a batched variant of the WTS scheme.

**Comment by bpfarmer** [comment]
Oh nice, thanks, we've also been working on something similar, will post here when it's open sourced.

**Comment by jon-chuang** [comment]
@ebfull The verifier circuit for Halo in terms of arithmetic complexity is significantly bigger than for pairing-based recursive SNARKs (about 10-20x bigger). Even considering that the outer SNARK is smaller (at most 2-4x faster pairing), being able to fit 10-20x fewer inner proofs will tip the scales towards pairing-based recursion. Prover times of 10s on 16-threads is not encouraging either. 

By the way, is the overall proof time for Halo linear?

**Comment by jon-chuang** [comment]
@imeckler What is your progress on using a BN curve on the pairing-friendly side? Since the verification circuit for Bulletproofs seemed larger than for pairings, does it truly reap the benefits of a smaller field size in terms of proving and verification times and proof size?

**Comment by daira** [comment]
By WTS you mean Hyrax?

I believe there's a flaw in the poly commitment scheme in Appendix A of the [Hyrax paper](https://eprint.iacr.org/2017/1132.pdf). @ebfull would know more.

**Comment by ebfull** [comment]
@imeckler is aware that the WTS scheme cannot be used as-is, and I think he is already using the scheme from the Halo paper which resolves this concern.

The "flaw" is that the WTS scheme effectively takes the polynomial commitment `P` and the claimed evaluation `v` and computes

`P + [v] U`

for some fixed `U`, and proceeds to use the Bulletproofs protocol modulo the second vector, which the verifier can handle itself. But in a polynomial commitment scheme the prover has arbitrary control of `P` and can include terms involving `U` in `P` to counteract the addition of `[v] U` at the beginning. In fact, they could commit to the zero polynomial in all their commitments so they can leverage this without even knowing the evaluation points in advance.

I'm not very familiar with Hyrax, so I don't know if this is a problem for them, but it's definitely a problem for us. `U` needs to be sampled after the prover and verifier have agreed on the commitment `P`. Hence, we do so in the Halo paper.

**Comment by daira** [comment]
We're "all-in" on this approach now with Halo 2, but I think this particular circuit is only of historical interest and can be closed.

**Comment by daira** [comment]
For anyone looking for a half-pairing cycle I suggest [Pluto-Eris](https://github.com/daira/pluto-eris). It has many of the same engineering advantages as Pallas-Vesta, and it is 446 bits which conservatively achieves 128-bit security against STNFS attacks.

**Comment by jon-chuang** [comment]
I suppose it would be a future "upgrade pathway" for zcash?

**Comment by daira** [comment]
No, we're using the Pallas-Vesta curves and are unlikely to change, since Halo 2 doesn't need pairings. Pluto-Eris was/is just a personal research project, since I think that approach has merit for further usage outside Zcash.

**Comment by wyattbenno777** [comment]
This is a great historic thread. Is there any new work on this being done any write ups or did it reach its theoretical conclusion?
