### ISSUE TITLE
Establish a cost model appropriate for arithmetic circuits in {Spartan, Bulletproofs, Sonic, Halo, PLONK} styles

### ISSUE THREAD

**Issue by daira** [zcash/zcash#4094]
Proposed cost model:

* M for a general multiplication (as in R1CS; also the cost of a division);
* m for a constant multiplication (free in R1CS; same as M in Spartan)
* A for an addition/subtraction gate (free in R1CS; same as M in Spartan)
* B for a Boolean-constrained witness variable
* W for an unconstrained witness variable.

We can use this model for both R1CS and Spartan-style circuits, ignoring m, A and W when we only care about R1CS.

@ebfull, does this model also work for Sonic?

**Comment by daira** [comment]
The motivation here is to be able to estimate costs for the approach in #4092, for example &mdash; where we use both Spartan or similar both for leaf proofs, and to recursively batch-validate other proofs, possibly in conjunction with a pairing-based SNARK.

It looks as though other *universal* proof systems (i.e. not requiring a trusted setup for each circuit, or possibly at all) tend to use a similar circuit language to Spartan, and so we would also need something like this for programmability.

**Comment by daira** [comment]
Idea: when writing out circuits, use the R1CS notation but mark new witness variables in bold on their first use. Then the cost of witness variables can be read off easily, just like the number of R1CS constraints (occurrences of ×) and the number of additions/subtractions. I'm not sure whether we need to distinguish constant and non-constant additions/subtractions and multiplications.

**Comment by ebfull** [comment]
I believe there is only a constant factor overhead in moving R1CS into Sonic-style and Spartan-style arithmetization.

**Comment by daira** [comment]
I don't think that's true for Spartan. Addition/subtraction gates count, and there can be (even asymptotically) more addition gates than multiplication gates in a given circuit.

**Comment by daira** [comment]
As an illustrative example, consider a circuit that just does a Toom-n multiplication of committed values for large n. In R1CS it costs O(n) constraints; in Spartan it costs O(n<sup>2</sup>) gates.

**Comment by daira** [comment]
Hmm, in R1CS costs I've been writing C for things that happen to take 1 constraint but are not multiplications, for example selection (z = b ? x : y) and Boolean constraints. I think a Boolean constraint costs M in Spartan because it can be written as b × b = b. I think selection is more expensive, though.

**Comment by daira** [comment]
For both R1CS and non-R1CS, I think it makes sense to use another cost term B to count the Boolean constraints. Ordinarily this would cost M+W, but it's easier to just count the non-Boolean constraints for W, and it may be useful to count Boolean constraints separately because they are potentially optimisable in any proof system.

**Comment by daira** [comment]
Another relevant system to consider is the quadratic equation-based (QE) constraint system used in https://eprint.iacr.org/2019/944.pdf (which is a refinement of Bulletproofs).

**Comment by kobigurk** [comment]
Should we also take the chance to express uniform computation? Or is it that the proof systems that enjoy this are too different?

**Comment by daira** [comment]
Uniform computation is outside the scope of this particular ticket. It'll be tricky enough finding a model that works well for {R1CS, Spartan, Bulletproofs, Sonic, PLONK}.

**Comment by daira** [comment]
I understand Sonic's cost model much better now. The crucial observation is that in a Sonic constraint system, each multiplication allocates three fresh variables. If you want one of those variables to be "the same as" another variable (in the same or a different multiplication) then you need a linear constraint for every such case.

The consequence of this is that as far as possible, to optimize a Sonic circuit you need to reuse variables that are already allocated by a strictly necessary multiplication. If you fail to do so then you'll need extra multiplications just to allocate those variables: one extra multiplication per two extra variables, since you can allocate two variables a and b by adding a dummy multiplication (a) × (b) = (c) for unconstrained c.

Boolean variables never require extra multiplications, since they're allocated by their Boolean constraint. (They do require two linear constraints to relate the three variables in the Boolean constraint, regardless of whether you write it as (1 - b) × (b) = 0 or (b) × (b) = (b). I'm not sure which method is concretely more efficient.)

**Comment by kenshamir** [comment]
> Another relevant system to consider is the quadratic equation-based (QE) constraint system used in https://eprint.iacr.org/2019/944.pdf (which is a refinement of Bulletproofs).

To give some more information to this topic on 944 from what I understand:

- It refines bulletproofs inner product argument.

- It uses the np-complete language QESA instead of R1SA/`R1CS`. For which R1CS is a special case of QESA (See 1.2.3). This section also notes that using QESA you can have certain optimisations in regards to embedded curves(JubJub), matrix-vector mul and twisted Edwards curve additions. 

- One particular interest for me, are the additional optimisations that can be done due to using QESA instead of R1CS.

**Comment by kenshamir** [comment]
A rough implementation of this protocol with the Linear Map Pre-Image Argument system(LPMA) can be found here: https://github.com/crate-crypto/qesa

**Comment by daira** [comment]
Note that the paper says that Edwards addition can be reduced from 8 R1CS constraints to 5 QESA constraints, but in Sapling we already do it in 6 R1CS constraints. Other situations are similar: you can shave off an odd constraint here and there, but there are very few cases I've seen where QESA gives a substantial improvement over R1CS.

**Comment by kenshamir** [comment]
> Note that the paper says that Edwards addition can be reduced from 8 R1CS constraints to 5 QESA constraints, but in Sapling we already do it in 6 R1CS constraints.

My mistake.

>there are very few cases I've seen where (well optimized) QESA gives a substantial improvement over (well optimized) R1CS

This I did not know. I am currently investigating(in a general sense) what these few cases are and their utility.

**Comment by daira** [comment]
It's looking as though variants of PLONK are gaining ground in the competition of proof systems. Supersonic and RedShift both use PLONK's circuit model. A complicating factor is PLONK's ability to express "custom gates", for example gates that express a MiMC round, or a Montgomery curve addition, or an Fp2 multiplication. These gates are constrained in terms of which wire values they can access, so the "placement" of the gates (assignment of wire indices) becomes important, meaning that it's no longer a "sea of gates" in general. This is not as big a deal for the cost model as it sounds, since in practice you use such gates in specialized contexts like a full MiMC hash, a scalar multiplication, or an E/Fp2 curve operation; therefore the wire index constraints only need to be considered locally.

(SLONK takes a similar idea to an extreme by completely dropping the permutation argument in PLONK that allows nonlocal wire references. This simplifies the proof system conceptually, but would introduce a whole new layer of routing-and-placement complexity to writing and optimizing circuits. In any case it seems to me that SLONK is just an interesting thought experiment, rather than a likely contender for the circuit model of future proof systems.)

**Comment by daira** [comment]
I'm going to close this, because I don't think it's feasible to define a single cost model that will work for all these circuit types. We are going to be focussing on PLONK for new circuit design. PLONK has obvious metrics that can be used for high-level optimization of a circuit + constraint system: the numbers of rows, advice columns, and fixed columns. It can be hard to figure out how to optimize those globally, but the solution is to drill down specifically on the factors affecting PLONK performance (for which see https://github.com/zcash/halo2/issues/47), not to try to come up with a general cost model that would cover other systems.
