### ISSUE TITLE
Zcash downloads are broken

### ISSUE THREAD

**Issue by gracenoah** [zcash/zcash#4095]
Following the instructions at
https://zcash.readthedocs.io/en/latest/rtd_pages/install_binary_tarball.html
The following page is dead:
https://z.cash/downloads/zcash-2.0.6-linux64.tar.gz

**Comment by gracenoah** [comment]
It's back now. It was down only long enough to make all my CI builds fail 😢

**Comment by daira** [comment]
This was a side effect of attempting to switch over the z.cash website infrastructure. Apologies for any inconvenience.
