### ISSUE TITLE
Develop a cleaner way to do local lock-step development of zcashd + librustzcash or other crates

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#4106]
This is a "wishlist" item from my experience learning how to extend `librustzcash`. I wanted to be able to edit the source in my local checkout of `librustzcash` and then change/build my local checkout of `zcashd` (they're directory siblings) and test the results immediately.

By default, with our `./depends` system, only changes with a known hash that can be fetched remotely are built, so the cycle between editing `librustzcash` and editing/building `zcashd` is cumbersome.

I was able to do this kind of local bypass in a really hacky manner by first patching the `librustzcash.mk` depends package file like this:

```
diff --git a/depends/packages/librustzcash.mk b/depends/packages/librustzcash.mk
index 9bc8ee543..ac38630b4 100644
--- a/depends/packages/librustzcash.mk
+++ b/depends/packages/librustzcash.mk
@@ -42,3 +42,20 @@ define $(package)_stage_cmds
   cp $($(package)_library_file) $($(package)_staging_dir)$(host_prefix)/lib/ && \
   cp librustzcash/include/librustzcash.h $($(package)_staging_dir)$(host_prefix)/include/
 endef
+
+## WARNING: DO NOT COMMIT. DO NOT PROPAGATE. DO NOT ACCEPT THE FOLLOWING CHANGES IN A PR.
+# Everything below is a TEMPORARY HACK for local lock-step development against my own librustzcash branch.
+
+define $(package)_fetch_cmds
+( echo '\n\n\n=== HACKY LOCK-STEP LOCAL integration with librustzcash ===\n\n' ; set -x ;cd ~/sandbox ; tar -cjf "$$($(package)_source_dir)/$($(package)_file_name)" librustzcash )
+endef
+
+$(package)_extract_cmds = \
+  mkdir -p $$($(1)_extract_dir) && \
+  echo "$$($(1)_sha256_hash)  $$($(1)_source)" > $$($(1)_extract_dir)/.$$($(1)_file_name).hash && \
+  ( \
+    $(build_SHA256SUM) -c $$($(1)_extract_dir)/.$$($(1)_file_name).hash || \
+    echo '\n\n  ___CAUTION___ integrity checking failed and is bypassed for a local-lockstep-development workaround. REMOVE THIS $(package)_extract_cmds override from any release branch, master, or general shared development branch!\n\n' \
+  ) \
+  && tar --strip-components=1 -xf $$($(1)_source)
+
```

Then, when building `zcashd` if I ever needed to pull in my local changes to `librustzcash` I had to run this "selective" clean of just `librustzcash` artifacts. (The reason for this was to avoid rebuilding all other dependencies.)

```bash
$ time ( rm -fr depends/sources/librustzcash-06da3b9ac8f278e5d4ae13088cf0a4c03d2c13f5.tar.gz ./depends/work/build/x86_64-unknown-linux-gnu/librustzcash/ ./depends/built/x86_64-unknown-linux-gnu/librustzcash/ ./depends/x86_64-unknown-linux-gnu/include/librustzcash.h && ./zcutil/build.sh )
```

The build time on my pixelbook when both my local `librustzcash` and `zcashd` had changes was about 90s, which is reasonable enough for me. For me, this hacky workaround is worth it, except I would never remember it.

Part of why I'm posting this ticket is to document it. The main reason though is to find a better recipe or approach to doing this "lockstep build" between our `./depends` dependencies.

**Comment by zancas** [comment]
When you say: "(The reason for this was to avoid rebuilding all other dependencies.)", do you mean you don't want to trigger the rebuild of all things which depend on `librustzcash` as described [here](https://github.com/zcash/zcash/blame/master/depends/description.md#L29)?

Can someone point me to an issue where I will be forced to make lockstep improvements to `librustzcash` and `zcashd`.   I think that (skin-in-the-game) experience is likely to be the most efficient way for me to learn about this problem space.

**Comment by str4d** [comment]
Any changes to the librustzcash crate will trigger this. I've most recently encountered this problem while testing a setup where the Rust tracing crate is used for logging.

I've worked out a change to the depends system that means this is as simple as `./zcutil/build.sh RUST_OVERRIDE=/path/to/librustzcash`.
