### ISSUE TITLE
No binary tarball for 2.0.7

### ISSUE THREAD

**Issue by 1000101** [zcash/zcash#4113]
### Describe the issue
There seems to be no binary tarball available for the latest version 2.0.7, only 2.0.6

https://zcash.readthedocs.io/en/latest/rtd_pages/install_binary_tarball.html

#### If so, please list the steps to reproduce below:
1. https://z.cash/downloads/zcash-2.0.7-linux64.tar.gz

### Expected behaviour
200 OK

### Actual behaviour + errors
404

**Comment by mdr0id** [comment]
These have been uploaded today. Closing for now, please re open if you have issues
