### ISSUE TITLE
[Theoretical discussion] Multiple PoW blockchain

### ISSUE THREAD

**Issue by fireice-uk** [zcash/zcash#4116]
This is purely theoretical issue. I will close it immediately not to interfere with issues that need action, rather than some armchair thought on a Sunday morning :). 

### Background

Combining multiple PoWs on a single chain in a non-trivial problem. I was discussing it with @aivve
and @psychocrypt to see if @daira 's model of "parallel + forcing rule" [[ 1 ]](https://github.com/zcash/zcash/issues/3672#issuecomment-443929484) can be improved upon.

In terms of practical attacks the major concern is that having multiple parallel difficulties makes it easier or game one of them to manipulate timestamps. This happened a few times on Verge blockchain [[ 2 ]](https://blog.theabacus.io/the-verge-hack-explained-7942f63a3017).

### Making others run into a brick wall meant for you

Our major concern was how "forcing" interacts with difficulty algorithm. In particular consider following scenario with PoW-A mined by majority and PoW-B mined by minority of miners.

1. Alice, a miner with let's say 25% of PoW-B joins the network. This isn't very far fetched as PoW-B is the less popular, and therefore easier one.
2. As the difficulty adjusts to compensate for the higher block count, the forcing limit is hit
3. Alice leaves the network switches to mine another coin.
4. Miners on PoW-B are forced to stop. 
5. When the miners can resume, the difficulty plummets.
6. Go to 1. 

While this kind of oscillation pattern can (and does) happen on any coin, having a brick wall to stop other miners works distinctly to Alice's advantage here, as she is effectively taking a chunk of what B miners would have mined under a hard stop.

### Replacing a brick wall with a sand trap

General formula that a mined needs to meet is  max_value / (hash_value*df) > difficulty 

`df` is 2^32 for most BTC-based coins, and 1 for most Cryptonote-based coins. Chain work is a sum of block difficulties - so nothing we do here will affect the chain length.

Therefore we can change the formula slightly to max_value / (hash_value*df*sf) > difficulty

 `sf` (scaling factor) can be used to make PoW-B's recovery smoother. Whether it should be linear or geometric in proportion to the amount of blocks needs to be simulated. My first instinct would be to make sf for a 12 block sized window:

`2^(min(b_cnt - 6, 0))`

Another avenue that can be explored in removing the min condition and making A easier if B is harder - and whether that can be gamed between the miners.

**Comment by daira** [comment]
We prefer "theoretical" issues to stay open. Closed issues are basically completely ignored.

**Comment by daira** [comment]
On the other hand, there hasn't been much interest in this topic since Harmony mining was abandoned, and there's no proposal to include it in NU5, so this ticket might as well be closed.
