### ISSUE TITLE
when  will the main net  Blossom activated?

### ISSUE THREAD

**Issue by ruyichang** [zcash/zcash#4123]
when  will the main net  Blossom activated?

**Comment by Eirik0** [comment]
Blossom activation is currently targeted for 2019-12-11 19:00 UTC.

**Comment by daira** [comment]
To clarify, we will aim for that time, but upgrade block heights can only be targetted to within a few hours.

**Comment by ruyichang** [comment]
@Eirik0 @daira thanks
