### ISSUE TITLE
Unable to disable Transaction expiry

### ISSUE THREAD

**Issue by mohamedGr** [zcash/zcash#4132]
Hi,

Is there a way to set  `expiryheight` to be unlimited when generating a zcash transaction through the rpc or in the daemon config file?

It says [here](https://github.com/zcash/zips/blob/master/zip-0203.rst#specification) that this is possible by setting the expiration to be `0`, but I couldn’t find how to configure this.

I tried to call the `createrawtransaction` rpc method by passing `0` as below:

`raw_tx = self.rpc.createrawtransaction(in_txn, outputs, 0, 0)`

But it looks like the minimum for the expiryheight in the createrawtransaction is `4`. 
I think this where the error that I am hitting is thrown,

https://github.com/zcash/zcash/blob/424d8b1af52d0c84812de69657b4a596afd7c22e/src/rpc/rawtransaction.cpp#L546

and this is due to the fact that `TX_EXPIRING_SOON_THRESHOLD` is set to `3` and passing `expiryheight` as `0` to disable the transaction expiry doesn't seem to be possible. 

Passing the `-txexpirydelta=0` when starting the node doesn't seem to work either, it accepts at least `4`

**Comment by daira** [comment]
@mohamedGr wrote:
> Passing the `-txexpirydelta=0` when starting the node doesn't seem to work either, it accepts at least 4

That's because `-txexpirydelta` is relative to the current height. I think it's by design that `-txexpirydelta=0` doesn't disable expiry (it didn't before the "expiring soon" limitation was added). In any case, the PR doesn't address that, but it does fix `createrawtransaction`.

**Comment by mohamedGr** [comment]
> @mohamedGr wrote:
> 
> > Passing the `-txexpirydelta=0` when starting the node doesn't seem to work either, it accepts at least 4
> 
> That's because `-txexpirydelta` is relative to the current height. I think it's by design that `-txexpirydelta=0` doesn't disable expiry (it didn't before the "expiring soon" limitation was added, either). In any case, the PR doesn't address that, but it does fix `createrawtransaction`.

Awesome, thank you @daira!
