### ISSUE TITLE
assertion failed

### ISSUE THREAD

**Issue by wyf15** [zcash/zcash#4141]
zcashd said:
Exception: St13runtime error
Assertion error
C:\Program FIles (x86)\zec-qt-wallet\zcashd.exe in AppInit()

in Win10

This issue tracker is only for technical issues related to zcashd.

General Zcash questions and/or support requests and are best directed to the [Zcash Forums](https://forum.z.cash) or [Community Rocket.Chat](https://chat.zcashcommunity.com).

For reporting security vulnerabilities or for sensitive discussions with our security team, please contact [security@z.cash](mailto:security@z.cash). You can use the [GPG key](https://z.cash/gpg-pubkeys/security.asc) (fingerprint: `AF85 0445 546C 18B7 86F9  2C62 88FB 8B86 D8B5 A68C`) to send an encrypted message. The key and fingerprint are duplicated on our [Public Keys page](https://z.cash/support/pubkeys.html).

### Describe the issue
Please provide a general summary of the issue you're experiencing

#### If so, please list the steps to reproduce below:
1. 
2. 
3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour + errors
Tell us what happens instead including any noticable error output (any messages displayed on-screen when e.g. a crash occurred)

### The version of Zcash you were using:
Run `zcashd --version` to find out

### Machine specs:
- OS name + version:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):
- Linux kernel version (uname -a):
- Compiler version (gcc --version):
- Linker version (ld -v):
- Assembler version (as --version):

### Any extra information that might be useful in the debugging process.
This includes the relevant contents of `~/.zcash/debug.log`. You can paste raw text, attach the file directly in the issue or link to the text via a pastebin type site.
Please also include any non-standard things you did during compilation (extra flags, dependency version changes etc.) if applicable.

### Do you have a backup of `~/.zcash` directory and/or take a VM snapshot?
- Backing up / making a copy of the `~/.zcash` directory might help make the problem reproducible. Please redact appropriately.
- Taking a VM snapshot is really helpful for interactively testing fixes

**Comment by daira** [comment]
Can you post the last 100 lines of `debug.log`, please? By default that file is at  `%HOMEPATH%\AppData\Roaming\Zcash\debug.log` where `%HOMEPATH%` is typically `C:\Users\username`.

Also, what version of zcashd are you running?

Does this assertion failure happen every time you start zcashd? Did it previously run successfully? Did you use prebuilt binaries?

**Comment by braddmiller** [comment]
This may be a zec-qt-wallet issue, @adityapk00, any ideas?

**Comment by adityapk00** [comment]
Are you using 32-bit Windows?

**Comment by wyf15** [comment]
> Are you using 32-bit Windows?

I am using 64-bit Windows

**Comment by Eirik0** [comment]
@wyf15 Are you able to post the last 100 lines of your debug.log?

@adityapk00 did you have any follow up questions?

**Comment by Eirik0** [comment]
@wyf15 Are you still experiencing this issue? We would need the last 100 lines of the debug.log to proceed further.

**Comment by daira** [comment]
There is insufficient information to debug this issue, if it still exists. Closing.
