### ISSUE TITLE
Where can I find the public key to address inference process

### ISSUE THREAD

**Issue by chenzhijun45** [zcash/zcash#4143]
I couldn't find the explain about public key to address inference process  in the document.
Who can tell me ? thanks

**Comment by daira** [comment]
I'm not sure what you mean by "inference process". Do you mean the zk-SNARK proving or verification keys?

**Comment by chenzhijun45** [comment]
I am sorry that my English is not well.
I can not  express myself well.
I have found my answer.
https://bitcoin.stackovernet.com/cn/q/10511
https://github.com/zcash/zcash/blob/master/src/chainparams.cpp#L102-L114
