### ISSUE TITLE
On-disk Parameter Compression

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#416]
The SNARK proving key is very large, a good chunk of the file consists of sequentially increasing numbers encoded in ASCII decimal. There's probably a lot of efficiency to be gained by changing the encoding and perhaps even running it through a simple data compressor.

**Comment by ebfull** [comment]
We cannot enable point compression until a DoS vulnerability is fixed in libsnark's sqrt implementation: #1073

**Comment by ebfull** [comment]
Hm, we're not going to use point compression for the parameters anyway, since it's too costly to decompress the entire key. The solution to #491 and the fact we already fixed #799 will reduce our ability to compress the keys in any significant way.

**Comment by daira** [comment]
There is still the option to use point compression in the downloaded format and then decompress for the on-disk format after download (as opposed to when loading from disk). That may be too complicated for 1.0. In the longer term, there might be the option to switch to an x-coordinate-only curve (in the same sense as Curve25519), but I don't know whether that's feasible at all for the pairing and/or SNARK.

**Comment by ebfull** [comment]
I vote that we do not do this for 1.0, since it won't change consensus rules to improve the compression of the keys after launch.

**Comment by nathan-at-least** [comment]
@ebfull: Agreed, let's put this in the large bucket of post-1.0 improvements.

**Comment by wkarshat** [comment]
For a quick check whether the params files have lots of fluff at this point, ran some compression on them.
Only compress a few percent, so apparently not too much.
[param_comp.xlsx](https://github.com/zcash/zcash/files/3305700/param_comp.xlsx)

**Comment by daira** [comment]
A general-purpose compression routine won't be able to compress curve points (unless there are identical points). Specialized point compression gets a compression ratio of roughly 50%; that's what this ticket was primarily talking about.

**Comment by wkarshat** [comment]
Would love to learn more. 
Decimal represented numbers should compress with LZ, maybe tune dictionary size.
What about the binary format, what about decompress time?

**Comment by str4d** [comment]
I'm marking this as being closed by #4060, since this issue refers to the original parameters. We should open a separate issue for later parameter files, if necessary.
