### ISSUE TITLE
Lightwalletd mainnet/testnet compatibility

### ISSUE THREAD

**Issue by braddmiller** [zcash/zcash#4173]
Story: As a wallet developer I would like a block server that allows me to quickly switch connection between mainnet and testnet so that I can test and deploy quickly.

Criteria:
1) Connection to either chain is as simple as passing a parameter
2) After initial sync, reconnecting to either network only requires syncing from the last known block
3) It is clear to any client connecting to the server which network it is connected to

**Assigned to: Larry** 
**Points: 8**

**Comment by LarryRuane** [comment]
This can be considered low priority.

**Comment by LarryRuane** [comment]
I don't think this is needed, and is a bit underspecified. For example, one might conclude from the description that this is a lightwalletd enhancement, not a zcashd enhancement.
