### ISSUE TITLE
Add "sanity check magic numbers" to libsnark serializations

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#418]
I just spent a lot of time debugging for #378. In the end, the problem was I was trying to deserialize a `r1cs_ppzksnark_proving_key` when what was serialized was in fact a `zerocash_pour_proving_key`. The difference between the two is small (the former is a suffix of the latter), so crazy things happened.

This bug would have been caught instantly if every class that does serialization and deserialization first writes (or verifies) a magic string unique to that class. This would serve as a sanity check that what you're about to deserialize is actually what you think it is.

**Comment by daira** [comment]
Note that the libsnark serializations are not consensus-critical, so we could still do this. It's low priority though.
