### ISSUE TITLE
Wherever upstream policy is anchored to a block height, we must do something about that.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#420]
One wacky option is to have a kind of "virtual block height" that is the number of zc blocks + some magic constant that makes the sum match all of the bitcoin policy checks appropriately.

**Comment by daira** [comment]
I believe we made all  previous forks unconditional, i.e. this should be closed as fixed.

**Comment by nathan-at-least** [comment]
Leaving this on the agenda to poll everyone to see if we know of any exceptions / follow up work. If not, I assume it's safe to close.

**Comment by nathan-at-least** [comment]
@ebfull and @daira aren't aware of any unaddressed block-height dependencies, so this is no longer relevant.
