### ISSUE TITLE
Failing Windows Build - now master branch - edit

### ISSUE THREAD

**Issue by milesmanley** [zcash/zcash#4214]
### Can you reliably reproduce the issue?
Yes

#### If so, please list the steps to reproduce below:
1. Install all dependencies required according to user guide 
2. Run `HOST=x86_64-w64-mingw32 ./zcutil/build.sh -j$(nproc)` according to user guide
3. - Run into this error

### Expected behaviour
Zcash should be built for Windows with dependencies and instructions found here: 
https://zcash.readthedocs.io/en/latest/rtd_pages/user_guide.html#build

### Actual behaviour + errors
Runs into this error 
![image](https://user-images.githubusercontent.com/35818597/68517199-775deb00-027e-11ea-9b5f-476d538f787b.png)

### The version of Zcash you were using:
I am building the master branch v2.1.0-1 | [zcash::master](https://github.com/zcash/zcash) for windows 

### Machine specs:
- OS name + version: Ubuntu 18.04.3 LTS
- CPU: Intel Xeon E312xx (Sandy Bridge)
- RAM: 32GB
- Disk size: 640GB
- Disk Type: SSD
- Linux kernel version : `4.15.0-55-generic`
- Compiler version: `7.4.0`
- Linker version: `2.30`
- Assembler version: `2.30`

**Comment by milesmanley** [comment]
Just ran from master and have adjusted issue accordingly - same error when building for Windows

**Comment by str4d** [comment]
Ah, this explains the undocumented `(char *)` cast in Bitcoin Core's hidden CVE fix. The POSIX `recv` takes a `void *buf` argument, which will automatically cast from `uint8_t`, making the cast unnecessary and odd. I'll open a PR that documents and fixes this.

**Comment by milesmanley** [comment]
Great, cheers @str4d
