### ISSUE TITLE
Update CTxMemPool::DynamicMemoryUsage() for shielded transactions

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#4224]
While reviewing #4218, I noticed that we never updated `CTxMemPool::DynamicMemoryUsage()` for the additional mempool functionality we've implemented. Currently it computes the mempool memory usage as:

```
// Memory usage of mapTx structure
memusage::MallocUsage(sizeof(CTxMemPoolEntry) + 6 * sizeof(void*)) * mapTx.size()
// Two metadata maps inherited from Bitcoin Core
+ memusage::DynamicUsage(mapNextTx)
+ memusage::DynamicUsage(mapDeltas)
// Cached memory usage for each CTransaction within mapTx
// (saves iterating over the full map)
+ cachedInnerUsage
```

We need to include the following structures that we introduced:
- Wallet notification:
    - `mapRecentlyAddedTx`
- Nullifier set tracking:
    - `mapSproutNullifiers`
    - `mapSaplingNullifiers`
- DoS mitigation:
    - `recentlyEvicted`
    - `weightedTxTree`
- Insight-related structures:
    - `mapAddress`
    - `mapAddressInserted`
    - `mapSpent`
    - `mapSpentInserted`

**Comment by str4d** [comment]
Fixing this will not itself alter the behaviour of `zcashd` (mempool size limiting is governed by the [ZIP 401](https://zips.z.cash/zip-0401) cost mechanic and the `-mempooltxcostlimit` option). `CTxMemPool::DynamicMemoryUsage()` is only used for the `usage` field of the `getmempoolinfo` RPC method result.

**Comment by oxarbitrage** [comment]
I made a commit for this a few weeks ago however i didn't submitted as a PR as i don't know yet how to approach a test case for it.

Open to suggestions.

https://github.com/oxarbitrage/zcash/commit/aecbb7a46d7db3562255b883592cb3dc8e944c8f

**Comment by oxarbitrage** [comment]
I was able to add some testing by adding the individual structure sizes used to calculate the usage into the output. https://github.com/zcash/zcash/pull/4306
