### ISSUE TITLE
libzerocash serialization is inefficient

### ISSUE THREAD

**Issue by ebfull** [zcash/zcash#423]
We're serializing externalCommitment in MintTransaction when it's derivable from the other two fields.

We're also serializing lengths of fixed-sized vectors.

We should run a pass through and fix some of these inefficiencies.

**Comment by daira** [comment]
This is obsolete; our current serialization does not unnecessarily use length fields. (Well, except for the Equihash solution, and we're not fixing that until we change Equihash parameters.)
