### ISSUE TITLE
Change the public/private key pairs for broadcasting alert messages

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#424]
There's an alert system built in where the holders of private keys can broadcast messages to the network. We'll have to change those keys. This is part of #107.

**Comment by ebfull** [comment]
As part of this ticket I will integrate some kind of alert building interface into the codebase so that we can easily issue such alerts.

**Comment by bitcartel** [comment]
Sending alerts follows the same method as described by upstream team members.

Note that all upstream clients have now removed the P2P alert system as they would have been sharing a centralized alert key.

**Comment by ebfull** [comment]
This is done by #1105 and I have received the alert key.
