### ISSUE TITLE
VerifySignature failed: Script evaluated without error but finished with a false/empty top stack element

### ISSUE THREAD

**Issue by yiailongsimon** [zcash/zcash#4263]
When broadcasting a signed transaction, I get the following error:
erifySignature failed: Script evaluated without error but finished with a false/empty top stack element

I use the latest version v2.1.0-1

**Comment by maiiz** [comment]
```
/**
 * General information about each network upgrade.
 * Ordered by Consensus::UpgradeIndex.
 */
const struct NUInfo NetworkUpgradeInfo[Consensus::MAX_NETWORK_UPGRADES] = {
    {
        /*.nBranchId =*/ 0,
        /*.strName =*/ "Sprout",
        /*.strInfo =*/ "The Zcash network at launch",
    },
    {
        /*.nBranchId =*/ 0x74736554,
        /*.strName =*/ "Test dummy",
        /*.strInfo =*/ "Test dummy info",
    },
    {
        /*.nBranchId =*/ 0x5ba81b19,
        /*.strName =*/ "Overwinter",
        /*.strInfo =*/ "See https://z.cash/upgrade/overwinter.html for details.",
    },
    {
        /*.nBranchId =*/ 0x76b809bb,
        /*.strName =*/ "Sapling",
        /*.strInfo =*/ "See https://z.cash/upgrade/sapling.html for details.",
    },
    {
        /*.nBranchId =*/ 0x2bb40e60,
        /*.strName =*/ "Blossom",
        /*.strInfo =*/ "See https://z.cash/upgrade/blossom.html for details.",
    },
    {
        /*.nBranchId =*/ 0xf5b9230b,
        /*.strName =*/ "Heartwood",
        /*.strInfo =*/ "See https://z.cash/upgrade/heartwood/ for details.",
    }
};

```
you should use `nBranchId` of  "Blossom"

see ZIP243 for  detail.

**Comment by cchpan** [comment]
how to use use nBranchId of "Blossom" which is 0x2bb40e60. ?

**Comment by daira** [comment]
@cchpan Since Blossom has already activated, the quickest way to do this is to search for the Sapling branch ID in your code (0x76b809bb) and replace it with the Blossom branch ID.

(If you're using zcashd then this happens automatically; it's only an issue when using custom code to create transactions.)

**Comment by cchpan** [comment]
@daira  thanks，The problem is solved。

**Comment by daira** [comment]
@cchpan good, I'll leave this ticket open for the time being in order to refer to it for others having the same problem.

**Comment by IhorStasiv** [comment]
Hi, I'm looking for a way to update the "Blossom branch ID" in real time. Perhaps you know where such a solution already exists or how to achieve it?
