### ISSUE TITLE
Add buildbot waterfall column for upstream libsnark.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#428]
Let's add a waterfall column to our buildbot (http://ci.leastauthority.com:8010/waterfall) for ``libsnark``. Even though we do not own that repository we can set up a polling build config. Later the ``libsnark`` owners can set up a webhook and/or github PR status updates on their repository if they like our service.

This would also allow us to close #78.

**Comment by daira** [comment]
This is now a duplicate of #521.
