### ISSUE TITLE
Libsodium fails to download - macOS build fails

### ISSUE THREAD

**Issue by milesmanley** [zcash/zcash#4295]
On macOS builds Libsodium fails to download with error 404. 

This is due to the download path changing. I am submitting a PR with the new path. 

Maybe this is an opportunity to update to Libsodium 1.0.16 - my pr just updates the path so it works with currently used 1.0.15.

**Comment by daira** [comment]
We can't update libsodium just yet due to #2872.

utACK.

**Comment by daira** [comment]
#4296 was merged.
