### ISSUE TITLE
Implement -lightwalletd configuration option

### ISSUE THREAD

**Issue by LarryRuane** [zcash/zcash#4326]
This is to more selectively enable Insight Explorer options than -insightexplorer, in particular, addressindex, for better space and time efficiency. I believe @oxarbitrage is planning to implement this.

**Comment by oxarbitrage** [comment]
Didn't checked the details yet but i plan to implement this as an experimental feature. Please let me know if this is not a good idea.

We should have this merged first if we do so: https://github.com/zcash/zcash/pull/4293

I added this task in Week 2 of my personal milestone to start the research and implementation:

https://github.com/oxarbitrage/zf-grants/blob/master/2020/milestone2.md

**Comment by oxarbitrage** [comment]
The `-insightexplorer` not only deal with indexes but with several rpc functions that are allowed if this option i present.

The following is a list of rpc calls the `insightexplorer` experimental feature enables when preesent:

- getblockdeltas
- getblockhashes
- getaddressmempool
- getaddressutxos
- getaddressdeltas
- getaddressbalance
- getaddresstxids
- getspentinfo

@LarryRuane please let me know if some(or all) of this functions are needed in the context of the new `lightwalletd` option.

**Comment by LarryRuane** [comment]
Currently, we use only `getaddresstxids`. However, I think it would be prudent to allow all the RPCs that can be enabled by `DB_ADDRESSINDEX`, namely, the ones that start with `getaddress` other than `getaddressutxos` because that requires an additional index, `DB_ADDRESSUNSPENTINDEX`. There is no cost in doing so, and those other RPCs may be useful in the future.

@adityapk00, is that correct? Do you need, or think you may need later, any other RPCs for Zecwallet?

**Comment by adityapk00** [comment]
This is correct - Zecwallet only needs `getaddresstxids`

**Comment by daira** [comment]
I agree that we should have `-lightwalletd` enable all the RPCs that are "free" to implement using `DB_ADDRESSINDEX`.
