### ISSUE TITLE
Boost fails to compile on latest Apple SDK

### ISSUE THREAD

**Issue by rex4539** [zcash/zcash#4333]
2 days ago, Apple released the [new Beta version of their SDK](https://developer.apple.com/services-account/download?path=/Developer_Tools/Xcode_11.4_beta/Xcode_11.4_beta.xip).

In combination with the [weird way that Boost does version comparison on macOS](https://github.com/boostorg/build/issues/440), results in Boost failing to compile.

A quick hack is to comment out the following lines from the file `darwin.jam`, extracted from the Boost archive under `boost/tools/build/src/tools/`:
```
    # - GCC 4.0 and higher in Darwin does not have -fcoalesce-templates.
    if $(real-version) < "4.0.0"
    {
        flags darwin.compile.c++ OPTIONS $(condition) : -fcoalesce-templates ;
    }
    # - GCC 4.2 and higher in Darwin does not have -Wno-long-double.
    if $(real-version) < "4.2.0"
    {
        flags darwin.compile OPTIONS $(condition) : -Wno-long-double ;
    }
```

**Comment by daira** [comment]
Note that [we require gcc >= 4.2](https://zcash.readthedocs.io/en/latest/rtd_pages/user_guide.html#dependency-version-check), so it is safe to remove the above lines. (On macOS it's actually clang-pretending-to-be-`gcc`, sometimes called LLVM-GCC, but the point is that removing those lines will not cause us to fail to build on any version of either GCC or LLVM-GCC that we previously supported.)
