### ISSUE TITLE
testnet faucet can't send to t-addr

### ISSUE THREAD

**Issue by wshhz** [zcash/zcash#4346]
i want to get some coins whit t-addr,but https://faucet.testnet.z.cash/ show (Issue sending transaction. Is your address correct?)

**Comment by wshhz** [comment]
my t-addr is tmAxxttve4KagQrdzEdB7iLPQcy83nTJobG

**Comment by mdr0id** [comment]
I can confirm the faucet is not sending to t-addrs. We will investigate and update soon.

**Comment by benzcash** [comment]
Ran low on funds, @wshhz can you please try again?

**Comment by mdr0id** [comment]
ACK. Just sent to t-addr and confirmed funds. Closing for now but please reopen if the issue still exists.

**Comment by wshhz** [comment]
the issue still exists,it's show `Issue sending transaction. Is your address correct?` also.

**Comment by benzcash** [comment]
Are you trying to use address `t1Mu5ney............`?

If so, that a mainnet address. The faucet is only for testnet wallet addresses.

If not, what address are you trying to use?

**Comment by wshhz** [comment]
this is my address: tmQXmkoiMrFXY9QqMDVgGqFPj5Pue2o1tzR

**Comment by benzcash** [comment]
OK, think I found the problem and sent that address some funds from the wallet in this transaction https://explorer.testnet.z.cash/tx/9996ce2144b807b482993d42e20eed2428f1a910f02bb32fd687fcd3e037151e

Please try it yourself and let me know if you're still having an issue.

**Comment by wshhz** [comment]
Faucet still can't send tokens to t-addr,my address:tmTniAgYytxHzeD9u5TrvLguhfZT9e2fQDP

**Comment by wshhz** [comment]
@benzcash

**Comment by benzcash** [comment]
Still or again? The faucet ran out again and I refilled.

Sent a be62fa484726c7ee14da414eb259bc6dac2d13e7d5db52298cbf688605ffee74 to the provided address!

**Comment by wshhz** [comment]
ok,now it's ok,thanks! @benzcash

**Comment by wshhz** [comment]
oh,faucet can't send again,my address: tmMLMFzNbyrA3Bg8a6nnKTZc6aEW7hiKBLH @benzcash
