### ISSUE TITLE
Update to hotfix process and versioning convention

### ISSUE THREAD

**Issue by zebambam** [zcash/zcash#4364]
As a result of the retrospective on the issue private-2019-12-20a, fixed in 2.1.1-1, we agreed that the hotfix process needs to be updated for security fixes.

- Trim out old entries and add in note about the release manager communicating directly with comms
- Need zcash-security-fixes policies for dealing with issues in private

**Comment by gojomo** [comment]
Per my comments at #2267, I find the "-1" version notation somewhat obscures a release's significance. The headline/announcement at the ECC blog – "New Releases: 2.1.1 and hotfix 2.1.1-1" – highlights the issue. It sounds as if they both came out at the same time, and leaves it a bit unclear whether everyone should/must get "2.1.1-1", or just people who may have grabbed a rapidly-withdrawn "2.1.1" release, or just the "miners & pools" specifically mentioned by the post text. So: I hope the review of hotfix/urgent-fix processes can consider using bigger version increments to more clearly communicate important releases.

**Comment by daira** [comment]
@gojomo I agree. We are considering changing the numbering convention so that, for a version number major.minor.micro:

* the major version reflects the Network Upgrade number (e.g. the version is bumped to 3 for the release that first supports NU3 on mainnet);
* "normal" releases increment the minor version;
* hotfixes increment the micro version.

**Comment by steven-ecc** [comment]
Just as an update, the convention Daira described above has been adopted.

**Comment by daira** [comment]
@str4d pointed out that we haven't yet updated the hotfix scripts to support incrementing the micro version (rather than the number after the hyphen).

**Comment by daira** [comment]
Here's a case where the difference between the publically advertized version (4.6.0-1) and the Debian version (4.6.0+1) caused confusion: https://forum.zcashcommunity.com/t/i-cant-update-my-zcash-node-to-v4-6-0-1-in-docker/40881

The proposed policy would make it unnecessary to have a difference between those two version numbers for any future release. (The reason why they are currently different for hotfix releases is that [Debian’s version number specification](https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-version) disallows hyphens if there is no `debian_revision`, so e.g. “4.6.0-1” is not a valid version number.)
