### ISSUE TITLE
Return the address corresponding to a viewing key imported by z_importviewingkey

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#4372]
Viewing key equivalent of #3748. This should be implemented similarly to #4220.

**Comment by oxarbitrage** [comment]
Need https://github.com/zcash/zcash/pull/4370 merged first.

**Comment by str4d** [comment]
#4370 has now been merged.

**Comment by holmesworcester** [comment]
This would be helpful to us at Zbay, fwiw!
