### ISSUE TITLE
zcashd quits immediately after running it (OS: Ubuntu 18.04)

### ISSUE THREAD

**Issue by lwins-lights** [zcash/zcash#4373]
- How did I get the executable zcashd
I tried the one from [Debian binary packages](https://zcash.readthedocs.io/en/latest/rtd_pages/install_debian_bin_packages.html) and also built one by myself according to the [user guide](https://zcash.readthedocs.io/en/latest/rtd_pages/user_guide.html)

- Error
After running zcashd, it will print:

` ... Thank you for running a mainnet zcashd v2.1.1-1 node!
You're helping to strengthen the network and contributing to a social good :)`
 
`In order to ensure you are adequately protecting your privacy when using Zcash,
please see <https://z.cash/support/security/>.`

`Since starting this node 0 seconds ago:
-You have validated no transactions.`
 
`Init message: `
 
`[Press Ctrl+C to exit] [Set 'showmetrics=0' to hide]
thread '<unnamed>' panicked at 'couldn't deserialize Sapling spend parameters file: Custom { kind: UnexpectedEof, error: StringError("failed to fill whole buffer") }', src/libcore/result.rs:999:5
note: Run with RUST_BACKTRACE=1 environment variable to display a backtrace.
Aborted (core dumped)`

- Zcash version
v2.1.1-1

- Machine specs
OS: Ubuntu 18.04 LTS
CPU: Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz
RAM: 8GB
Disk size: 1TB
Disk Type (HD/SDD): HD
Linux kernel version (uname -a): 5.3.0-28-generic
Compiler version (gcc --version): 7.4.0
Linker version (ld -v): 2.30
Assembler version (as --version): 2.30

Tell me if further information is needed. :)

**Comment by mdr0id** [comment]
@lwins-lights Please re-run `./zcutil/fetch-params.sh`.

**Comment by lwins-lights** [comment]
> @lwins-lights Please re-run `./zcutil/fetch-params.sh`.

Thanks! The result is the following.
`Zcash - fetch-params.sh`

`This script will fetch the Zcash zkSNARK parameters and verify their
integrity with sha256sum.`

`If they already exist locally, it will exit now and do nothing else.`

**Comment by rex4539** [comment]
Try removing `wallet.dat` and see if you get the same.

If it works, it means you have a corrupted wallet file.

**Comment by lwins-lights** [comment]
> Try removing `wallet.dat` and see if you get the same.
> 
> If it works, it means you have a corrupted wallet file.
> 
> If you still get the same, put the wallet file back and try the following.
> 
>     1. Delete the `/.zcash-params` folder.
> 
>     2. Run `./zcutil/fetch-params.sh`

Thanks! Problem solved by redownloading params. Not sure why the sha256 check did not work before.
