### ISSUE TITLE
Version string advertised over wire is incorrect for patch releases

### ISSUE THREAD

**Issue by ebfull** [zcash/zcash#4375]
I see `receive version message: /MagicBean:2.1.11/: version 170009` being advertised for what is (probably) a 2.1.1-1 node.

**Comment by oxarbitrage** [comment]
My apologies for taking a `good first issue`, i had it on my milestone before the label was added(https://github.com/oxarbitrage/zf-grants/blob/master/2020/milestone4.md#week-2) and i just saw it after the PR was done.

Just for clarification, i don't have the intention to take this type of issues anymore as they are most suited for contributors just starting in the repo.
