### ISSUE TITLE
Ephemeral keypair derived from PrivateAddress

### ISSUE THREAD

**Issue by ebfull** [zcash/zcash#439]
It may be possible to derive the ephemeral keypair used for cryptographic binding of the pour to the rest of the transaction from the zerocash private address. It's not clear that this would provide any advantage, but at least could be used to prove you constructed the pour. (Perhaps this advantage is moot in the context of other properties of the pour.)

**Comment by daira** [comment]
There are two private addresses known to the transaction creator, for the two input coins. The keypair could be derived from both, I suppose.

**Comment by daira** [comment]
This seems to be orthogonal to everything else and could easily be changed later without breaking compatibility.

**Comment by daira** [comment]
Relevant to https://github.com/zcash/zcash/issues/737#issuecomment-187204852 .

**Comment by daira** [comment]
Note however that we need to make sure this does not exacerbate any information leak from #679.

**Comment by daira** [comment]
Essentially this idea is part of the asymmetric payment construction in Sapling (#2277), but it does not need a separate ticket.
