### ISSUE TITLE
Getting Authentication Fail error when connecting my miner

### ISSUE THREAD

**Issue by Reaper1975** [zcash/zcash#4461]
Same issue on all these servers:

Current issue i am having and causes that my miner does not mine at all and i am wasting energy
ZEC: Authorization failed: (“id”:2,“result”:false,“error”:null)
After this error it fails over to nano pool and it is quite irritating.

Same issue on all these servers:
U.S.:      us-east.equihash-hub.miningpoolhub.com:20570
Europe: europe.equihash-hub.miningpoolhub.com:20570
Asia:      asia.equihash-hub.miningpoolhub.com:20570

Please let me know how i can get this resolved and get my miner and worker to connect to the site and start mining.

**Comment by rex4539** [comment]
Try asking at the Discord mining channel -> https://discordapp.com/channels/669694001464737815/679171213142261770

**Comment by mdr0id** [comment]
This appears to be an issue with the mining pool. Please let us know if we can help otherwise.
