### ISSUE TITLE
Collect data on the value moving into the Sprout pool, and the number of Sprout shielding transactions

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#4467]
This will help us to inform https://github.com/zcash/zips/pull/214.

**Comment by str4d** [comment]
I used the following script to collect data from the chain:

```python
from slickrpc.rpc import Proxy
import csv
import progressbar

rpc_connection = Proxy("http://RPC_USER:RPC_PASSWORD@127.0.0.1:8232")

cur_height = rpc_connection.getblockcount()
pbar = progressbar.ProgressBar(max_value=cur_height)

# Genesis
cur_block_hash = '00040fe8ec8471911baa1db1266ea15dd06b4a8a5c453883c000b031973dce08'

with open('zcash-sprout-data.csv', 'w') as csvfile:
    writer = csv.writer(csvfile, delimiter=',',
                            quotechar='|', quoting=csv.QUOTE_MINIMAL)
    while cur_block_hash:
        data = rpc_connection.getblock(cur_block_hash, 2)

        sprout_txs = []
        num_transparent = 0
        num_with_sapling = 0
        for tx in data['tx']:
            if len(tx['vjoinsplit']) > 0:
                # Transactions that involve Sprout
                value_shielded = [jsdesc['vpub_oldZat'] for jsdesc in tx['vjoinsplit'] if jsdesc['vpub_oldZat'] > 0]
                value_unshielded = [jsdesc['vpub_newZat'] for jsdesc in tx['vjoinsplit'] if jsdesc['vpub_newZat'] > 0]
                sprout_txs.append({
                    'num_jsdesc': len(tx['vjoinsplit']),
                    'value_shielded': value_shielded,
                    'value_unshielded': value_unshielded,
                })
            elif 'vShieldedSpend' in tx and ((len(tx['vShieldedSpend']) + len(tx['vShieldedOutput'])) > 0):
                # Transactions that don't involve Sprout and do involve Sapling
                num_with_sapling = num_with_sapling + 1
            else:
                # Purely transparent transactions
                num_transparent = num_transparent + 1

        # Extract some interesting metrics
        num_sprout = len(sprout_txs)
        num_jsdesc = sum([tx['num_jsdesc'] for tx in sprout_txs])
        num_shielding = len([tx for tx in sprout_txs if len(tx['value_shielded']) > 0])
        num_unshielding = len([tx for tx in sprout_txs if len(tx['value_unshielded']) > 0])
        value_shielded = sum([value for tx in sprout_txs for value in tx['value_shielded']])
        value_unshielded = sum([value for tx in sprout_txs for value in tx['value_unshielded']])
        num_less_private_shielding = len([tx for tx in sprout_txs if len(tx['value_shielded']) > 1])
        num_less_private_unshielding = len([tx for tx in sprout_txs if len(tx['value_unshielded']) > 1])

        writer.writerow([
            data['height'],
            num_transparent,
            num_with_sapling,
            num_sprout,
            num_jsdesc,
            num_shielding,
            num_less_private_shielding,
            value_shielded,
            num_unshielding,
            num_less_private_unshielding,
            value_unshielded,
        ])
        if data['height'] <= cur_height:
            pbar.update(data['height'])
        cur_block_hash = data.get('nextblockhash', None)
```

**Comment by str4d** [comment]
I plotted the average transactions per **block**, split into three buckets:
- Transactions that involve Sprout notes in any way (shielding, purely-shielded, unshielding, and Sprout-to-Sapling migration).
- Transactions that only involve Sapling notes and transparent coins.
- Transactions that don't involve any shielded notes.

![tx-types-0-805000](https://user-images.githubusercontent.com/4993799/80187691-2f802400-8664-11ea-823d-3c0223704a27.png)

![tx-types-600000-805000](https://user-images.githubusercontent.com/4993799/80187701-3444d800-8664-11ea-8fd5-a847743c5139.png)

The drop at height 653600 is due to the block target spacing being halved at Blossom activation.

**Comment by str4d** [comment]
I plotted the value moving into (shielding) and out of (unshielding) the Sprout value pool. I didn't collect the value moving into and out of the Sapling value pool, but there is a gradual tail-off in activity from height 419200, as the ecosystem started to use Sapling.

![tx-values-0-805000](https://user-images.githubusercontent.com/4993799/80269103-e03c0100-8700-11ea-9eec-859191c005ed.png)

The same drop at height 653600 (due to Blossom) is visible, but there is another drop around block height 713000. I suspect that this was a mining pool switching from Sprout to Sapling for shielding their coinbase outputs.

![tx-values-600000-805000](https://user-images.githubusercontent.com/4993799/80269108-ea5dff80-8700-11ea-8398-1974451e1b17.png)

The remaining Sprout activity (between blocks 720000 and 805000) shows less than 0.5 ZEC per block on average being shielded. The largest single amount being shielded in this range was 660 ZEC, and the largest single amount being unshielded was 2075.33 ZEC.

![tx-values-720000-805000-500](https://user-images.githubusercontent.com/4993799/80269261-38273780-8702-11ea-9891-b515c5ac42e2.png)

![tx-values-720000-805000-500-zoomed](https://user-images.githubusercontent.com/4993799/80269288-82101d80-8702-11ea-8244-92a04c772b41.png)

**Comment by str4d** [comment]
I modified the above script to collect additional data:
```python
from slickrpc.rpc import Proxy
import csv
import progressbar

rpc_connection = Proxy("http://str4d:zcpassword@127.0.0.1:8232")

cur_height = rpc_connection.getblockcount()
pbar = progressbar.ProgressBar(max_value=cur_height)

# Genesis
cur_block_hash = '00040fe8ec8471911baa1db1266ea15dd06b4a8a5c453883c000b031973dce08'

with open('zcash-shielded-data.csv', 'w') as csvfile:
    writer = csv.writer(csvfile, delimiter=',',
                            quotechar='|', quoting=csv.QUOTE_MINIMAL)
    while cur_block_hash:
        data = rpc_connection.getblock(cur_block_hash, 2)

        txs = []
        num_sprout = 0
        num_transparent = 0
        num_with_sapling = 0
        for tx in data['tx']:
            sprout_shielding = [jsdesc['vpub_oldZat'] for jsdesc in tx['vjoinsplit'] if jsdesc['vpub_oldZat'] > 0]
            sprout_unshielding = [jsdesc['vpub_newZat'] for jsdesc in tx['vjoinsplit'] if jsdesc['vpub_newZat'] > 0]
            sapling_shielding = -tx['valueBalanceZat'] if 'valueBalanceZat' in tx and tx['valueBalanceZat'] < 0 else 0
            sapling_unshielding = tx['valueBalanceZat'] if 'valueBalanceZat' in tx and tx['valueBalanceZat'] > 0 else 0

            is_mixed = len(tx['vjoinsplit']) > 0 and 'vShieldedSpend' in tx and (len(tx['vShieldedSpend']) + len(tx['vShieldedOutput'])) > 0
            is_migration = len(sprout_unshielding) > 0 and 'vShieldedSpend' in tx and len(tx['vShieldedSpend']) == 0 and len(tx['vShieldedOutput']) > 0

            txs.append({
                'num_jsdesc': len(tx['vjoinsplit']),
                'sprout_shielding': sprout_shielding,
                'sprout_unshielding': sprout_unshielding,
                'sapling_shielding': sapling_shielding,
                'sapling_unshielding': sapling_unshielding,
                'is_mixed': is_mixed,
                'is_migration': is_migration,
            })

            if len(tx['vjoinsplit']) > 0:
                # Transactions that involve Sprout
                num_sprout = num_sprout + 1
            elif 'vShieldedSpend' in tx and ((len(tx['vShieldedSpend']) + len(tx['vShieldedOutput'])) > 0):
                # Transactions that don't involve Sprout and do involve Sapling
                num_with_sapling = num_with_sapling + 1
            else:
                # Purely transparent transactions
                num_transparent = num_transparent + 1

        num_jsdesc = sum([tx['num_jsdesc'] for tx in txs])
        num_shielding = len([tx for tx in txs if len(tx['sprout_shielding']) > 0])
        num_unshielding = len([tx for tx in txs if len(tx['sprout_unshielding']) > 0])
        num_less_private_shielding = len([tx for tx in txs if len(tx['sprout_shielding']) > 1])
        num_less_private_unshielding = len([tx for tx in txs if len(tx['sprout_unshielding']) > 1])
        num_mixed = len([tx for tx in txs if tx['is_mixed']])
        num_migrating = len([tx for tx in txs if tx['is_migration']])

        sprout_shielding = sum([value for tx in txs for value in tx['sprout_shielding']])
        sprout_unshielding = sum([value for tx in txs for value in tx['sprout_unshielding']])
        sapling_shielding = sum([tx['sapling_shielding'] for tx in txs])
        sapling_unshielding = sum([tx['sapling_unshielding'] for tx in txs])

        writer.writerow([
            data['height'],
            num_transparent,
            num_with_sapling,
            num_sprout,
            num_jsdesc,
            num_shielding,
            num_unshielding,
            num_less_private_shielding,
            num_less_private_unshielding,
            num_mixed,
            num_migrating,
            sprout_shielding,
            sapling_shielding,
            sprout_unshielding,
            sapling_unshielding,
        ])
        if data['height'] <= cur_height:
            pbar.update(data['height'])
        cur_block_hash = data.get('nextblockhash', None)
```

**Comment by str4d** [comment]
Updated shielding and unshielding values showing both Sprout and Sapling:

![tx-values-0-811000-1000](https://user-images.githubusercontent.com/4993799/80425284-79545d00-8937-11ea-8462-a7ea46795bf7.png)

![tx-values-600000-811000-1000](https://user-images.githubusercontent.com/4993799/80425302-7fe2d480-8937-11ea-9ebe-20c7a9eaa84d.png)

![tx-values-720000-811000-500](https://user-images.githubusercontent.com/4993799/80425350-925d0e00-8937-11ea-8bdc-e823d036eabb.png)

![tx-values-720000-811000-500-zoomed](https://user-images.githubusercontent.com/4993799/80425314-84a78880-8937-11ea-93d2-f5fedf43a6a7.png)

**Comment by str4d** [comment]
Log-scale graph of tx number splits (for earlier granularity):
![tx-types-720000-811000-500-log](https://user-images.githubusercontent.com/4993799/80426767-7f980880-893a-11ea-9894-394734138bf1.png)

**Comment by str4d** [comment]
First pass at splitting up sprout transaction types:
![tx-sprout-splits-0-811000-1000](https://user-images.githubusercontent.com/4993799/80428069-22ea1d00-893d-11ea-97bb-9ebf20624168.png)

![tx-sprout-splits-600000-811000-1000](https://user-images.githubusercontent.com/4993799/80428093-2ed5df00-893d-11ea-8ae7-e25e3273ebd4.png)

![tx-sprout-splits-720000-811000-500](https://user-images.githubusercontent.com/4993799/80427998-fe8e4080-893c-11ea-8052-6e1e1d0feb04.png)

**Comment by str4d** [comment]
And including fully-shielded transactions:
![tx-sprout-splits-720000-811000-1000](https://user-images.githubusercontent.com/4993799/80428322-b3c0f880-893d-11ea-83cb-687b99b7fd9a.png)

**Comment by nathan-at-least** [comment]
Excellent work! @str4d could you put the data collection and plotting scripts in a repository, so I can play with it directly?

**Comment by str4d** [comment]
These graphs indicate that Sprout is being used to a negligible level internally, and the vast majority of its current usage is consistent with a mining pool still shielding their coinbase via Sprout. We can figure out which mining pool(s) this is by looking at the coinbases being shielded.

**Comment by str4d** [comment]
@nathan-at-least sure, I'll set that up.

**Comment by str4d** [comment]
The code for collecting the data and creating the graphs now lives in https://github.com/zcash-hackworks/zcash-graphs

**Comment by nathan-at-least** [comment]
I'm comfortable enough proceeding with [ZIP 211](https://github.com/zcash/zips/pull/214).

I'd still like to investigate the second-order inputs to separate shielding into "from coinbase" and "other" categories, just to be extra certain. That'll be my fun project this week. ;-)
