### ISSUE TITLE
Backport removal of Coin Age Priority

### ISSUE THREAD

**Issue by therealyingtong** [zcash/zcash#4476]
Support for Coin Age Priority was removed in Bitcoin Core v0.15, which means that miners now select transactions based on miner fee alone. However, the current version of zcashd still supports the selection of transactions by priority before switching to selection by fee.  

We should use this [PR 9602](https://github.com/bitcoin/bitcoin/pull/9602) as a template to backport removal of Coin Age Priority from miner selection strategy.

**Comment by therealyingtong** [comment]
Removing support for Coin Age Priority would close #4438 (failing test for transaction prioritisation).

**Comment by therealyingtong** [comment]
Reference older PR (https://github.com/bitcoin/bitcoin/pull/7062) instead

**Comment by daira** [comment]
Done in #6542.
