### ISSUE TITLE
implement "witness segregation"

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#451]
**Terminology note:** In this ticket and in upstream "witness segregation" has nothing to do with zkSNARK witnesses.

Witness segregation is a refactoring of transactions so that the data-to-be-signed is grouped together, and signatures are separate. As for motivations:
- The implementation of `SIGHASH_ALL` signatures is simpler.
- The runtime performance (or even complexity?) of `SIGHASH_ALL` is improved.
- They may be an important improvement for Lightning-Network-style payment channels: http://lists.linuxfoundation.org/pipermail/lightning-dev/2015-November/000310.html

This would be a notable deviation from upstream, so we need cost/benefit analysis.

**Comment by daira** [comment]
I am strongly in favour of implementing segwit for Zcash 1.0. It's how I think the signing should have been designed in the first place.

**Comment by daira** [comment]
Arrgh, we probably don't have time for this :-(

**Comment by zookozcash** [comment]
Segwit is even more mature now than last time we looked at it, and I think (uncertainly) that adopting segwit and *requiring* it for private-spends would ease/simplify the "how to bind Pours to txns" problem that we're currently struggling with. Also, it would be a big PR/marcom value if we could tell people that Zcash will have both segwit and 2 MB blocks (https://github.com/zcash/zcash/issues/765) at launch.

**Comment by zookozcash** [comment]
We can't quite fit this into the engineering schedule before the Zcash 1.0 genesis block (https://github.com/zcash/zcash/wiki/roadmap), but we'll plan to roll it out ASAP, in tandem with Bitcoin Core's rollout of segwit.

And we'll announce that we're going to do so.

**Comment by WyseNynja** [comment]
https://github.com/bitcoin/bips/blob/master/bip-0134.mediawiki "Flexible Transactions" might also be of interest

**Comment by daira** [comment]
I'm much more skeptical about segwit now than when I wrote the earlier comments. It's incredibly complicated and bundles together a scarily large set of changes. Most of the benefit can be obtained more simply by a hard fork to this approach that we very nearly included in 1.0: https://github.com/zcash/zcash/pull/1421

**Comment by runn1ng** [comment]
Hello.

This is the nearest thread I found about this

I need to now implement parsing both zcash transaction and BTC segwit transaction. And bitcoin signals segwit in transaction serialization by using 0 as a "input count" and 1 as "output count"; because this is impossible in bitcoin, it means it is segwit transaction (and the actual counts follow, and the segwit is appended at the end, etc).

However, 0 inputs is possible in zcash, so there needs to be different logic for zcash and BTC in the parsing.

So, just to be sure, zcash will not support segwit, right? 

And if it will, the serialization will have to be different anyway. :)

**Comment by daira** [comment]
It is undecided which approach Zcash will use to fix transaction malleability. Both segwit and FlexTrans (#2071) are under consideration.

**Comment by runn1ng** [comment]
OK. So just letting you know that if you go segwit route, you will need to change the format :)

**Comment by zookozcash** [comment]
Nathan has told me something like "let's spend our resources improving zaddrs and retiring taddrs, rather than improving taddrs". I agree. So unless we can come up with a user story in which users who use zaddrs are helped by this ticket, let's close it as wontfix.

**Comment by nuttycom** [comment]
This is complete as of the updates to transaction signing made in NU5.
