### ISSUE TITLE
build error on osx

### ISSUE THREAD

**Issue by senchzzZ** [zcash/zcash#4518]
I am follow the user guide to build zcash,but  the command ./zcutil/build.sh encounter an error below:
`ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bench/bench_bitcoin] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
`
Machine specs:
OS X 10.15.4

**Comment by rex4539** [comment]
Duplicate of https://github.com/zcash/zcash/issues/4309

`zcashd` is actually built, besides the error.

**Comment by senchzzZ** [comment]
> Duplicate of #4309
> 
> `zcashd` is actually built, besides the error.

`zcashd` is normal to use,thanks.
