### ISSUE TITLE
ld error in depends build on Ubuntu 14.04.3 LTS, linux 4.1.5-x86_64

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#452]
When running `./zcutil/build.sh` on an `Ubuntu 14.04.3` system, there is a [linking error](https://gist.github.com/amiller/adc829ffa4275686bf15#file-gistfile1-txt-L1461-L1466) ([full log link](https://gist.github.com/amiller/adc829ffa4275686bf15)):

```
/usr/bin/ld: skipping incompatible /home/amiller/installing/zerocashd/depends/x86_64-unknown-linux-gnu/lib/libgmpxx.a when searching for -lgmpxx
/usr/bin/ld: skipping incompatible /home/amiller/installing/zerocashd/depends/x86_64-unknown-linux-gnu/lib/libgmp.a when searching for -lgmp
/usr/bin/ld: skipping incompatible /home/amiller/installing/zerocashd/depends/x86_64-unknown-linux-gnu/lib/libboost_system-mt.a when searching for -lboost_system-mt
/usr/bin/ld: cannot find -lboost_system-mt
/usr/bin/ld: skipping incompatible /home/amiller/installing/zerocashd/depends/x86_64-unknown-linux-gnu/lib/libcrypto.a when searching for -lcrypto
collect2: error: ld returned 1 exit status
```

**Comment by ninmesara** [comment]
I also get the same build error on a 32 bit system. Which info would you like me to post?

**Comment by marsmensch** [comment]
I think this can be safely closed. Did multiple automated compilations of 0.11.2.z5 on Ubuntu today (x64: 14.04.3 & 14.04.4) with the following packages installed:
```
build-essential automake ncurses-dev libcurl4-openssl-dev \
    libssl-dev libgtest-dev make autoconf automake libtool git apt-utils pkg-config \
    libc6-dev libcurl3-dev libudev-dev m4 g++-multilib unzip git python zlib1g-dev \
    wget bsdmainutils
```
The builds ran fine and i had no issues with compilation and/or linking, at least for 0.11.2.z5.

**Comment by daira** [comment]
The set of packages installed above differs from that in the [Public Alpha Guide](https://github.com/zcash/zcash/wiki/Public-Alpha-Guide), so we shouldn't close this until the guide has been updated (or the differences proven to be inconsequential, which I don't think is the case).

**Comment by marsmensch** [comment]
Yes, those are the ones that worked for me in my docker [*] image.

I am going to nail the dependencies a bit more for recent Debian, Ubuntu and CentOS in the next days in a Vagrant setup to make it easier to replicate for everybody. 

https://github.com/marsmensch/docker-zcash/blob/master/Dockerfile

**Comment by daira** [comment]
Thanks, that's very useful.

**Comment by mdr0id** [comment]
Closing due to legacy life-cycle. Please re-open if needed.
