### ISSUE TITLE
Node does not halt when Ctrl-C pressed (for example) during reindexing

### ISSUE THREAD

**Issue by daira** [zcash/zcash#4535]
There are four things that are expected to tell the node to halt:
- pressing Ctrl-C;
- sending SIGINT (e.g. `pkill zcashd`);
- using `zcash-cli stop`;
- when `AbortNode` has been called due to a chain inconsistency.

None of these appear to work during a reindex.

Note that they all use the same mechanism: setting `fRequestShutdown`.
https://github.com/zcash/zcash/blob/4fad49d80276280ce0df2bfa424074f55937c423/src/init.cpp#L141

**Comment by nektro** [comment]
Any progress on this?

**Comment by nuttycom** [comment]
Fixed by #6368
