### ISSUE TITLE
Reconsider BLOCK_DOWNLOAD_WINDOW

### ISSUE THREAD

**Issue by daira** [zcash/zcash#4565]
In `main.h`:
```
/** Size of the "block download window": how far ahead of our current height do we fetch?
 *  Larger windows tolerate larger download speed differences between peer, but increase the potential
 *  degree of disordering of blocks on disk (which make reindexing and in the future perhaps pruning
 *  harder). We'll probably want to make this a per-peer adaptive value at some point. */
static const unsigned int BLOCK_DOWNLOAD_WINDOW = 1024;
```

Is this constant still right for Zcash given that we have a much smaller block time?

**Comment by daira** [comment]
I don't think we've ever seen evidence of a problem that could be attributed to this constant. Let's close this issue.

**Comment by nuttycom** [comment]
Closed (with @daira and @sellout) as this constant seems fine, and the network has been using it without trouble for years.
