### ISSUE TITLE
control-C during zcashd startup: "Assertion `nThreadsServicingQueue == 0' failed."

### ISSUE THREAD

**Issue by LarryRuane** [zcash/zcash#4568]
I started `zcashd` and during its start-up (after `init message: Loading block index...`, which happens very early), I pressed control-C, and it didn't seem to have any effect. I've seen this before, I believe it wants to get past the startup before responding to the control-C by shutting down cleanly. Sometime shortly after printing `Init message: Rewinding blocks if needed...`, the following occurred:

`zcashd: scheduler.cpp:19: CScheduler::~CScheduler(): Assertion `nThreadsServicingQueue == 0' failed.`

This is using May 26 master branch, commit de2e1160db45fe3f6c252b699cf56000c9104d76

I tried to reproduce this, but couldn't after 4 or 5 tries.

**Comment by oxarbitrage** [comment]
Duplicated of https://github.com/zcash/zcash/issues/4535 ?

**Comment by LarryRuane** [comment]
I think this can be closed, haven't seen in a long time.
