### ISSUE TITLE
Enable compiler warnings as errors.

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#457]
We disabled "treat warnings as errors" in libzerocash because crypto++ headers generate warnings, breaking the build. Re-enable them after crypto++ is fixed (or patch crypto++ ourselves).

**Comment by daira** [comment]
... or if we remove the dependency on Crypto++.

**Comment by daira** [comment]
Was this already done as a consequence of moving libzerocash into Zcash Core?

**Comment by ebfull** [comment]
I haven't done this yet, hopefully we *can* do this because I know libsnark triggers warnings too.

**Comment by defuse** [comment]
Related: #911

**Comment by daira** [comment]
https://github.com/bitcoin/bitcoin/pull/7165
