### ISSUE TITLE
Make libzerocash utils.cpp more defensive

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#458]
The API libzerocash's utils.cpp provides is very bug-prone. For example, if you don't pre-allocate space for some output parameters, you'll get an empty output. This is especially bad when the output is supposed to be a hash!

Add defensive checks to the utils.cpp functions to make sure the preconditions are satisfied, or just do the allocation inside using std::vector::resize. In some cases we may need to add explicit length parameters.

**Comment by daira** [comment]
I don't think the complaint in the description actually applies to the two remaining functions in https://github.com/zcash/zcash/blob/zc.v0.11.2.latest/src/zerocash/utils/util.cpp . Can we close this? (We still have #960 to move this code into ``src/zcash/`` and rename the namespace.)

**Comment by ebfull** [comment]
Yes! Good catch.
