### ISSUE TITLE
Parameter file download location is changing

### ISSUE THREAD

**Issue by zebambam** [zcash/zcash#4589]
To support our vendors in supplying excellent service to us, we will be changing the download location for parameter files (currently downloaded via fetch-params.sh) to new locations.

The new locations will need to be supported by this repo for at least one complete release before we are able to deny access to the old locations and maintain a good terms relationship with the vendor and thus to our users.

We can comment the new locations on this ticket when they are available.

**Comment by braddmiller** [comment]
@zebambam is this done? We're cleaning up some backlogs.

**Comment by sellout** [comment]
I think #5503 subsumes this.
