### ISSUE TITLE
Compile with clang and C++17 by default

### ISSUE THREAD

**Issue by daira** [zcash/zcash#4607]
This would include dependencies.

## Rationale

clang/LLVM is a better compiler toolchain all-round:

* It supports useful security features (sanitisers and efficient fuzzing) that GCC does not.
* It produces better error messages.
* It keeps up well with C++ standardisation and defect resolutions.
* It has an active development community and is not as hampered by technical debt as GCC.
* clang/LLVM has fewer optimization bugs (no toolchain is perfect, but GCC has had some absolute-WTF bugs).
* Because of that, I would personally trust clang/LLVM at a slightly more aggressive optimization level, that would produce better code. (We currently use `g++ -O1` because GCC isn't trustworthy at higher optimization levels.)

C++17 has some useful features that allow writing clearer code. I particularly like destructuring assignment (`auto [foo, bar] = ...;`) and `std::variant` may also be useful.

Given a desire to move to clang and to C++17, I don't see any reason to do it in two steps. (I checked that the current codebase compiles with `g++ -std=c++17`, so we *could* do so, I suppose.)

**Comment by str4d** [comment]
This would also help Zcash Foundation's current efforts to use `libzcashconsensus` inside `zebra` (in the interim until a pure-Rust script verifier exists), because it would help to eliminate the usage of `boost::variant` in `CTransaction`.

**Comment by str4d** [comment]
My initial stab at the `clang` step (which pins `clang 10.0.0` and currently only works for native Linux compilation) is here: https://github.com/str4d/zcash/tree/claaaaaang
