### ISSUE TITLE
Windows gtests fail due to process-death tests

### ISSUE THREAD

**Issue by daira** [zcash/zcash#4621]
When running `zcash-gtest.exe` built with `HOST=x86_64-w64-mingw32 ./zcutil/build.sh`:

![windows-death-test](https://user-images.githubusercontent.com/643204/87851118-96bd1580-c8ed-11ea-9e07-549b5690ce36.png)

`FoundersRewardTest.General` also failed in the same way. `TimeWarning` passed but only after dismissing several error dialogs. It appears to be a problem with all of the process-death tests; the ones that check for a particular error message fail, but all of them cause error dialogs.

**Comment by daira** [comment]
This appears to be https://github.com/google/googletest/issues/1116, which is supposed to have been fixed in https://github.com/google/googletest/pull/1120. Not sure why it's still happening for me. I'll check the googletest version later.

**Comment by mdr0id** [comment]
@charlieok Do you still have the old branch we did Windows gtest patches on?

**Comment by charlieok** [comment]
I don't think so, sorry to say

**Comment by daira** [comment]
This appears to have been fixed by updating GoogleTest, probably in 78a7230f5073d3fc228f6750d9f8d4b07a2df4a1.
