### ISSUE TITLE
{"result":null,"error":{"code":-26,"message":"16: old-consensus-branch-id (Expected f5b9230b, found 2bb40e60)"},"id":"curltest"}

### ISSUE THREAD

**Issue by JK-1024** [zcash/zcash#4629]
## What were you trying to do
my zcash node version :
```
zcash-cli --conf=/data/blockchain/zec/zcash.conf getinfo
{
  "version": 3000050,
  "protocolversion": 170011,
  "walletversion": 60000,
  "balance": 0.00000000,
  "blocks": 909699,
  "timeoffset": 0,
  "connections": 8,
  "proxy": "",
  "difficulty": 63056570.09206065,
  "testnet": false,
  "keypoololdest": 1576136771,
  "keypoolsize": 101,
  "paytxfee": 0.00000000,
  "relayfee": 0.00000100,
  "errors": ""
}
```

## What happened
when I broadcast rawtx to the node by RPC, get the error:

```
{"result":null,"error":{"code":-26,"message":"16: old-consensus-branch-id (Expected f5b9230b, found 2bb40e60)"},"id":"curltest"}
```

What can I broadcast rawtx successful ? 
expecting a reply，thanks.

**Comment by str4d** [comment]
As the error message says, you're creating the transaction using an old consensus branch ID. The Heartwood network upgrade activated last week, so you need to use its consensus branch ID, instead of the Blossom one.

It would be nice to make these errors more usable, though we are somewhat restricted by upstream Bitcoin Core's usage of JSON-RPC 1.0 + custom error extensions.

**Comment by JK-1024** [comment]
> As the error message says, you're creating the transaction using an old consensus branch ID. The Heartwood network upgrade activated last week, so you need to use its consensus branch ID, instead of the Blossom one.
> 
> It would be nice to make these errors more usable, though we are somewhat restricted by upstream Bitcoin Core's usage of JSON-RPC 1.0 + custom error extensions.

It means that the 'consensus branch ID' is one of the parameters for createing a transaction? 
So I need to modify the 'consensus branch ID' = 'f5b9230b' to my code for create transaction?

**Comment by str4d** [comment]
Yes. I don't know how you were creating your transaction, but if it wasn't using `zcashd` then there should be some way to set the consensus branch ID. On a fully-synced node, `zcash-cli getblockchaininfo` will show the consensus branch ID that you should be using at any given height (in `"consensus": { "nextblock": CONSENSUS_BRANCH_ID }`).
