### ISSUE TITLE
zcashd doesn't compile with --disable-mining

### ISSUE THREAD

**Issue by adityapk00** [zcash/zcash#4634]
### Describe the issue
` CONFIGURE_FLAGS="--disable-tests --disable-mining --disable-bench" ./zcutil/build.sh` fails with 
```
main.h:118:35: error: ‘equihash_solution_size’ was not declared in this scope
  118 |     ((CBlockHeader::HEADER_SIZE + equihash_solution_size(N, K))*MAX_HEADERS_RESULTS < \
      |                                   ^~~~~~~~~~~~~~~~~~~~~~
/home/adityapk/github/zcash/depends/x86_64-unknown-linux-gnu/share/../include/boost/static_assert.hpp:70:55: note: in definition of macro ‘BOOST_STATIC_ASSERT’
   70 | #     define BOOST_STATIC_ASSERT( ... ) static_assert(__VA_ARGS__, #__VA_ARGS__)
      |                                                       ^~~~~~~~~~~
chainparams.cpp:509:29: note: in expansion of macro ‘equihash_parameters_acceptable’
  509 |         BOOST_STATIC_ASSERT(equihash_parameters_acceptable(N, K));
```

### Can you reliably reproduce the issue?
Yes

### Expected behaviour
Compile succeeds with disabled mining

### The version of Zcash you were using:
master branch

### Any extra information that might be useful in the debugging process.
The problem is the method `equihash_solution_size` here (https://github.com/zcash/zcash/blob/b4ec903ac4e27943b667291c34271b2275653bb1/src/crypto/equihash.h#L160) is behind a `#ifdef ENABLE_MINING`, but is being used in a `static_assert` here (https://github.com/zcash/zcash/blob/959f5b09d0b5110499ce6a9675f0d3ea55792185/src/chainparams.cpp#L96) that is outside a `#ifdef ENABLE_MINING`

**Comment by daira** [comment]
@adityapk00 can you check the linked PR, please?
