### ISSUE TITLE
Input total and output total is not equal in many blocks of Zcash.

### ISSUE THREAD

**Issue by schadokar** [zcash/zcash#4647]
I am trying to understand the zcash transaction distribution.  
I am taking blockchain reference as a explorer.  

In block [916066](https://blockchair.com/zcash/block/916066)  
Input total is 38.37798567 ZEC while output total is only 8.00857469 ZEC.  

Why such a huge difference? I suppose it is because of shielded transactions but how to calculate the correct input and output total?

Usually, the input transactions value in the block + block reward == the output transaction value
For example: [Block 915405](https://blockchair.com/zcash/block/915405)
Input Total = 1.47491379 ZEC
Output total = 7.72491379 ZEC
Generation = 6.25000000 ZEC
Input Total + Generation = Output Total

**Comment by daira** [comment]
In each transaction,
* treat transparent inputs as positive
* treat transparent outputs as negative
* treat v<sub>pub</sub><sup>new</sup> values as positive
* treat v<sub>pub</sub><sup>old</sup> values as negative
* do not change the sign of valueBalance values.

Add all of these up in a block, and the result will be the total transaction fees going to the miner.

**Comment by nuttycom** [comment]
The outputs you see include the block reward from the coinbase transaction; there are those few small transparent outputs, then ~36 zec transferred to the shielded pool by:  https://blockchair.com/zcash/transaction/142ae6e4108ae04167209959feb28b237ea9986a72002ee0f46b22d1592bf445

**Comment by str4d** [comment]
The bug here is in Blockchair: their "Input total" and "Output total" are _transparent input_ and _transparent output_ totals, but that is not made clear in the UX.
