### ISSUE TITLE
Make librustzcash Wasm-compilable

### ISSUE THREAD

**Issue by jsamol** [zcash/zcash#4655]
Hey, my team and I would like to use `librustzcash` in our JS-based library, but it seems like it can't be compiled to Wasm at the moment:

```
$ wasm-pack build
> error[E0433]: failed to resolve: could not find `unix` in `os`
  --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/directories-1.0.2/src/lin.rs:99:18
   |
99 |     use std::os::unix::ffi::OsStringExt;
   |                  ^^^^ could not find `unix` in `os`

error[E0432]: unresolved import `unix`
  --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/directories-1.0.2/src/lin.rs:10:5
   |
10 | use unix;
   |     ^^^^ no `unix` in the root

   Compiling num-integer v0.1.43
   Compiling num-bigint v0.2.6
error[E0599]: no function or associated item named `from_vec` found for struct `std::ffi::OsString` in the current scope
   --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/directories-1.0.2/src/lin.rs:106:34
    |
106 |     Some(PathBuf::from(OsString::from_vec(out)))
    |                                  ^^^^^^^^ function or associated item not found in `std::ffi::OsString`
    |
    = help: items from traits can only be used if the trait is in scope
    = note: the following trait is implemented but not in scope; perhaps add a `use` for it:
            `use std::sys_common::os_str_bytes::OsStringExt;`\

> error: could not compile `directories`.
```
I'm not a Rust programmer, but as far as I can see `directories` (which is a dependency of `zcash_proofs`) just doesn't support Wasm ([wasm-pack compiler error - unix module not found](https://github.com/rustwasm/wasm-pack/issues/559)).

Would it be possible to adjust and prepare `librustzcash` so it can be compiled to Wasm?

**Comment by str4d** [comment]
The `directories` crate is only a dependency when the `local-prover` feature is enabled, which it is by default. If you set `default-features = false` in your `zcash_proofs` dependency, it will disable both that, and the `multicore` feature which similarly is not WASM-compatible.

I would not recommend depending directly on the `librustzcash` crate in this repository; it is only an `FFI` wrapper around the `zcash_*` Rust crates in https://github.com/zcash/librustzcash.

**Comment by jsamol** [comment]
Great, that seems to do the trick!

> I would not recommend depending directly on the librustzcash crate in this repository; it is only an FFI wrapper around the zcash_* Rust crates in https://github.com/zcash/librustzcash.

Yeah, just noticed. Apparently the `directories` crate isn't the only thing that keeps it from compiling to Wasm. At least we know how to compile the actual crates now, thanks for the help! 😄

**Comment by str4d** [comment]
I've added some WASM build targets to the Rust crate CI, to ensure we don't regress on support: https://github.com/zcash/librustzcash/pull/265
