### ISSUE TITLE
Remove redundant consensus rule check.

### ISSUE THREAD

**Issue by nuttycom** [zcash/zcash#4683]
I inadvertently forgot to remove this redundant consensus rule before r+'ing the associated PR.

https://github.com/zcash/zcash/pull/4542/files#diff-7ec3c68a81efff79b6ca22ac1f1eabbaR823

**Comment by daira** [comment]
I don't understand which rule this is referring to. Do you mean the rule that was here? https://github.com/zcash/zcash/blob/b94197436319eb4d621e2747109b8976489fe110/src/main.cpp#L824-L826
Or the one after it (which seems not redundant)?
