### ISSUE TITLE
 warning: '/*' within block comment [-Wcomment]

### ISSUE THREAD

**Issue by rex4539** [zcash/zcash#4698]
### Describe the issue
Clang warning: '/*' within block comment [-Wcomment]

#### If so, please list the steps to reproduce below:
1. Compile `zcashd` with `clang`.

### Expected behaviour
No warnings.

### Actual behaviour + errors
```
wallet/gtest/test_wallet_zkeys.cpp:413:1: warning: '/*' within block comment [-Wcomment]
/**
^
1 warning generated.
```

### The version of Zcash you were using:
Latest master.

### Machine specs:
- OS name + version: `macOS 10.15.6 (19G2021)`
- CPU: `6-Core Intel Core i7 2,6 GHz`
- RAM: `16 GB`
- Disk size: `498,89 GB`
- Disk Type (HD/SDD): `SSD`
- Linux kernel version (uname -a): `Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64`
- Compiler version (gcc --version): `Apple clang version 12.0.0 (clang-1200.0.31.1)`
- Linker version (ld -v): `@(#)PROGRAM:ld  PROJECT:ld64-609
BUILD 04:42:03 Aug 10 2020`
- Assembler version (as --version): `clang version 9.0.1 `

**Comment by oxarbitrage** [comment]
Similar to https://github.com/zcash/zcash/issues/4699 this seems it will be fixed by https://github.com/zcash/zcash/pull/4613 in commit https://github.com/zcash/zcash/pull/4613/commits/5b74c9bdb48a5c52739c6c816f769e489fb0ca2e
