### ISSUE TITLE
Zcash testnet faucet returns error

### ISSUE THREAD

**Issue by zhangwu416** [zcash/zcash#4703]
Hey all,

I have been trying to get some testnet Zcash from [https://faucet.testnet.z.cash/](https://faucet.testnet.z.cash/) but the faucet errors with the following message: “Issue sending transaction. Is your address correct?”. Could anyone send me some? thank you.

My address is tmNqvVQQNmvcKzDFRjDF6PDLAXmcb4HQ9Xp.

**Comment by therealyingtong** [comment]
i've successfully sent your address 1 testnet ZEC: https://explorer.testnet.z.cash/tx/f64bbdfb9717ce6479f3ef1c7c96fd8c0e9053c44d574c451d4417624332db20

**Comment by MohseniBigBoy** [comment]
please send me too.
Thaks.
tmKD4JSCVD6s5BrY2ZFDfoD7TVncF8FBxMt
