### ISSUE TITLE
Specify Poseidon instantiation

### ISSUE THREAD

**Issue by daira** [zcash/zcash#4708]
We need a precise specification of the following for ~~Rescue~~ Poseidon:
* [x] Field
* [x] Round constants
* [x] MDS matrix
* [x] Use of duplex sponge
* [x] Number of rounds

**Comment by daira** [comment]
Assuming that we're defining the proofs over Tweedledum, we will need Rescue in the scalar field of Tweedledum (F<sub>q</sub> in the Halo paper).

**Comment by daira** [comment]
A generator for the round constants and MDS matrix is [here](https://github.com/KULeuven-COSIC/Marvellous/blob/master/instance_generator.sage). The choice of round constants does affect security; see https://eprint.iacr.org/2020/820.pdf , in particular:
> We show that it is in principle possible to maliciously choose round constants that would lead to a significant non-random behaviour for any key even using the heavy key-scheduling of Rescue.

Appendix A of that paper includes code to check round constants.

**Comment by daira** [comment]
See also #4717 (Find optimized addition chains for the x^{1/5} map used in Rescue for the Tweedle fields).

**Comment by daira** [comment]
Note that we haven't ruled out switching to Poseidon. Nevertheless, Rescue is the current frontrunner and we need to implement and benchmark it.

**Comment by daira** [comment]
We decided on Poseidon (quite a while ago, but only the title of this ticket got updated).

**Comment by defuse** [comment]
The [code to generate the MDS matrix linked to in the Poseidon paper] warrants being reviewed a bit prior to generating the matrix.

`algorithm_1` in the code looks similar to Algorithm 1 in [GRS2020](https://eprint.iacr.org/2020/500.pdf) but possibly with some differences. The code allows A_1, ... A_n to span the whole space V but the paper doesn't, and the thing it's doing with the matrix's eigenspaces isn't obviously (at least to me) the same as the paper's while loop. [This other code from a footnote in the Poseidon paper](https://extgit.iaik.tugraz.at/krypto/linear-layer-tool/-/blob/master/code/algorithms_gf2n.sage#L132-161) looks like a more direct match. Also, some of Algorithm 3 is commented out.
