### ISSUE TITLE
PourTransactions with invalid proofs can trigger assertions

### ISSUE THREAD

**Issue by ebfull** [zcash/zcash#471]
I tried setting zkSnark in PourTransaction to "fail" and it triggered libsnark assertions. We should probably audit verification to ensure third parties cannot cause libsnark assertions. On that note, there are a lot of assertions throughout libzerocash, some of which should become exceptions or something.

**Comment by nathan-at-least** [comment]
This will no longer be relevant / valid when #1262 merges.
