### ISSUE TITLE
[Orchard] Commitment Merkle tree design

### ISSUE THREAD

**Issue by daira** [zcash/zcash#4713]
This looks straightforward. Domain separation for the tree layers needs to be specified.

**Comment by therealyingtong** [comment]
(draft)

Define the constants:
- (`int`) `l_MerkleCoppice` = 254 (Tweedledee is E<sub>p</sub>/F<sub>p</sub> where `p` is a 255-bit prime),
- (`int`) `MerkleDepth^Coppice`: depth of Coppice commitment Merkle tree,
- (`int`) `layerPrefixLength` = `ceil(log_2(MerkleDepth^Coppice))` + 1, and
- (`string`) `personal`: personalisation input string used in the `Hash()` function.

Define the Merkle hash function `MerkleCRH^Coppice` as:
```
MerkleCRH^Coppice(layer, left, right) := Hash(personal, l || left || right)
```
where:
- `layer` is an integer in the range `[0 .. MerkleDepth^Coppice]`;
- `left` and `right` are bitstrings of length `l_MerkleCoppice`; and
- the prefix `l` is a bitstring of length `layerPrefixLength`, calculated as `l  = I2LEBSP_{ layerPrefixLength}(MerkleDepth^Coppice - 1 - layer)`.

`Hash()` is a hash function that is collision-resistant between inputs of fixed length. It is defined as:

```
Hash(D, M) := output
```
where: 
- `D` (personalisation input) is a byte array of length 8;
- `M` (message) is an arbitrary-length bitstring; and
- `output` is a bitstring of length `l_MerkleCoppice`.

Leaf nodes and internal nodes are bitstrings of length `l_MerkleCoppice`.

**Comment by steven-ecc** [comment]
Closing this issue. Documented in the protocol spec [here](https://zips.z.cash/protocol/nu5.pdf#orchardmerklecrh).
