### ISSUE TITLE
Halving block height question

### ISSUE THREAD

**Issue by SpicaLab** [zcash/zcash#4719]
### Describe the issue

I saw that joshs(Electric Coin Company Team Member) said that ZEC will halve the reward at 1046400 block height, but I saw the code and ZIP 208 are not at 1046400 height.
https://forum.zcashcommunity.com/t/hello-blossom/35602/3

Of course, many websites have created a halving countdown page based on this height

- https://zcashblockhalf.com/
- https://www.f2pool.com/halving
- https://btc.com/stats/halving

#### If so, please list the steps to reproduce below:

The current block reward is 6.25 ZEC
When the block height is 1046400:

https://zips.z.cash/zip-0208
```
Halving(height) :=
floor((height - SlowStartShift) / PreBlossomHalvingInterval), if not IsBlossomActivated(height)
floor((BlossomActivationHeight - SlowStartShift) / PreBlossomHalvingInterval + (height - BlossomActivationHeight) / PostBlossomHalvingInterval), otherwise
```

BlossomActivationHeight = 653600
SlowStartShift = 20000
PreBlossomHalvingInterval = 840000
PostBlossomHalvingInterval = PreBlossomHalvingInterval * 2
Halving(1046400) = floor((653600 - 20000) / 840000 + (1046400 - 653600) / 1680000)
Halving(1046400) = 0

```
BlockSubsidy(height) :=
SlowStartRate · height, if height < SlowStartInterval / 2
SlowStartRate · (height + 1), if SlowStartInterval / 2 ≤ height and height < SlowStartInterval
floor(MaxBlockSubsidy / 2^Halving(*height*)), if SlowStartInterval ≤ height and not IsBlossomActivated(height)
floor(MaxBlockSubsidy / (BlossomPoWTargetSpacingRatio · 2^Halving(*height*))), otherwise
```
MaxBlockSubsidy = 12.5 * 10000000000
BlossomPoWTargetSpacingRatio = 2
BlockSubsidy(1046400) = floor(12.5 * 10000000000 / (2 · 2^0))
BlockSubsidy(1046400) = 62500000000 = 6.25 ZEC

I see the actual result of the code is like this also
https://github.com/zcash/zcash/blob/master/src/main.cpp#L1866-L1903

**Comment by therealyingtong** [comment]
`SlowStartShift` should be 10000 in your calculations instead of 20000.

To see this:
- `SubsidySlowStartShift()` returns `nSubsidySlowStartInterval / 2` (https://github.com/zcash/zcash/blob/master/src/consensus/params.h#L186)
- `nSubsidySlowStartInterval = 20000` (https://github.com/zcash/zcash/blob/master/src/chainparams.cpp#L89)
