### ISSUE TITLE
testnet faucet can't send to t-addr

### ISSUE THREAD

**Issue by zhujinghe** [zcash/zcash#4722]
i want to get some coins whit t-addr,but https://faucet.testnet.z.cash/ show (Issue sending transaction. Is your address correct?)

my t-addr is tmRrs9tWHp13YybX9uXZgTiFYC9qsT8tP9r

@benzcash

**Comment by benzcash** [comment]
Faucet has been topped off, I tested using your address an tx 9cdacc3fa0c61507d82b734c386fa9df24cdc097537d58c33c397e79230fd011

https://explorer.testnet.z.cash/tx/9cdacc3fa0c61507d82b734c386fa9df24cdc097537d58c33c397e79230fd011

Let me know if you have further issues.

**Comment by zhujinghe** [comment]
@benzcash thank you ，I have received

**Comment by MohseniBigBoy** [comment]
Please send me some, too.
Thank U.
tmKD4JSCVD6s5BrY2ZFDfoD7TVncF8FBxMt
