### ISSUE TITLE
Rewrite libzerocash's IncrementalMerkleTree

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#473]
Zooko is unsatisfied with the implementation because of lack of domain separation and all of the bugs we're finding. Re-write it in a way that has domain separation and is heavily unit tested.

We may also want to re-write other parts of libzerocash.

**Comment by daira** [comment]
@ebfull How does the new implementation address domain separation?

**Comment by ebfull** [comment]
@daira It doesn't. It's meant to be entirely compatible with the old tree's behavior, since modifying the circuit safely in time for 1.0 seems prohibitive. As such, this ticket isn't really closed by my pull request.

**Comment by nathan-at-least** [comment]
Would closing this ticket address #20?  If so, let's close #20 as duplicate/superceded.

**Comment by ebfull** [comment]
I think we could probably close #20, but *this* ticket should not be predicated on the rewrite adding domain separation.

**Comment by ebfull** [comment]
No, let's not close #20 until incremental deltas are implemented. This isn't strictly necessary for anything though.
