### ISSUE TITLE
An error occured: 16: mandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element). Code:-26

### ISSUE THREAD

**Issue by zhujinghe** [zcash/zcash#4731]
I don't know why I reported this error, can anyone help me

from:"tmW2DD3VxyoMmSDSP2ibXUHjvkh7i9sZp4c"
to:"tmGTWP8dqqPbAeqax2nwpBDMc7P4aUTRmcE"

sign:
       0400008085202f8902362c25c69f1091f05a3a863d87e10c6662350e747abf4ae5bcab14f08f6e7927010000006b483045022100db747a71f07206a947424a449805c337b55322eb9db62e6327137255beaf1adc0220734720a60381113e061fb92d26d46df9c866b76911cc31c04e8232429ac1f611032102ec6966f4698b5ef3266bfe3778c4a16415095221a447e507596218927d02fc6effffffff5120efb85b057bfac93d634098de23d5b464db40fc34b47fae8194ff5c5aed59010000006a473044022054b6c159a7d7ea7cd6a888466dec702a1622941481e5eaaca5ade7a61320efb102207fac51843af34ad2a1dca407975ac106f568bf8f9ef33102b5b24306bb51a1dc032102ec6966f4698b5ef3266bfe3778c4a16415095221a447e507596218927d02fc6effffffff02a0860100000000001976a91449fa324d7e1c2393fd59698fe2530606f7aa61ba88acd02fa000000000001976a914dec338eb3e7372a277a6ee388751f583bbd858a688ac00000000000000000000000000000000000000

code:
`
   
    // Required Zcash parameters
    const builder = new bitgoUTXOLib.TransactionBuilder(ZecTestNetwork)
    builder.setVersion(bitgoUTXOLib.Transaction.ZCASH_SAPLING_VERSION) // 4
    builder.setVersionGroupId(parseInt('0x892F2085', 16))

    // Optional parameters
    builder.setLockTime(0)
    builder.setExpiryHeight(0)

    let total = 0
    // Build inputs
    for(let key in utxo){
      total += parseInt(utxo[key].amount * 1e8)
      builder.addInput(utxo[key].txid, utxo[key].vout)
    }

    // Build outputs
    builder.addOutput(to, value)

    var change = parseInt(total - value - feeValue)
    // Build outputs
    builder.addOutput(from, change)

    const hashType = bitgoUTXOLib.Transaction.SIGHASH_ALL
    const keyPair = bitgoUTXOLib.ECPair.fromWIF(privateKey, ZecTestNetwork)

    for(let key in utxo){
      builder.sign(parseInt(key), keyPair, "", hashType, utxo[key].amount * 1e8)
    }

    return builder.build().toHex()`

**Comment by rex4539** [comment]
Looks like you are using an updated branch ID, eg. you need to update `zcashd` as the version you are using has been deprecated.

**Comment by zhujinghe** [comment]
Can you tell me what the current ID should be @rex4539

**Comment by rex4539** [comment]
I'm not very familiar with this. But this kind of error message usually pops up when an outdated branch ID is used.

It may or may not be related to your scenario. I'll let someone of knowledge give a proper answer :)

**Comment by zhujinghe** [comment]
thank you @rex4539

**Comment by daira** [comment]
The current consensus branch ID on mainnet is 0xF5B9230B (Heartwood, specified in [ZIP 250](https://zips.z.cash/zip-0250)).

The current consensus branch ID on testnet is 0xE9FF75A6 (Canopy, specified in [ZIP 251](https://zips.z.cash/zip-0251)). This will activate on mainnet at block 1046400.

**Comment by zhujinghe** [comment]
@daira   
It is An error occured:TX decode failed. Code:-22

my zcashd is 3.1.0 

tx.setLockTime(0)
tx.setExpiryHeight(0)
Do these two parameters need to be set?

**Comment by daira** [comment]
The issue is probably that `bitgoUTXOLib` is outdated.

**Comment by zhujinghe** [comment]
my bitgoUTXOLib is 1.9.0

**Comment by daira** [comment]
bitgoUTXOLib 1.9.1 [updates to the Heartwood consensus branch ID](https://github.com/BitGo/bitgo-utxo-lib/pull/78).

**Comment by zhujinghe** [comment]
now, my bitgoUTXOLib is 1.9.1 
but error:
An error occured:TX decode failed. Code:-22

**Comment by daira** [comment]
@zhujinghe filed this as https://github.com/BitGo/bitgo-utxo-lib/issues/88 .

**Comment by zhujinghe** [comment]
@daira @str4d  How can I solve this problem?

**Comment by daira** [comment]
It appears from https://github.com/BitGo/bitgo-utxo-lib/pull/89 as though the bitgo library doesn't set the consensus branch ID on the Transaction object by default (the previous PR https://github.com/BitGo/bitgo-utxo-lib/pull/78 added the ID to the source code but didn't set it, instead leaving that to the code that is using the transaction builder). So you would need to manually set the `consensusBranchId` property of the `Transaction` object just after creating it, using the correct ID for the block height (as defined in ZIPs 250 and 251).

**Comment by zhujinghe** [comment]
Can you give me a code example, I have tried many methods and it doesn't work. Or is there any other third-party library that can create transactions? @daira

**Comment by zhujinghe** [comment]
![image](https://user-images.githubusercontent.com/38774462/96246369-1d5fbc80-0fdb-11eb-9ea7-632fa45bb4fa.png)

I found a transaction in a block on the testnet. The VersionGroupId seems to be different from the new ID. Does this have any effect?

**Comment by daira** [comment]
The Canopy upgrade has already activated on testnet. This upgrade will activate on mainnet at block height 1046400, on [roughly November 18th](https://z.cash/upgrade/canopy/).

You must use the correct consensus branch ID for the current upgrade: 0xF5B9230B before Canopy, or 0xE9FF75A6 after Canopy. It would be preferable to make this configurable since it will change again at each subsequent upgrade (the next is in mid-2021).

To set the consensus branch ID, add something like this *after* the call to `builder.setVersion`:
```
if (height < 1046400) { // for mainnet
    builder.setConsensusBranchId(parseInt('0xF5B9230B', 16))
} else {
    builder.setConsensusBranchId(parseInt('0xE9FF75A6', 16))
}
```
However, this will only work on the branch created by https://github.com/BitGo/bitgo-utxo-lib/pull/89 . If you want to make it work before then, you can probably use:
```
if (height < 1046400) { // for mainnet
    builder.tx.consensusBranchId = parseInt('0xF5B9230B', 16)
} else {
    builder.tx.consensusBranchId = parseInt('0xE9FF75A6', 16)
}
```
(but this code depends on an implementation detail of `TransactionBuilder` rather than a supported API, and so it could break in future).

There is also [a change to the format of Sapling note encryption](https://zips.z.cash/zip-0212) for the Canopy upgrade. It doesn't appear as that bitgoUTXOLib supports shielded outputs so this probably doesn't affect you.

**Comment by zhujinghe** [comment]
The first way of writing：
`tx.setVersion(4)
tx.setConsensusBranchId(parseInt('0xE9FF75A6', 16))
tx.setVersionGroupId(parseInt('0x892f2085', 16))`

error code: -26
error message:
16: tx-overwinter-not-active

The second way of writing：
`tx.setVersion(4)
tx.setConsensusBranchId(parseInt('0xE9FF75A6', 16))
tx.setVersionGroupId(parseInt('0xE9FF75A6', 16))`

error code: -22
error message:
TX decode failed

In addition, I am currently testing on my own private chain, zcashd version is 4.0, are the above two writing methods correct?

@daira

**Comment by daira** [comment]
It seems as though your private chain has not activated the Overwinter upgrade. This is likely to cause difficulties, and potentially serious security problems, because current zcashd does not verify proofs prior to Sapling activation. Is your private chain a testnet, or a fork of Zcash mainnet, or a code fork from the genesis block?

**Comment by zhujinghe** [comment]
My private chain is a local zcash4.0 test network built by myself. After the subsequent test is successful, it will be transplanted to a node under the main network for use. How to activate the Overwinter upgrade, zcash4.0 does not include the Overwinter upgrade?
@daira

**Comment by zhujinghe** [comment]
![image](https://user-images.githubusercontent.com/38774462/96407516-21c2ea00-1214-11eb-8850-9a219916fe4c.png)
I can already broadcast to testnet, thank you very much @daira
