### ISSUE TITLE
Add option to complain loudly if a v1 note plaintext is received after Canopy activation

### ISSUE THREAD

**Issue by daira** [zcash/zcash#4735]
The current behaviour (as of 4.0.0) is to treat received v1 note plaintexts normally during the ZIP 212 grace period. That's not convenient for testing that v2 note plaintexts are being sent correctly. We should have an option that complains loudly if a v1 note plaintext is received.

**Comment by str4d** [comment]
The simplest way to implement this would be to add a debug log message for this case, and then document the `setlogfilter` command to enable it.
