### ISSUE TITLE
Make -reindex a superset of -rescan

### ISSUE THREAD

**Issue by daira** [zcash/zcash#4768]
Currently you might need both to fix some problems with witness caches.

**Comment by str4d** [comment]
`-reindex` is already a superset of `-rescan`:
  - `-rescan` starts from a given height (which may be genesis) and scans the existing chain for missed transactions (perhaps from a newly-imported key).
  - `reindex` rebuilds the chain using `ProcessNewBlock`, which will result in the regular process of the wallet being notified of every transaction in the chain and trial-decrypting etc.

What `-reindex` (and `-rescan`) don't do is delete existing transactions / witnesses and redetect them from scratch. This is what `-zapwallettxes` does, and it is potentially destructive (e.g. it can result in complete loss of transactions that were created and stored in the wallet but were never mined), so it should not happen as part of `-reindex`.

**Comment by LarryRuane** [comment]
Just for completeness, I'll mention that there's also a boolean option called `-reindex-chainstate` but it seems to have an identical effect as `-reindex`, despite the differing help text (it appears `reindex-chainstate` should be a subset of `reindex`):
```
  -reindex-chainstate
       Rebuild chain state from the currently indexed blocks

  -reindex
       Rebuild chain state and block index from the blk*.dat files on disk
```
It exists upstream as well and does seem to have a different effect than `-reindex` (probably what the help text says).
