### ISSUE TITLE
[Orchard] Document Sinsemilla hash function and commitment scheme

### ISSUE THREAD

**Issue by daira** [zcash/zcash#4786]
A simplified version of Sinsemilla is described at https://www.youtube.com/watch?v=YlTt12s7vGE&feature=youtu.be&t=4746

(Where I say "7 bases" in the example, I mean 8.)

**Comment by defuse** [comment]
Cool! I think where the slide says P[0 .. n - 1] it should actually say P[0 .. 2^k - 1].

**Comment by daira** [comment]
Yes that's correct, thanks.

**Comment by daira** [comment]
TODO(@daira): check whether the security argument can be extended to variable-length inputs.

**Comment by daira** [comment]
This is done in spec version 2021.1.17.
