### ISSUE TITLE
Define a "result" type for use in C++ error handling

### ISSUE THREAD

**Issue by daira** [zcash/zcash#4816]
## Is your feature request related to a problem? Please describe.
Sometimes we want to return either a success result or error information from a C++ function. Existing ways to do this are inconvenient and error-prone: https://github.com/zcash/zcash/pull/4812#discussion_r511624475

## Describe the solution you'd like
Define a result type similar to Haskell's [Data.Either](https://hackage.haskell.org/package/base-4.14.0.0/docs/Data-Either.html), Rust's [std::result](https://doc.rust-lang.org/std/result/), or Boost's [outcome](https://www.boost.org/doc/libs/1_74_0/libs/outcome/doc/html/tutorial/essential/outcome.html) (although that one seems overcomplicated to me), or use [an implementation of the std::expected proposal](https://github.com/TartanLlama/expected).

## Alternatives you've considered
Well, I did a [whole talk](https://github.com/noether-lang/noether/blob/master/doc/presentations/StrangeLoop2014/handling.pdf) on error handling techniques once, but the recovery block approach I suggested there requires deep language support and isn't suitable for C++. In any case, I think we want consistency between the error handling styles we use in Rust and C++.

**Comment by daira** [comment]
Upstream recently added, in https://github.com/bitcoin/bitcoin/pull/25218, a `BResult<T>` type similar to what this issue asks for. Unfortunately, it fixes the result type to Bitcoin Core's `bilingual_str` (initially added in https://github.com/bitcoin/bitcoin/pull/16362), which is almost certainly not what we want.

Suggestion: pull in https://github.com/bitcoin/bitcoin/pull/16362 (with later updates) and https://github.com/bitcoin/bitcoin/pull/25218, then modify `BResult` to be a more general `Result<T, E>`, and define `BResult` as a C++11 [templated type alias](https://en.cppreference.com/w/cpp/language/type_alias):
```
template<class T> using BResult = Result<T, bilingual_str>;
```
(This slightly funky syntax means that `BResult<T>` will be equivalent to `Result<T, bilingual_str>`.)

@nuttycom opined that we actually only need a type like Haskell's `data Either a b = Left a | Right b`. (For example, this could be `Either<Left, Right>` wrapping `std::variant<Left, Right>`, or just use the latter directly if we decide its API isn't too horrible.)

I would agree, but the thing I wanted to avoid with the above suggestion is having two completely distinct result-like types in Zcash vs ports from Bitcoin Core, rather than the upstream one just being a specialization of the general one.

**Comment by nuttycom** [comment]
I think we want to stick as close to Rust's `Result` here as possible, to ease interop. I wonder... would it maybe be possible to actually use whatever `cxx` uses for `Result` more broadly? That could be useful for interop across the FFI.

**Comment by daira** [comment]
I'm going cold on using `BResult` at all because of this (sample code from their PR):
```
BResult<Obj> doSomething(arg1, arg2, arg3, arg4) {
    // do something...
    if (error) return "something bad happened";

    return goodResult;
}
```
which appears to be guessing whether the result will be success or error depending on whether a value coerces to a `bilingual_str` or not. **Yuck**.

Ergonomics across the cxx FFI boundary are definitely something we should consider as a high priority.

**Comment by daira** [comment]
cxx has a [`Result<T>` type](https://cxx.rs/binding/result.html) but it maps errors to exceptions (always of type [`cxx::Exception`](https://docs.rs/cxx/1.0.72/cxx/struct.Exception.html)), and does not allow specifying the error type, which are both not what we want.

I think we may be forced to define our own type, and/or contribute something to upstream cxx: https://github.com/dtolnay/cxx/issues/16.

**Comment by daira** [comment]
[tl::expected] looks good to me:
* MIT-compatible license (CC0);
* Seems to have good unit tests and portability;
* Implementation of `std::expected` with Rust Result-like extensions (`map`, `map_error`, `and_then`, `or_else`) that do exactly what you'd expect;
* I read the code, and it is not too horribly overcomplicated as far as single-header libraries that implement a C++ standard library proposal go. It's better than Boost outcome in that regard.
