### ISSUE TITLE
QUESTION:  How to generate multi-sig address ?

### ISSUE THREAD

**Issue by minchenzz** [zcash/zcash#4833]
```
{
  "address": "t28DfbUt7SyNXvYNQohvzvhGVXwReAtc9Au",
  "redeemScript": "512103c62099f3d6e10dc66506ce8e38bfd6b0edfaca3a15f580523a4665744ac197c521025f71d0afcdc77de9a595dd7c6546fdbe127588fdb4d1773d89056cde1101ead852ae"
}
```

```
addr script 12515a422fcf69d4a8e914e62123e2a10029eb29
```

I try to use ```hash160(append([0x00, 0x20], sha256(redeemScript)))```, but got a wrong result.

What should I do.

I dont know CPP :(

**Comment by daira** [comment]
As far as I know this isn't different from Bitcoin. Did you use the procedure [here](https://en.bitcoin.it/wiki/Multisignature#Creating_a_Multisignature_Address_with_Bitcoin-Qt) (replacing `bitcoind` with `zcash-cli`) to generate the script?

**Comment by minchenzz** [comment]
resolved
