### ISSUE TITLE
Agree on exception names and namespacing for libzerocash

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#484]
Sometimes libzerocash throws an exception. Sometimes it returns false. Sometimes it `exit(1)`s. I propose we make it use exceptions consistently everywhere. Let's come to a consensus on which exception classes should exist in libzerocash (or at least a naming scheme, since we can't easily anticipate all exception cases without looking through the code).

Once that's done, we can open another ticket to go through libzerocash and change everything to use exceptions (I'm particularly motivated to do this).

**Comment by defuse** [comment]
We have a style guide?

**Comment by defuse** [comment]
I can't find any style guide so I think we should just close this issue. (It's obviated by #881 anyway I think).

**Comment by daira** [comment]
See #512

**Comment by daira** [comment]
I think this is completely covered by #512 and #881.
