### ISSUE TITLE
`read jobs pipe: Resource temporarily unavailable.` when compiling with multiple cores on macOS

### ISSUE THREAD

**Issue by rex4539** [zcash/zcash#4841]
This is an old bug but I forgot to file earlier.

It occurs when compiling on macOS with multiple cores.

```
make[2]: *** read jobs pipe: Resource temporarily unavailable.  Stop.
```

Searching online a bit, this appears to be caused by a macOS limitation regarding available resources with `ulimit`.

Invoking make with multiple cores again, continues the build from where it left off and succeeds.

**Comment by daira** [comment]
Hmm, some quick googling did not turn up anything useful for this error. I'm a little bit skeptical that it is due to `ulimit`.

**Comment by rex4539** [comment]
Surprisingly, this is fixed for me during the last week.

Not sure if it's due to my recent OS update or the latest upstream fixes, but it's not reproducible anymore.
