### ISSUE TITLE
coins disappeared from adresses and wallet

### ISSUE THREAD

**Issue by Aporbel** [zcash/zcash#4845]
last year, I bought some coins(76) for HODL. Now, I sync node and figure out that I don't have my coins on my wallet. I try "zecwallet-fullnode" and zcashd classic on debian, in windows version (zecwallet) I saw the transaction(that i did) but I can'
t choose any addresses, in zcashd and zcash-cli - i try to find some info, but receive the same information, all addresses that were export early, now have 0.00 balance. Money lie down from jun 28, 2019.

If it was scam, maybe attack 51%, I will discredit this cryptocurrency, and advertising my posts on social media about this situation. No one could hack me, cause I use a lot of method of defense.

**Comment by rex4539** [comment]
First of all, make sure you are using the latest version of Zecwallet -> https://github.com/ZcashFoundation/zecwallet/releases/latest

If you are still not seeing the funds, can you check the transactions tab? Do you see an outgoing transaction that proves your funds have been transferred to an unknown address?

If there is no outgoing transaction that proves your funds have been moved, do you have the private key to your address?

As long as you have your private key, you can access your funds in case of emergency.

If so, you can try importing the key in Zecwallet FullNode via File -> Import Private Keys

**Comment by Aporbel** [comment]
> 
> 
> First of all, make sure you are using the latest version of Zecwallet -> https://github.com/ZcashFoundation/zecwallet/releases/latest
> 
> If you are still not seeing the funds, can you check the transactions tab? Do you see an outgoing transaction that proves your funds have been transferred to an unknown address?
> 
> If there is no outgoing transaction that proves your funds have been moved, do you have the private key to your address?
> 
> As long as you have your private key, you can access your funds in case of emergency.
> 
> If so, you can try importing the key in Zecwallet FullNode via File -> Import Private Keys
I see transaction from t to z address that i did, but I check this z-adress and it's show that they don't have any funds there. 
Ofc, I have a private keys for all of this addresses, but after importing it's show 0 balance and no history transactions.

**Comment by rex4539** [comment]
Try a wallet rescan.

Issue `zcashd -rescan` in the command line.

It may take a while, depending on your hardware.

**Comment by Aporbel** [comment]
> 
> 
> Try a wallet rescan.
> 
> Issue `zcashd -rescan` in the command line.
> 
> It may take a while, depending on your hardware.

>>
Try to import z-address and get this error:
```
error code: -32601
error message:
Method not found

```
Do you know something about this error? Address is valid, exported from wallet

**Comment by Aporbel** [comment]
> 
> 
> Try a wallet rescan.
> 
> Issue `zcashd -rescan` in the command line.
> 
> It may take a while, depending on your hardware.

>>
passed, still balance 0.00

**Comment by rex4539** [comment]
Can you double check that the rescan is complete?

Open `debug.log` and check if the rescan is still in process and also see if there are any errors being logged.

Also check what is your `zcashd` version. It is written at the beginning of the log session.

**Comment by Aporbel** [comment]
> 
> 
> Can you double check that the rescan is complete?
> 
> Open `debug.log` and check if the rescan is still in progress and also see if there are any errors being logged.
> 
> Also check what is your `zcashd` version. It is written at the beginning of the log session.

>>
```
Nov 03 11:46:43.024  INFO Init: main: LoadBlockIndexDB: transaction index disabled
Nov 03 11:46:43.024  INFO Init: main: LoadBlockIndexDB: insight explorer disabled
Nov 03 11:46:43.024  INFO Init: main: LoadBlockIndexDB: light wallet daemon disabled

Nov 03 11:48:09.001  INFO Init: main: Still rescanning. At block 103713. Progress=0.027063
Nov 03 11:49:09.014  INFO Init: main: Still rescanning. At block 169557. Progress=0.055581
Nov 03 11:50:09.001  INFO Init: main: Still rescanning. At block 230877. Progress=0.090877
Nov 03 11:51:09.001  INFO Init: main: Still rescanning. At block 280899. Progress=0.136746
Nov 03 11:52:09.006  INFO Init: main: Still rescanning. At block 328912. Progress=0.168560
Nov 03 11:53:09.006  INFO Init: main: Still rescanning. At block 381871. Progress=0.200844
Nov 03 11:54:09.020  INFO Init: main: Still rescanning. At block 471597. Progress=0.230389
Nov 03 11:55:09.007  INFO Init: main: Still rescanning. At block 538684. Progress=0.276738
Nov 03 11:56:09.008  INFO Init: main: Still rescanning. At block 597897. Progress=0.415653
Nov 03 11:57:09.006  INFO Init: main: Still rescanning. At block 660628. Progress=0.538099
Nov 03 11:58:09.005  INFO Init: main: Still rescanning. At block 752407. Progress=0.647305
Nov 03 11:59:09.005  INFO Init: main: Still rescanning. At block 814381. Progress=0.726123
Nov 03 12:00:09.004  INFO Init: main: Still rescanning. At block 870932. Progress=0.800284
Nov 03 12:01:09.006  INFO Init: main: Still rescanning. At block 951329. Progress=0.902958
Nov 03 12:02:09.005  INFO Init: main: Still rescanning. At block 1000890. Progress=0.964786
Nov 03 12:02:39.548  INFO Init: main:  rescan               930173ms

Nov 03 12:02:39.565  INFO Init: main: mapBlockIndex.size() = 1029389
Nov 03 12:02:39.565  INFO Init: main: nBestHeight = 1029388
Nov 03 12:02:39.565  INFO Init: main: setKeyPool.size() = 101
Nov 03 12:02:39.565  INFO Init: main: mapWallet.size() = 0
Nov 03 12:02:39.565  INFO Init: main: mapAddressBook.size() = 5
Nov 03 12:02:39.571  INFO main: torcontrol thread start

INFO main: connect() to [::922:79:f170:b92e]:8233 failed: Network is unreachable (101)
Nov 03 12:02:50.665  INFO main: P2P peers available. Skipped DNS seeding.
Nov 03 12:02:50.665  INFO main: dnsseed thread exit

Nov 03 12:03:06.062  INFO main: connect() to [2603:3023:137:f000::23c2]:8233 failed: Network is unreachable (101)
Nov 03 12:03:06.728  INFO main: ProcessMessages: advertizing address 185.246.208.41:8233
Nov 03 12:03:06.728  INFO main: receive version message: /MagicBean:4.0.0/: version 170013, blocks=1029398, us=185.246.208.41:25548, peer=7
Nov 03 12:03:06.728  INFO main: Added time data, samples 7, offset +0 (+0 minutes)
```

zcashd v4.0.0 node,  walletversion: 60000

**Comment by Aporbel** [comment]
Also, after finished import addresses, I used zcash-cli gedaddressesbyaccount "", and doesnot see any of this z_addresses that were imported.

**Comment by rex4539** [comment]
First of all I would like to note that you are speaking with a community member, not “official staff” and I’m willing to help you get to the bottom of this, so bear with me.

I would propose that we go from the start., step by step.

1. Do you see your t->z transaction on a block explorer when you enter the transaction hash? This is a must. If you don’t see it, then this is the problem. If you do see it, go to step 2.
2. Does your z-address start with zc or zs?
3. Make sure your node is 100% synced.
4. Quit `zcashd` and Zecwallet if they are already running.
5. Move `wallet.dat` to your desktop. Don’t delete it, as you might need it, especially if you have multiple addresses with various private keys.
6. Launch Zecwallet.
7. File -> Import Private Keys -> Enter you z-address private key.
8. Check `debug.log` and make sure the import has finished (it can take from a several minutes to a several hours, depending on how old your transaction is), and that you can see your z-address displayed in Zecwallet. If everything went fine without errors, you should see your funds. If not, check the `debug.log` for errors and post them, then go to step 8.
9. Quit Zecwallet.
10. Open a command line and issue `zcashd -rescan`.
11. Check `debug.log` and make sure the rescan has finished.
12. Launch Zecwallet. Now you should see your funds. If not, there must be some error logged in `debug.log`.

**Comment by Aporbel** [comment]
> 
> 
> First of all I would like to note that you are speaking with a community member, not “official staff” and I’m willing to help you get to the bottom of this, so bear with me.
> 
> I would propose that we go from the start., step by step.
> 
>     1. Do you see your t->z transaction on a block explorer when you enter the transaction hash? This is a must. If you don’t see it, then this is the problem. If you do see it, go to step 2.
> 
>     2. Does your z-address start with zc or zs?
> 
>     3. Make sure your node is 100% synced.
> 
>     4. Quit `zcashd` and Zecwallet if they are already running.
> 
>     5. Move `wallet.dat` to your desktop. Don’t delete it, as you might need it, especially if you have multiple addresses with various private keys.
> 
>     6. Launch Zecwallet.
> 
>     7. File -> Import Private Keys -> Enter you z-address private key.
> 
>     8. Check `debug.log` and make sure the import has finished (it can take from several minutes to several hours, depending on how old your transaction is), and that you can see your z-address displayed in Zecwallet. If everything went fine without errors, you should see your funds. If not, check the `debug.log` for errors and post them, then go to step 8.
> 
>     9. Quit Zecwallet.
> 
>     10. Open a command line and issue `zcashd -rescan`.
> 
>     11. Check `debug.log` and make sure the rescan has finished.
> 
>     12. Launch Zecwallet. Now you should see your funds. If not, there must be some error logged in `debug.log`.

1. Yes, I see a transaction, in explorer is looks like  **Outputs (0 + 🛡️1)** but not appear shield-address.
2. It's not appear in explorer, all my shield-addresses **zs1**
3. Node synced 100%, repeat 3 times, did redownload.
4. Done
5. Done
6. Done
7.Done
8.
```
Nov 04 00:56:03.001  INFO main: Still rescanning. At block 554242. Progress=0.308885
Nov 04 00:56:23.259  INFO main: AddToWallet **hash transaction** 
Nov 04 00:56:23.997  INFO main: AddToWallet **hash transaction** 
Nov 04 00:56:24.010  INFO main: AddToWallet **hash transaction**   
Nov 04 00:56:24.016  INFO main: AddToWallet **hash transaction**   
Nov 04 00:56:24.480  INFO main: AddToWallet **hash transaction**   
Nov 04 00:56:24.481  INFO main: AddToWallet **hash transaction**   
Nov 04 00:56:24.489  INFO main: AddToWallet **hash transaction**   
Nov 04 00:57:03.001  INFO main: Still rescanning. At block 597970. Progress=0.415656

Nov 04 01:03:03.001  INFO main: Still rescanning. At block 884414. Progress=0.817124
Nov 04 01:03:50.039  INFO main: socket sending timeout: 1201s
Nov 04 01:03:51.026  INFO main: socket sending timeout: 1201s
Nov 04 01:03:53.044  INFO main: socket sending timeout: 1201s
Nov 04 01:04:00.012  INFO main: socket sending timeout: 1201s
Nov 04 01:04:01.030  INFO main: socket sending timeout: 1201s
Nov 04 01:04:03.000  INFO main: Still rescanning. At block 940861. Progress=0.889424
Nov 04 01:04:03.000  INFO main: Still rescanning. At block 940861. Progress=0.889424
Nov 04 01:05:03.000  INFO main: Still rescanning. At block 980587. Progress=0.939342
Nov 04 01:06:03.000  INFO main: Still rescanning. At block 1018142. Progress=0.985769
Nov 04 01:06:19.551  INFO main: socket send error An operation was attempted on something that is not a socket.  (10038)
Nov 04 01:06:19.551  INFO main: keypool reserve 4
Nov 04 01:06:19.551  INFO main: keypool return 4
Nov 04 01:06:25.883  INFO main: ProcessMessages: advertizing address **ip:port**
Nov 04 01:06:25.883  INFO main: receive version message: /MagicBean:4.0.0/: version 170013, blocks=1029694, us=185.246.208.41:25476, peer=11

```
9.  Done
10. Done
11.```
 Nov 04 01:32:05.000  INFO Init: main: Still rescanning. At block 490970. Progress=0.236210
Nov 04 01:33:05.001  INFO Init: main: Still rescanning. At block 541880. Progress=0.283543
Nov 04 01:33:39.602  INFO Init: main: AddToWallet  **hash transaction**
Nov 04 01:33:40.268  INFO Init: main: AddToWallet  **hash transaction**
Nov 04 01:33:40.284  INFO Init: main: AddToWallet  **hash transaction**
Nov 04 01:33:40.291  INFO Init: main: AddToWallet  **hash transaction**
Nov 04 01:33:40.742  INFO Init: main: AddToWallet  **hash transaction**
Nov 04 01:33:40.744  INFO Init: main: AddToWallet **hash transaction**
Nov 04 01:33:40.752  INFO Init: main: AddToWallet  **hash transaction** 
Nov 04 01:34:05.000  INFO Init: main: Still rescanning. At block 589628. Progress=0.395651
Nov 04 01:35:05.000  INFO Init: main: Still rescanning. At block 634268. Progress=0.489523
Nov 04 01:36:05.000  INFO Init: main: Still rescanning. At block 699473. Progress=0.583564
Nov 04 01:37:05.001  INFO Init: main: Still rescanning. At block 761374. Progress=0.658141
Nov 04 01:38:05.003  INFO Init: main: Still rescanning. At block 805635. Progress=0.714384
Nov 04 01:39:05.000  INFO Init: main: Still rescanning. At block 847761. Progress=0.769220
Nov 04 01:40:05.000  INFO Init: main: Still rescanning. At block 894602. Progress=0.829795
Nov 04 01:41:05.000  INFO Init: main: Still rescanning. At block 955915. Progress=0.908334
Nov 04 01:42:05.000  INFO Init: main: Still rescanning. At block 991180. Progress=0.952426
Nov 04 01:43:00.127  INFO Init: main:  rescan              1254804ms
Nov 04 01:43:00.131  INFO main: txnotify thread start
Nov 04 01:43:00.132  INFO Init: main: mapBlockIndex.size() = 1029702
Nov 04 01:43:00.132  INFO Init: main: nBestHeight = 1029700
Nov 04 01:43:00.132  INFO Init: main: setKeyPool.size() = **
Nov 04 01:43:00.132  INFO Init: main: mapWallet.size() = *
Nov 04 01:43:00.132  INFO Init: main: mapAddressBook.size() = *
Nov 04 01:43:00.133  INFO main: torcontrol thread start
Nov 04 01:43:00.212  INFO Init: main: Loaded 24863 addresses from peers.dat  79ms
Nov 04 01:43:00.214  INFO Init: main: AddLocal(ip:port)
Nov 04 01:43:00.215  INFO Init: main: Discover: ***PC-name - ***ip

Nov 04 01:51:05.719  INFO main: keypool return 4
Nov 04 01:51:14.657 ERROR main: AcceptToMemoryPool: inputs already spent
Nov 04 01:52:05.758  INFO main: keypool reserve 4
```
12. No one error in debug, no funds.

**Comment by rex4539** [comment]
@str4d @daira any insight?

**Comment by Aporbel** [comment]
I tried to repalce one of my backups, and it's said that wallet.dat corrupted, how can I restore him?

**Comment by daira** [comment]
First, note that `getaddressesbyaccount ""` will never show z-addresses. The command to use to show z-addresses is [z_listaddresses](https://zcash-rpc.github.io/z_listaddresses.html) (it does not need any arguments).

If you restore the wallet that you had imported the key into and resynced, does that show any addresses from this command?

**Comment by Aporbel** [comment]
> 
> 
> First, note that `getaddressesbyaccount ""` will never show z-addresses. The command to use to show z-addresses is [z_listaddresses](https://zcash-rpc.github.io/z_listaddresses.html) (it does not need any arguments).
> 
> If you restore the wallet that you had imported the key into and resynced, does that show any addresses from this command?
> 
> Also, what is the result of `z_getbalance "your z-address"`?

Yes, I see my z-addresses, but they didn't have any balance. Just 0.

**Comment by daira** [comment]
Please don't make unevidenced allegations of fraud. Also, please keep to a single ticket; opening multiple tickets won't resolve this any faster.

**Comment by daira** [comment]
Thanks for the reporting the result of z_listaddresses; that indicates that the import of the z-addresses was successful. The next thing to do is to resolve the `wallet.dat` corruption you mentioned in #4847:
* What exactly did you do to restore the `wallet.dat`?
* Please run `zcutil/bin/db_verify <path to wallet.dat>` and show us the output.

**Comment by Aporbel** [comment]
zcutil

> 
> 
> Thanks for the reporting the result of z_listaddresses; that indicates that the import of the z-addresses was successful. The next thing to do is to resolve the `wallet.dat` corruption you mentioned in #4847:
> 
>     * What exactly did you do to restore the `wallet.dat`?
> 
>     * Please run `zcutil/bin/db_verify <path to wallet.dat>` and show us the output. (If you didn't build `zcashd` from source, you'll need to do that in order to build `db_verify`.)

I make from source but can't to find any files in zcutil like **/bin/db_verify.**
`>/zcash - ls`
**sudo find / -type d -name "zcutil"**
`>>>home/zcash/zcutil `
**ls**
```
>>>afl                      clean.sh         fetch-params.sh  release-notes.py
build-debian-package.sh  cleanup-tags.sh  libfuzzer
build.sh                 distclean.sh     make-release.py

```

**Comment by Aporbel** [comment]
All my excuses! Problem is SOLVED.

_**db_verify**_ - resolve problem.

Used documentation:
https://docs.oracle.com/database/bdb181/html/installation/BDB_Installation.pdf
https://forum.zcashcommunity.com/t/wallet-dat/36395  - **RU version**
https://forum.zcashcommunity.com/t/recovering-funds-from-wallet-dat/37553/15 - **EN  version**

**Comment by rex4539** [comment]
This issue can be closed.
