### ISSUE TITLE
zcashd v4.1.0 cross-compile for windows fails

### ISSUE THREAD

**Issue by adityapk00** [zcash/zcash#4848]
### Describe the issue
Cross-compiling zcashd to windows fails for v4.1.0

### Can you reliably reproduce the issue?
Yes. Build fails everytime
```
git clone https://github.com/zcash/zcash
cd zcash
git checkout v4.1.0
HOST=x86_64-w64-mingw32 ./zcutil/build.sh -j8
```

### Actual behaviour + errors
```
In file included from sendalert.cpp:41:
In file included from ./main.h:13:
In file included from ./amount.h:9:
In file included from ./serialize.h:14:
In file included from /home/adityapk/github/zcash/depends/x86_64-w64-mingw32/include/c++/v1/ios:215:
/home/adityapk/github/zcash/depends/x86_64-w64-mingw32/include/c++/v1/__locale:401:32: error: use of undeclared identifier '_ISspace'
    static const mask space  = _ISspace;
```

Another error:
```
In file included from /home/adityapk/github/zcash/depends/x86_64-w64-mingw32/share/../include/boost/filesystem.hpp:16:
In file included from /home/adityapk/github/zcash/depends/x86_64-w64-mingw32/share/../include/boost/filesystem/path.hpp:26:
In file included from /home/adityapk/github/zcash/depends/x86_64-w64-mingw32/share/../include/boost/filesystem/path_traits.hpp:22:
In file included from /home/adityapk/github/zcash/depends/x86_64-w64-mingw32/share/../include/boost/system/error_code.hpp:905:
/home/adityapk/github/zcash/depends/x86_64-w64-mingw32/share/../include/boost/system/detail/generic_category.hpp:37:31: error: use of undeclared identifier 'strerror_r'; did you mean 'strerror_s'?
    return strerror_r_helper( strerror_r( ev, buffer, len ), buffer );
                              ^~~~~~~~~~
                              strerror_s
```

### Machine specs:
- I'm cross compiling in WSL Ubuntu 20.04

**Comment by str4d** [comment]
`zcashd` 4.1.0 onwards requires `mingw-w64` 6.0.0 or later for Windows cross-compilation. What version of `mingw-w64` are you using? I would assume 7.0.0 since IIRC that is what Ubuntu 20.04 comes with by default.

**Comment by adityapk00** [comment]
Yup. Mingw is 
```
Package: mingw-w64
Version: 7.0.0-2
```

**Comment by adityapk00** [comment]
BTW, I should note that this is a regression that applies only to `v4.1.0`. Checking out the `v4.0.0` tag and compiling it works just fine.

**Comment by str4d** [comment]
Hmm, this looks like the same issue that @mdr0id reported internally a few weeks ago, which we thought was unique to his local setup (Windows cross-compile works fine for me locally, and [on CI](https://ci.z.cash/#/builders/15/builds/522)).

> I should note that this is a regression that applies only to `v4.1.0`.

That's expected; this is a result of migrating to vendored Clang in #4613 and C++17 in #4611, both of which landed in 4.1.0.

**Comment by adityapk00** [comment]
@str4d  Do you have a docker file or some such that has the right setup to get the cross compile working? I can use any combination of `Mingw` and Ubuntu/Debian

**Comment by str4d** [comment]
Try one of the Dockerfiles in [`contrib/ci-builders`](https://github.com/zcash/zcash/tree/master/contrib/ci-builders) (which is what our CI builders use).

**Comment by adityapk00** [comment]
Thanks! I switched to using ECC's docker container, and I can now build everything. 

Would you like me to close this issue?

**Comment by str4d** [comment]
No, we still want to understand this issue. Were you using Docker before? If so, could you provide your Dockerfile that was reliable failing?

**Comment by adityapk00** [comment]
Yup, this reliably fails:

https://gist.github.com/adityapk00/421eef9d0a00eaa0d7c0da1394b1181b

**Comment by daira** [comment]
I think there is something broken about Ubuntu's multilib headers :-/

**Comment by bigbrain** [comment]
I get the same errors when cross-compiling for windows from Debian 10.7.0 (both amd64 architecture). Unable to compile versions 4.1.1 and 4.2.0. Version 4.0.0 was compiled.

**Comment by mdr0id** [comment]
If the headers get too mangled, you can use our Docker images to sanity check environments:
https://hub.docker.com/u/electriccoinco

Additionally, it is also possible to cross reference that local environment to production builders: https://ci.z.cash/#/builders/15

**Comment by str4d** [comment]
@mdr0id was running into the same `_ISspace` issue with Ubuntu 20.04.2 images from GCP. @daira eventually found this musl ML post: https://www.openwall.com/lists/musl/2018/11/25/1 that suggested it might be multilib-related (Marshall had them installed, I did not in my WSL). But uninstalling the multilib packages doesn't appear to help.

**Comment by str4d** [comment]
I was able to confirm that I can cross-compile for Windows using Docker with the `electriccoinco/zcashd-build-ubuntu2004` image:

```
$ docker run -ti electriccoinco/zcashd-build-ubuntu2004 bash
$ apt install zstd
$ git clone https://github.com/zcash/zcash.git
$ cd zcash
$ HOST=x86_64-w64-mingw32 ./zcutil/build.sh
```

Note that the old instructions to use `update-alternatives` to configure the POSIX variant of `x86_64-w64-mingw32-gcc` and `x86_64-w64-mingw32-g++` was not required; they remained in their `win32` state.

**Comment by bigbrain** [comment]
I have successfully cross-compiled zcash-4.3.0-rc1 for Windows from stable Debian 10.8.0 (+ mingw 8 from unstable, because https://github.com/zcash/zcash/issues/4975) and avoided the error described in the first message. I had this error before. :-)

Before compiling on Debian , I removed all installed multilib packages.
I had these packages: `g++-multilib`, `g++-8-multilib`, `gcc-multilib`, `gcc-8-multilib`.

`sudo apt-get install zstd`

```
sudo update-alternatives --config x86_64-w64-mingw32-gcc
sudo update-alternatives --config x86_64-w64-mingw32-g++
and choose auto (win32).
```
```
cd zcash
HOST=x86_64-w64-mingw32 ./zcutil/build.sh
```

Also I have successfully cross-compiled zcash-4.3.0-rc1 for Windows from a fresh install of Linux Mint 20.1
(based on Ubuntu 20.04 LTS) 
```
sudo apt-get install zstd
```
```
sudo update-alternatives --config x86_64-w64-mingw32-gcc
sudo update-alternatives --config x86_64-w64-mingw32-g++
and choose auto (win32). 
```


**Offtopic:**
I always get the output zcashs.exe file over 200MB in size. I think this is because all libraries are `static`.
Also during compilation the message is displayed:
```
libtool: warning: undefined symbols not allowed in x86_64-w64-mingw32 shared libraries; building static only
```
I think removing multilib packages is not the reason. Because I had a problem with large file size and when they were installed. 
Is there any command that can help to use external .dll libraries and reduce the size of the executable file?

**Comment by bigbrain** [comment]
Now I can also cross-compile **zcash 4.2.0** Release for Windows from Debian 10.8.0 with **mingw 6** included in it. Without installing any unstable packages.

Versions 4.1.0 and 4.1.1 I have not tried to cross-compile again, but I think they will be able to compile successfully too.

As I wrote in the previous post, the error related to multilib packages or their dependencies.
Removing `g++-multilib`, `g++-8-multilib`, `gcc-multilib`, `gcc-8-multilib` with unused other packages dependencies helped me cross-compile this version as well.

**Comment by daira** [comment]
@bigbrain Building an executable that statically links pinned versions of the dependencies is intentional, and essential for consensus compatibility. We deliberately don't support dynamically linking to those libraries.

**Comment by miodragpop** [comment]
@bigbrain Have you tried to strip debug symbols? 

> I always get the output zcashd.exe file over 200MB in size. I think this is because all libraries are static.

**Comment by bigbrain** [comment]
@miodragpop
> 
> 
> @bigbrain Have you tried to strip debug symbols?
> 
> > I always get the output zcashd.exe file over 200MB in size. I think this is because all libraries are static.


I compiled with the recommended parameters: `HOST=x86_64-w64-mingw32 ./zcutil/build.sh -j$(nproc)`

Now I tried to add a flag to completely disable debug information:
```
HOST=x86_64-w64-mingw32 CFLAGS="-g0" CXXFLAGS="-g0" ./zcutil/build.sh
```
As a result, I got an zcashd.exe file about 20MB in size. 20MB! It's incredible! This is ten times less than before!

**Thank you very much!**

**Comment by daira** [comment]
I think this can be closed now, but we should make sure to document the conclusions from this ticket on #4622.
