### ISSUE TITLE
Find a new home for the Calgary Snowflake doc and retire the old branch version.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#486]
Currently the design lives at [`doc/zcash/calgary.md` on branch `zc.v0.10.0.latest`](https://github.com/Electric-Coin-Company/zerocashd/blob/zc.v0.10.0.latest/doc/zcash/calgary.md). However, the implementation will begin off of [branch `zc.v0.11.2.latest`](https://github.com/Electric-Coin-Company/zerocashd/blob/zc.v0.10.0.latest/) so it makes much more sense for the design doc to live on that branch.

What do we do with the old branch?

I propose we "cap" it with a final revision which adds a warning banner saying **THIS REVISION IS OUT OF DATE. PLEASE SEE $new_branch**

**Comment by daira** [comment]
That doc now resides at https://github.com/zcash/zips/blob/master/historical/calgary.md , for historical reference.
