### ISSUE TITLE
receiveunsafe log doesn't include v1 note plaintexts received during the grace period

### ISSUE THREAD

**Issue by daira** [zcash/zcash#4887]
@str4d pointed out that `receiveunsafe` only logs note plaintexts that are invalid according to [ZIP 212](https://zips.z.cash/zip-0212), which doesn't include the ones that we actually wanted to test for as motivation for #4772.

**Comment by str4d** [comment]
Closed because the grace period is over, and the existing log message is sufficient for testing now.
