### ISSUE TITLE
Make zcash build for Windows

### ISSUE THREAD

**Issue by daira** [zcash/zcash#489]

**Comment by nathan-at-least** [comment]
We had the first user request windows just now.

**Comment by blackhatzw** [comment]
In my opinion, Windows is only an optional, most miners are familiar with Linux systems.

**Comment by radix42** [comment]
I'm currently working on a native windows build of v1.0.0-beta2, and will be packaging up a binary release (if/when I succeed) with a graphical installer and the needed utils to run zcash without the "Bash on Ubuntu on Windows" aka "Linux on Windows" subsystem (which currently DOES work to build it).

**Comment by Pwnmanship** [comment]
I would like to see the project build on Windows.

**Comment by ITH4Coinomia** [comment]
@daira I'm willing to take up this task! Please let me know where(Folder) to initiate the PRs for Zcash windows build!

**Comment by radix42** [comment]
@ITH4Coinomia I have branches in my fork that build all dependencies on Windows, they have problems linking zcash itself....I can writeup my notes on the Windows dev environment, I've been meaning to do that for a while, and stick them in a README in my repo...are you an experienced C++ dev?

**Comment by ITH4Coinomia** [comment]
@radix42 Thanks for letting me know about this info! I'm an intermediate C++ coder, please do share me the repo link so that I can able to make some meaningful contribution!

**Comment by ITH4Coinomia** [comment]
@radix42 Thanks for letting me know about this info! I'm an intermediate C++ coder, please do share me the repo link so that I can able to make some meaningful contribution!

**Comment by radix42** [comment]
@ITH4Coinomia do you prefer to cross-compile form linux->windows or just build on windows (needs the msys2 release of mingw64)? Cause I get identical errors on both now, so pick your poison!

**Comment by ITH4Coinomia** [comment]
@radix42 Actually I'm building a zcash docker image for windows and I'll soon initiate some PRs for the same. Could you let me know where(folder) to initiate the PRs?

**Comment by radix42** [comment]
so you're building a linux container to run with docker for windows?

**Comment by radix42** [comment]
because if so, that's not what this ticket is here to track...this is about building windows binaries

**Comment by ITH4Coinomia** [comment]
@radix42 No, I'm building a zcash docker image for windows and please let me know where to initiate the PRs? I have included a copy of snapshot taken during build process...
![zcash](https://cloud.githubusercontent.com/assets/23207793/19927628/8d833be6-a120-11e6-9ab0-26044c5b380f.png)

**Comment by ITH4Coinomia** [comment]
@radix42 Are you still working on this issue? or please let me know if I could contribute to this task anyway.

**Comment by radix42** [comment]
Yes I am, I keep meaning to write up where I'm at and put out a call for help with the C++ template and linking issues I'm having! As a first step, you'll need to install the msys2 release of mingw64. I'll link the writeup here when I get it done, too.

**Comment by radix42** [comment]
I've posted instructions on replicating my build environment for my Windows 10 port in progress at:
https://forum.z.cash/t/windows-port-in-progress-help-needed/8107

**Comment by mdr0id** [comment]
As of 4/17 there exists a solution(#3172) to address the above .

**Comment by ytrezq** [comment]
@mdr0id Why close this ?
There are still no official Widows exe ?

**Comment by mdr0id** [comment]
I only closed it because it has been implemented. We are working to get a
few things into master to fully support Windows. Stay tuned, and please let
us know if you have any questions.
