### ISSUE TITLE
Remove Boost compilation workaround that is probably no longer needed

### ISSUE THREAD

**Issue by daira** [zcash/zcash#4914]
https://github.com/zcash/zcash/blob/7a97e48cb7d8abb1adcc4ed0c2e8745b410f2f69/src/util.cpp#L85..L95

We currently depend on [Boost 0.74.0](https://github.com/zcash/zcash/blob/master/depends/packages/boost.mk#L2).

**Comment by jadijadi** [comment]
Hi @daira , This looks easy. Just removing those lines if I got it right. May I send a PR?
