### ISSUE TITLE
Build regression with Nix on a Raspberry Pi

### ISSUE THREAD

**Issue by daira** [zcash/zcash#5014]
orion on #public-community-dev:
> Hi. I think the following commit may have broken my build of 4.3.0:
> https://github.com/zcash/zcash/commit/e286250ce49309bfa931b622fabfc37100246266
> Specifically, the committer changed `bool` to `std::atomic_bool`, but never specified `#include <atomic>`.

daira:
> What platform are you building on/for?

orion:
> On a Raspberry Pi 4, with a Raspberry Pi 4.

daira:
> Ah, ok. I'll file a PR (on Monday)

Marshall:
> What system was used to compile the ARM binary? Asking because the builder for that platform has successfully built for a while now.

orion:
> Nix.

**Comment by mdr0id** [comment]
Apologies for not noticing you were doing this on the native system itself. Disregard my comment about our builder, since it is doing a cross compile for ARM from Deb10.
