### ISSUE TITLE
Add Orchard keys and receivers to the wallet

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#5019]
We may end up exposing these via "single-address" address bundles instead of directly as Orchard addresses; to be decided.

**Comment by str4d** [comment]
This only covers storage of these types in the wallet. Generating Orchard spending keys is #5255.

**Comment by nuttycom** [comment]
The wallet backend has been implemented in #5552; related/remaining work has been specified in #5567, #5568 and #5020. This can now be closed.
