### ISSUE TITLE
Jessie release is still in the Zcash Tor apt repo

### ISSUE THREAD

**Issue by the-metalworker** [zcash/zcash#5027]
```
Ign:10 tor+http://zcaptnv5ljsxpnjt.onion jessie InRelease 
Get:11 tor+http://zcaptnv5ljsxpnjt.onion jessie Release [3,424 B]
Get:12 tor+http://zcaptnv5ljsxpnjt.onion jessie Release.gpg [833 B]
Ign:12 tor+http://zcaptnv5ljsxpnjt.onion jessie Release.gpg
Reading package lists... Done 
W: GPG error: tor+http://zcaptnv5ljsxpnjt.onion jessie Release: The following signatures were invalid: BADSIG C2A798EF998940FA Zcash Master Signing Key (Zcash Electric Coin Company) <signingkey@z.cash>
E: The repository 'tor+http://zcaptnv5ljsxpnjt.onion jessie Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```

According to [this thread](https://forum.zcashcommunity.com/t/end-of-debian-jessie-support-is-on-october-1st-2020/37313) Jessie support ended in October 2020:

> We are ending support for the older and out-of-support “Jessie” distribution of Debian, and removing packages for that OS from our apt repository on October 1st 2020.

However Jessie is still in the Tor repo, it just returns the above BADSIG error when the user tries to update. http://zcaptnv5ljsxpnjt.onion/dists/

Is this expected? Could there be some message in the update error along the lines of "Jessie is no longer supported, please update your OS to Debian Stretch or newer to continue using Zcash"?

**Comment by charlieok** [comment]
Thank you for letting us know. I've unpublished the jessie repository.
