### ISSUE TITLE
Building from source is painfully slow on macOS

### ISSUE THREAD

**Issue by daira** [zcash/zcash#5042]
I'll get timings when I can, but it seems to be due to https://github.com/rust-lang/rust/issues/80684 .

We don't actually need to build the Rust docs. So we could speed up Zcash builds on all platforms by patching `config.toml` as described in that ticket:
```
[build]
docs = false
```

**Comment by jyn514** [comment]
> I'll get timings when I can, but it seems to be due to rust-lang/rust#80684 .

FYI vext01 reported times of almost an hour, personally I wouldn't bother letting it run that long: https://github.com/rust-lang/rust/issues/80684#issuecomment-754017981

**Comment by daira** [comment]
It turned out to be easier to pass `--without=rust-docs` as an argument to Rust's `install.sh`.

**Comment by daira** [comment]
@zkbot try
