### ISSUE TITLE
Identify necessary RPC changes to support Unified Addresses

### ISSUE THREAD

**Issue by steven-ecc** [zcash/zcash#5056]

**Comment by str4d** [comment]
We've discussed this, and opened up the following issues:

- #5177 (RPC deprecation)
- #5178 (`z_getnewaccount`)
- #5180 (`z_getaddressforaccount`)
- #5181 (`z_listunifiedreceivers`)
- #5182 (`z_getbalanceforaddress`)
- #5183 (`z_getbalanceforaccount`)
- #5184 (UA recipients in `z_sendmany`)
- #5185 (Funding `z_sendmany` with UA accounts)
- #5186 (Figure out how to render UAs in `z_viewtransaction`)
- #5191 (Deprecate `z_getbalance`)
