### ISSUE TITLE
Change depends to try https://z.cash/depends-sources *before* the upstream package sources.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#506]
This is a bandwidth and availability trade-off.  Our availability is tied directly to ``z.cash``, whereas an outage in any of the many upstream package sources may be harder to control or detect.

[Edit by Daira: zca.sh -> z.cash]

**Comment by daira** [comment]
I believe we already did this. @ageis, @ebfull?

**Comment by daira** [comment]
Yes this was done.
