### ISSUE TITLE
Questions regarding this project

### ISSUE THREAD

**Issue by Joe23232** [zcash/zcash#5067]
Hi I have some questions regarding this project:
1. Is it workable right now? Am I able to generate hashes to earn money?
2. Can I control how much processing power to take to generate hashes?
3. Am I able to change the output or not even display a console session for situations I may not want a console to open and for it to run in the background?
4. Say if I have the crypto wallet stored on my computer A and it is off, and I am doing cryptomining (using this crate) on Computer B and Computer B does NOT store the wallet and I wanted to send it off. Do I need to store the wallet on a server? Does the crypto wallet have a server where I can chose to create a wallet and where all my money can go over there?
5. Is this library capable of sending generated hashes via the Internet?
6. Am I able to use The [Rust](https://www.rust-lang.org/) Programming Language to script and control mining? If so how difficult would it be to code it up?
7. If 6 is applicable, then how efficiently can I generate the code?
8. Is it as private and secure as [Monera](https://www.getmonero.org/)?

**Comment by str4d** [comment]
For questions 1, 2, 4, 5, 6, 7: This repository is for the `zcashd` full node; it is not software that interacts at all with mining pools. It does have a standalone internal CPU miner but that is very non-optimal given the current network solution power; you probably want to use an ASIC instead.

3: You can run with the `-daemon` argument (or `daemon=1` in `zcash.conf`) to run `zcashd` in the background.
8: Monero uses ring signatures with a ring size of around 10, meaning that Monero transactions have a smaller anonymity set than fully-shielded Zcash transactions (for which the anonymity set is approximately the number of notes that have been created in the particular shielded pool at that time). Zcash also supports partially-shielded and fully-transparent transactions, which obviously have less / no privacy than either Monero or fully-shielded Zcash transactions.

**Comment by Joe23232** [comment]
@str4d Hey man thanks for your response.

I just have one more question, so are there any Rust configured cryptomining software where I can import it as a library and code my code and integrate it into my software?

**Comment by str4d** [comment]
I am not aware of any, but you could ask in the mining channel of the Zcash Community Discord.

**Comment by Joe23232** [comment]
Sure. thanks
