### ISSUE TITLE
Make it harder to misuse util.cpp in libzerocash

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#510]
The API util.cpp presents is confusing. Some output sizes are specified via input sizes, and some of them resize for you and others don't. Decide what the "safest" API should be, noting that in C++ it's usually possible to make it cheap to return objects, even big vectors, because of move constructors and things like that. Then, make them all behave similarly.

From #493.

**Comment by defuse** [comment]
@ebfull: This can probably be closed by one of your PRs, right?

**Comment by ebfull** [comment]
This is actually the only part of libzerocash that I leave alone.

**Comment by ebfull** [comment]
Taylor was able to reduce `util.cpp` to a very small amount of code, and eliminating it entirely can be the scope of this ticket.

**Comment by daira** [comment]
Why not just moved the remaining two functions into https://github.com/zcash/zcash/blob/zc.v0.11.2.latest/src/zcash/util.cpp ?
