### ISSUE TITLE
Check the security of the CSPRNG in libzerocash

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#515]
It uses `CryptoPP::AutoSeededRandomPool`, and I have no idea how that works.

From #493.

**Comment by daira** [comment]
I would like us to switch to libsodium's CSPRNG.

**Comment by daira** [comment]
@defuse wrote:
> Is it thread-safe? Is it fork-safe?

The [doc for Crypto++ random number generation](https://www.cryptopp.com/wiki/RandomNumberGenerator) says "If you are using a generator in a multithreaded program, then use a single generator per thread or provide an external lock for a single generator." Forking will duplicate the state.

libsodium [is thread-safe once sodium_init has been called](https://github.com/jedisct1/libsodium/issues/101). By default its RNG API reads directly from ``/dev/urandom``, [which should make it fork-safe](https://github.com/jedisct1/libsodium/issues/266) on platforms that have ``fork``.

**Comment by paragonie-scott** [comment]
(Another point in favor of libsodium's CSPRNG: On newer Linux kernels it also uses `getrandom(2)`.)

**Comment by daira** [comment]
Wait, does libzerocash use *both* Crypto++ and OpenSSL's CSPRNGs? I'm confused between this ticket and #450 .

**Comment by ebfull** [comment]
It does use both, one for the key-private encryption, and one for all of the other randomness such as the trapdoors.
