### ISSUE TITLE
./qa/zcash/test-depends-sources-mirror.py doesn't use $SOURCES_PATH when set

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#5150]
If you set SOURCES_PATH to use a common dependency-source directory for all your builds, then the ./qa/zcash/test-depends-sources-mirror.py script doesn't work because it looks in the default place within the zcash/zcash clone. It should check if SOURCES_PATH is set, and if so, use that path instead of the default one.

**Comment by daira** [comment]
This was fixed by #6538.
