### ISSUE TITLE
I got error when building [Android ARMv8]

### ISSUE THREAD

**Issue by Saikatsaha1996** [zcash/zcash#5166]
![Screenshot_2021-05-15-22-47-20-854_com termux](https://user-images.githubusercontent.com/72664192/118372493-850cd300-b5cf-11eb-9e13-6481d48da0b0.jpg)

Platform Android 
Arm V8 
Ram 8gb
Sdm 865 processor
How can I slove?

**Comment by daira** [comment]
Android likely has significant differences from Linux on a desktop; I'm not sure anyone has tried to build zcashd on it, and definitely not natively on the device. You might have more success with a cross-build from Linux.

Sdm 865 appears to be a Qualcomm Snapdragon 865 SoC using their [Kryo](https://en.wikipedia.org/wiki/Kryo) processor, which implements ARMv8-A. We should be able to build for that.

**Comment by Saikatsaha1996** [comment]
> Android likely has significant differences from Linux on a desktop; I'm not sure anyone has tried to build zcashd on it, and definitely not natively on the device. You might have more success with a cross-build from Linux.
> 
> Sdm 865 appears to be a Qualcomm Snapdragon 865 SoC using their [Kryo](https://en.wikipedia.org/wiki/Kryo) processor, which implements ARMv8-A. We should be able to cross-build for that.

Can you guide me please ?..
How can I cross build?..
I am using termux..

**Comment by daira** [comment]
The command to do a cross-build for Android ARM would be:
```
HOST=armv7-linux-androideabi zcutil/build.sh -j$(nproc)
```
(`armv7` is correct, not `armv8`). But that fails because it can't find the relevant standalone Rust installer, which doesn't appear to be available from [here](https://forge.rust-lang.org/infra/other-installation-methods.html#standalone-installers). (If it was then it would just be a matter of updating the build scripts to support this platform.)

You can install the needed Rust target locally using:
```
rustup target add armv7-linux-androideabi aarch64-linux-android i686-linux-android
```
but the zcashd build process won't use that. @str4d, how would you recommend to proceed?

**Comment by str4d** [comment]
To cross-compile to `aarch64-linux-android` (which is the one I believe you should use; AFAICT the Snapdragon 865 is a 64-bit processor), you would indeed need to add a Rust standard library line to `depends/packages/native_rust.mk`:
```diff
 # Mapping from Rust targets to SHA-256 hashes
+$(package)_rust_std_sha256_hash_aarch64-linux-android=458d365f6be2764dc04185928427292c348271ffb2d653a2219603877183d564
 $(package)_rust_std_sha256_hash_aarch64-unknown-linux-gnu=a6ed4abe59dfaf2119e2803f67fd8aef757a622ae3ac9a040946af2b02f4c269
 $(package)_rust_std_sha256_hash_x86_64-apple-darwin=2856bc46d3624ae2658897c15388c0c353bea916963a2fc5991c23b920d5678c
```

You will also need to have the relevant Android toolchain's linker available on your `PATH`. There are probably other necessary changes, which will become apparent.
