### ISSUE TITLE
What happens when you pass an index >= num elements in IncrementalMerkleTree?

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#517]
I accidentally passed a coin hash (256-bit bool vector) into the getWitness thing in the IncrementalMerkleTree, and there was no obvious error. Find out what happens when someone does that and write unit tests for it.

Why is the index even a vector of bools? From the outside we should be using uint64_t everywhere to be consistent.

Also, what happens inside the SNARK if you give it some weird index?

From #493.

**Comment by ebfull** [comment]
The new tree design will obviate this question.
