### ISSUE TITLE
Implement BIP 39 seed phrase support

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#5176]
We want all UAs to be derived from a BIP 39-compatible seed. For simplicity, we will start using this seed for all other derivations in the wallet (with the legacy RPCs using account 0, and UA-compatible RPCs using accounts 1+).

For this issue, we need to:
- Add BIP 39 support to the codebase.
- For all wallets (both new and existing), generate a new seed phrase on startup if one does not exist.
- Switch existing HD key derivation for legacy RPCs to derive from this seed phrase if available.
- Add the seed phrase to wallet exports.

**Comment by str4d** [comment]
Closed by #5391.

**Comment by daira** [comment]
Reopening this because it depends on #5399 to be complete.

**Comment by str4d** [comment]
I've reversed the ordering; #5399 is now a follow-up to this issue.
