### ISSUE TITLE
New RPC: z_getaddressforaccount

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#5180]
Usage: `z_getaddressforaccount ACCOUNT [DIVERSIFIER_INDEX] [LIST_OF_PROTOCOLS]`

- Returns an error for account 2<sup>31</sup>-1 (see https://github.com/zcash/zips/issues/511).
- Returns an error if the account is unknown.
  - This means that we have not generated it yet via `z_getnewaccount`.
  - We could maybe relax this to a warning, but it would significantly impair wallet recovery from the seed phrase.
- With no diversifier index (or the string `*`), returns the next unused (valid for the list of protocols) diversified UA for that account.
- With a diversifier index, returns the corresponding diversified UA.
  - If the list of protocols includes Sapling and the given index is not a valid Sapling index, then return an error.
  - If the list of protocols includes transparent and the given index is outside the valid range for transparent addresses, then return an error.
- With a list of protocols, returns the UA containing that (subset of) receivers.
  - If the diversifier index is valid for that subset (but wouldn't be for the full set), don't return an error.
- Returns a JSON dict with the account number, the diversifier index that was picked, the protocols the UA contains, and the resulting UA.

**Comment by nuttycom** [comment]
One question about this API: given that it's possible to provide both the list of protocols and the diversifier index, this means that the user could request two different addresses at the same diversifier index; if we allow this, then we can't uniquely identify the unified address corresponding to that diversifier index. Should this also return an error in the case that the diversifier index has already been used with a different set of receiver types?

**Comment by str4d** [comment]
Closed by #5475, merged into #5419.
