### ISSUE TITLE
New RPC: z_getbalanceforaccount

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#5183]
- Same output structure as `z_getbalanceforaddress` (#5182), but returns balances for all pools that have the potential to contain funds.
- This API can only return balances for accounts linked to the wallet’s BIP 39 seed phrase, and thus only returns spendable balances.

**Comment by LarryRuane** [comment]
Will this take an account number as the only required argument? Does the result dictionary possibly contain an entry for sprout (or only transparent, sapling, and orchard)?

Probably should also have an optional minconf argument.

**Comment by str4d** [comment]
Closed by #5500, merged into #5419.
