### ISSUE TITLE
z_viewtransaction: Figure out how to render UAs

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#5186]
Where possible, it would be great to render UAs inside `z_viewtransaction` output that matches what users might actually have used for those transactions. What this means is:

- If the user spent funds from a UA, show that UA in the output.
  - With domain separation of receivers, we should be able to link spent funds to specific Unified accounts.
  - Show the default UA for that account.
- If the user received funds to a UA, show that UA in the output.
  - We should be able to derive the exact UA that was used (e.g. from the diversifier in the note, recover the diversifier index, and use this to find or re-derive the UA).
  - This includes moving funds around inside the wallet with e.g. `z_mergetoaddress`.
- If the user sent funds to an external UA, show that UA in the output.
  - This would probably only be possible if we cache the recipient in `z_sendmany` (or other APIs).
  - For a recovery from seed phrase, we could only show a single-receiver UA (or for Sapling and transparent, a legacy format address).

**Comment by str4d** [comment]
One idea for external recipients: we could store the user-provided recipient address inside a change output memo.

- Use a zero-value change output if there would be no change?
  - We default to min of 2 outputs for Sapling and Orchard, so we’d likely have that anyway.
- For long UAs this might require multiple change outputs.
- Would be unauthenticated data; we'd need to ensure that it could not be used by an adversary to influence wallet behaviour.
  - If all spends are from us, we know it’s a change output (i.e. gating it behind a check that "this is only a change output if we actually spent funds in the transaction").
  - If collaborative, we might need the change output fields to be signed?
    - This would require a zkproof
    - For collaborative transactions, instead require that all senders can inspect all output memos (they need to see the private data anyway for correctly constructing proofs).

**Comment by str4d** [comment]
#5475 adds the logic to show the corresponding UA if a Sapling note belongs to an address that is part of a wallet account.

We still need to cache and display external UAs provided as recipients to e.g. `z_sendmany`.

**Comment by nuttycom** [comment]
It's probably also a good idea to add support for transparent spends and outputs at the point that we're making other modifications (adding Orchard) to this RPC endpoint.

**Comment by nuttycom** [comment]
In addition, if a node is unable to decrypt some information, it would be useful to add sentinels for these inputs or outputs to indicate to the user that the information cannot be decrypted.

**Comment by nuttycom** [comment]
The policy has to apply here has been applied in #5575

**Comment by nuttycom** [comment]
Fixed by #5700
