### ISSUE TITLE
Accounts are unsupported on Zcash v4.4.0 !!!!

### ISSUE THREAD

**Issue by MohseniBigBoy** [zcash/zcash#5206]
I use the Zcash Daemon version v4.4.0, but Account and Label are not supported! I use` --deprecatedrpc=accounts` flag to run both of `zcashd` and `zcash-cli `but when I use [getnewaddress Account_Name](https://zcash-rpc.github.io/getnewaddress.html) I get: 
```
error code: -11
error message:
Accounts are unsupported
```
At this version, I know the account must be an empty string, But I want to use from account or label.
I don't want to use previous versions, so How can I use accounts or labels?

**Comment by daira** [comment]
Accounts and labels have never been supported in zcashd. They never will be with the semantics defined in Bitcoin Core. (Actually, Bitcoin Core has deprecated them.)

**Comment by MohseniBigBoy** [comment]
Thanks, I test Zcash Daemon version v3.1.0, In this version, the Account is not supported, too! 😔😢
