### ISSUE TITLE
CI testing of libsnark

### ISSUE THREAD

**Issue by daira** [zcash/zcash#521]
libsnark has tests (in the `src/algebra/curves/tests` directory), but I don't know whether there is any continuous integration system running them.

**Comment by nathan-at-least** [comment]
I'm moving a bunch of CI improvements out of "Audit Tasks" into `1.0.0-beta2`.

**Comment by str4d** [comment]
In our fork of libsnark, we have the following tests:

```
./src/gadgetlib1/gadgets/merkle_tree/tests
./src/gadgetlib1/gadgets/hashes/sha256/tests
./src/algebra/fields/tests
./src/algebra/curves/tests
./src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/tests
./src/relations/arithmetic_programs/qap/tests
```

All of these tests are individual executables, so we'd need to call them specifically. The dependency-handling script has been removed from our fork of libsnark, so we'd need to either reinstate it, or conditionally enable building the tests inside the zcash depends system.

**Comment by nathan-at-least** [comment]
Note, our fork of libsnark may have broken these tests! Let's figure out which tests are important for our fork and remove tests that do not apply to our fork.

**Comment by nathan-at-least** [comment]
I'm unassigning @imichaelmiers because he's not familiar with our fork and may not be available on the timeline for Beta 2.

**Comment by bitcartel** [comment]
Not enough time to do this before launch.

**Comment by ignacionr** [comment]
Guys I am building libsnark as-is and its tests mostly fails. Did you find the same thing?
