### ISSUE TITLE
mapOrphans interactions

### ISSUE THREAD

**Issue by ebfull** [zcash/zcash#523]
Transactions with pours must be invalidated from mapOrphans if one of their serials is spent by another transaction entered into the mempool or chain tip.

**Comment by ebfull** [comment]
Bitcoin-style transactions which reference inputs that are not known (either in the blockchain or the mempool) are placed in what is called "mapOrphans." There are no scenarios where a pure "joinsplit" transaction would be placed in this map.

We have two options for handling transactions that contain both joinsplits and "transparent" inputs that are unknown to the node.

1. Don't allow transactions containing joinsplits to enter mapOrphans. (Current behavior.)
2. Allow transactions containing joinsplits to enter mapOrphans, evict them when a transaction is accepted to the mempool which contains a serial used by the transaction or a reorg occurs which invalidates the anchor.

Applying "what would zooko do" leaves me with option 1, and I honestly can't think of a good reason why we should bring the complexity of 2 into our protocol. As such, I recommend we just close this ticket.

**Comment by nathan-at-least** [comment]
We agree that since ``mapOrphans`` is an optimization and not visible in consensus, we're going with option 1.
