### ISSUE TITLE
Bind zcashd to a wallet

### ISSUE THREAD

**Issue by sulheru** [zcash/zcash#5230]
I recently installed the Zcash Debian Binary Packages and they are running perfectly. Now I would like to know how to I bind zcashd to my wallet address and get payments for mining.

**Comment by nuttycom** [comment]
CPU mining and GPU mining are generally not profitable at present. If you are interested in mining, there's an excellent guide here: https://zcash.readthedocs.io/en/latest/rtd_pages/zcash_mining_guide.html
