### ISSUE TITLE
Rename SaltedTxidHasher to SaltedHasher

### ISSUE THREAD

**Issue by daira** [zcash/zcash#5234]
#4979 renamed `CCoinsKeyHasher` to `SaltedTxidHasher`. This is a confusing name, because (like upstream!) we do not only use it to hash txids.

**Comment by elijahhampton** [comment]
@daira Is anyone working on this? I can complete it for you

**Comment by nuttycom** [comment]
@elijahhampton Nobody is currently working on this, but it would be great to look at what has happened with this type in the upstream Bitcoin codebase, and to backport whatever changes they might have made there. In general, for parts of the codebase that are largely derived from Bitcoin, we prefer to make changes in a way that minimizes conflicts when backporting changes from upstream; #4979 is a backport, so we likely don't want to do a rename unless the upstream codebase has also done so. If upstream hasn't made additional changes here, this issue should just be closed. Thanks for offering to help!

**Comment by elijahhampton** [comment]
Okay I'll take a look. No problem.

**Comment by elijahhampton** [comment]
@nuttycom A separate type "SaltedOutpointHasher" was created to handle hashing of COutPoint outpoints where necessary, however it looks like no rename was done in upstream and the type still exist. 

In this case I think it suffices to close the issue. If you need more information or would like me to dig deeper let me know!

**Comment by nuttycom** [comment]
@elijahhampton great, thank you for doing the research!
