### ISSUE TITLE
Add an Orchard nullifier test to `coins_tests`

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#5240]
https://github.com/zcash/zcash/blob/d8c818bfa507adb845e527f5beb38345c490b330/src/test/coins_tests.cpp#L285

Currently a `TODO` left over from https://github.com/zcash/zcash/pull/5233.

**Comment by str4d** [comment]
https://github.com/zcash/zcash/blob/d8c818bfa507adb845e527f5beb38345c490b330/src/test/coins_tests.cpp#L285

**Comment by nuttycom** [comment]
Fixed in #5647
