### ISSUE TITLE
How fix error TLS handshake on localhost for developing ?

### ISSUE THREAD

**Issue by zababurinsv** [zcash/zcash#5248]
## Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. Example: 
I'm i get TLS handshake error  because i use Self-signed certificate for developing
```
reconnect websocket (127.0.0.1:8232): tls: first record does not look like a TLS handshake
```
## Describe the solution you'd like
Is it possible to disable this check ?
example:
In node.js in the env file I am specifying the parameter for developing
 ```
 NODE_TLS_REJECT_UNAUTHORIZED=0
 ```

## Alternatives you've considered
I have a domain and letsencrypt cert.
This would fix the problem.
But I don't have a white ip address.
Now I can only access the Internet from a mobile phone.
I am unable to set up dynamic dns on the phone.

**Comment by str4d** [comment]
The JSON-RPC interface does not support TLS. It used to a long time ago, but upstream Bitcoin Core removed support in https://github.com/bitcoin/bitcoin/pull/5677, which we backported in https://github.com/zcash/zcash/pull/2176.

You will need to ensure that whatever JSON-RPC library you are using to interact with `zcashd` is using HTTP to connect, not HTTPS. You should also ensure that your `zcashd` node's JSON-RPC port is never exposed beyond localhost.

**Comment by str4d** [comment]
See also https://bitcoin.org/en/release/v0.12.0#rpc-ssl-support-dropped for more details on alternatives for securing remote access to the JSON-RPC interface, though you really should not expose it publicly.
