### ISSUE TITLE
Implement Unified Viewing Key parsing and serialization

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#5257]
Covers both UFVK and UIVK support in `KeyIO` etc.

**Comment by CRYONE7** [comment]
is:issue ZCASH |  https://www.globe.com.ph | 00000000000000000009aee86810c43c3c613a5608771c6c03e55961abd1f08f | Blockchain:67ADDA7754942AFE88CA3EF5282FC68F@html.blink> | CHAINLINK | 07E753C0-DA28-4456-B466-2E97070F2664 |BTCC | BITCOIN | NFT | ETF | CHRYSTOPHER CASERO DIZON's DIGITAL ASSETS | C8298F05-2D0E-4419-8144-341BBDB06DD4 | hash=sha256:14762875b22d0055f05d12abc7f7d61d5fd4fe4642ce1a249abdf8c700bf1fd8 | hash=sha256:15492a6368d985b76a2a5fdd2166cddfea5d24e69eefed4630cbaae5c81d89bd | EBOOKS | DIGITAL ARTS | CRYPTO CURRENCIES | PDF | MUSIC | POETRY | PHOTOGRAPHY | TRADEMARK | PATENTS | COPYRIGHT | | hash=sha256:0563c1b3826945eecd62186f3f5c7d31abb7391fedc893b7e2b26303b5a9f3fe | hash=sha256:114b281e4d68302a324dd33abb04778e8557d88947875cbf4e842c2c01a030c5 | hash=sha256:14762875b22d0055f05d12abc7f7d61d5fd4fe4642ce1a249abdf8c700bf1fd8 | hash=sha256:15492a6368d985b76a2a5fdd2166cddfea5d24e69eefed4630cbaae5c81d89bd | hash=sha256:17c07 |3de315745a1510393a96e680d20af8e67e324f70b42accbd4cb3315c9fb | hash=sha256:209b4a8ee987eccc91e2bd3ac36adee0e53a5970b8ac52c273f7f8fd4872c94c | DCB_ASSOCIATION:ZC340J4M0HQ2ICKDTU1DA5EQBTHFPN08V | https://google.developer/chrazzy808/03a0433bad5f71eed92f0d2374e1f2ec54cc20c3352b412b0c7d97d00a9c6b32 | 12dRugNcdxK39288NjcDV4GX7rMsKCGn6B | FYCbwxf7nMeHvR8dyms5Lsz1yS1y58a8JNJMU4oBT

**Comment by str4d** [comment]
Closed by #5400, merged into #5419.
