### ISSUE TITLE
`getaddresstxids` sometimes returns txids in the wrong order

### ISSUE THREAD

**Issue by adityapk00** [zcash/zcash#5285]
### Describe the issue
There's a rare case where the txids returned by `getaddresstxids` are in the wrong order. This causes unexpected bugs in wallets because wallets assume txids are returned in correct order when scanning. 

#### If so, please list the steps to reproduce below:
- If there are 2 txns involving the same taddress in the same block (for eg., when an unconfirmed t-address incoming tx is spent in the same block)
- Calling `getaddresstxids` returns the txids in the wrong order (i.e., the spending txid is returned before the receiving one) randomly. 

### Expected behaviour
txids should be returned in the exact same order they are in the blockchain. To do this, we should sort by `(blockheight, txindex)` instead of just `blockheight`

### The version of Zcash you were using:
v4.4.1, also master branch. 

### Any extra information that might be useful in the debugging process.
There's a fix in https://github.com/zcash/zcash/pull/5284

**Comment by str4d** [comment]
> txids should be returned in the exact same order they are in the blockchain

The RPC in question provided no such guarantees (it was originally added for use by block explorers), so this is not a bug. However, we're okay with making this change to the RPC output.

**Comment by adityapk00** [comment]
https://github.com/zcash/zcash/pull/5284

This PR was merged, closing.
