### ISSUE TITLE
Specify cryptographic binding of Pours to transactions.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#529]

**Comment by ebfull** [comment]
#663 is a very important ticket to consider for this ticket.

Additionally, we need to segregate the keys used for pours and for normal bitcoin transactions.

**Comment by ebfull** [comment]
I think we've agreed to go with a conservative scheme for 1.0. Perhaps before 1.0 we can make it more flexible.

**Comment by ebfull** [comment]
Remember, without advanced malleability features in 1.0 users cannot "pour" from the mempool using the replace-by-fee scheme I described.

**Comment by daira** [comment]
@ebfull I don't think I ever heard a description of the replace-by-fee scheme.

**Comment by nathan-at-least** [comment]
The next step here is to ensure the protocol spec unambiguously defines this binding.

There are actually two decoupled concerns:

* Using Bitcoin script versus "hard-coded" use of ecdsa.
* Extending signature hash algorithm to ensure TxIn and Pour Descriptor signatures bind to each other (and the rest of the transaction).

The second bullet can actually be thought of as two potentially separable concerns:

* Extending signature hashing so that in TxIn script, those hashes cover the relevant portions of Pour Descriptors, so that those TxIn signatures are invalidated if any bit of any of the Pour Descriptors is altered.
* Extending signature hashing for Pour Descriptor signatures, so that any change to any TxIn bit or any other non-signature bit of a CTransaction invalidates the signature.

Those *could* be independently specified. However, my inclination is to say "there is one kind of signature hash and both TxIn and Pour signatures sign the result of that kind of hash."

To do this, we want to extend [``SignatureHash`` in ``src/script/interpreter.cpp`` L1098-L1121 at ``3af297cc``](https://github.com/bitcoin/bitcoin//blob/3af297cc57ca70d2874187a378dbdee293b272b6/src/script/interpreter.cpp#L1098-L1121) ([latest on branch ``zc.v0.11.2.latest``](https://github.com/bitcoin/bitcoin//blob/zc.v0.11.2.latest/src/script/interpreter.cpp#L1098-L1121)).

More specifically we can probably modify only [``CTransactionSignatureSerializer`` in ``src/script/interpreter.cpp`` L985-L1094 at ``3af297cc``](https://github.com/bitcoin/bitcoin//blob/3af297cc57ca70d2874187a378dbdee293b272b6/src/script/interpreter.cpp#L985-L1094) ([latest on branch ``zc.v0.11.2.latest``](https://github.com/bitcoin/bitcoin//blob/zc.v0.11.2.latest/src/script/interpreter.cpp#L985-L1094))

**Comment by zookozcash** [comment]
Per Nathan's email “Wrapping up Feature Selection”, this is already agreed to be in 1.0 so it doesn't need to be in today's engineering meeting.

**Comment by nathan-at-least** [comment]
Renamed this to be about *specification only* rather than implementation. Close it when the spec is complete.

**Comment by nathan-at-least** [comment]
I added #808 to track the implementation of this spec, and *this ticket* can be closed when the spec lands.

**Comment by daira** [comment]
Fixed.
