### ISSUE TITLE
VerifyDB does not correctly perform Orchard batch validation.

### ISSUE THREAD

**Issue by nuttycom** [zcash/zcash#5316]
https://github.com/zcash/zcash/blob/master/src/main.cpp#L5372 constructs a batch validator that accumulates signatures for validation but never has validation actually run.

**Comment by str4d** [comment]
This does not need to be addressed for v4.5.0, but should be addressed before v5.0.0.

**Comment by daira** [comment]
We should fix this for 4.6.0, so that it's properly tested on testnet.

**Comment by daira** [comment]
Oh I see, this is only for the database consistency check at startup. I still think it should be done for 4.6.0.
