### ISSUE TITLE
This version has been deprecated [upgrade to v4.5.1 needed]

### ISSUE THREAD

**Issue by vae520283995** [zcash/zcash#5336]
My version is v4.4.1
```
Sep 30 17:02:34.915  INFO Init: main: Checking all blk files are present...
Sep 30 17:02:35.155  INFO Init: main: LoadBlockIndexDB: transaction index enabled
Sep 30 17:02:35.155  INFO Init: main: LoadBlockIndexDB: insight explorer disabled
Sep 30 17:02:35.155  INFO Init: main: LoadBlockIndexDB: light wallet daemon disabled
Sep 30 17:02:36.039  INFO Init: main: LoadBlockIndexDB: hashBestChain=000000000105fa7925ade0d29785d0fbb8575fadafdd649a847351cff4dd5c83 height=1408444 date=2021-09-30 13:43:12 progress=0.999871
Sep 30 17:02:36.039  INFO Init: main: *** This version has been deprecated as of block height 1408444. You should upgrade to the latest version of Zcash.
Sep 30 17:02:36.039  INFO Init: main: Error: This version has been deprecated as of block height 1408444. You should upgrade to the latest version of Zcash.
Error: This version has been deprecated as of block height 1408444. You should upgrade to the latest version of Zcash.
Sep 30 17:02:36.053  INFO Init: main: init message: Rewinding blocks if needed...
Sep 30 17:02:40.230  INFO Init: main: init message: Verifying blocks...
Sep 30 17:02:40.231  INFO Init: main: Verifying last 288 blocks at level 3
Sep 30 17:02:40.233  INFO Init: main: Shutdown requested. Exiting.
Sep 30 17:02:40.234  INFO Shutdown: main: StopRPC: waiting for async rpc workers to stop
Sep 30 17:02:40.234  INFO main: scheduler thread interrupt
Sep 30 17:02:40.234  INFO Shutdown: main: StopNode()
Sep 30 17:02:40.240  INFO Shutdown: main: done
```

**Comment by daira** [comment]
You will need to upgrade to version 4.5.1.

The reason for this is that zcashd implements an "End of Service halt" where each release will only run for 18 weeks before shutting down. The main motivation is to make sure that when designing consensus and peer protocol changes, we can make assumptions about which versions are running on the network.

**Comment by vae520283995** [comment]
> The reason for this is that zcashd implements an "End of Service halt" where each release will only run for 16 weeks before shutting down. The main motivation is to make sure that when designing consensus and peer protocol changes, we can make assumptions about which versions are running on the network.

Thank you for your answer, where should I get the updated information, I am now subscribed to the github release reminder, but I don't know when the old version will stop

**Comment by str4d** [comment]
You can check `zcash-cli getdeprecationinfo` for that information.

**Comment by vae520283995** [comment]
> You can check `zcash-cli getdeprecationinfo` for that information.

Sorry, my English is not good, you misunderstood what I meant.
I am an exchange wallet provider, and we run a zcash node.I know that the official release of the new version v0.5.1, but the release log does not indicate that the v0.4.1 version is deprecated, and we don't know that we need to upgrade until the user can't withdraw the zec. I want to know where do I get news about the need to upgrade the node

**Comment by steven-ecc** [comment]
We put out notices on our [blog](https://electriccoin.co/blog/) and also email our partners with reminders. If you want to send me an email (steven -at- electriccoin.co) I'll make sure you're on the list for future notices.

**Comment by vae520283995** [comment]
> We put out notices on our [blog](https://electriccoin.co/blog/) and also email our partners with reminders.
The blog is the same as the github release notes, only NU5 will activate on testnet at height 1,590,000, and there is no clear statement that the old version will be deprecated
> If you want to send me an email (steven -at- electriccoin.co) I'll make sure you're on the list for future notices.
I have emailed you, thank you

**Comment by daira** [comment]
https://z.cash/support/schedule/ has a timeline showing expected EoS halt dates. Note that it is updated manually, and therefore may not be as reliable as `getdeprecationinfo` for the purpose of finding the EoS halt height of a particular zcashd version.

**Comment by vae520283995** [comment]
> In addition to the email reminders, you can look at https://z.cash/support/schedule/ for a timeline showing expected EoS halt dates (the right-hand end of the bar for each release).
> 
> Note that this schedule is updated manually, and therefore may not be as reliable as `getdeprecationinfo` for the purpose of finding the EoS halt height of a particular zcashd version. However it does have planned release and EoS halt dates for future releases.

Thank you for your answer, very detailed and very helpful to me, thank you

> You can check `zcash-cli getdeprecationinfo` for that information.

I'm sorry, I didn't understand what you mean

**Comment by daira** [comment]
Run `zcash-cli getdeprecationinfo` and then the "deprecationheight" entry will tell you the height that the node will shut down, if it is a mainnet node. (If you passed a `-datadir` argument to `zcashd`, also pass it to `zcash-cli`.)

The approximate date can be calculated by subtracting the current block height from that one, multiplying by 75/3600 to get the number of hours in the future, and then calculating what date that is using https://www.timecalculator.net/hours-from-now-calculator , for example.

**Comment by vae520283995** [comment]
> The approximate date can be calculated by subtracting the current block height from that one, multiplying by 75/3600 to get the number of hours in the future, and then calculating what date that is using https://www.timecalculator.net/hours-from-now-calculator , for example.

thank you
