### ISSUE TITLE
Bring over important content from zerocash-project.org to our new z.cash website.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#534]

**Comment by defuse** [comment]
We're not going to redirect the DNS.

What content exactly do we still want to bring over? Perhaps we should put it in the form of a series of blog posts?

**Comment by daira** [comment]
http://zerocash-project.org/talks_and_media seems useful still. I don't think any of the technical stuff is important to bring over.

**Comment by daira** [comment]
This ticket should be moved to the z.cash repo.

**Comment by nathan-at-least** [comment]
We decided not to do this.
