### ISSUE TITLE
Find a better name than bucket.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#539]

**Comment by daira** [comment]
@nathan-at-least wrote:
> @daira the three reasons I dislike coin:
>
> * it seems to imply a small finite set of denominations,

To me it does not. The fact that physical coins are fixed denominations is an implementation detail of physical coinage, not inherent to the concept of "coin".

In any case, how about "zeronote" as an alternative?

**Comment by ebfull** [comment]
I like calling it just Note. Good idea @daira.

Another alternative is pluralizing `Coin`.

**Comment by gojomo** [comment]
In my experience lots of people think of 'coins' as inherently being: (a) concrete realizations of abstract value; and (b) inflexible denominations that must be worked-around – giving rise to familiar 'making change' exercises. (In bitcoin, some initially believe that "one bitcoin" is the smallest unit of that system – and thus even the minimum purchase/transaction size.)

Also, now, many games use only integral-counted 'coins' as the units-of-exchange... further reinforcing the implication of indivisibility. 

'Zeronote' is interesting as a contextually-definable-term with just a hint of connotation inherited from 'note'. In the same vein: 'zerobill', 'zeroclaim', 'zeroticket', 'zerocoupon'. Each implies that actors in the system might 'write'/'issue' or 'redeem' them with varying face-values. Also, each sounds a bit like a written document (that's understood to be encryptable). 

Is there a particular example of prose/code/pseudocode, where 'bucket' is now used, that could be used as a test block for conversion to new terms? Stepping through that translation, then coming back to the resulting text after a few days to see how it 'sits', could help choose an apt name...

**Comment by daira** [comment]
I also quite like "zerobill". Thanks @gojomo .

**Comment by ebfull** [comment]
> Is there a particular example of prose/code/pseudocode, where 'bucket' is now used, that could be used as a test block for conversion to new terms? Stepping through that translation, then coming back to the resulting text after a few days to see how it 'sits', could help choose an apt name... 

Not in common parlance; it'd come up as often as you'd use UTXO in Bitcoin-land. It's pretty much just a developer thing.

**Comment by zookozcash** [comment]
Thanks a lot @gojomo! I like "note". I've started using it in user-facing (not so much developer-facing) writing. So far it sounds good! What does everyone else think?

**Comment by ebfull** [comment]
I think note is great if everyone else does. One reservation is that we generally don't want end users to be confused by terminology, and "notes" are things they should never have to interact with.

**Comment by zookozcash** [comment]
@ebfull: this shouldn't be visible to end-users at all, except for those who want to understand at a deeper level. I mentioned that here: https://forum.z.cash/t/some-usability-adoptability-suggestions/118/7?u=zooko

**Comment by ebfull** [comment]
I believe "note" was decided upon and perhaps @daira should augment the spec.

**Comment by zookozcash** [comment]
+1

**Comment by zookozcash** [comment]
Let's move this discussion to https://github.com/zcash/zips/issues/26
