### ISSUE TITLE
Add Orchard key support to `ZcashdUnified*` types

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#5394]
Up until this point, support for handling wallet-generated Orchard keys and protocol addresses has been developed separately from handling wallet-generated USKs and UAs. For this issue, we will add an Orchard type to the wallet's USK etc. types.

This is the equivalent issue to #5256 but deals with wallet-generated keys and addresses (where we know the full set of types to support), rather than user-supplied external addresses (where we need to handle arbitrary receiver types).

**Comment by nuttycom** [comment]
Closed by #5569
