### ISSUE TITLE
Update LevelDB to 1.22+

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#5407]
The target PR for this issue is https://github.com/bitcoin/bitcoin/pull/17398. There are a bunch of blocking backports we need to do before this.

**Comment by superbaud** [comment]
i'm going to try and get this done

**Comment by str4d** [comment]
@superbaud we can't yet; this is blocked on other issues and PRs:
![image](https://user-images.githubusercontent.com/4993799/168196595-01b2acf9-1ac7-45f3-896f-ea325e712dc3.png)

**Comment by superbaud** [comment]
Ah, thanks for pointing that out; i didn't see those dependencies.

**Comment by str4d** [comment]
This is somewhat blocked on commit bitcoin-core/leveldb-subtree@f545dfabff4c2e9836efed094dba99a34fbc6b88 (the commit we currently depend on, from which we need to migrate) no longer existing on the upstream repo (so `git subtree` can't find a pathway from it to the new commit). It _does_ exist on GitHub, but I have no way of finding out which fork has it. I'm hoping that I have it on one of my older laptops (as I've tried this backport in the past).

**Comment by str4d** [comment]
> I'm hoping that I have it on one of my older laptops (as I've tried this backport in the past).

Haha, yes indeed I do!
