### ISSUE TITLE
Add UA sender support to the transaction builder

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#5412]

**Comment by nuttycom** [comment]
It has occurred to me in the process of working on #5433 that the transaction builder itself doesn't need any changes for UA support for the sender; the caller will resolve the UA to individual receivers before utxo/note selection. So I think that really, this is about z_sendmany, and this ticket is superfluous except for the change-key bits.

**Comment by nuttycom** [comment]
Closing, as change address handling is also being done external to the transaction builder and is accounted for by other issues.
