### ISSUE TITLE
Move lists.zca.sh to lists.z.cash

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#543]
There are two parts:

- Move the GNU Mailman web interface.
- Change the zcash-dev list to use the lists.z.cash domain, somehow preserving the member list.

**Comment by defuse** [comment]
It'll probably take me a couple days of research and work to do this because it involves editing postfix configuration. I think if we're going to do it at all we should do it for 1.0. :)

**Comment by defuse** [comment]
@solardiz offered to put our mailing list alongside the others on Openwall:

"For further occasions, a working mailing list would be very helpful, though. If there are any issues managing it on your end, I'm willing to set it up at Openwall - we manage many mailing lists anyway."

I think this is a great offer, since it'll close this ticket and eliminate an annoying frequent devops task.

**Comment by defuse** [comment]
What does @zookozcash think of hosting our mailing list there?

**Comment by ageis** [comment]
I would suggest Riseup's mailing list service instead. https://lists.riseup.net/www/

**Comment by zookozcash** [comment]
Superceded by https://github.com/zcash/zcash/issues/1108
