### ISSUE TITLE
Decide on naming of `unifiedaddress` in new RPC outputs

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#5432]
Does this need to be `unifiedaddress` (i.e. specifically indicating it is a Unified Address), or could it just be `address` (leaving the address kind defined by the string encoding)? If the latter, then we could instead make this `defaultaddress` to convey the documented semantics.

_Originally posted by @str4d in https://github.com/zcash/zcash/pull/5300#discussion_r769133181_

**Comment by nuttycom** [comment]
:+1: to changing these to `address`.
