### ISSUE TITLE
The new version releases the docker image in real time

### ISSUE THREAD

**Issue by vae520283995** [zcash/zcash#5439]
v4.6.0 has been released for a few days, but the docker image is still not updated https://hub.docker.com/r/electriccoinco/zcashd

**Comment by steven-ecc** [comment]
We'll get it published early in the week. Sorry for the inconvenience and thanks for bringing it to our attention.

**Comment by steven-ecc** [comment]
The docker image for 4.6.0 has now been published. Thanks @charlieok!
