### ISSUE TITLE
ZIP 244: Implement changes to bring its transparent semantics closer to BIP 341

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#5446]
See https://github.com/zcash/zips/issues/574#issuecomment-1002803827

We need to:
- Change https://github.com/zcash/zcash/blob/master/qa/rpc-tests/test_framework/zip244.py to match the updated ZIP 244 (which should cause RPC tests to fail.
- Migrate to a version of the Rust crates including https://github.com/zcash/librustzcash/issues/473 (which should fix the RPC tests).

**Comment by str4d** [comment]
I just realised this is quite a bit bigger than I thought. Now that shielded signatures need to commit to transparent input values (if present), shielded signature verification can no longer occur in `ContextualCheckTransaction`, because we don't have access to the transparent inputs at that point.

I'm going to handle this issue in several stages:
- Refactor the existing consensus code to move Sapling and Orchard signature validation into `ContextualCheckInputs`.
  - We don't need to worry about Sprout because it can't occur in v5 transactions that use ZIP 244.
- Refactor `PrecomputedTransactionData` to be passed around as a reference instead of a pointer.
  - Anywhere we are computing it already, we can pass the `CTxOut`s within it (on the Rust side).
  - Anywhere we are not, we'd need to alter the `SignatureHash` call chain anyway to pass through the `CTxOut`s, and would then perform the same precomputation once we reach `SignatureHash` anyway.
- Migrate to the latest ZIP 244 version (as outlined in OP).

**Comment by nuttycom** [comment]
Fixed by #5496
