### ISSUE TITLE
Use BLAKE2 from Python's hashlib if available

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#5457]
We currently use `pyblake2` in a bunch of places in the RPC tests. However, BLAKE2 was added to Python's `hashlib` in (I think) 3.6, directly ported from `pyblake2`. So if we try the `hashlib` impl first, we can avoid in most cases a direct dependency on `pyblake2`.

**Comment by zancas** [comment]
I don't know the minimum version of Python that is supported.

**Comment by str4d** [comment]
I just had a look, and [Python 3.6 reached end-of-life in December 2021](https://endoflife.date/python). So as long as I'm correct that BLAKE2b was available from Python 3.6, we can safely drop pyblake2 instead of keeping it as a fallback.
