### ISSUE TITLE
Fix ``configure.ac`` to support zcash dependencies on platforms without ``pkg-config``.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#548]
There's a `BUG / FIXME` in [`configure.ac` L675-L676 at `e5363187`](https://github.com/bitcoin/bitcoin//blob/e53631876252fdefbd42eb3529204dd5a458e153/configure.ac#L675-L676) ([latest on branch `zc.v0.11.2.ticket480.zcash-depends-cleanup.1`](https://github.com/bitcoin/bitcoin//blob/zc.v0.11.2.ticket480.zcash-depends-cleanup.1/configure.ac#L675-L676)) which is that non-`pkg-config` platforms aren't supported for `libzerocash` transitive dependencies.

**Comment by nuttycom** [comment]
@str4d says this is fixed.
