### ISSUE TITLE
Add orchard to z_getaddressbyaccount's list of possible pools (receivers)

### ISSUE THREAD

**Issue by LarryRuane** [zcash/zcash#5499]
Currently, the `"pools"` list argument of [`z_getaddressbyaccount`](https://github.com/zcash/zcash/blob/443136c137909f786796f2914761e0b695f7a9c5/src/wallet/rpcwallet.cpp#L3054) allows only `"transparent"` (`P2PKH`) and `"sapling"`. (The help text incorrectly mentions `"orchard"`.) This set of allowable pools needs to be extended to include `"orchard"`. Also, the [default pools list](https://github.com/zcash/zcash/blob/443136c137909f786796f2914761e0b695f7a9c5/src/wallet/rpcwallet.cpp#L3115) should be extended to include `ReceiverType::Orchard` (orchard and sapling will be the best two shielded pools).

**Comment by str4d** [comment]
Closed by #5586, merged into https://github.com/zcash/zcash/tree/feature/wallet_orchard.
