### ISSUE TITLE
Update release notes to cover newly added and updated RPC methods for unified address support.

### ISSUE THREAD

**Issue by nuttycom** [zcash/zcash#5514]

**Comment by str4d** [comment]
https://github.com/zcash/zcash/commit/9e9f58b26f95ddcf938d16c28a7a3773ac0d421a#r69330039:
> This should be "emergency recovery phrase" here and below.

**Comment by daira** [comment]
> [9e9f58b#r69330039](https://github.com/zcash/zcash/commit/9e9f58b26f95ddcf938d16c28a7a3773ac0d421a#r69330039):
> 
> > This should be "emergency recovery phrase" here and below.

This didn't get fixed, but it's not necessary. The last part of the section does refer to it as an emergency recovery phrase, so it's not ambiguous what is meant.
