### ISSUE TITLE
Update the `listaddresses` RPC endpoint to correctly report unified addresses.

### ISSUE THREAD

**Issue by nuttycom** [zcash/zcash#5515]
`listaddresses` needs to be updated in the following ways:
* Should return unified addresses
* Should not return bare addresses that are components of UAs
* Should not return UA change addresses.
* At present, newly created legacy Sapling addresses that are derived from the mnemonic seed are mistakenly being reported in the "legacy_hdseed" source.
Also address the following:
* https://github.com/zcash/zcash/pull/5525#discussion_r803267234
* https://github.com/zcash/zcash/pull/5525#discussion_r803268132
* https://github.com/zcash/zcash/pull/5525#discussion_r803269302

**Comment by nuttycom** [comment]
See also the comments on https://github.com/zcash/zcash/pull/5525 for the updates that `listaddresses` will require.

**Comment by steven-ecc** [comment]
Fixed by #5681.
