### ISSUE TITLE
Alter `getnewaddress` and `getrawchangeaddress` to not use the keypool

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#5529]
We can then just remove the keypool logic for external addresses. We _might_ want to keep something like it (at least the `reserve -> keep/return` workflow) for change addresses, to handle the case where we request a new change address to use in a transaction, and then don't actually use it due to some other error (a sequence of these could cause a gap limit problem).

**Comment by nuttycom** [comment]
Note: we also discussed that `GenerateNewKey` should perform a gap-limit check (at least when generating external addresses) to avoid situations where calling `GenerateNewKey` would generate transparent addresses in a way that violates the ability of other wallets to restore from this wallet's mnemonic seed using the gap limit.

**Comment by str4d** [comment]
Closed by #5531, merged into #5419.
