### ISSUE TITLE
take control of zerocoin.org

### ISSUE THREAD

**Issue by zookoatleastauthoritycom** [zcash/zcash#557]
@defuse: Do you mind emailing Matt and asking him to give you control of zerocoin.org on behalf of ZECC?

**Comment by defuse** [comment]
@ebfull: I don't see either of the two domains in the enom account. :(

**Comment by defuse** [comment]
@ebfull: Maybe the password you lost was the one Matt Green sent you for his registrar account? :)

**Comment by ebfull** [comment]
@defuse Nope, I have that.

**Comment by imichaelmiers** [comment]
I put up the same blurb we did on the Zerocash page. I think that's all Matt,Christina, and I are comfortable doing for the moment.

**Comment by defuse** [comment]
@imichaelmiers: Ok, so the transfer @ebfull started was canceled? I'm worried about the domain getting lost in a half-completed transfer process. Can you assure me you still have the domain in your accounts and that it's not waiting on some action from our side? Thanks!

What's the status of zerocash.org? Right now it's a parking page with no content on it. @imichaelmiers do you think we should redirect it to z.cash? Doing that would help us show up in google queries for "zerocash."

**Comment by ebfull** [comment]
This is time-sensitive, the domain may expire soon and I don't know Godaddy's policies. Godaddy's interface for transferring is really bad and I was on my laptop trying to do it in SF. It indicated it was performing the transfer but I guess it wasn't?

**Comment by defuse** [comment]
I pinged @imichaelmiers on slack just now.

**Comment by imichaelmiers** [comment]
This is an issue for @matthewdgreen . I know nothing about the DNS stuff

**Comment by defuse** [comment]
Sent @matthewdgreen an email.

**Comment by matthewdgreen** [comment]
What is my assignment? I gave @ebfull all the passwords, so he should still have access. Am I just making sure it isn't expiring, or am transferring it?

**Comment by defuse** [comment]
@matthewdgreen My understanding from @imichaelmiers's comment above is that you wanted to keep control of the domain. I'm just worried since a transfer apparently was started, and was never completed, that we might lose control of the domain somehow. I guess if you see it in your account and there's nothing that mentions a transfer and it isn't going to expire soon, then everything is fine.

**Comment by defuse** [comment]
I'm assuming since the domain is still up that it's safe under @imichaelmiers or @matthewdgreen's control. Maybe we can close this issue?

**Comment by zookozcash** [comment]
Yes, close it.
