### ISSUE TITLE
Add persistence for Orchard notes and witnesses

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#5571]
- [x] After the decryption of all notes in a transaction (or block?), the note data should be persisted to the wallet database.
- [x] Spentness metadata should be persisted to the wallet database.
- [x] Witness data should be persisted to the wallet database.
- [x] When a rewind occurs, the wallet database updated as appropriate.

This combined with #5567 covers all of Orchard wallet persistence.

**Comment by nuttycom** [comment]
Closed by #5656
