### ISSUE TITLE
Set HSTS headers on z.cash

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#562]

**Comment by str4d** [comment]
@ageis Could you please check the status of this? :smiley:

**Comment by str4d** [comment]
(Assigning because I think this is an infrastructure issue. Please reassign if necessary.)

**Comment by ageis** [comment]
![zcash_ssl_grade](https://cloud.githubusercontent.com/assets/1161532/18462244/678efd20-7935-11e6-8254-e150e0c24519.png)
Done as of a couple weeks ago ;)
