### ISSUE TITLE
Ensure that `dumpwallet` / `z_exportwallet` encode HD keypath information in all derived key lines

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#5673]
We currently add HD keypath data to Sapling keys exported in `z_exportwallet` (using a comment at the end of the line). We should ensure we do the same for any transparent etc. keys we show that have been derived.

This has a nice side-effect in that the presence of transparent keys without HD keypath comments in a wallet backup file indicates that it was an existing wallet before the release that includes this issue, so we can use that to detect whether we need to tell the user in `zcashd-wallet-tool` that they need to back up the full file, not just the emergency recovery phrase.

**Comment by nuttycom** [comment]
Fixed by #5709
