### ISSUE TITLE
Replace `allowRevealedAmounts` boolean argument to `z_sendmany` with a `strategy` string argument

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#5676]
To close this issue, the `strategy` flag needs to accept the string `allowRevealedAmounts` and interpret it the same way as the existing boolean flag. We can make this change because the `allowRevealedAmounts` flag has not yet been deployed in a release.

See discussion here for motivation: https://github.com/zcash/zcash/pull/5665/files/84cd3e54d82642e2aadad02166ab14f8ec695da6#r826335592

**Comment by nuttycom** [comment]
Fixed by #5693
