### ISSUE TITLE
Alter `allowRevealedAmounts` strategy to also control whether transparent outputs are allowed

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#5677]
There's no reason to differentiate "allow amounts to be revealed like when crossing the turnstile" and "allow transparent recipients", because the latter necessarily reveals amounts, and there is no way to reveal or not reveal senders in shielded contexts.

See discussion here for motivation: https://github.com/zcash/zcash/pull/5665/files/84cd3e54d82642e2aadad02166ab14f8ec695da6#r826335592

**Comment by nuttycom** [comment]
Fixed by #5693
