### ISSUE TITLE
Add an `allowRevealedSenders` strategy to `z_sendmany`

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#5678]
This will control whether or not transparent coins may be selected in the transaction. This strategy is logically a superset of `allowRevealedAmounts`, in that if this strategy is used, then transactions may also contain transparent recipients (though the transaction builder will attempt to avoid creating transactions with both if possible).

See discussion here for motivation: https://github.com/zcash/zcash/pull/5665/files/84cd3e54d82642e2aadad02166ab14f8ec695da6#r826335592

**Comment by nuttycom** [comment]
Fixed by #5693
