### ISSUE TITLE
Rename ``full-test-suite.sh`` to ``zcash-test-runner.py`` and dispatch all buildbot test commands through it.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#571]
We want to define the "canonical" automating test suite within the repository. To do this, we introduced ``full-test-suite.sh``, This way, the buildbot config is simple and delegates the decision about what our automated test process is to zcash repository code.

However, it would be nice to get finer grained feedback from buildbot, especially the difference between "quick" tests and a full, thorough, test battery.

This ticket proposes to do that by adding commandline options to ``full-test-suite.sh``.  Since ``full-test-suite.sh --quick`` is a naming contradiction, let's rename the script to ``zcash-test-suite.sh`` or something shorter.

Let's ensure the *default* mode of operation is still the full thorough test suite, and that will still be the definition of our automated acceptance.

Finally, after adding the ``--quick`` option, update buildbot to execute tests as a distinct step and waterfall box between build and the full canonical test battery.

**Comment by nathan-at-least** [comment]
paging @arcalinea, this ticket may be relevant to buildbot changes.

**Comment by daira** [comment]
@defuse will close this if we no longer need it.

**Comment by defuse** [comment]
We don't need this anymore, the only thing in full-test-suite.sh now is ensure-no-dot-so-in-depends.py as well as make check. The other tests are already split out on Buildbot into different waterfall columns.
