### ISSUE TITLE
Bug in witness caching

### ISSUE THREAD

**Issue by daira** [zcash/zcash#5777]
The wallet normally will only flush changes to witness data to disk at 10-minute intervals (`WITNESS_WRITE_INTERVAL`) or after 10000 updates (`WITNESS_WRITE_UPDATES`). This meant that in our automated tests that shut down and restart a node, the node would always have to rescan for notes received in the test, and so we had no test coverage for the case where the witnesses actually had been flushed.

This meant that we missed a bug in the Orchard wallet; @str4d to fill in further details.

**Comment by str4d** [comment]
Closed by #5779, merged into #5741.
