### ISSUE TITLE
UA assertion on address existing is too strong

### ISSUE THREAD

**Issue by ebfull** [zcash/zcash#5827]
```c++
        if (!isInternal) {
            auto ua = pwalletMain->FindUnifiedAddressByReceiver(entry.GetAddress());
            assert(ua.has_value());
            obj.pushKV("address", keyIO.EncodePaymentAddress(ua.value()));
        }
```

I rolled back to an older version of my wallet file, which seems like a reasonable thing to allow users to do, and then my wallet scanned and recognized some notes for an address I had created which was not in the rolled-back wallet file. I then did `z_listunspent` and ran into the assertion above. This seems unnecessary; we could substitute this with "<unknown>" or something rather than crashing the whole node.

**Comment by nuttycom** [comment]
Closed by #5833
