### ISSUE TITLE
Fix Orchard tree state format in `z_gettreestate`

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#5848]
#5560 added Orchard tree support to `z_gettreestate`. It did so by using the serialization format of `OrchardMerkleFrontier`, and writing that into the `finalState` field of the `orchard` object. However, this creates an inconsistent API:

- `finalState` in the `sprout` and `sapling` objects serializes an `IncrementalMerkleTree` object, which writes the format `(Option<left>, Option<right>, Vec<Option<ommers>>)` (equivalent to `zcash_primitives::merkle_tree::CommitmentTree::write`).
- `finalState` in the `orchard` object serializes using `zcash_primitives::merkle_tree::incremental::write_frontier_v1`, which writes the format `Option<(position, left, Option<right>, Vec<ommers>)>`.

This has already caused confusion: the `zebrad` developers are currently trying to figure out how to adapt `incrementalmerkletree`'s `Frontier` type to produce a `CommitmentTree` type for serialization, while we are silently altering the type of `finalState`.

We should either:
- Fix `['orchard']['finalState']` to use the sparse format.
- Use a different key to represent the dense format, and document the difference in the RPC help text.

**Comment by str4d** [comment]
Note that the sparse and dense formats are equivalent for our purposes: they can encode the same information, and you can transform valid encodings from one format to the other. The way to think about it, is that the pattern of `Some` vs `None` in `Vec<Option<ommers>>` in the sparse format encodes the `position` field of the dense format (with some twiddling). The dense format is a bit nicer overall because the sparse format can also encode invalid tree states more easily (e.g. a `None` left with `Some` right should never happen, and cannot be represented in the dense format).

**Comment by str4d** [comment]
Overnight it occurred to me that another option would be to have a `finalState` integer parameter, that specifies the format that `finalState` should use: the default 0 is the original sparse format, and 1 means `frontier_v1` as defined in `zcash_primitives`. That would likely be the most convenient, as it would avoid the need to serialize both forms in every RPC output.

**Comment by str4d** [comment]
We've decided that for 4.7.0 we will fix the Orchard output to use the sparse format like Sprout and Sapling, and then for 5.0.0 we will add a the above `finalState` parameter to enable dense format (#5850).

**Comment by nuttycom** [comment]
Fixed by #5852
