### ISSUE TITLE
Add link to z.cash in upstream's libzerocash

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#588]
The upstream libzerocash repository is another "thing that people wanting zerocash remember." We should add a link there, and in our clone, to z.cash.

**Comment by defuse** [comment]
Hey @madars: I think it's important for people to be able to find the latest version of libzerocash. Right now the upstream one shows up in google first, so people will find the older code of they go looking. What do you think we should do to fix that? We could delete it altogether, add a link to the new one (and z.cash), etc.

**Comment by defuse** [comment]
I don't think we should delete it since some people might have it bookmarked (and all of its google-credit would be lost).

**Comment by daira** [comment]
I think we should delete https://github.com/Electric-Coin-Company/libzerocash or make it private.

**Comment by daira** [comment]
I think @madars got unassigned accidentally due to the org change.

**Comment by nathan-at-least** [comment]
We've evolved away from `libzerocash` substantially. I expect people searching for 'zerocash' or anything similar will find us, so I'm closing this as not-relevant.
