### ISSUE TITLE
Bug: invalid filter directive message when running zcashd-wallet-tool

### ISSUE THREAD

**Issue by steven-ecc** [zcash/zcash#5887]
When running `zcashd-wallet-tool`, I always get this "ignoring..." message. I have no log filters set.

```
ignoring ``: invalid filter directive
To reduce the risk of loss of funds, we're going to confirm that the
zcashd wallet is backed up reliably.
```

**Comment by daira** [comment]
Do you have the `RUST_LOG` environment variable set (including to an empty string)?

**Comment by steven-ecc** [comment]
RUST_LOG is not set and I don't recall ever using it directly for anything. I believe @nuttycom also was able to reproduce this issue. You won't see it apparently if you have a logfilter specified in your zcash.conf.
