### ISSUE TITLE
Document the block time in the `z_gettreestate` RPC response

### ISSUE THREAD

**Issue by upbqdn** [zcash/zcash#5913]
### Describe the issue

The function [z_gettreestate](https://github.com/zcash/zcash/blob/master/src/rpc/blockchain.cpp#L1225) doesn't mention the block time in its docs, even though the function returns it ([here](https://github.com/zcash/zcash/blob/master/src/rpc/blockchain.cpp#L1286)). The block time is then also not rendered in the public  [docs](https://zcash.github.io/rpc/z_gettreestate.html).

`lightwalletd` also expects the block time field [here](https://github.com/zcash/lightwalletd/blob/68789356fb1a75f62735a529b38389ef08ea7582/common/common.go#L108).

**Comment by upbqdn** [comment]
It seems like a quick fix, should I submit a PR?

**Comment by steven-ecc** [comment]
@upbqdn A PR would be great! Thanks!
