### ISSUE TITLE
Will the v4 transaction format be rejected in the future?

### ISSUE THREAD

**Issue by vae520283995** [zcash/zcash#5968]
As an exchange or wallet provider in NU5 network upgrade, do we just need to update the node to v5.0.0 and change CONSENSUS_BRANCH_ID to 0xc2d6d0b4?
Do we need to modify the transaction format from v4 to v5? 
Will the v4 transaction format be rejected in the future?

**Comment by vae520283995** [comment]
@daira please help

**Comment by vae520283995** [comment]
> An exchange or wallet provider will need to (and should have already) updated to v5.0.0 before NU5 activation. However, it is not necessary to immediately modify your software to create v5 transactions; v4 transactions will remain valid on the network and we have no immediate plans for their deprecation. In the future, v4 transaction deprecation will follow the [deprecation process](https://zcash.github.io/zcash/user/deprecation.html), so you will have plenty of time to adapt your systems.
> 
> If you have software independent of Zcashd that is used to parse v5 transaction data or compute transaction IDs, that software will need to be updated for NU5 activation or it will fail to recognize v5 transactions.

okay, thank you

**Comment by daira** [comment]
> In the future, v4 transaction deprecation will follow the [deprecation process](https://zcash.github.io/zcash/user/deprecation.html), so you will have plenty of time to adapt your systems.

To be more precise, removal of v4 is likely to happen at a network upgrade (and probably not using the deprecation mechanism described at that link). The changes to be made in network upgrades are always planned and communicated well in advance.
