### ISSUE TITLE
Wallet export/import fails to retain Orchard addresses.

### ISSUE THREAD

**Issue by benjamin203** [zcash/zcash#5999]
### Describe the issue
The wallet export/import feature of zcash-cli fails to retain Orchard addresses.

### Can you reliably reproduce the issue?
Yes.
1. Create new zcashd wallet
     ` Run zcashd after deleting wallet.dat file in .zcash folder`
3. Create an orchard address
	`zcash-cli z_getnewaccount`
	`zcash-cli z_getaddressforaccount 0 '["orchard"]'`
4. Take note of this orchard address
5. Export wallet
	`zcash-cli z_exportwallet mywallet`
6. Stop zcashd
5. Delete the zcashd wallet
   `   Delete the wallet.dat file in .zcash folder`
7. Start zcashd
8. Import wallet file
	`zcash-cli z_importwallet path/to/file`
9. List addresses
	`zcash-cli listaddresses`

### Expected behaviour
The user should see the orchard address from their old wallet in their new wallet's list of addresses.

### Actual behaviour + errors
The orchard address does not appear.
Instead, a sapling address will appear in the legacy_hdseed category.

### The version of Zcash you were using:
v5.0.0

### Any extra information that might be useful in the debugging process.
If I repeat the same process for a unified address containing a sapling address, the sapling address is successfully recovered as a non-unified address.

The wallet export file should ideally contain the unified address spending keys instead of splitting the unified addresses into their component address types.

After exporting the wallet containing the orchard address, the exported wallet file contains a string in the following format under the Sapling Keys section:

`secret-extended-key-main1qd34plljqqqqpqx7vdzwp0lfjs4c55eymhaem2pm6afcjj3xzwmflda0gete5gxumqjrnnqketgn0dnuh4k56pusqvyhhvkavdm0praetvvg6rsfxseszmr0kg8tkktuwlutdndsvkfzrwevud7wth444df6llfwft3tkkcxkmmdsez075a3sv6hc9kjd6huz44sw6pxc2v7rrhpn9kcjzwvef9jarwvdpxuzre7qx3f82m0flzhcq4mluxw5m74zd72f57jxrdsf8s3ufdxh 2022-06-06T07:00:00Z m/32'/133'/0' 957f6dcbf6e30f45d8e3db9afe3d8e5fd1e9cc38f1c1822cedf8e37497fd74e3 # zaddr=zs1pdp06pt5eu0kkswrzp5pvpyv70tjgr6ldgt94fh533dnlzpcfvjgztdg7nq7kg3apjpykmpgtuk`

**Comment by str4d** [comment]
That wallet-importing API will likely never work properly for accounts. A wallet can only have a single mnemonic phrase associated with it, to which the accounts correspond. `z_importwallet` tries to import keys into an existing wallet, so it will never overwrite the existing mnemonic. We could in theory export the Orchard spending keys, but correlating them into their matching UFVKs becomes tricky.

The two issues we would need to decide on and resolve before making any progress on this issue, are #5796 (which we will definitely do, it's just a matter of figuring out a not-terrible UX), and #5937 (we wouldn't do this issue if we didn't do that one).
