### ISSUE TITLE
Plan security audits.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#6]
Let's organize a security audit focused on the delta from upstream bitcoin-core.  Ideally this would be performed by an independent third party auditor.

I recommend focusing on the delta rather than bitcoin-core on the assumption that bitcoin-core has many eyes on it.  (However, this might be a catastrophically dangerous assumption, and if we have extra time/resources we should also scrutinize bitcoin-core.)

**Comment by defuse** [comment]
We should find competent bitcoin/security people for doing the external audit soon, I think.

We could also have bug bounty so that the entire community has some incentive to look at our code.

**Comment by daira** [comment]
We should have done this, like, last month. Waiting until the security freeze is far too late.

**Comment by matthewdgreen** [comment]
Who is doing the audits?

**Comment by defuse** [comment]
I'm tracking this in zecc-private.
