### ISSUE TITLE
zeromq dependency fails to build on macOS Ventura

### ISSUE THREAD

**Issue by rex4539** [zcash/zcash#6006]
### Machine specs:
- OS name + version: `macOS 13.0 (22A5266r)`
- CPU: `2,6 GHz 6-Core Intel Core i7`
- RAM: `16 GB 2400 MHz DDR4`
- Disk size: `256GB`
- Disk Type (HD/SDD): `SSD`
- Linux kernel version (uname -a): `Darwin Kernel Version 22.0.0: Tue May 24 20:31:35 PDT 2022; root:xnu-8792.0.50.111.3~5/RELEASE_X86_64 x86_64`
- Compiler version (gcc --version): Apple clang version 14.0.0 (clang-1400.0.17.3.1)
- Linker version (ld -v): `@(#)PROGRAM:ld  PROJECT:ld64-816
BUILD 18:17:20 May 22 2022
configured to support archs: armv6 armv7 armv7s arm64 arm64e arm64_32 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em
LTO support using: LLVM version 14.0.0, (clang-1400.0.17.3.1) (static support for 29, runtime is 29)
TAPI support using: Apple TAPI version 14.0.0 (tapi-1400.0.9)`
- Assembler version (as --version): `Apple clang version 14.0.0 (clang-1400.0.17.3.1)`

```
src/tcp_address.cpp:132:12: error: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Werror,-Wdeprecated-declarations]
    pos += sprintf (pos, "%d", ntohs (port_));
           ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:214:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                      ^
1 error generated.
make[1]: *** [src/libzmq_la-tcp_address.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
src/udp_engine.cpp:371:7: error: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Werror,-Wdeprecated-declarations]
      sprintf (port, "%d", static_cast<int> (ntohs (addr_->sin_port)));
      ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:214:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                      ^
1 error generated.
make[1]: *** [src/libzmq_la-udp_engine.lo] Error 1
make: *** [/Users/rex/zcash/depends/work/build/x86_64-apple-darwin22.0.0/zeromq/4.3.4-1fa97bb96a3/./.stamp_built] Error 2
```

**Comment by rex4539** [comment]
I fixed it locally but the patch is somewhat complicated because the affected files are not part of this repo and are downloaded/compiled during build.

On `depends/work/build/x86_64-apple-darwin22.0.0/zeromq/4.3.4-1fa97bb96a3/src/tcp_address.cpp` line 132 needs to be changed to:
```
pos += snprintf (pos, sizeof(pos), "%d", ntohs (port_));
```

On `depends/work/build/x86_64-apple-darwin22.0.0/zeromq/4.3.4-1fa97bb96a3/src/udp_engine.cpp` line 371 needs to be changed to:
```
snprintf (port, sizeof(port), "%d", static_cast<int> (ntohs (addr_->sin_port)));
```

Someone please create a patch that is applied during the zeromq dependency compilation.

I used to know how to do this but my hacking skills have deteriorated since I don't exercise them anymore :)

**Comment by furzik** [comment]
Thanks! That fixed it for me. I'll attempt to create a patch for this and post for the zeromq community to review
