### ISSUE TITLE
Rename code around addresses, keys, notes, nullifiers, encryption/decryption, and spend authority.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#602]
Change type/variable names in code to match the following naming conventions (which were cut'n'pasted from #324, a ticket which mixed together multiple issues):

# Dev terminology

Let's begin distinguishing these three items:

* `bcaddr` and `bckey` for upstream "cleartext' Bitcoin address/key pairs.
* `zc-spend-authority address / key` for the second category. (It's unwieldy and only needs to be used in specialized topics.)
* `zc-transmission address / key` for the third category. (Also unwieldy and specialized.)
* `zcaddr` and `zckey` for the *combined* spend-and-transmit values.

So for example, at some layer of abstraction, the parameters to construct a Pour are `zcaddr` and `zckey` types, rather than the more distinct keys used behind that abstraction.

**Comment by daira** [comment]
This should also reflect the terminology changes decided on in https://github.com/zcash/zips/issues/26 .

**Comment by ebfull** [comment]
Moved the milestone on this since it has a lot to do with other work daira is doing.

**Comment by ebfull** [comment]
Darn! I've been working on this without realizing it's part of the next milestone, since it was assigned to me. I'll just move it to this milestone and submit a PR soon.
