### ISSUE TITLE
Decide on anchor-selection design alternatives.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#604]
The prover must choose an "anchor", our name for a commitment merkle tree's root.  This is a primary zkSNARK input for verifiers (eg: a public value on the block chain), and therefore the choice among alternatives reveals something to any blockchain observer.

There are several layers of protocol design and wallet design with inter-related trade-offs to consider:

a. Fundamentally, the protocol needs to specify which possible tree states are valid and how they are computed for each valid transaction.  Note that transactions are validated as they enter the mempool prior to becoming mined into blocks.
b. Next, even if it's *possible* to practically track multiple tree states, we may want to restrict the consensus protocol to only allow some options. For example, we may say there's one tree state per block *or* we may say there's only 1 valid tree state for every N blocks, and the last valid tree state is at height ``floor( block_height / N ) * N``.  This makes the possible options more coarse and improves the anonymity properties, while *degrading* latency, thus usability (since a confidential coin can't be spent until there's a valid tree state to refer to in its spending Pour).
c. Even if we allow flexibility in the consensus protocol so that clients may choose, we may want to define a "standardized" policy so that wallets made by different implementers gather around a "schelling point anchor" when privacy is desired.
d. Individual wallets may want to support users who desire low-latency or they may want to support high-privacy, or they may want a per-transaction knob, etc...

Related to this is the notion that when a block is getting "kicked out" due to a reorg (because there's a new longer chain which excludes the block), then any Pours anchored in that block's commitment root become invalid.  This is quite similar to transactions becoming invalid if any of their inputs point to transactions which have become invalid.  A difference, however, is that (barring all other issues such as consistency) a Pour's privacy is improved by referring to a more recent anchor, *even when* it is spending a coin that is very old.  This desire for a recent anchor for privacy contends with a desire to select an anchor old enough to prevent ejection during reorgs, and again different wallets/users may have different preferences.

Finally, these choices impact scalability and other protocol considerations.  For example, if anchors are restricted to being updated only every N blocks, then there's 1/N cost to maintaining a map of all anchors or having SPV protocols about anchors, etc...  (In person, @ebfull, @zookoatleastauthoritycom, and I explored ideas like logarithmic-combs of valid anchors so that all ancient coins are grouped into a large subtree, but recent coins are grouped into a small subtree, and this might have some scalability advantages.)

This [review comment](https://github.com/Electric-Coin-Company/zcash/commit/bf748a8f3d80677dbd11a45bec17f7d40675ed80#commitcomment-15438530) stimulated me to open this ticket.

**Comment by daira** [comment]
There was one remaining issue I wasn't sure of:

(2016-01-27 10:48:44) daira1: sbowe: I can't remember what we decided re: what anchors in a chained-Pour transaction can refer to
(2016-01-27 10:50:11) daira1: the current protocol spec says that Pours after the first can refer to the final treestate of an earlier block, or the output treestate of the immediately preceding Pour
(2016-01-27 10:51:28) daira1: the alternative is that they can refer to the final treestate of an earlier block, or the output treestate of an earlier Pour in that transaction
(2016-01-27 10:54:35) daira1: (the latter rule is slightly simpler because it's not necessary to treat the first Pour in a transaction as a special case -- you can just say...
(2016-01-27 10:56:32) daira1: "or the output treestate of an earlier Pour in that transaction, if there is one". But it adds degrees of freedom in constructing a transaction, which could split the anonymity set, if say, some clients always follow the stricter rule)

**Comment by ebfull** [comment]
At the end of every `CPourTx` anchor check, the treestate is added to a set that *future* pours can anchor to.

> daira: the alternative is that they can refer to the final treestate of an earlier block, or the output treestate of an earlier Pour in that transaction

I agree with this and is what should have been in the PDF.

I don't know what to think about partitioning the anonymity set with features like this. I think we need more rigorous analysis, considering users can partition the set with our *existing* scheme in myriad ways. It would be at least nice to keep a list (perhaps in the protocol document) of the places where wallets can screw up, and perhaps we can bat those down one by one?

**Comment by daira** [comment]
I will modify the protocol spec to allow the looser alternative for the time being. Analysis of that should go on #93.

**Comment by daira** [comment]
I removed "engineering meeting agenda" because the relevant ticket is actually #93.

**Comment by ebfull** [comment]
Thanks!

**Comment by daira** [comment]
@nathan-at-least wrote:
> In person, @ebfull, @zookoatleastauthoritycom, and I explored ideas like logarithmic-combs of valid anchors so that all ancient notes are grouped into a large subtree, but recent notes are grouped into a small subtree, and this might have some scalability advantages.

Incidentally this sounds similar to #43.
