### ISSUE TITLE
Add ``--debug=libsnark-profiling`` option.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#605]
Here's the runtime config of libsnark profiling in my latest review (public alpha branch) that can be the starting point: https://github.com/Electric-Coin-Company/zcash/commit/4200e0d3d373a8c034bab641732d54b57c606a5d#commitcomment-15441534

**Comment by nathan-at-least** [comment]
@ebfull says this is dangerous without modifying libsnark to remove race conditions with this flag enabled. Are we sure we need this?

**Comment by nathan-at-least** [comment]
I'm going to close this as wontfix. If it turns out we actually need this, it can be revived.

**Comment by daira** [comment]
I believe it would be trivial to fix the race conditions. OTOH, we don't strictly need it; it's useful to guide optimization of libsnark but that's all.

**Comment by daira** [comment]
I'm not really sure why this was closed; it's a valid desire to want to profile libsnark as it is used from zcashd.

**Comment by nathan-at-least** [comment]
Do #1516 then this or with this.

**Comment by rex4539** [comment]
Now that libsnark is gone, I guess this one can be closed?

**Comment by daira** [comment]
Yes.
