### ISSUE TITLE
Scriptable JoinSplit outputs

### ISSUE THREAD

**Issue by ebfull** [zcash/zcash#608]
We could place a CScript commitment in our "pour outputs" such that the spender must satisfy it. The script would become public at the point of send, but it would allow us to create cool constraints -- perhaps even timelocked funds (#344) or something else.

It might make sense to integrate this with our cryptographic binding scripts into a single system.

**Comment by nathan-at-least** [comment]
In a conversation @daira and I realized we don't understand how this would work. The transaction creator can already put standard ``scriptPubKey`` constraints on all of the ``TxOut`` values. What does it mean to have a condition on a ``vpub_out``? That's internal to a transaction.

**Comment by ebfull** [comment]
I may want to send money to someone contingent not only on them having the zcash private key, but also satisfying a `CScript`. The bucket will contain not only `v` but also a hash of the script they must satisfy, and the spender would need to know that script and provide it alongside a script which satisfies it.

This is just a way of crafting `scriptPubKey` and `scriptSig` onto our pours (but without confidentiality guarantees). As an example, right now you can't do zero-knowledge contingent payments without using cleartext transactions.

**Comment by ebfull** [comment]
There may be a tricky way to implement this without a circuit change, and it might even be possible in a softfork. I would encourage a "maybe in 1.0" until I've taken some time to consider it.

**Comment by zookozcash** [comment]
Isn't this an older variant of p2vk?

**Comment by str4d** [comment]
This is roughly the same as my "shielded WTP" idea: transparent predicates for shielded transactions.

**Comment by nuttycom** [comment]
Such updates are no longer relevant for Sprout, and if we want to do something on a new proving system then we'll open a ticket for that at that time.
