### ISSUE TITLE
UX: How to import my z_adress ?

### ISSUE THREAD

**Issue by yangchou19** [zcash/zcash#6110]
## What were you trying to do
I just want to import my z_address, but i am not sure the possess is right.Can anyone tell me how to do it?

## What happened
when I use the command "zcash-cli z_importkey "，it reported the problem:
![image](https://user-images.githubusercontent.com/49429748/183108842-b982a7d6-339d-469f-9f66-8a342e34f5a8.png)
 But I have started my zcashd.

**Comment by docblocxxx** [comment]
```
Arguments:
1. "zkey" (string, required) The zkey (see z_exportkey)
2. rescan (string, optional, default="whenkeyisnew") Rescan the wallet for transactions - can be "yes", "no" or "whenkeyisnew"
3. startHeight (numeric, optional, default=0) Block height to start rescan from
```


Rescan starts, which consumes resources, and requests to RPC just *fall off* until the rescan is completely completed.

you can track it
tail -n 10 debug.log
or showmetrics=1 in config or -showmetrics

I recommend that you wait for the process to finish completely, unexpected stop, is not very good.

**Comment by yangchou19** [comment]
> ```
> Arguments:
> 1. "zkey" (string, required) The zkey (see z_exportkey)
> 2. rescan (string, optional, default="whenkeyisnew") Rescan the wallet for transactions - can be "yes", "no" or "whenkeyisnew"
> 3. startHeight (numeric, optional, default=0) Block height to start rescan from
> ```
> 
> Rescan starts, which consumes resources, and requests to RPC just _fall off_ until the rescan is completely completed.
> 
> you can track it tail -n 10 debug.log or showmetrics=1 in config or -showmetrics
> 
> I recommend that you wait for the process to finish completely, unexpected stop, is not very good.

Thank you for your advice!!! I have solved this problem.

**Comment by nuttycom** [comment]
Closing per https://github.com/zcash/zcash/issues/6110#issuecomment-1209461032
