### ISSUE TITLE
Get Unified Address Balance

### ISSUE THREAD

**Issue by iha4** [zcash/zcash#6113]
## Is your feature request related to a problem? Please describe.

When trying to send funds using z_sendmany, the user needs to choose an address to send from and an amount to send.

To do this, they need to know the balances of their addresses.

It is currently not possible to display the balance of a unified address or all unified addresses.

## Describe the solution you'd like
A new rpc command called listmyaddressbalances should be created to display the balances of all wallet addresses, and getmyaddressbalance to get the balance of an individual address.

Both of these new commands can contain a minconf argument similar to z_getbalanceforaccount.

## Alternatives you've considered
z_getbalance is deprecated, and only displays balances for transparent addresses. For unified addresses, it displays the balance of the account that the address belongs to, rather than displaying the balance of the address itself.

**Comment by nuttycom** [comment]
Just to clarify, when using `z_sendmany` *any* unified address associated with a given account will allow access to all of the funds associated with that account. I will update the documentation of `z_sendmany` to make this clear.

**Comment by nuttycom** [comment]
Superseded by #6124

**Comment by nuttycom** [comment]
Opened #6125 to fix the docs.
