### ISSUE TITLE
Out-of-memory when downloading blockchain

### ISSUE THREAD

**Issue by wallart1** [zcash/zcash#6148]
Please provide a general summary of the issue you're experiencing
I am having problems during the initial download of the blockchain. 

Current, I am getting a repeatable out-of-memory condition. The zcash terminal looks like this: 

```
Thank you for running a mainnet zcashd v5.2.0 node!
You're helping to strengthen the network and contributing to a social good :)

In order to ensure you are adequately protecting your privacy when using Zcash,
please see <https://z.cash/support/security/>.

     Downloading blocks | 35630 (1728892 headers) / ~1798510 (1%)
                        | [                                                  ]
           Next upgrade | Overwinter at block height 347500, in around 541 days
            Connections | 8
  Network solution rate | 52.036 MSol/s


Since starting this node 51 minutes, 25 seconds ago:
- You have validated 9434993 transactions!

[Press Ctrl+C to exit] [Set 'showmetrics=0' to hide]
./startzcash: line 10:  3845 Killed                  sudo zcashd -reindex -rescan -conf=/data/zcash/zcash.conf -datadir=/data/zcash/ -paramsdir=/data/zcash/ -idbskiptxverification=1 -txindex=1 -maxconnections=50 -txconfirmtarget=2
dan@bullwinkle:~$ 
```
The debug log doesn't show anything. It's going along swimmingly, then it simply ends.

Dmesg ends with this: 
`oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/user@1000.service,task=zcashd,pid=3846,uid=0
[ 9513.108619] Out of memory: Killed process 3846 (zcashd) total-vm:9516984kB, anon-rss:7028060kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:15720kB oom_score_adj:0`

I am also noticing slowly increasing use of swap space. But it doesn't fill up -- only about 35% of 2GB. Normally the percentage is low single digits. 

I am doing this on the same VM as a couple of other crypto full nodes. They are stable and do not put very much load on the system. I have 8GB memory allocated to the VM. I just today installed additional memory and am thinking about shutting down the VM and allocating some of that new memory to it. 

So, two questions: 1) Does zcashd normally require a lot of memory? 2) If so, how much do I need? 

#### If so, please list the steps to reproduce below:
1. Run zcashd in an 8GB VM.
2. Wait awhile.
3. 

### Expected behaviour
It should finish the blockchain download and continue with whatever it does next. (I'm curious to see, as I haven't been able to complete the download.)

### Actual behaviour + errors
See above.

### The version of Zcash you were using:
`Thank you for running a mainnet zcashd v5.2.0 node!`

### Machine specs:
Here is Linux Mint's System Information output. I imagine this will answer the question: 
```
System:    Kernel: 5.4.0-125-generic x86_64 bits: 64 compiler: gcc v: 9.4.0 
           Desktop: Cinnamon 5.2.7 wm: muffin dm: LightDM Distro: Linux Mint 20.3 Una 
           base: Ubuntu 20.04 focal 
Machine:   Type: Kvm System: QEMU product: Standard PC (i440FX + PIIX, 1996) v: pc-i440fx-6.2 
           serial: <filter> Chassis: type: 1 v: pc-i440fx-6.2 serial: <filter> 
           Mobo: N/A model: N/A serial: N/A BIOS: SeaBIOS 
           v: rel-1.15.0-0-g2dd4b9b3f840-prebuilt.qemu.org date: 04/01/2014 
CPU:       Topology: Quad Core model: Common KVM bits: 64 type: MCP arch: Netburst Presler rev: 1 
           L2 cache: 16.0 MiB 
           flags: lm nx pae sse sse2 sse3 bogomips: 26419 
           Speed: 3302 MHz min/max: N/A Core speeds (MHz): 1: 3302 2: 3302 3: 3302 4: 3302 
Graphics:  Device-1: Red Hat Virtio GPU driver: virtio-pci v: 1 bus ID: 00:02.0 chip ID: 1af4:1050 
           Display: x11 server: X.Org 1.20.13 driver: modesetting unloaded: fbdev,vesa 
           resolution: 1920x1080~60Hz 
           OpenGL: renderer: virgl v: 4.3 Mesa 21.2.6 compat-v: 3.1 direct render: Yes 
Audio:     Message: No Device data found. 
Network:   Device-1: Intel 82371AB/EB/MB PIIX4 ACPI vendor: Red Hat Qemu virtual machine 
           type: network bridge driver: piix4_smbus v: N/A port: e100 bus ID: 00:01.3 
           chip ID: 8086:7113 
           Device-2: Red Hat Virtio network driver: virtio-pci v: 1 port: e120 bus ID: 00:12.0 
           chip ID: 1af4:1000 
           IF: ens18 state: up speed: -1 duplex: unknown mac: <filter> 
Drives:    Local Storage: total: 1.89 TiB used: 692.93 GiB (35.8%) 
           ID-1: /dev/sda vendor: QEMU model: HARDDISK size: 75.00 GiB speed: <unknown> 
           serial: <filter> 
           ID-2: /dev/sdb vendor: QEMU model: HARDDISK size: 1.82 TiB speed: <unknown> 
           serial: <filter> 
Partition: ID-1: / size: 72.78 GiB used: 18.60 GiB (25.6%) fs: ext4 dev: /dev/sda5 
USB:       Hub: 1-0:1 info: Full speed (or root) Hub ports: 2 rev: 1.1 chip ID: 1d6b:0001 
           Device-1: 1-1:2 info: Adomax QEMU USB Tablet type: HID driver: hid-generic,usbhid 
           rev: 2.0 chip ID: 0627:0001 
           Hub: 2-0:1 info: Full speed (or root) Hub ports: 4 rev: 2.0 chip ID: 1d6b:0002 
           Hub: 3-0:1 info: Full speed (or root) Hub ports: 4 rev: 3.0 chip ID: 1d6b:0003 
Sensors:   Message: No sensors data was found. Is sensors configured? 
Repos:     No active apt repos in: /etc/apt/sources.list 
           Active apt repos in: /etc/apt/sources.list.d/brave-browser-release.list 
           1: deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https: //brave-browser-apt-release.s3.brave.com/ stable main
           Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
           1: deb http: //packages.linuxmint.com una main upstream import backport #id:linuxmint_main
           2: deb http: //archive.ubuntu.com/ubuntu focal main restricted universe multiverse
           3: deb http: //archive.ubuntu.com/ubuntu focal-updates main restricted universe multiverse
           4: deb http: //archive.ubuntu.com/ubuntu focal-backports main restricted universe multiverse
           5: deb http: //security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
           6: deb http: //archive.canonical.com/ubuntu/ focal partner
           Active apt repos in: /etc/apt/sources.list.d/tor.list 
           1: deb [arch=amd64 signed-by=/usr/share/keyrings/tor-archive-keyring.gpg] https: //deb.torproject.org/torproject.org focal main
           2: deb-src [arch=amd64 signed-by=/usr/share/keyrings/tor-archive-keyring.gpg] https: //deb.torproject.org/torproject.org focal main
           Active apt repos in: /etc/apt/sources.list.d/zcash.list 
           1: deb [arch=amd64] https: //apt.z.cash/ bullseye main
Info:      Processes: 243 Uptime: 5h 02m Memory: 7.77 GiB used: 2.57 GiB (33.0%) Init: systemd 
           v: 245 runlevel: 5 Compilers: gcc: 9.4.0 alt: 9 Client: Unknown python3.8 client 
           inxi: 3.0.38 
```

### Any extra information that might be useful in the debugging process.
To install zcashd, I followed these instructions:
[https://zcash.readthedocs.io/en/latest/rtd_pages/install_debian_bin_packages.html]

### Do you have a backup of `~/.zcash` directory and/or take a VM snapshot?
- Backing up / making a copy of the `~/.zcash` directory might help make the
  problem reproducible. Please redact appropriately.
- Taking a VM snapshot is really helpful for interactively testing fixes

**Comment by wallart1** [comment]
Attached is the entire message group from dmesg.
[zcash-oom-dmesg.txt](https://github.com/zcash/zcash/files/9491995/zcash-oom-dmesg.txt)

**Comment by daira** [comment]
Did you create any shielded addresses in the wallet of this node?

**Comment by wallart1** [comment]
No. It's a brand new install. I was still waiting for the blockchain to download before I did anything with it. For the time being, I'm planning to just run a full node to help out the zcash network.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by str4d** [comment]
#6172 makes significant reductions to memory consumption of wallet scanning. It shouldn't in theory affect this issue because no shielded addresses had been created for this wallet, but it would be useful to know if it does actually fix the problem here.

**Comment by daira** [comment]
If after the 5.3.1 release you still see a problem, please file a new issue.
