### ISSUE TITLE
Load zk-SNARK parameters after logging initialization

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#620]
We discovered a startup race condition in an earlier revision of the public alpha branch, issue and fix described in https://github.com/Electric-Coin-Company/zcash/commit/efe0c9d9737ad24d802e41ff8cbaab3eaaac7482#commitcomment-15432901

However, the current implementation, while avoiding that race condition, also loads the parameters before logging has been initialized, so the UX is that the process appears to hang for a long time (~40s on my machine) even if they have debug turned to a high verbosity.

So, it would be nice to load the parameters after debug logging is initialized _iff_ that can avoid the other startup race.

**Comment by daira** [comment]
The parameters take much less time to load now, but this issue still exists I think.

**Comment by nathan-at-least** [comment]
This may no longer be relevant, similar to #432.

**Comment by daira** [comment]
It's definitely no longer relevant.
