### ISSUE TITLE
Renew the SSL certificates (Before October 2016)

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#623]
Let's encrypt certs are only ~3months or so. We have to periodically run the command that renews them.

**Comment by defuse** [comment]
If I do #543 first then it'll be easy to buy 2-year digicert certs instead of having to renew letsencrypt certs every 3 months.

**Comment by defuse** [comment]
Actually we still need certs for `lists.zca.sh` so that people with `https://` URLs get redirected.

**Comment by defuse** [comment]
Let's Encrypt switched to a thing called "certbot": https://letsencrypt.org/getting-started/

**Comment by defuse** [comment]
Just run this to renew the certs (as root):

```
cd /root/letsencrypt/
./certbot-auto renew
```

**Comment by defuse** [comment]
Adding the engineering meeting agenda label because this needs to be done around the time I leave, and I may be more focused on other things at that time.

**Comment by defuse** [comment]
(Also, the milestone needs to be updated, it's still in one of our old timebox milestones)

**Comment by defuse** [comment]
For the new servers, I've been getting two-year certs from DigiCert instead of Let's Encrypt. It costs money, but it saves us from having to log in and renew the certs every 3 months. The z.cash cert and zca.sh certs still use Let's Encrypt, so this still needs to happen.

**Comment by defuse** [comment]
@nathan-at-least: This needs to be done before August 14, but it's in a milestone due September 7.

**Comment by daira** [comment]
The only thing that depends on zca.sh is the zcash-dev mailing list, which we are proposing to shut down (#1108), is that right?

**Comment by ebfull** [comment]
Thanks.

**Comment by defuse** [comment]
@daira: Yeah, that's right. When we do #1108 we should move the archives onto `z.cash` so that we can get rid of `zca.sh` entirely.

**Comment by ageis** [comment]
FYI, I have a StartSSL Class 2 validation, which means I can get issued 2-year validity wildcard certificates for `*.z.cash` and `*.zca.sh` completely for free. It's always useful to have a wildcard cert—if you don't want to be using Let's Encrypt or paying for certs for every individual subdomain, it's probably something we should have.

**Comment by ebfull** [comment]
Is this ticket (and tickets like it) more appropriate for our infrastructure repository?

**Comment by ageis** [comment]
@ebfull yes.

**Comment by nathan-at-least** [comment]
I'm assuming this is on the agenda to ensure we don't drop it. I've added a ticket there, plus @ageis has ack'd. If this was on the agenda for another reason, re-raise it.

**Comment by ebfull** [comment]
Closing because @ageis should already be aware of this.
