### ISSUE TITLE
Add "Supported releases and EoS halt" page to book, and reference it elsewhere

### ISSUE THREAD

**Issue by mangekyousharingan** [zcash/zcash#6232]
Hey,

Regarding most recent update https://github.com/zcash/zcash/releases/tag/v5.3.0, the release notes does not contain any information whether the update was mandatory or not.
For those who did not update the nodes, they suddenly stopped working with info:
`Error: This version has been deprecated as of block height 1859395. You should upgrade to the latest version of Zcash. `

Would it be possible to get such info in release notes, to make sure we are up to date with necessary updates? 

Thank you!

**Comment by str4d** [comment]
It's not that 5.3.0 was a mandatory upgrade, but that your previous version (and every previous version) is "required to be upgraded at some point".

Every `zcashd` version released by us has an End-of-Support height, after which the binary will not run. This is for several reasons:
- We as maintainers do not have the resources to maintain old versions of `zcashd` indefinitely.
- Each time a user upgrades their `zcashd` node, they are re-confirming that they are happy to run the Zcash consensus rules encoded in the version of `zcashd` they are running. This is an important part of our overall strategy for changes to the node and consensus rules; users who want to follow different rules (or even just have a different EoS halt policy) will obtain a `zcashd` binary from some other source, with its own support policies.
- Knowing that old versions will shut down is very useful for planning backwards-incompatible changes in Network Upgrades; we can activate a Network Upgrade at a height where we know that all `zcashd` versions we had released which _did not_ support the NU will have shut down by the time the NU activates.

This does mean we need to regularly release `zcashd` versions before the older ones reach their EoS halt, and sometimes our releases are delayed (as 5.3.0 was) which reduces the amount of time in which users can upgrade. I apologise for this happening for 5.3.0.

You can use `zcash-cli getdeprecationinfo` to check the height at which your running `zcashd` node will shut down. This could be also called over JSON-RPC by a health checking or monitoring service, if you use those to manage your node.

---

With regard to the release notes, there's an ordering problem here. The logical place to put the EoS halt for a version is in its release notes (and in fact we should alter the release script to do this automatically). But I suspect that when a new `zcashd` release drops, people only look at _its_ release notes, and don't revisit the release notes of the version they are currently running. We have a few options here:

- We could add a table somewhere in each release notes, with the list of currently-supported (as of release time) `zcashd` versions with their EoS heights.
  - This is a point-in-time snapshot, so anyone reading old release notes would need to be aware that it is out-of-date. This would require us to include estimated dates alongside the EoS heights (which we can sort-of predict, but is prone to being off by a few days).
  - This affects any downstream code forks, which would need to be aware of this and know to patch them out.
- We could add a URL pointing to a separate page where we track supported `zcashd` versions.
  - This could be kept accurate, so anyone reading old release notes would still be given correct current information.
  - This requires the URL to be kept running, which is a maintenance hazard.

Whatever we go with, we should adjust the EoS halt error message to direct users to this information.

Actually, while writing this it occurred to me that we can thread the needle between the above two: put the information into the [`zcashd` book](https://zcash.github.io/zcash/):
- The book could give the same table as proposed above, updated in the same way by the release script.
- The book page would have a well-defined URL that we can include in error messages etc.
- The book is updated by GitHub Actions, so it's a much lower maintenance hazard than something we try to keep running "live" (instead this page would be updated each release).

**Comment by mangekyousharingan** [comment]
@str4d Thank you so much for such detailed explanation. I was not aware of `End-of-Support height` for each zcashd version. This helps me a lot and since now will keep it in mind! 🙏 ❤️

**Comment by str4d** [comment]
Reopening this to track the proposed changes to the book.

**Comment by daira** [comment]
> We could add a URL pointing to a separate page where we track supported zcashd versions.
> * This could be kept accurate, so anyone reading old release notes would still be given correct current information.
> * This requires the URL to be kept running, which is a maintenance hazard.

We already have such a URL, at https://z.cash/schedule . We should ensure that it is up-to-date by automating the process of checking its EoS halt dates.

**Comment by str4d** [comment]
I've seen another request for adding this information to the release notes, so I'm adding this issue to the 5.5.0 milestone for updating the release script to include it.
