### ISSUE TITLE
I want to modify the multiexpo.rs under zcash/depends/x86_64-pc-linux-gnu/vendored-sources/bellman to get the test results.  How to avoid the following errors?

### ISSUE THREAD

**Issue by pollyttlccb** [zcash/zcash#6269]
error: the listed checksum of `/home/zjw/zcash/zcash/depends/x86_64-pc-linux-gnu/share/../vendored-sources/bellman/src/multiexp.rs` has changed:
expected: ec31c0cc1cad36435f70b0281a5b7f0fafd36df855c0fe0f006df695190a71de
actual:   91d99640dee9239ba4d8f343fe05df70fc7468a5aba19beab860acad23259603

directory sources are not intended to be edited, if modifications are required then it is recommended that `[patch]` is used with a forked copy of the source

**Comment by str4d** [comment]
What you should do is check out a local copy of the https://github.com/zkcrypto/bellman repository, and then add a patch directive to use it in this repo's `Cargo.toml`:

```
[patch.crates-io]
bellman = { path = "../path/to/local/bellman" }
```

See https://zcash.github.io/zcash/dev/rust.html#using-a-local-rust-dependency for more details.
