### ISSUE TITLE
Set up network bootstrapping dns hooks for testnet.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#630]
See ``chainparams.cpp``.

**Comment by daira** [comment]
Is this unauthenticated DNS? Seems completely insecure to me.

**Comment by nathan-at-least** [comment]
Hm. Good point. Maybe we don't need to emulate upstream here and ponder a better bootstrapping solution.

**Comment by bitcartel** [comment]
Some options.  Guess all will need minor modification to work due to magic numbers having changed.

- Run a DNS seeder, popular with upstream:
  - https://github.com/sipa/bitcoin-seeder

- Cartographer:  A crawler which supports digitally signed seed data over HTTP.  Fully supported by BitcoinJ (same authors).  Advantages over DNS seeding are in the README.
  - https://github.com/bitcoinj/httpseed

- Bitnodes: Modify and run an instance of Bitnodes.  Use the RPC API to retrieve data over HTTPS.  Heavy compared to other approaches but nice to have in the long run as part of the ecosystem.
  - https://bitnodes.21.co/
  - https://github.com/ayeowch/bitnodes
  - Already implemented for another project: https://bitco.in/forum/threads/buip018-passed-bitnodes-seeding-and-user-configurable-dns-seeds.1065/

**Comment by indolering** [comment]
> Is this unauthenticated DNS? Seems completely insecure to me.

It is ... but so is your P2P network : )  You could run your own DNS seeds and use DNSSEC, but IP isn't authenticated either.  If you are worried about a Sybil attack, blend P2P clients with centralized validation (such as passing around a signed copy of the current root hash).  That's way easier than setting up your own key-value database with a massive global caching system ... which DNS gives you for free.

With Namecoin, we hardcoded DNS seeds run by trusted community members.  **Note that you definitely need to list some onion addresses**.

**Comment by defuse** [comment]
Will the Beta 1 release use this bootstrapping for the *testnet*? I think it should in order to make sure it gets enough real-world testing before 1.0.

**Comment by defuse** [comment]
The bootstrapping mechanism needs to be free of DoS vulnerabilities such as the one currently affecting our testnet (#1251).

**Comment by daira** [comment]
See https://github.com/zcash/zcash/issues/1256#issuecomment-240805248 for discussion of the reason why that DoS is effective.

**Comment by ageis** [comment]
It sounds to me like forking bitcoin-seeder is the way to go. Although the Cartographer approach is considerably more secure, support for its signed HTTP seed data is not in Bitcoin Core to my knowledge, and so there's a greater development burden. I'm not a strong C/C++ guy and I'm not familiar with the modifications that would have to be made, but I hope someone can take a deeper look.

**Comment by ageis** [comment]
I've forked bitcoin-seeder and made some modifications to make it compatible with Zcash. https://github.com/zcash/zcash-seeder/pull/1

I'm running it on alphatestnet.z.cash and there's a DNS record for dnsseed.testnet.z.cash (args: `./dnsseed -h dnsseed.testnet.zcash -n alphatestnet.z.cash -m 'sysadmin@z.cash' --testnet`). 

It is logging and responding to DNS requests from examples like `dig -t NS dnsseed.testnet.z.cash`.

Haven't really got this fully working yet. I'm not sure how it's supposed to find nodes without some pre-existing seeds, or what a good process for testing should be. I need to either talk to the developers for clarification or get some help from someone else.

**Comment by nathan-at-least** [comment]
I retitled this to be about testnet and set up a different ticket for prodnet. If this works for the testnet as of Beta 1 release, let's close it.

**Comment by nathan-at-least** [comment]
I'm bumping this to Beta 2.

**Comment by ageis** [comment]
The seeder has logged 54091 DNS requests + 2596 db queries, but it's still not returning any available nodes, if I'm understanding it correctly. So I don't think it's working. I just initiated a chat with @sipa to see if he might be able to figure out if we missed something.

**Comment by ageis** [comment]
The DNS seeder is now working, an announcement was made on the forum: https://forum.z.cash/t/improved-network-bootstrapping-and-reliability/1959/3

The main thing that was stopping it was a hard-coded required block height. There were other issues and questions that popped up during the process of debugging, but those have now been cleared up.
