### ISSUE TITLE
pindex->pprev->hashFinalOrchardRoot == orchardWallet.GetLatestAnchor()' failed

### ISSUE THREAD

**Issue by docblocxxx** [zcash/zcash#6301]
the problem appeared after updating the node to version 5.3.2, on 5.3.0 - no problem.

run
`zcashd`

afer a couple of minutes(the header was loading, and the blocks would soon start loading)
```
zcashd: wallet/wallet.cpp:2950: void CWallet::DecrementNoteWitnesses(const Consensus::Params &, const CBlockIndex *): Assertion `pindex->pprev->hashFinalOrchardRoot == orchardWallet.GetLatestAnchor()' failed.
Aborted
```

binary were obtained by downloading from apt
Linux 4.19.0-21-amd64 #1 SMP Debian 4.19.249-2 (2022-06-30) x86_64 GNU/Linux
8gb
4cpu
1tb ssd nvme samsung 970
zcashd --version
Zcash Daemon version v5.3.2
lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

debug.log
contains no errors.
only messages
`INFO main: UpdateTip: new best hash=`

zcash.conf
experimentalfeatures=1

It is not possible to launch the node in the future.
The error is repeated over and over again.

A possible solution is to run with the -rescan flag or something like -salvagewallet
Well, or create-rewrite wallet.dat

**Comment by docblocxxx** [comment]
rescan solves this problem.
But, this can occur at any other time when starting zcashd, especially if there were any *transactions* made last time.
terminating zcashd was always correct, zcash-cli stop (for example).
Nodes that have not been involved in transactions, with wallet.dat connected, and serve as and explorer=1, are not affected by this error.

**Comment by docblocxxx** [comment]
rescan solves this problem.
But, this can occur at any other time when starting zcashd, especially if there were any *transactions* made last time.
terminating zcashd was always correct, zcash-cli stop (for example).
Nodes that have not been involved in transactions, with wallet.dat connected, and serve as and explorer=1, are not affected by this error.

**Comment by EvilRedHorse** [comment]
This occurred during an initial block-sync for a used wallet.
dmesg indicates the system did not attempt to enter a suspend state; though perf had lowered the kernel.perf_event_max_sample_rate.
```
zcashd: wallet/wallet.cpp:2966: void CWallet::DecrementNoteWitnesses(const Consensus::Params &, const CBlockIndex *): Assertion `pindex->pprev->hashFinalOrchardRoot == orchardWallet.GetLatestAnchor()' failed.
```
Starting zcashd after crash; the block sync restarted at about block 1786220.
The wallet had not been fully synced; perhaps since this epoch... 
> Zcash NU5
> block 1687104, mined May 31, 2022 17:50:05 UTC+00:00
> BOSL provides some protection against these threats but also adds complication.
