### ISSUE TITLE
Add contributer repositories to buildbot's scanned repos.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#634]
We're switching branch mgmt policy so that devs keep their working branches in github clones of this repository. However, buildbot doesn't see those currently, so we need a whitelist of dev clone repos to scan.

**Comment by nathan-at-least** [comment]
Paging @daira: Do you happen to know if buildbot can do the feature described in this ticket, namely: "Notice and build other user repository URLs such as `nathan-at-least/zcash` along with this repository URL." ?

We found [a thread](http://comments.gmane.org/gmane.comp.python.buildbot.devel/9626) related to Tahoe-LAFS that discusses an alternative we might like, which is "notice then build/test Pull Requests".  If we could do that *and* restrict this to PRs from known sources, that would be the best feature set, IMO.  Does Tahoe-LAFS do anything like this?

**Comment by defuse** [comment]
I don't care if we build untrusted PRs *inside a docker container* since the attacker wouldn't be able to delete their PR so there'd be some evidence of an attack at least. However, it would be a huge waste of resources so we should make a reasonable effort to whitelist sources.

**Comment by defuse** [comment]
I suspect @ebfull might have something to say about this (is it a homu feature?)

**Comment by ebfull** [comment]
I believe homu uses github hooks to pull from branches that we authorize explicitly in issues by saying `r+` or `r+ <commit hash>`. Why would running it inside a docker container be a waste though?

**Comment by defuse** [comment]
When I wrote that comment I was thinking of it automatically running all of our tests whenever someone submits a PR, like Travis-CI does. That would DoS our build system. With Homu we don't have that problem.

I think we can close this ticket now, right?

**Comment by ebfull** [comment]
Yep, I think this can be closed.
