### ISSUE TITLE
Remove CentOS 8 as a Tier 1 platform

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#6340]
[CentOS 8 reached EoL on December 31st 2021](https://www.centos.org/centos-linux-eol/). I missed this in #5951 (instead putting an EoL date of "TBD" as I thought it wasn't defined at the time). Per our [Platform Tier Policy](https://zcash.github.io/zcash/dev/platform-tier-policy.html), CentOS 8 no longer meets our Tier 2 platform requirements, and therefore is not eligible for Tier 1 or Tier 2. We should therefore remove it.

**Comment by str4d** [comment]
CentOS 7 doesn't reach EoL [until mid-2024](https://wiki.centos.org/About/Product), but I don't believe we've ever got it to above equivalent of Tier 2, so it currently is not supported. #2817 is tracking that.

**Comment by str4d** [comment]
Order of operations:
- Remove it from the Tier 1 platforms list (#6341).
- Remove the "required" blocker from CI (so we can start merging PRs that fail on CentOS).
- Remove the CentOS builder from CI.
- Remove the CentOS 8 files under `contrib/ci-builders` that CI was using.

**Comment by nuttycom** [comment]
Moved to https://github.com/zcash/zcash/milestone/194 for the remaining removal of CI builder files.
