### ISSUE TITLE
allowdeprecated=getnewaddress doesn't work

### ISSUE THREAD

**Issue by gades** [zcash/zcash#6420]
### Describe the issue
After update to 5.4.0 I can't use RPC getnewaddress anymore by adding allowdeprecated=getnewaddress into config

#### If so, please list the steps to reproduce below:
1. add allowdeprecated=getnewaddress to the  ~/.zcash/zcash.conf
2. restart zcashd
3. zcash-cli getnewaddress

### Expected behaviour
I don't know why simple RPC function was removed from rpc, the better to add wallet encryption instead it

### The version of Zcash you were using:
Zcash Daemon version v5.4.0

**Comment by gades** [comment]
it's working only by using as parameters to zcashd but I need to add it into config

**Comment by str4d** [comment]
Huh, that's unexpected. We're using the same config parsing system as for every other config option, so it should work. I'll have a look later today.

**Comment by areebmajeed** [comment]
I'm facing the same issue. These lines are included in my config file.

```
allowdeprecated=z_getbalance
allowdeprecated=z_gettotalbalance
allowdeprecated=z_getnewaddress
allowdeprecated=getnewaddress
allowdeprecated=z_listaddresses
```

**Comment by gades** [comment]
> I'm facing the same issue. These lines are included in my config file.
> 
> ```
> allowdeprecated=z_getbalance
> allowdeprecated=z_gettotalbalance
> allowdeprecated=z_getnewaddress
> allowdeprecated=getnewaddress
> allowdeprecated=z_listaddresses
> ```

You can add those parameters to your Zcashd and it will work as workaround but the better fix it

**Comment by str4d** [comment]
I've identified the bug, and opened https://github.com/zcash/zcash/pull/6423 with the fix. We will release a v5.4.1 including this, but you can build directly from that branch (which is based on the v5.4.0 tag) if you want to use it early.
