### ISSUE TITLE
Cannot connect to nkf5e6b7pl4jfd4a.onion:18333: unsupported network

### ISSUE THREAD

**Issue by petjal** [zcash/zcash#644]
./src/zcashd -daemon -printtoconsole
...
UpdateTip: new best=000000237d4e4544690b783957d703cb1099c5e7441b2d54802029f7f1c5393b  height=8815  log2_work=37.159692  tx=8831  date=2016-01-21 05:58:53 progress=1.000000  cache=2.0MiB(8799tx)
Cannot connect to nkf5e6b7pl4jfd4a.onion:18333: unsupported network
UpdateTip: new best=000000059fe559c4fdecd9cbd4bb80f2aef061a3ffde2f314ae405a5dabaf189  height=8816  log2_work=37.160714  tx=8832  date=2016-01-21 05:59:36 progress=1.000000  cache=2.0MiB(8800tx)
Cannot connect to thfsmmn2jbitcoin.onion:18333: unsupported network
UpdateTip: new best=00000003792a258f80f69c0fabbbafff5e8fe40d357d041b7c17135b10bab70a  height=8817  log2_work=37.161735  tx=8833  date=2016-01-21 06:00:13 progress=1.000000  cache=2.0MiB(8801tx)
Cannot connect to nkf5e6b7pl4jfd4a.onion:18333: unsupported network
Cannot connect to t6xj6wilh4ytvcs7.onion:18333: unsupported network

My build threw these errors, but the daemon seems to be working fine:
collect2: error: ld returned 1 exit status
make[2]: *** [test/test_bitcoin] Error 1
make[2]: Leaving directory `/home/user/Documents/dev/zcash/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/user/Documents/dev/zcash/src'
make: *** [all-recursive] Error 1

I started tor but that didn't seem to help:
Jan 21 00:53:38.000 [notice] Tor has successfully opened a circuit. Looks like client functionality is working.
Jan 21 00:53:38.000 [notice] Bootstrapped 100%: Done.

I killed the daemon and tried again, but that didn't help:
./src/zcashd -daemon -printtoconsole
...
        (leave) Online pairing computations        	[0.0736s x0.96]	(1453356360.7128s x0.00 from start)
      (leave) Call to r1cs_ppzksnark_online_verifier_weak_IC	[0.0761s x0.96]	(1453356360.7128s x0.00 from start)
    (leave) Call to r1cs_ppzksnark_online_verifier_strong_IC	[0.0762s x0.96]	(1453356360.7128s x0.00 from start)
  (leave) Call to r1cs_ppzksnark_verifier_strong_IC	[0.0845s x0.96]	(1453356360.7129s x0.00 from start)
(leave) Call to zerocash_pour_ppzksnark_verifier	[0.0850s x0.96]	(1453356360.7129s x0.00 from start)
No coin database inconsistencies in last 289 blocks (299 transactions)
 block index            1615ms
init message: Loading wallet...
nFileVersion = 110200
Keys: 102 plaintext, 0 encrypted, 102 w/ metadata, 102 total
 wallet                  108ms
init message: Rescanning...
Rescanning last 8817 blocks (from block 0)...
 rescan                   15ms
init message: Activating best chain...
mapBlockIndex.size() = 8818
nBestHeight = 8817
setKeyPool.size() = 100
mapWallet.size() = 0
mapAddressBook.size() = 2
init message: Loading addresses...
Loaded 7 addresses from peers.dat  18ms
dnsseed thread start
net thread start
addcon thread start
msghand thread start
init message: Done loading
opencon thread start
receive version message: /Satoshi:0.11.2/: version 70002, blocks=8820, us=73.238.106.75:53575, peer=1
Added time data, samples 2, offset +0 (+0 minutes)
Cannot connect to thfsmmn2jbitcoin.onion:18333: unsupported network
UpdateTip: new best=000000023442ef665c127cfb8b54b46bd32743178bb7f129ecbfa9114cf72399  height=8818  log2_work=37.162756  tx=8834  date=2016-01-21 06:03:51 progress=1.000000  cache=0.0MiB(1tx)
UpdateTip: new best=0000001728a113701b29a54529166bd406a43ad7f07bee767a42f673d7e0c0ce  height=8819  log2_work=37.163776  tx=8835  date=2016-01-21 06:04:26 progress=1.000000  cache=0.0MiB(2tx)
UpdateTip: new best=0000001a9999878e77209f4b68d48fbda30c4a80f204084d71b7bd11ae275735  height=8820  log2_work=37.164795  tx=8836  date=2016-01-21 06:05:51 progress=1.000000  cache=0.0MiB(3tx)
Cannot connect to ubqj4rsu3nqtxmtp.onion:18333: unsupported network
Cannot connect to nkf5e6b7pl4jfd4a.onion:18333: unsupported network
Cannot connect to 4zhkir2ofl7orfom.onion:18333: unsupported network
Cannot connect to it2pj4f7657g3rhi.onion:18333: unsupported network
Cannot connect to t6xj6wilh4ytvcs7.onion:18333: unsupported network
Cannot connect to i6y6ivorwakd7nw3.onion:18333: unsupported network
Loading addresses from DNS seeds (could take a while)
0 addresses found from DNS seeds
dnsseed thread exit
UpdateTip: new best=00000023d0b1205eb6b6dd3b596894074a0a6517bfd10769aad2ebf7aea68331  height=8821  log2_work=37.165813  tx=8837  date=2016-01-21 06:06:16 progress=1.000000  cache=0.0MiB(4tx)
Cannot connect to t6xj6wilh4ytvcs7.onion:18333: unsupported network
Cannot connect to ubqj4rsu3nqtxmtp.onion:18333: unsupported network
Cannot connect to ubqj4rsu3nqtxmtp.onion:18333: unsupported network
Cannot connect to ubqj4rsu3nqtxmtp.onion:18333: unsupported network

I see that error in:
https://github.com/Electric-Coin-Company/zcash/blob/293e4f015b811a03e4059cab38c92e7b42978bcc/src/netbase.cpp

**Comment by ebfull** [comment]
It's not a big deal, it's just trying to connect to Tor nodes. Tor isn't supported yet, but it's part of our "in 1.0" features.

**Comment by daira** [comment]
This ticket should be left open until it works, right? Or the .onion seeds should be removed and then replaced later with one that work.

**Comment by ebfull** [comment]
Oops, I closed it because it was a dup of #651.
