### ISSUE TITLE
Coin commitment versioning

### ISSUE THREAD

**Issue by ebfull** [zcash/zcash#648]
We'd like our circuit to be able to detect usage of a bucket commitment produced by a previous circuit which may not be compatible if we were to switch circuits and change the overall scheme in some way. We can take a byte out of currently wasted space that was once used for `s`.

**Comment by nathan-at-least** [comment]
In a discussion just now (without @ebfull present), it seems that a future circuit would be able to use a distinct hash function for a new distinct ``COMM`` instantiation, and that there's no need to change anything for future proofing, so we're closing this as "wont fix".  (@ebfull should reopen if we're missing something.)

**Comment by daira** [comment]
Either a new hash function or a disjoint hash input to SHA-256-compress, yes.

**Comment by ebfull** [comment]
I was thinking about adding fields to the commitments alongside `v` such as commitments to `CScript`s.

However, the wasted space currently for `s` can be used to achieve versioning of this kind in the future, so wontfix is okay with me.

**Comment by ebfull** [comment]
This needs to be reconsidered in light of the new spec and the absense of `s`. Matthew Green [suggested](https://github.com/zcash/zcash/issues/406#issuecomment-194318284) that we can attach separate features as separate snarks, and it may be nice to use versioning of some kind so we can discriminate between `Coin`s which follow the old or newer rules.

**Comment by daira** [comment]
The current spec has a lead byte (0xC0) for the input to the coin commitment hash. That's what we would change for a future version, if necessary.

**Comment by ebfull** [comment]
I'm closing this since it's being added to the spec, so this ticket isn't useful.
