### ISSUE TITLE
-165 zec fee 

### ISSUE THREAD

**Issue by UserZEC** [zcash/zcash#6522]
### Describe the issue
A commission of 165 ZEC was written off. I tried to rescan and install the program on another computer, in zec native block explorer it does not find a transaction, in an alternative explorer there is a transaction, but the commission is normal 0.0001 zek. The problem occurred when sending to a private shielded address

#### If so, please list the steps to reproduce below:
1. too expensive to repeat

### Expected behaviour
an error occurred while sending to the address, a large commission

### Actual behaviour + errors
A commission of 165 zcash was written off. I tried to rescan and install the program on another computer, in zec native block explorer it does not find a transaction, in an alternative explorer there is a transaction, but the commission is normal 0.0001 zcash. The problem occurred when sending to a private shielded address

### The version of Zcash you were using:
Zecwallet Lite 1.8.8

### Machine specs:
Not important in different pc same problem

**Comment by Har01d** [comment]
Can you share the transaction hash? Most explorers process Orchard transactions incorrectly.

**Comment by UserZEC** [comment]
> Can you share the transaction hash? Most explorers process Orchard transactions incorrectly.

eae3aad72d3275a5a3071058413108fcdfe0de6fe1e899f48d43c8a5699a6954
Ywallet see balance, but in any amount can't transfer, error not enough funds

**Comment by UserZEC** [comment]
Problem solved. I copied the private key from the address, then completely removed the wallet program and imported the private key from the address. For some reason, other addresses or transaction history from other addresses cause an error in the wallet.

**Comment by nuttycom** [comment]
@UserZEC even though you solved the issue, the bug should still be noted and addressed. However, this is not the correct repository to raise the issue in; please move this issue to https://github.com/ZcashFoundation/zecwallet-lite as it is not related to zcashd behavior as far as I can tell.
