### ISSUE TITLE
build stops with error about LIBTOOL undefined

### ISSUE THREAD

**Issue by zookozcash** [zcash/zcash#653]
I followed these instructions:

https://github.com/Electric-Coin-Company/zcash/wiki/Public-Alpha-Guide

And ./zcutil/build.sh stopped with this as the tail of its output:

```
touch /home/zooko/ZECC/git/zcash/depends/x86_64-unknown-linux-gnu/share/config.site
make: Leaving directory `/home/zooko/ZECC/git/zcash/depends'
+ ./autogen.sh
configure.ac:25: installing 'build-aux/compile'
configure.ac:5: installing 'build-aux/config.guess'
configure.ac:5: installing 'build-aux/config.sub'
configure.ac:9: installing 'build-aux/install-sh'
configure.ac:9: installing 'build-aux/missing'
Makefile.am:3: error: Libtool library used but 'LIBTOOL' is undefined
Makefile.am:3:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
Makefile.am:3:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
Makefile.am:3:   If 'LT_INIT' is in 'configure.ac', make sure
Makefile.am:3:   its definition is in aclocal's search path.
Makefile.am: installing 'build-aux/depcomp'
parallel-tests: installing 'build-aux/test-driver'
autoreconf: automake failed with exit status: 1
```

Here are some details about my system:

```
zooko@spark ~/ZECC/git/zcash $ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty
zooko@spark ~/ZECC/git/zcash $ uname -a
Linux spark 4.1.15z35-slub-cfg-preempt #1 SMP PREEMPT Wed Dec 16 19:48:38 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
zooko@spark ~/ZECC/git/zcash $ dpkg --list |grep -i libtool
ii  libltdl7:amd64                                2.4.2-1.7ubuntu1                                    amd64        A system independent dlopen wrapper for GNU libtool
```

**Comment by zookozcash** [comment]
Installing this Ubuntu package fixed it: `libltdl-dev`. I guess Ubuntu is a common enough platform for our current users that it is worth adding a note about this to https://github.com/Electric-Coin-Company/zcash/wiki/Public-Alpha-Guide. If you agree I'll add it and close this ticket, or you (whoever you are reading this) add it and close this ticket, or tell me otherwise.

**Comment by nathan-at-least** [comment]
@zookozcash, we updated the alpha guide with an `apt-get` step, but it doesn't mention the package you found. Can you try removing the `libtool` and `libltdl-dev` packages and using the command in the guide?  (-or if not, we will hopefully have an ubuntu docker test sometime soonish.)

**Comment by defuse** [comment]
@zookozcash: If you aren't interested in doing what @nathan-at-least said above, you can just close this ticket. I'm pretty sure it's because we were missing the `apt-get install ... libtool ...` step when you tried it.

**Comment by daira** [comment]
I'm assuming this is no longer an issue.
