### ISSUE TITLE
Possible "ridiculous" consistency checks. Read of same CDiskBlockIndex twice.

### ISSUE THREAD

**Issue by DeckerSU** [zcash/zcash#6532]
I ported https://github.com/zcash/zcash/pull/6192 changes into [other](https://github.com/DeckerSU/KomodoOcean/pull/49) codebase and actively testing it now. During my tests I found that some consistency checks in `CBlockTreeDB::LoadBlockIndexGuts` possible can be "ridiculous" and just leads to useless I/O operations. Of course, I could be wrong and miss something, but ... let me explain. Let's image that we are going through this code:
https://github.com/zcash/zcash/blob/83dc37239458273d5029096180c26d6c5f5e7d20/src/txdb.cpp#L607-L613

1. Here we get next `DB_BLOCK_INDEX` value stored in LevelDB and read it into `diskindex`.
2. Then we create new or update the existing corresponding `CBlockIndex` pointer in `mapBlockIndex`. We took members values from  `diskindex` just read.
3. Then, to begin the "consistency checks" we should obtain hash of `CBlockHeader`:
https://github.com/zcash/zcash/blob/83dc37239458273d5029096180c26d6c5f5e7d20/src/txdb.cpp#L639-L655
Inside `CBlockIndex::GetBlockHeader()` we just copy all the values filled on step (2) from `CBlockIndex` pointer, except, solution ... which we read from disk using `ReadDiskBlockIndex`. Literally we just read this `CBlockIndex`  as `diskindex` on step (1), but inside `CBlockIndex::GetBlockHeader()` we doing it again with seeking in `CBlockTreeDB` by block hash. `phashBlock` which is used as a key also taken form `diskindex`.
4. When we have `header` which is literally copied from `diskindex` + 1 extra operation of read of the same `diskindex`, which we already have on step (1) we compare its hash with hashes `diskindex.GetBlockHash()` and `pindexNew->GetBlockHash()`. 
5. But according to the member's "fill algo" they are always will be identical. I mean that at the beginning of "consistency check" the following values will be equal anyway `key.second == diskindex.GetBlockHash() == pindexNew->GetBlockHash()`. 

The question arises as to the feasibility of these tests and re-reading same `CDiskBlockIndex` via `ReadDiskBlockIndex` in this loop. 

In Komodo blockchain which consists of `3366015` blocks at present it leads to the same amount of "double-read" of `CDiskBlockIndex` (i.e. 3.3M extra I/O operations) Again, maybe I'm wrong somewhere.

From perfomance point of view, `LoadBlockIndexGuts` execution time:

- with consistency checks: `67890 ms.`
- without consistency checks: `21762 ms.`

So, if I don't wrong anywhere, we can speed-up node start by `x3` if we will get rid of these checks.

**Comment by daira** [comment]
Yes this looks correct. The consistency checks can and should be removed.

**Comment by daira** [comment]
Fixed by #6565.
