### ISSUE TITLE
Ensure Spec retains distinctness assumption in hSig

### ISSUE THREAD

**Issue by ebfull** [zcash/zcash#663]
In the original zerocash paper, h<sub>Sig</sub> is unique for every pour. This is obviously necessary because pk<sub>Sig</sub> is an ephemeral ECDSA public key, and so privacy details would be leaked otherwise should the key be reused.

In the Calgary design we agreed to make h<sub>Sig</sub> a SHA256 hash of a `CScript` (`scriptPubKey`) in `CPourTx` in order to abstract away the conditions of cryptographic binding to achieve non-malleability. (#529)

**However**, the zkSNARK circuit also *assumes* that h<sub>Sig</sub> is unique for every pour, because h<sub>i</sub> is SHA256Compress(a<sub>sk, i</sub> || 10 || i || trunc<sub>253</sub>(h<sub>Sig</sub>)). In other words, if the same `scriptPubKey` were used to spend from the same private key in two different pours, h<sub>i</sub> would be the same for both pours, which would violate indistinguishability! (The source of two transactions could be correlated.)

As part of the Calgary design we did not intend to use `scriptPubKey` in this way anyway, but now there's a concrete reason not to. We do not want our users accidentally stumbling upon this when creating exotic protocols. We should consider modifying the zkSNARK circuit to make h<sub>i</sub> a cryptographic commitment to a<sub>sk</sub> and h<sub>Sig</sub>.

**Comment by ebfull** [comment]
CC @daira

**Comment by ebfull** [comment]
Rather than a circuit change, perhaps we could make h<sub>Sig</sub> hash `scriptPubKey` with a nonce?

**Comment by ebfull** [comment]
Here's a demonstration of the attack we'd like to fix, if you're confused.

If the user spends two different buckets using the same secret key, and chooses the same `scriptPubKey` for both (which incidentally is what currently happens because #529 has not been closed yet) the resulting two transactions are as follows:

```
$ ./src/zcash-cli zcrawpour 01000000000000000000 '{"805b6d2901000000208a822fa0e304db73c792cc34e7fdb8ea0f3b9371dadd49a80613c3d1dedeb6b23099b96223812b76d33793703b1a42409a3154e49f2c162e4f318895ad0c179122864a2cfdc547cb421a10da74224ed1fc":"20254a5b602a28b0d3ef1e0e9b4c23723acc845296ff47a2c7623e499b0c75fa44fd1f013082011b0201003081ec06072a8648ce3d02013081e0020101302c06072a8648ce3d0101022100ffffffff00000001000000000000000000000000ffffffffffffffffffffffff30440420ffffffff00000001000000000000000000000000fffffffffffffffffffffffc04205ac635d8aa3a93e7b3ebbd55769886bc651d06b0cc53b0f63bce3c3e27d2604b0441046b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c2964fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576b315ececbb6406837bf51f5022100ffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc6325510201010427302502010104207342a264212342c090161f5b4f846eb35fe0b07511833b073451aa5d3277a83d"}' '{"203eabc9a9c6943cb406e08e5745546665f5ed26a1cd22999c0845ea124ea913a5fd3401308201303081e906072a8648ce3d02013081dd020101302c06072a8648ce3d0101022100ffffffff00000001000000000000000000000000ffffffffffffffffffffffff30440420ffffffff00000001000000000000000000000000fffffffffffffffffffffffc04205ac635d8aa3a93e7b3ebbd55769886bc651d06b0cc53b0f63bce3c3e27d2604b0441046b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c2964fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576b315ececbb6406837bf51f5022100ffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc63255103420004633e4722a05bdaeebc57e8bd70cec808ab12145996bf9d5a770021a857f024b1db5f7ad66452ce75cec026bd51f78eaa1acaf01cac5d5ba647f2aab8602e67ea":49.8}' 0 0.1                                                     {
    "encryptedbucket1" : "04046cfc1c0bf63977127c3925aeb3c2d7f5bef54fda8e687c1c4c31547b0d1b16dd0fe9b4b42898e96fdb892048f25991a461f5d9f9d915085cb78418b383c156dc197d71f4920228a41573f552b576092b727854f1e9d58f0b2cff21977e1cd1e9426caca7d7943f9f18a741e9f15b5ee27200e2bdc410ce5845cf9530e67f9e45a0eb074831ff6b42b7bc7895947ee879f1fa9ff2c14bffdfaccaa0bb62068756e8036637aaa5d206ff4120",
    "encryptedbucket2" : "046f77067b5377056dc1c124e7c7b57f60df3600e82262d103c85fd9dfaacffca4aca655592c30d07914ec5206851a25e7038c4378b04498f09bfc820e430f792125652a7cf3c1d806b802f264d4063a809878cb7b577c21d51a4c6756720b3bd13cf01fc85ba7e8d3ee690ef95358f7ccdeed0010fad86c60a20c6f49991d34fd31efe9b01863c8d4dce1aed185a3bad2f65371052f8e614caaa09fe250cbd577bb12b614db63d38c818bdf8c",
    "rawtxn" : "0200000000000000000001000000000000000080969800000000000000d30acb326a19688fbe3521ad672000f73c33dc7b41d79c8f5f99113a7944161415fca8832431e3a949be40daf52e0c803a920793e94c8026adb0dabf70098cc3b0234d9315c0001720f2105d7ad5326ea1ce40ecbbd107bd8146be86a23419f1aae25b9be8702fab0931ba6b2c138e6844d35ddbeaeb3544ce8370e82d6926e73c8e2c3db8044155f2c046c81a4c17e9e8c1359444fe99bd4a96346a90f04b62ad04046cfc1c0bf63977127c3925aeb3c2d7f5bef54fda8e687c1c4c31547b0d1b16dd0fe9b4b42898e96fdb892048f25991a461f5d9f9d915085cb78418b383c156dc197d71f4920228a41573f552b576092b727854f1e9d58f0b2cff21977e1cd1e9426caca7d7943f9f18a741e9f15b5ee27200e2bdc410ce5845cf9530e67f9e45a0eb074831ff6b42b7bc7895947ee879f1fa9ff2c14bffdfaccaa0bb62068756e8036637aaa5d206ff4120ad046f77067b5377056dc1c124e7c7b57f60df3600e82262d103c85fd9dfaacffca4aca655592c30d07914ec5206851a25e7038c4378b04498f09bfc820e430f792125652a7cf3c1d806b802f264d4063a809878cb7b577c21d51a4c6756720b3bd13cf01fc85ba7e8d3ee690ef95358f7ccdeed0010fad86c60a20c6f49991d34fd31efe9b01863c8d4dce1aed185a3bad2f65371052f8e614caaa09fe250cbd577bb12b614db63d38c818bdf8ce38c15a4870587c8cf4653bec2a905aabbff60e42dd028ea677ff1fd755bcc1f1327a11a6aaec99cba17671b46f1fdec245ecd53fa92cdab4d28185c868d895dfd8205302031363034363333343438313434383436313634383132383736353536373831353632373038363132393535353636373631383739373630373932343134363633333636393536323533363637392039313234313830353036383936343137383732313932373934393934383431303739333833333234303932303135393034363430323935383739323335393735363133393938303439373130203020323234303238383038363931363737303030363037343737303333353630363834323931363632353234323539363839343337343331323332373033383937393837353932313533333733352031343033353134353534383731333338333534343034313035363739393439383139363431343031333131373032323535373335363734373036383836373838393234303638363735313236340a30203138383130363538373534393732333635393739363537373231323837393138373835323438363432393730393037373039353036363831363834373033383238383431363535313831363035203936323939323034393732323436313736343232333731393537343538323437313332353337313231363037333734303834333038343130323539383434363034333939313330383837323420353631303531333530393035383938313930323333323832303739393733383733353933343833373136393034383739303534363435323333313137393330353632373137393935373736322036313335353839373335393536303637353530393134313038323932383739393330353631383331383837303339353737323334323139353630373034373031353231303830313730383036203020323039333037323031343736353731353136363934313838353530323635383435343631343936343331323535383731343832323736333538323231383735363937333635303138313130383620373230343234353134353432363735333933393335353432363331343333323732303738353432373739373830353437303237363030313638393436393933373936313039323330393935310a302031323533373337383831353833323130363031393138343033383838363535373734363237373739373933323438353435353633313837313538313539353439383436333735333531343732352039323435323232353932353334353933393939323330333737373634313937333333373835333439333537303439363031343734363236383032383232373735383634333536353136363338203020313030333032333931303831313139303734323038343533303131373831343730303536343739353430363436333731333437323636333239383631383439383439343039353337353830343820393433353434313534373231313634303937303736353232393733353434393736313333333135383832373731383235373730343933323339343430333937383336333531353739323331340a30203737313535303737343433383438313632333630363334323432313633393832353734353535343830343734313632363139313531333332383237353231303630323435323535343134343520323733353237343734363837353539333838333934313238313234373534313439373334313433323830343934393833343138383639313733383837383339303832393433363238303436300a302031363830343330363233323635343439343134363435383838343131333833323837383436313538343530383935333030323231343739343833303235373734343237333235393331383137392031383730373831333234353334333333303139313938383438363532353431363739353235393530383335303030393932333132303138313039373833393334313331393339373634373835390a"
}
$ ./src/zcash-cli zcrawpour 01000000000000000000 '{"805b6d2901000000207e5a812385b5344e027c08e2ce44f23d12b2971a50bba318a5719466e20bbe273073c1d249e38bcc4f9574128c753367ec56f8b8e26d636ee6385be86430c01a90b9a700a5f78a81b618c4536982e5506a":"20254a5b602a28b0d3ef1e0e9b4c23723acc845296ff47a2c7623e499b0c75fa44fd1f013082011b0201003081ec06072a8648ce3d02013081e0020101302c06072a8648ce3d0101022100ffffffff00000001000000000000000000000000ffffffffffffffffffffffff30440420ffffffff00000001000000000000000000000000fffffffffffffffffffffffc04205ac635d8aa3a93e7b3ebbd55769886bc651d06b0cc53b0f63bce3c3e27d2604b0441046b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c2964fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576b315ececbb6406837bf51f5022100ffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc6325510201010427302502010104207342a264212342c090161f5b4f846eb35fe0b07511833b073451aa5d3277a83d"}' '{"203eabc9a9c6943cb406e08e5745546665f5ed26a1cd22999c0845ea124ea913a5fd3401308201303081e906072a8648ce3d02013081dd020101302c06072a8648ce3d0101022100ffffffff00000001000000000000000000000000ffffffffffffffffffffffff30440420ffffffff00000001000000000000000000000000fffffffffffffffffffffffc04205ac635d8aa3a93e7b3ebbd55769886bc651d06b0cc53b0f63bce3c3e27d2604b0441046b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c2964fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576b315ececbb6406837bf51f5022100ffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc63255103420004633e4722a05bdaeebc57e8bd70cec808ab12145996bf9d5a770021a857f024b1db5f7ad66452ce75cec026bd51f78eaa1acaf01cac5d5ba647f2aab8602e67ea":49.8}' 0 0.1                                                     
{
    "encryptedbucket1" : "04fa899e364fd7afa87423267e7dab8e2254e58e265c6108c01cb1dfa7acf677ce8a5fe14374b14c72136a90a88d9e135a4e62b7a5a4280a2d2a76ef49fb279504c22aa6fa43366e4317eefa178371641f984c3e0012a023235430ae2607a4b61cc32e363f19d5f767dfd9594acac2ff17fbf64c5b95c3715166d0659a22d303d1787e23d3c45739abe1e07719593edfacc83816a673730fcd6b3170e9971643cfe4bda1edeb76a1ad3e300a02",
    "encryptedbucket2" : "0436f30fe1af7c389270e67a2c5c9d10218b6cd984c21dc4782bbef7fe31d3ae309325c164f5c787870d6b87b136bca4defbe871390ec36ce935e4e11bf523b3df8beeb769729fb30235b9a4f0cf489d82f4c6fb415cf7dd0ea13edab9b57c742b87de5805bf52acbbc1457132a9a15f3f44ba6d03f03091693920dd8f6cabc89bfb47511ace6e34d4fe6b9a631db6ed4ebd0f9f3e0636955d5765864b65fe6b0ff96a8dab61de8be31e45d704",
    "rawtxn" : "0200000000000000000001000000000000000080969800000000000000d30acb326a19688fbe3521ad672000f73c33dc7b41d79c8f5f99113a79441614cfddcc0a1a5faf801bcc75be6ed187c58ff197200408ec5a4c36fd424455da2e09fff814b61b8866172a578f0eac176c285a3534d449c4e42517daa158d28849750514c8cd4edc4400136f099ccdf4f96b2d248f0f82c48a2be72d982b5c1671295588f50b32604f000229a9aab489bd7faa2f043b167a7fc75ad2cc14843f7ead04fa899e364fd7afa87423267e7dab8e2254e58e265c6108c01cb1dfa7acf677ce8a5fe14374b14c72136a90a88d9e135a4e62b7a5a4280a2d2a76ef49fb279504c22aa6fa43366e4317eefa178371641f984c3e0012a023235430ae2607a4b61cc32e363f19d5f767dfd9594acac2ff17fbf64c5b95c3715166d0659a22d303d1787e23d3c45739abe1e07719593edfacc83816a673730fcd6b3170e9971643cfe4bda1edeb76a1ad3e300a02ad0436f30fe1af7c389270e67a2c5c9d10218b6cd984c21dc4782bbef7fe31d3ae309325c164f5c787870d6b87b136bca4defbe871390ec36ce935e4e11bf523b3df8beeb769729fb30235b9a4f0cf489d82f4c6fb415cf7dd0ea13edab9b57c742b87de5805bf52acbbc1457132a9a15f3f44ba6d03f03091693920dd8f6cabc89bfb47511ace6e34d4fe6b9a631db6ed4ebd0f9f3e0636955d5765864b65fe6b0ff96a8dab61de8be31e45d704e38c15a4870587c8cf4653bec2a905aabbff60e42dd028ea677ff1fd755bcc1fea033bbf039a4c4fbfe70e43ae636cefdb72fefcab7717851e08816c29b5924bfd7e05302031373530393437333331303532343132353833333831323235363236393135303839343538383938303235323331343131393138323736333738373036393033303533323138353934343736352034303136303930393530343439323833393332353836303330353636333632383633383037323333353630323032393234333534353034393638353137333932333538343639333737373937203020313332353633303733363334303230343437383832353035343230313632323633313730363635363034353536303831373636363132353038303536303336353638363135323539323838313220383837393237333032353730373138343138393138373136323831333034343335373630323636363535313831313730393030323933313839343931363134333131353930333433313034370a302031303132333032373536373936313837373435313833393737343230373230343630303031343131393234323739313831393231363038393239333830303837343830353031313438353937203332353035323137353530383339303035383235393430363134303434373231383732333231303634353231393331373935313339353330373037353136333130393334363330323635362036363336323730303936303938323332383530343132373032363430373333323035333130353433373234323031363539343234323736393336383333393133353833313339393338343230203839323139353135323336323230373831383536393434373734333238303732333139333234323737363731383335313733353634363034323732353737313036373235333037303130332030203436343537383937313435373533343036363539323737373637363136323831383835343536353934313730373039363933373031393934363332313031343732373433343733333631393120393838343837323130373530313536313038303136303132383231393039323733333938313731343135393038363633373234343338303937323730313539313335323134373334333734370a302031363432333630303836313330363235393432363731373334393631343936333236363531343332373036353233343633313636373737373333323533353430373032343935333530313133203230373031373439363139323630343431313830303632333337373034363630393237313834393835383631303336393534303937303236333735383232383236383236303033383236303931203020313733393733313237353832303730383832393039363832303334323935333439303332353132353034343935393139393833373231393934383636313937393435303638383332343734353620353133393431323732333837363536383538393231363438343136393436353732333230303530373534383339313037373139323430373931343433333631393833323838383937313134390a3020323131373033383337323839363932313433313339353339323331313739303034303138333334353239303936333131343736393138383236333537393836343731343732303038393831363720363335383531373830313533323731303530323431373838393337363438373830333034313639323635303634323736393930393931363436363439303430343432373836373836343730340a3020323134373935313039333734313434323332303239323134303733303335303633313932373930313935333539343730303634393936333738313338383330373530323539303030313033373820313234363436383435303933313331333131383130303536383535313331363838323632333034333136353631323136363734343035363630393936363032323237353737343438363038360a"
}
```

Decoded:

```
{
    "txid" : "f31da48e038e4dc4fd014d226ca4afa7590354e805fd9cb5f0e49882a4e457fb",
    "version" : 2,
    "locktime" : 0,
    "vin" : [
    ],
    "vout" : [
    ],
    "vpour" : [
        {
            "anchor" : "141644793a11995f8f9cd7417bdc333cf7002067ad2135be8f68196a32cb0ad3",
            "serials" : [
                "c38c0970bfdab0ad26804ce99307923a800c2ef5da40be49a9e3312483a8fc15",
                "f11934a286be4681bd07d1bbec40cea16e32d57a5d10f2201700c015934d23b0"
            ],
            "commitments" : [
                "e726692de87083ce4435ebeadb5dd344688e132c6bba3109ab2f70e89b5be2aa",
                "624bf0906a34964abd99fe449435c1e8e9174c1ac846c0f2554104b83d2c8e3c"
            ],
            "macs" : [
                "1fcc5b75fdf17f67ea28d02de460ffbbaa05a9c2be5346cfc8870587a4158ce3",
                "5d898d865c18284dabcd92fa53cd5e24ecfdf1461b6717ba9cc9ae6a1aa12713"
            ],
            "vpub_old" : 0.00000000,
            "vpub_new" : 0.10000000,
            "scriptPubKey" : {
                "asm" : "",
                "hex" : "",
                "type" : "nonstandard"
            },
            "scriptSig" : {
                "asm" : "",
                "hex" : "",
                "type" : "nonstandard"
            },
            "valid" : true
        }
    ]
}
```

and

```
{
    "txid" : "59dd78116bb3596c6582d07013c3be24e1be8ac3461175c76e6f6b662a96dd2a",
    "version" : 2,
    "locktime" : 0,
    "vin" : [
    ],
    "vout" : [
    ],
    "vpour" : [
        {
            "anchor" : "141644793a11995f8f9cd7417bdc333cf7002067ad2135be8f68196a32cb0ad3",
            "serials" : [
                "2eda554442fd364c5aec08042097f18fc587d16ebe75cc1b80af5f1a0accddcf",
                "4988d258a1da1725e4c449d434355a286c17ac0e8f572a1766881bb614f8ff09"
            ],
            "commitments" : [
                "71165c2b982de72b8ac4820f8f242d6bf9f4cd9c096f130044dc4ecdc8140575",
                "7e3f8414ccd25ac77f7a163b042faa7fbd89b4aaa92902004f60320bf5885529"
            ],
            "macs" : [
                "1fcc5b75fdf17f67ea28d02de460ffbbaa05a9c2be5346cfc8870587a4158ce3",
                "4b92b5296c81081e851777abfcfe72dbef6c63ae430ee7bf4f4c9a03bf3b03ea"
            ],
            "vpub_old" : 0.00000000,
            "vpub_new" : 0.10000000,
            "scriptPubKey" : {
                "asm" : "",
                "hex" : "",
                "type" : "nonstandard"
            },
            "scriptSig" : {
                "asm" : "",
                "hex" : "",
                "type" : "nonstandard"
            },
            "valid" : true
        }
    ]
}
```

Notice the first `mac` is the same in both. We've just indicated to an adversary (which could be our recipient(s)) that both transactions spent from the same private key.

**Comment by ebfull** [comment]
The simplest fix for this in the circuit that I can imagine is to have an auxillary input for the Pour **h<sub>Nonce</sub>** which is a 256 bit nonce, and *XOR* it against h<sub>Sig</sub> such that:

h<sub>1</sub> = SHA256(a<sub>sk,1</sub> || 0 || h<sub>Sig</sub> XOR h<sub>Nonce</sub>)
h<sub>2</sub> = SHA256(a<sub>sk,2</sub> || 1 || h<sub>Sig</sub> XOR h<sub>Nonce</sub>)

* This only adds 256 more constraints.
* Security against malleability is not reduced.
* h<sub>i</sub>'s relationship with h<sub>Sig</sub> still does not violate soundness/triviality properties

**Comment by nathan-at-least** [comment]
My preferred solution is to avoid altering the circuit, to remove CScript-style signatures of Pours, and to have a very restrictive tractable signature system, such as:

* Augment the transaction signature hashing scheme so that ``SIGHASH_ALL`` covers all Pour bytes, excluding signatures which live in separate fields.
* Define the ``info`` parameter from the Zerocash paper Fig 2 to be identical to the ``SIGHASH_ALL`` hash of the transaction.
* Generate a unique key pair and sign the message exactly as described in Fig 2 of the paper.

This removes a lot of ambiguity and is much easier to argue preserves the paper's security assumptions.  The devil is in the details of the first bullet point.

This would sacrifice some signature flexibility that the Calgary Snowflake CScript signature scheme may allow, but without further investigation, I feel the least uncomfortable with this tradeoff.

**Comment by ebfull** [comment]
I'm not happy with such a reaction to this flaw, I think it's misunderstanding the implications.

The zerocash paper assumes that pk<sub>Sig</sub> is ephemeral and unique. Users can choose not to use ephemeral keys if they want in the original implementation anyway, and they still will leak *new* information. I can even think of a concrete and useful protocol which would leverage this property. As a result, this is perhaps a flaw in the paper itself, and so I will bring this up with 7S now. I don't even need to mention our `CScript` infrastructure.

Remember that we intend to use `CScript` effectively in the same way as the paper in our actual wallet. This privacy leak only affects users that are doing unsupported things. It would affect them regardless of our use of `CScript`.

Removing the `CScript` infrastructure from pours takes away the numerous benefits that we agreed during the redesign. It handles canonicality for us. It performs the signature hashing for us. Our delta minimization from upstream is small, as we can craft our logic alongside Bitcoin's, instead of creating a special case. That is not even mentioning the cool things you can do with it -- which you must opt into as a user.

**Comment by ebfull** [comment]
After getting some initial feedback from 7S, I want to reiterate that this specific privacy flaw has very little to do with the `CScript` changes we made, and so I slightly regret bringing it up in the first place. About the only thing `CScript` complicates is that it hands carte blanche flexibility to our users, and that we're more responsible if they misuse it than if there were less knobs for them to turn.

Personally, I'm convinced that if we don't make this circuit change soon, we will have to restrict our API in the way @nathan-at-least has proposed, and contemplate a circuit change after launch which meets the privacy standards we want. This would be really unfortunate because it's a huge thing to ditch just because we couldn't make a very simple change to the circuit, and circuit changes aren't exactly free after launch. They are logistical nightmares.

I think we can hold off on cryptographic binding to pours (#529) in the interim while we sort this out.

**Comment by nathan-at-least** [comment]
> About the only thing CScript complicates is that it hands carte blanche flexibility to our users, and that we're more responsible if they misuse it than if there were less knobs for them to turn.

This is precisely the issue, though. When you say "users can still use keys" that's glossing over the difference of two platforms.  In one platform there's a CScript, which is a scripting engine designed intentionally for users to write custom scripts.  In the other, the wallet is responsible for generating fresh keys and doing a signature in the way described in the paper.

In the second case, different wallet implementers may make security-compromising decisions like "I'll reuse the keypair here, even though the paper, reference wallet, and protocol specification require the use fresh ones" -or "I'll let the user plug in keys here", but that's quite different than saying "Here's an arbitrary CScript field, except if users reuse scripts here it will compromise their security."

I'd also like to revisit the benefits of using CScript itself for "flexible user-defined integrity". I know that I accepted this approach for the current design. Now however, I want us to have a clear rationale for the feature, or to revert it in order to match the paper as closely as possible.

@ebfull, I'm not sure what you mean by canonicality. As for hashing, we can perform the hashing we need by calling ``SignatureHash`` directly with specific flags, and this must be done whether or not we involve CScript system or not.

Part of my problem here is that I'm not very familiar with applications that rely on malleable parts of transactions, so it's hard for me to weigh their benefit against a simpler system with a clear restrictive protocol that everyone can reason about. Can we come up with specific use cases to motivate this complexity?

**Comment by ebfull** [comment]
> I'm not sure what you mean by canonicality.

    1) Public keys must be either 65 or 33 bytes long.
    2a) 65 byte long public keys must start with one byte prefix 0x04
    2b) 33 byte long public keys must start with one byte prefix 0x02 or 0x03
    3) Any other byte sequences can not be treated as public key

They've also made other changes to reduce malleability of ECDSA pubkeys and signatures.

> Can we come up with specific use cases to motivate this complexity?

One use case is trying to perform a crowdfunding transaction. In Bitcoin, everybody can send money to a particular entity in an all-or-nothing transaction. In order for this to work, inputs cannot sign other inputs, so that new inputs can be added arbitrarily. This is [SIGHASH_ANYONECANPAY](https://en.bitcoin.it/wiki/OP_CHECKSIG#Procedure_for_Hashtype_SIGHASH_ANYONECANPAY).

If we use the procedure described by the paper, neither pours nor new inputs can be added to transaction unless it's by the creator, which is very restrictive. Further, the creator of the transaction has to keep the ephemeral key around just long enough to sign the transaction after it has been fully constructed, which does not jive well with our current design: we zcrawpour onto a rawtx, and users sign the result.

There is just no way to make this work nicely without the flexibility of `CScript`s. That's why the original implementation could only do one thing and had to do it all at once in the RPC. Imagine trying to get cryptographic binding working nicely with chained pours.

Remember that users have to opt-in to this madness manually, and it only impacts their transactions if they do.

**Comment by ebfull** [comment]
For the record, it's possible to get this to work without `CScript`s, but it's really throwing the baby out with the bath water.

**Comment by daira** [comment]
I agree with everything @nathan-at-least has said here. TBH I never liked the ``CScript`` signing stuff in Bitcoin, so I'd like our Zcash integration to depends on it as little as possible, otherwise it will be horrendous to analyse.

**Comment by daira** [comment]
The "a<sub>sk,i</sub> XOR hNonce" scheme makes me slightly nervous, because it may be difficult to prove this is a secure hiding commitment based on any standard assumption about SHA256Compress.

**Comment by daira** [comment]
I have an alternative suggestion: we already need to define a unique txid for use in the Faerie Gold fix. Suppose txid = CRH("txid", sn<sup>old</sup><sub>1..N<sup>old</sub>), which is guaranteed to be unique because otherwise the transaction would be detected as a double-spend.

Then define h<sub>Sig</sub> := CRH("hSig", txid, pk<sub>sig</sub>).

This fixes the linkability problem without requiring changes to the circuit: h<sub>Sig</sub> is still based only on public information as required, but it is now tied to the transaction. Furthermore it is tied to the transaction in a way that we already need to prove secure, so it is not adding incidental complexity to the security proof.

I am still highly skeptical about using CScript signing in the Pour signatures, but this disentangles the decision about that from the linkability issue.

**Comment by ebfull** [comment]
* "a<sub>sk,i</sub> XOR h<sub>Nonce</sub>" doesn't *need* to be a secure hiding commitment, the reason why we're hiding h<sub>Nonce</sub> is so that we don't need to include it in the transaction. Otherwise we would just hash it against h<sub>Sig</sub> as part of the consensus rules.
* The `CScript` stuff is actually pretty simple, and yes the Bitcoin maintainers understand it. In our scheme, it's the pour creator placing a constraint on the transaction. We're using the scripting system to enforce the original zerocash paper's constraint (that the transaction is not malleable) whereas if we didn't use the scripting system we'd have to do that all manually anyway. And we get none of the flexibility we will eventually want. (I consider not using CScript in this instance to be a complete flaw.)
* There's a problem with your use of `pourid` in this scheme and it's the same problem as if we had XOR'd a<sub>sk</sub> with `sn` or another field: two pours on the *blockchain* would have distinctness for h<sub>i</sub> but that isn't private enough. We don't want any two pours to have the same h<sub>i</sub> because you could end up leaking privacy in off-chain protocols.

**Comment by ebfull** [comment]
I would feel somewhat comfortable throwing away the `CScript` stuff as @nathan-at-least *if* we still agree to fix the circuit in this respect.

**Comment by daira** [comment]
My proposal doesn't require a circuit change at all, because the checking of h<sub>Sig</sub> is outside the circuit.

**Comment by ebfull** [comment]
> My proposal doesn't require a circuit change at all, because the checking of h<sub>Sig</sub> is outside the circuit.

As far as I can tell, the faerie gold vulnerability fix doesn't require that φ be available outside the circuit. (And hence, φ would be similar to my nonce.)

The goal is to prevent a transaction from producing the same ρ in two `Coin`s. This is accomplished by enforcing ρ to be computed as H(sn<sub>old,i</sub> || φ). In order for the Pour to produce the same ρ, they will have to reuse sn<sub>old,i</sub> and (their chosen) φ. But reuse of sn<sub>old,i</sub> violates consensus checks. Thus, ρ is guaranteed to be unique in any valid transaction.

Your proposal here appears to elevate φ to a deterministic, public construction (unless I don't understand the faerie gold fix). Are there any negative consequences to that? I'm not entirely confident that won't cause more issues or privacy leaks than just adding a secret nonce to the h<sub>i</sub> construction.

**Comment by ebfull** [comment]
I'm happy with h<sub>Sig</sub> = SHA256(pk<sub>Sig</sub> || sn<sub>old,1</sub> || sn<sub>old,2</sub>) instead of a circuit change. I was concerned before along the lines of #679 but upon further thought this is fine.

**Comment by nathan-at-least** [comment]
I haven't yet taken the time to understand either @ebfull's ``h_nonce`` proposal nor Daira's proposal which dovetails with Faerie Gold protection, but before I do I just want to reiterate my primary stance: any deviation from the paper is *very high risk*. It's the product of many expert-cryptographer-years of effort, peer reviewed, and published. Every deviation risks security flaws which could undermine that massive expert effort.

Meanwhile, the Faerie Gold vulnerability is an example that *even after* all of that expert review, there may still be security flaws.

My vision is that after we launch if Zcash has a market cap of billions of dollars and thousands of engineer / cryptographer / expert eyes on it, *then* would be a good time to propose upgrades. Right now, with just our tiny team I'm afraid we have too much ground to cover and too high a risk. (Also if we focus on upgrades after have a large userbase we'll know what the big picture use case needs are an we can prioritize among those.)

One parting thought is that I don't feel like our current public alpha design is bad by any stretch. I think it's awesome and useful, and I agree in principle with the idea of more flexible signature schemes. If I knew we could get a lot of heavy review on it so that we'd be very confident in its security, then I would want to proceed with it.

I also think that scaling back from a working featureful design isn't throwing away that design's value, because now we have a very clear picture of this area of the design space, we know it's plausible to implement, how to implement it, and we know about some of the use cases we're precluding by scaling back. Those are all valuable things to know which we might now know if we just implemented the scaled-back design first.

**Comment by ebfull** [comment]
@nathan-at-least We do not need to consider this change for 1.0. We can make this change in the future in a hardfork. Daira's solution does not require a circuit change and is trivial to analyze and will not increase transaction size.

**Summary**: h<sub>i</sub> is calculated as <b>H(a<sub>sk,i</sub> || h<sub>Sig</sub>)</b> within the circuit. The problem is that if h<sub>Sig</sub> were repeated in two pours (which violates an assumption of the paper) the circuit will leak via h<sub>i</sub> the fact that both pours spent with the same a<sub>sk,i</sub>, if that were the case. We can still allow h<sub>Sig</sub> to be a commitment to pk<sub>Sig</sub> (as the paper requires) *and* ensure it is distinct to every transaction by redefining it outside the circuit to be <b>SHA256(pk<sub>Sig</sub> || sn<sub>old,1</sub> || sn<sub>old,2</sub>)</b>.

**Comment by daira** [comment]
I agree that deviations from the paper *might be risky in general*. This particular one doesn't seem risky. It's solving the <sub>h_Sig</sub>-uniqueness issue in precisely the same way we solve the ρ-uniqueness issue; the latter of which we have to do anyway.

The advantage of this solution from an analysis point of view is that it's not introducing any extra variable that needs to be confidential or for which we need to ensure integrity.

**Comment by daira** [comment]
@ebfull h<sub>Sig</sub> will only be the same if all input coins are the same between Pours, and in that case an attacker already knows that all a<sup>old</sup><sub>sk,i</sub> must be the same between Pours. Therefore no *additional* information is leaked in my solution beyond that already considered in #679. (Actually I filed #679 in response to this ticket.) But it was a good question.

**Comment by daira** [comment]
I don't know why "in 1.0" was removed. Although we *could* do this in a hardfork, I'm not sure why we'd want to leave it for that.

**Comment by ebfull** [comment]
@daira We don't really need it for 1.0, since 1.0 won't allow pk<sub>Sig</sub> to be flexible per @nathan-at-least's conservative approach for launch. I think we need to talk about this at an engineering meeting.

**Comment by daira** [comment]
I think it would be a good idea, and improve the robustness of the protocol, to apply the uniqueness enforcement to all of the random variables that the security proof assumes are chosen uniquely per transaction.

**Comment by daira** [comment]
The current proposal is https://github.com/Electric-Coin-Company/zcash/issues/98#issuecomment-177931795

**Comment by daira** [comment]
This currently "comes for free" with my preferred Faerie Gold fix.

**Comment by ebfull** [comment]
I agree. This makes no sense not to fix now.

**Comment by daira** [comment]
In the viewing keys proposal at https://github.com/zcash/zips/tree/406.viewing-keys.1/protocol , @earthrise and I made another change that slightly interacts with this: the computation of h<sub>Sig</sub> takes another randomSeed input. This should ensure it is unique even between transactions which are not yet on the blockchain and therefore can spend the same input coins.

**Comment by nathan-at-least** [comment]
I just noticed another benefit of using asymmetric signatures directly (as in the paper) rather than the Script system: resource limits and miner prioritizations.  (I don't know how compelling either argument is, though.)

A nice benefit of snark verifications is they all use the same amount of verification resources (since they are indistinguishable). So because of this, it's easy to estimate their verification resource requirements up-front. For the Script system, this is a bit more fiddly, especially with branching, and I assume there are only over-estimate heursitics like sigop counts.

Bitcoin limits total sigops (and maybe other kinds of script operations) per block to prevent "DoS" issues. These limits relate to block size non-linearly, I believe, so changing either requires carefully considering the other. The relationship between block size, max number of Pours, and therefore max Pour verification cost is more straightforward.

Also, as a miner, as your margins approach zero and you become sensitive to the costs of validating transactions, you may want to predict how costly it is to validate a transaction prior to attempting to do so. If a transaction has no Scripts and K pours, the validation cost is fairly simple to estimate (and I think it might just be O(K)). This means it's easy to divide total fees, F by K to determine if the fees would justify the effort of attempted validation.

Hm... as for block limits, maybe we still have a (distinct) problem here with the cost of SIGHASH_ALL hashes costing a super-linear amount in the number of TxIns in a transaction? (Does segwit remove that problem?)

Conversation snippet which lead to this: https://zcash.slack.com/archives/science-and-tech/p1457122566000964

**Comment by defuse** [comment]
While I was reading this issue I noticed lots of confusion between 1. The issue this ticket's title is about: making sure the h_i are distinct always for the same a_sk, which they aren't when h_sig is reused, and 2. Whether or not to use CScripts for the ephemeral keys. Despite the confusion I think we reached the correct conclusions.

**Comment by daira** [comment]
Fixed modulo https://github.com/zcash/zips/issues/36
