### ISSUE TITLE
Ensure we depend on sha2 0.10 (not 0.9.x) and metrics 0.21 (not 0.20.x)

### ISSUE THREAD

**Issue by daira** [zcash/zcash#6648]
This can be done by upgrading `bs58`, `ed25519-zebra`, and `metrics`. The immediate motivation for filing this ticket is to allow Zebra to remove exceptions they have in their `deny.toml` due to their `zcash_script` dependency: https://github.com/ZcashFoundation/zebra/pull/6624/files#r1187912655 , but it also deduplicates the `sha2` dependency for us.

**Comment by daira** [comment]
`bs58` is upgraded in `zcash_address` 0.3, and metrics (and related dependencies) in #6699. There is no release of `ed25519-zebra` that includes the `sha2` upgrade yet, though (see https://github.com/ZcashFoundation/ed25519-zebra/issues/79).

**Comment by nuttycom** [comment]
Fixed in #6705
