### ISSUE TITLE
z_sendmany crashes zcashd

### ISSUE THREAD

**Issue by buck54321** [zcash/zcash#6654]
On version 5.5.0. Starting with a fresh regtest node.
```bash
zcashd -regtest -printtoconsole -nuparams=5ba81b19:1 -nuparams=76b809bb:1 -nuparams=2bb40e60:1 -nuparams=f5b9230b:1 -nuparams=e9ff75a6:2 -nuparams=c2d6d0b4:3
```
```bash
# coinbase maturity = 100
zcash-cli -regtest generate 110
zcash-cli -regtest z_getnewaccount
zcash-cli -regtest z_getaddressforaccount 0
zcash-cli -regtest z_listunifiedreceivers "unified_addr"
# pick out the transparent address and send to ourselves to de-coinbase utxos.
zcash-cli -regtest sendtoaddress "t_addr" 50
zcash-cli -regtest generate 1
zcash-cli -regtest z_getaddressforaccount 0 '["orchard"]'
zcash-cli -regtest z_sendmany ANY_TADDR '[{"address": "orchard_addr", "amount": 2}]' 1 null AllowRevealedSenders
```
zcashd crashes with
```
zcashd: wallet/wallet_tx_builder.cpp:382: auto WalletTxBuilder::GetChangeAddress(CWallet &, const ZTXOSelector &, const SpendableInputs &, const Payments &, const TransactionStrategy &, bool)::(anonymous class)::operator()(const AccountZTXOPattern &) const: Assertion `addr.has_value()' failed.
Aborted (core dumped)
```

**Comment by sellout** [comment]
Sorry for this crash. Thanks for reporting, and we’re working on a fix.

However, this should only occur when the transaction isn’t valid anyway. In this case what’s happening is that the `z_sendmany` will result in change being sent to a taddr, but `AllowRevealedSenders` doesn’t allow change to taddrs. This tx requires `AllowFullyTransparent`.

That adjustment should avoid the crash, but I think this transaction is still unlikely to succeed. `ANY_TADDR` will only select non-coinbase UTXOs from non-UA taddrs, but it seems like you want it to select from `t_addr`, which is a UA receiver, so you would need to use the UA as the fromaddress. If you simply want to shield the original coinbase UXTOs, then `z_shieldcoinbase '*' orchard_addr` should do it (and doesn’t require `AllowRevealedRecipients`).
