### ISSUE TITLE
RPC doesn't allow multiple outputs to the same address

### ISSUE THREAD

**Issue by ebfull** [zcash/zcash#666]
`zcrawpour` currently takes an object for the outputs where it should take an array.

**Comment by ebfull** [comment]
Upstream's `createrawtransaction` doesn't support this either, is there a reason for that?

**Comment by ebfull** [comment]
This is not critical for 1.0, imho.

**Comment by nathan-at-least** [comment]
I believe this is wontfix, because we will remove that interface in our Beta, and we should ensure the new interface doesn't have the same flaw.
