### ISSUE TITLE
CI: installing cross dependencies does not first run `sudo apt update`

### ISSUE THREAD

**Issue by daira** [zcash/zcash#6706]
I believe this is probably what is causing the build failures on ARM64. The problem is here:
https://github.com/zcash/zcash/blob/fa3827656df8f97fb4700b22022cc581fbda61fa/.github/workflows/build.yml#L59

**Comment by str4d** [comment]
Yep, I started having a similar issue with `rage` in the last few days (maybe something changed about how GitHub's runner images are configured), and fixed it similarly: https://github.com/str4d/rage/pull/396
