### ISSUE TITLE
Buy a new domain for stuff we don't control

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#672]
I've started handing out subdomains to whoever asks on IRC for use in their projects. So far the only one is `testnetfaucet.z.cash`. Sean pointed out that this enables attacks on other z.cash stuff and I agree with him so we should buy a different domain to hand out subdomains for.

**Comment by zookozcash** [comment]
@defuse Can you easily do the domain-name-buying job, or should we ask @mlbaily to do that? I'd suggest that the domain name be human-meaningfully different from "Zcash" in addition to being "same-origin policy" different, so maybe get something like "zcash-contributions.org".

**Comment by defuse** [comment]
I bought `zcash-contributions.org` using the enom account and hooked it up to AWS's Route53 if we ever need to use it.

**Comment by defuse** [comment]
I deleted `testnetfaucet.z.cash` and added `testnetfaucet.zcash-contributions.org`. @ebfull can you change the URL in the IRC topic then close this?

**Comment by ebfull** [comment]
Done
