### ISSUE TITLE
getblocksubsidy with v5.6.0 does not work as expected

### ISSUE THREAD

**Issue by cryptooliko** [zcash/zcash#6727]
### Describe the issue
In the new version of zcash v5.6.0 when I call getblocksubsidy without params, get error:
`{"result":null,"error":{"code":-32602,"message":"Not enough parameters for method `getblocksubsidy`. Needed exactly 1, but received 0\n\ngetblocksubsidy height...`

before this version that was work as expected, return:
```{"result":{"fundingstreams":[{"recipient":"Electric Coin Company","specification":"https://zips.z.cash/zip-0214","value":0.21875000,"valueZat":21875000,"address":"t3dN8g9zi2UGJdixGe9txeSxeofLS9t3yFQ"},{"recipient":"Zcash Foundation","specification":"https://zips.z.cash/zip-0214","value":0.15625000,"valueZat":15625000,"address":"t3dvVE3SQEi7kqNzwrfNePxZ1d4hUyztBA1"},{"recipient":"Major Grants","specification":"https://zips.z.cash/zip-0214","value":0.25000000,"valueZat":25000000,"address":"t3XyYW8yBFRuMnfvm5KLGFbEVz25kckZXym"}],"miner":2.50000000,"founders":0.00000000},"error":null,"id":"curltest"}```

so, I suspect, that in new version you broke some how rule:
"Arguments:
1. height         (numeric, optional) The block height.  If not provided, defaults to the current height of the chain."

#### If so, please list the steps to reproduce below:
curl --user <user> --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getblocksubsidy", "params": [] }' -H 'content-type: text/plain;' http://127.0.0.1:8232/

### Expected behavior
 If not provided the block height, defaults to the current height of the chain.
curl --user <user> --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getblocksubsidy", "params": [] }' -H 'content-type: text/plain;' http://127.0.0.1:8232/

```{"result":{"fundingstreams":[{"recipient":"Electric Coin Company","specification":"https://zips.z.cash/zip-0214","value":0.21875000,"valueZat":21875000,"address":"t3dN8g9zi2UGJdixGe9txeSxeofLS9t3yFQ"},{"recipient":"Zcash Foundation","specification":"https://zips.z.cash/zip-0214","value":0.15625000,"valueZat":15625000,"address":"t3dvVE3SQEi7kqNzwrfNePxZ1d4hUyztBA1"},{"recipient":"Major Grants","specification":"https://zips.z.cash/zip-0214","value":0.25000000,"valueZat":25000000,"address":"t3XyYW8yBFRuMnfvm5KLGFbEVz25kckZXym"}],"miner":2.50000000,"founders":0.00000000},"error":null,"id":"curltest"}```

### The version of Zcash you were using:
v.5.6.0

**Comment by str4d** [comment]
Closed by #6728 in v5.6.1.
