### ISSUE TITLE
Zips: Justify coin commitment scheme in section 2.4

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#674]
If you're unaware that we're using the SHA256 compression function it looks kinda wonky, so add some justification there.

**Comment by daira** [comment]
Also "192 bit padding" is ambiguous; it should say "0<sup>192</sup>" if that's what it is.

**Comment by daira** [comment]
We're completely changing the coin commitment scheme in order to fix InternalH collisions (#738). We do need justification of the new scheme, but that goes in the "Differences from Zerocash" section of the protocol spec, and we don't need this ticket to track that.
