### ISSUE TITLE
Outdated zcashd Debian/Ubuntu documentation

### ISSUE THREAD

**Issue by metalworker2** [zcash/zcash#6742]
Sorry if this is the wrong place to share. I wanted to create this issue in the the docs [GitLab repo](https://gitlab.com/zcash-docs/zcash-docs) but when I tried registering for GitLab it wanted me to verify my identity with a payment method, phone number, and email address, and this was after I OAuth'd with GitHub and completed 4 captchas LOL. Not doing that. Maybe consider using a docs hosting platform that doesn't hate privacy? Anyways ...

I found these issues in the docs when I was following the instructions for installing on Debian/Ubuntu officially supported platform:

https://zcash.readthedocs.io/en/latest/rtd_pages/install_debian_bin_packages.html

## Issue 1. Out of date Debian version [fixed]

In the Zcash documentation, it says:

> Add the repository to your Buster sources

However, on the Debian website, it says:

> Debian 10 has been superseded by Debian 11 ("bullseye"). Security updates have been discontinued as of June 30th, 2022. 

https://www.debian.org/releases/buster/

Since it no longer receives security updates, you should probably not recommend people to use Buster, or consider it an "officially supported" OS version.

## Issue 2. Out of date onion address version [split to #6824]

> The repository is also accessible via Tor, after installing the apt-transport-tor package, at the address zcaptnv5ljsxpnjt.onion

However, if I visit this website in Tor browser, then I am met with an error message:

> The provided onionsite address is invalid. Please check that you entered it correctly.
> 
> Details: 0xF6 — The provided .onion address is invalid. This error is returned due to one of the following reasons: the address checksum doesn't match, the ed25519 public key is invalid, or the encoding is invalid.

Upon closer inspection I see that the given onion address is a Tor v2 address. According to the Tor project website:

> V2 onion addresses are fundamentally insecure. If you have a v2 onion, we recommend you migrate now. This is a backward incompatible change: v2 onion services will not be reachable after September 2021.

https://support.torproject.org/onionservices/v2-deprecation/

So this documentation is almost 2 years out of date! See related #6075 

## Issue 3. Deprecated signing key import method [split to #6825]

When I run the suggested command:

> wget -qO - https://apt.z.cash/zcash.asc | gpg --import
gpg --export B1C9095EAA1848DBB54D9DDA1D05FDC66B372CFE | sudo apt-key add -

The terminal says this message:

> Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).

It worked anyways, as far as I can tell. But since the terminal gives this warning and deprecation notice, maybe better to use the modern command for this.

## Issue 4. Expired feedback form [split to #6826]

At the top of the documentation page is a link that says "Leave feedback". The link leads a page that says:

> Sorry, the file that you've requested has been deleted.

https://docs.google.com/forms/d/e/1FAIpQLSf-QRiMN2IwoPKyei5N3vjfYTiay4a_1lXfW4rcbQZBnZ2tmg/viewform?usp=send_form

**Comment by jg777** [comment]
Anyone know where is the latest version of https://zcash.readthedocs.io/en/latest/rtd_pages/install_debian_bin_packages.html located?

**Comment by daira** [comment]
Issue 1 is fixed. I have split the rest into separate issues: #6824, #6825, and #6826.
