### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [zcash/zcash#676]
[An extra null pointer check is not needed in functions](http://dietmar-kuehl.de/mirror/c++-faq/freestore-mgmt.html#faq-16.8 "Do I need to check for NULL before delete p?") like the following.
* [PaymentRequestPlus::getMerchant](https://github.com/Electric-Coin-Company/zcash/blob/293e4f015b811a03e4059cab38c92e7b42978bcc/src/qt/paymentrequestplus.cpp#L189 "PaymentRequestPlus::getMerchant function")
* [Table::Open](https://github.com/Electric-Coin-Company/zcash/blob/293e4f015b811a03e4059cab38c92e7b42978bcc/src/leveldb/table/table.cc#L85 "Table::Open function")

**Comment by daira** [comment]
True, but the check is harmless (apart from the effect on coverage analysis), so I'd prefer to leave this unchanged unless upstream Bitcoin fixes it. Can you file an upstream ticket please?

**Comment by elfring** [comment]
Would you like to forward such an issue (if you have got an account for related tracking systems already)?

**Comment by ebfull** [comment]
Bitcoin lives here on github too: https://github.com/bitcoin/bitcoin.

**Comment by daira** [comment]
We'll fix this iff upstream does.
