### ISSUE TITLE
request: zcashd 5.7.0 on Docker Hub

### ISSUE THREAD

**Issue by mvpratt** [zcash/zcash#6776]
Would someone be willing to push the 5.7.0 docker image to Docker Hub?
https://hub.docker.com/r/electriccoinco/zcashd/tags

We use this for CI testing

**Comment by cshintov** [comment]
Needed the same. Built it myself using https://github.com/zcash/zcash/tree/master/contrib/docker.

**Comment by WISEPLAT** [comment]
Hi! You can try https://github.com/WISEPLAT/zcash 
I have compiled them.

**Comment by str4d** [comment]
Closed on October 13: https://hub.docker.com/layers/electriccoinco/zcashd/v5.7.0/images/sha256-767ca758d231c921a34d1542df6a3802bce4d34b382f898acf476e014b188239
