### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [zcash/zcash#678]
The variables "[fRequestShutdown](https://github.com/Electric-Coin-Company/zcash/blob/293e4f015b811a03e4059cab38c92e7b42978bcc/src/init.cpp#L111)" and "[fReopenDebugLog](https://github.com/Electric-Coin-Company/zcash/blob/293e4f015b811a03e4059cab38c92e7b42978bcc/src/util.h#L48)" should [use the data type "sig_atomic_t"](https://www.securecoding.cert.org/confluence/display/c/SIG31-C.+Do+not+access+shared+objects+in+signal+handlers "Do not access shared objects in signal handlers.") (instead of "bool").

**Comment by daira** [comment]
Agreed. This looks like an upstream Bitcoin bug; can you file a ticket there and link it from here, please?

**Comment by elfring** [comment]
How do you think about to forward such an issue (if you have got an account for related tracking systems already)?

**Comment by ebfull** [comment]
https://github.com/bitcoin/bitcoin

If you'd like to link this ticket, just put the URL of this ticket in the one from upstream.

**Comment by daira** [comment]
We'll fix this iff upstream does.
