### ISSUE TITLE
Update build-* for missing dependencies

### ISSUE THREAD

**Issue by slush0** [zcash/zcash#680]
Please update dependencies in build documentation. I'm currently unable to build binaries because of missing "cryptopp" (which is probably package libcrypto++-dev on debian), but this is not the first missing package and this trial and error method makes me crazy, especially when building on slow machine. Thanks!

**Comment by ebfull** [comment]
There is a `depends` tree which will download and install all of the necessary dependencies; in fact, for now, you must use this.

`make -C depends` or just `./zcutil/build.sh` to do it all.

**Comment by slush0** [comment]
Cool! Could you mention it in build-unix.txt? Would be very useful for others, too

**Comment by daira** [comment]
build-unix.txt has been removed.
