### ISSUE TITLE
Remove one of the fetch-params scripts.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#681]
We have a new python script for fetching parameters but we need to decide if it's acceptable to require python or not before we can fully accept it.

However, I want to avoid accepting "contrib"-style stuff that we don't fully support and test, so let's remove one or the other and fully support the remaining one.

**Comment by nathan-at-least** [comment]
@defuse and I just decided to temporarily remove the python ``fetch-params.py``.  We like it and prefer it, but we need to do a few things before we adopt it:

- ensure it's ok to rely on python
- we want regression tests in place first before we make a large-scale change, #682
- rewrite part of it to use python's builtin URL lib and sha256 (assuming those replicate all the features we want, like wget's ``--continue``)

**Comment by nathan-at-least** [comment]
Paging @eliteraspberries: sorry, we just removed your script, but we like it!  One thing which could help is to rewrite it using builtin python url fetchers (maybe urllib2?) and builtin sha256 instead of shelling out to other utilities. This can make it more cross-platform. Are you interested in this?

**Comment by defuse** [comment]
In standup this morning meejah told me urllib doesn't check certs and requests is better.

**Comment by nathan-at-least** [comment]
I just pulled and see only a single script, so I'm closing this.
