### ISSUE TITLE
Zcashd Audit for NU6 Release

### ISSUE THREAD

**Issue by nuttycom** [zcash/zcash#6860]
This is the same audit as zcash/zips#831, but I'm going to represent in the dag by having that issue block this.

**Comment by daira** [comment]
Merged into #831.

**Comment by nuttycom** [comment]
Completed by Least Authority.

**Comment by daira** [comment]
[Least Authority - Zcashd NU6 Updates Initial Audit Report.pdf](https://github.com/user-attachments/files/17573110/Least.Authority.-.Zcashd.NU6.Updates.Initial.Audit.Report.pdf)

**Comment by daira** [comment]
[Least Authority- ZCG Zcashd NU6 Updates Final Audit Report.pdf](https://github.com/user-attachments/files/17573128/Least.Authority-.ZCG.Zcashd.NU6.Updates.Final.Audit.Report.pdf)
