### ISSUE TITLE
full nodes cleanly handle blocks from newer versions as empty blocks

### ISSUE THREAD

**Issue by zookozcash** [zcash/zcash#688]
```
<adam3us> so i have been musing if one can create a new upgrade mechanism that
      is safe & fast, but protects old full nodes from funds loss on weak
      hashrate chain. this upgrade mechanism itself maybe deployable via
      firmfork (which forces SPV client upgrade) or possibly by hardfork
      which may not force SPV client upgrade.  [18:19]
<adam3us> it seems that part of the challenge is for safety hard-forks if used
      at all should be deployed well in advance. and yet future network
      capacity and decentralisation headroom is uncertain.  [18:20]
<MRL-Relay> [othe] why not just plan sheduled mandatory upgrades, once or
        twice a year?  [18:31]
<adam3us> [othe] funds loss risk
<adam3us> for example if fullnodes treated as an empty block devoid of
      transactions (except for coinbase) any block versions that are
      higher than it understands, we get a backwards compatible to SPV
      node firm fork. that means a fullnode would not accept payment, and
      miners would orphan (soft-fork) any blocks created on the old
      version  [18:36]
<adam3us> in this way, we could have a safe fast upgrade when consensus exists
      for it.  [18:37]
*** tjader (~tjader@189.60.218.22) has quit: Ping timeout: 272 seconds  [18:40]
<MRL-Relay> [othe] in monero too old nodes stop working (1 year currently),
        you are forced to upgrade, even if there was no protocol changes
                                        [18:42]
```

I love it! Related ideas:
- https://github.com/Electric-Coin-Company/zcash/issues/174 "transactions commit to blocks" (this idea of Adam's could be extended or converted to "transactions commit to block-version-numbers" ??)
- https://github.com/Electric-Coin-Company/zcash/issues/131 "Enable loud hard-fork detection"
- https://github.com/Electric-Coin-Company/zcash/issues/136 "checkpoints should explicitly declare transactions/blocks that are part of the history but would no longer verify"

Also all of this tag "future-proofing": https://github.com/Electric-Coin-Company/zcash/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22future+proofing%22+

**Comment by daira** [comment]
> for example if fullnodes treated as an empty block devoid of transactions (except for coinbase) any block versions that are higher than it understands, we get a backwards compatible to SPV node firm fork. that means a fullnode would not accept payment, and miners would orphan (soft-fork) any blocks created on the old version

How is this safe? It means that full nodes that don't understand the block version will not recognise that coins or UXTOs have been spent by transactions in that block.

**Comment by zookozcash** [comment]
Seems to be related to https://github.com/zcash/zcash/issues/131

**Comment by nathan-at-least** [comment]
This seems very similar to #171.

**Comment by daira** [comment]
@zookozcash @nathan-at-least How is this similar to #131 or #171?

**Comment by daira** [comment]
Closing as wontfix. @zookozcash, feel free to reopen if you want to defend this idea from a security point of view.
