### ISSUE TITLE
Clang 18's `intrin.h` is causing build errors on Windows

### ISSUE THREAD

**Issue by daira** [zcash/zcash#6922]
_Originally posted by @daira in https://github.com/zcash/zcash/issues/6910#issuecomment-2240103198_

> Clang 18's `intrin.h` is causing build errors on Windows. Seems related to https://github.com/llvm/llvm-project/issues/95133 (it's not that specific function, but it's the same error in the same header file).
>
> [...] It might be possible to work around it by a patch to the dependency / dependencies that use `intrin.h` (looks like just `libsodium`).

**Comment by str4d** [comment]
I confirmed that this issue is reproducible with `libsodium`'s current `master` branch, and opened https://github.com/jedisct1/libsodium/discussions/1413.
