### ISSUE TITLE
Update twitter link on zerocash-project.org

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#693]
Hey @tromer:

Could you make the twitter link on zerocash-project.org go to https://twitter.com/zcashco? Please make it a link like that not a follow button, if possible.

Also, who runs @zerocashproject? Whoever does should tweet from that account something like "Zerocash is being developed into a full-fledged digital currency. Follow @ZcashCo." and add a link to https://z.cash/ into the account's URL field (or bio).

**Comment by nathan-at-least** [comment]
We believe Zcash is prominent enough that anyone browsing zerocash-project.org can find us easily enough.
