### ISSUE TITLE
Investigate reward adjustment's effects on economics

### ISSUE THREAD

**Issue by ebfull** [zcash/zcash#697]
We've been advised to make the first difficulty cycle after a reward halving half of what it was before the adjustment, for game theoretical reasons. We should factor this into the founder's reward, which goes away after the first supply cycle, and thus would interact with our system differently (economically speaking) than a normal adjustment.

**Comment by daira** [comment]
@ebfull will link this ticket to the "Brad Templeton death spiral" ticket, and then close it.

**Comment by zookozcash** [comment]
https://github.com/zcash/zcash/issues/95
