### ISSUE TITLE
Protocol spec: document handling of zero-value coin input slots

### ISSUE THREAD

**Issue by daira** [zcash/zcash#700]
This is an important security-critical change to the circuit and protocol. If we get the details wrong then it could allow attacks that violate balance or (less seriously, but still contrary to the intent) allow distinguishing transactions with different numbers of real input coins.

The circuit change was implemented in https://github.com/Electric-Coin-Company/libzerocash/commit/ab777baa700cdc5069336eef86ecdf58cace4a43 , but I'm still not totally clear on some of the details &mdash; for example, precisely which checks are disabled when v<sup>old</sup><sub>i</sub> is zero.

@ebfull, can you write something for the Pour Proof section of the protocol spec about this, or explain it precisely enough for me to write that?

**Comment by ebfull** [comment]
`merkle_tree_check_read_gadget` can be initialized with a `pb_linear_combination` called `read_successful`. In the past this was `ONE` which resolves to the first variable of the constraint system (which is always one). This enforced equality of the merkle root with the root provided by the verifier (after unpacking).

Instead, I allocate a variable array `old_coin_enforce_commitment` which contains an entry for every input coin, and these are provided in place of the `ONE`.

The following constraints are added for all `i..num_old_coins`
* `1 - old_coin_enforce_commitment[i]` * `old_coin_enforce_commitment[i]` = `0` called the **boolean constraint** which requires it to either be zero or one. (If `read_successful` were larger than 1, I'm unsure if the behavior.)
* `pb_packing_sum(old_coin_value_variables[i])` * `1 - old_coin_enforce_commitment[i]` = `0` which forces `old_coin_enforce_commitment[i]` to be one if `pb_packing_sum(old_coin_value_variables[i])` is nonzero.

`pb_packing_sum(old_coin_value_variables[i])` is essentially an expansion of the bits (in little endian order) similar to what is done during the balance checks.

**Comment by ebfull** [comment]
I don't think things like linear combinations and so on are necessary for the protocol spec.

**Comment by daira** [comment]
Thanks for explaining this. (BTW I think you meant to put parentheses around ``1 - old_coin_enforce_commitment[i]`` in both places.) I agree it's not necessary to describe the implementation in terms of arithmetic constraints, but we do need to describe the effect. I think I have all the information needed to write that now.

**Comment by daira** [comment]
I wrote:
> If we get the details wrong then it could allow attacks that violate balance or (less seriously, but still contrary to the intent) allow distinguishing transactions with different numbers of real input coins.

#709 is an example of the latter.

**Comment by daira** [comment]
Moved to https://github.com/zcash/zips/issues/38
