### ISSUE TITLE
RPC command documentation

### ISSUE THREAD

**Issue by ebfull** [zcash/zcash#701]
Document the new RPC interface.

Here's the original description for posterity:

> We'd like people to experiment with the RPC to build cool mini wallets, wrappers to make things easier, etc. We should document our existing RPC commands better.
> 
> Also, we should make *new* RPC commands so that users don't need to exchange the encrypted buckets, which would allow more experimentation.
> 
> My proposal:
> 
> * zcrawscan (`zcsecretkey`, `height`=0) scans the blockchain for buckets spendable from this key starting at `height` and returns them all alongside their corresponding serials.
> * zcrawcheck (`serial`) returns whether or not the serial exists in `mapSerials` to show whether or not the bucket can be spent.
>
> (Some thought should be put into what buckets are returned from the mempool?)

**Comment by daira** [comment]
Let's convert the Google doc to markdown and put it under ``doc/``.

**Comment by bitcartel** [comment]
Google Doc can save as ODT and then we could use a Chrome browser plug-in to convert to MD or a tool like Pandoc.

**Comment by bitcartel** [comment]
Pandoc could not convert the tables from Google Doc to Markdown. Instead I used Github's wiki editor to create the document and then copy over the raw markdown into a file.
