### ISSUE TITLE
Extremely Minimal Wallet GUI

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#702]
Create a basic wallet GUI, which these explicitly minimal features:
- creates a single zcaddr pair if it doesn't already have one.
- displays the zcaddr encoding.
- displays a balance.
- has a "send transaction" feature that takes a zcaddr paste, and an amount.

Nothing else! Specifically:
- No support for multiple zc keypairs.
- No way to send to transparent addresses.
- No transaction history display.
- No passphrases or anything like that.

We'll add features later as they make sense.

There are at least three implementation alternatives:
- get `bitcoin-qt` building and working, rename it to `zcash-qt`, modify it to have our required features. (This may be a lot more work since the feature set above is explicitly restrictive, so we may need to disable many components.)
- make a new "built-in" gui that does not use RPC interface.
- write a new thing with implementation toolset of our choice which speaks to the RPC interface.

**Comment by daira** [comment]
@zookozcash will try to get an external wallet developer interested in doing this.

**Comment by nathan-at-least** [comment]
Note: We're interested in finding other parties who are motivated to make good wallets we can collaborate with. Or, we may make our own (although none of us are GUI/UX specialists, and we have limited bandwidth).

Either way *usability* is extremely important to us, especially as it interacts with security and protocol design, so we want to work closely on wallet implementations to promote particular usability/security choices.

**Comment by daira** [comment]
@zookozcash Did you contact any external developers about this?

**Comment by zookozcash** [comment]
I have contacted a couple of external developers, and will contact more.

I think @str4d/Vitalik's Python scripts satisfy this property, right?

**Comment by daira** [comment]
@zookozcash 's last comment was confusing this with #502.

**Comment by jprichardson** [comment]
> Either way usability is extremely important to us, especially as it interacts with security and protocol design, so we want to work closely on wallet implementations to promote particular usability/security choices.

This is incredibly important to us (http://www.exodus.io/) as well. We're planning on meeting with @zookozcash in April to discuss more on how we can help with this.

**Comment by zookozcash** [comment]
I think we should close this ticket, because [various others](https://zcashblog.wordpress.com/zcash-gui-wallets/) have made various wallet GUIs.

That's not to say that we shouldn't make one of our own in the future, but if we decide to do so we should re-open this ticket, and probably also modify it in consideration of the situation at that time.
