### ISSUE TITLE
Save four hashes in the circuit by simplifying definition of cm

### ISSUE THREAD

**Issue by daira** [zcash/zcash#704]
Currently,

k = CRH(r || InternalH)
cm = CRH(v || 0<sup>192</sup> || k)

where r is 384 bits, InternalH is 128 bits, and v is 64 bits.

We could change this to

cm = CRH(r || v || InternalH)

where r is now 320 bits. This would be modeled as cm = COMM<sub>r</sub>(v, InternalH); there is no more need for COMM<sub>s</sub>.

The reason for the nested commitments in the original paper was to allow Mint transactions to be verified without breaking indistinguishability (see section 1.3 Step 3 of the extended paper). But this is no longer necessary with unified Mint and Pour.

This saves four hashes in the circuit (one for each input and output coin). Four hashes are not to be sneezed at: if we choose a coin commitment tree depth of 48, for instance, then there are 48 + 16 (for checking coin commitments after the Faerie Gold fix) + 6 (for checking PRF<sup>{addr,sn,pk}</sup>) = 70 hashes in the circuit. So a saving of 4 hashes represents 5.7%, which is a rough estimate of the resulting improvement in proof time and memory. (There's also a 256-bit reduction in total witness size due to the change in size of r, but that's less significant.)

[Edit: I miscalculated this. There are 2 hashes per level of the commitment tree, one for each input coin. The current Faerie Gold fix requires 14 hashes to check coin commitments. So the number of hashes in the circuit is 48*2 + 14 + 6 = 116 for a commitment tree depth of 48, making the saving 3.45%. However this would increase proportionally if (only) the commitment tree used more SNARK-friendly hashes, as suggested in #40, or if the tree depth were less than 48.]

The drawbacks are:
* time to check that the security proof is still valid (I don't see any obstacles to this)
* it would be harder to switch back to separate Protects and Pours.

**Comment by ebfull** [comment]
Great observation and proposal! I was always curious why we needed this layering with the pour symmetry.

> We could change this to
> 
> cm = CRH(r || v || InternalH)
> 
> where r is now 320 bits. This would be modeled as cm = COMMr(v, InternalH); there is no more need for COMMs.

Why do we want InternalH to have 128 bits of security? Why should `r` be 320 bits? Is that not the wrong tradeoff?

**Comment by ebfull** [comment]
I've been thinking about this and I'm pretty happy. I think this would clear 7S review.

**Comment by daira** [comment]
@ebfull wrote:
> Why do we want InternalH to have 128 bits of security? Why should r be 320 bits? Is that not the wrong tradeoff?

My understanding is that the truncation to 128 bits is to ensure statistical hiding of the inputs to the InternalH hash, i.e. a<sub>pk</sub> and ρ:

> Section 4.1: "We use a commitment scheme COMM where the binding property holds computationally, while the hiding property holds statistically."
> Section 5.1: "Above, [·]<sub>128</sub> denotes that we are truncating the 256-bit string to 128 bits (say, by dropping least-significant bits, as in our implementation). Heuristically, for any string z ∈ {0, 1}<sup>128</sup>, the distribution induced by H(r || z) is 2<sup>-128</sup>-close to uniform, and this forms the basis of the statistically-hiding property."

I believe this only actually matters if coins are transmitted out-of-band, since if you're transmitting them on the blockchain using the key-private encryption, you're depending on cryptographic (not statistically secure) hiding of a<sub>pk</sub> and ρ anyway.

**Comment by daira** [comment]
The proposed fix for #738 includes this optimisation.

**Comment by daira** [comment]
Closing since #738 is sufficient.

**Comment by ebfull** [comment]
+1
