### ISSUE TITLE
setup slack↔IRC bridge.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#708]

**Comment by defuse** [comment]
It seems like sameroom.io is our best bet. It sends slack messages to IRC and IRC messages to slack. Everything else I saw was just one-way IRC->slack. I can't get it working with OFTC though... I briefly had it working with the old #leastauthority channel on freenode.

**Comment by defuse** [comment]
By the way, slack really does not support "working publicly as part of a community." You can't allow arbitrary people to join a channel in your slack without [implementing a fragile rube goldberg system that involves using some spreadsheet SaaS startup and writing custom code that uses undocumented Slack APIs](https://levels.io/slack-typeform-auto-invite-sign-ups/). The absolute best we can do is set up a connection between Slack and some other easy-to-join channel (like IRC).

**Comment by defuse** [comment]
Sameroom.io seems ideal for this, but I can't get it to connect to OFTC. I did test it briefly on Freenode, and it did exactly what we wanted... but it's refusing to connect to OFTC. That makes me wonder how reliable it will be even if I do get it to connect.

The next steps are: contact someone at sameroom.io to figure out why it's failing.

**Comment by defuse** [comment]
Zooko also said this to me: "@earthrise: potentially relevant to your discussion at standup this morning about "Slack as a public community channel": https://twitter.com/MattPRD/status/695731256772812800"

**Comment by defuse** [comment]
Unfortunately this isn't easily possible because `irc.oftc.net` is a "known unsupported network": https://sameroom.io/limitations

**Comment by defuse** [comment]
I propose we give up on this and not waste any more time on it, unfortunately.

**Comment by zookoatleastauthoritycom** [comment]
Ok!
