### ISSUE TITLE
understand the concrete security level of the BN_128 curve in libsnark

### ISSUE THREAD

**Issue by daira** [zcash/zcash#714]
Zooko writing: my current belief, after reading the expert discussion in the comments of this ticket, is that the strength of the `BN_128` curve is somewhere between 110 bits and 128 bits. It isn't clear to me if these strength level estimates are also implicitly allowing the attacker to call upon an infinite-sized, instantaneously-accessible, zero-cost RAM. If these estimates _are_ neglecting the costs of memory, then the effective safety of the `BN_128` curve may be even higher.

So for now, I'm satisfied that the `BN_128` curve is more than safe enough for our users' current needs. Of course, it wouldn't hurt to upgrade it to be even stronger in the future!

**Comment by ShenNoether** [comment]
Less than 128 bit if I am reading this correctly? https://ellipticnews.wordpress.com/2016/05/02/kim-barbulescu-variant-of-the-number-field-sieve-to-compute-discrete-logarithms-in-finite-fields/ (I haven't studied that much pairing crypto, so correct me if I have read this incorrectly / your parameters are different).

**Comment by zookozcash** [comment]
Thanks, ShenNoether! I am not equipped to evaluate this stuff myself, and am relying on elliptic curve crypto specialists to tell us if this is safe!

**Comment by ShenNoether** [comment]
@zookozcash no problem - the blog post popped up my feed this morning and I thought it may be relevant-  if I end up with some free time, I would definitely like to take a deeper look into the protocol more, but am quite busy atm.

**Comment by nathan-at-least** [comment]
It's my understanding there's a distinct potential attack against BN curves discussed in our meeting today: https://eprint.iacr.org/2008/300

We may want to either create distinct tickets or rename this ticket to encompass evaluating *all* security issues around the selection of BN curves.

**Comment by daira** [comment]
The post that @ShenNoether linked suggests that a 448-bit field size may be needed. We need to ask the Zerocash scientists to generate a suitable curve and implement it in libsnark soon, at the very least so that we can benchmark that field size.

**Comment by ebfull** [comment]
https://github.com/scipr-lab/libsnark/issues/29

**Comment by zookozcash** [comment]
@elibensasson posted on https://zcashcommunity.slack.com/messages/zcash/:

```
Regarding curve information: In http://eprint.iacr.org/2013/879.pdf on top of page 15...
and footnote 6 there for explanation why high 2-adic order is helpful. but iirc the order we settle on is not that high, like 20, 30 or so (will look more)
and in this older paper https://eprint.iacr.org/2013/507.pdf we describe the requirements for the curves, see page 23 there
the curve there has a group of order p such that p-1 is divisble by 2^20' and this useful for efficiently computing certain required polynomials
see page 25 there
```

**Comment by nathan-at-least** [comment]
What is the security level of BN128 given known attacks?

**Comment by daira** [comment]
The table at the end of https://ellipticnews.wordpress.com/2016/05/02/kim-barbulescu-variant-of-the-number-field-sieve-to-compute-discrete-logarithms-in-finite-fields/ send to suggest that there is a 29-bit difference in security level between a 256-bit and a 448-bit field; the latter is what the author recommends for 128-bit security. A 256-bit field would have a ~99-bit security level if that is correct; note however that this calculation is based just on evaluating the asymptotic complexity without making a detailed estimate of whether the constant factor changes between those field sizes.

**Comment by zookozcash** [comment]
We decided (it was my call to make) that BN_128 is safe enough for Zcash “Sprout” 1.0. I think we should upgrade it eventually. (To do so will require what blockchain specialists call a "hard fork" — new transactions are accepted by the new software but rejected by the old software — but _not_ what the blockchain enthusiasts and the press call a "hard fork" — contentious, acrimonious, and resulting in two separate communities each with their own blockchain. ☺)

**Comment by burdges** [comment]
Assuming there are no risks to the anonymity here, an alternative to changing curves would be instituting a cap on the maximum value in a transaction or account so that attacks cannot be profitable.

There are practical issues in that attacks costs are denominated in USD, EUR, etc., and the exchange rate should fluctuate, but 96 bits should give a safe margin for quite a while.

**Comment by daira** [comment]
@burdges wrote:
> Assuming there are no risks to the anonymity here, an alternative to changing curves would be instituting a cap on the maximum value in a transaction or account so that attacks cannot be profitable.

That cannot work for an anonymous/private cryptocurrency. Nothing prevents an adversary from just repeating the attack arbitrarily many times. We did consider a transaction limit (#141), but decided (in discussions that are not reflected on the ticket) that it had very limited usefulness and would not be in Zcash 1.0.

**Comment by daira** [comment]
Note that the cost of violating balance for N transactions is not necessarily N times larger (or even any larger at all) than for one transaction. Precomputation attacks are possible for other DL-based protocols and I would conservatively assume they are possible here. I also suspect that the best approach is to attack the parameters rather than the point multiplications used in any particular proof.

**Comment by burdges** [comment]
Right, I had not considered precomputation attacks, thanks.  :)  Yeah, I suppose your parameters are particularly subject to precomputation attacks.  I suppose the total market capitalization of zcash would need to remain below the cost of an attack or something.

**Comment by daira** [comment]
That would be the conservative approach, yes. In practice an adversary is unlikely to be able to realise the entire market cap of Zcash before the attack, even if they can arbitrarily violate balance.

**Comment by zookozcash** [comment]
According to [Trevor Perrin's summary ](https://moderncrypto.org/mail-archive/curves/2016/000740.html), 

> However, Kim and Barbulescu showed that DLP where the modulus is a
> 3072-bit (prime^12) is easier than DLP for a 3072-bit prime.  How much
> easier isn't clear, though by a "crude and naive estimation" they
> suggest increasing the size of relevant curves by a third (Section 6).
> Mehdi Tibouchi has a similar estimate [22]:  "after this attack,
> 256-bit Barreto-Naehrig curves no longer offer 128 bits of security,
> but perhaps closer to 96 or so".

**Comment by zookozcash** [comment]
http://eprint.iacr.org/2016/1102.pdf

I skimmed this, and asked Matt Green what it meant.

From the paper:

> In summary, if one is aiming for the 128-bit security level, then the bitlength of p should be at least 383, 384, 342 and 320 for BN, BLS12, KSS and BLS24 pairings.

So I said "But what then is the estimated strength of the BN_128 curve that we are currently using?

Matt wrote:

> Probably 96-100 bits which is still well in excess of RSA-2048. To be prudent we should probably upgrade within a year or so.

**Comment by palsarkar** [comment]
As per our calculations, BN curves with a 256-bit prime provides 110-bit security. See Remark 6 at the end of Section 6.3 in the updated version of our paper at http://eprint.iacr.org/2016/1102.

**Comment by arielgabizon** [comment]
@palsarkar This seems quite speculative to me..you're saying if all kinds of constants that we don't know much about are all 1 we get only 110-bit security.

**Comment by tromer** [comment]
A better methodology for estimating performance of such algorithms is to concretely execute them on moderately-sized inputs (as large we one can afford), and then _extrapolate_ to the large, target parameters using the asymptotic behavior. This implicitly and automatically calibrates many of the unknown constants, and gives good accuracy (in practice, when applied to other NFS variants).

Moreover, some NFS parameters can be practically computed for the large target parameters (e.g., NFS polynomial selection). This allows for finer extrapolations, just for the remaining aspects of the algorithm instead of monotonically, yielding more precise estimates.

See http://cs.tau.ac.il/~tromer/papers/factorest.pdf for a detailed example of how this works, in that case for factoring 1024-bit RSA using NFS.

**Comment by palsarkar** [comment]
@arielgabizon: Section 6.1 of http://eprint.iacr.org/2016/1102 provides some experimental evidence that the actual norm values are close to the expressions for the norm bounds without the constants. The title of our paper starts with "Challenges ..." indicating our position that it is difficult to come up with accurate estimates of key sizes for an algorithm which is as complex as the NFS. So, our figures are meant to be conservative estimates.

**Comment by arielgabizon** [comment]
Thanks @palsarkar if I understand correctly, the 110-bit security is assuming the quantities lg V f and lg(hat(N)f) in table 3 are identical for the relevant field F_p^k.
But the latter seems larger by 30-60 than the former for lg p= 256

**Comment by palsarkar** [comment]
@arielgabizon: The values in Table 3 corresponding to lg p = 256 are for n=18. Table 3 does not provide values for n=12 and lg p = 256. An estimate of security using average of 1000 values of the actual norms is about 112 bits, which is 2 bits more that the 110 that we obtain using the expressions without the constants.

**Comment by arielgabizon** [comment]
Ohh.. I assumed you were extrapolating from that result and did not have results for n=12.
Can those numbers be found somewhere?
Better still, is there can code somewhere that we can modify to test for n=12 and the p we are actually using right now,
i.e., p=21888242871839275222246405745257275088548364400416034343698204186575808495617

**Comment by palsarkar** [comment]
Shashank wrote the programs. You may approach him for the code. The present version of the code may not be using this particular value of p, but, it would be easy to modify the code to use this p. The results are expected to depend on the bit size of p rather than its actual value.

**Comment by arielgabizon** [comment]
Thanks, perhaps I will contact him soon, but let me ask something else meanwhile, if that's OK.
If I understand correctly, the estimate 112 means - 
under the assumption that for all** phi the norms N(f,phi) and N(g,phi) are always at most 2^112  ,
and that the probability of smoothness is as in integers as you say and the smoothness events are independent as you say in sec 5.4,
then the number of trials to find phi s.t N(f,phi), N(g,phi) are B-smooth for the desired B -(I am guessing 2^56 to balance out with linear algebra phase?)
is 2^112   .
But if talking in concrete numbers, don't you need to multiply by time to (attempt to) factor the deals phi(alpha)O_f and phi(beta)O_g ?
Is this negligible?



** this relates to a point I am not sure about in your result - the calculation in beginning of sec 6 seems to assume an upper bound an N(f,phi).  Is the number 112 assuming such upper bound , or just an average, in which case you need to assume something about the distribution on N(f,phi) over phi, and lose another factor from a markov or chernoff bound

**Comment by palsarkar** [comment]
@arielgabizon: Section 5.1 discusses several issues in the asymptotic analysis and highlights constants that get absorbed in the big-Oh expression. Smoothness checks and the operations for linear algebra computation including accessing a big matrix from memory all can take significant time and are not accounted for in the estimates. As I have previously mentioned, our estimates are conservative.

Upper bounds on the norms for exTNFS and SexTNFS are given by (7) and (10) respectively. These bounds have constant terms. We provide two kinds of estimates in the paper, one using the bounds (which takes the constants into account) and another using expressions for the norm bounds obtained by dropping the constants. The estimates without the constants are again conservative estimates. Experiments suggest that the average (over 1000 trials) of norms are closer to the values obtained without the constants. So, the estimates without constants are perhaps more meaningful than those obtained from the upper bounds.

For BN12 curves using a 256-bit prime, our estimate is 110 bits of security using values of norms obtained from the expressions without constants. This is reported in our paper. If instead, one uses the experimentally obtained average values for the norm bounds, then the security estimate is 112 bits. This last part is not reported in the paper.

**Comment by arielgabizon** [comment]
@palsarkar : I couldn't find anything in the paper about the cost of smoothness checks, so hope you don't mind if I ask again:
If I understand correctly,  in the most conservative scenario, you are taking B^2=E^2=2^110,
so B=2^55.
Now, in these 2^110 trials you need to do a B-smoothness check for N(phi,f) and N(phi,g)
Doesn't each such check take time at least B/log B, as this is the expected number of primes up to B?

**Comment by arielgabizon** [comment]
@palsarkar : I couldn't find anything in the paper about the cost of smoothness checks, so hope you don't mind if I ask again:
If I understand correctly, in the most conservative scenario, you are taking B^2=E^2=2^110,
so B=2^55. (or roughly that)
Now, in these 2^110 trials you need to do a B-smoothness check for N(phi,f) and N(phi,g)
Doesn't each such check take time at least B/log B, as this is the expected number of primes up to B?

**Comment by palsarkar** [comment]
@arielgabizon: The issue of smoothness checks is not discussed in our paper. For smoothness checking, trial division is not the method of choice. Either sieving or ECM will be used. See the discussion in Section 3 of http://eprint.iacr.org/2015/1027.pdf which also mentions the (asymptotic) cost. It is difficult to make a concrete estimate of this cost.

**Comment by arielgabizon** [comment]
Ohh right yeah that's naive..is it possible/is there some reference to a conservative estimate of the concrete cost for B=2^55.. e.g. if 2^18 was considered conservative than we'd be back to 128 bits :)

**Comment by palsarkar** [comment]
1. I do not know of any concrete estimate. 
2. Adding the concrete estimate of smoothness checks to reach 128 bits would perhaps not be proper since the estimate of 128-bit security obtained previously did not include the cost of smoothness checks. The lowering of security estimate is due to advancement of the NFS algorithm. The cost of smoothness checks in both the earlier variants and the new variants remain the same.

**Comment by zookozcash** [comment]
Okay, done! We've understood the concrete security level BN_128. Answer: _everyone_ agrees that it is at least 110 bits, and either everyone or almost-everyone agrees that if you counted all of the costs it would be at least 128 bits. Great! I pronounce it "good enough" and close this ticket. Special thanks to guest cryptographers @ghost and @palsarkar for your help.

**Comment by arielgabizon** [comment]
@daira : to address what you wrote on the top, the at least 110 estimate is assuming zero-cost RAM.
@zookozcash : I think that's a close enough description, and closing the ticket is reasonable.
 To more accurately describe how I view the "almost everyone agrees" part of what you wrote, I'm pasting here the footnote from Sean's blog post: https://z.cash/blog/new-snark-curve.html
`Menzes, Sarkar and Singh (http://eprint.iacr.org/2016/1102.pdf) show 2^110 is a conservative estimate for the size of the space of polynomials that needs to be scanned for smooth polynomials. However, for the case q=p^12 relevant for BN curves there is no currently published efficient method for scanning this space. (Checking each polynomial separately for smoothness would result in total running time larger than 2^128.) Thus, to the best of our knowledge the most efficient currently known fully described algorithm for breaking the curve Zcash is presently using is Pollard's rho, which would run in time sqrt(q)~2^127. (Our thanks to Palash Sankar and Shashank Singh for helping understand their result.)`

**Comment by daira** [comment]
BTW I agree with @palsarkar's comment "Adding the concrete estimate of smoothness checks to reach 128 bits would perhaps not be proper since the estimate of 128-bit security obtained previously did not include the cost of smoothness checks."

As I think I mentioned in a meeting, although it doesn't seem to have been recorded here, the usual way to measure concrete security level is to compare the attacker's cost with the cost of running the protocol for the legitimate users (e.g. of verification or proving), in which case 2<sup>110</sup> is roughly correct for a conservative estimate. It isn't usual to quote bit operations, for instance.

**Comment by arielgabizon** [comment]
@daira : The 128-bit estimate comes from Pollard's Rho Algorithm   https://en.wikipedia.org/wiki/Pollard's_rho_algorithm_for_logarithms, that shows the expected number of *group operations* on our curve for finding the discrete log would be very close to 2^128 for our curve.
  There are no smoothness checks there to include.
To get the 2^110 number, you have to, besides making some optimistic heuristic assumptions, omit not just cost of bit operations but the cost of checking whether a number is B-smooth, i.e., all it's prime factors are at most B, for B=2^55.
If you do this with, say, the elliptic curve method, which is considered a good method for such a task,
you would still have an added multiplicative factor of sqrt(B), taking you above 2^128,
and this is when counting a scalar multiplication on a curve as *one* operation.
It is possible that sieving methods would reduce the factor that needs to be added 
to 110, but there is no published work currently for the Tower NFS (which is the variant of NFS that gets the 110 number) that does these smoothness checks with sieving that is appropriate for BN curves where the field is of the form F_p^12

**Comment by daira** [comment]
You're right, I stand corrected.

**Comment by arielgabizon** [comment]
A new paper https://eprint.iacr.org/2017/334.pdf
claims our curve has only 100 bits of security.
This is also assuming the sieving time is not larger than the space to be sieved.

**Comment by arielgabizon** [comment]
8 years later, the tower number field sieve afaics has only been used to find discrete logs in a 512 bit field.
https://arxiv.org/pdf/2212.04999

While the record for discrete log in prime fields is currently for a 795 bit field:

https://eprint.iacr.org/2020/697.pdf


In other words, the [TNFS paper](https://eprint.iacr.org/2015/1027.pdf) that showed that *theoretically* medium prime fields of sizes like p^12 could have faster attacks, and consequently caused many to move to bls-381, has not been so far competitive with previous NFS algorithms under which bn254 was considered 128 bit secure.

I think this is very much related to the difficulties in figuring out how to efficiently sieve in larger dimensions alluded to in my above comments.
