### ISSUE TITLE
Create a use case document.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#72]
Let's track our supported use cases. Even with an MVP feature set, we already may support a different set of use cases than Bitcoin, due to the tradeoff between fungibility/privacy and (single node) transaction throughput.

Additionally it may contain "wishlist" use cases which would require the addition of wishlist features.

**Comment by daira** [comment]
https://github.com/Electric-Coin-Company/zcash/wiki/use-cases does not exist. Where did the content that @nathan-at-least mentions [above] (https://github.com/Electric-Coin-Company/zcash/issues/72#issuecomment-75588911) move to?

**Comment by nathan-at-least** [comment]
Let's close this. My new belief is that it's better to wait to see how real life people use the real-life launched Zcash, and *then* to document common use cases.
