### ISSUE TITLE
Make Zcash t-shirts

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#720]
Design a shirt and find a way to get them printed. We should remember to have the design in both men's and women's styles.

**Comment by mlbaily** [comment]
We have used Custom Ink in the past if you want to check them out.

Margaret

On Wednesday, February 10, 2016, Taylor Hornby <notifications@github.com>
wrote:

> Design a shirt and find a way to get them printed. We should remember to
> have the design in both men's and women's styles.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Electric-Coin-Company/zcash/issues/720>.
>


-- 
Margaret Baily
Executive Assistant
Least Authority/Zerocoin Electric Coin Company

**Comment by daira** [comment]
The initial batch of t-shirts have been ordered.
