### ISSUE TITLE
Rebase to upstream version later than 0.11.2

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#727]
Here's the high-level change summary: https://github.com/bitcoin/bitcoin/blob/0.12/doc/release-notes.md#notable-changes A detailed changelog with all PRs below that section.

Of the large-scale feature changes, a few seem especially relevant for us:
- using libsecp256k1 for signature verification (also removing openssl support in the RPC interface) - this helps us move away from openssl dependency via upstream.
- tor "hands-free" hidden service setup and use - we want this kind of feature for our intended Tor use anyway (since manual configuration is a barrier to entry and we want privacy-by-default).
- I can't tell yet if this release has code which will enable CLTV _iff miners signal to softfork it in_ or if that already happened and this release implements CLTV support unconditionally. We may want to hardwire in the latter, or we may leave vestigial softfork-transition code in place on a theory that every change from upstream carries risk.

Potentially risky feature interaction:
- pruning - I believe so long as pruning doesn't break our spent-serials set nor any of our undo/reorg requirements, it is fine. Something to keep in mind. (Also, it's not possible to prune our spent-serials yet, AFAIK, so our "pruning mode" will be a slight misnomer.)
- replace-by-fee - It seems that a spender could use RBF as designed while replacing Pours _at a loss of privacy_. In fact, each bumped `nVersion` will be a distinguisher, splitting the anonymity set between "no-RBF", "RBF with 0 replacements", "RBF with 1 replacements", etc... Aside from this privacy degradation, I can't think of any functionality/correctness problems with interacting Pours/RBF. Any other issues?

**Comment by daira** [comment]
We can't rebase since there are too many consensus changes upstream. So far our strategy had been to pull in groups of PRs, and it seems to work reasonably well &mdash; although it is quite difficult to keep up using that approach.
