### ISSUE TITLE
Clarify sending/receiving in the alpha guide.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#728]
This forum post suggests the alpha guide is confusing to at least two users:

https://forum.z.cash/t/zcash-is-spendable-only-once/252

Let's update the wiki to address their particular confusion, then reply to them.

**Comment by str4d** [comment]
This is also relevant to my question in #772.

**Comment by str4d** [comment]
Guide updated in https://github.com/zcash/zcash/wiki/Public-Alpha-Guide/0952626de51acf36092dae03f744092a14c2f373

Once someone has verified that my update is accurate, we can reply to them and close this ticket.

**Comment by ebfull** [comment]
You should not need to sign the second pour right now because there's nothing to sign, there are no inputs, just pours, and we don't have cryptographic binding for pours right now.

**Comment by str4d** [comment]
Okay, so simply sending the transaction to the network is sufficient?

**Comment by ebfull** [comment]
Should be, but in the future that may not be the case.

**Comment by str4d** [comment]
Outdated, we have easier RPC APIs now.
