### ISSUE TITLE
Are transactions verified twice as per the Zerocash paper?

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#729]
> Any plain Bitcoin inputs and outputs are processed as usual, and any Zerocash inputs and outputs are checked using VerifyTransaction with the entire Bitcoin transaction fed in as info for authentication. Once these transactions are assembled into a candidate block, each transaction needs to be verified again to ensure its serial number has not become spent or its Merkle root invalid.

In other words, if I spend the same coin twice in two different transactions, a miner might verify them individually and think everything's ok, then put them both in the same block, so that both spends make it onto the ledger, and so the same serial number gets revealed twice on the ledger.

I'm assigning myself this ticket as a code-reading exercise to check if our implementation does this correctly.

**Comment by ebfull** [comment]
Yup.

`CheckInputs` is in charge of this, and that's called by both `ConnectBlock` and `AcceptToMemoryPool`.
