### ISSUE TITLE
Fix glossary markup to emphasize terms.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#73]
Minor annoyance: The markdown in [the glossary](https://github.com/Electric-Coin-Company/zerocashd/blob/get_being_strange/doc/glossary.md) doesn't emphasize the terms when rendered by github.  I want the terms to be bolded, or otherwise very easy to jump to visually.

**Comment by daira** [comment]
I don't think ``doc/glossary.md`` ever existed in the branches for the rewritten code.
