### ISSUE TITLE
Create instructions and documentation for our homu CI setup

### ISSUE THREAD

**Issue by ebfull** [zcash/zcash#734]

**Comment by colealbon** [comment]
Gentoo install works after some fiddling with depends/packages/boost.mk
add the ignore-site-config flag 
./b2 --ignore-site-config  -d2 -j2 -d1 ..........

**Comment by daira** [comment]
Thanks @colealbon . That isn't the topic of this ticket so I opened #755.

**Comment by ebfull** [comment]
Here's just a quick overview of how homu works.

If you're on our team, you can do `@zkbot <command>` to tell zkbot to do things. Here are a few examples:

* `r+` this will test the merge and then actually commit the merge into the repo if the tests succeed.
* `try` this will test the merge and nothing else.
* `rollup` this is like `r+` but for insignificant changes. Use this when we want to test a bunch of merges at once to save buildbot time.

More instructions are found here: http://ci.leastauthority.com:12477/

**Comment by str4d** [comment]
The Homu/Buildbot CI system was decommissioned last year.
