### ISSUE TITLE
Receive needs to guarantee all coins are simultaneously spendable, not just that each coin is spendable on its own

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#739]
Here's an attack, which is an extension of the faerie gold attack:

Alice sends Bob two transactions, both with the same ρ. With the current faerie gold fix, I think Alice can do that at the expense of reusing a one-time signature keypair. This gives Bob two coins, except he will only be able to spend one of them since they'll both have the same serial number. When Bob's wallet runs Receive, it will see two coins, which are both *individually* spendable, since even though they have the same serial number as each other, the serial number doesn't appear on the ledger yet, and so the Receive check passes. Bob's wallet reports he got 100ZEC and a 20ZEC payments for a total balance of 120ZEC, but if he spends the 20ZEC first he won't be able to spend the 100ZEC.

We need to redefine Receive so that it guarantees all the coins it returns are simultaneously spendable.

**Comment by defuse** [comment]
Oh, this attack probably doesn't work: The serial numbers are included in h<sub>sig</sub>, so in order to get h<sub>sig</sub> to be the same I'd have to double spend.

Nevertheless, we should make sure Receive does the right thing.

**Comment by defuse** [comment]
Oops, didn't mean to close it.

**Comment by daira** [comment]
I think that this doesn't work provided PRF<sup>ρ</sup> and the H used to calculate h<sub>Sig</sub> are collision-resistant. In that case, both transactions cannot get onto a valid blockchain because they will repeat the same serial numbers. (See also https://github.com/zcash/zcash/issues/723#issuecomment-187955366 .)

**Comment by daira** [comment]
Tying up a loose end...

@defuse wrote:
> But what if I'm the one who chose the previous rho's all the way up back until the block reward, then can I do it?

No, choosing previous ρ values doesn't help.
