### ISSUE TITLE
Add consideration to the glossary about the basecoin address/transaction vs Zcash address/transaction conflation.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#74]
It's getting cumbersome to verbally say "the Zerocash transaction embedded in the basecoin transaction TXin" or similar things.

We could clarify developer discussions if we were to use distinct single-word terms to disambiguate these two layers.  This is just a wish on my part, and even if we don't adopt new terms, we need to highlight the conflation in the glossary.

**Comment by daira** [comment]
This ticket is obsolete.
