### ISSUE TITLE
Fix the dev wiki page

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#740]
I'm very confused about what conventions we're following now. Let's update the dev page!

**Comment by zookozcash** [comment]
+1! We don't want newcomers like @str4d, old-timers like @defuse, and random contributors on github to be misled or cast into doubt by the "development conventions" documentation. Delete everything that is incorrect and replace it with a succinct doc that gives the reader guidance and confidence!

**Comment by daira** [comment]
This is done except for #734.
