### ISSUE TITLE
Buildbot Performance Measurement

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#748]
Make buildbot measure and track the performance of our software over time. In particular, the memory usage and the time it takes to send a pour.

**Comment by zookozcash** [comment]
Note: do _not_ measure or report "virtual memory"/vsz. That is a misleading number that will only waste people's time if it gets measured or reported. Instead, use https://www.selenic.com/smem/ and measure *proportional set size*.

For bonus points, we could run it under valgrind and use valgrind massif to profile the heap: http://valgrind.org/docs/manual/ms-manual.html

(Note: we definitely *ought* to run it under valgrind anyway, to catch memory bugs which could be critical security holes. That should be a separate ticket.)

**Comment by zookozcash** [comment]
https://github.com/zcash/zcash/issues/761

**Comment by daira** [comment]
+1 for using valgrind/massif.

**Comment by daira** [comment]
Isn't smem oriented toward finding the proportion of memory that can be attributed to a given process in a running system, provided that the usage of all processes in that system is known? In this case or process will be running in an unknown environment on end-user machines, so the extent to which its libraries will get shared is also unknown.

**Comment by zookozcash** [comment]
Here's my wishlist for performance measurements.

1. A buildbot step that would be e.g. step 6 on http://ci.leastauthority.com:8010/builders/zcash/builds/79 that runs zcashd under massif, does all initialization including proving-key loading, and then shuts down, and uploads the resulting profiling results somewhere that we can inspect and archive.

   I'd love to see this complete and live on our buildbot before any of the rest of the items on my wishlist!

2. Same as 1, but with the `--time-unit=ms` option, and after it is finished initializing and loading the proving key then it prints out the current time and then does a single zk-spend proof.

3. A performance measurement: initialize and load the proving key, then ten times in a row measure the (unix wall-clock) time, do a single zk-spend proof, then measure the time again, and then print out the time elapsed during the proof.

4. The same as 3 but for a single zk-spend verification instead of a proof, and do it around 1000 times instead of 10 (reporting *all* of the elapsed times)

**Comment by zookozcash** [comment]
Another wishlist item: rent ARM servers and run all these same tests on there. (See also: https://github.com/zcash/zcash/issues/408.)

**Comment by defuse** [comment]
This is kind of tricky to implement, for example if we're using massif to measure memory, then when the binary gets run to do a verify, it *can't also* do things like generate parameters, load the proving key, generate a pour, etc. since we would be measuring the memory of all of those setup steps too.

What I'm going to do is add a command to `bitcoin-cli` (since it's already linked up to the bitcoin code and I don't want to mess around in Makefiles to figure out how to add another binary that's linked up to the bitcoin code). It can be used the following ways:

- `generatebenchmarkinputs` which creates ` ./benchmarkinputs/` which contains a file containing a valid transaction with a single joinsplit.
- `benchmarkverify N` which loads the transaction from the file and verifies the joinsplit proof N times.
- `benchmarkjoinsplit N` which creates a joinsplit N times reporting the time for each.
- `benchmarkprovingkeyload N` which loads and unloads the proving key N times
- `benchmarkequihash N` which finds an equihash solution for whichever parameters we're currently using N times.

To measure time, you run them with N=10 (for the slow ones) or N=1000 (for the fast ones). To measure memory, you run them with N=1 under massif. There will be a script in `./qa/zcash` that does all that and also runs `zcashd` under massif.

**Comment by defuse** [comment]
Bitcoin does have some stuff for benchmarking secpk256k1 but it's not useful/reusable.

**Comment by defuse** [comment]
PR #846 is ready for review & merge. Left to do:

- Add a command that benchmarks verification (it will have to take a transaction containing a pour as an argument).
- Add a command that benchmarks PoW solution finding (just one attempt at finding an Equihash solution, so that there's less variance in the results).
- Add a command that benchmarks PoW verification (takes PoW solution as a command-line argument).
- Add another buildbot waterfall column.

**Comment by defuse** [comment]
Buildbot's FileUpload stuff doesn't link it into the build, so I'm going to make the performance measurement script take a command-line option specifying the thing you want to test, and then there'll be one step in the build for each test. That way it will be easy to make a script that pulls them all down given the build number.

**Comment by nathan-at-least** [comment]
@defuse: I see that #846 merged, and I see a performance buildbot waterfall column, so I'm closing this. If this is a mistake, please re-open it.

Nice work!

**Comment by daira** [comment]
I think we should have both ``benchmark_pow_solution`` and ``benchmark_equihash_basicsolve``, where the latter only ever does one iteration. That way we can also tell whether the ratio between them is changing.
