### ISSUE TITLE
Can we mitigate abusive/threatening communication via memo fields?

### ISSUE THREAD

**Issue by daira** [zcash/zcash#749]
The memo field attached to a sent coin (#85) is a sender-anonymous communication channel. The field is currently planned only to be 64 bytes, but that's enough for a death threat, rape threat, blackmail, or other abusive communication. Unlike centralized communication platforms with an anonymous messaging feature, there is no way to implement a facility for recipients to block particular senders (identifying the sender would be a failure of anonymity/unlinkability). Also, an abusive sender is likely to be able to find ways around any filtering that a recipient's software might perform based on the content of the memo (e.g. by using Unicode look-alike characters to avoid matching blocked words).

**Comment by daira** [comment]
The memo field size implemented in 1.0 is 512 bytes (#1187 / #1254).

**Comment by zookozcash** [comment]
I can't think of anything we can do for this, so I propose we close this ticket as "Answer: no".

**Comment by daira** [comment]
https://twitter.com/sonyasupposedly/status/1163981148675903488
