### ISSUE TITLE
specify and implement memo fields in RPC interface

### ISSUE THREAD

**Issue by daira** [zcash/zcash#756]
Part of the implementation of #85.

**Comment by daira** [comment]
@ebfull Was this implemented/documented?

**Comment by ebfull** [comment]
Not yet.

**Comment by nathan-at-least** [comment]
Let's distinguish the "Zcashd 1.0 RPC interface" and associated documentation from a "Zcash Wallet Implementation Guidelines" kind of document that we can develop post launch. For this ticket let's just focus on our RPC interface.

**Comment by daira** [comment]
This isn't absolutely critical for z9, but it might get bumped if we don't have time.

**Comment by daira** [comment]
I thought this was implemented in beta 1?

**Comment by daira** [comment]
See #1362 for future improvements.
