### ISSUE TITLE
Update guide on wiki to point to canonical

### ISSUE THREAD

**Issue by alfiedotwtf** [zcash/zcash#757]
On https://github.com/zcash/zcash/wiki/Public-Alpha-Guide, it says:

    git clone https://github.com/Electric-Coin-Company/zcash.git
    cd zcash/
    ./zcutil/fetch-params.sh

Shouldn't this now be:

    git clone https://github.com/zcash/zcash.git
    cd zcash/
    ./zcutil/fetch-params.sh

**Comment by ebfull** [comment]
Thanks!
