### ISSUE TITLE
mining slow start

### ISSUE THREAD

**Issue by zookozcash** [zcash/zcash#762]
What happened to Litecoin (http://www.devtome.com/doku.php?id=a_massive_investigation_of_instamines_and_fastmines_for_the_top_alt_coins#litecoin) could also happen to us — the mining power in the early days/hours could be much higher than the initial setting of the difficulty factor, thus leading to faster than normal blocks, and making people who missed out on that period suspect that we had deliberately colluded with early miners to give the early miners an unfair advantage. A possible prevention of that would be to have a "slow start", where for the first few blocks there is only a small reward, like on the order of 0.2ⓩ, and then it periodically redoubles until it reaches 50ⓩ. The advantages of a slow start are:

 * We get a real measurement of mining power, which can be used to adjust the difficulty factor, before the more valuable rewards start coming. (In contrast, the earlier proposal to have mining of empty blocks with no reward doesn't have this advantage, because early miners would be incentivized to hide their mining power from the difficulty calculations and then turn on their mining power just in time for the first 50ⓩ reward.)

 * People have less reason to be suspicious that there was some kind of collusion in which we pulled the starting gun trigger right when their competitors had gotten to the starting line but before they had. Since the starting gun just starts doling out rewards of 0.2ⓩ per block, it is fine for late-comers to jump in.

**Comment by zookozcash** [comment]
I'm very much in favor of this, because it can ease our operational burden. Having a "big bang" event where everything has to be set up in advance, and then everything happens fast… that's terrifying, and it means that we'll be tempted to delay it because we don't feel ready, and so on. With the "slow start" approach, we can pull the trigger to start mining, knowing that we still have a few weeks before it gets to be significantly valuable, giving us time to watch for failures, work on related operational things (updating our web site, dealing with getting hacked and defaced and all that, collaborating with wallet makers, exchange operators, and other partners, touring the world to visit stadiums of screaming fans, etc.).

**Comment by daira** [comment]
I favour a linear ramp-up in block reward combined with a difficulty adjustment algorithm that starts with a high estimate of mining power (hence blocks may be less frequent than the target time initially).

**Comment by str4d** [comment]
Linear per block, or stepped-linear? I assume you mean the latter, so your combination results in a smooth pseudo-exponential ramp-up (at least initially - the difficulty algorithm should smooth out the target time relatively quickly if it is working as intended).

**Comment by daira** [comment]
I meant linear per block.

**Comment by daira** [comment]
For concreteness, suppose we set the slope of the ramp to be 0.01 ZEC per 10 minutes. That would take 5000 * 10 minutes = 34.7 days to reach 50 ZEC. The monetary base at that point would be 0.01*(5000*5001/2) = 125025 ZEC (as compared to 250000 ZEC if there were no slow start, so the founders would lose 124975/5 = 24995 ZEC, or about 1.2% of their total reward, unless we also adjusted that).

**Comment by nathan-at-least** [comment]
I didn't see @daira's comment about change in Founder's Reward.

I agree that it does not affect that fraction of monetary base in the first ~4 years. Let's resolve another ambiguity by extending @daira's concrete proposal by saying the halving interval remains unaltered (assuming block size/target rate remain unchanged), so even with the slow start ramp up, the halving interval will still remain 210,000 blocks (assuming no change to block rate/reward). Let's henceforth call this proposal "Slow Start Alpha".

In Slow Start Alpha, the total Founder's Reward to monetary base at the first halving interval changes from [1]:

```
Std_FR = 210,000 blocks * 10 ⓩ = 2,100,000 ⓩ
Std_MB_FirstHalvening = 210,000 blocks * 50 ⓩ = 10,500,000 ⓩ
Std_MB_Total = 20999999.97690000 ⓩ
```

-to:

```
SSA_FR = (210,000 - (5000+1)/2) blocks * 10 ⓩ = 2074995 ⓩ
SSA_MB_FirstHalvening = (210,000 - (5000+1)/2) blocks * 50 ⓩ = 10,374,975 ⓩ
SSA_MB_Total = 20999999.97690000 ⓩ - ((5000+1/2) blocks * 50 ⓩ/block) = 20874974.97690000 ⓩ
```

So the ratio's of the Founder's Reward to the monetary base at the first halvening (~4 years) and the total (after mining rewards cease) for both the "standard" mining rate and the Slow Start Alpha proposal would be:

Standard Mining Schedule:

```
Std_FR / Std_MB_FirstHalvening = 0.2 (exact) = 20%
Std_FR / Std_MB_Total ~= 0.1 (within 9 sig digs) ~= 10%
```

Slow Start Alpha Schedule ratios:

```
SSA_FR / SSA_MB_FirstHalvening = 0.2 (exact) = 20%
SSA_FR / SSA_MB_Total ~= 0.09940 ~= 9.94%
```

Note that we intend to change the block rate, block reward, and halving interval (as counted in blocks) to keep these ratios and the *approximate* real-time of the monetary base schedule as specified here. By approximate real-time, I mean "about 4 years", so for example, if we double the block rate, we halve the per-block reward.

A final nit: the genesis block coinbase is unspendable; a wart we inherit from Bitcoin. With Mining Slow Start Alpha this difference to the actually-available-monetary-supply is 5000 times smaller than in Bitcoin, but it still affects the above ratios a miniscule amount. I consider those unspendable coins to be like a ceremonial sacrifice for the birth of the chain. ;-)

**Comment by daira** [comment]
Re: the "final nit", in the Slow Start Alpha proposal the reward starts at zero and increases by 0.01 ZEC in each subsequent block, so it doesn't matter that the first reward is unspendable. (I'm assuming that having a zero reward for the first block doesn't trigger bugs, which might be an optimistic assumption :-p )

**Comment by str4d** [comment]
In the engineering meeting today, we confirmed that we will be consistent with what was said in the funding blog post, ie. 21 million ZEC total, and 2.1 million ZEC as founder's reward. This means that the first ~4-year halving period will be extended by a few weeks so that the total ZEC mined in the first halving interval stays at 10.5 million.

**Comment by str4d** [comment]
Here's a Jupyter analysis I just finished of two alternatives:

- A linear ramp (per @daira)
- An "exponential" ramp, consisting of four sequential linear ramps (for @zookozcash's benefit).

```python
from __future__ import division
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
```

First, we define the standard Bitcoin parameters:

```python
COIN = 100000000
BASE_BLOCK_SUBSIDY = 50 * COIN
HALVING_INTERVAL = 210000
```

And then the parameters for the slow-start options:

```python
LIN_SLOW_START_INTERVAL = 5000
LIN_SLOW_START_OFFSET = int(LIN_SLOW_START_INTERVAL/2)

# Ramp of 3000 blocks
#EXP_SLOW_START_BASE_INTERVAL = 200
# Ramp of 6000 blocks
EXP_SLOW_START_BASE_INTERVAL = 400
EXP_SLOW_START_OFFSET = int(10.375*EXP_SLOW_START_BASE_INTERVAL)
```

These parameters were chosen specifically so that the subsidy per block was always a "nice" amount (ie. an integer number of Satoshi).

Now we define the subsidy functions:

```python
def get_subsidy(height):
    return BASE_BLOCK_SUBSIDY / 2**int(height/HALVING_INTERVAL)

def get_lin_slow_start_subsidy(height):
    if height > LIN_SLOW_START_INTERVAL:
        return BASE_BLOCK_SUBSIDY / 2**int((height - LIN_SLOW_START_OFFSET)/HALVING_INTERVAL)
    else:
        return BASE_BLOCK_SUBSIDY*(height/LIN_SLOW_START_INTERVAL)

def get_exp_slow_start_subsidy(height):
    if height > 15*EXP_SLOW_START_BASE_INTERVAL:
        return BASE_BLOCK_SUBSIDY / 2**int((height - EXP_SLOW_START_OFFSET)/HALVING_INTERVAL)
    elif height > 14*EXP_SLOW_START_BASE_INTERVAL:
        return (3*BASE_BLOCK_SUBSIDY/4) + (BASE_BLOCK_SUBSIDY/4)*((height-14*EXP_SLOW_START_BASE_INTERVAL)/EXP_SLOW_START_BASE_INTERVAL)
    elif height > 12*EXP_SLOW_START_BASE_INTERVAL:
        return (BASE_BLOCK_SUBSIDY/2) + (BASE_BLOCK_SUBSIDY/4)*((height-12*EXP_SLOW_START_BASE_INTERVAL)/(2*EXP_SLOW_START_BASE_INTERVAL))
    elif height > 8*EXP_SLOW_START_BASE_INTERVAL:
        return (BASE_BLOCK_SUBSIDY/4) + (BASE_BLOCK_SUBSIDY/4)*((height-8*EXP_SLOW_START_BASE_INTERVAL)/(4*EXP_SLOW_START_BASE_INTERVAL))
    else:
        return (BASE_BLOCK_SUBSIDY/4)*(height/(8*EXP_SLOW_START_BASE_INTERVAL))

def get_founders_reward(height, subsidy, period):
    if height > period:
        return 0
    else:
        return subsidy/5

vec_get_subsidy = np.vectorize(get_subsidy)
vec_get_lin_slow_start_subsidy = np.vectorize(get_lin_slow_start_subsidy)
vec_get_exp_slow_start_subsidy = np.vectorize(get_exp_slow_start_subsidy)
vec_get_founders_reward = np.vectorize(get_founders_reward)
```

Finally, we calculate the subsidies for the first eight halving intervals:

```python
blocks = np.arange(0,8*HALVING_INTERVAL)

reg_subsidy = vec_get_subsidy(blocks)
reg_fr = vec_get_founders_reward(blocks, reg_subsidy, HALVING_INTERVAL)
reg_mined = np.cumsum(reg_subsidy)
reg_mined_fr = np.cumsum(reg_fr)

lin_subsidy = vec_get_lin_slow_start_subsidy(blocks)
lin_fr = vec_get_founders_reward(blocks, lin_subsidy, LIN_SLOW_START_OFFSET + HALVING_INTERVAL)
lin_mined = np.cumsum(lin_subsidy)
lin_mined_fr = np.cumsum(lin_fr)

exp_subsidy = vec_get_exp_slow_start_subsidy(blocks)
exp_fr = vec_get_founders_reward(blocks, exp_subsidy, EXP_SLOW_START_OFFSET + HALVING_INTERVAL)
exp_mined = np.cumsum(exp_subsidy)
exp_mined_fr = np.cumsum(exp_fr)
```

Plotting the block subsidies and founders reward over the slow start interval shows how the subsidies are ramped up:

```python
window = LIN_SLOW_START_INTERVAL + 1000
yscale = COIN

plt.plot(blocks[:window], reg_subsidy[:window]/yscale, label='reg_s', lw=1.5)
plt.plot(blocks[:window], reg_fr[:window]/yscale, label='reg_fr', lw=1.5)
plt.plot(blocks[:window], lin_subsidy[:window]/yscale, label='lin_s', lw=1.5)
plt.plot(blocks[:window], lin_fr[:window]/yscale, label='lin_fr', lw=1.5)
plt.plot(blocks[:window], exp_subsidy[:window]/yscale, label='exp_s', lw=1.5)
plt.plot(blocks[:window], exp_fr[:window]/yscale, label='exp_fr', lw=1.5)

plt.ylim(0, 55)
plt.legend(loc='upper left')

plt.show()
```

![output_10_0](https://cloud.githubusercontent.com/assets/4993799/14629726/bf9be74a-065c-11e6-9ded-2d9c6cfc01fe.png)

Plotting the mined ZEC and mined founder's reward shows that the slow start has no effect on the shape of the monetary curve; it simply delays it by a few thousand blocks.

```python
xscale = 1000
yscale = 1000000*COIN

plt.plot(blocks/xscale, reg_mined/yscale, label='reg_mined', lw=1.5)
plt.plot(blocks/xscale, reg_mined_fr/yscale, label='reg_mined_fr', lw=1.5)
plt.plot(blocks/xscale, lin_mined/yscale, label='lin_mined', lw=1.5)
plt.plot(blocks/xscale, lin_mined_fr/yscale, label='lin_mined_fr', lw=1.5)
plt.plot(blocks/xscale, exp_mined/yscale, label='exp_mined', lw=1.5)
plt.plot(blocks/xscale, exp_mined_fr/yscale, label='exp_mined_fr', lw=1.5)

plt.legend(loc='upper left')

plt.show()
```

![output_12_0](https://cloud.githubusercontent.com/assets/4993799/14629744/d7bc14c6-065c-11e6-9e18-ec8393c16784.png)

Zooming in on the slow start interval, we can see the actual effect that mining slow start has on the monetary supply:

```python
window = LIN_SLOW_START_INTERVAL + 2000
yscale = 1000*COIN

plt.plot(blocks[:window], reg_mined[:window]/yscale, label='reg_mined', lw=1.5)
plt.plot(blocks[:window], reg_mined_fr[:window]/yscale, label='reg_mined_fr', lw=1.5)
plt.plot(blocks[:window], lin_mined[:window]/yscale, label='lin_mined', lw=1.5)
plt.plot(blocks[:window], lin_mined_fr[:window]/yscale, label='lin_mined_fr', lw=1.5)
plt.plot(blocks[:window], exp_mined[:window]/yscale, label='exp_mined', lw=1.5)
plt.plot(blocks[:window], exp_mined_fr[:window]/yscale, label='exp_mined_fr', lw=1.5)

plt.legend(loc='upper left')

plt.show()
```

![output_14_0](https://cloud.githubusercontent.com/assets/4993799/14629747/dfddf8d6-065c-11e6-90b4-f17bf37217ea.png)

**Comment by str4d** [comment]
Oops, it's not a bug, it's just a feature of the linear ramp. A ramp from 0 to 50 in 0.01 increments has 5001 elements, with 25 in the middle. Hence the discrete sum is 125,025 while the area under the ramp is 1/2 * 5000 * 50 = 125,000.

**Comment by str4d** [comment]
The following is a corrected analysis. Apologies for triggering another large email, but I'd like to keep it self-contained :smile:

```python
from __future__ import division
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
```

First, we define the standard Bitcoin parameters:

```python
COIN = 100000000
BASE_BLOCK_SUBSIDY = 50 * COIN
HALVING_INTERVAL = 210000
```

And then the parameters for the slow-start options:

```python
LIN_SLOW_START_INTERVAL = 5000
LIN_SLOW_START_OFFSET = int(LIN_SLOW_START_INTERVAL/2)

# Ramp of 3000 blocks
#EXP_SLOW_START_BASE_INTERVAL = 200
# Ramp of 6000 blocks
EXP_SLOW_START_BASE_INTERVAL = 400
EXP_SLOW_START_OFFSET = int(10.375*EXP_SLOW_START_BASE_INTERVAL)
```

These parameters were chosen specifically so that the subsidy per block was always a "nice" amount (ie. an integer number of Satoshi).

Now we define the subsidy functions:

```python
def get_subsidy(height):
    return BASE_BLOCK_SUBSIDY / 2**int(height/HALVING_INTERVAL)

def get_lin_slow_start_subsidy(height):
    if height >= LIN_SLOW_START_INTERVAL:
        return BASE_BLOCK_SUBSIDY / 2**int((height - LIN_SLOW_START_OFFSET)/HALVING_INTERVAL)
    elif height >= LIN_SLOW_START_INTERVAL/2:
        return BASE_BLOCK_SUBSIDY*((height+1)/LIN_SLOW_START_INTERVAL)
    else:
        return BASE_BLOCK_SUBSIDY*(height/LIN_SLOW_START_INTERVAL)

def get_exp_slow_start_subsidy(height):
    if height >= 15*EXP_SLOW_START_BASE_INTERVAL:
        return BASE_BLOCK_SUBSIDY / 2**int((height - EXP_SLOW_START_OFFSET)/HALVING_INTERVAL)
    elif height >= 14*EXP_SLOW_START_BASE_INTERVAL:
        return (3*BASE_BLOCK_SUBSIDY/4) + (BASE_BLOCK_SUBSIDY/4)*((height+1-14*EXP_SLOW_START_BASE_INTERVAL)/EXP_SLOW_START_BASE_INTERVAL)
    elif height >= 12*EXP_SLOW_START_BASE_INTERVAL:
        return (BASE_BLOCK_SUBSIDY/2) + (BASE_BLOCK_SUBSIDY/4)*((height+1-12*EXP_SLOW_START_BASE_INTERVAL)/(2*EXP_SLOW_START_BASE_INTERVAL))
    elif height >= 8*EXP_SLOW_START_BASE_INTERVAL:
        return (BASE_BLOCK_SUBSIDY/4) + (BASE_BLOCK_SUBSIDY/4)*((height-8*EXP_SLOW_START_BASE_INTERVAL)/(4*EXP_SLOW_START_BASE_INTERVAL))
    else:
        return (BASE_BLOCK_SUBSIDY/4)*(height/(8*EXP_SLOW_START_BASE_INTERVAL))

def get_founders_reward(height, subsidy, period):
    if height >= period:
        return 0
    else:
        return subsidy/5

vec_get_subsidy = np.vectorize(get_subsidy)
vec_get_lin_slow_start_subsidy = np.vectorize(get_lin_slow_start_subsidy)
vec_get_exp_slow_start_subsidy = np.vectorize(get_exp_slow_start_subsidy)
vec_get_founders_reward = np.vectorize(get_founders_reward)
```

Note that in both the linear and "exponential" ramps, we skip over the block payout of exactly 25 ZEC. This minor adjustment is made to enable the total monetary supply to be unaltered from regular Bitcoin.

Finally, we calculate the subsidies for the first eight halving intervals:

```python
blocks = np.arange(0,8*HALVING_INTERVAL)

reg_subsidy = vec_get_subsidy(blocks)
reg_fr = vec_get_founders_reward(blocks, reg_subsidy, HALVING_INTERVAL)
reg_mined = np.cumsum(reg_subsidy)
reg_mined_fr = np.cumsum(reg_fr)

lin_subsidy = vec_get_lin_slow_start_subsidy(blocks)
lin_fr = vec_get_founders_reward(blocks, lin_subsidy, LIN_SLOW_START_OFFSET + HALVING_INTERVAL)
lin_mined = np.cumsum(lin_subsidy)
lin_mined_fr = np.cumsum(lin_fr)

exp_subsidy = vec_get_exp_slow_start_subsidy(blocks)
exp_fr = vec_get_founders_reward(blocks, exp_subsidy, EXP_SLOW_START_OFFSET + HALVING_INTERVAL)
exp_mined = np.cumsum(exp_subsidy)
exp_mined_fr = np.cumsum(exp_fr)
```

Plotting the block subsidies and founders reward over the slow start interval shows how the subsidies are ramped up:

```python
window = LIN_SLOW_START_INTERVAL + 1000
yscale = COIN

plt.plot(blocks[:window], reg_subsidy[:window]/yscale, label='reg_s', lw=1.5)
plt.plot(blocks[:window], reg_fr[:window]/yscale, label='reg_fr', lw=1.5)
plt.plot(blocks[:window], lin_subsidy[:window]/yscale, label='lin_s', lw=1.5)
plt.plot(blocks[:window], lin_fr[:window]/yscale, label='lin_fr', lw=1.5)
plt.plot(blocks[:window], exp_subsidy[:window]/yscale, label='exp_s', lw=1.5)
plt.plot(blocks[:window], exp_fr[:window]/yscale, label='exp_fr', lw=1.5)

plt.ylim(0, 55)
plt.legend(loc='upper left')

plt.show()
```

![output_10_0](https://cloud.githubusercontent.com/assets/4993799/14638330/013eeb9c-068b-11e6-97eb-708e17ecde05.png)

Plotting the mined ZEC and mined founder's reward shows that the slow start has no effect on the shape of the monetary curve; it simply delays it by a few thousand blocks.

```python
xscale = 1000
yscale = 1000000*COIN

plt.plot(blocks/xscale, reg_mined/yscale, label='reg_mined', lw=1.5)
plt.plot(blocks/xscale, reg_mined_fr/yscale, label='reg_mined_fr', lw=1.5)
plt.plot(blocks/xscale, lin_mined/yscale, label='lin_mined', lw=1.5)
plt.plot(blocks/xscale, lin_mined_fr/yscale, label='lin_mined_fr', lw=1.5)
plt.plot(blocks/xscale, exp_mined/yscale, label='exp_mined', lw=1.5)
plt.plot(blocks/xscale, exp_mined_fr/yscale, label='exp_mined_fr', lw=1.5)

plt.legend(loc='upper left')

plt.show()
```

![output_12_0](https://cloud.githubusercontent.com/assets/4993799/14638335/089dde70-068b-11e6-9301-bc40559d79c7.png)

Zooming in on the slow start interval, we can see the actual effect that mining slow start has on the monetary supply:

```python
window = LIN_SLOW_START_INTERVAL + 2000
yscale = 1000*COIN

plt.plot(blocks[:window], reg_mined[:window]/yscale, label='reg_mined', lw=1.5)
plt.plot(blocks[:window], reg_mined_fr[:window]/yscale, label='reg_mined_fr', lw=1.5)
plt.plot(blocks[:window], lin_mined[:window]/yscale, label='lin_mined', lw=1.5)
plt.plot(blocks[:window], lin_mined_fr[:window]/yscale, label='lin_mined_fr', lw=1.5)
plt.plot(blocks[:window], exp_mined[:window]/yscale, label='exp_mined', lw=1.5)
plt.plot(blocks[:window], exp_mined_fr[:window]/yscale, label='exp_mined_fr', lw=1.5)

plt.legend(loc='upper left')

plt.show()
```

![output_14_0](https://cloud.githubusercontent.com/assets/4993799/14638339/10ed8008-068b-11e6-9ed0-7752f9136fa2.png)

To check we have the correct monetary supply, we can print out block subsidies and mined amounts around key transitions:

```python
print lin_subsidy[LIN_SLOW_START_INTERVAL-4:LIN_SLOW_START_INTERVAL+2]/COIN
print exp_subsidy[15*EXP_SLOW_START_BASE_INTERVAL-4:15*EXP_SLOW_START_BASE_INTERVAL+2]/COIN
```

    [ 49.97  49.98  49.99  50.    50.    50.  ]
    [ 49.90625  49.9375   49.96875  50.       50.       50.     ]

```python
print lin_mined[LIN_SLOW_START_INTERVAL-4:LIN_SLOW_START_INTERVAL+2]/COIN
print exp_mined[15*EXP_SLOW_START_BASE_INTERVAL-4:15*EXP_SLOW_START_BASE_INTERVAL+2]/COIN
```

    [ 124850.03  124900.01  124950.    125000.    125050.    125100.  ]
    [ 92350.09375  92400.03125  92450.       92500.       92550.       92600.     ]

```python
print reg_mined[HALVING_INTERVAL-2:HALVING_INTERVAL+2]/COIN
print lin_mined[HALVING_INTERVAL+LIN_SLOW_START_OFFSET-2:HALVING_INTERVAL+LIN_SLOW_START_OFFSET+2]/COIN
print exp_mined[HALVING_INTERVAL+EXP_SLOW_START_OFFSET-2:HALVING_INTERVAL+EXP_SLOW_START_OFFSET+2]/COIN
```

    [ 10499950.  10500000.  10500025.  10500050.]
    [ 10499950.  10500000.  10500025.  10500050.]
    [ 10499950.  10500000.  10500025.  10500050.]

```python
print reg_mined_fr[HALVING_INTERVAL-2:HALVING_INTERVAL+2]/COIN
print lin_mined_fr[HALVING_INTERVAL+LIN_SLOW_START_OFFSET-2:HALVING_INTERVAL+LIN_SLOW_START_OFFSET+2]/COIN
print exp_mined_fr[HALVING_INTERVAL+EXP_SLOW_START_OFFSET-2:HALVING_INTERVAL+EXP_SLOW_START_OFFSET+2]/COIN
```

    [ 2099990.  2100000.  2100000.  2100000.]
    [ 2099990.  2100000.  2100000.  2100000.]
    [ 2099990.  2100000.  2100000.  2100000.]

**Comment by str4d** [comment]
And for comparison, here are the changes to the "exponential" mining slow start if we halve the ramp from 6000 blocks to 3000:

![output_10_0](https://cloud.githubusercontent.com/assets/4993799/14638475/b3f47a54-068b-11e6-818e-42ebdc0bf375.png)
![output_14_0](https://cloud.githubusercontent.com/assets/4993799/14638481/b6debf68-068b-11e6-8964-7f549a494322.png)

The total monetary supply and founder's reward is unaffected.

**Comment by daira** [comment]
Excellent work @str4d !

**Comment by daira** [comment]
BTW, TIL that Satoshi used a clever hack to prove the absence of premining for Bitcoin: https://bitcointalk.org/index.php?topic=172009.0
To summarize, Satoshi encoded a newspaper headline in the genesis block that was recent at the time the block was published. This proves that they could not have been premining a large number of blocks that could then have been submitted as successors to the genesis block, before other miners had an opportunity to do so. We should use the same idea.

**Comment by str4d** [comment]
In our pairing, @daira and I decided to leave the choice of slow start ramp to @zookozcash. Please could you review the above graphs and decide whether you would prefer the linear or "exponential" slow start? I have already implemented most of the linear ramp locally, but the "exponential" ramp is only a few extra conditionals and slightly more maths.

For reference, these are the slow start periods given the current block target time:

- Linear, 5000-block ramp: ~34.7 days = ~4.96 weeks
- "Exponential", 3000-block ramp: ~20.8 days = ~2.98 weeks
- "Exponential", 6000-block ramp: ~41.7 days = ~5.95 weeks

**Comment by daira** [comment]
I mildly prefer the linear ramp because I think it is simpler both in terms of code/design complexity and to explain to people. But it's only a small difference.

**Comment by nathan-at-least** [comment]
@str4d's model looks excellent. I also slightly prefer the linear ramp.

I'm a bit curious about the ramp time scale parameter. Why ~1 month time scale? What about 2 days? What about 1 year? Also, how does the timescale interact with difficulty?

One thought about a very long time scale: if there are any mining disruptions early on, the effect on the total supply will be smaller. Not sure if that matters, or what other effects this might entail.

**Comment by str4d** [comment]
The ramp length has no direct interaction with difficulty - it only changes the block reward, not how difficult it is to mine a block. However, you do raise an interesting point: if the point of mining slow start is to reduce the effect of high-powered centralised mining at the early stages, then the slow start interval needs to be long enough to handle that. With the current difficulty algorithm, that means it needs to be at least a month or two long to ensure there are several difficulty adjustments during slow start (ie. at least a few times longer than 2016 blocks). With #147, the period needs to be long enough for the new algorithm to be calculating effectively (ie. at least one or two times the length of the block window it uses).

**Comment by zookozcash** [comment]
Great work, Jack! I choose linear 5000-block ramp. Thanks everyone for your contributions. Remember about the "5000-block" part, though, that we're planning to reduce the block interval from 10 minutes to 2.5 minutes (https://github.com/zcash/zcash/issues/764). I guess that means we should multiply by 4 all the block-count constants above?

**Comment by str4d** [comment]
Yes, that's correct. Multiplying all values up will of course not add any rounding errors (assuming I didn't accidentally add any originally!)

**Comment by daira** [comment]
Yes, in that case the block reward would increase by 0.0025 ZEC per 2.5 minutes. That would take 20000 * 2.5 minutes = 34.7 days to reach 50 ZEC, as before.

**Comment by daira** [comment]
Another possibility that has slightly rounder numbers for the 2.5-minute block case, is a ramp of 0.005 ZEC per block. This takes 25000 blocks to reach the full 12.5 ZEC reward, which takes 43.4 days.

**Comment by nathan-at-least** [comment]
Will the lower block time also have more frequent realtime difficulty adjustments? Will difficulty adjustments be defined by a fixed block window, regardless of block target time, or will we scale difficulty adjustment window recriprocally to block target time in order to have difficulty adjustments *roughly* unchanged in realtime intervals?

Let's call the number of difficulty adjustments occuring prior to the end of the ramp ``A``. If ``A = 0`` what behavior does this have? As ``A`` grows, what effect does this have? Is there an optimal number?

My intuition is that ``A = 0`` loses some important characteristics for this ramp, and the larger ``A`` is the better, because this means the network has reacted to mining capacity sufficiently before the block reward reaches the max rate / time.

**Comment by daira** [comment]
I would assume that the difficulty will be adjusted per block based on some function of the previous N blocks, using a sliding window. (As far as I can see, a sliding window is a strict improvement over a fixed window for all relevant security and responsiveness properties.) In that case N should be much smaller than the number of blocks in the ramp, let's say at least 10 times smaller. How small it can be depends on a security analysis of potential difficulty adjustment algorithms that we haven't done yet.

**Comment by str4d** [comment]
We decided in the engineering meeting to disable mining slow start in regtest mode to avoid the various issues that created in unrelated RPC tests.

**Comment by blackhatzw** [comment]
A slow start is unfair to the early miners who help this project.

**Comment by daira** [comment]
The monetary curve is published well in advance, and miners can make their own decisions about whether they find it worthwhile to mine at any given point in time. I don't see how that's unfair.

**Comment by ralphtheninja** [comment]
Is the mining algorithm sha256 just like bitcoin?

**Comment by daira** [comment]
The mining algorithm is [Equihash](https://z.cash/blog/why-equihash.html). Please note that this is a bug tracker and needs to be kept focused (for example, this ticket is about the design and implementation of mining slow start). The [forum](https://forum.z.cash) is a better place for such questions.
