### ISSUE TITLE
prepare to get compromised (and survive)

### ISSUE THREAD

**Issue by zookozcash** [zcash/zcash#763]
Before the blockchain genesis, we should game through what the consequences would be of various parts of our infrastructure getting compromised — Taylor's laptop, Zooko's laptop, our google apps accounts, the z.cash domain name, our github account, etc.

* How can we detect each of these kinds of compromise?
* How can we verify that somebody who temporarily had write access to our github account didn't insert a backdoor into the code?
* Can we recover control of z.cash if an attacker manages to take over our account with our domain name service?
* How many hours/days/weeks will it take to construct a fresh web site from backups that we have *verified* were not touched by the attacker?
* How will we communicate to our users during the interim, when we don't have a web site up or we might not even have access to the z.cash domain name?
* How will we communicate with each other if gmail, slack, and/or IRC are suspected of being compromised or are unavailable?
* Should we agree in advance on a fallback domain name under different access control in case we can't, or can't quickly, recover control of z.cash? zerocash-project.org? zca.sh?
* Is there data that an attacker could delete that would interfere with our ability to function and which is not securely backed up?

Note that none of the above is about *preventing* getting compromised! We have tried hard to maintain good prevention all along, and perhaps running through this "detection and remediation" exercise will help us think of ways to further strengthen our prevention, but it is important to me that this exercise is primarily about detection and remediation, not strengthening prevention.

**Comment by zookozcash** [comment]
I think we need to pick the most important subset of these to do before 1.0. It's too much to do everything before then.

**Comment by nathan-at-least** [comment]
I'm going to move this to our devops issue tracker.

**Comment by taoeffect** [comment]
> We have tried hard to maintain good prevention all along, and perhaps running through this "detection and remediation" exercise will help us think of ways to further strengthen our prevention, but it is important to me that this exercise is primarily about detection and remediation, not strengthening prevention.

Is there literature on concrete steps regarding either prevention or mitigation of the trusted setup getting compromised (a thing that's not terribly difficult to do for a nation-state adversary, of which Zcash likely has a couple at least)?

**Comment by nathan-at-least** [comment]
Moved to our infrastructure issue tracker.
