### ISSUE TITLE
Broadcast channel for the zkSNARK multiparty computation

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#768]
The multiparty parameter setup assumes the existence of an authenticated broadcast channel. If the science team hasn't implemented this already, we'll have to do it. We should also double-check it is secure and provides the properties the multiparty setup assumes.

**Comment by defuse** [comment]
Step 1: Decide which protocol to use.

@amiller recommended Dolev-Strong ([see page 11](https://people.csail.mit.edu/ranjit/papers/thesis.pdf)) and mentioned the protocol used by Honey Badger ([see page 10](https://eprint.iacr.org/2016/199.pdf)).

@madars: It's unclear to me from the paper what formal properties the broadcast channel has to have. Is Dolev-Strong sufficient? Do you know of a simpler and/or more efficient option?

**Comment by ebfull** [comment]
Madars said that our broadcast protocol can behave like a bulletin board, sign for your message and the known state.

**Comment by ebfull** [comment]
The MPC design is a "bulletin board" style append-only transcript.
