### ISSUE TITLE
fix the bug that allows time travel attack

### ISSUE THREAD

**Issue by zookozcash** [zcash/zcash#773]
This is very low risk because it is a very simple fix and it has been analyzed, tested, and even deployed by many people.

The advantage of this patch is that it reduces the capabilities of what a dominant miner (often called "51% attacker") can do.

https://github.com/freicoin/freicoin/commit/beb2fa54745180d755949470466cbffd1cd6ff14

**Comment by daira** [comment]
Duplicate of #696?

**Comment by zookozcash** [comment]
Yep.
