### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by loxal** [zcash/zcash#775]
`tune=native -DUSE_ASM -DMONTGOMERY_OUTPUT -DCURVE_ALT_BN128 -I/home/alex/zcash/depends/x86_64-unknown-linux-gnu/include -Isrc -DNO_PROCPS -static -DSTATIC
g++ -o src/gadgetlib2/adapters.o   src/gadgetlib2/adapters.cpp -c -MMD -fPIC -DNO_PT_COMPRESSION=1 -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wno-comment -Wfatal-errors -O2 -march=native -mtune=native -DUSE_ASM -DMONTGOMERY_OUTPUT -DCURVE_ALT_BN128 -I/home/alex/zcash/depends/x86_64-unknown-linux-gnu/include -Isrc -DNO_PROCPS -static -DSTATIC
In file included from src/gadgetlib2/adapters.hpp:18:0,
                 from src/gadgetlib2/adapters.cpp:10:
src/gadgetlib2/constraint.hpp:157:23: error: ‘<::’ cannot begin a template-argument list [-fpermissive]
compilation terminated due to -Wfatal-errors.
make[1]: *** [src/gadgetlib2/adapters.o] Error 1
make[1]: Leaving directory`/home/alex/zcash/depends/work/build/x86_64-unknown-linux-gnu/libsnark/0.1-c4451db1301'
make: **\* [/home/alex/zcash/depends/work/build/x86_64-unknown-linux-gnu/libsnark/0.1-c4451db1301/./.stamp_built] Error 2
make: Leaving directory `/home/alex/zcash/depends'`

…on _Linux gae-default-1--0--0-e76u 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3~bpo70+1 (2016-01-19) x86_64 GNU/Linux_

> using commit commit 559ab22589c75c57ba181a54ac4d92f8cd87818e
> Author: Sean Bowe ewillbefull@gmail.com
> Date:   Wed Jan 20 09:15:36 2016 -0700
> 
> ```
> Added link to alpha guide in the README.
> ```

**Comment by daira** [comment]
http://stackoverflow.com/a/24977313/393146

Summary: g++ is buggy; this code should be valid in C++11 (although there's an easy workaround that we should probably apply to libsnark). What version of g++ is it, out of interest?

**Comment by daira** [comment]
(Digraphs, sheesh. Makes me want to submit an entry to the next [Underhanded Crypto Contest] (https://underhandedcrypto.com)...)

**Comment by daira** [comment]
gadgetlib2 is no longer in our libsnark fork. @loxal, can you try to build again to see whether this is resolved?

**Comment by ebfull** [comment]
I am moving this issue out of the beta milestone since it can only be replicated by one person and it's not a priority for beta.

**Comment by ioptio** [comment]
Closing this due to age and relevance.
