### ISSUE TITLE
run tests under AddressSanitizer (ASan)

### ISSUE THREAD

**Issue by zookozcash** [zcash/zcash#777]
https://github.com/google/sanitizers/wiki/AddressSanitizer

https://github.com/scipr-lab/libsnark/issues/24 was found by use of ASan. Valgrind tries to do the same things. I don't know if running under valgrind (https://github.com/zcash/zcash/issues/761) as well as (in a separate run) under ASan would reveal more problems than running under just one of them.

**Comment by 0x64616E69656C** [comment]
I'd also recommend extending and "simplyfing" the test-suite into smaller test cases, that makes finding bugs easier and quicker ;-)

For example, I ran into some issues with the testcase and the zcashd in testnet mode, e.g. when  __interceptor_malloc() prevented allocating > 2G memory loading the proving key while running the rpc-test with ASan enabled, or ```zcashd -daemon``` instrumented with ThreadSanitizer was killed by the kernel OOM killer on a 16G machine. So in such cases it even might be useful to prevent parts of the code from being instrumented [1]

[1] http://clang.llvm.org/docs/AddressSanitizer.html#disabling-instrumentation-with-attribute-no-sanitize-address

**Comment by daira** [comment]
#1217 is about automating the running of tests under ASan as part of the CI.

**Comment by rcseacord** [comment]
here are the changes I made to get it to run:

rcs@rcs-VirtualBox:~/Test/zcash/zcash$ git diff src/Makefile.am
diff --git a/src/Makefile.am b/src/Makefile.am
index 7c843cb..6fd1a31 100644
--- a/src/Makefile.am
+++ b/src/Makefile.am
@@ -415,7 +415,9 @@ libzcash_a_SOURCES = \
   zcash/prf.cpp \
   zcash/util.cpp
 
-libzcash_a_CPPFLAGS = -DMULTICORE -fopenmp -fPIC -DBINARY_OUTPUT -DCURVE_ALT_BN128 -DBOOST_SPIRIT_THREADSAFE -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS $(HARDENED_CPPFLAGS) $(HARDENED_CXXFLAGS) $(HARDENED_LDFLAGS) -pipe -O1 -g -Wstack-protector -fstack-protector-all -fPIE -fvisibility=hidden -DSTATIC $(BITCOIN_INCLUDES)
+#libzcash_a_CPPFLAGS = -DMULTICORE -fopenmp -fPIC -DBINARY_OUTPUT -DCURVE_ALT_BN128 -DBOOST_SPIRIT_THREADSAFE -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS $(HARDENED_CPPFLAGS) $(HARDENED_CXXFLAGS) $(HARDENED_LDFLAGS) -pipe -O1 -g -Wstack-protector -fstack-protector-all -fPIE -fvisibility=hidden -DSTATIC $(BITCOIN_INCLUDES)
+
+libzcash_a_CPPFLAGS = -DMULTICORE -fopenmp -fPIC -DBINARY_OUTPUT -DCURVE_ALT_BN128 -DBOOST_SPIRIT_THREADSAFE -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS $(HARDENED_CPPFLAGS) $(HARDENED_CXXFLAGS) $(HARDENED_LDFLAGS) -pipe -static-libstdc++ -static-libasan -O -g -Wstack-protector  -fsanitize=address -fstack-protector-all -fPIE -fvisibility=hidden ASAN_OPTIONS=symbolize=1 ASAN_SYMBOLIZER_PATH=/usr/bin/llvm-symbolizer-3.8 -DSTATIC $(BITCOIN_INCLUDES)
 
 # bitcoinconsensus library #
 if BUILD_BITCOIN_LIBS
rcs@rcs-VirtualBox:~/Test/zcash/zcash$ git diff zcutil/build.sh
diff --git a/zcutil/build.sh b/zcutil/build.sh
index 6f79157..d258021 100755
--- a/zcutil/build.sh
+++ b/zcutil/build.sh
@@ -35,5 +35,5 @@ PREFIX="$(pwd)/depends/x86_64-unknown-linux-gnu/"
 
 make "$@" -C ./depends/ V=1 NO_QT=1
 ./autogen.sh
-./configure --prefix="${PREFIX}" --with-gui=no --enable-hardening "$LCOV_ARG" CXXFLAGS='-Wno-deprecated-declarations -Wno-placement-new -Wno-terminate -Werror -O1 -g'
+./configure --prefix="${PREFIX}" --with-gui=no --enable-hardening "$LCOV_ARG" CXXFLAGS='-Wno-deprecated-declarations -Wno-placement-new -Wno-terminate -Werror -static-libstdc++ -static-libasan -g -fsanitize=address'
 make "$@" V=1

**Comment by rcseacord** [comment]
I also installed Clang to 3.8 to get the llvm-symbolizer, which apparently works with gcc and set the following environment variables:

export ASAN_SYMBOLIZER_PATH=/usr/bin/llvm-symbolizer-3.8
export ASAN_OPTIONS=symbolize=1

**Comment by ageis** [comment]
@daira @str4d @nathan-at-least When I add those two ASAN variables to `libzcash_a_CPPFLAGS` as in @rcseacord's diff and then try to run the test suite, etc., I get:

```
g++: error: ASAN_OPTIONS=symbolize=1: No such file or directory
g++: error: ASAN_SYMBOLIZER_PATH=/usr/bin/llvm-symbolizer-3.6: No such file or directory
```

I suspect they are not really supposed to be there (in CPPFLAGS). Might it be sufficient to declare them at build-time in `build.sh`, while having `-static-libasan  -fsanitize=address` in CPPFLAGS?

**Comment by ageis** [comment]
I need to update the asan.patch for rc1. https://ci.z.cash/builders/zcashASan/builds/35/steps/git_1/logs/stdio 
Then I will close this.
