### ISSUE TITLE
randomize or sort the order of input and output notes

### ISSUE THREAD

**Issue by daira** [zcash/zcash#778]
For input notes, this could help to mitigate #679. For output notes, it mitigates potential information leaks to the note recipient (or viewing key holder): if a wallet is implemented in such a way that the ordering of notes depends on private information (such as the relative value of the notes) then that information could be leaked.

**Comment by daira** [comment]
We think that the higher-level payment interface should do this, but that the "raw" RPC interface cannot feasibly do so.

**Comment by daira** [comment]
Sorting the output notes by their commitments, and the input notes by their serial numbers, would suffice to block the information leak.

**Comment by daira** [comment]
@ebfull points out that the computation of a commitment (specifically PRF<sup>ρ</sup><sub>φ 
</sub>(i, hSig) ) depends on its index. Therefore the outputs cannot simply be sorted after computing the commitments, since changing their order would invalidate them.

This leaves two options:
1. If the output commitments are not sorted, pick new r values until they are sorted.
2. Randomize the order of outputs, don't sort them.

I think option 2 is simpler. (If we do option 2 for outputs then we should also randomize the order of inputs, since the benefit of determinism has already been lost in that case.)

**Comment by daira** [comment]
To clarify, the order of outputs would be randomized *before* computing the commitments, so that their order isn't correlated with wallet behaviour. Randomizing their order after computing the commitments would run into the same problem.

**Comment by defuse** [comment]
+1 on randomizing the order of both the inputs and the outputs.

**Comment by daira** [comment]
I need to specify this as well.

**Comment by daira** [comment]
Given that we're doing randomization rather than sorting, this is not a consensus change, so I'm bumping it to beta1.

**Comment by str4d** [comment]
This could be done in several locations:

- `JoinSplit::prove()` - this would cover all potential uses in one place, but has the unfortunate side-effect that the order of the `prove()` outputs (nullifiers, commitments etc) would not correspond to the order provided by the caller (unless we made the inputs and outputs non-const, and modified them for the caller).
- `JSDescription()` - limits the effect to transactions, and still has the above issue
- In the RPC code (#1200) - essentially requires us to implement randomisation anywhere we start creating a JoinSplit, but has the advantage that we know that the ordering of the `JSDescription` properties corresponds to the inputs and outputs we provided.

**Comment by daira** [comment]
We should implement another layer over ``JSDescription`` and have the RPC code use it, IMHO. How much this layer handles is up for discussion.

**Comment by nathan-at-least** [comment]
BTW- I consider this a low priority (in comparison to other beta2 goals). The *one case* I have thought of that makes me hesitate to kick it to post-1.0 is if the non-random order leak compromises a user's activity in the early days before we release a randomized version.

Let's work on this PR later in the Beta 2 process.

**Comment by str4d** [comment]
IIRC @ebfull was going to work on this as part of @bitcartel's RPC work, but I'm not sure if it has happened in any of the open PRs (and @ebfull has had his head in other critical work). Could I get a status update please? I can add this to my list of things to knock out over the weekend if necessary.

**Comment by daira** [comment]
Let's add a ``RandomizedJSDescription`` that just does this, and have the RPC use it in place of ``JSDescription``.

**Comment by str4d** [comment]
@daira and I paired on a function that would permute an array in a way that could be tracked by the caller. Next I will pair with @bitcartel to integrate the new `JSDescription::Randomized()` into the RPC code, and to update the corresponding tests to ensure that the resulting mappings are a valid permutation.
