### ISSUE TITLE
libsnark PRNG hook

### ISSUE THREAD

**Issue by ebfull** [zcash/zcash#780]
Let's hook libsnark's PRNG and attach libsodium's to it. We don't need this for 1.0, probably, but we do as we expand platform support or want better (reproducable) testing.

**Comment by daira** [comment]
+10.

**Comment by daira** [comment]
Actually, doing this would probably be cheaper than a proper security review of libsnark's PRNG.

**Comment by 0x64616E69656C** [comment]
I'm currently running libFuzzer against the libsodium (1.0.8) api functions. so far nothing, including the PRNG. Besides this, I'm always :+1:  for using libsodium whereever possible  ;-)
