### ISSUE TITLE
Failing integration test, running ./qa/pull-tester/rpc-tests.sh on Ubuntu 15.10 

### ISSUE THREAD

**Issue by loxal** [zcash/zcash#797]
Running commit 

```
commit a633044b25c307f9ab89715f52fe87cff2de709c
Author: Sean Bowe <ewillbefull@gmail.com>
Date:   Tue Mar 15 15:59:52 2016 -0600

    Reorder proving key and verifying key arguments.


```

I just got

> Stopping nodes
> Cleaning up
> Tests successful
> Running testscript proxy_test.py...
> Traceback (most recent call last):
>   File "/home/alex/mine/zcash/qa/rpc-tests/proxy_test.py", line 145, in <module>
>     ProxyTest().main()
>   File "/home/alex/mine/zcash/qa/rpc-tests/proxy_test.py", line 61, in **init**
>     self.serv3 = Socks5Server(self.conf3)
>   File "/home/alex/mine/zcash/qa/rpc-tests/test_framework/socks5.py", line 131, in **init**
>     self.s.bind(conf.addr)
>   File "/usr/lib/python2.7/socket.py", line 228, in meth
>     return getattr(self._sock,name)(*args)
> socket.error: [Errno 99] Cannot assign requested address

**Comment by ioptio** [comment]
Closing this ticket because it's very old (pre launch version). Please open a new ticket if there are new problems.
