### ISSUE TITLE
select binary serialization in libsnark

### ISSUE THREAD

**Issue by daira** [zcash/zcash#799]
Apparently it [defaults to] text-based. Ugh.

**Comment by daira** [comment]
Arrgh, it is so much worse than I thought.

https://github.com/scipr-lab/libsnark/blob/master/src/common/serialization.tcc#L53

For example, a bit vector is represented as a sequence of ``size_t``-sized native-endian binary integers (i.e. typically 32 times as large as it needs to be), possibly interspersed with newlines.

Why would anyone write this? Ever?

**Comment by daira** [comment]
I misinterpreted the C++ code; it's actually a (locale-dependent) string representation of 0 or 1, not a native-endian binary representation. So only 8 times as space-inefficient as it needs to be, not 32 times.

**Comment by tromer** [comment]
The textual representation was convenient during development, but as the README points out, `-DBINARY_OUTPUT` switches to a binary representation.

**Comment by daira** [comment]
I see that we're currently [not building](https://github.com/zcash/zcash/blob/1e62bba762e5a2317fa69f6279a615f2fe14cf49/depends/packages/libsnark.mk#L17) with ``-DBINARY_OUTPUT``. This seems like a straightforward improvement. Does it require reencoding the proving and verifying key files?

**Comment by ebfull** [comment]
> Does it require reencoding the proving and verifying key files?

Yes.

The reason we weren't using that flag is that @defuse ran into a bug with it. It may have been unrelated, but it was a very strange issue, so we were a little disturbed by it. It's probably a good idea to just switch over to it and see.

**Comment by tromer** [comment]
Any remaining problems with BINARY_OUTPUT?

Note that, as the libsnark README says:
_libsnark binary serialization routines assume a fixed machine word size (i.e. sizeof(mp_limb_t) for GMP's limb data type). Objects serialized in binary on a 64-bit system cannot be de-serialized on a 32-bit system, and vice versa. (The decimal serialization routines have no such limitation.)_

**Comment by daira** [comment]
Hmm, how much work would it be to clean this up to use the 64-bit serialization format regardless of word size?

**Comment by ebfull** [comment]
@tromer BINARY_OUTPUT and point compression both appear to be working fine.

**Comment by tromer** [comment]
Fixing binary serialization compatibility may be easy. See this new libsnark issue: https://github.com/scipr-lab/libsnark/issues/26
