### ISSUE TITLE
adopt formal code of conduct

### ISSUE THREAD

**Issue by daira** [zcash/zcash#802]
I suggest the Contributor Covenant (e.g. https://twistedmatrix.com/trac/browser/tags/releases/twisted-16.0.0/code_of_conduct.md).

**Comment by ebfull** [comment]
CC @zookozcash

**Comment by daira** [comment]
I volunteer to be one of the people available for reporting of conduct issues.

**Comment by daira** [comment]
https://github.com/zcash/zcash/pull/817

**Comment by daira** [comment]
Merged.
