### ISSUE TITLE
Implement JoinSplit signatures via ``SignatureHash``.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#808]
This is the implementation side of #529.

**Comment by nathan-at-least** [comment]
Note: This is actually specified in Protocol 2.0-alpha-<mumble mumble> but we're implementing it here.

**Comment by nathan-at-least** [comment]
@daira We removed the agenda label because this is already on a milestone. Any other concerns?

**Comment by daira** [comment]
I'm a bit confused as to why this is in the Protocol 2.1 milestone rather than Protocol 2.0-alpha-9bb4410. Especially since, according to https://github.com/zcash/zcash/pull/908#discussion_r62610365 it includes things like the computation of the ``pubKeyHash`` for h<sub>Sig</sub>, not just the ``SIGHASH_*`` semantics.

**Comment by ebfull** [comment]
Calculation of `pubKeyHash` involves adding new fields to `CTransaction`, and at that point you might as well lump it together with this.

**Comment by daira** [comment]
Okay. It's just a little difficult for me to keep track of what it intended to already be implemented, when it doesn't correspond to any particular spec version. But I can live with that, it's just more to remember.

**Comment by ebfull** [comment]
We forgot this in the RPC (and perhaps in other places).

**Comment by defuse** [comment]
What needs to be done for this issue? The new RPC?

**Comment by ebfull** [comment]
In the RPC (decoderawtransaction or another API) there's a todo with this ticket number in it.

**Comment by nathan-at-least** [comment]
In the new high level API, only z_sendmany creates JS's, so that PR will need to do this: #1274 (or maybe a followup PR if that's easier/cleaner).

**Comment by daira** [comment]
I'm totally confused. JoinSplit signatures were already implemented; can we please open a new ticket for the precise thing that was forgotten in the RPC?

**Comment by ebfull** [comment]
See #1309.
