### ISSUE TITLE
Deploy new release to testnet.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#811]
Test/monitor it for failures, especially since we may have untested backwards incompatible breaks such as PoW.

**Comment by ebfull** [comment]
This is done, but I want to see #868 land ASAP.

**Comment by nathan-at-least** [comment]
@ebfull Can we deploy the newly tagged v0.11.2.z2 then close this after doing some manual tests?

**Comment by ebfull** [comment]
We're good to go!

**Comment by ebfull** [comment]
`94f0dcddb4d200d95bafa106047d9020cfc79fd7` is up and running!
