### ISSUE TITLE
Test crypto primitives against an independent non-C++ implementation

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#813]
The correctness of our implementations of the crypto primitives are crucial for security, so let's write them twice, once in C++ and again in Python, so that automated tests can compare the two implementations. I'd include at least:
- The note commitment
- The PRFs
- The calculation of hSig
- KDF

Bonus:
- The Merkle tree root calculation
- Implement the whole NoteEncryption class in Python (with libsodium) and check that you can encrypt with either one and decrypt with the other.

**Comment by zookozcash** [comment]
Great idea! Relatedly: generate test-vectors a.k.a. "Known Answer Tests" for each of them and bake the known answers into our test suite.

**Comment by daira** [comment]
Excellent idea :+1:

**Comment by ebfull** [comment]
The most valuable thing to have written in a separate language would certainly be the NoteEncryption stuff.

**Comment by str4d** [comment]
I have most of this code re-implemented in JavaScript, and have ported some of the tests over.

**Comment by daira** [comment]
This is being done for Sapling in Python 3: https://github.com/zcash-hackworks/zcash-test-vectors
