### ISSUE TITLE
SHA256 compression function doesn't get called when not enough data is passed

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#814]
In both of our SHA256 compression function implementations:

- https://github.com/zcash/zcash/pull/804/files#diff-cf563899256ae1ec7ee78b61806e40caL153
- https://github.com/Electric-Coin-Company/libzerocash/blob/zc.latest.0/libzerocash/utils/sha256.cpp#L99

If you pass in less than 64 bytes, and use them to get the compression function (rather than the full hash) as in this test pattern https://github.com/zcash/zcash/pull/804/files#diff-e872c9211727e681e7485031acee832aR56 then the compression function doesn't actually get called at all!

**Comment by defuse** [comment]
We might not actually trigger this bug, but still the implementations shouldn't allow it!

**Comment by zookozcash** [comment]
Good catch, Taylor!

**Comment by zookozcash** [comment]
Is this bug present in upstream bitcoin-core?

**Comment by ebfull** [comment]
This isn't a bug in upstream implementations, just in ours because you usually calculate the correct length of the padding and invoke the correct properties.

I believe we should enforce in `FinalizeNoPadding` that the length is 64.

**Comment by daira** [comment]
Upstream Bitcoin doesn't use the bare compression function, does it? The bug is in our change to add ``FinalizeNoPadding``.

**Comment by daira** [comment]
I think this API (still, after merging #816) doesn't fit our usage. As I said in https://github.com/zcash/zcash/issues/181#issuecomment-192367337 :
> The ``init``/``update``/``final`` API is wrong for a compression function; it makes it seem as though you can hash multiple blocks even though we never actually do that, and it would be insecure if we did. Let's replace that API with a single ``sha256_compress`` function.

**Comment by daira** [comment]
Moved my suggestion to #819.
