### ISSUE TITLE
Have a plan for increasing commitment tree depth

### ISSUE THREAD

**Issue by daira** [zcash/zcash#821]
Desired properties:
- maintain the anonymity set including all prior notes. This seems as though it requires being able to graft the old tree into the new one. _If_ a different number of hashes is needed for each input note, the circuit must be given this as a _private_ input.
- minimise the design, security analysis, and implementation complexity of the system after the transition. Minimising analysis complexity requires for example being able to easily rule out hash-for-data and similar substitution attacks.

Having a concrete plan for how to do this could help to dispel potential FUD about the scalability of the number of Zcash notes. We could possibly aim to do this as an early hard fork.

**Comment by defuse** [comment]
For a not-completely-insane amount of money, an attacker can max out our network's transaction rate which will exhaust the tree earlier than we expect. We may think there are years of "normal use" left and de-prioritize the depth increase, when there may actually only be months of "attacker is flooding the network use" left. Let's not let that catch us off guard. See my analysis here: https://github.com/zcash/zcash/pull/994#issuecomment-224671113

**Comment by ebfull** [comment]
In an emergency, we can extend the depth of the tree by adding an additional accumulator. An attack begins and we add a new accumulator. Before the attack completes we hardfork to allow anchors to the new accumulator as well. I'm not concerned about a spam attack scenario as long as we have enough notice to implement that change.

If we aren't attacked in such a way, we can increase the depth when we change our tree's CRH.

**Comment by daira** [comment]
In https://github.com/zcash/zcash/issues/2173#issuecomment-285976568 I describe how to expand the number of supported note commitments to ~2<sup>46</sup> without increasing the number of SHA256Compress hashes.

**Comment by daira** [comment]
For Sapling we increased the depth from 29 to 32 (by creating a new commitment tree). This is essentially what @ebfull suggested above, although not prompted by an attack.

**Comment by zookozcash** [comment]
This issue overlaps (partially complementary partially alternative I think) with https://github.com/zcash/zcash/issues/3667. In particular the "union of privacy sets" requirement that Daira listed in this ticket is swapped for a "public turnstile accounting" requirement in that one.

**Comment by nuttycom** [comment]
The plan is to decide on a new commitment tree depth for each new shielded protocol.
