### ISSUE TITLE
Problems signing transaction during the Public Alpha Guide procedure

### ISSUE THREAD

**Issue by JanKalin** [zcash/zcash#839]
Having successfully compiled and started zcashd and recevied some ZEC from the faucet (http://coin.cell.systems/tx/4f5d03c7628515a642dc6384b7d0d3a07d71ee1a0d3a267a162e70936ba3f340
http://coin.cell.systems/address/muKGUbTvPkjWtmLUxdciGQSMnakQhe1vM6)

I am now stuck at the signing stage

`./src/zcash-cli signrawtransaction "$RAWTXN_FROM_ZCRAWPOUR"`

This is what it returns:

`{
    "hex" : "02...0a",
    "complete" : false,
    "errors" : [
        {
            "txid" : "4f5d03c7628515a642dc6384b7d0d3a07d71ee1a0d3a267a162e70936ba3f340",
            "vout" : 0,
            "scriptSig" : "",
            "sequence" : 4294967295,
            "error" : "Operation not valid with the current stack size"
        }
    ]
}`

**Comment by ebfull** [comment]
Usually what happens is that when you did the `createrawtransaction` call originally, you specified the wrong `vout` of the output you were spending.

Do `listunspent` again and compare what you're spending with the `txid` and `vout` of your `createrawtransaction` call.

**Comment by JanKalin** [comment]
Thanks. Yes, the `vout` was wrong, 0 instead of 1.
