### ISSUE TITLE
Bug hunter wall of fame

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#840]
Here's an idea: We could have a "wall of fame" where we put people's names up on a page in our public website when they find security bugs in Zcash. This would incentivize people to look for bugs even if we don't have a cash-reward bug bounty.

**Comment by nathan-at-least** [comment]
I'm going to delegate the decision and execution of this to the PR/website teams.

**Comment by nuttycom** [comment]
Not a zcashd feature.
