### ISSUE TITLE
rename bitcoin.conf to zcash.conf

### ISSUE THREAD

**Issue by daira** [zcash/zcash#844]

**Comment by JanKalin** [comment]
There are other places where bitcoin remains, e.g., in the "zcash-cli" help message. But I'm sure that refactoring will be done before the final release.

**Comment by daira** [comment]
Yes, I meant that we should prioritize this as more important than, e.g. message strings, to avoid people having to rename their ``bitcoin.conf`` files later (or worse, have their edits to them ignored).

**Comment by daira** [comment]
Also rename ``bitcoind.pid`` to ``zcashd.pid``.

https://github.com/nathan-at-least/zcash/blob/525a3b92238b9489effd5adc21a0b0d5de18269b/doc/files.md

**Comment by daira** [comment]
I want to get this into the next release; the earlier we do it, the fewer people who have made changes to their config files will be affected.

**Comment by daira** [comment]
Fixed via #907.
