### ISSUE TITLE
specify the memo field requirements - include metadata with sent coins

### ISSUE THREAD

**Issue by daira** [zcash/zcash#85]
In https://github.com/Electric-Coin-Company/zerocashd/issues/72#issuecomment-72696961 , Nathan wrote:

> A cleaner solution [than using multiple addresses to associate payments with customer-specific context] would be to attach transaction metadata. Note that the multi-address approach requires an interactive seller, so this rules out billboards.
> 
> If instead, the buyer is required to attach appropriate metadata, this could still support the billboard use case: "Buy your ticket today! Send 12 ⓩ to Zf3bl… and you must include your phone number in the Memo line." If this is a feature we would add, we obviously want confidentiality such that the recipient and sender are the only ones who can read the Memo field.

It seems quite straightforward to modify a Pour operation to include metadata in the plaintexts corresponding to <b>C</b><sub>1</sub> and <b>C</b><sub>2</sub> (see step 1) j) in the description of a Pour operation in Figure 2 of the [Oakland paper](http://zerocash-project.org/media/pdf/zerocash-oakland2014.pdf)). The protocol already ensures that this metadata is confidential and non-malleable. A minor complication is that information could be leaked by the ciphertext lengths, so perhaps we should fix a size for the metadata field and always include it.

**Comment by daira** [comment]
@zookozcash recently suggested that the memo field should be 64 bytes. One reason why I had originally proposed 256 bytes is that I was taking into account that the UTF-8 encoding of strings in some scripts may use up to 4 bytes per character. Although some such scripts (Hangul and Han for instance) are more information-dense per-character, others are only approximately as dense as Latin; they use 3 or 4 bytes per character purely by happenstance of where they were encoded. 256 bytes is sufficient to compensate for this and still allow a useful number of characters to be encoded; 64 bytes would only allow 16 characters (and potentially fewer grapheme clusters if the Unicode coding of the language/script uses combining characters heavily), which could be seen as quite stingy.

**Comment by nathan-at-least** [comment]
This imposes a requirement on envelope encryption, which we're proceeding with #558. Additionally, we need follow up changes (separate tickets) to the RPC interface to allow memo specification.

**Comment by daira** [comment]
As I just pointed out in #288, the upgrade path to  privacy-preserving delegation of Pour detection would be made easier if there is room to reduce the initial length of the memo field by 16 bytes (the length of an authentication tag) for coin ciphertexts that are double-encrypted to a detector public key.

Given this and the Unicode issue raised above, I recommend a memo field of 128 bytes.

**Comment by daira** [comment]
I need to re-estimate the overhead for the current design (with and without viewing keys).

**Comment by defuse** [comment]
+1 to increasing it to 128 bytes.

**Comment by zookoatleastauthoritycom** [comment]
+1 to increasing it to 128 bytes

**Comment by ebfull** [comment]
For what it's worth, I opposed (probably over IRC at the time) the addition of a memo field, and still think it's a matter for another layer. However, if we're having a memo field, it makes sense for it to be large enough that it's useful, so +1 to 128 byte memos.

**Comment by daira** [comment]
Fixed.

**Comment by daira** [comment]
Reopening because @zookozcash wants to consider a larger memo field size.

**Comment by nathan-at-least** [comment]
We need some kind of reference in selecting a size. Here are some recommendations:

* [UK Government Data Standards Catalogue, page 16](http://webarchive.nationalarchives.gov.uk/+/http://www.cabinetoffice.gov.uk/media/254290/GDS%20Catalogue%20Vol%202.pdf) (via https://stackoverflow.com/questions/20958/list-of-standard-lengths-for-database-fields), which recommends 35 chars/line * 5 lines max.
* [The Length of International Addresses and Your Database](http://blog.worldvu.com/2011/09/length-of-international-addresses.html) which has a table showing a worst-case for "international addresses" at 10 lines * 54 chars/line, and an "average" of 5.9 lines * 14.8 chars/line. For the US these numbers are worst case 6 lines * 30 chars/line and "average" 4.1 lines * 18.9 chars/line.

Note these are characters, so we need to account for UTF-8 encoding size.

**Comment by nathan-at-least** [comment]
Estimates:

International address average: ``5.9 lines * 14.8 chars/line * ~2.5 bytes/char = 218 bytes``
International address worst-case: ``10 lines * 54 chars/line * ~3 bytes/char = 1620 bytes``
US worst-case assuming ASCII-only: ``6 lines * 30 chars/line * ~1 byte/char = 180 bytes``

**Comment by nathan-at-least** [comment]
Given the above estimates, 128 bytes seems too small for "average", and 256 bytes might accommodate "average". One issue is that "average" may be the mean, and median or 90% percentile or something like that would be much more helpful.

Note that when a UI makes it apparent to users that there is a length limit, they can often squash addresses in an manner acceptable to postal services.

**Comment by nathan-at-least** [comment]
This was re-opened, and it "fits naturally" with our RPC specification, although notice that it is altering a consensus rule.

**Comment by nathan-at-least** [comment]
ping @zookozcash What's your decision about memo field size, given the above references / estimates?

**Comment by daira** [comment]
I believe @zookozcash was thinking the FinCEN "travel rule", for which there is an FAQ [here](https://www.sec.gov/about/offices/ocie/aml2007/fincen-advissu7.pdf). I'm not sure how much if any of the information specified there it makes sense for payers to transmit in a private payment protocol, although some of it may be okay to send in some selective transparency cases.

**Comment by zookozcash** [comment]
Okay, let's make the memo field be 512 bytes.

**Comment by daira** [comment]
ACK, I'll update the spec.

**Comment by bitcartel** [comment]
Reminder that this will need a PR to update ZC_MEMO_SIZE in zcash.h.

**Comment by nathan-at-least** [comment]
Close this ticket when the spec is appropriately updated. Meanwhile, we have a separate ticket now (#1187) for the size change itself.

**Comment by daira** [comment]
Spec change moved to https://github.com/zcash/zips/issues/60

**Comment by zookozcash** [comment]
I can't find the memo format spec ZIP or an issue ticket to track it. https://github.com/zcash/zips/issues/60 is not it.

**Comment by zookozcash** [comment]
Oh, sorry. I thought this was the memo format spec zip. My mistake.
