### ISSUE TITLE
[Meta] How do we track issues in our dependencies (or in Bitcoin Core)?

### ISSUE THREAD

**Issue by daira** [zcash/zcash#855]
For example, https://github.com/scipr-lab/libsnark/issues/24 is a security issue in libsnark. Do we open another issue here to track that? It's too easy for issues in dependencies or in upstream bitcoin to get forgotten (by us) otherwise, and we need some way to assign the issue to a Zcash milestone.

Note that github does not support any Launchpad-style formal linking of issues (even just within github), and therefore there's no at-a-glance indication of the status of a linked ticket. I guess it's tolerable to update that manually, but blech.

**Comment by daira** [comment]
Hmm, maybe this is what I want:

https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+user%3Azcash+user%3Ascipr-lab+user%3Abitcoin+sort%3Aupdated-desc

**Comment by daira** [comment]
For the example libsnark issue above, I didn't spot that our ticket is #780. How would I have spotted that? (Maybe by looking at the libsnark label, but that still means trawling through a bunch of less relevant tickets.)

I propose a convention where we edit the first comment of our ticket to link to the upstream ticket. Unfortunately we can't edit the first comment of their ticket to link to our ticket, in general.

**Comment by nathan-at-least** [comment]
Let's make "place-holder" tickets for anything that's we need on our roadmap that crosslink. :-<

**Comment by Eirik0** [comment]
Further tracking of this ticket will happen https://github.com/zcash/zcash/issues/3786
