### ISSUE TITLE
Add a ``gcov`` enabled build and profiling run of unit test binary

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#858]

**Comment by defuse** [comment]
I use `cpp-coveralls` in my password generator: https://github.com/defuse/passgen I'm not sure if that's something different from gcov or if it just uses gcov under the hood.

**Comment by nathan-at-least** [comment]
I'm going to experiment with adding ``gcov`` to my WIP results of #861.

**Comment by nathan-at-least** [comment]
There's already some system for ``gcov``-based report generation: ``--enable-lcov``, as seen in [``src/Makefile.am`` L145-L197 at ``f2ea1ec1``](https://github.com/bitcoin/bitcoin/blob/f2ea1ec1a02be783688ac2335e5e5281de6cd3e3/src/Makefile.am#L145-L197) ([latest on branch ``nathan_t858-gcov``](https://github.com/bitcoin/bitcoin/blob/nathan_t858-gcov/src/Makefile.am#L145-L197)).

Going to hook ``zcash-gtest`` into that, but also see if we can optionally run/generate reports for only this new test binary rather than the non-mock integration tests.

**Comment by nathan-at-least** [comment]
This is available on our ``.latest``.
