### ISSUE TITLE
Review Bitcoin feature proposals with wide support but which require forks to implement.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#86]
There are probably quite a few "low hanging fruit" features that have already been specified, implemented, and tested for Bitcoin *but* for which there is not an easy/clear upgrade strategy because of forks (hard or soft).

Let's review all of those and see if we want to enable any prior to launch, while we have the benefit of not worrying about forks.

**Comment by zookozcash** [comment]
Per https://github.com/zcash/zcash/issues/86#issuecomment-134398466 I'm closing this ticket.
