### ISSUE TITLE
Integrate production Founders' Reward keys into ChainParams.

### ISSUE THREAD

**Issue by daira** [zcash/zcash#870]
The plan is to pay the Founders' reward to a transparent multisig address. The one used on the testnet is just temporary. Because it will receive 10% of the eventual monetary base, the keys for this address need to be particularly securely generated and stored (maybe in hardware wallets?) See also https://github.com/zcash/zcash/issues/125#issuecomment-196629653 , which suggests paying to different addresses (baked in at the start) in subintervals of the 4-year reward period.

**Comment by daira** [comment]
Note that operational security requires that we not go into too much detail on this ticket. However, it is fine to brainstorm ideas here.

**Comment by defuse** [comment]
Make sure to balance security measures with availability guarantees. Accidentally losing those keys could be worse than them getting stolen.

**Comment by daira** [comment]
Note that we did use the idea from https://github.com/zcash/zcash/issues/125#issuecomment-196629653 . Thanks @zmanian!
