### ISSUE TITLE
Ensure zcrawpour and CheckTransaction check the same properties

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#875]
In CheckTransaction we check some properties of the PourTx which are not also checked in the zcrawpour RPC implementation. This could lead to someone creating a pour with zcrawpour that isn't valid on the network.

(e.g. #466).

**Comment by nathan-at-least** [comment]
We're probably going to deprecate zcrawpour prior to launch making this less relevant. So closing as wontfix.
