### ISSUE TITLE
Build Zcash as an Android Native Activity

### ISSUE THREAD

**Issue by daira** [zcash/zcash#878]
http://developer.android.com/ndk/guides/concepts.html#naa

Just building on Android is not that useful in itself, but is a prerequisite to other Android development based on Zcash Core.

**Comment by kxra** [comment]
Has there been any progress on this? 

Seems freewallet.org has an Android app supporting Zcash, but I don't think there's an easy way to mine with the mobile app for Minergate

**Comment by nuttycom** [comment]
Light clients are more suitable for Android use.
