### ISSUE TITLE
Add buildbot column to generate coverage reports (at least for mock tests)

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#880]
Coverage reports are implemented in PR #879, so when that merges we're ready to add a buildbot task to generate them. We also need to serve up the generated HTML somewhere, probably just on the buildbot host.

**Comment by defuse** [comment]
Before I forget: Nathan said something about passing a flag to build.sh and `make coverage` or something like that.

**Comment by daira** [comment]
This seems to not be uploading the results yet: http://ci.leastauthority.com:8010/builders/zcashcoverage/builds/4/steps/upload/logs/err.text

**Comment by defuse** [comment]
It's done now!

**Comment by defuse** [comment]
It seems to be working now, so I'm closing this ticket :)
