### ISSUE TITLE
Consider mmap'ping the proving key into memory

### ISSUE THREAD

**Issue by daira** [zcash/zcash#890]
This would improve loading time and also allow the pages to be shared between processes. It won't work unless the file format is the same as the in-memory format, which it currently isn't (see #799).

**Comment by daira** [comment]
Test

**Comment by daira** [comment]
Another possibility is to put the proving and verifying keys into a shared library, and packaging that library That would have the advantage of sharing this memory between multiple processes using the keys (and the implementation of shared library loading from disk is pretty well optimised on most operating systems).

**Comment by ebfull** [comment]
I think it would be far better to stream the proving key from disk during proving time, which both amortizes away the initialization cost (which is already a design issue with our RPC) and vastly reduces memory usage. My understanding is that this is possible but will require us to rewrite the proving routines.

**Comment by nathan-at-least** [comment]
I had the impression that mmap'ing an array, and then accessing it randomly *is* a way to make that memory "streaming" by relying on the VFS layer.

I think the best case story for mmap is: "We access an array, and by adding just a few lines to call mmap, suddenly we get VFS memory management, which happens to be 90% good enough for our needs."

In our case, the story might be more like: "We have all these C++ instances, so we have to jump through weird hoops to allocate them inside an mmap, and then we have to add a few lines of mmap management, but then the VFS streaming / caching behavior doesn't quite fit our application well."

But, I just want to be sure our story is not closer to the "mmap ideal".

**Comment by daira** [comment]
I want a little time to research how mmap behaves before we decide on this.

**Comment by nathan-at-least** [comment]
Agreed. Note that this has "not in 1.0" so let's not spend much more time on it right now. As for streaming parameters, we need to make a design trade-off decision as part of #56 (tradeoffs listed here: https://github.com/zcash/zcash/issues/432#issuecomment-234002650).

**Comment by ebfull** [comment]
The problem with mmap is we have to deserialize from the proving key anyway. It just so happens we only need each (small) portion of the proving key *once* during proof generation, so perhaps we should just stream it from disk to reduce IO/caching.

**Comment by daira** [comment]
@ebfull:
> The problem with mmap is we have to deserialize from the proving key anyway.

Not necessarily; the file could be in the required in-memory format already. (This seems easier if we use the library approach mentioned above in https://github.com/zcash/zcash/issues/890#issuecomment-233800513 , since then the library can directly declare a data structure compatible with the C++ ABI.

**Comment by ebfull** [comment]
That's interesting, I've always been scared of doing that because of alignment issues...

**Comment by daira** [comment]
No longer relevant: libsnark is going away in #4060, and the Groth16 proving keys are not large enough to worry about this.
