### ISSUE TITLE
Enable MULTICORE in libsnark build.

### ISSUE THREAD

**Issue by daira** [zcash/zcash#896]
The [current build configuration for libsnark](https://github.com/zcash/zcash/blob/zc.v0.11.2.latest/depends/packages/libsnark.mk) does not enable ``MULTICORE`` or ``USE_ASM`` options. Investigate to what extent these improve performance of JoinSplit proof and verification, to decide whether we should enable either or both of them.

``MULTICORE`` obviously needs to be benchmarked on systems with various numbers of cores/hyperthreads. It uses the number of threads reported by OpenMP (which is a compiler-supported thing, not an external library).

``USE_ASM`` incurs a greater risk of bugs, and should only be enabled if any observed performance advantage is significant enough to justify the cost of security-reviewing all of the asm code in libsnark within the 1.0 launch schedule. The asm code appears to be only for x86-64.

**Comment by daira** [comment]
For ``MULTICORE``, we also need to check whether it could interfere with optimising memory usage.

**Comment by zookozcash** [comment]
I am very reluctant to approve either of these two changes for 1.0 "Sprout", _even_ if it turns out that they help a lot.

On the other hand, I would like to have the information about how much they help, in order to (right now!) start selling future, post-1.0, versions of Zcash to enterprise customers and to the public.

As far as marketing it to the public, we could make a list of known potential performance improvements and estimated or measured speedups, and that could be a blog post.

The blog post would emphasize that these speedups are coming _after_ 1.0 Sprout launch.

**Comment by nathan-at-least** [comment]
@zookozcash What information would you like to have? That would help us define this ticket.

Otherwise, I'm inclined to postpone it until after 1.0.

**Comment by daira** [comment]
I'm very concerned that mitigating the attacks mentioned on #714 will increase the cost of proving to the point that we *have* to do some of the performance enhancements we've talked about (this ticket, #750, #647) before launch.

**Comment by nathan-at-least** [comment]
We've decided to enable ``MULTICORE`` but *not* ``USE_ASM`` for the time being.

**Comment by daira** [comment]
I'm reviewing all uses of ``MULTICORE`` in libsnark.

In the ``enter_block`` and ``leave_block`` functions of ``src/common/profiling.cpp``, there appear to be shared variables (e.g. ``block_names``, ``invocation_counts`` etc.) that are modified outside a ``#pragma omp critical`` section. (There are critical sections in those functions, so they're presumably called from parallel code, but they're not covering all of the shared variable writes.)

**Comment by ebfull** [comment]
A while ago I disabled those profiling features, because they were indeed causing race conditions with parallel proving/verifying routines.

**Comment by daira** [comment]
It should be relatively straightforward to extend the ``#pragma omp critical`` blocks to fix that.

**Comment by tromer** [comment]
Those global variables contain thread-specific information (e.g., current stack of nested blocks), so just protecting the code that updates them won't be enough. And even if we made the block stack thread-local, it's not clear what the profiling output should look like.

However:

IIRC libsnark currently never does `enter_block()`/`leave_block()` inside parallelized code, so neither problem arises.

We should, at the very least, add an `assert` to `enter_block()` to catch this situation. Is there a good way to figure out whether we're currently inside a `#pragma omp parallel` block?

(Upstream libsnark welcomes patches...)

**Comment by daira** [comment]
Yes, ``omp_in_parallel()``.
