### ISSUE TITLE
Enforce 4 leading bits are zero on 252-bit values

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#899]
After #888 is merged, those values are represented by `uint256` and when they're given to the PRF the leading bits are masked off. I'd prefer to throw an exception when those leading bits are nonzero, and to have a separate method for generating those 252-bit values (instead of just generating a random `uint256`. Sean also suggest having a `uint252` type, which I would also like.

**Comment by daira** [comment]
+1 for a uint252 type.
