### ISSUE TITLE
Gather empirical evidence of ``sendmany`` output arity distribution from exchanges.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#900]
This is a subset of #426 that focuses on: only output arity, only exchange ``sendmany`` distribution data.

Note we do not plan to adjust the output arity prior to 1.0 launch, so this ticket is just to ensure we have this useful real-world performance data on-hand for future optimizations.

**Comment by daira** [comment]
Note that we cannot increase the output (or input) arity beyond 3 without changing the PRF domain separation.

**Comment by ebfull** [comment]
@daira do you mean beyond 2?

**Comment by daira** [comment]
No, 3. (The formats are deliberately designed to allow easy expansion to 3.)

**Comment by nathan-at-least** [comment]
Added to the meeting agenda, where I will advocate for sticking to 2x2 for launch and removing all arity-adjustment work out of the critical path.

**Comment by nathan-at-least** [comment]
We aren't changing circuit arity for 1.0, so this is wontfix.
