### ISSUE TITLE
Decide if / how to alter transaction priority to account for mining slow start

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#904]
(This issue is based on [this comment](/zcash/zcash/pull/887#issuecomment-216378652))

The code inherited from Bitcoin Core [has a requirement](/zcash/zcash/blob/zc.v0.11.2.latest/src/txmempool.h#L18) that large (in bytes) low-priority (new, small-coin) transactions need a fee. This normally doesn't affect coinbase because:

- Coinbase can only be spent after 100 confirmations.
- By the time that the block reward is small enough to not qualify even after 100 confirmations, miners and users are all expecting fees anyway.

The problem is that with mining slow start, the initial coins are all new *and* small, and individual spends of them fall below the priority threshold:

- Threshold: `1 ZEC * 144 / 250 = 0.576`
- First block cannot be spent ASAP: `0.01 ZEC * 100 / 250 = 0.004`
- 144th block is first that can be spent ASAP: `1.44 ZEC * 100 / 250 = 0.576`
- First block reaches threshold: `0.01 ZEC * 14,400 / 250 = 0.576`
  - First block coinbase therefore requires a fee until 100 days after mining starts.

I am somewhat concerned about what effect this will actually have on the spendability of coins mined within the mining slow start ramp (or at least within the first few hundred blocks).

Do we want to consider altering the priority calculation for coins mined during slow start to match that of higher-value coins? Perhaps regular 40 ZEC coins? Or have the first 144 coins be "equal" in priority to a 1.44 ZEC coin, and then ramp up as usual from there? Or some other policy? Or just require fees (status quo)?

**Comment by str4d** [comment]
It was pointed out in the engineering meeting that the 144th block (which is the first that can be spent on its own without fee) can be spent on its own from block 244, which should be ~40.7 hours after launch. However, the calculations above do not account for the presence of JoinSplits, and we will be enforcing in consensus rules that coinbase must go though a JoinSplit first (#101). @ebfull said a rough estimation of the size of a single JoinSplit is 1000 bytes, which changes the calculations thusly:

- Threshold: `1 ZEC * 144 / 250 = 0.576`
- First block cannot be spent ASAP: `0.01 ZEC * 100 / 1250 = 0.0008`
- 720th block is first that can be spent ASAP: `7.2 ZEC * 100 / 1250 = 0.576`
  - This block is expected to be mined exactly 5 days after launch.
- First block reaches threshold: `0.01 ZEC * 72,000 / 1250 = 0.576`
  - First block coinbase therefore requires a fee until 500 days (~1.4 years) after mining starts.

I could justify to myself ignoring this problem if it only lasted 40 hours and we had a wallet that understood this issue and selected coins accordingly. But a 5 day delay and longer tail, combined with the expected eagerness of uptake in the first few days, makes doing nothing a bit harder to justify.

**Comment by defuse** [comment]
I'm concerned that if the tests make such assumptions than we may be missing non-test code that also makes those assumptions. (an #826 thing)

**Comment by nathan-at-least** [comment]
Let's deprecate priority (similar to upstream bitcoin-core). Maybe for our 1.0 release we should set the default ``blockprioritysize = 0`` just like Bitcoin core 0.12.

**Comment by nathan-at-least** [comment]
Wait... why does some code refer to the *constant* named ``DEFAULT_BLOCK_PRIORITY_SIZE`` *instead* of the result of parsing the ``-blockprioritysize`` argument.

**Comment by daira** [comment]
I want the fee acceptance logic to be simple enough to fit in my head. At the moment it's ridiculously overcomplicated :-(

**Comment by str4d** [comment]
There are two parts to the algorithm: the checks for accepting a transaction into the mempool, and the checks for mining a mempool transaction into a block.

`-blockprioritysize` defaults to `DEFAULT_BLOCK_PRIORITY_SIZE` and is used in `CreateNewBlock()`; if `-blockprioritysize <= 0` then blocks are filled highest-fee-first. In fee-sorted mode, transactions are only included until the block passes `-blockminsize`.

`DEFAULT_BLOCK_PRIORITY_SIZE` is only used on its own in `GetMinRelayFee()`, to avoid encouraging multiple small transactions instead of one big transaction to avoid fees.

This issue is concerned with early-coin-containing transactions not being accepted into the mempool due to insufficient priority. This behaviour can be disabled with `-relaypriority = false`. I will test this out in the mining slow start RPC tests (prior to removing them per our decision on that PR), to see if setting that default is sufficient to alleviate this issue.

**Comment by str4d** [comment]
Setting the default `relaypriority` to false does remove the `insufficient priority` errors in the mining slow start RPC tests (and uncovers other errors in those tests, but we are removing them now per [#762 (comment)](/zcash/zcash/issues/762#issuecomment-218125048)).

**Comment by nathan-at-least** [comment]
Let's just go with setting the ``-relaypriority = false`` default.

**Comment by str4d** [comment]
Diagnosing a test failure in #989, I realised another issue. As part of keeping the monetary supply and mining slow-start ramp the same across the block interval decrease, the maximum block subsidy is quartered and length of the ramp is quadrupled. This has the effect of decreasing the value of the first coinbase by `1/16`. Additionally, the calculations above neglected the effect of the founder's reward (the first block valye above should have been 0.008 ZEC). Recalculating:

- Threshold: `1 ZEC * 144 / 250 = 0.576`
- First block cannot be spent ASAP: `0.0005 ZEC * 100 / 1250 = 0.00004`
- 14400th block is first that can be spent ASAP: `7.2 ZEC * 100 / 1250 = 0.576`
  - This block is expected to be mined exactly 25 days after launch, and spendable after ~4.2 hours (since the 100-block time-to-maturity is currently being maintained).
- First block reaches threshold: `0.0005 ZEC * 1,440,000 / 1250 = 0.576`
  - First block coinbase therefore requires a fee until 2500 days (~6.8 years) after mining starts.

So yes, we definitely want to go with the above :sweat_smile:
