### ISSUE TITLE
add -Wno-deprecated-declarations to recipe for compiling boost (or globally?)

### ISSUE THREAD

**Issue by daira** [zcash/zcash#911]
This will get rid of the spurious warnings about ``std::auto_ptr`` being deprecated.

**Comment by defuse** [comment]
I'll do this since I've spent 2 hours scrolling through warnings to find the actual errors today.

**Comment by daira** [comment]
https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#Warning-Options

``-Wno-deprecated-declarations``
> Do not warn about uses of functions (see Function Attributes), variables (see Variable Attributes), and types (see Type Attributes) marked as deprecated by using the deprecated attribute.

It's a bit of a sledgehammer for just suppressing the ``auto_ptr`` warnings, but I don't care about any other deprecated stuff used by boost either; that's the boost devs' problem.

**Comment by defuse** [comment]
This will come in #913.

**Comment by nathan-at-least** [comment]
Yes! Let's figure out how to use the compiler to tell us only about useful problems. ;-)

One note of caution: I'm only comfortable disabling specific warnings *only for* boost compilation. If boost *headers* rely on some warning-generating construct, then those warnings will still appear when compiling zcash. If that happens, let's figure out a separate strategy for that.

**Comment by defuse** [comment]
@nathan-at-least: What I did in #913 does exactly what you mentioned not wanting to do. I also did something *worse* which was to disable security features that were generating warnings (some of which were already unintentionally disabled)! See #915.

**Comment by defuse** [comment]
I'm fine with adding `-Wno-deprecated-declarations` to the whole build until we figure out a better solution since a quieter build will speed up our development a lot: I spent around ~2hrs total yesterday just scrolling through the output trying to find the actual compile error, because it was always above/between the useless warnings. Now that the build is quiet I can find the error instantly.

**Comment by defuse** [comment]
In my pairing with @nathan-at-least just now:

-  We tried upgrading boost to 1.60 and found that they haven't fixed the warnings yet. It actually made things worse because we're currently using stuff that's deprecated in that version of boost so there are even *more* warnings when we use that version.
- We looked at the `-isystem` flag which is like `-I` but (among other unknown effects) turns off reporting of warnings in those header files. We rejected that because we could only easily apply it to *all* depends packages, not just boost, so it's too broad and could hide important warnings.
- We decided to keep `-Wno-deprecated-declarations` since it's clear which types of warnings we'll possibly be missing.

I'm going to:

1. Do a full rebuild without `-Wno-deprecated-declarations` and save the output, then grep for `: warning:` to list all the warnings, and check our hypothesis that they are all `auto_ptr` warnings.
2. Do a full rebuild with `-Wno-deprecated-declarations` and check how many warnings there are.

**Comment by defuse** [comment]
If there aren't too many warnings with `-Wno-deprecated-declarations` then I can just fix them and we'll enable `-Werror`.

**Comment by daira** [comment]
Could we use
```
#pragma GCC diagnostic push
#pragma GCC diagnostic warning "-Wno-deprecated-declarations"
#include <boost/smart_ptr/shared_ptr.hpp>
#include <boost/smart_ptr/scoped_ptr.hpp>
#pragma GCC diagnostic pop
```
in a header that gets included first?

**Comment by daira** [comment]
I would prefer to have a separate PR and separate review for this rather than including it in the PR for #913. On the Fortify optimization issue, I'm in favour of enabling ``-O1``.

**Comment by defuse** [comment]
I think what I'm going to do is try to patch this stuff https://github.com/zcash/zcash/issues/911#issuecomment-217049144 into the boost header files themselves. It's a trickier change but will hide less warnings.

**Comment by defuse** [comment]
There's also `-Og` which might enable enough optimization for the FORTIFY stuff to work, I'll see.

**Comment by daira** [comment]
My impression from the documentation was that ``-Og`` wasn't sufficient, but you could try it.

**Comment by defuse** [comment]
Here are the warnings from a fresh build, excluding FORTIFY_SOURCE and auto_ptr:

```
[firexware@firexware-pc zcash]$ cat BUILD_STDERR | grep warning: | grep -v auto_ptr | grep -v FORTIFY
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[2]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[2]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[2]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[2]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[1]: warning: -jN forced in submake: disabling jobserver mode.
d1_both.c:1367:3: warning: ‘save_write_sequence’ may be used uninitialized in this function [-Wmaybe-uninitialized]
make[1]: warning: -jN forced in submake: disabling jobserver mode.
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
libtool: install: warning: remember to run `libtool --finish /home/firexware/Data-1/Documents/FireXware/la/zcash/depends/x86_64-unknown-linux-gnu/lib'
src/gadgetlib2/variable.cpp:120:1: warning: control reaches end of non-void function [-Wreturn-type]
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
libtool: warning: remember to run 'libtool --finish /home/firexware/Data-1/Documents/FireXware/la/zcash/depends/x86_64-unknown-linux-gnu/lib'
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
Makefile.am:5: warning: user variable 'GZIP_ENV' defined here ...
Makefile.am:55: warning: user target 'distcleancheck' defined here ...
src/Makefile.am:468: warning: user target '.mm.o' defined here ...
crypto/equihash.cpp:250:29: warning: narrowing conversion of ‘pow(2.0e+0, (double)((Equihash*)this)->Equihash::k)’ from ‘double’ to ‘eh_index {aka unsigned int}’ inside { } [-Wnarrowing]
crypto/equihash.cpp:250:29: warning: narrowing conversion of ‘pow(2.0e+0, (double)((Equihash*)this)->Equihash::k)’ from ‘double’ to ‘eh_index {aka unsigned int}’ inside { } [-Wnarrowing]
zerocash/utils/util.cpp:38:6: warning: stack protector not protecting local variables: variable length buffer [-Wstack-protector]
zerocash/utils/util.cpp:48:6: warning: stack protector not protecting local variables: variable length buffer [-Wstack-protector]
zerocash/utils/util.cpp:127:6: warning: stack protector not protecting local variables: variable length buffer [-Wstack-protector]
zerocash/utils/util.cpp:134:6: warning: stack protector not protecting local variables: variable length buffer [-Wstack-protector]
zerocash/utils/util.cpp:219:6: warning: stack protector not protecting local variables: variable length buffer [-Wstack-protector]
zerocash/utils/util.cpp:230:6: warning: stack protector not protecting local variables: variable length buffer [-Wstack-protector]
zerocash/utils/util.cpp:241:6: warning: stack protector not protecting local variables: variable length buffer [-Wstack-protector]
zerocash/utils/util.cpp:254:6: warning: stack protector not protecting local variables: variable length buffer [-Wstack-protector]
zerocash/utils/util.cpp:267:6: warning: stack protector not protecting local variables: variable length buffer [-Wstack-protector]
zerocash/utils/util.cpp:281:6: warning: stack protector not protecting local variables: variable length buffer [-Wstack-protector]
zerocash/utils/util.cpp:295:6: warning: stack protector not protecting local variables: variable length buffer [-Wstack-protector]
zerocash/utils/util.cpp:309:6: warning: stack protector not protecting local variables: variable length buffer [-Wstack-protector]
test/sighash_tests.cpp:133:54: warning: narrowing conversion of ‘(insecure_rand() % 100u)’ from ‘uint32_t {aka unsigned int}’ to ‘unsigned char’ inside { } [-Wnarrowing]
test/sighash_tests.cpp:133:77: warning: narrowing conversion of ‘(insecure_rand() % 100u)’ from ‘uint32_t {aka unsigned int}’ to ‘unsigned char’ inside { } [-Wnarrowing]
test/sighash_tests.cpp:134:54: warning: narrowing conversion of ‘(insecure_rand() % 100u)’ from ‘uint32_t {aka unsigned int}’ to ‘unsigned char’ inside { } [-Wnarrowing]
test/sighash_tests.cpp:134:77: warning: narrowing conversion of ‘(insecure_rand() % 100u)’ from ‘uint32_t {aka unsigned int}’ to ‘unsigned char’ inside { } [-Wnarrowing]
```

**Comment by daira** [comment]
The ``pow(2.0e+0, ...)`` in ``equihash.cpp`` should probably be left-shifts. The narrowing conversions in ``sighash_tests.cpp`` need explicit casts to ``unsigned char`` to suppress the warning. For the jobserver warning, see https://blog.flameeyes.eu/2008/11/for-a-parallel-world-case-study-n-4-jobserver-unavailable .

**Comment by defuse** [comment]
Opened #941 about the jobserver stuff since it seems to be inside the depends system stuff.
