### ISSUE TITLE
Update alpha guide for Protocol 2016.0-alpha-3 Implementation release

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#912]
https://github.com/zcash/zcash/pull/907#issuecomment-216710688

**Comment by defuse** [comment]
(I think there were some more big things that needed to be mentioned, but I can't recall them at the moment.)

**Comment by daira** [comment]
Add instructions to:

- [ ] clear out blockchain data
- [ ] rename ``bitcoin.conf`` to ``zcash.conf`` if it was modified

**Comment by ebfull** [comment]
Addresses and some other things are now smaller, which should improve readability of the guide.

**Comment by ebfull** [comment]
I'll update this guide.

**Comment by ebfull** [comment]
Updated!
