### ISSUE TITLE
Analyze the risk of disabling IP-based blocking behavior.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#92]
We may want to disable or alter upstream features for "blocking abusive peers" based on IP, because doing so may be a way to leverage attacks against Tor users. We want Tor integration out of the box, #12.

If we are going to remove IP-based blocking, we need to thoroughly understand the attacks this would enable, so that we can determine if we can accept that risk or start to brainstorm replacement defenses that are still Tor-friendly.

**Comment by str4d** [comment]
Note that IP-like banning can be implemented for I2P (when #1111 lands), because clients and servers are functionally identical and clients have I2P Destinations. The barrier to evasion is lower of course, because clients can regenerate their Destination whenever they want, but it *is* possible.

**Comment by nathan-at-least** [comment]
str4d: That's cool, and could fit in with the current banning logic.

My larger desire is to remove all IP-based banning altogether, and re-engineer the p2p protocol so that is not necessary. That's probably a massive task and I choose to fight other more important battles.

With that in mind, I'm considering closing this ticket as wontfix.

**Comment by daira** [comment]
+1 for wontfix.

**Comment by indolering** [comment]
> If we are going to remove IP-based blocking, we need to thoroughly understand the attacks this would enable, so that we can determine if we can accept that risk or start to brainstorm replacement defenses that are still Tor-friendly.

The canonical paper on the subject suggested disabling IP blocking on some fraction of all clients.  You could whitelist Tor exit nodes or reduce the ban length from 24 hours down to, for example, 2 hours.

> My larger desire is to remove all IP-based banning altogether, and re-engineer the p2p protocol so that is not necessary. That's probably a massive task and I choose to fight other more important battles.

All nodes would need to create new public keys for each node they connect to, throttle new identities via an adjustable proof-of-work scheme, and rotate identities/connections regularly.  I think that you would also need to link identity creation to the anonymizing network's circuit.  There are probably other fingerprinting vectors that I'm not thinking of....

For now, it's probably easier to hardcode trusted Tor full nodes and make sure the client connects to at least one of them.

**Comment by daira** [comment]
Consider adopting this fix from upstream, which is advertised as helping against Eclipse attacks: https://github.com/bitcoin/bitcoin/pull/8282

**Comment by nathan-at-least** [comment]
Closing as wontfix. We may decide to add @amiller 's proposal or the patches @daira linked to as post-1.0 features.
