### ISSUE TITLE
Test that `merkle_tree_check_read_gadget` behavior with respect to `read_success` acts as expected

### ISSUE THREAD

**Issue by ebfull** [zcash/zcash#920]
Write a test that ensures the `merkle_tree_check_read_gadget` behaves properly, in particular, during witnessing there is a weird API edge case that must be examined. (See [this comment](https://github.com/zcash/zcash/issues/920#issuecomment-233811236).)

**Comment by daira** [comment]
I agree. I believe it's possible to do this in a way that makes it evident with a small amount of code review that the code paths are always enabled in production code.

**Comment by nathan-at-least** [comment]
I agree on this: we'll use a principled way to disable constraints in order to target key constraints in tests, and in a way that's easy to audit, and to easily verify cannot occur in production.

**Comment by nathan-at-least** [comment]
Is this part of #908? I put it in the same milestone on that assumption.

**Comment by nathan-at-least** [comment]
This is work we'll do before security audit.

**Comment by ebfull** [comment]
The primary reason that I wanted to write targeted internal circuit tests was to test for a weird API design issue in libsnark that I was concerned about when writing libzcash. Now that I understand the issue better, I realize we can test it with a unit test and not a mock test or a macro. (There is no bug in the code, but it is something that may confuse auditors, and so we should have a test for it.)

I will be writing a test for this, and for now I've renamed this ticket. (I've talked to both @nathan-at-least about it and I've walked @str4d through the problem; he was very helpful for me understanding this as an API issue.)

------

The `merkle_tree_check_read_gadget` ([header](https://github.com/scipr-lab/libsnark/blob/master/src/gadgetlib1/gadgets/merkle_tree/merkle_tree_check_read_gadget.hpp), [source](https://github.com/scipr-lab/libsnark/blob/master/src/gadgetlib1/gadgets/merkle_tree/merkle_tree_check_read_gadget.tcc)) is used by our circuit to evaluate a merkle tree authentication path over the note commitment of an input note. We provide a `root` parameter (the public input to our circuit, called the `anchor`) but for input notes of zero value, as per the specification, we do not enforce that the calculated root is equal to the anchor.

The `merkle_tree_check_read_gadget` uses the [`bit_vector_copy_gadget`](https://github.com/scipr-lab/libsnark/blob/master/src/gadgetlib1/gadgets/basic_gadgets.tcc#L150) to compare the anchor to the computed root conditionally. In our circuit code, that condition is `value_enforce` which must be 1 if the value of the input note is nonzero.

This gadget uses an optimization to perform the conditional equality check: the bits are packed into field elements (2 constraints for the anchor, 2 constraints for the computed root) and then compared (using `field_vector_copy_gadget`) with a constraint of the form `do_copy` * `a - b` = `0`, which forces them to be equal if `do_copy` is 1.

However, notice that this unintentionally will constrain the `target` to whatever it currently is, even if the copy is not performed, because the multipacker witnesses its current contents. In order to avoid this, we need to witness the root before running any `merkle_tree_check_read_gadget` witnessing routines, which is what we already do.

**Comment by daira** [comment]
"Whatever it currently is"?! Arggh why is this not purely functional? Please help me understand this aspect of libsnark better.

**Comment by ebfull** [comment]
During witnessing, gadgets sometimes use outside variables to inform them about how they should witness their own variables. This is fine, but if those "outside variables" have not been witnessed themselves, your witness might be wrong when those outside variables are witnessed later (changing them), which could violate the constraint system.

In bellman, I avoid this issue using witness groups; gadgets are only instructed to witness when all of their "input variables" have been witnessed already. This has the added advantage of allowing all gadgets in a group to be witnessed in parallel. :stuck_out_tongue_winking_eye:
