### ISSUE TITLE
Slack: add github notifications for zcash/zips

### ISSUE THREAD

**Issue by daira** [zcash/zcash#923]

**Comment by nathan-at-least** [comment]
Let's assign this to @str4d and remove it from the engineering meeting. Let me know if that doesn't work.

**Comment by str4d** [comment]
Assigning to @sean because all that needs to happen AFAICT is setting up zips with the same webhook as zcash (which I do not have permissions for).

**Comment by nathan-at-least** [comment]
I'll take a crack at this. @ebfull's probably working on more important stuff atm.

**Comment by str4d** [comment]
@nathan-at-least ACK. You should be able to copy all config from the zcash webhook.

**Comment by nathan-at-least** [comment]
Done. I copied all the config, and I also enabled a new event: "releases" in both repos. Should be low traffic and useful.

**Comment by daira** [comment]
Thankyou!
