### ISSUE TITLE
Disable USE_ASM in libsnark build

### ISSUE THREAD

**Issue by daira** [zcash/zcash#932]
Split from #896. ``USE_ASM`` incurs significant risk of bugs, and should only be enabled if any observed performance advantage is significant enough to justify the cost of security-reviewing all of the asm code in libsnark within the 1.0 launch schedule. The asm code appears to be only for x86-64.

**Comment by bitcartel** [comment]
It looks like USE_ASM is enabled by default in the libsnark project's makefile:

`FEATUREFLAGS = -DUSE_ASM -DMONTGOMERY_OUTPUT
`

To disable USE_ASM, one has to pass FEATUREFLAGS= to make on the command-line (tested).  I don't see this in the [dependencies file for libsnark](https://github.com/zcash/zcash/blob/zc.v0.11.2.latest/depends/packages/libsnark.mk
), so it might be worth double-checking to make sure you have the flags you want.

**Comment by ebfull** [comment]
USE_ASM might be used in some headers, as enabling it [like this](https://github.com/ebfull/zcash/pull/1/commits/046a512d4427b1e3d180270008574038166f568a) had a measurable impact on performance.

**Comment by nathan-at-least** [comment]
Good catch @bitcartel.

Let's disable ``USE_ASM`` in the depends tree and if the time-to-prove is worse than a 30% increase, then let's reconsider re-enabling it for 1.0.

@bitcartel Are you interested in submitting a PR which removes ``USE_ASM`` in the ./depends tree so that we can measure this? If you're not available @ebfull can do it.

**Comment by ebfull** [comment]
```
USE_ASM removed:

createjoinsplit: "runningtime" : 39.32725500
verifyjoinsplit: "runningtime" : 0.02733400

USE_ASM remains partially:

createjoinsplit: "runningtime" : 40.80124300
verifyjoinsplit: "runningtime" : 0.02702900

USE_ASM enabled everywhere:

createjoinsplit: "runningtime" : 31.85218700
verifyjoinsplit: "runningtime" : 0.02065400
```

Decision must take place at engineering meeting.

**Comment by daira** [comment]
Is the difference between removing USE_ASM and leaving it partially (with the latter taking slightly longer) repeatable, or due to timing variation?

**Comment by daira** [comment]
The time reduction between no USE_ASM and all USE_ASM is 19%.

**Comment by bitcartel** [comment]
Just a thought for your discussion: If USE_ASM is disabled by default, I think many miners would simply enable it in a custom build.  ~20% improvement seems too good to give up, especially as the ASM implementation comes from Scipr Lab themselves.

**Comment by daira** [comment]
USE_ASM is not relevant to mining, only to the SNARK arithmetic.

**Comment by bitcartel** [comment]
Yes, sorry, I meant to say people (in general) rather than miners.  To make things easier for enthusiasts and full node operators who seek optimal performance, perhaps libsnark could be refactored and the user given a run-time option e.g. zcashd -snarkasm.

**Comment by zookozcash** [comment]
-1

The reason we're not enabling USE_ASM is that it is our opinion, as experts who are studying and maintaining this system, that a ~20% improvement is _not_ worth the added risk of a fatal security vulnerability. If someone else is willing and capable of doing that analysis (i.e. auditing the ASM code for security vulns) or they have an informed reason to value that trade-off differently, then they can maintain their own fork.

**Comment by nathan-at-least** [comment]
We don't feel the performance gain outweighs the risk and development time for this, so we're pushing it out of 1.0 release.

**Comment by daira** [comment]
Note that it is removing the existing enabling of USE_ASM in libsnark (which does not really in any performance improvement for createjoinsplit; in fact a slight performance loss according to https://github.com/zcash/zcash/issues/932#issuecomment-228782467) that is in 1.0.

**Comment by daira** [comment]
Maybe after 1.0 we can look at which parts of the asm actually paid off (clearly not all of it does) and are sufficiently auditable to justify the risk.

**Comment by ebfull** [comment]
Done in #1044, thanks @bitcartel.
