### ISSUE TITLE
zcrawpour - report invalid UTXO inputs to user 

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#933]
Branch zc.v0.11.2.z2

1. Test faucet sent 50 ZEC to my address
2. zcash-cli listunspent showed them sitting on vout 1.
3. When using zcash-cli createrawtransaction, I accidentally set the vout to 0.
4. No error reported when using zcrawpour:
./src/zcash-cli zcrawpour "$RAWTX" '{}' "{\"$ZCADDRESS\":49.9}" 50.0 0.1
5. signrawtransaction returns error: "Operation not valid with the current stack size"

Creating a new transaction with vout set correctly to 1 resolves this problem.
Error message can lead user to increase stack size in terminal which will not resolve the issue.
Can mismatch of inputs be detected and reported when invoking zcrawpour?

**Comment by nathan-at-least** [comment]
We're deprecating the alpha-phase ``zcraw*`` RPC operations, so we won't fix bugs in them.
