### ISSUE TITLE
add buildbot builder for verifying hosted parameters

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#937]
Part of our release process is to verify the correct circuit parameters are available for download. It's a pain for the release engineer to do this. An obvious way is to move aside any local parameters, then run the `fetch-params.sh` script.

For all of these tedious verifications, it's much better to just have a link to buildbot where they can verify a box is green.

Ideally this test wouldn't need to transmit the parameters but could just report and verify their hash. Can we hook up the webserver that hosts the param files to show their sha256sum in an HTTP HEAD request or something like that?

**Comment by str4d** [comment]
@nathan-at-least is this still relevant, now that we have a single set of parameters? If so, I'll move this to infrastructure.

**Comment by nuttycom** [comment]
Obsolete.
