### ISSUE TITLE
decide what to do, if anything about the "↓price↬↓mining↬↓price" death spiral

### ISSUE THREAD

**Issue by zookoatleastauthoritycom** [zcash/zcash#95]
Is there anything that Zcash could do to make this less of a risk?

http://ideas.4brad.com/would-bitcoin-fall-cliff-if-it-dropped-100#comment-15801

I can't stop thinking about this now, so I'm coming back here, and I'm happy to read the new comments since I last looked.

So, let me sketch this out one more time to help me think:

1. (fact?) Proof-of-Work mining, because it offers no barrier to entry, drives the marginal revenue of a miner down. Miners exit when the marginal revenue < their marginal costs (which we're mostly assuming is electricity, although cooling might be a big component of marginal cost, too). Therefore, eventually the surviving miners are those which have a low marginal cost (let's think in terms of marginal cost per hash instead of per time or per unit of equipment or whatever), but even they, the survivors, also have low marginal revenue, because the way they drove their more cost-sensitive competitors out of business was to increase the system-wide difficulty, harming their own marginal revenue as well as everyone else's.

   In short: we can expect that in a mature Proof-of-Work system there are huge swathes — maybe even a large majority — of the mining power perched on the edge of marginal profitability.

2. (fact) The market price of the coin can swing up or down.

3. (fact) Brad's first observation: if the price drops below some threshold, some fraction of those marginal miners will shut down to avoid marginal costs. (This is a fact because almost all of these miners are not hobbyists/enthusiasts — they are pros with their eyes on their bottom line. For a nice video of what professional Bitcoin mining was like a year ago: https://www.youtube.com/watch?v=K8kua5B5K3I .)

4. (fact) If a substantial fraction of miners shut down, the average block confirmation time increases proportionally, until the next difficulty adjustment. E.g. a 90th percentile of 35 minutes instead of 23 minutes, if 2% of the mining capacity is exiting every day; I got these numbers from Dave Hudson's good blog post on the topic: http://hashingit.com/analysis/41-waiting-for-blocks .

5. (speculation) If the block time increases, proportionally fewer coinbases are given out to miners, and perhaps miners are currently selling all their fresh coinbases, which puts downward pressure on the price, so if they do that less then there will be a reduction in downward pressure on the price. Thanks to Dave Hudson's blog for mentioning this speculation, and also Gwern above alludes to a similar consideration when he points out that longer block times mean a slower rate of dilution of the monetary base.) I don't have an opinion on whether this would be a significant factor.

6. (fact) If the average block confirmation time increases, the time to know that a payment to you is confirmed increases proportionally. E.g. a 90th percentile for 6-confirmations of 143 minutes, instead of 93 minutes (ibid).

7. (fact) If the average block confirmation time increases, the transaction bandwidth limit could be reached, so that transactions that come with no or low fees take even longer, or stop being serviced entirely and average transaction fees go up. (According to Dave Hudson, Bitcoin typically currently has 30% of its txn capacity in use: http://hashingit.com/analysis/39-the-myth-of-the-megabyte-bitcoin-block .)

8. (speculation) Because of point 7, average transaction fees could rise enough to make mining more profitable again. I'm skeptical of this.

9. (speculation) Because of point 7, people could switch to alternatives away from Bitcoin, reducing demand for it and further depressing its price. I'm skeptical of this, too. :-)

10. (speculation) Brad's second observation: due to some combination of 3, 4, 6, and 9, if the mining power drops, this could cause a further drop in the price of the coin. I'm not sure what I think of the likelihood of this.

So, here's why this is potentially important: if 10 happens, then the combination of 3 and 10 would make a strong positive feedback loop that simultaneously crashes the price of the coin and the performance of the transaction processing system.

I think this is worth worrying about.

**Comment by zookozcash** [comment]
Interesting that the Bitcoin devs are currently thinking about this issue!

* http://lists.linuxfoundation.org/pipermail/bitcoin-dev/2016-March/012489.html
* http://lists.linuxfoundation.org/pipermail/bitcoin-dev/2016-March/012501.html
* http://lists.linuxfoundation.org/pipermail/bitcoin-dev/2016-March/012500.html
* http://lists.linuxfoundation.org/pipermail/bitcoin-dev/2016-March/012495.html

**Comment by daira** [comment]
Having read that thread, I really strongly think we should reconsider #143 (Change block reward to smooth asymptotic function).

This would interact with the founders' reward, but not in a particularly complicated way or that contradicts anything we've logically committed to &mdash; it would be straightforward to ensure that the founders still get 10% of the eventual monetary base, over a ~4-year period.

**Comment by zookozcash** [comment]
Note that the discontinuities in block reward are only one thing that could arguably trigger a "↓price↬↓mining↬↓price" spiral. Anything that changes the price of the currency could trigger the same. So regardless of whether we smooth out the discontinuities in the reward curve, we should still try to prevent the "↓mining↬↓price" leg of the spiral, which means making it so that a dropping mining power does *not* result in a worse service (e.g. long delays between blocks, and the attendant capacity problems if blocks are near capacity).

**Comment by zookozcash** [comment]
https://github.com/zcash/zcash/issues/147 might help with this problem, by reducing the impact of points 6 and 7 from https://github.com/zcash/zcash/issues/147

**Comment by zookozcash** [comment]
Okay, I think our answer to "what to do about the death spiral" is #147, at least as far as the "Zcash 1.0 (Frontier)" release goes. I can't think of anything else that we could possibly do to help with this issue, so I'm going to close it.

**Comment by zookozcash** [comment]
People worrying about the Death Spiral on Bitcoin: https://steemit.com/bitcoin/@belerophon/the-black-swan-that-could-turn-bitcoin-upside-down
