### ISSUE TITLE
zcashd core dumps may contain long-term secrets

### ISSUE THREAD

**Issue by daira** [zcash/zcash#950]
@bitcartel wrote on #69:

> Btw, I don't think there is any signal handling to catch abort(), which means bitcoind/zcashd will core dump. Security issue?

What shall we do about this? I believe core dump generation is of by default on most Linux distributions, but still we might want to either disable it explicitly, or document the risk.

**Comment by rcseacord** [comment]
Setting the value of RLIMIT_CORE to 0 prevents the process from writing any memory dump to disk, instead simply terminating the program when a fatal problem is encountered.

~~~~
#include <sys/types.h>
#include <sys/time.h>
#include <sys/resource.h>
   
void spc_limit_core(void) {
  struct rlimit rlim;
   
  rlim.rlim_cur = rlim.rlim_max = 0;
  setrlimit(RLIMIT_CORE, &rlim);
}
~~~~

**Comment by daira** [comment]
Duplicate of #494.
