### ISSUE TITLE
Add testnet upgrade checklist and Guide update to release-process.md

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#959]
We need to define what upgrading the testnet entails in our [``doc/release-process.md``](https://github.com/zcash/zcash/blob/master/doc/release-process.md).

In particular this needs to include:

* notifying community infrastructure operators about the need to upgrade (eg: http://zcashfaucet.xyz/ )
* verifying that they have upgraded, or updating our alpha guide / FAQ to point out they are out of date.

We should really automate the second bullet if possible. Maybe we can get http://zcashfaucet.xyz/ to post which version they're running in an HTTP response.

**Comment by nathan-at-least** [comment]
Hey @ageis, I've assigned this to you. Document anything you need from a release engineer to get the testnet deployed (which might just be a ping saying the git tag is in place).

**Comment by str4d** [comment]
#1474 added an initial list. If there is more to do, we should move this ticket to the appropriate milestone.

**Comment by str4d** [comment]
@nathan-at-least as the OP could you please outline what tasks remain for this issue.

**Comment by daira** [comment]
Updating the Beta Guide is a missing step.

**Comment by ageis** [comment]
@daira added.

**Comment by ageis** [comment]
Oh crap, it was already merged. Have to cut a new PR.

**Comment by daira** [comment]
Moving this to the rc1 milestone since it didn't block the beta2 release.

**Comment by daira** [comment]
... and it won't be called the Beta Guide in future.

**Comment by nathan-at-least** [comment]
@daira asserts this is done (except for future polish).
