### ISSUE TITLE
rename libzerocash to libzcash in Makefiles and source (C++ namespace)

### ISSUE THREAD

**Issue by daira** [zcash/zcash#960]
This is fairly low priority; it works fine without this change.

**Comment by daira** [comment]
Note that #961 changed the libzcash library name, but not the C++ namespace. There's also a small amount of remaining code in ``src/zerocash/utils/until.cpp``.

**Comment by ebfull** [comment]
This should be fixed by #1061.

**Comment by defuse** [comment]
Some renaming was missing, I did it in #1089.
