### ISSUE TITLE
Make SignatureHash throw exceptions instead of returning "one"

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#966]
`SignatureHash()` returns "one" (a `uint256` of value `1`) if you call `SignatureHash()` wrong. This should be an exception. The bitcoin developer guide actually [says](https://bitcoin.org/en/developer-guide#signature-hash-types) the following about at least one of the cases where "one" can be returned:

> The corresponding output must exist or the value “1” will be signed, breaking the security scheme.

**Comment by nathan-at-least** [comment]
Bleah. What does "calling it wrong" mean?

**Comment by nathan-at-least** [comment]
This is another thing in the growing category: It seems bad for quality and security, but upstream relies on it, and we don't have bandwidth to alter this before launch.

**Comment by defuse** [comment]
#1078 is a duplicate of this.
