### ISSUE TITLE
Enforce strict DER for ECDSA signatures and compressed ECDSA public keys

### ISSUE THREAD

**Issue by daira** [zcash/zcash#968]
Bitcoin started enforcing "strict" DER ECDSA signatures as a *standard* rule [in v0.8.0](https://bitcointalk.org/index.php?topic=106461.msg3932995#msg3932995). It does not enforce this or canonicity of ECDSA public keys as an acceptance rule. I propose that Zcash should enforce these as acceptance rules from the start.

**Comment by daira** [comment]
A canonical ECDSA public key is a compressed key with a 33-byte encoding.

**Comment by ebfull** [comment]
This is one of those soft fork activation rules we were planning on making default correct?

**Comment by nathan-at-least** [comment]
I have the same question as @ebfull, and in any case this sounds like a change I like.

**Comment by daira** [comment]
Yes, it is. Let's discuss it at the engineering meeting to see whether we have consensus for this to be in 1.0.

**Comment by daira** [comment]
See also the [BIP66 spec](https://github.com/bitcoin/bips/blob/master/bip-0066.mediawiki) for the precise definition of a strict ECDSA signature. See three graph linked from https://twitter.com/petertoddbtc/status/569340245130539008 for adoption of BIP66.

**Comment by daira** [comment]
This is necessary in order to remove use of OpenSSL for signature verification (as it was for Bitcoin).

**Comment by ebfull** [comment]
BIP66 (which is what this ticket is about) is enforced automatically for us (in an irreversible process) shortly after launch, so in the interest of avoiding changes to upstream, I'd like to consider this complete.

However, two other rules have Bitcoin-specific rules: BIP 16 which begins at timestamp 1333238400, and BIP 30 which has two block ID exceptions (`0x00000000000a4d0a398161ffc163c503763b1f4360639393e0e4c8e300e0caec` and `0x00000000000743f190a18c5577a3c2d2a1f610ae9601ac046a38084ccb7cd721`). I am fixing these in a separate PR.

**Comment by daira** [comment]
@ebfull Can you elaborate on "shortly after launch"?

**Comment by ebfull** [comment]
There is a rule that nodes will reject older version blocks so long as a supermajority (`IsSuperMajority`) of the last `nMajorityWindow` blocks have a newer version. And those BIPs are activated by the newer block versions.
