### ISSUE TITLE
Audit MULTICORE routines in libsnark

### ISSUE THREAD

**Issue by ebfull** [zcash/zcash#969]

**Comment by nathan-at-least** [comment]
@ebfull, @daira: does this affect "bytewise protocol" in any way, or only performance?

I assume it affects _only_ performance, and therefore I've moved it post 1.0.0 launch. Alert me soon if I've made a mistake.

**Comment by daira** [comment]
We already enabled MULTICORE. It does not affect consensus. However, we enabled it on the understanding that the OpenMP code would be audited before launch. (It's not that hard, I can probably do it if I have a solid day or two.)

**Comment by daira** [comment]
Duplicate of #1517.
