### ISSUE TITLE
Create worst-case-block-verification time tests.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#971]
Before we land #962 (which closes #765), let's add two performance tests:

Test A - measure latency/memory-usage for verifying a very large transparent (Bitcoin) transaction's signatures. I think this is a transaction with as many valid SIGHASH_ALL txin signatures as can fit in a block. Note that the test must ensure the txn is valid in the block, so for example introducing a new limit like ``MAX_BLOCK_SIGHASH`` [1] may break this test, which would need to be adjusted to fit the new limit.

~~Test B - measure latency/memory-usage for verifying a block full of JoinSplits. I don't think it matters if these are in a single txn or separate txns, although the non-JS overhead might be lower if they're in a single txn.~~

With these in place, we can track performance changes as we change limit constants or introduce new limits. (Side note: we view introducing new limits with disdain.)

My expectations are that Test A has super-linear time w/ sig count and Test B has linear size w/ sig count.

Notice: other details aside from limits may affect these measurements. For example, if we change JoinSplit verification from serial to parallel, the latency may drop.

[1] http://gavinandresen.ninja/a-guided-tour-of-the-2mb-fork

**Edit:** Let's remove the JoinSplit test from this ticket. JoinSplit verification is constant time, and highly parallelizeable, so we expect worse case verification time to scale linearly with block size.

**Comment by zookozcash** [comment]
Do me a favor and include estimation of the costs of generating that DoS-block while you're at it. ;-)

**Comment by nathan-at-least** [comment]
Oh hang on...  Test B may not be easy at all to generate, as @zookozcash alludes to, because proving is expensive.

Test A should be easy, and that's the more concerning one because of the superlinear relationship to blocksize.

For Test B:

a. we could spend a lot of computing power to generate a large test vector.
b. if proof verification is constant time regardless of if a proof is invalid or not, we can simulate this: rather than having a block full of txns, just call verify K times on noise-inputs.  (Having a real block is thorny because a validation faliure should greedily invalidate a txn which should greedily invalidate a block.)

**Comment by str4d** [comment]
Test A is now up for review.

Test B seems much harder to handle deterministically, but it should be possible (I think) if we can ensure that the wallet addresses are deterministic. That way, we can generate a large JoinSplit test vector once, and have it be valid every time.
