### ISSUE TITLE
Use Ed25519 for JoinSplit signatures.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#977]
This requires updating the specification and implementation.

Related Tickets:

- This is a much smaller scope than #715 which would replace all transaction signatures.
- This signature is over the hash computed in #808.
- https://github.com/zcash/zips/issues/51 is the specification part of this.

**Comment by nathan-at-least** [comment]
Implemented in #976.

**Comment by ebfull** [comment]
Done in #976, and I'm closing this since daira made a ticket in zips about specifying it.

**Comment by ebfull** [comment]
(https://github.com/zcash/zips/issues/51)
