### ISSUE TITLE
Specify a mitigation of the faerie gold vulnerability.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#98]
If a sender selects multiple ρ, this produces colliding sn. If a recipient receives multiple identical sn and fails to check for collisions between *any* serials they've received (regardless of whether those serial numbers are stored in the global spent set), then it is an error for the recipient to assume received coins have a *spendable* value.

**FIXME** - Verify the necessary and sufficient conditions for this vulnerability to compromise some assumption by a recipient.

**Comment by ebfull** [comment]
**Summary of the proposed fix to the circuit:**

𝜌<sub>new,i</sub> = H(sn<sub>old,i</sub> || φ)

This assumes that there are just as many inputs as outputs. If we only had one pour input (#647):

𝜌<sub>new,i</sub> = H(sn<sub>old,0</sub> || i || φ)

Duplicate serials are prohibited, so if there are zero inputs to the pour (a Protect) then sn<sub>old,i</sub> must be distinctly random for the transaction to be valid. φ is randomly sampled to prevent serials from carrying history.

**Comment by daira** [comment]
+1 for the above proposal. I had had a slightly different fix in mind:

* pourid = CRH(sn<sup>old</sup><sub>1..N<sup>old</sup>)
* ρ<sup>new</sup><sub>i</sub> = CRH(pourid || i || φ)

but the one @ebfull gives should be equally secure and requires one less hash in the circuit.

(Orthogonally, we should probably truncate ρ<sup>new</sup><sub>i</sub> to 254 bits to address #500, if we're changing how it is computed anyway.)

**Comment by daira** [comment]
A nitpick: serial numbers must be distinct *between all Pours in a valid blockchain view*, but needn't be random. (Indeed, it is perfectly possible for two submitted transactions that are independently valid to have Pours with nondistinct serial numbers, even though only one of them will get into any given blockchain view.)

**Comment by daira** [comment]
Ah, I remember another reason why I wanted pourid. Consider the argument in https://github.com/Electric-Coin-Company/zcash/issues/663#issuecomment-176687934 :
> [If h<sub>Sig</sub> depends on pourid, then] h<sub>Sig</sub> will only be the same if all input coins are the same between Pours, and in that case an attacker already knows that all a<sup>old</sup><sub>sk,i</sub> must be the same between Pours. Therefore no additional information is leaked in my solution beyond that already considered in #679.

This doesn't directly affect Faerie Gold because it is protecting against information leakage, which is a different category of attack. However, let's say two single-Pour transactions share the same coin as input 1, with different coins as input 2. Clearly they can't both get into a consistent blockchain view, but that doesn't mean they can't both be submitted. What my Faerie Gold fix does is place an additional constraint on the attacker that for any attack that involves creating coins with the same ρ, all of the input coins will be the same *across all submitted transactions*. Although I don't know of any specific attack that this would prevent, it seems sensible to deny the attacker degrees of freedom when it can be done without any extra cost, as in this case.

**Comment by ebfull** [comment]
@daira Thanks for the insight! That makes sense. What kind of truncation should we do to avoid that additional CRH?

**Comment by daira** [comment]
There's a way to avoid the extra input (and the extra hash outside the circuit), by taking advantage of the fact that hSig is already an input. It's a little bit hacky and I suspect that this doesn't have much of an effect on performance:

* hSig = trunc<sub>253</sub>(CRH(pk<sub>Sig</sub> || sn<sup>old</sup><sub>1..N<sup>old</sup></sub>))
* ρ<sup>new</sup><sub>i</sub> = trunc<sub>254</sub>(CRH(φ || 11 || i || hSig))

This includes fixes to #663 and #500.

**Comment by ebfull** [comment]
+1 on this proposed change.

**Comment by daira** [comment]
I'm leaning toward the approach in my last comment now even though I said it was a little bit hacky. Avoiding the extra pourid variable makes for a slightly simpler specification that fits in my head better. I'm going to rename φ to q though. (That will make a coin tuple (addr<sub>pk</sub>, v, q, r).)

**Comment by daira** [comment]
Note that with q (or equivalently φ, i, and hSig) stored in a coin tuple, we might be concerned that you can tell just from the coin tuple (without having a<sub>sk</sub>) which Pour created the coin. However, you could tell that anyway for the original Zerocash protocol, by when the corresponding coin commitment was added to the commitment tree.

**Comment by daira** [comment]
See [https://github.com/Electric-Coin-Company/zips/compare/f36e7a3e064daccc37f47e6d47a576a1f2a02228%5E...98.fix-faerie-gold.1] for proposed changes.

**Comment by nathan-at-least** [comment]
Renamed this ticket to be solely about specification so it can be closed when the spec lands which addressed the issue.

**Comment by daira** [comment]
Fixed.
