### ISSUE TITLE
port conflict?

### ISSUE THREAD

**Issue by jl777** [zcash/zcash#990]
It seems the existing bitcoin ports are being used by default.
hopefully there are plans to change this to make running zcashd alongside bitcoind easier

**Comment by daira** [comment]
Yes, we should change the port numbers.

**Comment by jl777** [comment]
also alert pubkey and maybe network magic for mainnet. i assumed you just didnt get around to changing all the chain params

**Comment by daira** [comment]
Network magic is already changed. Alert key pairs are #424.
