### ISSUE TITLE
miner in C?

### ISSUE THREAD

**Issue by jl777** [zcash/zcash#992]
The current miner is in C++ and quite inefficient from what I can tell. I know there are plans for a more efficient miner. Will it be in C? If so, I can add it much easier into iguana

**Comment by str4d** [comment]
The miner in the latest release (.z4) is much more efficient in memory use, and the next release will include speed increases I am currently working on (see #988).

> Will it be in C?

The miner is written in C++11, and the optimisations are being made in place, so no.

**Comment by jl777** [comment]
If there is some clear definition of the mining algo, I can see if I can make a C based miner. please dont say the code is the documentation, I am easily confused by C++ things

**Comment by ebfull** [comment]
> please dont say the code is the documentation

I think you're right at home here.

**Comment by daira** [comment]
There will be a clear definition of the mining algorithm in the spec, but it's not written yet. That won't include optimizations though, since they don't belong in the spec. We might write some separate technical docs on Equihash optimisation but that's not an immediate priority.

**Comment by jl777** [comment]
i just need the clear definition of the mining algo, as inefficient and easy to understand as possible. perfectly fine for the code to document the optimizations, but need a clear definition of exactly what is needed to mine a block

Thanks! you guys are doing great work

**Comment by daira** [comment]
The spec ticket is https://github.com/zcash/zips/issues/40 . We're unlikely to implement a miner in C ourselves, so can this ticket be closed? (Others are of course free to transliterate the C++ code into C or other languages respecting the [MIT licence](https://github.com/zcash/zcash/blob/zc.v0.11.2.latest/COPYING), or reimplement it.)

**Comment by str4d** [comment]
This is now being considered as a result of discussions in #857.

**Comment by solardiz** [comment]
Thanks for reopening this @str4d. I think we need to decide whether to start with a simpler C implementation such as based on your Python one https://github.com/str4d/zcash-pow and then to optimize it with separate commits, or to port over the current C++ code which already has some optimizations in it (but not necessarily the ones I'd be making in the C code first). We could also try both approaches.

**Comment by str4d** [comment]
I wrote the Python implementation first as a means of understanding the Equihash algorithm. `Equihash::BasicSolve()` in our C++ code basically followed the approach you outline (see the commit history) - I ported over the Python implementation and then proceeded to optimise for memory (a necessary step because the basic implementation in Python is very memory-heavy, and even after porting to C++ used >10x the theoretical peak memory IIRC).

**Comment by daira** [comment]
The current C++ implementation is well-written, well-reviewed, solidly engineered code that several of us understand in depth. Also the memory optimizations it makes are absolutely necessary. We should transliterate it directly, rather than losing time reimplementing.

**Comment by nathan-at-least** [comment]
If we already have a goal of producing an open-source GPU implementation, then having a second CPU-oriented implementation seems like a lower priority. If a C-based CPU-oriented implementation is a stepping stone to or side-effect of the GPU implementation, that's a bonus.

So our primary requirements:

* open source GPU implementation
* working CPU reference implementation

A C-oriented CPU reference implementation is a "nice-to-have" and I'm all for creating one after launch or supporting community volunteers who wish to create one.

**Comment by sammy007** [comment]
I'll try to rise my concerns here while it's not too late.

Even ethereum launched with GPU miner of acceptable quality even if it's obvious that they don't care about PoW phase at all.

Launching PoW currency without any acceptable GPU mining solution like an sgminer fork is a disaster. Well, there is no even cpu miner (minerd fork). I see some standalone miners available but actually there is no even stratum documented. Yet another fragmentation. Awesome that @tromp published his work, but actually it's just a code, not a working solution for "end-users".

Also, every shitcoin on bitcointalk launching with windows builds. ZCash is better, right? My prediction on launch is simple: ZCash will be raped by private mining farms and cloud mining scam services. Then all these instamined coins (even if you have a "slow" launch) will be dumped hard on "innocent" ignorants. You are trying to be ASIC-resistant but having a bunch of private farms with miners faster by orders of magnitude is almost equal to be not-ASIC resistant.

Must admit that ethereum with all their PoW ignore organized perfect launch. You are leading to disaster instead.  Please reconsider providing a mining solution of acceptable quality and windows builds before it's not too late.

Thanks.

**Comment by str4d** [comment]
> I see some standalone miners available but actually there is no even stratum documented.

Incorrect; see the draft Stratum ZIP I wrote: https://github.com/zcash/zips/pull/78

**Comment by nicehashdev** [comment]
I completely disagree with you sammy007.

So far, zcash devs did good job. Stratum specs are online for long time already, so we were able to adjust our systems. And it is clearly visible that professionals put together specs. I cannot say the same for ethereum (miners doing same work etc).

Miners are coming out too. Not everything is glancy and fancy for end users, true. But that is where we come into the play - we are already polishing standalone CPU miner that does 10-15 S/s on modern CPU. We plan to do the same for GPU mining. And this all will be ready before the official launch. We (NiceHash) can guarantee that everyone will have fair chances at launch. We will take care of that.

**Comment by sammy007** [comment]
@nicehashdev omg of course, you have thousands commercial reasons to disagree.

**Comment by daira** [comment]
There are now plenty of third-party miner implementations, for CPU and GPU, so this can be closed.
