### ISSUE TITLE
error: {"code":-8

### ISSUE THREAD

**Issue by chip99** [zcash/zcash#995]
getting this error when doing the protecting your testcoins procedure.

error: {"code":-8,"message":"to_address must be hexadecimal string (not '')"}

**Comment by chip99** [comment]
./src/zcash-cli zcrawpour "$RAWTX"'{ }' "{\"$ZCADDRESS\":40}" 40 0
error: {"code":-1,"message":"zcrawpour rawtx inputs outputs vpub_old vpub_new\n  inputs: a JSON object mapping {bucket: zcsecretkey, ...}\n  outputs: a JSON object mapping {zcaddr: value, ...}\n\nSplices a Pour into rawtx. Inputs are unilaterally confidential.\nOutputs are confidential between sender/receiver. The vpub_old and\nvpub_new values are globally public and move transparent value into\nor out of the confidential value store, respectively.\n\nNote: The caller is responsible for delivering the output enc1 and\nenc2 to the appropriate recipients, as well as signing rawtxout and\nensuring it is mined. (A future RPC call will deliver the confidential\npayments in-band on the blockchain.)\n\nOutput: {\n  \"encryptedbucket1\": enc1,\n  \"encryptedbucket2\": enc2,\n  \"rawtxn\": rawtxout\n}\n"}

**Comment by ebfull** [comment]
We can help you with issues like this on our slack: https://inviteme.z.cash/

Your command line looks a little wonky, try

``./src/zcash-cli zcrawpour "$RAWTX" '{}' "{\"$ZCADDRESS\":39.9}" 39.9 0``
