### ISSUE TITLE
Testing Error Ubuntu 14.04

### ISSUE THREAD

**Issue by Chicodemilo** [zcash/zcash#996]
I'm reporting because the test told me to.

Hope this make sense to you:

============================================================================
See src/test-suite.log
Please report to https://github.com/zcash/zcash/issues
============================================================================
make[4]: *** [test-suite.log] Error 1
make[4]: Leaving directory `/home/parallels/zcash/src'
make[3]: *** [check-TESTS] Error 2
make[3]: Leaving directory `/home/parallels/zcash/src'
make[2]: *** [check-am] Error 2
make[2]: Leaving directory `/home/parallels/zcash/src'
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory `/home/parallels/zcash/src'
make: *** [check-recursive] Error 1
=== ./src/test-suite.log ===
=============================================================
   Zcash 0.11.2.z_CLIENT_VERSION_ZCASH: src/test-suite.log
=============================================================

# TOTAL: 2
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test/test_bitcoin
=======================

Running 168 test cases...
unknown location(0): fatal error in "test_basic_pour_verification": std::bad_alloc: std::bad_alloc
test/transaction_tests.cpp(253): last checkpoint
test/transaction_tests.cpp(484): error in "test_simple_pour_invalidity": check state.GetRejectReason() == "bad-pours-serials-duplicate" failed

*** 2 failures detected in test suite "Bitcoin Test Suite"

FAIL: zcash-gtest
=================

[==========] Running 21 tests from 6 test cases.
[----------] Global test environment set-up.
[----------] 1 test from tautologies
[ RUN      ] tautologies.seven_eq_seven
[       OK ] tautologies.seven_eq_seven (0 ms)
[----------] 1 test from tautologies (0 ms total)

[----------] 1 test from checktransaction_tests
[ RUN      ] checktransaction_tests.check_vpub_not_both_nonzero
[       OK ] checktransaction_tests.check_vpub_not_both_nonzero (8 ms)
[----------] 1 test from checktransaction_tests (8 ms total)

[----------] 3 tests from joinsplit
[ RUN      ] joinsplit.h_sig
[       OK ] joinsplit.h_sig (18 ms)
[ RUN      ] joinsplit.full_api_test
unknown file: Failure
C++ exception with description "std::bad_alloc" thrown in the test body.
[  FAILED  ] joinsplit.full_api_test (131549 ms)
[ RUN      ] joinsplit.note_plaintexts
[       OK ] joinsplit.note_plaintexts (23 ms)
[----------] 3 tests from joinsplit (131591 ms total)

[----------] 6 tests from noteencryption
[ RUN      ] noteencryption.api
[       OK ] noteencryption.api (183 ms)
[ RUN      ] noteencryption.prf_addr
[       OK ] noteencryption.prf_addr (1 ms)
[ RUN      ] noteencryption.prf_nf
[       OK ] noteencryption.prf_nf (1 ms)
[ RUN      ] noteencryption.prf_pk
[       OK ] noteencryption.prf_pk (1 ms)
[ RUN      ] noteencryption.prf_rho
[       OK ] noteencryption.prf_rho (2 ms)
[ RUN      ] noteencryption.uint252
[       OK ] noteencryption.uint252 (0 ms)
[----------] 6 tests from noteencryption (188 ms total)

[----------] 8 tests from merkletree
[ RUN      ] merkletree.vectors
[       OK ] merkletree.vectors (66484 ms)
[ RUN      ] merkletree.emptyroots
[       OK ] merkletree.emptyroots (0 ms)
[ RUN      ] merkletree.emptyroot
[       OK ] merkletree.emptyroot (1 ms)
[ RUN      ] merkletree.deserializeInvalid
[       OK ] merkletree.deserializeInvalid (0 ms)
[ RUN      ] merkletree.deserializeInvalid2
[       OK ] merkletree.deserializeInvalid2 (0 ms)
[ RUN      ] merkletree.deserializeInvalid3
[       OK ] merkletree.deserializeInvalid3 (0 ms)
[ RUN      ] merkletree.deserializeInvalid4
[       OK ] merkletree.deserializeInvalid4 (0 ms)
[ RUN      ] merkletree.testZeroElements
[       OK ] merkletree.testZeroElements (1 ms)
[----------] 8 tests from merkletree (66487 ms total)

[----------] 2 tests from circuit
[ RUN      ] circuit.values
[       OK ] circuit.values (60 ms)
[ RUN      ] circuit.endianness
[       OK ] circuit.endianness (0 ms)
[----------] 2 tests from circuit (60 ms total)

[----------] Global test environment tear-down
[==========] 21 tests from 6 test cases ran. (198335 ms total)
[  PASSED  ] 20 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] joinsplit.full_api_test

 1 FAILED TEST

===== FAILED: make check || { echo === ./src/test-suite.log === ; cat ./src/test-suite.log ; false ; }

**Comment by ebfull** [comment]
I think this is because you don't have enough resources (memory) to run the test.
